// 1 Kings 5 — quiz bank (RSV). Every row is anchored to a verse; fill-in-the-blank
// rows are verified against the stored verse text by scripts/seed-quiz-bank.ts.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: '1 Kings',
  chapter: 5,
  tag: 'quiz-v2-1kings-5',
  rows: [
    // ══════════════════════════════════ v1–2 · Hiram sends to Solomon
    mc(1, 'Hiram was king of which city?', ['Tyre', 'Sidon', 'Gebal', 'Damascus'], 1),
    word(1, 'Who was the king of Tyre who sent servants to Solomon?', 'Hiram', 1),
    blank(1, 'Now Hiram king of _____ sent his servants to Solomon, when he heard that they had anointed him king in place of his father; for Hiram always loved David.', 'Tyre', 1),
    tf(1, 'Hiram always loved David.', true, 1),
    mc(2, 'Why did Hiram send his servants to Solomon?', ['He heard they had anointed Solomon king in place of his father', 'Solomon had asked him for timber', 'To collect tribute from Israel', 'To settle a border dispute'], 1),
    blank(2, 'Now Hiram king of Tyre sent his servants to Solomon, when he heard that they had _____ him king in place of his father; for Hiram always loved David.', 'anointed', 1),
    tf(2, 'Solomon was the first to send servants, sending them to Hiram king of Tyre.', false, 1, 'Hiram sent his servants to Solomon when he heard Solomon had been anointed king.'),
    word(3, 'The verse says Hiram "always ___ David."', 'loved', 1),
    blank(3, 'Now Hiram king of Tyre sent his servants to Solomon, when he heard that they had anointed him king in place of his _____; for Hiram always loved David.', 'father', 1),

    blank(1, 'And Solomon sent word to _____,', 'Hiram', 2),
    tf(1, 'Solomon sent word to Hiram.', true, 2),
    mc(2, 'After Hiram’s servants came, what did Solomon do?', ['He sent word to Hiram', 'He went to Tyre himself', 'He sent gold to Hiram', 'He sent the servants away'], 2),
    word(2, 'Solomon "sent ___ to Hiram" — what did he send?', 'word', 2, ['a message', 'message']),

    // ══════════════════════════════════ v3–6 · Solomon’s message
    mc(1, 'According to Solomon, why could David not build a house for the name of the LORD?', ['Because of the warfare with which his enemies surrounded him', 'Because he lacked cedar timber', 'Because he was too old', 'Because the priests opposed it'], 3),
    blank(1, 'You know that David my father could not build a house for the name of the LORD his God because of the _____ with which his enemies surrounded him, until the LORD put them under the soles of his feet.', 'warfare', 3),
    word(2, 'Solomon said the LORD put David’s enemies under the soles of his what?', 'feet', 3),
    tf(1, 'Solomon said his father David had built a house for the name of the LORD.', false, 3, 'David "could not build a house for the name of the LORD his God because of the warfare".'),
    blank(3, 'You know that David my father could not build a house for the name of the LORD his God because of the warfare with which his enemies surrounded him, until the LORD put them under the _____ of his feet.', 'soles', 3),
    mc(3, 'Solomon said David’s enemies were finally subdued when the LORD did what?', ['Put them under the soles of his feet', 'Scattered them to the mountains', 'Drove them into the sea', 'Made them pay tribute'], 3),
    tf(2, 'Solomon said David could not build the house because of the warfare with which his enemies surrounded him.', true, 3),

    blank(1, 'But now the LORD my God has given me _____ on every side; there is neither adversary nor misfortune.', 'rest', 4),
    mc(1, 'What did Solomon say the LORD his God had given him?', ['Rest on every side', 'Victory over Tyre', 'Great riches', 'A long life'], 4),
    word(2, 'Solomon said there was "neither adversary nor ___".', 'misfortune', 4),
    tf(2, 'Solomon said there was neither adversary nor misfortune.', true, 4),
    blank(3, 'But now the LORD my God has given me rest on every side; there is neither _____ nor misfortune.', 'adversary', 4),
    tf(3, 'Solomon said the LORD had given him rest on every side but one.', false, 4, 'He said "rest on every side; there is neither adversary nor misfortune".'),
    mc(3, 'Complete Solomon’s words: "there is neither adversary nor ___".', ['misfortune', 'enemy', 'famine', 'plague'], 4),

    mc(1, 'What did Solomon purpose to build?', ['A house for the name of the LORD his God', 'A palace for himself', 'A fleet of ships', 'A wall around Jerusalem'], 5),
    blank(1, 'And so I purpose to build a _____ for the name of the LORD my God, as the LORD said to David my father, `Your son, whom I will set upon your throne in your place, shall build the house for my name.\'', 'house', 5),
    word(1, 'Solomon purposed to build a house for the ___ of the LORD his God.', 'name', 5),
    mc(2, 'According to Solomon, who had the LORD said would build the house for his name?', ['David’s son, whom the LORD would set upon David’s throne', 'David himself', 'Hiram king of Tyre', 'The priests of Israel'], 5),
    tf(2, 'Solomon said the LORD had told David that David’s son would build the house for the LORD’s name.', true, 5),
    blank(2, 'as the LORD said to David my father, `Your son, whom I will set upon your _____ in your place, shall build the house for my name.\'', 'throne', 5),
    tf(3, 'Solomon quoted the LORD as saying to David, "You shall build the house for my name."', false, 5, 'The LORD said, "Your son … shall build the house for my name."'),
    word(3, 'The LORD told David, "Your son, whom I will set upon your throne in your ___".', 'place', 5),

    mc(1, 'What did Solomon ask Hiram to command be cut for him?', ['Cedars of Lebanon', 'Oaks of Bashan', 'Cypress of Tyre', 'Stones of Gebal'], 6),
    word(1, 'Solomon asked for cedars from which region?', 'Lebanon', 6),
    blank(1, 'Now therefore command that _____ of Lebanon be cut for me; and my servants will join your servants, and I will pay you for your servants such wages as you set;', 'cedars', 6),
    mc(2, 'Who, according to Solomon, were unmatched at cutting timber?', ['The Sidonians', 'The Israelites', 'The men of Gebal', 'The Egyptians'], 6),
    word(2, 'Solomon said no one among his people could cut timber like which people?', 'Sido’nians', 6, ['sidonians', 'sidonian', 'sidon']),
    blank(2, 'for you know that there is no one among us who knows how to cut timber like the _____."', 'Sido’nians', 6, ['sidonians']),
    tf(3, 'Solomon offered to pay Hiram’s servants whatever wages Hiram set.', true, 6),
    tf(3, 'Solomon said the Israelites were the most skilled at cutting timber.', false, 6, 'He said "there is no one among us who knows how to cut timber like the Sidonians".'),
    blank(3, 'and my servants will join your servants, and I will pay you for your servants such _____ as you set;', 'wages', 6),
    mc(3, 'What did Solomon propose about the workforce for cutting the cedars?', ['His servants would join Hiram’s servants', 'Only Hiram’s servants would cut the timber', 'Only Israelites would do the cutting', 'Sidonians would be hired from Egypt'], 6),

    // ══════════════════════════════════ v7–9 · Hiram’s reply
    mc(1, 'How did Hiram react when he heard Solomon’s words?', ['He rejoiced greatly', 'He was angry', 'He demanded more payment', 'He refused the request'], 7),
    blank(1, 'When Hiram heard the words of Solomon, he _____ greatly, and said, "Blessed be the LORD this day, who has given to David a wise son to be over this great people."', 'rejoiced', 7),
    word(1, 'Hiram called Solomon a ___ son given to David.', 'wise', 7),
    mc(2, 'What did Hiram say when he rejoiced?', ['"Blessed be the LORD this day, who has given to David a wise son to be over this great people"', '"Long live King Solomon"', '"May the gods of Tyre bless you"', '"Now Israel and Tyre are one"'], 7),
    tf(2, 'Hiram blessed the LORD for giving David a wise son.', true, 7),
    blank(2, 'Blessed be the LORD this day, who has given to David a _____ son to be over this great people.', 'wise', 7),
    tf(3, 'Hiram said the LORD had given David a wise son to be over "this small nation".', false, 7, 'He said "over this great people".'),
    word(3, 'Hiram said Solomon was to be over "this great ___".', 'people', 7),

    mc(1, 'Which two kinds of timber did Hiram say he was ready to supply?', ['Cedar and cypress', 'Oak and pine', 'Cedar and olive', 'Fir and acacia'], 8),
    word(1, 'Besides cedar, what other timber did Hiram mention?', 'cypress', 8),
    blank(1, 'I am ready to do all you desire in the matter of cedar and _____ timber.', 'cypress', 8),
    tf(1, 'Hiram said he was ready to do all Solomon desired in the matter of cedar and cypress timber.', true, 8),
    blank(2, 'And Hiram sent to Solomon, saying, "I have heard the _____ which you have sent to me; I am ready to do all you desire in the matter of cedar and cypress timber.', 'message', 8),
    tf(2, 'Hiram agreed to supply cedar but refused to supply cypress.', false, 8, 'He was ready to do all Solomon desired "in the matter of cedar and cypress timber".'),
    mc(3, 'How did Hiram begin his reply to Solomon?', ['"I have heard the message which you have sent to me"', '"Blessed be the LORD this day"', '"My servants shall bring it down to the sea"', '"You shall meet my wishes"'], 8),

    mc(1, 'How did Hiram plan to transport the timber?', ['Make it into rafts to go by sea', 'Carry it on camels through the desert', 'Float it down the Jordan River', 'Haul it on ox carts over the mountains'], 9),
    word(1, 'Hiram said he would make the timber into what to go by sea?', 'rafts', 9, ['raft']),
    blank(1, 'My servants shall bring it down to the _____ from Lebanon;', 'sea', 9),
    mc(2, 'What did Hiram ask Solomon for in return for the timber?', ['Food for his household', 'Gold and silver', 'Horses and chariots', 'Twenty cities in Galilee'], 9),
    word(2, 'Hiram wanted Solomon to provide ___ for his household.', 'food', 9),
    tf(2, 'Hiram asked Solomon to pay for the timber in gold.', false, 9, 'He asked Solomon to "meet my wishes by providing food for my household".'),
    blank(2, 'and I will make it into _____ to go by sea to the place you direct, and I will have them broken up there, and you shall receive it;', 'rafts', 9),
    tf(3, 'Hiram said the rafts would be broken up at the place Solomon directed.', true, 9),
    blank(3, 'and you shall meet my wishes by providing food for my _____."', 'household', 9),
    mc(3, 'Who would decide where the rafts of timber were to go?', ['Solomon — "to the place you direct"', 'Hiram’s sea captains', 'The Sidonians', 'Adoniram'], 9),
    word(3, 'Hiram said, "I will have them ___ up there" — what would be done to the rafts?', 'broken', 9, ['broken up']),
    tf(3, 'Hiram said his servants would bring the timber down to the sea from Lebanon.', true, 9),

    // ══════════════════════════════════ v10–12 · The exchange and treaty
    blank(1, 'So Hiram supplied Solomon with all the timber of cedar and _____ that he desired,', 'cypress', 10),
    tf(1, 'Hiram supplied Solomon with all the cedar and cypress timber that he desired.', true, 10),
    mc(2, 'How much of the timber Solomon desired did Hiram supply?', ['All of it', 'Half of it', 'Only the cedar', 'Only what the rafts could carry in one year'], 10),
    word(2, 'Who supplied Solomon with all the timber of cedar and cypress?', 'Hiram', 10),
    tf(3, 'Hiram supplied Solomon with the cedar timber he desired, but not cypress.', false, 10, 'He supplied "all the timber of cedar and cypress that he desired".'),

    mc(1, 'What did Solomon give Hiram as food for his household?', ['Twenty thousand cors of wheat', 'Twenty thousand sheep', 'A thousand oxen', 'Ten thousand measures of barley'], 11),
    word(1, 'What grain did Solomon give Hiram?', 'wheat', 11),
    blank(1, 'while Solomon gave Hiram twenty thousand cors of _____ as food for his household, and twenty thousand cors of beaten oil.', 'wheat', 11),
    mc(2, 'How often did Solomon give Hiram the wheat and oil?', ['Year by year', 'Once only', 'Month by month', 'Every seven years'], 11),
    tf(2, 'Solomon gave Hiram wheat and beaten oil year by year.', true, 11),
    word(2, 'How many cors of wheat did Solomon give Hiram?', 'twenty thousand', 11, ['20000', '20,000', '20 thousand']),
    blank(2, 'Solomon gave this to Hiram year by _____.', 'year', 11),
    mc(3, 'What kind of oil did Solomon give Hiram?', ['Beaten oil', 'Anointing oil', 'Perfumed oil', 'Oil pressed in Lebanon'], 11),
    blank(3, 'while Solomon gave Hiram twenty thousand cors of wheat as food for his household, and twenty thousand cors of _____ oil.', 'beaten', 11),
    tf(3, 'Solomon gave Hiram ten thousand cors of beaten oil.', false, 11, 'He gave "twenty thousand cors of beaten oil".'),
    word(3, 'What unit of measure is used for the wheat and oil Solomon gave Hiram?', 'cors', 11, ['cor']),

    mc(1, 'What did the LORD give Solomon, as he had promised?', ['Wisdom', 'Riches', 'Long life', 'Victory'], 12),
    blank(1, 'And the LORD gave Solomon _____, as he promised him; and there was peace between Hiram and Solomon; and the two of them made a treaty.', 'wisdom', 12),
    word(2, 'What did Hiram and Solomon make together?', 'treaty', 12, ['a treaty']),
    tf(1, 'There was peace between Hiram and Solomon.', true, 12),
    mc(2, 'What was the relationship between Hiram and Solomon?', ['There was peace between them and they made a treaty', 'They were at war', 'Hiram paid tribute to Solomon', 'Solomon was Hiram’s vassal'], 12),
    blank(2, 'and there was _____ between Hiram and Solomon; and the two of them made a treaty.', 'peace', 12),
    tf(3, 'The verse says the LORD gave Solomon wisdom "as he promised him".', true, 12),
    word(3, 'The LORD gave Solomon wisdom "as he ___ him".', 'promised', 12),
    blank(3, 'And the LORD gave Solomon wisdom, as he _____ him;', 'promised', 12),

    // ══════════════════════════════════ v13–16 · The labor force
    mc(1, 'How many men were in Solomon’s levy of forced labor?', ['Thirty thousand', 'Ten thousand', 'Seventy thousand', 'Eighty thousand'], 13),
    word(1, 'How many men numbered in the levy Solomon raised out of all Israel?', 'thirty thousand', 13, ['30000', '30,000', '30 thousand']),
    blank(1, 'King Solomon raised a levy of forced labor out of all Israel; and the levy numbered _____ thousand men.', 'thirty', 13, ['30']),
    tf(1, 'Solomon raised a levy of forced labor out of all Israel.', true, 13),
    blank(2, 'King Solomon raised a levy of forced _____ out of all Israel; and the levy numbered thirty thousand men.', 'labor', 13, ['labour']),
    tf(2, 'Solomon raised his levy of forced labor only from the tribe of Judah.', false, 13, 'The levy was raised "out of all Israel".'),
    mc(3, 'From where did Solomon raise the levy of forced labor?', ['Out of all Israel', 'Out of Tyre and Sidon', 'From the men of Gebal', 'From the hill country only'], 13),

    mc(1, 'Who was in charge of the levy?', ['Adoniram', 'Hiram', 'Benaiah', 'Zadok'], 14),
    word(1, 'Who was in charge of Solomon’s levy of forced labor?', 'Adoni’ram', 14, ['adoniram']),
    blank(1, '_____ was in charge of the levy.', 'Adoni’ram', 14, ['adoniram']),
    mc(2, 'How many men of the levy were sent to Lebanon each month?', ['Ten thousand', 'Thirty thousand', 'Three thousand three hundred', 'Twenty thousand'], 14),
    word(2, 'How many men went to Lebanon a month in relays?', 'ten thousand', 14, ['10000', '10,000', '10 thousand']),
    blank(2, 'And he sent them to Lebanon, _____ thousand a month in relays;', 'ten', 14, ['10']),
    mc(3, 'What was the rotation for the men of the levy?', ['A month in Lebanon and two months at home', 'Two months in Lebanon and a month at home', 'Six months in Lebanon and six months at home', 'A year in Lebanon and a year at home'], 14),
    tf(2, 'The men of the levy spent a month in Lebanon and two months at home.', true, 14),
    tf(3, 'The men of the levy spent two months in Lebanon and one month at home.', false, 14, 'They would be "a month in Lebanon and two months at home".'),
    blank(3, 'they would be a month in Lebanon and two months at _____;', 'home', 14),
    word(3, 'The ten thousand a month were sent to Lebanon "in ___".', 'relays', 14),

    mc(1, 'How many burden-bearers did Solomon have?', ['Seventy thousand', 'Eighty thousand', 'Thirty thousand', 'Ten thousand'], 15),
    word(1, 'How many hewers of stone did Solomon have in the hill country?', 'eighty thousand', 15, ['80000', '80,000', '80 thousand']),
    blank(1, 'Solomon also had _____ thousand burden-bearers and eighty thousand hewers of stone in the hill country,', 'seventy', 15, ['70']),
    mc(2, 'Where were Solomon’s eighty thousand hewers of stone?', ['In the hill country', 'In Lebanon', 'By the sea', 'In Tyre'], 15),
    blank(2, 'Solomon also had seventy thousand burden-bearers and eighty thousand hewers of _____ in the hill country,', 'stone', 15),
    tf(2, 'Solomon had eighty thousand burden-bearers and seventy thousand hewers of stone.', false, 15, 'It was seventy thousand burden-bearers and eighty thousand hewers of stone.'),
    tf(3, 'The hewers of stone worked in the hill country.', true, 15),
    word(3, 'Solomon’s seventy thousand workers were "___-bearers".', 'burden', 15, ['burden-bearers', 'burden bearers']),
    blank(3, 'Solomon also had seventy thousand burden-bearers and eighty thousand hewers of stone in the _____ country,', 'hill', 15),

    mc(1, 'How many chief officers did Solomon have over the work?', ['Three thousand three hundred', 'Three thousand', 'Thirty thousand', 'Three hundred'], 16),
    word(1, 'How many chief officers were over the work?', 'three thousand three hundred', 16, ['3300', '3,300']),
    blank(1, 'besides Solomon\'s three thousand three hundred chief _____ who were over the work, who had charge of the people who carried on the work.', 'officers', 16),
    tf(2, 'Solomon had three thousand three hundred chief officers over the work.', true, 16),
    blank(2, 'besides Solomon\'s three thousand three _____ chief officers who were over the work,', 'hundred', 16),
    tf(3, 'Solomon had three thousand six hundred chief officers over the work.', false, 16, 'The RSV says "three thousand three hundred chief officers".'),
    mc(3, 'What did the chief officers do?', ['They had charge of the people who carried on the work', 'They cut the cedars in Lebanon', 'They sailed the rafts', 'They collected the wheat for Hiram'], 16),
    blank(3, 'who had charge of the people who carried on the _____.', 'work', 16),

    // ══════════════════════════════════ v17–18 · Stones and builders
    mc(1, 'What was quarried at the king’s command?', ['Great, costly stones', 'Cedar logs', 'Gold ore', 'Marble pillars'], 17),
    word(1, 'The great, costly stones were quarried to lay the ___ of the house.', 'foundation', 17),
    blank(1, 'At the king\'s command, they quarried out great, costly stones in order to lay the _____ of the house with dressed stones.', 'foundation', 17),
    tf(2, 'The stones were quarried at the king’s command.', true, 17),
    blank(2, 'At the king\'s command, they quarried out great, _____ stones in order to lay the foundation of the house with dressed stones.', 'costly', 17),
    mc(2, 'The foundation of the house was laid with what kind of stones?', ['Dressed stones', 'Rough field stones', 'Bricks of clay', 'Stones from the sea'], 17),
    tf(2, 'The foundation of the house was laid with rough, uncut stones.', false, 17, 'It was laid "with dressed stones".'),
    word(3, 'The foundation was laid with "___ stones" — what word describes them?', 'dressed', 17),
    blank(3, 'At the king\'s command, they _____ out great, costly stones in order to lay the foundation of the house with dressed stones.', 'quarried', 17),

    mc(1, 'Along with Solomon’s and Hiram’s builders, who did the hewing?', ['The men of Gebal', 'The men of Sidon', 'The men of Tyre', 'The Levites'], 18),
    word(1, 'The men of which place worked alongside Solomon’s and Hiram’s builders?', 'Gebal', 18),
    blank(1, 'So Solomon\'s builders and Hiram\'s builders and the men of _____ did the hewing and prepared the timber and the stone to build the house.', 'Gebal', 18),
    tf(2, 'Solomon’s builders and Hiram’s builders worked together on the house.', true, 18),
    mc(2, 'What did the builders prepare to build the house?', ['The timber and the stone', 'Gold and silver', 'Bronze and iron', 'Linen and dyed wool'], 18),
    blank(2, 'So Solomon\'s builders and Hiram\'s builders and the men of Gebal did the _____ and prepared the timber and the stone to build the house.', 'hewing', 18),
    tf(3, 'Only Solomon’s builders prepared the timber and the stone for the house.', false, 18, 'Solomon’s builders, Hiram’s builders, and the men of Gebal all did the work.'),
    word(3, 'The builders "did the ___" and prepared the timber and the stone.', 'hewing', 18),

    // ══════════════════════════════════ Whole-chapter
    mc(2, 'Which happened FIRST in 1 Kings 5?', ['Hiram sent his servants to Solomon', 'Solomon raised a levy of thirty thousand men', 'Hiram and Solomon made a treaty', 'Great stones were quarried for the foundation'], 1),
    mc(3, 'Who said, "Blessed be the LORD this day, who has given to David a wise son"?', ['Hiram', 'Solomon', 'Adoniram', 'David'], 7),
    mc(2, 'Who said, "there is no one among us who knows how to cut timber like the Sidonians"?', ['Solomon', 'Hiram', 'Adoniram', 'The men of Gebal'], 6),
    tf(2, 'In 1 Kings 5, Solomon gave Hiram timber and Hiram gave Solomon wheat.', false, 11, 'It was the reverse: Hiram supplied timber and Solomon gave wheat and oil.'),
    mc(3, 'Which number does NOT appear in 1 Kings 5?', ['Forty thousand', 'Thirty thousand', 'Seventy thousand', 'Eighty thousand'], 15),
    word(2, 'Which king’s name is paired with Solomon throughout 1 Kings 5?', 'Hiram', 12),
    tf(3, 'Adoniram was in charge of the hewers of stone in the hill country.', false, 14, 'Adoniram was in charge of the levy of forced labor sent to Lebanon.'),
  ],
};

export default bank;
