// 1 Kings 9 — quiz bank (RSV). Every row is anchored to a verse; fill-in-the-blank
// rows are verified against the stored verse text by scripts/seed-quiz-bank.ts.
import { mc, blank, word, tf, type ChapterBank, sa } from './types'

const bank: ChapterBank = {
  book: '1 Kings',
  chapter: 9,
  tag: 'quiz-v2-1kings-9',
  rows: [
    // ══════════════════════════════════ v1–2 · The LORD appears a second time
    blank(1, 'When Solomon had finished building the house of the _____ and the king’s house and all that Solomon desired to build,', 'LORD', 1, ['lord']),
    mc(1, 'What had Solomon finished building at the start of 1 Kings 9?', ['The house of the LORD and the king’s house', 'The wall of Jericho', 'A fleet of ships', 'The city of Hazor'], 1),
    tf(1, 'At the opening of 1 Kings 9, Solomon had finished building the house of the LORD and the king’s house.', true, 1),
    word(2, 'Besides the house of the LORD, whose house had Solomon finished building?', 'king', 1, ['the king', 'kings', 'kings house', 'the kings house']),
    tf(3, 'Verse 1 says Solomon had finished the house of the LORD but the king’s house was still unfinished.', false, 1, 'He had finished the house of the LORD and the king’s house and all that he desired to build.'),
    blank(2, 'When Solomon had finished building the house of the LORD and the king’s house and all that Solomon _____ to build,', 'desired', 1),

    mc(1, 'Where had the LORD previously appeared to Solomon?', ['Gibeon', 'Jerusalem', 'Bethel', 'Hebron'], 2),
    word(1, 'The LORD appeared to Solomon a second time, as he had at what place?', 'Gibeon', 2),
    blank(1, 'the LORD appeared to Solomon a _____ time, as he had appeared to him at Gibeon.', 'second', 2, ['2nd']),
    tf(2, 'This was the first time the LORD had appeared to Solomon.', false, 2, 'The LORD appeared to him "a second time, as he had appeared to him at Gibeon".'),
    blank(2, 'the LORD appeared to Solomon a second time, as he had appeared to him at _____.', 'Gibeon', 2),

    // ══════════════════════════════════ v3–5 · The promise
    blank(1, 'I have heard your _____ and your supplication, which you have made before me;', 'prayer', 3),
    blank(2, 'I have consecrated this house which you have built, and put my _____ there for ever;', 'name', 3),
    mc(2, 'What did the LORD say he had heard from Solomon?', ['His prayer and his supplication', 'His song and his vow', 'His complaint and his lament', 'His oath and his sacrifice'], 3),
    mc(3, 'What did the LORD say would be in the house "for all time"?', ['His eyes and his heart', 'His glory and his cloud', 'His ark and his law', 'His fire and his altar'], 3),
    word(3, 'The LORD said, "my eyes and my ___ will be there for all time."', 'heart', 3),
    tf(1, 'The LORD said he had consecrated the house Solomon built and put his name there for ever.', true, 3),
    blank(3, 'my eyes and my heart will be there for all _____.', 'time', 3),
    mc(1, 'What did the LORD say he had done to the house Solomon built?', ['Consecrated it and put his name there for ever', 'Filled it with smoke', 'Sent fire from heaven upon it', 'Commanded it to be enlarged'], 3),

    mc(1, 'Whose example of walking before the LORD was Solomon told to follow?', ['David his father', 'Moses', 'Abraham', 'Samuel'], 4),
    blank(2, 'if you will walk before me, as David your father walked, with _____ of heart and uprightness,', 'integrity', 4),
    word(2, 'Solomon was to walk before the LORD "with integrity of heart and ___".', 'uprightness', 4),
    tf(2, 'The LORD said Solomon should walk before him as Saul had walked.', false, 4, 'He was to walk "as David your father walked".'),
    blank(3, 'doing according to all that I have commanded you, and keeping my _____ and my ordinances,', 'statutes', 4),
    mc(3, 'Which two things was Solomon to keep, according to verse 4?', ['The LORD’s statutes and ordinances', 'The Sabbath and the feasts', 'The tithes and the offerings', 'The covenant and the ark'], 4),

    blank(1, 'then I will establish your royal _____ over Israel for ever, as I promised David your father,', 'throne', 5),
    mc(2, 'What had the LORD promised David?', ['"There shall not fail you a man upon the throne of Israel"', '"Your son shall build my house"', '"I will give you rest from all your enemies"', '"Your name shall be great in all the earth"'], 5),
    tf(1, 'The LORD promised to establish Solomon’s royal throne over Israel for ever if he obeyed.', true, 5),
    blank(3, 'There shall not fail you a _____ upon the throne of Israel.', 'man', 5),
    word(2, 'The LORD promised to establish Solomon’s royal throne over what nation?', 'Israel', 5),
    tf(3, 'The promise "There shall not fail you a man upon the throne of Israel" was first made to Solomon himself.', false, 5, 'The LORD said, "as I promised David your father".'),

    // ══════════════════════════════════ v6–9 · The warning
    blank(1, 'but go and serve other _____ and worship them,', 'gods', 6),
    mc(2, 'Who, besides Solomon, is named in the warning about turning aside from following the LORD?', ['His children', 'His servants', 'His wives', 'His officials'], 6),
    tf(2, 'The warning in verse 6 applied to Solomon alone, not to his children.', false, 6, 'It says "if you turn aside from following me, you or your children".'),
    word(3, 'The LORD warned against turning aside from following him and going to serve other ___.', 'gods', 6),
    blank(3, 'and do not keep my _____ and my statutes which I have set before you,', 'commandments', 6),
    tf(1, 'The LORD warned Solomon against going to serve other gods and worshiping them.', true, 6),
    mc(3, 'In verse 6, what does "turn aside from following me" go together with?', ['Not keeping his commandments and statutes, and serving other gods', 'Making alliances with Egypt', 'Failing to finish the house', 'Taxing the people heavily'], 6),

    mc(1, 'What did the LORD say he would do to Israel if they turned to other gods?', ['Cut them off from the land he had given them', 'Send famine for seven years', 'Scatter them to Egypt', 'Give them to the Philistines'], 7),
    blank(2, 'and the house which I have consecrated for my name I will cast out of my _____;', 'sight', 7),
    mc(3, 'What would Israel become among all peoples?', ['A proverb and a byword', 'A light and a blessing', 'A terror and a scourge', 'A remnant and a ruin'], 7),
    word(3, 'Israel would become "a proverb and a ___ among all peoples".', 'byword', 7),
    blank(3, 'and Israel will become a _____ and a byword among all peoples.', 'proverb', 7),
    tf(2, 'The LORD said he would cast the consecrated house out of his sight.', true, 7),
    tf(3, 'The LORD threatened to cut off Solomon’s children from the throne but leave Israel in the land.', false, 7, 'He said, "I will cut off Israel from the land which I have given them".'),

    blank(1, 'And this house will become a heap of _____;', 'ruins', 8),
    mc(2, 'What would everyone passing by the ruined house do?', ['Be astonished and hiss', 'Weep and tear their clothes', 'Bow down and pray', 'Laugh and mock'], 8),
    word(2, 'Passers-by would be astonished and would ___.', 'hiss', 8),
    blank(3, 'and they will say, `Why has the LORD done thus to this _____ and to this house?\'', 'land', 8),
    tf(1, 'The LORD said the house would become a heap of ruins if Israel forsook him.', true, 8),
    tf(3, 'Passers-by would ask, "Why has the LORD done thus to this city and to this temple?"', false, 8, 'They would ask, "Why has the LORD done thus to this land and to this house?"'),
    mc(3, 'What question would passers-by ask?', ['"Why has the LORD done thus to this land and to this house?"', '"Where is the God of Israel?"', '"Who has destroyed this great house?"', '"Has the LORD forgotten his people?"'], 8),

    blank(1, 'Because they forsook the LORD their God who brought their fathers out of the land of _____,', 'Egypt', 9),
    mc(2, 'What answer would be given for why the LORD brought all this evil upon them?', ['They forsook the LORD and laid hold on other gods', 'They failed to pay tribute to Egypt', 'They neglected the Sabbath', 'They made an alliance with Tyre'], 9),
    word(1, 'The LORD brought their fathers out of the land of what?', 'Egypt', 9),
    blank(3, 'and laid hold on other gods, and worshiped them and served them; therefore the LORD has brought all this _____ upon them.', 'evil', 9),
    tf(2, 'Verse 9 says the people forsook the LORD who brought their fathers out of the land of Egypt.', true, 9),
    word(3, 'The people "laid hold on other gods, and ___ them and served them."', 'worshiped', 9, ['worshipped']),
    mc(3, 'In verse 9, what did the people do with other gods?', ['Laid hold on them, worshiped them and served them', 'Burned them and cast them out', 'Sold them to the nations', 'Hid them in the house of the LORD'], 9),

    // ══════════════════════════════════ v10–14 · Solomon and Hiram
    mc(1, 'How many years did it take Solomon to build the two houses?', ['Twenty', 'Seven', 'Thirteen', 'Forty'], 10),
    word(1, 'At the end of how many years had Solomon built the two houses?', 'twenty', 10, ['20']),
    blank(1, 'At the end of _____ years, in which Solomon had built the two houses, the house of the LORD and the king’s house,', 'twenty', 10, ['20']),
    mc(2, 'What were the "two houses" of verse 10?', ['The house of the LORD and the king’s house', 'The house of Pharaoh’s daughter and the Millo', 'The houses of Hiram and Solomon', 'The palaces at Hazor and Megiddo'], 10),
    tf(3, 'Verse 10 says the two houses were completed at the end of thirteen years.', false, 10, 'It was "at the end of twenty years".'),

    mc(1, 'Hiram was king of which city?', ['Tyre', 'Sidon', 'Damascus', 'Gaza'], 11),
    word(1, 'Who was king of Tyre?', 'Hiram', 11),
    mc(2, 'What did Solomon give Hiram?', ['Twenty cities in the land of Galilee', 'One hundred talents of silver', 'Ships from Ezion-geber', 'The city of Gezer'], 11),
    word(2, 'How many cities did Solomon give Hiram?', 'twenty', 11, ['20']),
    blank(2, 'King Solomon gave to Hiram twenty cities in the land of _____.', 'Galilee', 11),
    blank(3, 'and Hiram king of Tyre had supplied Solomon with cedar and _____ timber and gold, as much as he desired,', 'cypress', 11),
    mc(3, 'What had Hiram supplied Solomon with?', ['Cedar and cypress timber and gold', 'Silver and bronze and iron', 'Horses and chariots', 'Stone and marble and ivory'], 11),
    tf(1, 'Hiram king of Tyre supplied Solomon with cedar and cypress timber and gold.', true, 11),
    mc(1, 'Who supplied Solomon with timber and gold for his building?', ['Hiram king of Tyre', 'Pharaoh king of Egypt', 'The king of Edom', 'The queen of Sheba'], 11),
    tf(2, 'Solomon gave Hiram twenty cities in the land of Judah.', false, 11, 'The cities were "in the land of Galilee".'),

    tf(1, 'Hiram was pleased with the cities Solomon gave him.', false, 12, 'When he came to see them, "they did not please him".'),
    blank(1, 'But when Hiram came from Tyre to see the cities which Solomon had given him, they did not _____ him.', 'please', 12),
    mc(2, 'What happened when Hiram came from Tyre to see the cities?', ['They did not please him', 'He gave Solomon more gold', 'He settled his servants there', 'He fortified them with walls'], 12),
    word(2, 'Hiram came from where to see the cities Solomon had given him?', 'Tyre', 12),
    mc(2, 'According to verse 12, why did Hiram travel from Tyre?', ['To see the cities which Solomon had given him', 'To deliver cedar and cypress timber', 'To attend the dedication of the house', 'To collect one hundred and twenty talents of gold'], 12),
    tf(3, 'Hiram sent messengers to inspect the cities but never came to see them himself.', false, 12, 'Hiram "came from Tyre to see the cities".'),

    mc(1, 'What name were the cities Solomon gave Hiram called?', ['The land of Cabul', 'The land of Goshen', 'The land of Tob', 'The land of Uz'], 13),
    word(1, 'The cities Hiram received are called the land of what "to this day"?', 'Cabul', 13),
    blank(2, 'So they are called the land of _____ to this day.', 'Cabul', 13),
    mc(2, 'What did Hiram ask Solomon about the cities?', ['"What kind of cities are these which you have given me, my brother?"', '"Why have you given me cities without walls?"', '"Are these the best of Galilee?"', '"Shall I return these to you, my brother?"'], 13),
    word(3, 'Hiram addressed Solomon as "my ___" when complaining about the cities.', 'brother', 13),
    blank(3, 'What kind of cities are these which you have given me, my _____?', 'brother', 13),
    tf(2, 'Hiram addressed Solomon as "my brother" when asking about the cities.', true, 13),
    tf(3, 'Hiram called Solomon "my servant" when he complained about the cities.', false, 13, 'He said, "my brother".'),

    mc(1, 'How much gold had Hiram sent to the king?', ['One hundred and twenty talents', 'Four hundred and twenty talents', 'Six hundred talents', 'Twenty talents'], 14),
    sa(2, 'How many talents of gold had Hiram sent to the king?', 'one hundred and twenty', 14, ['120', 'one hundred twenty', 'a hundred and twenty', 'hundred and twenty']),
    blank(2, 'Hiram had sent to the king one hundred and twenty talents of _____.', 'gold', 14),
    tf(1, 'Hiram had sent the king one hundred and twenty talents of gold.', true, 14),
    tf(3, 'Hiram had sent the king one hundred and twenty talents of silver.', false, 14, 'It was gold.'),
    blank(3, 'Hiram had sent to the king one hundred and _____ talents of gold.', 'twenty', 14, ['20']),

    // ══════════════════════════════════ v15–19 · The forced labor and building projects
    mc(1, 'What kind of labor did Solomon levy to build his projects?', ['Forced labor', 'Volunteer labor', 'Hired labor from Tyre', 'Levite labor'], 15),
    mc(2, 'Which three cities are named at the end of verse 15 as built with forced labor?', ['Hazor, Megiddo and Gezer', 'Jericho, Ai and Bethel', 'Dan, Beersheba and Hebron', 'Tyre, Sidon and Byblos'], 15),
    word(2, 'Which structure is named between "his own house" and "the wall of Jerusalem" in verse 15?', 'Millo', 15, ['the millo']),
    blank(2, 'to build the house of the LORD and his own house and the _____ and the wall of Jerusalem', 'Millo', 15),
    blank(3, 'and the wall of Jerusalem and Hazor and Megid’do and _____', 'Gezer', 15),
    tf(2, 'Solomon used forced labor to build the wall of Jerusalem.', true, 15),
    tf(3, 'Verse 15 lists Hazor, Megiddo and Jericho among Solomon’s building projects.', false, 15, 'The three cities are Hazor, Megiddo and Gezer.'),
    word(3, 'Which city is listed between Hazor and Gezer in verse 15?', 'Megiddo', 15, ['megido']),

    mc(1, 'Who had captured Gezer and burnt it with fire?', ['Pharaoh king of Egypt', 'Hiram king of Tyre', 'David', 'The Philistines'], 16),
    mc(2, 'To whom did Pharaoh give Gezer as a dowry?', ['His daughter, Solomon’s wife', 'Solomon himself', 'Hiram’s daughter', 'The queen of Egypt'], 16),
    blank(1, 'Pharaoh king of Egypt had gone up and captured _____ and burnt it with fire,', 'Gezer', 16),
    word(2, 'Which people dwelling in Gezer did Pharaoh slay?', 'Canaanites', 16, ['canaanite']),
    blank(3, 'and had slain the _____ who dwelt in the city, and had given it as dowry to his daughter, Solomon’s wife;', 'Canaanites', 16),
    tf(2, 'Pharaoh gave Gezer to his daughter as a dowry.', true, 16),
    tf(3, 'Pharaoh captured Gezer and gave it to Hiram king of Tyre.', false, 16, 'He gave it as dowry to his daughter, Solomon’s wife.'),
    word(3, 'Pharaoh gave Gezer to his daughter as what?', 'dowry', 16, ['a dowry']),

    mc(1, 'Which city did Solomon rebuild after Pharaoh burnt it?', ['Gezer', 'Hazor', 'Megiddo', 'Baalath'], 17),
    blank(1, 'so Solomon rebuilt _____) and Lower Beth-hor’on', 'Gezer', 17),
    word(2, 'Along with Gezer, Solomon built "Lower ___".', 'Beth-horon', 17, ['bethhoron', 'beth horon', 'beth-horon']),
    blank(2, 'so Solomon rebuilt Gezer) and _____ Beth-hor’on', 'Lower', 17),
    tf(2, 'According to verse 17, Solomon built Upper Beth-horon.', false, 17, 'It was "Lower Beth-horon".'),
    tf(1, 'Solomon rebuilt Gezer.', true, 17),

    mc(2, 'Which city is described as "in the wilderness, in the land of Judah"?', ['Tamar', 'Baalath', 'Gezer', 'Hazor'], 18),
    word(2, 'Which city is named with Tamar in verse 18?', 'Baalath', 18, ['balath', 'baalat', 'baalah']),
    blank(2, 'and Ba’alath and _____ in the wilderness, in the land of Judah,', 'Tamar', 18),
    blank(3, 'and Ba’alath and Tamar in the wilderness, in the land of _____,', 'Judah', 18),
    tf(3, 'Tamar in the wilderness was in the land of Judah.', true, 18),
    tf(2, 'Tamar in the wilderness was in the land of Galilee.', false, 18, 'It was "in the land of Judah".'),
    mc(3, 'Where was Tamar located, according to verse 18?', ['In the wilderness, in the land of Judah', 'In the land of Galilee', 'On the shore of the Red Sea', 'In Lebanon'], 18),

    mc(2, 'Verse 19 mentions cities for Solomon’s chariots and cities for his what?', ['Horsemen', 'Priests', 'Merchants', 'Craftsmen'], 19),
    blank(1, 'and all the store-cities that Solomon had, and the cities for his _____, and the cities for his horsemen,', 'chariots', 19),
    mc(3, 'In which three places did Solomon build whatever he desired, according to verse 19?', ['Jerusalem, Lebanon, and all the land of his dominion', 'Jerusalem, Egypt, and Tyre', 'Galilee, Judah, and Edom', 'Hazor, Megiddo, and Gezer'], 19),
    word(3, 'Besides Jerusalem and all the land of his dominion, in what land did Solomon build whatever he desired?', 'Lebanon', 19),
    blank(3, 'and whatever Solomon desired to build in Jerusalem, in _____, and in all the land of his dominion.', 'Lebanon', 19),
    word(1, 'Verse 19 names cities for Solomon’s chariots and cities for his ___.', 'horsemen', 19, ['horseman']),

    // ══════════════════════════════════ v20–23 · Slaves and officers
    mc(2, 'Which of these peoples is NOT in the list of verse 20?', ['Philistines', 'Amorites', 'Hittites', 'Jebusites'], 20),
    mc(3, 'Which people is named first in verse 20?', ['Amorites', 'Hittites', 'Perizzites', 'Hivites'], 20),
    word(3, 'Which people is listed between the Hittites and the Hivites in verse 20?', 'Perizzites', 20, ['perizites', 'perizzite']),
    blank(2, 'All the people who were left of the Amorites, the _____, the Per’izzites, the Hivites, and the Jeb’usites,', 'Hittites', 20),
    blank(3, 'All the people who were left of the _____, the Hittites, the Per’izzites, the Hivites, and the Jeb’usites, who were not of the people of Israel', 'Amorites', 20),
    tf(1, 'The peoples listed in verse 20 were not of the people of Israel.', true, 20),
    tf(2, 'Verse 20 lists the Philistines among the peoples who were left in the land.', false, 20, 'The list is the Amorites, Hittites, Perizzites, Hivites and Jebusites.'),
    word(1, 'Verse 20 says the peoples listed "were not of the people of ___".', 'Israel', 20),

    mc(1, 'What did Solomon do with the descendants of the peoples Israel could not destroy?', ['Made them a forced levy of slaves', 'Made them soldiers', 'Expelled them to Egypt', 'Made them priests'], 21),
    blank(2, 'these Solomon made a forced levy of _____, and so they are to this day.', 'slaves', 21),
    tf(2, 'The people of Israel had been unable to destroy these peoples utterly.', true, 21),
    mc(3, 'According to verse 21, why were these peoples’ descendants still in the land?', ['The people of Israel were unable to destroy them utterly', 'Solomon had made a covenant with them', 'They had paid tribute to David', 'Pharaoh had protected them'], 21),
    word(2, 'Solomon made the remaining descendants "a forced levy of ___".', 'slaves', 21),
    blank(3, 'their descendants who were left after them in the land, whom the people of Israel were unable to _____ utterly', 'destroy', 21),
    tf(3, 'Verse 21 says the forced levy of slaves lasted only until Solomon’s death.', false, 21, 'It says "and so they are to this day".'),

    mc(1, 'Of whom did Solomon make no slaves?', ['The people of Israel', 'The Amorites', 'The Canaanites', 'The people of Tyre'], 22),
    tf(1, 'Solomon made slaves of the people of Israel.', false, 22, '"But of the people of Israel Solomon made no slaves."'),
    blank(1, 'But of the people of Israel Solomon made no _____;', 'slaves', 22),
    mc(3, 'Which role is NOT listed for the Israelites in verse 22?', ['Priests', 'Soldiers', 'Officials', 'Chariot commanders'], 22),
    word(2, 'Verse 22 says the Israelites were "the ___", his officials, his commanders, his captains.', 'soldiers', 22, ['soldier']),
    blank(3, 'they were the soldiers, they were his officials, his commanders, his captains, his _____ commanders and his horsemen.', 'chariot', 22),

    mc(1, 'How many chief officers were over Solomon’s work?', ['Five hundred and fifty', 'Three hundred', 'Two hundred and fifty', 'One thousand'], 23),
    sa(1, 'How many chief officers had charge of the people carrying on Solomon’s work?', 'five hundred and fifty', 23, ['550', 'five hundred fifty']),
    blank(2, 'These were the chief officers who were over Solomon’s work: five hundred and _____, who had charge of the people who carried on the work.', 'fifty', 23, ['50']),
    tf(2, 'There were five hundred and fifty chief officers over Solomon’s work.', true, 23),
    blank(3, 'These were the chief _____ who were over Solomon’s work:', 'officers', 23),

    // ══════════════════════════════════ v24–25 · Pharaoh’s daughter; the offerings
    mc(1, 'From where did Pharaoh’s daughter go up to her own house?', ['The city of David', 'Egypt', 'Gezer', 'The house of the LORD'], 24),
    blank(2, 'But Pharaoh’s daughter went up from the city of _____ to her own house which Solomon had built for her;', 'David', 24),
    word(2, 'What did Solomon build after Pharaoh’s daughter moved to her own house?', 'Millo', 24, ['the millo']),
    blank(2, 'then he built the _____.', 'Millo', 24),
    tf(1, 'Solomon built a house for Pharaoh’s daughter.', true, 24),
    tf(3, 'Pharaoh’s daughter went up from the city of David to the house of the LORD.', false, 24, 'She went up "to her own house which Solomon had built for her".'),
    mc(3, 'What did Solomon build right after Pharaoh’s daughter moved into her house?', ['The Millo', 'The wall of Jerusalem', 'The fleet at Ezion-geber', 'Lower Beth-horon'], 24),

    mc(1, 'How often did Solomon offer up burnt offerings and peace offerings on the altar?', ['Three times a year', 'Once a year', 'Every Sabbath', 'Every new moon'], 25),
    word(1, 'How many times a year did Solomon offer up burnt offerings?', 'three', 25, ['3']),
    blank(1, '_____ times a year Solomon used to offer up burnt offerings and peace offerings upon the altar which he built to the LORD,', 'Three', 25, ['3']),
    mc(2, 'What two kinds of offerings did Solomon offer three times a year?', ['Burnt offerings and peace offerings', 'Sin offerings and guilt offerings', 'Grain offerings and drink offerings', 'Wave offerings and firstfruits'], 25),
    blank(3, 'upon the altar which he built to the LORD, burning _____ before the LORD. So he finished the house.', 'incense', 25),
    tf(2, 'Solomon burned incense before the LORD.', true, 25),
    tf(3, 'Solomon offered burnt offerings and peace offerings seven times a year.', false, 25, 'It was "three times a year".'),
    word(3, 'Verse 25 ends: "So he finished the ___."', 'house', 25),

    // ══════════════════════════════════ v26–28 · The fleet and Ophir
    mc(1, 'Where did King Solomon build a fleet of ships?', ['Ezion-geber', 'Joppa', 'Tyre', 'Gezer'], 26),
    word(1, 'What did Solomon build at Ezion-geber?', 'fleet', 26, ['ships', 'a fleet', 'fleet of ships', 'a fleet of ships']),
    blank(1, 'King Solomon built a fleet of _____ at E’zion-ge’ber,', 'ships', 26),
    mc(2, 'Ezion-geber was near which town?', ['Eloth', 'Gaza', 'Beersheba', 'Ophir'], 26),
    word(2, 'Ezion-geber was on the shore of which sea?', 'Red Sea', 26, ['red', 'the red sea']),
    blank(2, 'which is near Eloth on the shore of the Red Sea, in the land of _____.', 'Edom', 26),
    blank(3, 'which is near _____ on the shore of the Red Sea, in the land of Edom.', 'Eloth', 26, ['elath']),
    tf(2, 'Ezion-geber was in the land of Edom.', true, 26),
    tf(3, 'Solomon’s fleet was built at Eloth, in the land of Moab.', false, 26, 'It was built at Ezion-geber, near Eloth, in the land of Edom.'),
    mc(3, 'In what land was Ezion-geber?', ['Edom', 'Moab', 'Judah', 'Egypt'], 26),

    mc(1, 'Who sent seamen familiar with the sea to sail with Solomon’s fleet?', ['Hiram', 'Pharaoh', 'The king of Edom', 'The queen of Sheba'], 27),
    blank(2, 'And Hiram sent with the fleet his servants, _____ who were familiar with the sea, together with the servants of Solomon;', 'seamen', 27),
    word(2, 'Hiram’s servants were seamen who were familiar with what?', 'sea', 27, ['the sea']),
    tf(1, 'Hiram’s seamen sailed together with the servants of Solomon.', true, 27),
    tf(3, 'Verse 27 says Solomon’s servants sailed alone because Hiram refused to send seamen.', false, 27, 'Hiram sent his servants, seamen familiar with the sea, together with Solomon’s servants.'),
    mc(3, 'How does verse 27 describe the servants Hiram sent with the fleet?', ['Seamen who were familiar with the sea', 'Craftsmen skilled in cedar', 'Soldiers trained for war', 'Merchants who knew the markets'], 27),

    mc(1, 'Where did the fleet go to get gold?', ['Ophir', 'Tarshish', 'Sheba', 'Egypt'], 28),
    word(1, 'The fleet sailed to what place and brought back gold?', 'Ophir', 28),
    mc(2, 'How much gold was brought from Ophir?', ['Four hundred and twenty talents', 'One hundred and twenty talents', 'Six hundred and sixty-six talents', 'Two hundred talents'], 28),
    sa(3, 'How many talents of gold did the fleet bring from Ophir?', 'four hundred and twenty', 28, ['420', 'four hundred twenty']),
    blank(1, 'and they went to _____, and brought from there gold,', 'Ophir', 28),
    blank(3, 'and brought from there gold, to the amount of four hundred and _____ talents; and they brought it to King Solomon.', 'twenty', 28, ['20']),
    tf(2, 'The fleet brought four hundred and twenty talents of gold to King Solomon.', true, 28),
    tf(3, 'The fleet brought back one hundred and twenty talents of gold from Ophir.', false, 28, 'It was four hundred and twenty talents; one hundred and twenty was Hiram’s gift in verse 14.'),

    // ══════════════════════════════════ Whole-chapter
    mc(2, 'Which of these happened FIRST in 1 Kings 9?', ['The LORD appeared to Solomon a second time', 'Solomon gave Hiram twenty cities', 'Solomon built a fleet at Ezion-geber', 'The fleet brought gold from Ophir'], 2),
    mc(3, 'Who said, "What kind of cities are these which you have given me, my brother?"', ['Hiram', 'Solomon', 'Pharaoh', 'The LORD'], 13),
    mc(2, 'Which two amounts of gold are mentioned in 1 Kings 9?', ['120 talents from Hiram and 420 talents from Ophir', '100 talents from Hiram and 400 from Ophir', '20 talents from Hiram and 200 from Ophir', '666 talents from Ophir and 120 from Sheba'], 28),
    mc(3, 'Which of these events comes LAST in 1 Kings 9?', ['The fleet brought gold from Ophir', 'Hiram inspected the cities in Galilee', 'Pharaoh’s daughter moved to her own house', 'The LORD appeared to Solomon a second time'], 28),
    tf(2, 'In 1 Kings 9, Solomon received gold from both Hiram and Ophir.', true, 28),
    mc(2, 'Who said, "I have consecrated this house which you have built, and put my name there for ever"?', ['The LORD', 'Solomon', 'Hiram', 'Pharaoh'], 3),
    mc(1, 'Which two kings besides Solomon are named in 1 Kings 9?', ['Hiram king of Tyre and Pharaoh king of Egypt', 'David and Saul', 'The kings of Edom and Moab', 'Hiram and the king of Sheba'], 16),
  ],
};

export default bank;
