// 1 Kings 3 — quiz bank (RSV). Every row is anchored to a verse; fill-in-the-blank
// rows are verified against the stored verse text by scripts/seed-quiz-bank.ts.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: '1 Kings',
  chapter: 3,
  tag: 'quiz-v2-1kings-3',
  rows: [
    // ══════════════════════════════════ v1–3 · Marriage alliance, high places
    mc(1, 'With whom did Solomon make a marriage alliance?', ['Pharaoh king of Egypt', 'The king of Tyre', 'The king of Moab', 'The king of Edom'], 1),
    word(1, 'Solomon took the daughter of which king as his wife?', 'Pharaoh', 1),
    blank(1, 'Solomon made a marriage alliance with Pharaoh king of _____; he took Pharaoh’s daughter, and brought her into the city of David,', 'Egypt', 1),
    mc(2, 'Where did Solomon bring Pharaoh’s daughter?', ['Into the city of David', 'Into the house of the LORD', 'To Gibeon', 'To Egypt'], 1),
    blank(3, 'until he had finished building his own house and the house of the LORD and the _____ around Jerusalem.', 'wall', 1),
    tf(2, 'Solomon brought Pharaoh’s daughter into the city of David until he had finished building his own house, the house of the LORD, and the wall around Jerusalem.', true, 1),
    mc(3, 'Which of these is NOT one of the three building projects named in verse 1?', ['The altar at Gibeon', 'His own house', 'The house of the LORD', 'The wall around Jerusalem'], 1),

    mc(1, 'Why were the people sacrificing at the high places?', ['Because no house had yet been built for the name of the LORD', 'Because the king commanded it', 'Because the ark was kept there', 'Because the priests had fled'], 2),
    blank(2, 'The people were sacrificing at the high places, however, because no _____ had yet been built for the name of the LORD.', 'house', 2),
    word(1, 'Before the temple was built the people were sacrificing at the "high ___".', 'places', 2, ['high places']),
    tf(2, 'The people sacrificed at the high places because a house for the name of the LORD had already been built there.', false, 2, 'They did so because no house had yet been built for the name of the LORD.'),
    mc(3, 'What does verse 2 say had not yet been built?', ['A house for the name of the LORD', 'The wall around Jerusalem', 'Solomon’s own house', 'The altar at Gibeon'], 2),

    blank(1, 'Solomon _____ the LORD, walking in the statutes of David his father;', 'loved', 3),
    mc(2, 'Whose statutes did Solomon walk in?', ['David his father', 'Moses', 'Samuel', 'Pharaoh'], 3),
    tf(1, 'Solomon loved the LORD, walking in the statutes of David his father.', true, 3),
    blank(3, 'only, he sacrificed and burnt _____ at the high places.', 'incense', 3),
    word(2, 'Besides sacrificing, what did Solomon burn at the high places?', 'incense', 3),
    mc(3, 'What qualification ("only, …") does verse 3 add about Solomon’s devotion?', ['He sacrificed and burnt incense at the high places', 'He married a foreign wife', 'He built no altar', 'He neglected the statutes of David'], 3),

    // ══════════════════════════════════ v4–5 · Gibeon and the dream
    mc(1, 'Where did the king go to sacrifice?', ['Gibeon', 'Jerusalem', 'Bethel', 'Hebron'], 4),
    word(1, 'To which place did Solomon go to sacrifice, "the great high place"?', 'Gibeon', 4),
    blank(1, 'And the king went to _____ to sacrifice there, for that was the great high place;', 'Gibeon', 4),
    mc(2, 'How many burnt offerings did Solomon use to offer on the altar at Gibeon?', ['A thousand', 'A hundred', 'Seventy', 'Ten thousand'], 4),
    word(2, 'How many burnt offerings did Solomon use to offer upon the altar at Gibeon?', 'thousand', 4, ['1000', '1,000', 'a thousand']),
    blank(3, 'Solomon used to offer a thousand _____ offerings upon that altar.', 'burnt', 4),
    tf(2, 'Gibeon is described as "the great high place".', true, 4),
    tf(3, 'Solomon used to offer a hundred burnt offerings upon the altar at Gibeon.', false, 4, 'He used to offer a thousand burnt offerings.'),

    mc(1, 'How did the LORD appear to Solomon at Gibeon?', ['In a dream by night', 'In a pillar of fire', 'Through the prophet Nathan', 'In a vision at the altar'], 5),
    blank(1, 'At Gibeon the LORD appeared to Solomon in a _____ by night;', 'dream', 5),
    word(1, 'God appeared to Solomon at Gibeon in a ___ by night.', 'dream', 5),
    mc(1, 'What did God say to Solomon in the dream?', ['"Ask what I shall give you."', '"Build me a house."', '"Fear not, for I am with you."', '"Why have you sacrificed at the high places?"'], 5),
    blank(3, 'and God said, "Ask what I shall _____ you."', 'give', 5),
    tf(1, 'The LORD appeared to Solomon in a dream by night at Gibeon.', true, 5),
    tf(2, 'The LORD appeared to Solomon in a dream while he was in Jerusalem.', false, 5, 'The dream came at Gibeon.'),

    // ══════════════════════════════════ v6–9 · Solomon’s prayer
    blank(2, 'Thou hast shown great and _____ love to thy servant David my father,', 'steadfast', 6),
    mc(3, 'According to Solomon, how had David walked before the LORD?', ['In faithfulness, in righteousness, and in uprightness of heart', 'In humility, in wisdom, and in strength', 'In fear and in trembling', 'In sacrifice and in song'], 6),
    blank(3, 'because he walked before thee in faithfulness, in righteousness, and in _____ of heart toward thee;', 'uprightness', 6),
    word(3, 'Solomon said God had given David a son to sit on his ___ this day.', 'throne', 6),
    tf(2, 'Solomon began his prayer by recalling God’s steadfast love to his father David.', true, 6),
    mc(2, 'In his prayer, Solomon said God had kept his steadfast love for David and given him what?', ['A son to sit on his throne this day', 'Victory over all his enemies', 'A house of cedar', 'Length of days'], 6),

    blank(1, 'thou hast made thy servant king in place of David my father, although I am but a little _____;', 'child', 7),
    mc(1, 'How did Solomon describe himself to God?', ['As "but a little child"', 'As a mighty warrior', 'As the wisest of men', 'As a faithful priest'], 7),
    word(2, 'Solomon said, "I do not know how to go out or come ___."', 'in', 7),
    tf(2, 'Solomon told God, "I do not know how to go out or come in."', true, 7),
    blank(3, 'And now, O LORD my God, thou hast made thy servant _____ in place of David my father,', 'king', 7),
    tf(1, 'Solomon told God he was fully prepared and experienced for kingship.', false, 7, 'He said "I am but a little child; I do not know how to go out or come in."'),

    blank(2, 'And thy servant is in the midst of thy people whom thou hast _____, a great people,', 'chosen', 8),
    mc(2, 'How did Solomon describe the people of Israel in his prayer?', ['A great people that cannot be numbered or counted for multitude', 'A stiff-necked people', 'A people few in number', 'A people scattered among the nations'], 8),
    word(3, 'Solomon said the people could not be numbered or counted for what?', 'multitude', 8),
    tf(3, 'Solomon said God’s people were so few they could easily be counted.', false, 8, 'He said they were "a great people, that cannot be numbered or counted for multitude".'),
    blank(3, 'a great people, that cannot be _____ or counted for multitude.', 'numbered', 8),
    mc(3, 'Solomon said he was "in the midst of" whom?', ['Thy people whom thou hast chosen', 'His enemies', 'The princes of Egypt', 'The priests and Levites'], 8),

    mc(1, 'What did Solomon ask God for?', ['An understanding mind to govern the people', 'Long life', 'Riches', 'The death of his enemies'], 9),
    blank(1, 'Give thy servant therefore an _____ mind to govern thy people,', 'understanding', 9),
    word(2, 'Solomon asked for an understanding ___ to govern the people.', 'mind', 9),
    blank(2, 'that I may discern between good and _____;', 'evil', 9),
    mc(2, 'Why did Solomon want an understanding mind?', ['To discern between good and evil', 'To build the temple', 'To defeat his enemies', 'To interpret dreams'], 9),
    tf(1, 'Solomon asked God for an understanding mind to govern the people.', true, 9),
    word(3, 'Solomon ended his request with a question: "for who is able to ___ this thy great people?"', 'govern', 9),
    tf(3, 'Solomon asked for an understanding mind so that he might discern between rich and poor.', false, 9, 'He asked to "discern between good and evil".'),

    // ══════════════════════════════════ v10–14 · God’s answer
    tf(1, 'The Lord was pleased with Solomon’s request.', true, 10),
    blank(1, 'It _____ the Lord that Solomon had asked this.', 'pleased', 10),
    mc(2, 'How did the Lord respond to Solomon’s request?', ['It pleased the Lord', 'The Lord was angry', 'The Lord was silent', 'The Lord rebuked him'], 10),
    tf(2, 'The Lord was displeased that Solomon asked for wisdom rather than riches.', false, 10, 'It pleased the Lord that Solomon had asked this.'),

    mc(1, 'Which of these did Solomon NOT ask for, according to God?', ['Long life, riches, or the life of his enemies', 'Understanding', 'Discernment of what is right', 'Wisdom to govern'], 11),
    blank(2, 'and have not asked for yourself long life or _____ or the life of your enemies,', 'riches', 11),
    blank(3, 'but have asked for yourself understanding to discern what is _____,', 'right', 11),
    word(2, 'God noted Solomon had not asked for the life of his ___.', 'enemies', 11),
    tf(2, 'God noted that Solomon had not asked for long life, riches, or the life of his enemies.', true, 11),
    mc(3, 'God said Solomon had asked for understanding to do what?', ['To discern what is right', 'To build the house of the LORD', 'To rule over Egypt', 'To interpret the law'], 11),
    tf(3, 'God said Solomon had asked for the life of his enemies.', false, 11, 'He had NOT asked for long life, riches, or the life of his enemies.'),

    blank(1, 'Behold, I give you a wise and _____ mind,', 'discerning', 12),
    mc(1, 'What did God give Solomon?', ['A wise and discerning mind', 'A strong and mighty army', 'A long and peaceful life', 'A house of cedar'], 12),
    word(2, 'God gave Solomon "a wise and discerning ___".', 'mind', 12),
    mc(2, 'How unique would Solomon’s wisdom be, according to God?', ['None like him had been before and none like him would arise after', 'Equal to the wise men of Egypt', 'Greater than David but less than Moses', 'Greatest in Israel for a generation'], 12),
    blank(3, 'so that none like you has been before you and none like you shall _____ after you.', 'arise', 12),
    tf(2, 'God said none like Solomon had been before him and none like him would arise after him.', true, 12),
    blank(3, 'behold, I now do according to your _____.', 'word', 12),

    mc(1, 'What did God give Solomon that he had NOT asked for?', ['Riches and honor', 'Long life', 'Victory over his enemies', 'Many sons'], 13),
    blank(1, 'I give you also what you have not asked, both _____ and honor,', 'riches', 13),
    word(2, 'Along with riches, what did God give Solomon that he had not asked for?', 'honor', 13, ['honour']),
    tf(3, 'God said no other king would compare with Solomon all his days.', true, 13),
    blank(3, 'so that no other _____ shall compare with you, all your days.', 'king', 13),
    tf(1, 'God gave Solomon riches and honor even though he had not asked for them.', true, 13),

    mc(2, 'What did God promise if Solomon walked in his ways?', ['To lengthen his days', 'To give him more riches', 'To subdue all nations before him', 'To dwell in his house'], 14),
    blank(2, 'then I will _____ your days.', 'lengthen', 14),
    word(2, 'God promised to lengthen Solomon’s ___ if he kept the statutes and commandments.', 'days', 14),
    word(2, 'God told Solomon to walk in his ways "as your father ___ walked".', 'David', 14),
    blank(3, 'And if you will walk in my ways, keeping my _____ and my commandments, as your father David walked,', 'statutes', 14),
    tf(1, 'God’s promise of long life to Solomon was conditional on him walking in God’s ways.', true, 14),
    tf(3, 'God promised to lengthen Solomon’s days unconditionally.', false, 14, 'The promise was "if you will walk in my ways, keeping my statutes and my commandments".'),
    mc(3, 'Whose example was Solomon to follow in walking in God’s ways?', ['His father David', 'Moses', 'Abraham', 'Samuel'], 14),

    // ══════════════════════════════════ v15 · Back to Jerusalem
    blank(1, 'And Solomon awoke, and behold, it was a _____.', 'dream', 15),
    mc(1, 'Where did Solomon go after he awoke from the dream?', ['Jerusalem', 'Gibeon', 'Hebron', 'Egypt'], 15),
    word(2, 'In Jerusalem Solomon stood before the ark of the ___ of the LORD.', 'covenant', 15),
    mc(2, 'What offerings did Solomon offer in Jerusalem after the dream?', ['Burnt offerings and peace offerings', 'Sin offerings and guilt offerings', 'Grain offerings and drink offerings', 'A thousand burnt offerings'], 15),
    blank(3, 'and offered up burnt offerings and _____ offerings, and made a feast for all his servants.', 'peace', 15),
    tf(2, 'After the dream Solomon made a feast for all his servants.', true, 15),
    tf(3, 'After awaking, Solomon stayed at Gibeon and offered burnt offerings there.', false, 15, 'He came to Jerusalem and stood before the ark of the covenant.'),
    word(1, 'For whom did Solomon make a feast after returning to Jerusalem?', 'servants', 15, ['his servants', 'all his servants']),

    // ══════════════════════════════════ v16–22 · The two harlots
    mc(1, 'Who came to the king and stood before him?', ['Two harlots', 'Two priests', 'Two elders', 'Two widows'], 16),
    blank(1, 'Then two _____ came to the king, and stood before him.', 'harlots', 16, ['harlot']),
    word(1, 'How many harlots came to the king?', 'two', 16, ['2']),
    tf(2, 'Three harlots came before the king.', false, 16, 'Two harlots came to the king.'),

    blank(1, 'Oh, my lord, this woman and I dwell in the same _____;', 'house', 17),
    tf(1, 'The two women lived in the same house.', true, 17),
    mc(3, 'What did the first woman say about where she and the other woman lived?', ['They dwelt in the same house', 'They lived in neighboring houses', 'They lived in the king’s palace', 'They lived in different cities'], 17),
    word(2, 'The first woman said, "I gave birth to a ___ while she was in the house."', 'child', 17),
    blank(3, 'and I gave _____ to a child while she was in the house.', 'birth', 17),

    mc(2, 'How long after the first woman gave birth did the second woman give birth?', ['On the third day', 'The same night', 'On the seventh day', 'A month later'], 18),
    word(2, 'On which day after the first woman was delivered did the other woman give birth?', 'third', 18, ['3rd', 'the third day', '3']),
    blank(2, 'Then on the _____ day after I was delivered, this woman also gave birth;', 'third', 18),
    tf(2, 'The first woman said there were witnesses in the house when the children were born.', false, 18, 'She said "there was no one else with us in the house, only we two were in the house".'),
    blank(3, 'and we were alone; there was no one else with us in the house, only we _____ were in the house.', 'two', 18),
    tf(3, 'The first woman said only the two of them were in the house.', true, 18),
    mc(2, 'Who else was in the house when the second woman gave birth?', ['No one — only the two women', 'A midwife', 'The women’s husbands', 'A servant'], 18),

    mc(1, 'How did the other woman’s son die?', ['She lay on it in the night', 'It fell sick', 'It was stolen', 'It was never born alive'], 19),
    blank(1, 'And this woman’s son died in the _____, because she lay on it.', 'night', 19),
    word(2, 'The first woman said the other woman’s son died because she ___ on it.', 'lay', 19),
    word(1, 'At what time of day did the other woman’s son die?', 'night', 19, ['in the night', 'at night']),
    tf(1, 'According to the first woman, the other woman’s son died because she lay on it.', true, 19),
    tf(3, 'The first woman said the other woman’s son died in the morning.', false, 19, 'The son "died in the night".'),

    mc(2, 'At what time did the other woman switch the babies?', ['Midnight', 'Dawn', 'Noon', 'Evening'], 20),
    word(3, 'The first woman said the other woman arose at what time?', 'midnight', 20),
    blank(1, 'And she arose at _____, and took my son from beside me, while your maidservant slept,', 'midnight', 20),
    blank(3, 'and laid it in her bosom, and laid her _____ son in my bosom.', 'dead', 20),
    tf(2, 'The first woman claimed the other woman took her son while she slept and laid the dead son in her bosom.', true, 20),
    mc(3, 'According to the first woman, what did the other woman do while she slept?', ['Took her son from beside her, laid it in her own bosom, and laid her dead son in the first woman’s bosom', 'Fled the house with both children', 'Woke the neighbors', 'Hid the dead child in the street'], 20),

    blank(1, 'When I rose in the morning to _____ my child, behold, it was dead;', 'nurse', 21),
    mc(1, 'When did the first woman discover the dead child?', ['In the morning, when she rose to nurse her child', 'At midnight', 'On the third day', 'When the king questioned her'], 21),
    word(2, 'When the first woman rose in the ___, she found the child dead.', 'morning', 21),
    tf(2, 'The first woman said that when she looked closely, the dead child was not the one she had borne.', true, 21),
    blank(3, 'but when I looked at it _____ in the morning, behold, it was not the child that I had borne.', 'closely', 21),
    mc(3, 'How did the first woman realize the switch?', ['She looked at the dead child closely and saw it was not the child she had borne', 'The other woman confessed', 'A neighbor told her', 'The living child cried for her'], 21),

    blank(1, 'But the other woman said, "No, the _____ child is mine, and the dead child is yours."', 'living', 22),
    mc(1, 'What did the other woman claim?', ['"The living child is mine, and the dead child is yours"', '"Both children are mine"', '"The dead child is mine"', '"Neither child is mine"'], 22),
    tf(1, 'The two women agreed about which child belonged to whom.', false, 22, 'Each claimed the living child was hers and the dead child the other’s.'),
    blank(3, 'The first said, "No, the dead child is yours, and the living child is mine." Thus they spoke before the _____.', 'king', 22),
    tf(3, 'The other woman admitted that the dead child was hers.', false, 22, 'She said "the living child is mine, and the dead child is yours".'),
    word(3, 'Verse 22 ends, "Thus they spoke before the ___."', 'king', 22),

    // ══════════════════════════════════ v23–28 · The judgment
    mc(2, 'What did the king do after hearing both women?', ['He restated each woman’s claim', 'He dismissed them both', 'He called for witnesses', 'He asked the priests to judge'], 23),
    blank(2, 'The one says, `This is my son that is _____, and your son is dead\';', 'alive', 23),
    tf(2, 'The king summarized both women’s claims before acting.', true, 23),
    blank(3, 'and the other says, `No; but your son is dead, and my son is the _____ one.\'', 'living', 23),
    word(3, 'The king repeated, "This is my son that is ___, and your son is dead."', 'alive', 23),

    mc(1, 'What did the king ask to be brought to him?', ['A sword', 'A scale', 'The ark', 'A cradle'], 24),
    word(1, 'What did the king say, "Bring me a ___"?', 'sword', 24),
    blank(1, 'And the king said, "Bring me a _____." So a sword was brought before the king.', 'sword', 24),
    tf(1, 'The king asked for a sword to be brought before him.', true, 24),
    tf(3, 'The king asked for a spear to be brought before him.', false, 24, 'He said "Bring me a sword."'),

    mc(1, 'What did the king command be done with the living child?', ['Divide it in two and give half to each woman', 'Give it to the first woman', 'Give it to the second woman', 'Raise it in the palace'], 25),
    blank(1, 'And the king said, "_____ the living child in two, and give half to the one, and half to the other."', 'Divide', 25),
    word(3, 'The king ordered the living child divided in how many parts?', 'two', 25, ['2']),
    blank(2, 'Divide the living child in two, and give _____ to the one, and half to the other.', 'half', 25),
    tf(2, 'The king commanded that the dead child be divided in two.', false, 25, 'He commanded the living child be divided.'),
    tf(3, 'The king said to give half of the child to the one and half to the other.', true, 25),

    mc(1, 'What did the true mother say when the king ordered the child divided?', ['"Oh, my lord, give her the living child, and by no means slay it"', '"It shall be neither mine nor yours; divide it"', '"Give me the sword"', '"The child is dead already"'], 26),
    mc(2, 'What did the other woman say when the king ordered the child divided?', ['"It shall be neither mine nor yours; divide it"', '"Give her the living child"', '"Spare the child, my lord"', '"I am its mother"'], 26),
    blank(1, 'Oh, my lord, give her the living child, and by no means _____ it.', 'slay', 26),
    word(2, 'Why did the true mother speak up? Because her ___ yearned for her son.', 'heart', 26),
    blank(3, 'Then the woman whose son was alive said to the king, because her heart _____ for her son,', 'yearned', 26),
    tf(1, 'The real mother begged the king to give the living child to the other woman rather than kill it.', true, 26),
    tf(2, 'The woman whose son was alive said, "It shall be neither mine nor yours; divide it."', false, 26, 'That was said by the other woman; the true mother said "give her the living child, and by no means slay it".'),
    blank(3, 'But the other said, "It shall be neither mine nor yours; _____ it."', 'divide', 26),

    mc(1, 'To whom did the king give the living child?', ['The first woman', 'The second woman', 'Neither woman', 'The priests'], 27),
    blank(1, 'Give the living child to the _____ woman, and by no means slay it; she is its mother.', 'first', 27),
    word(1, 'The king said of the first woman, "she is its ___".', 'mother', 27),
    tf(1, 'The king gave the living child to the first woman.', true, 27),
    blank(3, 'Give the living child to the first woman, and by no means slay it; she is its _____.', 'mother', 27),
    mc(3, 'What reason did the king give for his verdict?', ['"She is its mother"', '"She spoke first"', '"She is the elder"', '"The other woman lied about the night"'], 27),
    tf(3, 'The king ruled that the child be given to the second woman.', false, 27, 'He said "Give the living child to the first woman".'),

    mc(1, 'How did all Israel react to the king’s judgment?', ['They stood in awe of the king', 'They rebelled against the king', 'They mourned the child', 'They demanded a new trial'], 28),
    blank(1, 'And all Israel heard of the _____ which the king had rendered;', 'judgment', 28, ['judgement']),
    blank(3, 'and they stood in _____ of the king,', 'awe', 28),
    word(2, 'Israel perceived that the ___ of God was in Solomon.', 'wisdom', 28),
    mc(2, 'Why did Israel stand in awe of the king?', ['They perceived that the wisdom of God was in him, to render justice', 'He had a thousand chariots', 'He had married Pharaoh’s daughter', 'He had built the temple'], 28),
    blank(3, 'because they perceived that the wisdom of God was in him, to render _____.', 'justice', 28),
    tf(1, 'All Israel heard of the king’s judgment and stood in awe of him.', true, 28),
    tf(3, 'Only the people of Jerusalem heard of the king’s judgment.', false, 28, '"All Israel heard of the judgment".'),

    // ══════════════════════════════════ Whole-chapter
    mc(3, 'Which of these events happened FIRST in 1 Kings 3?', ['Solomon’s marriage alliance with Pharaoh', 'The dream at Gibeon', 'The two harlots come before the king', 'All Israel stands in awe of the king'], 1),
    mc(2, 'Which of these happened LAST in 1 Kings 3?', ['All Israel heard of the judgment and stood in awe of the king', 'Solomon offered a thousand burnt offerings at Gibeon', 'God appeared to Solomon in a dream', 'Solomon made a feast for all his servants'], 28),
    mc(2, 'Who said, "Ask what I shall give you"?', ['God', 'Solomon', 'Pharaoh', 'The first woman'], 5),
    mc(2, 'Who said, "Bring me a sword"?', ['The king', 'The first woman', 'The other woman', 'A servant'], 24),
    mc(3, 'Who said, "It shall be neither mine nor yours; divide it"?', ['The other woman (whose son was dead)', 'The woman whose son was alive', 'The king', 'A servant of the king'], 26),
    tf(2, 'In 1 Kings 3 the dream at Gibeon comes before the judgment between the two harlots.', true, 16),
    word(1, 'Who is the king throughout 1 Kings 3?', 'Solomon', 4),
  ],
};

export default bank;
