// 1 Kings 22 — quiz bank (RSV). Four verse-anchored forms per verse.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: "1 Kings",
  chapter: 22,
  tag: "quiz-v2-1kings-22",
  rows: [
    blank(2, "For three years Syria and _____ continued without war.", "Israel", 1, ["israel"]),
    mc(3, "Which word correctly completes this RSV wording: “For three years Syria and _____ continued without war.”", ["Israel", "Sama’ria", "Jo’ash", "Shilhi"], 1),
    word(1, "In verse 1, what word completes this phrase: “For three years Syria and _____ continued without war.”?", "Israel", 1, ["israel"]),
    tf(2, "The RSV states: “For three years Syria and Israel continued without war.”", true, 1),
    blank(3, "But in the third year _____ the king of Judah came down to the king of Israel.", "Jehosh’aphat", 2, ["jehoshaphat"]),
    mc(1, "Which word correctly completes this RSV wording: “But in the third year _____ the king of Judah came down to the king of Israel.”", ["Jehosh’aphat", "Jeho’ram", "Ahazi’ah", "Zedeki’ah"], 2),
    word(2, "In verse 2, what word completes this phrase: “But in the third year _____ the king of Judah came down to the king of Israel.”?", "Jehosh’aphat", 2, ["jehoshaphat"]),
    tf(3, "The RSV does not state: “But in the third year Jehosh’aphat the king of Judah came down to the king of Israel.”", false, 2, "The quoted wording is the RSV text of this verse."),
    blank(1, "And the king of Israel said to his servants, \"Do you know that _____ belongs to us, and we keep quiet and do not take it out of the hand of", "Ramoth-gilead", 3, ["ramoth-gilead"]),
    mc(2, "Which word correctly completes this RSV wording: “And the king of Israel said to his servants, \"Do you know that _____ belongs to us, and we keep quiet and do not take it out of the hand of”", ["Ramoth-gilead", "Jerusalem", "Chronicles", "Chena’anah"], 3),
    word(3, "In verse 3, what word completes this phrase: “And the king of Israel said to his servants, \"Do you know that _____ belongs to us, and we keep quiet and do not take it out of the hand of”?", "Ramoth-gilead", 3, ["ramoth-gilead"]),
    tf(1, "The RSV states: “And the king of Israel said to his servants, \"Do you know that Ramoth-gilead belongs to us, and we keep quiet and do not take it out of the hand of the king of Syria?\"”", true, 3),
    blank(2, "And he said to Jehosh’aphat, \"Will you go with me to battle at _____?\" And Jehosh’aphat said to the king of Israel, \"I am as you are, my people", "Ramoth-gilead", 4, ["ramoth-gilead"]),
    mc(3, "Which word correctly completes this RSV wording: “And he said to Jehosh’aphat, \"Will you go with me to battle at _____?\" And Jehosh’aphat said to the king of Israel, \"I am as you are, my people”", ["Ramoth-gilead", "Sama’ria", "Jehosh’aphat", "Jeho’ram"], 4),
    word(1, "In verse 4, what word completes this phrase: “And he said to Jehosh’aphat, \"Will you go with me to battle at _____?\" And Jehosh’aphat said to the king of Israel, \"I am as you are, my people”?", "Ramoth-gilead", 4, ["ramoth-gilead"]),
    tf(2, "The RSV does not state: “And he said to Jehosh’aphat, \"Will you go with me to battle at Ramoth-gilead?\" And Jehosh’aphat said to the king of Israel, \"I am as you are, my people as your people, my horses as your horses.\"”", false, 4, "The quoted wording is the RSV text of this verse."),
    blank(3, "And _____ said to the king of Israel, \"Inquire first for the word of the LORD.\"", "Jehosh’aphat", 5, ["jehoshaphat"]),
    mc(1, "Which word correctly completes this RSV wording: “And _____ said to the king of Israel, \"Inquire first for the word of the LORD.\"”", ["Jehosh’aphat", "Sama’ria", "Jeho’ram", "Ahazi’ah"], 5),
    word(2, "In verse 5, what word completes this phrase: “And _____ said to the king of Israel, \"Inquire first for the word of the LORD.\"”?", "Jehosh’aphat", 5, ["jehoshaphat"]),
    tf(3, "The RSV states: “And Jehosh’aphat said to the king of Israel, \"Inquire first for the word of the LORD.\"”", true, 5),
    blank(1, "about four hundred men, and said to them, \"Shall I go to battle against _____, or shall I forbear?\" And they said, \"Go up; for the Lord will give it", "Ramoth-gilead", 6, ["ramoth-gilead"]),
    mc(2, "Which word correctly completes this RSV wording: “about four hundred men, and said to them, \"Shall I go to battle against _____, or shall I forbear?\" And they said, \"Go up; for the Lord will give it”", ["Ramoth-gilead", "Zedeki’ah", "Micai’ah", "Jerobo’am"], 6),
    word(3, "In verse 6, what word completes this phrase: “about four hundred men, and said to them, \"Shall I go to battle against _____, or shall I forbear?\" And they said, \"Go up; for the Lord will give it”?", "Ramoth-gilead", 6, ["ramoth-gilead"]),
    tf(1, "The RSV does not state: “Then the king of Israel gathered the prophets together, about four hundred men, and said to them, \"Shall I go to battle against Ramoth-gilead, or shall I forbear?\" And they said, \"Go up; for the Lord will give it into the hand of the king.\"”", false, 6, "The quoted wording is the RSV text of this verse."),
    blank(2, "But _____ said, \"Is there not here another prophet of the LORD of whom we may inquire?\"", "Jehosh’aphat", 7, ["jehoshaphat"]),
    mc(3, "Which word correctly completes this RSV wording: “But _____ said, \"Is there not here another prophet of the LORD of whom we may inquire?\"”", ["Jehosh’aphat", "Inquire", "Tarshish", "Therefore"], 7),
    word(1, "In verse 7, what word completes this phrase: “But _____ said, \"Is there not here another prophet of the LORD of whom we may inquire?\"”?", "Jehosh’aphat", 7, ["jehoshaphat"]),
    tf(2, "The RSV states: “But Jehosh’aphat said, \"Is there not here another prophet of the LORD of whom we may inquire?\"”", true, 7),
    blank(3, "And the king of Israel said to _____, \"There is yet one man by whom we may inquire of the LORD, Micai’ah the", "Jehosh’aphat", 8, ["jehoshaphat"]),
    mc(1, "Which word correctly completes this RSV wording: “And the king of Israel said to _____, \"There is yet one man by whom we may inquire of the LORD, Micai’ah the”", ["Jehosh’aphat", "Chronicles", "Sama’ria", "Jeho’ram"], 8),
    word(2, "In verse 8, what word completes this phrase: “And the king of Israel said to _____, \"There is yet one man by whom we may inquire of the LORD, Micai’ah the”?", "Jehosh’aphat", 8, ["jehoshaphat"]),
    tf(3, "The RSV does not state: “And the king of Israel said to Jehosh’aphat, \"There is yet one man by whom we may inquire of the LORD, Micai’ah the son of Imlah; but I hate him, for he never prophesies good concerning me, but evil.\" And Jehosh’aphat said, \"Let not the king say so.\"”", false, 8, "The quoted wording is the RSV text of this verse."),
    blank(1, "Then the king of Israel summoned an officer and said, \"Bring quickly _____ the son of Imlah.\"", "Micai’ah", 9, ["micaiah"]),
    mc(2, "Which word correctly completes this RSV wording: “Then the king of Israel summoned an officer and said, \"Bring quickly _____ the son of Imlah.\"”", ["Micai’ah", "Fight", "Tarshish", "Judah"], 9),
    word(3, "In verse 9, what word completes this phrase: “Then the king of Israel summoned an officer and said, \"Bring quickly _____ the son of Imlah.\"”?", "Micai’ah", 9, ["micaiah"]),
    tf(1, "The RSV states: “Then the king of Israel summoned an officer and said, \"Bring quickly Micai’ah the son of Imlah.\"”", true, 9),
    blank(2, "Now the king of Israel and _____ the king of Judah were sitting on their thrones, arrayed in their robes,", "Jehosh’aphat", 10, ["jehoshaphat"]),
    mc(3, "Which word correctly completes this RSV wording: “Now the king of Israel and _____ the king of Judah were sitting on their thrones, arrayed in their robes,”", ["Jehosh’aphat", "Syrians", "Inquire", "Tarshish"], 10),
    word(1, "In verse 10, what word completes this phrase: “Now the king of Israel and _____ the king of Judah were sitting on their thrones, arrayed in their robes,”?", "Jehosh’aphat", 10, ["jehoshaphat"]),
    tf(2, "The RSV does not state: “Now the king of Israel and Jehosh’aphat the king of Judah were sitting on their thrones, arrayed in their robes, at the threshing floor at the entrance of the gate of Sama’ria; and all the prophets were prophesying before them.”", false, 10, "The quoted wording is the RSV text of this verse."),
    blank(3, "And Zedeki’ah the son of _____ made for himself horns of iron, and said, \"Thus says the LORD, `With these", "Chena’anah", 11, ["chenaanah"]),
    mc(1, "Which word correctly completes this RSV wording: “And Zedeki’ah the son of _____ made for himself horns of iron, and said, \"Thus says the LORD, `With these”", ["Chena’anah", "Bring", "Chronicles", "Jerobo’am"], 11),
    word(2, "In verse 11, what word completes this phrase: “And Zedeki’ah the son of _____ made for himself horns of iron, and said, \"Thus says the LORD, `With these”?", "Chena’anah", 11, ["chenaanah"]),
    tf(3, "The RSV states: “And Zedeki’ah the son of Chena’anah made for himself horns of iron, and said, \"Thus says the LORD, `With these you shall push the Syrians until they are destroyed.’\"”", true, 11),
    blank(1, "And all the prophets prophesied so, and said, \"Go up to _____ and triumph; the LORD will give it into the hand of the king.\"", "Ramoth-gilead", 12, ["ramoth-gilead"]),
    mc(2, "Which word correctly completes this RSV wording: “And all the prophets prophesied so, and said, \"Go up to _____ and triumph; the LORD will give it into the hand of the king.\"”", ["Ramoth-gilead", "Chronicles", "Chena’anah", "Sama’ria"], 12),
    word(3, "In verse 12, what word completes this phrase: “And all the prophets prophesied so, and said, \"Go up to _____ and triumph; the LORD will give it into the hand of the king.\"”?", "Ramoth-gilead", 12, ["ramoth-gilead"]),
    tf(1, "The RSV does not state: “And all the prophets prophesied so, and said, \"Go up to Ramoth-gilead and triumph; the LORD will give it into the hand of the king.\"”", false, 12, "The quoted wording is the RSV text of this verse."),
    blank(2, "And the messenger who went to summon _____ said to him, \"Behold, the words of the prophets with one accord are favorable", "Micai’ah", 13, ["micaiah"]),
    mc(3, "Which word correctly completes this RSV wording: “And the messenger who went to summon _____ said to him, \"Behold, the words of the prophets with one accord are favorable”", ["Micai’ah", "Sama’ria", "Jo’ash", "Shilhi"], 13),
    word(1, "In verse 13, what word completes this phrase: “And the messenger who went to summon _____ said to him, \"Behold, the words of the prophets with one accord are favorable”?", "Micai’ah", 13, ["micaiah"]),
    tf(2, "The RSV states: “And the messenger who went to summon Micai’ah said to him, \"Behold, the words of the prophets with one accord are favorable to the king; let your word be like the word of one of them, and speak favorably.\"”", true, 13),
    blank(3, "But _____ said, \"As the LORD lives, what the LORD says to me, that I will speak.\"", "Micai’ah", 14, ["micaiah"]),
    mc(1, "Which word correctly completes this RSV wording: “But _____ said, \"As the LORD lives, what the LORD says to me, that I will speak.\"”", ["Micai’ah", "Ahab", "Kings", "Jerobo’am"], 14),
    word(2, "In verse 14, what word completes this phrase: “But _____ said, \"As the LORD lives, what the LORD says to me, that I will speak.\"”?", "Micai’ah", 14, ["micaiah"]),
    tf(3, "The RSV does not state: “But Micai’ah said, \"As the LORD lives, what the LORD says to me, that I will speak.\"”", false, 14, "The quoted wording is the RSV text of this verse."),
    blank(1, "had come to the king, the king said to him, \"Micai’ah, shall we go to _____ to battle, or shall we forbear?\" And he answered him, \"Go up and triumph;", "Ramoth-gilead", 15, ["ramoth-gilead"]),
    mc(2, "Which word correctly completes this RSV wording: “had come to the king, the king said to him, \"Micai’ah, shall we go to _____ to battle, or shall we forbear?\" And he answered him, \"Go up and triumph;”", ["Ramoth-gilead", "Micai’ah", "Jerobo’am", "E’zion-ge’ber"], 15),
    word(3, "In verse 15, what word completes this phrase: “had come to the king, the king said to him, \"Micai’ah, shall we go to _____ to battle, or shall we forbear?\" And he answered him, \"Go up and triumph;”?", "Ramoth-gilead", 15, ["ramoth-gilead"]),
    tf(1, "The RSV states: “And when he had come to the king, the king said to him, \"Micai’ah, shall we go to Ramoth-gilead to battle, or shall we forbear?\" And he answered him, \"Go up and triumph; the LORD will give it into the hand of the king.\"”", true, 15),
    blank(2, "said to him, \"How many times shall I adjure you that you speak to me _____ but the truth in the name of the LORD?\"", "nothing", 16, ["nothing"]),
    mc(3, "Which word correctly completes this RSV wording: “said to him, \"How many times shall I adjure you that you speak to me _____ but the truth in the name of the LORD?\"”", ["nothing", "succeed", "back", "peoples"], 16),
    word(1, "In verse 16, what word completes this phrase: “said to him, \"How many times shall I adjure you that you speak to me _____ but the truth in the name of the LORD?\"”?", "nothing", 16, ["nothing"]),
    tf(2, "The RSV does not state: “But the king said to him, \"How many times shall I adjure you that you speak to me nothing but the truth in the name of the LORD?\"”", false, 16, "The quoted wording is the RSV text of this verse."),
    blank(3, "And he said, \"I saw all _____ scattered upon the mountains, as sheep that have no shepherd; and the", "Israel", 17, ["israel"]),
    mc(1, "Which word correctly completes this RSV wording: “And he said, \"I saw all _____ scattered upon the mountains, as sheep that have no shepherd; and the”", ["Israel", "Imlah", "Seize", "Jerusalem"], 17),
    word(2, "In verse 17, what word completes this phrase: “And he said, \"I saw all _____ scattered upon the mountains, as sheep that have no shepherd; and the”?", "Israel", 17, ["israel"]),
    tf(3, "The RSV states: “And he said, \"I saw all Israel scattered upon the mountains, as sheep that have no shepherd; and the LORD said, `These have no master; let each return to his home in peace.’\"”", true, 17),
    blank(1, "And the king of Israel said to _____, \"Did I not tell you that he would not prophesy good concerning me, but", "Jehosh’aphat", 18, ["jehoshaphat"]),
    mc(2, "Which word correctly completes this RSV wording: “And the king of Israel said to _____, \"Did I not tell you that he would not prophesy good concerning me, but”", ["Jehosh’aphat", "Jeho’ram", "Ahazi’ah", "Zedeki’ah"], 18),
    word(3, "In verse 18, what word completes this phrase: “And the king of Israel said to _____, \"Did I not tell you that he would not prophesy good concerning me, but”?", "Jehosh’aphat", 18, ["jehoshaphat"]),
    tf(1, "The RSV does not state: “And the king of Israel said to Jehosh’aphat, \"Did I not tell you that he would not prophesy good concerning me, but evil?\"”", false, 18, "The quoted wording is the RSV text of this verse."),
    blank(2, "And Micai’ah said, \"_____ hear the word of the LORD: I saw the LORD sitting on his throne, and all", "Therefore", 19, ["therefore"]),
    mc(3, "Which word correctly completes this RSV wording: “And Micai’ah said, \"_____ hear the word of the LORD: I saw the LORD sitting on his throne, and all”", ["Therefore", "Sama’ria", "Hear", "Edom"], 19),
    word(1, "In verse 19, what word completes this phrase: “And Micai’ah said, \"_____ hear the word of the LORD: I saw the LORD sitting on his throne, and all”?", "Therefore", 19, ["therefore"]),
    tf(2, "The RSV states: “And Micai’ah said, \"Therefore hear the word of the LORD: I saw the LORD sitting on his throne, and all the host of heaven standing beside him on his right hand and on his left;”", true, 19),
    blank(3, "and the LORD said, `Who will entice Ahab, that he may go up and fall at _____?’ And one said one thing, and another said another.", "Ramoth-gilead", 20, ["ramoth-gilead"]),
    mc(1, "Which word correctly completes this RSV wording: “and the LORD said, `Who will entice Ahab, that he may go up and fall at _____?’ And one said one thing, and another said another.”", ["Ramoth-gilead", "E’zion-ge’ber", "Jerusalem", "Chronicles"], 20),
    word(2, "In verse 20, what word completes this phrase: “and the LORD said, `Who will entice Ahab, that he may go up and fall at _____?’ And one said one thing, and another said another.”?", "Ramoth-gilead", 20, ["ramoth-gilead"]),
    tf(3, "The RSV does not state: “and the LORD said, `Who will entice Ahab, that he may go up and fall at Ramoth-gilead?’ And one said one thing, and another said another.”", false, 20, "The quoted wording is the RSV text of this verse."),
    blank(1, "Then a spirit came _____ and stood before the LORD, saying, `I will entice him.’", "forward", 21, ["forward"]),
    mc(2, "Which word correctly completes this RSV wording: “Then a spirit came _____ and stood before the LORD, saying, `I will entice him.’”", ["forward", "surely", "breastplate", "wound"], 21),
    word(3, "In verse 21, what word completes this phrase: “Then a spirit came _____ and stood before the LORD, saying, `I will entice him.’”?", "forward", 21, ["forward"]),
    tf(1, "The RSV states: “Then a spirit came forward and stood before the LORD, saying, `I will entice him.’”", true, 21),
    blank(2, "`I will go forth, and will be a lying spirit in the mouth of all his _____.’ And he said, `You are to entice him, and you shall succeed; go forth", "prophets", 22, ["prophets"]),
    mc(3, "Which word correctly completes this RSV wording: “`I will go forth, and will be a lying spirit in the mouth of all his _____.’ And he said, `You are to entice him, and you shall succeed; go forth”", ["prophets", "venture", "facing", "brought"], 22),
    word(1, "In verse 22, what word completes this phrase: “`I will go forth, and will be a lying spirit in the mouth of all his _____.’ And he said, `You are to entice him, and you shall succeed; go forth”?", "prophets", 22, ["prophets"]),
    tf(2, "The RSV does not state: “And the LORD said to him, `By what means?’ And he said, `I will go forth, and will be a lying spirit in the mouth of all his prophets.’ And he said, `You are to entice him, and you shall succeed; go forth and do so.’”", false, 22, "The quoted wording is the RSV text of this verse."),
    blank(3, "spirit in the mouth of all these your prophets; the LORD has spoken evil _____ you.\"", "concerning", 23, ["concerning"]),
    mc(1, "Which word correctly completes this RSV wording: “spirit in the mouth of all these your prophets; the LORD has spoken evil _____ you.\"”", ["concerning", "still", "deputy", "years"], 23),
    word(2, "In verse 23, what word completes this phrase: “spirit in the mouth of all these your prophets; the LORD has spoken evil _____ you.\"”?", "concerning", 23, ["concerning"]),
    tf(3, "The RSV states: “Now therefore behold, the LORD has put a lying spirit in the mouth of all these your prophets; the LORD has spoken evil concerning you.\"”", true, 23),
    blank(1, "Then Zedeki’ah the son of _____ came near and struck Micai’ah on the cheek, and said, \"How did the Spirit", "Chena’anah", 24, ["chenaanah"]),
    mc(2, "Which word correctly completes this RSV wording: “Then Zedeki’ah the son of _____ came near and struck Micai’ah on the cheek, and said, \"How did the Spirit”", ["Chena’anah", "Nebat", "Bring", "Chronicles"], 24),
    word(3, "In verse 24, what word completes this phrase: “Then Zedeki’ah the son of _____ came near and struck Micai’ah on the cheek, and said, \"How did the Spirit”?", "Chena’anah", 24, ["chenaanah"]),
    tf(1, "The RSV does not state: “Then Zedeki’ah the son of Chena’anah came near and struck Micai’ah on the cheek, and said, \"How did the Spirit of the LORD go from me to speak to you?\"”", false, 24, "The quoted wording is the RSV text of this verse."),
    blank(2, "And _____ said, \"Behold, you shall see on that day when you go into an inner chamber", "Micai’ah", 25, ["micaiah"]),
    mc(3, "Which word correctly completes this RSV wording: “And _____ said, \"Behold, you shall see on that day when you go into an inner chamber”", ["Micai’ah", "Chena’anah", "Fight", "Tarshish"], 25),
    word(1, "In verse 25, what word completes this phrase: “And _____ said, \"Behold, you shall see on that day when you go into an inner chamber”?", "Micai’ah", 25, ["micaiah"]),
    tf(2, "The RSV states: “And Micai’ah said, \"Behold, you shall see on that day when you go into an inner chamber to hide yourself.\"”", true, 25),
    blank(3, "And the king of Israel said, \"Seize _____, and take him back to Amon the governor of the city and to Jo’ash the", "Micai’ah", 26, ["micaiah"]),
    mc(1, "Which word correctly completes this RSV wording: “And the king of Israel said, \"Seize _____, and take him back to Amon the governor of the city and to Jo’ash the”", ["Micai’ah", "Seize", "Jerusalem", "Ba’al"], 26),
    word(2, "In verse 26, what word completes this phrase: “And the king of Israel said, \"Seize _____, and take him back to Amon the governor of the city and to Jo’ash the”?", "Micai’ah", 26, ["micaiah"]),
    tf(3, "The RSV does not state: “And the king of Israel said, \"Seize Micai’ah, and take him back to Amon the governor of the city and to Jo’ash the king’s son;”", false, 26, "The quoted wording is the RSV text of this verse."),
    blank(1, "and say, `_____ says the king, \"Put this fellow in prison, and feed him with scant fare", "Thus", 27, ["thus"]),
    mc(2, "Which word correctly completes this RSV wording: “and say, `_____ says the king, \"Put this fellow in prison, and feed him with scant fare”", ["Thus", "Zedeki’ah", "Turn", "David"], 27),
    word(3, "In verse 27, what word completes this phrase: “and say, `_____ says the king, \"Put this fellow in prison, and feed him with scant fare”?", "Thus", 27, ["thus"]),
    tf(1, "The RSV states: “and say, `Thus says the king, \"Put this fellow in prison, and feed him with scant fare of bread and water, until I come in peace.\"’\"”", true, 27),
    blank(2, "And _____ said, \"If you return in peace, the LORD has not spoken by me.\" And he", "Micai’ah", 28, ["micaiah"]),
    mc(3, "Which word correctly completes this RSV wording: “And _____ said, \"If you return in peace, the LORD has not spoken by me.\" And he”", ["Micai’ah", "Edom", "Jehosh’aphat", "Syrians"], 28),
    word(1, "In verse 28, what word completes this phrase: “And _____ said, \"If you return in peace, the LORD has not spoken by me.\" And he”?", "Micai’ah", 28, ["micaiah"]),
    tf(2, "The RSV does not state: “And Micai’ah said, \"If you return in peace, the LORD has not spoken by me.\" And he said, \"Hear, all you peoples!\"”", false, 28, "The quoted wording is the RSV text of this verse."),
    blank(3, "So the king of Israel and Jehosh’aphat the king of Judah went up to _____.", "Ramoth-gilead", 29, ["ramoth-gilead"]),
    mc(1, "Which word correctly completes this RSV wording: “So the king of Israel and Jehosh’aphat the king of Judah went up to _____.”", ["Ramoth-gilead", "Jerusalem", "Chronicles", "Chena’anah"], 29),
    word(2, "In verse 29, what word completes this phrase: “So the king of Israel and Jehosh’aphat the king of Judah went up to _____.”?", "Ramoth-gilead", 29, ["ramoth-gilead"]),
    tf(3, "The RSV states: “ So the king of Israel and Jehosh’aphat the king of Judah went up to Ramoth-gilead.”", true, 29),
    blank(1, "And the king of Israel said to _____, \"I will disguise myself and go into battle, but you wear your robes.\"", "Jehosh’aphat", 30, ["jehoshaphat"]),
    mc(2, "Which word correctly completes this RSV wording: “And the king of Israel said to _____, \"I will disguise myself and go into battle, but you wear your robes.\"”", ["Jehosh’aphat", "Micai’ah", "E’zion-ge’ber", "Chronicles"], 30),
    word(3, "In verse 30, what word completes this phrase: “And the king of Israel said to _____, \"I will disguise myself and go into battle, but you wear your robes.\"”?", "Jehosh’aphat", 30, ["jehoshaphat"]),
    tf(1, "The RSV does not state: “And the king of Israel said to Jehosh’aphat, \"I will disguise myself and go into battle, but you wear your robes.\" And the king of Israel disguised himself and went into battle.”", false, 30, "The quoted wording is the RSV text of this verse."),
    blank(2, "chariots, \"Fight with neither small nor great, but only with the king of _____.\"", "Israel", 31, ["israel"]),
    mc(3, "Which word correctly completes this RSV wording: “chariots, \"Fight with neither small nor great, but only with the king of _____.\"”", ["Israel", "Jerusalem", "Syria", "Syrians"], 31),
    word(1, "In verse 31, what word completes this phrase: “chariots, \"Fight with neither small nor great, but only with the king of _____.\"”?", "Israel", 31, ["israel"]),
    tf(2, "The RSV states: “Now the king of Syria had commanded the thirty-two captains of his chariots, \"Fight with neither small nor great, but only with the king of Israel.\"”", true, 31),
    blank(3, "And when the captains of the chariots saw _____, they said, \"It is surely the king of Israel.\" So they turned to fight", "Jehosh’aphat", 32, ["jehoshaphat"]),
    mc(1, "Which word correctly completes this RSV wording: “And when the captains of the chariots saw _____, they said, \"It is surely the king of Israel.\" So they turned to fight”", ["Jehosh’aphat", "Ramoth-gilead", "Azu’bah", "Syrians"], 32),
    word(2, "In verse 32, what word completes this phrase: “And when the captains of the chariots saw _____, they said, \"It is surely the king of Israel.\" So they turned to fight”?", "Jehosh’aphat", 32, ["jehoshaphat"]),
    tf(3, "The RSV does not state: “And when the captains of the chariots saw Jehosh’aphat, they said, \"It is surely the king of Israel.\" So they turned to fight against him; and Jehosh’aphat cried out.”", false, 32, "The quoted wording is the RSV text of this verse."),
    blank(1, "And when the captains of the chariots saw that it was not the king of _____, they turned back from pursuing him.", "Israel", 33, ["israel"]),
    mc(2, "Which word correctly completes this RSV wording: “And when the captains of the chariots saw that it was not the king of _____, they turned back from pursuing him.”", ["Israel", "Shall", "Ahab", "Kings"], 33),
    word(3, "In verse 33, what word completes this phrase: “And when the captains of the chariots saw that it was not the king of _____, they turned back from pursuing him.”?", "Israel", 33, ["israel"]),
    tf(1, "The RSV states: “And when the captains of the chariots saw that it was not the king of Israel, they turned back from pursuing him.”", true, 33),
    blank(2, "But a certain man drew his bow at a venture, and struck the king of _____ between the scale armor and the breastplate; therefore he said to the", "Israel", 34, ["israel"]),
    mc(3, "Which word correctly completes this RSV wording: “But a certain man drew his bow at a venture, and struck the king of _____ between the scale armor and the breastplate; therefore he said to the”", ["Israel", "Thus", "Turn", "Ophir"], 34),
    word(1, "In verse 34, what word completes this phrase: “But a certain man drew his bow at a venture, and struck the king of _____ between the scale armor and the breastplate; therefore he said to the”?", "Israel", 34, ["israel"]),
    tf(2, "The RSV does not state: “But a certain man drew his bow at a venture, and struck the king of Israel between the scale armor and the breastplate; therefore he said to the driver of his chariot, \"Turn about, and carry me out of the battle, for I am wounded.\"”", false, 34, "The quoted wording is the RSV text of this verse."),
    blank(3, "grew hot that day, and the king was propped up in his chariot facing the _____, until at evening he died; and the blood of the wound flowed into the", "Syrians", 35, ["syrians"]),
    mc(1, "Which word correctly completes this RSV wording: “grew hot that day, and the king was propped up in his chariot facing the _____, until at evening he died; and the blood of the wound flowed into the”", ["Syrians", "Chena’anah", "Turn", "Ophir"], 35),
    word(2, "In verse 35, what word completes this phrase: “grew hot that day, and the king was propped up in his chariot facing the _____, until at evening he died; and the blood of the wound flowed into the”?", "Syrians", 35, ["syrians"]),
    tf(3, "The RSV states: “And the battle grew hot that day, and the king was propped up in his chariot facing the Syrians, until at evening he died; and the blood of the wound flowed into the bottom of the chariot.”", true, 35),
    blank(1, "And about sunset a cry went through the army, \"_____ man to his city, and every man to his country!\"", "Every", 36, ["every"]),
    mc(2, "Which word correctly completes this RSV wording: “And about sunset a cry went through the army, \"_____ man to his city, and every man to his country!\"”", ["Every", "Chronicles", "Jerobo’am", "Sama’ria"], 36),
    word(3, "In verse 36, what word completes this phrase: “And about sunset a cry went through the army, \"_____ man to his city, and every man to his country!\"”?", "Every", 36, ["every"]),
    tf(1, "The RSV does not state: “And about sunset a cry went through the army, \"Every man to his city, and every man to his country!\"”", false, 36, "The quoted wording is the RSV text of this verse."),
    blank(2, "So the king died, and was brought to _____; and they buried the king in Sama’ria.", "Sama’ria", 37, ["samaria"]),
    mc(3, "Which word correctly completes this RSV wording: “So the king died, and was brought to _____; and they buried the king in Sama’ria.”", ["Sama’ria", "Syrians", "Every", "E’zion-ge’ber"], 37),
    word(1, "In verse 37, what word completes this phrase: “So the king died, and was brought to _____; and they buried the king in Sama’ria.”?", "Sama’ria", 37, ["samaria"]),
    tf(2, "The RSV states: “So the king died, and was brought to Sama’ria; and they buried the king in Sama’ria.”", true, 37),
    blank(3, "And they washed the chariot by the pool of _____, and the dogs licked up his blood, and the harlots washed themselves in", "Sama’ria", 38, ["samaria"]),
    mc(1, "Which word correctly completes this RSV wording: “And they washed the chariot by the pool of _____, and the dogs licked up his blood, and the harlots washed themselves in”", ["Sama’ria", "Jo’ash", "Shilhi", "Israel"], 38),
    word(2, "In verse 38, what word completes this phrase: “And they washed the chariot by the pool of _____, and the dogs licked up his blood, and the harlots washed themselves in”?", "Sama’ria", 38, ["samaria"]),
    tf(3, "The RSV does not state: “And they washed the chariot by the pool of Sama’ria, and the dogs licked up his blood, and the harlots washed themselves in it, according to the word of the LORD which he had spoken.”", false, 38, "The quoted wording is the RSV text of this verse."),
    blank(1, "all the cities that he built, are they not written in the Book of the _____ of the Kings of Israel?", "Chronicles", 39, ["chronicles"]),
    mc(2, "Which word correctly completes this RSV wording: “all the cities that he built, are they not written in the Book of the _____ of the Kings of Israel?”", ["Chronicles", "Israel", "Chena’anah", "Jerusalem"], 39),
    word(3, "In verse 39, what word completes this phrase: “all the cities that he built, are they not written in the Book of the _____ of the Kings of Israel?”?", "Chronicles", 39, ["chronicles"]),
    tf(1, "The RSV states: “Now the rest of the acts of Ahab, and all that he did, and the ivory house which he built, and all the cities that he built, are they not written in the Book of the Chronicles of the Kings of Israel?”", true, 39),
    blank(2, "So Ahab slept with his fathers; and _____ his son reigned in his stead.", "Ahazi’ah", 40, ["ahaziah"]),
    mc(3, "Which word correctly completes this RSV wording: “So Ahab slept with his fathers; and _____ his son reigned in his stead.”", ["Ahazi’ah", "Ophir", "Ramoth-gilead", "Behold"], 40),
    word(1, "In verse 40, what word completes this phrase: “So Ahab slept with his fathers; and _____ his son reigned in his stead.”?", "Ahazi’ah", 40, ["ahaziah"]),
    tf(2, "The RSV does not state: “So Ahab slept with his fathers; and Ahazi’ah his son reigned in his stead.”", false, 40, "The quoted wording is the RSV text of this verse."),
    blank(3, "_____ the son of Asa began to reign over Judah in the fourth year of Ahab king", "Jehosh’aphat", 41, ["jehoshaphat"]),
    mc(1, "Which word correctly completes this RSV wording: “_____ the son of Asa began to reign over Judah in the fourth year of Ahab king”", ["Jehosh’aphat", "Jerobo’am", "Jerusalem", "Chena’anah"], 41),
    word(2, "In verse 41, what word completes this phrase: “_____ the son of Asa began to reign over Judah in the fourth year of Ahab king”?", "Jehosh’aphat", 41, ["jehoshaphat"]),
    tf(3, "The RSV states: “Jehosh’aphat the son of Asa began to reign over Judah in the fourth year of Ahab king of Israel.”", true, 41),
    blank(1, "_____ was thirty-five years old when he began to reign, and he reigned twenty-five", "Jehosh’aphat", 42, ["jehoshaphat"]),
    mc(2, "Which word correctly completes this RSV wording: “_____ was thirty-five years old when he began to reign, and he reigned twenty-five”", ["Jehosh’aphat", "Syrians", "Inquire", "Tarshish"], 42),
    word(3, "In verse 42, what word completes this phrase: “_____ was thirty-five years old when he began to reign, and he reigned twenty-five”?", "Jehosh’aphat", 42, ["jehoshaphat"]),
    tf(1, "The RSV does not state: “Jehosh’aphat was thirty-five years old when he began to reign, and he reigned twenty-five years in Jerusalem. His mother’s name was Azu’bah the daughter of Shilhi.”", false, 42, "The quoted wording is the RSV text of this verse."),
    blank(2, "the LORD; yet the high places were not taken away, and the people still _____ and burned incense on the high places.", "sacrificed", 43, ["sacrificed"]),
    mc(3, "Which word correctly completes this RSV wording: “the LORD; yet the high places were not taken away, and the people still _____ and burned incense on the high places.”", ["sacrificed", "chariot", "every", "built"], 43),
    word(1, "In verse 43, what word completes this phrase: “the LORD; yet the high places were not taken away, and the people still _____ and burned incense on the high places.”?", "sacrificed", 43, ["sacrificed"]),
    tf(2, "The RSV states: “He walked in all the way of Asa his father; he did not turn aside from it, doing what was right in the sight of the LORD; yet the high places were not taken away, and the people still sacrificed and burned incense on the high places.”", true, 43),
    blank(3, "_____ also made peace with the king of Israel.", "Jehosh’aphat", 44, ["jehoshaphat"]),
    mc(1, "Which word correctly completes this RSV wording: “_____ also made peace with the king of Israel.”", ["Jehosh’aphat", "Zedeki’ah", "Jerobo’am", "Jerusalem"], 44),
    word(2, "In verse 44, what word completes this phrase: “_____ also made peace with the king of Israel.”?", "Jehosh’aphat", 44, ["jehoshaphat"]),
    tf(3, "The RSV does not state: “Jehosh’aphat also made peace with the king of Israel.”", false, 44, "The quoted wording is the RSV text of this verse."),
    blank(1, "Now the rest of the acts of _____, and his might that he showed, and how he warred, are they not written", "Jehosh’aphat", 45, ["jehoshaphat"]),
    mc(2, "Which word correctly completes this RSV wording: “Now the rest of the acts of _____, and his might that he showed, and how he warred, are they not written”", ["Jehosh’aphat", "Azu’bah", "Syrians", "Inquire"], 45),
    word(3, "In verse 45, what word completes this phrase: “Now the rest of the acts of _____, and his might that he showed, and how he warred, are they not written”?", "Jehosh’aphat", 45, ["jehoshaphat"]),
    tf(1, "The RSV states: “ Now the rest of the acts of Jehosh’aphat, and his might that he showed, and how he warred, are they not written in the Book of the Chronicles of the Kings of Judah?”", true, 45),
    blank(2, "male cult prostitutes who remained in the days of his father Asa, he _____ from the land.", "exterminated", 46, ["exterminated"]),
    mc(3, "Which word correctly completes this RSV wording: “male cult prostitutes who remained in the days of his father Asa, he _____ from the land.”", ["exterminated", "sacrificed", "without", "inquire"], 46),
    word(1, "In verse 46, what word completes this phrase: “male cult prostitutes who remained in the days of his father Asa, he _____ from the land.”?", "exterminated", 46, ["exterminated"]),
    tf(2, "The RSV does not state: “And the remnant of the male cult prostitutes who remained in the days of his father Asa, he exterminated from the land.”", false, 46, "The quoted wording is the RSV text of this verse."),
    blank(3, "There was no king in _____; a deputy was king.", "Edom", 47, ["edom"]),
    mc(1, "Which word correctly completes this RSV wording: “There was no king in _____; a deputy was king.”", ["Edom", "Micai’ah", "Seize", "Azu’bah"], 47),
    word(2, "In verse 47, what word completes this phrase: “There was no king in _____; a deputy was king.”?", "Edom", 47, ["edom"]),
    tf(3, "The RSV states: “There was no king in Edom; a deputy was king.”", true, 47),
    blank(1, "to Ophir for gold; but they did not go, for the ships were wrecked at _____.", "E’zion-ge’ber", 48, ["ezion-geber"]),
    mc(2, "Which word correctly completes this RSV wording: “to Ophir for gold; but they did not go, for the ships were wrecked at _____.”", ["E’zion-ge’ber", "Jeho’ram", "Jerusalem", "Chronicles"], 48),
    word(3, "In verse 48, what word completes this phrase: “to Ophir for gold; but they did not go, for the ships were wrecked at _____.”?", "E’zion-ge’ber", 48, ["ezion-geber"]),
    tf(1, "The RSV does not state: “Jehosh’aphat made ships of Tarshish to go to Ophir for gold; but they did not go, for the ships were wrecked at E’zion-ge’ber.”", false, 48, "The quoted wording is the RSV text of this verse."),
    blank(2, "Then Ahazi’ah the son of Ahab said to _____, \"Let my servants go with your servants in the ships,\" but Jehosh’aphat", "Jehosh’aphat", 49, ["jehoshaphat"]),
    mc(3, "Which word correctly completes this RSV wording: “Then Ahazi’ah the son of Ahab said to _____, \"Let my servants go with your servants in the ships,\" but Jehosh’aphat”", ["Jehosh’aphat", "Therefore", "Micai’ah", "E’zion-ge’ber"], 49),
    word(1, "In verse 49, what word completes this phrase: “Then Ahazi’ah the son of Ahab said to _____, \"Let my servants go with your servants in the ships,\" but Jehosh’aphat”?", "Jehosh’aphat", 49, ["jehoshaphat"]),
    tf(2, "The RSV states: “Then Ahazi’ah the son of Ahab said to Jehosh’aphat, \"Let my servants go with your servants in the ships,\" but Jehosh’aphat was not willing.”", true, 49),
    blank(3, "And _____ slept with his fathers, and was buried with his fathers in the city of", "Jehosh’aphat", 50, ["jehoshaphat"]),
    mc(1, "Which word correctly completes this RSV wording: “And _____ slept with his fathers, and was buried with his fathers in the city of”", ["Jehosh’aphat", "Jeho’ram", "Ahazi’ah", "Zedeki’ah"], 50),
    word(2, "In verse 50, what word completes this phrase: “And _____ slept with his fathers, and was buried with his fathers in the city of”?", "Jehosh’aphat", 50, ["jehoshaphat"]),
    tf(3, "The RSV does not state: “And Jehosh’aphat slept with his fathers, and was buried with his fathers in the city of David his father; and Jeho’ram his son reigned in his stead.”", false, 50, "The quoted wording is the RSV text of this verse."),
    blank(1, "Ahab began to reign over Israel in Sama’ria in the seventeenth year of _____ king of Judah, and he reigned two years over Israel.", "Jehosh’aphat", 51, ["jehoshaphat"]),
    mc(2, "Which word correctly completes this RSV wording: “Ahab began to reign over Israel in Sama’ria in the seventeenth year of _____ king of Judah, and he reigned two years over Israel.”", ["Jehosh’aphat", "Chena’anah", "Ramoth-gilead", "Azu’bah"], 51),
    word(3, "In verse 51, what word completes this phrase: “Ahab began to reign over Israel in Sama’ria in the seventeenth year of _____ king of Judah, and he reigned two years over Israel.”?", "Jehosh’aphat", 51, ["jehoshaphat"]),
    tf(1, "The RSV states: “Ahazi’ah the son of Ahab began to reign over Israel in Sama’ria in the seventeenth year of Jehosh’aphat king of Judah, and he reigned two years over Israel.”", true, 51),
    blank(2, "the way of his father, and in the way of his mother, and in the way of _____ the son of Nebat, who made Israel to sin.", "Jerobo’am", 52, ["jeroboam"]),
    mc(3, "Which word correctly completes this RSV wording: “the way of his father, and in the way of his mother, and in the way of _____ the son of Nebat, who made Israel to sin.”", ["Jerobo’am", "E’zion-ge’ber", "Shall", "Ahab"], 52),
    word(1, "In verse 52, what word completes this phrase: “the way of his father, and in the way of his mother, and in the way of _____ the son of Nebat, who made Israel to sin.”?", "Jerobo’am", 52, ["jeroboam"]),
    tf(2, "The RSV does not state: “He did what was evil in the sight of the LORD, and walked in the way of his father, and in the way of his mother, and in the way of Jerobo’am the son of Nebat, who made Israel to sin.”", false, 52, "The quoted wording is the RSV text of this verse."),
    blank(3, "He served Ba’al and worshiped him, and provoked the LORD, the God of _____, to anger in every way that his father had done.", "Israel", 53, ["israel"]),
    mc(1, "Which word correctly completes this RSV wording: “He served Ba’al and worshiped him, and provoked the LORD, the God of _____, to anger in every way that his father had done.”", ["Israel", "Shilhi", "Inquire", "Therefore"], 53),
    word(2, "In verse 53, what word completes this phrase: “He served Ba’al and worshiped him, and provoked the LORD, the God of _____, to anger in every way that his father had done.”?", "Israel", 53, ["israel"]),
    tf(3, "The RSV states: “He served Ba’al and worshiped him, and provoked the LORD, the God of Israel, to anger in every way that his father had done.”", true, 53),
    mc(1, "What did Jehoshaphat ask Ahab to do before going to Ramoth-gilead?", ["Inquire first for the word of the LORD", "Send gifts to the king of Syria", "Consult the prophets of Baal", "Gather the elders of Judah"], 5),
    mc(2, "Why did Ahab say he hated Micaiah son of Imlah?", ["Micaiah never prophesied good concerning him, but evil", "Micaiah refused to come before him", "Micaiah supported Jehoshaphat", "Micaiah had fled to Syria"], 8),
    mc(2, "Which prophet made horns of iron and said Israel would push the Syrians with them?", ["Zedekiah son of Chenaanah", "Micaiah son of Imlah", "Jehu son of Hanani", "Elijah the Tishbite"], 11),
    mc(3, "What spirit volunteered to entice Ahab in Micaiah’s vision?", ["A lying spirit in the mouth of all his prophets", "A spirit of fear in his army", "An evil spirit in the king of Syria", "A spirit of confusion among the people"], 22),
    mc(3, "How was the disguised Ahab mortally wounded?", ["A man drew his bow at a venture and struck between his scale armor and breastplate", "A Syrian king recognized and speared him", "His chariot overturned", "An arrow struck him while he addressed his army"], 34),
    mc(2, "Where did dogs lick up Ahab’s blood?", ["By the pool of Samaria where they washed his chariot", "At Naboth’s vineyard", "At the gate of Jezreel", "Beside the pool of Gibeon"], 38),
  ],
};

export default bank;
