import { mc, blank, word, tf, type ChapterBank, sa } from './types'

const bank: ChapterBank = {
  book: '1 Kings', chapter: 17, tag: 'quiz-v2-1kings-17', rows: [
    mc(3, 'Who announced that there would be neither dew nor rain?', ['Elijah the Tishbite', 'Jehu son of Hanani', 'Ahab', 'Obadiah'], 1),
    blank(1, 'there shall be neither dew nor rain these years, except by my _____.', 'word', 1),
    word(3, 'To which king did Elijah speak?', 'Ahab', 1),
    tf(1, 'Elijah said rain would come only by his word.', true, 1),
    mc(2, 'From what region was Elijah?', ['Tishbe in Gilead', 'Samaria', 'Zarephath in Sidon', 'Bethel'], 1),
    blank(2, 'Now Eli’jah the Tishbite, of Tishbe in _____', 'Gilead', 1),

    mc(1, 'Whose word came to Elijah?', ['The LORD’s', 'Ahab’s', 'The widow’s', 'The king of Sidon’s'], 2),
    blank(2, 'And the _____ of the LORD came to him', 'word', 2),
    word(1, 'To whom did the word come?', 'Elijah', 2),
    tf(3, 'The word of the LORD came to Elijah.', true, 2),
    mc(2, 'What begins the next stage of Elijah’s journey?', ['A word from the LORD', 'An order from Ahab', 'A plea from a widow', 'A message from ravens'], 2),
    blank(3, 'And the word of the LORD _____ to him', 'came', 2),

    mc(1, 'Where was Elijah told to hide?', ['By the brook Cherith', 'In Samaria', 'At Zarephath’s gate', 'In Tirzah'], 3),
    blank(2, 'Depart from here and turn _____', 'eastward', 3),
    word(2, 'What river lay west of the brook Cherith?', 'Jordan', 3, ['the Jordan']),
    tf(3, 'The brook Cherith was east of the Jordan.', true, 3),
    mc(2, 'What two directions did the LORD give Elijah?', ['Turn eastward and hide by Cherith', 'Go west and enter Samaria', 'Travel south and meet Ahab', 'Cross north into Sidon'], 3),
    blank(3, 'and hide yourself by the brook _____', 'Cherith', 3),

    mc(1, 'What was Elijah to drink?', ['Water from the brook', 'Wine from Samaria', 'Oil from a cruse', 'Rainwater'], 4),
    blank(2, 'I have commanded the _____ to feed you there.', 'ravens', 4),
    word(1, 'Who would feed Elijah?', 'ravens', 4),
    tf(3, 'Elijah was told to find his own food.', false, 4, 'The LORD had commanded ravens to feed him.'),
    mc(2, 'Which provision came directly from the brook?', ['Elijah’s drink', 'His bread', 'His meat', 'His oil'], 4),
    blank(3, 'You shall _____ from the brook', 'drink', 4),

    mc(1, 'How did Elijah respond to the LORD’s word?', ['He went and did according to it', 'He stayed with Ahab', 'He went to Zarephath immediately', 'He questioned the command'], 5),
    blank(2, 'he went and dwelt by the brook _____', 'Cherith', 5),
    sa(2, 'Where was Cherith located?', 'east of the Jordan', 5),
    tf(3, 'Elijah went and lived by the brook Cherith as the LORD had commanded.', true, 5),
    mc(2, 'What did Elijah do in response to the LORD’s command?', ['He went and lived by the brook Cherith east of the Jordan', 'He returned to Ahab and remained at the royal court', 'He announced that rain would begin immediately', 'He left Israel and settled permanently in Jerusalem'], 5),
    blank(3, 'So he went and _____ according to the word of the LORD; he went and dwelt by the brook Cherith that is east of the Jordan.', 'did', 5),

    mc(1, 'What did the ravens bring Elijah?', ['Bread and meat', 'Meal and oil', 'Loaves and honey', 'Fish and bread'], 6),
    blank(2, 'And the ravens brought him bread and meat in the _____.', 'morning', 6),
    sa(1, 'From where did Elijah drink?', 'the brook', 6),
    tf(3, 'The ravens brought Elijah bread and meat in both the morning and the evening.', true, 6),
    mc(2, 'How often did the ravens bring bread and meat?', ['Morning and evening', 'Once each week', 'Only at noon', 'Every other day'], 6),
    blank(3, 'and bread and meat in the _____', 'evening', 6),

    mc(1, 'Why did the brook dry up?', ['There was no rain in the land', 'Ahab diverted it', 'The ravens stopped coming', 'Elijah crossed the Jordan'], 7),
    blank(2, 'And after a while the brook _____ up', 'dried', 7),
    word(2, 'What was absent from the land?', 'rain', 7),
    tf(3, 'The brook dried up because there was no rain in the land.', true, 7),
    mc(2, 'What consequence of the drought affected Elijah’s shelter?', ['Cherith dried up', 'Zarephath’s gate closed', 'The Jordan flooded', 'Samaria burned'], 7),
    blank(3, 'because there was no _____ in the land.', 'rain', 7),

    mc(1, 'What came to Elijah after the brook dried?', ['The word of the LORD', 'A message from Ahab', 'A raven', 'The widow’s son'], 8),
    blank(2, 'Then the word of the LORD _____ to him', 'came', 8),
    word(1, 'Whose word came?', 'LORD', 8, ['the LORD', 'the LORD’s', "LORD's"]),
    tf(3, 'Elijah received no further direction after Cherith dried.', false, 8, 'The word of the LORD came to him again.'),
    mc(2, 'What connected Elijah’s move from Cherith to his next location?', ['A new word from the LORD', 'A royal decree', 'A famine council', 'A dream from Ahab'], 8),
    blank(3, 'Then the _____ of the LORD came to him', 'word', 8),

    mc(1, 'Where was Elijah told to go next?', ['Zarephath', 'Tirzah', 'Bethel', 'Gibbethon'], 9),
    blank(2, 'Arise, go to Zar’ephath, which belongs to _____.', 'Sidon', 9),
    sa(1, 'Whom had the LORD commanded to feed Elijah there?', 'a widow', 9, ['widow']),
    tf(3, 'Zarephath belonged to Judah.', false, 9, 'Zarephath belonged to Sidon.'),
    mc(2, 'What was Elijah to do in Zarephath?', ['Dwell there', 'Anoint its king', 'Build an altar', 'Hide beside a brook'], 9),
    blank(3, 'I have commanded a _____ there to feed you.', 'widow', 9),

    mc(1, 'What was the widow doing when Elijah saw her?', ['Gathering sticks', 'Baking bread', 'Drawing oil', 'Feeding her son'], 10),
    blank(2, 'when he came to the _____ of the city', 'gate', 10),
    sa(1, 'What did Elijah first ask her to bring?', 'a little water', 10, ['water']),
    tf(3, 'Elijah first met the widow inside her house.', false, 10, 'He met her at the city gate.'),
    mc(2, 'In what did Elijah ask the widow to carry water?', ['A vessel', 'A cruse', 'A jar of meal', 'A cup of gold'], 10),
    blank(3, 'behold, a widow was there gathering _____.', 'sticks', 10),

    mc(1, 'What additional item did Elijah request?', ['A morsel of bread', 'A jar of honey', 'A piece of meat', 'A cake of raisins'], 11),
    blank(2, 'Bring me a morsel of _____ in your hand.', 'bread', 11),
    sa(2, 'When did Elijah call after her?', 'as she was going to bring the water', 11, ['as she was going to bring it']),
    tf(3, 'The widow refused to fetch water before Elijah asked for bread.', false, 11, 'She was going to bring water when he called for bread.'),
    mc(2, 'How was the requested bread to be brought?', ['In her hand', 'In a basket', 'On a plate', 'In a jar'], 11),
    blank(3, 'And as she was going to _____ it', 'bring', 11),

    mc(2, 'What food supplies did the widow still have?', ['A handful of meal and a little oil', 'Ten loaves and honey', 'Bread and meat', 'Fish and flour'], 12),
    blank(3, 'only a handful of meal in a jar, and a little oil in a _____.', 'cruse', 12),
    sa(1, 'How many sticks was she gathering?', 'a couple', 12, ['two', '2']),
    tf(2, 'The widow expected that she and her son would eat and then die.', true, 12),
    mc(1, 'For whom was the widow preparing her final meal?', ['Herself and her son', 'Elijah and Ahab', 'Her whole household', 'The ravens'], 12),
    blank(2, 'And she said, "As the LORD your God lives, I have nothing _____, only a handful of meal in a jar, and a little oil in a cruse;', 'baked', 12),

    mc(1, 'What did Elijah first tell the widow?', ['Fear not', 'Leave Zarephath', 'Call your son', 'Gather more oil'], 13),
    blank(2, 'but first make me a little _____ of it and bring it to me', 'cake', 13),
    sa(2, 'For whom was she to make food afterward?', 'herself and her son', 13, ['yourself and your son']),
    tf(3, 'Elijah told her to feed her son before making anything for him.', false, 13, 'He told her first to make him a little cake.'),
    mc(2, 'In what order did Elijah tell the widow to prepare food?', ['Make Elijah a little cake first, then make food for herself and her son', 'Feed her son first, then use whatever remained to make Elijah a cake', 'Save all the meal and oil until the following day before baking anything', 'Divide the meal among her neighbors before preparing food for her household'], 13),
    blank(3, 'and _____ make for yourself and your son.', 'afterward', 13),

    mc(1, 'What did the LORD promise about the jar of meal?', ['It would not be spent', 'It would become gold', 'It would last one day', 'It would be carried to Samaria'], 14),
    blank(2, 'and the cruse of oil shall not _____', 'fail', 14),
    sa(2, 'Until what event would the supplies last?', 'until the LORD sends rain', 14, ['the LORD sends rain', 'rain']),
    tf(3, 'The promise lasted only until Elijah finished eating.', false, 14, 'It lasted until the LORD sent rain upon the earth.'),
    mc(2, 'Which two supplies would continue until the LORD sent rain?', ['The meal in the jar and the oil in the cruse', 'The bread and meat delivered by the ravens', 'The water in the brook and the honey in the jar', 'The gathered sticks and the flour kept for baking'], 14),
    blank(3, 'The jar of meal shall not be _____', 'spent', 14),

    mc(1, 'How did the widow respond to Elijah?', ['She went and did as he said', 'She sent him away', 'She appealed to Ahab', 'She hid the meal'], 15),
    blank(2, 'and she, and he, and her household ate for many _____.', 'days', 15),
    sa(1, 'Who ate with the widow and Elijah?', 'her household', 15),
    tf(3, 'The food sustained only Elijah and not the widow’s household.', false, 15, 'She, Elijah, and her household ate for many days.'),
    mc(2, 'For how long did the household eat?', ['Many days', 'One evening', 'Seven days exactly', 'Until the next morning'], 15),
    blank(3, 'And she went and _____ as Eli\'jah said; and she, and he, and her household ate for many days.', 'did', 15),

    mc(1, 'What happened to the widow’s jar of meal?', ['It was not spent', 'It spoiled', 'It was stolen', 'It became empty that night'], 16),
    blank(2, 'neither did the cruse of oil _____', 'fail', 16),
    word(2, 'Through whom had the LORD spoken this word?', 'Elijah', 16, ["Eli'jah"]),
    tf(3, 'The oil failed before the meal was spent.', false, 16, 'Neither the meal was spent nor the oil failed.'),
    mc(2, 'How was the LORD’s promise through Elijah fulfilled?', ['The meal was not spent and the oil did not fail', 'Rain fell immediately after the widow baked the first cake', 'Ahab sent enough provisions to sustain the entire household', 'Ravens filled the widow’s house with bread and meat each day'], 16),
    blank(3, 'The jar of meal was not _____', 'spent', 16),

    mc(1, 'What happened to the widow’s son?', ['He became severely ill and stopped breathing', 'He left for Sidon', 'He recovered from a mild fever', 'He went to find Elijah'], 17),
    blank(2, 'and his illness was so severe that there was no _____ left in him.', 'breath', 17),
    sa(1, 'Who was the mistress of the house?', 'the woman', 17, ['the widow']),
    tf(3, 'The son’s illness was mild.', false, 17, 'It was so severe that no breath remained in him.'),
    mc(2, 'What detail shows the illness ended in death?', ['No breath was left in him', 'He lay on Elijah’s bed', 'His mother gathered sticks', 'The oil stopped flowing'], 17),
    blank(3, 'the son of the woman, the mistress of the house, became _____.', 'ill', 17),

    mc(1, 'What did the widow accuse Elijah of causing?', ['The death of her son', 'The drought in Sidon', 'The loss of her oil', 'Ahab’s anger'], 18),
    blank(3, 'You have come to me to bring my sin to _____', 'remembrance', 18),
    sa(2, 'What did the widow call Elijah?', 'man of God', 18),
    tf(2, 'The widow believed Elijah had come to reward her.', false, 18, 'She accused him of recalling her sin and causing her son’s death.'),

    mc(1, 'Where did Elijah carry the child?', ['To the upper chamber', 'To the city gate', 'To the brook Cherith', 'To Ahab’s house'], 19),
    blank(2, 'and laid him upon his own _____.', 'bed', 19),
    sa(1, 'From where did Elijah take the child?', 'her bosom', 19, ['the mother’s bosom']),
    tf(3, 'Elijah left the child in his mother’s arms.', false, 19, 'He carried him to the upper chamber and laid him on his bed.'),

    mc(2, 'To whom did Elijah cry about the widow’s calamity?', ['The LORD his God', 'Ahab', 'The king of Sidon', 'The widow’s household'], 20),
    blank(3, 'hast thou brought _____ even upon the widow with whom I sojourn', 'calamity', 20),
    sa(1, 'With whom was Elijah sojourning?', 'the widow', 20),
    tf(2, 'Elijah asked whether the LORD had slain the widow’s son.', true, 20),

    mc(1, 'How many times did Elijah stretch himself upon the child?', ['Three times', 'Seven times', 'Once', 'Twice'], 21),
    blank(3, 'let this child’s _____ come into him again.', 'soul', 21),
    sa(1, 'What did Elijah ask to return to the child?', 'his soul', 21, ['soul', 'the child’s soul']),
    tf(2, 'Elijah stretched himself on the child only once.', false, 21, 'He did so three times.'),

    mc(1, 'How did the LORD respond to Elijah’s cry?', ['He hearkened to Elijah, and the child’s soul returned so that he revived', 'He sent rain over Zarephath but left the child without breath', 'He sent ravens to bring food to the widow’s household', 'He remained silent while Elijah returned the child to his mother'], 22),
    blank(2, 'and the soul of the child came into him again, and he _____.', 'revived', 22),
    word(2, 'To whose voice did the LORD hearken?', 'Elijah’s', 22, ['Elijah', "Eli'jah"]),
    tf(3, 'The child’s soul returned, but he did not revive.', false, 22, 'His soul returned and he revived.'),

    mc(1, 'To whom did Elijah deliver the living child?', ['His mother', 'Ahab', 'The household servants', 'The elders of Sidon'], 23),
    blank(3, 'And Eli\'jah took the child, and brought him down from the upper chamber into the house, and delivered him to his mother; and Eli\'jah said, "See, your son _____."', 'lives', 23),
    sa(1, 'From where did Elijah bring the child down?', 'the upper chamber', 23),
    tf(2, 'Elijah told the mother that her son lived.', true, 23),

    mc(1, 'What did the woman now know about Elijah?', ['He was a man of God', 'He was king of Israel', 'He was from Sidon', 'He was Ahab’s servant'], 24),
    blank(2, 'and that the word of the LORD in your mouth is _____.', 'truth', 24),
    sa(2, 'What did she say was truth?', 'the word of the LORD in Elijah’s mouth', 24, ['the word of the LORD']),
    tf(3, 'After her son revived, the woman still denied Elijah was a man of God.', false, 24, 'She said she now knew he was a man of God.'),

    word(3, 'In which direction was Elijah told to turn?', 'eastward', 3),
    tf(1, 'The LORD had commanded ravens to feed Elijah at Cherith.', true, 4),
    mc(3, 'What did the ravens bring Elijah each day?', ['Bread and meat in both the morning and the evening', 'A jar of meal and a cruse of oil each morning', 'Bread in the morning but nothing in the evening', 'Meat at noon and water carried from the Jordan'], 6),
    sa(3, 'What happened to Cherith after a while?', 'it dried up', 7, ['dried up']),
    tf(1, 'The word of the LORD came to Elijah after the brook dried.', true, 8),
    mc(3, 'Where exactly did Elijah encounter the widow?', ['At the gate of Zarephath', 'Beside the brook Cherith', 'Inside her upper chamber', 'At Ahab’s palace'], 10),
    word(3, 'What morsel did Elijah request as the widow went for water?', 'bread', 11, ['a morsel of bread']),
    tf(1, 'The widow had only a handful of meal and a little oil.', true, 12),
    mc(3, 'Until what event would the meal and oil continue?', ['The LORD sending rain upon the earth', 'Elijah leaving the widow’s household', 'The widow baking one cake for Elijah', 'The widow’s son becoming severely ill'], 14),
    sa(3, 'For how long did the widow’s household eat?', 'many days', 15),
    tf(1, 'The continuing meal and oil fulfilled the LORD’s word through Elijah.', true, 16),
    mc(3, 'What did the widow say Elijah had brought to remembrance?', ['Her sin', 'Ahab’s decree', 'The drought', 'Her promise'], 18),
    sa(3, 'On whose bed did Elijah lay the child?', 'his own bed', 19, ['Elijah’s bed']),
    tf(1, 'Elijah cried to the LORD about the death of the widow’s son.', true, 20),
    blank(1, 'Then he stretched himself upon the child _____ times', 'three', 21, ['3']),
    mc(3, 'What two actions did Elijah repeat three times?', ['He stretched upon the child and cried to the LORD', 'He carried the child downstairs and back', 'He poured meal and oil over him', 'He called the widow and Ahab'], 21),
    mc(2, 'What returned to the child before he revived?', ['His soul', 'His breath alone', 'His voice', 'His strength'], 22),
    sa(3, 'What did Elijah say after returning the child?', 'See, your son lives', 23, ['your son lives']),
    tf(1, 'The woman declared that the LORD’s word in Elijah’s mouth was truth.', true, 24),
  ],
}

export default bank
