// 1 Kings 20 — quiz bank (RSV). Four verse-anchored forms per verse.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: "1 Kings",
  chapter: 20,
  tag: "quiz-v2-1kings-20",
  rows: [
    blank(2, "_____ the king of Syria gathered all his army together; thirty-two kings were", "Ben-ha’dad", 1, ["ben-hadad"]),
    mc(3, "Which word correctly completes this RSV wording: “_____ the king of Syria gathered all his army together; thirty-two kings were”", ["Ben-ha’dad", "Because", "Damascus", "Strike"], 1),
    word(1, "In verse 1, what word completes this phrase: “_____ the king of Syria gathered all his army together; thirty-two kings were”?", "Ben-ha’dad", 1, ["ben-hadad"]),
    tf(2, "The RSV states: “Ben-ha’dad the king of Syria gathered all his army together; thirty-two kings were with him, and horses and chariots; and he went up and besieged Sama’ria, and fought against it.”", true, 1),
    blank(3, "messengers into the city to Ahab king of Israel, and said to him, \"Thus says _____:", "Ben-ha’dad", 2, ["ben-hadad"]),
    mc(1, "Which word correctly completes this RSV wording: “messengers into the city to Ahab king of Israel, and said to him, \"Thus says _____:”", ["Ben-ha’dad", "Behold", "Syrians", "Aphek"], 2),
    word(2, "In verse 2, what word completes this phrase: “messengers into the city to Ahab king of Israel, and said to him, \"Thus says _____:”?", "Ben-ha’dad", 2, ["ben-hadad"]),
    tf(3, "The RSV does not state: “And he sent messengers into the city to Ahab king of Israel, and said to him, \"Thus says Ben-ha’dad:”", false, 2, "The quoted wording is the RSV text of this verse."),
    blank(1, "`Your silver and your gold are mine; your fairest wives and _____ also are mine.’\"", "children", 3, ["children"]),
    mc(2, "Which word correctly completes this RSV wording: “`Your silver and your gold are mine; your fairest wives and _____ also are mine.’\"”", ["children", "wives", "about", "called"], 3),
    word(3, "In verse 3, what word completes this phrase: “`Your silver and your gold are mine; your fairest wives and _____ also are mine.’\"”?", "children", 3, ["children"]),
    tf(1, "The RSV states: “`Your silver and your gold are mine; your fairest wives and children also are mine.’\"”", true, 3),
    blank(2, "And the king of _____ answered, \"As you say, my lord, O king, I am yours, and all that I have.\"", "Israel", 4, ["israel"]),
    mc(3, "Which word correctly completes this RSV wording: “And the king of _____ answered, \"As you say, my lord, O king, I am yours, and all that I have.\"”", ["Israel", "Syrians", "Ahab", "Pray"], 4),
    word(1, "In verse 4, what word completes this phrase: “And the king of _____ answered, \"As you say, my lord, O king, I am yours, and all that I have.\"”?", "Israel", 4, ["israel"]),
    tf(2, "The RSV does not state: “And the king of Israel answered, \"As you say, my lord, O king, I am yours, and all that I have.\"”", false, 4, "The quoted wording is the RSV text of this verse."),
    blank(3, "The messengers came again, and said, \"Thus says _____: `I sent to you, saying, \"Deliver to me your silver and your gold, your", "Ben-ha’dad", 5, ["ben-hadad"]),
    mc(1, "Which word correctly completes this RSV wording: “The messengers came again, and said, \"Thus says _____: `I sent to you, saying, \"Deliver to me your silver and your gold, your”", ["Ben-ha’dad", "Syrians", "Aphek", "Because"], 5),
    word(2, "In verse 5, what word completes this phrase: “The messengers came again, and said, \"Thus says _____: `I sent to you, saying, \"Deliver to me your silver and your gold, your”?", "Ben-ha’dad", 5, ["ben-hadad"]),
    tf(3, "The RSV states: “The messengers came again, and said, \"Thus says Ben-ha’dad: `I sent to you, saying, \"Deliver to me your silver and your gold, your wives and your children\";”", true, 5),
    blank(1, "_____ I will send my servants to you tomorrow about this time, and they shall", "nevertheless", 6, ["nevertheless"]),
    mc(2, "Which word correctly completes this RSV wording: “_____ I will send my servants to you tomorrow about this time, and they shall”", ["nevertheless", "yourself", "opposite", "watching"], 6),
    word(3, "In verse 6, what word completes this phrase: “_____ I will send my servants to you tomorrow about this time, and they shall”?", "nevertheless", 6, ["nevertheless"]),
    tf(1, "The RSV does not state: “nevertheless I will send my servants to you tomorrow about this time, and they shall search your house and the houses of your servants, and lay hands on whatever pleases them, and take it away.’\"”", false, 6, "The quoted wording is the RSV text of this verse."),
    blank(2, "Then the king of _____ called all the elders of the land, and said, \"Mark, now, and see how this", "Israel", 7, ["israel"]),
    mc(3, "Which word correctly completes this RSV wording: “Then the king of _____ called all the elders of the land, and said, \"Mark, now, and see how this”", ["Israel", "Because", "Mark", "Keep"], 7),
    word(1, "In verse 7, what word completes this phrase: “Then the king of _____ called all the elders of the land, and said, \"Mark, now, and see how this”?", "Israel", 7, ["israel"]),
    tf(2, "The RSV states: “Then the king of Israel called all the elders of the land, and said, \"Mark, now, and see how this man is seeking trouble; for he sent to me for my wives and my children, and for my silver and my gold, and I did not refuse him.\"”", true, 7),
    blank(3, "And all the elders and all the people said to him, \"Do not heed or _____.\"", "consent", 8, ["consent"]),
    mc(1, "Which word correctly completes this RSV wording: “And all the elders and all the people said to him, \"Do not heed or _____.\"”", ["consent", "cannot", "armor", "prophet"], 8),
    word(2, "In verse 8, what word completes this phrase: “And all the elders and all the people said to him, \"Do not heed or _____.\"”?", "consent", 8, ["consent"]),
    tf(3, "The RSV does not state: “And all the elders and all the people said to him, \"Do not heed or consent.\"”", false, 8, "The quoted wording is the RSV text of this verse."),
    blank(1, "So he said to the messengers of _____, \"Tell my lord the king, `All that you first demanded of your servant", "Ben-ha’dad", 9, ["ben-hadad"]),
    mc(2, "Which word correctly completes this RSV wording: “So he said to the messengers of _____, \"Tell my lord the king, `All that you first demanded of your servant”", ["Ben-ha’dad", "Deliver", "Behold", "Syrians"], 9),
    word(3, "In verse 9, what word completes this phrase: “So he said to the messengers of _____, \"Tell my lord the king, `All that you first demanded of your servant”?", "Ben-ha’dad", 9, ["ben-hadad"]),
    tf(1, "The RSV states: “So he said to the messengers of Ben-ha’dad, \"Tell my lord the king, `All that you first demanded of your servant I will do; but this thing I cannot do.’\" And the messengers departed and brought him word again.”", true, 9),
    blank(2, "_____ sent to him and said, \"The gods do so to me, and more also, if the dust", "Ben-ha’dad", 10, ["ben-hadad"]),
    mc(3, "Which word correctly completes this RSV wording: “_____ sent to him and said, \"The gods do so to me, and more also, if the dust”", ["Ben-ha’dad", "Syria", "Sama’ria", "Israel"], 10),
    word(1, "In verse 10, what word completes this phrase: “_____ sent to him and said, \"The gods do so to me, and more also, if the dust”?", "Ben-ha’dad", 10, ["ben-hadad"]),
    tf(2, "The RSV does not state: “Ben-ha’dad sent to him and said, \"The gods do so to me, and more also, if the dust of Sama’ria shall suffice for handfuls for all the people who follow me.\"”", false, 10, "The quoted wording is the RSV text of this verse."),
    blank(3, "And the king of _____ answered, \"Tell him, `Let not him that girds on his armor boast himself", "Israel", 11, ["israel"]),
    mc(1, "Which word correctly completes this RSV wording: “And the king of _____ answered, \"Tell him, `Let not him that girds on his armor boast himself”", ["Israel", "Deliver", "Strike", "Behold"], 11),
    word(2, "In verse 11, what word completes this phrase: “And the king of _____ answered, \"Tell him, `Let not him that girds on his armor boast himself”?", "Israel", 11, ["israel"]),
    tf(3, "The RSV states: “And the king of Israel answered, \"Tell him, `Let not him that girds on his armor boast himself as he that puts it off.’\"”", true, 11),
    blank(1, "When _____ heard this message as he was drinking with the kings in the booths, he", "Ben-ha’dad", 12, ["ben-hadad"]),
    mc(2, "Which word correctly completes this RSV wording: “When _____ heard this message as he was drinking with the kings in the booths, he”", ["Ben-ha’dad", "Behold", "Syrians", "Aphek"], 12),
    word(3, "In verse 12, what word completes this phrase: “When _____ heard this message as he was drinking with the kings in the booths, he”?", "Ben-ha’dad", 12, ["ben-hadad"]),
    tf(1, "The RSV does not state: “When Ben-ha’dad heard this message as he was drinking with the kings in the booths, he said to his men, \"Take your positions.\" And they took their positions against the city.”", false, 12, "The quoted wording is the RSV text of this verse."),
    blank(2, "And behold, a prophet came near to Ahab king of _____ and said, \"Thus says the LORD, Have you seen all this great multitude?", "Israel", 13, ["israel"]),
    mc(3, "Which word correctly completes this RSV wording: “And behold, a prophet came near to Ahab king of _____ and said, \"Thus says the LORD, Have you seen all this great multitude?”", ["Israel", "Syria", "Aphek", "Deliver"], 13),
    word(1, "In verse 13, what word completes this phrase: “And behold, a prophet came near to Ahab king of _____ and said, \"Thus says the LORD, Have you seen all this great multitude?”?", "Israel", 13, ["israel"]),
    tf(2, "The RSV states: “And behold, a prophet came near to Ahab king of Israel and said, \"Thus says the LORD, Have you seen all this great multitude? Behold, I will give it into your hand this day; and you shall know that I am the LORD.\"”", true, 13),
    blank(3, "And _____ said, \"By whom?\" He said, \"Thus says the LORD, By the servants of the", "Ahab", 14, ["ahab"]),
    mc(1, "Which word correctly completes this RSV wording: “And _____ said, \"By whom?\" He said, \"Thus says the LORD, By the servants of the”", ["Ahab", "Pray", "Take", "Sama’ria"], 14),
    word(2, "In verse 14, what word completes this phrase: “And _____ said, \"By whom?\" He said, \"Thus says the LORD, By the servants of the”?", "Ahab", 14, ["ahab"]),
    tf(3, "The RSV does not state: “And Ahab said, \"By whom?\" He said, \"Thus says the LORD, By the servants of the governors of the districts.\" Then he said, \"Who shall begin the battle?\" He answered, \"You.\"”", false, 14, "The quoted wording is the RSV text of this verse."),
    blank(1, "hundred and thirty-two; and after them he mustered all the people of _____, seven thousand.", "Israel", 15, ["israel"]),
    mc(2, "Which word correctly completes this RSV wording: “hundred and thirty-two; and after them he mustered all the people of _____, seven thousand.”", ["Israel", "Damascus", "Take", "Syria"], 15),
    word(3, "In verse 15, what word completes this phrase: “hundred and thirty-two; and after them he mustered all the people of _____, seven thousand.”?", "Israel", 15, ["israel"]),
    tf(1, "The RSV states: “Then he mustered the servants of the governors of the districts, and they were two hundred and thirty-two; and after them he mustered all the people of Israel, seven thousand.”", true, 15),
    blank(2, "And they went out at noon, while _____ was drinking himself drunk in the booths, he and the thirty-two kings", "Ben-ha’dad", 16, ["ben-hadad"]),
    mc(3, "Which word correctly completes this RSV wording: “And they went out at noon, while _____ was drinking himself drunk in the booths, he and the thirty-two kings”", ["Ben-ha’dad", "Israel", "Deliver", "Behold"], 16),
    word(1, "In verse 16, what word completes this phrase: “And they went out at noon, while _____ was drinking himself drunk in the booths, he and the thirty-two kings”?", "Ben-ha’dad", 16, ["ben-hadad"]),
    tf(2, "The RSV does not state: “And they went out at noon, while Ben-ha’dad was drinking himself drunk in the booths, he and the thirty-two kings who helped him.”", false, 16, "The quoted wording is the RSV text of this verse."),
    blank(3, "The servants of the governors of the districts went out first. And _____ sent out scouts, and they reported to him, \"Men are coming out from Sama’ria.\"", "Ben-ha’dad", 17, ["ben-hadad"]),
    mc(1, "Which word correctly completes this RSV wording: “The servants of the governors of the districts went out first. And _____ sent out scouts, and they reported to him, \"Men are coming out from Sama’ria.\"”", ["Ben-ha’dad", "Strike", "Syria", "Sama’ria"], 17),
    word(2, "In verse 17, what word completes this phrase: “The servants of the governors of the districts went out first. And _____ sent out scouts, and they reported to him, \"Men are coming out from Sama’ria.\"”?", "Ben-ha’dad", 17, ["ben-hadad"]),
    tf(3, "The RSV states: “The servants of the governors of the districts went out first. And Ben-ha’dad sent out scouts, and they reported to him, \"Men are coming out from Sama’ria.\"”", true, 17),
    blank(1, "He said, \"If they have come out for _____, take them alive; or if they have come out for war, take them alive.\"", "peace", 18, ["peace"]),
    mc(2, "Which word correctly completes this RSV wording: “He said, \"If they have come out for _____, take them alive; or if they have come out for war, take them alive.\"”", ["peace", "places", "goats", "foot"], 18),
    word(3, "In verse 18, what word completes this phrase: “He said, \"If they have come out for _____, take them alive; or if they have come out for war, take them alive.\"”?", "peace", 18, ["peace"]),
    tf(1, "The RSV does not state: “He said, \"If they have come out for peace, take them alive; or if they have come out for war, take them alive.\"”", false, 18, "The quoted wording is the RSV text of this verse."),
    blank(2, "So these went out of the city, the servants of the _____ of the districts, and the army which followed them.", "governors", 19, ["governors"]),
    mc(3, "Which word correctly completes this RSV wording: “So these went out of the city, the servants of the _____ of the districts, and the army which followed them.”", ["governors", "voice", "opposite", "twenty-seven"], 19),
    word(1, "In verse 19, what word completes this phrase: “So these went out of the city, the servants of the _____ of the districts, and the army which followed them.”?", "governors", 19, ["governors"]),
    tf(2, "The RSV states: “So these went out of the city, the servants of the governors of the districts, and the army which followed them.”", true, 19),
    blank(3, "And each killed his man; the Syrians fled and Israel pursued them, but _____ king of Syria escaped on a horse with horsemen.", "Ben-ha’dad", 20, ["ben-hadad"]),
    mc(1, "Which word correctly completes this RSV wording: “And each killed his man; the Syrians fled and Israel pursued them, but _____ king of Syria escaped on a horse with horsemen.”", ["Ben-ha’dad", "Syria", "Sama’ria", "Israel"], 20),
    word(2, "In verse 20, what word completes this phrase: “And each killed his man; the Syrians fled and Israel pursued them, but _____ king of Syria escaped on a horse with horsemen.”?", "Ben-ha’dad", 20, ["ben-hadad"]),
    tf(3, "The RSV does not state: “And each killed his man; the Syrians fled and Israel pursued them, but Ben-ha’dad king of Syria escaped on a horse with horsemen.”", false, 20, "The quoted wording is the RSV text of this verse."),
    blank(1, "Israel went out, and captured the horses and chariots, and killed the _____ with a great slaughter.", "Syrians", 21, ["syrians"]),
    mc(2, "Which word correctly completes this RSV wording: “Israel went out, and captured the horses and chariots, and killed the _____ with a great slaughter.”", ["Syrians", "Ahab", "Pray", "Mark"], 21),
    word(3, "In verse 21, what word completes this phrase: “Israel went out, and captured the horses and chariots, and killed the _____ with a great slaughter.”?", "Syrians", 21, ["syrians"]),
    tf(1, "The RSV states: “And the king of Israel went out, and captured the horses and chariots, and killed the Syrians with a great slaughter.”", true, 21),
    blank(2, "Then the prophet came near to the king of _____, and said to him, \"Come, strengthen yourself, and consider well what you", "Israel", 22, ["israel"]),
    mc(3, "Which word correctly completes this RSV wording: “Then the prophet came near to the king of _____, and said to him, \"Come, strengthen yourself, and consider well what you”", ["Israel", "Syrians", "Ahab", "Pray"], 22),
    word(1, "In verse 22, what word completes this phrase: “Then the prophet came near to the king of _____, and said to him, \"Come, strengthen yourself, and consider well what you”?", "Israel", 22, ["israel"]),
    tf(2, "The RSV does not state: “Then the prophet came near to the king of Israel, and said to him, \"Come, strengthen yourself, and consider well what you have to do; for in the spring the king of Syria will come up against you.\"”", false, 22, "The quoted wording is the RSV text of this verse."),
    blank(3, "And the servants of the king of _____ said to him, \"Their gods are gods of the hills, and so they were stronger", "Syria", 23, ["syria"]),
    mc(1, "Which word correctly completes this RSV wording: “And the servants of the king of _____ said to him, \"Their gods are gods of the hills, and so they were stronger”", ["Syria", "Keep", "Syrians", "Israel"], 23),
    word(2, "In verse 23, what word completes this phrase: “And the servants of the king of _____ said to him, \"Their gods are gods of the hills, and so they were stronger”?", "Syria", 23, ["syria"]),
    tf(3, "The RSV states: “And the servants of the king of Syria said to him, \"Their gods are gods of the hills, and so they were stronger than we; but let us fight against them in the plain, and surely we shall be stronger than they.”", true, 23),
    blank(1, "And do this: remove the kings, each from his post, and put _____ in their places;", "commanders", 24, ["commanders"]),
    mc(2, "Which word correctly completes this RSV wording: “And do this: remove the kings, each from his post, and put _____ in their places;”", ["commanders", "resentful", "messengers", "tomorrow"], 24),
    word(3, "In verse 24, what word completes this phrase: “And do this: remove the kings, each from his post, and put _____ in their places;”?", "commanders", 24, ["commanders"]),
    tf(1, "The RSV does not state: “And do this: remove the kings, each from his post, and put commanders in their places;”", false, 24, "The quoted wording is the RSV text of this verse."),
    blank(2, "them in the plain, and surely we shall be stronger than they.\" And he _____ to their voice, and did so.", "hearkened", 25, ["hearkened"]),
    mc(3, "Which word correctly completes this RSV wording: “them in the plain, and surely we shall be stronger than they.\" And he _____ to their voice, and did so.”", ["hearkened", "bring", "certain", "lion"], 25),
    word(1, "In verse 25, what word completes this phrase: “them in the plain, and surely we shall be stronger than they.\" And he _____ to their voice, and did so.”?", "hearkened", 25, ["hearkened"]),
    tf(2, "The RSV states: “and muster an army like the army that you have lost, horse for horse, and chariot for chariot; then we will fight against them in the plain, and surely we shall be stronger than they.\" And he hearkened to their voice, and did so.”", true, 25),
    blank(3, "In the spring _____ mustered the Syrians, and went up to Aphek, to fight against Israel.", "Ben-ha’dad", 26, ["ben-hadad"]),
    mc(1, "Which word correctly completes this RSV wording: “In the spring _____ mustered the Syrians, and went up to Aphek, to fight against Israel.”", ["Ben-ha’dad", "Israel", "Deliver", "Behold"], 26),
    word(2, "In verse 26, what word completes this phrase: “In the spring _____ mustered the Syrians, and went up to Aphek, to fight against Israel.”?", "Ben-ha’dad", 26, ["ben-hadad"]),
    tf(3, "The RSV does not state: “In the spring Ben-ha’dad mustered the Syrians, and went up to Aphek, to fight against Israel.”", false, 26, "The quoted wording is the RSV text of this verse."),
    blank(1, "Israel encamped before them like two little flocks of goats, but the _____ filled the country.", "Syrians", 27, ["syrians"]),
    mc(2, "Which word correctly completes this RSV wording: “Israel encamped before them like two little flocks of goats, but the _____ filled the country.”", ["Syrians", "Take", "Sama’ria", "Because"], 27),
    word(3, "In verse 27, what word completes this phrase: “Israel encamped before them like two little flocks of goats, but the _____ filled the country.”?", "Syrians", 27, ["syrians"]),
    tf(1, "The RSV states: “And the people of Israel were mustered, and were provisioned, and went against them; the people of Israel encamped before them like two little flocks of goats, but the Syrians filled the country.”", true, 27),
    blank(2, "of God came near and said to the king of Israel, \"Thus says the LORD, `_____ the Syrians have said, \"The LORD is a god of the hills but he is not a", "Because", 28, ["because"]),
    mc(3, "Which word correctly completes this RSV wording: “of God came near and said to the king of Israel, \"Thus says the LORD, `_____ the Syrians have said, \"The LORD is a god of the hills but he is not a”", ["Because", "Strike", "Take", "Sama’ria"], 28),
    word(1, "In verse 28, what word completes this phrase: “of God came near and said to the king of Israel, \"Thus says the LORD, `_____ the Syrians have said, \"The LORD is a god of the hills but he is not a”?", "Because", 28, ["because"]),
    tf(2, "The RSV does not state: “And a man of God came near and said to the king of Israel, \"Thus says the LORD, `Because the Syrians have said, \"The LORD is a god of the hills but he is not a god of the valleys,\" therefore I will give all this great multitude into your hand, and you shall know that I am the LORD.’\"”", false, 28, "The quoted wording is the RSV text of this verse."),
    blank(3, "seventh day the battle was joined; and the people of Israel smote of the _____ a hundred thousand foot soldiers in one day.", "Syrians", 29, ["syrians"]),
    mc(1, "Which word correctly completes this RSV wording: “seventh day the battle was joined; and the people of Israel smote of the _____ a hundred thousand foot soldiers in one day.”", ["Syrians", "Thus", "Strike", "Take"], 29),
    word(2, "In verse 29, what word completes this phrase: “seventh day the battle was joined; and the people of Israel smote of the _____ a hundred thousand foot soldiers in one day.”?", "Syrians", 29, ["syrians"]),
    tf(3, "The RSV states: “And they encamped opposite one another seven days. Then on the seventh day the battle was joined; and the people of Israel smote of the Syrians a hundred thousand foot soldiers in one day.”", true, 29),
    blank(1, "Aphek; and the wall fell upon twenty-seven thousand men that were left. _____ also fled, and entered an inner chamber in the city.", "Ben-ha’dad", 30, ["ben-hadad"]),
    mc(2, "Which word correctly completes this RSV wording: “Aphek; and the wall fell upon twenty-seven thousand men that were left. _____ also fled, and entered an inner chamber in the city.”", ["Ben-ha’dad", "Syria", "Sama’ria", "Israel"], 30),
    word(3, "In verse 30, what word completes this phrase: “Aphek; and the wall fell upon twenty-seven thousand men that were left. _____ also fled, and entered an inner chamber in the city.”?", "Ben-ha’dad", 30, ["ben-hadad"]),
    tf(1, "The RSV does not state: “And the rest fled into the city of Aphek; and the wall fell upon twenty-seven thousand men that were left. Ben-ha’dad also fled, and entered an inner chamber in the city.”", false, 30, "The quoted wording is the RSV text of this verse."),
    blank(2, "And his servants said to him, \"_____ now, we have heard that the kings of the house of Israel are merciful", "Behold", 31, ["behold"]),
    mc(3, "Which word correctly completes this RSV wording: “And his servants said to him, \"_____ now, we have heard that the kings of the house of Israel are merciful”", ["Behold", "Syria", "Aphek", "Thus"], 31),
    word(1, "In verse 31, what word completes this phrase: “And his servants said to him, \"_____ now, we have heard that the kings of the house of Israel are merciful”?", "Behold", 31, ["behold"]),
    tf(2, "The RSV states: “And his servants said to him, \"Behold now, we have heard that the kings of the house of Israel are merciful kings; let us put sackcloth on our loins and ropes upon our heads, and go out to the king of Israel; perhaps he will spare your life.\"”", true, 31),
    blank(3, "on their heads, and went to the king of Israel and said, \"Your servant _____ says, `Pray, let me live.’\" And he said, \"Does he still live? He is my", "Ben-ha’dad", 32, ["ben-hadad"]),
    mc(1, "Which word correctly completes this RSV wording: “on their heads, and went to the king of Israel and said, \"Your servant _____ says, `Pray, let me live.’\" And he said, \"Does he still live? He is my”", ["Ben-ha’dad", "Behold", "Syrians", "Aphek"], 32),
    word(2, "In verse 32, what word completes this phrase: “on their heads, and went to the king of Israel and said, \"Your servant _____ says, `Pray, let me live.’\" And he said, \"Does he still live? He is my”?", "Ben-ha’dad", 32, ["ben-hadad"]),
    tf(3, "The RSV does not state: “So they girded sackcloth on their loins, and put ropes on their heads, and went to the king of Israel and said, \"Your servant Ben-ha’dad says, `Pray, let me live.’\" And he said, \"Does he still live? He is my brother.\"”", false, 32, "The quoted wording is the RSV text of this verse."),
    blank(1, "omen, and they quickly took it up from him and said, \"Yes, your brother _____.\" Then he said, \"Go and bring him.\" Then Ben-ha’dad came forth to him;", "Ben-ha’dad", 33, ["ben-hadad"]),
    mc(2, "Which word correctly completes this RSV wording: “omen, and they quickly took it up from him and said, \"Yes, your brother _____.\" Then he said, \"Go and bring him.\" Then Ben-ha’dad came forth to him;”", ["Ben-ha’dad", "Sama’ria", "Israel", "Deliver"], 33),
    word(3, "In verse 33, what word completes this phrase: “omen, and they quickly took it up from him and said, \"Yes, your brother _____.\" Then he said, \"Go and bring him.\" Then Ben-ha’dad came forth to him;”?", "Ben-ha’dad", 33, ["ben-hadad"]),
    tf(1, "The RSV states: “Now the men were watching for an omen, and they quickly took it up from him and said, \"Yes, your brother Ben-ha’dad.\" Then he said, \"Go and bring him.\" Then Ben-ha’dad came forth to him; and he caused him to come up into the chariot.”", true, 33),
    blank(2, "And _____ said to him, \"The cities which my father took from your father I will", "Ben-ha’dad", 34, ["ben-hadad"]),
    mc(3, "Which word correctly completes this RSV wording: “And _____ said to him, \"The cities which my father took from your father I will”", ["Ben-ha’dad", "Damascus", "Strike", "Syria"], 34),
    word(1, "In verse 34, what word completes this phrase: “And _____ said to him, \"The cities which my father took from your father I will”?", "Ben-ha’dad", 34, ["ben-hadad"]),
    tf(2, "The RSV does not state: “And Ben-ha’dad said to him, \"The cities which my father took from your father I will restore; and you may establish bazaars for yourself in Damascus, as my father did in Sama’ria.\" And Ahab said, \"I will let you go on these terms.\" So he made a covenant with him and let him go.”", false, 34, "The quoted wording is the RSV text of this verse."),
    blank(3, "sons of the prophets said to his fellow at the command of the LORD, \"_____ me, I pray.\" But the man refused to strike him.", "Strike", 35, ["strike"]),
    mc(1, "Which word correctly completes this RSV wording: “sons of the prophets said to his fellow at the command of the LORD, \"_____ me, I pray.\" But the man refused to strike him.”", ["Strike", "Syrians", "Israel", "Pray"], 35),
    word(2, "In verse 35, what word completes this phrase: “sons of the prophets said to his fellow at the command of the LORD, \"_____ me, I pray.\" But the man refused to strike him.”?", "Strike", 35, ["strike"]),
    tf(3, "The RSV states: “And a certain man of the sons of the prophets said to his fellow at the command of the LORD, \"Strike me, I pray.\" But the man refused to strike him.”", true, 35),
    blank(1, "Then he said to him, \"_____ you have not obeyed the voice of the LORD, behold, as soon as you have", "Because", 36, ["because"]),
    mc(2, "Which word correctly completes this RSV wording: “Then he said to him, \"_____ you have not obeyed the voice of the LORD, behold, as soon as you have”", ["Because", "Ben-ha’dad", "Syrians", "Israel"], 36),
    word(3, "In verse 36, what word completes this phrase: “Then he said to him, \"_____ you have not obeyed the voice of the LORD, behold, as soon as you have”?", "Because", 36, ["because"]),
    tf(1, "The RSV does not state: “Then he said to him, \"Because you have not obeyed the voice of the LORD, behold, as soon as you have gone from me, a lion shall kill you.\" And as soon as he had departed from him, a lion met him and killed him.”", false, 36, "The quoted wording is the RSV text of this verse."),
    blank(2, "Then he found another man, and said, \"_____ me, I pray.\" And the man struck him, smiting and wounding him.", "Strike", 37, ["strike"]),
    mc(3, "Which word correctly completes this RSV wording: “Then he found another man, and said, \"_____ me, I pray.\" And the man struck him, smiting and wounding him.”", ["Strike", "Mark", "Ben-ha’dad", "Syrians"], 37),
    word(1, "In verse 37, what word completes this phrase: “Then he found another man, and said, \"_____ me, I pray.\" And the man struck him, smiting and wounding him.”?", "Strike", 37, ["strike"]),
    tf(2, "The RSV states: “Then he found another man, and said, \"Strike me, I pray.\" And the man struck him, smiting and wounding him.”", true, 37),
    blank(3, "So the prophet departed, and waited for the king by the way, _____ himself with a bandage over his eyes.", "disguising", 38, ["disguising"]),
    mc(1, "Which word correctly completes this RSV wording: “So the prophet departed, and waited for the king by the way, _____ himself with a bandage over his eyes.”", ["disguising", "chariot", "valleys", "chamber"], 38),
    word(2, "In verse 38, what word completes this phrase: “So the prophet departed, and waited for the king by the way, _____ himself with a bandage over his eyes.”?", "disguising", 38, ["disguising"]),
    tf(3, "The RSV does not state: “So the prophet departed, and waited for the king by the way, disguising himself with a bandage over his eyes.”", false, 38, "The quoted wording is the RSV text of this verse."),
    blank(1, "battle; and behold, a soldier turned and brought a man to me, and said, `_____ this man; if by any means he be missing, your life shall be for his life,", "Keep", 39, ["keep"]),
    mc(2, "Which word correctly completes this RSV wording: “battle; and behold, a soldier turned and brought a man to me, and said, `_____ this man; if by any means he be missing, your life shall be for his life,”", ["Keep", "Sama’ria", "Aphek", "Mark"], 39),
    word(3, "In verse 39, what word completes this phrase: “battle; and behold, a soldier turned and brought a man to me, and said, `_____ this man; if by any means he be missing, your life shall be for his life,”?", "Keep", 39, ["keep"]),
    tf(1, "The RSV states: “And as the king passed, he cried to the king and said, \"Your servant went out into the midst of the battle; and behold, a soldier turned and brought a man to me, and said, `Keep this man; if by any means he be missing, your life shall be for his life, or else you shall pay a talent of silver.’”", true, 39),
    blank(2, "And as your servant was busy here and there, he was gone.\" The king of _____ said to him, \"So shall your judgment be; you yourself have decided it.\"", "Israel", 40, ["israel"]),
    mc(3, "Which word correctly completes this RSV wording: “And as your servant was busy here and there, he was gone.\" The king of _____ said to him, \"So shall your judgment be; you yourself have decided it.\"”", ["Israel", "Syrians", "Ahab", "Pray"], 40),
    word(1, "In verse 40, what word completes this phrase: “And as your servant was busy here and there, he was gone.\" The king of _____ said to him, \"So shall your judgment be; you yourself have decided it.\"”?", "Israel", 40, ["israel"]),
    tf(2, "The RSV does not state: “And as your servant was busy here and there, he was gone.\" The king of Israel said to him, \"So shall your judgment be; you yourself have decided it.\"”", false, 40, "The quoted wording is the RSV text of this verse."),
    blank(3, "he made haste to take the bandage away from his eyes; and the king of _____ recognized him as one of the prophets.", "Israel", 41, ["israel"]),
    mc(1, "Which word correctly completes this RSV wording: “he made haste to take the bandage away from his eyes; and the king of _____ recognized him as one of the prophets.”", ["Israel", "Keep", "Syrians", "Ahab"], 41),
    word(2, "In verse 41, what word completes this phrase: “he made haste to take the bandage away from his eyes; and the king of _____ recognized him as one of the prophets.”?", "Israel", 41, ["israel"]),
    tf(3, "The RSV states: “Then he made haste to take the bandage away from his eyes; and the king of Israel recognized him as one of the prophets.”", true, 41),
    blank(1, "And he said to him, \"Thus says the LORD, `_____ you have let go out of your hand the man whom I had devoted to destruction,", "Because", 42, ["because"]),
    mc(2, "Which word correctly completes this RSV wording: “And he said to him, \"Thus says the LORD, `_____ you have let go out of your hand the man whom I had devoted to destruction,”", ["Because", "Deliver", "Keep", "Behold"], 42),
    word(3, "In verse 42, what word completes this phrase: “And he said to him, \"Thus says the LORD, `_____ you have let go out of your hand the man whom I had devoted to destruction,”?", "Because", 42, ["because"]),
    tf(1, "The RSV does not state: “And he said to him, \"Thus says the LORD, `Because you have let go out of your hand the man whom I had devoted to destruction, therefore your life shall go for his life, and your people for his people.’\"”", false, 42, "The quoted wording is the RSV text of this verse."),
    blank(2, "the king of Israel went to his house resentful and sullen, and came to _____.", "Sama’ria", 43, ["samaria"]),
    mc(3, "Which word correctly completes this RSV wording: “the king of Israel went to his house resentful and sullen, and came to _____.”", ["Sama’ria", "Because", "Mark", "Keep"], 43),
    word(1, "In verse 43, what word completes this phrase: “the king of Israel went to his house resentful and sullen, and came to _____.”?", "Sama’ria", 43, ["samaria"]),
    tf(2, "The RSV states: “And the king of Israel went to his house resentful and sullen, and came to Sama’ria.”", true, 43),
    mc(1, "How many kings joined Ben-hadad when he besieged Samaria?", ["Thirty-two", "Twelve", "Twenty-four", "Forty"], 1),
    mc(3, "How did Ahab answer Ben-hadad’s boast about the coming battle?", ["Let not him that girds on his armor boast himself as he that puts it off", "The battle is the LORD’s", "A soft answer turns away wrath", "The race is not to the swift"], 11),
    mc(2, "Why did the Syrians plan to fight Israel in the plain after their first defeat?", ["They believed Israel’s gods were gods of the hills", "Their chariots could not enter Samaria", "They believed Ahab had no infantry", "Ben-hadad refused to fight near a city"], 23),
    mc(2, "How did Ben-hadad’s servants approach Ahab to plead for their king’s life?", ["With sackcloth on their loins and ropes on their heads", "Barefoot with ashes on their heads", "With gifts of gold and silver", "Wearing torn royal garments"], 32),
  ],
};

export default bank;
