// 1 Kings 13 — quiz bank (RSV). Four verse-anchored forms per verse.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: "1 Kings",
  chapter: 13,
  tag: "quiz-v2-1kings-13",
  rows: [
    blank(2, "behold, a man of God came out of Judah by the word of the LORD to Bethel. _____ was standing by the altar to burn incense.", "Jerobo’am", 1, ["jeroboam"]),
    mc(3, "Which word correctly completes this RSV wording: “behold, a man of God came out of Judah by the word of the LORD to Bethel. _____ was standing by the altar to burn incense.”", ["Jerobo’am", "Saddle", "Josi’ah", "Bethel"], 1),
    word(1, "In verse 1, what word completes this phrase: “behold, a man of God came out of Judah by the word of the LORD to Bethel. _____ was standing by the altar to burn incense.”?", "Jerobo’am", 1, ["jeroboam"]),
    tf(2, "The RSV states: “And behold, a man of God came out of Judah by the word of the LORD to Bethel. Jerobo’am was standing by the altar to burn incense.”", true, 1),
    blank(3, "thus says the LORD: `Behold, a son shall be born to the house of David, _____ by name; and he shall sacrifice upon you the priests of the high places", "Josi’ah", 2, ["josiah"]),
    mc(1, "Which word correctly completes this RSV wording: “thus says the LORD: `Behold, a son shall be born to the house of David, _____ by name; and he shall sacrifice upon you the priests of the high places”", ["Josi’ah", "Judah", "Alas", "Bring"], 2),
    word(2, "In verse 2, what word completes this phrase: “thus says the LORD: `Behold, a son shall be born to the house of David, _____ by name; and he shall sacrifice upon you the priests of the high places”?", "Josi’ah", 2, ["josiah"]),
    tf(3, "The RSV does not state: “And the man cried against the altar by the word of the LORD, and said, \"O altar, altar, thus says the LORD: `Behold, a son shall be born to the house of David, Josi’ah by name; and he shall sacrifice upon you the priests of the high places who burn incense upon you, and men’s bones shall be burned upon you.’\"”", false, 2, "The quoted wording is the RSV text of this verse."),
    blank(1, "sign the same day, saying, \"This is the sign that the LORD has spoken: `_____, the altar shall be torn down, and the ashes that are upon it shall be", "Behold", 3, ["behold"]),
    mc(2, "Which word correctly completes this RSV wording: “sign the same day, saying, \"This is the sign that the LORD has spoken: `_____, the altar shall be torn down, and the ashes that are upon it shall be”", ["Behold", "Saddle", "Josi’ah", "Bethel"], 3),
    word(3, "In verse 3, what word completes this phrase: “sign the same day, saying, \"This is the sign that the LORD has spoken: `_____, the altar shall be torn down, and the ashes that are upon it shall be”?", "Behold", 3, ["behold"]),
    tf(1, "The RSV states: “And he gave a sign the same day, saying, \"This is the sign that the LORD has spoken: `Behold, the altar shall be torn down, and the ashes that are upon it shall be poured out.’\"”", true, 3),
    blank(2, "saying of the man of God, which he cried against the altar at Bethel, _____ stretched out his hand from the altar, saying, \"Lay hold of him.\" And", "Jerobo’am", 4, ["jeroboam"]),
    mc(3, "Which word correctly completes this RSV wording: “saying of the man of God, which he cried against the altar at Bethel, _____ stretched out his hand from the altar, saying, \"Lay hold of him.\" And”", ["Jerobo’am", "Judah", "Alas", "Bring"], 4),
    word(1, "In verse 4, what word completes this phrase: “saying of the man of God, which he cried against the altar at Bethel, _____ stretched out his hand from the altar, saying, \"Lay hold of him.\" And”?", "Jerobo’am", 4, ["jeroboam"]),
    tf(2, "The RSV does not state: “And when the king heard the saying of the man of God, which he cried against the altar at Bethel, Jerobo’am stretched out his hand from the altar, saying, \"Lay hold of him.\" And his hand, which he stretched out against him, dried up, so that he could not draw it back to himself.”", false, 4, "The quoted wording is the RSV text of this verse."),
    blank(3, "The altar also was torn down, and the ashes poured out from the altar, _____ to the sign which the man of God had given by the word of the LORD.", "according", 5, ["according"]),
    mc(1, "Which word correctly completes this RSV wording: “The altar also was torn down, and the ashes poured out from the altar, _____ to the sign which the man of God had given by the word of the LORD.”", ["according", "hand", "restored", "bread"], 5),
    word(2, "In verse 5, what word completes this phrase: “The altar also was torn down, and the ashes poured out from the altar, _____ to the sign which the man of God had given by the word of the LORD.”?", "according", 5, ["according"]),
    tf(3, "The RSV states: “The altar also was torn down, and the ashes poured out from the altar, according to the sign which the man of God had given by the word of the LORD.”", true, 5),
    blank(1, "And the king said to the man of God, \"_____ now the favor of the LORD your God, and pray for me, that my hand may", "Entreat", 6, ["entreat"]),
    mc(2, "Which word correctly completes this RSV wording: “And the king said to the man of God, \"_____ now the favor of the LORD your God, and pray for me, that my hand may”", ["Entreat", "Judah", "Alas", "Bring"], 6),
    word(3, "In verse 6, what word completes this phrase: “And the king said to the man of God, \"_____ now the favor of the LORD your God, and pray for me, that my hand may”?", "Entreat", 6, ["entreat"]),
    tf(1, "The RSV does not state: “And the king said to the man of God, \"Entreat now the favor of the LORD your God, and pray for me, that my hand may be restored to me.\" And the man of God entreated the LORD; and the king’s hand was restored to him, and became as it was before.”", false, 6, "The quoted wording is the RSV text of this verse."),
    blank(2, "And the king said to the man of God, \"_____ home with me, and refresh yourself, and I will give you a reward.\"", "Come", 7, ["come"]),
    mc(3, "Which word correctly completes this RSV wording: “And the king said to the man of God, \"_____ home with me, and refresh yourself, and I will give you a reward.\"”", ["Come", "Saddle", "David", "Bethel"], 7),
    word(1, "In verse 7, what word completes this phrase: “And the king said to the man of God, \"_____ home with me, and refresh yourself, and I will give you a reward.\"”?", "Come", 7, ["come"]),
    tf(2, "The RSV states: “And the king said to the man of God, \"Come home with me, and refresh yourself, and I will give you a reward.\"”", true, 7),
    blank(3, "And the man of God said to the king, \"If you give me half your _____, I will not go in with you. And I will not eat bread or drink water in", "house", 8, ["house"]),
    mc(1, "Which word correctly completes this RSV wording: “And the man of God said to the king, \"If you give me half your _____, I will not go in with you. And I will not eat bread or drink water in”", ["house", "half", "prophet", "found"], 8),
    word(2, "In verse 8, what word completes this phrase: “And the man of God said to the king, \"If you give me half your _____, I will not go in with you. And I will not eat bread or drink water in”?", "house", 8, ["house"]),
    tf(3, "The RSV does not state: “And the man of God said to the king, \"If you give me half your house, I will not go in with you. And I will not eat bread or drink water in this place;”", false, 8, "The quoted wording is the RSV text of this verse."),
    blank(1, "for so was it _____ me by the word of the LORD, saying, `You shall neither eat bread, nor", "commanded", 9, ["commanded"]),
    mc(2, "Which word correctly completes this RSV wording: “for so was it _____ me by the word of the LORD, saying, `You shall neither eat bread, nor”", ["commanded", "return", "gone", "table"], 9),
    word(3, "In verse 9, what word completes this phrase: “for so was it _____ me by the word of the LORD, saying, `You shall neither eat bread, nor”?", "commanded", 9, ["commanded"]),
    tf(1, "The RSV states: “for so was it commanded me by the word of the LORD, saying, `You shall neither eat bread, nor drink water, nor return by the way that you came.’\"”", true, 9),
    blank(2, "So he went another way, and did not return by the way that he came to _____.", "Bethel", 10, ["bethel"]),
    mc(3, "Which word correctly completes this RSV wording: “So he went another way, and did not return by the way that he came to _____.”", ["Bethel", "Judah", "Alas", "Bring"], 10),
    word(1, "In verse 10, what word completes this phrase: “So he went another way, and did not return by the way that he came to _____.”?", "Bethel", 10, ["bethel"]),
    tf(2, "The RSV does not state: “So he went another way, and did not return by the way that he came to Bethel.”", false, 10, "The quoted wording is the RSV text of this verse."),
    blank(3, "Now there dwelt an old prophet in _____. And his sons came and told him all that the man of God had done that", "Bethel", 11, ["bethel"]),
    mc(1, "Which word correctly completes this RSV wording: “Now there dwelt an old prophet in _____. And his sons came and told him all that the man of God had done that”", ["Bethel", "Saddle", "Josi’ah", "Jerobo’am"], 11),
    word(2, "In verse 11, what word completes this phrase: “Now there dwelt an old prophet in _____. And his sons came and told him all that the man of God had done that”?", "Bethel", 11, ["bethel"]),
    tf(3, "The RSV states: “Now there dwelt an old prophet in Bethel. And his sons came and told him all that the man of God had done that day in Bethel; the words also which he had spoken to the king, they told to their father.”", true, 11),
    blank(1, "go?\" And his sons showed him the way which the man of God who came from _____ had gone.", "Judah", 12, ["judah"]),
    mc(2, "Which word correctly completes this RSV wording: “go?\" And his sons showed him the way which the man of God who came from _____ had gone.”", ["Judah", "Bethel", "Alas", "Bring"], 12),
    word(3, "In verse 12, what word completes this phrase: “go?\" And his sons showed him the way which the man of God who came from _____ had gone.”?", "Judah", 12, ["judah"]),
    tf(1, "The RSV does not state: “And their father said to them, \"Which way did he go?\" And his sons showed him the way which the man of God who came from Judah had gone.”", false, 12, "The quoted wording is the RSV text of this verse."),
    blank(2, "And he said to his sons, \"_____ the ass for me.\" So they saddled the ass for him and he mounted it.", "Saddle", 13, ["saddle"]),
    mc(3, "Which word correctly completes this RSV wording: “And he said to his sons, \"_____ the ass for me.\" So they saddled the ass for him and he mounted it.”", ["Saddle", "Come", "David", "Bethel"], 13),
    word(1, "In verse 13, what word completes this phrase: “And he said to his sons, \"_____ the ass for me.\" So they saddled the ass for him and he mounted it.”?", "Saddle", 13, ["saddle"]),
    tf(2, "The RSV states: “And he said to his sons, \"Saddle the ass for me.\" So they saddled the ass for him and he mounted it.”", true, 13),
    blank(3, "under an oak; and he said to him, \"Are you the man of God who came from _____?\" And he said, \"I am.\"", "Judah", 14, ["judah"]),
    mc(1, "Which word correctly completes this RSV wording: “under an oak; and he said to him, \"Are you the man of God who came from _____?\" And he said, \"I am.\"”", ["Judah", "Bethel", "Alas", "Bring"], 14),
    word(2, "In verse 14, what word completes this phrase: “under an oak; and he said to him, \"Are you the man of God who came from _____?\" And he said, \"I am.\"”?", "Judah", 14, ["judah"]),
    tf(3, "The RSV does not state: “And he went after the man of God, and found him sitting under an oak; and he said to him, \"Are you the man of God who came from Judah?\" And he said, \"I am.\"”", false, 14, "The quoted wording is the RSV text of this verse."),
    blank(1, "Then he said to him, \"_____ home with me and eat bread.\"", "Come", 15, ["come"]),
    mc(2, "Which word correctly completes this RSV wording: “Then he said to him, \"_____ home with me and eat bread.\"”", ["Come", "Saddle", "David", "Bethel"], 15),
    word(3, "In verse 15, what word completes this phrase: “Then he said to him, \"_____ home with me and eat bread.\"”?", "Come", 15, ["come"]),
    tf(1, "The RSV states: “Then he said to him, \"Come home with me and eat bread.\"”", true, 15),
    blank(2, "And he said, \"I may not return with you, or go in with you; _____ will I eat bread nor drink water with you in this place;", "neither", 16, ["neither"]),
    mc(3, "Which word correctly completes this RSV wording: “And he said, \"I may not return with you, or go in with you; _____ will I eat bread nor drink water with you in this place;”", ["neither", "mourned", "made", "standing"], 16),
    word(1, "In verse 16, what word completes this phrase: “And he said, \"I may not return with you, or go in with you; _____ will I eat bread nor drink water with you in this place;”?", "neither", 16, ["neither"]),
    tf(2, "The RSV does not state: “And he said, \"I may not return with you, or go in with you; neither will I eat bread nor drink water with you in this place;”", false, 16, "The quoted wording is the RSV text of this verse."),
    blank(3, "for it was said to me by the word of the LORD, `You shall _____ eat bread nor drink water there, nor return by the way that you came.’\"", "neither", 17, ["neither"]),
    mc(1, "Which word correctly completes this RSV wording: “for it was said to me by the word of the LORD, `You shall _____ eat bread nor drink water there, nor return by the way that you came.’\"”", ["neither", "pass", "earth", "thus"], 17),
    word(2, "In verse 17, what word completes this phrase: “for it was said to me by the word of the LORD, `You shall _____ eat bread nor drink water there, nor return by the way that you came.’\"”?", "neither", 17, ["neither"]),
    tf(3, "The RSV states: “for it was said to me by the word of the LORD, `You shall neither eat bread nor drink water there, nor return by the way that you came.’\"”", true, 17),
    blank(1, "as you are, and an angel spoke to me by the word of the LORD, saying, `_____ him back with you into your house that he may eat bread and drink water.’\"", "Bring", 18, ["bring"]),
    mc(2, "Which word correctly completes this RSV wording: “as you are, and an angel spoke to me by the word of the LORD, saying, `_____ him back with you into your house that he may eat bread and drink water.’\"”", ["Bring", "Judah", "Alas", "Saddle"], 18),
    word(3, "In verse 18, what word completes this phrase: “as you are, and an angel spoke to me by the word of the LORD, saying, `_____ him back with you into your house that he may eat bread and drink water.’\"”?", "Bring", 18, ["bring"]),
    tf(1, "The RSV does not state: “And he said to him, \"I also am a prophet as you are, and an angel spoke to me by the word of the LORD, saying, `Bring him back with you into your house that he may eat bread and drink water.’\" But he lied to him.”", false, 18, "The quoted wording is the RSV text of this verse."),
    blank(2, "So he went back with him, and ate _____ in his house, and drank water.", "bread", 19, ["bread"]),
    mc(3, "Which word correctly completes this RSV wording: “So he went back with him, and ate _____ in his house, and drank water.”", ["bread", "altar", "name", "saying"], 19),
    word(1, "In verse 19, what word completes this phrase: “So he went back with him, and ate _____ in his house, and drank water.”?", "bread", 19, ["bread"]),
    tf(2, "The RSV states: “So he went back with him, and ate bread in his house, and drank water.”", true, 19),
    blank(3, "And as they sat at the table, the word of the LORD came to the _____ who had brought him back;", "prophet", 20, ["prophet"]),
    mc(1, "Which word correctly completes this RSV wording: “And as they sat at the table, the word of the LORD came to the _____ who had brought him back;”", ["prophet", "said", "men’s", "poured"], 20),
    word(2, "In verse 20, what word completes this phrase: “And as they sat at the table, the word of the LORD came to the _____ who had brought him back;”?", "prophet", 20, ["prophet"]),
    tf(3, "The RSV does not state: “And as they sat at the table, the word of the LORD came to the prophet who had brought him back;”", false, 20, "The quoted wording is the RSV text of this verse."),
    blank(1, "he cried to the man of God who came from Judah, \"Thus says the LORD, `_____ you have disobeyed the word of the LORD, and have not kept the commandment", "Because", 21, ["because"]),
    mc(2, "Which word correctly completes this RSV wording: “he cried to the man of God who came from Judah, \"Thus says the LORD, `_____ you have disobeyed the word of the LORD, and have not kept the commandment”", ["Because", "Come", "David", "Bethel"], 21),
    word(3, "In verse 21, what word completes this phrase: “he cried to the man of God who came from Judah, \"Thus says the LORD, `_____ you have disobeyed the word of the LORD, and have not kept the commandment”?", "Because", 21, ["because"]),
    tf(1, "The RSV states: “and he cried to the man of God who came from Judah, \"Thus says the LORD, `Because you have disobeyed the word of the LORD, and have not kept the commandment which the LORD your God commanded you,”", true, 21),
    blank(2, "bread, and drink no water\"; your body shall not come to the tomb of your _____.’\"", "fathers", 22, ["fathers"]),
    mc(3, "Which word correctly completes this RSV wording: “bread, and drink no water\"; your body shall not come to the tomb of your _____.’\"”", ["fathers", "gave", "stretched", "favor"], 22),
    word(1, "In verse 22, what word completes this phrase: “bread, and drink no water\"; your body shall not come to the tomb of your _____.’\"”?", "fathers", 22, ["fathers"]),
    tf(2, "The RSV does not state: “but have come back, and have eaten bread and drunk water in the place of which he said to you, \"Eat no bread, and drink no water\"; your body shall not come to the tomb of your fathers.’\"”", false, 22, "The quoted wording is the RSV text of this verse."),
    blank(3, "And after he had eaten bread and drunk, he _____ the ass for the prophet whom he had brought back.", "saddled", 23, ["saddled"]),
    mc(1, "Which word correctly completes this RSV wording: “And after he had eaten bread and drunk, he _____ the ass for the prophet whom he had brought back.”", ["saddled", "ashes", "himself", "home"], 23),
    word(2, "In verse 23, what word completes this phrase: “And after he had eaten bread and drunk, he _____ the ass for the prophet whom he had brought back.”?", "saddled", 23, ["saddled"]),
    tf(3, "The RSV states: “And after he had eaten bread and drunk, he saddled the ass for the prophet whom he had brought back.”", true, 23),
    blank(1, "And as he went away a lion met him on the road and _____ him. And his body was thrown in the road, and the ass stood beside it;", "killed", 24, ["killed"]),
    mc(2, "Which word correctly completes this RSV wording: “And as he went away a lion met him on the road and _____ him. And his body was thrown in the road, and the ass stood beside it;”", ["killed", "dried", "entreated", "drink"], 24),
    word(3, "In verse 24, what word completes this phrase: “And as he went away a lion met him on the road and _____ him. And his body was thrown in the road, and the ass stood beside it;”?", "killed", 24, ["killed"]),
    tf(1, "The RSV does not state: “And as he went away a lion met him on the road and killed him. And his body was thrown in the road, and the ass stood beside it; the lion also stood beside the body.”", false, 24, "The quoted wording is the RSV text of this verse."),
    blank(2, "behold, men passed by, and saw the body thrown in the road, and the lion _____ by the body. And they came and told it in the city where the old prophet", "standing", 25, ["standing"]),
    mc(3, "Which word correctly completes this RSV wording: “behold, men passed by, and saw the body thrown in the road, and the lion _____ by the body. And they came and told it in the city where the old prophet”", ["standing", "favor", "reward", "dwelt"], 25),
    word(1, "In verse 25, what word completes this phrase: “behold, men passed by, and saw the body thrown in the road, and the lion _____ by the body. And they came and told it in the city where the old prophet”?", "standing", 25, ["standing"]),
    tf(2, "The RSV states: “And behold, men passed by, and saw the body thrown in the road, and the lion standing by the body. And they came and told it in the city where the old prophet dwelt.”", true, 25),
    blank(3, "him back from the way heard of it, he said, \"It is the man of God, who _____ the word of the LORD; therefore the LORD has given him to the lion, which", "disobeyed", 26, ["disobeyed"]),
    mc(1, "Which word correctly completes this RSV wording: “him back from the way heard of it, he said, \"It is the man of God, who _____ the word of the LORD; therefore the LORD has given him to the lion, which”", ["disobeyed", "before", "commanded", "father"], 26),
    word(2, "In verse 26, what word completes this phrase: “him back from the way heard of it, he said, \"It is the man of God, who _____ the word of the LORD; therefore the LORD has given him to the lion, which”?", "disobeyed", 26, ["disobeyed"]),
    tf(3, "The RSV does not state: “And when the prophet who had brought him back from the way heard of it, he said, \"It is the man of God, who disobeyed the word of the LORD; therefore the LORD has given him to the lion, which has torn him and slain him, according to the word which the LORD spoke to him.\"”", false, 26, "The quoted wording is the RSV text of this verse."),
    blank(1, "And he said to his sons, \"_____ the ass for me.\" And they saddled it.", "Saddle", 27, ["saddle"]),
    mc(2, "Which word correctly completes this RSV wording: “And he said to his sons, \"_____ the ass for me.\" And they saddled it.”", ["Saddle", "Come", "David", "Bethel"], 27),
    word(3, "In verse 27, what word completes this phrase: “And he said to his sons, \"_____ the ass for me.\" And they saddled it.”?", "Saddle", 27, ["saddle"]),
    tf(1, "The RSV states: “And he said to his sons, \"Saddle the ass for me.\" And they saddled it.”", true, 27),
    blank(2, "went and found his body thrown in the road, and the ass and the lion _____ beside the body. The lion had not eaten the body or torn the ass.", "standing", 28, ["standing"]),
    mc(3, "Which word correctly completes this RSV wording: “went and found his body thrown in the road, and the ass and the lion _____ beside the body. The lion had not eaten the body or torn the ass.”", ["standing", "another", "mounted", "disobeyed"], 28),
    word(1, "In verse 28, what word completes this phrase: “went and found his body thrown in the road, and the ass and the lion _____ beside the body. The lion had not eaten the body or torn the ass.”?", "standing", 28, ["standing"]),
    tf(2, "The RSV does not state: “And he went and found his body thrown in the road, and the ass and the lion standing beside the body. The lion had not eaten the body or torn the ass.”", false, 28, "The quoted wording is the RSV text of this verse."),
    blank(3, "And the _____ took up the body of the man of God and laid it upon the ass, and brought", "prophet", 29, ["prophet"]),
    mc(1, "Which word correctly completes this RSV wording: “And the _____ took up the body of the man of God and laid it upon the ass, and brought”", ["prophet", "father", "lied", "tomb"], 29),
    word(2, "In verse 29, what word completes this phrase: “And the _____ took up the body of the man of God and laid it upon the ass, and brought”?", "prophet", 29, ["prophet"]),
    tf(3, "The RSV states: “And the prophet took up the body of the man of God and laid it upon the ass, and brought it back to the city, to mourn and to bury him.”", true, 29),
    blank(1, "he laid the body in his own grave; and they mourned over him, saying, \"_____, my brother!\"", "Alas", 30, ["alas"]),
    mc(2, "Which word correctly completes this RSV wording: “he laid the body in his own grave; and they mourned over him, saying, \"_____, my brother!\"”", ["Alas", "Judah", "Because", "Saddle"], 30),
    word(3, "In verse 30, what word completes this phrase: “he laid the body in his own grave; and they mourned over him, saying, \"_____, my brother!\"”?", "Alas", 30, ["alas"]),
    tf(1, "The RSV does not state: “And he laid the body in his own grave; and they mourned over him, saying, \"Alas, my brother!\"”", false, 30, "The quoted wording is the RSV text of this verse."),
    blank(2, "And after he had _____ him, he said to his sons, \"When I die, bury me in the grave in which the", "buried", 31, ["buried"]),
    mc(3, "Which word correctly completes this RSV wording: “And after he had _____ him, he said to his sons, \"When I die, bury me in the grave in which the”", ["buried", "table", "away", "took"], 31),
    word(1, "In verse 31, what word completes this phrase: “And after he had _____ him, he said to his sons, \"When I die, bury me in the grave in which the”?", "buried", 31, ["buried"]),
    tf(2, "The RSV states: “And after he had buried him, he said to his sons, \"When I die, bury me in the grave in which the man of God is buried; lay my bones beside his bones.”", true, 31),
    blank(3, "against all the houses of the high places which are in the cities of _____, shall surely come to pass.\"", "Sama’ria", 32, ["samaria"]),
    mc(1, "Which word correctly completes this RSV wording: “against all the houses of the high places which are in the cities of _____, shall surely come to pass.\"”", ["Sama’ria", "Judah", "Because", "Saddle"], 32),
    word(2, "In verse 32, what word completes this phrase: “against all the houses of the high places which are in the cities of _____, shall surely come to pass.\"”?", "Sama’ria", 32, ["samaria"]),
    tf(3, "The RSV does not state: “For the saying which he cried by the word of the LORD against the altar in Bethel, and against all the houses of the high places which are in the cities of Sama’ria, shall surely come to pass.\"”", false, 32, "The quoted wording is the RSV text of this verse."),
    blank(1, "After this thing _____ did not turn from his evil way, but made priests for the high places again", "Jerobo’am", 33, ["jeroboam"]),
    mc(2, "Which word correctly completes this RSV wording: “After this thing _____ did not turn from his evil way, but made priests for the high places again”", ["Jerobo’am", "Saddle", "Josi’ah", "Bethel"], 33),
    word(3, "In verse 33, what word completes this phrase: “After this thing _____ did not turn from his evil way, but made priests for the high places again”?", "Jerobo’am", 33, ["jeroboam"]),
    tf(1, "The RSV states: “After this thing Jerobo’am did not turn from his evil way, but made priests for the high places again from among all the people; any who would, he consecrated to be priests of the high places.”", true, 33),
    blank(2, "And this thing became sin to the house of _____, so as to cut it off and to destroy it from the face of the earth.", "Jerobo’am", 34, ["jeroboam"]),
    mc(3, "Which word correctly completes this RSV wording: “And this thing became sin to the house of _____, so as to cut it off and to destroy it from the face of the earth.”", ["Jerobo’am", "Judah", "Alas", "Bring"], 34),
    word(1, "In verse 34, what word completes this phrase: “And this thing became sin to the house of _____, so as to cut it off and to destroy it from the face of the earth.”?", "Jerobo’am", 34, ["jeroboam"]),
    tf(2, "The RSV does not state: “And this thing became sin to the house of Jerobo’am, so as to cut it off and to destroy it from the face of the earth.”", false, 34, "The quoted wording is the RSV text of this verse."),
    mc(1, "What future king did the man of God name in his prophecy against the altar at Bethel?", ["Josiah", "Hezekiah", "Jehu", "Ahab"], 2),
    mc(2, "What happened to Jeroboam’s hand when he ordered that the man of God be seized?", ["It dried up so he could not draw it back", "It became leprous", "It was burned", "It was cut by a sword"], 4),
    mc(2, "Which three commands governed the man of God’s journey?", ["Eat no bread, drink no water, and do not return by the same way", "Speak to no king, enter no city, and carry no money", "Offer no sacrifice, touch no altar, and appoint no priest", "Ride no animal, sleep in no house, and cross no river"], 9),
    mc(3, "How did the old prophet persuade the man of God to return and eat with him?", ["He falsely claimed that an angel had spoken to him by the word of the LORD", "He said Jeroboam had ordered it", "He promised to hide him from the king", "He claimed the road to Judah was closed"], 18),
    mc(1, "What met the man of God on the road and killed him?", ["A lion", "A bear", "A band of robbers", "Jeroboam’s guards"], 24),
    mc(3, "What did the old prophet tell his sons to do when he died?", ["Bury him in the man of God’s grave and lay his bones beside the man’s bones", "Carry his bones to Judah", "Bury him beside the altar at Bethel", "Burn his body outside the city"], 31),
  ],
};

export default bank;
