// 1 Kings 1 — quiz bank (RSV). Every row is anchored to a verse; fill-in-the-blank
// rows are verified against the stored verse text by scripts/seed-quiz-bank.ts.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: '1 Kings',
  chapter: 1,
  tag: 'quiz-v2-1kings-1',
  rows: [
    // ══════════════════════════════════ v1–4 · David’s old age, Abishag
    tf(1, 'David could not get warm even though his servants covered him with clothes.', true, 1),
    blank(1, 'Now King David was old and advanced in years; and although they covered him with clothes, he could not get _____.', 'warm', 1),
    blank(2, 'Let a young maiden be sought for my lord the king, and let her wait upon the king, and be his _____; let her lie in your bosom, that my lord the king may be warm.', 'nurse', 2),
    word(2, 'David’s servants proposed that a young maiden serve the king in what role?', 'nurse', 2),
    mc(1, 'Where was Abishag from?', ['Shunem (she was the Shunammite)', 'Gihon (where Solomon was anointed)', 'En-rogel (beside the Serpent’s Stone)', 'Judah (home of the royal officials)'], 3),
    mc(1, 'Why was Abishag the Shunammite brought to King David?', ['To warm him and care for him because he could not get warm', 'To advise him about the dispute over who would reign next', 'To summon the priest and prophet who would anoint Solomon', 'To bring him news of the feast being held beside En-rogel'], 3),
    blank(2, 'So they sought for a beautiful maiden throughout all the territory of _____, and found Ab’ishag the Shu’nammite, and brought her to the king.', 'Israel', 3),
    tf(1, 'Abishag the Shunammite was brought to King David to advise him about the succession.', false, 3, 'The servants brought Abishag to David so that "my lord the king may be warm."'),
    word(3, 'Which people is Abishag identified with (the “___ite”)?', 'Shunammite', 3, ['shunamite', 'shunem']),
    blank(3, 'The maiden was very beautiful; and she became the king’s nurse and _____ to him; but the king knew her not.', 'ministered', 4),
    tf(2, 'King David knew Abishag as his wife after she became his nurse.', false, 4, 'Although Abishag became the king’s nurse and ministered to him, "the king knew her not."'),

    // ══════════════════════════════════ v5–10 · Adonijah exalts himself
    mc(1, 'Adonijah was the son of which woman?', ['Haggith', 'Bathsheba', 'Michal', 'Ahinoam'], 5),
    word(2, 'Who was Adonijah’s mother?', 'Haggith', 5),
    blank(1, 'Now Adoni’jah the son of Haggith exalted himself, saying, "I will be _____"; and he prepared for himself chariots and horsemen, and fifty men to run before him.', 'king', 5),
    word(1, 'Along with horsemen, what did Adonijah prepare for himself?', 'chariots', 5, ['chariot']),
    word(2, 'How many men did Adonijah have running before him?', 'fifty', 5, ['50']),
    mc(2, 'What did Adonijah say when he exalted himself?', ['"I will be king"', '"The LORD has chosen me"', '"My father has appointed me"', '"Solomon is too young"'], 5),
    tf(3, 'David had often rebuked Adonijah for his behavior.', false, 6, 'His father had never at any time displeased him by asking, "Why have you done thus and so?"'),
    mc(2, 'Adonijah was born next after which of David’s sons?', ['Absalom', 'Amnon', 'Solomon', 'Chileab'], 6),
    word(3, 'Adonijah was born next after which brother?', 'Absalom', 6),
    blank(3, 'His father had never at any time displeased him by asking, "Why have you done thus and so?" He was also a very _____ man; and he was born next after Ab’salom.', 'handsome', 6),
    mc(2, 'Which two men followed Adonijah and helped him?', ['Joab the son of Zeruiah and Abiathar the priest', 'Zadok the priest and Nathan the prophet', 'Benaiah the son of Jehoiada and Shimei', 'Nathan the prophet and David’s servant Rei'], 7),
    word(2, 'Which priest sided with Adonijah?', 'Abiathar', 7),
    word(2, 'Who was Joab’s mother?', 'Zeruiah', 7),
    blank(1, 'He conferred with Jo’ab the son of Zeru’iah and with Abi’athar the _____; and they followed Adoni’jah and helped him.', 'priest', 7),
    tf(1, 'Joab the commander supported Solomon’s claim to the throne.', false, 7, 'Joab and Abiathar the priest followed Adonijah.'),
    mc(2, 'Which of these was NOT among those who stayed loyal to David (not with Adonijah)?', ['Abiathar the priest', 'Zadok the priest', 'Benaiah the son of Jehoiada', 'Shimei'], 8),
    mc(2, 'Benaiah was the son of whom?', ['Jehoiada', 'Zeruiah', 'Abiathar', 'Haggith'], 8),
    blank(3, 'But Zadok the priest, and Benai’ah the son of Jehoi’ada, and Nathan the prophet, and Shim’e-i, and Re’i, and David’s _____ men were not with Adoni’jah.', 'mighty', 8),
    word(3, 'Who is named right after Shimei among those who were not with Adonijah?', 'Rei', 8),
    tf(2, 'Nathan the prophet sided with Adonijah.', false, 8),
    mc(2, 'Where did Adonijah hold his sacrifice and feast?', ['By the Serpent’s Stone beside En-rogel', 'At Gihon beside King David’s own mule', 'In King David’s chamber beside his bed', 'At the tent containing Zadok’s horn of oil'], 9),
    word(2, 'Adonijah sacrificed sheep, oxen, and fatlings beside what stone?', 'Serpent’s Stone', 9, ['serpents stone', 'serpent stone', 'the serpents stone']),
    word(3, 'The Serpent’s Stone, where Adonijah sacrificed, was beside which spring?', 'En-rogel', 9, ['enrogel', 'en rogel']),
    blank(1, 'Adoni’jah sacrificed sheep, oxen, and fatlings by the Serpent’s Stone, which is beside _____, and he invited all his brothers, the king’s sons, and all the royal officials of Judah,', 'En-rogel', 9, ['enrogel', 'en rogel']),
    mc(3, 'Whom did Adonijah invite to his sacrifice?', ['All his brothers the king’s sons, and all the royal officials of Judah', 'Nathan the prophet, Benaiah, Solomon, and David’s mighty men', 'Zadok the priest, Nathan the prophet, and Benaiah son of Jehoiada', 'The Cherethites, the Pelethites, and all the people of Israel'], 9),
    mc(1, 'Who was NOT invited to Adonijah’s feast?', ['Solomon', 'Joab', 'Abiathar', 'The king’s sons'], 10),
    blank(2, 'but he did not invite Nathan the prophet or Benai’ah or the mighty men or _____ his brother.', 'Solomon', 10),
    tf(1, 'Adonijah invited his brother Solomon to his sacrifice at En-rogel.', false, 10, 'He invited all his brothers except Solomon, and left out Nathan, Benaiah and the mighty men.'),

    // ══════════════════════════════════ v11–14 · Nathan’s plan
    mc(1, 'Who was Solomon’s mother?', ['Bathsheba', 'Haggith', 'Abishag', 'Abigail'], 11),
    word(1, 'Which prophet went to Bathsheba with a plan to save Solomon?', 'Nathan', 11),
    blank(1, 'Then Nathan said to Bathshe’ba the mother of Solomon, "Have you not heard that Adoni’jah the son of Haggith has become _____ and David our lord does not know it?', 'king', 11),
    tf(1, 'David knew that Adonijah had made himself king.', false, 11, 'Nathan: "Adonijah … has become king and David our lord does not know it."'),
    mc(3, 'According to Nathan, why should Bathsheba go to King David at once?', ['To save her own life and the life of her son Solomon', 'To preserve Adonijah’s feast and the lives of all his guests', 'To protect Joab the commander and Abiathar the priest from David', 'To save Nathan, Zadok, Benaiah, and all David’s mighty men'], 12),
    word(3, 'Nathan said to Bathsheba, "let me give you ___" — what did he offer?', 'counsel', 12, ['advice']),
    blank(3, 'Now therefore come, let me give you counsel, that you may save your own _____ and the life of your son Solomon.', 'life', 12),
    mc(2, 'What oath was Bathsheba to remind David he had sworn?', ['"Solomon your son shall reign after me, and he shall sit upon my throne"', '"Adonijah son of Haggith shall reign after me and sit upon my throne"', '"Joab son of Zeruiah shall command my servants and sit upon my throne"', '"Nathan the prophet shall choose from among my sons who will sit upon my throne"'], 13),
    blank(2, 'Did you not, my lord the king, swear to your maidservant, saying, "Solomon your son shall reign after me, and he shall sit upon my _____"? Why then is Adoni’jah king?', 'throne', 13),
    tf(2, 'Nathan told Bathsheba to go in to King David "at once".', true, 13),
    blank(2, 'Then while you are still speaking with the king, I also will come in after you and _____ your words.', 'confirm', 14),
    word(2, 'Nathan promised to come in after Bathsheba and do what to her words?', 'confirm', 14),
    mc(3, 'Why did Nathan’s plan have both Bathsheba and himself speak to David?', ['So Nathan could come in while she was still speaking and confirm her words', 'So Abiathar could come in after Bathsheba and contradict her words', 'So Joab could enter with Nathan and report the feast at En-rogel', 'So Solomon could come before the king and ask directly for the throne'], 14),

    // ══════════════════════════════════ v15–21 · Bathsheba before David
    tf(1, 'When Bathsheba went in to the king, Abishag the Shunammite was ministering to him.', true, 15),
    blank(3, 'So Bathshe’ba went to the king into his _____ (now the king was very old, and Ab’ishag the Shu’nammite was ministering to the king).', 'chamber', 15),
    mc(1, 'What did David say when Bathsheba bowed before him?', ['"What do you desire?"', '"Why have you come?"', '"Where is Nathan?"', '"Call Solomon"'], 16),
    blank(1, 'Bathshe’ba bowed and did _____ to the king, and the king said, "What do you desire?"', 'obeisance', 16),
    blank(2, 'She said to him, "My lord, you swore to your maidservant by the LORD your _____, saying, `Solomon your son shall reign after me, and he shall sit upon my throne.\'', 'God', 17),
    tf(2, 'Bathsheba reminded David that he had sworn by Abiathar the priest.', false, 17, 'She said, "you swore to your maidservant by the LORD your God."'),
    blank(1, 'And now, behold, Adoni’jah is king, although you, my lord the king, do not _____ it.', 'know', 18),
    mc(3, 'In Bathsheba’s account, whom had Adonijah invited?', ['All the sons of the king, Abiathar the priest, and Joab the commander of the army', 'Zadok the priest, Nathan the prophet, and Benaiah the son of Jehoiada', 'Solomon, the Cherethites, the Pelethites, and all David’s mighty men', 'Bathsheba, Abishag the Shunammite, Shimei, Rei, and all the people'], 19),
    blank(3, 'He has sacrificed oxen, fatlings, and sheep in _____, and has invited all the sons of the king, Abi’athar the priest, and Jo’ab the commander of the army; but Solomon your servant he has not invited.', 'abundance', 19),
    blank(2, 'And now, my lord the king, the eyes of all _____ are upon you, to tell them who shall sit on the throne of my lord the king after him.', 'Israel', 20),
    word(2, 'Bathsheba said the eyes of all Israel were on David to tell them who would sit on what?', 'throne', 20),
    tf(3, 'Bathsheba said the eyes of all Judah were upon the king.', false, 20, 'She said "the eyes of all Israel are upon you".'),
    blank(3, 'Otherwise it will come to pass, when my lord the king sleeps with his fathers, that I and my son Solomon will be counted _____.', 'offenders', 21),
    mc(3, 'What did Bathsheba fear would happen to her and Solomon after David died?', ['They would be counted offenders', 'They would be exiled to Egypt', 'They would be made servants of Adonijah', 'They would lose their inheritance'], 21),
    word(3, 'Bathsheba described David’s death as when he "sleeps with his ___".', 'fathers', 21),

    // ══════════════════════════════════ v22–27 · Nathan before David
    tf(1, 'Nathan the prophet came in while Bathsheba was still speaking with the king.', true, 22),
    tf(2, 'Nathan came in before Bathsheba began speaking with King David.', false, 22, 'Nathan came in "while she was still speaking with the king."'),
    blank(2, 'And they told the king, "Here is Nathan the _____." And when he came in before the king, he bowed before the king, with his face to the ground.', 'prophet', 23),
    word(2, 'When Nathan came before the king, he bowed with his face to what?', 'ground', 23, ['the ground']),
    mc(2, 'How did Nathan put his question to David?', ['"Have you said, ‘Adonijah shall reign after me, and he shall sit upon my throne’?"', '"Have you said, ‘Solomon shall give his throne to Adonijah and serve him’?"', '"Have you ordered Joab and Abiathar to anoint Adonijah beside En-rogel?"', '"Have you told Bathsheba that neither of your sons shall sit upon your throne?"'], 24),
    blank(2, 'and behold, they are eating and drinking before him, and saying, `Long live King _____!\'', 'Adonijah', 25, ['adonijah']),
    word(1, 'At Adonijah’s feast the guests were shouting "Long live King ___!"', 'Adonijah', 25),
    tf(2, 'Nathan reported that Adonijah’s guests were fasting in silence before him.', false, 25, 'Nathan said, "they are eating and drinking before him."'),
    blank(3, 'But me, your servant, and Zadok the priest, and Benai’ah the son of Jehoi’ada, and your servant _____, he has not invited.', 'Solomon', 26),
    mc(3, 'Nathan listed those Adonijah had NOT invited. Which name is on that list?', ['Zadok the priest', 'Joab the commander', 'Abiathar the priest', 'The king’s sons'], 26),
    blank(3, 'Has this thing been brought about by my lord the king and you have not told your _____ who should sit on the throne of my lord the king after him?"', 'servants', 27),
    tf(3, 'Nathan asked whether David himself had arranged Adonijah’s kingship without telling his servants.', true, 27),
    mc(2, 'What news did Nathan bring to Bathsheba?', ['Adonijah son of Haggith had become king without David knowing it', 'Solomon had been anointed king at Gihon on David’s own mule', 'Adonijah had taken hold of the altar because he feared Solomon', 'Jonathan son of Abiathar had brought good news from the city'], 11),

    // ══════════════════════════════════ v28–31 · David renews his oath
    word(1, 'Whom did David call back to him after Nathan had spoken?', 'Bathsheba', 28),
    blank(1, 'Then King David answered, "Call _____ to me." So she came into the king’s presence, and stood before the king.', 'Bathsheba', 28),
    blank(3, 'And the king swore, saying, "As the LORD lives, who has redeemed my soul out of every _____,', 'adversity', 29),
    tf(2, 'David swore, "As the LORD lives, who has redeemed my soul out of every adversity."', true, 29),
    blank(2, 'as I swore to you by the LORD, the God of Israel, saying, `Solomon your son shall reign after me, and he shall sit upon my throne in my _____\'; even so will I do this day."', 'stead', 30),
    word(3, 'David promised to carry out his oath "even so will I do this ___".', 'day', 30),
    tf(3, 'David swore that Solomon would sit upon his throne "in my stead".', true, 30),
    mc(2, 'What did David promise Bathsheba he would do that day?', ['Fulfill his oath that Solomon would reign after him and sit on his throne', 'Accept Adonijah’s claim and allow him to sit upon the royal throne', 'Let Joab and Abiathar decide which of his sons should reign after him', 'Wait until another day before deciding who should sit upon his throne'], 30),
    blank(1, 'Then Bathshe’ba bowed with her face to the ground, and did obeisance to the king, and said, "May my lord King David live for _____!"', 'ever', 31),
    mc(1, 'What did Bathsheba say after David confirmed his oath?', ['"May my lord King David live for ever!"', '"May the LORD make Solomon’s throne greater than yours!"', '"Blessed be the LORD, who has granted your offspring the throne!"', '"Long live King Solomon, ruler over Israel and Judah!"'], 31),

    // ══════════════════════════════════ v32–37 · David’s orders
    mc(2, 'Which three men did David summon to carry out Solomon’s anointing?', ['Zadok the priest, Nathan the prophet, and Benaiah the son of Jehoiada', 'Abiathar the priest, Joab the son of Zeruiah, and Adonijah son of Haggith', 'Shimei, Rei, and Jonathan the son of Abiathar the priest', 'Solomon, Adonijah, and all the other sons of King David'], 32),
    blank(2, 'King David said, "Call to me Zadok the priest, Nathan the prophet, and Benai’ah the son of _____." So they came before the king.', 'Jehoiada', 32),
    blank(1, 'And the king said to them, "Take with you the servants of your lord, and cause Solomon my son to ride on my own _____, and bring him down to Gihon;', 'mule', 33),
    word(1, 'What animal did Solomon ride down to Gihon?', 'mule', 33, ['king’s mule', 'davids mule']),
    word(2, 'Where did David order that Solomon be brought down to?', 'Gihon', 33),
    tf(1, 'David told them to bring Solomon down to En-rogel.', false, 33, 'David said, "bring him down to Gihon."'),
    mc(1, 'Where did David command that Solomon be anointed as king?', ['At Gihon', 'At En-rogel', 'In Hebron', 'At Bethel'], 34),
    mc(1, 'Who anointed Solomon as king at Gihon?', ['Zadok the priest and Nathan the prophet', 'Abiathar the priest and Joab son of Zeruiah', 'Benaiah son of Jehoiada and Shimei', 'King David and Bathsheba, Solomon’s mother'], 34),
    blank(1, 'and let Zadok the priest and Nathan the prophet there anoint him king over Israel; then blow the trumpet, and say, `Long live King _____!\'', 'Solomon', 34),
    tf(2, 'David said Solomon was to be anointed king over Israel.', true, 34),
    blank(3, 'You shall then come up after him, and he shall come and sit upon my throne; for he shall be king in my stead; and I have appointed him to be _____ over Israel and over Judah."', 'ruler', 35),
    mc(3, 'Over whom did David say he had appointed Solomon ruler?', ['Israel and Judah', 'Israel only', 'Judah only', 'All the nations round about'], 35),
    word(3, 'David said he had appointed Solomon to be ___ over Israel and over Judah.', 'ruler', 35),
    mc(3, 'Who answered David, "Amen! May the LORD, the God of my lord the king, say so"?', ['Benaiah the son of Jehoiada', 'Zadok the priest', 'Nathan the prophet', 'Joab the commander'], 36),
    word(2, 'What single word did Benaiah answer the king with first?', 'Amen', 36),
    blank(2, 'And Benai’ah the son of Jehoi’ada answered the king, "_____! May the LORD, the God of my lord the king, say so.', 'Amen', 36),
    mc(2, 'Benaiah prayed that the LORD would make Solomon’s throne what?', ['Greater than the throne of my lord King David', 'Equal to the throne of his brother Adonijah', 'Lower than the throne of his father King David', 'Separate from the rule over Israel and over Judah'], 37),
    blank(3, 'As the LORD has been with my lord the king, even so may he be with Solomon, and make his throne _____ than the throne of my lord King David."', 'greater', 37),
    tf(3, 'Benaiah prayed that Solomon’s throne would be equal to David’s.', false, 37, 'He prayed it would be "greater than the throne of my lord King David".'),

    // ══════════════════════════════════ v38–40 · The anointing at Gihon
    mc(2, 'Who went down with Solomon to Gihon?', ['Zadok, Nathan, Benaiah, the Cherethites and the Pelethites', 'Abiathar, Joab, Adonijah, and all the king’s other sons', 'Bathsheba, Abishag, Shimei, Rei, and David’s mighty men', 'Jonathan, the royal officials of Judah, and Adonijah’s guests'], 38),
    word(3, 'Along with the Cherethites, which group escorted Solomon to Gihon?', 'Pelethites', 38, ['pelethite']),
    blank(3, 'So Zadok the priest, Nathan the prophet, and Benai’ah the son of Jehoi’ada, and the Cher’ethites and the _____, went down and caused Solomon to ride on King David’s mule, and brought him to Gihon.', 'Pelethites', 38),
    tf(2, 'Joab and Abiathar escorted Solomon to Gihon.', false, 38, 'The verse names Zadok, Nathan, Benaiah, the Cherethites, and the Pelethites as Solomon’s escort.'),
    mc(1, 'Where was Solomon anointed king?', ['Gihon', 'Hebron', 'En-rogel', 'Bethel'], 38),
    blank(1, 'There Zadok the priest took the horn of _____ from the tent, and anointed Solomon. Then they blew the trumpet; and all the people said, "Long live King Solomon!"', 'oil', 39),
    word(3, 'Zadok took the oil for Solomon’s anointing from the tent in what?', 'horn', 39, ['horn of oil']),
    word(1, 'From where did Zadok take the horn of oil?', 'tent', 39, ['the tent']),
    word(1, 'What instrument was blown to announce Solomon as king?', 'trumpet', 39),
    mc(1, 'What instrument was used to publicly announce Solomon’s anointing?', ['Trumpet', 'Harp', 'Cymbals', 'Lyre'], 39),
    mc(1, 'After Solomon was anointed, what did all the people say?', ['"Long live King Solomon!"', '"God save the king!"', '"Hail, son of David!"', '"Blessed be the LORD!"'], 39),
    blank(2, 'Then they blew the trumpet; and all the _____ said, "Long live King Solomon!"', 'people', 39),
    tf(1, 'Zadok the priest anointed Solomon.', true, 39),
    mc(2, 'What instruments did the people play as they went up after Solomon?', ['Pipes', 'Harps', 'Lyres', 'Cymbals'], 40),
    word(1, 'The people rejoiced going up after Solomon, playing on what?', 'pipes', 40, ['pipe', 'flutes']),
    blank(2, 'And all the people went up after him, playing on pipes, and rejoicing with great joy, so that the earth was split by their _____.', 'noise', 40),
    tf(1, 'The people’s rejoicing was so loud that "the earth was split by their noise".', true, 40),

    // ══════════════════════════════════ v41–48 · The news reaches Adonijah
    mc(3, 'What did Joab ask when he heard the sound of the trumpet?', ['"What does this uproar in the city mean?"', '"Why are the people playing pipes as they go up?"', '"Who caused Solomon to ride on the king’s mule?"', '"Where did Zadok take the horn of oil from?"'], 41),
    word(2, 'Who asked, "What does this uproar in the city mean?"', 'Joab', 41),
    blank(1, 'And when Jo’ab heard the sound of the _____, he said, "What does this uproar in the city mean?"', 'trumpet', 41),
    tf(3, 'Adonijah and his guests heard the noise from the city as they were finishing their feast.', true, 41),
    word(2, 'Who was Jonathan’s father?', 'Abiathar', 42),
    mc(2, 'How did Adonijah greet Jonathan when he arrived?', ['"Come in, for you are a worthy man and bring good news"', '"Come in, for you are the king’s servant and bring his command"', '"Go back, for Solomon sits on the royal throne in the city"', '"Stand outside, for the sound of the trumpet means bad news"'], 42),
    blank(2, 'While he was still speaking, behold, Jonathan the son of Abi’athar the priest came; and Adoni’jah said, "Come in, for you are a worthy man and bring good _____."', 'news', 42),
    tf(3, 'Adonijah said "Come in, for you are a worthy man and bring good news" to Nathan the prophet.', false, 42, 'He said it to Jonathan the son of Abiathar — who then brought the bad news.'),
    mc(2, 'Who brought Adonijah’s party the news that Solomon had been made king?', ['Jonathan the son of Abiathar', 'Benaiah the son of Jehoiada', 'Nathan the prophet and David’s servant', 'Zadok the priest who anointed Solomon'], 43),
    blank(1, 'Jonathan answered Adoni’jah, "No, for our lord King David has made _____ king;', 'Solomon', 43),
    tf(1, 'Jonathan told Adonijah that King David had made Solomon king.', true, 43),
    tf(3, 'Jonathan reported that Solomon had been made to ride on the king’s mule.', true, 44),
    mc(3, 'In Jonathan’s report, whom had the king sent with Solomon?', ['Zadok, Nathan, Benaiah, the Cherethites and the Pelethites', 'Abiathar, Joab, Adonijah, and all the king’s other sons', 'Bathsheba, Abishag, Shimei, Rei, and David’s mighty men', 'Jonathan, the royal officials of Judah, and Adonijah’s guests'], 44),
    blank(2, 'and Zadok the priest and Nathan the prophet have anointed him king at _____; and they have gone up from there rejoicing, so that the city is in an uproar. This is the noise that you have heard.', 'Gihon', 45),
    word(3, 'Jonathan said the city was in what state?', 'uproar', 45, ['an uproar']),
    tf(2, 'Jonathan told Adonijah that the uproar in the city was the people rejoicing over Solomon’s anointing.', true, 45),
    blank(1, 'Solomon sits upon the royal _____.', 'throne', 46),
    tf(1, 'Jonathan reported, "Solomon sits upon the royal throne."', true, 46),
    mc(3, 'What did the king’s servants say when they came to congratulate David?', ['"Your God make the name of Solomon more famous than yours, and make his throne greater than your throne"', '"Your God make the name of Adonijah more famous than yours, and establish his throne above your throne"', '"May the LORD be with Solomon as he was with David, and make both of their thrones equal in greatness"', '"Blessed be the LORD who has granted one of your servants to sit on the royal throne this day"'], 47),
    word(3, 'The king’s servants came to do what to David?', 'congratulate', 47),
    blank(3, 'Moreover the king’s servants came to congratulate our lord King David, saying, `Your God make the name of Solomon more _____ than yours, and make his throne greater than your throne.\'', 'famous', 47),
    mc(3, 'What did David do as his servants congratulated him?', ['He bowed himself upon the bed', 'He rose from the bed and went down to Gihon', 'He called Adonijah into the king’s chamber', 'He sent the servants away from his presence'], 47),
    tf(3, 'David bowed himself upon the bed when his servants congratulated him.', true, 47),
    blank(2, 'And the king also said, `Blessed be the LORD, the God of Israel, who has granted one of my offspring to sit on my throne this day, my own _____ seeing it.\'', 'eyes', 48),
    blank(3, 'Blessed be the LORD, the God of Israel, who has granted one of my _____ to sit on my throne this day, my own eyes seeing it.', 'offspring', 48),
    mc(2, 'What did David bless the LORD for?', ['Granting one of his offspring to sit on his throne while his own eyes saw it', 'Granting Joab victory over Adonijah while David watched from his chamber', 'Granting Abiathar the priest a place beside Solomon on the royal throne', 'Granting all David’s sons authority over Israel and Judah while he still lived'], 48),
    word(2, 'David said, "Blessed be the LORD, the God of ___".', 'Israel', 48),

    // ══════════════════════════════════ v49–53 · Adonijah at the altar
    blank(1, 'Then all the guests of Adoni’jah trembled, and rose, and each went his own _____.', 'way', 49),
    mc(1, 'How did Adonijah’s guests react to the news?', ['They trembled, rose, and each went his own way', 'They rejoiced, played pipes, and went together to Gihon', 'They entered David’s chamber and congratulated the old king', 'They remained at the feast and proclaimed Adonijah king again'], 49),
    word(1, 'What did Adonijah’s guests do when they heard the news — they ___ and rose.', 'trembled', 49, ['tremble']),
    mc(2, 'What did Adonijah do because he feared Solomon?', ['He went and caught hold of the horns of the altar', 'He rode David’s mule down to the spring at Gihon', 'He entered the king’s chamber and bowed upon the bed', 'He gathered his brothers and Judah’s officials at En-rogel'], 50),
    word(1, 'Fearing Solomon, Adonijah caught hold of the horns of what?', 'altar', 50, ['the altar']),
    blank(2, 'And Adoni’jah feared Solomon; and he arose, and went, and caught hold of the horns of the _____.', 'altar', 50),
    tf(1, 'Adonijah feared Solomon and fled to the altar.', true, 50),
    mc(3, 'Why did Adonijah grab the horns of the altar?', ['He feared Solomon after Solomon had been made king', 'He wished to offer the sheep and oxen left from his feast', 'He hoped to take Zadok’s horn of oil and anoint himself king', 'He intended to summon Joab and Abiathar back to En-rogel'], 50),
    blank(2, 'Let King Solomon swear to me first that he will not slay his servant with the _____.', 'sword', 51),
    mc(2, 'What did Adonijah want Solomon to swear?', ['That he would not slay his servant with the sword', 'That he would let Adonijah sit beside him on the royal throne', 'That he would return Adonijah’s guests to the feast at En-rogel', 'That he would appoint Joab and Abiathar to serve him again'], 51),
    tf(2, 'Adonijah asked that Solomon swear first that he would not kill him.', true, 51),
    mc(3, 'What condition did Solomon set for sparing Adonijah’s life?', ['That Adonijah prove worthy — if wickedness is found in him he shall die', 'That Adonijah leave the land and never return to the king’s presence', 'That Adonijah serve in the army under Benaiah son of Jehoiada', 'That Adonijah surrender his house and possessions to Solomon’s servants'], 52),
    blank(3, 'And Solomon said, "If he prove to be a worthy man, not one of his _____ shall fall to the earth; but if wickedness is found in him, he shall die."', 'hairs', 52),
    mc(2, 'What would happen to Adonijah if wickedness were found in him?', ['He shall die', 'He would be exiled', 'He would be imprisoned', 'He would lose his inheritance'], 52),
    word(2, 'Solomon said, "not one of his hairs shall fall to the ___".', 'earth', 52, ['ground']),
    tf(2, 'Solomon promised Adonijah an unconditional pardon.', false, 52, 'The pardon was conditional: "if wickedness is found in him, he shall die."'),
    tf(2, 'Solomon had Adonijah executed as soon as he was anointed.', false, 53, 'Solomon sent him home: "Go to your house."'),
    blank(1, 'So King Solomon sent, and they brought him down from the altar. And he came and did obeisance to King Solomon; and Solomon said to him, "Go to your _____."', 'house', 53),
    mc(1, 'What did Solomon tell Adonijah after he was brought down from the altar?', ['"Go to your house"', '"You shall surely die"', '"Serve me faithfully"', '"Leave Jerusalem"'], 53),
    tf(3, 'Adonijah did obeisance to King Solomon after being brought down from the altar.', true, 53),

    // ══════════════════════════════════ Whole-chapter
    mc(1, 'Who is king of Israel by the end of 1 Kings 1?', ['Solomon', 'Adonijah', 'Absalom', 'Joab'], 46),
    mc(2, 'Who did NOT support Adonijah’s bid for kingship?', ['Zadok the priest', 'Joab', 'Abiathar', 'The royal officials of Judah'], 8),
    tf(2, 'King David went down to Gihon to watch Solomon be anointed.', false, 47, 'David stayed in his chamber; his servants came to congratulate him and he bowed on the bed.'),
  ],
};

export default bank;
