// 1 Kings 2 — quiz bank (RSV). Every row is anchored to a verse; fill-in-the-blank
// rows are verified against the stored verse text by scripts/seed-quiz-bank.ts.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: '1 Kings',
  chapter: 2,
  tag: 'quiz-v2-1kings-2',
  rows: [
    // ══════════════════════════════════ v1–4 · David’s charge to Solomon
    blank(1, 'When David’s time to die drew near, he charged _____ his son, saying,', 'Solomon', 1),
    tf(1, 'David charged Solomon his son when his time to die drew near.', true, 1),
    mc(1, 'What was happening when David charged Solomon?', ['David’s time to die was drawing near', 'Solomon was about to go to war', 'The temple was being dedicated', 'Adonijah had just been executed'], 1),
    blank(1, 'I am about to go the way of all the earth. Be strong, and show yourself a _____,', 'man', 2),
    blank(1, 'I am about to go the way of all the _____.', 'earth', 2),
    mc(2, 'How did David describe his approaching death to Solomon?', ['"I am about to go the way of all the earth"', '"I am about to sleep with my fathers"', '"My days are numbered"', '"The LORD is calling me home"'], 2),
    word(1, 'David told Solomon, "Be strong, and show yourself a ___."', 'man', 2),
    tf(2, 'David told Solomon, "Be strong, and show yourself a king."', false, 2, 'David said "show yourself a man".'),
    blank(2, 'and keep the charge of the LORD your God, walking in his ways and keeping his statutes, his commandments, his ordinances, and his testimonies, as it is written in the law of _____,', 'Moses', 3),
    mc(2, 'According to David, where is the charge of the LORD written?', ['In the law of Moses', 'On the tablets in the ark', 'In the book of the covenant', 'In the words of Samuel'], 3),
    mc(3, 'Which of these is NOT in David’s list of what Solomon must keep?', ['His promises', 'His statutes', 'His ordinances', 'His testimonies'], 3, 'The list is statutes, commandments, ordinances, and testimonies.'),
    word(3, 'David said keeping the LORD’s statutes would let Solomon do what "in all that you do"?', 'prosper', 3),
    blank(3, 'If your sons take heed to their way, to walk before me in faithfulness with all their heart and with all their soul, there shall not fail you a man on the throne of _____.', 'Israel', 4),
    mc(3, 'What had the LORD promised David on condition that his sons walk before him in faithfulness?', ['There shall not fail you a man on the throne of Israel', 'Your house shall build my temple', 'Your enemies shall be scattered', 'Your name shall be great among the nations'], 4),
    tf(3, 'The LORD’s word to David required his sons to walk before him "with all their heart and with all their soul".', true, 4),
    word(3, 'David’s sons were to walk before the LORD in what — "to walk before me in ___"?', 'faithfulness', 4),

    // ══════════════════════════════════ v5–6 · Joab
    mc(1, 'Which two commanders did Joab murder, according to David?', ['Abner the son of Ner and Amasa the son of Jether', 'Abiathar the priest and Zadok the priest', 'Shimei the son of Gera and Adonijah son of Haggith', 'Benaiah the son of Jehoiada and Absalom son of David'], 5),
    word(2, 'Who was Abner’s father?', 'Ner', 5),
    word(3, 'Who was Amasa’s father?', 'Jether', 5),
    blank(2, 'Moreover you know also what Jo’ab the son of Zeru’iah did to me, how he dealt with the two _____ of the armies of Israel,', 'commanders', 5),
    tf(3, 'David said Joab avenged in time of war blood that had been shed in peace.', false, 5, 'It is the reverse: "avenging in time of peace blood which had been shed in war".'),
    mc(3, 'Where did David say Joab had put innocent blood?', ['Upon the girdle about his loins and the sandals on his feet', 'Upon the horns of the altar inside the tent of the LORD', 'Upon the gate of Jerusalem and the brook called Kidron', 'Upon the throne of David and the table of King Solomon'], 5),
    blank(3, 'and putting innocent blood upon the girdle about my loins, and upon the _____ on my feet.', 'sandals', 5),
    blank(1, 'Act therefore according to your wisdom, but do not let his gray head go down to _____ in peace.', 'Sheol', 6),
    blank(1, 'Act therefore according to your _____, but do not let his gray head go down to Sheol in peace.', 'wisdom', 6),
    tf(1, 'David told Solomon to let Joab’s gray head go down to Sheol in peace.', false, 6, 'David said "do not let his gray head go down to Sheol in peace."'),
    mc(2, 'What did David tell Solomon to act according to, concerning Joab?', ['His wisdom', 'The law of Moses', 'The counsel of Nathan', 'His anger'], 6),
    word(2, 'David said of Joab, "do not let his ___ head go down to Sheol in peace."', 'gray', 6, ['grey']),

    // ══════════════════════════════════ v7 · Sons of Barzillai
    mc(1, 'With whom did David tell Solomon to "deal loyally"?', ['The sons of Barzillai the Gileadite', 'The sons of Shimei', 'The house of Joab', 'The sons of Abiathar'], 7),
    blank(2, 'But deal loyally with the sons of Barzil’lai the _____, and let them be among those who eat at your table;', 'Gileadite', 7),
    word(3, 'The sons of Barzillai were to be among those who eat at Solomon’s what?', 'table', 7),
    tf(2, 'Barzillai’s sons showed David loyalty when he fled from Saul.', false, 7, 'It was "when I fled from Absalom your brother".'),
    mc(3, 'From whom was David fleeing when Barzillai’s family met him with loyalty?', ['Absalom his son', 'Saul', 'Adonijah', 'The Philistines'], 7),
    tf(3, 'Barzillai is called "the Benjaminite" in David’s charge.', false, 7, 'Barzillai is "the Gileadite"; Shimei is the Benjaminite.'),

    // ══════════════════════════════════ v8–9 · Shimei
    mc(1, 'Who cursed David with a grievous curse on the day he went to Mahanaim?', ['Shimei the son of Gera', 'Joab the son of Zeruiah', 'Abner the son of Ner', 'Barzillai the Gileadite'], 8),
    word(2, 'Who was Shimei’s father?', 'Gera', 8),
    word(2, 'Shimei the Benjaminite was from which town?', 'Bahurim', 8),
    blank(2, 'And there is also with you Shim’e-i the son of Gera, the Benjaminite from _____, who cursed me with a grievous curse on the day when I went to Mahana’im;', 'Bahurim', 8),
    mc(2, 'Where was David going on the day Shimei cursed him?', ['Mahanaim', 'Hebron', 'Jerusalem', 'Gath'], 8),
    blank(3, 'but when he came down to meet me at the _____, I swore to him by the LORD, saying, `I will not put you to death with the sword.\'', 'Jordan', 8),
    tf(2, 'David had sworn to Shimei by the LORD, "I will not put you to death with the sword."', true, 8),
    tf(3, 'Shimei came down to meet David at the brook Kidron.', false, 8, 'He met David "at the Jordan".'),
    word(3, 'Shimei is identified as belonging to which tribe (the "___ite")?', 'Benjaminite', 8, ['benjamite', 'benjamin']),
    blank(2, 'Now therefore hold him not guiltless, for you are a _____ man; you will know what you ought to do to him,', 'wise', 9),
    mc(1, 'What did David tell Solomon to do about Shimei?', ['Hold him not guiltless and bring his gray head down with blood to Sheol', 'Deal loyally with him and let him be among those who ate at the king’s table', 'Send him from Jerusalem to his former home among the people of Bahurim', 'Honor the oath David made and permanently forgive the grievous curse'], 9),
    tf(1, 'David told Solomon to hold Shimei guiltless.', false, 9, 'David said "hold him not guiltless … you shall bring his gray head down with blood to Sheol."'),
    blank(3, 'you will know what you ought to do to him, and you shall bring his gray head down with _____ to Sheol.', 'blood', 9),

    // ══════════════════════════════════ v10–12 · David’s death
    blank(1, 'Then David slept with his fathers, and was buried in the city of _____.', 'David', 10),
    blank(1, 'Then David _____ with his fathers, and was buried in the city of David.', 'slept', 10),
    mc(1, 'Where was David buried?', ['In the city of David', 'In Hebron', 'In Bethlehem', 'In Mahanaim'], 10),
    tf(1, 'David was buried in Hebron.', false, 10, 'He "was buried in the city of David".'),
    word(1, 'The text says David "slept with his ___".', 'fathers', 10),
    mc(1, 'How long did David reign over Israel in total?', ['Forty years', 'Thirty-three years', 'Seven years', 'Fifty years'], 11),
    word(2, 'How many years did David reign in Hebron?', 'seven', 11, ['7']),
    word(2, 'How many years did David reign in Jerusalem?', 'thirty-three', 11, ['33', 'thirty three']),
    blank(2, 'And the time that David reigned over Israel was _____ years; he reigned seven years in Hebron, and thirty-three years in Jerusalem.', 'forty', 11, ['40']),
    blank(3, 'he reigned seven years in _____, and thirty-three years in Jerusalem.', 'Hebron', 11),
    tf(2, 'David reigned seven years in Jerusalem and thirty-three years in Hebron.', false, 11, 'It was seven years in Hebron and thirty-three in Jerusalem.'),
    mc(3, 'In which city did David reign for seven years?', ['Hebron', 'Jerusalem', 'Mahanaim', 'Gath'], 11),
    blank(1, 'So Solomon sat upon the throne of David his father; and his kingdom was firmly _____.', 'established', 12),
    blank(1, 'So Solomon sat upon the _____ of David his father;', 'throne', 12),
    tf(1, 'After David’s death, Solomon’s kingdom was firmly established.', true, 12),
    word(1, 'Solomon sat upon the ___ of David his father.', 'throne', 12),

    // ══════════════════════════════════ v13–18 · Adonijah asks Bathsheba
    mc(1, 'Who came to Bathsheba and was asked, "Do you come peaceably?"', ['Adonijah the son of Haggith', 'Joab the son of Zeruiah', 'Abiathar the priest of the LORD', 'Shimei the son of Gera'], 13),
    blank(1, 'Then Adoni’jah the son of Haggith came to Bathshe’ba the mother of Solomon. And she said, "Do you come _____?" He said, "Peaceably."', 'peaceably', 13),
    word(1, 'How did Adonijah say he had come when Bathsheba questioned him?', 'Peaceably', 13),
    tf(2, 'Bathsheba asked Adonijah, "Do you come peaceably?"', true, 13),
    blank(2, 'Then he said, "I have something to say to you." She said, "_____."', 'Say on', 14),
    mc(1, 'How did Bathsheba reply when Adonijah said "I have something to say to you"?', ['"Say on."', '"Speak quickly."', '"What do you desire?"', '"Go to the king."'], 14),
    tf(3, 'When Adonijah said he had something to say, Bathsheba refused to hear him.', false, 14, 'She said, "Say on."'),
    mc(1, 'What did Adonijah claim about the kingdom when speaking to Bathsheba?', ['That it was his and all Israel expected him to reign, but it turned to his brother from the LORD', 'That it had always belonged to Solomon because all Israel had expected his brother to reign', 'That Joab and Abiathar had received the kingdom from the LORD and would share its throne', 'That David had given the kingdom to Bathsheba because she had asked for it on Solomon’s behalf'], 15),
    blank(2, 'You know that the kingdom was mine, and that all _____ fully expected me to reign;', 'Israel', 15),
    blank(3, 'however the kingdom has turned about and become my brother’s, for it was his from the _____.', 'LORD', 15, ['lord']),
    tf(2, 'Adonijah admitted that the kingdom had become Solomon’s "from the LORD".', true, 15),
    word(3, 'Adonijah said the kingdom had "turned about" and become whose?', 'brother’s', 15, ['brothers', 'his brothers', 'solomons', 'solomon']),
    blank(2, 'And now I have one _____ to make of you; do not refuse me." She said to him, "Say on."', 'request', 16),
    tf(2, 'Adonijah told Bathsheba he had two requests to make of her.', false, 16, 'He said, "I have one request to make of you."'),
    mc(3, 'What did Adonijah add after telling Bathsheba he had one request?', ['"do not refuse me"', '"the king will listen to you"', '"it is a small thing"', '"I ask it for the LORD’s sake"'], 16),
    mc(1, 'What did Adonijah ask Bathsheba to request from Solomon?', ['Abishag the Shunammite as his wife', 'A share of the kingdom', 'The city of Hebron', 'Pardon for Joab'], 17),
    blank(1, 'Pray ask King Solomon -- he will not refuse you -- to give me Ab’ishag the Shu’nammite as my _____.', 'wife', 17),
    word(1, 'Adonijah wanted which woman as his wife?', 'Abishag', 17),
    tf(2, 'Adonijah told Bathsheba that Solomon "will not refuse you".', true, 17),
    blank(1, 'Bathshe’ba said, "Very well; I will speak for you to the _____."', 'king', 18),
    tf(1, 'Bathsheba agreed to speak to the king on Adonijah’s behalf.', true, 18),
    mc(1, 'How did Bathsheba respond to Adonijah’s request?', ['"Very well; I will speak for you to the king."', '"I will not ask this of my son, the king."', '"Go and make your request directly to King Solomon."', '"The king has already sworn that he will refuse you."'], 18),

    // ══════════════════════════════════ v19–25 · Bathsheba before Solomon; Adonijah dies
    mc(1, 'What did King Solomon do when Bathsheba came to him?', ['Rose to meet her, bowed down to her, and had a seat brought for her', 'Remained on his throne and commanded his mother to stand before him', 'Sent his mother away and summoned Benaiah the son of Jehoiada', 'Rose from his throne and sent Bathsheba to speak with Adonijah'], 19),
    blank(2, 'And the king rose to meet her, and bowed down to her; then he sat on his throne, and had a seat brought for the king’s _____; and she sat on his right.', 'mother', 19),
    blank(3, 'So Bathshe’ba went to King Solomon, to speak to him on behalf of _____.', 'Adonijah', 19),
    word(2, 'Bathsheba sat on which side of Solomon?', 'right', 19, ['right hand', 'his right']),
    tf(2, 'Bathsheba sat at Solomon’s left hand.', false, 19, '"she sat on his right."'),
    tf(3, 'Solomon bowed down to his mother Bathsheba.', true, 19),
    blank(2, 'Then she said, "I have one _____ request to make of you; do not refuse me."', 'small', 20),
    blank(3, 'And the king said to her, "Make your request, my _____; for I will not refuse you."', 'mother', 20),
    mc(2, 'What did Solomon say to Bathsheba before hearing her request?', ['"Make your request, my mother; for I will not refuse you."', '"Tell me your request, but I cannot promise to grant it."', '"Speak first to Benaiah, for he will decide this matter."', '"Ask what you desire, and Abiathar shall answer for me."'], 20),
    word(3, 'Bathsheba described her request to Solomon as "one ___ request".', 'small', 20),
    blank(1, 'She said, "Let Ab’ishag the Shu’nammite be given to Adoni’jah your _____ as his wife."', 'brother', 21),
    mc(1, 'What did Bathsheba ask Solomon for?', ['That Abishag the Shunammite be given to Adonijah as his wife', 'That Adonijah the son of Haggith be placed over the king’s army', 'That Joab the son of Zeruiah be forgiven and restored as commander', 'That Shimei the son of Gera be released from his oath to the LORD'], 21),
    tf(1, 'Bathsheba asked that Abishag be given to Adonijah as his wife.', true, 21),
    mc(1, 'How did Solomon react to the request for Abishag?', ['"Ask for him the kingdom also"', '"It shall be done as you say"', '"Let Nathan decide"', '"Abishag belongs to me"'], 22),
    blank(2, 'And why do you ask Ab’ishag the Shu’nammite for Adoni’jah? Ask for him the _____ also; for he is my elder brother,', 'kingdom', 22),
    blank(3, 'for he is my elder brother, and on his side are Abi’athar the priest and Jo’ab the son of _____."', 'Zeruiah', 22),
    mc(3, 'Whom did Solomon say were on Adonijah’s side?', ['Abiathar the priest and Joab the son of Zeruiah', 'Zadok the priest and Benaiah the son of Jehoiada', 'Nathan the prophet and Shimei the son of Gera', 'Barzillai the Gileadite and the sons who ate at the table'], 22),
    tf(2, 'Solomon called Adonijah his "elder brother".', true, 22),
    word(3, 'Solomon said Joab and which priest were on Adonijah’s side?', 'Abiathar', 22),
    tf(3, 'Solomon said Zadok the priest was on Adonijah’s side.', false, 22, 'He named "Abiathar the priest and Joab the son of Zeruiah".'),
    blank(2, 'Then King Solomon swore by the LORD, saying, "God do so to me and more also if this word does not cost Adoni’jah his _____!', 'life', 23),
    tf(2, 'Solomon swore by the LORD that Adonijah’s request would cost him his life.', true, 23),
    mc(3, 'What oath formula did Solomon use when swearing against Adonijah?', ['"God do so to me and more also if this word does not cost Adonijah his life!"', '"The LORD judge between me and Adonijah if I do not grant this request today!"', '"May Adonijah’s blood be upon his own head if he leaves the city of Jerusalem!"', '"As the LORD lives, Joab and Abiathar shall answer for every word spoken here!"'], 23),
    word(2, 'By whom did King Solomon swear concerning Adonijah?', 'the LORD', 23, ['lord', 'god']),
    blank(3, 'Now therefore as the LORD lives, who has established me, and placed me on the throne of David my father, and who has made me a _____, as he promised, Adoni’jah shall be put to death this day."', 'house', 24),
    mc(2, 'When did Solomon say Adonijah would be put to death?', ['This day', 'At the new moon', 'After the mourning for David', 'When Joab was found'], 24),
    word(2, 'Solomon said Adonijah "shall be put to death this ___".', 'day', 24),
    mc(1, 'Whom did Solomon send to strike down Adonijah?', ['Benaiah the son of Jehoiada', 'Joab the son of Zeruiah', 'Zadok the priest', 'Shimei the son of Gera'], 25),
    blank(1, 'So King Solomon sent Benai’ah the son of _____; and he struck him down, and he died.', 'Jehoiada', 25),
    blank(1, 'So King Solomon sent Benai’ah the son of Jehoi’ada; and he struck him down, and he _____.', 'died', 25),
    tf(1, 'Adonijah was struck down by Joab and died.', false, 25, 'Solomon sent Benaiah the son of Jehoiada, who struck him down.'),
    word(1, 'Who struck down Adonijah?', 'Benaiah', 25),

    // ══════════════════════════════════ v26–27 · Abiathar banished
    mc(1, 'Where did Solomon send Abiathar the priest?', ['To Anathoth, to his estate', 'To Shiloh, to the house of Eli', 'To Gath, to the court of King Achish', 'To Hebron, where David had reigned'], 26),
    blank(1, 'And to Abi’athar the priest the king said, "Go to _____, to your estate; for you deserve death.', 'Anathoth', 26),
    mc(2, 'Why did Solomon spare Abiathar’s life?', ['He bore the ark before David and shared in all David’s affliction', 'Bathsheba pleaded for him after presenting Adonijah’s request', 'He was the brother of Zadok, whom Solomon appointed in his place', 'He had anointed Solomon at Gihon and placed him on David’s throne'], 26),
    word(3, 'Abiathar had borne what before David?', 'ark', 26, ['the ark', 'ark of the lord', 'ark of the lord god']),
    tf(2, 'Solomon told Abiathar, "you deserve death."', true, 26),
    tf(2, 'Solomon put Abiathar the priest to death.', false, 26, '"I will not at this time put you to death" — he sent him to Anathoth.'),
    blank(3, 'But I will not at this time put you to death, because you bore the ark of the Lord GOD before David my father, and because you shared in all the _____ of my father."', 'affliction', 26),
    blank(3, 'So Solomon expelled Abi’athar from being priest to the LORD, thus fulfilling the word of the LORD which he had spoken concerning the house of Eli in _____.', 'Shiloh', 27),
    mc(2, 'The expulsion of Abiathar fulfilled the LORD’s word concerning which house?', ['The house of Eli in Shiloh', 'The house of Saul', 'The house of Joab', 'The house of Zadok'], 27),
    word(2, 'Abiathar’s expulsion fulfilled the word spoken about the house of whom?', 'Eli', 27),

    // ══════════════════════════════════ v28–35 · Joab dies
    mc(1, 'Where did Joab flee when the news reached him?', ['To the tent of the LORD, grasping the horns of the altar', 'To Gath, seeking protection from Achish son of Maacah', 'To Anathoth, seeking refuge at Abiathar’s estate', 'To his own house in the wilderness outside Jerusalem'], 28),
    blank(1, 'Jo’ab fled to the tent of the LORD and caught hold of the horns of the _____.', 'altar', 28),
    blank(3, 'When the news came to Jo’ab -- for Jo’ab had supported Adoni’jah although he had not supported _____ --', 'Absalom', 28),
    tf(2, 'Joab had supported both Adonijah and Absalom.', false, 28, 'He supported Adonijah "although he had not supported Absalom".'),
    word(2, 'Joab caught hold of the ___ of the altar.', 'horns', 28),
    blank(2, 'Solomon sent Benai’ah the son of Jehoi’ada, saying, "Go, _____ him down."', 'strike', 29),
    mc(1, 'What order did Solomon give Benaiah concerning Joab at the altar?', ['"Go, strike him down."', '"Bring him to me alive."', '"Let him stay at the altar."', '"Send him to Anathoth."'], 29),
    tf(1, 'Solomon sent Benaiah to strike Joab down.', true, 29),
    word(2, 'Solomon was told Joab had fled to the tent of the LORD and was beside the what?', 'altar', 29, ['the altar']),
    mc(1, 'What did Joab answer when Benaiah said, "The king commands, Come forth"?', ['"No, I will die here."', '"I will go to the king."', '"Spare me, for I served David."', '"Let Solomon come to me."'], 30),
    blank(2, 'So Benai’ah came to the tent of the LORD, and said to him, "The king commands, `Come _____.\'"', 'forth', 30),
    blank(3, 'But he said, "No, I will _____ here."', 'die', 30),
    tf(2, 'Joab agreed to come out of the tent when Benaiah commanded him.', false, 30, 'He said, "No, I will die here."'),
    word(3, 'After Joab refused to come out, Benaiah brought the king ___ again.', 'word', 30),
    tf(3, 'Benaiah struck Joab down immediately without reporting back to the king.', false, 30, 'He first "brought the king word again", and only then did Solomon tell him to do as Joab had said.'),
    blank(2, 'The king replied to him, "Do as he has said, strike him down and _____ him;', 'bury', 31),
    mc(1, 'What did Solomon tell Benaiah to do with Joab after striking him down?', ['Bury him', 'Hang his body on the wall', 'Leave him at the altar', 'Send his body to Hebron'], 31),
    mc(3, 'What did Solomon say Joab’s death would take away?', ['The guilt for the blood Joab shed without cause, from Solomon and his father’s house', 'The grievous curse Shimei spoke against David when he traveled toward Mahanaim', 'The threat posed by Adonijah’s alliance with Abiathar the priest and Joab', 'The disloyalty of Absalom when David fled and Barzillai’s sons met him'], 31),
    tf(2, 'Solomon said Joab had shed blood "without cause".', true, 31),
    word(3, 'Solomon wanted to take away from his father’s house the ___ for the blood Joab shed.', 'guilt', 31),
    mc(2, 'Solomon said Joab slew two men "more righteous and better than himself". Who were they?', ['Abner the son of Ner and Amasa the son of Jether', 'Absalom the son of David and Amnon his brother', 'Adonijah the son of Haggith and Abiathar the priest', 'Shimei the son of Gera and Achish the son of Maacah'], 32),
    blank(3, 'Abner the son of Ner, commander of the army of Israel, and Ama’sa the son of Jether, commander of the army of _____.', 'Judah', 32),
    word(3, 'Abner was commander of the army of which people?', 'Israel', 32),
    word(3, 'Amasa was commander of the army of which people?', 'Judah', 32),
    tf(3, 'Solomon said Joab killed Abner and Amasa with David’s knowledge.', false, 32, 'It was "without the knowledge of my father David".'),
    blank(3, 'The LORD will bring back his bloody deeds upon his own _____,', 'head', 32),
    tf(2, 'Solomon said Joab attacked and slew Abner and Amasa with the sword.', true, 32),
    blank(3, 'So shall their blood come back upon the head of Jo’ab and upon the head of his _____ for ever;', 'descendants', 33),
    blank(3, 'but to David, and to his descendants, and to his house, and to his throne, there shall be _____ from the LORD for evermore."', 'peace', 33),
    mc(3, 'What did Solomon say there would be for David, his descendants, his house, and his throne "for evermore"?', ['Peace from the LORD', 'Victory over enemies', 'A priest of Zadok’s line', 'Riches and honor'], 33),
    word(2, 'Solomon said there shall be ___ from the LORD for David’s throne for evermore.', 'peace', 33),
    mc(2, 'Where was Joab buried?', ['In his own house in the wilderness', 'In the city of David', 'In Hebron', 'Beside the altar'], 34),
    blank(2, 'Then Benai’ah the son of Jehoi’ada went up, and struck him down and killed him; and he was buried in his own house in the _____.', 'wilderness', 34),
    tf(2, 'Joab was buried in the city of David.', false, 34, 'He "was buried in his own house in the wilderness".'),
    word(1, 'Joab was buried in his own house in what kind of place?', 'wilderness', 34, ['the wilderness']),
    mc(1, 'Who replaced Joab over the army?', ['Benaiah the son of Jehoiada', 'Zadok the priest who replaced Abiathar', 'Abner the son of Ner, commander of Israel', 'Amasa the son of Jether, commander of Judah'], 35),
    mc(1, 'Who replaced Abiathar as priest?', ['Zadok', 'Benaiah', 'Nathan', 'Eli'], 35),
    blank(1, 'The king put Benai’ah the son of Jehoi’ada over the army in place of Jo’ab, and the king put _____ the priest in the place of Abi’athar.', 'Zadok', 35),
    tf(1, 'Zadok the priest took the place of Abiathar.', true, 35),
    tf(2, 'Solomon put Zadok over the army in place of Joab.', false, 35, 'Benaiah was put over the army; Zadok replaced Abiathar as priest.'),
    word(1, 'Whom did Solomon put over the army in place of Joab?', 'Benaiah', 35),

    // ══════════════════════════════════ v36–46 · Shimei
    mc(1, 'Where did Solomon command Shimei to build a house and dwell?', ['Jerusalem', 'Bahurim', 'Gath', 'Hebron'], 36),
    blank(1, 'Build yourself a house in _____, and dwell there, and do not go forth from there to any place whatever.', 'Jerusalem', 36),
    blank(1, 'Then the king sent and summoned _____, and said to him, "Build yourself a house in Jerusalem, and dwell there,', 'Shim’e-i', 36, ['shimei', 'shim e i']),
    tf(1, 'Solomon told Shimei to build a house in Jerusalem and not go forth from there.', true, 36),
    word(1, 'Solomon told Shimei to build himself a ___ in Jerusalem.', 'house', 36),
    mc(1, 'Which brook did Solomon warn Shimei not to cross?', ['Kidron', 'Jordan', 'Jabbok', 'Cherith'], 37),
    blank(2, 'For on the day you go forth, and cross the brook _____, know for certain that you shall die;', 'Kidron', 37),
    word(2, 'What did Solomon say would happen to Shimei on the day he crossed the brook Kidron?', 'die', 37, ['death', 'he shall die', 'he would die', 'you shall die']),
    tf(3, 'Solomon said that if Shimei crossed the brook Kidron, his blood would be upon his own head.', true, 37),
    tf(3, 'Solomon warned Shimei not to cross the Jordan.', false, 37, 'The boundary was "the brook Kidron".'),
    blank(2, 'And Shim’e-i said to the king, "What you say is _____; as my lord the king has said, so will your servant do."', 'good', 38),
    mc(1, 'How did Shimei respond to Solomon’s command?', ['"What you say is good; as my lord the king has said, so will your servant do."', '"I have done no evil to David your father and deserve no commandment from you."', '"Let me return to Bahurim rather than build a house and remain in Jerusalem."', '"The king’s judgment is unjust, and I will cross the brook Kidron this day."'], 38),
    tf(2, 'Shimei dwelt in Bahurim many days.', false, 38, '"Shimei dwelt in Jerusalem many days."'),
    word(3, 'Shimei "dwelt in Jerusalem many ___".', 'days', 38),
    mc(1, 'After how many years did two of Shimei’s slaves run away?', ['Three years', 'Seven years', 'Forty years', 'One year'], 39),
    word(2, 'How many of Shimei’s slaves ran away?', 'two', 39, ['2']),
    word(2, 'To which king did Shimei’s slaves flee?', 'Achish', 39),
    blank(3, 'But it happened at the end of _____ years that two of Shim’e-i’s slaves ran away to Achish, son of Ma’acah, king of Gath.', 'three', 39, ['3']),
    mc(3, 'Achish, king of Gath, was the son of whom?', ['Maacah', 'Gera', 'Jether', 'Ner'], 39),
    tf(2, 'Three of Shimei’s slaves ran away to Gath.', false, 39, 'It was "two of Shimei’s slaves".'),
    blank(3, 'And when it was told Shim’e-i, "Behold, your slaves are in _____,"', 'Gath', 39),
    mc(1, 'What animal did Shimei saddle to go to Gath?', ['An ass', 'A horse', 'A camel', 'A mule'], 40),
    blank(1, 'Shim’e-i arose and saddled an _____, and went to Gath to Achish, to seek his slaves;', 'ass', 40, ['donkey']),
    blank(1, 'Shim’e-i went and brought his slaves from _____.', 'Gath', 40),
    tf(1, 'Shimei went to Gath and brought back his slaves.', true, 40),
    word(1, 'Shimei went to Gath to seek his what?', 'slaves', 40, ['servants']),
    tf(3, 'Shimei sent his servants to Gath to fetch the runaway slaves while he stayed in Jerusalem.', false, 40, 'Shimei himself "arose and saddled an ass, and went to Gath".'),
    blank(1, 'And when Solomon was told that Shim’e-i had gone from Jerusalem to _____ and returned,', 'Gath', 41),
    mc(3, 'What was Solomon told about Shimei?', ['That he had gone from Jerusalem to Gath and returned', 'That he had cursed the king', 'That he had fled to Achish for refuge', 'That he had crossed the Jordan'], 41),
    tf(2, 'Solomon was told that Shimei had gone from Jerusalem to Gath and returned.', true, 41),
    blank(3, 'Did I not make you swear by the LORD, and solemnly _____ you, saying,', 'admonish', 42),
    mc(2, 'According to Solomon, what had Shimei said in reply — "What you say is good; ___"?', ['"I obey."', '"so be it."', '"I will not go."', '"the king is wise."'], 42),
    blank(3, 'And you said to me, `What you say is good; I _____.\'', 'obey', 42),
    word(3, 'Solomon said he had "solemnly ___" Shimei — what verb?', 'admonish', 42, ['admonished']),
    blank(1, 'Why then have you not kept your _____ to the LORD and the commandment with which I charged you?"', 'oath', 43),
    mc(2, 'What two things did Solomon accuse Shimei of not keeping?', ['His oath to the LORD and the commandment Solomon charged him with', 'The law of Moses and the charge David had given before his death', 'His promise to Achish and his obligation to remain with his slaves in Gath', 'His loyalty to David and his agreement to eat at King Solomon’s table'], 43),
    tf(3, 'Solomon accused Shimei of failing to keep his oath to David.', false, 43, 'It was "your oath to the LORD".'),
    word(2, 'Solomon asked Shimei why he had not kept the ___ with which he charged him.', 'commandment', 43),
    blank(1, 'You know in your own heart all the evil that you did to _____ my father; so the LORD will bring back your evil upon your own head.', 'David', 44),
    mc(1, 'What did Solomon say the LORD would do about the evil Shimei did to David?', ['Bring back his evil upon his own head', 'Forgive it because of Shimei’s oath', 'Visit it upon his sons', 'Remember it no more'], 44),
    word(3, 'Solomon said Shimei knew the evil he did to David "in your own ___".', 'heart', 44),
    blank(3, 'But King Solomon shall be _____, and the throne of David shall be established before the LORD for ever."', 'blessed', 45),
    tf(2, 'Solomon said the throne of David would be established before the LORD for forty years.', false, 45, 'He said "for ever".'),
    mc(3, 'In contrast to Shimei’s fate, what did Solomon declare about himself?', ['"King Solomon shall be blessed"', '"King Solomon shall reign forty years"', '"King Solomon shall build a house for the LORD"', '"King Solomon shall be greater than David"'], 45),
    word(2, 'Solomon said the throne of David would be established before the LORD for how long?', 'ever', 45, ['for ever', 'forever']),
    mc(1, 'Who struck down Shimei?', ['Benaiah the son of Jehoiada', 'Joab the son of Zeruiah', 'Zadok the priest of the LORD', 'Achish the son of Maacah'], 46),
    blank(1, 'Then the king commanded Benai’ah the son of Jehoi’ada; and he went out and struck him down, and he _____.', 'died', 46),
    blank(3, 'Then the king commanded Benai’ah the son of Jehoi’ada; and he went out and _____ him down, and he died.', 'struck', 46),
    tf(1, 'Shimei was struck down by Benaiah and died.', true, 46),
    tf(1, 'Solomon banished Shimei to Gath instead of killing him.', false, 46, 'Benaiah "went out and struck him down, and he died."'),

    // ══════════════════════════════════ Whole-chapter
    mc(3, 'Who said, "No, I will die here"?', ['Joab', 'Adonijah', 'Shimei', 'Abiathar'], 30),
    mc(2, 'Who said, "What you say is good; as my lord the king has said, so will your servant do"?', ['Shimei', 'Joab', 'Abiathar', 'Bathsheba'], 38),
    word(1, 'Which brother of Solomon was executed in 1 Kings 2?', 'Adonijah', 25),
  ],
};

export default bank;
