// 1 Kings 15 — quiz bank (RSV). Four verse-anchored forms per verse.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: "1 Kings",
  chapter: 15,
  tag: "quiz-v2-1kings-15",
  rows: [
    blank(2, "Now in the eighteenth year of King _____ the son of Nebat, Abi’jam began to reign over Judah.", "Jerobo’am", 1, ["jeroboam"]),
    mc(3, "Which word correctly completes this RSV wording: “Now in the eighteenth year of King _____ the son of Nebat, Abi’jam began to reign over Judah.”", ["Jerobo’am", "David", "Kidron", "Tirzah"], 1),
    word(1, "In verse 1, what word completes this phrase: “Now in the eighteenth year of King _____ the son of Nebat, Abi’jam began to reign over Judah.”?", "Jerobo’am", 1, ["jeroboam"]),
    tf(2, "The RSV states: “Now in the eighteenth year of King Jerobo’am the son of Nebat, Abi’jam began to reign over Judah.”", true, 1),
    blank(3, "three years in Jerusalem. His mother’s name was Ma’acah the daughter of _____.", "Abish’alom", 2, ["abishalom"]),
    mc(1, "Which word correctly completes this RSV wording: “three years in Jerusalem. His mother’s name was Ma’acah the daughter of _____.”", ["Abish’alom", "Israel", "Naph’tali", "Jerobo’am"], 2),
    word(2, "In verse 2, what word completes this phrase: “three years in Jerusalem. His mother’s name was Ma’acah the daughter of _____.”?", "Abish’alom", 2, ["abishalom"]),
    tf(3, "The RSV does not state: “He reigned for three years in Jerusalem. His mother’s name was Ma’acah the daughter of Abish’alom.”", false, 2, "The quoted wording is the RSV text of this verse."),
    blank(1, "and his heart was not wholly true to the LORD his God, as the heart of _____ his father.", "David", 3, ["david"]),
    mc(2, "Which word correctly completes this RSV wording: “and his heart was not wholly true to the LORD his God, as the heart of _____ his father.”", ["David", "Tabrim’mon", "Ahi’jah", "Abish’alom"], 3),
    word(3, "In verse 3, what word completes this phrase: “and his heart was not wholly true to the LORD his God, as the heart of _____ his father.”?", "David", 3, ["david"]),
    tf(1, "The RSV states: “And he walked in all the sins which his father did before him; and his heart was not wholly true to the LORD his God, as the heart of David his father.”", true, 3),
    blank(2, "_____ for David’s sake the LORD his God gave him a lamp in Jerusalem, setting", "Nevertheless", 4, ["nevertheless"]),
    mc(3, "Which word correctly completes this RSV wording: “_____ for David’s sake the LORD his God gave him a lamp in Jerusalem, setting”", ["Nevertheless", "Abish’alom", "Chin’neroth", "Jerusalem"], 4),
    word(1, "In verse 4, what word completes this phrase: “_____ for David’s sake the LORD his God gave him a lamp in Jerusalem, setting”?", "Nevertheless", 4, ["nevertheless"]),
    tf(2, "The RSV does not state: “Nevertheless for David’s sake the LORD his God gave him a lamp in Jerusalem, setting up his son after him, and establishing Jerusalem;”", false, 4, "The quoted wording is the RSV text of this verse."),
    blank(3, "commanded him all the days of his life, except in the matter of Uri’ah the _____.", "Hittite", 5, ["hittite"]),
    mc(1, "Which word correctly completes this RSV wording: “commanded him all the days of his life, except in the matter of Uri’ah the _____.”", ["Hittite", "Ahi’jah", "Ma’acah", "Ashe’rah"], 5),
    word(2, "In verse 5, what word completes this phrase: “commanded him all the days of his life, except in the matter of Uri’ah the _____.”?", "Hittite", 5, ["hittite"]),
    tf(3, "The RSV states: “because David did what was right in the eyes of the LORD, and did not turn aside from anything that he commanded him all the days of his life, except in the matter of Uri’ah the Hittite.”", true, 5),
    blank(1, "Now there was war between _____ and Jerobo’am all the days of his life.", "Rehobo’am", 6, ["rehoboam"]),
    mc(2, "Which word correctly completes this RSV wording: “Now there was war between _____ and Jerobo’am all the days of his life.”", ["Rehobo’am", "Nebat", "Book", "Syria"], 6),
    word(3, "In verse 6, what word completes this phrase: “Now there was war between _____ and Jerobo’am all the days of his life.”?", "Rehobo’am", 6, ["rehoboam"]),
    tf(1, "The RSV does not state: “Now there was war between Rehobo’am and Jerobo’am all the days of his life.”", false, 6, "The quoted wording is the RSV text of this verse."),
    blank(2, "Abi’jam, and all that he did, are they not written in the Book of the _____ of the Kings of Judah? And there was war between Abi’jam and Jerobo’am.", "Chronicles", 7, ["chronicles"]),
    mc(3, "Which word correctly completes this RSV wording: “Abi’jam, and all that he did, are they not written in the Book of the _____ of the Kings of Judah? And there was war between Abi’jam and Jerobo’am.”", ["Chronicles", "Kings", "Chin’neroth", "Shi’lonite"], 7),
    word(1, "In verse 7, what word completes this phrase: “Abi’jam, and all that he did, are they not written in the Book of the _____ of the Kings of Judah? And there was war between Abi’jam and Jerobo’am.”?", "Chronicles", 7, ["chronicles"]),
    tf(2, "The RSV states: “The rest of the acts of Abi’jam, and all that he did, are they not written in the Book of the Chronicles of the Kings of Judah? And there was war between Abi’jam and Jerobo’am.”", true, 7),
    blank(3, "And _____ slept with his fathers; and they buried him in the city of David. And", "Abi’jam", 8, ["abijam"]),
    mc(1, "Which word correctly completes this RSV wording: “And _____ slept with his fathers; and they buried him in the city of David. And”", ["Abi’jam", "Israel", "Chin’neroth", "Philistines"], 8),
    word(2, "In verse 8, what word completes this phrase: “And _____ slept with his fathers; and they buried him in the city of David. And”?", "Abi’jam", 8, ["abijam"]),
    tf(3, "The RSV does not state: “And Abi’jam slept with his fathers; and they buried him in the city of David. And Asa his son reigned in his stead.”", false, 8, "The quoted wording is the RSV text of this verse."),
    blank(1, "In the twentieth year of _____ king of Israel Asa began to reign over Judah,", "Jerobo’am", 9, ["jeroboam"]),
    mc(2, "Which word correctly completes this RSV wording: “In the twentieth year of _____ king of Israel Asa began to reign over Judah,”", ["Jerobo’am", "He’zi-on", "Nadab", "Ma’acah"], 9),
    word(3, "In verse 9, what word completes this phrase: “In the twentieth year of _____ king of Israel Asa began to reign over Judah,”?", "Jerobo’am", 9, ["jeroboam"]),
    tf(1, "The RSV states: “In the twentieth year of Jerobo’am king of Israel Asa began to reign over Judah,”", true, 9),
    blank(2, "forty-one years in Jerusalem. His mother’s name was Ma’acah the daughter of _____.", "Abish’alom", 10, ["abishalom"]),
    mc(3, "Which word correctly completes this RSV wording: “forty-one years in Jerusalem. His mother’s name was Ma’acah the daughter of _____.”", ["Abish’alom", "Philistines", "Uri’ah", "Tabrim’mon"], 10),
    word(1, "In verse 10, what word completes this phrase: “forty-one years in Jerusalem. His mother’s name was Ma’acah the daughter of _____.”?", "Abish’alom", 10, ["abishalom"]),
    tf(2, "The RSV does not state: “and he reigned forty-one years in Jerusalem. His mother’s name was Ma’acah the daughter of Abish’alom.”", false, 10, "The quoted wording is the RSV text of this verse."),
    blank(3, "And Asa did what was right in the eyes of the LORD, as _____ his father had done.", "David", 11, ["david"]),
    mc(1, "Which word correctly completes this RSV wording: “And Asa did what was right in the eyes of the LORD, as _____ his father had done.”", ["David", "Jerusalem", "Ashe’rah", "Tirzah"], 11),
    word(2, "In verse 11, what word completes this phrase: “And Asa did what was right in the eyes of the LORD, as _____ his father had done.”?", "David", 11, ["david"]),
    tf(3, "The RSV states: “And Asa did what was right in the eyes of the LORD, as David his father had done.”", true, 11),
    blank(1, "He put away the male cult _____ out of the land, and removed all the idols that his fathers had made.", "prostitutes", 12, ["prostitutes"]),
    mc(2, "Which word correctly completes this RSV wording: “He put away the male cult _____ out of the land, and removed all the idols that his fathers had made.”", ["prostitutes", "fathers", "silver", "present"], 12),
    word(3, "In verse 12, what word completes this phrase: “He put away the male cult _____ out of the land, and removed all the idols that his fathers had made.”?", "prostitutes", 12, ["prostitutes"]),
    tf(1, "The RSV does not state: “He put away the male cult prostitutes out of the land, and removed all the idols that his fathers had made.”", false, 12, "The quoted wording is the RSV text of this verse."),
    blank(2, "from being queen mother because she had an abominable image made for _____; and Asa cut down her image and burned it at the brook Kidron.", "Ashe’rah", 13, ["asherah"]),
    mc(3, "Which word correctly completes this RSV wording: “from being queen mother because she had an abominable image made for _____; and Asa cut down her image and burned it at the brook Kidron.”", ["Ashe’rah", "Uri’ah", "Tabrim’mon", "Jehosh’aphat"], 13),
    word(1, "In verse 13, what word completes this phrase: “from being queen mother because she had an abominable image made for _____; and Asa cut down her image and burned it at the brook Kidron.”?", "Ashe’rah", 13, ["asherah"]),
    tf(2, "The RSV states: “He also removed Ma’acah his mother from being queen mother because she had an abominable image made for Ashe’rah; and Asa cut down her image and burned it at the brook Kidron.”", true, 13),
    blank(3, "But the high places were not taken away. _____ the heart of Asa was wholly true to the LORD all his days.", "Nevertheless", 14, ["nevertheless"]),
    mc(1, "Which word correctly completes this RSV wording: “But the high places were not taken away. _____ the heart of Asa was wholly true to the LORD all his days.”", ["Nevertheless", "Jerusalem", "He’zi-on", "Jerobo’am"], 14),
    word(2, "In verse 14, what word completes this phrase: “But the high places were not taken away. _____ the heart of Asa was wholly true to the LORD all his days.”?", "Nevertheless", 14, ["nevertheless"]),
    tf(3, "The RSV does not state: “But the high places were not taken away. Nevertheless the heart of Asa was wholly true to the LORD all his days.”", false, 14, "The quoted wording is the RSV text of this verse."),
    blank(1, "And he _____ into the house of the LORD the votive gifts of his father and his own", "brought", 15, ["brought"]),
    mc(2, "Which word correctly completes this RSV wording: “And he _____ into the house of the LORD the votive gifts of his father and his own”", ["brought", "carried", "laying", "servant"], 15),
    word(3, "In verse 15, what word completes this phrase: “And he _____ into the house of the LORD the votive gifts of his father and his own”?", "brought", 15, ["brought"]),
    tf(1, "The RSV states: “And he brought into the house of the LORD the votive gifts of his father and his own votive gifts, silver, and gold, and vessels.”", true, 15),
    blank(2, "And there was war between Asa and _____ king of Israel all their days.", "Ba’asha", 16, ["baasha"]),
    mc(3, "Which word correctly completes this RSV wording: “And there was war between Asa and _____ king of Israel all their days.”", ["Ba’asha", "Mizpah", "Abi’jam", "Book"], 16),
    word(1, "In verse 16, what word completes this phrase: “And there was war between Asa and _____ king of Israel all their days.”?", "Ba’asha", 16, ["baasha"]),
    tf(2, "The RSV does not state: “And there was war between Asa and Ba’asha king of Israel all their days.”", false, 16, "The quoted wording is the RSV text of this verse."),
    blank(3, "_____ king of Israel went up against Judah, and built Ramah, that he might permit", "Ba’asha", 17, ["baasha"]),
    mc(1, "Which word correctly completes this RSV wording: “_____ king of Israel went up against Judah, and built Ramah, that he might permit”", ["Ba’asha", "Shi’lonite", "David’s", "Ben-ha’dad"], 17),
    word(2, "In verse 17, what word completes this phrase: “_____ king of Israel went up against Judah, and built Ramah, that he might permit”?", "Ba’asha", 17, ["baasha"]),
    tf(3, "The RSV states: “Ba’asha king of Israel went up against Judah, and built Ramah, that he might permit no one to go out or come in to Asa king of Judah.”", true, 17),
    blank(1, "and gave them into the hands of his servants; and King Asa sent them to _____ the son of Tabrim’mon, the son of He’zi-on, king of Syria, who dwelt in", "Ben-ha’dad", 18, ["ben-hadad"]),
    mc(2, "Which word correctly completes this RSV wording: “and gave them into the hands of his servants; and King Asa sent them to _____ the son of Tabrim’mon, the son of He’zi-on, king of Syria, who dwelt in”", ["Ben-ha’dad", "Ba’asha", "Jehosh’aphat", "Jerusalem"], 18),
    word(3, "In verse 18, what word completes this phrase: “and gave them into the hands of his servants; and King Asa sent them to _____ the son of Tabrim’mon, the son of He’zi-on, king of Syria, who dwelt in”?", "Ben-ha’dad", 18, ["ben-hadad"]),
    tf(1, "The RSV does not state: “Then Asa took all the silver and the gold that were left in the treasures of the house of the LORD and the treasures of the king’s house, and gave them into the hands of his servants; and King Asa sent them to Ben-ha’dad the son of Tabrim’mon, the son of He’zi-on, king of Syria, who dwelt in Damascus, saying,”", false, 18, "The quoted wording is the RSV text of this verse."),
    blank(2, "sending to you a present of silver and gold; go, break your league with _____ king of Israel, that he may withdraw from me.\"", "Ba’asha", 19, ["baasha"]),
    mc(3, "Which word correctly completes this RSV wording: “sending to you a present of silver and gold; go, break your league with _____ king of Israel, that he may withdraw from me.\"”", ["Ba’asha", "Rehobo’am", "Syria", "Ahi’jah"], 19),
    word(1, "In verse 19, what word completes this phrase: “sending to you a present of silver and gold; go, break your league with _____ king of Israel, that he may withdraw from me.\"”?", "Ba’asha", 19, ["baasha"]),
    tf(2, "The RSV states: “\"Let there be a league between me and you, as between my father and your father: behold, I am sending to you a present of silver and gold; go, break your league with Ba’asha king of Israel, that he may withdraw from me.\"”", true, 19),
    blank(3, "of his armies against the cities of Israel, and conquered Ijon, Dan, _____, and all Chin’neroth, with all the land of Naph’tali.", "A’bel-beth-ma’acah", 20, ["abel-beth-maacah"]),
    mc(1, "Which word correctly completes this RSV wording: “of his armies against the cities of Israel, and conquered Ijon, Dan, _____, and all Chin’neroth, with all the land of Naph’tali.”", ["A’bel-beth-ma’acah", "Jerusalem", "Israel", "Solomon"], 20),
    word(2, "In verse 20, what word completes this phrase: “of his armies against the cities of Israel, and conquered Ijon, Dan, _____, and all Chin’neroth, with all the land of Naph’tali.”?", "A’bel-beth-ma’acah", 20, ["abel-beth-maacah"]),
    tf(3, "The RSV does not state: “And Ben-ha’dad hearkened to King Asa, and sent the commanders of his armies against the cities of Israel, and conquered Ijon, Dan, A’bel-beth-ma’acah, and all Chin’neroth, with all the land of Naph’tali.”", false, 20, "The quoted wording is the RSV text of this verse."),
    blank(1, "And when _____ heard of it, he stopped building Ramah, and he dwelt in Tirzah.", "Ba’asha", 21, ["baasha"]),
    mc(2, "Which word correctly completes this RSV wording: “And when _____ heard of it, he stopped building Ramah, and he dwelt in Tirzah.”", ["Ba’asha", "Chin’neroth", "Philistines", "Nevertheless"], 21),
    word(3, "In verse 21, what word completes this phrase: “And when _____ heard of it, he stopped building Ramah, and he dwelt in Tirzah.”?", "Ba’asha", 21, ["baasha"]),
    tf(1, "The RSV states: “And when Ba’asha heard of it, he stopped building Ramah, and he dwelt in Tirzah.”", true, 21),
    blank(2, "which Ba’asha had been building; and with them King Asa built Geba of _____ and Mizpah.", "Benjamin", 22, ["benjamin"]),
    mc(3, "Which word correctly completes this RSV wording: “which Ba’asha had been building; and with them King Asa built Geba of _____ and Mizpah.”", ["Benjamin", "Nadab", "Jerusalem", "Kings"], 22),
    word(1, "In verse 22, what word completes this phrase: “which Ba’asha had been building; and with them King Asa built Geba of _____ and Mizpah.”?", "Benjamin", 22, ["benjamin"]),
    tf(2, "The RSV does not state: “Then King Asa made a proclamation to all Judah, none was exempt, and they carried away the stones of Ramah and its timber, with which Ba’asha had been building; and with them King Asa built Geba of Benjamin and Mizpah.”", false, 22, "The quoted wording is the RSV text of this verse."),
    blank(3, "and the cities which he built, are they not written in the Book of the _____ of the Kings of Judah? But in his old age he was diseased in his feet.", "Chronicles", 23, ["chronicles"]),
    mc(1, "Which word correctly completes this RSV wording: “and the cities which he built, are they not written in the Book of the _____ of the Kings of Judah? But in his old age he was diseased in his feet.”", ["Chronicles", "Ba’asha", "Mizpah", "Judah"], 23),
    word(2, "In verse 23, what word completes this phrase: “and the cities which he built, are they not written in the Book of the _____ of the Kings of Judah? But in his old age he was diseased in his feet.”?", "Chronicles", 23, ["chronicles"]),
    tf(3, "The RSV states: “Now the rest of all the acts of Asa, all his might, and all that he did, and the cities which he built, are they not written in the Book of the Chronicles of the Kings of Judah? But in his old age he was diseased in his feet.”", true, 23),
    blank(1, "and was buried with his fathers in the city of David his father; and _____ his son reigned in his stead.", "Jehosh’aphat", 24, ["jehoshaphat"]),
    mc(2, "Which word correctly completes this RSV wording: “and was buried with his fathers in the city of David his father; and _____ his son reigned in his stead.”", ["Jehosh’aphat", "Jerobo’am", "Ba’asha", "Philistines"], 24),
    word(3, "In verse 24, what word completes this phrase: “and was buried with his fathers in the city of David his father; and _____ his son reigned in his stead.”?", "Jehosh’aphat", 24, ["jehoshaphat"]),
    tf(1, "The RSV does not state: “And Asa slept with his fathers, and was buried with his fathers in the city of David his father; and Jehosh’aphat his son reigned in his stead.”", false, 24, "The quoted wording is the RSV text of this verse."),
    blank(2, "Nadab the son of _____ began to reign over Israel in the second year of Asa king of Judah; and", "Jerobo’am", 25, ["jeroboam"]),
    mc(3, "Which word correctly completes this RSV wording: “Nadab the son of _____ began to reign over Israel in the second year of Asa king of Judah; and”", ["Jerobo’am", "Kings", "Ijon", "Gib’bethon"], 25),
    word(1, "In verse 25, what word completes this phrase: “Nadab the son of _____ began to reign over Israel in the second year of Asa king of Judah; and”?", "Jerobo’am", 25, ["jeroboam"]),
    tf(2, "The RSV states: “Nadab the son of Jerobo’am began to reign over Israel in the second year of Asa king of Judah; and he reigned over Israel two years.”", true, 25),
    blank(3, "LORD, and walked in the way of his father, and in his sin which he made _____ to sin.", "Israel", 26, ["israel"]),
    mc(1, "Which word correctly completes this RSV wording: “LORD, and walked in the way of his father, and in his sin which he made _____ to sin.”", ["Israel", "Benjamin", "Abi’jam", "Chronicles"], 26),
    word(2, "In verse 26, what word completes this phrase: “LORD, and walked in the way of his father, and in his sin which he made _____ to sin.”?", "Israel", 26, ["israel"]),
    tf(3, "The RSV does not state: “He did what was evil in the sight of the LORD, and walked in the way of his father, and in his sin which he made Israel to sin.”", false, 26, "The quoted wording is the RSV text of this verse."),
    blank(1, "him; and Ba’asha struck him down at Gib’bethon, which belonged to the _____; for Nadab and all Israel were laying siege to Gib’bethon.", "Philistines", 27, ["philistines"]),
    mc(2, "Which word correctly completes this RSV wording: “him; and Ba’asha struck him down at Gib’bethon, which belonged to the _____; for Nadab and all Israel were laying siege to Gib’bethon.”", ["Philistines", "Ben-ha’dad", "Is’sachar", "Hittite"], 27),
    word(3, "In verse 27, what word completes this phrase: “him; and Ba’asha struck him down at Gib’bethon, which belonged to the _____; for Nadab and all Israel were laying siege to Gib’bethon.”?", "Philistines", 27, ["philistines"]),
    tf(1, "The RSV states: “Ba’asha the son of Ahi’jah, of the house of Is’sachar, conspired against him; and Ba’asha struck him down at Gib’bethon, which belonged to the Philistines; for Nadab and all Israel were laying siege to Gib’bethon.”", true, 27),
    blank(2, "So _____ killed him in the third year of Asa king of Judah, and reigned in his", "Ba’asha", 28, ["baasha"]),
    mc(3, "Which word correctly completes this RSV wording: “So _____ killed him in the third year of Asa king of Judah, and reigned in his”", ["Ba’asha", "Is’sachar", "Abish’alom", "Ashe’rah"], 28),
    word(1, "In verse 28, what word completes this phrase: “So _____ killed him in the third year of Asa king of Judah, and reigned in his”?", "Ba’asha", 28, ["baasha"]),
    tf(2, "The RSV does not state: “So Ba’asha killed him in the third year of Asa king of Judah, and reigned in his stead.”", false, 28, "The quoted wording is the RSV text of this verse."),
    blank(3, "according to the word of the LORD which he spoke by his servant Ahi’jah the _____;", "Shi’lonite", 29, ["shilonite"]),
    mc(1, "Which word correctly completes this RSV wording: “according to the word of the LORD which he spoke by his servant Ahi’jah the _____;”", ["Shi’lonite", "Syria", "Gib’bethon", "David’s"], 29),
    word(2, "In verse 29, what word completes this phrase: “according to the word of the LORD which he spoke by his servant Ahi’jah the _____;”?", "Shi’lonite", 29, ["shilonite"]),
    tf(3, "The RSV states: “And as soon as he was king, he killed all the house of Jerobo’am; he left to the house of Jerobo’am not one that breathed, until he had destroyed it, according to the word of the LORD which he spoke by his servant Ahi’jah the Shi’lonite;”", true, 29),
    blank(1, "it was for the sins of _____ which he sinned and which he made Israel to sin, and because of the anger", "Jerobo’am", 30, ["jeroboam"]),
    mc(2, "Which word correctly completes this RSV wording: “it was for the sins of _____ which he sinned and which he made Israel to sin, and because of the anger”", ["Jerobo’am", "Uri’ah", "Ben-ha’dad", "Mizpah"], 30),
    word(3, "In verse 30, what word completes this phrase: “it was for the sins of _____ which he sinned and which he made Israel to sin, and because of the anger”?", "Jerobo’am", 30, ["jeroboam"]),
    tf(1, "The RSV does not state: “it was for the sins of Jerobo’am which he sinned and which he made Israel to sin, and because of the anger to which he provoked the LORD, the God of Israel.”", false, 30, "The quoted wording is the RSV text of this verse."),
    blank(2, "of Nadab, and all that he did, are they not written in the Book of the _____ of the Kings of Israel?", "Chronicles", 31, ["chronicles"]),
    mc(3, "Which word correctly completes this RSV wording: “of Nadab, and all that he did, are they not written in the Book of the _____ of the Kings of Israel?”", ["Chronicles", "Nebat", "Rehobo’am", "Damascus"], 31),
    word(1, "In verse 31, what word completes this phrase: “of Nadab, and all that he did, are they not written in the Book of the _____ of the Kings of Israel?”?", "Chronicles", 31, ["chronicles"]),
    tf(2, "The RSV states: “Now the rest of the acts of Nadab, and all that he did, are they not written in the Book of the Chronicles of the Kings of Israel?”", true, 31),
    word(2, "In verse 32, what word completes this phrase: “And there was war between Asa and _____ king of Israel all their days.”?", "Ba’asha", 32, ["baasha"]),
    blank(1, "In the third year of Asa king of Judah, _____ the son of Ahi’jah began to reign over all Israel at Tirzah, and reigned", "Ba’asha", 33, ["baasha"]),
    mc(2, "Which word correctly completes this RSV wording: “In the third year of Asa king of Judah, _____ the son of Ahi’jah began to reign over all Israel at Tirzah, and reigned”", ["Ba’asha", "Benjamin", "Nebat", "Rehobo’am"], 33),
    word(3, "In verse 33, what word completes this phrase: “In the third year of Asa king of Judah, _____ the son of Ahi’jah began to reign over all Israel at Tirzah, and reigned”?", "Ba’asha", 33, ["baasha"]),
    tf(1, "The RSV states: “In the third year of Asa king of Judah, Ba’asha the son of Ahi’jah began to reign over all Israel at Tirzah, and reigned twenty-four years.”", true, 33),
    blank(2, "did what was evil in the sight of the LORD, and walked in the way of _____ and in his sin which he made Israel to sin.", "Jerobo’am", 34, ["jeroboam"]),
    mc(3, "Which word correctly completes this RSV wording: “did what was evil in the sight of the LORD, and walked in the way of _____ and in his sin which he made Israel to sin.”", ["Jerobo’am", "Philistines", "David’s", "Ramah"], 34),
    word(1, "In verse 34, what word completes this phrase: “did what was evil in the sight of the LORD, and walked in the way of _____ and in his sin which he made Israel to sin.”?", "Jerobo’am", 34, ["jeroboam"]),
    tf(2, "The RSV does not state: “He did what was evil in the sight of the LORD, and walked in the way of Jerobo’am and in his sin which he made Israel to sin.”", false, 34, "The quoted wording is the RSV text of this verse."),
    mc(3, "Why did the LORD give Abijam a lamp in Jerusalem despite his sins?", ["For David’s sake, because David had done what was right except in the matter of Uriah", "Because Abijam destroyed the high places", "Because Asa interceded for him", "Because Israel had no other heir"], 5),
    mc(2, "Why did Asa remove Maacah from being queen mother?", ["She had made an abominable image for Asherah", "She supported Baasha", "She took gold from the temple", "She rebuilt Jericho"], 13),
    mc(3, "How did Asa respond when Baasha fortified Ramah?", ["He sent temple and palace silver and gold to Ben-hadad to break his league with Baasha", "He surrendered Jerusalem to Baasha", "He asked Egypt to invade Israel", "He abandoned the cities of Judah"], 18),
    mc(1, "What illness troubled Asa in his old age?", ["A disease in his feet", "Blindness", "Leprosy", "A disease in his hands"], 23),
    mc(2, "Who conspired against Nadab, killed him at Gibbethon, and destroyed Jeroboam’s house?", ["Baasha son of Ahijah", "Zimri son of Salu", "Omri", "Ben-hadad"], 27),
  ],
};

export default bank;
