// 1 Kings 6 — quiz bank (RSV). Every row is anchored to a verse; fill-in-the-blank
// rows are verified against the stored verse text by scripts/seed-quiz-bank.ts.
// Note: the stored RSV text for this chapter has no verse 33 (37 verses: 1–32, 34–38).
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: '1 Kings',
  chapter: 6,
  tag: 'quiz-v2-1kings-6',
  rows: [
    // ══════════════════════════════════ v1–4 · Solomon begins the house; its dimensions
    mc(1, 'What did Solomon begin to build in 1 Kings 6:1?', ['The house of the LORD', 'His own palace', 'The wall of Jerusalem', 'A fleet of ships'], 1),
    word(2, 'In which month did Solomon begin to build the house of the LORD?', 'Ziv', 1),
    blank(2, 'in the fourth year of Solomon’s reign over Israel, in the month of _____, which is the second month, he began to build the house of the LORD.', 'Ziv', 1),
    mc(3, 'In which year after the people of Israel came out of Egypt did Solomon begin to build the house?', ['The four hundred and eightieth year', 'The four hundredth year', 'The four hundred and thirtieth year', 'The four hundred and ninetieth year'], 1),
    tf(2, 'Solomon began to build the house of the LORD in the fourth year of his reign over Israel.', true, 1),
    word(3, 'The month of Ziv is which month of the year?', 'second', 1, ['2', '2nd', 'the second']),
    tf(3, 'The month of Ziv is described as the fifth month.', false, 1, 'Ziv "is the second month".'),
    word(1, 'How many cubits long was the house King Solomon built for the LORD?', 'sixty', 2, ['60']),
    blank(1, 'The house which King Solomon built for the LORD was sixty cubits long, _____ cubits wide, and thirty cubits high.', 'twenty', 2, ['20']),
    mc(1, 'How high was the house King Solomon built for the LORD?', ['Thirty cubits', 'Twenty cubits', 'Sixty cubits', 'Ten cubits'], 2),
    tf(2, 'The house Solomon built for the LORD was twenty cubits wide.', true, 2),
    mc(3, 'Which set of dimensions matches the house Solomon built for the LORD?', ['Sixty cubits long, twenty wide, thirty high', 'Sixty cubits long, thirty wide, twenty high', 'Forty cubits long, twenty wide, thirty high', 'Eighty cubits long, twenty wide, thirty high'], 2),
    word(1, 'What structure stood in front of the nave of the house?', 'vestibule', 3, ['the vestibule']),
    blank(2, 'The vestibule in front of the nave of the house was twenty cubits long, equal to the width of the house, and _____ cubits deep in front of the house.', 'ten', 3, ['10']),
    mc(3, 'The vestibule’s length of twenty cubits was said to be equal to what?', ['The width of the house', 'The height of the house', 'The length of the nave', 'The depth of the inner sanctuary'], 3),
    tf(3, 'The vestibule was ten cubits deep in front of the house.', true, 3),
    tf(2, 'The vestibule in front of the nave was thirty cubits long.', false, 3, 'The vestibule was twenty cubits long, equal to the width of the house.'),
    word(1, 'What did he make for the house with recessed frames?', 'windows', 4, ['window']),
    blank(1, 'And he made for the house _____ with recessed frames.', 'windows', 4),
    mc(2, 'What kind of frames did the windows of the house have?', ['Recessed frames', 'Gilded frames', 'Cedar frames', 'Bronze frames'], 4),
    tf(1, 'The windows made for the house had recessed frames.', true, 4),

    // ══════════════════════════════════ v5–10 · The side structure and stories
    blank(2, 'He also built a structure against the wall of the house, running round the walls of the house, both the nave and the inner sanctuary; and he made side _____ all around.', 'chambers', 5, ['chamber']),
    mc(1, 'What did Solomon make all around the house?', ['Side chambers', 'Pillars of bronze', 'Gardens', 'Watchtowers'], 5),
    tf(2, 'The structure built against the wall ran round both the nave and the inner sanctuary.', true, 5),
    word(3, 'The structure in verse 5 was built against what part of the house?', 'wall', 5, ['walls', 'the wall']),
    blank(3, 'He also built a structure against the _____ of the house, running round the walls of the house, both the nave and the inner sanctuary;', 'wall', 5),
    word(2, 'How many cubits broad was the lowest story?', 'five', 6, ['5']),
    mc(2, 'How broad was the third story?', ['Seven cubits', 'Five cubits', 'Six cubits', 'Eight cubits'], 6),
    blank(3, 'The lowest story was five cubits broad, the middle one was _____ cubits broad, and the third was seven cubits broad;', 'six', 6, ['6']),
    mc(3, 'Why did he make offsets on the wall around the outside of the house?', ['So the supporting beams should not be inserted into the walls of the house', 'To hold the windows in place', 'To carry the stairs to the upper stories', 'For decoration with carved flowers'], 6),
    tf(3, 'The supporting beams of the side structure were inserted into the walls of the house.', false, 6, 'He made offsets on the wall "in order that the supporting beams should not be inserted into the walls of the house".'),
    word(3, 'What did he make on the wall around the outside of the house so the beams need not be inserted?', 'offsets', 6, ['offset']),
    mc(1, 'Where was the stone for the house prepared?', ['At the quarry', 'At the temple site', 'In Lebanon', 'In Egypt'], 7),
    blank(1, 'When the house was built, it was with stone prepared at the _____;', 'quarry', 7),
    tf(1, 'Neither hammer nor axe nor any tool of iron was heard in the temple while it was being built.', true, 7),
    word(2, 'Neither hammer nor axe nor any tool of what metal was heard in the temple?', 'iron', 7),
    mc(3, 'Which two tools are named as not being heard in the temple while it was built?', ['Hammer and axe', 'Saw and chisel', 'Mallet and adze', 'Pick and shovel'], 7),
    blank(3, 'so that neither hammer nor _____ nor any tool of iron was heard in the temple, while it was being built.', 'axe', 7, ['ax']),
    mc(1, 'On which side of the house was the entrance for the lowest story?', ['South', 'North', 'East', 'West'], 8),
    word(1, 'One went up from the lowest story to the middle story by what?', 'stairs', 8, ['stair', 'a staircase', 'staircase']),
    blank(2, 'The entrance for the lowest story was on the _____ side of the house;', 'south', 8),
    tf(2, 'The entrance for the lowest story was on the north side of the house.', false, 8, 'It was on the south side.'),
    word(1, 'The ceiling of the house was made of beams and planks of what wood?', 'cedar', 9),
    blank(1, 'So he built the house, and finished it; and he made the ceiling of the house of beams and planks of _____.', 'cedar', 9),
    mc(2, 'What was the ceiling of the house made of?', ['Beams and planks of cedar', 'Boards of cypress', 'Hewn stone', 'Olivewood'], 9),
    tf(2, 'The ceiling of the house was made of beams and planks of cypress.', false, 9, 'The ceiling was of beams and planks of cedar.'),
    word(3, 'How many cubits high was each story of the structure built against the whole house?', 'five', 10, ['5']),
    blank(3, 'He built the structure against the whole house, each story _____ cubits high, and it was joined to the house with timbers of cedar.', 'five', 10, ['5']),
    mc(3, 'How was the structure joined to the house?', ['With timbers of cedar', 'With iron nails', 'With bronze clamps', 'With ropes of flax'], 10),
    tf(3, 'The structure against the whole house was joined to it with timbers of cedar.', true, 10),

    // ══════════════════════════════════ v11–14 · The word of the LORD to Solomon
    word(1, 'To whom did the word of the LORD come in 1 Kings 6:11?', 'Solomon', 11),
    blank(1, 'Now the word of the _____ came to Solomon,', 'LORD', 11, ['lord', 'the lord']),
    tf(1, 'In 1 Kings 6:11 the word of the LORD came to Solomon.', true, 11),
    mc(2, 'What came to Solomon in 1 Kings 6:11?', ['The word of the LORD', 'A messenger from Hiram', 'A letter from Pharaoh', 'The queen of Sheba'], 11),
    mc(2, 'What did the LORD promise to establish with Solomon if he walked in his statutes?', ['His word, which he spoke to David his father', 'A new covenant with Israel', 'Solomon’s wealth and fame', 'Peace with Egypt'], 12),
    blank(2, 'then I will establish my word with you, which I spoke to _____ your father.', 'David', 12),
    word(1, 'The LORD had spoken his word to Solomon’s father — who was he?', 'David', 12),
    tf(1, 'The LORD’s word to Solomon concerned the house he was building.', true, 12),
    mc(3, 'Which three things did the LORD require of Solomon in verse 12?', ['Walk in my statutes, obey my ordinances, and keep all my commandments', 'Offer sacrifices, fast, and pray', 'Build an altar, appoint priests, and keep the sabbath', 'Pay tithes, free the slaves, and honor the prophets'], 12),
    blank(3, 'if you will walk in my _____ and obey my ordinances and keep all my commandments and walk in them,', 'statutes', 12, ['statute']),
    tf(3, 'The LORD promised to establish his word with Solomon unconditionally.', false, 12, 'The promise was conditional: "if you will walk in my statutes and obey my ordinances and keep all my commandments".'),
    mc(1, 'What did the LORD promise about his people Israel in verse 13?', ['He would dwell among them and not forsake them', 'He would give them great wealth', 'He would drive out all their enemies', 'He would multiply them like the sand'], 13),
    blank(1, 'And I will dwell among the children of Israel, and will not _____ my people Israel.', 'forsake', 13),
    word(2, 'The LORD said, "I will ___ among the children of Israel."', 'dwell', 13),
    blank(2, 'And I will _____ among the children of Israel, and will not forsake my people Israel.', 'dwell', 13),
    tf(1, 'The LORD said he would forsake his people Israel.', false, 13, 'He said he "will not forsake my people Israel".'),
    tf(1, 'Solomon built the house and finished it.', true, 14),
    blank(1, 'So Solomon built the house, and _____ it.', 'finished', 14),
    word(1, 'Who built the house and finished it?', 'Solomon', 14),
    mc(2, 'What does 1 Kings 6:14 say Solomon did with the house?', ['Built it and finished it', 'Abandoned it unfinished', 'Dedicated it with sacrifices', 'Tore it down and rebuilt it'], 14),

    // ══════════════════════════════════ v15–22 · The interior: cedar, cypress and gold
    mc(1, 'What wood covered the floor of the house?', ['Boards of cypress', 'Boards of cedar', 'Olivewood', 'Oak planks'], 15),
    word(1, 'The walls of the house were lined on the inside with boards of what wood?', 'cedar', 15),
    blank(2, 'and he covered the floor of the house with boards of _____.', 'cypress', 15),
    tf(2, 'The floor of the house was covered with boards of cedar.', false, 15, 'The floor was covered with boards of cypress; the walls were lined with cedar.'),
    blank(3, 'He lined the walls of the house on the inside with boards of cedar; from the floor of the house to the _____ of the ceiling, he covered them on the inside with wood;', 'rafters', 15, ['rafter']),
    tf(3, 'The inside walls were covered with wood from the floor of the house to the rafters of the ceiling.', true, 15),
    mc(2, 'What lined the walls of the house on the inside?', ['Boards of cedar', 'Boards of cypress', 'Plates of gold', 'Hewn stone'], 15),
    mc(2, 'How many cubits of the rear of the house were built as the inner sanctuary?', ['Twenty cubits', 'Ten cubits', 'Thirty cubits', 'Forty cubits'], 16),
    blank(2, 'and he built this within as an inner sanctuary, as the most _____ place.', 'holy', 16),
    word(1, 'The inner sanctuary is also called "the most ___ place".', 'holy', 16),
    tf(3, 'The twenty cubits at the rear of the house were built with boards of cypress.', false, 16, 'They were built with boards of cedar from the floor to the rafters.'),
    mc(3, 'Where in the house was the inner sanctuary built?', ['At the rear of the house', 'At the front, by the vestibule', 'In the middle story', 'In the inner court'], 16),
    word(2, 'How many cubits long was the nave in front of the inner sanctuary?', 'forty', 17, ['40']),
    blank(2, 'The house, that is, the nave in front of the inner sanctuary, was _____ cubits long.', 'forty', 17, ['40']),
    mc(3, 'What part of the house was forty cubits long?', ['The nave in front of the inner sanctuary', 'The vestibule', 'The inner sanctuary', 'The side chambers'], 17),
    tf(3, 'The nave in front of the inner sanctuary was forty cubits long.', true, 17),
    mc(1, 'The cedar within the house was carved in the form of what?', ['Gourds and open flowers', 'Lions and oxen', 'Pomegranates and lilies', 'Vines and grapes'], 18),
    word(2, 'Along with open flowers, the cedar within the house was carved in the form of what?', 'gourds', 18, ['gourd']),
    blank(2, 'The cedar within the house was carved in the form of gourds and open flowers; all was cedar, no _____ was seen.', 'stone', 18),
    tf(1, 'Inside the house all was cedar, and no stone was seen.', true, 18),
    tf(3, 'The cedar within the house was carved in the form of pomegranates.', false, 18, 'It was carved in the form of gourds and open flowers.'),
    mc(1, 'What was to be set in the inner sanctuary?', ['The ark of the covenant of the LORD', 'The bronze altar', 'The golden lampstand', 'The table of showbread'], 19),
    blank(1, 'The inner sanctuary he prepared in the innermost part of the house, to set there the _____ of the covenant of the LORD.', 'ark', 19),
    word(1, 'The inner sanctuary was prepared to hold the ark of the ___ of the LORD.', 'covenant', 19),
    tf(1, 'The inner sanctuary was prepared so the ark of the covenant of the LORD could be set there.', true, 19),
    blank(3, 'The inner sanctuary he prepared in the _____ part of the house, to set there the ark of the covenant of the LORD.', 'innermost', 19),
    mc(2, 'What were the dimensions of the inner sanctuary?', ['Twenty cubits long, twenty wide, and twenty high', 'Twenty cubits long, ten wide, and ten high', 'Forty cubits long, twenty wide, and thirty high', 'Sixty cubits long, twenty wide, and thirty high'], 20),
    word(1, 'The altar mentioned in verse 20 was made of what wood?', 'cedar', 20),
    blank(1, 'and he overlaid it with pure _____. He also made an altar of cedar.', 'gold', 20),
    tf(2, 'The inner sanctuary was twenty cubits high.', true, 20),
    tf(3, 'The inner sanctuary was overlaid with pure silver.', false, 20, 'He overlaid it with pure gold.'),
    blank(3, 'The inner sanctuary was twenty cubits long, twenty cubits wide, and _____ cubits high;', 'twenty', 20, ['20']),
    word(1, 'Solomon overlaid the inside of the house with pure what?', 'gold', 21),
    mc(1, 'What did Solomon draw across in front of the inner sanctuary?', ['Chains of gold', 'A veil of blue', 'Cedar beams', 'A bronze grating'], 21),
    blank(2, 'and he drew _____ of gold across, in front of the inner sanctuary, and overlaid it with gold.', 'chains', 21, ['chain']),
    tf(2, 'Solomon drew chains of gold across in front of the inner sanctuary.', true, 21),
    mc(3, 'What did he overlay with gold "until all the house was finished"?', ['The whole house', 'Only the doors', 'Only the floor', 'The outer court'], 22),
    blank(2, 'Also the whole _____ that belonged to the inner sanctuary he overlaid with gold.', 'altar', 22),
    tf(3, 'The altar that belonged to the inner sanctuary was left as plain cedar.', false, 22, 'The whole altar that belonged to the inner sanctuary he overlaid with gold.'),
    word(3, 'The whole altar that he overlaid with gold belonged to which part of the house?', 'inner sanctuary', 22, ['sanctuary', 'the inner sanctuary']),

    // ══════════════════════════════════ v23–28 · The two cherubim
    mc(1, 'What did he make in the inner sanctuary out of olivewood?', ['Two cherubim', 'Two pillars', 'A table', 'A lampstand'], 23),
    word(1, 'How many cherubim did he make in the inner sanctuary?', 'two', 23, ['2']),
    blank(1, 'In the inner sanctuary he made two cherubim of _____, each ten cubits high.', 'olivewood', 23, ['olive wood']),
    tf(2, 'The two cherubim in the inner sanctuary were made of cedar.', false, 23, 'They were made of olivewood.'),
    mc(1, 'How high was each of the two cherubim?', ['Ten cubits', 'Five cubits', 'Twenty cubits', 'Fifteen cubits'], 23),
    word(2, 'How many cubits was the length of one wing of the cherub?', 'five', 24, ['5']),
    blank(3, 'it was _____ cubits from the tip of one wing to the tip of the other.', 'ten', 24, ['10']),
    mc(3, 'How far was it from the tip of one wing of the cherub to the tip of the other?', ['Ten cubits', 'Five cubits', 'Twenty cubits', 'Fifteen cubits'], 24),
    tf(3, 'Each wing of the cherub was five cubits long.', true, 24),
    mc(2, 'How long was one wing of the cherub?', ['Five cubits', 'Ten cubits', 'Two cubits', 'Seven cubits'], 24),
    tf(2, 'Both cherubim had the same measure and the same form.', true, 25),
    blank(2, 'The other cherub also measured ten cubits; both cherubim had the same measure and the same _____.', 'form', 25),
    mc(3, 'What does verse 25 say about the two cherubim?', ['They had the same measure and the same form', 'One was larger than the other', 'They faced in opposite directions', 'They were made of different woods'], 25),
    word(3, 'The other cherub also measured how many cubits?', 'ten', 25, ['10']),
    blank(2, 'The height of one cherub was _____ cubits, and so was that of the other cherub.', 'ten', 26, ['10']),
    tf(2, 'One cherub was ten cubits high and the other was twelve cubits high.', false, 26, 'The height of one cherub was ten cubits, "and so was that of the other cherub".'),
    word(3, 'Verse 26: "The height of one cherub was ten cubits, and so was that of the other ___."', 'cherub', 26),
    mc(3, 'According to verse 26, what was the height of the other cherub?', ['Also ten cubits', 'Five cubits', 'Twenty cubits', 'It is not given'], 26),
    mc(2, 'Where did the cherubim’s other wings touch each other?', ['In the middle of the house', 'At the door of the inner sanctuary', 'At the vestibule', 'Against the ceiling'], 27),
    blank(2, 'He put the cherubim in the innermost part of the house; and the _____ of the cherubim were spread out', 'wings', 27, ['wing']),
    tf(2, 'A wing of each cherub touched a wall of the house.', true, 27),
    word(3, 'In which part of the house did he put the cherubim?', 'innermost part', 27, ['innermost', 'the innermost part', 'innermost part of the house']),
    tf(3, 'The wings of the cherubim were folded at their sides.', false, 27, 'The wings were spread out, touching the walls and each other in the middle of the house.'),
    blank(3, 'their other wings touched each other in the _____ of the house.', 'middle', 27),
    word(1, 'With what did he overlay the cherubim?', 'gold', 28),
    blank(1, 'And he overlaid the _____ with gold.', 'cherubim', 28, ['cherubims', 'cherubs']),
    tf(1, 'The cherubim were overlaid with gold.', true, 28),
    mc(1, 'What was done to the cherubim in verse 28?', ['They were overlaid with gold', 'They were painted blue', 'They were covered with linen', 'They were carved with flowers'], 28),

    // ══════════════════════════════════ v29–32 · Carved walls, gold floor, olivewood doors
    mc(1, 'Which three figures were carved on all the walls of the house?', ['Cherubim, palm trees, and open flowers', 'Lions, oxen, and cherubim', 'Gourds, vines, and pomegranates', 'Stars, moons, and suns'], 29),
    blank(2, 'He carved all the walls of the house round about with carved figures of cherubim and _____ trees and open flowers, in the inner and outer rooms.', 'palm', 29),
    word(2, 'Besides cherubim and open flowers, what kind of trees were carved on the walls?', 'palm', 29, ['palm trees', 'palms']),
    tf(3, 'The carved figures of cherubim, palm trees, and open flowers were only in the inner rooms.', false, 29, 'They were "in the inner and outer rooms".'),
    blank(3, 'He carved all the walls of the house round about with carved figures of cherubim and palm trees and open flowers, in the inner and _____ rooms.', 'outer', 29),
    word(1, 'With what did he overlay the floor of the house?', 'gold', 30),
    blank(1, 'The _____ of the house he overlaid with gold in the inner and outer rooms.', 'floor', 30),
    tf(2, 'The floor of the house was overlaid with gold in both the inner and outer rooms.', true, 30),
    mc(3, 'In which rooms was the floor of the house overlaid with gold?', ['The inner and outer rooms', 'Only the inner sanctuary', 'Only the nave', 'Only the vestibule'], 30),
    mc(1, 'The doors for the entrance to the inner sanctuary were made of what?', ['Olivewood', 'Cedar', 'Cypress', 'Bronze'], 31),
    word(3, 'The lintel and the doorposts of the entrance to the inner sanctuary formed what shape?', 'pentagon', 31, ['a pentagon']),
    blank(3, 'For the entrance to the inner sanctuary he made doors of olivewood; the lintel and the doorposts formed a _____.', 'pentagon', 31),
    tf(3, 'The lintel and the doorposts of the inner sanctuary entrance formed a square.', false, 31, 'They formed a pentagon.'),
    blank(1, 'For the entrance to the inner sanctuary he made _____ of olivewood;', 'doors', 31, ['door']),
    mc(2, 'What carvings covered the two doors of olivewood?', ['Cherubim, palm trees, and open flowers', 'Gourds and lilies', 'Lions and bulls', 'Pomegranates and bells'], 32),
    blank(2, 'he overlaid them with gold, and spread gold upon the cherubim and upon the _____ trees.', 'palm', 32),
    tf(1, 'The two doors of olivewood were overlaid with gold.', true, 32),
    word(3, 'How many doors of olivewood were covered with carvings of cherubim, palm trees, and open flowers?', 'two', 32, ['2']),
    tf(3, 'Gold was spread upon the cherubim and upon the palm trees of the olivewood doors.', true, 32),

    // ══════════════════════════════════ v34–36 · Cypress doors and the inner court
    mc(1, 'The two doors in verse 34 were made of what wood?', ['Cypress wood', 'Olivewood', 'Cedar', 'Oak'], 34),
    word(2, 'Each door of cypress wood had two folding what?', 'leaves', 34, ['leaf']),
    blank(2, 'and two doors of _____ wood; the two leaves of the one door were folding, and the two leaves of the other door were folding.', 'cypress', 34),
    tf(3, 'The leaves of the cypress doors were fixed and did not fold.', false, 34, 'The two leaves of each door were folding.'),
    mc(3, 'How many leaves did each door of cypress wood have?', ['Two', 'One', 'Three', 'Four'], 34),
    blank(3, 'and he overlaid them with gold _____ applied upon the carved work.', 'evenly', 35),
    mc(3, 'How was the gold applied on the carved work of the cypress doors?', ['Evenly applied upon the carved work', 'Hammered into thin plates', 'Beaten only on the edges', 'Poured on in molten form'], 35),
    tf(2, 'On the cypress doors he carved cherubim and palm trees and open flowers.', true, 35),
    word(2, 'On the cypress doors he carved cherubim, palm trees, and open ___.', 'flowers', 35, ['flower']),
    mc(1, 'The inner court was built with how many courses of hewn stone?', ['Three', 'One', 'Two', 'Four'], 36),
    word(2, 'The inner court had one course of what kind of beams?', 'cedar', 36),
    blank(2, 'He built the inner court with three courses of hewn stone and one course of _____ beams.', 'cedar', 36),
    tf(2, 'The inner court had three courses of hewn stone and one course of cedar beams.', true, 36),
    blank(3, 'He built the inner _____ with three courses of hewn stone and one course of cedar beams.', 'court', 36),
    tf(3, 'The inner court was built with one course of hewn stone and three courses of cedar beams.', false, 36, 'It was three courses of hewn stone and one course of cedar beams.'),

    // ══════════════════════════════════ v37–38 · Foundation laid, house finished
    word(1, 'In which year was the foundation of the house of the LORD laid?', 'fourth', 37, ['4th', '4', 'the fourth year', 'fourth year']),
    blank(1, 'In the fourth year the _____ of the house of the LORD was laid, in the month of Ziv.', 'foundation', 37, ['foundations']),
    mc(1, 'In which month was the foundation of the house of the LORD laid?', ['Ziv', 'Bul', 'Ethanim', 'Abib'], 37),
    tf(1, 'The foundation of the house of the LORD was laid in the month of Ziv.', true, 37),
    mc(3, 'In which year was the foundation of the house laid, according to verse 37?', ['The fourth year', 'The first year', 'The seventh year', 'The eleventh year'], 37),
    mc(1, 'How many years was Solomon in building the house?', ['Seven', 'Eleven', 'Four', 'Thirteen'], 38),
    word(1, 'How many years did it take to build the house?', 'seven', 38, ['7']),
    blank(1, 'He was _____ years in building it.', 'seven', 38, ['7']),
    mc(1, 'In which month was the house finished?', ['Bul', 'Ziv', 'Ethanim', 'Nisan'], 38),
    word(2, 'In which year was the house finished in all its parts?', 'eleventh', 38, ['11th', '11', 'the eleventh year', 'eleventh year']),
    blank(2, 'And in the eleventh year, in the month of _____, which is the eighth month, the house was finished in all its parts,', 'Bul', 38),
    tf(2, 'The month of Bul is described as the eighth month.', true, 38),
    tf(3, 'The house was finished in the ninth year.', false, 38, 'It was finished in the eleventh year, in the month of Bul.'),
    mc(3, 'Verse 38 says the house was finished in all its parts and according to all its what?', ['Specifications', 'Measurements', 'Blueprints', 'Commandments'], 38),
    blank(3, 'the house was finished in all its parts, and according to all its _____.', 'specifications', 38, ['specification']),

    // ══════════════════════════════════ Whole-chapter
    mc(1, 'What building does 1 Kings 6 describe Solomon constructing?', ['The house of the LORD', 'His own palace', 'The city wall of Jerusalem', 'A house for Pharaoh’s daughter'], 1),
    mc(2, 'Which three woods are named in the building of the house in 1 Kings 6?', ['Cedar, cypress, and olivewood', 'Oak, pine, and acacia', 'Cedar, oak, and fir', 'Sycamore, almug, and olivewood'], 23),
    mc(1, 'Which metal was used to overlay the inside of the house, the cherubim, the floor, and the doors?', ['Gold', 'Silver', 'Bronze', 'Iron'], 22),
    mc(3, 'Which of these events comes FIRST in 1 Kings 6?', ['Solomon begins to build the house in the month of Ziv', 'The word of the LORD comes to Solomon', 'The cherubim are overlaid with gold', 'The house is finished in the month of Bul'], 1),
    tf(2, 'According to 1 Kings 6, the house was begun in the month of Ziv and finished in the month of Bul.', true, 38),
  ],
};

export default bank;
