// 1 Kings 8 — quiz bank (RSV). Every row is anchored to a verse; fill-in-the-blank
// rows are verified against the stored verse text by scripts/seed-quiz-bank.ts.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: '1 Kings',
  chapter: 8,
  tag: 'quiz-v2-1kings-8',
  rows: [
    // ══════════════════════════════════ v1–5 · The ark brought up
    mc(1, 'Whom did Solomon assemble in Jerusalem to bring up the ark?', ['The elders of Israel and all the heads of the tribes, the leaders of the fathers’ houses', 'The priests and Levites only', 'The commanders of the army', 'The kings of the surrounding nations'], 1),
    blank(1, 'to bring up the ark of the covenant of the LORD out of the city of David, which is _____.', 'Zion', 1),
    word(2, 'The ark of the covenant was brought up out of "the city of David, which is ___".', 'Zion', 1),
    word(1, 'In which city did Solomon assemble the elders of Israel to bring up the ark?', 'Jerusalem', 1),
    tf(2, 'The ark was brought up to Jerusalem out of Hebron.', false, 1, 'It was brought up "out of the city of David, which is Zion".'),
    mc(2, 'In which month did all the men of Israel assemble to King Solomon at the feast?', ['Ethanim, the seventh month', 'Ziv, the second month', 'Bul, the eighth month', 'Abib, the first month'], 2),
    word(3, 'What is the name of the month in which the men of Israel assembled to Solomon for the feast?', 'Eth’anim', 2, ['ethanim', 'eth-anim']),
    blank(1, 'And all the men of Israel assembled to King Solomon at the feast in the month Eth’anim, which is the _____ month.', 'seventh', 2, ['7th']),
    tf(1, 'The month Ethanim is identified as the seventh month.', true, 2),
    tf(3, 'The men of Israel assembled to Solomon in the month Ethanim, the eighth month.', false, 2, 'Ethanim is "the seventh month".'),
    blank(1, 'And all the elders of Israel came, and the _____ took up the ark.', 'priests', 3),
    mc(1, 'Who took up the ark when the elders of Israel came?', ['The priests', 'The elders themselves', 'King Solomon', 'The heads of the tribes'], 3),
    tf(1, 'The elders of Israel took up the ark and carried it.', false, 3, 'The priests took up the ark.'),
    mc(1, 'Along with the ark of the LORD, what else was brought up?', ['The tent of meeting and all the holy vessels that were in the tent', 'The bronze altar and the sea', 'The golden lampstands only', 'Solomon’s throne'], 4),
    blank(2, 'And they brought up the ark of the LORD, the tent of _____, and all the holy vessels that were in the tent; the priests and the Levites brought them up.', 'meeting', 4),
    word(2, 'Along with the priests, which group brought up the ark, the tent, and the holy vessels?', 'Levites', 4, ['the levites', 'levite']),
    tf(1, 'The priests and the Levites brought up the ark, the tent of meeting, and the holy vessels.', true, 4),
    mc(1, 'What were Solomon and the congregation doing before the ark?', ['Sacrificing so many sheep and oxen that they could not be counted', 'Singing psalms with harps', 'Fasting and weeping', 'Reading the law of Moses'], 5),
    blank(3, 'sacrificing so many sheep and oxen that they could not be _____ or numbered.', 'counted', 5),
    tf(1, 'Before the ark, Solomon and the congregation sacrificed exactly one thousand sheep and oxen.', false, 5, 'They sacrificed so many sheep and oxen "that they could not be counted or numbered".'),
    word(3, 'Which two kinds of animals were sacrificed before the ark in numbers that could not be counted?', 'sheep and oxen', 5, ['sheep oxen', 'oxen and sheep', 'sheep, oxen', 'oxen sheep']),

    // ══════════════════════════════════ v6–9 · The ark in the most holy place
    mc(1, 'Where did the priests bring the ark of the covenant?', ['To the inner sanctuary, the most holy place, underneath the wings of the cherubim', 'To the court before the house', 'To the city of David', 'To the tent of meeting'], 6),
    blank(1, 'Then the priests brought the ark of the covenant of the LORD to its place, in the inner sanctuary of the house, in the most holy place, underneath the wings of the _____.', 'cherubim', 6, ['cherubims', 'cherubs']),
    word(1, 'The ark was placed underneath the wings of what?', 'cherubim', 6, ['the cherubim', 'cherubs', 'cherubims']),
    tf(1, 'The ark was set in the court of the house, beside the bronze altar.', false, 6, 'It was brought to the inner sanctuary, the most holy place, underneath the wings of the cherubim.'),
    blank(3, 'For the cherubim spread out their wings over the place of the ark, so that the cherubim made a _____ above the ark and its poles.', 'covering', 7),
    mc(2, 'What did the cherubim’s outstretched wings form above the ark and its poles?', ['A covering', 'A throne', 'A gateway', 'A veil'], 7),
    word(2, 'The cherubim spread out their wings over the place of what?', 'ark', 7, ['the ark']),
    mc(3, 'From where could the ends of the ark’s poles be seen?', ['From the holy place before the inner sanctuary', 'From outside the house', 'From the court', 'From the city of David'], 8),
    blank(3, 'And the poles were so long that the ends of the poles were seen from the holy place before the inner sanctuary; but they could not be seen from _____; and they are there to this day.', 'outside', 8),
    tf(3, 'The ends of the poles could be seen from outside the house.', false, 8, 'They were seen from the holy place before the inner sanctuary, "but they could not be seen from outside".'),
    word(3, 'What part of the ark was so long that its ends were seen from the holy place?', 'poles', 8, ['the poles', 'pole']),
    word(2, 'The poles of the ark "are there to this ___".', 'day', 8),
    mc(1, 'What was inside the ark when it was brought into the temple?', ['Nothing except the two tables of stone which Moses put there at Horeb', 'The rod of Aaron and a jar of manna', 'The book of the law', 'Gold and silver vessels'], 9),
    blank(1, 'There was nothing in the ark except the two tables of _____ which Moses put there at Horeb,', 'stone', 9),
    word(2, 'At what place did Moses put the two tables of stone in the ark?', 'Horeb', 9),
    tf(1, 'The ark contained nothing except the two tables of stone.', true, 9),
    blank(2, 'where the LORD made a covenant with the people of Israel, when they came out of the land of _____.', 'Egypt', 9),
    tf(2, 'The ark contained the two tables of stone and the rod of Aaron.', false, 9, 'There was nothing in the ark except the two tables of stone which Moses put there at Horeb.'),
    mc(3, 'Who put the two tables of stone in the ark?', ['Moses', 'Aaron', 'David', 'Solomon'], 9),
    word(2, 'How many tables of stone were in the ark?', 'two', 9, ['2']),

    // ══════════════════════════════════ v10–13 · The cloud and the glory
    mc(1, 'What happened when the priests came out of the holy place?', ['A cloud filled the house of the LORD', 'Fire came down from heaven', 'The earth shook', 'The people shouted for joy'], 10),
    blank(1, 'And when the priests came out of the holy place, a _____ filled the house of the LORD,', 'cloud', 10),
    word(1, 'What filled the house of the LORD when the priests came out of the holy place?', 'cloud', 10, ['a cloud', 'the cloud']),
    tf(1, 'When the priests came out of the holy place, fire filled the house of the LORD.', false, 10, 'A cloud filled the house of the LORD.'),
    mc(1, 'Why could the priests not stand to minister?', ['Because of the cloud, for the glory of the LORD filled the house', 'Because the people were too many', 'Because the altar was too small', 'Because Solomon dismissed them'], 11),
    blank(1, 'so that the priests could not stand to minister because of the cloud; for the _____ of the LORD filled the house of the LORD.', 'glory', 11),
    blank(2, 'so that the priests could not stand to _____ because of the cloud;', 'minister', 11),
    tf(1, 'The glory of the LORD filled the house so that the priests could not stand to minister.', true, 11),
    word(1, 'What of the LORD filled the house so that the priests could not minister?', 'glory', 11, ['the glory', 'his glory']),
    mc(2, 'According to Solomon, where had the LORD said he would dwell?', ['In thick darkness', 'In the sun', 'On Mount Zion', 'In the tent of meeting'], 12),
    blank(2, 'Then Solomon said, "The LORD has set the sun in the heavens, but has said that he would dwell in thick _____.', 'darkness', 12),
    tf(3, 'Solomon said the LORD had said he would dwell in bright light.', false, 12, 'The LORD "has said that he would dwell in thick darkness".'),
    word(3, 'Solomon said the LORD has set what in the heavens?', 'sun', 12, ['the sun']),
    blank(1, 'I have built thee an _____ house, a place for thee to dwell in for ever."', 'exalted', 13),
    mc(2, 'How did Solomon describe the house he had built for the LORD?', ['An exalted house, a place for thee to dwell in for ever', 'A humble tent', 'A house of cedar and gold', 'A house for the ark'], 13),
    tf(2, 'Solomon said he had built the LORD a place to dwell in for forty years.', false, 13, '"a place for thee to dwell in for ever."'),

    // ══════════════════════════════════ v14–21 · Solomon blesses the assembly
    mc(1, 'What did the king do after he faced about?', ['He blessed all the assembly of Israel while they stood', 'He offered sacrifice', 'He entered the most holy place', 'He dismissed the priests'], 14),
    blank(1, 'Then the king faced about, and _____ all the assembly of Israel, while all the assembly of Israel stood.', 'blessed', 14),
    tf(2, 'When the king blessed the assembly of Israel, the assembly was seated.', false, 14, 'All the assembly of Israel stood.'),
    word(2, 'What did all the assembly of Israel do while the king blessed them — they ___.', 'stood', 14, ['standing', 'stand']),
    blank(1, 'And he said, "Blessed be the LORD, the God of Israel, who with his hand has fulfilled what he promised with his mouth to _____ my father, saying,', 'David', 15),
    mc(2, 'How did Solomon say the LORD fulfilled his promise to David?', ['With his hand he fulfilled what he promised with his mouth', 'Through the prophet Nathan', 'By the sword of Joab', 'Through the tribes of Israel'], 15),
    word(1, 'Solomon began his blessing, "Blessed be the LORD, the God of ___".', 'Israel', 15),
    word(3, 'The LORD fulfilled with his hand what he promised with his ___.', 'mouth', 15),
    mc(2, 'Since bringing Israel out of Egypt, what had the LORD not chosen?', ['A city in all the tribes of Israel in which to build a house for his name', 'A king over Israel', 'A priest to serve him', 'A land for his people'], 16),
    blank(3, 'I chose no city in all the tribes of Israel in which to build a house, that my name might be there; but I chose _____ to be over my people Israel.\'', 'David', 16),
    tf(3, 'The LORD said he chose Jerusalem as the city when he brought Israel out of Egypt.', false, 16, '"I chose no city in all the tribes of Israel in which to build a house … but I chose David to be over my people Israel."'),
    word(1, 'Whom did the LORD say he chose to be over his people Israel?', 'David', 16),
    blank(3, '`Since the day that I brought my people Israel out of _____, I chose no city in all the tribes of Israel in which to build a house,', 'Egypt', 16),
    blank(1, 'Now it was in the heart of _____ my father to build a house for the name of the LORD, the God of Israel.', 'David', 17),
    tf(1, 'It was in David’s heart to build a house for the name of the LORD.', true, 17),
    mc(1, 'What was in the heart of David, according to Solomon?', ['To build a house for the name of the LORD, the God of Israel', 'To conquer Egypt', 'To make Solomon king', 'To bring the ark to Hebron'], 17),
    mc(2, 'What did the LORD say to David about his desire to build a house?', ['"you did well that it was in your heart"', '"you shall build it in your old age"', '"your heart is proud"', '"I have no need of a house"'], 18),
    blank(2, 'But the LORD said to David my father, `Whereas it was in your heart to build a house for my name, you did _____ that it was in your heart;', 'well', 18),
    tf(2, 'The LORD rebuked David for wanting to build a house for his name.', false, 18, 'The LORD said, "you did well that it was in your heart".'),
    word(3, 'The LORD told David, "you did ___ that it was in your heart".', 'well', 18),
    mc(1, 'Who did the LORD say would build the house for his name?', ['David’s son who would be born to him', 'David himself', 'Nathan the prophet', 'Zadok the priest'], 19),
    blank(1, 'nevertheless you shall not build the house, but your _____ who shall be born to you shall build the house for my name.\'', 'son', 19),
    tf(1, 'The LORD told David that David himself would build the house.', false, 19, '"you shall not build the house, but your son who shall be born to you shall build the house for my name."'),
    word(3, 'The LORD said to David, "nevertheless you shall not ___ the house".', 'build', 19),
    blank(2, 'Now the LORD has fulfilled his promise which he made; for I have risen in the place of David my father, and sit on the _____ of Israel, as the LORD promised,', 'throne', 20),
    mc(3, 'What two things did Solomon say showed the LORD had fulfilled his promise?', ['He had risen in David’s place on the throne of Israel and built the house for the name of the LORD', 'He had defeated his enemies and grown rich', 'He had married and had sons', 'He had built a palace and a fleet'], 20),
    word(1, 'Solomon said, "I have built the house for the ___ of the LORD".', 'name', 20),
    word(2, 'Solomon said he had risen in the place of whom?', 'David', 20, ['david my father', 'his father']),
    blank(2, 'And there I have provided a place for the _____, in which is the covenant of the LORD which he made with our fathers, when he brought them out of the land of Egypt."', 'ark', 21),
    mc(1, 'What did Solomon say is in the ark?', ['The covenant of the LORD which he made with our fathers', 'The gold of Ophir', 'The scroll of the law', 'Aaron’s rod'], 21),
    tf(3, 'Solomon said the covenant in the ark was made with the fathers when the LORD brought them into Canaan.', false, 21, 'It was made "when he brought them out of the land of Egypt".'),

    // ══════════════════════════════════ v22–30 · The prayer begins
    mc(1, 'Where did Solomon stand to pray, and what did he do with his hands?', ['Before the altar of the LORD, spreading forth his hands toward heaven', 'In the most holy place, with hands folded', 'On the city wall, pointing to the temple', 'At the gate, with hands on the ark'], 22),
    blank(1, 'Then Solomon stood before the _____ of the LORD in the presence of all the assembly of Israel, and spread forth his hands toward heaven;', 'altar', 22),
    word(1, 'Solomon spread forth his hands toward what?', 'heaven', 22),
    tf(1, 'Solomon prayed before the altar in the presence of all the assembly of Israel.', true, 22),
    tf(3, 'Solomon prayed inside the inner sanctuary, away from the assembly.', false, 22, 'He stood before the altar of the LORD in the presence of all the assembly of Israel.'),
    mc(2, 'How did Solomon begin his prayer?', ['"O LORD, God of Israel, there is no God like thee, in heaven above or on earth beneath"', '"Hear, O Israel"', '"Blessed be the LORD who has given rest"', '"Have mercy on me, O God"'], 23),
    blank(3, 'and said, "O LORD, God of Israel, there is no God like thee, in heaven above or on earth beneath, keeping covenant and showing steadfast _____ to thy servants who walk before thee with all their heart;', 'love', 23),
    word(2, 'Solomon prayed, "there is no God like thee, in heaven above or on earth ___".', 'beneath', 23),
    word(3, 'God shows steadfast love to servants who walk before him with all their ___.', 'heart', 23),
    blank(3, 'who hast kept with thy servant David my father what thou didst declare to him; yea, thou didst speak with thy mouth, and with thy _____ hast fulfilled it this day.', 'hand', 24),
    tf(3, 'Solomon said the LORD had spoken with his mouth and fulfilled it with his hand "this day".', true, 24),
    mc(3, 'With whom did Solomon say the LORD had kept what he declared (v24)?', ['His servant David, Solomon’s father', 'Moses his servant', 'Abraham', 'The elders of Israel'], 24),
    mc(2, 'What promise to David did Solomon ask the LORD to keep?', ['"There shall never fail you a man before me to sit upon the throne of Israel"', '"I will give you rest from all your enemies"', '"Your house shall stand for a thousand generations"', '"I will dwell in your city for ever"'], 25),
    blank(2, '`There shall never fail you a man before me to sit upon the _____ of Israel, if only your sons take heed to their way, to walk before me as you have walked before me.\'', 'throne', 25),
    tf(3, 'The promise of a man on the throne of Israel was conditioned on David’s sons taking heed to their way.', true, 25),
    word(3, 'The promise held "if only your ___ take heed to their way".', 'sons', 25),
    tf(3, 'Solomon said the promise of a man on the throne was unconditional.', false, 25, 'It held "if only your sons take heed to their way, to walk before me as you have walked before me."'),
    blank(3, 'Now therefore, O God of Israel, let thy word be _____, which thou hast spoken to thy servant David my father.', 'confirmed', 26),
    mc(3, 'What did Solomon ask God to do with the word spoken to David (v26)?', ['Let it be confirmed', 'Let it be written down', 'Let it be forgotten', 'Let it be repeated'], 26),
    word(2, 'Solomon asked of the word spoken to David, "let thy word be ___".', 'confirmed', 26),
    mc(1, 'What did Solomon say cannot contain God?', ['Heaven and the highest heaven', 'The sea and the dry land', 'The earth and all its nations', 'The tent of meeting'], 27),
    blank(1, '"But will God indeed dwell on the _____? Behold, heaven and the highest heaven cannot contain thee; how much less this house which I have built!', 'earth', 27),
    blank(1, 'Behold, heaven and the highest _____ cannot contain thee; how much less this house which I have built!', 'heaven', 27),
    word(1, 'Solomon asked, "But will God indeed dwell on the ___?"', 'earth', 27, ['the earth']),
    tf(1, 'Solomon said that heaven and the highest heaven cannot contain God.', true, 27),
    tf(2, 'Solomon declared that the house he had built was great enough to contain God.', false, 27, '"heaven and the highest heaven cannot contain thee; how much less this house which I have built!"'),
    mc(1, 'What question did Solomon ask just before saying heaven cannot contain God?', ['"But will God indeed dwell on the earth?"', '"Who is like the LORD?"', '"Will God hear from heaven?"', '"Shall this house stand for ever?"'], 27),
    blank(3, 'Yet have regard to the prayer of thy servant and to his _____, O LORD my God, hearkening to the cry and to the prayer which thy servant prays before thee this day;', 'supplication', 28),
    tf(3, 'In verse 28 Solomon asks the LORD to hearken to the prayers his servant will pray in years to come.', false, 28, 'He asks the LORD to hearken to "the prayer which thy servant prays before thee this day".'),
    mc(3, 'In verse 28 Solomon asks the LORD to hearken to what?', ['The cry and the prayer which thy servant prays before thee this day', 'The songs of the Levites', 'The voice of the people', 'The blood of the sacrifices'], 28),
    mc(2, 'What did Solomon ask about the LORD’s eyes (v29)?', ['That they be open night and day toward this house', 'That they look away from Israel’s sin', 'That they watch the borders of the land', 'That they see the sacrifices'], 29),
    blank(3, 'that thy eyes may be open night and day toward this house, the place of which thou hast said, `My _____ shall be there,\'', 'name', 29),
    tf(2, 'Solomon asked that God’s eyes be open toward the house only by day.', false, 29, '"that thy eyes may be open night and day toward this house".'),
    word(2, 'God had said of the house, "My ___ shall be there".', 'name', 29),
    blank(1, 'yea, hear thou in heaven thy dwelling place; and when thou hearest, _____.', 'forgive', 30),
    mc(1, 'Where did Solomon say the LORD’s dwelling place is?', ['In heaven', 'In the most holy place', 'In the cloud', 'In Zion'], 30),
    tf(1, 'Solomon asked the LORD to hear in heaven and, when he hears, to forgive.', true, 30),
    word(3, 'Solomon asked God to "hear thou in heaven thy ___ place".', 'dwelling', 30),

    // ══════════════════════════════════ v31–32 · The oath before the altar
    mc(2, 'What is the first situation Solomon prays about (v31)?', ['A man sins against his neighbor and is made to take an oath before the altar', 'Israel is defeated before the enemy', 'Heaven is shut up and there is no rain', 'A foreigner comes from a far country'], 31),
    blank(3, '"If a man sins against his neighbor and is made to take an _____, and comes and swears his oath before thine altar in this house,', 'oath', 31),
    tf(2, 'The first petition concerns a man who sins against his neighbor and swears an oath before the altar.', true, 31),
    word(2, 'In verse 31, a man sins against whom?', 'neighbor', 31, ['his neighbor', 'neighbour', 'his neighbour']),
    mc(3, 'In the case of the oath, how did Solomon ask God to condemn the guilty?', ['By bringing his conduct upon his own head', 'By striking him with sickness', 'By sending him into exile', 'By burning him at the altar'], 32),
    blank(3, 'then hear thou in heaven, and act, and judge thy servants, condemning the _____ by bringing his conduct upon his own head, and vindicating the righteous by rewarding him according to his righteousness.', 'guilty', 32),
    tf(3, 'Solomon asked God to vindicate the righteous by rewarding him according to his righteousness.', true, 32),
    word(3, 'God is asked to condemn the guilty and vindicate the ___.', 'righteous', 32),

    // ══════════════════════════════════ v33–34 · Defeat before the enemy
    mc(1, 'Why, in verse 33, are the people of Israel defeated before the enemy?', ['Because they have sinned against the LORD', 'Because their army is small', 'Because the king is young', 'Because of drought'], 33),
    blank(2, '"When thy people Israel are defeated before the _____ because they have sinned against thee, if they turn again to thee, and acknowledge thy name, and pray and make supplication to thee in this house;', 'enemy', 33),
    tf(3, 'In the case of defeat, Solomon asks that the people turn again to God, acknowledge his name, and pray in this house.', true, 33),
    word(3, 'When Israel is defeated before the enemy, they must turn again to God and "acknowledge thy ___".', 'name', 33),
    mc(2, 'After defeat and repentance, what did Solomon ask God to do?', ['Forgive their sin and bring them again to the land given to their fathers', 'Give them new weapons', 'Destroy the enemy’s cities', 'Raise up a new king'], 34),
    blank(2, 'then hear thou in heaven, and forgive the sin of thy people Israel, and bring them again to the _____ which thou gavest to their fathers.', 'land', 34),
    tf(3, 'In the petition about defeat, Solomon asks that the people be given victory over the enemy.', false, 34, 'He asks God to forgive their sin "and bring them again to the land which thou gavest to their fathers".'),

    // ══════════════════════════════════ v35–36 · No rain
    mc(1, 'In verse 35, why is heaven shut up with no rain?', ['Because they have sinned against the LORD', 'Because Solomon delayed the temple', 'Because of the enemy’s siege', 'Because the priests did not minister'], 35),
    blank(1, '"When heaven is shut up and there is no _____ because they have sinned against thee, if they pray toward this place, and acknowledge thy name, and turn from their sin, when thou dost afflict them,', 'rain', 35),
    word(1, 'What is withheld when "heaven is shut up"?', 'rain', 35),
    tf(3, 'The petition about no rain asks that the people turn from their sin when God afflicts them.', true, 35),
    mc(2, 'In the drought petition, what did Solomon ask God to grant?', ['Rain upon thy land, given to thy people as an inheritance', 'Victory over the enemy', 'Compassion from their captors', 'A new harvest of grain'], 36),
    blank(2, 'and grant rain upon thy land, which thou hast given to thy people as an _____.', 'inheritance', 36),
    blank(3, 'then hear thou in heaven, and forgive the sin of thy servants, thy people Israel, when thou dost _____ them the good way in which they should walk;', 'teach', 36),
    tf(3, 'In verse 36 Solomon asks God to teach the people the good way in which they should walk.', true, 36),

    // ══════════════════════════════════ v37–40 · Famine, pestilence, plague
    mc(2, 'Which list of calamities appears in verse 37?', ['Famine, pestilence, blight, mildew, locust, caterpillar', 'Fire, flood, earthquake, storm', 'Sword, exile, plague, death', 'Drought, hail, frost, wind'], 37),
    blank(3, '"If there is famine in the land, if there is pestilence or blight or mildew or _____ or caterpillar;', 'locust', 37, ['locusts']),
    tf(3, 'Verse 37 mentions the enemy besieging the people in any of their cities.', true, 37),
    word(3, 'After "locust", which creature is named in the list of plagues in verse 37?', 'caterpillar', 37, ['caterpillars']),
    tf(3, 'The list of calamities in verse 37 includes hail and earthquake.', false, 37, 'It lists famine, pestilence, blight, mildew, locust, caterpillar, siege, plague and sickness.'),
    mc(3, 'In verse 38, what does each person know as he stretches out his hands toward the house?', ['The affliction of his own heart', 'The name of the LORD', 'The law of Moses', 'The sin of his fathers'], 38),
    blank(3, 'whatever prayer, whatever supplication is made by any man or by all thy people Israel, each knowing the affliction of his own heart and stretching out his _____ toward this house;', 'hands', 38),
    tf(3, 'In verse 38 the one praying stretches out his hands toward the house.', true, 38),
    mc(2, 'According to verse 39, who alone knows the hearts of all the children of men?', ['The LORD ("thou, thou only")', 'The king', 'The priests', 'The prophets'], 39),
    blank(3, 'according to all his ways (for thou, thou only, knowest the _____ of all the children of men);', 'hearts', 39),
    tf(2, 'Solomon said the king alone knows the hearts of all the children of men.', false, 39, '"for thou, thou only, knowest the hearts of all the children of men".'),
    word(3, 'God is asked to "render to each whose ___ thou knowest".', 'heart', 39),
    blank(3, 'that they may _____ thee all the days that they live in the land which thou gavest to our fathers.', 'fear', 40),
    mc(3, 'What purpose is given in verse 40 for God’s answering?', ['That they may fear him all the days they live in the land', 'That they may become rich', 'That the nations may serve them', 'That the king may reign long'], 40),
    tf(3, 'Verse 40 says the goal is that the people may fear the LORD all the days they live in the land.', true, 40),

    // ══════════════════════════════════ v41–43 · The foreigner
    mc(1, 'Who is the subject of the petition in verse 41?', ['A foreigner, not of God’s people Israel, who comes from a far country', 'A priest who has sinned', 'A soldier going to battle', 'A widow of Israel'], 41),
    blank(1, '"Likewise when a _____, who is not of thy people Israel, comes from a far country for thy name’s sake', 'foreigner', 41, ['stranger']),
    tf(1, 'Solomon prayed for the foreigner who comes from a far country for the LORD’s name’s sake.', true, 41),
    word(2, 'The foreigner in verse 41 comes from where?', 'a far country', 41, ['far country', 'far', 'a far land', 'far away']),
    mc(3, 'In verse 42, what will the foreigners hear of?', ['God’s great name, his mighty hand, and his outstretched arm', 'Solomon’s wisdom and wealth', 'The temple’s gold and cedar', 'The victories of David'], 42),
    blank(3, '(for they shall hear of thy great name, and thy mighty hand, and of thy outstretched _____), when he comes and prays toward this house,', 'arm', 42),
    tf(3, 'Verse 42 says the foreigners will hear of Solomon’s wisdom and the beauty of the house.', false, 42, 'They "shall hear of thy great name, and thy mighty hand, and of thy outstretched arm".'),
    mc(2, 'Why did Solomon ask God to answer the foreigner?', ['So that all the peoples of the earth may know his name and fear him, as Israel does', 'So that Israel would gain allies', 'So that the foreigner would pay tribute', 'So that the priests would be honored'], 43),
    blank(3, 'in order that all the peoples of the earth may know thy name and _____ thee, as do thy people Israel,', 'fear', 43),
    blank(3, 'and that they may know that this house which I have built is called by thy _____.', 'name', 43),
    tf(2, 'Solomon asked God to do according to all for which the foreigner calls to him.', true, 43),
    word(3, 'Solomon says the house he has built "is called by thy ___".', 'name', 43),

    // ══════════════════════════════════ v44–45 · Going out to battle
    mc(2, 'In verse 44, toward what do the people pray when they go out to battle?', ['The city God has chosen and the house built for his name', 'The rising sun', 'The camp of the enemy', 'Mount Horeb'], 44),
    blank(1, '"If thy people go out to _____ against their enemy, by whatever way thou shalt send them,', 'battle', 44),
    tf(3, 'In the battle petition, the people go out "by whatever way thou shalt send them".', true, 44),
    word(2, 'In verse 44 the people go out to battle against whom?', 'enemy', 44, ['their enemy', 'enemies', 'their enemies']),
    blank(2, 'then hear thou in heaven their prayer and their supplication, and maintain their _____.', 'cause', 45),
    mc(3, 'What did Solomon ask God to do for the people who pray while out at battle (v45)?', ['Hear their prayer and supplication and maintain their cause', 'Send fire on the enemy', 'Give them spoil', 'Return them to the land'], 45),
    tf(3, 'For those going out to battle, Solomon asked God to bring them back to the land.', false, 45, 'He asked God to "hear thou in heaven their prayer and their supplication, and maintain their cause".'),

    // ══════════════════════════════════ v46–51 · Captivity
    mc(1, 'What does Solomon say in verse 46 about people and sin?', ['"there is no man who does not sin"', '"the righteous never sin"', '"only the king sins"', '"Israel alone is without sin"'], 46),
    blank(1, '"If they sin against thee -- for there is no man who does not _____ -- and thou art angry with them,', 'sin', 46),
    tf(1, 'Solomon said, "there is no man who does not sin".', true, 46),
    word(2, 'In verse 46 the people are carried away ___ to the land of the enemy.', 'captive', 46, ['captives']),
    blank(2, 'and dost give them to an enemy, so that they are carried away _____ to the land of the enemy, far off or near;', 'captive', 46),
    mc(2, 'What confession do the captives make in verse 47?', ['"We have sinned, and have acted perversely and wickedly"', '"We have kept thy law"', '"The LORD has forsaken us"', '"Our fathers sinned, not we"'], 47),
    blank(3, 'yet if they lay it to heart in the land to which they have been carried captive, and _____, and make supplication to thee in the land of their captors,', 'repent', 47),
    tf(2, 'The captives’ confession in verse 47 is "We have sinned, and have acted perversely and wickedly".', true, 47),
    word(3, 'The captives make supplication "in the land of their ___".', 'captors', 47),
    blank(3, 'if they repent with all their mind and with all their _____ in the land of their enemies, who carried them captive,', 'heart', 48),
    mc(3, 'Toward what three things do the captives pray in verse 48?', ['Their land, the city God has chosen, and the house built for his name', 'Heaven, the sun, and the stars', 'The ark, the altar, and the cherubim', 'Egypt, Horeb, and Zion'], 48),
    tf(3, 'In verse 48 the captives are to repent "with all their mind and with all their heart".', true, 48),
    tf(3, 'In verse 48 the captives pray toward the land of their captors.', false, 48, 'They pray toward their own land, the city God has chosen, and the house built for his name.'),
    blank(3, 'then hear thou in heaven thy _____ place their prayer and their supplication, and maintain their cause', 'dwelling', 49),
    tf(2, 'For the captives, Solomon asks God to hear from the temple in Jerusalem.', false, 49, '"then hear thou in heaven thy dwelling place their prayer and their supplication".'),
    mc(2, 'What did Solomon ask God to grant the captives in the sight of their captors?', ['Compassion', 'Riches', 'Weapons', 'Freedom by force'], 50),
    blank(2, 'and grant them _____ in the sight of those who carried them captive, that they may have compassion on them', 'compassion', 50),
    tf(2, 'Solomon asked God to grant the captives vengeance on those who carried them captive.', false, 50, 'He asked God to "grant them compassion in the sight of those who carried them captive".'),
    word(3, 'In verse 50 God is asked to forgive all their ___ which they have committed against him.', 'transgressions', 50, ['transgression']),
    mc(2, 'From where did Solomon say God brought his people, his heritage?', ['Out of Egypt, from the midst of the iron furnace', 'Out of Babylon', 'Out of the wilderness of Sinai', 'Out of Horeb'], 51),
    blank(2, '(for they are thy people, and thy heritage, which thou didst bring out of Egypt, from the midst of the iron _____).', 'furnace', 51),
    word(2, 'Egypt is described in verse 51 as "the iron ___".', 'furnace', 51),
    tf(2, 'Verse 51 describes Egypt as "the iron furnace".', true, 51),
    tf(3, 'Verse 51 describes Egypt as "the house of bondage".', false, 51, 'It says "from the midst of the iron furnace".'),

    // ══════════════════════════════════ v52–53 · Close of the prayer
    blank(3, 'Let thy eyes be open to the supplication of thy servant, and to the supplication of thy people Israel, giving _____ to them whenever they call to thee.', 'ear', 52),
    mc(3, 'In verse 52, when did Solomon ask God to give ear to the people?', ['Whenever they call to him', 'Only at the feasts', 'Once each year', 'When the king prays for them'], 52),
    word(2, 'Solomon asked God to give ___ to the people whenever they call to him.', 'ear', 52),
    mc(2, 'Through whom did God declare that Israel would be his heritage (v53)?', ['Moses his servant', 'David', 'Abraham', 'Samuel'], 53),
    blank(2, 'For thou didst separate them from among all the peoples of the earth, to be thy heritage, as thou didst declare through _____, thy servant, when thou didst bring our fathers out of Egypt, O Lord GOD."', 'Moses', 53),
    tf(2, 'Solomon said God separated Israel from among all the peoples of the earth to be his heritage.', true, 53),
    word(3, 'God separated Israel from among all the peoples of the earth to be his ___.', 'heritage', 53),
    mc(3, 'With what words does Solomon’s prayer end in verse 53?', ['"O Lord GOD"', '"Amen"', '"for ever and ever"', '"Blessed be the LORD"'], 53),

    // ══════════════════════════════════ v54–61 · Solomon’s closing blessing
    mc(1, 'In what posture had Solomon prayed, according to verse 54?', ['Kneeling with hands outstretched toward heaven', 'Standing with head bowed', 'Lying face down', 'Seated on his throne'], 54),
    blank(1, 'he arose from before the altar of the LORD, where he had _____ with hands outstretched toward heaven;', 'knelt', 54, ['kneeled']),
    tf(1, 'Solomon had knelt before the altar with his hands outstretched toward heaven.', true, 54),
    word(2, 'After finishing his prayer, Solomon arose from before what?', 'altar', 54, ['the altar', 'the altar of the lord']),
    tf(2, 'Verse 54 says Solomon prayed lying prostrate on the ground.', false, 54, 'He had knelt with hands outstretched toward heaven.'),
    blank(1, 'and he stood, and blessed all the assembly of Israel with a loud _____, saying,', 'voice', 55),
    mc(2, 'How did Solomon bless the assembly after his prayer?', ['Standing, with a loud voice', 'Kneeling, in a whisper', 'From his throne, through a priest', 'By writing it on tablets'], 55),
    tf(1, 'After the prayer, Solomon blessed the assembly with a loud voice.', true, 55),
    mc(2, 'For what did Solomon bless the LORD in verse 56?', ['Giving rest to his people Israel, with not one word of his good promise failing', 'Giving Solomon wisdom', 'Defeating the Philistines', 'Sending rain'], 56),
    blank(1, '"Blessed be the LORD who has given _____ to his people Israel, according to all that he promised;', 'rest', 56),
    blank(3, 'not one word has failed of all his good promise, which he uttered by _____ his servant.', 'Moses', 56),
    tf(3, 'Solomon said not one word had failed of all God’s good promise uttered by Moses.', true, 56),
    word(2, 'Solomon said not one ___ has failed of all God’s good promise.', 'word', 56),
    tf(3, 'In verse 56 Solomon says the good promise was uttered by David his servant.', false, 56, 'It was "uttered by Moses his servant".'),
    blank(1, 'The LORD our God be with us, as he was with our fathers; may he not leave us or _____ us;', 'forsake', 57),
    mc(2, 'What did Solomon ask in verse 57?', ['That the LORD be with us as with our fathers and not leave or forsake us', 'That the LORD give us victory', 'That the LORD send rain', 'That the LORD destroy our enemies'], 57),
    word(1, 'Solomon prayed, "may he not leave us or ___ us".', 'forsake', 57),
    blank(3, 'that he may incline our _____ to him, to walk in all his ways, and to keep his commandments, his statutes, and his ordinances, which he commanded our fathers.', 'hearts', 58),
    mc(3, 'What three things does verse 58 say are to be kept?', ['His commandments, his statutes, and his ordinances', 'The feasts, the sabbaths, and the tithes', 'The law, the prophets, and the psalms', 'Oaths, vows, and offerings'], 58),
    word(2, 'Solomon asked that God incline our hearts "to walk in all his ___".', 'ways', 58),
    word(3, 'Solomon asked that God may "___ our hearts to him".', 'incline', 58),
    blank(3, 'Let these words of mine, wherewith I have made supplication before the LORD, be near to the LORD our God day and _____,', 'night', 59),
    mc(3, 'In verse 59 Solomon asks that God maintain whose cause?', ['The cause of his servant and the cause of his people Israel', 'The cause of the foreigner', 'The cause of the priests', 'The cause of the widow'], 59),
    tf(3, 'Solomon asked that his words be near to the LORD "day and night".', true, 59),
    word(3, 'God is asked to maintain the cause of his people "as each ___ requires".', 'day', 59),
    blank(1, 'that all the peoples of the earth may know that the LORD is God; there is no _____.', 'other', 60),
    mc(1, 'What did Solomon want all the peoples of the earth to know (v60)?', ['That the LORD is God; there is no other', 'That Solomon is the wisest king', 'That Israel is the greatest nation', 'That the temple is the largest house'], 60),
    tf(1, 'Solomon prayed that all the peoples of the earth may know that the LORD is God and there is no other.', true, 60),
    blank(2, 'Let your heart therefore be wholly _____ to the LORD our God, walking in his statutes and keeping his commandments, as at this day."', 'true', 61),
    mc(2, 'What did Solomon charge the people’s heart to be?', ['Wholly true to the LORD our God', 'Loyal to the king', 'Steadfast in sacrifice', 'Humble before the priests'], 61),
    tf(2, 'Solomon urged the people to let their heart be wholly true to the LORD.', true, 61),
    word(1, 'Solomon said, "Let your heart therefore be wholly ___ to the LORD our God".', 'true', 61),

    // ══════════════════════════════════ v62–66 · The dedication and feast
    blank(1, 'Then the king, and all Israel with him, offered _____ before the LORD.', 'sacrifice', 62),
    word(1, 'In verse 62 the king and all Israel offered what before the LORD?', 'sacrifice', 62, ['sacrifices', 'a sacrifice']),
    mc(1, 'Who offered sacrifice before the LORD in verse 62?', ['The king and all Israel with him', 'The priests alone', 'The Levites alone', 'The elders only'], 62),
    mc(1, 'How many oxen did Solomon offer as peace offerings?', ['Twenty-two thousand', 'Twelve thousand', 'A hundred and twenty thousand', 'Two thousand'], 63),
    mc(1, 'How many sheep did Solomon offer as peace offerings?', ['A hundred and twenty thousand', 'Twenty-two thousand', 'Twelve thousand', 'Twenty thousand'], 63),
    blank(1, 'Solomon offered as peace offerings to the LORD twenty-two thousand _____ and a hundred and twenty thousand sheep.', 'oxen', 63),
    blank(2, 'Solomon offered as peace offerings to the LORD _____ oxen and a hundred and twenty thousand sheep.', 'twenty-two thousand', 63, ['22000', '22,000', 'twenty two thousand']),
    word(1, 'How many sheep were offered as peace offerings at the dedication of the house?', 'a hundred and twenty thousand', 63, ['120000', '120,000', 'one hundred twenty thousand', 'hundred and twenty thousand', 'one hundred and twenty thousand', '120 thousand']),
    word(1, 'How many oxen did Solomon offer as peace offerings at the dedication of the house?', 'twenty-two thousand', 63, ['22000', '22,000', 'twenty two thousand', '22 thousand']),
    tf(1, 'Solomon offered twenty-two thousand oxen as peace offerings.', true, 63),
    tf(2, 'Solomon offered twenty-two thousand sheep and a hundred and twenty thousand oxen.', false, 63, 'It was twenty-two thousand oxen and a hundred and twenty thousand sheep.'),
    blank(1, 'So the king and all the people of Israel _____ the house of the LORD.', 'dedicated', 63),
    mc(2, 'The oxen and sheep in verse 63 were offered as what kind of offering?', ['Peace offerings', 'Sin offerings', 'Guilt offerings', 'Wave offerings'], 63),
    mc(2, 'Why did the king consecrate the middle of the court?', ['The bronze altar was too small to receive all the offerings', 'The priests refused to use the altar', 'The cloud covered the altar', 'The people could not see the altar'], 64),
    blank(2, 'because the _____ altar that was before the LORD was too small to receive the burnt offering and the cereal offering and the fat pieces of the peace offerings.', 'bronze', 64, ['brazen', 'brass']),
    blank(3, 'The same day the king consecrated the middle of the _____ that was before the house of the LORD;', 'court', 64),
    tf(1, 'The bronze altar was too small to receive the offerings.', true, 64),
    word(2, 'What part of the court did the king consecrate the same day?', 'middle', 64, ['the middle', 'middle of the court']),
    mc(3, 'Which three kinds of offering does verse 64 say were offered in the middle of the court?', ['The burnt offering, the cereal offering, and the fat pieces of the peace offerings', 'Sin, guilt, and wave offerings', 'Drink, incense, and firstfruit offerings', 'Thank, vow, and freewill offerings'], 64),
    tf(3, 'The altar before the LORD in verse 64 was made of gold.', false, 64, 'It was "the bronze altar".'),
    mc(1, 'The great assembly at the feast came from where to where?', ['From the entrance of Hamath to the Brook of Egypt', 'From Dan to Beersheba', 'From Jerusalem to Jericho', 'From Lebanon to the Red Sea'], 65),
    blank(2, 'a great assembly, from the entrance of _____ to the Brook of Egypt, before the LORD our God, seven days.', 'Hamath', 65),
    blank(1, 'So Solomon held the feast at that time, and all Israel with him, a great assembly, from the entrance of Hamath to the Brook of Egypt, before the LORD our God, _____ days.', 'seven', 65, ['7']),
    word(1, 'How many days did Solomon hold the feast?', 'seven', 65, ['7', 'seven days', '7 days']),
    word(3, 'The assembly stretched from the entrance of Hamath to the Brook of ___.', 'Egypt', 65),
    tf(1, 'Solomon held the feast for fourteen days.', false, 65, 'The feast lasted "seven days".'),
    tf(2, 'The assembly stretched from the entrance of Hamath to the Brook of Egypt.', true, 65),
    mc(1, 'On which day did Solomon send the people away?', ['The eighth day', 'The seventh day', 'The tenth day', 'The first day of the next month'], 66),
    blank(1, 'On the _____ day he sent the people away; and they blessed the king,', 'eighth', 66, ['8th']),
    mc(1, 'How did the people go to their homes?', ['Joyful and glad of heart for all the goodness the LORD had shown to David and to Israel', 'Weeping because the feast was over', 'In fear because of the cloud', 'Silently in procession'], 66),
    blank(2, 'and went to their homes joyful and glad of _____ for all the goodness that the LORD had shown to David his servant and to Israel his people.', 'heart', 66),
    tf(1, 'The people went to their homes joyful and glad of heart.', true, 66),
    tf(1, 'Solomon sent the people away on the seventh day.', false, 66, 'He sent them away "on the eighth day".'),
    word(2, 'Before going home on the eighth day, what did the people do to the king — they ___ him.', 'blessed', 66, ['bless', 'blessed him']),
    mc(2, 'Why were the people glad of heart in verse 66?', ['For all the goodness the LORD had shown to David his servant and to Israel his people', 'Because Solomon had given them gifts', 'Because the harvest was great', 'Because the enemy had been defeated'], 66),

    // ══════════════════════════════════ Whole-chapter
    mc(2, 'Which of these events happened FIRST in 1 Kings 8?', ['The priests brought the ark into the most holy place', 'The cloud filled the house', 'Solomon knelt and prayed before the altar', 'Solomon offered peace offerings and dedicated the house'], 6),
    mc(3, 'Which of these events happened LAST in 1 Kings 8?', ['Solomon sent the people to their homes on the eighth day', 'The cloud filled the house of the LORD', 'Solomon blessed the assembly with a loud voice', 'The priests brought the ark to the inner sanctuary'], 66),
    mc(1, 'Who said, "there is no man who does not sin"?', ['Solomon, in his prayer of dedication', 'David, to Solomon', 'The LORD, to David', 'Moses'], 46),
    mc(1, 'Who speaks nearly all the words recorded in 1 Kings 8:12–61?', ['Solomon', 'Nathan the prophet', 'Zadok the priest', 'David'], 22),
    tf(2, 'In 1 Kings 8 the ark was carried into the temple by the elders of Israel.', false, 3, 'The priests took up the ark and brought it to its place.'),
    mc(3, 'Which of these situations is NOT one of the petitions in Solomon’s prayer?', ['A king who dies without an heir', 'Defeat before the enemy', 'No rain because of sin', 'Captivity in the land of the enemy'], 33),
    mc(3, 'In Solomon’s prayer, which petition comes immediately after the one about no rain?', ['Famine, pestilence, blight, mildew, locust, caterpillar', 'The foreigner from a far country', 'Defeat before the enemy', 'Captivity'], 37),
  ],
};

export default bank;
