// 1 Kings 21 — quiz bank (RSV). Four verse-anchored forms per verse.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: "1 Kings",
  chapter: 21,
  tag: "quiz-v2-1kings-21",
  rows: [
    blank(2, "Now Naboth the _____ had a vineyard in Jezreel, beside the palace of Ahab king of Sama’ria.", "Jezreelite", 1, ["jezreelite"]),
    mc(3, "Which word correctly completes this RSV wording: “Now Naboth the _____ had a vineyard in Jezreel, beside the palace of Ahab king of Sama’ria.”", ["Jezreelite", "Ahab’s", "Jezreel", "Jerobo’am"], 1),
    word(1, "In verse 1, what word completes this phrase: “Now Naboth the _____ had a vineyard in Jezreel, beside the palace of Ahab king of Sama’ria.”?", "Jezreelite", 1, ["jezreelite"]),
    tf(2, "The RSV states: “Now Naboth the Jezreelite had a vineyard in Jezreel, beside the palace of Ahab king of Sama’ria.”", true, 1),
    blank(3, "And after this Ahab said to _____, \"Give me your vineyard, that I may have it for a vegetable garden, because", "Naboth", 2, ["naboth"]),
    mc(1, "Which word correctly completes this RSV wording: “And after this Ahab said to _____, \"Give me your vineyard, that I may have it for a vegetable garden, because”", ["Naboth", "Behold", "Jez’ebel", "Nebat"], 2),
    word(2, "In verse 2, what word completes this phrase: “And after this Ahab said to _____, \"Give me your vineyard, that I may have it for a vegetable garden, because”?", "Naboth", 2, ["naboth"]),
    tf(3, "The RSV does not state: “And after this Ahab said to Naboth, \"Give me your vineyard, that I may have it for a vegetable garden, because it is near my house; and I will give you a better vineyard for it; or, if it seems good to you, I will give you its value in money.\"”", false, 2, "The quoted wording is the RSV text of this verse."),
    blank(1, "But _____ said to Ahab, \"The LORD forbid that I should give you the inheritance", "Naboth", 3, ["naboth"]),
    mc(2, "Which word correctly completes this RSV wording: “But _____ said to Ahab, \"The LORD forbid that I should give you the inheritance”", ["Naboth", "Jezreel", "Tishbite", "Sama’ria"], 3),
    word(3, "In verse 3, what word completes this phrase: “But _____ said to Ahab, \"The LORD forbid that I should give you the inheritance”?", "Naboth", 3, ["naboth"]),
    tf(1, "The RSV states: “But Naboth said to Ahab, \"The LORD forbid that I should give you the inheritance of my fathers.\"”", true, 3),
    blank(2, "Ahab went into his house vexed and sullen because of what Naboth the _____ had said to him; for he had said, \"I will not give you the inheritance", "Jezreelite", 4, ["jezreelite"]),
    mc(3, "Which word correctly completes this RSV wording: “Ahab went into his house vexed and sullen because of what Naboth the _____ had said to him; for he had said, \"I will not give you the inheritance”", ["Jezreelite", "Behold", "Israel", "Amorites"], 4),
    word(1, "In verse 4, what word completes this phrase: “Ahab went into his house vexed and sullen because of what Naboth the _____ had said to him; for he had said, \"I will not give you the inheritance”?", "Jezreelite", 4, ["jezreelite"]),
    tf(2, "The RSV does not state: “And Ahab went into his house vexed and sullen because of what Naboth the Jezreelite had said to him; for he had said, \"I will not give you the inheritance of my fathers.\" And he lay down on his bed, and turned away his face, and would eat no food.”", false, 4, "The quoted wording is the RSV text of this verse."),
    blank(3, "But _____ his wife came to him, and said to him, \"Why is your spirit so vexed that", "Jez’ebel", 5, ["jezebel"]),
    mc(1, "Which word correctly completes this RSV wording: “But _____ his wife came to him, and said to him, \"Why is your spirit so vexed that”", ["Jez’ebel", "Jerobo’am", "Because", "Ba’asha"], 5),
    word(2, "In verse 5, what word completes this phrase: “But _____ his wife came to him, and said to him, \"Why is your spirit so vexed that”?", "Jez’ebel", 5, ["jezebel"]),
    tf(3, "The RSV states: “But Jez’ebel his wife came to him, and said to him, \"Why is your spirit so vexed that you eat no food?\"”", true, 5),
    blank(1, "And he said to her, \"Because I spoke to Naboth the _____, and said to him, `Give me your vineyard for money; or else, if it please", "Jezreelite", 6, ["jezreelite"]),
    mc(2, "Which word correctly completes this RSV wording: “And he said to her, \"Because I spoke to Naboth the _____, and said to him, `Give me your vineyard for money; or else, if it please”", ["Jezreelite", "Proclaim", "Sama’ria", "Nebat"], 6),
    word(3, "In verse 6, what word completes this phrase: “And he said to her, \"Because I spoke to Naboth the _____, and said to him, `Give me your vineyard for money; or else, if it please”?", "Jezreelite", 6, ["jezreelite"]),
    tf(1, "The RSV does not state: “And he said to her, \"Because I spoke to Naboth the Jezreelite, and said to him, `Give me your vineyard for money; or else, if it please you, I will give you another vineyard for it’; and he answered, `I will not give you my vineyard.’\"”", false, 6, "The quoted wording is the RSV text of this verse."),
    blank(2, "let your heart be cheerful; I will give you the vineyard of Naboth the _____.\"", "Jezreelite", 7, ["jezreelite"]),
    mc(3, "Which word correctly completes this RSV wording: “let your heart be cheerful; I will give you the vineyard of Naboth the _____.\"”", ["Jezreelite", "Ahi’jah", "Eli’jah", "Jez’ebel"], 7),
    word(1, "In verse 7, what word completes this phrase: “let your heart be cheerful; I will give you the vineyard of Naboth the _____.\"”?", "Jezreelite", 7, ["jezreelite"]),
    tf(2, "The RSV states: “And Jez’ebel his wife said to him, \"Do you now govern Israel? Arise, and eat bread, and let your heart be cheerful; I will give you the vineyard of Naboth the Jezreelite.\"”", true, 7),
    blank(3, "So she wrote letters in _____ name and sealed them with his seal, and she sent the letters to the elders", "Ahab’s", 8, ["ahabs"]),
    mc(1, "Which word correctly completes this RSV wording: “So she wrote letters in _____ name and sealed them with his seal, and she sent the letters to the elders”", ["Ahab’s", "Nebat", "Because", "Ahi’jah"], 8),
    word(2, "In verse 8, what word completes this phrase: “So she wrote letters in _____ name and sealed them with his seal, and she sent the letters to the elders”?", "Ahab’s", 8, ["ahabs"]),
    tf(3, "The RSV does not state: “So she wrote letters in Ahab’s name and sealed them with his seal, and she sent the letters to the elders and the nobles who dwelt with Naboth in his city.”", false, 8, "The quoted wording is the RSV text of this verse."),
    blank(1, "And she wrote in the letters, \"_____ a fast, and set Naboth on high among the people;", "Proclaim", 9, ["proclaim"]),
    mc(2, "Which word correctly completes this RSV wording: “And she wrote in the letters, \"_____ a fast, and set Naboth on high among the people;”", ["Proclaim", "Ahab", "Behold", "Give"], 9),
    word(3, "In verse 9, what word completes this phrase: “And she wrote in the letters, \"_____ a fast, and set Naboth on high among the people;”?", "Proclaim", 9, ["proclaim"]),
    tf(1, "The RSV states: “And she wrote in the letters, \"Proclaim a fast, and set Naboth on high among the people;”", true, 9),
    blank(2, "and set two base fellows _____ him, and let them bring a charge against him, saying, `You have cursed", "opposite", 10, ["opposite"]),
    mc(3, "Which word correctly completes this RSV wording: “and set two base fellows _____ him, and let them bring a charge against him, saying, `You have cursed”", ["opposite", "took", "meet", "blood"], 10),
    word(1, "In verse 10, what word completes this phrase: “and set two base fellows _____ him, and let them bring a charge against him, saying, `You have cursed”?", "opposite", 10, ["opposite"]),
    tf(2, "The RSV does not state: “and set two base fellows opposite him, and let them bring a charge against him, saying, `You have cursed God and the king.’ Then take him out, and stone him to death.\"”", false, 10, "The quoted wording is the RSV text of this verse."),
    blank(3, "of his city, the elders and the nobles who dwelt in his city, did as _____ had sent word to them. As it was written in the letters which she had", "Jez’ebel", 11, ["jezebel"]),
    mc(1, "Which word correctly completes this RSV wording: “of his city, the elders and the nobles who dwelt in his city, did as _____ had sent word to them. As it was written in the letters which she had”", ["Jez’ebel", "Ba’asha", "Arise", "Amorites"], 11),
    word(2, "In verse 11, what word completes this phrase: “of his city, the elders and the nobles who dwelt in his city, did as _____ had sent word to them. As it was written in the letters which she had”?", "Jez’ebel", 11, ["jezebel"]),
    tf(3, "The RSV states: “And the men of his city, the elders and the nobles who dwelt in his city, did as Jez’ebel had sent word to them. As it was written in the letters which she had sent to them,”", true, 11),
    blank(1, "they proclaimed a fast, and set _____ on high among the people.", "Naboth", 12, ["naboth"]),
    mc(2, "Which word correctly completes this RSV wording: “they proclaimed a fast, and set _____ on high among the people.”", ["Naboth", "Give", "Jerobo’am", "Because"], 12),
    word(3, "In verse 12, what word completes this phrase: “they proclaimed a fast, and set _____ on high among the people.”?", "Naboth", 12, ["naboth"]),
    tf(1, "The RSV does not state: “they proclaimed a fast, and set Naboth on high among the people.”", false, 12, "The quoted wording is the RSV text of this verse."),
    blank(2, "in and sat opposite him; and the base fellows brought a charge against _____, in the presence of the people, saying, \"Naboth cursed God and the king.\"", "Naboth", 13, ["naboth"]),
    mc(3, "Which word correctly completes this RSV wording: “in and sat opposite him; and the base fellows brought a charge against _____, in the presence of the people, saying, \"Naboth cursed God and the king.\"”", ["Naboth", "Eli’jah", "Ahab", "Thus"], 13),
    word(1, "In verse 13, what word completes this phrase: “in and sat opposite him; and the base fellows brought a charge against _____, in the presence of the people, saying, \"Naboth cursed God and the king.\"”?", "Naboth", 13, ["naboth"]),
    tf(2, "The RSV states: “And the two base fellows came in and sat opposite him; and the base fellows brought a charge against Naboth, in the presence of the people, saying, \"Naboth cursed God and the king.\" So they took him outside the city, and stoned him to death with stones.”", true, 13),
    blank(3, "Then they sent to _____, saying, \"Naboth has been stoned; he is dead.\"", "Jez’ebel", 14, ["jezebel"]),
    mc(1, "Which word correctly completes this RSV wording: “Then they sent to _____, saying, \"Naboth has been stoned; he is dead.\"”", ["Jez’ebel", "Ahi’jah", "Ahab’s", "Naboth"], 14),
    word(2, "In verse 14, what word completes this phrase: “Then they sent to _____, saying, \"Naboth has been stoned; he is dead.\"”?", "Jez’ebel", 14, ["jezebel"]),
    tf(3, "The RSV does not state: “Then they sent to Jez’ebel, saying, \"Naboth has been stoned; he is dead.\"”", false, 14, "The quoted wording is the RSV text of this verse."),
    blank(1, "Jez’ebel said to Ahab, \"Arise, take possession of the vineyard of Naboth the _____, which he refused to give you for money; for Naboth is not alive, but", "Jezreelite", 15, ["jezreelite"]),
    mc(2, "Which word correctly completes this RSV wording: “Jez’ebel said to Ahab, \"Arise, take possession of the vineyard of Naboth the _____, which he refused to give you for money; for Naboth is not alive, but”", ["Jezreelite", "Jez’ebel", "Ba’asha", "Proclaim"], 15),
    word(3, "In verse 15, what word completes this phrase: “Jez’ebel said to Ahab, \"Arise, take possession of the vineyard of Naboth the _____, which he refused to give you for money; for Naboth is not alive, but”?", "Jezreelite", 15, ["jezreelite"]),
    tf(1, "The RSV states: “As soon as Jez’ebel heard that Naboth had been stoned and was dead, Jez’ebel said to Ahab, \"Arise, take possession of the vineyard of Naboth the Jezreelite, which he refused to give you for money; for Naboth is not alive, but dead.\"”", true, 15),
    blank(2, "Naboth was dead, Ahab arose to go down to the vineyard of Naboth the _____, to take possession of it.", "Jezreelite", 16, ["jezreelite"]),
    mc(3, "Which word correctly completes this RSV wording: “Naboth was dead, Ahab arose to go down to the vineyard of Naboth the _____, to take possession of it.”", ["Jezreelite", "Tishbite", "Because", "Ahi’jah"], 16),
    word(1, "In verse 16, what word completes this phrase: “Naboth was dead, Ahab arose to go down to the vineyard of Naboth the _____, to take possession of it.”?", "Jezreelite", 16, ["jezreelite"]),
    tf(2, "The RSV does not state: “And as soon as Ahab heard that Naboth was dead, Ahab arose to go down to the vineyard of Naboth the Jezreelite, to take possession of it.”", false, 16, "The quoted wording is the RSV text of this verse."),
    blank(3, "Then the word of the LORD came to Eli’jah the _____, saying,", "Tishbite", 17, ["tishbite"]),
    mc(1, "Which word correctly completes this RSV wording: “Then the word of the LORD came to Eli’jah the _____, saying,”", ["Tishbite", "Amorites", "Ahab’s", "Jezreelite"], 17),
    word(2, "In verse 17, what word completes this phrase: “Then the word of the LORD came to Eli’jah the _____, saying,”?", "Tishbite", 17, ["tishbite"]),
    tf(3, "The RSV states: “Then the word of the LORD came to Eli’jah the Tishbite, saying,”", true, 17),
    blank(1, "\"Arise, go down to meet Ahab king of Israel, who is in _____; behold, he is in the vineyard of Naboth, where he has gone to take possession.", "Sama’ria", 18, ["samaria"]),
    mc(2, "Which word correctly completes this RSV wording: “\"Arise, go down to meet Ahab king of Israel, who is in _____; behold, he is in the vineyard of Naboth, where he has gone to take possession.”", ["Sama’ria", "Because", "Ba’asha", "Arise"], 18),
    word(3, "In verse 18, what word completes this phrase: “\"Arise, go down to meet Ahab king of Israel, who is in _____; behold, he is in the vineyard of Naboth, where he has gone to take possession.”?", "Sama’ria", 18, ["samaria"]),
    tf(1, "The RSV does not state: “\"Arise, go down to meet Ahab king of Israel, who is in Sama’ria; behold, he is in the vineyard of Naboth, where he has gone to take possession.”", false, 18, "The quoted wording is the RSV text of this verse."),
    blank(2, "`Thus says the LORD: \"In the place where dogs licked up the blood of _____ shall dogs lick your own blood.\"’\"", "Naboth", 19, ["naboth"]),
    mc(3, "Which word correctly completes this RSV wording: “`Thus says the LORD: \"In the place where dogs licked up the blood of _____ shall dogs lick your own blood.\"’\"”", ["Naboth", "Thus", "Give", "Jerobo’am"], 19),
    word(1, "In verse 19, what word completes this phrase: “`Thus says the LORD: \"In the place where dogs licked up the blood of _____ shall dogs lick your own blood.\"’\"”?", "Naboth", 19, ["naboth"]),
    tf(2, "The RSV states: “And you shall say to him, `Thus says the LORD, \"Have you killed, and also taken possession?\"’ And you shall say to him, `Thus says the LORD: \"In the place where dogs licked up the blood of Naboth shall dogs lick your own blood.\"’\"”", true, 19),
    blank(3, "Ahab said to _____, \"Have you found me, O my enemy?\" He answered, \"I have found you, because", "Eli’jah", 20, ["elijah"]),
    mc(1, "Which word correctly completes this RSV wording: “Ahab said to _____, \"Have you found me, O my enemy?\" He answered, \"I have found you, because”", ["Eli’jah", "Naboth", "Proclaim", "Jezreel"], 20),
    word(2, "In verse 20, what word completes this phrase: “Ahab said to _____, \"Have you found me, O my enemy?\" He answered, \"I have found you, because”?", "Eli’jah", 20, ["elijah"]),
    tf(3, "The RSV does not state: “Ahab said to Eli’jah, \"Have you found me, O my enemy?\" He answered, \"I have found you, because you have sold yourself to do what is evil in the sight of the LORD.”", false, 20, "The quoted wording is the RSV text of this verse."),
    blank(1, "_____, I will bring evil upon you; I will utterly sweep you away, and will cut", "Behold", 21, ["behold"]),
    mc(2, "Which word correctly completes this RSV wording: “_____, I will bring evil upon you; I will utterly sweep you away, and will cut”", ["Behold", "Because", "Ahi’jah", "Arise"], 21),
    word(3, "In verse 21, what word completes this phrase: “_____, I will bring evil upon you; I will utterly sweep you away, and will cut”?", "Behold", 21, ["behold"]),
    tf(1, "The RSV states: “Behold, I will bring evil upon you; I will utterly sweep you away, and will cut off from Ahab every male, bond or free, in Israel;”", true, 21),
    blank(2, "and I will make your house like the house of _____ the son of Nebat, and like the house of Ba’asha the son of Ahi’jah, for", "Jerobo’am", 22, ["jeroboam"]),
    mc(3, "Which word correctly completes this RSV wording: “and I will make your house like the house of _____ the son of Nebat, and like the house of Ba’asha the son of Ahi’jah, for”", ["Jerobo’am", "Thus", "Give", "Nebat"], 22),
    word(1, "In verse 22, what word completes this phrase: “and I will make your house like the house of _____ the son of Nebat, and like the house of Ba’asha the son of Ahi’jah, for”?", "Jerobo’am", 22, ["jeroboam"]),
    tf(2, "The RSV does not state: “and I will make your house like the house of Jerobo’am the son of Nebat, and like the house of Ba’asha the son of Ahi’jah, for the anger to which you have provoked me, and because you have made Israel to sin.”", false, 22, "The quoted wording is the RSV text of this verse."),
    blank(3, "And of _____ the LORD also said, `The dogs shall eat Jez’ebel within the bounds of", "Jez’ebel", 23, ["jezebel"]),
    mc(1, "Which word correctly completes this RSV wording: “And of _____ the LORD also said, `The dogs shall eat Jez’ebel within the bounds of”", ["Jez’ebel", "Jezreelite", "Tishbite", "Ahab"], 23),
    word(2, "In verse 23, what word completes this phrase: “And of _____ the LORD also said, `The dogs shall eat Jez’ebel within the bounds of”?", "Jez’ebel", 23, ["jezebel"]),
    tf(3, "The RSV states: “And of Jez’ebel the LORD also said, `The dogs shall eat Jez’ebel within the bounds of Jezreel.’”", true, 23),
    blank(1, "Any one belonging to _____ who dies in the city the dogs shall eat; and any one of his who dies in", "Ahab", 24, ["ahab"]),
    mc(2, "Which word correctly completes this RSV wording: “Any one belonging to _____ who dies in the city the dogs shall eat; and any one of his who dies in”", ["Ahab", "Ba’asha", "Ahab’s", "Naboth"], 24),
    word(3, "In verse 24, what word completes this phrase: “Any one belonging to _____ who dies in the city the dogs shall eat; and any one of his who dies in”?", "Ahab", 24, ["ahab"]),
    tf(1, "The RSV does not state: “Any one belonging to Ahab who dies in the city the dogs shall eat; and any one of his who dies in the open country the birds of the air shall eat.\"”", false, 24, "The quoted wording is the RSV text of this verse."),
    blank(2, "himself to do what was evil in the sight of the LORD like Ahab, whom _____ his wife incited.", "Jez’ebel", 25, ["jezebel"]),
    mc(3, "Which word correctly completes this RSV wording: “himself to do what was evil in the sight of the LORD like Ahab, whom _____ his wife incited.”", ["Jez’ebel", "Jerobo’am", "Because", "Ba’asha"], 25),
    word(1, "In verse 25, what word completes this phrase: “himself to do what was evil in the sight of the LORD like Ahab, whom _____ his wife incited.”?", "Jez’ebel", 25, ["jezebel"]),
    tf(2, "The RSV states: “(There was none who sold himself to do what was evil in the sight of the LORD like Ahab, whom Jez’ebel his wife incited.”", true, 25),
    blank(3, "He did very abominably in going after idols, as the _____ had done, whom the LORD cast out before the people of Israel.)", "Amorites", 26, ["amorites"]),
    mc(1, "Which word correctly completes this RSV wording: “He did very abominably in going after idols, as the _____ had done, whom the LORD cast out before the people of Israel.)”", ["Amorites", "Jezreel", "Tishbite", "Sama’ria"], 26),
    word(2, "In verse 26, what word completes this phrase: “He did very abominably in going after idols, as the _____ had done, whom the LORD cast out before the people of Israel.)”?", "Amorites", 26, ["amorites"]),
    tf(3, "The RSV does not state: “He did very abominably in going after idols, as the Amorites had done, whom the LORD cast out before the people of Israel.)”", false, 26, "The quoted wording is the RSV text of this verse."),
    blank(1, "And when _____ heard those words, he rent his clothes, and put sackcloth upon his flesh,", "Ahab", 27, ["ahab"]),
    mc(2, "Which word correctly completes this RSV wording: “And when _____ heard those words, he rent his clothes, and put sackcloth upon his flesh,”", ["Ahab", "Amorites", "Eli’jah", "Sama’ria"], 27),
    word(3, "In verse 27, what word completes this phrase: “And when _____ heard those words, he rent his clothes, and put sackcloth upon his flesh,”?", "Ahab", 27, ["ahab"]),
    tf(1, "The RSV states: “And when Ahab heard those words, he rent his clothes, and put sackcloth upon his flesh, and fasted and lay in sackcloth, and went about dejectedly.”", true, 27),
    blank(2, "And the word of the LORD came to Eli’jah the _____, saying,", "Tishbite", 28, ["tishbite"]),
    mc(3, "Which word correctly completes this RSV wording: “And the word of the LORD came to Eli’jah the _____, saying,”", ["Tishbite", "Nebat", "Because", "Ahi’jah"], 28),
    word(1, "In verse 28, what word completes this phrase: “And the word of the LORD came to Eli’jah the _____, saying,”?", "Tishbite", 28, ["tishbite"]),
    tf(2, "The RSV does not state: “And the word of the LORD came to Eli’jah the Tishbite, saying,”", false, 28, "The quoted wording is the RSV text of this verse."),
    blank(3, "\"Have you seen how Ahab has humbled himself before me? _____ he has humbled himself before me, I will not bring the evil in his days;", "Because", 29, ["because"]),
    mc(1, "Which word correctly completes this RSV wording: “\"Have you seen how Ahab has humbled himself before me? _____ he has humbled himself before me, I will not bring the evil in his days;”", ["Because", "Ahab", "Behold", "Give"], 29),
    word(2, "In verse 29, what word completes this phrase: “\"Have you seen how Ahab has humbled himself before me? _____ he has humbled himself before me, I will not bring the evil in his days;”?", "Because", 29, ["because"]),
    tf(3, "The RSV states: “\"Have you seen how Ahab has humbled himself before me? Because he has humbled himself before me, I will not bring the evil in his days; but in his son’s days I will bring the evil upon his house.\"”", true, 29),
    blank(1, "Now Naboth the Jezreelite had a _____ in Jezreel, beside the palace of Ahab king of Sama’ria.", "vineyard", 1, ["vineyard"]),
    mc(2, "Select the missing RSV word: “Ahab said to Naboth, \"Give me your vineyard, that I may have it for a _____ garden, because it is near my house; and I will give you a better vineyard”", ["vegetable", "wife", "cheerful", "fast"], 2),
    word(3, "What missing word belongs in this verse 3 clause: “But Naboth said to Ahab, \"The LORD forbid that I should give you the _____ of my fathers.\"”?", "inheritance", 3, ["inheritance"]),
    tf(1, "This wording appears in verse 4: “Jezreelite had said to him; for he had said, \"I will not give you the inheritance of my fathers.\" And he lay down on his bed, and turned away his face,”", true, 4),
    mc(1, "Why did Naboth refuse to give Ahab his vineyard?", ["The LORD forbade him to give away the inheritance of his fathers", "The vineyard had already been promised to Jezebel", "He wanted a larger payment", "The elders of Jezreel owned it"], 3),
    mc(3, "How did Jezebel arrange for Naboth to be killed?", ["She used Ahab’s name and seal to order a fast and false accusations by two base fellows, leading to his stoning", "She sent soldiers to seize the vineyard at night", "She accused him directly before Ahab", "She hired Syrians to attack him"], 10),
    mc(2, "What did Ahab say when Elijah met him in Naboth’s vineyard?", ["Have you found me, O my enemy?", "Is it you, troubler of Israel?", "What have I done to you?", "Go away from my vineyard"], 20),
    mc(2, "What fate did the LORD announce for Jezebel?", ["Dogs would eat her within the bounds of Jezreel", "She would be carried captive to Syria", "She would die in Samaria’s palace", "She would be exiled to Sidon"], 23),
    mc(3, "Why did the LORD postpone disaster on Ahab’s house until his son’s days?", ["Ahab humbled himself, tore his clothes, wore sackcloth, and fasted", "Elijah interceded for him", "Ahab returned Naboth’s vineyard", "Jezebel confessed the false accusation"], 29),
  ],
};

export default bank;
