// 1 Kings 18 — quiz bank (RSV). Four verse-anchored forms per verse.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: "1 Kings",
  chapter: 18,
  tag: "quiz-v2-1kings-18",
  rows: [
    blank(2, "After many days the word of the LORD came to _____, in the third year, saying, \"Go, show yourself to Ahab; and I will send", "Eli’jah", 1, ["elijah"]),
    mc(3, "Which word correctly completes this RSV wording: “After many days the word of the LORD came to _____, in the third year, saying, \"Go, show yourself to Ahab; and I will send”", ["Eli’jah", "Spirit", "Come", "Ahab"], 1),
    word(1, "In verse 1, what word completes this phrase: “After many days the word of the LORD came to _____, in the third year, saying, \"Go, show yourself to Ahab; and I will send”?", "Eli’jah", 1, ["elijah"]),
    tf(2, "The RSV states: “After many days the word of the LORD came to Eli’jah, in the third year, saying, \"Go, show yourself to Ahab; and I will send rain upon the earth.\"”", true, 1),
    blank(3, "So Eli’jah went to show himself to Ahab. Now the famine was severe in _____.", "Sama’ria", 2, ["samaria"]),
    mc(1, "Which word correctly completes this RSV wording: “So Eli’jah went to show himself to Ahab. Now the famine was severe in _____.”", ["Sama’ria", "Ashe’rah", "Kishon", "LORD’S"], 2),
    word(2, "In verse 2, what word completes this phrase: “So Eli’jah went to show himself to Ahab. Now the famine was severe in _____.”?", "Sama’ria", 2, ["samaria"]),
    tf(3, "The RSV does not state: “So Eli’jah went to show himself to Ahab. Now the famine was severe in Sama’ria.”", false, 2, "The quoted wording is the RSV text of this verse."),
    blank(1, "And Ahab called _____, who was over the household. (Now Obadi’ah revered the LORD greatly;", "Obadi’ah", 3, ["obadiah"]),
    mc(2, "Which word correctly completes this RSV wording: “And Ahab called _____, who was over the household. (Now Obadi’ah revered the LORD greatly;”", ["Obadi’ah", "Abraham", "Jez’ebel", "Jez’ebel’s"], 3),
    word(3, "In verse 3, what word completes this phrase: “And Ahab called _____, who was over the household. (Now Obadi’ah revered the LORD greatly;”?", "Obadi’ah", 3, ["obadiah"]),
    tf(1, "The RSV states: “And Ahab called Obadi’ah, who was over the household. (Now Obadi’ah revered the LORD greatly;”", true, 3),
    blank(2, "and when _____ cut off the prophets of the LORD, Obadi’ah took a hundred prophets and", "Jez’ebel", 4, ["jezebel"]),
    mc(3, "Which word correctly completes this RSV wording: “and when _____ cut off the prophets of the LORD, Obadi’ah took a hundred prophets and”", ["Jez’ebel", "After", "Mount", "Isaac"], 4),
    word(1, "In verse 4, what word completes this phrase: “and when _____ cut off the prophets of the LORD, Obadi’ah took a hundred prophets and”?", "Jez’ebel", 4, ["jezebel"]),
    tf(2, "The RSV does not state: “and when Jez’ebel cut off the prophets of the LORD, Obadi’ah took a hundred prophets and hid them by fifties in a cave, and fed them with bread and water.)”", false, 4, "The quoted wording is the RSV text of this verse."),
    blank(3, "And Ahab said to _____, \"Go through the land to all the springs of water and to all the valleys;", "Obadi’ah", 5, ["obadiah"]),
    mc(1, "Which word correctly completes this RSV wording: “And Ahab said to _____, \"Go through the land to all the springs of water and to all the valleys;”", ["Obadi’ah", "Spirit", "Come", "Eli’jah"], 5),
    word(2, "In verse 5, what word completes this phrase: “And Ahab said to _____, \"Go through the land to all the springs of water and to all the valleys;”?", "Obadi’ah", 5, ["obadiah"]),
    tf(3, "The RSV states: “And Ahab said to Obadi’ah, \"Go through the land to all the springs of water and to all the valleys; perhaps we may find grass and save the horses and mules alive, and not lose some of the animals.\"”", true, 5),
    blank(1, "between them to pass through it; Ahab went in one direction by himself, and _____ went in another direction by himself.", "Obadi’ah", 6, ["obadiah"]),
    mc(2, "Which word correctly completes this RSV wording: “between them to pass through it; Ahab went in one direction by himself, and _____ went in another direction by himself.”", ["Obadi’ah", "Ashe’rah", "Kishon", "LORD’S"], 6),
    word(3, "In verse 6, what word completes this phrase: “between them to pass through it; Ahab went in one direction by himself, and _____ went in another direction by himself.”?", "Obadi’ah", 6, ["obadiah"]),
    tf(1, "The RSV does not state: “So they divided the land between them to pass through it; Ahab went in one direction by himself, and Obadi’ah went in another direction by himself.”", false, 6, "The quoted wording is the RSV text of this verse."),
    blank(2, "And as _____ was on the way, behold, Eli’jah met him; and Obadi’ah recognized him,", "Obadi’ah", 7, ["obadiah"]),
    mc(3, "Which word correctly completes this RSV wording: “And as _____ was on the way, behold, Eli’jah met him; and Obadi’ah recognized him,”", ["Obadi’ah", "Abraham", "Jez’ebel", "Jez’ebel’s"], 7),
    word(1, "In verse 7, what word completes this phrase: “And as _____ was on the way, behold, Eli’jah met him; and Obadi’ah recognized him,”?", "Obadi’ah", 7, ["obadiah"]),
    tf(2, "The RSV states: “And as Obadi’ah was on the way, behold, Eli’jah met him; and Obadi’ah recognized him, and fell on his face, and said, \"Is it you, my lord Eli’jah?\"”", true, 7),
    blank(3, "And he answered him, \"It is I. Go, tell your lord, `Behold, _____ is here.’\"", "Eli’jah", 8, ["elijah"]),
    mc(1, "Which word correctly completes this RSV wording: “And he answered him, \"It is I. Go, tell your lord, `Behold, _____ is here.’\"”", ["Eli’jah", "After", "Mount", "Isaac"], 8),
    word(2, "In verse 8, what word completes this phrase: “And he answered him, \"It is I. Go, tell your lord, `Behold, _____ is here.’\"”?", "Eli’jah", 8, ["elijah"]),
    tf(3, "The RSV does not state: “And he answered him, \"It is I. Go, tell your lord, `Behold, Eli’jah is here.’\"”", false, 8, "The quoted wording is the RSV text of this verse."),
    blank(1, "And he said, \"_____ have I sinned, that you would give your servant into the hand of Ahab,", "Wherein", 9, ["wherein"]),
    mc(2, "Which word correctly completes this RSV wording: “And he said, \"_____ have I sinned, that you would give your servant into the hand of Ahab,”", ["Wherein", "Spirit", "Come", "Eli’jah"], 9),
    word(3, "In verse 9, what word completes this phrase: “And he said, \"_____ have I sinned, that you would give your servant into the hand of Ahab,”?", "Wherein", 9, ["wherein"]),
    tf(1, "The RSV states: “And he said, \"Wherein have I sinned, that you would give your servant into the hand of Ahab, to kill me?”", true, 9),
    blank(2, "As the LORD your God lives, there is no nation or _____ whither my lord has not sent to seek you; and when they would say, `He", "kingdom", 10, ["kingdom"]),
    mc(3, "Which word correctly completes this RSV wording: “As the LORD your God lives, there is no nation or _____ whither my lord has not sent to seek you; and when they would say, `He”", ["kingdom", "know", "myself", "therefore"], 10),
    word(1, "In verse 10, what word completes this phrase: “As the LORD your God lives, there is no nation or _____ whither my lord has not sent to seek you; and when they would say, `He”?", "kingdom", 10, ["kingdom"]),
    tf(2, "The RSV does not state: “As the LORD your God lives, there is no nation or kingdom whither my lord has not sent to seek you; and when they would say, `He is not here,’ he would take an oath of the kingdom or nation, that they had not found you.”", false, 10, "The quoted wording is the RSV text of this verse."),
    blank(3, "And now you say, `Go, tell your lord, \"Behold, _____ is here.\"’", "Eli’jah", 11, ["elijah"]),
    mc(1, "Which word correctly completes this RSV wording: “And now you say, `Go, tell your lord, \"Behold, _____ is here.\"’”", ["Eli’jah", "Abraham", "Jez’ebel", "Jez’ebel’s"], 11),
    word(2, "In verse 11, what word completes this phrase: “And now you say, `Go, tell your lord, \"Behold, _____ is here.\"’”?", "Eli’jah", 11, ["elijah"]),
    tf(3, "The RSV states: “And now you say, `Go, tell your lord, \"Behold, Eli’jah is here.\"’”", true, 11),
    blank(1, "And as soon as I have gone from you, the _____ of the LORD will carry you whither I know not; and so, when I come and", "Spirit", 12, ["spirit"]),
    mc(2, "Which word correctly completes this RSV wording: “And as soon as I have gone from you, the _____ of the LORD will carry you whither I know not; and so, when I come and”", ["Spirit", "After", "Mount", "Isaac"], 12),
    word(3, "In verse 12, what word completes this phrase: “And as soon as I have gone from you, the _____ of the LORD will carry you whither I know not; and so, when I come and”?", "Spirit", 12, ["spirit"]),
    tf(1, "The RSV does not state: “And as soon as I have gone from you, the Spirit of the LORD will carry you whither I know not; and so, when I come and tell Ahab and he cannot find you, he will kill me, although I your servant have revered the LORD from my youth.”", false, 12, "The quoted wording is the RSV text of this verse."),
    blank(2, "Has it not been told my lord what I did when _____ killed the prophets of the LORD, how I hid a hundred men of the LORD’S", "Jez’ebel", 13, ["jezebel"]),
    mc(3, "Which word correctly completes this RSV wording: “Has it not been told my lord what I did when _____ killed the prophets of the LORD, how I hid a hundred men of the LORD’S”", ["Jez’ebel", "Spirit", "Come", "Eli’jah"], 13),
    word(1, "In verse 13, what word completes this phrase: “Has it not been told my lord what I did when _____ killed the prophets of the LORD, how I hid a hundred men of the LORD’S”?", "Jez’ebel", 13, ["jezebel"]),
    tf(2, "The RSV states: “Has it not been told my lord what I did when Jez’ebel killed the prophets of the LORD, how I hid a hundred men of the LORD’S prophets by fifties in a cave, and fed them with bread and water?”", true, 13),
    blank(3, "And now you say, `Go, tell your lord, \"Behold, _____ is here\"’; and he will kill me.\"", "Eli’jah", 14, ["elijah"]),
    mc(1, "Which word correctly completes this RSV wording: “And now you say, `Go, tell your lord, \"Behold, _____ is here\"’; and he will kill me.\"”", ["Eli’jah", "Ashe’rah", "Kishon", "LORD’S"], 14),
    word(2, "In verse 14, what word completes this phrase: “And now you say, `Go, tell your lord, \"Behold, _____ is here\"’; and he will kill me.\"”?", "Eli’jah", 14, ["elijah"]),
    tf(3, "The RSV does not state: “And now you say, `Go, tell your lord, \"Behold, Eli’jah is here\"’; and he will kill me.\"”", false, 14, "The quoted wording is the RSV text of this verse."),
    blank(1, "And _____ said, \"As the LORD of hosts lives, before whom I stand, I will surely", "Eli’jah", 15, ["elijah"]),
    mc(2, "Which word correctly completes this RSV wording: “And _____ said, \"As the LORD of hosts lives, before whom I stand, I will surely”", ["Eli’jah", "Abraham", "Jez’ebel", "Jez’ebel’s"], 15),
    word(3, "In verse 15, what word completes this phrase: “And _____ said, \"As the LORD of hosts lives, before whom I stand, I will surely”?", "Eli’jah", 15, ["elijah"]),
    tf(1, "The RSV states: “And Eli’jah said, \"As the LORD of hosts lives, before whom I stand, I will surely show myself to him today.\"”", true, 15),
    blank(2, "So _____ went to meet Ahab, and told him; and Ahab went to meet Eli’jah.", "Obadi’ah", 16, ["obadiah"]),
    mc(3, "Which word correctly completes this RSV wording: “So _____ went to meet Ahab, and told him; and Ahab went to meet Eli’jah.”", ["Obadi’ah", "After", "Mount", "Isaac"], 16),
    word(1, "In verse 16, what word completes this phrase: “So _____ went to meet Ahab, and told him; and Ahab went to meet Eli’jah.”?", "Obadi’ah", 16, ["obadiah"]),
    tf(2, "The RSV does not state: “So Obadi’ah went to meet Ahab, and told him; and Ahab went to meet Eli’jah.”", false, 16, "The quoted wording is the RSV text of this verse."),
    blank(3, "When Ahab saw _____, Ahab said to him, \"Is it you, you troubler of Israel?\"", "Eli’jah", 17, ["elijah"]),
    mc(1, "Which word correctly completes this RSV wording: “When Ahab saw _____, Ahab said to him, \"Is it you, you troubler of Israel?\"”", ["Eli’jah", "Spirit", "Come", "Ahab"], 17),
    word(2, "In verse 17, what word completes this phrase: “When Ahab saw _____, Ahab said to him, \"Is it you, you troubler of Israel?\"”?", "Eli’jah", 17, ["elijah"]),
    tf(3, "The RSV states: “When Ahab saw Eli’jah, Ahab said to him, \"Is it you, you troubler of Israel?\"”", true, 17),
    blank(1, "And he answered, \"I have not troubled _____; but you have, and your father’s house, because you have forsaken the", "Israel", 18, ["israel"]),
    mc(2, "Which word correctly completes this RSV wording: “And he answered, \"I have not troubled _____; but you have, and your father’s house, because you have forsaken the”", ["Israel", "Ashe’rah", "Kishon", "Spirit"], 18),
    word(3, "In verse 18, what word completes this phrase: “And he answered, \"I have not troubled _____; but you have, and your father’s house, because you have forsaken the”?", "Israel", 18, ["israel"]),
    tf(1, "The RSV does not state: “And he answered, \"I have not troubled Israel; but you have, and your father’s house, because you have forsaken the commandments of the LORD and followed the Ba’als.”", false, 18, "The quoted wording is the RSV text of this verse."),
    blank(2, "prophets of Ba’al and the four hundred prophets of Ashe’rah, who eat at _____ table.\"", "Jez’ebel’s", 19, ["jezebels"]),
    mc(3, "Which word correctly completes this RSV wording: “prophets of Ba’al and the four hundred prophets of Ashe’rah, who eat at _____ table.\"”", ["Jez’ebel’s", "LORD’S", "Isaac", "Behold"], 19),
    word(1, "In verse 19, what word completes this phrase: “prophets of Ba’al and the four hundred prophets of Ashe’rah, who eat at _____ table.\"”?", "Jez’ebel’s", 19, ["jezebels"]),
    tf(2, "The RSV states: “Now therefore send and gather all Israel to me at Mount Carmel, and the four hundred and fifty prophets of Ba’al and the four hundred prophets of Ashe’rah, who eat at Jez’ebel’s table.\"”", true, 19),
    blank(3, "So Ahab sent to all the people of _____, and gathered the prophets together at Mount Carmel.", "Israel", 20, ["israel"]),
    mc(1, "Which word correctly completes this RSV wording: “So Ahab sent to all the people of _____, and gathered the prophets together at Mount Carmel.”", ["Israel", "After", "Mount", "Isaac"], 20),
    word(2, "In verse 20, what word completes this phrase: “So Ahab sent to all the people of _____, and gathered the prophets together at Mount Carmel.”?", "Israel", 20, ["israel"]),
    tf(3, "The RSV does not state: “ So Ahab sent to all the people of Israel, and gathered the prophets together at Mount Carmel.”", false, 20, "The quoted wording is the RSV text of this verse."),
    blank(1, "And _____ came near to all the people, and said, \"How long will you go limping with", "Eli’jah", 21, ["elijah"]),
    mc(2, "Which word correctly completes this RSV wording: “And _____ came near to all the people, and said, \"How long will you go limping with”", ["Eli’jah", "Spirit", "Come", "Ahab"], 21),
    word(3, "In verse 21, what word completes this phrase: “And _____ came near to all the people, and said, \"How long will you go limping with”?", "Eli’jah", 21, ["elijah"]),
    tf(1, "The RSV states: “And Eli’jah came near to all the people, and said, \"How long will you go limping with two different opinions? If the LORD is God, follow him; but if Ba’al, then follow him.\" And the people did not answer him a word.”", true, 21),
    blank(2, "Then _____ said to the people, \"I, even I only, am left a prophet of the LORD; but", "Eli’jah", 22, ["elijah"]),
    mc(3, "Which word correctly completes this RSV wording: “Then _____ said to the people, \"I, even I only, am left a prophet of the LORD; but”", ["Eli’jah", "Ashe’rah", "Kishon", "LORD’S"], 22),
    word(1, "In verse 22, what word completes this phrase: “Then _____ said to the people, \"I, even I only, am left a prophet of the LORD; but”?", "Eli’jah", 22, ["elijah"]),
    tf(2, "The RSV does not state: “Then Eli’jah said to the people, \"I, even I only, am left a prophet of the LORD; but Ba’al’s prophets are four hundred and fifty men.”", false, 22, "The quoted wording is the RSV text of this verse."),
    blank(3, "Let two bulls be given to us; and let them choose one bull for _____, and cut it in pieces and lay it on the wood, but put no fire to it; and", "themselves", 23, ["themselves"]),
    mc(1, "Which word correctly completes this RSV wording: “Let two bulls be given to us; and let them choose one bull for _____, and cut it in pieces and lay it on the wood, but put no fire to it; and”", ["themselves", "saying", "hundred", "animals"], 23),
    word(2, "In verse 23, what word completes this phrase: “Let two bulls be given to us; and let them choose one bull for _____, and cut it in pieces and lay it on the wood, but put no fire to it; and”?", "themselves", 23, ["themselves"]),
    tf(3, "The RSV states: “Let two bulls be given to us; and let them choose one bull for themselves, and cut it in pieces and lay it on the wood, but put no fire to it; and I will prepare the other bull and lay it on the wood, and put no fire to it.”", true, 23),
    blank(1, "LORD; and the God who answers by fire, he is God.\" And all the people _____, \"It is well spoken.\"", "answered", 24, ["answered"]),
    mc(2, "Which word correctly completes this RSV wording: “LORD; and the God who answers by fire, he is God.\" And all the people _____, \"It is well spoken.\"”", ["answered", "sons", "pour", "turned"], 24),
    word(3, "In verse 24, what word completes this phrase: “LORD; and the God who answers by fire, he is God.\" And all the people _____, \"It is well spoken.\"”?", "answered", 24, ["answered"]),
    tf(1, "The RSV does not state: “And you call on the name of your god and I will call on the name of the LORD; and the God who answers by fire, he is God.\" And all the people answered, \"It is well spoken.\"”", false, 24, "The quoted wording is the RSV text of this verse."),
    blank(2, "Then _____ said to the prophets of Ba’al, \"Choose for yourselves one bull and prepare", "Eli’jah", 25, ["elijah"]),
    mc(3, "Which word correctly completes this RSV wording: “Then _____ said to the prophets of Ba’al, \"Choose for yourselves one bull and prepare”", ["Eli’jah", "Spirit", "Come", "Ahab"], 25),
    word(1, "In verse 25, what word completes this phrase: “Then _____ said to the prophets of Ba’al, \"Choose for yourselves one bull and prepare”?", "Eli’jah", 25, ["elijah"]),
    tf(2, "The RSV states: “Then Eli’jah said to the prophets of Ba’al, \"Choose for yourselves one bull and prepare it first, for you are many; and call on the name of your god, but put no fire to it.\"”", true, 25),
    blank(3, "which was given them, and they prepared it, and called on the name of _____ from morning until noon, saying, \"O Ba’al, answer us!\" But there was no", "Ba’al", 26, ["baal"]),
    mc(1, "Which word correctly completes this RSV wording: “which was given them, and they prepared it, and called on the name of _____ from morning until noon, saying, \"O Ba’al, answer us!\" But there was no”", ["Ba’al", "Ashe’rah", "Kishon", "Spirit"], 26),
    word(2, "In verse 26, what word completes this phrase: “which was given them, and they prepared it, and called on the name of _____ from morning until noon, saying, \"O Ba’al, answer us!\" But there was no”?", "Ba’al", 26, ["baal"]),
    tf(3, "The RSV does not state: “And they took the bull which was given them, and they prepared it, and called on the name of Ba’al from morning until noon, saying, \"O Ba’al, answer us!\" But there was no voice, and no one answered. And they limped about the altar which they had made.”", false, 26, "The quoted wording is the RSV text of this verse."),
    blank(1, "And at noon _____ mocked them, saying, \"Cry aloud, for he is a god; either he is musing,", "Eli’jah", 27, ["elijah"]),
    mc(2, "Which word correctly completes this RSV wording: “And at noon _____ mocked them, saying, \"Cry aloud, for he is a god; either he is musing,”", ["Eli’jah", "Abraham", "Jez’ebel", "Jez’ebel’s"], 27),
    word(3, "In verse 27, what word completes this phrase: “And at noon _____ mocked them, saying, \"Cry aloud, for he is a god; either he is musing,”?", "Eli’jah", 27, ["elijah"]),
    tf(1, "The RSV states: “And at noon Eli’jah mocked them, saying, \"Cry aloud, for he is a god; either he is musing, or he has gone aside, or he is on a journey, or perhaps he is asleep and must be awakened.\"”", true, 27),
    blank(2, "And they cried aloud, and cut _____ after their custom with swords and lances, until the blood gushed out", "themselves", 28, ["themselves"]),
    mc(3, "Which word correctly completes this RSV wording: “And they cried aloud, and cut _____ after their custom with swords and lances, until the blood gushed out”", ["themselves", "whither", "myself", "gather"], 28),
    word(1, "In verse 28, what word completes this phrase: “And they cried aloud, and cut _____ after their custom with swords and lances, until the blood gushed out”?", "themselves", 28, ["themselves"]),
    tf(2, "The RSV does not state: “And they cried aloud, and cut themselves after their custom with swords and lances, until the blood gushed out upon them.”", false, 28, "The quoted wording is the RSV text of this verse."),
    blank(3, "And as midday passed, they raved on until the time of the _____ of the oblation, but there was no voice; no one answered, no one heeded.", "offering", 29, ["offering"]),
    mc(1, "Which word correctly completes this RSV wording: “And as midday passed, they raved on until the time of the _____ of the oblation, but there was no voice; no one answered, no one heeded.”", ["offering", "rushing", "little", "clouds"], 29),
    word(2, "In verse 29, what word completes this phrase: “And as midday passed, they raved on until the time of the _____ of the oblation, but there was no voice; no one answered, no one heeded.”?", "offering", 29, ["offering"]),
    tf(3, "The RSV states: “And as midday passed, they raved on until the time of the offering of the oblation, but there was no voice; no one answered, no one heeded.”", true, 29),
    blank(1, "Then _____ said to all the people, \"Come near to me\"; and all the people came near", "Eli’jah", 30, ["elijah"]),
    mc(2, "Which word correctly completes this RSV wording: “Then _____ said to all the people, \"Come near to me\"; and all the people came near”", ["Eli’jah", "Ashe’rah", "Kishon", "LORD’S"], 30),
    word(3, "In verse 30, what word completes this phrase: “Then _____ said to all the people, \"Come near to me\"; and all the people came near”?", "Eli’jah", 30, ["elijah"]),
    tf(1, "The RSV does not state: “Then Eli’jah said to all the people, \"Come near to me\"; and all the people came near to him. And he repaired the altar of the LORD that had been thrown down;”", false, 30, "The quoted wording is the RSV text of this verse."),
    blank(2, "_____ took twelve stones, according to the number of the tribes of the sons", "Eli’jah", 31, ["elijah"]),
    mc(3, "Which word correctly completes this RSV wording: “_____ took twelve stones, according to the number of the tribes of the sons”", ["Eli’jah", "Abraham", "Jez’ebel", "Jez’ebel’s"], 31),
    word(1, "In verse 31, what word completes this phrase: “_____ took twelve stones, according to the number of the tribes of the sons”?", "Eli’jah", 31, ["elijah"]),
    tf(2, "The RSV states: “Eli’jah took twelve stones, according to the number of the tribes of the sons of Jacob, to whom the word of the LORD came, saying, \"Israel shall be your name\";”", true, 31),
    blank(3, "LORD. And he made a trench about the altar, as great as would contain two _____ of seed.", "measures", 32, ["measures"]),
    mc(1, "Which word correctly completes this RSV wording: “LORD. And he made a trench about the altar, as great as would contain two _____ of seed.”", ["measures", "black", "third", "severe"], 32),
    word(2, "In verse 32, what word completes this phrase: “LORD. And he made a trench about the altar, as great as would contain two _____ of seed.”?", "measures", 32, ["measures"]),
    tf(3, "The RSV does not state: “and with the stones he built an altar in the name of the LORD. And he made a trench about the altar, as great as would contain two measures of seed.”", false, 32, "The quoted wording is the RSV text of this verse."),
    blank(1, "order, and cut the bull in pieces and laid it on the wood. And he said, \"_____ four jars with water, and pour it on the burnt offering, and on the wood.\"", "Fill", 33, ["fill"]),
    mc(2, "Which word correctly completes this RSV wording: “order, and cut the bull in pieces and laid it on the wood. And he said, \"_____ four jars with water, and pour it on the burnt offering, and on the wood.\"”", ["Fill", "Ashe’rah", "Jezreel", "Israel"], 33),
    word(3, "In verse 33, what word completes this phrase: “order, and cut the bull in pieces and laid it on the wood. And he said, \"_____ four jars with water, and pour it on the burnt offering, and on the wood.\"”?", "Fill", 33, ["fill"]),
    tf(1, "The RSV states: “And he put the wood in order, and cut the bull in pieces and laid it on the wood. And he said, \"Fill four jars with water, and pour it on the burnt offering, and on the wood.\"”", true, 33),
    blank(2, "And he said, \"Do it a _____ time\"; and they did it a second time. And he said, \"Do it a third time\";", "second", 34, ["second"]),
    mc(3, "Which word correctly completes this RSV wording: “And he said, \"Do it a _____ time\"; and they did it a second time. And he said, \"Do it a third time\";”", ["second", "yourself", "revered", "springs"], 34),
    word(1, "In verse 34, what word completes this phrase: “And he said, \"Do it a _____ time\"; and they did it a second time. And he said, \"Do it a third time\";”?", "second", 34, ["second"]),
    tf(2, "The RSV does not state: “And he said, \"Do it a second time\"; and they did it a second time. And he said, \"Do it a third time\"; and they did it a third time.”", false, 34, "The quoted wording is the RSV text of this verse."),
    blank(3, "And the water ran round about the altar, and _____ the trench also with water.", "filled", 35, ["filled"]),
    mc(1, "Which word correctly completes this RSV wording: “And the water ran round about the altar, and _____ the trench also with water.”", ["filled", "severe", "bread", "mules"], 35),
    word(2, "In verse 35, what word completes this phrase: “And the water ran round about the altar, and _____ the trench also with water.”?", "filled", 35, ["filled"]),
    tf(3, "The RSV states: “And the water ran round about the altar, and filled the trench also with water.”", true, 35),
    blank(1, "And at the time of the offering of the oblation, _____ the prophet came near and said, \"O LORD, God of Abraham, Isaac, and Israel,", "Eli’jah", 36, ["elijah"]),
    mc(2, "Which word correctly completes this RSV wording: “And at the time of the offering of the oblation, _____ the prophet came near and said, \"O LORD, God of Abraham, Isaac, and Israel,”", ["Eli’jah", "After", "Mount", "Isaac"], 36),
    word(3, "In verse 36, what word completes this phrase: “And at the time of the offering of the oblation, _____ the prophet came near and said, \"O LORD, God of Abraham, Isaac, and Israel,”?", "Eli’jah", 36, ["elijah"]),
    tf(1, "The RSV does not state: “And at the time of the offering of the oblation, Eli’jah the prophet came near and said, \"O LORD, God of Abraham, Isaac, and Israel, let it be known this day that thou art God in Israel, and that I am thy servant, and that I have done all these things at thy word.”", false, 36, "The quoted wording is the RSV text of this verse."),
    blank(2, "_____ me, O LORD, answer me, that this people may know that thou, O LORD, art", "Answer", 37, ["answer"]),
    mc(3, "Which word correctly completes this RSV wording: “_____ me, O LORD, answer me, that this people may know that thou, O LORD, art”", ["Answer", "Wherein", "Choose", "Eli’jah"], 37),
    word(1, "In verse 37, what word completes this phrase: “_____ me, O LORD, answer me, that this people may know that thou, O LORD, art”?", "Answer", 37, ["answer"]),
    tf(2, "The RSV states: “Answer me, O LORD, answer me, that this people may know that thou, O LORD, art God, and that thou hast turned their hearts back.\"”", true, 37),
    blank(3, "Then the fire of the LORD fell, and _____ the burnt offering, and the wood, and the stones, and the dust, and licked", "consumed", 38, ["consumed"]),
    mc(1, "Which word correctly completes this RSV wording: “Then the fire of the LORD fell, and _____ the burnt offering, and the wood, and the stones, and the dust, and licked”", ["consumed", "save", "another", "hand"], 38),
    word(2, "In verse 38, what word completes this phrase: “Then the fire of the LORD fell, and _____ the burnt offering, and the wood, and the stones, and the dust, and licked”?", "consumed", 38, ["consumed"]),
    tf(3, "The RSV does not state: “Then the fire of the LORD fell, and consumed the burnt offering, and the wood, and the stones, and the dust, and licked up the water that was in the trench.”", false, 38, "The quoted wording is the RSV text of this verse."),
    blank(1, "And when all the _____ saw it, they fell on their faces; and they said, \"The LORD, he is God;", "people", 39, ["people"]),
    mc(2, "Which word correctly completes this RSV wording: “And when all the _____ saw it, they fell on their faces; and they said, \"The LORD, he is God;”", ["people", "between", "sinned", "take"], 39),
    word(3, "In verse 39, what word completes this phrase: “And when all the _____ saw it, they fell on their faces; and they said, \"The LORD, he is God;”?", "people", 39, ["people"]),
    tf(1, "The RSV states: “And when all the people saw it, they fell on their faces; and they said, \"The LORD, he is God; the LORD, he is God.\"”", true, 39),
    blank(2, "And _____ said to them, \"Seize the prophets of Ba’al; let not one of them escape.\"", "Eli’jah", 40, ["elijah"]),
    mc(3, "Which word correctly completes this RSV wording: “And _____ said to them, \"Seize the prophets of Ba’al; let not one of them escape.\"”", ["Eli’jah", "After", "Mount", "Isaac"], 40),
    word(1, "In verse 40, what word completes this phrase: “And _____ said to them, \"Seize the prophets of Ba’al; let not one of them escape.\"”?", "Eli’jah", 40, ["elijah"]),
    tf(2, "The RSV does not state: “And Eli’jah said to them, \"Seize the prophets of Ba’al; let not one of them escape.\" And they seized them; and Eli’jah brought them down to the brook Kishon, and killed them there.”", false, 40, "The quoted wording is the RSV text of this verse."),
    blank(3, "And _____ said to Ahab, \"Go up, eat and drink; for there is a sound of the rushing", "Eli’jah", 41, ["elijah"]),
    mc(1, "Which word correctly completes this RSV wording: “And _____ said to Ahab, \"Go up, eat and drink; for there is a sound of the rushing”", ["Eli’jah", "Spirit", "Come", "Ahab"], 41),
    word(2, "In verse 41, what word completes this phrase: “And _____ said to Ahab, \"Go up, eat and drink; for there is a sound of the rushing”?", "Eli’jah", 41, ["elijah"]),
    tf(3, "The RSV states: “And Eli’jah said to Ahab, \"Go up, eat and drink; for there is a sound of the rushing of rain.\"”", true, 41),
    blank(1, "So Ahab went up to eat and to drink. And _____ went up to the top of Carmel; and he bowed himself down upon the earth,", "Eli’jah", 42, ["elijah"]),
    mc(2, "Which word correctly completes this RSV wording: “So Ahab went up to eat and to drink. And _____ went up to the top of Carmel; and he bowed himself down upon the earth,”", ["Eli’jah", "Ashe’rah", "Kishon", "LORD’S"], 42),
    word(3, "In verse 42, what word completes this phrase: “So Ahab went up to eat and to drink. And _____ went up to the top of Carmel; and he bowed himself down upon the earth,”?", "Eli’jah", 42, ["elijah"]),
    tf(1, "The RSV does not state: “So Ahab went up to eat and to drink. And Eli’jah went up to the top of Carmel; and he bowed himself down upon the earth, and put his face between his knees.”", false, 42, "The quoted wording is the RSV text of this verse."),
    blank(2, "And he said to his _____, \"Go up now, look toward the sea.\" And he went up and looked, and said,", "servant", 43, ["servant"]),
    mc(3, "Which word correctly completes this RSV wording: “And he said to his _____, \"Go up now, look toward the sea.\" And he went up and looked, and said,”", ["servant", "know", "myself", "therefore"], 43),
    word(1, "In verse 43, what word completes this phrase: “And he said to his _____, \"Go up now, look toward the sea.\" And he went up and looked, and said,”?", "servant", 43, ["servant"]),
    tf(2, "The RSV states: “And he said to his servant, \"Go up now, look toward the sea.\" And he went up and looked, and said, \"There is nothing.\" And he said, \"Go again seven times.\"”", true, 43),
    blank(3, "man’s hand is rising out of the sea.\" And he said, \"Go up, say to Ahab, `_____ your chariot and go down, lest the rain stop you.’\"", "Prepare", 44, ["prepare"]),
    mc(1, "Which word correctly completes this RSV wording: “man’s hand is rising out of the sea.\" And he said, \"Go up, say to Ahab, `_____ your chariot and go down, lest the rain stop you.’\"”", ["Prepare", "After", "Ba’als", "Abraham"], 44),
    word(2, "In verse 44, what word completes this phrase: “man’s hand is rising out of the sea.\" And he said, \"Go up, say to Ahab, `_____ your chariot and go down, lest the rain stop you.’\"”?", "Prepare", 44, ["prepare"]),
    tf(3, "The RSV does not state: “And at the seventh time he said, \"Behold, a little cloud like a man’s hand is rising out of the sea.\" And he said, \"Go up, say to Ahab, `Prepare your chariot and go down, lest the rain stop you.’\"”", false, 44, "The quoted wording is the RSV text of this verse."),
    blank(1, "clouds and wind, and there was a great rain. And Ahab rode and went to _____.", "Jezreel", 45, ["jezreel"]),
    mc(2, "Which word correctly completes this RSV wording: “clouds and wind, and there was a great rain. And Ahab rode and went to _____.”", ["Jezreel", "Wherein", "Choose", "Eli’jah"], 45),
    word(3, "In verse 45, what word completes this phrase: “clouds and wind, and there was a great rain. And Ahab rode and went to _____.”?", "Jezreel", 45, ["jezreel"]),
    tf(1, "The RSV states: “And in a little while the heavens grew black with clouds and wind, and there was a great rain. And Ahab rode and went to Jezreel.”", true, 45),
    blank(2, "And the hand of the LORD was on _____; and he girded up his loins and ran before Ahab to the entrance of Jezreel.", "Eli’jah", 46, ["elijah"]),
    mc(3, "Which word correctly completes this RSV wording: “And the hand of the LORD was on _____; and he girded up his loins and ran before Ahab to the entrance of Jezreel.”", ["Eli’jah", "Ashe’rah", "Kishon", "LORD’S"], 46),
    word(1, "In verse 46, what word completes this phrase: “And the hand of the LORD was on _____; and he girded up his loins and ran before Ahab to the entrance of Jezreel.”?", "Eli’jah", 46, ["elijah"]),
    tf(2, "The RSV does not state: “And the hand of the LORD was on Eli’jah; and he girded up his loins and ran before Ahab to the entrance of Jezreel.”", false, 46, "The quoted wording is the RSV text of this verse."),
    mc(2, "How did Obadiah protect one hundred prophets of the LORD from Jezebel?", ["He hid them by fifties in a cave and fed them bread and water", "He sent them to Judah", "He disguised them as servants", "He hid them in Ahab’s palace"], 4),
    mc(2, "Whom did Elijah identify as the true troublers of Israel?", ["Ahab and his father’s house, for forsaking the LORD’s commandments and following the Baals", "Obadiah and the hidden prophets", "The people of Judah", "The prophets at Mount Carmel"], 18),
    mc(3, "How many prophets of Baal and Asherah ate at Jezebel’s table?", ["Four hundred fifty of Baal and four hundred of Asherah", "Four hundred of Baal and fifty of Asherah", "Eight hundred of Baal and fifty of Asherah", "One hundred of each"], 19),
    mc(1, "What choice did Elijah place before the people on Mount Carmel?", ["If the LORD is God, follow Him; but if Baal, follow him", "Choose between Ahab and Obadiah", "Choose whether to return to Egypt", "Choose between Judah and Israel"], 21),
    mc(2, "How much water was poured over Elijah’s sacrifice?", ["Four jars, repeated three times", "Seven jars once", "Twelve jars twice", "Three jars four times"], 34),
    mc(3, "What did the fire of the LORD consume?", ["The burnt offering, wood, stones, dust, and water in the trench", "Only the burnt offering", "The altar and the prophets of Baal", "The sacrifice and the surrounding trees"], 38),
    mc(1, "What did Elijah’s servant see on his seventh look toward the sea?", ["A little cloud like a man’s hand rising from the sea", "A chariot approaching Jezreel", "A wall of fire", "A flock of ravens"], 44),
  ],
};

export default bank;
