// 1 Kings 19 — quiz bank (RSV). Four verse-anchored forms per verse.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: "1 Kings",
  chapter: 19,
  tag: "quiz-v2-1kings-19",
  rows: [
    blank(2, "Ahab told _____ all that Eli’jah had done, and how he had slain all the prophets with", "Jez’ebel", 1, ["jezebel"]),
    mc(3, "Which word correctly completes this RSV wording: “Ahab told _____ all that Eli’jah had done, and how he had slain all the prophets with”", ["Jez’ebel", "Damascus", "Judah", "Ba’al"], 1),
    word(1, "In verse 1, what word completes this phrase: “Ahab told _____ all that Eli’jah had done, and how he had slain all the prophets with”?", "Jez’ebel", 1, ["jezebel"]),
    tf(2, "The RSV states: “Ahab told Jez’ebel all that Eli’jah had done, and how he had slain all the prophets with the sword.”", true, 1),
    blank(3, "Then _____ sent a messenger to Eli’jah, saying, \"So may the gods do to me, and more", "Jez’ebel", 2, ["jezebel"]),
    mc(1, "Which word correctly completes this RSV wording: “Then _____ sent a messenger to Eli’jah, saying, \"So may the gods do to me, and more”", ["Jez’ebel", "Ba’al", "Jehu", "Israel"], 2),
    word(2, "In verse 2, what word completes this phrase: “Then _____ sent a messenger to Eli’jah, saying, \"So may the gods do to me, and more”?", "Jez’ebel", 2, ["jezebel"]),
    tf(3, "The RSV does not state: “Then Jez’ebel sent a messenger to Eli’jah, saying, \"So may the gods do to me, and more also, if I do not make your life as the life of one of them by this time tomorrow.\"”", false, 2, "The quoted wording is the RSV text of this verse."),
    blank(1, "Then he was afraid, and he arose and went for his life, and came to _____, which belongs to Judah, and left his servant there.", "Beer-sheba", 3, ["beer-sheba"]),
    mc(2, "Which word correctly completes this RSV wording: “Then he was afraid, and he arose and went for his life, and came to _____, which belongs to Judah, and left his servant there.”", ["Beer-sheba", "Haz’ael", "Horeb", "Eli’jah"], 3),
    word(3, "In verse 3, what word completes this phrase: “Then he was afraid, and he arose and went for his life, and came to _____, which belongs to Judah, and left his servant there.”?", "Beer-sheba", 3, ["beer-sheba"]),
    tf(1, "The RSV states: “Then he was afraid, and he arose and went for his life, and came to Beer-sheba, which belongs to Judah, and left his servant there.”", true, 3),
    blank(2, "But he himself went a day’s journey into the _____, and came and sat down under a broom tree; and he asked that he might", "wilderness", 4, ["wilderness"]),
    mc(3, "Which word correctly completes this RSV wording: “But he himself went a day’s journey into the _____, and came and sat down under a broom tree; and he asked that he might”", ["wilderness", "drank", "hosts", "mountains"], 4),
    word(1, "In verse 4, what word completes this phrase: “But he himself went a day’s journey into the _____, and came and sat down under a broom tree; and he asked that he might”?", "wilderness", 4, ["wilderness"]),
    tf(2, "The RSV does not state: “But he himself went a day’s journey into the wilderness, and came and sat down under a broom tree; and he asked that he might die, saying, \"It is enough; now, O LORD, take away my life; for I am no better than my fathers.\"”", false, 4, "The quoted wording is the RSV text of this verse."),
    blank(3, "under a broom tree; and behold, an angel touched him, and said to him, \"_____ and eat.\"", "Arise", 5, ["arise"]),
    mc(1, "Which word correctly completes this RSV wording: “under a broom tree; and behold, an angel touched him, and said to him, \"_____ and eat.\"”", ["Arise", "Horeb", "Jez’ebel", "Eli’sha"], 5),
    word(2, "In verse 5, what word completes this phrase: “under a broom tree; and behold, an angel touched him, and said to him, \"_____ and eat.\"”?", "Arise", 5, ["arise"]),
    tf(3, "The RSV states: “And he lay down and slept under a broom tree; and behold, an angel touched him, and said to him, \"Arise and eat.\"”", true, 5),
    blank(1, "And he _____, and behold, there was at his head a cake baked on hot stones and a jar", "looked", 6, ["looked"]),
    mc(2, "Which word correctly completes this RSV wording: “And he _____, and behold, there was at his head a cake baked on hot stones and a jar”", ["looked", "head", "food", "jealous"], 6),
    word(3, "In verse 6, what word completes this phrase: “And he _____, and behold, there was at his head a cake baked on hot stones and a jar”?", "looked", 6, ["looked"]),
    tf(1, "The RSV does not state: “And he looked, and behold, there was at his head a cake baked on hot stones and a jar of water. And he ate and drank, and lay down again.”", false, 6, "The quoted wording is the RSV text of this verse."),
    blank(2, "angel of the LORD came again a second time, and touched him, and said, \"_____ and eat, else the journey will be too great for you.\"", "Arise", 7, ["arise"]),
    mc(3, "Which word correctly completes this RSV wording: “angel of the LORD came again a second time, and touched him, and said, \"_____ and eat, else the journey will be too great for you.\"”", ["Arise", "Judah", "Ahab", "Nimshi"], 7),
    word(1, "In verse 7, what word completes this phrase: “angel of the LORD came again a second time, and touched him, and said, \"_____ and eat, else the journey will be too great for you.\"”?", "Arise", 7, ["arise"]),
    tf(2, "The RSV states: “And the angel of the LORD came again a second time, and touched him, and said, \"Arise and eat, else the journey will be too great for you.\"”", true, 7),
    blank(3, "and went in the strength of that food forty days and forty nights to _____ the mount of God.", "Horeb", 8, ["horeb"]),
    mc(1, "Which word correctly completes this RSV wording: “and went in the strength of that food forty days and forty nights to _____ the mount of God.”", ["Horeb", "Nimshi", "Damascus", "Beer-sheba"], 8),
    word(2, "In verse 8, what word completes this phrase: “and went in the strength of that food forty days and forty nights to _____ the mount of God.”?", "Horeb", 8, ["horeb"]),
    tf(3, "The RSV does not state: “And he arose, and ate and drank, and went in the strength of that food forty days and forty nights to Horeb the mount of God.”", false, 8, "The quoted wording is the RSV text of this verse."),
    blank(1, "of the LORD came to him, and he said to him, \"What are you doing here, _____?\"", "Eli’jah", 9, ["elijah"]),
    mc(2, "Which word correctly completes this RSV wording: “of the LORD came to him, and he said to him, \"What are you doing here, _____?\"”", ["Eli’jah", "Judah", "Ba’al", "Jehu"], 9),
    word(3, "In verse 9, what word completes this phrase: “of the LORD came to him, and he said to him, \"What are you doing here, _____?\"”?", "Eli’jah", 9, ["elijah"]),
    tf(1, "The RSV states: “And there he came to a cave, and lodged there; and behold, the word of the LORD came to him, and he said to him, \"What are you doing here, Eli’jah?\"”", true, 9),
    blank(2, "have been very jealous for the LORD, the God of hosts; for the people of _____ have forsaken thy covenant, thrown down thy altars, and slain thy prophets", "Israel", 10, ["israel"]),
    mc(3, "Which word correctly completes this RSV wording: “have been very jealous for the LORD, the God of hosts; for the people of _____ have forsaken thy covenant, thrown down thy altars, and slain thy prophets”", ["Israel", "Jehu", "Horeb", "Eli’jah"], 10),
    word(1, "In verse 10, what word completes this phrase: “have been very jealous for the LORD, the God of hosts; for the people of _____ have forsaken thy covenant, thrown down thy altars, and slain thy prophets”?", "Israel", 10, ["israel"]),
    tf(2, "The RSV does not state: “He said, \"I have been very jealous for the LORD, the God of hosts; for the people of Israel have forsaken thy covenant, thrown down thy altars, and slain thy prophets with the sword; and I, even I only, am left; and they seek my life, to take it away.\"”", false, 10, "The quoted wording is the RSV text of this verse."),
    blank(3, "before the LORD, but the LORD was not in the wind; and after the wind an _____, but the LORD was not in the earthquake;", "earthquake", 11, ["earthquake"]),
    mc(1, "Which word correctly completes this RSV wording: “before the LORD, but the LORD was not in the wind; and after the wind an _____, but the LORD was not in the earthquake;”", ["earthquake", "mouth", "following", "afraid"], 11),
    word(2, "In verse 11, what word completes this phrase: “before the LORD, but the LORD was not in the wind; and after the wind an _____, but the LORD was not in the earthquake;”?", "earthquake", 11, ["earthquake"]),
    tf(3, "The RSV states: “And he said, \"Go forth, and stand upon the mount before the LORD.\" And behold, the LORD passed by, and a great and strong wind rent the mountains, and broke in pieces the rocks before the LORD, but the LORD was not in the wind; and after the wind an earthquake, but the LORD was not in the earthquake;”", true, 11),
    blank(1, "and after the _____ a fire, but the LORD was not in the fire; and after the fire a still small", "earthquake", 12, ["earthquake"]),
    mc(2, "Which word correctly completes this RSV wording: “and after the _____ a fire, but the LORD was not in the fire; and after the fire a still small”", ["earthquake", "father", "sword", "wilderness"], 12),
    word(3, "In verse 12, what word completes this phrase: “and after the _____ a fire, but the LORD was not in the fire; and after the fire a still small”?", "earthquake", 12, ["earthquake"]),
    tf(1, "The RSV does not state: “and after the earthquake a fire, but the LORD was not in the fire; and after the fire a still small voice.”", false, 12, "The quoted wording is the RSV text of this verse."),
    blank(2, "And when _____ heard it, he wrapped his face in his mantle and went out and stood at", "Eli’jah", 13, ["elijah"]),
    mc(3, "Which word correctly completes this RSV wording: “And when _____ heard it, he wrapped his face in his mantle and went out and stood at”", ["Eli’jah", "Jez’ebel", "Eli’sha", "Haz’ael"], 13),
    word(1, "In verse 13, what word completes this phrase: “And when _____ heard it, he wrapped his face in his mantle and went out and stood at”?", "Eli’jah", 13, ["elijah"]),
    tf(2, "The RSV states: “And when Eli’jah heard it, he wrapped his face in his mantle and went out and stood at the entrance of the cave. And behold, there came a voice to him, and said, \"What are you doing here, Eli’jah?\"”", true, 13),
    word(2, "In verse 14, what word completes this phrase: “have been very jealous for the LORD, the God of hosts; for the people of _____ have forsaken thy covenant, thrown down thy altars, and slain thy prophets”?", "Israel", 14, ["israel"]),
    blank(1, "And the LORD said to him, \"Go, return on your way to the wilderness of _____; and when you arrive, you shall anoint Haz’ael to be king over Syria;", "Damascus", 15, ["damascus"]),
    mc(2, "Which word correctly completes this RSV wording: “And the LORD said to him, \"Go, return on your way to the wilderness of _____; and when you arrive, you shall anoint Haz’ael to be king over Syria;”", ["Damascus", "Ahab", "Nimshi", "Israel"], 15),
    word(3, "In verse 15, what word completes this phrase: “And the LORD said to him, \"Go, return on your way to the wilderness of _____; and when you arrive, you shall anoint Haz’ael to be king over Syria;”?", "Damascus", 15, ["damascus"]),
    tf(1, "The RSV states: “And the LORD said to him, \"Go, return on your way to the wilderness of Damascus; and when you arrive, you shall anoint Haz’ael to be king over Syria;”", true, 15),
    blank(2, "shall anoint to be king over Israel; and Eli’sha the son of Shaphat of _____ you shall anoint to be prophet in your place.", "A’bel-meho’lah", 16, ["abel-meholah"]),
    mc(3, "Which word correctly completes this RSV wording: “shall anoint to be king over Israel; and Eli’sha the son of Shaphat of _____ you shall anoint to be prophet in your place.”", ["A’bel-meho’lah", "Beer-sheba", "Jerusalem", "Israel"], 16),
    word(1, "In verse 16, what word completes this phrase: “shall anoint to be king over Israel; and Eli’sha the son of Shaphat of _____ you shall anoint to be prophet in your place.”?", "A’bel-meho’lah", 16, ["abel-meholah"]),
    tf(2, "The RSV does not state: “and Jehu the son of Nimshi you shall anoint to be king over Israel; and Eli’sha the son of Shaphat of A’bel-meho’lah you shall anoint to be prophet in your place.”", false, 16, "The quoted wording is the RSV text of this verse."),
    blank(3, "And him who escapes from the sword of _____ shall Jehu slay; and him who escapes from the sword of Jehu shall Eli’sha", "Haz’ael", 17, ["hazael"]),
    mc(1, "Which word correctly completes this RSV wording: “And him who escapes from the sword of _____ shall Jehu slay; and him who escapes from the sword of Jehu shall Eli’sha”", ["Haz’ael", "Ba’al", "Jehu", "Horeb"], 17),
    word(2, "In verse 17, what word completes this phrase: “And him who escapes from the sword of _____ shall Jehu slay; and him who escapes from the sword of Jehu shall Eli’sha”?", "Haz’ael", 17, ["hazael"]),
    tf(3, "The RSV states: “And him who escapes from the sword of Haz’ael shall Jehu slay; and him who escapes from the sword of Jehu shall Eli’sha slay.”", true, 17),
    blank(1, "Yet I will leave seven thousand in _____, all the knees that have not bowed to Ba’al, and every mouth that has", "Israel", 18, ["israel"]),
    mc(2, "Which word correctly completes this RSV wording: “Yet I will leave seven thousand in _____, all the knees that have not bowed to Ba’al, and every mouth that has”", ["Israel", "Horeb", "Eli’jah", "Shaphat"], 18),
    word(3, "In verse 18, what word completes this phrase: “Yet I will leave seven thousand in _____, all the knees that have not bowed to Ba’al, and every mouth that has”?", "Israel", 18, ["israel"]),
    tf(1, "The RSV does not state: “Yet I will leave seven thousand in Israel, all the knees that have not bowed to Ba’al, and every mouth that has not kissed him.\"”", false, 18, "The quoted wording is the RSV text of this verse."),
    blank(2, "So he departed from there, and found _____ the son of Shaphat, who was plowing, with twelve yoke of oxen before him,", "Eli’sha", 19, ["elisha"]),
    mc(3, "Which word correctly completes this RSV wording: “So he departed from there, and found _____ the son of Shaphat, who was plowing, with twelve yoke of oxen before him,”", ["Eli’sha", "Shaphat", "Haz’ael", "Arise"], 19),
    word(1, "In verse 19, what word completes this phrase: “So he departed from there, and found _____ the son of Shaphat, who was plowing, with twelve yoke of oxen before him,”?", "Eli’sha", 19, ["elisha"]),
    tf(2, "The RSV states: “ So he departed from there, and found Eli’sha the son of Shaphat, who was plowing, with twelve yoke of oxen before him, and he was with the twelfth. Eli’jah passed by him and cast his mantle upon him.”", true, 19),
    blank(3, "And he left the oxen, and ran after _____, and said, \"Let me kiss my father and my mother, and then I will follow", "Eli’jah", 20, ["elijah"]),
    mc(1, "Which word correctly completes this RSV wording: “And he left the oxen, and ran after _____, and said, \"Let me kiss my father and my mother, and then I will follow”", ["Eli’jah", "Horeb", "Jez’ebel", "Eli’sha"], 20),
    word(2, "In verse 20, what word completes this phrase: “And he left the oxen, and ran after _____, and said, \"Let me kiss my father and my mother, and then I will follow”?", "Eli’jah", 20, ["elijah"]),
    tf(3, "The RSV does not state: “And he left the oxen, and ran after Eli’jah, and said, \"Let me kiss my father and my mother, and then I will follow you.\" And he said to him, \"Go back again; for what have I done to you?\"”", false, 20, "The quoted wording is the RSV text of this verse."),
    blank(1, "and gave it to the people, and they ate. Then he arose and went after _____, and ministered to him.", "Eli’jah", 21, ["elijah"]),
    mc(2, "Which word correctly completes this RSV wording: “and gave it to the people, and they ate. Then he arose and went after _____, and ministered to him.”", ["Eli’jah", "Eli’sha", "Haz’ael", "Arise"], 21),
    word(3, "In verse 21, what word completes this phrase: “and gave it to the people, and they ate. Then he arose and went after _____, and ministered to him.”?", "Eli’jah", 21, ["elijah"]),
    tf(1, "The RSV states: “And he returned from following him, and took the yoke of oxen, and slew them, and boiled their flesh with the yokes of the oxen, and gave it to the people, and they ate. Then he arose and went after Eli’jah, and ministered to him.”", true, 21),
    blank(1, "told Jez’ebel all that Eli’jah had done, and how he had slain all the _____ with the sword.", "prophets", 1, ["prophets"]),
    mc(2, "Select the missing RSV word: “Then Jez’ebel sent a _____ to Eli’jah, saying, \"So may the gods do to me, and more also, if I do”", ["messenger", "tree", "touched", "else"], 2),
    word(3, "What missing word belongs in this verse 3 clause: “afraid, and he arose and went for his life, and came to Beer-sheba, which _____ to Judah, and left his servant there.”?", "belongs", 3, ["belongs"]),
    tf(1, "This wording appears in verse 4: “But he himself went a day’s journey into the wilderness, and came and sat down under”", true, 4),
    blank(2, "And he lay down and slept under a broom tree; and behold, an angel _____ him, and said to him, \"Arise and eat.\"", "touched", 5, ["touched"]),
    mc(3, "Select the missing RSV word: “And he looked, and _____, there was at his head a cake baked on hot stones and a jar of water.”", ["behold", "rocks", "stood", "slay"], 6),
    word(1, "What missing word belongs in this verse 7 clause: “And the angel of the LORD came again a second time, and _____ him, and said, \"Arise and eat, else the journey will be too great for”?", "touched", 7, ["touched"]),
    tf(2, "This wording appears in verse 8: “And he arose, and ate and drank, and went in the strength of that food forty days and forty nights to Horeb the mount of God.”", true, 8),
    blank(3, "And there he came to a cave, and _____ there; and behold, the word of the LORD came to him, and he said to him,", "lodged", 9, ["lodged"]),
    mc(1, "Select the missing RSV word: “jealous for the LORD, the God of hosts; for the people of Israel have _____ thy covenant, thrown down thy altars, and slain thy prophets with the”", ["forsaken", "prophets", "tomorrow", "wilderness"], 10),
    word(2, "What missing word belongs in this verse 11 clause: “And behold, the LORD passed by, and a great and strong wind rent the _____, and broke in pieces the rocks before the LORD, but the LORD was not in”?", "mountains", 11, ["mountains"]),
    tf(3, "This wording appears in verse 12: “and after the earthquake a fire, but the LORD was not in the fire; and after the”", true, 12),
    blank(1, "heard it, he wrapped his face in his mantle and went out and stood at the _____ of the cave. And behold, there came a voice to him, and said, \"What are", "entrance", 13, ["entrance"]),
    word(3, "What missing word belongs in this verse 15 clause: “And the LORD said to him, \"Go, return on your way to the _____ of Damascus; and when you arrive, you shall anoint Haz’ael to be king”?", "wilderness", 15, ["wilderness"]),
    tf(1, "This wording appears in verse 16: “and Jehu the son of Nimshi you shall anoint to be king over Israel; and Eli’sha the son of Shaphat of A’bel-meho’lah you shall anoint to be prophet in”", true, 16),
    blank(2, "And him who _____ from the sword of Haz’ael shall Jehu slay; and him who escapes from the", "escapes", 17, ["escapes"]),
    mc(3, "Select the missing RSV word: “Yet I will leave seven _____ in Israel, all the knees that have not bowed to Ba’al, and every mouth”", ["thousand", "departed", "follow", "told"], 18),
    word(1, "What missing word belongs in this verse 19 clause: “So he _____ from there, and found Eli’sha the son of Shaphat, who was plowing, with”?", "departed", 19, ["departed"]),
    tf(2, "This wording appears in verse 20: “And he left the oxen, and ran after Eli’jah, and said, \"Let me kiss my father and my mother, and then I will follow you.\" And he said to him, \"Go back”", true, 20),
    blank(3, "to the people, and they ate. Then he arose and went after Eli’jah, and _____ to him.", "ministered", 21, ["ministered"]),
    mc(1, "Select the missing RSV word: “told Jez’ebel all that Eli’jah had done, and how he had slain all the _____ with the sword.”", ["prophets", "wilderness", "fathers", "water"], 1),
    word(2, "What missing word belongs in this verse 2 clause: “Then Jez’ebel sent a _____ to Eli’jah, saying, \"So may the gods do to me, and more also, if I do”?", "messenger", 2, ["messenger"]),
    tf(3, "This wording appears in verse 3: “afraid, and he arose and went for his life, and came to Beer-sheba, which belongs to Judah, and left his servant there.”", true, 3),
    blank(1, "But he _____ went a day’s journey into the wilderness, and came and sat down under", "himself", 4, ["himself"]),
    mc(2, "Select the missing RSV word: “And he lay down and slept under a broom tree; and behold, an angel _____ him, and said to him, \"Arise and eat.\"”", ["touched", "rent", "heard", "over"], 5),
    word(3, "What missing word belongs in this verse 6 clause: “And he looked, and _____, there was at his head a cake baked on hot stones and a jar of water.”?", "behold", 6, ["behold"]),
    tf(1, "This wording appears in verse 7: “And the angel of the LORD came again a second time, and touched him, and said, \"Arise and eat, else the journey will be too great for”", true, 7),
    blank(2, "And he arose, and ate and drank, and went in the _____ of that food forty days and forty nights to Horeb the mount of God.", "strength", 8, ["strength"]),
    mc(3, "Select the missing RSV word: “And there he came to a cave, and _____ there; and behold, the word of the LORD came to him, and he said to him,”", ["lodged", "ministered", "also", "servant"], 9),
    word(1, "What missing word belongs in this verse 10 clause: “jealous for the LORD, the God of hosts; for the people of Israel have _____ thy covenant, thrown down thy altars, and slain thy prophets with the”?", "forsaken", 10, ["forsaken"]),
    tf(2, "This wording appears in verse 11: “And behold, the LORD passed by, and a great and strong wind rent the mountains, and broke in pieces the rocks before the LORD, but the LORD was not in”", true, 11),
    blank(3, "and _____ the earthquake a fire, but the LORD was not in the fire; and after the", "after", 12, ["after"]),
    mc(1, "Select the missing RSV word: “heard it, he wrapped his face in his mantle and went out and stood at the _____ of the cave. And behold, there came a voice to him, and said, \"What are”", ["entrance", "forty", "hosts", "before"], 13),
    word(2, "What missing word belongs in this verse 14 clause: “jealous for the LORD, the God of hosts; for the people of Israel have _____ thy covenant, thrown down thy altars, and slain thy prophets with the”?", "forsaken", 14, ["forsaken"]),
    tf(3, "This wording appears in verse 15: “And the LORD said to him, \"Go, return on your way to the wilderness of Damascus; and when you arrive, you shall anoint Haz’ael to be king”", true, 15),
    mc(1, "Whose threat caused Elijah to flee for his life?", ["Jezebel’s", "Ahab’s", "Obadiah’s", "Ben-hadad’s"], 2),
    mc(2, "What did Elijah pray beneath the broom tree?", ["That the LORD would take away his life because he was no better than his fathers", "That fire would fall from heaven", "That rain would cease again", "That he would become king over Israel"], 4),
    mc(3, "What food did the angel provide, and how far did its strength carry Elijah?", ["A cake baked on hot stones and a jar of water; forty days and nights to Horeb", "Bread and meat from ravens; seven days to Carmel", "Meal and oil; three days to Jerusalem", "Manna and water; forty years in the wilderness"], 8),
    mc(1, "After the wind, earthquake, and fire, how did the LORD’s presence come to Elijah?", ["In a still small voice", "In thunder", "In a pillar of cloud", "In a second earthquake"], 12),
    mc(3, "Which three appointments was Elijah commanded to make?", ["Hazael over Syria, Jehu over Israel, and Elisha as prophet in his place", "Jehu over Syria, Hazael over Israel, and Elisha over Judah", "Elisha over Syria, Jehu as prophet, and Hazael over Israel", "Ahab over Israel, Obadiah over Judah, and Elisha as priest"], 16),
    mc(2, "How many in Israel had not bowed to Baal?", ["Seven thousand", "Seven hundred", "Twelve thousand", "One hundred"], 18),
    mc(2, "What was Elisha doing when Elijah cast his mantle upon him?", ["Plowing with twelve yoke of oxen, while he was with the twelfth", "Watching sheep near Horeb", "Drawing water at Beersheba", "Serving Ahab in Samaria"], 19),
  ],
};

export default bank;
