// 1 Kings 16 — quiz bank (RSV). Four verse-anchored forms per verse.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: "1 Kings",
  chapter: 16,
  tag: "quiz-v2-1kings-16",
  rows: [
    blank(2, "And the word of the LORD came to Jehu the son of _____ against Ba’asha, saying,", "Hana’ni", 1, ["hanani"]),
    mc(3, "Which word correctly completes this RSV wording: “And the word of the LORD came to Jehu the son of _____ against Ba’asha, saying,”", ["Hana’ni", "Chronicles", "Omri", "Hi’el"], 1),
    word(1, "In verse 1, what word completes this phrase: “And the word of the LORD came to Jehu the son of _____ against Ba’asha, saying,”?", "Hana’ni", 1, ["hanani"]),
    tf(2, "The RSV states: “And the word of the LORD came to Jehu the son of Hana’ni against Ba’asha, saying,”", true, 1),
    blank(3, "made you leader over my people Israel, and you have walked in the way of _____, and have made my people Israel to sin, provoking me to anger with their", "Jerobo’am", 2, ["jeroboam"]),
    mc(1, "Which word correctly completes this RSV wording: “made you leader over my people Israel, and you have walked in the way of _____, and have made my people Israel to sin, provoking me to anger with their”", ["Jerobo’am", "Arza", "Ethba’al", "Hana’ni"], 2),
    word(2, "In verse 2, what word completes this phrase: “made you leader over my people Israel, and you have walked in the way of _____, and have made my people Israel to sin, provoking me to anger with their”?", "Jerobo’am", 2, ["jeroboam"]),
    tf(3, "The RSV does not state: “\"Since I exalted you out of the dust and made you leader over my people Israel, and you have walked in the way of Jerobo’am, and have made my people Israel to sin, provoking me to anger with their sins,”", false, 2, "The quoted wording is the RSV text of this verse."),
    blank(1, "away Ba’asha and his house, and I will make your house like the house of _____ the son of Nebat.", "Jerobo’am", 3, ["jeroboam"]),
    mc(2, "Which word correctly completes this RSV wording: “away Ba’asha and his house, and I will make your house like the house of _____ the son of Nebat.”", ["Jerobo’am", "Sama’ria", "Abi’ram", "Kings"], 3),
    word(3, "In verse 3, what word completes this phrase: “away Ba’asha and his house, and I will make your house like the house of _____ the son of Nebat.”?", "Jerobo’am", 3, ["jeroboam"]),
    tf(1, "The RSV states: “behold, I will utterly sweep away Ba’asha and his house, and I will make your house like the house of Jerobo’am the son of Nebat.”", true, 3),
    blank(2, "Any one belonging to _____ who dies in the city the dogs shall eat; and any one of his who dies in", "Ba’asha", 4, ["baasha"]),
    mc(3, "Which word correctly completes this RSV wording: “Any one belonging to _____ who dies in the city the dogs shall eat; and any one of his who dies in”", ["Ba’asha", "Ashe’rah", "Jerobo’am", "Thus"], 4),
    word(1, "In verse 4, what word completes this phrase: “Any one belonging to _____ who dies in the city the dogs shall eat; and any one of his who dies in”?", "Ba’asha", 4, ["baasha"]),
    tf(2, "The RSV does not state: “Any one belonging to Ba’asha who dies in the city the dogs shall eat; and any one of his who dies in the field the birds of the air shall eat.\"”", false, 4, "The quoted wording is the RSV text of this verse."),
    blank(3, "and what he did, and his might, are they not written in the Book of the _____ of the Kings of Israel?", "Chronicles", 5, ["chronicles"]),
    mc(1, "Which word correctly completes this RSV wording: “and what he did, and his might, are they not written in the Book of the _____ of the Kings of Israel?”", ["Chronicles", "Tirzah", "Ethba’al", "Ba’asha"], 5),
    word(2, "In verse 5, what word completes this phrase: “and what he did, and his might, are they not written in the Book of the _____ of the Kings of Israel?”?", "Chronicles", 5, ["chronicles"]),
    tf(3, "The RSV states: “Now the rest of the acts of Ba’asha, and what he did, and his might, are they not written in the Book of the Chronicles of the Kings of Israel?”", true, 5),
    blank(1, "And _____ slept with his fathers, and was buried at Tirzah; and Elah his son reigned", "Ba’asha", 6, ["baasha"]),
    mc(2, "Which word correctly completes this RSV wording: “And _____ slept with his fathers, and was buried at Tirzah; and Elah his son reigned”", ["Ba’asha", "Chronicles", "Omri", "Hi’el"], 6),
    word(3, "In verse 6, what word completes this phrase: “And _____ slept with his fathers, and was buried at Tirzah; and Elah his son reigned”?", "Ba’asha", 6, ["baasha"]),
    tf(1, "The RSV does not state: “And Ba’asha slept with his fathers, and was buried at Tirzah; and Elah his son reigned in his stead.”", false, 6, "The quoted wording is the RSV text of this verse."),
    blank(2, "provoking him to anger with the work of his hands, in being like the house of _____, and also because he destroyed it.", "Jerobo’am", 7, ["jeroboam"]),
    mc(3, "Which word correctly completes this RSV wording: “provoking him to anger with the work of his hands, in being like the house of _____, and also because he destroyed it.”", ["Jerobo’am", "Arza", "Ethba’al", "Hana’ni"], 7),
    word(1, "In verse 7, what word completes this phrase: “provoking him to anger with the work of his hands, in being like the house of _____, and also because he destroyed it.”?", "Jerobo’am", 7, ["jeroboam"]),
    tf(2, "The RSV states: “Moreover the word of the LORD came by the prophet Jehu the son of Hana’ni against Ba’asha and his house, both because of all the evil that he did in the sight of the LORD, provoking him to anger with the work of his hands, in being like the house of Jerobo’am, and also because he destroyed it.”", true, 7),
    blank(3, "In the twenty-sixth year of Asa king of Judah, Elah the son of _____ began to reign over Israel in Tirzah, and reigned two years.", "Ba’asha", 8, ["baasha"]),
    mc(1, "Which word correctly completes this RSV wording: “In the twenty-sixth year of Asa king of Judah, Elah the son of _____ began to reign over Israel in Tirzah, and reigned two years.”", ["Ba’asha", "Sama’ria", "Abi’ram", "Kings"], 8),
    word(2, "In verse 8, what word completes this phrase: “In the twenty-sixth year of Asa king of Judah, Elah the son of _____ began to reign over Israel in Tirzah, and reigned two years.”?", "Ba’asha", 8, ["baasha"]),
    tf(3, "The RSV does not state: “In the twenty-sixth year of Asa king of Judah, Elah the son of Ba’asha began to reign over Israel in Tirzah, and reigned two years.”", false, 8, "The quoted wording is the RSV text of this verse."),
    blank(1, "commander of half his chariots, conspired against him. When he was at _____, drinking himself drunk in the house of Arza, who was over the household", "Tirzah", 9, ["tirzah"]),
    mc(2, "Which word correctly completes this RSV wording: “commander of half his chariots, conspired against him. When he was at _____, drinking himself drunk in the house of Arza, who was over the household”", ["Tirzah", "Ashe’rah", "Israel", "Thus"], 9),
    word(3, "In verse 9, what word completes this phrase: “commander of half his chariots, conspired against him. When he was at _____, drinking himself drunk in the house of Arza, who was over the household”?", "Tirzah", 9, ["tirzah"]),
    tf(1, "The RSV states: “But his servant Zimri, commander of half his chariots, conspired against him. When he was at Tirzah, drinking himself drunk in the house of Arza, who was over the household in Tirzah,”", true, 9),
    blank(2, "_____ came in and struck him down and killed him, in the twenty-seventh year", "Zimri", 10, ["zimri"]),
    mc(3, "Which word correctly completes this RSV wording: “_____ came in and struck him down and killed him, in the twenty-seventh year”", ["Zimri", "Ba’asha", "Judah", "Ethba’al"], 10),
    word(1, "In verse 10, what word completes this phrase: “_____ came in and struck him down and killed him, in the twenty-seventh year”?", "Zimri", 10, ["zimri"]),
    tf(2, "The RSV does not state: “Zimri came in and struck him down and killed him, in the twenty-seventh year of Asa king of Judah, and reigned in his stead.”", false, 10, "The quoted wording is the RSV text of this verse."),
    blank(3, "soon as he had seated himself on his throne, he killed all the house of _____; he did not leave him a single male of his kinsmen or his friends.", "Ba’asha", 11, ["baasha"]),
    mc(1, "Which word correctly completes this RSV wording: “soon as he had seated himself on his throne, he killed all the house of _____; he did not leave him a single male of his kinsmen or his friends.”", ["Ba’asha", "Chronicles", "Omri", "Hi’el"], 11),
    word(2, "In verse 11, what word completes this phrase: “soon as he had seated himself on his throne, he killed all the house of _____; he did not leave him a single male of his kinsmen or his friends.”?", "Ba’asha", 11, ["baasha"]),
    tf(3, "The RSV states: “When he began to reign, as soon as he had seated himself on his throne, he killed all the house of Ba’asha; he did not leave him a single male of his kinsmen or his friends.”", true, 11),
    blank(1, "Thus Zimri destroyed all the house of _____, according to the word of the LORD, which he spoke against Ba’asha by", "Ba’asha", 12, ["baasha"]),
    mc(2, "Which word correctly completes this RSV wording: “Thus Zimri destroyed all the house of _____, according to the word of the LORD, which he spoke against Ba’asha by”", ["Ba’asha", "Arza", "Ethba’al", "Hana’ni"], 12),
    word(3, "In verse 12, what word completes this phrase: “Thus Zimri destroyed all the house of _____, according to the word of the LORD, which he spoke against Ba’asha by”?", "Ba’asha", 12, ["baasha"]),
    tf(1, "The RSV does not state: “Thus Zimri destroyed all the house of Ba’asha, according to the word of the LORD, which he spoke against Ba’asha by Jehu the prophet,”", false, 12, "The quoted wording is the RSV text of this verse."),
    blank(2, "for all the sins of _____ and the sins of Elah his son which they sinned, and which they made Israel", "Ba’asha", 13, ["baasha"]),
    mc(3, "Which word correctly completes this RSV wording: “for all the sins of _____ and the sins of Elah his son which they sinned, and which they made Israel”", ["Ba’asha", "Sama’ria", "Abi’ram", "Kings"], 13),
    word(1, "In verse 13, what word completes this phrase: “for all the sins of _____ and the sins of Elah his son which they sinned, and which they made Israel”?", "Ba’asha", 13, ["baasha"]),
    tf(2, "The RSV states: “for all the sins of Ba’asha and the sins of Elah his son which they sinned, and which they made Israel to sin, provoking the LORD God of Israel to anger with their idols.”", true, 13),
    blank(3, "of Elah, and all that he did, are they not written in the Book of the _____ of the Kings of Israel?", "Chronicles", 14, ["chronicles"]),
    mc(1, "Which word correctly completes this RSV wording: “of Elah, and all that he did, are they not written in the Book of the _____ of the Kings of Israel?”", ["Chronicles", "Ginath", "Abi’ram", "Moreover"], 14),
    word(2, "In verse 14, what word completes this phrase: “of Elah, and all that he did, are they not written in the Book of the _____ of the Kings of Israel?”?", "Chronicles", 14, ["chronicles"]),
    tf(3, "The RSV does not state: “Now the rest of the acts of Elah, and all that he did, are they not written in the Book of the Chronicles of the Kings of Israel?”", false, 14, "The quoted wording is the RSV text of this verse."),
    blank(1, "Now the troops were encamped against Gib’bethon, which belonged to the _____,", "Philistines", 15, ["philistines"]),
    mc(2, "Which word correctly completes this RSV wording: “Now the troops were encamped against Gib’bethon, which belonged to the _____,”", ["Philistines", "Shemer", "Israel", "Sido’nians"], 15),
    word(3, "In verse 15, what word completes this phrase: “Now the troops were encamped against Gib’bethon, which belonged to the _____,”?", "Philistines", 15, ["philistines"]),
    tf(1, "The RSV states: “In the twenty-seventh year of Asa king of Judah, Zimri reigned seven days in Tirzah. Now the troops were encamped against Gib’bethon, which belonged to the Philistines,”", true, 15),
    blank(2, "said, \"Zimri has conspired, and he has killed the king\"; therefore all _____ made Omri, the commander of the army, king over Israel that day in the", "Israel", 16, ["israel"]),
    mc(3, "Which word correctly completes this RSV wording: “said, \"Zimri has conspired, and he has killed the king\"; therefore all _____ made Omri, the commander of the army, king over Israel that day in the”", ["Israel", "Chronicles", "Omri", "Hi’el"], 16),
    word(1, "In verse 16, what word completes this phrase: “said, \"Zimri has conspired, and he has killed the king\"; therefore all _____ made Omri, the commander of the army, king over Israel that day in the”?", "Israel", 16, ["israel"]),
    tf(2, "The RSV does not state: “and the troops who were encamped heard it said, \"Zimri has conspired, and he has killed the king\"; therefore all Israel made Omri, the commander of the army, king over Israel that day in the camp.”", false, 16, "The quoted wording is the RSV text of this verse."),
    blank(3, "So Omri went up from _____, and all Israel with him, and they besieged Tirzah.", "Gib’bethon", 17, ["gibbethon"]),
    mc(1, "Which word correctly completes this RSV wording: “So Omri went up from _____, and all Israel with him, and they besieged Tirzah.”", ["Gib’bethon", "Kings", "Ethba’al", "Ba’asha"], 17),
    word(2, "In verse 17, what word completes this phrase: “So Omri went up from _____, and all Israel with him, and they besieged Tirzah.”?", "Gib’bethon", 17, ["gibbethon"]),
    tf(3, "The RSV states: “So Omri went up from Gib’bethon, and all Israel with him, and they besieged Tirzah.”", true, 17),
    blank(1, "And when _____ saw that the city was taken, he went into the citadel of the king’s house,", "Zimri", 18, ["zimri"]),
    mc(2, "Which word correctly completes this RSV wording: “And when _____ saw that the city was taken, he went into the citadel of the king’s house,”", ["Zimri", "Ethba’al", "Hana’ni", "Moreover"], 18),
    word(3, "In verse 18, what word completes this phrase: “And when _____ saw that the city was taken, he went into the citadel of the king’s house,”?", "Zimri", 18, ["zimri"]),
    tf(1, "The RSV does not state: “And when Zimri saw that the city was taken, he went into the citadel of the king’s house, and burned the king’s house over him with fire, and died,”", false, 18, "The quoted wording is the RSV text of this verse."),
    blank(2, "committed, doing evil in the sight of the LORD, walking in the way of _____, and for his sin which he committed, making Israel to sin.", "Jerobo’am", 19, ["jeroboam"]),
    mc(3, "Which word correctly completes this RSV wording: “committed, doing evil in the sight of the LORD, walking in the way of _____, and for his sin which he committed, making Israel to sin.”", ["Jerobo’am", "Ashe’rah", "Israel", "Thus"], 19),
    word(1, "In verse 19, what word completes this phrase: “committed, doing evil in the sight of the LORD, walking in the way of _____, and for his sin which he committed, making Israel to sin.”?", "Jerobo’am", 19, ["jeroboam"]),
    tf(2, "The RSV states: “because of his sins which he committed, doing evil in the sight of the LORD, walking in the way of Jerobo’am, and for his sin which he committed, making Israel to sin.”", true, 19),
    blank(3, "the conspiracy which he made, are they not written in the Book of the _____ of the Kings of Israel?", "Chronicles", 20, ["chronicles"]),
    mc(1, "Which word correctly completes this RSV wording: “the conspiracy which he made, are they not written in the Book of the _____ of the Kings of Israel?”", ["Chronicles", "Hana’ni", "Gib’bethon", "Hi’el"], 20),
    word(2, "In verse 20, what word completes this phrase: “the conspiracy which he made, are they not written in the Book of the _____ of the Kings of Israel?”?", "Chronicles", 20, ["chronicles"]),
    tf(3, "The RSV does not state: “Now the rest of the acts of Zimri, and the conspiracy which he made, are they not written in the Book of the Chronicles of the Kings of Israel?”", false, 20, "The quoted wording is the RSV text of this verse."),
    blank(1, "Then the people of _____ were divided into two parts; half of the people followed Tibni the son", "Israel", 21, ["israel"]),
    mc(2, "Which word correctly completes this RSV wording: “Then the people of _____ were divided into two parts; half of the people followed Tibni the son”", ["Israel", "Chronicles", "Omri", "Hi’el"], 21),
    word(3, "In verse 21, what word completes this phrase: “Then the people of _____ were divided into two parts; half of the people followed Tibni the son”?", "Israel", 21, ["israel"]),
    tf(1, "The RSV states: “Then the people of Israel were divided into two parts; half of the people followed Tibni the son of Ginath, to make him king, and half followed Omri.”", true, 21),
    blank(2, "people who followed Omri overcame the people who followed Tibni the son of _____; so Tibni died, and Omri became king.", "Ginath", 22, ["ginath"]),
    mc(3, "Which word correctly completes this RSV wording: “people who followed Omri overcame the people who followed Tibni the son of _____; so Tibni died, and Omri became king.”", ["Ginath", "Zimri", "Ethba’al", "Hana’ni"], 22),
    word(1, "In verse 22, what word completes this phrase: “people who followed Omri overcame the people who followed Tibni the son of _____; so Tibni died, and Omri became king.”?", "Ginath", 22, ["ginath"]),
    tf(2, "The RSV does not state: “But the people who followed Omri overcame the people who followed Tibni the son of Ginath; so Tibni died, and Omri became king.”", false, 22, "The quoted wording is the RSV text of this verse."),
    blank(3, "the thirty-first year of Asa king of Judah, Omri began to reign over _____, and reigned for twelve years; six years he reigned in Tirzah.", "Israel", 23, ["israel"]),
    mc(1, "Which word correctly completes this RSV wording: “the thirty-first year of Asa king of Judah, Omri began to reign over _____, and reigned for twelve years; six years he reigned in Tirzah.”", ["Israel", "Sama’ria", "Abi’ram", "Kings"], 23),
    word(2, "In verse 23, what word completes this phrase: “the thirty-first year of Asa king of Judah, Omri began to reign over _____, and reigned for twelve years; six years he reigned in Tirzah.”?", "Israel", 23, ["israel"]),
    tf(3, "The RSV states: “In the thirty-first year of Asa king of Judah, Omri began to reign over Israel, and reigned for twelve years; six years he reigned in Tirzah.”", true, 23),
    blank(1, "He bought the hill of _____ from Shemer for two talents of silver; and he fortified the hill, and", "Sama’ria", 24, ["samaria"]),
    mc(2, "Which word correctly completes this RSV wording: “He bought the hill of _____ from Shemer for two talents of silver; and he fortified the hill, and”", ["Sama’ria", "Ashe’rah", "Israel", "Arza"], 24),
    word(3, "In verse 24, what word completes this phrase: “He bought the hill of _____ from Shemer for two talents of silver; and he fortified the hill, and”?", "Sama’ria", 24, ["samaria"]),
    tf(1, "The RSV does not state: “He bought the hill of Sama’ria from Shemer for two talents of silver; and he fortified the hill, and called the name of the city which he built, Sama’ria, after the name of Shemer, the owner of the hill.”", false, 24, "The quoted wording is the RSV text of this verse."),
    blank(2, "_____ did what was evil in the sight of the LORD, and did more evil than all", "Omri", 25, ["omri"]),
    mc(3, "Which word correctly completes this RSV wording: “_____ did what was evil in the sight of the LORD, and did more evil than all”", ["Omri", "Ahab", "Jehu", "Moreover"], 25),
    word(1, "In verse 25, what word completes this phrase: “_____ did what was evil in the sight of the LORD, and did more evil than all”?", "Omri", 25, ["omri"]),
    tf(2, "The RSV states: “Omri did what was evil in the sight of the LORD, and did more evil than all who were before him.”", true, 25),
    blank(3, "For he walked in all the way of _____ the son of Nebat, and in the sins which he made Israel to sin, provoking", "Jerobo’am", 26, ["jeroboam"]),
    mc(1, "Which word correctly completes this RSV wording: “For he walked in all the way of _____ the son of Nebat, and in the sins which he made Israel to sin, provoking”", ["Jerobo’am", "Chronicles", "Omri", "Hi’el"], 26),
    word(2, "In verse 26, what word completes this phrase: “For he walked in all the way of _____ the son of Nebat, and in the sins which he made Israel to sin, provoking”?", "Jerobo’am", 26, ["jeroboam"]),
    tf(3, "The RSV does not state: “For he walked in all the way of Jerobo’am the son of Nebat, and in the sins which he made Israel to sin, provoking the LORD, the God of Israel, to anger by their idols.”", false, 26, "The quoted wording is the RSV text of this verse."),
    blank(1, "and the might that he showed, are they not written in the Book of the _____ of the Kings of Israel?", "Chronicles", 27, ["chronicles"]),
    mc(2, "Which word correctly completes this RSV wording: “and the might that he showed, are they not written in the Book of the _____ of the Kings of Israel?”", ["Chronicles", "Ashe’rah", "Jerobo’am", "Sama’ria"], 27),
    word(3, "In verse 27, what word completes this phrase: “and the might that he showed, are they not written in the Book of the _____ of the Kings of Israel?”?", "Chronicles", 27, ["chronicles"]),
    tf(1, "The RSV states: “Now the rest of the acts of Omri which he did, and the might that he showed, are they not written in the Book of the Chronicles of the Kings of Israel?”", true, 27),
    blank(2, "And Omri slept with his fathers, and was buried in _____; and Ahab his son reigned in his stead.", "Sama’ria", 28, ["samaria"]),
    mc(3, "Which word correctly completes this RSV wording: “And Omri slept with his fathers, and was buried in _____; and Ahab his son reigned in his stead.”", ["Sama’ria", "Ginath", "Abi’ram", "Chronicles"], 28),
    word(1, "In verse 28, what word completes this phrase: “And Omri slept with his fathers, and was buried in _____; and Ahab his son reigned in his stead.”?", "Sama’ria", 28, ["samaria"]),
    tf(2, "The RSV does not state: “And Omri slept with his fathers, and was buried in Sama’ria; and Ahab his son reigned in his stead.”", false, 28, "The quoted wording is the RSV text of this verse."),
    blank(3, "to reign over Israel, and Ahab the son of Omri reigned over Israel in _____ twenty-two years.", "Sama’ria", 29, ["samaria"]),
    mc(1, "Which word correctly completes this RSV wording: “to reign over Israel, and Ahab the son of Omri reigned over Israel in _____ twenty-two years.”", ["Sama’ria", "Ashe’rah", "Israel", "Arza"], 29),
    word(2, "In verse 29, what word completes this phrase: “to reign over Israel, and Ahab the son of Omri reigned over Israel in _____ twenty-two years.”?", "Sama’ria", 29, ["samaria"]),
    tf(3, "The RSV states: “In the thirty-eighth year of Asa king of Judah, Ahab the son of Omri began to reign over Israel, and Ahab the son of Omri reigned over Israel in Sama’ria twenty-two years.”", true, 29),
    blank(1, "And _____ the son of Omri did evil in the sight of the LORD more than all that were", "Ahab", 30, ["ahab"]),
    mc(2, "Which word correctly completes this RSV wording: “And _____ the son of Omri did evil in the sight of the LORD more than all that were”", ["Ahab", "Ashe’rah", "Israel", "Thus"], 30),
    word(3, "In verse 30, what word completes this phrase: “And _____ the son of Omri did evil in the sight of the LORD more than all that were”?", "Ahab", 30, ["ahab"]),
    tf(1, "The RSV does not state: “And Ahab the son of Omri did evil in the sight of the LORD more than all that were before him.”", false, 30, "The quoted wording is the RSV text of this verse."),
    blank(2, "Nebat, he took for wife Jez’ebel the daughter of Ethba’al king of the _____, and went and served Ba’al, and worshiped him.", "Sido’nians", 31, ["sidonians"]),
    mc(3, "Which word correctly completes this RSV wording: “Nebat, he took for wife Jez’ebel the daughter of Ethba’al king of the _____, and went and served Ba’al, and worshiped him.”", ["Sido’nians", "Ashe’rah", "Jerobo’am", "Ginath"], 31),
    word(1, "In verse 31, what word completes this phrase: “Nebat, he took for wife Jez’ebel the daughter of Ethba’al king of the _____, and went and served Ba’al, and worshiped him.”?", "Sido’nians", 31, ["sidonians"]),
    tf(2, "The RSV states: “And as if it had been a light thing for him to walk in the sins of Jerobo’am the son of Nebat, he took for wife Jez’ebel the daughter of Ethba’al king of the Sido’nians, and went and served Ba’al, and worshiped him.”", true, 31),
    blank(3, "He erected an altar for Ba’al in the house of Ba’al, which he built in _____.", "Sama’ria", 32, ["samaria"]),
    mc(1, "Which word correctly completes this RSV wording: “He erected an altar for Ba’al in the house of Ba’al, which he built in _____.”", ["Sama’ria", "Zimri", "Ethba’al", "Hana’ni"], 32),
    word(2, "In verse 32, what word completes this phrase: “He erected an altar for Ba’al in the house of Ba’al, which he built in _____.”?", "Sama’ria", 32, ["samaria"]),
    tf(3, "The RSV does not state: “He erected an altar for Ba’al in the house of Ba’al, which he built in Sama’ria.”", false, 32, "The quoted wording is the RSV text of this verse."),
    blank(1, "And Ahab made an _____. Ahab did more to provoke the LORD, the God of Israel, to anger than all", "Ashe’rah", 33, ["asherah"]),
    mc(2, "Which word correctly completes this RSV wording: “And Ahab made an _____. Ahab did more to provoke the LORD, the God of Israel, to anger than all”", ["Ashe’rah", "Ginath", "Abi’ram", "Chronicles"], 33),
    word(3, "In verse 33, what word completes this phrase: “And Ahab made an _____. Ahab did more to provoke the LORD, the God of Israel, to anger than all”?", "Ashe’rah", 33, ["asherah"]),
    tf(1, "The RSV states: “And Ahab made an Ashe’rah. Ahab did more to provoke the LORD, the God of Israel, to anger than all the kings of Israel who were before him.”", true, 33),
    blank(2, "In his days Hi’el of Bethel built _____; he laid its foundation at the cost of Abi’ram his first-born, and set", "Jericho", 34, ["jericho"]),
    mc(3, "Which word correctly completes this RSV wording: “In his days Hi’el of Bethel built _____; he laid its foundation at the cost of Abi’ram his first-born, and set”", ["Jericho", "Ba’al", "Israel", "Arza"], 34),
    word(1, "In verse 34, what word completes this phrase: “In his days Hi’el of Bethel built _____; he laid its foundation at the cost of Abi’ram his first-born, and set”?", "Jericho", 34, ["jericho"]),
    tf(2, "The RSV does not state: “In his days Hi’el of Bethel built Jericho; he laid its foundation at the cost of Abi’ram his first-born, and set up its gates at the cost of his youngest son Segub, according to the word of the LORD, which he spoke by Joshua the son of Nun.”", false, 34, "The quoted wording is the RSV text of this verse."),
    mc(1, "Which prophet delivered the word of the LORD against Baasha?", ["Jehu son of Hanani", "Elijah the Tishbite", "Ahijah the Shilonite", "Shemaiah"], 1),
    mc(2, "What was Elah doing when Zimri struck him down?", ["Drinking himself drunk in Arza’s house at Tirzah", "Fighting the Philistines at Gibbethon", "Offering incense at Bethel", "Inspecting the army at Samaria"], 9),
    mc(2, "How long did Zimri reign before burning the king’s house over himself?", ["Seven days", "Seven months", "Two years", "Twenty-four years"], 15),
    mc(3, "From whom and for what price did Omri buy the hill of Samaria?", ["From Shemer for two talents of silver", "From Arza for one talent of gold", "From Tibni for six thousand shekels", "From Ethbaal for twenty talents of silver"], 24),
    mc(1, "Who was Ahab’s wife?", ["Jezebel, daughter of Ethbaal king of the Sidonians", "Maacah, daughter of Abishalom", "Zeruah, mother of Jeroboam", "Tahpenes, queen of Egypt"], 31),
    mc(3, "What did rebuilding Jericho cost Hiel of Bethel?", ["His first-born Abiram at its foundation and his youngest Segub at its gates", "Seven years of forced labor", "Two talents of silver", "The lives of all his servants"], 34),
  ],
};

export default bank;
