// 1 Kings 17 — quiz bank (RSV). Four verse-anchored forms per verse.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: "1 Kings",
  chapter: 17,
  tag: "quiz-v2-1kings-17",
  rows: [
    blank(2, "Now Eli’jah the _____, of Tishbe in Gilead, said to Ahab, \"As the LORD the God of Israel lives,", "Tishbite", 1, ["tishbite"]),
    mc(3, "Which word correctly completes this RSV wording: “Now Eli’jah the _____, of Tishbe in Gilead, said to Ahab, \"As the LORD the God of Israel lives,”", ["Tishbite", "Jordan", "Gilead", "Fear"], 1),
    word(1, "In verse 1, what word completes this phrase: “Now Eli’jah the _____, of Tishbe in Gilead, said to Ahab, \"As the LORD the God of Israel lives,”?", "Tishbite", 1, ["tishbite"]),
    tf(2, "The RSV states: “Now Eli’jah the Tishbite, of Tishbe in Gilead, said to Ahab, \"As the LORD the God of Israel lives, before whom I stand, there shall be neither dew nor rain these years, except by my word.\"”", true, 1),
    blank(3, "And the _____ of the LORD came to him,", "word", 2, ["word"]),
    mc(1, "Which word correctly completes this RSV wording: “And the _____ of the LORD came to him,”", ["word", "yourself", "bread", "widow"], 2),
    word(2, "In verse 2, what word completes this phrase: “And the _____ of the LORD came to him,”?", "word", 2, ["word"]),
    tf(3, "The RSV does not state: “And the word of the LORD came to him,”", false, 2, "The quoted wording is the RSV text of this verse."),
    blank(1, "\"Depart from here and turn eastward, and hide yourself by the brook _____, that is east of the Jordan.", "Cherith", 3, ["cherith"]),
    mc(2, "Which word correctly completes this RSV wording: “\"Depart from here and turn eastward, and hide yourself by the brook _____, that is east of the Jordan.”", ["Cherith", "Israel", "Eli’jah", "Behold"], 3),
    word(3, "In verse 3, what word completes this phrase: “\"Depart from here and turn eastward, and hide yourself by the brook _____, that is east of the Jordan.”?", "Cherith", 3, ["cherith"]),
    tf(1, "The RSV states: “\"Depart from here and turn eastward, and hide yourself by the brook Cherith, that is east of the Jordan.”", true, 3),
    blank(2, "You shall drink from the brook, and I have _____ the ravens to feed you there.\"", "commanded", 4, ["commanded"]),
    mc(3, "Which word correctly completes this RSV wording: “You shall drink from the brook, and I have _____ the ravens to feed you there.\"”", ["commanded", "evening", "city", "hand"], 4),
    word(1, "In verse 4, what word completes this phrase: “You shall drink from the brook, and I have _____ the ravens to feed you there.\"”?", "commanded", 4, ["commanded"]),
    tf(2, "The RSV does not state: “You shall drink from the brook, and I have commanded the ravens to feed you there.\"”", false, 4, "The quoted wording is the RSV text of this verse."),
    blank(3, "did according to the word of the LORD; he went and dwelt by the brook _____ that is east of the Jordan.", "Cherith", 5, ["cherith"]),
    mc(1, "Which word correctly completes this RSV wording: “did according to the word of the LORD; he went and dwelt by the brook _____ that is east of the Jordan.”", ["Cherith", "Gilead", "After", "Zar’ephath"], 5),
    word(2, "In verse 5, what word completes this phrase: “did according to the word of the LORD; he went and dwelt by the brook _____ that is east of the Jordan.”?", "Cherith", 5, ["cherith"]),
    tf(3, "The RSV states: “So he went and did according to the word of the LORD; he went and dwelt by the brook Cherith that is east of the Jordan.”", true, 5),
    blank(1, "And the ravens _____ him bread and meat in the morning, and bread and meat in the evening;", "brought", 6, ["brought"]),
    mc(2, "Which word correctly completes this RSV wording: “And the ravens _____ him bread and meat in the morning, and bread and meat in the evening;”", ["brought", "sticks", "only", "thus"], 6),
    word(3, "In verse 6, what word completes this phrase: “And the ravens _____ him bread and meat in the morning, and bread and meat in the evening;”?", "brought", 6, ["brought"]),
    tf(1, "The RSV does not state: “And the ravens brought him bread and meat in the morning, and bread and meat in the evening; and he drank from the brook.”", false, 6, "The quoted wording is the RSV text of this verse."),
    blank(2, "And after a while the brook dried up, _____ there was no rain in the land.", "because", 7, ["because"]),
    mc(3, "Which word correctly completes this RSV wording: “And after a while the brook dried up, _____ there was no rain in the land.”", ["because", "morsel", "first", "household"], 7),
    word(1, "In verse 7, what word completes this phrase: “And after a while the brook dried up, _____ there was no rain in the land.”?", "because", 7, ["because"]),
    tf(2, "The RSV states: “And after a while the brook dried up, because there was no rain in the land.”", true, 7),
    blank(3, "Then the _____ of the LORD came to him,", "word", 8, ["word"]),
    mc(1, "Which word correctly completes this RSV wording: “Then the _____ of the LORD came to him,”", ["word", "cruse", "fail", "became"], 8),
    word(2, "In verse 8, what word completes this phrase: “Then the _____ of the LORD came to him,”?", "word", 8, ["word"]),
    tf(3, "The RSV does not state: “Then the word of the LORD came to him,”", false, 8, "The quoted wording is the RSV text of this verse."),
    blank(1, "\"Arise, go to _____, which belongs to Sidon, and dwell there. Behold, I have commanded a widow", "Zar’ephath", 9, ["zarephath"]),
    mc(2, "Which word correctly completes this RSV wording: “\"Arise, go to _____, which belongs to Sidon, and dwell there. Behold, I have commanded a widow”", ["Zar’ephath", "Bring", "Sidon", "Jordan"], 9),
    word(3, "In verse 9, what word completes this phrase: “\"Arise, go to _____, which belongs to Sidon, and dwell there. Behold, I have commanded a widow”?", "Zar’ephath", 9, ["zarephath"]),
    tf(1, "The RSV states: “\"Arise, go to Zar’ephath, which belongs to Sidon, and dwell there. Behold, I have commanded a widow there to feed you.\"”", true, 9),
    blank(2, "So he arose and went to _____; and when he came to the gate of the city, behold, a widow was there gathering", "Zar’ephath", 10, ["zarephath"]),
    mc(3, "Which word correctly completes this RSV wording: “So he arose and went to _____; and when he came to the gate of the city, behold, a widow was there gathering”", ["Zar’ephath", "Depart", "Gilead", "Tishbite"], 10),
    word(1, "In verse 10, what word completes this phrase: “So he arose and went to _____; and when he came to the gate of the city, behold, a widow was there gathering”?", "Zar’ephath", 10, ["zarephath"]),
    tf(2, "The RSV does not state: “So he arose and went to Zar’ephath; and when he came to the gate of the city, behold, a widow was there gathering sticks; and he called to her and said, \"Bring me a little water in a vessel, that I may drink.\"”", false, 10, "The quoted wording is the RSV text of this verse."),
    blank(3, "And as she was going to bring it, he called to her and said, \"_____ me a morsel of bread in your hand.\"", "Bring", 11, ["bring"]),
    mc(1, "Which word correctly completes this RSV wording: “And as she was going to bring it, he called to her and said, \"_____ me a morsel of bread in your hand.\"”", ["Bring", "Fear", "Jordan", "Gilead"], 11),
    word(2, "In verse 11, what word completes this phrase: “And as she was going to bring it, he called to her and said, \"_____ me a morsel of bread in your hand.\"”?", "Bring", 11, ["bring"]),
    tf(3, "The RSV states: “And as she was going to bring it, he called to her and said, \"Bring me a morsel of bread in your hand.\"”", true, 11),
    blank(1, "handful of meal in a jar, and a little oil in a cruse; and now, I am _____ a couple of sticks, that I may go in and prepare it for myself and my", "gathering", 12, ["gathering"]),
    mc(2, "Which word correctly completes this RSV wording: “handful of meal in a jar, and a little oil in a cruse; and now, I am _____ a couple of sticks, that I may go in and prepare it for myself and my”", ["gathering", "come", "cried", "times"], 12),
    word(3, "In verse 12, what word completes this phrase: “handful of meal in a jar, and a little oil in a cruse; and now, I am _____ a couple of sticks, that I may go in and prepare it for myself and my”?", "gathering", 12, ["gathering"]),
    tf(1, "The RSV does not state: “And she said, \"As the LORD your God lives, I have nothing baked, only a handful of meal in a jar, and a little oil in a cruse; and now, I am gathering a couple of sticks, that I may go in and prepare it for myself and my son, that we may eat it, and die.\"”", false, 12, "The quoted wording is the RSV text of this verse."),
    blank(2, "And _____ said to her, \"Fear not; go and do as you have said; but first make me", "Eli’jah", 13, ["elijah"]),
    mc(3, "Which word correctly completes this RSV wording: “And _____ said to her, \"Fear not; go and do as you have said; but first make me”", ["Eli’jah", "Behold", "Cherith", "Tishbe"], 13),
    word(1, "In verse 13, what word completes this phrase: “And _____ said to her, \"Fear not; go and do as you have said; but first make me”?", "Eli’jah", 13, ["elijah"]),
    tf(2, "The RSV states: “And Eli’jah said to her, \"Fear not; go and do as you have said; but first make me a little cake of it and bring it to me, and afterward make for yourself and your son.”", true, 13),
    blank(3, "For thus says the LORD the God of _____, `The jar of meal shall not be spent, and the cruse of oil shall not fail,", "Israel", 14, ["israel"]),
    mc(1, "Which word correctly completes this RSV wording: “For thus says the LORD the God of _____, `The jar of meal shall not be spent, and the cruse of oil shall not fail,”", ["Israel", "Tishbe", "Fear", "Arise"], 14),
    word(2, "In verse 14, what word completes this phrase: “For thus says the LORD the God of _____, `The jar of meal shall not be spent, and the cruse of oil shall not fail,”?", "Israel", 14, ["israel"]),
    tf(3, "The RSV does not state: “For thus says the LORD the God of Israel, `The jar of meal shall not be spent, and the cruse of oil shall not fail, until the day that the LORD sends rain upon the earth.’\"”", false, 14, "The quoted wording is the RSV text of this verse."),
    blank(1, "And she went and did as _____ said; and she, and he, and her household ate for many days.", "Eli’jah", 15, ["elijah"]),
    mc(2, "Which word correctly completes this RSV wording: “And she went and did as _____ said; and she, and he, and her household ate for many days.”", ["Eli’jah", "Zar’ephath", "Israel", "Give"], 15),
    word(3, "In verse 15, what word completes this phrase: “And she went and did as _____ said; and she, and he, and her household ate for many days.”?", "Eli’jah", 15, ["elijah"]),
    tf(1, "The RSV states: “And she went and did as Eli’jah said; and she, and he, and her household ate for many days.”", true, 15),
    blank(2, "cruse of oil fail, according to the word of the LORD which he spoke by _____.", "Eli’jah", 16, ["elijah"]),
    mc(3, "Which word correctly completes this RSV wording: “cruse of oil fail, according to the word of the LORD which he spoke by _____.”", ["Eli’jah", "Tishbite", "Behold", "Cherith"], 16),
    word(1, "In verse 16, what word completes this phrase: “cruse of oil fail, according to the word of the LORD which he spoke by _____.”?", "Eli’jah", 16, ["elijah"]),
    tf(2, "The RSV does not state: “The jar of meal was not spent, neither did the cruse of oil fail, according to the word of the LORD which he spoke by Eli’jah.”", false, 16, "The quoted wording is the RSV text of this verse."),
    blank(3, "_____ this the son of the woman, the mistress of the house, became ill; and", "After", 17, ["after"]),
    mc(1, "Which word correctly completes this RSV wording: “_____ this the son of the woman, the mistress of the house, became ill; and”", ["After", "Cherith", "Tishbe", "Bring"], 17),
    word(2, "In verse 17, what word completes this phrase: “_____ this the son of the woman, the mistress of the house, became ill; and”?", "After", 17, ["after"]),
    tf(3, "The RSV states: “After this the son of the woman, the mistress of the house, became ill; and his illness was so severe that there was no breath left in him.”", true, 17),
    blank(1, "And she said to _____, \"What have you against me, O man of God? You have come to me to bring", "Eli’jah", 18, ["elijah"]),
    mc(2, "Which word correctly completes this RSV wording: “And she said to _____, \"What have you against me, O man of God? You have come to me to bring”", ["Eli’jah", "After", "Zar’ephath", "Israel"], 18),
    word(3, "In verse 18, what word completes this phrase: “And she said to _____, \"What have you against me, O man of God? You have come to me to bring”?", "Eli’jah", 18, ["elijah"]),
    tf(1, "The RSV does not state: “And she said to Eli’jah, \"What have you against me, O man of God? You have come to me to bring my sin to remembrance, and to cause the death of my son!\"”", false, 18, "The quoted wording is the RSV text of this verse."),
    blank(2, "And he said to her, \"_____ me your son.\" And he took him from her bosom, and carried him up into", "Give", 19, ["give"]),
    mc(3, "Which word correctly completes this RSV wording: “And he said to her, \"_____ me your son.\" And he took him from her bosom, and carried him up into”", ["Give", "Fear", "Arise", "Israel"], 19),
    word(1, "In verse 19, what word completes this phrase: “And he said to her, \"_____ me your son.\" And he took him from her bosom, and carried him up into”?", "Give", 19, ["give"]),
    tf(2, "The RSV states: “And he said to her, \"Give me your son.\" And he took him from her bosom, and carried him up into the upper chamber, where he lodged, and laid him upon his own bed.”", true, 19),
    blank(3, "And he cried to the LORD, \"O LORD my God, hast thou brought _____ even upon the widow with whom I sojourn, by slaying her son?\"", "calamity", 20, ["calamity"]),
    mc(1, "Which word correctly completes this RSV wording: “And he cried to the LORD, \"O LORD my God, hast thou brought _____ even upon the widow with whom I sojourn, by slaying her son?\"”", ["calamity", "feed", "dried", "sticks"], 20),
    word(2, "In verse 20, what word completes this phrase: “And he cried to the LORD, \"O LORD my God, hast thou brought _____ even upon the widow with whom I sojourn, by slaying her son?\"”?", "calamity", 20, ["calamity"]),
    tf(3, "The RSV does not state: “And he cried to the LORD, \"O LORD my God, hast thou brought calamity even upon the widow with whom I sojourn, by slaying her son?\"”", false, 20, "The quoted wording is the RSV text of this verse."),
    blank(1, "Then he _____ himself upon the child three times, and cried to the LORD, \"O LORD my", "stretched", 21, ["stretched"]),
    mc(2, "Which word correctly completes this RSV wording: “Then he _____ himself upon the child three times, and cried to the LORD, \"O LORD my”", ["stretched", "morning", "gate", "morsel"], 21),
    word(3, "In verse 21, what word completes this phrase: “Then he _____ himself upon the child three times, and cried to the LORD, \"O LORD my”?", "stretched", 21, ["stretched"]),
    tf(1, "The RSV states: “Then he stretched himself upon the child three times, and cried to the LORD, \"O LORD my God, let this child’s soul come into him again.\"”", true, 21),
    blank(2, "And the LORD hearkened to the voice of _____; and the soul of the child came into him again, and he revived.", "Eli’jah", 22, ["elijah"]),
    mc(3, "Which word correctly completes this RSV wording: “And the LORD hearkened to the voice of _____; and the soul of the child came into him again, and he revived.”", ["Eli’jah", "Sidon", "Depart", "Tishbite"], 22),
    word(1, "In verse 22, what word completes this phrase: “And the LORD hearkened to the voice of _____; and the soul of the child came into him again, and he revived.”?", "Eli’jah", 22, ["elijah"]),
    tf(2, "The RSV does not state: “And the LORD hearkened to the voice of Eli’jah; and the soul of the child came into him again, and he revived.”", false, 22, "The quoted wording is the RSV text of this verse."),
    blank(3, "And _____ took the child, and brought him down from the upper chamber into the house,", "Eli’jah", 23, ["elijah"]),
    mc(1, "Which word correctly completes this RSV wording: “And _____ took the child, and brought him down from the upper chamber into the house,”", ["Eli’jah", "Tishbe", "Bring", "Jordan"], 23),
    word(2, "In verse 23, what word completes this phrase: “And _____ took the child, and brought him down from the upper chamber into the house,”?", "Eli’jah", 23, ["elijah"]),
    tf(3, "The RSV states: “And Eli’jah took the child, and brought him down from the upper chamber into the house, and delivered him to his mother; and Eli’jah said, \"See, your son lives.\"”", true, 23),
    blank(1, "And the woman said to _____, \"Now I know that you are a man of God, and that the word of the LORD", "Eli’jah", 24, ["elijah"]),
    mc(2, "Which word correctly completes this RSV wording: “And the woman said to _____, \"Now I know that you are a man of God, and that the word of the LORD”", ["Eli’jah", "Arise", "Ahab", "After"], 24),
    word(3, "In verse 24, what word completes this phrase: “And the woman said to _____, \"Now I know that you are a man of God, and that the word of the LORD”?", "Eli’jah", 24, ["elijah"]),
    tf(1, "The RSV does not state: “And the woman said to Eli’jah, \"Now I know that you are a man of God, and that the word of the LORD in your mouth is truth.\"”", false, 24, "The quoted wording is the RSV text of this verse."),
    blank(1, "Now _____ the Tishbite, of Tishbe in Gilead, said to Ahab, \"As the LORD the God", "Eli’jah", 1, ["elijah"]),
    mc(2, "Select the missing RSV word: “And the word of the LORD _____ to him,”", ["came", "evening", "city", "hand"], 2),
    word(3, "What missing word belongs in this verse 3 clause: “\"Depart from here and turn _____, and hide yourself by the brook Cherith, that is east of the Jordan.”?", "eastward", 3, ["eastward"]),
    tf(1, "This wording appears in verse 4: “You shall drink from the brook, and I have commanded the ravens to feed you there.\"”", true, 4),
    blank(2, "So he went and did _____ to the word of the LORD; he went and dwelt by the brook Cherith that is", "according", 5, ["according"]),
    mc(3, "Select the missing RSV word: “And the ravens brought him bread and meat in the _____, and bread and meat in the evening; and he drank from the brook.”", ["morning", "come", "cried", "times"], 6),
    word(1, "What missing word belongs in this verse 7 clause: “And _____ a while the brook dried up, because there was no rain in the land.”?", "after", 7, ["after"]),
    tf(2, "This wording appears in verse 8: “Then the word of the LORD came to him,”", true, 8),
    blank(3, "to Zar’ephath, which belongs to Sidon, and dwell there. Behold, I have _____ a widow there to feed you.\"", "commanded", 9, ["commanded"]),
    mc(1, "Select the missing RSV word: “Zar’ephath; and when he came to the gate of the city, behold, a widow was there _____ sticks; and he called to her and said, \"Bring me a little water in a vessel,”", ["gathering", "feed", "dried", "called"], 10),
    word(2, "What missing word belongs in this verse 11 clause: “And as she was going to bring it, he _____ to her and said, \"Bring me a morsel of bread in your hand.\"”?", "called", 11, ["called"]),
    tf(3, "This wording appears in verse 12: “And she said, \"As the LORD your God lives, I have nothing baked, only a handful of meal in a jar, and a little oil in a cruse; and”", true, 12),
    blank(1, "have said; but first make me a little cake of it and bring it to me, and _____ make for yourself and your son.", "afterward", 13, ["afterward"]),
    mc(2, "Select the missing RSV word: “For thus says the LORD the God of Israel, `The jar of meal _____ not be spent, and the cruse of oil shall not fail, until the day that”", ["shall", "became", "carried", "slaying"], 14),
    word(3, "What missing word belongs in this verse 15 clause: “And she went and did as Eli’jah said; and she, and he, and her _____ ate for many days.”?", "household", 15, ["household"]),
    tf(1, "This wording appears in verse 16: “The jar of meal was not spent, neither did the cruse of oil fail, according to the word of the LORD which he spoke by Eli’jah.”", true, 16),
    blank(2, "After this the son of the woman, the _____ of the house, became ill; and his illness was so severe that there was", "mistress", 17, ["mistress"]),
    mc(3, "Select the missing RSV word: “you against me, O man of God? You have come to me to bring my sin to _____, and to cause the death of my son!\"”", ["remembrance", "couple", "carried", "delivered"], 18),
    word(1, "What missing word belongs in this verse 19 clause: “said to her, \"Give me your son.\" And he took him from her bosom, and _____ him up into the upper chamber, where he lodged, and laid him upon his”?", "carried", 19, ["carried"]),
    tf(2, "This wording appears in verse 20: “And he cried to the LORD, \"O LORD my God, hast thou brought calamity even upon the widow with whom I sojourn, by slaying her son?\"”", true, 20),
    blank(3, "Then he stretched _____ upon the child three times, and cried to the LORD, \"O LORD my God, let", "himself", 21, ["himself"]),
    mc(1, "Select the missing RSV word: “And the LORD _____ to the voice of Eli’jah; and the soul of the child came into him again,”", ["hearkened", "sends", "severe", "upper"], 22),
    word(2, "What missing word belongs in this verse 23 clause: “child, and brought him down from the upper chamber into the house, and _____ him to his mother; and Eli’jah said, \"See, your son lives.\"”?", "delivered", 23, ["delivered"]),
    tf(3, "This wording appears in verse 24: “And the woman said to Eli’jah, \"Now I know that you are a man of God, and that the word”", true, 24),
    mc(2, "For how long did Elijah say there would be neither dew nor rain?", ["These years, except by my word", "Forty days", "Seven years exactly", "Until Ahab left Samaria"], 1),
    mc(1, "Who brought Elijah bread and meat at the brook Cherith?", ["Ravens", "The widow of Zarephath", "Obadiah", "A prophet from Samaria"], 6),
    mc(1, "What was the widow of Zarephath doing when Elijah met her at the city gate?", ["Gathering sticks", "Drawing water", "Grinding meal", "Selling oil"], 10),
    mc(3, "What promise did Elijah give concerning the widow’s meal and oil?", ["The jar of meal would not be spent and the cruse of oil would not fail until the LORD sent rain", "The vessels would double every morning", "The oil would become wine", "The meal would last for seven days"], 14),
    mc(3, "What did Elijah do when the widow’s son died?", ["He stretched himself upon the child three times and cried to the LORD", "He carried the child to the brook", "He anointed the child with the widow’s oil", "He called the elders of the city"], 21),
  ],
};

export default bank;
