// 1 Kings 11 — quiz bank (RSV). Every row is anchored to a verse; fill-in-the-blank
// rows are verified against the stored verse text by scripts/seed-quiz-bank.ts.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: '1 Kings',
  chapter: 11,
  tag: 'quiz-v2-1kings-11',
  rows: [
    // ══════════════════════════════════ v1–8 · Solomon’s foreign wives and their gods
    mc(1, 'What does 1 Kings 11 open by saying King Solomon loved?', ['Many foreign women', 'Gold and silver', 'Horses and chariots', 'The wisdom of Egypt'], 1),
    blank(1, 'Now King Solomon loved many _____ women: the daughter of Pharaoh, and Moabite, Ammonite, E’domite, Sido’nian, and Hittite women,', 'foreign', 1),
    word(2, 'Whose daughter is named first among the foreign women Solomon loved?', 'Pharaoh', 1, ['pharaohs daughter']),
    mc(3, 'Which of these peoples is NOT listed in 1 Kings 11:1 among Solomon’s foreign wives?', ['Philistine', 'Moabite', 'Hittite', 'Ammonite'], 1),
    tf(2, '1 Kings 11:1 lists Sidonian women among the foreign women Solomon loved.', true, 1),
    blank(3, '"You shall not enter into _____ with them, neither shall they with you, for surely they will turn away your heart after their gods"', 'marriage', 2),
    mc(1, 'According to the LORD’s warning in 1 Kings 11:2, why should Israel not intermarry with these nations?', ['"Surely they will turn away your heart after their gods"', 'Because they were unclean', 'Because they would take Israel’s land', 'Because they were enemies of David'], 2),
    blank(3, 'Solomon _____ to these in love.', 'clung', 2),
    tf(1, 'The LORD had told the people of Israel not to enter into marriage with these nations.', true, 2),
    word(3, 'Verse 2 says Solomon "___ to these in love." Which verb?', 'clung', 2, ['clung to']),
    mc(1, 'How many wives did Solomon have?', ['Seven hundred', 'Three hundred', 'One thousand', 'Seventy'], 3),
    word(1, 'How many concubines did Solomon have?', 'three hundred', 3, ['300']),
    blank(1, 'He had _____ wives, princesses, and three hundred concubines; and his wives turned away his heart.', 'seven hundred', 3, ['700']),
    blank(3, 'He had seven hundred wives, princesses, and _____ concubines; and his wives turned away his heart.', 'three hundred', 3, ['300']),
    tf(1, 'Solomon had three hundred wives and seven hundred concubines.', false, 3, 'It was seven hundred wives, princesses, and three hundred concubines.'),
    mc(1, 'What effect did Solomon’s wives have on him (1 Kings 11:3)?', ['They turned away his heart', 'They made him rich', 'They made him wise', 'They built him a palace'], 3),
    tf(2, 'Solomon’s seven hundred wives are described as princesses.', true, 3),
    blank(3, 'For when Solomon was _____ his wives turned away his heart after other gods;', 'old', 4),
    mc(1, 'When did Solomon’s wives turn his heart after other gods?', ['When Solomon was old', 'In the first year of his reign', 'When he built the temple', 'When he married Pharaoh’s daughter'], 4),
    word(2, 'Whose heart was wholly true to the LORD, in contrast to Solomon’s?', 'David', 4, ['david his father']),
    blank(3, 'and his heart was not _____ true to the LORD his God, as was the heart of David his father.', 'wholly', 4),
    tf(2, 'Solomon’s heart was wholly true to the LORD, as the heart of David his father had been.', false, 4, 'His heart was NOT wholly true to the LORD, as David’s was.'),
    mc(1, 'Ashtoreth was the goddess of which people?', ['The Sidonians', 'The Ammonites', 'The Moabites', 'The Hittites'], 5),
    word(1, 'Solomon went after Ashtoreth, the goddess of which people?', 'Sidonians', 5, ['sidonian', 'the sidonians', 'sidon']),
    blank(1, 'For Solomon went after _____ the goddess of the Sido’nians, and after Milcom the abomination of the Ammonites.', 'Ash’toreth', 5, ['ashtoreth']),
    mc(1, 'Milcom was the abomination of which people?', ['The Ammonites', 'The Sidonians', 'The Moabites', 'The Edomites'], 5),
    word(2, 'Which god is called "the abomination of the Ammonites" in 1 Kings 11:5?', 'Milcom', 5),
    blank(3, 'and after _____ the abomination of the Ammonites.', 'Milcom', 5),
    tf(1, 'Ashtoreth is called the goddess of the Sidonians.', true, 5),
    tf(2, 'Solomon went after Milcom the abomination of Moab.', false, 5, 'Milcom was the abomination of the Ammonites.'),
    blank(1, 'So Solomon did what was _____ in the sight of the LORD, and did not wholly follow the LORD, as David his father had done.', 'evil', 6),
    tf(1, 'Solomon did what was evil in the sight of the LORD.', true, 6),
    mc(1, 'Verse 6 says Solomon "did not wholly follow the LORD, as ___ had done." Who?', ['David his father', 'Moses', 'Samuel', 'Joshua'], 6),
    blank(3, 'and did not wholly _____ the LORD, as David his father had done.', 'follow', 6),
    mc(1, 'Chemosh was the abomination of which nation?', ['Moab', 'The Ammonites', 'The Sidonians', 'Edom'], 7),
    word(2, 'Along with Chemosh, for which abomination of the Ammonites did Solomon build a high place?', 'Molech', 7),
    blank(3, 'Then Solomon built a high place for _____ the abomination of Moab, and for Molech the abomination of the Ammonites, on the mountain east of Jerusalem.', 'Chemosh', 7),
    mc(1, 'Where did Solomon build the high place for Chemosh and Molech?', ['On the mountain east of Jerusalem', 'In the temple court', 'At Gibeon', 'In the valley of Hinnom'], 7),
    blank(3, 'on the mountain _____ of Jerusalem.', 'east', 7),
    tf(2, 'Solomon built the high place for Chemosh and Molech on the mountain west of Jerusalem.', false, 7, 'It was on the mountain east of Jerusalem.'),
    word(1, 'What did Solomon build for Chemosh and for Molech?', 'high place', 7, ['a high place', 'high places']),
    blank(1, 'And so he did for all his foreign wives, who burned _____ and sacrificed to their gods.', 'incense', 8),
    mc(1, 'What did Solomon’s foreign wives do (1 Kings 11:8)?', ['Burned incense and sacrificed to their gods', 'Wove garments for the temple', 'Fasted and prayed', 'Taught Israel their languages'], 8),
    tf(2, 'Solomon built high places only for Pharaoh’s daughter.', false, 8, '"And so he did for all his foreign wives."'),
    word(3, 'Verse 8: the foreign wives "burned incense and ___ to their gods." Which verb?', 'sacrificed', 8, ['sacrifice']),

    // ══════════════════════════════════ v9–13 · The LORD’s anger and sentence
    mc(1, 'How many times had the LORD appeared to Solomon?', ['Twice', 'Once', 'Three times', 'Seven times'], 9),
    word(1, 'The LORD had appeared to Solomon how many times?', 'twice', 9, ['2', 'two']),
    blank(1, 'And the LORD was _____ with Solomon, because his heart had turned away from the LORD, the God of Israel, who had appeared to him twice,', 'angry', 9),
    blank(3, 'the God of Israel, who had appeared to him _____,', 'twice', 9),
    tf(1, 'The LORD was angry with Solomon because his heart had turned away from the LORD.', true, 9),
    tf(3, 'Verse 9 says the LORD had appeared to Solomon once.', false, 9, 'The LORD had appeared to him twice.'),
    blank(3, 'and had commanded him concerning this thing, that he should not go after other _____;', 'gods', 10),
    mc(1, 'What had the LORD commanded Solomon concerning (1 Kings 11:10)?', ['That he should not go after other gods', 'To build the temple in seven years', 'To keep the Sabbath', 'Not to marry Pharaoh’s daughter'], 10),
    tf(2, 'Solomon kept what the LORD had commanded him about other gods.', false, 10, '"He did not keep what the LORD commanded."'),
    blank(3, 'but he did not _____ what the LORD commanded.', 'keep', 10),
    mc(1, 'To whom did the LORD say He would give the kingdom torn from Solomon (1 Kings 11:11)?', ['Solomon’s servant', 'Solomon’s son', 'Pharaoh', 'Hadad'], 11),
    blank(1, 'I will surely _____ the kingdom from you and will give it to your servant.', 'tear', 11),
    blank(3, 'and you have not kept my _____ and my statutes which I have commanded you', 'covenant', 11),
    word(2, 'The LORD said He would tear the kingdom from Solomon and give it to his ___.', 'servant', 11),
    tf(2, 'The LORD told Solomon He would give the kingdom to Solomon’s brother.', false, 11, 'He would give it to Solomon’s servant.'),
    mc(3, 'With what phrase does the LORD begin His charge against Solomon in 1 Kings 11:11?', ['"Since this has been your mind"', '"Because you have despised me"', '"Since you have forgotten my law"', '"Because you have loved foreign women"'], 11),
    mc(1, 'For whose sake did the LORD refuse to tear the kingdom away during Solomon’s own days?', ['David his father', 'Solomon’s son', 'Jerusalem', 'Bathsheba'], 12),
    blank(3, 'Yet for the sake of David your father I will not do it in your _____, but I will tear it out of the hand of your son.', 'days', 12),
    word(2, 'Out of whose hand would the LORD tear the kingdom (1 Kings 11:12)?', 'son', 12, ['his son', 'solomons son', 'your son']),
    tf(1, 'The LORD said the kingdom would be torn away during Solomon’s own days.', false, 12, '"I will not do it in your days, but I will tear it out of the hand of your son."'),
    blank(3, 'but I will tear it out of the _____ of your son.', 'hand', 12),
    mc(1, 'How many tribes did the LORD say He would give to Solomon’s son (1 Kings 11:13)?', ['One tribe', 'Two tribes', 'Ten tribes', 'Twelve tribes'], 13),
    blank(1, 'However I will not tear away all the kingdom; but I will give _____ tribe to your son,', 'one', 13, ['1']),
    mc(2, 'For whose sake did the LORD leave one tribe to Solomon’s son (1 Kings 11:13)?', ['For the sake of David my servant and for the sake of Jerusalem which I have chosen', 'For the sake of Solomon’s wisdom', 'For the sake of Pharaoh’s daughter', 'For the sake of the temple Solomon built'], 13),
    blank(3, 'for the sake of David my servant and for the sake of _____ which I have chosen."', 'Jerusalem', 13),
    tf(2, 'The LORD said He would tear away all of the kingdom from Solomon’s line.', false, 13, '"I will not tear away all the kingdom; but I will give one tribe to your son."'),
    word(3, 'In 1 Kings 11:13 Jerusalem is described as the city the LORD had ___.', 'chosen', 13),

    // ══════════════════════════════════ v14–22 · Hadad the Edomite
    mc(1, 'Who was the adversary the LORD raised up against Solomon in 1 Kings 11:14?', ['Hadad the Edomite', 'Rezon the son of Eliada', 'Jeroboam the son of Nebat', 'Shishak king of Egypt'], 14),
    word(1, 'Hadad belonged to which people?', 'Edomite', 14, ['edom', 'the edomites', 'edomites']),
    blank(1, 'And the LORD raised up an _____ against Solomon, Hadad the E’domite; he was of the royal house in Edom.', 'adversary', 14),
    blank(3, 'And the LORD raised up an adversary against Solomon, _____ the E’domite; he was of the royal house in Edom.', 'Hadad', 14),
    mc(2, 'What was Hadad’s background?', ['He was of the royal house in Edom', 'He was a servant of Solomon', 'He was a priest of Chemosh', 'He was a Syrian merchant'], 14),
    tf(1, 'Hadad was of the royal house in Edom.', true, 14),
    mc(2, 'Who slew every male in Edom?', ['Joab the commander of the army', 'David', 'Solomon', 'Benaiah'], 15),
    blank(3, 'and Jo’ab the commander of the army went up to bury the _____, he slew every male in Edom', 'slain', 15),
    word(2, 'Joab went up to Edom to bury whom?', 'the slain', 15, ['slain']),
    tf(2, 'Joab slew every male in Edom.', true, 15),
    tf(3, 'Joab went up to bury the slain in Edom while Solomon was in Edom.', false, 15, 'It was "when David was in Edom".'),
    mc(1, 'How long did Joab and all Israel remain in Edom?', ['Six months', 'Forty days', 'A year', 'Three years'], 16),
    word(2, 'Joab and all Israel remained in Edom for six what?', 'months', 16),
    blank(3, '(for Jo’ab and all Israel remained there _____ months, until he had cut off every male in Edom);', 'six', 16, ['6']),
    tf(2, 'Joab and all Israel remained in Edom six years.', false, 16, 'They remained six months.'),
    mc(1, 'To what country did Hadad flee?', ['Egypt', 'Syria', 'Midian', 'Zobah'], 17),
    blank(1, 'but Hadad fled to _____, together with certain E’domites of his father’s servants, Hadad being yet a little child.', 'Egypt', 17),
    word(2, 'Hadad fled with certain Edomites who were whose servants?', 'his father’s', 17, ['his fathers', 'father', 'his father', 'fathers']),
    tf(1, 'Hadad was a grown man when he fled to Egypt.', false, 17, 'Hadad was "yet a little child".'),
    blank(3, 'Hadad being yet a little _____.', 'child', 17),
    mc(2, 'From where did Hadad’s party set out on the way to Egypt?', ['Midian', 'Paran', 'Edom', 'Zobah'], 18),
    word(2, 'Hadad’s party took men with them from which place before reaching Egypt?', 'Paran', 18),
    blank(3, 'They set out from _____ and came to Paran, and took men with them from Paran and came to Egypt,', 'Mid’ian', 18, ['midian']),
    mc(3, 'What three things did Pharaoh give Hadad?', ['A house, an allowance of food, and land', 'A chariot, horses, and gold', 'A wife, a house, and servants', 'A city, a field, and a vineyard'], 18),
    blank(3, 'who gave him a house, and assigned him an allowance of _____, and gave him land.', 'food', 18),
    tf(2, 'Pharaoh gave Hadad a house, an allowance of food, and land.', true, 18),
    mc(2, 'Whom did Pharaoh give Hadad in marriage?', ['The sister of his own wife, Tahpenes the queen', 'His own daughter', 'Tahpenes the queen herself', 'A daughter of Shishak'], 19),
    word(2, 'What was the name of Pharaoh’s wife, the queen?', 'Tahpenes', 19),
    blank(3, 'so that he gave him in marriage the sister of his own wife, the sister of _____ the queen.', 'Tah’penes', 19, ['tahpenes']),
    blank(1, 'And Hadad found great _____ in the sight of Pharaoh,', 'favor', 19, ['favour']),
    tf(2, 'Pharaoh gave Hadad his own daughter in marriage.', false, 19, 'He gave him the sister of his own wife, Tahpenes the queen.'),
    mc(2, 'What was the name of Hadad’s son?', ['Genubath', 'Rezon', 'Hadadezer', 'Eliada'], 20),
    word(3, 'Who weaned Genubath in Pharaoh’s house?', 'Tahpenes', 20),
    blank(3, 'And the sister of Tah’penes bore him _____ his son,', 'Genu’bath', 20, ['genubath']),
    tf(3, 'Genubath was in Pharaoh’s house among the sons of Pharaoh.', true, 20),
    blank(3, 'and Genu’bath was in Pharaoh’s house among the _____ of Pharaoh.', 'sons', 20),
    mc(2, 'What news prompted Hadad to ask Pharaoh to let him go home?', ['That David slept with his fathers and Joab the commander was dead', 'That Solomon had become king', 'That Edom had rebelled', 'That Pharaoh had died'], 21),
    blank(3, 'Hadad said to Pharaoh, "Let me _____, that I may go to my own country."', 'depart', 21),
    word(2, 'Hadad heard that which commander of the army was dead?', 'Joab', 21),
    tf(2, 'Hadad asked Pharaoh to let him depart when he heard that David and Joab were dead.', true, 21),
    mc(3, 'What did Hadad say to Pharaoh?', ['"Let me depart, that I may go to my own country"', '"Give me an army to fight Solomon"', '"Let my son reign in Edom"', '"Make me ruler over Paran"'], 21),
    mc(2, 'How did Pharaoh respond to Hadad’s request to leave?', ['"What have you lacked with me that you are now seeking to go to your own country?"', 'He gave him an army', 'He refused and imprisoned him', 'He sent him away with gifts'], 22),
    blank(3, 'But Pharaoh said to him, "What have you _____ with me that you are now seeking to go to your own country?"', 'lacked', 22),
    word(3, 'Hadad’s short reply to Pharaoh was "Only let me ___."', 'go', 22),
    tf(3, 'Hadad answered Pharaoh, "Only let me go."', true, 22),
    blank(3, 'And he said to him, "Only let me _____."', 'go', 22),

    // ══════════════════════════════════ v23–25 · Rezon of Damascus
    mc(1, 'Who was the second adversary God raised up against Solomon?', ['Rezon the son of Eliada', 'Hadad the Edomite', 'Jeroboam the son of Nebat', 'Genubath'], 23),
    word(1, 'Rezon was the son of whom?', 'Eliada', 23),
    blank(1, 'God also raised up as an adversary to him, _____ the son of Eli’ada, who had fled from his master Hadade’zer king of Zobah.', 'Rezon', 23),
    mc(2, 'From whom had Rezon fled?', ['Hadadezer king of Zobah', 'Pharaoh king of Egypt', 'David king of Israel', 'Hadad the Edomite'], 23),
    word(2, 'Hadadezer, Rezon’s master, was king of what?', 'Zobah', 23),
    blank(3, 'who had fled from his master _____ king of Zobah.', 'Hadade’zer', 23, ['hadadezer']),
    tf(2, 'Rezon had fled from his master Hadadezer king of Zobah.', true, 23),
    tf(1, 'Rezon the son of Eliada was of the royal house in Edom.', false, 23, 'That was Hadad; Rezon had fled from his master Hadadezer king of Zobah.'),
    mc(1, 'In which city was Rezon made king?', ['Damascus', 'Zobah', 'Edom', 'Egypt'], 24),
    word(1, 'Rezon and his men went to and dwelt in which city?', 'Damascus', 24),
    blank(3, 'and they went to _____, and dwelt there, and made him king in Damascus.', 'Damascus', 24),
    blank(3, 'And he gathered men about him and became leader of a _____ band, after the slaughter by David;', 'marauding', 24),
    mc(2, 'Rezon gathered men about him and became leader of what?', ['A marauding band', 'Pharaoh’s army', 'The forced labor', 'The priests of Chemosh'], 24),
    tf(2, 'Rezon was made king in Zobah.', false, 24, 'He was made king in Damascus.'),
    mc(2, 'Over what did Rezon reign?', ['Syria', 'Edom', 'Egypt', 'Moab'], 25),
    blank(3, 'and he abhorred Israel, and reigned over _____.', 'Syria', 25),
    blank(3, 'He was an adversary of Israel all the days of Solomon, doing _____ as Hadad did;', 'mischief', 25),
    word(3, 'Verse 25 says Rezon "___ Israel." Which verb?', 'abhorred', 25, ['abhor', 'abhorred israel']),
    tf(2, 'Rezon was an adversary of Israel all the days of Solomon.', true, 25),
    tf(3, 'Rezon reigned over Edom.', false, 25, 'He reigned over Syria.'),

    // ══════════════════════════════════ v26–28 · Jeroboam introduced
    mc(1, 'Jeroboam was the son of whom?', ['Nebat', 'Eliada', 'Ahijah', 'Solomon'], 26),
    word(1, 'Who was Jeroboam’s father?', 'Nebat', 26),
    word(2, 'What was the name of Jeroboam’s mother?', 'Zeruah', 26),
    blank(3, 'Jerobo’am the son of _____, an E’phraimite of Zer’edah, a servant of Solomon,', 'Nebat', 26),
    mc(2, 'Jeroboam was from which town?', ['Zeredah', 'Shiloh', 'Shechem', 'Bethel'], 26),
    mc(3, 'Jeroboam was of which tribe?', ['Ephraimite', 'Benjaminite', 'Judahite', 'Levite'], 26),
    blank(3, 'whose mother’s name was Zeru’ah, a _____, also lifted up his hand against the king.', 'widow', 26),
    tf(1, 'Jeroboam was a servant of Solomon.', true, 26),
    tf(2, 'Jeroboam’s mother Zeruah was a widow.', true, 26),
    tf(3, 'Jeroboam was a Benjaminite of Zeredah.', false, 26, 'He was an Ephraimite of Zeredah.'),
    mc(2, 'What did Solomon build, according to 1 Kings 11:27?', ['The Millo', 'The temple', 'A house for Pharaoh’s daughter', 'The wall of Gezer'], 27),
    word(2, 'Solomon built the ___ and closed up the breach of the city of David.', 'Millo', 27),
    blank(3, 'Solomon built the _____, and closed up the breach of the city of David his father.', 'Millo', 27),
    blank(3, 'Solomon built the Millo, and closed up the _____ of the city of David his father.', 'breach', 27),
    tf(3, 'Verse 27 says Solomon closed up the breach of the city of David his father.', true, 27),
    mc(1, 'What charge did Solomon give Jeroboam?', ['All the forced labor of the house of Joseph', 'The royal treasury', 'The army', 'The temple worship'], 28),
    word(2, 'Jeroboam had charge over the forced labor of the house of whom?', 'Joseph', 28),
    blank(3, 'he gave him charge over all the forced labor of the house of _____.', 'Joseph', 28),
    blank(3, 'The man Jerobo’am was very _____,', 'able', 28),
    mc(3, 'Solomon saw that the young man Jeroboam was what?', ['Industrious', 'Ambitious', 'Cunning', 'Wealthy'], 28),
    tf(2, 'Solomon gave Jeroboam charge over the forced labor of the house of Judah.', false, 28, 'It was the forced labor of the house of Joseph.'),

    // ══════════════════════════════════ v29–39 · Ahijah and the torn garment
    mc(1, 'Which prophet found Jeroboam on the road outside Jerusalem?', ['Ahijah the Shilonite', 'Nathan', 'Shemaiah', 'Elijah'], 29),
    word(1, 'Ahijah the prophet is called "the ___ite" — from which place?', 'Shilonite', 29, ['shiloh', 'shilonite']),
    blank(1, 'the prophet Ahi’jah the Shi’lonite found him on the _____.', 'road', 29),
    blank(3, 'Now Ahi’jah had clad himself with a _____ garment;', 'new', 29),
    mc(2, 'Where were Jeroboam and Ahijah when they met?', ['Alone in the open country', 'In the temple', 'At Solomon’s palace', 'In Shiloh'], 29),
    word(2, 'Jeroboam was going out of which city when Ahijah found him?', 'Jerusalem', 29),
    tf(2, 'Ahijah had clad himself with an old garment.', false, 29, 'He had clad himself with a new garment.'),
    tf(1, 'Ahijah and Jeroboam were alone in the open country.', true, 29),
    mc(1, 'Into how many pieces did Ahijah tear his new garment?', ['Twelve', 'Ten', 'Two', 'Seven'], 30),
    word(1, 'Ahijah tore the garment into how many pieces?', 'twelve', 30, ['12']),
    blank(1, 'Then Ahi’jah laid hold of the new garment that was on him, and tore it into _____ pieces.', 'twelve', 30, ['12']),
    tf(1, 'Ahijah tore his new garment into twelve pieces.', true, 30),
    tf(2, 'Jeroboam tore Ahijah’s garment into twelve pieces.', false, 30, 'Ahijah himself laid hold of the garment and tore it.'),
    mc(2, 'Whose garment was torn into twelve pieces?', ['Ahijah’s own new garment', 'Jeroboam’s cloak', 'Solomon’s robe', 'A garment from the temple'], 30),
    mc(1, 'How many of the pieces was Jeroboam told to take?', ['Ten', 'Twelve', 'Two', 'One'], 31),
    word(1, 'How many tribes did the LORD say He would give Jeroboam?', 'ten', 31, ['10']),
    blank(1, 'And he said to Jerobo’am, "Take for yourself _____ pieces;', 'ten', 31, ['10']),
    blank(3, 'Behold, I am about to tear the kingdom from the hand of _____, and will give you ten tribes', 'Solomon', 31),
    tf(1, 'Ahijah told Jeroboam to take all twelve pieces for himself.', false, 31, '"Take for yourself ten pieces."'),
    mc(3, 'In whose name did Ahijah speak when he gave Jeroboam the ten pieces?', ['"Thus says the LORD, the God of Israel"', 'In the name of Solomon', 'In his own name as prophet', 'In the name of the elders of Israel'], 31),
    mc(2, 'How is Jerusalem described in 1 Kings 11:32?', ['The city which I have chosen out of all the tribes of Israel', 'The city of David’s birth', 'The city of the great king', 'The city Solomon built'], 32),
    blank(3, '(but he shall have _____ tribe, for the sake of my servant David and for the sake of Jerusalem,', 'one', 32, ['1']),
    blank(3, 'the city which I have _____ out of all the tribes of Israel),', 'chosen', 32),
    tf(2, 'Verse 32 says Solomon’s line would keep one tribe for the sake of David and of Jerusalem.', true, 32),
    word(2, 'Verse 32: "for the sake of my servant ___" — whom?', 'David', 32),
    mc(2, 'Which three gods are named in 1 Kings 11:33?', ['Ashtoreth, Chemosh, and Milcom', 'Baal, Asherah, and Dagon', 'Molech, Baal, and Ashtoreth', 'Chemosh, Dagon, and Rimmon'], 33),
    blank(3, 'because he has _____ me, and worshiped Ash’toreth the goddess of the Sido’nians,', 'forsaken', 33),
    blank(3, 'Chemosh the god of _____, and Milcom the god of the Ammonites,', 'Moab', 33),
    word(3, 'Verse 33 calls Chemosh "the god of ___" — of what?', 'Moab', 33),
    tf(3, 'In 1 Kings 11:33 Chemosh is called the god of the Ammonites.', false, 33, 'Chemosh is the god of Moab; Milcom is the god of the Ammonites.'),
    mc(3, 'Verse 33 says Solomon has not walked in the LORD’s ways "as ___ did." Who?', ['David his father', 'Moses my servant', 'Joshua', 'Samuel'], 33),
    mc(2, 'For how long would Solomon remain ruler (1 Kings 11:34)?', ['All the days of his life', 'Ten more years', 'Until Jeroboam returned', 'Until his son came of age'], 34),
    blank(3, 'Nevertheless I will not take the whole kingdom out of his hand; but I will make him _____ all the days of his life,', 'ruler', 34),
    blank(3, 'for the sake of David my servant whom I chose, who kept my _____ and my statutes;', 'commandments', 34),
    tf(2, 'The LORD said He would take the whole kingdom out of Solomon’s hand at once.', false, 34, '"I will not take the whole kingdom out of his hand; but I will make him ruler all the days of his life."'),
    word(3, 'Verse 34 describes David as one "who kept my commandments and my ___."', 'statutes', 34),
    blank(1, 'but I will take the kingdom out of his son’s hand, and will give it to you, _____ tribes.', 'ten', 35, ['10']),
    mc(2, 'Out of whose hand would the kingdom be taken and given to Jeroboam (1 Kings 11:35)?', ['Solomon’s son’s hand', 'Solomon’s own hand', 'Hadad’s hand', 'Pharaoh’s hand'], 35),
    tf(1, 'The LORD promised to give Jeroboam ten tribes.', true, 35),
    word(2, 'Verse 35: "I will take the kingdom out of his ___ hand" — whose?', 'son’s', 35, ['sons', 'son', 'his sons']),
    mc(1, 'What image does 1 Kings 11:36 use for David’s continuing line in Jerusalem?', ['A lamp', 'A throne', 'A rock', 'A vine'], 36),
    word(1, '"that David my servant may always have a ___ before me in Jerusalem" — what?', 'lamp', 36),
    blank(1, 'that David my servant may always have a _____ before me in Jerusalem,', 'lamp', 36),
    blank(3, 'Jerusalem, the city where I have chosen to put my _____.', 'name', 36),
    mc(2, 'Why did God give one tribe to Solomon’s son, according to 1 Kings 11:36?', ['That David His servant may always have a lamp before Him in Jerusalem', 'As a reward for building the temple', 'Because Jeroboam refused it', 'So that Egypt would not attack'], 36),
    tf(2, 'Verse 36 calls Jerusalem the city where the LORD has chosen to put His name.', true, 36),
    tf(3, 'In 1 Kings 11:36 the LORD gives Solomon’s son two tribes.', false, 36, '"Yet to his son I will give one tribe."'),
    blank(3, 'And I will take you, and you shall reign over all that your _____ desires, and you shall be king over Israel.', 'soul', 37),
    mc(2, 'Over what did the LORD tell Jeroboam he would reign?', ['All that your soul desires', 'Judah and Benjamin', 'Egypt', 'Syria and Damascus'], 37),
    tf(1, 'The LORD told Jeroboam, "you shall be king over Israel."', true, 37),
    word(2, 'Verse 37: "you shall be king over ___" — over what?', 'Israel', 37),
    mc(2, 'What did the LORD promise to build for Jeroboam if he obeyed?', ['A sure house', 'A temple', 'A palace in Shechem', 'A city wall'], 38),
    blank(2, 'I will be with you, and will build you a _____ house, as I built for David, and I will give Israel to you.', 'sure', 38),
    blank(3, 'And if you will _____ to all that I command you, and will walk in my ways,', 'hearken', 38),
    mc(3, 'On what condition was the LORD’s promise of a sure house to Jeroboam made?', ['That he hearken to God’s commands and walk in His ways as David did', 'That he offer sacrifices at Shiloh', 'That he pay tribute to Solomon', 'That he marry an Israelite'], 38),
    tf(2, 'The LORD promised Jeroboam a sure house with no conditions attached.', false, 38, 'The promise began "if you will hearken to all that I command you".'),
    word(3, 'Verse 38: "I will build you a sure house, as I built for ___" — whom?', 'David', 38),
    mc(2, 'For how long would the LORD afflict the descendants of David (1 Kings 11:39)?', ['Not for ever', 'For ever', 'For forty years', 'Until Solomon died'], 39),
    blank(2, 'And I will for this _____ the descendants of David, but not for ever.', 'afflict', 39),
    tf(2, 'The LORD said the descendants of David would be afflicted for ever.', false, 39, '"but not for ever."'),
    word(3, 'Verse 39: "I will for this afflict the ___ of David" — what word?', 'descendants', 39),

    // ══════════════════════════════════ v40–43 · Jeroboam flees; Solomon dies
    mc(1, 'Where did Jeroboam flee from Solomon?', ['Egypt', 'Syria', 'Edom', 'Shiloh'], 40),
    mc(1, 'To which king did Jeroboam flee?', ['Shishak king of Egypt', 'Hadadezer king of Zobah', 'Rezon in Damascus', 'Hadad in Edom'], 40),
    word(1, 'Shishak was king of which country?', 'Egypt', 40),
    word(2, 'Which king of Egypt sheltered Jeroboam?', 'Shishak', 40),
    blank(1, 'but Jerobo’am arose, and fled into Egypt, to _____ king of Egypt, and was in Egypt until the death of Solomon.', 'Shishak', 40),
    blank(2, 'Solomon sought therefore to _____ Jerobo’am;', 'kill', 40),
    tf(1, 'Solomon sought to kill Jeroboam.', true, 40),
    tf(2, 'Jeroboam remained in Egypt until the death of Solomon.', true, 40),
    tf(3, 'Jeroboam fled into Syria, to Rezon in Damascus.', false, 40, 'He fled into Egypt, to Shishak king of Egypt.'),
    mc(2, 'How long was Jeroboam in Egypt?', ['Until the death of Solomon', 'Three years', 'Until Rehoboam invited him back', 'Forty days'], 40),
    mc(2, 'Where are the rest of the acts of Solomon said to be written?', ['The book of the acts of Solomon', 'The Chronicles of the Kings of Israel', 'The book of Nathan the prophet', 'The book of the law'], 41),
    blank(2, 'Now the rest of the acts of Solomon, and all that he did, and his _____, are they not written in the book of the acts of Solomon?', 'wisdom', 41),
    tf(3, 'Verse 41 says the rest of Solomon’s acts are written in the Chronicles of the Kings of Judah.', false, 41, 'They are written in "the book of the acts of Solomon".'),
    word(3, 'Solomon’s acts were written in "the book of the ___ of Solomon."', 'acts', 41),
    mc(1, 'How long did Solomon reign in Jerusalem over all Israel?', ['Forty years', 'Thirty years', 'Seven years', 'Fifty years'], 42),
    word(1, 'How many years did Solomon reign?', 'forty', 42, ['40']),
    blank(1, 'And the time that Solomon reigned in Jerusalem over all Israel was _____ years.', 'forty', 42, ['40']),
    tf(1, 'Solomon reigned forty years.', true, 42),
    blank(2, 'And the time that Solomon reigned in _____ over all Israel was forty years.', 'Jerusalem', 42),
    tf(2, 'Solomon reigned in Jerusalem over Judah only.', false, 42, 'He reigned "over all Israel".'),
    mc(1, 'Who reigned in Solomon’s stead after his death?', ['Rehoboam his son', 'Jeroboam', 'Hadad', 'Adonijah'], 43),
    word(1, 'Which son of Solomon reigned in his stead?', 'Rehoboam', 43),
    blank(1, 'and _____ his son reigned in his stead.', 'Rehobo’am', 43, ['rehoboam']),
    mc(2, 'Where was Solomon buried?', ['The city of David his father', 'Hebron', 'Bethlehem', 'Gibeon'], 43),
    blank(2, 'And Solomon slept with his fathers, and was buried in the city of _____ his father;', 'David', 43),
    tf(1, 'Solomon was buried in the city of David his father.', true, 43),
    tf(2, 'Jeroboam reigned in Solomon’s stead.', false, 43, 'Rehoboam his son reigned in his stead.'),

    // ══════════════════════════════════ Whole-chapter
    mc(2, 'Name the two adversaries the LORD raised up against Solomon in 1 Kings 11.', ['Hadad the Edomite and Rezon the son of Eliada', 'Jeroboam and Rehoboam', 'Shishak and Pharaoh', 'Hadadezer and Genubath'], 23),
    mc(1, 'In 1 Kings 11, how did Solomon’s downfall begin?', ['He loved many foreign women who turned away his heart', 'He grew greedy for gold', 'He went to war with Egypt', 'He killed Jeroboam'], 1),
    mc(2, 'Which of these events happened FIRST in 1 Kings 11?', ['Solomon built high places for Chemosh and Molech', 'Ahijah tore his garment into twelve pieces', 'Jeroboam fled to Shishak in Egypt', 'Rehoboam reigned in Solomon’s stead'], 7),
    mc(3, 'Who said, "What have you lacked with me that you are now seeking to go to your own country?"', ['Pharaoh, to Hadad', 'Solomon, to Jeroboam', 'Ahijah, to Jeroboam', 'Hadadezer, to Rezon'], 22),
    mc(3, 'Who said, "Take for yourself ten pieces"?', ['Ahijah, to Jeroboam', 'The LORD, to Solomon', 'Jeroboam, to Ahijah', 'Solomon, to Rehoboam'], 31),
    mc(3, 'Which men in 1 Kings 11 fled to Egypt?', ['Both Hadad and Jeroboam', 'Only Hadad', 'Only Jeroboam', 'Rezon and Hadadezer'], 40),
    tf(2, 'In 1 Kings 11 both Hadad and Rezon are called adversaries raised up against Solomon.', true, 25, 'Hadad in v14, Rezon in v23; v25 says Rezon did mischief "as Hadad did".'),
    mc(3, 'Which of these events happened LAST in 1 Kings 11?', ['Solomon slept with his fathers and Rehoboam reigned', 'Hadad fled to Egypt as a little child', 'Joab slew every male in Edom', 'Ahijah met Jeroboam on the road'], 43),
  ],
};

export default bank;
