// 1 Kings 14 — quiz bank (RSV). Four verse-anchored forms per verse.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: "1 Kings",
  chapter: 14,
  tag: "quiz-v2-1kings-14",
  rows: [
    blank(2, "At that time Abi’jah the son of _____ fell sick.", "Jerobo’am", 1, ["jeroboam"]),
    mc(3, "Which word correctly completes this RSV wording: “At that time Abi’jah the son of _____ fell sick.”", ["Jerobo’am", "Thus", "Kings", "Abi’jam"], 1),
    word(1, "In verse 1, what word completes this phrase: “At that time Abi’jah the son of _____ fell sick.”?", "Jerobo’am", 1, ["jeroboam"]),
    tf(2, "The RSV states: “At that time Abi’jah the son of Jerobo’am fell sick.”", true, 1),
    blank(3, "And _____ said to his wife, \"Arise, and disguise yourself, that it be not known", "Jerobo’am", 2, ["jeroboam"]),
    mc(1, "Which word correctly completes this RSV wording: “And _____ said to his wife, \"Arise, and disguise yourself, that it be not known”", ["Jerobo’am", "Ashe’rim", "Ammonitess", "Behold"], 2),
    word(2, "In verse 2, what word completes this phrase: “And _____ said to his wife, \"Arise, and disguise yourself, that it be not known”?", "Jerobo’am", 2, ["jeroboam"]),
    tf(3, "The RSV does not state: “And Jerobo’am said to his wife, \"Arise, and disguise yourself, that it be not known that you are the wife of Jerobo’am, and go to Shiloh; behold, Ahi’jah the prophet is there, who said of me that I should be king over this people.”", false, 2, "The quoted wording is the RSV text of this verse."),
    blank(1, "_____ with you ten loaves, some cakes, and a jar of honey, and go to him; he", "Take", 3, ["take"]),
    mc(2, "Which word correctly completes this RSV wording: “_____ with you ten loaves, some cakes, and a jar of honey, and go to him; he”", ["Take", "Na’amah", "Thus", "Rehobo’am"], 3),
    word(3, "In verse 3, what word completes this phrase: “_____ with you ten loaves, some cakes, and a jar of honey, and go to him; he”?", "Take", 3, ["take"]),
    tf(1, "The RSV states: “Take with you ten loaves, some cakes, and a jar of honey, and go to him; he will tell you what shall happen to the child.\"”", true, 3),
    blank(2, "_____ wife did so; she arose, and went to Shiloh, and came to the house of Ahi’jah.", "Jerobo’am’s", 4, ["jeroboams"]),
    mc(3, "Which word correctly completes this RSV wording: “_____ wife did so; she arose, and went to Shiloh, and came to the house of Ahi’jah.”", ["Jerobo’am’s", "Ashe’rim", "Jerobo’am", "Rehobo’am"], 4),
    word(1, "In verse 4, what word completes this phrase: “_____ wife did so; she arose, and went to Shiloh, and came to the house of Ahi’jah.”?", "Jerobo’am’s", 4, ["jeroboams"]),
    tf(2, "The RSV does not state: “Jerobo’am’s wife did so; she arose, and went to Shiloh, and came to the house of Ahi’jah. Now Ahi’jah could not see, for his eyes were dim because of his age.”", false, 4, "The quoted wording is the RSV text of this verse."),
    blank(3, "And the LORD said to Ahi’jah, \"Behold, the wife of _____ is coming to inquire of you concerning her son; for he is sick. Thus and", "Jerobo’am", 5, ["jeroboam"]),
    mc(1, "Which word correctly completes this RSV wording: “And the LORD said to Ahi’jah, \"Behold, the wife of _____ is coming to inquire of you concerning her son; for he is sick. Thus and”", ["Jerobo’am", "Jerobo’am’s", "Book", "Shishak"], 5),
    word(2, "In verse 5, what word completes this phrase: “And the LORD said to Ahi’jah, \"Behold, the wife of _____ is coming to inquire of you concerning her son; for he is sick. Thus and”?", "Jerobo’am", 5, ["jeroboam"]),
    tf(3, "The RSV states: “And the LORD said to Ahi’jah, \"Behold, the wife of Jerobo’am is coming to inquire of you concerning her son; for he is sick. Thus and thus shall you say to her.\" When she came, she pretended to be another woman.”", true, 5),
    blank(1, "sound of her feet, as she came in at the door, he said, \"Come in, wife of _____; why do you pretend to be another? For I am charged with heavy tidings", "Jerobo’am", 6, ["jeroboam"]),
    mc(2, "Which word correctly completes this RSV wording: “sound of her feet, as she came in at the door, he said, \"Come in, wife of _____; why do you pretend to be another? For I am charged with heavy tidings”", ["Jerobo’am", "Moreover", "Jerusalem", "Take"], 6),
    word(3, "In verse 6, what word completes this phrase: “sound of her feet, as she came in at the door, he said, \"Come in, wife of _____; why do you pretend to be another? For I am charged with heavy tidings”?", "Jerobo’am", 6, ["jeroboam"]),
    tf(1, "The RSV does not state: “But when Ahi’jah heard the sound of her feet, as she came in at the door, he said, \"Come in, wife of Jerobo’am; why do you pretend to be another? For I am charged with heavy tidings for you.”", false, 6, "The quoted wording is the RSV text of this verse."),
    blank(2, "Go, tell _____, `Thus says the LORD, the God of Israel: \"Because I exalted you from among", "Jerobo’am", 7, ["jeroboam"]),
    mc(3, "Which word correctly completes this RSV wording: “Go, tell _____, `Thus says the LORD, the God of Israel: \"Because I exalted you from among”", ["Jerobo’am", "Nadab", "Abi’jah", "David"], 7),
    word(1, "In verse 7, what word completes this phrase: “Go, tell _____, `Thus says the LORD, the God of Israel: \"Because I exalted you from among”?", "Jerobo’am", 7, ["jeroboam"]),
    tf(2, "The RSV states: “Go, tell Jerobo’am, `Thus says the LORD, the God of Israel: \"Because I exalted you from among the people, and made you leader over my people Israel,”", true, 7),
    blank(3, "and tore the kingdom away from the house of _____ and gave it to you; and yet you have not been like my servant David, who", "David", 8, ["david"]),
    mc(1, "Which word correctly completes this RSV wording: “and tore the kingdom away from the house of _____ and gave it to you; and yet you have not been like my servant David, who”", ["David", "Egypt", "Israel", "Solomon"], 8),
    word(2, "In verse 8, what word completes this phrase: “and tore the kingdom away from the house of _____ and gave it to you; and yet you have not been like my servant David, who”?", "David", 8, ["david"]),
    tf(3, "The RSV does not state: “and tore the kingdom away from the house of David and gave it to you; and yet you have not been like my servant David, who kept my commandments, and followed me with all his heart, doing only that which was right in my eyes,”", false, 8, "The quoted wording is the RSV text of this verse."),
    blank(1, "you and have gone and made for yourself other gods, and molten images, _____ me to anger, and have cast me behind your back;", "provoking", 9, ["provoking"]),
    mc(2, "Which word correctly completes this RSV wording: “you and have gone and made for yourself other gods, and molten images, _____ me to anger, and have cast me behind your back;”", ["provoking", "evil", "back", "dung"], 9),
    word(3, "In verse 9, what word completes this phrase: “you and have gone and made for yourself other gods, and molten images, _____ me to anger, and have cast me behind your back;”?", "provoking", 9, ["provoking"]),
    tf(1, "The RSV states: “but you have done evil above all that were before you and have gone and made for yourself other gods, and molten images, provoking me to anger, and have cast me behind your back;”", true, 9),
    blank(2, "therefore behold, I will bring evil upon the house of _____, and will cut off from Jerobo’am every male, both bond and free in Israel,", "Jerobo’am", 10, ["jeroboam"]),
    mc(3, "Which word correctly completes this RSV wording: “therefore behold, I will bring evil upon the house of _____, and will cut off from Jerobo’am every male, both bond and free in Israel,”", ["Jerobo’am", "Because", "Solomon", "Shiloh"], 10),
    word(1, "In verse 10, what word completes this phrase: “therefore behold, I will bring evil upon the house of _____, and will cut off from Jerobo’am every male, both bond and free in Israel,”?", "Jerobo’am", 10, ["jeroboam"]),
    tf(2, "The RSV does not state: “therefore behold, I will bring evil upon the house of Jerobo’am, and will cut off from Jerobo’am every male, both bond and free in Israel, and will utterly consume the house of Jerobo’am, as a man burns up dung until it is all gone.”", false, 10, "The quoted wording is the RSV text of this verse."),
    blank(3, "Any one belonging to _____ who dies in the city the dogs shall eat; and any one who dies in the open", "Jerobo’am", 11, ["jeroboam"]),
    mc(1, "Which word correctly completes this RSV wording: “Any one belonging to _____ who dies in the city the dogs shall eat; and any one who dies in the open”", ["Jerobo’am", "Chronicles", "Egypt", "Israel"], 11),
    word(2, "In verse 11, what word completes this phrase: “Any one belonging to _____ who dies in the city the dogs shall eat; and any one who dies in the open”?", "Jerobo’am", 11, ["jeroboam"]),
    tf(3, "The RSV states: “Any one belonging to Jerobo’am who dies in the city the dogs shall eat; and any one who dies in the open country the birds of the air shall eat; for the LORD has spoken it.\"’”", true, 11),
    blank(1, "_____ therefore, go to your house. When your feet enter the city, the child", "Arise", 12, ["arise"]),
    mc(2, "Which word correctly completes this RSV wording: “_____ therefore, go to your house. When your feet enter the city, the child”", ["Arise", "Shishak", "Israel", "Rehobo’am"], 12),
    word(3, "In verse 12, what word completes this phrase: “_____ therefore, go to your house. When your feet enter the city, the child”?", "Arise", 12, ["arise"]),
    tf(1, "The RSV does not state: “Arise therefore, go to your house. When your feet enter the city, the child shall die.”", false, 12, "The quoted wording is the RSV text of this verse."),
    blank(2, "And all Israel shall mourn for him, and bury him; for he only of _____ shall come to the grave, because in him there is found something pleasing", "Jerobo’am", 13, ["jeroboam"]),
    mc(3, "Which word correctly completes this RSV wording: “And all Israel shall mourn for him, and bury him; for he only of _____ shall come to the grave, because in him there is found something pleasing”", ["Jerobo’am", "Arise", "Moreover", "Jerusalem"], 13),
    word(1, "In verse 13, what word completes this phrase: “And all Israel shall mourn for him, and bury him; for he only of _____ shall come to the grave, because in him there is found something pleasing”?", "Jerobo’am", 13, ["jeroboam"]),
    tf(2, "The RSV states: “And all Israel shall mourn for him, and bury him; for he only of Jerobo’am shall come to the grave, because in him there is found something pleasing to the LORD, the God of Israel, in the house of Jerobo’am.”", true, 13),
    blank(3, "raise up for himself a king over Israel, who shall cut off the house of _____ today. And henceforth", "Jerobo’am", 14, ["jeroboam"]),
    mc(1, "Which word correctly completes this RSV wording: “raise up for himself a king over Israel, who shall cut off the house of _____ today. And henceforth”", ["Jerobo’am", "Come", "Nadab", "Abi’jah"], 14),
    word(2, "In verse 14, what word completes this phrase: “raise up for himself a king over Israel, who shall cut off the house of _____ today. And henceforth”?", "Jerobo’am", 14, ["jeroboam"]),
    tf(3, "The RSV does not state: “Moreover the LORD will raise up for himself a king over Israel, who shall cut off the house of Jerobo’am today. And henceforth”", false, 14, "The quoted wording is the RSV text of this verse."),
    blank(1, "good land which he gave to their fathers, and scatter them beyond the _____, because they have made their Ashe’rim, provoking the LORD to anger.", "Euphra’tes", 15, ["euphrates"]),
    mc(2, "Which word correctly completes this RSV wording: “good land which he gave to their fathers, and scatter them beyond the _____, because they have made their Ashe’rim, provoking the LORD to anger.”", ["Euphra’tes", "Jerobo’am’s", "Rehobo’am", "Arise"], 15),
    word(3, "In verse 15, what word completes this phrase: “good land which he gave to their fathers, and scatter them beyond the _____, because they have made their Ashe’rim, provoking the LORD to anger.”?", "Euphra’tes", 15, ["euphrates"]),
    tf(1, "The RSV states: “the LORD will smite Israel, as a reed is shaken in the water, and root up Israel out of this good land which he gave to their fathers, and scatter them beyond the Euphra’tes, because they have made their Ashe’rim, provoking the LORD to anger.”", true, 15),
    blank(2, "And he will give Israel up because of the sins of _____, which he sinned and which he made Israel to sin.\"", "Jerobo’am", 16, ["jeroboam"]),
    mc(3, "Which word correctly completes this RSV wording: “And he will give Israel up because of the sins of _____, which he sinned and which he made Israel to sin.\"”", ["Jerobo’am", "Judah", "Ahi’jah", "Ashe’rim"], 16),
    word(1, "In verse 16, what word completes this phrase: “And he will give Israel up because of the sins of _____, which he sinned and which he made Israel to sin.\"”?", "Jerobo’am", 16, ["jeroboam"]),
    tf(2, "The RSV does not state: “And he will give Israel up because of the sins of Jerobo’am, which he sinned and which he made Israel to sin.\"”", false, 16, "The quoted wording is the RSV text of this verse."),
    blank(3, "Then _____ wife arose, and departed, and came to Tirzah. And as she came to the threshold", "Jerobo’am’s", 17, ["jeroboams"]),
    mc(1, "Which word correctly completes this RSV wording: “Then _____ wife arose, and departed, and came to Tirzah. And as she came to the threshold”", ["Jerobo’am’s", "Israel", "Ammonitess", "Euphra’tes"], 17),
    word(2, "In verse 17, what word completes this phrase: “Then _____ wife arose, and departed, and came to Tirzah. And as she came to the threshold”?", "Jerobo’am’s", 17, ["jeroboams"]),
    tf(3, "The RSV states: “Then Jerobo’am’s wife arose, and departed, and came to Tirzah. And as she came to the threshold of the house, the child died.”", true, 17),
    blank(1, "him, according to the word of the LORD, which he spoke by his servant _____ the prophet.", "Ahi’jah", 18, ["ahijah"]),
    mc(2, "Which word correctly completes this RSV wording: “him, according to the word of the LORD, which he spoke by his servant _____ the prophet.”", ["Ahi’jah", "Behold", "Chronicles", "Egypt"], 18),
    word(3, "In verse 18, what word completes this phrase: “him, according to the word of the LORD, which he spoke by his servant _____ the prophet.”?", "Ahi’jah", 18, ["ahijah"]),
    tf(1, "The RSV does not state: “And all Israel buried him and mourned for him, according to the word of the LORD, which he spoke by his servant Ahi’jah the prophet.”", false, 18, "The quoted wording is the RSV text of this verse."),
    blank(2, "warred and how he reigned, behold, they are written in the Book of the _____ of the Kings of Israel.", "Chronicles", 19, ["chronicles"]),
    mc(3, "Which word correctly completes this RSV wording: “warred and how he reigned, behold, they are written in the Book of the _____ of the Kings of Israel.”", ["Chronicles", "Because", "Jerusalem", "Jerobo’am’s"], 19),
    word(1, "In verse 19, what word completes this phrase: “warred and how he reigned, behold, they are written in the Book of the _____ of the Kings of Israel.”?", "Chronicles", 19, ["chronicles"]),
    tf(2, "The RSV states: “Now the rest of the acts of Jerobo’am, how he warred and how he reigned, behold, they are written in the Book of the Chronicles of the Kings of Israel.”", true, 19),
    blank(3, "And the time that _____ reigned was twenty-two years; and he slept with his fathers, and Nadab", "Jerobo’am", 20, ["jeroboam"]),
    mc(1, "Which word correctly completes this RSV wording: “And the time that _____ reigned was twenty-two years; and he slept with his fathers, and Nadab”", ["Jerobo’am", "Rehobo’am", "Arise", "Moreover"], 20),
    word(2, "In verse 20, what word completes this phrase: “And the time that _____ reigned was twenty-two years; and he slept with his fathers, and Nadab”?", "Jerobo’am", 20, ["jeroboam"]),
    tf(3, "The RSV does not state: “And the time that Jerobo’am reigned was twenty-two years; and he slept with his fathers, and Nadab his son reigned in his stead.”", false, 20, "The quoted wording is the RSV text of this verse."),
    blank(1, "tribes of Israel, to put his name there. His mother’s name was Na’amah the _____.", "Ammonitess", 21, ["ammonitess"]),
    mc(2, "Which word correctly completes this RSV wording: “tribes of Israel, to put his name there. His mother’s name was Na’amah the _____.”", ["Ammonitess", "Shishak", "Because", "Judah"], 21),
    word(3, "In verse 21, what word completes this phrase: “tribes of Israel, to put his name there. His mother’s name was Na’amah the _____.”?", "Ammonitess", 21, ["ammonitess"]),
    tf(1, "The RSV states: “Now Rehobo’am the son of Solomon reigned in Judah. Rehobo’am was forty-one years old when he began to reign, and he reigned seventeen years in Jerusalem, the city which the LORD had chosen out of all the tribes of Israel, to put his name there. His mother’s name was Na’amah the Ammonitess.”", true, 21),
    blank(2, "And _____ did what was evil in the sight of the LORD, and they provoked him to jealousy", "Judah", 22, ["judah"]),
    mc(3, "Which word correctly completes this RSV wording: “And _____ did what was evil in the sight of the LORD, and they provoked him to jealousy”", ["Judah", "Israel", "Rehobo’am", "Arise"], 22),
    word(1, "In verse 22, what word completes this phrase: “And _____ did what was evil in the sight of the LORD, and they provoked him to jealousy”?", "Judah", 22, ["judah"]),
    tf(2, "The RSV does not state: “And Judah did what was evil in the sight of the LORD, and they provoked him to jealousy with their sins which they committed, more than all that their fathers had done.”", false, 22, "The quoted wording is the RSV text of this verse."),
    blank(3, "For they also built for themselves high places, and pillars, and _____ on every high hill and under every green tree;", "Ashe’rim", 23, ["asherim"]),
    mc(1, "Which word correctly completes this RSV wording: “For they also built for themselves high places, and pillars, and _____ on every high hill and under every green tree;”", ["Ashe’rim", "Because", "Judah", "Shiloh"], 23),
    word(2, "In verse 23, what word completes this phrase: “For they also built for themselves high places, and pillars, and _____ on every high hill and under every green tree;”?", "Ashe’rim", 23, ["asherim"]),
    tf(3, "The RSV states: “For they also built for themselves high places, and pillars, and Ashe’rim on every high hill and under every green tree;”", true, 23),
    blank(1, "abominations of the nations which the LORD drove out before the people of _____.", "Israel", 24, ["israel"]),
    mc(2, "Which word correctly completes this RSV wording: “abominations of the nations which the LORD drove out before the people of _____.”", ["Israel", "Kings", "Abi’jam", "Because"], 24),
    word(3, "In verse 24, what word completes this phrase: “abominations of the nations which the LORD drove out before the people of _____.”?", "Israel", 24, ["israel"]),
    tf(1, "The RSV does not state: “and there were also male cult prostitutes in the land. They did according to all the abominations of the nations which the LORD drove out before the people of Israel.”", false, 24, "The quoted wording is the RSV text of this verse."),
    blank(2, "In the fifth year of King _____, Shishak king of Egypt came up against Jerusalem;", "Rehobo’am", 25, ["rehoboam"]),
    mc(3, "Which word correctly completes this RSV wording: “In the fifth year of King _____, Shishak king of Egypt came up against Jerusalem;”", ["Rehobo’am", "Ammonitess", "Jerobo’am’s", "Book"], 25),
    word(1, "In verse 25, what word completes this phrase: “In the fifth year of King _____, Shishak king of Egypt came up against Jerusalem;”?", "Rehobo’am", 25, ["rehoboam"]),
    tf(2, "The RSV states: “In the fifth year of King Rehobo’am, Shishak king of Egypt came up against Jerusalem;”", true, 25),
    blank(3, "took away everything. He also took away all the shields of gold which _____ had made;", "Solomon", 26, ["solomon"]),
    mc(1, "Which word correctly completes this RSV wording: “took away everything. He also took away all the shields of gold which _____ had made;”", ["Solomon", "Arise", "Moreover", "Na’amah"], 26),
    word(2, "In verse 26, what word completes this phrase: “took away everything. He also took away all the shields of gold which _____ had made;”?", "Solomon", 26, ["solomon"]),
    tf(3, "The RSV does not state: “he took away the treasures of the house of the LORD and the treasures of the king’s house; he took away everything. He also took away all the shields of gold which Solomon had made;”", false, 26, "The quoted wording is the RSV text of this verse."),
    blank(1, "and King _____ made in their stead shields of bronze, and committed them to the hands", "Rehobo’am", 27, ["rehoboam"]),
    mc(2, "Which word correctly completes this RSV wording: “and King _____ made in their stead shields of bronze, and committed them to the hands”", ["Rehobo’am", "Come", "Nadab", "Jerobo’am"], 27),
    word(3, "In verse 27, what word completes this phrase: “and King _____ made in their stead shields of bronze, and committed them to the hands”?", "Rehobo’am", 27, ["rehoboam"]),
    tf(1, "The RSV states: “and King Rehobo’am made in their stead shields of bronze, and committed them to the hands of the officers of the guard, who kept the door of the king’s house.”", true, 27),
    blank(2, "the house of the LORD, the guard bore them and brought them back to the _____.", "guardroom", 28, ["guardroom"]),
    mc(3, "Which word correctly completes this RSV wording: “the house of the LORD, the guard bore them and brought them back to the _____.”", ["guardroom", "over", "went", "another"], 28),
    word(1, "In verse 28, what word completes this phrase: “the house of the LORD, the guard bore them and brought them back to the _____.”?", "guardroom", 28, ["guardroom"]),
    tf(2, "The RSV does not state: “And as often as the king went into the house of the LORD, the guard bore them and brought them back to the guardroom.”", false, 28, "The quoted wording is the RSV text of this verse."),
    blank(3, "Rehobo’am, and all that he did, are they not written in the Book of the _____ of the Kings of Judah?", "Chronicles", 29, ["chronicles"]),
    mc(1, "Which word correctly completes this RSV wording: “Rehobo’am, and all that he did, are they not written in the Book of the _____ of the Kings of Judah?”", ["Chronicles", "Shiloh", "Kings", "Abi’jah"], 29),
    word(2, "In verse 29, what word completes this phrase: “Rehobo’am, and all that he did, are they not written in the Book of the _____ of the Kings of Judah?”?", "Chronicles", 29, ["chronicles"]),
    tf(3, "The RSV states: “Now the rest of the acts of Rehobo’am, and all that he did, are they not written in the Book of the Chronicles of the Kings of Judah?”", true, 29),
    blank(1, "And there was war between _____ and Jerobo’am continually.", "Rehobo’am", 30, ["rehoboam"]),
    mc(2, "Which word correctly completes this RSV wording: “And there was war between _____ and Jerobo’am continually.”", ["Rehobo’am", "Abi’jah", "Because", "Judah"], 30),
    word(3, "In verse 30, what word completes this phrase: “And there was war between _____ and Jerobo’am continually.”?", "Rehobo’am", 30, ["rehoboam"]),
    tf(1, "The RSV does not state: “And there was war between Rehobo’am and Jerobo’am continually.”", false, 30, "The quoted wording is the RSV text of this verse."),
    blank(2, "with his fathers in the city of David. His mother’s name was Na’amah the _____. And Abi’jam his son reigned in his stead.", "Ammonitess", 31, ["ammonitess"]),
    mc(3, "Which word correctly completes this RSV wording: “with his fathers in the city of David. His mother’s name was Na’amah the _____. And Abi’jam his son reigned in his stead.”", ["Ammonitess", "Rehobo’am", "Shiloh", "Chronicles"], 31),
    word(1, "In verse 31, what word completes this phrase: “with his fathers in the city of David. His mother’s name was Na’amah the _____. And Abi’jam his son reigned in his stead.”?", "Ammonitess", 31, ["ammonitess"]),
    tf(2, "The RSV states: “And Rehobo’am slept with his fathers and was buried with his fathers in the city of David. His mother’s name was Na’amah the Ammonitess. And Abi’jam his son reigned in his stead.”", true, 31),
    mc(1, "What did Jeroboam tell his wife to do before visiting the prophet Ahijah?", ["Disguise herself so she would not be known as Jeroboam’s wife", "Bring the sick child with her", "Wear royal clothing", "Ask the elders to accompany her"], 2),
    mc(2, "How did the blind prophet Ahijah know Jeroboam’s wife had arrived?", ["The LORD had told him she was coming, and he heard the sound of her feet", "A servant announced her name", "She removed her disguise", "He recognized the gifts she carried"], 6),
    mc(3, "Why was Jeroboam’s son Abijah the only member of his house to be buried and mourned?", ["Something pleasing to the LORD, the God of Israel, was found in him", "He had served as a priest", "He had warned Jeroboam against the calves", "He died in Jerusalem"], 13),
    mc(2, "What did Rehoboam make after Shishak took away Solomon’s gold shields?", ["Shields of bronze", "Shields of iron", "Shields of silver", "Shields of cedar"], 27),
  ],
};

export default bank;
