// 2 Kings 12 — quiz bank (RSV). Four verse-anchored forms per verse.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: "2 Kings",
  chapter: 12,
  tag: "quiz-v2-2kings-12",
  rows: [
    blank(2, "he reigned forty years in Jerusalem. His mother’s name was Zib’iah of _____.", "Beer-sheba", 1, ["beer-sheba"]),
    mc(3, "Which word correctly completes this RSV wording: “he reigned forty years in Jerusalem. His mother’s name was Zib’iah of _____.”", ["Beer-sheba", "Syria", "Shim’e-ath", "Haz’ael"], 1),
    word(1, "In verse 1, what word completes this phrase: “he reigned forty years in Jerusalem. His mother’s name was Zib’iah of _____.”?", "Beer-sheba", 1, ["beer-sheba"]),
    tf(2, "The RSV states: “In the seventh year of Jehu Jeho’ash began to reign, and he reigned forty years in Jerusalem. His mother’s name was Zib’iah of Beer-sheba.”", true, 1),
    blank(3, "Jeho’ash did what was right in the eyes of the LORD all his days, because _____ the priest instructed him.", "Jehoi’ada", 2, ["jehoiada"]),
    mc(1, "Which word correctly completes this RSV wording: “Jeho’ash did what was right in the eyes of the LORD all his days, because _____ the priest instructed him.”", ["Jehoi’ada", "Ahazi’ah", "David", "Syria"], 2),
    word(2, "In verse 2, what word completes this phrase: “Jeho’ash did what was right in the eyes of the LORD all his days, because _____ the priest instructed him.”?", "Jehoi’ada", 2, ["jehoiada"]),
    tf(3, "The RSV does not state: “And Jeho’ash did what was right in the eyes of the LORD all his days, because Jehoi’ada the priest instructed him.”", false, 2, "The quoted wording is the RSV text of this verse."),
    blank(1, "_____ the high places were not taken away; the people continued to sacrifice", "Nevertheless", 3, ["nevertheless"]),
    mc(2, "Which word correctly completes this RSV wording: “_____ the high places were not taken away; the people continued to sacrifice”", ["Nevertheless", "Haz’ael", "Zib’iah", "Jeho’zabad"], 3),
    word(3, "In verse 3, what word completes this phrase: “_____ the high places were not taken away; the people continued to sacrifice”?", "Nevertheless", 3, ["nevertheless"]),
    tf(1, "The RSV states: “Nevertheless the high places were not taken away; the people continued to sacrifice and burn incense on the high places.”", true, 3),
    blank(2, "_____ said to the priests, \"All the money of the holy things which is brought", "Jeho’ash", 4, ["jehoash"]),
    mc(3, "Which word correctly completes this RSV wording: “_____ said to the priests, \"All the money of the holy things which is brought”", ["Jeho’ash", "Jerusalem", "Jehosh’aphat", "Jeho’zabad"], 4),
    word(1, "In verse 4, what word completes this phrase: “_____ said to the priests, \"All the money of the holy things which is brought”?", "Jeho’ash", 4, ["jehoash"]),
    tf(2, "The RSV does not state: “Jeho’ash said to the priests, \"All the money of the holy things which is brought into the house of the LORD, the money for which each man is assessed -- the money from the assessment of persons -- and the money which a man’s heart prompts him to bring into the house of the LORD,”", false, 4, "The quoted wording is the RSV text of this verse."),
    blank(3, "let the priests take, each from his _____; and let them repair the house wherever any need of repairs is discovered.\"", "acquaintance", 5, ["acquaintance"]),
    mc(1, "Which word correctly completes this RSV wording: “let the priests take, each from his _____; and let them repair the house wherever any need of repairs is discovered.\"”", ["acquaintance", "snuffers", "treasuries", "incense"], 5),
    word(2, "In verse 5, what word completes this phrase: “let the priests take, each from his _____; and let them repair the house wherever any need of repairs is discovered.\"”?", "acquaintance", 5, ["acquaintance"]),
    tf(3, "The RSV states: “let the priests take, each from his acquaintance; and let them repair the house wherever any need of repairs is discovered.\"”", true, 5),
    blank(1, "But by the twenty-third year of King _____ the priests had made no repairs on the house.", "Jeho’ash", 6, ["jehoash"]),
    mc(2, "Which word correctly completes this RSV wording: “But by the twenty-third year of King _____ the priests had made no repairs on the house.”", ["Jeho’ash", "Jo’ash", "Amazi’ah", "Gath"], 6),
    word(3, "In verse 6, what word completes this phrase: “But by the twenty-third year of King _____ the priests had made no repairs on the house.”?", "Jeho’ash", 6, ["jehoash"]),
    tf(1, "The RSV does not state: “But by the twenty-third year of King Jeho’ash the priests had made no repairs on the house.”", false, 6, "The quoted wording is the RSV text of this verse."),
    blank(2, "_____ King Jeho’ash summoned Jehoi’ada the priest and the other priests and", "Therefore", 7, ["therefore"]),
    mc(3, "Which word correctly completes this RSV wording: “_____ King Jeho’ash summoned Jehoi’ada the priest and the other priests and”", ["Therefore", "Shim’e-ath", "Nevertheless", "Chronicles"], 7),
    word(1, "In verse 7, what word completes this phrase: “_____ King Jeho’ash summoned Jehoi’ada the priest and the other priests and”?", "Therefore", 7, ["therefore"]),
    tf(2, "The RSV states: “Therefore King Jeho’ash summoned Jehoi’ada the priest and the other priests and said to them, \"Why are you not repairing the house? Now therefore take no more money from your acquaintances, but hand it over for the repair of the house.\"”", true, 7),
    blank(3, "So the _____ agreed that they should take no more money from the people, and that they", "priests", 8, ["priests"]),
    mc(1, "Which word correctly completes this RSV wording: “So the _____ agreed that they should take no more money from the people, and that they”", ["priests", "took", "much", "workmen"], 8),
    word(2, "In verse 8, what word completes this phrase: “So the _____ agreed that they should take no more money from the people, and that they”?", "priests", 8, ["priests"]),
    tf(3, "The RSV does not state: “So the priests agreed that they should take no more money from the people, and that they should not repair the house.”", false, 8, "The quoted wording is the RSV text of this verse."),
    blank(1, "Then _____ the priest took a chest, and bored a hole in the lid of it, and set it", "Jehoi’ada", 9, ["jehoiada"]),
    mc(2, "Which word correctly completes this RSV wording: “Then _____ the priest took a chest, and bored a hole in the lid of it, and set it”", ["Jehoi’ada", "Syria", "Silla", "Beer-sheba"], 9),
    word(3, "In verse 9, what word completes this phrase: “Then _____ the priest took a chest, and bored a hole in the lid of it, and set it”?", "Jehoi’ada", 9, ["jehoiada"]),
    tf(1, "The RSV states: “Then Jehoi’ada the priest took a chest, and bored a hole in the lid of it, and set it beside the altar on the right side as one entered the house of the LORD; and the priests who guarded the threshold put in it all the money that was brought into the house of the LORD.”", true, 9),
    blank(2, "whenever they saw that there was much money in the chest, the king’s _____ and the high priest came up and they counted and tied up in bags the money", "secretary", 10, ["secretary"]),
    mc(3, "Which word correctly completes this RSV wording: “whenever they saw that there was much money in the chest, the king’s _____ and the high priest came up and they counted and tied up in bags the money”", ["secretary", "king’s", "paid", "outlay"], 10),
    word(1, "In verse 10, what word completes this phrase: “whenever they saw that there was much money in the chest, the king’s _____ and the high priest came up and they counted and tied up in bags the money”?", "secretary", 10, ["secretary"]),
    tf(2, "The RSV does not state: “And whenever they saw that there was much money in the chest, the king’s secretary and the high priest came up and they counted and tied up in bags the money that was found in the house of the LORD.”", false, 10, "The quoted wording is the RSV text of this verse."),
    blank(3, "had the oversight of the house of the LORD; and they paid it out to the _____ and the builders who worked upon the house of the LORD,", "carpenters", 11, ["carpenters"]),
    mc(1, "Which word correctly completes this RSV wording: “had the oversight of the house of the LORD; and they paid it out to the _____ and the builders who worked upon the house of the LORD,”", ["carpenters", "honestly", "treasuries", "reigned"], 11),
    word(2, "In verse 11, what word completes this phrase: “had the oversight of the house of the LORD; and they paid it out to the _____ and the builders who worked upon the house of the LORD,”?", "carpenters", 11, ["carpenters"]),
    tf(3, "The RSV states: “Then they would give the money that was weighed out into the hands of the workmen who had the oversight of the house of the LORD; and they paid it out to the carpenters and the builders who worked upon the house of the LORD,”", true, 11),
    blank(1, "and to the masons and the _____, as well as to buy timber and quarried stone for making repairs on the", "stonecutters", 12, ["stonecutters"]),
    mc(2, "Which word correctly completes this RSV wording: “and to the masons and the _____, as well as to buy timber and quarried stone for making repairs on the”", ["stonecutters", "quarried", "dedicated", "sacrifice"], 12),
    word(3, "In verse 12, what word completes this phrase: “and to the masons and the _____, as well as to buy timber and quarried stone for making repairs on the”?", "stonecutters", 12, ["stonecutters"]),
    tf(1, "The RSV does not state: “and to the masons and the stonecutters, as well as to buy timber and quarried stone for making repairs on the house of the LORD, and for any outlay upon the repairs of the house.”", false, 12, "The quoted wording is the RSV text of this verse."),
    blank(2, "But there were not made for the house of the LORD basins of silver, _____, bowls, trumpets, or any vessels of gold, or of silver, from the money", "snuffers", 13, ["snuffers"]),
    mc(3, "Which word correctly completes this RSV wording: “But there were not made for the house of the LORD basins of silver, _____, bowls, trumpets, or any vessels of gold, or of silver, from the money”", ["snuffers", "stone", "delivered", "face"], 13),
    word(1, "In verse 13, what word completes this phrase: “But there were not made for the house of the LORD basins of silver, _____, bowls, trumpets, or any vessels of gold, or of silver, from the money”?", "snuffers", 13, ["snuffers"]),
    tf(2, "The RSV states: “But there were not made for the house of the LORD basins of silver, snuffers, bowls, trumpets, or any vessels of gold, or of silver, from the money that was brought into the house of the LORD,”", true, 13),
    blank(3, "for that was given to the workmen who were _____ the house of the LORD with it.", "repairing", 14, ["repairing"]),
    mc(1, "Which word correctly completes this RSV wording: “for that was given to the workmen who were _____ the house of the LORD with it.”", ["repairing", "vessels", "king", "sent"], 14),
    word(2, "In verse 14, what word completes this phrase: “for that was given to the workmen who were _____ the house of the LORD with it.”?", "repairing", 14, ["repairing"]),
    tf(3, "The RSV does not state: “for that was given to the workmen who were repairing the house of the LORD with it.”", false, 14, "The quoted wording is the RSV text of this verse."),
    blank(1, "And they did not ask an _____ from the men into whose hand they delivered the money to pay out to the", "accounting", 15, ["accounting"]),
    mc(2, "Which word correctly completes this RSV wording: “And they did not ask an _____ from the men into whose hand they delivered the money to pay out to the”", ["accounting", "priest", "brought", "wherever"], 15),
    word(3, "In verse 15, what word completes this phrase: “And they did not ask an _____ from the men into whose hand they delivered the money to pay out to the”?", "accounting", 15, ["accounting"]),
    tf(1, "The RSV states: “And they did not ask an accounting from the men into whose hand they delivered the money to pay out to the workmen, for they dealt honestly.”", true, 15),
    blank(2, "The money from the guilt _____ and the money from the sin offerings was not brought into the house of", "offerings", 16, ["offerings"]),
    mc(3, "Which word correctly completes this RSV wording: “The money from the guilt _____ and the money from the sin offerings was not brought into the house of”", ["offerings", "against", "written", "stead"], 16),
    word(1, "In verse 16, what word completes this phrase: “The money from the guilt _____ and the money from the sin offerings was not brought into the house of”?", "offerings", 16, ["offerings"]),
    tf(2, "The RSV does not state: “The money from the guilt offerings and the money from the sin offerings was not brought into the house of the LORD; it belonged to the priests.”", false, 16, "The quoted wording is the RSV text of this verse."),
    blank(3, "against Gath, and took it. But when Haz’ael set his face to go up against _____,", "Jerusalem", 17, ["jerusalem"]),
    mc(1, "Which word correctly completes this RSV wording: “against Gath, and took it. But when Haz’ael set his face to go up against _____,”", ["Jerusalem", "Judah", "Shim’e-ath", "King"], 17),
    word(2, "In verse 17, what word completes this phrase: “against Gath, and took it. But when Haz’ael set his face to go up against _____,”?", "Jerusalem", 17, ["jerusalem"]),
    tf(3, "The RSV states: “At that time Haz’ael king of Syria went up and fought against Gath, and took it. But when Haz’ael set his face to go up against Jerusalem,”", true, 17),
    blank(1, "Jeho’ash king of Judah took all the votive gifts that _____ and Jeho’ram and Ahazi’ah, his fathers, the kings of Judah, had dedicated,", "Jehosh’aphat", 18, ["jehoshaphat"]),
    mc(2, "Which word correctly completes this RSV wording: “Jeho’ash king of Judah took all the votive gifts that _____ and Jeho’ram and Ahazi’ah, his fathers, the kings of Judah, had dedicated,”", ["Jehosh’aphat", "Therefore", "Zib’iah", "Jeho’zabad"], 18),
    word(3, "In verse 18, what word completes this phrase: “Jeho’ash king of Judah took all the votive gifts that _____ and Jeho’ram and Ahazi’ah, his fathers, the kings of Judah, had dedicated,”?", "Jehosh’aphat", 18, ["jehoshaphat"]),
    tf(1, "The RSV does not state: “Jeho’ash king of Judah took all the votive gifts that Jehosh’aphat and Jeho’ram and Ahazi’ah, his fathers, the kings of Judah, had dedicated, and his own votive gifts, and all the gold that was found in the treasuries of the house of the LORD and of the king’s house, and sent these to Haz’ael king of Syria. Then Haz’ael went away from Jerusalem.”", false, 18, "The quoted wording is the RSV text of this verse."),
    blank(2, "Jo’ash, and all that he did, are they not written in the Book of the _____ of the Kings of Judah?", "Chronicles", 19, ["chronicles"]),
    mc(3, "Which word correctly completes this RSV wording: “Jo’ash, and all that he did, are they not written in the Book of the _____ of the Kings of Judah?”", ["Chronicles", "Shim’e-ath", "Therefore", "Jo’zacar"], 19),
    word(1, "In verse 19, what word completes this phrase: “Jo’ash, and all that he did, are they not written in the Book of the _____ of the Kings of Judah?”?", "Chronicles", 19, ["chronicles"]),
    tf(2, "The RSV states: “Now the rest of the acts of Jo’ash, and all that he did, are they not written in the Book of the Chronicles of the Kings of Judah?”", true, 19),
    blank(3, "His servants arose and made a conspiracy, and slew _____ in the house of Millo, on the way that goes down to Silla.", "Jo’ash", 20, ["joash"]),
    mc(1, "Which word correctly completes this RSV wording: “His servants arose and made a conspiracy, and slew _____ in the house of Millo, on the way that goes down to Silla.”", ["Jo’ash", "Chronicles", "Jeho’ash", "Jeho’ram"], 20),
    word(2, "In verse 20, what word completes this phrase: “His servants arose and made a conspiracy, and slew _____ in the house of Millo, on the way that goes down to Silla.”?", "Jo’ash", 20, ["joash"]),
    tf(3, "The RSV does not state: “His servants arose and made a conspiracy, and slew Jo’ash in the house of Millo, on the way that goes down to Silla.”", false, 20, "The quoted wording is the RSV text of this verse."),
    blank(1, "It was Jo’zacar the son of _____ and Jeho’zabad the son of Shomer, his servants, who struck him down, so", "Shim’e-ath", 21, ["shime-ath"]),
    mc(2, "Which word correctly completes this RSV wording: “It was Jo’zacar the son of _____ and Jeho’zabad the son of Shomer, his servants, who struck him down, so”", ["Shim’e-ath", "Judah", "Shomer", "Syria"], 21),
    word(3, "In verse 21, what word completes this phrase: “It was Jo’zacar the son of _____ and Jeho’zabad the son of Shomer, his servants, who struck him down, so”?", "Shim’e-ath", 21, ["shime-ath"]),
    tf(1, "The RSV states: “It was Jo’zacar the son of Shim’e-ath and Jeho’zabad the son of Shomer, his servants, who struck him down, so that he died. And they buried him with his fathers in the city of David, and Amazi’ah his son reigned in his stead.”", true, 21),
    blank(1, "seventh year of Jehu Jeho’ash began to reign, and he reigned forty years in _____. His mother’s name was Zib’iah of Beer-sheba.", "Jerusalem", 1, ["jerusalem"]),
    mc(2, "Select the missing RSV word: “right in the eyes of the LORD all his days, because Jehoi’ada the priest _____ him.”", ["instructed", "acquaintance", "agreed", "secretary"], 2),
    word(3, "What missing word belongs in this verse 3 clause: “Nevertheless the high places were not taken away; the people _____ to sacrifice and burn incense on the high places.”?", "continued", 3, ["continued"]),
    tf(1, "This wording appears in verse 4: “LORD, the money for which each man is assessed -- the money from the assessment of persons -- and the money which a man’s heart prompts him to bring into”", true, 4),
    blank(2, "acquaintance; and let them repair the house wherever any need of repairs is _____.\"", "discovered", 5, ["discovered"]),
    mc(3, "Select the missing RSV word: “But by the _____ year of King Jeho’ash the priests had made no repairs on the house.”", ["twenty-third", "quarried", "dedicated", "sacrifice"], 6),
    word(1, "What missing word belongs in this verse 7 clause: “you not repairing the house? Now therefore take no more money from your _____, but hand it over for the repair of the house.\"”?", "acquaintances", 7, ["acquaintances"]),
    tf(2, "This wording appears in verse 8: “So the priests agreed that they should take no more money from the people, and that they should”", true, 8),
    blank(3, "as one entered the house of the LORD; and the priests who guarded the _____ put in it all the money that was brought into the house of the LORD.", "threshold", 9, ["threshold"]),
    mc(1, "Select the missing RSV word: “And _____ they saw that there was much money in the chest, the king’s secretary”", ["whenever", "forty", "places", "holy"], 10),
    word(2, "What missing word belongs in this verse 11 clause: “money that was weighed out into the hands of the workmen who had the _____ of the house of the LORD; and they paid it out to the carpenters and the”?", "oversight", 11, ["oversight"]),
    tf(3, "This wording appears in verse 12: “and to the masons and the stonecutters, as well as to buy timber and quarried stone for making repairs on the house of the LORD, and for any outlay”", true, 12),
    blank(1, "not made for the house of the LORD basins of silver, snuffers, bowls, _____, or any vessels of gold, or of silver, from the money that was brought", "trumpets", 13, ["trumpets"]),
    mc(2, "Select the missing RSV word: “for that was given to the _____ who were repairing the house of the LORD with it.”", ["workmen", "altar", "tied", "masons"], 14),
    word(3, "What missing word belongs in this verse 15 clause: “And they did not ask an accounting from the men into whose hand they _____ the money to pay out to the workmen, for they dealt honestly.”?", "delivered", 15, ["delivered"]),
    tf(1, "This wording appears in verse 16: “from the sin offerings was not brought into the house of the LORD; it belonged to the priests.”", true, 16),
    blank(2, "At that time _____ king of Syria went up and fought against Gath, and took it. But when Haz’ael", "Haz’ael", 17, ["hazael"]),
    mc(3, "Select the missing RSV word: “dedicated, and his own votive gifts, and all the gold that was found in the _____ of the house of the LORD and of the king’s house, and sent these to Haz’ael”", ["treasuries", "worked", "bowls", "fought"], 18),
    word(1, "What missing word belongs in this verse 19 clause: “Now the rest of the acts of Jo’ash, and all that he did, are they not _____ in the Book of the Chronicles of the Kings of Judah?”?", "written", 19, ["written"]),
    tf(2, "This wording appears in verse 20: “His servants arose and made a conspiracy, and slew Jo’ash in the house of Millo, on the way that goes down to Silla.”", true, 20),
    blank(3, "It was Jo’zacar the son of Shim’e-ath and _____ the son of Shomer, his servants, who struck him down, so that he died.", "Jeho’zabad", 21, ["jehozabad"]),
    mc(1, "Select the missing RSV word: “In the seventh year of Jehu _____ began to reign, and he reigned forty years in Jerusalem. His mother’s”", ["Jeho’ash", "Amazi’ah", "Gath", "Jo’zacar"], 1),
    word(2, "What missing word belongs in this verse 2 clause: “And _____ did what was right in the eyes of the LORD all his days, because Jehoi’ada”?", "Jeho’ash", 2, ["jehoash"]),
    tf(3, "This wording appears in verse 3: “Nevertheless the high places were not taken away; the people continued to sacrifice and burn incense on the high places.”", true, 3),
    blank(1, "is brought into the house of the LORD, the money for which each man is _____ -- the money from the assessment of persons -- and the money which a man’s", "assessed", 4, ["assessed"]),
    mc(2, "Select the missing RSV word: “priests take, each from his acquaintance; and let them repair the house _____ any need of repairs is discovered.\"”", ["wherever", "carpenters", "basins", "honestly"], 5),
    word(3, "What missing word belongs in this verse 6 clause: “But by the twenty-third year of King Jeho’ash the _____ had made no repairs on the house.”?", "priests", 6, ["priests"]),
    tf(1, "This wording appears in verse 7: “Therefore King Jeho’ash summoned Jehoi’ada the priest and the other priests and said to them, \"Why are you not repairing”", true, 7),
    blank(2, "So the priests agreed that they _____ take no more money from the people, and that they should not repair the", "should", 8, ["should"]),
    mc(3, "Select the missing RSV word: “in the lid of it, and set it beside the altar on the right side as one _____ the house of the LORD; and the priests who guarded the threshold put in”", ["entered", "forty", "places", "holy"], 9),
    word(1, "What missing word belongs in this verse 10 clause: “the chest, the king’s secretary and the high priest came up and they _____ and tied up in bags the money that was found in the house of the LORD.”?", "counted", 10, ["counted"]),
    tf(2, "This wording appears in verse 11: “the house of the LORD; and they paid it out to the carpenters and the builders who worked upon the house of the LORD,”", true, 11),
    blank(3, "stonecutters, as well as to buy timber and quarried stone for making _____ on the house of the LORD, and for any outlay upon the repairs of the house.", "repairs", 12, ["repairs"]),
    mc(1, "Select the missing RSV word: “house of the LORD basins of silver, snuffers, bowls, trumpets, or any _____ of gold, or of silver, from the money that was brought into the house”", ["vessels", "beside", "counted", "builders"], 13),
    word(2, "What missing word belongs in this verse 14 clause: “for that was _____ to the workmen who were repairing the house of the LORD with it.”?", "given", 14, ["given"]),
    tf(3, "This wording appears in verse 15: “hand they delivered the money to pay out to the workmen, for they dealt honestly.”", true, 15),
    mc(1, "What did Jehoiada make to collect money for repairing the LORD’s house?", ["A chest with a hole bored in its lid, placed beside the altar", "A bronze basin at the gate", "A locked room in the palace", "A collection basket carried by priests"], 9),
    mc(2, "Why was no accounting required from the men who paid the temple workmen?", ["They dealt honestly", "The king counted the money himself", "The priests kept written records", "No silver remained after repairs"], 15),
  ],
};

export default bank;
