// 2 Kings 19 — quiz bank (RSV). Four verse-anchored forms per verse.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: "2 Kings",
  chapter: 19,
  tag: "quiz-v2-2kings-19",
  rows: [
    blank(2, "When King _____ heard it, he rent his clothes, and covered himself with sackcloth, and", "Hezeki’ah", 1, ["hezekiah"]),
    mc(3, "Which word correctly completes this RSV wording: “When King _____ heard it, he rent his clothes, and covered himself with sackcloth, and”", ["Hezeki’ah", "Assyria", "Eden", "Against"], 1),
    word(1, "In verse 1, what word completes this phrase: “When King _____ heard it, he rent his clothes, and covered himself with sackcloth, and”?", "Hezeki’ah", 1, ["hezekiah"]),
    tf(2, "The RSV states: “When King Hezeki’ah heard it, he rent his clothes, and covered himself with sackcloth, and went into the house of the LORD.”", true, 1),
    blank(3, "And he sent _____, who was over the household, and Shebna the secretary, and the senior", "Eli’akim", 2, ["eliakim"]),
    mc(1, "Which word correctly completes this RSV wording: “And he sent _____, who was over the household, and Shebna the secretary, and the senior”", ["Eli’akim", "Jerusalem", "Israel", "David"], 2),
    word(2, "In verse 2, what word completes this phrase: “And he sent _____, who was over the household, and Shebna the secretary, and the senior”?", "Eli’akim", 2, ["eliakim"]),
    tf(3, "The RSV does not state: “And he sent Eli’akim, who was over the household, and Shebna the secretary, and the senior priests, covered with sackcloth, to the prophet Isaiah the son of Amoz.”", false, 2, "The quoted wording is the RSV text of this verse."),
    blank(1, "They said to him, \"Thus says _____, This day is a day of distress, of rebuke, and of disgrace; children have", "Hezeki’ah", 3, ["hezekiah"]),
    mc(2, "Which word correctly completes this RSV wording: “They said to him, \"Thus says _____, This day is a day of distress, of rebuke, and of disgrace; children have”", ["Hezeki’ah", "Arpad", "Egypt", "Esarhad’don"], 3),
    word(3, "In verse 3, what word completes this phrase: “They said to him, \"Thus says _____, This day is a day of distress, of rebuke, and of disgrace; children have”?", "Hezeki’ah", 3, ["hezekiah"]),
    tf(1, "The RSV states: “They said to him, \"Thus says Hezeki’ah, This day is a day of distress, of rebuke, and of disgrace; children have come to the birth, and there is no strength to bring them forth.”", true, 3),
    blank(2, "It may be that the LORD your God heard all the words of the _____, whom his master the king of Assyria has sent to mock the living God,", "Rab’shakeh", 4, ["rabshakeh"]),
    mc(3, "Which word correctly completes this RSV wording: “It may be that the LORD your God heard all the words of the _____, whom his master the king of Assyria has sent to mock the living God,”", ["Rab’shakeh", "Therefore", "Shebna", "Haran"], 4),
    word(1, "In verse 4, what word completes this phrase: “It may be that the LORD your God heard all the words of the _____, whom his master the king of Assyria has sent to mock the living God,”?", "Rab’shakeh", 4, ["rabshakeh"]),
    tf(2, "The RSV does not state: “It may be that the LORD your God heard all the words of the Rab’shakeh, whom his master the king of Assyria has sent to mock the living God, and will rebuke the words which the LORD your God has heard; therefore lift up your prayer for the remnant that is left.\"”", false, 4, "The quoted wording is the RSV text of this verse."),
    blank(3, "When the servants of King _____ came to Isaiah,", "Hezeki’ah", 5, ["hezekiah"]),
    mc(1, "Which word correctly completes this RSV wording: “When the servants of King _____ came to Isaiah,”", ["Hezeki’ah", "Therefore", "Shebna", "Judah"], 5),
    word(2, "In verse 5, what word completes this phrase: “When the servants of King _____ came to Isaiah,”?", "Hezeki’ah", 5, ["hezekiah"]),
    tf(3, "The RSV states: “When the servants of King Hezeki’ah came to Isaiah,”", true, 5),
    blank(1, "the words that you have heard, with which the servants of the king of _____ have reviled me.", "Assyria", 6, ["assyria"]),
    mc(2, "Which word correctly completes this RSV wording: “the words that you have heard, with which the servants of the king of _____ have reviled me.”", ["Assyria", "Ar’arat", "Libnah", "Hamath"], 6),
    word(3, "In verse 6, what word completes this phrase: “the words that you have heard, with which the servants of the king of _____ have reviled me.”?", "Assyria", 6, ["assyria"]),
    tf(1, "The RSV does not state: “Isaiah said to them, \"Say to your master, `Thus says the LORD: Do not be afraid because of the words that you have heard, with which the servants of the king of Assyria have reviled me.”", false, 6, "The quoted wording is the RSV text of this verse."),
    blank(2, "_____, I will put a spirit in him, so that he shall hear a rumor and return", "Behold", 7, ["behold"]),
    mc(3, "Which word correctly completes this RSV wording: “_____, I will put a spirit in him, so that he shall hear a rumor and return”", ["Behold", "Rab’shakeh", "Eden", "Holy"], 7),
    word(1, "In verse 7, what word completes this phrase: “_____, I will put a spirit in him, so that he shall hear a rumor and return”?", "Behold", 7, ["behold"]),
    tf(2, "The RSV states: “Behold, I will put a spirit in him, so that he shall hear a rumor and return to his own land; and I will cause him to fall by the sword in his own land.’\"”", true, 7),
    blank(3, "The _____ returned, and found the king of Assyria fighting against Libnah; for he", "Rab’shakeh", 8, ["rabshakeh"]),
    mc(1, "Which word correctly completes this RSV wording: “The _____ returned, and found the king of Assyria fighting against Libnah; for he”", ["Rab’shakeh", "Ivvah", "Assyrians", "Assyria"], 8),
    word(2, "In verse 8, what word completes this phrase: “The _____ returned, and found the king of Assyria fighting against Libnah; for he”?", "Rab’shakeh", 8, ["rabshakeh"]),
    tf(3, "The RSV does not state: “The Rab’shakeh returned, and found the king of Assyria fighting against Libnah; for he heard that the king had left Lachish.”", false, 8, "The quoted wording is the RSV text of this verse."),
    blank(1, "And when the king heard concerning _____ king of Ethiopia, \"Behold, he has set out to fight against you,\" he sent", "Tirha’kah", 9, ["tirhakah"]),
    mc(2, "Which word correctly completes this RSV wording: “And when the king heard concerning _____ king of Ethiopia, \"Behold, he has set out to fight against you,\" he sent”", ["Tirha’kah", "Tel-assar", "Holy", "Share’zer"], 9),
    word(3, "In verse 9, what word completes this phrase: “And when the king heard concerning _____ king of Ethiopia, \"Behold, he has set out to fight against you,\" he sent”?", "Tirha’kah", 9, ["tirhakah"]),
    tf(1, "The RSV states: “And when the king heard concerning Tirha’kah king of Ethiopia, \"Behold, he has set out to fight against you,\" he sent messengers again to Hezeki’ah, saying,”", true, 9),
    blank(2, "\"Thus shall you speak to _____ king of Judah: `Do not let your God on whom you rely deceive you by promising", "Hezeki’ah", 10, ["hezekiah"]),
    mc(3, "Which word correctly completes this RSV wording: “\"Thus shall you speak to _____ king of Judah: `Do not let your God on whom you rely deceive you by promising”", ["Hezeki’ah", "Incline", "Assyrians", "Amoz"], 10),
    word(1, "In verse 10, what word completes this phrase: “\"Thus shall you speak to _____ king of Judah: `Do not let your God on whom you rely deceive you by promising”?", "Hezeki’ah", 10, ["hezekiah"]),
    tf(2, "The RSV does not state: “\"Thus shall you speak to Hezeki’ah king of Judah: `Do not let your God on whom you rely deceive you by promising that Jerusalem will not be given into the hand of the king of Assyria.”", false, 10, "The quoted wording is the RSV text of this verse."),
    blank(3, "Behold, you have heard what the kings of _____ have done to all lands, destroying them utterly. And shall you be delivered?", "Assyria", 11, ["assyria"]),
    mc(1, "Which word correctly completes this RSV wording: “Behold, you have heard what the kings of _____ have done to all lands, destroying them utterly. And shall you be delivered?”", ["Assyria", "Because", "King", "Tirha’kah"], 11),
    word(2, "In verse 11, what word completes this phrase: “Behold, you have heard what the kings of _____ have done to all lands, destroying them utterly. And shall you be delivered?”?", "Assyria", 11, ["assyria"]),
    tf(3, "The RSV states: “Behold, you have heard what the kings of Assyria have done to all lands, destroying them utterly. And shall you be delivered?”", true, 11),
    blank(1, "fathers destroyed, Gozan, Haran, Rezeph, and the people of Eden who were in _____?", "Tel-assar", 12, ["tel-assar"]),
    mc(2, "Which word correctly completes this RSV wording: “fathers destroyed, Gozan, Haran, Rezeph, and the people of Eden who were in _____?”", ["Tel-assar", "Adram’melech", "Rab’shakeh", "Rezeph"], 12),
    word(3, "In verse 12, what word completes this phrase: “fathers destroyed, Gozan, Haran, Rezeph, and the people of Eden who were in _____?”?", "Tel-assar", 12, ["tel-assar"]),
    tf(1, "The RSV does not state: “Have the gods of the nations delivered them, the nations which my fathers destroyed, Gozan, Haran, Rezeph, and the people of Eden who were in Tel-assar?”", false, 12, "The quoted wording is the RSV text of this verse."),
    blank(2, "Where is the king of Hamath, the king of Arpad, the king of the city of _____, the king of Hena, or the king of Ivvah?’\"", "Sepharva’im", 13, ["sepharvaim"]),
    mc(3, "Which word correctly completes this RSV wording: “Where is the king of Hamath, the king of Arpad, the king of the city of _____, the king of Hena, or the king of Ivvah?’\"”", ["Sepharva’im", "Rab’shakeh", "Israel", "Share’zer"], 13),
    word(1, "In verse 13, what word completes this phrase: “Where is the king of Hamath, the king of Arpad, the king of the city of _____, the king of Hena, or the king of Ivvah?’\"”?", "Sepharva’im", 13, ["sepharvaim"]),
    tf(2, "The RSV states: “Where is the king of Hamath, the king of Arpad, the king of the city of Sepharva’im, the king of Hena, or the king of Ivvah?’\"”", true, 13),
    blank(3, "_____ received the letter from the hand of the messengers, and read it; and", "Hezeki’ah", 14, ["hezekiah"]),
    mc(1, "Which word correctly completes this RSV wording: “_____ received the letter from the hand of the messengers, and read it; and”", ["Hezeki’ah", "Lachish", "Arpad", "Egypt"], 14),
    word(2, "In verse 14, what word completes this phrase: “_____ received the letter from the hand of the messengers, and read it; and”?", "Hezeki’ah", 14, ["hezekiah"]),
    tf(3, "The RSV does not state: “Hezeki’ah received the letter from the hand of the messengers, and read it; and Hezeki’ah went up to the house of the LORD, and spread it before the LORD.”", false, 14, "The quoted wording is the RSV text of this verse."),
    blank(1, "And _____ prayed before the LORD, and said: \"O LORD the God of Israel, who art enthroned", "Hezeki’ah", 15, ["hezekiah"]),
    mc(2, "Which word correctly completes this RSV wording: “And _____ prayed before the LORD, and said: \"O LORD the God of Israel, who art enthroned”", ["Hezeki’ah", "Rezeph", "Zion", "Nisroch"], 15),
    word(3, "In verse 15, what word completes this phrase: “And _____ prayed before the LORD, and said: \"O LORD the God of Israel, who art enthroned”?", "Hezeki’ah", 15, ["hezekiah"]),
    tf(1, "The RSV states: “And Hezeki’ah prayed before the LORD, and said: \"O LORD the God of Israel, who art enthroned above the cherubim, thou art the God, thou alone, of all the kingdoms of the earth; thou hast made heaven and earth.”", true, 15),
    blank(2, "LORD, and hear; open thy eyes, O LORD, and see; and hear the words of _____, which he has sent to mock the living God.", "Sennach’erib", 16, ["sennacherib"]),
    mc(3, "Which word correctly completes this RSV wording: “LORD, and hear; open thy eyes, O LORD, and see; and hear the words of _____, which he has sent to mock the living God.”", ["Sennach’erib", "Rab’shakeh", "Because", "Jerusalem"], 16),
    word(1, "In verse 16, what word completes this phrase: “LORD, and hear; open thy eyes, O LORD, and see; and hear the words of _____, which he has sent to mock the living God.”?", "Sennach’erib", 16, ["sennacherib"]),
    tf(2, "The RSV does not state: “Incline thy ear, O LORD, and hear; open thy eyes, O LORD, and see; and hear the words of Sennach’erib, which he has sent to mock the living God.”", false, 16, "The quoted wording is the RSV text of this verse."),
    blank(3, "Of a truth, O LORD, the kings of _____ have laid waste the nations and their lands,", "Assyria", 17, ["assyria"]),
    mc(1, "Which word correctly completes this RSV wording: “Of a truth, O LORD, the kings of _____ have laid waste the nations and their lands,”", ["Assyria", "Lebanon", "Ar’arat", "Libnah"], 17),
    word(2, "In verse 17, what word completes this phrase: “Of a truth, O LORD, the kings of _____ have laid waste the nations and their lands,”?", "Assyria", 17, ["assyria"]),
    tf(3, "The RSV states: “Of a truth, O LORD, the kings of Assyria have laid waste the nations and their lands,”", true, 17),
    blank(1, "fire; for they were no gods, but the work of men’s hands, wood and stone; _____ they were destroyed.", "therefore", 18, ["therefore"]),
    mc(2, "Which word correctly completes this RSV wording: “fire; for they were no gods, but the work of men’s hands, wood and stone; _____ they were destroyed.”", ["therefore", "heights", "densest", "long"], 18),
    word(3, "In verse 18, what word completes this phrase: “fire; for they were no gods, but the work of men’s hands, wood and stone; _____ they were destroyed.”?", "therefore", 18, ["therefore"]),
    tf(1, "The RSV does not state: “and have cast their gods into the fire; for they were no gods, but the work of men’s hands, wood and stone; therefore they were destroyed.”", false, 18, "The quoted wording is the RSV text of this verse."),
    blank(2, "O LORD our God, save us, I beseech thee, from his hand, that all the _____ of the earth may know that thou, O LORD, art God alone.\"", "kingdoms", 19, ["kingdoms"]),
    mc(3, "Which word correctly completes this RSV wording: “O LORD our God, save us, I beseech thee, from his hand, that all the _____ of the earth may know that thou, O LORD, art God alone.\"”", ["kingdoms", "cypresses", "sole", "cities"], 19),
    word(1, "In verse 19, what word completes this phrase: “O LORD our God, save us, I beseech thee, from his hand, that all the _____ of the earth may know that thou, O LORD, art God alone.\"”?", "kingdoms", 19, ["kingdoms"]),
    tf(2, "The RSV states: “So now, O LORD our God, save us, I beseech thee, from his hand, that all the kingdoms of the earth may know that thou, O LORD, art God alone.\"”", true, 19),
    blank(3, "saying, \"Thus says the LORD, the God of Israel: Your prayer to me about _____ king of Assyria I have heard.", "Sennach’erib", 20, ["sennacherib"]),
    mc(1, "Which word correctly completes this RSV wording: “saying, \"Thus says the LORD, the God of Israel: Your prayer to me about _____ king of Assyria I have heard.”", ["Sennach’erib", "Tel-assar", "Share’zer", "Jerusalem"], 20),
    word(2, "In verse 20, what word completes this phrase: “saying, \"Thus says the LORD, the God of Israel: Your prayer to me about _____ king of Assyria I have heard.”?", "Sennach’erib", 20, ["sennacherib"]),
    tf(3, "The RSV does not state: “Then Isaiah the son of Amoz sent to Hezeki’ah, saying, \"Thus says the LORD, the God of Israel: Your prayer to me about Sennach’erib king of Assyria I have heard.”", false, 20, "The quoted wording is the RSV text of this verse."),
    blank(1, "virgin daughter of Zion; she wags her head behind you -- the daughter of _____.", "Jerusalem", 21, ["jerusalem"]),
    mc(2, "Which word correctly completes this RSV wording: “virgin daughter of Zion; she wags her head behind you -- the daughter of _____.”", ["Jerusalem", "Gozan", "Incline", "Assyrians"], 21),
    word(3, "In verse 21, what word completes this phrase: “virgin daughter of Zion; she wags her head behind you -- the daughter of _____.”?", "Jerusalem", 21, ["jerusalem"]),
    tf(1, "The RSV states: “This is the word that the LORD has spoken concerning him: \"She despises you, she scorns you -- the virgin daughter of Zion; she wags her head behind you -- the daughter of Jerusalem.”", true, 21),
    blank(2, "\"Whom have you mocked and reviled? _____ whom have you raised your voice and haughtily lifted your eyes? Against", "Against", 22, ["against"]),
    mc(3, "Which word correctly completes this RSV wording: “\"Whom have you mocked and reviled? _____ whom have you raised your voice and haughtily lifted your eyes? Against”", ["Against", "Arpad", "Because", "King"], 22),
    word(1, "In verse 22, what word completes this phrase: “\"Whom have you mocked and reviled? _____ whom have you raised your voice and haughtily lifted your eyes? Against”?", "Against", 22, ["against"]),
    tf(2, "The RSV does not state: “\"Whom have you mocked and reviled? Against whom have you raised your voice and haughtily lifted your eyes? Against the Holy One of Israel!”", false, 22, "The quoted wording is the RSV text of this verse."),
    blank(3, "chariots I have gone up the heights of the mountains, to the far recesses of _____; I felled its tallest cedars, its choicest cypresses; I entered its farthest", "Lebanon", 23, ["lebanon"]),
    mc(1, "Which word correctly completes this RSV wording: “chariots I have gone up the heights of the mountains, to the far recesses of _____; I felled its tallest cedars, its choicest cypresses; I entered its farthest”", ["Lebanon", "Zion", "Adram’melech", "Rab’shakeh"], 23),
    word(2, "In verse 23, what word completes this phrase: “chariots I have gone up the heights of the mountains, to the far recesses of _____; I felled its tallest cedars, its choicest cypresses; I entered its farthest”?", "Lebanon", 23, ["lebanon"]),
    tf(3, "The RSV states: “By your messengers you have mocked the LORD, and you have said, `With my many chariots I have gone up the heights of the mountains, to the far recesses of Lebanon; I felled its tallest cedars, its choicest cypresses; I entered its farthest retreat, its densest forest.”", true, 23),
    blank(1, "foreign waters, and I dried up with the sole of my foot all the streams of _____.’", "Egypt", 24, ["egypt"]),
    mc(2, "Which word correctly completes this RSV wording: “foreign waters, and I dried up with the sole of my foot all the streams of _____.’”", ["Egypt", "Assyria", "Eden", "Lebanon"], 24),
    word(3, "In verse 24, what word completes this phrase: “foreign waters, and I dried up with the sole of my foot all the streams of _____.’”?", "Egypt", 24, ["egypt"]),
    tf(1, "The RSV does not state: “I dug wells and drank foreign waters, and I dried up with the sole of my foot all the streams of Egypt.’”", false, 24, "The quoted wording is the RSV text of this verse."),
    blank(2, "\"Have you not heard that I _____ it long ago? I planned from days of old what now I bring to pass, that", "determined", 25, ["determined"]),
    mc(3, "Which word correctly completes this RSV wording: “\"Have you not heard that I _____ it long ago? I planned from days of old what now I bring to pass, that”", ["determined", "senior", "words", "shall"], 25),
    word(1, "In verse 25, what word completes this phrase: “\"Have you not heard that I _____ it long ago? I planned from days of old what now I bring to pass, that”?", "determined", 25, ["determined"]),
    tf(2, "The RSV states: “\"Have you not heard that I determined it long ago? I planned from days of old what now I bring to pass, that you should turn fortified cities into heaps of ruins,”", true, 25),
    blank(3, "while their _____, shorn of strength, are dismayed and confounded, and have become like", "inhabitants", 26, ["inhabitants"]),
    mc(1, "Which word correctly completes this RSV wording: “while their _____, shorn of strength, are dismayed and confounded, and have become like”", ["inhabitants", "cypresses", "should", "coming"], 26),
    word(2, "In verse 26, what word completes this phrase: “while their _____, shorn of strength, are dismayed and confounded, and have become like”?", "inhabitants", 26, ["inhabitants"]),
    tf(3, "The RSV does not state: “while their inhabitants, shorn of strength, are dismayed and confounded, and have become like plants of the field, and like tender grass, like grass on the housetops; blighted before it is grown?”", false, 26, "The quoted wording is the RSV text of this verse."),
    blank(1, "\"But I know your _____ down and your going out and coming in, and your raging against me.", "sitting", 27, ["sitting"]),
    mc(2, "Which word correctly completes this RSV wording: “\"But I know your _____ down and your going out and coming in, and your raging against me.”", ["sitting", "same", "upward", "sake"], 27),
    word(3, "In verse 27, what word completes this phrase: “\"But I know your _____ down and your going out and coming in, and your raging against me.”?", "sitting", 27, ["sitting"]),
    tf(1, "The RSV states: “\"But I know your sitting down and your going out and coming in, and your raging against me.”", true, 27),
    blank(2, "_____ you have raged against me and your arrogance has come into my ears, I", "Because", 28, ["because"]),
    mc(3, "Which word correctly completes this RSV wording: “_____ you have raged against me and your arrogance has come into my ears, I”", ["Because", "Tel-assar", "Holy", "Ar’arat"], 28),
    word(1, "In verse 28, what word completes this phrase: “_____ you have raged against me and your arrogance has come into my ears, I”?", "Because", 28, ["because"]),
    tf(2, "The RSV does not state: “Because you have raged against me and your arrogance has come into my ears, I will put my hook in your nose and my bit in your mouth, and I will turn you back on the way by which you came.”", false, 28, "The quoted wording is the RSV text of this verse."),
    blank(3, "springs of the same; then in the third year sow, and reap, and plant _____, and eat their fruit.", "vineyards", 29, ["vineyards"]),
    mc(1, "Which word correctly completes this RSV wording: “springs of the same; then in the third year sow, and reap, and plant _____, and eat their fruit.”", ["vineyards", "zeal", "angel", "bodies"], 29),
    word(2, "In verse 29, what word completes this phrase: “springs of the same; then in the third year sow, and reap, and plant _____, and eat their fruit.”?", "vineyards", 29, ["vineyards"]),
    tf(3, "The RSV states: “\"And this shall be the sign for you: this year you shall eat what grows of itself, and in the second year what springs of the same; then in the third year sow, and reap, and plant vineyards, and eat their fruit.”", true, 29),
    blank(1, "And the surviving remnant of the house of _____ shall again take root downward, and bear fruit upward;", "Judah", 30, ["judah"]),
    mc(2, "Which word correctly completes this RSV wording: “And the surviving remnant of the house of _____ shall again take root downward, and bear fruit upward;”", ["Judah", "Libnah", "Arpad", "Mount"], 30),
    word(3, "In verse 30, what word completes this phrase: “And the surviving remnant of the house of _____ shall again take root downward, and bear fruit upward;”?", "Judah", 30, ["judah"]),
    tf(1, "The RSV does not state: “And the surviving remnant of the house of Judah shall again take root downward, and bear fruit upward;”", false, 30, "The quoted wording is the RSV text of this verse."),
    blank(2, "for out of _____ shall go forth a remnant, and out of Mount Zion a band of survivors. The", "Jerusalem", 31, ["jerusalem"]),
    mc(3, "Which word correctly completes this RSV wording: “for out of _____ shall go forth a remnant, and out of Mount Zion a band of survivors. The”", ["Jerusalem", "Share’zer", "Assyria", "Tel-assar"], 31),
    word(1, "In verse 31, what word completes this phrase: “for out of _____ shall go forth a remnant, and out of Mount Zion a band of survivors. The”?", "Jerusalem", 31, ["jerusalem"]),
    tf(2, "The RSV states: “for out of Jerusalem shall go forth a remnant, and out of Mount Zion a band of survivors. The zeal of the LORD will do this.”", true, 31),
    blank(3, "\"_____ thus says the LORD concerning the king of Assyria, He shall not come into", "Therefore", 32, ["therefore"]),
    mc(1, "Which word correctly completes this RSV wording: “\"_____ thus says the LORD concerning the king of Assyria, He shall not come into”", ["Therefore", "Isaiah", "Jerusalem", "Israel"], 32),
    word(2, "In verse 32, what word completes this phrase: “\"_____ thus says the LORD concerning the king of Assyria, He shall not come into”?", "Therefore", 32, ["therefore"]),
    tf(3, "The RSV does not state: “\"Therefore thus says the LORD concerning the king of Assyria, He shall not come into this city or shoot an arrow there, or come before it with a shield or cast up a siege mound against it.”", false, 32, "The quoted wording is the RSV text of this verse."),
    blank(1, "By the way that he came, by the same he shall _____, and he shall not come into this city, says the LORD.", "return", 33, ["return"]),
    mc(2, "Which word correctly completes this RSV wording: “By the way that he came, by the same he shall _____, and he shall not come into this city, says the LORD.”", ["return", "escaped", "sent", "disgrace"], 33),
    word(3, "In verse 33, what word completes this phrase: “By the way that he came, by the same he shall _____, and he shall not come into this city, says the LORD.”?", "return", 33, ["return"]),
    tf(1, "The RSV states: “By the way that he came, by the same he shall return, and he shall not come into this city, says the LORD.”", true, 33),
    blank(2, "this city to save it, for my own sake and for the sake of my servant _____.\"", "David", 34, ["david"]),
    mc(3, "Which word correctly completes this RSV wording: “this city to save it, for my own sake and for the sake of my servant _____.\"”", ["David", "Share’zer", "Behold", "Tel-assar"], 34),
    word(1, "In verse 34, what word completes this phrase: “this city to save it, for my own sake and for the sake of my servant _____.\"”?", "David", 34, ["david"]),
    tf(2, "The RSV does not state: “For I will defend this city to save it, for my own sake and for the sake of my servant David.\"”", false, 34, "The quoted wording is the RSV text of this verse."),
    blank(3, "forth, and slew a hundred and eighty-five thousand in the camp of the _____; and when men arose early in the morning, behold, these were all dead", "Assyrians", 35, ["assyrians"]),
    mc(1, "Which word correctly completes this RSV wording: “forth, and slew a hundred and eighty-five thousand in the camp of the _____; and when men arose early in the morning, behold, these were all dead”", ["Assyrians", "Ivvah", "Therefore", "Shebna"], 35),
    word(2, "In verse 35, what word completes this phrase: “forth, and slew a hundred and eighty-five thousand in the camp of the _____; and when men arose early in the morning, behold, these were all dead”?", "Assyrians", 35, ["assyrians"]),
    tf(3, "The RSV states: “ And that night the angel of the LORD went forth, and slew a hundred and eighty-five thousand in the camp of the Assyrians; and when men arose early in the morning, behold, these were all dead bodies.”", true, 35),
    blank(1, "Then _____ king of Assyria departed, and went home, and dwelt at Nin’eveh.", "Sennach’erib", 36, ["sennacherib"]),
    mc(2, "Which word correctly completes this RSV wording: “Then _____ king of Assyria departed, and went home, and dwelt at Nin’eveh.”", ["Sennach’erib", "Incline", "Esarhad’don", "Jerusalem"], 36),
    word(3, "In verse 36, what word completes this phrase: “Then _____ king of Assyria departed, and went home, and dwelt at Nin’eveh.”?", "Sennach’erib", 36, ["sennacherib"]),
    tf(1, "The RSV does not state: “Then Sennach’erib king of Assyria departed, and went home, and dwelt at Nin’eveh.”", false, 36, "The quoted wording is the RSV text of this verse."),
    blank(2, "And as he was worshiping in the house of Nisroch his god, _____ and Share’zer, his sons, slew him with the sword, and escaped into the", "Adram’melech", 37, ["adrammelech"]),
    mc(3, "Which word correctly completes this RSV wording: “And as he was worshiping in the house of Nisroch his god, _____ and Share’zer, his sons, slew him with the sword, and escaped into the”", ["Adram’melech", "Nin’eveh", "Ethiopia", "Jerusalem"], 37),
    word(1, "In verse 37, what word completes this phrase: “And as he was worshiping in the house of Nisroch his god, _____ and Share’zer, his sons, slew him with the sword, and escaped into the”?", "Adram’melech", 37, ["adrammelech"]),
    tf(2, "The RSV states: “And as he was worshiping in the house of Nisroch his god, Adram’melech and Share’zer, his sons, slew him with the sword, and escaped into the land of Ar’arat. And Esarhad’don his son reigned in his stead.”", true, 37),
    mc(1, "What did Hezekiah do with Sennacherib’s threatening letter?", ["He spread it before the LORD in the temple and prayed", "He burned it before the city elders", "He returned it to the messengers", "He sent it to Isaiah without reading it"], 14),
    mc(3, "Complete the LORD’s image of turning Assyria back: where would He put His hook and bit?", ["Hook in the nose and bit in the mouth", "Hook in the mouth and bit on the tongue", "Hook in the jaw and bit in the nose", "Hook in the ear and bit in the mouth"], 28),
    mc(2, "How many Assyrians did the angel of the LORD strike in the camp?", ["One hundred eighty-five thousand", "Eighty-five thousand", "One hundred twenty thousand", "Seven thousand"], 35),
    mc(3, "How did Sennacherib die?", ["His sons Adrammelech and Sharezer killed him while he worshiped in Nisroch’s house", "He died in the Assyrian camp", "He was killed by Hezekiah’s soldiers", "The angel struck him at Jerusalem"], 37),
  ],
};

export default bank;
