import { mc, blank, word, tf, type ChapterBank, sa } from './types'

const bank: ChapterBank = {
  book: '2 Kings', chapter: 1, tag: 'quiz-v2-2kings-1', rows: [
    mc(1, 'Which nation rebelled after Ahab’s death?', ['Moab', 'Syria', 'Judah', 'Edom'], 1),
    blank(1, 'After the death of Ahab, _____ rebelled against Israel.', 'Moab', 1),
    word(3, 'Against whom did Moab rebel?', 'Israel', 1),
    tf(1, 'Moab remained loyal to Israel after Ahab died.', false, 1, 'Moab rebelled.'),
    mc(2, 'When did Moab rebel against Israel?', ['After Ahab died', 'Before Ahab became king', 'While Elijah was at Carmel', 'After Jehoram died'], 1),
    word(2, 'Whose death preceded Moab’s rebellion?', 'Ahab’s', 1, ['Ahab']),
    tf(3, 'Moab’s rebellion followed the death of Ahab.', true, 1),

    mc(1, 'How was Ahaziah injured?', ['He fell through the lattice of his upper chamber in Samaria', 'He was wounded while leading Israel’s army against Moab', 'He was thrown from his horse while traveling toward Ekron', 'A wall fell upon him while he inspected the defenses of Samaria'], 2),
    blank(3, 'he sent messengers, telling them, “Go, inquire of _____-ze’bub”', 'Ba’al', 2, ['Baal-zebub', 'Baal']),
    word(1, 'Of which city was Baal-zebub the god?', 'Ekron', 2),
    tf(2, 'Ahaziah sent to inquire whether he would recover.', true, 2),
    mc(3, 'What led Ahaziah to send messengers to Baal-zebub of Ekron?', ['He fell through his upper-room lattice in Samaria and wanted to know whether he would recover', 'He was wounded while fighting in Moab and wanted Elijah to heal him', 'He fell while visiting Mount Carmel and sought an answer from the LORD’s temple', 'He became ill in Jerusalem and asked for counsel from his father Ahab'], 2),
    mc(2, 'Where was Ahaziah when he fell through the lattice?', ['In his upper chamber in Samaria', 'In the temple in Jerusalem', 'On Mount Carmel', 'At the gate of Ekron'], 2),
    sa(2, 'What part of the upper chamber did Ahaziah fall through?', 'the lattice', 2, ['lattice']),
    tf(1, 'Baal-zebub was identified as the god of Ekron.', true, 2),

    mc(1, 'Who told Elijah to meet Ahaziah’s messengers?', ['The angel of the LORD', 'Ahab', 'The captain of fifty', 'Jehoram'], 3),
    blank(2, 'Is it because there is no _____ in Israel', 'God', 3),
    sa(2, 'Which prophet was sent?', 'Elijah the Tishbite', 3, ['Elijah']),
    tf(3, 'The messengers were going to inquire of the God of Israel.', false, 3, 'They were going to Baal-zebub of Ekron.'),
    mc(2, 'Where did the angel direct Elijah to meet the messengers?', ['On their way from the king of Samaria', 'Inside the temple at Jerusalem', 'At Ahab’s tomb', 'In the palace at Ekron'], 3),
    sa(3, 'What question exposed the king’s lack of faith?', 'Is it because there is no God in Israel?', 3, ['Is there no God in Israel', 'because there is no God in Israel']),
    tf(1, 'The angel of the LORD sent Elijah to confront the royal messengers.', true, 3),

    mc(1, 'What judgment was announced to Ahaziah?', ['He would not leave his bed but would surely die', 'He would recover in seven days', 'He would lose his kingdom but live', 'He would defeat Moab'], 4),
    blank(3, 'but you shall surely _____.', 'die', 4),
    word(1, 'Who went after receiving the message?', 'Elijah', 4, ["Eli'jah"]),
    tf(2, 'The LORD promised Ahaziah a full recovery.', false, 4, 'He said Ahaziah would surely die.'),
    mc(2, 'Why would Ahaziah not come down from his bed?', ['He had sent to inquire of Baal-zebub', 'Moab had rebelled', 'Elijah refused to visit him', 'His messengers returned too soon'], 4),
    sa(2, 'From what would Ahaziah not come down?', 'the bed to which he had gone', 4, ['his bed', 'the bed']),
    tf(3, 'Elijah delivered the LORD’s judgment that Ahaziah would surely die.', true, 4),

    mc(1, 'What surprised the king about his messengers?', ['They returned early', 'They brought Elijah', 'They had gone to Israel’s God', 'They had been attacked'], 5),
    blank(2, 'Why have you _____?', 'returned', 5),
    sa(2, 'Who questioned the messengers?', 'the king', 5, ['Ahaziah']),
    tf(3, 'The king expected the messengers’ immediate return.', false, 5, 'He asked why they had returned.'),
    mc(2, 'To whom did the messengers return?', ['Ahaziah the king', 'Elijah', 'The god of Ekron', 'The captain of fifty'], 5),
    sa(1, 'What did the king ask them to explain?', 'why they had returned', 5, ['their return', 'why they returned']),
    tf(2, 'The messengers came back to the king before completing the trip to Ekron.', true, 5),

    mc(2, 'What message did the unknown man send back?', ['Ahaziah would not leave his bed but would die', 'Ahaziah would recover', 'Moab would surrender', 'The messengers should continue to Ekron'], 6),
    blank(3, 'Go _____ to the king who sent you', 'back', 6),
    word(1, 'Whom had Ahaziah intended to consult?', 'Baal-zebub', 6, ["Ba'al-ze'bub"]),
    tf(2, 'The messengers continued to Ekron after meeting Elijah.', false, 6, 'They returned to the king with Elijah’s message.'),
    mc(3, 'Why did the messengers say Ahaziah would not recover?', ['He sought Baal-zebub as though there were no God in Israel to inquire of', 'He refused to fight Moab after its rebellion against Israel', 'He dismissed the captains who had been sent to bring Elijah', 'He abandoned Samaria and attempted to move his court to Ekron'], 6),
    sa(2, 'What outcome did the messengers report for Ahaziah?', 'he would surely die', 6, ['surely die', 'death']),
    tf(1, 'The man told the messengers to carry his words back to the king.', true, 6),

    mc(1, 'What did Ahaziah ask about the messenger?', ['What kind of man he was', 'Where he lived', 'How old he was', 'Whether he served Moab'], 7),
    blank(2, 'What _____ of man was he', 'kind', 7),
    sa(2, 'Whom had the man met?', 'Ahaziah’s messengers', 7, ['the messengers']),
    tf(3, 'Ahaziah asked only what words were spoken, not what the man looked like.', false, 7, 'He asked what kind of man he was.'),
    mc(2, 'Why did Ahaziah ask what kind of man had met them?', ['He wanted to identify the bearer of the message', 'He wanted to reward an Ekron priest', 'He needed a new captain', 'He planned to send him to Moab'], 7),
    sa(1, 'What information about the man did the king request?', 'what kind of man he was', 7, ['his appearance', 'a description of him']),
    tf(2, 'The king sought a description of the man who had spoken to the messengers.', true, 7),

    mc(1, 'How was Elijah dressed?', ['A haircloth garment and leather girdle', 'Royal robes and a crown', 'Linen with a golden sash', 'Sackcloth with ropes'], 8),
    blank(3, 'with a girdle of _____ about his loins.', 'leather', 8),
    sa(1, 'Whom did Ahaziah identify?', 'Elijah the Tishbite', 8, ['Elijah']),
    tf(2, 'The description made Ahaziah recognize Elijah.', true, 8),
    mc(3, 'Which description identified Elijah?', ['A garment of haircloth with a leather girdle', 'An iron breastplate with a red cloak', 'A linen robe with a gold belt', 'Sackcloth with ropes on his head'], 8),
    mc(2, 'What did Ahaziah conclude after hearing the man’s appearance?', ['It was Elijah the Tishbite', 'It was a priest of Ekron', 'It was Jehoram', 'It was a Moabite messenger'], 8),
    word(3, 'What material was Elijah’s girdle made from?', 'leather', 8),
    tf(1, 'Elijah’s distinctive clothing helped identify him.', true, 8),

    mc(1, 'Whom did the king first send to Elijah?', ['A captain of fifty with his fifty', 'A single messenger', 'Jehoram', 'A hundred prophets'], 9),
    blank(2, 'who was sitting on the top of a _____.', 'hill', 9),
    sa(2, 'What title did the captain use for Elijah?', 'man of God', 9),
    tf(3, 'Elijah was hiding inside a cave.', false, 9, 'He was sitting on top of a hill.'),
    mc(2, 'Where did the first captain find Elijah?', ['Sitting on top of a hill', 'Standing in Ahaziah’s chamber', 'At the gate of Samaria', 'Walking toward Ekron'], 9),
    sa(1, 'What command from the king did the captain give Elijah?', 'Come down', 9, ['come down from the hill']),
    tf(2, 'The first captain arrived with fifty men.', true, 9),

    mc(1, 'What happened to the first captain and his fifty?', ['Fire from heaven consumed them', 'They arrested Elijah', 'They fled to Samaria', 'A lion killed them'], 10),
    blank(3, 'let _____ come down from heaven and consume you and your fifty.', 'fire', 10),
    word(1, 'How many men accompanied the captain?', 'fifty', 10, ['50']),
    tf(2, 'No fire came after Elijah spoke.', false, 10, 'Fire came down and consumed them.'),
    mc(3, 'How did Elijah answer the first captain’s demand?', ['He called for fire from heaven, which consumed the captain and his fifty', 'He surrendered immediately and went with the company to the king', 'He fled from the hill before the captain’s men could approach him', 'He asked the LORD to send rain so the company would leave the hill'], 10),
    word(2, 'From where did the consuming fire come?', 'heaven', 10, ['from heaven']),
    tf(3, 'The fire consumed both the captain and his fifty men.', true, 10),

    mc(1, 'What did the second captain order Elijah to do?', ['Come down quickly', 'Remain on the hill', 'Go to Ekron', 'Send a message only'], 11),
    blank(2, 'Again the king sent to him _____ captain of fifty men', 'another', 11),
    sa(2, 'Whose order did the second captain cite?', 'the king’s', 11, ['the king']),
    tf(3, 'The second captain approached without an order from Ahaziah.', false, 11, 'He cited the king’s order.'),
    mc(2, 'How did the second captain intensify the command?', ['He ordered Elijah to come down quickly', 'He asked Elijah to wait', 'He offered Elijah protection', 'He knelt and begged'], 11),
    word(1, 'How many men were under the second captain?', 'fifty', 11, ['50']),
    tf(2, 'The king sent another captain after the first company was consumed.', true, 11),

    mc(1, 'What happened to the second company?', ['The fire of God consumed them', 'They persuaded Elijah', 'They begged for mercy', 'They returned safely'], 12),
    blank(3, 'Then the fire of _____ came down from heaven', 'God', 12),
    word(1, 'Who called down the fire?', 'Elijah', 12),
    tf(2, 'The second captain and his fifty survived the fire.', false, 12, 'The fire consumed them.'),
    mc(3, 'What source does the verse give for the second fire?', ['The fire of God came down from heaven', 'The captain lit the hill', 'Lightning came from Ekron', 'The soldiers set a signal fire'], 12),
    sa(2, 'What happened to the second captain’s company?', 'they were consumed', 12, ['fire consumed them', 'consumed by fire']),
    tf(1, 'Elijah again answered by calling down fire.', true, 12),

    mc(1, 'How did the third captain approach Elijah?', ['He fell on his knees and pleaded', 'He commanded more forcefully', 'He attacked at once', 'He stayed with the king'], 13),
    blank(2, 'let my life, and the life of these fifty servants of yours, be _____ in your sight.', 'precious', 13),
    sa(2, 'Which captain showed humility?', 'the third captain', 13, ['third']),
    tf(3, 'The third captain repeated the demand without pleading.', false, 13, 'He knelt and entreated Elijah.'),
    mc(2, 'Whose lives did the third captain ask Elijah to value?', ['His own life and the lives of his fifty servants', 'Only the king’s life', 'The lives of the first two captains', 'Only Elijah’s life'], 13),
    sa(1, 'What did the third captain do before speaking?', 'fell on his knees', 13, ['knelt', 'fell on his knees before Elijah']),

    mc(2, 'What precedent did the third captain mention when pleading for his life?', ['Fire had consumed the first two captains and their groups of fifty', 'A lion had killed the messengers who were traveling toward Ekron', 'Elijah had healed Ahaziah after the king inquired of Israel’s God', 'Moab had defeated Israel after the death of King Ahab'], 14),
    blank(3, 'but now let my life be _____ in your sight.', 'precious', 14),
    word(1, 'How many former captains had been consumed?', 'two', 14, ['2']),
    tf(2, 'The third captain asked that his life be spared.', true, 14),
    mc(3, 'How did the third captain differ from the first two?', ['He knelt and pleaded that his life and his men’s lives be precious', 'He approached Elijah with twice as many soldiers as the earlier captains', 'He refused the king’s order and came only to warn Elijah to escape', 'He called down fire himself before asking Elijah to come with him'], 14),
    mc(1, 'What did the third captain ask concerning his own life?', ['That it be precious in Elijah’s sight', 'That it be exchanged for the king’s', 'That it be tested by fire', 'That it be given to Moab'], 14),
    tf(3, 'The third captain understood what had happened to the two earlier companies.', true, 14),

    mc(1, 'What did the angel tell Elijah about the third captain?', ['Go down with him and do not fear', 'Call down fire again', 'Send him away', 'Hide on the hill'], 15),
    blank(2, 'do not be _____ of him.', 'afraid', 15),
    sa(2, 'To whom did Elijah go?', 'the king', 15, ['Ahaziah']),
    tf(3, 'Elijah refused to accompany the humbled captain.', false, 15, 'He went down with him to the king.'),
    mc(2, 'What reassurance did the angel give Elijah before he went with the captain?', ['Elijah was not to be afraid of him', 'Ahaziah had already recovered from his injuries', 'Moab had surrendered and no longer threatened Israel', 'Fire from heaven could no longer harm either company'], 15),
    tf(1, 'Elijah obeyed the angel and went to the king.', true, 15),

    mc(2, 'Why did Elijah repeat that Ahaziah would not leave his bed?', ['Ahaziah had consulted Baal-zebub instead of inquiring of Israel’s God', 'Ahaziah had attempted to fight Moab after its rebellion against Israel', 'The first two captains had failed to bring Elijah down from the hill', 'Ahab had died and left Ahaziah without anyone to seek counsel from'], 16),
    blank(3, 'therefore you shall not come down from the _____ to which you have gone', 'bed', 16),
    sa(1, 'Whom should Ahaziah have inquired of?', 'the God of Israel', 16, ['God in Israel', 'Israel’s God']),
    tf(2, 'Elijah changed the judgment after meeting Ahaziah.', false, 16, 'He repeated that Ahaziah would surely die.'),
    mc(1, 'What contrast did Elijah make in his message to Ahaziah?', ['The king consulted Baal-zebub instead of inquiring of Israel’s God', 'The king sought help from Judah rather than from his own people in Israel', 'The king sent military captains rather than the messengers who had gone to Ekron', 'The king remained in bed rather than leading Israel against rebellious Moab'], 16),
    tf(3, 'Elijah’s face-to-face message matched the earlier judgment.', true, 16),

    mc(1, 'Who became king after Ahaziah?', ['Jehoram his brother', 'Elijah', 'Moab’s king', 'Ahab'], 17),
    blank(3, 'because Ahazi’ah had no _____.', 'son', 17),
    sa(1, 'Whose word, spoken by Elijah, was fulfilled when Ahaziah died?', 'the LORD’s word', 17, ['the word of the LORD', 'the LORD', 'Elijah’s word']),
    tf(2, 'Ahaziah’s son succeeded him.', false, 17, 'He had no son, so his brother Jehoram became king.'),
    mc(3, 'Why did Jehoram succeed Ahaziah?', ['Ahaziah had no son', 'Elijah appointed him', 'Moab selected him', 'Ahab returned to rule'], 17),
    sa(2, 'In whose reign in Judah did Jehoram begin to rule Israel?', 'Jehoram son of Jehoshaphat', 17, ['Jehoram', 'Jehoram the son of Jehoshaphat']),

    mc(1, 'Where were Ahaziah’s other acts recorded?', ['The Chronicles of the Kings of Israel', 'The Chronicles of Judah', 'The book of Elijah', 'The records of Ekron'], 18),
    blank(2, 'Now the rest of the _____ of Ahazi’ah which he did', 'acts', 18),
    word(2, 'Which kingdom’s chronicles recorded Ahaziah?', 'Israel', 18),
    tf(3, 'The text says Ahaziah’s acts were never recorded.', false, 18, 'They were written in Israel’s royal chronicles.'),
    mc(2, 'What kind of information closes the account of Ahaziah?', ['A reference to the record of his other acts', 'A list of his sons', 'A report of victory over Moab', 'A hymn written by Elijah'], 18),
    sa(1, 'What record contained the rest of Ahaziah’s deeds?', 'the Book of the Chronicles of the Kings of Israel', 18, ['Chronicles of the Kings of Israel', 'the chronicles of Israel’s kings']),
  ],
}

export default bank
