// 2 Kings 2 — quiz bank (RSV). Four verse-anchored forms per verse.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: "2 Kings",
  chapter: 2,
  tag: "quiz-v2-2kings-2",
  rows: [
    blank(2, "Now when the LORD was about to take _____ up to heaven by a whirlwind, Eli’jah and Eli’sha were on their way from", "Eli’jah", 1, ["elijah"]),
    mc(3, "Which word correctly completes this RSV wording: “Now when the LORD was about to take _____ up to heaven by a whirlwind, Eli’jah and Eli’sha were on their way from”", ["Eli’jah", "Israel", "Tarry", "Mount"], 1),
    word(1, "In verse 1, what word completes this phrase: “Now when the LORD was about to take _____ up to heaven by a whirlwind, Eli’jah and Eli’sha were on their way from”?", "Eli’jah", 1, ["elijah"]),
    tf(2, "The RSV states: “Now when the LORD was about to take Eli’jah up to heaven by a whirlwind, Eli’jah and Eli’sha were on their way from Gilgal.”", true, 1),
    blank(3, "And _____ said to Eli’sha, \"Tarry here, I pray you; for the LORD has sent me as", "Eli’jah", 2, ["elijah"]),
    mc(1, "Which word correctly completes this RSV wording: “And _____ said to Eli’sha, \"Tarry here, I pray you; for the LORD has sent me as”", ["Eli’jah", "Carmel", "Spirit", "Jericho"], 2),
    word(2, "In verse 2, what word completes this phrase: “And _____ said to Eli’sha, \"Tarry here, I pray you; for the LORD has sent me as”?", "Eli’jah", 2, ["elijah"]),
    tf(3, "The RSV does not state: “And Eli’jah said to Eli’sha, \"Tarry here, I pray you; for the LORD has sent me as far as Bethel.\" But Eli’sha said, \"As the LORD lives, and as you yourself live, I will not leave you.\" So they went down to Bethel.”", false, 2, "The quoted wording is the RSV text of this verse."),
    blank(1, "And the sons of the prophets who were in Bethel came out to _____, and said to him, \"Do you know that today the LORD will take away your", "Eli’sha", 3, ["elisha"]),
    mc(2, "Which word correctly completes this RSV wording: “And the sons of the prophets who were in Bethel came out to _____, and said to him, \"Do you know that today the LORD will take away your”", ["Eli’sha", "Jordan", "Eli’jah", "Bring"], 3),
    word(3, "In verse 3, what word completes this phrase: “And the sons of the prophets who were in Bethel came out to _____, and said to him, \"Do you know that today the LORD will take away your”?", "Eli’sha", 3, ["elisha"]),
    tf(1, "The RSV states: “And the sons of the prophets who were in Bethel came out to Eli’sha, and said to him, \"Do you know that today the LORD will take away your master from over you?\" And he said, \"Yes, I know it; hold your peace.\"”", true, 3),
    blank(2, "_____ said to him, \"Eli’sha, tarry here, I pray you; for the LORD has sent me", "Eli’jah", 4, ["elijah"]),
    mc(3, "Which word correctly completes this RSV wording: “_____ said to him, \"Eli’sha, tarry here, I pray you; for the LORD has sent me”", ["Eli’jah", "Thus", "Israel", "Tarry"], 4),
    word(1, "In verse 4, what word completes this phrase: “_____ said to him, \"Eli’sha, tarry here, I pray you; for the LORD has sent me”?", "Eli’jah", 4, ["elijah"]),
    tf(2, "The RSV does not state: “Eli’jah said to him, \"Eli’sha, tarry here, I pray you; for the LORD has sent me to Jericho.\" But he said, \"As the LORD lives, and as you yourself live, I will not leave you.\" So they came to Jericho.”", false, 4, "The quoted wording is the RSV text of this verse."),
    blank(3, "The sons of the prophets who were at _____ drew near to Eli’sha, and said to him, \"Do you know that today the LORD", "Jericho", 5, ["jericho"]),
    mc(1, "Which word correctly completes this RSV wording: “The sons of the prophets who were at _____ drew near to Eli’sha, and said to him, \"Do you know that today the LORD”", ["Jericho", "Tarry", "Carmel", "Spirit"], 5),
    word(2, "In verse 5, what word completes this phrase: “The sons of the prophets who were at _____ drew near to Eli’sha, and said to him, \"Do you know that today the LORD”?", "Jericho", 5, ["jericho"]),
    tf(3, "The RSV states: “The sons of the prophets who were at Jericho drew near to Eli’sha, and said to him, \"Do you know that today the LORD will take away your master from over you?\" And he answered, \"Yes, I know it; hold your peace.\"”", true, 5),
    blank(1, "Then _____ said to him, \"Tarry here, I pray you; for the LORD has sent me to the", "Eli’jah", 6, ["elijah"]),
    mc(2, "Which word correctly completes this RSV wording: “Then _____ said to him, \"Tarry here, I pray you; for the LORD has sent me to the”", ["Eli’jah", "Send", "Jordan", "Eli’sha"], 6),
    word(3, "In verse 6, what word completes this phrase: “Then _____ said to him, \"Tarry here, I pray you; for the LORD has sent me to the”?", "Eli’jah", 6, ["elijah"]),
    tf(1, "The RSV does not state: “Then Eli’jah said to him, \"Tarry here, I pray you; for the LORD has sent me to the Jordan.\" But he said, \"As the LORD lives, and as you yourself live, I will not leave you.\" So the two of them went on.”", false, 6, "The quoted wording is the RSV text of this verse."),
    blank(2, "and stood at some distance from them, as they both were standing by the _____.", "Jordan", 7, ["jordan"]),
    mc(3, "Which word correctly completes this RSV wording: “and stood at some distance from them, as they both were standing by the _____.”", ["Jordan", "Eli’sha", "Thus", "Israel"], 7),
    word(1, "In verse 7, what word completes this phrase: “and stood at some distance from them, as they both were standing by the _____.”?", "Jordan", 7, ["jordan"]),
    tf(2, "The RSV states: “Fifty men of the sons of the prophets also went, and stood at some distance from them, as they both were standing by the Jordan.”", true, 7),
    blank(3, "Then _____ took his mantle, and rolled it up, and struck the water, and the water", "Eli’jah", 8, ["elijah"]),
    mc(1, "Which word correctly completes this RSV wording: “Then _____ took his mantle, and rolled it up, and struck the water, and the water”", ["Eli’jah", "Behold", "Bethel", "Carmel"], 8),
    word(2, "In verse 8, what word completes this phrase: “Then _____ took his mantle, and rolled it up, and struck the water, and the water”?", "Eli’jah", 8, ["elijah"]),
    tf(3, "The RSV does not state: “Then Eli’jah took his mantle, and rolled it up, and struck the water, and the water was parted to the one side and to the other, till the two of them could go over on dry ground.”", false, 8, "The quoted wording is the RSV text of this verse."),
    blank(1, "When they had crossed, _____ said to Eli’sha, \"Ask what I shall do for you, before I am taken from", "Eli’jah", 9, ["elijah"]),
    mc(2, "Which word correctly completes this RSV wording: “When they had crossed, _____ said to Eli’sha, \"Ask what I shall do for you, before I am taken from”", ["Eli’jah", "Sama’ria", "Send", "Jordan"], 9),
    word(3, "In verse 9, what word completes this phrase: “When they had crossed, _____ said to Eli’sha, \"Ask what I shall do for you, before I am taken from”?", "Eli’jah", 9, ["elijah"]),
    tf(1, "The RSV states: “When they had crossed, Eli’jah said to Eli’sha, \"Ask what I shall do for you, before I am taken from you.\" And Eli’sha said, \"I pray you, let me inherit a double share of your spirit.\"”", true, 9),
    blank(2, "And he said, \"You have _____ a hard thing; yet, if you see me as I am being taken from you, it shall", "asked", 10, ["asked"]),
    mc(3, "Which word correctly completes this RSV wording: “And he said, \"You have _____ a hard thing; yet, if you see me as I am being taken from you, it shall”", ["asked", "fallen", "seek", "sought"], 10),
    word(1, "In verse 10, what word completes this phrase: “And he said, \"You have _____ a hard thing; yet, if you see me as I am being taken from you, it shall”?", "asked", 10, ["asked"]),
    tf(2, "The RSV does not state: “And he said, \"You have asked a hard thing; yet, if you see me as I am being taken from you, it shall be so for you; but if you do not see me, it shall not be so.\"”", false, 10, "The quoted wording is the RSV text of this verse."),
    blank(3, "behold, a chariot of fire and horses of fire separated the two of them. And _____ went up by a whirlwind into heaven.", "Eli’jah", 11, ["elijah"]),
    mc(1, "Which word correctly completes this RSV wording: “behold, a chariot of fire and horses of fire separated the two of them. And _____ went up by a whirlwind into heaven.”", ["Eli’jah", "Mount", "Behold", "Bethel"], 11),
    word(2, "In verse 11, what word completes this phrase: “behold, a chariot of fire and horses of fire separated the two of them. And _____ went up by a whirlwind into heaven.”?", "Eli’jah", 11, ["elijah"]),
    tf(3, "The RSV states: “And as they still went on and talked, behold, a chariot of fire and horses of fire separated the two of them. And Eli’jah went up by a whirlwind into heaven.”", true, 11),
    blank(1, "And _____ saw it and he cried, \"My father, my father! the chariots of Israel and", "Eli’sha", 12, ["elisha"]),
    mc(2, "Which word correctly completes this RSV wording: “And _____ saw it and he cried, \"My father, my father! the chariots of Israel and”", ["Eli’sha", "Jericho", "Sama’ria", "Send"], 12),
    word(3, "In verse 12, what word completes this phrase: “And _____ saw it and he cried, \"My father, my father! the chariots of Israel and”?", "Eli’sha", 12, ["elisha"]),
    tf(1, "The RSV does not state: “And Eli’sha saw it and he cried, \"My father, my father! the chariots of Israel and its horsemen!\" And he saw him no more. Then he took hold of his own clothes and rent them in two pieces.”", false, 12, "The quoted wording is the RSV text of this verse."),
    blank(2, "And he took up the mantle of _____ that had fallen from him, and went back and stood on the bank of the Jordan.", "Eli’jah", 13, ["elijah"]),
    mc(3, "Which word correctly completes this RSV wording: “And he took up the mantle of _____ that had fallen from him, and went back and stood on the bank of the Jordan.”", ["Eli’jah", "Bring", "Fifty", "Gilgal"], 13),
    word(1, "In verse 13, what word completes this phrase: “And he took up the mantle of _____ that had fallen from him, and went back and stood on the bank of the Jordan.”?", "Eli’jah", 13, ["elijah"]),
    tf(2, "The RSV states: “And he took up the mantle of Eli’jah that had fallen from him, and went back and stood on the bank of the Jordan.”", true, 13),
    blank(3, "Then he took the mantle of _____ that had fallen from him, and struck the water, saying, \"Where is the", "Eli’jah", 14, ["elijah"]),
    mc(1, "Which word correctly completes this RSV wording: “Then he took the mantle of _____ that had fallen from him, and struck the water, saying, \"Where is the”", ["Eli’jah", "Tarry", "Mount", "Behold"], 14),
    word(2, "In verse 14, what word completes this phrase: “Then he took the mantle of _____ that had fallen from him, and struck the water, saying, \"Where is the”?", "Eli’jah", 14, ["elijah"]),
    tf(3, "The RSV does not state: “Then he took the mantle of Eli’jah that had fallen from him, and struck the water, saying, \"Where is the LORD, the God of Eli’jah?\" And when he had struck the water, the water was parted to the one side and to the other; and Eli’sha went over.”", false, 14, "The quoted wording is the RSV text of this verse."),
    blank(1, "Now when the sons of the prophets who were at _____ saw him over against them, they said, \"The spirit of Eli’jah rests on", "Jericho", 15, ["jericho"]),
    mc(2, "Which word correctly completes this RSV wording: “Now when the sons of the prophets who were at _____ saw him over against them, they said, \"The spirit of Eli’jah rests on”", ["Jericho", "Spirit", "Bethel", "Sama’ria"], 15),
    word(3, "In verse 15, what word completes this phrase: “Now when the sons of the prophets who were at _____ saw him over against them, they said, \"The spirit of Eli’jah rests on”?", "Jericho", 15, ["jericho"]),
    tf(1, "The RSV states: “Now when the sons of the prophets who were at Jericho saw him over against them, they said, \"The spirit of Eli’jah rests on Eli’sha.\" And they came to meet him, and bowed to the ground before him.”", true, 15),
    blank(2, "And they said to him, \"_____ now, there are with your servants fifty strong men; pray, let them go,", "Behold", 16, ["behold"]),
    mc(3, "Which word correctly completes this RSV wording: “And they said to him, \"_____ now, there are with your servants fifty strong men; pray, let them go,”", ["Behold", "Eli’jah", "Bring", "Jordan"], 16),
    word(1, "In verse 16, what word completes this phrase: “And they said to him, \"_____ now, there are with your servants fifty strong men; pray, let them go,”?", "Behold", 16, ["behold"]),
    tf(2, "The RSV does not state: “And they said to him, \"Behold now, there are with your servants fifty strong men; pray, let them go, and seek your master; it may be that the Spirit of the LORD has caught him up and cast him upon some mountain or into some valley.\" And he said, \"You shall not send.\"”", false, 16, "The quoted wording is the RSV text of this verse."),
    blank(3, "But when they urged him till he was ashamed, he said, \"_____.\" They sent therefore fifty men; and for three days they sought him but", "Send", 17, ["send"]),
    mc(1, "Which word correctly completes this RSV wording: “But when they urged him till he was ashamed, he said, \"_____.\" They sent therefore fifty men; and for three days they sought him but”", ["Send", "Fifty", "Gilgal", "Mount"], 17),
    word(2, "In verse 17, what word completes this phrase: “But when they urged him till he was ashamed, he said, \"_____.\" They sent therefore fifty men; and for three days they sought him but”?", "Send", 17, ["send"]),
    tf(3, "The RSV states: “But when they urged him till he was ashamed, he said, \"Send.\" They sent therefore fifty men; and for three days they sought him but did not find him.”", true, 17),
    blank(1, "And they came back to him, while he tarried at _____, and he said to them, \"Did I not say to you, Do not go?\"", "Jericho", 18, ["jericho"]),
    mc(2, "Which word correctly completes this RSV wording: “And they came back to him, while he tarried at _____, and he said to them, \"Did I not say to you, Do not go?\"”", ["Jericho", "Carmel", "Spirit", "Bethel"], 18),
    word(3, "In verse 18, what word completes this phrase: “And they came back to him, while he tarried at _____, and he said to them, \"Did I not say to you, Do not go?\"”?", "Jericho", 18, ["jericho"]),
    tf(1, "The RSV does not state: “And they came back to him, while he tarried at Jericho, and he said to them, \"Did I not say to you, Do not go?\"”", false, 18, "The quoted wording is the RSV text of this verse."),
    blank(2, "Now the men of the city said to _____, \"Behold, the situation of this city is pleasant, as my lord sees; but", "Eli’sha", 19, ["elisha"]),
    mc(3, "Which word correctly completes this RSV wording: “Now the men of the city said to _____, \"Behold, the situation of this city is pleasant, as my lord sees; but”", ["Eli’sha", "Jordan", "Eli’jah", "Bring"], 19),
    word(1, "In verse 19, what word completes this phrase: “Now the men of the city said to _____, \"Behold, the situation of this city is pleasant, as my lord sees; but”?", "Eli’sha", 19, ["elisha"]),
    tf(2, "The RSV states: “Now the men of the city said to Eli’sha, \"Behold, the situation of this city is pleasant, as my lord sees; but the water is bad, and the land is unfruitful.\"”", true, 19),
    blank(3, "He said, \"_____ me a new bowl, and put salt in it.\" So they brought it to him.", "Bring", 20, ["bring"]),
    mc(1, "Which word correctly completes this RSV wording: “He said, \"_____ me a new bowl, and put salt in it.\" So they brought it to him.”", ["Bring", "Thus", "Fifty", "Gilgal"], 20),
    word(2, "In verse 20, what word completes this phrase: “He said, \"_____ me a new bowl, and put salt in it.\" So they brought it to him.”?", "Bring", 20, ["bring"]),
    tf(3, "The RSV does not state: “He said, \"Bring me a new bowl, and put salt in it.\" So they brought it to him.”", false, 20, "The quoted wording is the RSV text of this verse."),
    blank(1, "Then he went to the spring of water and threw salt in it, and said, \"_____ says the LORD, I have made this water wholesome; henceforth neither death", "Thus", 21, ["thus"]),
    mc(2, "Which word correctly completes this RSV wording: “Then he went to the spring of water and threw salt in it, and said, \"_____ says the LORD, I have made this water wholesome; henceforth neither death”", ["Thus", "Tarry", "Carmel", "Behold"], 21),
    word(3, "In verse 21, what word completes this phrase: “Then he went to the spring of water and threw salt in it, and said, \"_____ says the LORD, I have made this water wholesome; henceforth neither death”?", "Thus", 21, ["thus"]),
    tf(1, "The RSV states: “Then he went to the spring of water and threw salt in it, and said, \"Thus says the LORD, I have made this water wholesome; henceforth neither death nor miscarriage shall come from it.\"”", true, 21),
    blank(2, "the water has been wholesome to this day, according to the word which _____ spoke.", "Eli’sha", 22, ["elisha"]),
    mc(3, "Which word correctly completes this RSV wording: “the water has been wholesome to this day, according to the word which _____ spoke.”", ["Eli’sha", "Send", "Jordan", "Eli’jah"], 22),
    word(1, "In verse 22, what word completes this phrase: “the water has been wholesome to this day, according to the word which _____ spoke.”?", "Eli’sha", 22, ["elisha"]),
    tf(2, "The RSV does not state: “So the water has been wholesome to this day, according to the word which Eli’sha spoke.”", false, 22, "The quoted wording is the RSV text of this verse."),
    blank(3, "He went up from there to _____; and while he was going up on the way, some small boys came out of the", "Bethel", 23, ["bethel"]),
    mc(1, "Which word correctly completes this RSV wording: “He went up from there to _____; and while he was going up on the way, some small boys came out of the”", ["Bethel", "Eli’sha", "Thus", "Israel"], 23),
    word(2, "In verse 23, what word completes this phrase: “He went up from there to _____; and while he was going up on the way, some small boys came out of the”?", "Bethel", 23, ["bethel"]),
    tf(3, "The RSV states: “He went up from there to Bethel; and while he was going up on the way, some small boys came out of the city and jeered at him, saying, \"Go up, you baldhead! Go up, you baldhead!\"”", true, 23),
    blank(1, "and when he saw them, he cursed them in the name of the LORD. And two _____ came out of the woods and tore forty-two of the boys.", "she-bears", 24, ["she-bears"]),
    mc(2, "Which word correctly completes this RSV wording: “and when he saw them, he cursed them in the name of the LORD. And two _____ came out of the woods and tore forty-two of the boys.”", ["she-bears", "rolled", "before", "behold"], 24),
    word(3, "In verse 24, what word completes this phrase: “and when he saw them, he cursed them in the name of the LORD. And two _____ came out of the woods and tore forty-two of the boys.”?", "she-bears", 24, ["she-bears"]),
    tf(1, "The RSV does not state: “And he turned around, and when he saw them, he cursed them in the name of the LORD. And two she-bears came out of the woods and tore forty-two of the boys.”", false, 24, "The quoted wording is the RSV text of this verse."),
    blank(2, "From there he went on to Mount Carmel, and thence he returned to _____.", "Sama’ria", 25, ["samaria"]),
    mc(3, "Which word correctly completes this RSV wording: “From there he went on to Mount Carmel, and thence he returned to _____.”", ["Sama’ria", "Carmel", "Spirit", "Jericho"], 25),
    word(1, "In verse 25, what word completes this phrase: “From there he went on to Mount Carmel, and thence he returned to _____.”?", "Sama’ria", 25, ["samaria"]),
    tf(2, "The RSV states: “From there he went on to Mount Carmel, and thence he returned to Sama’ria.”", true, 25),
    blank(1, "Now when the LORD was about to take Eli’jah up to heaven by a _____, Eli’jah and Eli’sha were on their way from Gilgal.", "whirlwind", 1, ["whirlwind"]),
    mc(2, "Select the missing RSV word: “me as far as Bethel.\" But Eli’sha said, \"As the LORD lives, and as you _____ live, I will not leave you.\" So they went down to Bethel.”", ["yourself", "stood", "side", "share"], 2),
    word(3, "What missing word belongs in this verse 3 clause: “And the sons of the _____ who were in Bethel came out to Eli’sha, and said to him, \"Do you know”?", "prophets", 3, ["prophets"]),
    tf(1, "This wording appears in verse 4: “has sent me to Jericho.\" But he said, \"As the LORD lives, and as you yourself live, I will not leave you.\" So they came to Jericho.”", true, 4),
    blank(2, "The sons of the _____ who were at Jericho drew near to Eli’sha, and said to him, \"Do you know", "prophets", 5, ["prophets"]),
    mc(3, "Select the missing RSV word: “has sent me to the Jordan.\" But he said, \"As the LORD lives, and as you _____ live, I will not leave you.\" So the two of them went on.”", ["yourself", "mountain", "city", "says"], 6),
    word(1, "What missing word belongs in this verse 7 clause: “Fifty men of the sons of the _____ also went, and stood at some distance from them, as they both were standing”?", "prophets", 7, ["prophets"]),
    tf(2, "This wording appears in verse 8: “Then Eli’jah took his mantle, and rolled it up, and struck the water, and the water was parted to the”", true, 8),
    blank(3, "When they had _____, Eli’jah said to Eli’sha, \"Ask what I shall do for you, before I am taken", "crossed", 9, ["crossed"]),
    mc(1, "Select the missing RSV word: “And he said, \"You have asked a hard _____; yet, if you see me as I am being taken from you, it shall be so for you;”", ["thing", "yourself", "master", "distance"], 10),
    word(2, "What missing word belongs in this verse 11 clause: “still went on and talked, behold, a chariot of fire and horses of fire _____ the two of them. And Eli’jah went up by a whirlwind into heaven.”?", "separated", 11, ["separated"]),
    tf(3, "This wording appears in verse 12: “And Eli’sha saw it and he cried, \"My father, my father! the chariots of Israel and its horsemen!\" And he saw him no more. Then he took hold”", true, 12),
    blank(1, "And he took up the _____ of Eli’jah that had fallen from him, and went back and stood on the bank", "mantle", 13, ["mantle"]),
    mc(2, "Select the missing RSV word: “the water, the water was parted to the one side and to the other; and _____ went over.”", ["Eli’sha", "Jericho", "Sama’ria", "Send"], 14),
    word(3, "What missing word belongs in this verse 15 clause: “Now when the sons of the _____ who were at Jericho saw him over against them, they said, \"The spirit”?", "prophets", 15, ["prophets"]),
    tf(1, "This wording appears in verse 16: “And they said to him, \"Behold now, there are with your servants fifty strong men; pray, let them go, and seek your master; it may be that”", true, 16),
    blank(2, "But when they urged him till he was ashamed, he said, \"Send.\" They sent _____ fifty men; and for three days they sought him but did not find him.", "therefore", 17, ["therefore"]),
    mc(3, "Select the missing RSV word: “And they came back to him, while he _____ at Jericho, and he said to them, \"Did I not say to you, Do not go?\"”", ["tarried", "jeered", "returned", "live"], 18),
    word(1, "What missing word belongs in this verse 19 clause: “city is pleasant, as my lord sees; but the water is bad, and the land is _____.\"”?", "unfruitful", 19, ["unfruitful"]),
    tf(2, "This wording appears in verse 20: “He said, \"Bring me a new bowl, and put salt in it.\" So they brought it to him.”", true, 20),
    mc(1, "What did Elisha ask Elijah to give him before Elijah was taken away?", ["A double share of Elijah’s spirit", "Elijah’s staff", "Authority over the prophets", "A sign from heaven"], 9),
    mc(2, "How was Elijah taken up into heaven?", ["A chariot and horses of fire separated them, and Elijah went up in a whirlwind", "An angel carried him from Mount Carmel", "A cloud covered him at Bethel", "He ascended in a pillar of fire from Jericho"], 11),
    mc(2, "What did Elisha say when he struck the Jordan with Elijah’s mantle?", ["Where is the LORD, the God of Elijah?", "Let the waters be divided", "The spirit of Elijah rests on me", "Open a path for the prophets"], 14),
    mc(3, "How did Elisha heal Jericho’s bad water?", ["He threw salt from a new bowl into the spring and declared it wholesome", "He struck the spring with Elijah’s mantle", "He poured oil into the water", "He prayed for rain over the city"], 21),
    mc(3, "What happened after the boys jeered at Elisha as a baldhead?", ["He cursed them in the LORD’s name, and two she-bears tore forty-two of them", "Fire came down and consumed them", "They were driven from Bethel", "The sons of the prophets arrested them"], 24),
  ],
};

export default bank;
