// 2 Kings 9 — quiz bank (RSV). Four verse-anchored forms per verse.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: "2 Kings",
  chapter: 9,
  tag: "quiz-v2-2kings-9",
  rows: [
    blank(2, "\"Gird up your loins, and take this flask of oil in your hand, and go to _____.", "Ramoth-gilead", 1, ["ramoth-gilead"]),
    mc(3, "Which word correctly completes this RSV wording: “\"Gird up your loins, and take this flask of oil in your hand, and go to _____.”", ["Ramoth-gilead", "Megid’do", "Jerusalem", "Tishbite"], 1),
    word(1, "In verse 1, what word completes this phrase: “\"Gird up your loins, and take this flask of oil in your hand, and go to _____.”?", "Ramoth-gilead", 1, ["ramoth-gilead"]),
    tf(2, "The RSV states: “Then Eli’sha the prophet called one of the sons of the prophets and said to him, \"Gird up your loins, and take this flask of oil in your hand, and go to Ramoth-gilead.”", true, 1),
    blank(3, "And when you arrive, look there for Jehu the son of _____, son of Nimshi; and go in and bid him rise from among his fellows, and", "Jehosh’aphat", 2, ["jehoshaphat"]),
    mc(1, "Which word correctly completes this RSV wording: “And when you arrive, look there for Jehu the son of _____, son of Nimshi; and go in and bid him rise from among his fellows, and”", ["Jehosh’aphat", "Jerusalem", "Syrians", "Jez’ebel"], 2),
    word(2, "In verse 2, what word completes this phrase: “And when you arrive, look there for Jehu the son of _____, son of Nimshi; and go in and bid him rise from among his fellows, and”?", "Jehosh’aphat", 2, ["jehoshaphat"]),
    tf(3, "The RSV does not state: “And when you arrive, look there for Jehu the son of Jehosh’aphat, son of Nimshi; and go in and bid him rise from among his fellows, and lead him to an inner chamber.”", false, 2, "The quoted wording is the RSV text of this verse."),
    blank(1, "it on his head, and say, `Thus says the LORD, I anoint you king over _____.’ Then open the door and flee; do not tarry.\"", "Israel", 3, ["israel"]),
    mc(2, "Which word correctly completes this RSV wording: “it on his head, and say, `Thus says the LORD, I anoint you king over _____.’ Then open the door and flee; do not tarry.\"”", ["Israel", "Again", "David", "Jez’ebel"], 3),
    word(3, "In verse 3, what word completes this phrase: “it on his head, and say, `Thus says the LORD, I anoint you king over _____.’ Then open the door and flee; do not tarry.\"”?", "Israel", 3, ["israel"]),
    tf(1, "The RSV states: “Then take the flask of oil, and pour it on his head, and say, `Thus says the LORD, I anoint you king over Israel.’ Then open the door and flee; do not tarry.\"”", true, 3),
    blank(2, "So the young man, the prophet, went to _____.", "Ramoth-gilead", 4, ["ramoth-gilead"]),
    mc(3, "Which word correctly completes this RSV wording: “So the young man, the prophet, went to _____.”", ["Ramoth-gilead", "Jerusalem", "Tishbite", "Jehosh’aphat"], 4),
    word(1, "In verse 4, what word completes this phrase: “So the young man, the prophet, went to _____.”?", "Ramoth-gilead", 4, ["ramoth-gilead"]),
    tf(2, "The RSV does not state: “So the young man, the prophet, went to Ramoth-gilead.”", false, 4, "The quoted wording is the RSV text of this verse."),
    blank(3, "in council; and he said, \"I have an errand to you, O commander.\" And _____ said, \"To which of us all?\" And he said, \"To you, O commander.\"", "Jehu", 5, ["jehu"]),
    mc(1, "Which word correctly completes this RSV wording: “in council; and he said, \"I have an errand to you, O commander.\" And _____ said, \"To which of us all?\" And he said, \"To you, O commander.\"”", ["Jehu", "Eli’sha", "Jezreel", "Make"], 5),
    word(2, "In verse 5, what word completes this phrase: “in council; and he said, \"I have an errand to you, O commander.\" And _____ said, \"To which of us all?\" And he said, \"To you, O commander.\"”?", "Jehu", 5, ["jehu"]),
    tf(3, "The RSV states: “And when he came, behold, the commanders of the army were in council; and he said, \"I have an errand to you, O commander.\" And Jehu said, \"To which of us all?\" And he said, \"To you, O commander.\"”", true, 5),
    blank(1, "poured the oil on his head, saying to him, \"Thus says the LORD the God of _____, I anoint you king over the people of the LORD, over Israel.", "Israel", 6, ["israel"]),
    mc(2, "Which word correctly completes this RSV wording: “poured the oil on his head, saying to him, \"Thus says the LORD the God of _____, I anoint you king over the people of the LORD, over Israel.”", ["Israel", "Ahab", "Syrians", "Beth-haggan"], 6),
    word(3, "In verse 6, what word completes this phrase: “poured the oil on his head, saying to him, \"Thus says the LORD the God of _____, I anoint you king over the people of the LORD, over Israel.”?", "Israel", 6, ["israel"]),
    tf(1, "The RSV does not state: “So he arose, and went into the house; and the young man poured the oil on his head, saying to him, \"Thus says the LORD the God of Israel, I anoint you king over the people of the LORD, over Israel.”", false, 6, "The quoted wording is the RSV text of this verse."),
    blank(2, "shall strike down the house of Ahab your master, that I may avenge on _____ the blood of my servants the prophets, and the blood of all the servants", "Jez’ebel", 7, ["jezebel"]),
    mc(3, "Which word correctly completes this RSV wording: “shall strike down the house of Ahab your master, that I may avenge on _____ the blood of my servants the prophets, and the blood of all the servants”", ["Jez’ebel", "Nebat", "Take", "Megid’do"], 7),
    word(1, "In verse 7, what word completes this phrase: “shall strike down the house of Ahab your master, that I may avenge on _____ the blood of my servants the prophets, and the blood of all the servants”?", "Jez’ebel", 7, ["jezebel"]),
    tf(2, "The RSV states: “And you shall strike down the house of Ahab your master, that I may avenge on Jez’ebel the blood of my servants the prophets, and the blood of all the servants of the LORD.”", true, 7),
    blank(3, "shall perish; and I will cut off from Ahab every male, bond or free, in _____.", "Israel", 8, ["israel"]),
    mc(1, "Which word correctly completes this RSV wording: “shall perish; and I will cut off from Ahab every male, bond or free, in _____.”", ["Israel", "Take", "Megid’do", "Thus"], 8),
    word(2, "In verse 8, what word completes this phrase: “shall perish; and I will cut off from Ahab every male, bond or free, in _____.”?", "Israel", 8, ["israel"]),
    tf(3, "The RSV does not state: “For the whole house of Ahab shall perish; and I will cut off from Ahab every male, bond or free, in Israel.”", false, 8, "The quoted wording is the RSV text of this verse."),
    blank(1, "And I will make the house of Ahab like the house of _____ the son of Nebat, and like the house of Ba’asha the son of Ahi’jah.", "Jerobo’am", 9, ["jeroboam"]),
    mc(2, "Which word correctly completes this RSV wording: “And I will make the house of Ahab like the house of _____ the son of Nebat, and like the house of Ba’asha the son of Ahi’jah.”", ["Jerobo’am", "Make", "Zimri", "Israel"], 9),
    word(3, "In verse 9, what word completes this phrase: “And I will make the house of Ahab like the house of _____ the son of Nebat, and like the house of Ba’asha the son of Ahi’jah.”?", "Jerobo’am", 9, ["jeroboam"]),
    tf(1, "The RSV states: “And I will make the house of Ahab like the house of Jerobo’am the son of Nebat, and like the house of Ba’asha the son of Ahi’jah.”", true, 9),
    blank(2, "And the dogs shall eat _____ in the territory of Jezreel, and none shall bury her.\" Then he opened", "Jez’ebel", 10, ["jezebel"]),
    mc(3, "Which word correctly completes this RSV wording: “And the dogs shall eat _____ in the territory of Jezreel, and none shall bury her.\" Then he opened”", ["Jez’ebel", "Ibleam", "Jehu", "Joram"], 10),
    word(1, "In verse 10, what word completes this phrase: “And the dogs shall eat _____ in the territory of Jezreel, and none shall bury her.\" Then he opened”?", "Jez’ebel", 10, ["jezebel"]),
    tf(2, "The RSV does not state: “And the dogs shall eat Jez’ebel in the territory of Jezreel, and none shall bury her.\" Then he opened the door, and fled.”", false, 10, "The quoted wording is the RSV text of this verse."),
    blank(3, "When _____ came out to the servants of his master, they said to him, \"Is all well?", "Jehu", 11, ["jehu"]),
    mc(1, "Which word correctly completes this RSV wording: “When _____ came out to the servants of his master, they said to him, \"Is all well?”", ["Jehu", "Jerobo’am", "Judah", "Jerusalem"], 11),
    word(2, "In verse 11, what word completes this phrase: “When _____ came out to the servants of his master, they said to him, \"Is all well?”?", "Jehu", 11, ["jehu"]),
    tf(3, "The RSV states: “When Jehu came out to the servants of his master, they said to him, \"Is all well? Why did this mad fellow come to you?\" And he said to them, \"You know the fellow and his talk.\"”", true, 11),
    blank(1, "so he spoke to me, saying, `Thus says the LORD, I anoint you king over _____.’\"", "Israel", 12, ["israel"]),
    mc(2, "Which word correctly completes this RSV wording: “so he spoke to me, saying, `Thus says the LORD, I anoint you king over _____.’\"”", ["Israel", "Ahi’jah", "Again", "David"], 12),
    word(3, "In verse 12, what word completes this phrase: “so he spoke to me, saying, `Thus says the LORD, I anoint you king over _____.’\"”?", "Israel", 12, ["israel"]),
    tf(1, "The RSV does not state: “And they said, \"That is not true; tell us now.\" And he said, \"Thus and so he spoke to me, saying, `Thus says the LORD, I anoint you king over Israel.’\"”", false, 12, "The quoted wording is the RSV text of this verse."),
    blank(2, "under him on the bare steps, and they blew the trumpet, and proclaimed, \"_____ is king.\"", "Jehu", 13, ["jehu"]),
    mc(3, "Which word correctly completes this RSV wording: “under him on the bare steps, and they blew the trumpet, and proclaimed, \"_____ is king.\"”", ["Jehu", "Again", "Throw", "Nebat"], 13),
    word(1, "In verse 13, what word completes this phrase: “under him on the bare steps, and they blew the trumpet, and proclaimed, \"_____ is king.\"”?", "Jehu", 13, ["jehu"]),
    tf(2, "The RSV states: “Then in haste every man of them took his garment, and put it under him on the bare steps, and they blew the trumpet, and proclaimed, \"Jehu is king.\"”", true, 13),
    blank(3, "conspired against Joram. (Now Joram with all Israel had been on guard at _____ against Haz’ael king of Syria;", "Ramoth-gilead", 14, ["ramoth-gilead"]),
    mc(1, "Which word correctly completes this RSV wording: “conspired against Joram. (Now Joram with all Israel had been on guard at _____ against Haz’ael king of Syria;”", ["Ramoth-gilead", "Jerusalem", "Tishbite", "Jehosh’aphat"], 14),
    word(2, "In verse 14, what word completes this phrase: “conspired against Joram. (Now Joram with all Israel had been on guard at _____ against Haz’ael king of Syria;”?", "Ramoth-gilead", 14, ["ramoth-gilead"]),
    tf(3, "The RSV does not state: “Thus Jehu the son of Jehosh’aphat the son of Nimshi conspired against Joram. (Now Joram with all Israel had been on guard at Ramoth-gilead against Haz’ael king of Syria;”", false, 14, "The quoted wording is the RSV text of this verse."),
    blank(1, "but King Joram had returned to be healed in _____ of the wounds which the Syrians had given him, when he fought with Haz’ael", "Jezreel", 15, ["jezreel"]),
    mc(2, "Which word correctly completes this RSV wording: “but King Joram had returned to be healed in _____ of the wounds which the Syrians had given him, when he fought with Haz’ael”", ["Jezreel", "Shoot", "Jehu", "Joram"], 15),
    word(3, "In verse 15, what word completes this phrase: “but King Joram had returned to be healed in _____ of the wounds which the Syrians had given him, when he fought with Haz’ael”?", "Jezreel", 15, ["jezreel"]),
    tf(1, "The RSV states: “but King Joram had returned to be healed in Jezreel of the wounds which the Syrians had given him, when he fought with Haz’ael king of Syria.) So Jehu said, \"If this is your mind, then let no one slip out of the city to go and tell the news in Jezreel.\"”", true, 15),
    blank(2, "Jehu mounted his chariot, and went to Jezreel, for Joram lay there. And _____ king of Judah had come down to visit Joram.", "Ahazi’ah", 16, ["ahaziah"]),
    mc(3, "Which word correctly completes this RSV wording: “Jehu mounted his chariot, and went to Jezreel, for Joram lay there. And _____ king of Judah had come down to visit Joram.”", ["Ahazi’ah", "David", "Thus", "Syria"], 16),
    word(1, "In verse 16, what word completes this phrase: “Jehu mounted his chariot, and went to Jezreel, for Joram lay there. And _____ king of Judah had come down to visit Joram.”?", "Ahazi’ah", 16, ["ahaziah"]),
    tf(2, "The RSV does not state: “Then Jehu mounted his chariot, and went to Jezreel, for Joram lay there. And Ahazi’ah king of Judah had come down to visit Joram.”", false, 16, "The quoted wording is the RSV text of this verse."),
    blank(3, "Now the watchman was standing on the tower in _____, and he spied the company of Jehu as he came, and said, \"I see a company.\"", "Jezreel", 17, ["jezreel"]),
    mc(1, "Which word correctly completes this RSV wording: “Now the watchman was standing on the tower in _____, and he spied the company of Jehu as he came, and said, \"I see a company.\"”", ["Jezreel", "Thus", "King", "Bidkar"], 17),
    word(2, "In verse 17, what word completes this phrase: “Now the watchman was standing on the tower in _____, and he spied the company of Jehu as he came, and said, \"I see a company.\"”?", "Jezreel", 17, ["jezreel"]),
    tf(3, "The RSV states: “Now the watchman was standing on the tower in Jezreel, and he spied the company of Jehu as he came, and said, \"I see a company.\" And Joram said, \"Take a horseman, and send to meet them, and let him say, `Is it peace?’\"”", true, 17),
    blank(1, "So a man on horseback went to meet him, and said, \"_____ says the king, `Is it peace?’\" And Jehu said, \"What have you to do with", "Thus", 18, ["thus"]),
    mc(2, "Which word correctly completes this RSV wording: “So a man on horseback went to meet him, and said, \"_____ says the king, `Is it peace?’\" And Jehu said, \"What have you to do with”", ["Thus", "Again", "Throw", "Nebat"], 18),
    word(3, "In verse 18, what word completes this phrase: “So a man on horseback went to meet him, and said, \"_____ says the king, `Is it peace?’\" And Jehu said, \"What have you to do with”?", "Thus", 18, ["thus"]),
    tf(1, "The RSV does not state: “So a man on horseback went to meet him, and said, \"Thus says the king, `Is it peace?’\" And Jehu said, \"What have you to do with peace? Turn round and ride behind me.\" And the watchman reported, saying, \"The messenger reached them, but he is not coming back.\"”", false, 18, "The quoted wording is the RSV text of this verse."),
    blank(2, "Then he sent out a second horseman, who came to them, and said, \"_____ the king has said, `Is it peace?’\" And Jehu answered, \"What have you to", "Thus", 19, ["thus"]),
    mc(3, "Which word correctly completes this RSV wording: “Then he sent out a second horseman, who came to them, and said, \"_____ the king has said, `Is it peace?’\" And Jehu answered, \"What have you to”", ["Thus", "Megid’do", "Israel", "King"], 19),
    word(1, "In verse 19, what word completes this phrase: “Then he sent out a second horseman, who came to them, and said, \"_____ the king has said, `Is it peace?’\" And Jehu answered, \"What have you to”?", "Thus", 19, ["thus"]),
    tf(2, "The RSV states: “Then he sent out a second horseman, who came to them, and said, \"Thus the king has said, `Is it peace?’\" And Jehu answered, \"What have you to do with peace? Turn round and ride behind me.\"”", true, 19),
    blank(3, "not coming back. And the driving is like the driving of Jehu the son of _____; for he drives furiously.\"", "Nimshi", 20, ["nimshi"]),
    mc(1, "Which word correctly completes this RSV wording: “not coming back. And the driving is like the driving of Jehu the son of _____; for he drives furiously.\"”", ["Nimshi", "Ibleam", "Thus", "Syria"], 20),
    word(2, "In verse 20, what word completes this phrase: “not coming back. And the driving is like the driving of Jehu the son of _____; for he drives furiously.\"”?", "Nimshi", 20, ["nimshi"]),
    tf(3, "The RSV does not state: “Again the watchman reported, \"He reached them, but he is not coming back. And the driving is like the driving of Jehu the son of Nimshi; for he drives furiously.\"”", false, 20, "The quoted wording is the RSV text of this verse."),
    blank(1, "chariot, and went to meet Jehu, and met him at the property of Naboth the _____.", "Jezreelite", 21, ["jezreelite"]),
    mc(2, "Which word correctly completes this RSV wording: “chariot, and went to meet Jehu, and met him at the property of Naboth the _____.”", ["Jezreelite", "Ibleam", "Nimshi", "Syrians"], 21),
    word(3, "In verse 21, what word completes this phrase: “chariot, and went to meet Jehu, and met him at the property of Naboth the _____.”?", "Jezreelite", 21, ["jezreelite"]),
    tf(1, "The RSV states: “Joram said, \"Make ready.\" And they made ready his chariot. Then Joram king of Israel and Ahazi’ah king of Judah set out, each in his chariot, and went to meet Jehu, and met him at the property of Naboth the Jezreelite.”", true, 21),
    blank(2, "there be, so long as the harlotries and the sorceries of your mother _____ are so many?\"", "Jez’ebel", 22, ["jezebel"]),
    mc(3, "Which word correctly completes this RSV wording: “there be, so long as the harlotries and the sorceries of your mother _____ are so many?\"”", ["Jez’ebel", "Eli’jah", "Jerobo’am", "Judah"], 22),
    word(1, "In verse 22, what word completes this phrase: “there be, so long as the harlotries and the sorceries of your mother _____ are so many?\"”?", "Jez’ebel", 22, ["jezebel"]),
    tf(2, "The RSV does not state: “And when Joram saw Jehu, he said, \"Is it peace, Jehu?\" He answered, \"What peace can there be, so long as the harlotries and the sorceries of your mother Jez’ebel are so many?\"”", false, 22, "The quoted wording is the RSV text of this verse."),
    blank(3, "Then Joram reined about and fled, saying to Ahazi’ah, \"_____, O Ahazi’ah!\"", "Treachery", 23, ["treachery"]),
    mc(1, "Which word correctly completes this RSV wording: “Then Joram reined about and fled, saying to Ahazi’ah, \"_____, O Ahazi’ah!\"”", ["Treachery", "Nimshi", "Haz’ael", "Jezreelite"], 23),
    word(2, "In verse 23, what word completes this phrase: “Then Joram reined about and fled, saying to Ahazi’ah, \"_____, O Ahazi’ah!\"”?", "Treachery", 23, ["treachery"]),
    tf(3, "The RSV states: “Then Joram reined about and fled, saying to Ahazi’ah, \"Treachery, O Ahazi’ah!\"”", true, 23),
    blank(1, "And Jehu drew his bow with his full strength, and shot _____ between the shoulders, so that the arrow pierced his heart, and he sank", "Joram", 24, ["joram"]),
    mc(2, "Which word correctly completes this RSV wording: “And Jehu drew his bow with his full strength, and shot _____ between the shoulders, so that the arrow pierced his heart, and he sank”", ["Joram", "Jezreelite", "Tishbite", "Ba’asha"], 24),
    word(3, "In verse 24, what word completes this phrase: “And Jehu drew his bow with his full strength, and shot _____ between the shoulders, so that the arrow pierced his heart, and he sank”?", "Joram", 24, ["joram"]),
    tf(1, "The RSV does not state: “And Jehu drew his bow with his full strength, and shot Joram between the shoulders, so that the arrow pierced his heart, and he sank in his chariot.”", false, 24, "The quoted wording is the RSV text of this verse."),
    blank(2, "\"Take him up, and cast him on the plot of ground belonging to Naboth the _____; for remember, when you and I rode side by side behind Ahab his father,", "Jezreelite", 25, ["jezreelite"]),
    mc(3, "Which word correctly completes this RSV wording: “\"Take him up, and cast him on the plot of ground belonging to Naboth the _____; for remember, when you and I rode side by side behind Ahab his father,”", ["Jezreelite", "Bidkar", "Eli’sha", "Joram"], 25),
    word(1, "In verse 25, what word completes this phrase: “\"Take him up, and cast him on the plot of ground belonging to Naboth the _____; for remember, when you and I rode side by side behind Ahab his father,”?", "Jezreelite", 25, ["jezreelite"]),
    tf(2, "The RSV states: “Jehu said to Bidkar his aide, \"Take him up, and cast him on the plot of ground belonging to Naboth the Jezreelite; for remember, when you and I rode side by side behind Ahab his father, how the LORD uttered this oracle against him:”", true, 25),
    blank(3, "`As surely as I saw yesterday the blood of _____ and the blood of his sons -- says the LORD -- I will requite you on this", "Naboth", 26, ["naboth"]),
    mc(1, "Which word correctly completes this RSV wording: “`As surely as I saw yesterday the blood of _____ and the blood of his sons -- says the LORD -- I will requite you on this”", ["Naboth", "Throw", "Jerobo’am", "Judah"], 26),
    word(2, "In verse 26, what word completes this phrase: “`As surely as I saw yesterday the blood of _____ and the blood of his sons -- says the LORD -- I will requite you on this”?", "Naboth", 26, ["naboth"]),
    tf(3, "The RSV does not state: “`As surely as I saw yesterday the blood of Naboth and the blood of his sons -- says the LORD -- I will requite you on this plot of ground.’ Now therefore take him up and cast him on the plot of ground, in accordance with the word of the LORD.\"”", false, 26, "The quoted wording is the RSV text of this verse."),
    blank(1, "When Ahazi’ah the king of Judah saw this, he fled in the direction of _____. And Jehu pursued him, and said, \"Shoot him also\"; and they shot him in", "Beth-haggan", 27, ["beth-haggan"]),
    mc(2, "Which word correctly completes this RSV wording: “When Ahazi’ah the king of Judah saw this, he fled in the direction of _____. And Jehu pursued him, and said, \"Shoot him also\"; and they shot him in”", ["Beth-haggan", "Naboth", "Jehosh’aphat", "Jerusalem"], 27),
    word(3, "In verse 27, what word completes this phrase: “When Ahazi’ah the king of Judah saw this, he fled in the direction of _____. And Jehu pursued him, and said, \"Shoot him also\"; and they shot him in”?", "Beth-haggan", 27, ["beth-haggan"]),
    tf(1, "The RSV states: “When Ahazi’ah the king of Judah saw this, he fled in the direction of Beth-haggan. And Jehu pursued him, and said, \"Shoot him also\"; and they shot him in the chariot at the ascent of Gur, which is by Ibleam. And he fled to Megid’do, and died there.”", true, 27),
    blank(2, "His servants carried him in a chariot to _____, and buried him in his tomb with his fathers in the city of David.", "Jerusalem", 28, ["jerusalem"]),
    mc(3, "Which word correctly completes this RSV wording: “His servants carried him in a chariot to _____, and buried him in his tomb with his fathers in the city of David.”", ["Jerusalem", "Gird", "Ba’asha", "Turn"], 28),
    word(1, "In verse 28, what word completes this phrase: “His servants carried him in a chariot to _____, and buried him in his tomb with his fathers in the city of David.”?", "Jerusalem", 28, ["jerusalem"]),
    tf(2, "The RSV does not state: “His servants carried him in a chariot to Jerusalem, and buried him in his tomb with his fathers in the city of David.”", false, 28, "The quoted wording is the RSV text of this verse."),
    blank(3, "In the eleventh year of Joram the son of Ahab, _____ began to reign over Judah.", "Ahazi’ah", 29, ["ahaziah"]),
    mc(1, "Which word correctly completes this RSV wording: “In the eleventh year of Joram the son of Ahab, _____ began to reign over Judah.”", ["Ahazi’ah", "Ahab", "Syrians", "Shoot"], 29),
    word(2, "In verse 29, what word completes this phrase: “In the eleventh year of Joram the son of Ahab, _____ began to reign over Judah.”?", "Ahazi’ah", 29, ["ahaziah"]),
    tf(3, "The RSV states: “In the eleventh year of Joram the son of Ahab, Ahazi’ah began to reign over Judah.”", true, 29),
    blank(1, "When Jehu came to Jezreel, _____ heard of it; and she painted her eyes, and adorned her head, and looked", "Jez’ebel", 30, ["jezebel"]),
    mc(2, "Which word correctly completes this RSV wording: “When Jehu came to Jezreel, _____ heard of it; and she painted her eyes, and adorned her head, and looked”", ["Jez’ebel", "Haz’ael", "Jezreelite", "Eli’jah"], 30),
    word(3, "In verse 30, what word completes this phrase: “When Jehu came to Jezreel, _____ heard of it; and she painted her eyes, and adorned her head, and looked”?", "Jez’ebel", 30, ["jezebel"]),
    tf(1, "The RSV does not state: “When Jehu came to Jezreel, Jez’ebel heard of it; and she painted her eyes, and adorned her head, and looked out of the window.”", false, 30, "The quoted wording is the RSV text of this verse."),
    blank(2, "And as Jehu entered the gate, she said, \"Is it peace, you _____, murderer of your master?\"", "Zimri", 31, ["zimri"]),
    mc(3, "Which word correctly completes this RSV wording: “And as Jehu entered the gate, she said, \"Is it peace, you _____, murderer of your master?\"”", ["Zimri", "Gird", "Jezreel", "Make"], 31),
    word(1, "In verse 31, what word completes this phrase: “And as Jehu entered the gate, she said, \"Is it peace, you _____, murderer of your master?\"”?", "Zimri", 31, ["zimri"]),
    tf(2, "The RSV states: “And as Jehu entered the gate, she said, \"Is it peace, you Zimri, murderer of your master?\"”", true, 31),
    blank(3, "face to the window, and said, \"Who is on my side? Who?\" Two or three _____ looked out at him.", "eunuchs", 32, ["eunuchs"]),
    mc(1, "Which word correctly completes this RSV wording: “face to the window, and said, \"Who is on my side? Who?\" Two or three _____ looked out at him.”", ["eunuchs", "anoint", "commanders", "strike"], 32),
    word(2, "In verse 32, what word completes this phrase: “face to the window, and said, \"Who is on my side? Who?\" Two or three _____ looked out at him.”?", "eunuchs", 32, ["eunuchs"]),
    tf(3, "The RSV does not state: “And he lifted up his face to the window, and said, \"Who is on my side? Who?\" Two or three eunuchs looked out at him.”", false, 32, "The quoted wording is the RSV text of this verse."),
    blank(1, "He said, \"_____ her down.\" So they threw her down; and some of her blood spattered on", "Throw", 33, ["throw"]),
    mc(2, "Which word correctly completes this RSV wording: “He said, \"_____ her down.\" So they threw her down; and some of her blood spattered on”", ["Throw", "Syria", "Treachery", "Gird"], 33),
    word(3, "In verse 33, what word completes this phrase: “He said, \"_____ her down.\" So they threw her down; and some of her blood spattered on”?", "Throw", 33, ["throw"]),
    tf(1, "The RSV states: “He said, \"Throw her down.\" So they threw her down; and some of her blood spattered on the wall and on the horses, and they trampled on her.”", true, 33),
    blank(2, "said, \"See now to this cursed woman, and bury her; for she is a king’s _____.\"", "daughter", 34, ["daughter"]),
    mc(3, "Which word correctly completes this RSV wording: “said, \"See now to this cursed woman, and bury her; for she is a king’s _____.\"”", ["daughter", "errand", "avenge", "dogs"], 34),
    word(1, "In verse 34, what word completes this phrase: “said, \"See now to this cursed woman, and bury her; for she is a king’s _____.\"”?", "daughter", 34, ["daughter"]),
    tf(2, "The RSV does not state: “Then he went in and ate and drank; and he said, \"See now to this cursed woman, and bury her; for she is a king’s daughter.\"”", false, 34, "The quoted wording is the RSV text of this verse."),
    blank(3, "But when they went to bury her, they _____ no more of her than the skull and the feet and the palms of her hands.", "found", 35, ["found"]),
    mc(1, "Which word correctly completes this RSV wording: “But when they went to bury her, they _____ no more of her than the skull and the feet and the palms of her hands.”", ["found", "shall", "bond", "fellow"], 35),
    word(2, "In verse 35, what word completes this phrase: “But when they went to bury her, they _____ no more of her than the skull and the feet and the palms of her hands.”?", "found", 35, ["found"]),
    tf(3, "The RSV states: “But when they went to bury her, they found no more of her than the skull and the feet and the palms of her hands.”", true, 35),
    blank(1, "\"This is the word of the LORD, which he spoke by his servant Eli’jah the _____, `In the territory of Jezreel the dogs shall eat the flesh of Jez’ebel;", "Tishbite", 36, ["tishbite"]),
    mc(2, "Which word correctly completes this RSV wording: “\"This is the word of the LORD, which he spoke by his servant Eli’jah the _____, `In the territory of Jezreel the dogs shall eat the flesh of Jez’ebel;”", ["Tishbite", "King", "Bidkar", "Gird"], 36),
    word(3, "In verse 36, what word completes this phrase: “\"This is the word of the LORD, which he spoke by his servant Eli’jah the _____, `In the territory of Jezreel the dogs shall eat the flesh of Jez’ebel;”?", "Tishbite", 36, ["tishbite"]),
    tf(1, "The RSV does not state: “When they came back and told him, he said, \"This is the word of the LORD, which he spoke by his servant Eli’jah the Tishbite, `In the territory of Jezreel the dogs shall eat the flesh of Jez’ebel;”", false, 36, "The quoted wording is the RSV text of this verse."),
    blank(2, "and the corpse of _____ shall be as dung upon the face of the field in the territory of Jezreel,", "Jez’ebel", 37, ["jezebel"]),
    mc(3, "Which word correctly completes this RSV wording: “and the corpse of _____ shall be as dung upon the face of the field in the territory of Jezreel,”", ["Jez’ebel", "Naboth", "Throw", "Ahab"], 37),
    word(1, "In verse 37, what word completes this phrase: “and the corpse of _____ shall be as dung upon the face of the field in the territory of Jezreel,”?", "Jez’ebel", 37, ["jezebel"]),
    tf(2, "The RSV states: “and the corpse of Jez’ebel shall be as dung upon the face of the field in the territory of Jezreel, so that no one can say, This is Jez’ebel.’\"”", true, 37),
    mc(2, "What was the young prophet’s errand at Ramoth-gilead, and what was he to do afterward?", ["Anoint Jehu king in an inner chamber, then open the door and flee", "Warn Joram, then remain in the city", "Anoint Hazael, then return to Elisha", "Deliver a letter to Jehu, then hide"], 3),
    mc(1, "How did the Jezreel watchman identify Jehu’s approaching company?", ["The driving was like Jehu son of Nimshi, for he drove furiously", "The company carried Jehu’s banner", "Jehu rode ahead of every chariot", "The watchman recognized Jehu’s horses"], 20),
    mc(3, "Where and why did Jehu order Joram’s body to be thrown?", ["On Naboth’s plot, fulfilling the LORD’s word against Ahab", "At Jezreel’s gate, as a warning to the city", "In Samaria’s pool, fulfilling Elijah’s word", "On the road to Ramoth-gilead, because Joram fled"], 26),
    mc(2, "What remained when they went to bury Jezebel?", ["Her skull, feet, and palms of her hands", "Only her bones", "Her hands and royal robes", "Nothing at all"], 35),
  ],
};

export default bank;
