// 2 Kings 3 — quiz bank (RSV). Four verse-anchored forms per verse.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: "2 Kings",
  chapter: 3,
  tag: "quiz-v2-2kings-3",
  rows: [
    blank(2, "In the eighteenth year of _____ king of Judah, Jeho’ram the son of Ahab became king over Israel in Sama’ria,", "Jehosh’aphat", 1, ["jehoshaphat"]),
    mc(3, "Which word correctly completes this RSV wording: “In the eighteenth year of _____ king of Judah, Jeho’ram the son of Ahab became king over Israel in Sama’ria,”", ["Jehosh’aphat", "Eli’jah", "Jerusalem", "Israel"], 1),
    word(1, "In verse 1, what word completes this phrase: “In the eighteenth year of _____ king of Judah, Jeho’ram the son of Ahab became king over Israel in Sama’ria,”?", "Jehosh’aphat", 1, ["jehoshaphat"]),
    tf(2, "The RSV states: “In the eighteenth year of Jehosh’aphat king of Judah, Jeho’ram the son of Ahab became king over Israel in Sama’ria, and he reigned twelve years.”", true, 1),
    blank(3, "though not like his father and mother, for he put away the pillar of _____ which his father had made.", "Ba’al", 2, ["baal"]),
    mc(1, "Which word correctly completes this RSV wording: “though not like his father and mother, for he put away the pillar of _____ which his father had made.”", ["Ba’al", "Shaphat", "Nebat", "Moabites"], 2),
    word(2, "In verse 2, what word completes this phrase: “though not like his father and mother, for he put away the pillar of _____ which his father had made.”?", "Ba’al", 2, ["baal"]),
    tf(3, "The RSV does not state: “He did what was evil in the sight of the LORD, though not like his father and mother, for he put away the pillar of Ba’al which his father had made.”", false, 2, "The quoted wording is the RSV text of this verse."),
    blank(1, "_____ he clung to the sin of Jerobo’am the son of Nebat, which he made Israel", "Nevertheless", 3, ["nevertheless"]),
    mc(2, "Which word correctly completes this RSV wording: “_____ he clung to the sin of Jerobo’am the son of Nebat, which he made Israel”", ["Nevertheless", "Kir-har’eseth", "Jerusalem", "Israel"], 3),
    word(3, "In verse 3, what word completes this phrase: “_____ he clung to the sin of Jerobo’am the son of Nebat, which he made Israel”?", "Nevertheless", 3, ["nevertheless"]),
    tf(1, "The RSV states: “Nevertheless he clung to the sin of Jerobo’am the son of Nebat, which he made Israel to sin; he did not depart from it.”", true, 3),
    blank(2, "Moab was a sheep breeder; and he had to deliver annually to the king of _____ a hundred thousand lambs, and the wool of a hundred thousand rams.", "Israel", 4, ["israel"]),
    mc(3, "Which word correctly completes this RSV wording: “Moab was a sheep breeder; and he had to deliver annually to the king of _____ a hundred thousand lambs, and the wool of a hundred thousand rams.”", ["Israel", "King", "Jeho’ram", "Israel’s"], 4),
    word(1, "In verse 4, what word completes this phrase: “Moab was a sheep breeder; and he had to deliver annually to the king of _____ a hundred thousand lambs, and the wool of a hundred thousand rams.”?", "Israel", 4, ["israel"]),
    tf(2, "The RSV does not state: “Now Mesha king of Moab was a sheep breeder; and he had to deliver annually to the king of Israel a hundred thousand lambs, and the wool of a hundred thousand rams.”", false, 4, "The quoted wording is the RSV text of this verse."),
    blank(3, "But when Ahab died, the king of Moab rebelled against the king of _____.", "Israel", 5, ["israel"]),
    mc(1, "Which word correctly completes this RSV wording: “But when Ahab died, the king of Moab rebelled against the king of _____.”", ["Israel", "Thus", "Moab", "Judah"], 5),
    word(2, "In verse 5, what word completes this phrase: “But when Ahab died, the king of Moab rebelled against the king of _____.”?", "Israel", 5, ["israel"]),
    tf(3, "The RSV states: “But when Ahab died, the king of Moab rebelled against the king of Israel.”", true, 5),
    blank(1, "So King _____ marched out of Sama’ria at that time and mustered all Israel.", "Jeho’ram", 6, ["jehoram"]),
    mc(2, "Which word correctly completes this RSV wording: “So King _____ marched out of Sama’ria at that time and mustered all Israel.”", ["Jeho’ram", "Israelites", "Mesha", "Jerusalem"], 6),
    word(3, "In verse 6, what word completes this phrase: “So King _____ marched out of Sama’ria at that time and mustered all Israel.”?", "Jeho’ram", 6, ["jehoram"]),
    tf(1, "The RSV does not state: “So King Jeho’ram marched out of Sama’ria at that time and mustered all Israel.”", false, 6, "The quoted wording is the RSV text of this verse."),
    blank(2, "And he went and sent word to _____ king of Judah, \"The king of Moab has rebelled against me; will you go", "Jehosh’aphat", 7, ["jehoshaphat"]),
    mc(3, "Which word correctly completes this RSV wording: “And he went and sent word to _____ king of Judah, \"The king of Moab has rebelled against me; will you go”", ["Jehosh’aphat", "Eli’sha", "Jerusalem", "Israel"], 7),
    word(1, "In verse 7, what word completes this phrase: “And he went and sent word to _____ king of Judah, \"The king of Moab has rebelled against me; will you go”?", "Jehosh’aphat", 7, ["jehoshaphat"]),
    tf(2, "The RSV states: “And he went and sent word to Jehosh’aphat king of Judah, \"The king of Moab has rebelled against me; will you go with me to battle against Moab?\" And he said, \"I will go; I am as you are, my people as your people, my horses as your horses.\"”", true, 7),
    blank(3, "Then he said, \"By which way shall we march?\" _____ answered, \"By the way of the wilderness of Edom.\"", "Jeho’ram", 8, ["jehoram"]),
    mc(1, "Which word correctly completes this RSV wording: “Then he said, \"By which way shall we march?\" _____ answered, \"By the way of the wilderness of Edom.\"”", ["Jeho’ram", "Edom", "Judah", "Jerusalem"], 8),
    word(2, "In verse 8, what word completes this phrase: “Then he said, \"By which way shall we march?\" _____ answered, \"By the way of the wilderness of Edom.\"”?", "Jeho’ram", 8, ["jehoram"]),
    tf(3, "The RSV does not state: “Then he said, \"By which way shall we march?\" Jeho’ram answered, \"By the way of the wilderness of Edom.\"”", false, 8, "The quoted wording is the RSV text of this verse."),
    blank(1, "So the king of _____ went with the king of Judah and the king of Edom. And when they had made", "Israel", 9, ["israel"]),
    mc(2, "Which word correctly completes this RSV wording: “So the king of _____ went with the king of Judah and the king of Edom. And when they had made”", ["Israel", "Nebat", "Moabites", "King"], 9),
    word(3, "In verse 9, what word completes this phrase: “So the king of _____ went with the king of Judah and the king of Edom. And when they had made”?", "Israel", 9, ["israel"]),
    tf(1, "The RSV states: “So the king of Israel went with the king of Judah and the king of Edom. And when they had made a circuitous march of seven days, there was no water for the army or for the beasts which followed them.”", true, 9),
    blank(2, "Then the king of _____ said, \"Alas! The LORD has called these three kings to give them into the", "Israel", 10, ["israel"]),
    mc(3, "Which word correctly completes this RSV wording: “Then the king of _____ said, \"Alas! The LORD has called these three kings to give them into the”", ["Israel", "Eli’sha", "Jerobo’am", "Thus"], 10),
    word(1, "In verse 10, what word completes this phrase: “Then the king of _____ said, \"Alas! The LORD has called these three kings to give them into the”?", "Israel", 10, ["israel"]),
    tf(2, "The RSV does not state: “Then the king of Israel said, \"Alas! The LORD has called these three kings to give them into the hand of Moab.\"”", false, 10, "The quoted wording is the RSV text of this verse."),
    blank(3, "And _____ said, \"Is there no prophet of the LORD here, through whom we may inquire", "Jehosh’aphat", 11, ["jehoshaphat"]),
    mc(1, "Which word correctly completes this RSV wording: “And _____ said, \"Is there no prophet of the LORD here, through whom we may inquire”", ["Jehosh’aphat", "Jeho’ram", "Jerusalem", "Israel"], 11),
    word(2, "In verse 11, what word completes this phrase: “And _____ said, \"Is there no prophet of the LORD here, through whom we may inquire”?", "Jehosh’aphat", 11, ["jehoshaphat"]),
    tf(3, "The RSV states: “And Jehosh’aphat said, \"Is there no prophet of the LORD here, through whom we may inquire of the LORD?\" Then one of the king of Israel’s servants answered, \"Eli’sha the son of Shaphat is here, who poured water on the hands of Eli’jah.\"”", true, 11),
    blank(1, "And _____ said, \"The word of the LORD is with him.\" So the king of Israel and Jehosh’aphat", "Jehosh’aphat", 12, ["jehoshaphat"]),
    mc(2, "Which word correctly completes this RSV wording: “And _____ said, \"The word of the LORD is with him.\" So the king of Israel and Jehosh’aphat”", ["Jehosh’aphat", "Eli’jah", "Jerusalem", "Israel"], 12),
    word(3, "In verse 12, what word completes this phrase: “And _____ said, \"The word of the LORD is with him.\" So the king of Israel and Jehosh’aphat”?", "Jehosh’aphat", 12, ["jehoshaphat"]),
    tf(1, "The RSV does not state: “And Jehosh’aphat said, \"The word of the LORD is with him.\" So the king of Israel and Jehosh’aphat and the king of Edom went down to him.”", false, 12, "The quoted wording is the RSV text of this verse."),
    blank(2, "And _____ said to the king of Israel, \"What have I to do with you? Go to the prophets", "Eli’sha", 13, ["elisha"]),
    mc(3, "Which word correctly completes this RSV wording: “And _____ said to the king of Israel, \"What have I to do with you? Go to the prophets”", ["Eli’sha", "Nevertheless", "Thus", "Jerobo’am"], 13),
    word(1, "In verse 13, what word completes this phrase: “And _____ said to the king of Israel, \"What have I to do with you? Go to the prophets”?", "Eli’sha", 13, ["elisha"]),
    tf(2, "The RSV states: “And Eli’sha said to the king of Israel, \"What have I to do with you? Go to the prophets of your father and the prophets of your mother.\" But the king of Israel said to him, \"No; it is the LORD who has called these three kings to give them into the hand of Moab.\"”", true, 13),
    blank(3, "LORD of hosts lives, whom I serve, were it not that I have regard for _____ the king of Judah, I would neither look at you, nor see you.", "Jehosh’aphat", 14, ["jehoshaphat"]),
    mc(1, "Which word correctly completes this RSV wording: “LORD of hosts lives, whom I serve, were it not that I have regard for _____ the king of Judah, I would neither look at you, nor see you.”", ["Jehosh’aphat", "Kir-har’eseth", "Jerusalem", "Israel"], 14),
    word(2, "In verse 14, what word completes this phrase: “LORD of hosts lives, whom I serve, were it not that I have regard for _____ the king of Judah, I would neither look at you, nor see you.”?", "Jehosh’aphat", 14, ["jehoshaphat"]),
    tf(3, "The RSV does not state: “And Eli’sha said, \"As the LORD of hosts lives, whom I serve, were it not that I have regard for Jehosh’aphat the king of Judah, I would neither look at you, nor see you.”", false, 14, "The quoted wording is the RSV text of this verse."),
    blank(1, "But now bring me a _____.\" And when the minstrel played, the power of the LORD came upon him.", "minstrel", 15, ["minstrel"]),
    mc(2, "Which word correctly completes this RSV wording: “But now bring me a _____.\" And when the minstrel played, the power of the LORD came upon him.”", ["minstrel", "about", "armor", "fought"], 15),
    word(3, "In verse 15, what word completes this phrase: “But now bring me a _____.\" And when the minstrel played, the power of the LORD came upon him.”?", "minstrel", 15, ["minstrel"]),
    tf(1, "The RSV states: “But now bring me a minstrel.\" And when the minstrel played, the power of the LORD came upon him.”", true, 15),
    blank(2, "And he said, \"_____ says the LORD, `I will make this dry stream-bed full of pools.’", "Thus", 16, ["thus"]),
    mc(3, "Which word correctly completes this RSV wording: “And he said, \"_____ says the LORD, `I will make this dry stream-bed full of pools.’”", ["Thus", "Sama’ria", "Shaphat", "Mesha"], 16),
    word(1, "In verse 16, what word completes this phrase: “And he said, \"_____ says the LORD, `I will make this dry stream-bed full of pools.’”?", "Thus", 16, ["thus"]),
    tf(2, "The RSV does not state: “And he said, \"Thus says the LORD, `I will make this dry stream-bed full of pools.’”", false, 16, "The quoted wording is the RSV text of this verse."),
    blank(3, "For thus says the LORD, `You shall not see wind or rain, but that _____ shall be filled with water, so that you shall drink, you, your cattle,", "stream-bed", 17, ["stream-bed"]),
    mc(1, "Which word correctly completes this RSV wording: “For thus says the LORD, `You shall not see wind or rain, but that _____ shall be filled with water, so that you shall drink, you, your cattle,”", ["stream-bed", "returned", "clung", "marched"], 17),
    word(2, "In verse 17, what word completes this phrase: “For thus says the LORD, `You shall not see wind or rain, but that _____ shall be filled with water, so that you shall drink, you, your cattle,”?", "stream-bed", 17, ["stream-bed"]),
    tf(3, "The RSV states: “For thus says the LORD, `You shall not see wind or rain, but that stream-bed shall be filled with water, so that you shall drink, you, your cattle, and your beasts.’”", true, 17),
    blank(1, "This is a light thing in the sight of the LORD; he will also give the _____ into your hand,", "Moabites", 18, ["moabites"]),
    mc(2, "Which word correctly completes this RSV wording: “This is a light thing in the sight of the LORD; he will also give the _____ into your hand,”", ["Moabites", "Eli’sha", "Sama’ria", "Jerusalem"], 18),
    word(3, "In verse 18, what word completes this phrase: “This is a light thing in the sight of the LORD; he will also give the _____ into your hand,”?", "Moabites", 18, ["moabites"]),
    tf(1, "The RSV does not state: “This is a light thing in the sight of the LORD; he will also give the Moabites into your hand,”", false, 18, "The quoted wording is the RSV text of this verse."),
    blank(2, "and you shall conquer every _____ city, and every choice city, and shall fell every good tree, and stop", "fortified", 19, ["fortified"]),
    mc(3, "Which word correctly completes this RSV wording: “and you shall conquer every _____ city, and every choice city, and shall fell every good tree, and stop”", ["fortified", "attacked", "stopped", "swordsmen"], 19),
    word(1, "In verse 19, what word completes this phrase: “and you shall conquer every _____ city, and every choice city, and shall fell every good tree, and stop”?", "fortified", 19, ["fortified"]),
    tf(2, "The RSV states: “and you shall conquer every fortified city, and every choice city, and shall fell every good tree, and stop up all springs of water, and ruin every good piece of land with stones.\"”", true, 19),
    blank(3, "time of offering the sacrifice, behold, water came from the direction of _____, till the country was filled with water.", "Edom", 20, ["edom"]),
    mc(1, "Which word correctly completes this RSV wording: “time of offering the sacrifice, behold, water came from the direction of _____, till the country was filled with water.”", ["Edom", "Shaphat", "Nebat", "Judah"], 20),
    word(2, "In verse 20, what word completes this phrase: “time of offering the sacrifice, behold, water came from the direction of _____, till the country was filled with water.”?", "Edom", 20, ["edom"]),
    tf(3, "The RSV does not state: “The next morning, about the time of offering the sacrifice, behold, water came from the direction of Edom, till the country was filled with water.”", false, 20, "The quoted wording is the RSV text of this verse."),
    blank(1, "When all the _____ heard that the kings had come up to fight against them, all who were able", "Moabites", 21, ["moabites"]),
    mc(2, "Which word correctly completes this RSV wording: “When all the _____ heard that the kings had come up to fight against them, all who were able”", ["Moabites", "Israel’s", "Israel", "Jerusalem"], 21),
    word(3, "In verse 21, what word completes this phrase: “When all the _____ heard that the kings had come up to fight against them, all who were able”?", "Moabites", 21, ["moabites"]),
    tf(1, "The RSV states: “When all the Moabites heard that the kings had come up to fight against them, all who were able to put on armor, from the youngest to the oldest, were called out, and were drawn up at the frontier.”", true, 21),
    blank(2, "they rose early in the morning, and the sun shone upon the water, the _____ saw the water opposite them as red as blood.", "Moabites", 22, ["moabites"]),
    mc(3, "Which word correctly completes this RSV wording: “they rose early in the morning, and the sun shone upon the water, the _____ saw the water opposite them as red as blood.”", ["Moabites", "Jehosh’aphat", "Moab", "Jerusalem"], 22),
    word(1, "In verse 22, what word completes this phrase: “they rose early in the morning, and the sun shone upon the water, the _____ saw the water opposite them as red as blood.”?", "Moabites", 22, ["moabites"]),
    tf(2, "The RSV does not state: “And when they rose early in the morning, and the sun shone upon the water, the Moabites saw the water opposite them as red as blood.”", false, 22, "The quoted wording is the RSV text of this verse."),
    blank(3, "the kings have surely fought together, and slain one another. Now then, _____, to the spoil!\"", "Moab", 23, ["moab"]),
    mc(1, "Which word correctly completes this RSV wording: “the kings have surely fought together, and slain one another. Now then, _____, to the spoil!\"”", ["Moab", "Moabites", "Edom", "Israel"], 23),
    word(2, "In verse 23, what word completes this phrase: “the kings have surely fought together, and slain one another. Now then, _____, to the spoil!\"”?", "Moab", 23, ["moab"]),
    tf(3, "The RSV states: “And they said, \"This is blood; the kings have surely fought together, and slain one another. Now then, Moab, to the spoil!\"”", true, 23),
    blank(1, "But when they came to the camp of Israel, the _____ rose and attacked the Moabites, till they fled before them; and they went", "Israelites", 24, ["israelites"]),
    mc(2, "Which word correctly completes this RSV wording: “But when they came to the camp of Israel, the _____ rose and attacked the Moabites, till they fled before them; and they went”", ["Israelites", "Nebat", "Israel", "Moabites"], 24),
    word(3, "In verse 24, what word completes this phrase: “But when they came to the camp of Israel, the _____ rose and attacked the Moabites, till they fled before them; and they went”?", "Israelites", 24, ["israelites"]),
    tf(1, "The RSV does not state: “But when they came to the camp of Israel, the Israelites rose and attacked the Moabites, till they fled before them; and they went forward, slaughtering the Moabites as they went.”", false, 24, "The quoted wording is the RSV text of this verse."),
    blank(2, "water, and felled all the good trees; till only its stones were left in _____, and the slingers surrounded and conquered it.", "Kir-har’eseth", 25, ["kir-hareseth"]),
    mc(3, "Which word correctly completes this RSV wording: “water, and felled all the good trees; till only its stones were left in _____, and the slingers surrounded and conquered it.”", ["Kir-har’eseth", "Israelites", "Sama’ria", "Israel’s"], 25),
    word(1, "In verse 25, what word completes this phrase: “water, and felled all the good trees; till only its stones were left in _____, and the slingers surrounded and conquered it.”?", "Kir-har’eseth", 25, ["kir-hareseth"]),
    tf(2, "The RSV states: “And they overthrew the cities, and on every good piece of land every man threw a stone, until it was covered; they stopped every spring of water, and felled all the good trees; till only its stones were left in Kir-har’eseth, and the slingers surrounded and conquered it.”", true, 25),
    blank(3, "When the king of _____ saw that the battle was going against him, he took with him seven hundred", "Moab", 26, ["moab"]),
    mc(1, "Which word correctly completes this RSV wording: “When the king of _____ saw that the battle was going against him, he took with him seven hundred”", ["Moab", "Ahab", "Eli’sha", "Jerobo’am"], 26),
    word(2, "In verse 26, what word completes this phrase: “When the king of _____ saw that the battle was going against him, he took with him seven hundred”?", "Moab", 26, ["moab"]),
    tf(3, "The RSV does not state: “When the king of Moab saw that the battle was going against him, he took with him seven hundred swordsmen to break through, opposite the king of Edom; but they could not.”", false, 26, "The quoted wording is the RSV text of this verse."),
    blank(1, "him for a burnt offering upon the wall. And there came great wrath upon _____; and they withdrew from him and returned to their own land.", "Israel", 27, ["israel"]),
    mc(2, "Which word correctly completes this RSV wording: “him for a burnt offering upon the wall. And there came great wrath upon _____; and they withdrew from him and returned to their own land.”", ["Israel", "Israelites", "Edom", "Ahab"], 27),
    word(3, "In verse 27, what word completes this phrase: “him for a burnt offering upon the wall. And there came great wrath upon _____; and they withdrew from him and returned to their own land.”?", "Israel", 27, ["israel"]),
    tf(1, "The RSV states: “Then he took his eldest son who was to reign in his stead, and offered him for a burnt offering upon the wall. And there came great wrath upon Israel; and they withdrew from him and returned to their own land.”", true, 27),
    blank(1, "In the _____ year of Jehosh’aphat king of Judah, Jeho’ram the son of Ahab became king", "eighteenth", 1, ["eighteenth"]),
    mc(2, "Select the missing RSV word: “He did what was evil in the sight of the LORD, _____ not like his father and mother, for he put away the pillar of Ba’al which”", ["though", "rebelled", "horses", "followed"], 2),
    word(3, "What missing word belongs in this verse 3 clause: “Nevertheless he clung to the sin of _____ the son of Nebat, which he made Israel to sin; he did not depart from”?", "Jerobo’am", 3, ["jeroboam"]),
    tf(1, "This wording appears in verse 4: “Now Mesha king of Moab was a sheep breeder; and he had to deliver annually to the king of Israel a hundred thousand lambs, and the wool of a hundred”", true, 4),
    blank(2, "But when Ahab died, the king of Moab _____ against the king of Israel.", "rebelled", 5, ["rebelled"]),
    mc(3, "Select the missing RSV word: “So King Jeho’ram marched out of _____ at that time and mustered all Israel.”", ["Sama’ria", "Thus", "Jerobo’am", "Jerusalem"], 6),
    word(1, "What missing word belongs in this verse 7 clause: “went and sent word to Jehosh’aphat king of Judah, \"The king of Moab has _____ against me; will you go with me to battle against Moab?\" And he said,”?", "rebelled", 7, ["rebelled"]),
    tf(2, "This wording appears in verse 8: “\"By which way shall we march?\" Jeho’ram answered, \"By the way of the wilderness of Edom.\"”", true, 8),
    blank(3, "with the king of Judah and the king of Edom. And when they had made a _____ march of seven days, there was no water for the army or for the beasts", "circuitous", 9, ["circuitous"]),
    mc(1, "Select the missing RSV word: “Then the king of Israel said, \"Alas! The LORD has _____ these three kings to give them into the hand of Moab.\"”", ["called", "stone", "conquered", "wall"], 10),
    word(2, "What missing word belongs in this verse 11 clause: “here, through whom we may inquire of the LORD?\" Then one of the king of _____ servants answered, \"Eli’sha the son of Shaphat is here, who poured water”?", "Israel’s", 11, ["israels"]),
    tf(3, "This wording appears in verse 12: “Jehosh’aphat said, \"The word of the LORD is with him.\" So the king of Israel and Jehosh’aphat and the king of Edom went down to him.”", true, 12),
    mc(2, "What annual tribute did Mesha king of Moab deliver to Israel’s king?", ["One hundred thousand lambs and the wool of one hundred thousand rams", "Ten thousand sheep and ten thousand goats", "One hundred talents of silver", "Fifty thousand lambs and fifty thousand rams"], 4),
    mc(1, "What did Elisha request before the power of the LORD came upon him?", ["A minstrel", "A scroll", "A bowl of salt", "A new mantle"], 15),
    mc(3, "Why did the Moabites rush toward Israel’s camp?", ["The sunrise made the water appear like blood, so they thought the allied kings had slain one another", "They saw the Israelite army retreating", "They believed the camp was empty after hearing chariots", "They mistook dust for a fire signal"], 23),
  ],
};

export default bank;
