import { mc, blank, word, tf, type ChapterBank, sa } from './types'

const bank: ChapterBank = {
  book: '2 Kings', chapter: 12, tag: 'quiz-v2-2kings-12', rows: [
    mc(1, 'When did Jehoash begin to reign?', ['Jehu’s seventh year', 'Jehu’s twenty-third year', 'Hazael’s first year', 'Athaliah’s sixth year'], 1),
    blank(1, 'he reigned _____ years in Jerusalem.', 'forty', 1, ['40']),
    sa(3, 'Who was Jehoash’s mother?', 'Zibiah of Beer-sheba', 1, ['Zibiah', 'Zibiah of Beersheba']),
    tf(2, 'Jehoash ruled Israel from Samaria.', false, 1, 'Jehoash ruled Judah from Jerusalem for forty years.'),
    mc(2, 'Which regnal details introduce Jehoash?', ['He began in Jehu’s seventh year and reigned forty years', 'He began at seven and reigned six years', 'He began in Joram’s fifth year and reigned eight years', 'He began in Hazael’s reign and ruled one year'], 1),
    word(2, 'From what town was Jehoash’s mother?', 'Beer-sheba', 1, ['Beersheba']),

    mc(1, 'Why did Jehoash do what was right?', ['Jehoiada the priest instructed him', 'Athaliah trained him', 'Hazael advised him', 'He followed Ahab’s house'], 2),
    blank(3, 'Jeho’ash did what was _____ in the eyes of the LORD', 'right', 2),
    sa(2, 'Who taught the king?', 'Jehoiada the priest', 2, ['Jehoiada']),
    tf(1, 'Jehoiada’s instruction shaped Jehoash’s conduct.', true, 2),
    mc(2, 'For how much of his life did Jehoash do right under Jehoiada?', ['All his days', 'Only seven years', 'Until the temple repair', 'Only while young'], 2),
    word(1, 'Who regarded Jehoash’s conduct as right?', 'LORD', 2, ['the LORD', 'God']),

    mc(1, 'What worship sites remained?', ['The high places', 'Baal’s temple in Jerusalem', 'The golden calves only', 'Syria’s altars'], 3),
    blank(2, 'the people continued to sacrifice and burn _____', 'incense', 3),
    sa(1, 'Who continued worshiping at the high places?', 'the people', 3),
    tf(3, 'Jehoash removed every high place.', false, 3, 'The high places were not taken away.'),
    mc(2, 'What limitation remained despite the king’s right conduct?', ['People still worshiped at the high places', 'The temple remained permanently closed', 'Baal’s priest continued ruling Jerusalem', 'No priest provided instruction to the king'], 3),
    sa(2, 'What two activities continued there?', 'sacrifice and burning incense', 3, ['sacrificing and burning incense']),

    mc(1, 'What funds did Jehoash dedicate to the LORD’s house?', ['Sacred assessments and voluntary gifts', 'Only royal taxes', 'Spoils from Syria', 'Money from sin offerings'], 4),
    blank(3, 'the money which a man’s heart _____ him to bring', 'prompts', 4),
    sa(2, 'Where was the money brought?', 'the house of the LORD', 4, ['the temple']),
    tf(1, 'The collection included both assessed and heart-prompted gifts.', true, 4),
    mc(2, 'Which sources made up the repair fund?', ['Sacred assessments and voluntary offerings', 'Only the wages received by temple priests', 'Gold and silver received from King Hazael', 'Only money from guilt and sin offerings'], 4),
    word(1, 'Who established the funding plan?', 'Jehoash', 4, ['King Jehoash']),

    mc(1, 'How were priests initially to collect repair money?', ['Each from his acquaintance', 'Only from the king', 'From foreign merchants', 'From Baal’s priests'], 5),
    blank(2, 'repair the house wherever any _____ of repairs is discovered.', 'need', 5),
    sa(1, 'What was the money’s purpose?', 'repairing the house of the LORD', 5, ['temple repairs']),
    tf(3, 'The priests were initially responsible only for collecting, not repairing.', false, 5, 'They were to collect the money and repair the house wherever damage was found.'),
    mc(2, 'When was work to be done?', ['Whenever a need for repair was discovered', 'Only after Hazael attacked Jerusalem', 'At an interval of exactly seven years', 'Only following the death of the king'], 5),
    sa(2, 'From whom did each priest collect?', 'his acquaintance', 5, ['people he knew']),

    mc(1, 'By what year had the priests still made no repairs?', ['Jehoash’s twenty-third year', 'His seventh year', 'His fortieth year', 'Jehu’s twenty-eighth year'], 6),
    blank(3, 'the priests had made _____ repairs on the house.', 'no', 6),
    sa(2, 'What project had stalled?', 'repairs to the LORD’s house', 6, ['temple repairs']),
    tf(1, 'Many years passed without the planned work being completed.', true, 6),
    mc(2, 'What failure prompted the king to revise the process?', ['No repairs had been made by his twenty-third year', 'The people had completely stopped giving money', 'Hazael had stolen the accumulated repair fund', 'The skilled workmen had refused to accept payment'], 6),
    word(1, 'Whose regnal year dates the delay?', 'Jehoash’s', 6, ['King Jehoash']),

    mc(1, 'Whom did Jehoash summon about the delay?', ['Jehoiada and the other priests', 'Hazael', 'The king’s assassins', 'The workmen only'], 7),
    blank(2, 'hand it over for the _____ of the house.', 'repair', 7, ['repairs']),
    sa(1, 'What collection method did the king stop?', 'priests taking money from acquaintances', 7, ['taking money from the people']),
    tf(3, 'Jehoash praised the priests for completing the temple repairs promptly.', false, 7, 'He summoned them and asked why they had not repaired the house.'),
    mc(2, 'What new accountability did the king impose?', ['Collected money must be handed over for repairs', 'The priests could retain every collection personally', 'The delayed repair project would be canceled', 'The royal palace would take control of worship'], 7),
    word(2, 'Who was the leading priest named?', 'Jehoiada', 7),

    mc(1, 'What did the priests agree to stop doing?', ['Collecting public money and managing repairs', 'Serving in the temple as ordained priests', 'Receiving the money from designated offerings', 'Providing religious instruction to King Jehoash'], 8),
    blank(3, 'they should take no more money from the _____.', 'people', 8),
    tf(2, 'The priests agreed to take no more money from the people and to make no more repairs on the house.', true, 8),
    tf(1, 'The priests accepted the king’s revised arrangement.', true, 8),
    mc(2, 'What two responsibilities were removed from the priests?', ['Public collection and repair management', 'Temple worship and sacrificial service', 'Religious teaching and judicial decisions', 'Guard duty and the singing of psalms'], 8),
    sa(1, 'Who reached this agreement?', 'the priests', 8),

    mc(1, 'What did Jehoiada make for collecting money?', ['A chest with a hole in its lid', 'A large basin fashioned from silver', 'A sealed storage jar formed from clay', 'A locked room serving as the treasury'], 9),
    blank(2, 'and set it beside the _____', 'altar', 9),
    sa(1, 'On which side was the chest placed?', 'the right side as one entered', 9, ['right side']),
    tf(3, 'The collection chest was hidden inside the royal palace.', false, 9, 'It stood beside the altar on the right as one entered the LORD’s house.'),
    mc(2, 'How was the new collection system made visible and controlled?', ['A slotted chest stood beside the altar', 'All money was sent privately into the palace', 'Every priest retained a separate collection box', 'King Hazael personally guarded the treasury'], 9),
    sa(2, 'What alteration was made to the chest?', 'a hole was bored in its lid', 9, ['hole in the lid']),
    mc(3, 'What exact device did Jehoiada create for repair funds?', ['A chest with a bored lid beside the altar', 'A locked room behind the altar', 'A golden bowl at the city gate', 'A bag carried by each priest'], 9),

    mc(1, 'Who counted and bagged the accumulated money?', ['The royal secretary and high priest', 'The carpenters and builders doing the work', 'King Jehoash acting completely by himself', 'The guards stationed at the temple threshold'], 10),
    blank(3, 'they counted and tied up in _____ the money', 'bags', 10),
    sa(2, 'When was the money processed?', 'when much had accumulated in the chest', 10, ['when the chest held much money']),
    tf(1, 'Both royal and priestly officials handled the count.', true, 10),
    mc(2, 'What safeguarded the transfer from collection to construction?', ['Joint counting by royal and priestly officials', 'Secret handling by a single unnamed priest', 'Immediate delivery of the fund to Hazael', 'Allowing the money to pass without a count'], 10),
    sa(1, 'Where was the money found?', 'in the house of the LORD', 10, ['the temple chest']),

    mc(1, 'Who received the weighed repair money?', ['Workmen overseeing the LORD’s house', 'The priests for personal use', 'The king of Syria', 'The city elders'], 11),
    blank(2, 'they paid it out to the carpenters and the _____.', 'builders', 11),
    sa(1, 'What role did the first recipients have?', 'oversight of the temple work', 11, ['oversight of the house']),
    tf(3, 'The repair overseers kept the money instead of paying the workers.', false, 11, 'The overseers paid it to the carpenters and builders working on the house.'),
    mc(2, 'How did money reach individual trades?', ['Overseers received it and paid the workers', 'Each worshiper paid a tradesperson directly', 'Priests compensated them with offering meat', 'The king paid them from his private treasury'], 11),
    sa(2, 'Which two trades were paid from the repair fund?', 'carpenters and builders', 11),

    mc(1, 'Which additional workers were paid?', ['Masons and stonecutters', 'Shepherds and farmers', 'Scribes and singers', 'Soldiers and guards'], 12),
    blank(3, 'as well as to buy timber and quarried _____.', 'stone', 12),
    sa(2, 'What two building materials were purchased?', 'timber and quarried stone', 12),
    tf(1, 'The repair fund covered labor, materials, and other repair expenses.', true, 12),
    mc(2, 'What shows the fund was reserved for practical restoration?', ['It paid workers, materials, and repair expenses', 'It purchased new decorative vessels of gold', 'It financed the expansion of Judah’s army', 'It supplied tribute demanded by a foreign king'], 12),
    sa(1, 'What kind of stone was purchased?', 'quarried stone', 12),

    mc(1, 'What was not made from the repair money?', ['Silver and gold objects for temple service', 'Timber supports required for the building', 'Blocks of quarried stone for reconstruction', 'Wages paid to carpenters and builders'], 13),
    blank(2, 'basins of silver, snuffers, bowls, trumpets, or any _____.', 'vessels', 13),
    sa(1, 'Which two precious metals are named?', 'gold and silver', 13),
    tf(3, 'The repair collection was primarily used to make new gold and silver vessels.', false, 13, 'The money was reserved for the workmen repairing the house, not for new vessels.'),
    mc(2, 'Why does the list of unmade objects matter?', ['Structural repairs took priority over new vessels', 'It proves the temple possessed no vessels at all', 'It records the valuable gifts delivered to Syria', 'It provides a detailed schedule of priestly wages'], 13),
    sa(2, 'Name one silver object not made.', 'a basin', 13, ['basins', 'snuffers', 'bowls', 'trumpets']),

    mc(1, 'Where did the repair money go instead of to vessels?', ['To the workmen repairing the house', 'To Hazael', 'To the priests’ offerings', 'To the palace treasury'], 14),
    blank(3, 'for that was given to the _____', 'workmen', 14),
    sa(2, 'What building were they repairing?', 'the house of the LORD', 14, ['the temple']),
    tf(1, 'The verse reinforces the restricted purpose of the fund.', true, 14),
    mc(2, 'What single priority governed use of the collection?', ['Completion of the temple repairs', 'Production of new gold vessels', 'Payment of Syrian tribute', 'Expansion of the palace'], 14),
    sa(1, 'Who controlled the practical expenditure?', 'the repair workmen', 14, ['workmen']),

    mc(1, 'Why was no accounting demanded from the managers?', ['They dealt honestly', 'The sums were too small', 'The king waived oversight for relatives', 'No records existed'], 15),
    blank(2, 'And they did not ask an accounting from the men into whose hand they delivered the money to pay out to the workmen, for they dealt _____.', 'honestly', 15),
    sa(1, 'To whom did the managers pay out money?', 'the workmen', 15),
    tf(3, 'The managers required constant auditing because they dealt dishonestly.', false, 15, 'No accounting was demanded from them because they dealt honestly.'),
    mc(2, 'What quality underpinned trust in the repair administration?', ['Honesty', 'Royal birth', 'Priestly status alone', 'Military authority'], 15),
    sa(2, 'What was not requested from these men?', 'an accounting', 15, ['accounts']),
    mc(3, 'Why could the repair funds be entrusted without a separate reckoning?', ['The distributors were known to deal honestly', 'The collection chest never contained much money', 'Only Jehoiada was permitted to touch the funds', 'Every workman completed the project without wages'], 15),

    mc(1, 'Which offering money belonged to the priests?', ['Guilt and sin offering money', 'All repair gifts', 'The king’s votive gifts', 'The chest collection'], 16),
    blank(3, 'The money from the guilt offerings and the money from the sin offerings was not brought into the house of the LORD; it _____ to the priests.', 'belonged', 16),
    tf(2, 'The money from the guilt offerings and the sin offerings was brought into the house of the LORD.', false, 16, 'That money was not brought into the house of the LORD; it belonged to the priests.'),
    tf(1, 'Guilt- and sin-offering money remained priestly income.', true, 16),
    mc(2, 'What financial boundary did the verse preserve?', ['Priestly offering money remained outside the repair fund', 'All income received by priests funded construction', 'The king personally confiscated every offering', 'Sin-offering money was delivered as tribute to Syria'], 16),

    mc(1, 'Which city did Hazael capture?', ['Gath', 'Jerusalem', 'Samaria', 'Beer-sheba'], 17),
    blank(2, 'Haz’ael set his face to go up against _____.', 'Jerusalem', 17),
    word(1, 'What kingdom did Hazael rule?', 'Syria', 17),
    tf(3, 'After taking Gath, Hazael abandoned his campaign against Judah.', false, 17, 'He set his face to go up against Jerusalem.'),
    mc(2, 'What sequence increased Judah’s danger?', ['Hazael captured Gath, then targeted Jerusalem', 'Jehoash launched the first attack against Syria', 'The defeated king of Gath invaded Jerusalem', 'Hazael withdrew and abandoned his campaign'], 17),

    mc(1, 'How did Jehoash persuade Hazael to withdraw?', ['Sent sacred gifts and treasury gold', 'Defeated the Syrian army in open battle', 'Transferred possession of Gath to Hazael', 'Summoned the prophet Elisha for assistance'], 18),
    blank(3, 'and sent these to Haz’ael king of _____.', 'Syria', 18),
    sa(2, 'Which two treasuries supplied the gold?', 'the LORD’s house and the king’s house', 18, ['temple and palace treasuries']),
    tf(1, 'Jehoash included both earlier kings’ votive gifts and his own.', true, 18),
    mc(2, 'What was the result of the costly tribute?', ['Hazael went away from Jerusalem', 'Hazael occupied the temple', 'Jehoash lost his throne immediately', 'Syria returned the gifts'], 18),

    mc(1, 'Where were Joash’s other acts recorded?', ['Chronicles of the Kings of Judah', 'Chronicles of Israel', 'Records of Syria', 'Book of Jehoiada'], 19),
    blank(2, 'the Book of the _____ of the Kings of Judah', 'Chronicles', 19),
    word(1, 'Which king’s acts are summarized?', 'Joash’s', 19, ['Joash', 'Jehoash']),
    tf(3, 'The narrator says Joash’s other acts were recorded in Israel’s chronicles.', false, 19, 'They were written in the Book of the Chronicles of the Kings of Judah.'),
    mc(2, 'What information does the closing formula imply exists elsewhere?', ['The rest of Joash’s deeds', 'Only the temple repair accounts', 'Hazael’s biography', 'The priests’ genealogy'], 19),

    mc(1, 'How did Joash die?', ['His servants conspired and killed him', 'Hazael killed him in battle', 'He died peacefully', 'Jehoiada executed him'], 20),
    blank(3, 'slew Jo’ash in the house of _____.', 'Millo', 20),
    sa(2, 'Where did the route from Millo lead?', 'down to Silla', 20, ['Silla']),
    tf(1, 'Joash’s death resulted from an internal conspiracy.', true, 20),
    mc(2, 'Who initiated the plot against the king?', ['His own servants', 'The Syrian army', 'The priests', 'The people of Gath'], 20),

    mc(1, 'Which two servants struck Joash down?', ['Jozacar and Jehozabad', 'Jehoiada and Hazael', 'Jehu and Jehoahaz', 'Mattan and Shomer'], 21),
    blank(2, 'Amazi’ah his son reigned in his _____.', 'stead', 21),
    sa(1, 'Where was Joash buried?', 'the city of David', 21, ['City of David']),
    tf(3, 'Joash’s assassins divided Judah instead of allowing a royal successor.', false, 21, 'Joash was buried with his fathers, and his son Amaziah reigned in his place.'),
    mc(2, 'How did the royal succession continue after the assassination?', ['Joash was buried and his son Amaziah reigned', 'Syria installed Hazael upon Judah’s throne', 'The assassins divided the kingdom among themselves', 'Jehoiada returned to govern Judah as priest-king'], 21),
  ],
}

export default bank
