import { mc, blank, word, tf, type ChapterBank, sa } from './types'

const bank: ChapterBank = {
  book: '2 Kings', chapter: 16, tag: 'quiz-v2-2kings-16', rows: [
    mc(1, 'Who began reigning over Judah in Pekah’s seventeenth year?', ['Ahaz son of Jotham', 'Hezekiah', 'Rezin', 'Uriah'], 1),
    blank(1, 'In the seventeenth year of Pekah the son of _____, Ahaz the son of Jotham, king of Judah, began to reign.', 'Remali’ah', 1, ['Remaliah']),
    word(3, 'Who was Ahaz’s father?', 'Jotham', 1),
    tf(2, 'Ahaz succeeded Pekah as king of Israel.', false, 1, 'Ahaz son of Jotham began to reign as king of Judah.'),
    mc(2, 'Which Israelite king dated Ahaz’s accession?', ['Pekah son of Remaliah', 'Hoshea son of Elah', 'Menahem', 'Jeroboam'], 1),
    mc(3, 'What relationship joined Ahaz to the preceding Judean king?', ['He was Jotham’s son', 'He was Jotham’s brother', 'He conquered Jotham', 'He was Jotham’s priest'], 1),

    mc(1, 'How old was Ahaz when he began to reign?', ['Twenty', 'Sixteen', 'Twenty-five', 'Seventeen'], 2),
    blank(3, 'he reigned _____ years in Jerusalem.', 'sixteen', 2, ['16']),
    word(2, 'Where did Ahaz reign?', 'Jerusalem', 2),
    tf(1, 'Ahaz did what was right as David had done.', false, 2, 'He did not do what was right as David had done.'),
    mc(2, 'How does the narrator compare Ahaz with David?', ['Ahaz did not do what was right as David did', 'Ahaz surpassed David', 'Ahaz restored David’s worship', 'Ahaz was unrelated to David'], 2),
    mc(3, 'How long did Ahaz’s reign last?', ['Sixteen years', 'Twenty years', 'Seventeen years', 'Forty years'], 2),

    mc(1, 'Whose ways did Ahaz follow?', ['The kings of Israel’s', 'David’s', 'Hezekiah’s', 'The priests’'], 3),
    blank(2, 'He even burned his _____ as an offering', 'son', 3),
    sa(1, 'What did Ahaz do to his son?', 'burned him as an offering', 3, ['burned his son as an offering']),
    tf(2, 'Ahaz rejected the abominable practices of the nations displaced before Israel.', false, 3, 'He imitated those practices and even burned his son as an offering.'),
    mc(3, 'What especially abominable act showed Ahaz’s apostasy?', ['He burned his son as an offering', 'He dismissed every priest', 'He destroyed Jerusalem', 'He sold his son to Assyria'], 3),
    mc(2, 'Who had driven those nations out before Israel?', ['The LORD', 'The king of Assyria', 'David', 'Pekah'], 3),
    mc(3, 'What contrast does Ahaz’s behavior create?', ['Judah’s king copied the expelled nations', 'Israel copied the worship practiced in Judah’s temple', 'Assyria adopted and enforced the law of Israel', 'Edom restored proper worship within Jerusalem'], 3),

    mc(1, 'Where did Ahaz sacrifice and burn incense?', ['High places, hills, and beneath green trees', 'Only inside the Jerusalem temple', 'Only at the foreign altar in Damascus', 'Only upon the summit of Mount Carmel'], 4),
    blank(2, 'and under every green _____.', 'tree', 4),
    word(1, 'What did Ahaz burn at these sites?', 'incense', 4),
    tf(2, 'Ahaz confined his sacrifices to the Jerusalem temple.', false, 4, 'He sacrificed at high places, hills, and under green trees.'),
    mc(3, 'How widespread was Ahaz’s illicit worship?', ['It spread across elevated and wooded sites', 'It consisted of one isolated act of sacrifice', 'It occurred entirely outside Judah’s borders', 'It remained confined within the royal palace'], 4),

    mc(1, 'Who besieged Ahaz in Jerusalem?', ['Rezin of Syria and Pekah of Israel', 'Assyria and Edom', 'Moab and Ammon', 'Hoshea and Hezekiah'], 5),
    blank(2, 'they besieged Ahaz but could not _____ him.', 'conquer', 5),
    word(1, 'Which city did Rezin and Pekah attack?', 'Jerusalem', 5),
    tf(2, 'The besieging kings succeeded in conquering Ahaz.', false, 5, 'They could not conquer him.'),
    mc(2, 'Which kingdoms joined against Judah?', ['Syria and Israel', 'Assyria and Edom', 'Moab and Philistia', 'Egypt and Israel'], 5),
    mc(3, 'What was the immediate outcome of the siege?', ['Ahaz remained unconquered', 'Jerusalem fell', 'Pekah was captured', 'Rezin surrendered'], 5),

    mc(1, 'Which city did the king of Edom recover?', ['Elath', 'Damascus', 'Jerusalem', 'Samaria'], 6),
    blank(2, 'and drove the men of _____ from Elath', 'Judah', 6),
    sa(1, 'Who came to dwell in Elath?', 'the Edomites', 6, ['Edomites']),
    tf(2, 'Judah retained control of Elath.', false, 6, 'Edom recovered Elath and expelled Judah’s men.'),
    mc(2, 'For which kingdom was Elath recovered?', ['Edom', 'Israel', 'Judah', 'Assyria'], 6),
    mc(3, 'What territorial reversal occurred during Ahaz’s crisis?', ['Edom regained Elath from Judah', 'Judah captured Damascus', 'Israel seized Assyria', 'Syria restored Samaria'], 6),

    mc(1, 'To whom did Ahaz appeal for rescue?', ['Tiglath-pileser king of Assyria', 'Rezin king of Syria', 'Pekah king of Israel', 'The king of Edom'], 7),
    blank(2, 'I am your servant and your _____.', 'son', 7),
    word(1, 'Who carried Ahaz’s appeal?', 'messengers', 7),
    tf(2, 'Ahaz refused to seek Assyrian help against Syria and Israel.', false, 7, 'He called himself Assyria’s servant and son and asked for rescue.'),
    mc(2, 'How did Ahaz describe himself to Assyria’s king?', ['Your servant and your son', 'Your equal and ally', 'Your conqueror', 'Your prophet'], 7),
    mc(3, 'From whose hands did Ahaz seek deliverance?', ['The kings of Syria and Israel', 'Edom and Moab', 'Judah’s priests', 'Egypt and Philistia'], 7),

    mc(1, 'What did Ahaz send to Assyria’s king?', ['Silver and gold as a present', 'The ark', 'His son', 'The bronze altar'], 8),
    blank(2, 'Ahaz also took the silver and _____', 'gold', 8),
    sa(1, 'From which two treasuries did Ahaz take wealth?', 'the LORD’s house and the king’s house', 8, ['temple and palace treasuries']),
    tf(2, 'Some of Ahaz’s payment came from the house of the LORD.', true, 8),
    mc(2, 'Why were sacred and royal treasures removed?', ['To purchase Assyrian aid', 'To rebuild Elath', 'To pay temple workers', 'To ransom Pekah'], 8),
    mc(3, 'What did Ahaz’s gift make Judah’s dependence visible?', ['Sacred and royal wealth purchased Assyrian aid', 'Judah’s treasury financed the Syrian siege', 'Temple wealth was used to enrich the Edomites', 'Assyrian silver restored the treasury of David'], 8),

    mc(1, 'Which city did Assyria capture in response?', ['Damascus', 'Jerusalem', 'Elath', 'Samaria'], 9),
    blank(2, 'carrying its people captive to _____.', 'Kir', 9),
    word(1, 'Whom did the Assyrian king kill?', 'Rezin', 9),
    tf(2, 'The king of Assyria listened to Ahaz.', true, 9),
    mc(2, 'What happened to Damascus’s people?', ['They were carried captive to Kir', 'They moved to Jerusalem', 'They became Judah’s army', 'They remained untouched'], 9),
    mc(3, 'How was the Syrian threat ended?', ['Assyria took Damascus and killed Rezin', 'Ahaz defeated Rezin without foreign assistance', 'Pekah negotiated a lasting treaty of peace', 'The Edomite army intervened to rescue Judah'], 9),

    mc(1, 'What did Ahaz see when he went to Damascus?', ['An altar', 'A palace model', 'A golden calf', 'A chariot'], 10),
    blank(2, 'sent to Uri’ah the priest a _____ of the altar', 'model', 10),
    word(1, 'To which priest did Ahaz send the altar design?', 'Uriah', 10, ['Uri’ah']),
    tf(2, 'The pattern Ahaz sent was exact in all its details.', true, 10),
    mc(2, 'Whom did Ahaz meet in Damascus?', ['Tiglath-pileser, Assyria’s king', 'Pekah, the reigning king of Israel', 'Rezin, the defeated king of Syria', 'Hezekiah, the future king of Judah'], 10),
    mc(3, 'What did Ahaz transmit from Damascus to Jerusalem?', ['A model and pattern of the foreign altar', 'A written copy of Assyrian imperial law', 'The royal throne formerly belonging to Rezin', 'Architectural plans for a new royal palace'], 10),

    mc(1, 'Who built the copied Damascus altar?', ['Uriah the priest', 'Ahaz himself', 'Tiglath-pileser', 'Hezekiah'], 11),
    blank(2, 'in accordance with all that King Ahaz had sent from _____.', 'Damascus', 11),
    sa(1, 'When was the altar ready?', 'before Ahaz arrived from Damascus', 11, ['before the king returned']),
    tf(2, 'Uriah waited for Ahaz to return before beginning the altar.', false, 11, 'He completed it before Ahaz arrived.'),
    mc(2, 'What guided Uriah’s construction?', ['Everything Ahaz sent from Damascus', 'The law of Moses', 'A vision from the LORD', 'Solomon’s original plans'], 11),
    mc(3, 'How faithfully did Uriah reproduce the foreign altar?', ['In accordance with Ahaz’s exact design', 'Only approximately', 'He refused to build it', 'He changed it to match the bronze altar'], 11),
    mc(2, 'Where was the duplicate altar constructed?', ['Jerusalem', 'Damascus', 'Samaria', 'Elath'], 11),
    tf(3, 'The priest complied with the king’s foreign altar instructions.', true, 11),

    mc(1, 'What did Ahaz do after viewing the new altar?', ['Drew near and went up on it', 'Destroyed it', 'Sent it back', 'Asked Uriah to remove it'], 12),
    word(1, 'From where had Ahaz returned?', 'Damascus', 12),
    tf(2, 'Ahaz used the copied altar upon his return.', true, 12),
    mc(3, 'What showed Ahaz’s approval of the new altar?', ['He approached and ascended it', 'He covered it', 'He expelled Uriah', 'He restored the bronze altar'], 12),

    mc(1, 'Which offerings did Ahaz burn on the altar?', ['Burnt and cereal offerings', 'Incense only', 'Peace offerings only', 'No offerings'], 13),
    blank(2, 'and poured his _____ offering', 'drink', 13),
    sa(1, 'What blood did Ahaz throw on the altar?', 'the blood of his peace offerings', 13, ['peace-offering blood']),
    tf(2, 'Ahaz poured a drink offering on the new altar.', true, 13),
    mc(2, 'What range of ritual acts did Ahaz perform?', ['Burning, pouring, and applying blood', 'Prayer only', 'Reading the law', 'Offering incense only'], 13),
    mc(3, 'Which offering accompanied Ahaz’s burnt offering?', ['A cereal offering', 'A guilt offering only', 'Firstfruits only', 'No other offering'], 13),

    mc(1, 'What did Ahaz do with the bronze altar?', ['Moved it north of the copied altar', 'Completely destroyed and melted it down', 'Transported it to the city of Damascus', 'Installed it inside Judah’s royal palace'], 14),
    blank(2, 'and put it on the _____ side of his altar.', 'north', 14),
    sa(1, 'Where had the bronze altar stood?', 'before the LORD', 14),
    tf(2, 'Ahaz displaced the bronze altar from the temple front.', true, 14),
    mc(2, 'What took the bronze altar’s prominent position?', ['Ahaz’s copied altar', 'The ark', 'A golden calf', 'The laver'], 14),
    mc(3, 'Between what two points had the bronze altar been located?', ['Ahaz’s altar and the house of the LORD', 'The palace and city gate', 'The laver and sea', 'The north and south gates'], 14),

    mc(1, 'Whom did Ahaz command about altar use?', ['Uriah the priest', 'Hezekiah', 'Tiglath-pileser', 'Pekah'], 15),
    blank(2, 'Upon the great altar burn the _____ burnt offering', 'morning', 15),
    sa(1, 'What purpose did Ahaz reserve for the bronze altar?', 'for him to inquire by', 15, ['to inquire by']),
    tf(2, 'Ahaz ordered public and royal offerings placed on the great altar.', true, 15),
    mc(2, 'What was to be thrown upon the great altar?', ['The blood of all offerings and sacrifices', 'Only the incense offered each morning', 'The silver collected within the temple', 'The water held within the bronze laver'], 15),
    mc(3, 'How did Ahaz reassign the two altars?', ['Offerings used the great altar; inquiry used the bronze', 'Both altars were dismantled and destroyed', 'Only priests could approach the Damascus altar', 'Every form of sacrifice at the temple ceased'], 15),

    mc(1, 'How did Uriah respond to Ahaz’s commands?', ['He did all of them', 'He refused', 'He appealed to Assyria', 'He fled Jerusalem'], 16),
    word(1, 'Who gave Uriah these commands?', 'Ahaz', 16, ['King Ahaz']),
    tf(2, 'Uriah resisted the king’s altar changes.', false, 16, 'He did all that Ahaz commanded.'),
    mc(3, 'What does Uriah’s response demonstrate?', ['Complete compliance with Ahaz’s orders', 'Secret opposition', 'Ignorance of the orders', 'A return to Mosaic worship'], 16),

    mc(1, 'What did Ahaz remove from the stands?', ['The laver', 'The altar', 'The ark', 'The lampstands'], 17),
    blank(2, 'he took down the sea from off the bronze _____.', 'oxen', 17),
    sa(1, 'What supported the sea after Ahaz’s change?', 'a pediment of stone', 17, ['stone pediment']),
    tf(2, 'Ahaz cut off the frames of the stands.', true, 17),
    mc(2, 'What material were the original oxen?', ['Bronze', 'Gold', 'Stone', 'Wood'], 17),
    mc(3, 'How did Ahaz alter the temple furnishings?', ['He stripped the stands and moved the sea onto stone', 'He restored the furnishings to Solomon’s arrangement', 'He added additional bronze oxen beneath the sea', 'He sent the bronze sea away as tribute to Assyria'], 17),

    mc(1, 'Why did Ahaz remove royal structures from the LORD’s house?', ['Because of the king of Assyria', 'Because of Rezin', 'Because of fire', 'Because Hezekiah asked'], 18),
    blank(2, 'the covered way for the _____', 'sabbath', 18),
    sa(1, 'What royal access did Ahaz remove?', 'the outer entrance for the king', 18, ['outer royal entrance']),
    tf(2, 'The covered sabbath way had been built inside the royal palace.', false, 18, 'The text places the covered sabbath way inside the house of the LORD.'),
    mc(2, 'Which two structures were removed?', ['The sabbath way and the king’s outer entrance', 'The bronze altar and the covenant ark', 'The fortified gates surrounding Jerusalem', 'The palace treasury and the entire temple'], 18),
    mc(3, 'Whose influence drove Ahaz’s architectural changes?', ['The Assyrian king’s', 'Uriah’s', 'Pekah’s', 'David’s'], 18),

    mc(1, 'Where were Ahaz’s remaining acts recorded?', ['Chronicles of the Kings of Judah', 'Chronicles of Israel', 'Assyrian annals', 'Book of Uriah'], 19),
    blank(2, 'the rest of the acts of _____ which he did', 'Ahaz', 19),
    word(1, 'Which kingdom’s royal record is cited?', 'Judah', 19),
    tf(2, 'The narrator refers readers to Judah’s chronicles.', true, 19),
    mc(2, 'What information does the cited source contain?', ['Ahaz’s remaining acts', 'Only Uriah’s genealogy', 'Assyria’s laws', 'Rezin’s burial'], 19),
    mc(3, 'How does the account direct readers to Ahaz’s other deeds?', ['It cites Judah’s royal chronicles', 'It supplies a concluding prophetic oracle', 'It reproduces the king’s Assyrian treaty', 'It presents a full inventory of the temple'], 19),

    mc(1, 'Who succeeded Ahaz?', ['His son Hezekiah', 'Jotham', 'Pekah', 'Uriah'], 20),
    blank(2, 'and _____ his son reigned in his stead.', 'Hezeki’ah', 20, ['Hezekiah']),
    sa(1, 'Where was Ahaz buried?', 'the city of David', 20, ['city of David']),
    tf(2, 'Ahaz was buried with his fathers.', true, 20),
    mc(2, 'What phrase reports Ahaz’s death?', ['He slept with his fathers', 'He was carried to Assyria', 'He fell in battle', 'He disappeared'], 20),
    mc(3, 'How did Judah’s succession continue?', ['Hezekiah, Ahaz’s son, took the throne', 'Assyria appointed Uriah', 'Pekah ruled Judah', 'The throne remained empty'], 20),
  ],
}

export default bank
