// 2 Kings 13 — quiz bank (RSV). Four verse-anchored forms per verse.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: "2 Kings",
  chapter: 13,
  tag: "quiz-v2-2kings-13",
  rows: [
    blank(2, "In the twenty-third year of Jo’ash the son of Ahazi’ah, king of Judah, _____ the son of Jehu began to reign over Israel in Sama’ria, and he reigned", "Jeho’ahaz", 1, ["jehoahaz"]),
    mc(3, "Which word correctly completes this RSV wording: “In the twenty-third year of Jo’ash the son of Ahazi’ah, king of Judah, _____ the son of Jehu began to reign over Israel in Sama’ria, and he reigned”", ["Jeho’ahaz", "Nebat", "Jeho’ash", "Abraham"], 1),
    word(1, "In verse 1, what word completes this phrase: “In the twenty-third year of Jo’ash the son of Ahazi’ah, king of Judah, _____ the son of Jehu began to reign over Israel in Sama’ria, and he reigned”?", "Jeho’ahaz", 1, ["jehoahaz"]),
    tf(2, "The RSV states: “In the twenty-third year of Jo’ash the son of Ahazi’ah, king of Judah, Jeho’ahaz the son of Jehu began to reign over Israel in Sama’ria, and he reigned seventeen years.”", true, 1),
    blank(3, "did what was evil in the sight of the LORD, and followed the sins of _____ the son of Nebat, which he made Israel to sin; he did not depart from", "Jerobo’am", 2, ["jeroboam"]),
    mc(1, "Which word correctly completes this RSV wording: “did what was evil in the sight of the LORD, and followed the sins of _____ the son of Nebat, which he made Israel to sin; he did not depart from”", ["Jerobo’am", "Ashe’rah", "LORD’s", "Jeho’ahaz"], 2),
    word(2, "In verse 2, what word completes this phrase: “did what was evil in the sight of the LORD, and followed the sins of _____ the son of Nebat, which he made Israel to sin; he did not depart from”?", "Jerobo’am", 2, ["jeroboam"]),
    tf(3, "The RSV does not state: “He did what was evil in the sight of the LORD, and followed the sins of Jerobo’am the son of Nebat, which he made Israel to sin; he did not depart from them.”", false, 2, "The quoted wording is the RSV text of this verse."),
    blank(1, "continually into the hand of Haz’ael king of Syria and into the hand of _____ the son of Haz’ael.", "Ben-ha’dad", 3, ["ben-hadad"]),
    mc(2, "Which word correctly completes this RSV wording: “continually into the hand of Haz’ael king of Syria and into the hand of _____ the son of Haz’ael.”", ["Ben-ha’dad", "Aphek", "Israel", "Kings"], 3),
    word(3, "In verse 3, what word completes this phrase: “continually into the hand of Haz’ael king of Syria and into the hand of _____ the son of Haz’ael.”?", "Ben-ha’dad", 3, ["ben-hadad"]),
    tf(1, "The RSV states: “And the anger of the LORD was kindled against Israel, and he gave them continually into the hand of Haz’ael king of Syria and into the hand of Ben-ha’dad the son of Haz’ael.”", true, 3),
    blank(2, "Then _____ besought the LORD, and the LORD hearkened to him; for he saw the oppression", "Jeho’ahaz", 4, ["jehoahaz"]),
    mc(3, "Which word correctly completes this RSV wording: “Then _____ besought the LORD, and the LORD hearkened to him; for he saw the oppression”", ["Jeho’ahaz", "Moabites", "Jerobo’am", "Kings"], 4),
    word(1, "In verse 4, what word completes this phrase: “Then _____ besought the LORD, and the LORD hearkened to him; for he saw the oppression”?", "Jeho’ahaz", 4, ["jehoahaz"]),
    tf(2, "The RSV does not state: “Then Jeho’ahaz besought the LORD, and the LORD hearkened to him; for he saw the oppression of Israel, how the king of Syria oppressed them.”", false, 4, "The quoted wording is the RSV text of this verse."),
    blank(3, "(_____ the LORD gave Israel a savior, so that they escaped from the hand of the", "Therefore", 5, ["therefore"]),
    mc(1, "Which word correctly completes this RSV wording: “(_____ the LORD gave Israel a savior, so that they escaped from the hand of the”", ["Therefore", "Judah", "Nevertheless", "Shoot"], 5),
    word(2, "In verse 5, what word completes this phrase: “(_____ the LORD gave Israel a savior, so that they escaped from the hand of the”?", "Therefore", 5, ["therefore"]),
    tf(3, "The RSV states: “(Therefore the LORD gave Israel a savior, so that they escaped from the hand of the Syrians; and the people of Israel dwelt in their homes as formerly.”", true, 5),
    blank(1, "_____ they did not depart from the sins of the house of Jerobo’am, which he", "Nevertheless", 6, ["nevertheless"]),
    mc(2, "Which word correctly completes this RSV wording: “_____ they did not depart from the sins of the house of Jerobo’am, which he”", ["Nevertheless", "Eli’sha", "Ashe’rah", "Haz’ael"], 6),
    word(3, "In verse 6, what word completes this phrase: “_____ they did not depart from the sins of the house of Jerobo’am, which he”?", "Nevertheless", 6, ["nevertheless"]),
    tf(1, "The RSV does not state: “Nevertheless they did not depart from the sins of the house of Jerobo’am, which he made Israel to sin, but walked in them; and the Ashe’rah also remained in Sama’ria.)”", false, 6, "The quoted wording is the RSV text of this verse."),
    blank(2, "For there was not left to _____ an army of more than fifty horsemen and ten chariots and ten thousand", "Jeho’ahaz", 7, ["jehoahaz"]),
    mc(3, "Which word correctly completes this RSV wording: “For there was not left to _____ an army of more than fifty horsemen and ten chariots and ten thousand”", ["Jeho’ahaz", "Chronicles", "Strike", "Sama’ria"], 7),
    word(1, "In verse 7, what word completes this phrase: “For there was not left to _____ an army of more than fifty horsemen and ten chariots and ten thousand”?", "Jeho’ahaz", 7, ["jehoahaz"]),
    tf(2, "The RSV states: “For there was not left to Jeho’ahaz an army of more than fifty horsemen and ten chariots and ten thousand footmen; for the king of Syria had destroyed them and made them like the dust at threshing.”", true, 7),
    blank(3, "all that he did, and his might, are they not written in the Book of the _____ of the Kings of Israel?", "Chronicles", 8, ["chronicles"]),
    mc(1, "Which word correctly completes this RSV wording: “all that he did, and his might, are they not written in the Book of the _____ of the Kings of Israel?”", ["Chronicles", "Jo’ash", "Therefore", "Strike"], 8),
    word(2, "In verse 8, what word completes this phrase: “all that he did, and his might, are they not written in the Book of the _____ of the Kings of Israel?”?", "Chronicles", 8, ["chronicles"]),
    tf(3, "The RSV does not state: “Now the rest of the acts of Jeho’ahaz and all that he did, and his might, are they not written in the Book of the Chronicles of the Kings of Israel?”", false, 8, "The quoted wording is the RSV text of this verse."),
    blank(1, "So _____ slept with his fathers, and they buried him in Sama’ria; and Jo’ash his", "Jeho’ahaz", 9, ["jehoahaz"]),
    mc(2, "Which word correctly completes this RSV wording: “So _____ slept with his fathers, and they buried him in Sama’ria; and Jo’ash his”", ["Jeho’ahaz", "Isaac", "Haz’ael", "Amazi’ah"], 9),
    word(3, "In verse 9, what word completes this phrase: “So _____ slept with his fathers, and they buried him in Sama’ria; and Jo’ash his”?", "Jeho’ahaz", 9, ["jehoahaz"]),
    tf(1, "The RSV states: “So Jeho’ahaz slept with his fathers, and they buried him in Sama’ria; and Jo’ash his son reigned in his stead.”", true, 9),
    blank(2, "In the thirty-seventh year of Jo’ash king of Judah Jeho’ash the son of _____ began to reign over Israel in Sama’ria, and he reigned sixteen years.", "Jeho’ahaz", 10, ["jehoahaz"]),
    mc(3, "Which word correctly completes this RSV wording: “In the thirty-seventh year of Jo’ash king of Judah Jeho’ash the son of _____ began to reign over Israel in Sama’ria, and he reigned sixteen years.”", ["Jeho’ahaz", "Israel", "Book", "Aphek"], 10),
    word(1, "In verse 10, what word completes this phrase: “In the thirty-seventh year of Jo’ash king of Judah Jeho’ash the son of _____ began to reign over Israel in Sama’ria, and he reigned sixteen years.”?", "Jeho’ahaz", 10, ["jehoahaz"]),
    tf(2, "The RSV does not state: “In the thirty-seventh year of Jo’ash king of Judah Jeho’ash the son of Jeho’ahaz began to reign over Israel in Sama’ria, and he reigned sixteen years.”", false, 10, "The quoted wording is the RSV text of this verse."),
    blank(3, "evil in the sight of the LORD; he did not depart from all the sins of _____ the son of Nebat, which he made Israel to sin, but he walked in them.", "Jerobo’am", 11, ["jeroboam"]),
    mc(1, "Which word correctly completes this RSV wording: “evil in the sight of the LORD; he did not depart from all the sins of _____ the son of Nebat, which he made Israel to sin, but he walked in them.”", ["Jerobo’am", "Therefore", "Draw", "Jo’ash"], 11),
    word(2, "In verse 11, what word completes this phrase: “evil in the sight of the LORD; he did not depart from all the sins of _____ the son of Nebat, which he made Israel to sin, but he walked in them.”?", "Jerobo’am", 11, ["jeroboam"]),
    tf(3, "The RSV states: “He also did what was evil in the sight of the LORD; he did not depart from all the sins of Jerobo’am the son of Nebat, which he made Israel to sin, but he walked in them.”", true, 11),
    blank(1, "against Amazi’ah king of Judah, are they not written in the Book of the _____ of the Kings of Israel?", "Chronicles", 12, ["chronicles"]),
    mc(2, "Which word correctly completes this RSV wording: “against Amazi’ah king of Judah, are they not written in the Book of the _____ of the Kings of Israel?”", ["Chronicles", "Jo’ash", "Therefore", "Strike"], 12),
    word(3, "In verse 12, what word completes this phrase: “against Amazi’ah king of Judah, are they not written in the Book of the _____ of the Kings of Israel?”?", "Chronicles", 12, ["chronicles"]),
    tf(1, "The RSV does not state: “Now the rest of the acts of Jo’ash, and all that he did, and the might with which he fought against Amazi’ah king of Judah, are they not written in the Book of the Chronicles of the Kings of Israel?”", false, 12, "The quoted wording is the RSV text of this verse."),
    blank(2, "So Jo’ash slept with his fathers, and _____ sat upon his throne; and Jo’ash was buried in Sama’ria with the kings", "Jerobo’am", 13, ["jeroboam"]),
    mc(3, "Which word correctly completes this RSV wording: “So Jo’ash slept with his fathers, and _____ sat upon his throne; and Jo’ash was buried in Sama’ria with the kings”", ["Jerobo’am", "LORD’s", "Jeho’ahaz", "Ashe’rah"], 13),
    word(1, "In verse 13, what word completes this phrase: “So Jo’ash slept with his fathers, and _____ sat upon his throne; and Jo’ash was buried in Sama’ria with the kings”?", "Jerobo’am", 13, ["jeroboam"]),
    tf(2, "The RSV states: “So Jo’ash slept with his fathers, and Jerobo’am sat upon his throne; and Jo’ash was buried in Sama’ria with the kings of Israel.”", true, 13),
    blank(3, "Now when _____ had fallen sick with the illness of which he was to die, Jo’ash king of", "Eli’sha", 14, ["elisha"]),
    mc(1, "Which word correctly completes this RSV wording: “Now when _____ had fallen sick with the illness of which he was to die, Jo’ash king of”", ["Eli’sha", "Three", "Syria", "Take"], 14),
    word(2, "In verse 14, what word completes this phrase: “Now when _____ had fallen sick with the illness of which he was to die, Jo’ash king of”?", "Eli’sha", 14, ["elisha"]),
    tf(3, "The RSV does not state: “Now when Eli’sha had fallen sick with the illness of which he was to die, Jo’ash king of Israel went down to him, and wept before him, crying, \"My father, my father! The chariots of Israel and its horsemen!\"”", false, 14, "The quoted wording is the RSV text of this verse."),
    blank(1, "And _____ said to him, \"Take a bow and arrows\"; so he took a bow and arrows.", "Eli’sha", 15, ["elisha"]),
    mc(2, "Which word correctly completes this RSV wording: “And _____ said to him, \"Take a bow and arrows\"; so he took a bow and arrows.”", ["Eli’sha", "Sama’ria", "Chronicles", "Moabites"], 15),
    word(3, "In verse 15, what word completes this phrase: “And _____ said to him, \"Take a bow and arrows\"; so he took a bow and arrows.”?", "Eli’sha", 15, ["elisha"]),
    tf(1, "The RSV states: “And Eli’sha said to him, \"Take a bow and arrows\"; so he took a bow and arrows.”", true, 15),
    blank(2, "Then he said to the king of Israel, \"Draw the bow\"; and he drew it. And _____ laid his hands upon the king’s hands.", "Eli’sha", 16, ["elisha"]),
    mc(3, "Which word correctly completes this RSV wording: “Then he said to the king of Israel, \"Draw the bow\"; and he drew it. And _____ laid his hands upon the king’s hands.”", ["Eli’sha", "Syrians", "Shoot", "Judah"], 16),
    word(1, "In verse 16, what word completes this phrase: “Then he said to the king of Israel, \"Draw the bow\"; and he drew it. And _____ laid his hands upon the king’s hands.”?", "Eli’sha", 16, ["elisha"]),
    tf(2, "The RSV does not state: “Then he said to the king of Israel, \"Draw the bow\"; and he drew it. And Eli’sha laid his hands upon the king’s hands.”", false, 16, "The quoted wording is the RSV text of this verse."),
    blank(3, "And he said, \"Open the window eastward\"; and he opened it. Then _____ said, \"Shoot\"; and he shot. And he said, \"The LORD’s arrow of victory,", "Eli’sha", 17, ["elisha"]),
    mc(1, "Which word correctly completes this RSV wording: “And he said, \"Open the window eastward\"; and he opened it. Then _____ said, \"Shoot\"; and he shot. And he said, \"The LORD’s arrow of victory,”", ["Eli’sha", "Amazi’ah", "Jacob", "Haz’ael"], 17),
    word(2, "In verse 17, what word completes this phrase: “And he said, \"Open the window eastward\"; and he opened it. Then _____ said, \"Shoot\"; and he shot. And he said, \"The LORD’s arrow of victory,”?", "Eli’sha", 17, ["elisha"]),
    tf(3, "The RSV states: “And he said, \"Open the window eastward\"; and he opened it. Then Eli’sha said, \"Shoot\"; and he shot. And he said, \"The LORD’s arrow of victory, the arrow of victory over Syria! For you shall fight the Syrians in Aphek until you have made an end of them.\"”", true, 17),
    blank(1, "said, \"Take the arrows\"; and he took them. And he said to the king of _____, \"Strike the ground with them\"; and he struck three times, and stopped.", "Israel", 18, ["israel"]),
    mc(2, "Which word correctly completes this RSV wording: “said, \"Take the arrows\"; and he took them. And he said to the king of _____, \"Strike the ground with them\"; and he struck three times, and stopped.”", ["Israel", "Jacob", "Syria", "Take"], 18),
    word(3, "In verse 18, what word completes this phrase: “said, \"Take the arrows\"; and he took them. And he said to the king of _____, \"Strike the ground with them\"; and he struck three times, and stopped.”?", "Israel", 18, ["israel"]),
    tf(1, "The RSV does not state: “And he said, \"Take the arrows\"; and he took them. And he said to the king of Israel, \"Strike the ground with them\"; and he struck three times, and stopped.”", false, 18, "The quoted wording is the RSV text of this verse."),
    blank(2, "should have struck five or six times; then you would have struck down _____ until you had made an end of it, but now you will strike down Syria only", "Syria", 19, ["syria"]),
    mc(3, "Which word correctly completes this RSV wording: “should have struck five or six times; then you would have struck down _____ until you had made an end of it, but now you will strike down Syria only”", ["Syria", "Israel", "Kings", "Moabites"], 19),
    word(1, "In verse 19, what word completes this phrase: “should have struck five or six times; then you would have struck down _____ until you had made an end of it, but now you will strike down Syria only”?", "Syria", 19, ["syria"]),
    tf(2, "The RSV states: “Then the man of God was angry with him, and said, \"You should have struck five or six times; then you would have struck down Syria until you had made an end of it, but now you will strike down Syria only three times.\"”", true, 19),
    blank(3, "So Eli’sha died, and they buried him. Now bands of _____ used to invade the land in the spring of the year.", "Moabites", 20, ["moabites"]),
    mc(1, "Which word correctly completes this RSV wording: “So Eli’sha died, and they buried him. Now bands of _____ used to invade the land in the spring of the year.”", ["Moabites", "Nebat", "Jeho’ash", "Isaac"], 20),
    word(2, "In verse 20, what word completes this phrase: “So Eli’sha died, and they buried him. Now bands of _____ used to invade the land in the spring of the year.”?", "Moabites", 20, ["moabites"]),
    tf(3, "The RSV does not state: “So Eli’sha died, and they buried him. Now bands of Moabites used to invade the land in the spring of the year.”", false, 20, "The quoted wording is the RSV text of this verse."),
    blank(1, "lo, a marauding band was seen and the man was cast into the grave of _____; and as soon as the man touched the bones of Eli’sha, he revived, and", "Eli’sha", 21, ["elisha"]),
    mc(2, "Which word correctly completes this RSV wording: “lo, a marauding band was seen and the man was cast into the grave of _____; and as soon as the man touched the bones of Eli’sha, he revived, and”", ["Eli’sha", "Ashe’rah", "Aphek", "Jehu"], 21),
    word(3, "In verse 21, what word completes this phrase: “lo, a marauding band was seen and the man was cast into the grave of _____; and as soon as the man touched the bones of Eli’sha, he revived, and”?", "Eli’sha", 21, ["elisha"]),
    tf(1, "The RSV states: “And as a man was being buried, lo, a marauding band was seen and the man was cast into the grave of Eli’sha; and as soon as the man touched the bones of Eli’sha, he revived, and stood on his feet.”", true, 21),
    blank(2, "Now Haz’ael king of Syria oppressed Israel all the days of _____.", "Jeho’ahaz", 22, ["jehoahaz"]),
    mc(3, "Which word correctly completes this RSV wording: “Now Haz’ael king of Syria oppressed Israel all the days of _____.”", ["Jeho’ahaz", "Draw", "Jo’ash", "Therefore"], 22),
    word(1, "In verse 22, what word completes this phrase: “Now Haz’ael king of Syria oppressed Israel all the days of _____.”?", "Jeho’ahaz", 22, ["jehoahaz"]),
    tf(2, "The RSV does not state: “Now Haz’ael king of Syria oppressed Israel all the days of Jeho’ahaz.”", false, 22, "The quoted wording is the RSV text of this verse."),
    blank(3, "compassion on them, and he turned toward them, because of his covenant with _____, Isaac, and Jacob, and would not destroy them; nor has he cast them from", "Abraham", 23, ["abraham"]),
    mc(1, "Which word correctly completes this RSV wording: “compassion on them, and he turned toward them, because of his covenant with _____, Isaac, and Jacob, and would not destroy them; nor has he cast them from”", ["Abraham", "Moabites", "Jerobo’am", "Kings"], 23),
    word(2, "In verse 23, what word completes this phrase: “compassion on them, and he turned toward them, because of his covenant with _____, Isaac, and Jacob, and would not destroy them; nor has he cast them from”?", "Abraham", 23, ["abraham"]),
    tf(3, "The RSV states: “But the LORD was gracious to them and had compassion on them, and he turned toward them, because of his covenant with Abraham, Isaac, and Jacob, and would not destroy them; nor has he cast them from his presence until now.”", true, 23),
    blank(1, "When Haz’ael king of Syria died, _____ his son became king in his stead.", "Ben-ha’dad", 24, ["ben-hadad"]),
    mc(2, "Which word correctly completes this RSV wording: “When Haz’ael king of Syria died, _____ his son became king in his stead.”", ["Ben-ha’dad", "Jo’ash", "Syrians", "Strike"], 24),
    word(3, "In verse 24, what word completes this phrase: “When Haz’ael king of Syria died, _____ his son became king in his stead.”?", "Ben-ha’dad", 24, ["ben-hadad"]),
    tf(1, "The RSV does not state: “When Haz’ael king of Syria died, Ben-ha’dad his son became king in his stead.”", false, 24, "The quoted wording is the RSV text of this verse."),
    blank(2, "Then Jeho’ash the son of Jeho’ahaz took again from _____ the son of Haz’ael the cities which he had taken from Jeho’ahaz his father", "Ben-ha’dad", 25, ["ben-hadad"]),
    mc(3, "Which word correctly completes this RSV wording: “Then Jeho’ash the son of Jeho’ahaz took again from _____ the son of Haz’ael the cities which he had taken from Jeho’ahaz his father”", ["Ben-ha’dad", "Nebat", "Eli’sha", "Ahazi’ah"], 25),
    word(1, "In verse 25, what word completes this phrase: “Then Jeho’ash the son of Jeho’ahaz took again from _____ the son of Haz’ael the cities which he had taken from Jeho’ahaz his father”?", "Ben-ha’dad", 25, ["ben-hadad"]),
    tf(2, "The RSV states: “Then Jeho’ash the son of Jeho’ahaz took again from Ben-ha’dad the son of Haz’ael the cities which he had taken from Jeho’ahaz his father in war. Three times Jo’ash defeated him and recovered the cities of Israel.”", true, 25),
    blank(1, "In the _____ year of Jo’ash the son of Ahazi’ah, king of Judah, Jeho’ahaz the son of", "twenty-third", 1, ["twenty-third"]),
    mc(2, "Select the missing RSV word: “He did what was evil in the sight of the LORD, and _____ the sins of Jerobo’am the son of Nebat, which he made Israel to sin; he”", ["followed", "homes", "chariots", "slept"], 2),
    word(3, "What missing word belongs in this verse 3 clause: “And the anger of the LORD was kindled against Israel, and he gave them _____ into the hand of Haz’ael king of Syria and into the hand of Ben-ha’dad”?", "continually", 3, ["continually"]),
    tf(1, "This wording appears in verse 4: “Jeho’ahaz besought the LORD, and the LORD hearkened to him; for he saw the oppression of Israel, how the king of Syria oppressed them.”", true, 4),
    blank(2, "hand of the Syrians; and the people of Israel dwelt in their homes as _____.", "formerly", 5, ["formerly"]),
    mc(3, "Select the missing RSV word: “Nevertheless they did not depart from the sins of the house of _____, which he made Israel to sin, but walked in them; and the Ashe’rah also”", ["Jerobo’am", "Jeho’ash", "Abraham", "Nebat"], 6),
    word(1, "What missing word belongs in this verse 7 clause: “and ten chariots and ten thousand footmen; for the king of Syria had _____ them and made them like the dust at threshing.”?", "destroyed", 7, ["destroyed"]),
    tf(2, "This wording appears in verse 8: “Now the rest of the acts of Jeho’ahaz and all that he did, and his might, are they not written in the Book of”", true, 8),
    blank(3, "So Jeho’ahaz slept with his fathers, and they buried him in _____; and Jo’ash his son reigned in his stead.", "Sama’ria", 9, ["samaria"]),
    mc(1, "Select the missing RSV word: “In the _____ year of Jo’ash king of Judah Jeho’ash the son of Jeho’ahaz began to reign”", ["thirty-seventh", "marauding", "Jerusalem", "Israel"], 10),
    word(2, "What missing word belongs in this verse 11 clause: “He also did what was evil in the sight of the LORD; he did not _____ from all the sins of Jerobo’am the son of Nebat, which he made Israel”?", "depart", 11, ["depart"]),
    tf(3, "This wording appears in verse 12: “Jo’ash, and all that he did, and the might with which he fought against Amazi’ah king of Judah, are they not written in the Book of the Chronicles of the”", true, 12),
    blank(1, "fathers, and Jerobo’am sat upon his throne; and Jo’ash was buried in _____ with the kings of Israel.", "Sama’ria", 13, ["samaria"]),
    mc(2, "Select the missing RSV word: “down to him, and wept before him, crying, \"My father, my father! The _____ of Israel and its horsemen!\"”", ["chariots", "laid", "until", "died"], 14),
    word(3, "What missing word belongs in this verse 15 clause: “And Eli’sha said to him, \"Take a bow and _____\"; so he took a bow and arrows.”?", "arrows", 15, ["arrows"]),
    tf(1, "This wording appears in verse 16: “Then he said to the king of Israel, \"Draw the bow\"; and he drew it. And Eli’sha laid his hands upon the king’s”", true, 16),
    blank(2, "And he said, \"Open the window _____\"; and he opened it. Then Eli’sha said, \"Shoot\"; and he shot. And he said,", "eastward", 17, ["eastward"]),
    mc(3, "Select the missing RSV word: “Israel, \"Strike the ground with them\"; and he struck three times, and _____.”", ["stopped", "king", "made", "oppressed"], 18),
    word(1, "What missing word belongs in this verse 19 clause: “Then the man of God was angry with him, and said, \"You _____ have struck five or six times; then you would have struck down Syria until”?", "should", 19, ["should"]),
    tf(2, "This wording appears in verse 20: “So Eli’sha died, and they buried him. Now bands of Moabites used to invade the land”", true, 20),
    mc(3, "Why was Elisha angry when Joash struck the ground only three times?", ["Joash should have struck five or six times and then would have ended Syria", "Joash used the wrong arrows", "Joash struck before opening the window", "Joash refused to take the bow"], 19),
    mc(2, "What happened when a dead man’s body touched Elisha’s bones?", ["The man revived and stood on his feet", "Elisha returned to life", "The grave opened", "The men who buried him fled"], 21),
  ],
};

export default bank;
