// 2 Kings 8 — quiz bank (RSV). Four verse-anchored forms per verse.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: "2 Kings",
  chapter: 8,
  tag: "quiz-v2-2kings-8",
  rows: [
    blank(2, "Now _____ had said to the woman whose son he had restored to life, \"Arise, and depart", "Eli’sha", 1, ["elisha"]),
    mc(3, "Which word correctly completes this RSV wording: “Now _____ had said to the woman whose son he had restored to life, \"Arise, and depart”", ["Eli’sha", "Syria", "Jerusalem", "Omri"], 1),
    word(1, "In verse 1, what word completes this phrase: “Now _____ had said to the woman whose son he had restored to life, \"Arise, and depart”?", "Eli’sha", 1, ["elisha"]),
    tf(2, "The RSV states: “Now Eli’sha had said to the woman whose son he had restored to life, \"Arise, and depart with your household, and sojourn wherever you can; for the LORD has called for a famine, and it will come upon the land for seven years.\"”", true, 1),
    blank(3, "of God; she went with her household and sojourned in the land of the _____ seven years.", "Philistines", 2, ["philistines"]),
    mc(1, "Which word correctly completes this RSV wording: “of God; she went with her household and sojourned in the land of the _____ seven years.”", ["Philistines", "Ahazi’ah", "Because", "Syrians"], 2),
    word(2, "In verse 2, what word completes this phrase: “of God; she went with her household and sojourned in the land of the _____ seven years.”?", "Philistines", 2, ["philistines"]),
    tf(3, "The RSV does not state: “So the woman arose, and did according to the word of the man of God; she went with her household and sojourned in the land of the Philistines seven years.”", false, 2, "The quoted wording is the RSV text of this verse."),
    blank(1, "end of the seven years, when the woman returned from the land of the _____, she went forth to appeal to the king for her house and her land.", "Philistines", 3, ["philistines"]),
    mc(2, "Which word correctly completes this RSV wording: “end of the seven years, when the woman returned from the land of the _____, she went forth to appeal to the king for her house and her land.”", ["Philistines", "Restore", "Chronicles", "Haz’ael"], 3),
    word(3, "In verse 3, what word completes this phrase: “end of the seven years, when the woman returned from the land of the _____, she went forth to appeal to the king for her house and her land.”?", "Philistines", 3, ["philistines"]),
    tf(1, "The RSV states: “And at the end of the seven years, when the woman returned from the land of the Philistines, she went forth to appeal to the king for her house and her land.”", true, 3),
    blank(2, "Now the king was talking with _____ the servant of the man of God, saying, \"Tell me all the great things that", "Geha’zi", 4, ["gehazi"]),
    mc(3, "Which word correctly completes this RSV wording: “Now the king was talking with _____ the servant of the man of God, saying, \"Tell me all the great things that”", ["Geha’zi", "Athali’ah", "Damascus", "Jehosh’aphat"], 4),
    word(1, "In verse 4, what word completes this phrase: “Now the king was talking with _____ the servant of the man of God, saying, \"Tell me all the great things that”?", "Geha’zi", 4, ["gehazi"]),
    tf(2, "The RSV does not state: “Now the king was talking with Geha’zi the servant of the man of God, saying, \"Tell me all the great things that Eli’sha has done.\"”", false, 4, "The quoted wording is the RSV text of this verse."),
    blank(3, "And while he was telling the king how _____ had restored the dead to life, behold, the woman whose son he had restored", "Eli’sha", 5, ["elisha"]),
    mc(1, "Which word correctly completes this RSV wording: “And while he was telling the king how _____ had restored the dead to life, behold, the woman whose son he had restored”", ["Eli’sha", "Philistines", "Israel", "Libnah"], 5),
    word(2, "In verse 5, what word completes this phrase: “And while he was telling the king how _____ had restored the dead to life, behold, the woman whose son he had restored”?", "Eli’sha", 5, ["elisha"]),
    tf(3, "The RSV states: “And while he was telling the king how Eli’sha had restored the dead to life, behold, the woman whose son he had restored to life appealed to the king for her house and her land. And Geha’zi said, \"My lord, O king, here is the woman, and here is her son whom Eli’sha restored to life.\"”", true, 5),
    blank(1, "woman, she told him. So the king appointed an official for her, saying, \"_____ all that was hers, together with all the produce of the fields from the", "Restore", 6, ["restore"]),
    mc(2, "Which word correctly completes this RSV wording: “woman, she told him. So the king appointed an official for her, saying, \"_____ all that was hers, together with all the produce of the fields from the”", ["Restore", "Haz’ael", "David", "Syrians"], 6),
    word(3, "In verse 6, what word completes this phrase: “woman, she told him. So the king appointed an official for her, saying, \"_____ all that was hers, together with all the produce of the fields from the”?", "Restore", 6, ["restore"]),
    tf(1, "The RSV does not state: “And when the king asked the woman, she told him. So the king appointed an official for her, saying, \"Restore all that was hers, together with all the produce of the fields from the day that she left the land until now.\"”", false, 6, "The quoted wording is the RSV text of this verse."),
    blank(2, "Now Eli’sha came to Damascus. _____ the king of Syria was sick; and when it was told him, \"The man of God", "Ben-ha’dad", 7, ["ben-hadad"]),
    mc(3, "Which word correctly completes this RSV wording: “Now Eli’sha came to Damascus. _____ the king of Syria was sick; and when it was told him, \"The man of God”", ["Ben-ha’dad", "Kings", "Restore", "Jerusalem"], 7),
    word(1, "In verse 7, what word completes this phrase: “Now Eli’sha came to Damascus. _____ the king of Syria was sick; and when it was told him, \"The man of God”?", "Ben-ha’dad", 7, ["ben-hadad"]),
    tf(2, "The RSV states: “Now Eli’sha came to Damascus. Ben-ha’dad the king of Syria was sick; and when it was told him, \"The man of God has come here,\"”", true, 7),
    blank(3, "the king said to _____, \"Take a present with you and go to meet the man of God, and inquire of", "Haz’ael", 8, ["hazael"]),
    mc(1, "Which word correctly completes this RSV wording: “the king said to _____, \"Take a present with you and go to meet the man of God, and inquire of”", ["Haz’ael", "E’domites", "Ramah", "Shall"], 8),
    word(2, "In verse 8, what word completes this phrase: “the king said to _____, \"Take a present with you and go to meet the man of God, and inquire of”?", "Haz’ael", 8, ["hazael"]),
    tf(3, "The RSV does not state: “the king said to Haz’ael, \"Take a present with you and go to meet the man of God, and inquire of the LORD through him, saying, `Shall I recover from this sickness?’\"”", false, 8, "The quoted wording is the RSV text of this verse."),
    blank(1, "forty camel loads. When he came and stood before him, he said, \"Your son _____ king of Syria has sent me to you, saying, `Shall I recover from this sickness?’\"", "Ben-ha’dad", 9, ["ben-hadad"]),
    mc(2, "Which word correctly completes this RSV wording: “forty camel loads. When he came and stood before him, he said, \"Your son _____ king of Syria has sent me to you, saying, `Shall I recover from this sickness?’\"”", ["Ben-ha’dad", "Haz’ael", "E’domites", "Arise"], 9),
    word(3, "In verse 9, what word completes this phrase: “forty camel loads. When he came and stood before him, he said, \"Your son _____ king of Syria has sent me to you, saying, `Shall I recover from this sickness?’\"”?", "Ben-ha’dad", 9, ["ben-hadad"]),
    tf(1, "The RSV states: “So Haz’ael went to meet him, and took a present with him, all kinds of goods of Damascus, forty camel loads. When he came and stood before him, he said, \"Your son Ben-ha’dad king of Syria has sent me to you, saying, `Shall I recover from this sickness?’\"”", true, 9),
    blank(2, "And _____ said to him, \"Go, say to him, `You shall certainly recover’; but the LORD", "Eli’sha", 10, ["elisha"]),
    mc(3, "Which word correctly completes this RSV wording: “And _____ said to him, \"Go, say to him, `You shall certainly recover’; but the LORD”", ["Eli’sha", "Geha’zi", "Joram", "Book"], 10),
    word(1, "In verse 10, what word completes this phrase: “And _____ said to him, \"Go, say to him, `You shall certainly recover’; but the LORD”?", "Eli’sha", 10, ["elisha"]),
    tf(2, "The RSV does not state: “And Eli’sha said to him, \"Go, say to him, `You shall certainly recover’; but the LORD has shown me that he shall certainly die.\"”", false, 10, "The quoted wording is the RSV text of this verse."),
    blank(3, "And he fixed his gaze and stared at him, until he was _____. And the man of God wept.", "ashamed", 11, ["ashamed"]),
    mc(1, "Which word correctly completes this RSV wording: “And he fixed his gaze and stared at him, until he was _____. And the man of God wept.”", ["ashamed", "young", "departed", "stead"], 11),
    word(2, "In verse 11, what word completes this phrase: “And he fixed his gaze and stared at him, until he was _____. And the man of God wept.”?", "ashamed", 11, ["ashamed"]),
    tf(3, "The RSV states: “And he fixed his gaze and stared at him, until he was ashamed. And the man of God wept.”", true, 11),
    blank(1, "And _____ said, \"Why does my lord weep?\" He answered, \"Because I know the evil that", "Haz’ael", 12, ["hazael"]),
    mc(2, "Which word correctly completes this RSV wording: “And _____ said, \"Why does my lord weep?\" He answered, \"Because I know the evil that”", ["Haz’ael", "Jehosh’aphat", "Ahazi’ah", "Tell"], 12),
    word(3, "In verse 12, what word completes this phrase: “And _____ said, \"Why does my lord weep?\" He answered, \"Because I know the evil that”?", "Haz’ael", 12, ["hazael"]),
    tf(1, "The RSV does not state: “And Haz’ael said, \"Why does my lord weep?\" He answered, \"Because I know the evil that you will do to the people of Israel; you will set on fire their fortresses, and you will slay their young men with the sword, and dash in pieces their little ones, and rip up their women with child.\"”", false, 12, "The quoted wording is the RSV text of this verse."),
    blank(2, "And _____ said, \"What is your servant, who is but a dog, that he should do this", "Haz’ael", 13, ["hazael"]),
    mc(3, "Which word correctly completes this RSV wording: “And _____ said, \"What is your servant, who is but a dog, that he should do this”", ["Haz’ael", "Libnah", "Eli’sha", "Because"], 13),
    word(1, "In verse 13, what word completes this phrase: “And _____ said, \"What is your servant, who is but a dog, that he should do this”?", "Haz’ael", 13, ["hazael"]),
    tf(2, "The RSV states: “And Haz’ael said, \"What is your servant, who is but a dog, that he should do this great thing?\" Eli’sha answered, \"The LORD has shown me that you are to be king over Syria.\"”", true, 13),
    blank(3, "Then he departed from _____, and came to his master, who said to him, \"What did Eli’sha say to you?\"", "Eli’sha", 14, ["elisha"]),
    mc(1, "Which word correctly completes this RSV wording: “Then he departed from _____, and came to his master, who said to him, \"What did Eli’sha say to you?\"”", ["Eli’sha", "Syrians", "Syria", "Jerusalem"], 14),
    word(2, "In verse 14, what word completes this phrase: “Then he departed from _____, and came to his master, who said to him, \"What did Eli’sha say to you?\"”?", "Eli’sha", 14, ["elisha"]),
    tf(3, "The RSV does not state: “Then he departed from Eli’sha, and came to his master, who said to him, \"What did Eli’sha say to you?\" And he answered, \"He told me that you would certainly recover.\"”", false, 14, "The quoted wording is the RSV text of this verse."),
    blank(1, "and dipped it in water and spread it over his face, till he died. And _____ became king in his stead.", "Haz’ael", 15, ["hazael"]),
    mc(2, "Which word correctly completes this RSV wording: “and dipped it in water and spread it over his face, till he died. And _____ became king in his stead.”", ["Haz’ael", "Geha’zi", "Ahab", "Chronicles"], 15),
    word(3, "In verse 15, what word completes this phrase: “and dipped it in water and spread it over his face, till he died. And _____ became king in his stead.”?", "Haz’ael", 15, ["hazael"]),
    tf(1, "The RSV states: “But on the morrow he took the coverlet and dipped it in water and spread it over his face, till he died. And Haz’ael became king in his stead.”", true, 15),
    blank(2, "fifth year of Joram the son of Ahab, king of Israel, Jeho’ram the son of _____, king of Judah, began to reign.", "Jehosh’aphat", 16, ["jehoshaphat"]),
    mc(3, "Which word correctly completes this RSV wording: “fifth year of Joram the son of Ahab, king of Israel, Jeho’ram the son of _____, king of Judah, began to reign.”", ["Jehosh’aphat", "E’domites", "Damascus", "Syrians"], 16),
    word(1, "In verse 16, what word completes this phrase: “fifth year of Joram the son of Ahab, king of Israel, Jeho’ram the son of _____, king of Judah, began to reign.”?", "Jehosh’aphat", 16, ["jehoshaphat"]),
    tf(2, "The RSV does not state: “In the fifth year of Joram the son of Ahab, king of Israel, Jeho’ram the son of Jehosh’aphat, king of Judah, began to reign.”", false, 16, "The quoted wording is the RSV text of this verse."),
    blank(3, "thirty-two years old when he became king, and he reigned eight years in _____.", "Jerusalem", 17, ["jerusalem"]),
    mc(1, "Which word correctly completes this RSV wording: “thirty-two years old when he became king, and he reigned eight years in _____.”", ["Jerusalem", "Joram", "Chronicles", "Arise"], 17),
    word(2, "In verse 17, what word completes this phrase: “thirty-two years old when he became king, and he reigned eight years in _____.”?", "Jerusalem", 17, ["jerusalem"]),
    tf(3, "The RSV states: “He was thirty-two years old when he became king, and he reigned eight years in Jerusalem.”", true, 17),
    blank(1, "And he walked in the way of the kings of _____, as the house of Ahab had done, for the daughter of Ahab was his wife.", "Israel", 18, ["israel"]),
    mc(2, "Which word correctly completes this RSV wording: “And he walked in the way of the kings of _____, as the house of Ahab had done, for the daughter of Ahab was his wife.”", ["Israel", "Athali’ah", "Restore", "Judah"], 18),
    word(3, "In verse 18, what word completes this phrase: “And he walked in the way of the kings of _____, as the house of Ahab had done, for the daughter of Ahab was his wife.”?", "Israel", 18, ["israel"]),
    tf(1, "The RSV does not state: “And he walked in the way of the kings of Israel, as the house of Ahab had done, for the daughter of Ahab was his wife. And he did what was evil in the sight of the LORD.”", false, 18, "The quoted wording is the RSV text of this verse."),
    blank(2, "Yet the LORD would not destroy _____, for the sake of David his servant, since he promised to give a lamp to", "Judah", 19, ["judah"]),
    mc(3, "Which word correctly completes this RSV wording: “Yet the LORD would not destroy _____, for the sake of David his servant, since he promised to give a lamp to”", ["Judah", "Damascus", "Jerusalem", "Omri"], 19),
    word(1, "In verse 19, what word completes this phrase: “Yet the LORD would not destroy _____, for the sake of David his servant, since he promised to give a lamp to”?", "Judah", 19, ["judah"]),
    tf(2, "The RSV states: “Yet the LORD would not destroy Judah, for the sake of David his servant, since he promised to give a lamp to him and to his sons for ever.”", true, 19),
    blank(3, "In his days Edom revolted from the rule of _____, and set up a king of their own.", "Judah", 20, ["judah"]),
    mc(1, "Which word correctly completes this RSV wording: “In his days Edom revolted from the rule of _____, and set up a king of their own.”", ["Judah", "Israel", "Chronicles", "Geha’zi"], 20),
    word(2, "In verse 20, what word completes this phrase: “In his days Edom revolted from the rule of _____, and set up a king of their own.”?", "Judah", 20, ["judah"]),
    tf(3, "The RSV does not state: “In his days Edom revolted from the rule of Judah, and set up a king of their own.”", false, 20, "The quoted wording is the RSV text of this verse."),
    blank(1, "chariots, and rose by night, and he and his chariot commanders smote the _____ who had surrounded him; but his army fled home.", "E’domites", 21, ["edomites"]),
    mc(2, "Which word correctly completes this RSV wording: “chariots, and rose by night, and he and his chariot commanders smote the _____ who had surrounded him; but his army fled home.”", ["E’domites", "Ben-ha’dad", "Judah", "Omri"], 21),
    word(3, "In verse 21, what word completes this phrase: “chariots, and rose by night, and he and his chariot commanders smote the _____ who had surrounded him; but his army fled home.”?", "E’domites", 21, ["edomites"]),
    tf(1, "The RSV states: “Then Joram passed over to Za’ir with all his chariots, and rose by night, and he and his chariot commanders smote the E’domites who had surrounded him; but his army fled home.”", true, 21),
    blank(2, "So Edom revolted from the rule of Judah to this day. Then _____ revolted at the same time.", "Libnah", 22, ["libnah"]),
    mc(3, "Which word correctly completes this RSV wording: “So Edom revolted from the rule of Judah to this day. Then _____ revolted at the same time.”", ["Libnah", "E’domites", "Eli’sha", "Shall"], 22),
    word(1, "In verse 22, what word completes this phrase: “So Edom revolted from the rule of Judah to this day. Then _____ revolted at the same time.”?", "Libnah", 22, ["libnah"]),
    tf(2, "The RSV does not state: “So Edom revolted from the rule of Judah to this day. Then Libnah revolted at the same time.”", false, 22, "The quoted wording is the RSV text of this verse."),
    blank(3, "of Joram, and all that he did, are they not written in the Book of the _____ of the Kings of Judah?", "Chronicles", 23, ["chronicles"]),
    mc(1, "Which word correctly completes this RSV wording: “of Joram, and all that he did, are they not written in the Book of the _____ of the Kings of Judah?”", ["Chronicles", "Kings", "Restore", "Judah"], 23),
    word(2, "In verse 23, what word completes this phrase: “of Joram, and all that he did, are they not written in the Book of the _____ of the Kings of Judah?”?", "Chronicles", 23, ["chronicles"]),
    tf(3, "The RSV states: “Now the rest of the acts of Joram, and all that he did, are they not written in the Book of the Chronicles of the Kings of Judah?”", true, 23),
    blank(1, "his fathers, and was buried with his fathers in the city of David; and _____ his son reigned in his stead.", "Ahazi’ah", 24, ["ahaziah"]),
    mc(2, "Which word correctly completes this RSV wording: “his fathers, and was buried with his fathers in the city of David; and _____ his son reigned in his stead.”", ["Ahazi’ah", "Athali’ah", "Tell", "Ahab"], 24),
    word(3, "In verse 24, what word completes this phrase: “his fathers, and was buried with his fathers in the city of David; and _____ his son reigned in his stead.”?", "Ahazi’ah", 24, ["ahaziah"]),
    tf(1, "The RSV does not state: “So Joram slept with his fathers, and was buried with his fathers in the city of David; and Ahazi’ah his son reigned in his stead.”", false, 24, "The quoted wording is the RSV text of this verse."),
    blank(2, "In the twelfth year of Joram the son of Ahab, king of Israel, _____ the son of Jeho’ram, king of Judah, began to reign.", "Ahazi’ah", 25, ["ahaziah"]),
    mc(3, "Which word correctly completes this RSV wording: “In the twelfth year of Joram the son of Ahab, king of Israel, _____ the son of Jeho’ram, king of Judah, began to reign.”", ["Ahazi’ah", "Eli’sha", "Shall", "Za’ir"], 25),
    word(1, "In verse 25, what word completes this phrase: “In the twelfth year of Joram the son of Ahab, king of Israel, _____ the son of Jeho’ram, king of Judah, began to reign.”?", "Ahazi’ah", 25, ["ahaziah"]),
    tf(2, "The RSV states: “In the twelfth year of Joram the son of Ahab, king of Israel, Ahazi’ah the son of Jeho’ram, king of Judah, began to reign.”", true, 25),
    blank(3, "twenty-two years old when he began to reign, and he reigned one year in _____. His mother’s name was Athali’ah; she was a granddaughter of Omri king", "Jerusalem", 26, ["jerusalem"]),
    mc(1, "Which word correctly completes this RSV wording: “twenty-two years old when he began to reign, and he reigned one year in _____. His mother’s name was Athali’ah; she was a granddaughter of Omri king”", ["Jerusalem", "Ben-ha’dad", "Judah", "Omri"], 26),
    word(2, "In verse 26, what word completes this phrase: “twenty-two years old when he began to reign, and he reigned one year in _____. His mother’s name was Athali’ah; she was a granddaughter of Omri king”?", "Jerusalem", 26, ["jerusalem"]),
    tf(3, "The RSV does not state: “Ahazi’ah was twenty-two years old when he began to reign, and he reigned one year in Jerusalem. His mother’s name was Athali’ah; she was a granddaughter of Omri king of Israel.”", false, 26, "The quoted wording is the RSV text of this verse."),
    blank(1, "He also walked in the way of the house of _____, and did what was evil in the sight of the LORD, as the house of Ahab", "Ahab", 27, ["ahab"]),
    mc(2, "Which word correctly completes this RSV wording: “He also walked in the way of the house of _____, and did what was evil in the sight of the LORD, as the house of Ahab”", ["Ahab", "Shall", "Libnah", "Arise"], 27),
    word(3, "In verse 27, what word completes this phrase: “He also walked in the way of the house of _____, and did what was evil in the sight of the LORD, as the house of Ahab”?", "Ahab", 27, ["ahab"]),
    tf(1, "The RSV states: “He also walked in the way of the house of Ahab, and did what was evil in the sight of the LORD, as the house of Ahab had done, for he was son-in-law to the house of Ahab.”", true, 27),
    blank(2, "with Joram the son of Ahab to make war against Haz’ael king of Syria at _____, where the Syrians wounded Joram.", "Ramoth-gilead", 28, ["ramoth-gilead"]),
    mc(3, "Which word correctly completes this RSV wording: “with Joram the son of Ahab to make war against Haz’ael king of Syria at _____, where the Syrians wounded Joram.”", ["Ramoth-gilead", "E’domites", "Chronicles", "Ahazi’ah"], 28),
    word(1, "In verse 28, what word completes this phrase: “with Joram the son of Ahab to make war against Haz’ael king of Syria at _____, where the Syrians wounded Joram.”?", "Ramoth-gilead", 28, ["ramoth-gilead"]),
    tf(2, "The RSV does not state: “He went with Joram the son of Ahab to make war against Haz’ael king of Syria at Ramoth-gilead, where the Syrians wounded Joram.”", false, 28, "The quoted wording is the RSV text of this verse."),
    blank(3, "given him at Ramah, when he fought against Haz’ael king of Syria. And _____ the son of Jeho’ram king of Judah went down to see Joram the son of Ahab", "Ahazi’ah", 29, ["ahaziah"]),
    mc(1, "Which word correctly completes this RSV wording: “given him at Ramah, when he fought against Haz’ael king of Syria. And _____ the son of Jeho’ram king of Judah went down to see Joram the son of Ahab”", ["Ahazi’ah", "Athali’ah", "Tell", "Ahab"], 29),
    word(2, "In verse 29, what word completes this phrase: “given him at Ramah, when he fought against Haz’ael king of Syria. And _____ the son of Jeho’ram king of Judah went down to see Joram the son of Ahab”?", "Ahazi’ah", 29, ["ahaziah"]),
    tf(3, "The RSV states: “And King Joram returned to be healed in Jezreel of the wounds which the Syrians had given him at Ramah, when he fought against Haz’ael king of Syria. And Ahazi’ah the son of Jeho’ram king of Judah went down to see Joram the son of Ahab in Jezreel, because he was sick.”", true, 29),
    blank(1, "woman whose son he had restored to life, \"Arise, and depart with your _____, and sojourn wherever you can; for the LORD has called for a famine, and", "household", 1, ["household"]),
    mc(2, "Select the missing RSV word: “So the woman arose, and did _____ to the word of the man of God; she went with her household and sojourned”", ["according", "done", "together", "sickness"], 2),
    word(3, "What missing word belongs in this verse 3 clause: “And at the end of the seven years, when the woman _____ from the land of the Philistines, she went forth to appeal to the king”?", "returned", 3, ["returned"]),
    tf(1, "This wording appears in verse 4: “Now the king was talking with Geha’zi the servant of the man of God, saying, \"Tell me all the great”", true, 4),
    mc(2, "Who was describing Elisha’s restoration of the Shunammite’s son when she returned to appeal to the king?", ["Gehazi, Elisha’s servant", "Hazael", "The king’s servant", "One of the sons of the prophets"], 5),
    mc(3, "Why did Elisha weep while speaking with Hazael?", ["He knew the terrible harm Hazael would do to Israel", "He knew Ben-hadad would recover", "He feared Hazael would kill him", "He had learned that Samaria had fallen"], 12),
    mc(2, "How did Hazael kill Ben-hadad?", ["He dipped a coverlet in water and spread it over the king’s face", "He poisoned the king’s water", "He struck him with a sword", "He set fire to his chamber"], 15),
    mc(3, "Why would the LORD not destroy Judah despite Jehoram’s evil?", ["For David’s sake, because He had promised to give David and his sons a lamp", "Because Jehoram removed the high places", "Because Edom returned to Judah", "Because Elisha interceded for Jerusalem"], 19),
  ],
};

export default bank;
