// 2 Kings 20 — quiz bank (RSV). Four verse-anchored forms per verse.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: "2 Kings",
  chapter: 20,
  tag: "quiz-v2-2kings-20",
  rows: [
    blank(2, "In those days _____ became sick and was at the point of death. And Isaiah the prophet the", "Hezeki’ah", 1, ["hezekiah"]),
    mc(3, "Which word correctly completes this RSV wording: “In those days _____ became sick and was at the point of death. And Isaiah the prophet the”", ["Hezeki’ah", "David’s", "Judah", "Ahaz"], 1),
    word(1, "In verse 1, what word completes this phrase: “In those days _____ became sick and was at the point of death. And Isaiah the prophet the”?", "Hezeki’ah", 1, ["hezekiah"]),
    tf(2, "The RSV states: “In those days Hezeki’ah became sick and was at the point of death. And Isaiah the prophet the son of Amoz came to him, and said to him, \"Thus says the LORD, `Set your house in order; for you shall die, you shall not recover.’\"”", true, 1),
    blank(3, "Then _____ turned his face to the wall, and prayed to the LORD, saying,", "Hezeki’ah", 2, ["hezekiah"]),
    mc(1, "Which word correctly completes this RSV wording: “Then _____ turned his face to the wall, and prayed to the LORD, saying,”", ["Hezeki’ah", "Behold", "David", "Chronicles"], 2),
    word(2, "In verse 2, what word completes this phrase: “Then _____ turned his face to the wall, and prayed to the LORD, saying,”?", "Hezeki’ah", 2, ["hezekiah"]),
    tf(3, "The RSV does not state: “Then Hezeki’ah turned his face to the wall, and prayed to the LORD, saying,”", false, 2, "The quoted wording is the RSV text of this verse."),
    blank(1, "and with a whole heart, and have done what is good in thy sight.\" And _____ wept bitterly.", "Hezeki’ah", 3, ["hezekiah"]),
    mc(2, "Which word correctly completes this RSV wording: “and with a whole heart, and have done what is good in thy sight.\" And _____ wept bitterly.”", ["Hezeki’ah", "Amoz", "King", "Remember"], 3),
    word(3, "In verse 3, what word completes this phrase: “and with a whole heart, and have done what is good in thy sight.\" And _____ wept bitterly.”?", "Hezeki’ah", 3, ["hezekiah"]),
    tf(1, "The RSV states: “\"Remember now, O LORD, I beseech thee, how I have walked before thee in faithfulness and with a whole heart, and have done what is good in thy sight.\" And Hezeki’ah wept bitterly.”", true, 3),
    blank(2, "And before _____ had gone out of the middle court, the word of the LORD came to him:", "Isaiah", 4, ["isaiah"]),
    mc(3, "Which word correctly completes this RSV wording: “And before _____ had gone out of the middle court, the word of the LORD came to him:”", ["Isaiah", "Bring", "Manas’seh", "Bal’adan"], 4),
    word(1, "In verse 4, what word completes this phrase: “And before _____ had gone out of the middle court, the word of the LORD came to him:”?", "Isaiah", 4, ["isaiah"]),
    tf(2, "The RSV does not state: “And before Isaiah had gone out of the middle court, the word of the LORD came to him:”", false, 4, "The quoted wording is the RSV text of this verse."),
    blank(3, "\"Turn back, and say to _____ the prince of my people, Thus says the LORD, the God of David your father:", "Hezeki’ah", 5, ["hezekiah"]),
    mc(1, "Which word correctly completes this RSV wording: “\"Turn back, and say to _____ the prince of my people, Thus says the LORD, the God of David your father:”", ["Hezeki’ah", "Book", "Assyria", "Kings"], 5),
    word(2, "In verse 5, what word completes this phrase: “\"Turn back, and say to _____ the prince of my people, Thus says the LORD, the God of David your father:”?", "Hezeki’ah", 5, ["hezekiah"]),
    tf(3, "The RSV states: “\"Turn back, and say to Hezeki’ah the prince of my people, Thus says the LORD, the God of David your father: I have heard your prayer, I have seen your tears; behold, I will heal you; on the third day you shall go up to the house of the LORD.”", true, 5),
    blank(1, "life. I will deliver you and this city out of the hand of the king of _____, and I will defend this city for my own sake and for my servant David’s", "Assyria", 6, ["assyria"]),
    mc(2, "Which word correctly completes this RSV wording: “life. I will deliver you and this city out of the hand of the king of _____, and I will defend this city for my own sake and for my servant David’s”", ["Assyria", "Amoz", "Hear", "Remember"], 6),
    word(3, "In verse 6, what word completes this phrase: “life. I will deliver you and this city out of the hand of the king of _____, and I will defend this city for my own sake and for my servant David’s”?", "Assyria", 6, ["assyria"]),
    tf(1, "The RSV does not state: “And I will add fifteen years to your life. I will deliver you and this city out of the hand of the king of Assyria, and I will defend this city for my own sake and for my servant David’s sake.\"”", false, 6, "The quoted wording is the RSV text of this verse."),
    blank(2, "And _____ said, \"Bring a cake of figs. And let them take and lay it on the boil,", "Isaiah", 7, ["isaiah"]),
    mc(3, "Which word correctly completes this RSV wording: “And _____ said, \"Bring a cake of figs. And let them take and lay it on the boil,”", ["Isaiah", "Ahaz", "Hezeki’ah", "Babylon"], 7),
    word(1, "In verse 7, what word completes this phrase: “And _____ said, \"Bring a cake of figs. And let them take and lay it on the boil,”?", "Isaiah", 7, ["isaiah"]),
    tf(2, "The RSV states: “And Isaiah said, \"Bring a cake of figs. And let them take and lay it on the boil, that he may recover.\"”", true, 7),
    blank(3, "And _____ said to Isaiah, \"What shall be the sign that the LORD will heal me, and", "Hezeki’ah", 8, ["hezekiah"]),
    mc(1, "Which word correctly completes this RSV wording: “And _____ said to Isaiah, \"What shall be the sign that the LORD will heal me, and”", ["Hezeki’ah", "Chronicles", "David’s", "Judah"], 8),
    word(2, "In verse 8, what word completes this phrase: “And _____ said to Isaiah, \"What shall be the sign that the LORD will heal me, and”?", "Hezeki’ah", 8, ["hezekiah"]),
    tf(3, "The RSV does not state: “And Hezeki’ah said to Isaiah, \"What shall be the sign that the LORD will heal me, and that I shall go up to the house of the LORD on the third day?\"”", false, 8, "The quoted wording is the RSV text of this verse."),
    blank(1, "And _____ said, \"This is the sign to you from the LORD, that the LORD will do the", "Isaiah", 9, ["isaiah"]),
    mc(2, "Which word correctly completes this RSV wording: “And _____ said, \"This is the sign to you from the LORD, that the LORD will do the”", ["Isaiah", "Remember", "Behold", "David"], 9),
    word(3, "In verse 9, what word completes this phrase: “And _____ said, \"This is the sign to you from the LORD, that the LORD will do the”?", "Isaiah", 9, ["isaiah"]),
    tf(1, "The RSV states: “And Isaiah said, \"This is the sign to you from the LORD, that the LORD will do the thing that he has promised: shall the shadow go forward ten steps, or go back ten steps?\"”", true, 9),
    blank(2, "And _____ answered, \"It is an easy thing for the shadow to lengthen ten steps; rather", "Hezeki’ah", 10, ["hezekiah"]),
    mc(3, "Which word correctly completes this RSV wording: “And _____ answered, \"It is an easy thing for the shadow to lengthen ten steps; rather”", ["Hezeki’ah", "Bal’adan", "Amoz", "King"], 10),
    word(1, "In verse 10, what word completes this phrase: “And _____ answered, \"It is an easy thing for the shadow to lengthen ten steps; rather”?", "Hezeki’ah", 10, ["hezekiah"]),
    tf(2, "The RSV does not state: “And Hezeki’ah answered, \"It is an easy thing for the shadow to lengthen ten steps; rather let the shadow go back ten steps.\"”", false, 10, "The quoted wording is the RSV text of this verse."),
    blank(3, "And _____ the prophet cried to the LORD; and he brought the shadow back ten steps,", "Isaiah", 11, ["isaiah"]),
    mc(1, "Which word correctly completes this RSV wording: “And _____ the prophet cried to the LORD; and he brought the shadow back ten steps,”", ["Isaiah", "Kings", "Bring", "Manas’seh"], 11),
    word(2, "In verse 11, what word completes this phrase: “And _____ the prophet cried to the LORD; and he brought the shadow back ten steps,”?", "Isaiah", 11, ["isaiah"]),
    tf(3, "The RSV states: “And Isaiah the prophet cried to the LORD; and he brought the shadow back ten steps, by which the sun had declined on the dial of Ahaz.”", true, 11),
    blank(1, "At that time _____ the son of Bal’adan, king of Babylon, sent envoys with letters and a present", "Mero’dach-bal’adan", 12, ["merodach-baladan"]),
    mc(2, "Which word correctly completes this RSV wording: “At that time _____ the son of Bal’adan, king of Babylon, sent envoys with letters and a present”", ["Mero’dach-bal’adan", "Jerusalem", "Israel", "Solomon"], 12),
    word(3, "In verse 12, what word completes this phrase: “At that time _____ the son of Bal’adan, king of Babylon, sent envoys with letters and a present”?", "Mero’dach-bal’adan", 12, ["merodach-baladan"]),
    tf(1, "The RSV does not state: “At that time Mero’dach-bal’adan the son of Bal’adan, king of Babylon, sent envoys with letters and a present to Hezeki’ah; for he heard that Hezeki’ah had been sick.”", false, 12, "The quoted wording is the RSV text of this verse."),
    blank(2, "And _____ welcomed them, and he showed them all his treasure house, the silver,", "Hezeki’ah", 13, ["hezekiah"]),
    mc(3, "Which word correctly completes this RSV wording: “And _____ welcomed them, and he showed them all his treasure house, the silver,”", ["Hezeki’ah", "Babylon", "Thus", "Hear"], 13),
    word(1, "In verse 13, what word completes this phrase: “And _____ welcomed them, and he showed them all his treasure house, the silver,”?", "Hezeki’ah", 13, ["hezekiah"]),
    tf(2, "The RSV states: “And Hezeki’ah welcomed them, and he showed them all his treasure house, the silver, the gold, the spices, the precious oil, his armory, all that was found in his storehouses; there was nothing in his house or in all his realm that Hezeki’ah did not show them.”", true, 13),
    blank(3, "Then Isaiah the prophet came to King _____, and said to him, \"What did these men say? And whence did they come to", "Hezeki’ah", 14, ["hezekiah"]),
    mc(1, "Which word correctly completes this RSV wording: “Then Isaiah the prophet came to King _____, and said to him, \"What did these men say? And whence did they come to”", ["Hezeki’ah", "Judah", "Ahaz", "Isaiah"], 14),
    word(2, "In verse 14, what word completes this phrase: “Then Isaiah the prophet came to King _____, and said to him, \"What did these men say? And whence did they come to”?", "Hezeki’ah", 14, ["hezekiah"]),
    tf(3, "The RSV does not state: “Then Isaiah the prophet came to King Hezeki’ah, and said to him, \"What did these men say? And whence did they come to you?\" And Hezeki’ah said, \"They have come from a far country, from Babylon.\"”", false, 14, "The quoted wording is the RSV text of this verse."),
    blank(1, "He said, \"What have they seen in your house?\" And _____ answered, \"They have seen all that is in my house; there is nothing in", "Hezeki’ah", 15, ["hezekiah"]),
    mc(2, "Which word correctly completes this RSV wording: “He said, \"What have they seen in your house?\" And _____ answered, \"They have seen all that is in my house; there is nothing in”", ["Hezeki’ah", "David", "Chronicles", "David’s"], 15),
    word(3, "In verse 15, what word completes this phrase: “He said, \"What have they seen in your house?\" And _____ answered, \"They have seen all that is in my house; there is nothing in”?", "Hezeki’ah", 15, ["hezekiah"]),
    tf(1, "The RSV states: “He said, \"What have they seen in your house?\" And Hezeki’ah answered, \"They have seen all that is in my house; there is nothing in my storehouses that I did not show them.\"”", true, 15),
    blank(2, "Then Isaiah said to _____, \"Hear the word of the LORD:", "Hezeki’ah", 16, ["hezekiah"]),
    mc(3, "Which word correctly completes this RSV wording: “Then Isaiah said to _____, \"Hear the word of the LORD:”", ["Hezeki’ah", "King", "Remember", "Behold"], 16),
    word(1, "In verse 16, what word completes this phrase: “Then Isaiah said to _____, \"Hear the word of the LORD:”?", "Hezeki’ah", 16, ["hezekiah"]),
    tf(2, "The RSV does not state: “Then Isaiah said to Hezeki’ah, \"Hear the word of the LORD:”", false, 16, "The quoted wording is the RSV text of this verse."),
    blank(3, "which your fathers have stored up till this day, shall be carried to _____; nothing shall be left, says the LORD.", "Babylon", 17, ["babylon"]),
    mc(1, "Which word correctly completes this RSV wording: “which your fathers have stored up till this day, shall be carried to _____; nothing shall be left, says the LORD.”", ["Babylon", "Manas’seh", "Ahaz", "Isaiah"], 17),
    word(2, "In verse 17, what word completes this phrase: “which your fathers have stored up till this day, shall be carried to _____; nothing shall be left, says the LORD.”?", "Babylon", 17, ["babylon"]),
    tf(3, "The RSV states: “Behold, the days are coming, when all that is in your house, and that which your fathers have stored up till this day, shall be carried to Babylon; nothing shall be left, says the LORD.”", true, 17),
    blank(1, "be taken away; and they shall be eunuchs in the palace of the king of _____.\"", "Babylon", 18, ["babylon"]),
    mc(2, "Which word correctly completes this RSV wording: “be taken away; and they shall be eunuchs in the palace of the king of _____.\"”", ["Babylon", "David", "Kings", "David’s"], 18),
    word(3, "In verse 18, what word completes this phrase: “be taken away; and they shall be eunuchs in the palace of the king of _____.\"”?", "Babylon", 18, ["babylon"]),
    tf(1, "The RSV does not state: “And some of your own sons, who are born to you, shall be taken away; and they shall be eunuchs in the palace of the king of Babylon.\"”", false, 18, "The quoted wording is the RSV text of this verse."),
    blank(2, "Then said _____ to Isaiah, \"The word of the LORD which you have spoken is good.\" For he", "Hezeki’ah", 19, ["hezekiah"]),
    mc(3, "Which word correctly completes this RSV wording: “Then said _____ to Isaiah, \"The word of the LORD which you have spoken is good.\" For he”", ["Hezeki’ah", "Hear", "Turn", "Book"], 19),
    word(1, "In verse 19, what word completes this phrase: “Then said _____ to Isaiah, \"The word of the LORD which you have spoken is good.\" For he”?", "Hezeki’ah", 19, ["hezekiah"]),
    tf(2, "The RSV states: “Then said Hezeki’ah to Isaiah, \"The word of the LORD which you have spoken is good.\" For he thought, \"Why not, if there will be peace and security in my days?\"”", true, 19),
    blank(3, "brought water into the city, are they not written in the Book of the _____ of the Kings of Judah?", "Chronicles", 20, ["chronicles"]),
    mc(1, "Which word correctly completes this RSV wording: “brought water into the city, are they not written in the Book of the _____ of the Kings of Judah?”", ["Chronicles", "Kings", "Babylon", "Bring"], 20),
    word(2, "In verse 20, what word completes this phrase: “brought water into the city, are they not written in the Book of the _____ of the Kings of Judah?”?", "Chronicles", 20, ["chronicles"]),
    tf(3, "The RSV does not state: “ The rest of the deeds of Hezeki’ah, and all his might, and how he made the pool and the conduit and brought water into the city, are they not written in the Book of the Chronicles of the Kings of Judah?”", false, 20, "The quoted wording is the RSV text of this verse."),
    blank(1, "And _____ slept with his fathers; and Manas’seh his son reigned in his stead.", "Hezeki’ah", 21, ["hezekiah"]),
    mc(2, "Which word correctly completes this RSV wording: “And _____ slept with his fathers; and Manas’seh his son reigned in his stead.”", ["Hezeki’ah", "David’s", "Judah", "Ahaz"], 21),
    word(3, "In verse 21, what word completes this phrase: “And _____ slept with his fathers; and Manas’seh his son reigned in his stead.”?", "Hezeki’ah", 21, ["hezekiah"]),
    tf(1, "The RSV states: “And Hezeki’ah slept with his fathers; and Manas’seh his son reigned in his stead.”", true, 21),
    blank(1, "days Hezeki’ah became sick and was at the point of death. And Isaiah the _____ the son of Amoz came to him, and said to him, \"Thus says the LORD, `Set", "prophet", 1, ["prophet"]),
    mc(2, "Select the missing RSV word: “Then Hezeki’ah _____ his face to the wall, and prayed to the LORD, saying,”", ["turned", "gone", "tears", "defend"], 2),
    word(3, "What missing word belongs in this verse 3 clause: “\"Remember now, O LORD, I beseech thee, how I have walked before thee in _____ and with a whole heart, and have done what is good in thy sight.\" And”?", "faithfulness", 3, ["faithfulness"]),
    tf(1, "This wording appears in verse 4: “And before Isaiah had gone out of the middle court, the word of the LORD came to”", true, 4),
    blank(2, "\"Turn back, and say to Hezeki’ah the _____ of my people, Thus says the LORD, the God of David your father: I have", "prince", 5, ["prince"]),
    mc(3, "Select the missing RSV word: “And I will add _____ years to your life. I will deliver you and this city out of the hand of”", ["fifteen", "armory", "stored", "spoken"], 6),
    word(1, "What missing word belongs in this verse 7 clause: “a cake of figs. And let them take and lay it on the boil, that he may _____.\"”?", "recover", 7, ["recover"]),
    tf(2, "This wording appears in verse 8: “And Hezeki’ah said to Isaiah, \"What shall be the sign that the LORD will heal me, and that I shall”", true, 8),
    blank(3, "sign to you from the LORD, that the LORD will do the thing that he has _____: shall the shadow go forward ten steps, or go back ten steps?\"", "promised", 9, ["promised"]),
    mc(1, "Select the missing RSV word: “And Hezeki’ah _____, \"It is an easy thing for the shadow to lengthen ten steps; rather let”", ["answered", "thee", "gone", "tears"], 10),
    word(2, "What missing word belongs in this verse 11 clause: “LORD; and he brought the shadow back ten steps, by which the sun had _____ on the dial of Ahaz.”?", "declined", 11, ["declined"]),
    tf(3, "This wording appears in verse 12: “Bal’adan, king of Babylon, sent envoys with letters and a present to Hezeki’ah; for he heard that Hezeki’ah had been sick.”", true, 12),
    blank(1, "gold, the spices, the precious oil, his armory, all that was found in his _____; there was nothing in his house or in all his realm that Hezeki’ah did", "storehouses", 13, ["storehouses"]),
    mc(2, "Select the missing RSV word: “Then Isaiah the _____ came to King Hezeki’ah, and said to him, \"What did these men say? And”", ["prophet", "letters", "storehouses", "carried"], 14),
    word(3, "What missing word belongs in this verse 15 clause: “answered, \"They have seen all that is in my house; there is nothing in my _____ that I did not show them.\"”?", "storehouses", 15, ["storehouses"]),
    tf(1, "This wording appears in verse 16: “Then Isaiah said to Hezeki’ah, \"Hear the word of the LORD:”", true, 16),
    blank(2, "days are coming, when all that is in your house, and that which your _____ have stored up till this day, shall be carried to Babylon; nothing shall", "fathers", 17, ["fathers"]),
    mc(3, "Select the missing RSV word: “own sons, who are born to you, shall be taken away; and they shall be _____ in the palace of the king of Babylon.\"”", ["eunuchs", "order", "before", "court"], 18),
    word(1, "What missing word belongs in this verse 19 clause: “spoken is good.\" For he thought, \"Why not, if there will be peace and _____ in my days?\"”?", "security", 19, ["security"]),
    tf(2, "This wording appears in verse 20: “The rest of the deeds of Hezeki’ah, and all his might, and how he made the pool and the conduit and brought”", true, 20),
    blank(3, "And Hezeki’ah slept with his fathers; and _____ his son reigned in his stead.", "Manas’seh", 21, ["manasseh"]),
    mc(1, "Select the missing RSV word: “the LORD, `Set your house in order; for you shall die, you shall not _____.’\"”", ["recover", "tears", "defend", "forward"], 1),
    word(2, "What missing word belongs in this verse 2 clause: “Then Hezeki’ah turned his face to the wall, and _____ to the LORD, saying,”?", "prayed", 2, ["prayed"]),
    tf(3, "This wording appears in verse 3: “\"Remember now, O LORD, I beseech thee, how I have walked before thee in faithfulness”", true, 3),
    blank(1, "And before Isaiah had gone out of the _____ court, the word of the LORD came to him:", "middle", 4, ["middle"]),
    mc(2, "Select the missing RSV word: “\"Turn back, and say to Hezeki’ah the prince of my _____, Thus says the LORD, the God of David your father: I have heard your prayer,”", ["people", "left", "security", "stead"], 5),
    word(3, "What missing word belongs in this verse 6 clause: “And I will add fifteen years to your life. I will _____ you and this city out of the hand of the king of Assyria, and I will defend”?", "deliver", 6, ["deliver"]),
    tf(1, "This wording appears in verse 7: “And Isaiah said, \"Bring a cake of figs. And let them take and lay it on the boil, that he may”", true, 7),
    blank(2, "And Hezeki’ah said to Isaiah, \"What _____ be the sign that the LORD will heal me, and that I shall go up to the", "shall", 8, ["shall"]),
    mc(3, "Select the missing RSV word: “the LORD will do the thing that he has promised: shall the shadow go _____ ten steps, or go back ten steps?\"”", ["forward", "middle", "behold", "sake"], 9),
    word(1, "What missing word belongs in this verse 10 clause: “And Hezeki’ah answered, \"It is an easy thing for the shadow to _____ ten steps; rather let the shadow go back ten steps.\"”?", "lengthen", 10, ["lengthen"]),
    tf(2, "This wording appears in verse 11: “And Isaiah the prophet cried to the LORD; and he brought the shadow back ten steps, by which”", true, 11),
    blank(3, "At that time Mero’dach-bal’adan the son of _____, king of Babylon, sent envoys with letters and a present to Hezeki’ah;", "Bal’adan", 12, ["baladan"]),
    mc(1, "Select the missing RSV word: “And Hezeki’ah _____ them, and he showed them all his treasure house, the silver, the gold,”", ["welcomed", "nothing", "left", "security"], 13),
    word(2, "What missing word belongs in this verse 14 clause: “did they come to you?\" And Hezeki’ah said, \"They have come from a far _____, from Babylon.\"”?", "country", 14, ["country"]),
    tf(3, "This wording appears in verse 15: “He said, \"What have they seen in your house?\" And Hezeki’ah answered, \"They have seen all that is in my house; there is nothing in my storehouses”", true, 15),
    mc(2, "What moved the LORD to heal Hezekiah, and how many years were added?", ["The LORD heard his prayer and saw his tears; fifteen years", "Isaiah offered a sacrifice; seven years", "The people fasted; twenty years", "Hezekiah destroyed an altar; twelve years"], 6),
    mc(3, "What sign confirmed Hezekiah’s healing?", ["The shadow went backward ten steps on the dial of Ahaz", "The sun stood still for a day", "A fleece became dry", "Fire consumed an offering"], 11),
    mc(3, "What did Hezekiah show Babylon’s envoys, and what did Isaiah predict?", ["He showed all his treasures; they and some of his sons would be carried to Babylon", "He showed only the temple; it would be destroyed by Syria", "He showed his army; Judah would conquer Babylon", "He showed nothing; the envoys would return peacefully"], 18),
  ],
};

export default bank;
