// 2 Kings 10 — quiz bank (RSV). Four verse-anchored forms per verse.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: "2 Kings",
  chapter: 10,
  tag: "quiz-v2-2kings-10",
  rows: [
    blank(2, "Now Ahab had seventy sons in _____. So Jehu wrote letters, and sent them to Sama’ria, to the rulers of the", "Sama’ria", 1, ["samaria"]),
    mc(3, "Which word correctly completes this RSV wording: “Now Ahab had seventy sons in _____. So Jehu wrote letters, and sent them to Sama’ria, to the rulers of the”", ["Sama’ria", "Shepherds", "Search", "Manas’sites"], 1),
    word(1, "In verse 1, what word completes this phrase: “Now Ahab had seventy sons in _____. So Jehu wrote letters, and sent them to Sama’ria, to the rulers of the”?", "Sama’ria", 1, ["samaria"]),
    tf(2, "The RSV states: “Now Ahab had seventy sons in Sama’ria. So Jehu wrote letters, and sent them to Sama’ria, to the rulers of the city, to the elders, and to the guardians of the sons of Ahab, saying,”", true, 1),
    blank(3, "master’s sons are with you, and there are with you chariots and horses, _____ cities also, and weapons,", "fortified", 2, ["fortified"]),
    mc(1, "Which word correctly completes this RSV wording: “master’s sons are with you, and there are with you chariots and horses, _____ cities also, and weapons,”", ["fortified", "master’s", "fight", "together"], 2),
    word(2, "In verse 2, what word completes this phrase: “master’s sons are with you, and there are with you chariots and horses, _____ cities also, and weapons,”?", "fortified", 2, ["fortified"]),
    tf(3, "The RSV does not state: “\"Now then, as soon as this letter comes to you, seeing your master’s sons are with you, and there are with you chariots and horses, fortified cities also, and weapons,”", false, 2, "The quoted wording is the RSV text of this verse."),
    blank(1, "select the best and fittest of your _____ sons and set him on his father’s throne, and fight for your master’s house.\"", "master’s", 3, ["masters"]),
    mc(2, "Which word correctly completes this RSV wording: “select the best and fittest of your _____ sons and set him on his father’s throne, and fight for your master’s house.\"”", ["master’s", "best", "stand", "second"], 3),
    word(3, "In verse 3, what word completes this phrase: “select the best and fittest of your _____ sons and set him on his father’s throne, and fight for your master’s house.\"”?", "master’s", 3, ["masters"]),
    tf(1, "The RSV states: “select the best and fittest of your master’s sons and set him on his father’s throne, and fight for your master’s house.\"”", true, 3),
    blank(2, "But they were exceedingly afraid, and said, \"_____, the two kings could not stand before him; how then can we stand?\"", "Behold", 4, ["behold"]),
    mc(3, "Which word correctly completes this RSV wording: “But they were exceedingly afraid, and said, \"_____, the two kings could not stand before him; how then can we stand?\"”", ["Behold", "Reubenites", "Jehu", "Come"], 4),
    word(1, "In verse 4, what word completes this phrase: “But they were exceedingly afraid, and said, \"_____, the two kings could not stand before him; how then can we stand?\"”?", "Behold", 4, ["behold"]),
    tf(2, "The RSV does not state: “But they were exceedingly afraid, and said, \"Behold, the two kings could not stand before him; how then can we stand?\"”", false, 4, "The quoted wording is the RSV text of this verse."),
    blank(3, "was over the city, together with the elders and the guardians, sent to _____, saying, \"We are your servants, and we will do all that you bid us. We", "Jehu", 5, ["jehu"]),
    mc(1, "Which word correctly completes this RSV wording: “was over the city, together with the elders and the guardians, sent to _____, saying, \"We are your servants, and we will do all that you bid us. We”", ["Jehu", "Behold", "Ba’al", "Jordan"], 5),
    word(2, "In verse 5, what word completes this phrase: “was over the city, together with the elders and the guardians, sent to _____, saying, \"We are your servants, and we will do all that you bid us. We”?", "Jehu", 5, ["jehu"]),
    tf(3, "The RSV states: “So he who was over the palace, and he who was over the city, together with the elders and the guardians, sent to Jehu, saying, \"We are your servants, and we will do all that you bid us. We will not make any one king; do whatever is good in your eyes.\"”", true, 5),
    blank(1, "ready to obey me, take the heads of your master’s sons, and come to me at _____ tomorrow at this time.\" Now the king’s sons, seventy persons, were with", "Jezreel", 6, ["jezreel"]),
    mc(2, "Which word correctly completes this RSV wording: “ready to obey me, take the heads of your master’s sons, and come to me at _____ tomorrow at this time.\" Now the king’s sons, seventy persons, were with”", ["Jezreel", "Eli’jah", "Israel", "Gadites"], 6),
    word(3, "In verse 6, what word completes this phrase: “ready to obey me, take the heads of your master’s sons, and come to me at _____ tomorrow at this time.\" Now the king’s sons, seventy persons, were with”?", "Jezreel", 6, ["jezreel"]),
    tf(1, "The RSV does not state: “Then he wrote to them a second letter, saying, \"If you are on my side, and if you are ready to obey me, take the heads of your master’s sons, and come to me at Jezreel tomorrow at this time.\" Now the king’s sons, seventy persons, were with the great men of the city, who were bringing them up.”", false, 6, "The quoted wording is the RSV text of this verse."),
    blank(2, "seventy persons, and put their heads in baskets, and sent them to him at _____.", "Jezreel", 7, ["jezreel"]),
    mc(3, "Which word correctly completes this RSV wording: “seventy persons, and put their heads in baskets, and sent them to him at _____.”", ["Jezreel", "Rechab", "Because", "Chronicles"], 7),
    word(1, "In verse 7, what word completes this phrase: “seventy persons, and put their heads in baskets, and sent them to him at _____.”?", "Jezreel", 7, ["jezreel"]),
    tf(2, "The RSV states: “And when the letter came to them, they took the king’s sons, and slew them, seventy persons, and put their heads in baskets, and sent them to him at Jezreel.”", true, 7),
    blank(3, "When the _____ came and told him, \"They have brought the heads of the king’s sons,\" he", "messenger", 8, ["messenger"]),
    mc(1, "Which word correctly completes this RSV wording: “When the _____ came and told him, \"They have brought the heads of the king’s sons,\" he”", ["messenger", "bringing", "morning", "fall"], 8),
    word(2, "In verse 8, what word completes this phrase: “When the _____ came and told him, \"They have brought the heads of the king’s sons,\" he”?", "messenger", 8, ["messenger"]),
    tf(3, "The RSV does not state: “When the messenger came and told him, \"They have brought the heads of the king’s sons,\" he said, \"Lay them in two heaps at the entrance of the gate until the morning.\"”", false, 8, "The quoted wording is the RSV text of this verse."),
    blank(1, "he stood, and said to all the people, \"You are innocent. It was I who _____ against my master, and slew him; but who struck down all these?", "conspired", 9, ["conspired"]),
    mc(2, "Which word correctly completes this RSV wording: “he stood, and said to all the people, \"You are innocent. It was I who _____ against my master, and slew him; but who struck down all these?”", ["conspired", "brought", "master", "servant"], 9),
    word(3, "In verse 9, what word completes this phrase: “he stood, and said to all the people, \"You are innocent. It was I who _____ against my master, and slew him; but who struck down all these?”?", "conspired", 9, ["conspired"]),
    tf(1, "The RSV states: “Then in the morning, when he went out, he stood, and said to all the people, \"You are innocent. It was I who conspired against my master, and slew him; but who struck down all these?”", true, 9),
    blank(2, "the house of Ahab; for the LORD has done what he said by his servant _____.\"", "Eli’jah", 10, ["elijah"]),
    mc(3, "Which word correctly completes this RSV wording: “the house of Ahab; for the LORD has done what he said by his servant _____.\"”", ["Eli’jah", "Book", "Shepherds", "Search"], 10),
    word(1, "In verse 10, what word completes this phrase: “the house of Ahab; for the LORD has done what he said by his servant _____.\"”?", "Eli’jah", 10, ["elijah"]),
    tf(2, "The RSV does not state: “Know then that there shall fall to the earth nothing of the word of the LORD, which the LORD spoke concerning the house of Ahab; for the LORD has done what he said by his servant Eli’jah.\"”", false, 10, "The quoted wording is the RSV text of this verse."),
    blank(3, "So Jehu slew all that remained of the house of Ahab in _____, all his great men, and his familiar friends, and his priests, until he", "Jezreel", 11, ["jezreel"]),
    mc(1, "Which word correctly completes this RSV wording: “So Jehu slew all that remained of the house of Ahab in _____, all his great men, and his familiar friends, and his priests, until he”", ["Jezreel", "Behold", "Ba’al", "Jordan"], 11),
    word(2, "In verse 11, what word completes this phrase: “So Jehu slew all that remained of the house of Ahab in _____, all his great men, and his familiar friends, and his priests, until he”?", "Jezreel", 11, ["jezreel"]),
    tf(3, "The RSV states: “So Jehu slew all that remained of the house of Ahab in Jezreel, all his great men, and his familiar friends, and his priests, until he left him none remaining.”", true, 11),
    blank(1, "Then he set out and went to Sama’ria. On the way, when he was at _____ of the Shepherds,", "Beth-eked", 12, ["beth-eked"]),
    mc(2, "Which word correctly completes this RSV wording: “Then he set out and went to Sama’ria. On the way, when he was at _____ of the Shepherds,”", ["Beth-eked", "Take", "Nebat", "Bashan"], 12),
    word(3, "In verse 12, what word completes this phrase: “Then he set out and went to Sama’ria. On the way, when he was at _____ of the Shepherds,”?", "Beth-eked", 12, ["beth-eked"]),
    tf(1, "The RSV does not state: “Then he set out and went to Sama’ria. On the way, when he was at Beth-eked of the Shepherds,”", false, 12, "The quoted wording is the RSV text of this verse."),
    blank(2, "Jehu met the kinsmen of _____ king of Judah, and he said, \"Who are you?\" And they answered, \"We are", "Ahazi’ah", 13, ["ahaziah"]),
    mc(3, "Which word correctly completes this RSV wording: “Jehu met the kinsmen of _____ king of Judah, and he said, \"Who are you?\" And they answered, \"We are”", ["Ahazi’ah", "Bring", "Reubenites", "Jehu"], 13),
    word(1, "In verse 13, what word completes this phrase: “Jehu met the kinsmen of _____ king of Judah, and he said, \"Who are you?\" And they answered, \"We are”?", "Ahazi’ah", 13, ["ahaziah"]),
    tf(2, "The RSV states: “Jehu met the kinsmen of Ahazi’ah king of Judah, and he said, \"Who are you?\" And they answered, \"We are the kinsmen of Ahazi’ah, and we came down to visit the royal princes and the sons of the queen mother.\"”", true, 13),
    blank(3, "\"Take them alive.\" And they took them alive, and slew them at the pit of _____, forty-two persons, and he spared none of them.", "Beth-eked", 14, ["beth-eked"]),
    mc(1, "Which word correctly completes this RSV wording: “\"Take them alive.\" And they took them alive, and slew them at the pit of _____, forty-two persons, and he spared none of them.”", ["Beth-eked", "Haz’ael", "Kings", "Judah"], 14),
    word(2, "In verse 14, what word completes this phrase: “\"Take them alive.\" And they took them alive, and slew them at the pit of _____, forty-two persons, and he spared none of them.”?", "Beth-eked", 14, ["beth-eked"]),
    tf(3, "The RSV does not state: “He said, \"Take them alive.\" And they took them alive, and slew them at the pit of Beth-eked, forty-two persons, and he spared none of them.”", false, 14, "The quoted wording is the RSV text of this verse."),
    blank(1, "And when he departed from there, he met _____ the son of Rechab coming to meet him; and he greeted him, and said to", "Jehon’adab", 15, ["jehonadab"]),
    mc(2, "Which word correctly completes this RSV wording: “And when he departed from there, he met _____ the son of Rechab coming to meet him; and he greeted him, and said to”", ["Jehon’adab", "Nebat", "Bashan", "Judah"], 15),
    word(3, "In verse 15, what word completes this phrase: “And when he departed from there, he met _____ the son of Rechab coming to meet him; and he greeted him, and said to”?", "Jehon’adab", 15, ["jehonadab"]),
    tf(1, "The RSV states: “And when he departed from there, he met Jehon’adab the son of Rechab coming to meet him; and he greeted him, and said to him, \"Is your heart true to my heart as mine is to yours?\" And Jehon’adab answered, \"It is.\" Jehu said, \"If it is, give me your hand.\" So he gave him his hand. And Jehu took him up with him into the chariot.”", true, 15),
    blank(2, "And he said, \"_____ with me, and see my zeal for the LORD.\" So he had him ride in his chariot.", "Come", 16, ["come"]),
    mc(3, "Which word correctly completes this RSV wording: “And he said, \"_____ with me, and see my zeal for the LORD.\" So he had him ride in his chariot.”", ["Come", "Ba’al", "Jordan", "Jehu"], 16),
    word(1, "In verse 16, what word completes this phrase: “And he said, \"_____ with me, and see my zeal for the LORD.\" So he had him ride in his chariot.”?", "Come", 16, ["come"]),
    tf(2, "The RSV does not state: “And he said, \"Come with me, and see my zeal for the LORD.\" So he had him ride in his chariot.”", false, 16, "The quoted wording is the RSV text of this verse."),
    blank(3, "And when he came to _____, he slew all that remained to Ahab in Sama’ria, till he had wiped them", "Sama’ria", 17, ["samaria"]),
    mc(1, "Which word correctly completes this RSV wording: “And when he came to _____, he slew all that remained to Ahab in Sama’ria, till he had wiped them”", ["Sama’ria", "Ahazi’ah", "Thus", "Aro’er"], 17),
    word(2, "In verse 17, what word completes this phrase: “And when he came to _____, he slew all that remained to Ahab in Sama’ria, till he had wiped them”?", "Sama’ria", 17, ["samaria"]),
    tf(3, "The RSV states: “And when he came to Sama’ria, he slew all that remained to Ahab in Sama’ria, till he had wiped them out, according to the word of the LORD which he spoke to Eli’jah.”", true, 17),
    blank(1, "Then Jehu assembled all the people, and said to them, \"Ahab served _____ a little; but Jehu will serve him much.", "Ba’al", 18, ["baal"]),
    mc(2, "Which word correctly completes this RSV wording: “Then Jehu assembled all the people, and said to them, \"Ahab served _____ a little; but Jehu will serve him much.”", ["Ba’al", "Search", "Aro’er", "Jezreel"], 18),
    word(3, "In verse 18, what word completes this phrase: “Then Jehu assembled all the people, and said to them, \"Ahab served _____ a little; but Jehu will serve him much.”?", "Ba’al", 18, ["baal"]),
    tf(1, "The RSV does not state: “Then Jehu assembled all the people, and said to them, \"Ahab served Ba’al a little; but Jehu will serve him much.”", false, 18, "The quoted wording is the RSV text of this verse."),
    blank(2, "Now therefore call to me all the prophets of _____, all his worshipers and all his priests; let none be missing, for I have", "Ba’al", 19, ["baal"]),
    mc(3, "Which word correctly completes this RSV wording: “Now therefore call to me all the prophets of _____, all his worshipers and all his priests; let none be missing, for I have”", ["Ba’al", "Jordan", "Ahab", "Take"], 19),
    word(1, "In verse 19, what word completes this phrase: “Now therefore call to me all the prophets of _____, all his worshipers and all his priests; let none be missing, for I have”?", "Ba’al", 19, ["baal"]),
    tf(2, "The RSV states: “Now therefore call to me all the prophets of Ba’al, all his worshipers and all his priests; let none be missing, for I have a great sacrifice to offer to Ba’al; whoever is missing shall not live.\" But Jehu did it with cunning in order to destroy the worshipers of Ba’al.”", true, 19),
    blank(3, "And Jehu ordered, \"_____ a solemn assembly for Ba’al.\" So they proclaimed it.", "Sanctify", 20, ["sanctify"]),
    mc(1, "Which word correctly completes this RSV wording: “And Jehu ordered, \"_____ a solemn assembly for Ba’al.\" So they proclaimed it.”", ["Sanctify", "Manas’sites", "Behold", "Come"], 20),
    word(2, "In verse 20, what word completes this phrase: “And Jehu ordered, \"_____ a solemn assembly for Ba’al.\" So they proclaimed it.”?", "Sanctify", 20, ["sanctify"]),
    tf(3, "The RSV does not state: “And Jehu ordered, \"Sanctify a solemn assembly for Ba’al.\" So they proclaimed it.”", false, 20, "The quoted wording is the RSV text of this verse."),
    blank(1, "And Jehu sent throughout all _____; and all the worshipers of Ba’al came, so that there was not a man left", "Israel", 21, ["israel"]),
    mc(2, "Which word correctly completes this RSV wording: “And Jehu sent throughout all _____; and all the worshipers of Ba’al came, so that there was not a man left”", ["Israel", "Jeho’ahaz", "Judah", "Nebat"], 21),
    word(3, "In verse 21, what word completes this phrase: “And Jehu sent throughout all _____; and all the worshipers of Ba’al came, so that there was not a man left”?", "Israel", 21, ["israel"]),
    tf(1, "The RSV states: “And Jehu sent throughout all Israel; and all the worshipers of Ba’al came, so that there was not a man left who did not come. And they entered the house of Ba’al, and the house of Ba’al was filled from one end to the other.”", true, 21),
    blank(2, "He said to him who was in charge of the wardrobe, \"_____ out the vestments for all the worshipers of Ba’al.\" So he brought out", "Bring", 22, ["bring"]),
    mc(3, "Which word correctly completes this RSV wording: “He said to him who was in charge of the wardrobe, \"_____ out the vestments for all the worshipers of Ba’al.\" So he brought out”", ["Bring", "Judah", "Nebat", "Book"], 22),
    word(1, "In verse 22, what word completes this phrase: “He said to him who was in charge of the wardrobe, \"_____ out the vestments for all the worshipers of Ba’al.\" So he brought out”?", "Bring", 22, ["bring"]),
    tf(2, "The RSV does not state: “He said to him who was in charge of the wardrobe, \"Bring out the vestments for all the worshipers of Ba’al.\" So he brought out the vestments for them.”", false, 22, "The quoted wording is the RSV text of this verse."),
    blank(3, "Then Jehu went into the house of Ba’al with _____ the son of Rechab; and he said to the worshipers of Ba’al, \"Search, and", "Jehon’adab", 23, ["jehonadab"]),
    mc(1, "Which word correctly completes this RSV wording: “Then Jehu went into the house of Ba’al with _____ the son of Rechab; and he said to the worshipers of Ba’al, \"Search, and”", ["Jehon’adab", "Israel", "Reubenites", "Eli’jah"], 23),
    word(2, "In verse 23, what word completes this phrase: “Then Jehu went into the house of Ba’al with _____ the son of Rechab; and he said to the worshipers of Ba’al, \"Search, and”?", "Jehon’adab", 23, ["jehonadab"]),
    tf(3, "The RSV states: “Then Jehu went into the house of Ba’al with Jehon’adab the son of Rechab; and he said to the worshipers of Ba’al, \"Search, and see that there is no servant of the LORD here among you, but only the worshipers of Ba’al.\"”", true, 23),
    blank(1, "Then he went in to offer sacrifices and burnt offerings. Now _____ had stationed eighty men outside, and said, \"The man who allows any of", "Jehu", 24, ["jehu"]),
    mc(2, "Which word correctly completes this RSV wording: “Then he went in to offer sacrifices and burnt offerings. Now _____ had stationed eighty men outside, and said, \"The man who allows any of”", ["Jehu", "Jezreel", "Sanctify", "Gilead"], 24),
    word(3, "In verse 24, what word completes this phrase: “Then he went in to offer sacrifices and burnt offerings. Now _____ had stationed eighty men outside, and said, \"The man who allows any of”?", "Jehu", 24, ["jehu"]),
    tf(1, "The RSV does not state: “Then he went in to offer sacrifices and burnt offerings. Now Jehu had stationed eighty men outside, and said, \"The man who allows any of those whom I give into your hands to escape shall forfeit his life.\"”", false, 24, "The quoted wording is the RSV text of this verse."),
    blank(2, "the officers cast them out and went into the inner room of the house of _____", "Ba’al", 25, ["baal"]),
    mc(3, "Which word correctly completes this RSV wording: “the officers cast them out and went into the inner room of the house of _____”", ["Ba’al", "Bashan", "Eli’jah", "Bring"], 25),
    word(1, "In verse 25, what word completes this phrase: “the officers cast them out and went into the inner room of the house of _____”?", "Ba’al", 25, ["baal"]),
    tf(2, "The RSV states: “So as soon as he had made an end of offering the burnt offering, Jehu said to the guard and to the officers, \"Go in and slay them; let not a man escape.\" So when they put them to the sword, the guard and the officers cast them out and went into the inner room of the house of Ba’al”", true, 25),
    blank(3, "and they brought out the pillar that was in the house of _____, and burned it.", "Ba’al", 26, ["baal"]),
    mc(1, "Which word correctly completes this RSV wording: “and they brought out the pillar that was in the house of _____, and burned it.”", ["Ba’al", "Jehu", "Rechab", "Haz’ael"], 26),
    word(2, "In verse 26, what word completes this phrase: “and they brought out the pillar that was in the house of _____, and burned it.”?", "Ba’al", 26, ["baal"]),
    tf(3, "The RSV does not state: “and they brought out the pillar that was in the house of Ba’al, and burned it.”", false, 26, "The quoted wording is the RSV text of this verse."),
    blank(1, "And they demolished the pillar of _____, and demolished the house of Ba’al, and made it a latrine to this day.", "Ba’al", 27, ["baal"]),
    mc(2, "Which word correctly completes this RSV wording: “And they demolished the pillar of _____, and demolished the house of Ba’al, and made it a latrine to this day.”", ["Ba’al", "Ahazi’ah", "Jerobo’am", "Bashan"], 27),
    word(3, "In verse 27, what word completes this phrase: “And they demolished the pillar of _____, and demolished the house of Ba’al, and made it a latrine to this day.”?", "Ba’al", 27, ["baal"]),
    tf(1, "The RSV states: “And they demolished the pillar of Ba’al, and demolished the house of Ba’al, and made it a latrine to this day.”", true, 27),
    blank(2, "Thus Jehu wiped out Ba’al from _____.", "Israel", 28, ["israel"]),
    mc(3, "Which word correctly completes this RSV wording: “Thus Jehu wiped out Ba’al from _____.”", ["Israel", "Take", "Bethel", "Book"], 28),
    word(1, "In verse 28, what word completes this phrase: “Thus Jehu wiped out Ba’al from _____.”?", "Israel", 28, ["israel"]),
    tf(2, "The RSV does not state: “Thus Jehu wiped out Ba’al from Israel.”", false, 28, "The quoted wording is the RSV text of this verse."),
    blank(3, "But Jehu did not turn aside from the sins of _____ the son of Nebat, which he made Israel to sin, the golden calves that", "Jerobo’am", 29, ["jeroboam"]),
    mc(1, "Which word correctly completes this RSV wording: “But Jehu did not turn aside from the sins of _____ the son of Nebat, which he made Israel to sin, the golden calves that”", ["Jerobo’am", "Bring", "Manas’sites", "Behold"], 29),
    word(2, "In verse 29, what word completes this phrase: “But Jehu did not turn aside from the sins of _____ the son of Nebat, which he made Israel to sin, the golden calves that”?", "Jerobo’am", 29, ["jeroboam"]),
    tf(3, "The RSV states: “But Jehu did not turn aside from the sins of Jerobo’am the son of Nebat, which he made Israel to sin, the golden calves that were in Bethel, and in Dan.”", true, 29),
    blank(1, "And the LORD said to Jehu, \"_____ you have done well in carrying out what is right in my eyes, and have", "Because", 30, ["because"]),
    mc(2, "Which word correctly completes this RSV wording: “And the LORD said to Jehu, \"_____ you have done well in carrying out what is right in my eyes, and have”", ["Because", "Jordan", "Jeho’ahaz", "Judah"], 30),
    word(3, "In verse 30, what word completes this phrase: “And the LORD said to Jehu, \"_____ you have done well in carrying out what is right in my eyes, and have”?", "Because", 30, ["because"]),
    tf(1, "The RSV does not state: “And the LORD said to Jehu, \"Because you have done well in carrying out what is right in my eyes, and have done to the house of Ahab according to all that was in my heart, your sons of the fourth generation shall sit on the throne of Israel.\"”", false, 30, "The quoted wording is the RSV text of this verse."),
    blank(2, "the God of Israel with all his heart; he did not turn from the sins of _____, which he made Israel to sin.", "Jerobo’am", 31, ["jeroboam"]),
    mc(3, "Which word correctly completes this RSV wording: “the God of Israel with all his heart; he did not turn from the sins of _____, which he made Israel to sin.”", ["Jerobo’am", "Bashan", "Eli’jah", "Israel"], 31),
    word(1, "In verse 31, what word completes this phrase: “the God of Israel with all his heart; he did not turn from the sins of _____, which he made Israel to sin.”?", "Jerobo’am", 31, ["jeroboam"]),
    tf(2, "The RSV states: “But Jehu was not careful to walk in the law of the LORD the God of Israel with all his heart; he did not turn from the sins of Jerobo’am, which he made Israel to sin.”", true, 31),
    blank(3, "In those days the LORD began to cut off parts of Israel. _____ defeated them throughout the territory of Israel:", "Haz’ael", 32, ["hazael"]),
    mc(1, "Which word correctly completes this RSV wording: “In those days the LORD began to cut off parts of Israel. _____ defeated them throughout the territory of Israel:”", ["Haz’ael", "Jehu", "Rechab", "Because"], 32),
    word(2, "In verse 32, what word completes this phrase: “In those days the LORD began to cut off parts of Israel. _____ defeated them throughout the territory of Israel:”?", "Haz’ael", 32, ["hazael"]),
    tf(3, "The RSV does not state: “In those days the LORD began to cut off parts of Israel. Haz’ael defeated them throughout the territory of Israel:”", false, 32, "The quoted wording is the RSV text of this verse."),
    blank(1, "eastward, all the land of Gilead, the Gadites, and the Reubenites, and the _____, from Aro’er, which is by the valley of the Arnon, that is, Gilead and", "Manas’sites", 33, ["manassites"]),
    mc(2, "Which word correctly completes this RSV wording: “eastward, all the land of Gilead, the Gadites, and the Reubenites, and the _____, from Aro’er, which is by the valley of the Arnon, that is, Gilead and”", ["Manas’sites", "Haz’ael", "Jezreel", "Bethel"], 33),
    word(3, "In verse 33, what word completes this phrase: “eastward, all the land of Gilead, the Gadites, and the Reubenites, and the _____, from Aro’er, which is by the valley of the Arnon, that is, Gilead and”?", "Manas’sites", 33, ["manassites"]),
    tf(1, "The RSV states: “from the Jordan eastward, all the land of Gilead, the Gadites, and the Reubenites, and the Manas’sites, from Aro’er, which is by the valley of the Arnon, that is, Gilead and Bashan.”", true, 33),
    blank(2, "that he did, and all his might, are they not written in the Book of the _____ of the Kings of Israel?", "Chronicles", 34, ["chronicles"]),
    mc(3, "Which word correctly completes this RSV wording: “that he did, and all his might, are they not written in the Book of the _____ of the Kings of Israel?”", ["Chronicles", "Kings", "Rechab", "Jordan"], 34),
    word(1, "In verse 34, what word completes this phrase: “that he did, and all his might, are they not written in the Book of the _____ of the Kings of Israel?”?", "Chronicles", 34, ["chronicles"]),
    tf(2, "The RSV does not state: “Now the rest of the acts of Jehu, and all that he did, and all his might, are they not written in the Book of the Chronicles of the Kings of Israel?”", false, 34, "The quoted wording is the RSV text of this verse."),
    blank(3, "So Jehu slept with his fathers, and they buried him in Sama’ria. And _____ his son reigned in his stead.", "Jeho’ahaz", 35, ["jehoahaz"]),
    mc(1, "Which word correctly completes this RSV wording: “So Jehu slept with his fathers, and they buried him in Sama’ria. And _____ his son reigned in his stead.”", ["Jeho’ahaz", "Bethel", "Book", "Shepherds"], 35),
    word(2, "In verse 35, what word completes this phrase: “So Jehu slept with his fathers, and they buried him in Sama’ria. And _____ his son reigned in his stead.”?", "Jeho’ahaz", 35, ["jehoahaz"]),
    tf(3, "The RSV states: “So Jehu slept with his fathers, and they buried him in Sama’ria. And Jeho’ahaz his son reigned in his stead.”", true, 35),
    blank(1, "The time that Jehu reigned over Israel in _____ was twenty-eight years.", "Sama’ria", 36, ["samaria"]),
    mc(2, "Which word correctly completes this RSV wording: “The time that Jehu reigned over Israel in _____ was twenty-eight years.”", ["Sama’ria", "Aro’er", "Know", "Sanctify"], 36),
    word(3, "In verse 36, what word completes this phrase: “The time that Jehu reigned over Israel in _____ was twenty-eight years.”?", "Sama’ria", 36, ["samaria"]),
    tf(1, "The RSV does not state: “The time that Jehu reigned over Israel in Sama’ria was twenty-eight years.”", false, 36, "The quoted wording is the RSV text of this verse."),
    mc(2, "What proof of loyalty did Jehu demand concerning Ahab’s seventy sons?", ["Their heads, sent in baskets to Jezreel and placed in two heaps at the gate", "Their royal seals", "Their weapons and chariots", "Written oaths from each son"], 8),
    mc(3, "How did Jehu gather and destroy the worshipers of Baal?", ["He proclaimed a great sacrifice, gathered them into Baal’s house, had them slain, and made the house a latrine", "He ordered them exiled to Sidon", "He burned the house while it was empty", "He challenged their prophets on Mount Carmel"], 27),
  ],
};

export default bank;
