// 2 Kings 25 — quiz bank (RSV). Four verse-anchored forms per verse.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: "2 Kings",
  chapter: 25,
  tag: "quiz-v2-2kings-25",
  rows: [
    blank(2, "year of his reign, in the tenth month, on the tenth day of the month, _____ king of Babylon came with all his army against Jerusalem, and laid siege", "Nebuchadnez’zar", 1, ["nebuchadnezzar"]),
    mc(3, "Which word correctly completes this RSV wording: “year of his reign, in the tenth month, on the tenth day of the month, _____ king of Babylon came with all his army against Jerusalem, and laid siege”", ["Nebuchadnez’zar", "Ma-ac’athite", "Jehoi’achin", "Evil-mero’dach"], 1),
    word(1, "In verse 1, what word completes this phrase: “year of his reign, in the tenth month, on the tenth day of the month, _____ king of Babylon came with all his army against Jerusalem, and laid siege”?", "Nebuchadnez’zar", 1, ["nebuchadnezzar"]),
    tf(2, "The RSV states: “And in the ninth year of his reign, in the tenth month, on the tenth day of the month, Nebuchadnez’zar king of Babylon came with all his army against Jerusalem, and laid siege to it; and they built siegeworks against it round about.”", true, 1),
    blank(3, "So the city was besieged till the eleventh year of King _____.", "Zedeki’ah", 2, ["zedekiah"]),
    mc(1, "Which word correctly completes this RSV wording: “So the city was besieged till the eleventh year of King _____.”", ["Zedeki’ah", "Ahi’kam", "Chalde’an", "Jericho"], 2),
    word(2, "In verse 2, what word completes this phrase: “So the city was besieged till the eleventh year of King _____.”?", "Zedeki’ah", 2, ["zedekiah"]),
    tf(3, "The RSV does not state: “So the city was besieged till the eleventh year of King Zedeki’ah.”", false, 2, "The quoted wording is the RSV text of this verse."),
    blank(1, "On the ninth day of the _____ month the famine was so severe in the city that there was no food for", "fourth", 3, ["fourth"]),
    mc(2, "Which word correctly completes this RSV wording: “On the ninth day of the _____ month the famine was so severe in the city that there was no food for”", ["fourth", "food", "garden", "passed"], 3),
    word(3, "In verse 3, what word completes this phrase: “On the ninth day of the _____ month the famine was so severe in the city that there was no food for”?", "fourth", 3, ["fourth"]),
    tf(1, "The RSV states: “On the ninth day of the fourth month the famine was so severe in the city that there was no food for the people of the land.”", true, 3),
    blank(2, "way of the gate between the two walls, by the king’s garden, though the _____ were around the city. And they went in the direction of the Arabah.", "Chalde’ans", 4, ["chaldeans"]),
    mc(3, "Which word correctly completes this RSV wording: “way of the gate between the two walls, by the king’s garden, though the _____ were around the city. And they went in the direction of the Arabah.”", ["Chalde’ans", "Jehoi’achin", "Serai’ah", "Kare’ah"], 4),
    word(1, "In verse 4, what word completes this phrase: “way of the gate between the two walls, by the king’s garden, though the _____ were around the city. And they went in the direction of the Arabah.”?", "Chalde’ans", 4, ["chaldeans"]),
    tf(2, "The RSV does not state: “Then a breach was made in the city; the king with all the men of war fled by night by the way of the gate between the two walls, by the king’s garden, though the Chalde’ans were around the city. And they went in the direction of the Arabah.”", false, 4, "The quoted wording is the RSV text of this verse."),
    blank(3, "But the army of the _____ pursued the king, and overtook him in the plains of Jericho; and all his", "Chalde’ans", 5, ["chaldeans"]),
    mc(1, "Which word correctly completes this RSV wording: “But the army of the _____ pursued the king, and overtook him in the plains of Jericho; and all his”", ["Chalde’ans", "Jericho", "Mizpah", "Egypt"], 5),
    word(2, "In verse 5, what word completes this phrase: “But the army of the _____ pursued the king, and overtook him in the plains of Jericho; and all his”?", "Chalde’ans", 5, ["chaldeans"]),
    tf(3, "The RSV states: “But the army of the Chalde’ans pursued the king, and overtook him in the plains of Jericho; and all his army was scattered from him.”", true, 5),
    blank(1, "Then they captured the king, and brought him up to the king of _____ at Riblah, who passed sentence upon him.", "Babylon", 6, ["babylon"]),
    mc(2, "Which word correctly completes this RSV wording: “Then they captured the king, and brought him up to the king of _____ at Riblah, who passed sentence upon him.”", ["Babylon", "Shaphan", "Jews", "Serai’ah"], 6),
    word(3, "In verse 6, what word completes this phrase: “Then they captured the king, and brought him up to the king of _____ at Riblah, who passed sentence upon him.”?", "Babylon", 6, ["babylon"]),
    tf(1, "The RSV does not state: “Then they captured the king, and brought him up to the king of Babylon at Riblah, who passed sentence upon him.”", false, 6, "The quoted wording is the RSV text of this verse."),
    blank(2, "They slew the sons of _____ before his eyes, and put out the eyes of Zedeki’ah, and bound him in fetters,", "Zedeki’ah", 7, ["zedekiah"]),
    mc(3, "Which word correctly completes this RSV wording: “They slew the sons of _____ before his eyes, and put out the eyes of Zedeki’ah, and bound him in fetters,”", ["Zedeki’ah", "Nethani’ah", "Jehoi’achin", "Serai’ah"], 7),
    word(1, "In verse 7, what word completes this phrase: “They slew the sons of _____ before his eyes, and put out the eyes of Zedeki’ah, and bound him in fetters,”?", "Zedeki’ah", 7, ["zedekiah"]),
    tf(2, "The RSV states: “They slew the sons of Zedeki’ah before his eyes, and put out the eyes of Zedeki’ah, and bound him in fetters, and took him to Babylon.”", true, 7),
    blank(3, "the seventh day of the month -- which was the nineteenth year of King _____, king of Babylon -- Nebu’zarad’an, the captain of the bodyguard, a servant", "Nebuchadnez’zar", 8, ["nebuchadnezzar"]),
    mc(1, "Which word correctly completes this RSV wording: “the seventh day of the month -- which was the nineteenth year of King _____, king of Babylon -- Nebu’zarad’an, the captain of the bodyguard, a servant”", ["Nebuchadnez’zar", "Ja-azani’ah", "Ma-ac’athite", "Jehoi’achin"], 8),
    word(2, "In verse 8, what word completes this phrase: “the seventh day of the month -- which was the nineteenth year of King _____, king of Babylon -- Nebu’zarad’an, the captain of the bodyguard, a servant”?", "Nebuchadnez’zar", 8, ["nebuchadnezzar"]),
    tf(3, "The RSV does not state: “In the fifth month, on the seventh day of the month -- which was the nineteenth year of King Nebuchadnez’zar, king of Babylon -- Nebu’zarad’an, the captain of the bodyguard, a servant of the king of Babylon, came to Jerusalem.”", false, 8, "The quoted wording is the RSV text of this verse."),
    blank(1, "burned the house of the LORD, and the king’s house and all the houses of _____; every great house he burned down.", "Jerusalem", 9, ["jerusalem"]),
    mc(2, "Which word correctly completes this RSV wording: “burned the house of the LORD, and the king’s house and all the houses of _____; every great house he burned down.”", ["Jerusalem", "King", "Judah", "Ja-azani’ah"], 9),
    word(3, "In verse 9, what word completes this phrase: “burned the house of the LORD, and the king’s house and all the houses of _____; every great house he burned down.”?", "Jerusalem", 9, ["jerusalem"]),
    tf(1, "The RSV states: “And he burned the house of the LORD, and the king’s house and all the houses of Jerusalem; every great house he burned down.”", true, 9),
    blank(2, "And all the army of the _____, who were with the captain of the guard, broke down the walls around Jerusalem.", "Chalde’ans", 10, ["chaldeans"]),
    mc(3, "Which word correctly completes this RSV wording: “And all the army of the _____, who were with the captain of the guard, broke down the walls around Jerusalem.”", ["Chalde’ans", "Zephani’ah", "Tanhu’meth", "Jerusalem"], 10),
    word(1, "In verse 10, what word completes this phrase: “And all the army of the _____, who were with the captain of the guard, broke down the walls around Jerusalem.”?", "Chalde’ans", 10, ["chaldeans"]),
    tf(2, "The RSV does not state: “And all the army of the Chalde’ans, who were with the captain of the guard, broke down the walls around Jerusalem.”", false, 10, "The quoted wording is the RSV text of this verse."),
    blank(3, "deserted to the king of Babylon, together with the rest of the multitude, _____ the captain of the guard carried into exile.", "Nebu’zarad’an", 11, ["nebuzaradan"]),
    mc(1, "Which word correctly completes this RSV wording: “deserted to the king of Babylon, together with the rest of the multitude, _____ the captain of the guard carried into exile.”", ["Nebu’zarad’an", "Zephani’ah", "Jehoi’achin", "Joha’nan"], 11),
    word(2, "In verse 11, what word completes this phrase: “deserted to the king of Babylon, together with the rest of the multitude, _____ the captain of the guard carried into exile.”?", "Nebu’zarad’an", 11, ["nebuzaradan"]),
    tf(3, "The RSV states: “And the rest of the people who were left in the city and the deserters who had deserted to the king of Babylon, together with the rest of the multitude, Nebu’zarad’an the captain of the guard carried into exile.”", true, 11),
    blank(1, "But the captain of the guard left some of the poorest of the land to be _____ and plowmen.", "vinedressers", 12, ["vinedressers"]),
    mc(2, "Which word correctly completes this RSV wording: “But the captain of the guard left some of the poorest of the land to be _____ and plowmen.”", ["vinedressers", "poorest", "network", "appointed"], 12),
    word(3, "In verse 12, what word completes this phrase: “But the captain of the guard left some of the poorest of the land to be _____ and plowmen.”?", "vinedressers", 12, ["vinedressers"]),
    tf(1, "The RSV does not state: “But the captain of the guard left some of the poorest of the land to be vinedressers and plowmen.”", false, 12, "The quoted wording is the RSV text of this verse."),
    blank(2, "the stands and the bronze sea that were in the house of the LORD, the _____ broke in pieces, and carried the bronze to Babylon.", "Chalde’ans", 13, ["chaldeans"]),
    mc(3, "Which word correctly completes this RSV wording: “the stands and the bronze sea that were in the house of the LORD, the _____ broke in pieces, and carried the bronze to Babylon.”", ["Chalde’ans", "Babylon", "Judah", "Ja-azani’ah"], 13),
    word(1, "In verse 13, what word completes this phrase: “the stands and the bronze sea that were in the house of the LORD, the _____ broke in pieces, and carried the bronze to Babylon.”?", "Chalde’ans", 13, ["chaldeans"]),
    tf(2, "The RSV states: “And the pillars of bronze that were in the house of the LORD, and the stands and the bronze sea that were in the house of the LORD, the Chalde’ans broke in pieces, and carried the bronze to Babylon.”", true, 13),
    blank(3, "And they took away the pots, and the shovels, and the _____, and the dishes for incense and all the vessels of bronze used in the", "snuffers", 14, ["snuffers"]),
    mc(1, "Which word correctly completes this RSV wording: “And they took away the pots, and the shovels, and the _____, and the dishes for incense and all the vessels of bronze used in the”", ["snuffers", "weight", "chief", "mustered"], 14),
    word(2, "In verse 14, what word completes this phrase: “And they took away the pots, and the shovels, and the _____, and the dishes for incense and all the vessels of bronze used in the”?", "snuffers", 14, ["snuffers"]),
    tf(3, "The RSV does not state: “And they took away the pots, and the shovels, and the snuffers, and the dishes for incense and all the vessels of bronze used in the temple service,”", false, 14, "The quoted wording is the RSV text of this verse."),
    blank(1, "the _____ also, and the bowls. What was of gold the captain of the guard took away", "firepans", 15, ["firepans"]),
    mc(2, "Which word correctly completes this RSV wording: “the _____ also, and the bowls. What was of gold the captain of the guard took away”", ["firepans", "network", "council", "appointed"], 15),
    word(3, "In verse 15, what word completes this phrase: “the _____ also, and the bowls. What was of gold the captain of the guard took away”?", "firepans", 15, ["firepans"]),
    tf(1, "The RSV states: “the firepans also, and the bowls. What was of gold the captain of the guard took away as gold, and what was of silver, as silver.”", true, 15),
    blank(2, "As for the two pillars, the one sea, and the stands, which _____ had made for the house of the LORD, the bronze of all these vessels was", "Solomon", 16, ["solomon"]),
    mc(3, "Which word correctly completes this RSV wording: “As for the two pillars, the one sea, and the stands, which _____ had made for the house of the LORD, the bronze of all these vessels was”", ["Solomon", "Babylon", "Judah", "Ma-ac’athite"], 16),
    word(1, "In verse 16, what word completes this phrase: “As for the two pillars, the one sea, and the stands, which _____ had made for the house of the LORD, the bronze of all these vessels was”?", "Solomon", 16, ["solomon"]),
    tf(2, "The RSV does not state: “As for the two pillars, the one sea, and the stands, which Solomon had made for the house of the LORD, the bronze of all these vessels was beyond weight.”", false, 16, "The quoted wording is the RSV text of this verse."),
    blank(3, "of bronze; the height of the capital was three cubits; a network and _____, all of bronze, were upon the capital round about. And the second pillar", "pomegranates", 17, ["pomegranates"]),
    mc(1, "Which word correctly completes this RSV wording: “of bronze; the height of the capital was three cubits; a network and _____, all of bronze, were upon the capital round about. And the second pillar”", ["pomegranates", "allowance", "scattered", "deserted"], 17),
    word(2, "In verse 17, what word completes this phrase: “of bronze; the height of the capital was three cubits; a network and _____, all of bronze, were upon the capital round about. And the second pillar”?", "pomegranates", 17, ["pomegranates"]),
    tf(3, "The RSV states: “The height of the one pillar was eighteen cubits, and upon it was a capital of bronze; the height of the capital was three cubits; a network and pomegranates, all of bronze, were upon the capital round about. And the second pillar had the like, with the network.”", true, 17),
    blank(1, "And the captain of the guard took Serai’ah the chief priest, and _____ the second priest, and the three keepers of the threshold;", "Zephani’ah", 18, ["zephaniah"]),
    mc(2, "Which word correctly completes this RSV wording: “And the captain of the guard took Serai’ah the chief priest, and _____ the second priest, and the three keepers of the threshold;”", ["Zephani’ah", "Jericho", "Ish’mael", "Jehoi’achin"], 18),
    word(3, "In verse 18, what word completes this phrase: “And the captain of the guard took Serai’ah the chief priest, and _____ the second priest, and the three keepers of the threshold;”?", "Zephani’ah", 18, ["zephaniah"]),
    tf(1, "The RSV does not state: “And the captain of the guard took Serai’ah the chief priest, and Zephani’ah the second priest, and the three keepers of the threshold;”", false, 18, "The quoted wording is the RSV text of this verse."),
    blank(2, "and five men of the king’s council who were found in the city; and the _____ of the commander of the army who mustered the people of the land; and", "secretary", 19, ["secretary"]),
    mc(3, "Which word correctly completes this RSV wording: “and five men of the king’s council who were found in the city; and the _____ of the commander of the army who mustered the people of the land; and”", ["secretary", "heard", "royal", "graciously"], 19),
    word(1, "In verse 19, what word completes this phrase: “and five men of the king’s council who were found in the city; and the _____ of the commander of the army who mustered the people of the land; and”?", "secretary", 19, ["secretary"]),
    tf(2, "The RSV states: “and from the city he took an officer who had been in command of the men of war, and five men of the king’s council who were found in the city; and the secretary of the commander of the army who mustered the people of the land; and sixty men of the people of the land who were found in the city.”", true, 19),
    blank(3, "And _____ the captain of the guard took them, and brought them to the king of Babylon", "Nebu’zarad’an", 20, ["nebuzaradan"]),
    mc(1, "Which word correctly completes this RSV wording: “And _____ the captain of the guard took them, and brought them to the king of Babylon”", ["Nebu’zarad’an", "Chalde’an", "Ish’mael", "Nebuchadnez’zar"], 20),
    word(2, "In verse 20, what word completes this phrase: “And _____ the captain of the guard took them, and brought them to the king of Babylon”?", "Nebu’zarad’an", 20, ["nebuzaradan"]),
    tf(3, "The RSV does not state: “And Nebu’zarad’an the captain of the guard took them, and brought them to the king of Babylon at Riblah.”", false, 20, "The quoted wording is the RSV text of this verse."),
    blank(1, "And the king of _____ smote them, and put them to death at Riblah in the land of Hamath. So", "Babylon", 21, ["babylon"]),
    mc(2, "Which word correctly completes this RSV wording: “And the king of _____ smote them, and put them to death at Riblah in the land of Hamath. So”", ["Babylon", "Solomon", "Joha’nan", "King"], 21),
    word(3, "In verse 21, what word completes this phrase: “And the king of _____ smote them, and put them to death at Riblah in the land of Hamath. So”?", "Babylon", 21, ["babylon"]),
    tf(1, "The RSV states: “And the king of Babylon smote them, and put them to death at Riblah in the land of Hamath. So Judah was taken into exile out of its land.”", true, 21),
    blank(2, "And over the people who remained in the land of Judah, whom _____ king of Babylon had left, he appointed Gedali’ah the son of Ahi’kam, son", "Nebuchadnez’zar", 22, ["nebuchadnezzar"]),
    mc(3, "Which word correctly completes this RSV wording: “And over the people who remained in the land of Judah, whom _____ king of Babylon had left, he appointed Gedali’ah the son of Ahi’kam, son”", ["Nebuchadnez’zar", "Tanhu’meth", "Netoph’athite", "Ja-azani’ah"], 22),
    word(1, "In verse 22, what word completes this phrase: “And over the people who remained in the land of Judah, whom _____ king of Babylon had left, he appointed Gedali’ah the son of Ahi’kam, son”?", "Nebuchadnez’zar", 22, ["nebuchadnezzar"]),
    tf(2, "The RSV does not state: “And over the people who remained in the land of Judah, whom Nebuchadnez’zar king of Babylon had left, he appointed Gedali’ah the son of Ahi’kam, son of Shaphan, governor.”", false, 22, "The quoted wording is the RSV text of this verse."),
    blank(3, "and Joha’nan the son of Kare’ah, and Serai’ah the son of Tanhu’meth the _____, and Ja-azani’ah the son of the Ma-ac’athite.", "Netoph’athite", 23, ["netophathite"]),
    mc(1, "Which word correctly completes this RSV wording: “and Joha’nan the son of Kare’ah, and Serai’ah the son of Tanhu’meth the _____, and Ja-azani’ah the son of the Ma-ac’athite.”", ["Netoph’athite", "Evil-mero’dach", "Joha’nan", "Chalde’ans"], 23),
    word(2, "In verse 23, what word completes this phrase: “and Joha’nan the son of Kare’ah, and Serai’ah the son of Tanhu’meth the _____, and Ja-azani’ah the son of the Ma-ac’athite.”?", "Netoph’athite", 23, ["netophathite"]),
    tf(3, "The RSV states: “Now when all the captains of the forces in the open country and their men heard that the king of Babylon had appointed Gedali’ah governor, they came with their men to Gedali’ah at Mizpah, namely, Ish’mael the son of Nethani’ah, and Joha’nan the son of Kare’ah, and Serai’ah the son of Tanhu’meth the Netoph’athite, and Ja-azani’ah the son of the Ma-ac’athite.”", true, 23),
    blank(1, "And _____ swore to them and their men, saying, \"Do not be afraid because of the", "Gedali’ah", 24, ["gedaliah"]),
    mc(2, "Which word correctly completes this RSV wording: “And _____ swore to them and their men, saying, \"Do not be afraid because of the”", ["Gedali’ah", "Judah", "Ma-ac’athite", "Chalde’ans"], 24),
    word(3, "In verse 24, what word completes this phrase: “And _____ swore to them and their men, saying, \"Do not be afraid because of the”?", "Gedali’ah", 24, ["gedaliah"]),
    tf(1, "The RSV does not state: “And Gedali’ah swore to them and their men, saying, \"Do not be afraid because of the Chalde’an officials; dwell in the land, and serve the king of Babylon, and it shall be well with you.\"”", false, 24, "The quoted wording is the RSV text of this verse."),
    blank(2, "But in the seventh month, Ish’mael the son of _____, son of Eli’shama, of the royal family, came with ten men, and attacked", "Nethani’ah", 25, ["nethaniah"]),
    mc(3, "Which word correctly completes this RSV wording: “But in the seventh month, Ish’mael the son of _____, son of Eli’shama, of the royal family, came with ten men, and attacked”", ["Nethani’ah", "Chalde’an", "Jericho", "Mizpah"], 25),
    word(1, "In verse 25, what word completes this phrase: “But in the seventh month, Ish’mael the son of _____, son of Eli’shama, of the royal family, came with ten men, and attacked”?", "Nethani’ah", 25, ["nethaniah"]),
    tf(2, "The RSV states: “But in the seventh month, Ish’mael the son of Nethani’ah, son of Eli’shama, of the royal family, came with ten men, and attacked and killed Gedali’ah and the Jews and the Chalde’ans who were with him at Mizpah.”", true, 25),
    blank(3, "captains of the forces arose, and went to Egypt; for they were afraid of the _____.", "Chalde’ans", 26, ["chaldeans"]),
    mc(1, "Which word correctly completes this RSV wording: “captains of the forces arose, and went to Egypt; for they were afraid of the _____.”", ["Chalde’ans", "Jerusalem", "Gedali’ah", "Ma-ac’athite"], 26),
    word(2, "In verse 26, what word completes this phrase: “captains of the forces arose, and went to Egypt; for they were afraid of the _____.”?", "Chalde’ans", 26, ["chaldeans"]),
    tf(3, "The RSV does not state: “Then all the people, both small and great, and the captains of the forces arose, and went to Egypt; for they were afraid of the Chalde’ans.”", false, 26, "The quoted wording is the RSV text of this verse."),
    blank(1, "Judah, in the twelfth month, on the twenty-seventh day of the month, _____ king of Babylon, in the year that he began to reign, graciously freed", "Evil-mero’dach", 27, ["evil-merodach"]),
    mc(2, "Which word correctly completes this RSV wording: “Judah, in the twelfth month, on the twenty-seventh day of the month, _____ king of Babylon, in the year that he began to reign, graciously freed”", ["Evil-mero’dach", "Netoph’athite", "Zephani’ah", "Jerusalem"], 27),
    word(3, "In verse 27, what word completes this phrase: “Judah, in the twelfth month, on the twenty-seventh day of the month, _____ king of Babylon, in the year that he began to reign, graciously freed”?", "Evil-mero’dach", 27, ["evil-merodach"]),
    tf(1, "The RSV states: “And in the thirty-seventh year of the exile of Jehoi’achin king of Judah, in the twelfth month, on the twenty-seventh day of the month, Evil-mero’dach king of Babylon, in the year that he began to reign, graciously freed Jehoi’achin king of Judah from prison;”", true, 27),
    blank(2, "and gave him a seat above the seats of the kings who were with him in _____.", "Babylon", 28, ["babylon"]),
    mc(3, "Which word correctly completes this RSV wording: “and gave him a seat above the seats of the kings who were with him in _____.”", ["Babylon", "Jerusalem", "Judah", "Ma-ac’athite"], 28),
    word(1, "In verse 28, what word completes this phrase: “and gave him a seat above the seats of the kings who were with him in _____.”?", "Babylon", 28, ["babylon"]),
    tf(2, "The RSV does not state: “and he spoke kindly to him, and gave him a seat above the seats of the kings who were with him in Babylon.”", false, 28, "The quoted wording is the RSV text of this verse."),
    blank(3, "So _____ put off his prison garments. And every day of his life he dined regularly", "Jehoi’achin", 29, ["jehoiachin"]),
    mc(1, "Which word correctly completes this RSV wording: “So _____ put off his prison garments. And every day of his life he dined regularly”", ["Jehoi’achin", "Riblah", "Nethani’ah", "Babylon"], 29),
    word(2, "In verse 29, what word completes this phrase: “So _____ put off his prison garments. And every day of his life he dined regularly”?", "Jehoi’achin", 29, ["jehoiachin"]),
    tf(3, "The RSV states: “So Jehoi’achin put off his prison garments. And every day of his life he dined regularly at the king’s table;”", true, 29),
    blank(1, "and for his _____, a regular allowance was given him by the king, every day a portion, as", "allowance", 30, ["allowance"]),
    mc(2, "Which word correctly completes this RSV wording: “and for his _____, a regular allowance was given him by the king, every day a portion, as”", ["allowance", "though", "sentence", "captain"], 30),
    word(3, "In verse 30, what word completes this phrase: “and for his _____, a regular allowance was given him by the king, every day a portion, as”?", "allowance", 30, ["allowance"]),
    tf(1, "The RSV does not state: “and for his allowance, a regular allowance was given him by the king, every day a portion, as long as he lived.”", false, 30, "The quoted wording is the RSV text of this verse."),
    mc(2, "What was the last thing Zedekiah saw before he was blinded?", ["His sons being slain; then he was bound and taken to Babylon", "Jerusalem’s walls falling", "The temple burning", "Nebuchadnezzar entering the city"], 7),
    mc(3, "Who burned Jerusalem’s temple and great houses, and whom did he leave in the land?", ["Nebuzaradan; some of the poorest as vinedressers and plowmen", "Nebuchadnezzar; the priests and craftsmen", "Gedaliah; the royal officials", "Seraiah; the poorest soldiers"], 12),
    mc(3, "What kindness did Evil-merodach show Jehoiachin in the thirty-seventh year of exile?", ["He freed him, spoke kindly, seated him above other kings, and let him dine at the king’s table", "He returned him to Jerusalem as governor", "He restored all temple vessels to him", "He released every captive from Judah"], 30),
  ],
};

export default bank;
