// 2 Kings 5 — quiz bank (RSV). Four verse-anchored forms per verse.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: "2 Kings",
  chapter: 5,
  tag: "quiz-v2-2kings-5",
  rows: [
    blank(2, "_____, commander of the army of the king of Syria, was a great man with his", "Na’aman", 1, ["naaman"]),
    mc(3, "Which word correctly completes this RSV wording: “_____, commander of the army of the king of Syria, was a great man with his”", ["Na’aman", "Eli’sha", "Syrian", "Eli’sha’s"], 1),
    word(1, "In verse 1, what word completes this phrase: “_____, commander of the army of the king of Syria, was a great man with his”?", "Na’aman", 1, ["naaman"]),
    tf(2, "The RSV states: “Na’aman, commander of the army of the king of Syria, was a great man with his master and in high favor, because by him the LORD had given victory to Syria. He was a mighty man of valor, but he was a leper.”", true, 1),
    blank(3, "carried off a little maid from the land of Israel, and she waited on _____ wife.", "Na’aman’s", 2, ["naamans"]),
    mc(1, "Which word correctly completes this RSV wording: “carried off a little maid from the land of Israel, and she waited on _____ wife.”", ["Na’aman’s", "Could", "Sama’ria", "Wash"], 2),
    word(2, "In verse 2, what word completes this phrase: “carried off a little maid from the land of Israel, and she waited on _____ wife.”?", "Na’aman’s", 2, ["naamans"]),
    tf(3, "The RSV does not state: “Now the Syrians on one of their raids had carried off a little maid from the land of Israel, and she waited on Na’aman’s wife.”", false, 2, "The quoted wording is the RSV text of this verse."),
    blank(1, "to her mistress, \"Would that my lord were with the prophet who is in _____! He would cure him of his leprosy.\"", "Sama’ria", 3, ["samaria"]),
    mc(2, "Which word correctly completes this RSV wording: “to her mistress, \"Would that my lord were with the prophet who is in _____! He would cure him of his leprosy.\"”", ["Sama’ria", "Na’aman", "Aba’na", "Syria"], 3),
    word(3, "In verse 3, what word completes this phrase: “to her mistress, \"Would that my lord were with the prophet who is in _____! He would cure him of his leprosy.\"”?", "Sama’ria", 3, ["samaria"]),
    tf(1, "The RSV states: “She said to her mistress, \"Would that my lord were with the prophet who is in Sama’ria! He would cure him of his leprosy.\"”", true, 3),
    blank(2, "So _____ went in and told his lord, \"Thus and so spoke the maiden from the land", "Na’aman", 4, ["naaman"]),
    mc(3, "Which word correctly completes this RSV wording: “So _____ went in and told his lord, \"Thus and so spoke the maiden from the land”", ["Na’aman", "Eli’sha", "Syrian", "Eli’sha’s"], 4),
    word(1, "In verse 4, what word completes this phrase: “So _____ went in and told his lord, \"Thus and so spoke the maiden from the land”?", "Na’aman", 4, ["naaman"]),
    tf(2, "The RSV does not state: “So Na’aman went in and told his lord, \"Thus and so spoke the maiden from the land of Israel.\"”", false, 4, "The quoted wording is the RSV text of this verse."),
    blank(3, "king of Syria said, \"Go now, and I will send a letter to the king of _____.\" So he went, taking with him ten talents of silver, six thousand shekels", "Israel", 5, ["israel"]),
    mc(1, "Which word correctly completes this RSV wording: “king of Syria said, \"Go now, and I will send a letter to the king of _____.\" So he went, taking with him ten talents of silver, six thousand shekels”", ["Israel", "Could", "Sama’ria", "Wash"], 5),
    word(2, "In verse 5, what word completes this phrase: “king of Syria said, \"Go now, and I will send a letter to the king of _____.\" So he went, taking with him ten talents of silver, six thousand shekels”?", "Israel", 5, ["israel"]),
    tf(3, "The RSV states: “And the king of Syria said, \"Go now, and I will send a letter to the king of Israel.\" So he went, taking with him ten talents of silver, six thousand shekels of gold, and ten festal garments.”", true, 5),
    blank(1, "which read, \"When this letter reaches you, know that I have sent to you _____ my servant, that you may cure him of his leprosy.\"", "Na’aman", 6, ["naaman"]),
    mc(2, "Which word correctly completes this RSV wording: “which read, \"When this letter reaches you, know that I have sent to you _____ my servant, that you may cure him of his leprosy.\"”", ["Na’aman", "Syria", "Aba’na", "Syrians"], 6),
    word(3, "In verse 6, what word completes this phrase: “which read, \"When this letter reaches you, know that I have sent to you _____ my servant, that you may cure him of his leprosy.\"”?", "Na’aman", 6, ["naaman"]),
    tf(1, "The RSV does not state: “And he brought the letter to the king of Israel, which read, \"When this letter reaches you, know that I have sent to you Na’aman my servant, that you may cure him of his leprosy.\"”", false, 6, "The quoted wording is the RSV text of this verse."),
    blank(2, "And when the king of _____ read the letter, he rent his clothes and said, \"Am I God, to kill and", "Israel", 7, ["israel"]),
    mc(3, "Which word correctly completes this RSV wording: “And when the king of _____ read the letter, he rent his clothes and said, \"Am I God, to kill and”", ["Israel", "Eli’sha", "Syrian", "Eli’sha’s"], 7),
    word(1, "In verse 7, what word completes this phrase: “And when the king of _____ read the letter, he rent his clothes and said, \"Am I God, to kill and”?", "Israel", 7, ["israel"]),
    tf(2, "The RSV states: “And when the king of Israel read the letter, he rent his clothes and said, \"Am I God, to kill and to make alive, that this man sends word to me to cure a man of his leprosy? Only consider, and see how he is seeking a quarrel with me.\"”", true, 7),
    blank(3, "But when _____ the man of God heard that the king of Israel had rent his clothes, he", "Eli’sha", 8, ["elisha"]),
    mc(1, "Which word correctly completes this RSV wording: “But when _____ the man of God heard that the king of Israel had rent his clothes, he”", ["Eli’sha", "Could", "Na’aman’s", "Wash"], 8),
    word(2, "In verse 8, what word completes this phrase: “But when _____ the man of God heard that the king of Israel had rent his clothes, he”?", "Eli’sha", 8, ["elisha"]),
    tf(3, "The RSV does not state: “But when Eli’sha the man of God heard that the king of Israel had rent his clothes, he sent to the king, saying, \"Why have you rent your clothes? Let him come now to me, that he may know that there is a prophet in Israel.\"”", false, 8, "The quoted wording is the RSV text of this verse."),
    blank(1, "Na’aman came with his horses and chariots, and halted at the door of _____ house.", "Eli’sha’s", 9, ["elishas"]),
    mc(2, "Which word correctly completes this RSV wording: “Na’aman came with his horses and chariots, and halted at the door of _____ house.”", ["Eli’sha’s", "Na’aman", "Aba’na", "Syria"], 9),
    word(3, "In verse 9, what word completes this phrase: “Na’aman came with his horses and chariots, and halted at the door of _____ house.”?", "Eli’sha’s", 9, ["elishas"]),
    tf(1, "The RSV states: “So Na’aman came with his horses and chariots, and halted at the door of Eli’sha’s house.”", true, 9),
    blank(2, "And _____ sent a messenger to him, saying, \"Go and wash in the Jordan seven times,", "Eli’sha", 10, ["elisha"]),
    mc(3, "Which word correctly completes this RSV wording: “And _____ sent a messenger to him, saying, \"Go and wash in the Jordan seven times,”", ["Eli’sha", "Only", "Syrian", "Eli’sha’s"], 10),
    word(1, "In verse 10, what word completes this phrase: “And _____ sent a messenger to him, saying, \"Go and wash in the Jordan seven times,”?", "Eli’sha", 10, ["elisha"]),
    tf(2, "The RSV does not state: “And Eli’sha sent a messenger to him, saying, \"Go and wash in the Jordan seven times, and your flesh shall be restored, and you shall be clean.\"”", false, 10, "The quoted wording is the RSV text of this verse."),
    blank(3, "But _____ was angry, and went away, saying, \"Behold, I thought that he would surely", "Na’aman", 11, ["naaman"]),
    mc(1, "Which word correctly completes this RSV wording: “But _____ was angry, and went away, saying, \"Behold, I thought that he would surely”", ["Na’aman", "Could", "Sama’ria", "Wash"], 11),
    word(2, "In verse 11, what word completes this phrase: “But _____ was angry, and went away, saying, \"Behold, I thought that he would surely”?", "Na’aman", 11, ["naaman"]),
    tf(3, "The RSV states: “But Na’aman was angry, and went away, saying, \"Behold, I thought that he would surely come out to me, and stand, and call on the name of the LORD his God, and wave his hand over the place, and cure the leper.”", true, 11),
    blank(1, "Are not Aba’na and Pharpar, the rivers of _____, better than all the waters of Israel? Could I not wash in them, and be", "Damascus", 12, ["damascus"]),
    mc(2, "Which word correctly completes this RSV wording: “Are not Aba’na and Pharpar, the rivers of _____, better than all the waters of Israel? Could I not wash in them, and be”", ["Damascus", "Na’aman", "Behold", "Syria"], 12),
    word(3, "In verse 12, what word completes this phrase: “Are not Aba’na and Pharpar, the rivers of _____, better than all the waters of Israel? Could I not wash in them, and be”?", "Damascus", 12, ["damascus"]),
    tf(1, "The RSV does not state: “Are not Aba’na and Pharpar, the rivers of Damascus, better than all the waters of Israel? Could I not wash in them, and be clean?\" So he turned and went away in a rage.”", false, 12, "The quoted wording is the RSV text of this verse."),
    blank(2, "would you not have done it? How much rather, then, when he says to you, `_____, and be clean’?\"", "Wash", 13, ["wash"]),
    mc(3, "Which word correctly completes this RSV wording: “would you not have done it? How much rather, then, when he says to you, `_____, and be clean’?\"”", ["Wash", "Only", "Syrian", "Eli’sha"], 13),
    word(1, "In verse 13, what word completes this phrase: “would you not have done it? How much rather, then, when he says to you, `_____, and be clean’?\"”?", "Wash", 13, ["wash"]),
    tf(2, "The RSV states: “But his servants came near and said to him, \"My father, if the prophet had commanded you to do some great thing, would you not have done it? How much rather, then, when he says to you, `Wash, and be clean’?\"”", true, 13),
    blank(3, "So he went down and dipped himself seven times in the _____, according to the word of the man of God; and his flesh was restored like", "Jordan", 14, ["jordan"]),
    mc(1, "Which word correctly completes this RSV wording: “So he went down and dipped himself seven times in the _____, according to the word of the man of God; and his flesh was restored like”", ["Jordan", "Could", "Na’aman’s", "Wash"], 14),
    word(2, "In verse 14, what word completes this phrase: “So he went down and dipped himself seven times in the _____, according to the word of the man of God; and his flesh was restored like”?", "Jordan", 14, ["jordan"]),
    tf(3, "The RSV does not state: “So he went down and dipped himself seven times in the Jordan, according to the word of the man of God; and his flesh was restored like the flesh of a little child, and he was clean.”", false, 14, "The quoted wording is the RSV text of this verse."),
    blank(1, "and all his company, and he came and stood before him; and he said, \"_____, I know that there is no God in all the earth but in Israel; so accept", "Behold", 15, ["behold"]),
    mc(2, "Which word correctly completes this RSV wording: “and all his company, and he came and stood before him; and he said, \"_____, I know that there is no God in all the earth but in Israel; so accept”", ["Behold", "Na’aman", "Aba’na", "Syria"], 15),
    word(3, "In verse 15, what word completes this phrase: “and all his company, and he came and stood before him; and he said, \"_____, I know that there is no God in all the earth but in Israel; so accept”?", "Behold", 15, ["behold"]),
    tf(1, "The RSV states: “Then he returned to the man of God, he and all his company, and he came and stood before him; and he said, \"Behold, I know that there is no God in all the earth but in Israel; so accept now a present from your servant.\"”", true, 15),
    blank(2, "But he said, \"As the LORD lives, whom I serve, I will _____ none.\" And he urged him to take it, but he refused.", "receive", 16, ["receive"]),
    mc(3, "Which word correctly completes this RSV wording: “But he said, \"As the LORD lives, whom I serve, I will _____ none.\" And he urged him to take it, but he refused.”", ["receive", "lives", "burnt", "short"], 16),
    word(1, "In verse 16, what word completes this phrase: “But he said, \"As the LORD lives, whom I serve, I will _____ none.\" And he urged him to take it, but he refused.”?", "receive", 16, ["receive"]),
    tf(2, "The RSV does not state: “But he said, \"As the LORD lives, whom I serve, I will receive none.\" And he urged him to take it, but he refused.”", false, 16, "The quoted wording is the RSV text of this verse."),
    blank(3, "Then _____ said, \"If not, I pray you, let there be given to your servant two mules’", "Na’aman", 17, ["naaman"]),
    mc(1, "Which word correctly completes this RSV wording: “Then _____ said, \"If not, I pray you, let there be given to your servant two mules’”", ["Na’aman", "Could", "Sama’ria", "Wash"], 17),
    word(2, "In verse 17, what word completes this phrase: “Then _____ said, \"If not, I pray you, let there be given to your servant two mules’”?", "Na’aman", 17, ["naaman"]),
    tf(3, "The RSV states: “Then Na’aman said, \"If not, I pray you, let there be given to your servant two mules’ burden of earth; for henceforth your servant will not offer burnt offering or sacrifice to any god but the LORD.”", true, 17),
    blank(1, "may the LORD pardon your servant: when my master goes into the house of _____ to worship there, leaning on my arm, and I bow myself in the house of", "Rimmon", 18, ["rimmon"]),
    mc(2, "Which word correctly completes this RSV wording: “may the LORD pardon your servant: when my master goes into the house of _____ to worship there, leaning on my arm, and I bow myself in the house of”", ["Rimmon", "Na’aman", "Behold", "Syria"], 18),
    word(3, "In verse 18, what word completes this phrase: “may the LORD pardon your servant: when my master goes into the house of _____ to worship there, leaning on my arm, and I bow myself in the house of”?", "Rimmon", 18, ["rimmon"]),
    tf(1, "The RSV does not state: “In this matter may the LORD pardon your servant: when my master goes into the house of Rimmon to worship there, leaning on my arm, and I bow myself in the house of Rimmon, when I bow myself in the house of Rimmon, the LORD pardon your servant in this matter.\"”", false, 18, "The quoted wording is the RSV text of this verse."),
    blank(2, "He said to him, \"Go in peace.\" But when _____ had gone from him a short distance,", "Na’aman", 19, ["naaman"]),
    mc(3, "Which word correctly completes this RSV wording: “He said to him, \"Go in peace.\" But when _____ had gone from him a short distance,”", ["Na’aman", "Eli’sha", "Syrian", "Eli’sha’s"], 19),
    word(1, "In verse 19, what word completes this phrase: “He said to him, \"Go in peace.\" But when _____ had gone from him a short distance,”?", "Na’aman", 19, ["naaman"]),
    tf(2, "The RSV states: “He said to him, \"Go in peace.\" But when Na’aman had gone from him a short distance,”", true, 19),
    blank(3, "_____, the servant of Eli’sha the man of God, said, \"See, my master has spared", "Geha’zi", 20, ["gehazi"]),
    mc(1, "Which word correctly completes this RSV wording: “_____, the servant of Eli’sha the man of God, said, \"See, my master has spared”", ["Geha’zi", "Damascus", "Na’aman’s", "Could"], 20),
    word(2, "In verse 20, what word completes this phrase: “_____, the servant of Eli’sha the man of God, said, \"See, my master has spared”?", "Geha’zi", 20, ["gehazi"]),
    tf(3, "The RSV does not state: “Geha’zi, the servant of Eli’sha the man of God, said, \"See, my master has spared this Na’aman the Syrian, in not accepting from his hand what he brought. As the LORD lives, I will run after him, and get something from him.\"”", false, 20, "The quoted wording is the RSV text of this verse."),
    blank(1, "So _____ followed Na’aman. And when Na’aman saw some one running after him, he", "Geha’zi", 21, ["gehazi"]),
    mc(2, "Which word correctly completes this RSV wording: “So _____ followed Na’aman. And when Na’aman saw some one running after him, he”", ["Geha’zi", "Na’aman", "Behold", "Syria"], 21),
    word(3, "In verse 21, what word completes this phrase: “So _____ followed Na’aman. And when Na’aman saw some one running after him, he”?", "Geha’zi", 21, ["gehazi"]),
    tf(1, "The RSV states: “So Geha’zi followed Na’aman. And when Na’aman saw some one running after him, he alighted from the chariot to meet him, and said, \"Is all well?\"”", true, 21),
    blank(2, "sent me to say, `There have just now come to me from the hill country of _____ two young men of the sons of the prophets; pray, give them a talent of", "E’phraim", 22, ["ephraim"]),
    mc(3, "Which word correctly completes this RSV wording: “sent me to say, `There have just now come to me from the hill country of _____ two young men of the sons of the prophets; pray, give them a talent of”", ["E’phraim", "Only", "Geha’zi", "Eli’sha"], 22),
    word(1, "In verse 22, what word completes this phrase: “sent me to say, `There have just now come to me from the hill country of _____ two young men of the sons of the prophets; pray, give them a talent of”?", "E’phraim", 22, ["ephraim"]),
    tf(2, "The RSV does not state: “And he said, \"All is well. My master has sent me to say, `There have just now come to me from the hill country of E’phraim two young men of the sons of the prophets; pray, give them a talent of silver and two festal garments.’\"”", false, 22, "The quoted wording is the RSV text of this verse."),
    blank(3, "And _____ said, \"Be pleased to accept two talents.\" And he urged him, and tied up", "Na’aman", 23, ["naaman"]),
    mc(1, "Which word correctly completes this RSV wording: “And _____ said, \"Be pleased to accept two talents.\" And he urged him, and tied up”", ["Na’aman", "Could", "Sama’ria", "Wash"], 23),
    word(2, "In verse 23, what word completes this phrase: “And _____ said, \"Be pleased to accept two talents.\" And he urged him, and tied up”?", "Na’aman", 23, ["naaman"]),
    tf(3, "The RSV states: “And Na’aman said, \"Be pleased to accept two talents.\" And he urged him, and tied up two talents of silver in two bags, with two festal garments, and laid them upon two of his servants; and they carried them before Geha’zi.”", true, 23),
    blank(1, "their hand, and put them in the house; and he sent the men away, and they _____.", "departed", 24, ["departed"]),
    mc(2, "Which word correctly completes this RSV wording: “their hand, and put them in the house; and he sent the men away, and they _____.”", ["departed", "oxen", "king", "raids"], 24),
    word(3, "In verse 24, what word completes this phrase: “their hand, and put them in the house; and he sent the men away, and they _____.”?", "departed", 24, ["departed"]),
    tf(1, "The RSV does not state: “And when he came to the hill, he took them from their hand, and put them in the house; and he sent the men away, and they departed.”", false, 24, "The quoted wording is the RSV text of this verse."),
    blank(2, "He went in, and stood before his master, and _____ said to him, \"Where have you been, Geha’zi?\" And he said, \"Your servant", "Eli’sha", 25, ["elisha"]),
    mc(3, "Which word correctly completes this RSV wording: “He went in, and stood before his master, and _____ said to him, \"Where have you been, Geha’zi?\" And he said, \"Your servant”", ["Eli’sha", "Only", "Syrian", "Eli’sha’s"], 25),
    word(1, "In verse 25, what word completes this phrase: “He went in, and stood before his master, and _____ said to him, \"Where have you been, Geha’zi?\" And he said, \"Your servant”?", "Eli’sha", 25, ["elisha"]),
    tf(2, "The RSV states: “He went in, and stood before his master, and Eli’sha said to him, \"Where have you been, Geha’zi?\" And he said, \"Your servant went nowhere.\"”", true, 25),
    blank(3, "garments, olive orchards and vineyards, sheep and oxen, menservants and _____?", "maidservants", 26, ["maidservants"]),
    mc(1, "Which word correctly completes this RSV wording: “garments, olive orchards and vineyards, sheep and oxen, menservants and _____?”", ["maidservants", "commanded", "worship", "pleased"], 26),
    word(2, "In verse 26, what word completes this phrase: “garments, olive orchards and vineyards, sheep and oxen, menservants and _____?”?", "maidservants", 26, ["maidservants"]),
    tf(3, "The RSV does not state: “But he said to him, \"Did I not go with you in spirit when the man turned from his chariot to meet you? Was it a time to accept money and garments, olive orchards and vineyards, sheep and oxen, menservants and maidservants?”", false, 26, "The quoted wording is the RSV text of this verse."),
    blank(1, "_____ the leprosy of Na’aman shall cleave to you, and to your descendants for", "Therefore", 27, ["therefore"]),
    mc(2, "Which word correctly completes this RSV wording: “_____ the leprosy of Na’aman shall cleave to you, and to your descendants for”", ["Therefore", "Na’aman", "Behold", "Syria"], 27),
    word(3, "In verse 27, what word completes this phrase: “_____ the leprosy of Na’aman shall cleave to you, and to your descendants for”?", "Therefore", 27, ["therefore"]),
    tf(1, "The RSV states: “Therefore the leprosy of Na’aman shall cleave to you, and to your descendants for ever.\" So he went out from his presence a leper, as white as snow.”", true, 27),
    blank(1, "Na’aman, _____ of the army of the king of Syria, was a great man with his master and", "commander", 1, ["commander"]),
    mc(2, "Select the missing RSV word: “Now the _____ on one of their raids had carried off a little maid from the land of Israel,”", ["Syrians", "Eli’sha", "Syrian", "Eli’sha’s"], 2),
    word(3, "What missing word belongs in this verse 3 clause: “She said to her _____, \"Would that my lord were with the prophet who is in Sama’ria! He would”?", "mistress", 3, ["mistress"]),
    tf(1, "This wording appears in verse 4: “So Na’aman went in and told his lord, \"Thus and so spoke the maiden from the land of Israel.\"”", true, 4),
    blank(2, "king of Israel.\" So he went, taking with him ten talents of silver, six _____ shekels of gold, and ten festal garments.", "thousand", 5, ["thousand"]),
    mc(3, "Select the missing RSV word: “And he _____ the letter to the king of Israel, which read, \"When this letter reaches”", ["brought", "waters", "rather", "stood"], 6),
    word(1, "What missing word belongs in this verse 7 clause: “alive, that this man sends word to me to cure a man of his leprosy? Only _____, and see how he is seeking a quarrel with me.\"”?", "consider", 7, ["consider"]),
    tf(2, "This wording appears in verse 8: “when Eli’sha the man of God heard that the king of Israel had rent his clothes, he sent to the king, saying, \"Why have you rent your clothes? Let him”", true, 8),
    blank(3, "So Na’aman came with his horses and _____, and halted at the door of Eli’sha’s house.", "chariots", 9, ["chariots"]),
    mc(1, "Select the missing RSV word: “And Eli’sha sent a _____ to him, saying, \"Go and wash in the Jordan seven times, and your flesh”", ["messenger", "followed", "prophets", "time"], 10),
    word(2, "What missing word belongs in this verse 11 clause: “But Na’aman was angry, and went away, saying, \"Behold, I _____ that he would surely come out to me, and stand, and call on the name of”?", "thought", 11, ["thought"]),
    tf(3, "This wording appears in verse 12: “Are not Aba’na and Pharpar, the rivers of Damascus, better than all the waters of Israel? Could I”", true, 12),
    mc(1, "Who first told Naaman’s household about the prophet in Samaria who could heal him?", ["A little Israelite maid serving Naaman’s wife", "The king of Syria", "Gehazi", "Naaman’s captain"], 3),
    mc(2, "What instruction from Elisha initially angered Naaman?", ["Wash in the Jordan seven times", "Offer seven sacrifices", "Fast for seven days", "Travel to Jerusalem"], 10),
    mc(2, "Which rivers did Naaman say were better than all the waters of Israel?", ["Abana and Pharpar", "Jordan and Kishon", "Habor and Gozan", "Kidron and Cherith"], 12),
    mc(3, "What was Naaman’s flesh like after he dipped seven times in the Jordan?", ["Like the flesh of a little child, and he was clean", "White as snow", "Covered with scars", "As it had been before the illness"], 14),
    mc(3, "What judgment came upon Gehazi for deceiving Naaman?", ["Naaman’s leprosy cleaved to Gehazi and his descendants, and he went out white as snow", "He was expelled from Israel", "He lost the silver and garments", "He became blind"], 27),
  ],
};

export default bank;
