// 2 Kings 21 — quiz bank (RSV). Four verse-anchored forms per verse.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: "2 Kings",
  chapter: 21,
  tag: "quiz-v2-2kings-21",
  rows: [
    blank(2, "reign, and he reigned fifty-five years in Jerusalem. His mother’s name was _____.", "Heph’zibah", 1, ["hephzibah"]),
    mc(3, "Which word correctly completes this RSV wording: “reign, and he reigned fifty-five years in Jerusalem. His mother’s name was _____.”", ["Heph’zibah", "Solomon", "Meshul’lemeth", "Jerusalem"], 1),
    word(1, "In verse 1, what word completes this phrase: “reign, and he reigned fifty-five years in Jerusalem. His mother’s name was _____.”?", "Heph’zibah", 1, ["hephzibah"]),
    tf(2, "The RSV states: “Manas’seh was twelve years old when he began to reign, and he reigned fifty-five years in Jerusalem. His mother’s name was Heph’zibah.”", true, 1),
    blank(3, "practices of the nations whom the LORD drove out before the people of _____.", "Israel", 2, ["israel"]),
    mc(1, "Which word correctly completes this RSV wording: “practices of the nations whom the LORD drove out before the people of _____.”", ["Israel", "Sama’ria", "Josi’ah", "Because"], 2),
    word(2, "In verse 2, what word completes this phrase: “practices of the nations whom the LORD drove out before the people of _____.”?", "Israel", 2, ["israel"]),
    tf(3, "The RSV does not state: “And he did what was evil in the sight of the LORD, according to the abominable practices of the nations whom the LORD drove out before the people of Israel.”", false, 2, "The quoted wording is the RSV text of this verse."),
    blank(1, "For he rebuilt the high places which _____ his father had destroyed; and he erected altars for Ba’al, and made an", "Hezeki’ah", 3, ["hezekiah"]),
    mc(2, "Which word correctly completes this RSV wording: “For he rebuilt the high places which _____ his father had destroyed; and he erected altars for Ba’al, and made an”", ["Hezeki’ah", "Amon", "Ashe’rah", "Moreover"], 3),
    word(3, "In verse 3, what word completes this phrase: “For he rebuilt the high places which _____ his father had destroyed; and he erected altars for Ba’al, and made an”?", "Hezeki’ah", 3, ["hezekiah"]),
    tf(1, "The RSV states: “For he rebuilt the high places which Hezeki’ah his father had destroyed; and he erected altars for Ba’al, and made an Ashe’rah, as Ahab king of Israel had done, and worshiped all the host of heaven, and served them.”", true, 3),
    blank(2, "built altars in the house of the LORD, of which the LORD had said, \"In _____ will I put my name.\"", "Jerusalem", 4, ["jerusalem"]),
    mc(3, "Which word correctly completes this RSV wording: “built altars in the house of the LORD, of which the LORD had said, \"In _____ will I put my name.\"”", ["Jerusalem", "Heph’zibah", "Amorites", "Haruz"], 4),
    word(1, "In verse 4, what word completes this phrase: “built altars in the house of the LORD, of which the LORD had said, \"In _____ will I put my name.\"”?", "Jerusalem", 4, ["jerusalem"]),
    tf(2, "The RSV does not state: “And he built altars in the house of the LORD, of which the LORD had said, \"In Jerusalem will I put my name.\"”", false, 4, "The quoted wording is the RSV text of this verse."),
    blank(3, "And he built _____ for all the host of heaven in the two courts of the house of the LORD.", "altars", 5, ["altars"]),
    mc(1, "Which word correctly completes this RSV wording: “And he built _____ for all the host of heaven in the two courts of the house of the LORD.”", ["altars", "offering", "image", "only"], 5),
    word(2, "In verse 5, what word completes this phrase: “And he built _____ for all the host of heaven in the two courts of the house of the LORD.”?", "altars", 5, ["altars"]),
    tf(3, "The RSV states: “And he built altars for all the host of heaven in the two courts of the house of the LORD.”", true, 5),
    blank(1, "And he burned his son as an offering, and practiced _____ and augury, and dealt with mediums and with wizards. He did much evil", "soothsaying", 6, ["soothsaying"]),
    mc(2, "Which word correctly completes this RSV wording: “And he burned his son as an offering, and practiced _____ and augury, and dealt with mediums and with wizards. He did much evil”", ["soothsaying", "wicked", "heritage", "garden"], 6),
    word(3, "In verse 6, what word completes this phrase: “And he burned his son as an offering, and practiced _____ and augury, and dealt with mediums and with wizards. He did much evil”?", "soothsaying", 6, ["soothsaying"]),
    tf(1, "The RSV does not state: “And he burned his son as an offering, and practiced soothsaying and augury, and dealt with mediums and with wizards. He did much evil in the sight of the LORD, provoking him to anger.”", false, 6, "The quoted wording is the RSV text of this verse."),
    blank(2, "the LORD said to David and to Solomon his son, \"In this house, and in _____, which I have chosen out of all the tribes of Israel, I will put my name", "Jerusalem", 7, ["jerusalem"]),
    mc(3, "Which word correctly completes this RSV wording: “the LORD said to David and to Solomon his son, \"In this house, and in _____, which I have chosen out of all the tribes of Israel, I will put my name”", ["Jerusalem", "Meshul’lemeth", "Ahab", "Book"], 7),
    word(1, "In verse 7, what word completes this phrase: “the LORD said to David and to Solomon his son, \"In this house, and in _____, which I have chosen out of all the tribes of Israel, I will put my name”?", "Jerusalem", 7, ["jerusalem"]),
    tf(2, "The RSV states: “And the graven image of Ashe’rah that he had made he set in the house of which the LORD said to David and to Solomon his son, \"In this house, and in Jerusalem, which I have chosen out of all the tribes of Israel, I will put my name for ever;”", true, 7),
    blank(3, "and I will not cause the feet of _____ to wander any more out of the land which I gave to their fathers, if only", "Israel", 8, ["israel"]),
    mc(1, "Which word correctly completes this RSV wording: “and I will not cause the feet of _____ to wander any more out of the land which I gave to their fathers, if only”", ["Israel", "Ba’al", "Egypt", "Manas’seh"], 8),
    word(2, "In verse 8, what word completes this phrase: “and I will not cause the feet of _____ to wander any more out of the land which I gave to their fathers, if only”?", "Israel", 8, ["israel"]),
    tf(3, "The RSV does not state: “and I will not cause the feet of Israel to wander any more out of the land which I gave to their fathers, if only they will be careful to do according to all that I have commanded them, and according to all the law that my servant Moses commanded them.\"”", false, 8, "The quoted wording is the RSV text of this verse."),
    blank(1, "But they did not listen, and _____ seduced them to do more evil than the nations had done whom the LORD destroyed", "Manas’seh", 9, ["manasseh"]),
    mc(2, "Which word correctly completes this RSV wording: “But they did not listen, and _____ seduced them to do more evil than the nations had done whom the LORD destroyed”", ["Manas’seh", "Moses", "Uzza", "Ba’al"], 9),
    word(3, "In verse 9, what word completes this phrase: “But they did not listen, and _____ seduced them to do more evil than the nations had done whom the LORD destroyed”?", "Manas’seh", 9, ["manasseh"]),
    tf(1, "The RSV states: “But they did not listen, and Manas’seh seduced them to do more evil than the nations had done whom the LORD destroyed before the people of Israel.”", true, 9),
    blank(2, "And the LORD said by his _____ the prophets,", "servants", 10, ["servants"]),
    mc(3, "Which word correctly completes this RSV wording: “And the LORD said by his _____ the prophets,”", ["servants", "idols", "over", "cast"], 10),
    word(1, "In verse 10, what word completes this phrase: “And the LORD said by his _____ the prophets,”?", "servants", 10, ["servants"]),
    tf(2, "The RSV does not state: “And the LORD said by his servants the prophets,”", false, 10, "The quoted wording is the RSV text of this verse."),
    blank(3, "\"Because _____ king of Judah has committed these abominations, and has done things more", "Manas’seh", 11, ["manasseh"]),
    mc(1, "Which word correctly completes this RSV wording: “\"Because _____ king of Judah has committed these abominations, and has done things more”", ["Manas’seh", "Haruz", "David", "Chronicles"], 11),
    word(2, "In verse 11, what word completes this phrase: “\"Because _____ king of Judah has committed these abominations, and has done things more”?", "Manas’seh", 11, ["manasseh"]),
    tf(3, "The RSV states: “\"Because Manas’seh king of Judah has committed these abominations, and has done things more wicked than all that the Amorites did, who were before him, and has made Judah also to sin with his idols;”", true, 11),
    blank(1, "therefore thus says the LORD, the God of Israel, Behold, I am bringing upon _____ and Judah such evil that the ears of every one who hears of it will tingle.", "Jerusalem", 12, ["jerusalem"]),
    mc(2, "Which word correctly completes this RSV wording: “therefore thus says the LORD, the God of Israel, Behold, I am bringing upon _____ and Judah such evil that the ears of every one who hears of it will tingle.”", ["Jerusalem", "Hezeki’ah", "Sama’ria", "King"], 12),
    word(3, "In verse 12, what word completes this phrase: “therefore thus says the LORD, the God of Israel, Behold, I am bringing upon _____ and Judah such evil that the ears of every one who hears of it will tingle.”?", "Jerusalem", 12, ["jerusalem"]),
    tf(1, "The RSV does not state: “therefore thus says the LORD, the God of Israel, Behold, I am bringing upon Jerusalem and Judah such evil that the ears of every one who hears of it will tingle.”", false, 12, "The quoted wording is the RSV text of this verse."),
    blank(2, "And I will stretch over _____ the measuring line of Sama’ria, and the plummet of the house of Ahab;", "Jerusalem", 13, ["jerusalem"]),
    mc(3, "Which word correctly completes this RSV wording: “And I will stretch over _____ the measuring line of Sama’ria, and the plummet of the house of Ahab;”", ["Jerusalem", "Because", "Amon", "Ashe’rah"], 13),
    word(1, "In verse 13, what word completes this phrase: “And I will stretch over _____ the measuring line of Sama’ria, and the plummet of the house of Ahab;”?", "Jerusalem", 13, ["jerusalem"]),
    tf(2, "The RSV states: “And I will stretch over Jerusalem the measuring line of Sama’ria, and the plummet of the house of Ahab; and I will wipe Jerusalem as one wipes a dish, wiping it and turning it upside down.”", true, 13),
    blank(3, "And I will cast off the remnant of my _____, and give them into the hand of their enemies, and they shall become a", "heritage", 14, ["heritage"]),
    mc(1, "Which word correctly completes this RSV wording: “And I will cast off the remnant of my _____, and give them into the hand of their enemies, and they shall become a”", ["heritage", "shall", "innocent", "garden"], 14),
    word(2, "In verse 14, what word completes this phrase: “And I will cast off the remnant of my _____, and give them into the hand of their enemies, and they shall become a”?", "heritage", 14, ["heritage"]),
    tf(3, "The RSV does not state: “And I will cast off the remnant of my heritage, and give them into the hand of their enemies, and they shall become a prey and a spoil to all their enemies,”", false, 14, "The quoted wording is the RSV text of this verse."),
    blank(1, "and have provoked me to anger, since the day their fathers came out of _____, even to this day.\"", "Egypt", 15, ["egypt"]),
    mc(2, "Which word correctly completes this RSV wording: “and have provoked me to anger, since the day their fathers came out of _____, even to this day.\"”", ["Egypt", "Jerusalem", "Judah", "Jotbah"], 15),
    word(3, "In verse 15, what word completes this phrase: “and have provoked me to anger, since the day their fathers came out of _____, even to this day.\"”?", "Egypt", 15, ["egypt"]),
    tf(1, "The RSV states: “because they have done what is evil in my sight and have provoked me to anger, since the day their fathers came out of Egypt, even to this day.\"”", true, 15),
    blank(2, "Moreover _____ shed very much innocent blood, till he had filled Jerusalem from one end", "Manas’seh", 16, ["manasseh"]),
    mc(3, "Which word correctly completes this RSV wording: “Moreover _____ shed very much innocent blood, till he had filled Jerusalem from one end”", ["Manas’seh", "Ba’al", "Egypt", "Josi’ah"], 16),
    word(1, "In verse 16, what word completes this phrase: “Moreover _____ shed very much innocent blood, till he had filled Jerusalem from one end”?", "Manas’seh", 16, ["manasseh"]),
    tf(2, "The RSV does not state: “ Moreover Manas’seh shed very much innocent blood, till he had filled Jerusalem from one end to another, besides the sin which he made Judah to sin so that they did what was evil in the sight of the LORD.”", false, 16, "The quoted wording is the RSV text of this verse."),
    blank(3, "and the sin that he committed, are they not written in the Book of the _____ of the Kings of Judah?", "Chronicles", 17, ["chronicles"]),
    mc(1, "Which word correctly completes this RSV wording: “and the sin that he committed, are they not written in the Book of the _____ of the Kings of Judah?”", ["Chronicles", "Moses", "Jotbah", "Jerusalem"], 17),
    word(2, "In verse 17, what word completes this phrase: “and the sin that he committed, are they not written in the Book of the _____ of the Kings of Judah?”?", "Chronicles", 17, ["chronicles"]),
    tf(3, "The RSV states: “Now the rest of the acts of Manas’seh, and all that he did, and the sin that he committed, are they not written in the Book of the Chronicles of the Kings of Judah?”", true, 17),
    blank(1, "And _____ slept with his fathers, and was buried in the garden of his house, in", "Manas’seh", 18, ["manasseh"]),
    mc(2, "Which word correctly completes this RSV wording: “And _____ slept with his fathers, and was buried in the garden of his house, in”", ["Manas’seh", "Chronicles", "Israel", "Behold"], 18),
    word(3, "In verse 18, what word completes this phrase: “And _____ slept with his fathers, and was buried in the garden of his house, in”?", "Manas’seh", 18, ["manasseh"]),
    tf(1, "The RSV does not state: “And Manas’seh slept with his fathers, and was buried in the garden of his house, in the garden of Uzza; and Amon his son reigned in his stead.”", false, 18, "The quoted wording is the RSV text of this verse."),
    blank(2, "to reign, and he reigned two years in Jerusalem. His mother’s name was _____ the daughter of Haruz of Jotbah.", "Meshul’lemeth", 19, ["meshullemeth"]),
    mc(3, "Which word correctly completes this RSV wording: “to reign, and he reigned two years in Jerusalem. His mother’s name was _____ the daughter of Haruz of Jotbah.”", ["Meshul’lemeth", "Moreover", "Manas’seh", "Heph’zibah"], 19),
    word(1, "In verse 19, what word completes this phrase: “to reign, and he reigned two years in Jerusalem. His mother’s name was _____ the daughter of Haruz of Jotbah.”?", "Meshul’lemeth", 19, ["meshullemeth"]),
    tf(2, "The RSV states: “ Amon was twenty-two years old when he began to reign, and he reigned two years in Jerusalem. His mother’s name was Meshul’lemeth the daughter of Haruz of Jotbah.”", true, 19),
    blank(3, "And he did what was evil in the sight of the LORD, as _____ his father had done.", "Manas’seh", 20, ["manasseh"]),
    mc(1, "Which word correctly completes this RSV wording: “And he did what was evil in the sight of the LORD, as _____ his father had done.”", ["Manas’seh", "Ashe’rah", "Moreover", "Jerusalem"], 20),
    word(2, "In verse 20, what word completes this phrase: “And he did what was evil in the sight of the LORD, as _____ his father had done.”?", "Manas’seh", 20, ["manasseh"]),
    tf(3, "The RSV does not state: “And he did what was evil in the sight of the LORD, as Manas’seh his father had done.”", false, 20, "The quoted wording is the RSV text of this verse."),
    blank(1, "which his father walked, and served the idols that his father served, and _____ them;", "worshiped", 21, ["worshiped"]),
    mc(2, "Which word correctly completes this RSV wording: “which his father walked, and served the idols that his father served, and _____ them;”", ["worshiped", "before", "done", "soothsaying"], 21),
    word(3, "In verse 21, what word completes this phrase: “which his father walked, and served the idols that his father served, and _____ them;”?", "worshiped", 21, ["worshiped"]),
    tf(1, "The RSV states: “He walked in all the way in which his father walked, and served the idols that his father served, and worshiped them;”", true, 21),
    blank(2, "he _____ the LORD, the God of his fathers, and did not walk in the way of the LORD.", "forsook", 22, ["forsook"]),
    mc(3, "Which word correctly completes this RSV wording: “he _____ the LORD, the God of his fathers, and did not walk in the way of the LORD.”", ["forsook", "erected", "said", "provoking"], 22),
    word(1, "In verse 22, what word completes this phrase: “he _____ the LORD, the God of his fathers, and did not walk in the way of the LORD.”?", "forsook", 22, ["forsook"]),
    tf(2, "The RSV does not state: “he forsook the LORD, the God of his fathers, and did not walk in the way of the LORD.”", false, 22, "The quoted wording is the RSV text of this verse."),
    blank(3, "And the servants of _____ conspired against him, and killed the king in his house.", "Amon", 23, ["amon"]),
    mc(1, "Which word correctly completes this RSV wording: “And the servants of _____ conspired against him, and killed the king in his house.”", ["Amon", "Book", "Ba’al", "Egypt"], 23),
    word(2, "In verse 23, what word completes this phrase: “And the servants of _____ conspired against him, and killed the king in his house.”?", "Amon", 23, ["amon"]),
    tf(3, "The RSV states: “And the servants of Amon conspired against him, and killed the king in his house.”", true, 23),
    blank(1, "who had conspired against King Amon, and the people of the land made _____ his son king in his stead.", "Josi’ah", 24, ["josiah"]),
    mc(2, "Which word correctly completes this RSV wording: “who had conspired against King Amon, and the people of the land made _____ his son king in his stead.”", ["Josi’ah", "Judah", "Haruz", "David"], 24),
    word(3, "In verse 24, what word completes this phrase: “who had conspired against King Amon, and the people of the land made _____ his son king in his stead.”?", "Josi’ah", 24, ["josiah"]),
    tf(1, "The RSV does not state: “But the people of the land slew all those who had conspired against King Amon, and the people of the land made Josi’ah his son king in his stead.”", false, 24, "The quoted wording is the RSV text of this verse."),
    blank(2, "the acts of Amon which he did, are they not written in the Book of the _____ of the Kings of Judah?", "Chronicles", 25, ["chronicles"]),
    mc(3, "Which word correctly completes this RSV wording: “the acts of Amon which he did, are they not written in the Book of the _____ of the Kings of Judah?”", ["Chronicles", "Josi’ah", "Because", "Jerusalem"], 25),
    word(1, "In verse 25, what word completes this phrase: “the acts of Amon which he did, are they not written in the Book of the _____ of the Kings of Judah?”?", "Chronicles", 25, ["chronicles"]),
    tf(2, "The RSV states: “Now the rest of the acts of Amon which he did, are they not written in the Book of the Chronicles of the Kings of Judah?”", true, 25),
    blank(3, "And he was buried in his tomb in the garden of Uzza; and _____ his son reigned in his stead.", "Josi’ah", 26, ["josiah"]),
    mc(1, "Which word correctly completes this RSV wording: “And he was buried in his tomb in the garden of Uzza; and _____ his son reigned in his stead.”", ["Josi’ah", "Manas’seh", "Because", "Amon"], 26),
    word(2, "In verse 26, what word completes this phrase: “And he was buried in his tomb in the garden of Uzza; and _____ his son reigned in his stead.”?", "Josi’ah", 26, ["josiah"]),
    tf(3, "The RSV does not state: “And he was buried in his tomb in the garden of Uzza; and Josi’ah his son reigned in his stead.”", false, 26, "The quoted wording is the RSV text of this verse."),
    blank(1, "Manas’seh was twelve years old when he began to reign, and he reigned _____ years in Jerusalem. His mother’s name was Heph’zibah.", "fifty-five", 1, ["fifty-five"]),
    mc(2, "Select the missing RSV word: “And he did what was evil in the sight of the LORD, according to the _____ practices of the nations whom the LORD drove out before the people of”", ["abominable", "practiced", "tribes", "committed"], 2),
    word(3, "What missing word belongs in this verse 3 clause: “For he rebuilt the high places which Hezeki’ah his father had _____; and he erected altars for Ba’al, and made an Ashe’rah, as Ahab king of”?", "destroyed", 3, ["destroyed"]),
    tf(1, "This wording appears in verse 4: “And he built altars in the house of the LORD, of which the LORD had said, \"In Jerusalem will”", true, 4),
    blank(2, "And he built altars for all the host of _____ in the two courts of the house of the LORD.", "heaven", 5, ["heaven"]),
    mc(3, "Select the missing RSV word: “And he burned his son as an offering, and _____ soothsaying and augury, and dealt with mediums and with wizards. He did”", ["practiced", "plummet", "give", "even"], 6),
    word(1, "What missing word belongs in this verse 7 clause: “And the graven image of _____ that he had made he set in the house of which the LORD said to David and”?", "Ashe’rah", 7, ["asherah"]),
    tf(2, "This wording appears in verse 8: “land which I gave to their fathers, if only they will be careful to do according to all that I have commanded them, and according to all the law that my”", true, 8),
    blank(3, "seduced them to do more evil than the nations had done whom the LORD _____ before the people of Israel.", "destroyed", 9, ["destroyed"]),
    mc(1, "Select the missing RSV word: “And the LORD said by his servants the _____,”", ["prophets", "evil", "places", "served"], 10),
    word(2, "What missing word belongs in this verse 11 clause: “\"Because Manas’seh king of Judah has committed these _____, and has done things more wicked than all that the Amorites did, who were”?", "abominations", 11, ["abominations"]),
    tf(3, "This wording appears in verse 12: “therefore thus says the LORD, the God of Israel, Behold, I am bringing upon Jerusalem”", true, 12),
    blank(1, "And I will stretch over Jerusalem the _____ line of Sama’ria, and the plummet of the house of Ahab; and I will wipe", "measuring", 13, ["measuring"]),
    mc(2, "Select the missing RSV word: “And I will cast off the _____ of my heritage, and give them into the hand of their enemies, and they”", ["remnant", "servants", "bringing", "wipe"], 14),
    word(3, "What missing word belongs in this verse 15 clause: “because they have done what is evil in my sight and have _____ me to anger, since the day their fathers came out of Egypt, even to this”?", "provoked", 15, ["provoked"]),
    tf(1, "This wording appears in verse 16: “Moreover Manas’seh shed very much innocent blood, till he had filled Jerusalem from one end to another, besides the sin which he made Judah to sin so”", true, 16),
    mc(1, "How old was Manasseh when he began to reign, and how long did he reign?", ["Twelve years old; fifty-five years", "Twenty years old; sixteen years", "Eight years old; thirty-one years", "Twenty-five years old; twenty-nine years"], 1),
    mc(3, "What image described the LORD’s coming judgment on Jerusalem?", ["Wiping Jerusalem like a dish, wiping it and turning it upside down", "Breaking Jerusalem like a potter’s vessel", "Sweeping Jerusalem with a broom", "Cutting Jerusalem down like a tree"], 13),
  ],
};

export default bank;
