// 2 Kings 18 — quiz bank (RSV). Four verse-anchored forms per verse.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: "2 Kings",
  chapter: 18,
  tag: "quiz-v2-2kings-18",
  rows: [
    blank(2, "In the third year of Hoshe’a son of Elah, king of Israel, _____ the son of Ahaz, king of Judah, began to reign.", "Hezeki’ah", 1, ["hezekiah"]),
    mc(3, "Which word correctly completes this RSV wording: “In the third year of Hoshe’a son of Elah, king of Israel, _____ the son of Ahaz, king of Judah, began to reign.”", ["Hezeki’ah", "David", "Halah", "Eli’akim"], 1),
    word(1, "In verse 1, what word completes this phrase: “In the third year of Hoshe’a son of Elah, king of Israel, _____ the son of Ahaz, king of Judah, began to reign.”?", "Hezeki’ah", 1, ["hezekiah"]),
    tf(2, "The RSV states: “In the third year of Hoshe’a son of Elah, king of Israel, Hezeki’ah the son of Ahaz, king of Judah, began to reign.”", true, 1),
    blank(3, "twenty-nine years in Jerusalem. His mother’s name was Abi the daughter of _____.", "Zechari’ah", 2, ["zechariah"]),
    mc(1, "Which word correctly completes this RSV wording: “twenty-nine years in Jerusalem. His mother’s name was Abi the daughter of _____.”", ["Zechari’ah", "Halah", "Eli’akim", "Arpad"], 2),
    word(2, "In verse 2, what word completes this phrase: “twenty-nine years in Jerusalem. His mother’s name was Abi the daughter of _____.”?", "Zechari’ah", 2, ["zechariah"]),
    tf(3, "The RSV does not state: “He was twenty-five years old when he began to reign, and he reigned twenty-nine years in Jerusalem. His mother’s name was Abi the daughter of Zechari’ah.”", false, 2, "The quoted wording is the RSV text of this verse."),
    blank(1, "he did what was right in the eyes of the LORD, according to all that _____ his father had done.", "David", 3, ["david"]),
    mc(2, "Which word correctly completes this RSV wording: “he did what was right in the eyes of the LORD, according to all that _____ his father had done.”", ["David", "Tartan", "Behold", "Arpad"], 3),
    word(3, "In verse 3, what word completes this phrase: “he did what was right in the eyes of the LORD, according to all that _____ his father had done.”?", "David", 3, ["david"]),
    tf(1, "The RSV states: “And he did what was right in the eyes of the LORD, according to all that David his father had done.”", true, 3),
    blank(2, "those days the people of Israel had burned incense to it; it was called _____.", "Nehush’tan", 4, ["nehushtan"]),
    mc(3, "Which word correctly completes this RSV wording: “those days the people of Israel had burned incense to it; it was called _____.”", ["Nehush’tan", "Jo’ah", "Shebna", "Philistines"], 4),
    word(1, "In verse 4, what word completes this phrase: “those days the people of Israel had burned incense to it; it was called _____.”?", "Nehush’tan", 4, ["nehushtan"]),
    tf(2, "The RSV does not state: “He removed the high places, and broke the pillars, and cut down the Ashe’rah. And he broke in pieces the bronze serpent that Moses had made, for until those days the people of Israel had burned incense to it; it was called Nehush’tan.”", false, 4, "The quoted wording is the RSV text of this verse."),
    blank(3, "He trusted in the LORD the God of _____; so that there was none like him among all the kings of Judah after him,", "Israel", 5, ["israel"]),
    mc(1, "Which word correctly completes this RSV wording: “He trusted in the LORD the God of _____; so that there was none like him among all the kings of Judah after him,”", ["Israel", "Such", "Hena", "Ashe’rah"], 5),
    word(2, "In verse 5, what word completes this phrase: “He trusted in the LORD the God of _____; so that there was none like him among all the kings of Judah after him,”?", "Israel", 5, ["israel"]),
    tf(3, "The RSV states: “He trusted in the LORD the God of Israel; so that there was none like him among all the kings of Judah after him, nor among those who were before him.”", true, 5),
    blank(1, "from following him, but kept the commandments which the LORD commanded _____.", "Moses", 6, ["moses"]),
    mc(2, "Which word correctly completes this RSV wording: “from following him, but kept the commandments which the LORD commanded _____.”", ["Moses", "Hamath", "Jerusalem", "Habor"], 6),
    word(3, "In verse 6, what word completes this phrase: “from following him, but kept the commandments which the LORD commanded _____.”?", "Moses", 6, ["moses"]),
    tf(1, "The RSV does not state: “For he held fast to the LORD; he did not depart from following him, but kept the commandments which the LORD commanded Moses.”", false, 6, "The quoted wording is the RSV text of this verse."),
    blank(2, "wherever he went forth, he prospered. He rebelled against the king of _____, and would not serve him.", "Assyria", 7, ["assyria"]),
    mc(3, "Which word correctly completes this RSV wording: “wherever he went forth, he prospered. He rebelled against the king of _____, and would not serve him.”", ["Assyria", "Ivvah", "Ashe’rah", "Gozan"], 7),
    word(1, "In verse 7, what word completes this phrase: “wherever he went forth, he prospered. He rebelled against the king of _____, and would not serve him.”?", "Assyria", 7, ["assyria"]),
    tf(2, "The RSV states: “And the LORD was with him; wherever he went forth, he prospered. He rebelled against the king of Assyria, and would not serve him.”", true, 7),
    blank(3, "He smote the _____ as far as Gaza and its territory, from watchtower to fortified city.", "Philistines", 8, ["philistines"]),
    mc(1, "Which word correctly completes this RSV wording: “He smote the _____ as far as Gaza and its territory, from watchtower to fortified city.”", ["Philistines", "Hezeki’ah", "Tartan", "Hamath"], 8),
    word(2, "In verse 8, what word completes this phrase: “He smote the _____ as far as Gaza and its territory, from watchtower to fortified city.”?", "Philistines", 8, ["philistines"]),
    tf(3, "The RSV does not state: “He smote the Philistines as far as Gaza and its territory, from watchtower to fortified city.”", false, 8, "The quoted wording is the RSV text of this verse."),
    blank(1, "Hezeki’ah, which was the seventh year of Hoshe’a son of Elah, king of Israel, _____ king of Assyria came up against Sama’ria and besieged it", "Shalmane’ser", 9, ["shalmaneser"]),
    mc(2, "Which word correctly completes this RSV wording: “Hezeki’ah, which was the seventh year of Hoshe’a son of Elah, king of Israel, _____ king of Assyria came up against Sama’ria and besieged it”", ["Shalmane’ser", "Moreover", "Sama’ria", "Jerusalem"], 9),
    word(3, "In verse 9, what word completes this phrase: “Hezeki’ah, which was the seventh year of Hoshe’a son of Elah, king of Israel, _____ king of Assyria came up against Sama’ria and besieged it”?", "Shalmane’ser", 9, ["shalmaneser"]),
    tf(1, "The RSV states: “In the fourth year of King Hezeki’ah, which was the seventh year of Hoshe’a son of Elah, king of Israel, Shalmane’ser king of Assyria came up against Sama’ria and besieged it”", true, 9),
    blank(2, "and at the end of three years he took it. In the sixth year of _____, which was the ninth year of Hoshe’a king of Israel, Sama’ria was taken.", "Hezeki’ah", 10, ["hezekiah"]),
    mc(3, "Which word correctly completes this RSV wording: “and at the end of three years he took it. In the sixth year of _____, which was the ninth year of Hoshe’a king of Israel, Sama’ria was taken.”", ["Hezeki’ah", "Habor", "Hilki’ah", "Pray"], 10),
    word(1, "In verse 10, what word completes this phrase: “and at the end of three years he took it. In the sixth year of _____, which was the ninth year of Hoshe’a king of Israel, Sama’ria was taken.”?", "Hezeki’ah", 10, ["hezekiah"]),
    tf(2, "The RSV does not state: “and at the end of three years he took it. In the sixth year of Hezeki’ah, which was the ninth year of Hoshe’a king of Israel, Sama’ria was taken.”", false, 10, "The quoted wording is the RSV text of this verse."),
    blank(3, "The king of Assyria carried the _____ away to Assyria, and put them in Halah, and on the Habor, the river of", "Israelites", 11, ["israelites"]),
    mc(1, "Which word correctly completes this RSV wording: “The king of Assyria carried the _____ away to Assyria, and put them in Halah, and on the Habor, the river of”", ["Israelites", "Sepharva’im", "Moses", "Lachish"], 11),
    word(2, "In verse 11, what word completes this phrase: “The king of Assyria carried the _____ away to Assyria, and put them in Halah, and on the Habor, the river of”?", "Israelites", 11, ["israelites"]),
    tf(3, "The RSV states: “The king of Assyria carried the Israelites away to Assyria, and put them in Halah, and on the Habor, the river of Gozan, and in the cities of the Medes,”", true, 11),
    blank(1, "voice of the LORD their God but transgressed his covenant, even all that _____ the servant of the LORD commanded; they neither listened nor obeyed.", "Moses", 12, ["moses"]),
    mc(2, "Which word correctly completes this RSV wording: “voice of the LORD their God but transgressed his covenant, even all that _____ the servant of the LORD commanded; they neither listened nor obeyed.”", ["Moses", "Moreover", "Elah", "Gaza"], 12),
    word(3, "In verse 12, what word completes this phrase: “voice of the LORD their God but transgressed his covenant, even all that _____ the servant of the LORD commanded; they neither listened nor obeyed.”?", "Moses", 12, ["moses"]),
    tf(1, "The RSV does not state: “because they did not obey the voice of the LORD their God but transgressed his covenant, even all that Moses the servant of the LORD commanded; they neither listened nor obeyed.”", false, 12, "The quoted wording is the RSV text of this verse."),
    blank(2, "In the fourteenth year of King Hezeki’ah _____ king of Assyria came up against all the fortified cities of Judah and", "Sennach’erib", 13, ["sennacherib"]),
    mc(3, "Which word correctly completes this RSV wording: “In the fourteenth year of King Hezeki’ah _____ king of Assyria came up against all the fortified cities of Judah and”", ["Sennach’erib", "Zechari’ah", "Fuller’s", "Jerusalem"], 13),
    word(1, "In verse 13, what word completes this phrase: “In the fourteenth year of King Hezeki’ah _____ king of Assyria came up against all the fortified cities of Judah and”?", "Sennach’erib", 13, ["sennacherib"]),
    tf(2, "The RSV states: “In the fourteenth year of King Hezeki’ah Sennach’erib king of Assyria came up against all the fortified cities of Judah and took them.”", true, 13),
    blank(3, "And _____ king of Judah sent to the king of Assyria at Lachish, saying, \"I have", "Hezeki’ah", 14, ["hezekiah"]),
    mc(1, "Which word correctly completes this RSV wording: “And _____ king of Judah sent to the king of Assyria at Lachish, saying, \"I have”", ["Hezeki’ah", "Sepharva’im", "David", "Halah"], 14),
    word(2, "In verse 14, what word completes this phrase: “And _____ king of Judah sent to the king of Assyria at Lachish, saying, \"I have”?", "Hezeki’ah", 14, ["hezekiah"]),
    tf(3, "The RSV does not state: “And Hezeki’ah king of Judah sent to the king of Assyria at Lachish, saying, \"I have done wrong; withdraw from me; whatever you impose on me I will bear.\" And the king of Assyria required of Hezeki’ah king of Judah three hundred talents of silver and thirty talents of gold.”", false, 14, "The quoted wording is the RSV text of this verse."),
    blank(1, "And _____ gave him all the silver that was found in the house of the LORD, and in", "Hezeki’ah", 15, ["hezekiah"]),
    mc(2, "Which word correctly completes this RSV wording: “And _____ gave him all the silver that was found in the house of the LORD, and in”", ["Hezeki’ah", "Ahaz", "King", "Rab’saris"], 15),
    word(3, "In verse 15, what word completes this phrase: “And _____ gave him all the silver that was found in the house of the LORD, and in”?", "Hezeki’ah", 15, ["hezekiah"]),
    tf(1, "The RSV states: “And Hezeki’ah gave him all the silver that was found in the house of the LORD, and in the treasuries of the king’s house.”", true, 15),
    blank(2, "At that time _____ stripped the gold from the doors of the temple of the LORD, and from the", "Hezeki’ah", 16, ["hezekiah"]),
    mc(3, "Which word correctly completes this RSV wording: “At that time _____ stripped the gold from the doors of the temple of the LORD, and from the”", ["Hezeki’ah", "Nehush’tan", "Medes", "Jo’ah"], 16),
    word(1, "In verse 16, what word completes this phrase: “At that time _____ stripped the gold from the doors of the temple of the LORD, and from the”?", "Hezeki’ah", 16, ["hezekiah"]),
    tf(2, "The RSV does not state: “At that time Hezeki’ah stripped the gold from the doors of the temple of the LORD, and from the doorposts which Hezeki’ah king of Judah had overlaid and gave it to the king of Assyria.”", false, 16, "The quoted wording is the RSV text of this verse."),
    blank(3, "And the king of Assyria sent the Tartan, the Rab’saris, and the _____ with a great army from Lachish to King Hezeki’ah at Jerusalem. And they", "Rab’shakeh", 17, ["rabshakeh"]),
    mc(1, "Which word correctly completes this RSV wording: “And the king of Assyria sent the Tartan, the Rab’saris, and the _____ with a great army from Lachish to King Hezeki’ah at Jerusalem. And they”", ["Rab’shakeh", "Shebna", "Assyria", "Tartan"], 17),
    word(2, "In verse 17, what word completes this phrase: “And the king of Assyria sent the Tartan, the Rab’saris, and the _____ with a great army from Lachish to King Hezeki’ah at Jerusalem. And they”?", "Rab’shakeh", 17, ["rabshakeh"]),
    tf(3, "The RSV states: “And the king of Assyria sent the Tartan, the Rab’saris, and the Rab’shakeh with a great army from Lachish to King Hezeki’ah at Jerusalem. And they went up and came to Jerusalem. When they arrived, they came and stood by the conduit of the upper pool, which is on the highway to the Fuller’s Field.”", true, 17),
    blank(1, "And when they called for the king, there came out to them _____ the son of Hilki’ah, who was over the household, and Shebnah the secretary,", "Eli’akim", 18, ["eliakim"]),
    mc(2, "Which word correctly completes this RSV wording: “And when they called for the king, there came out to them _____ the son of Hilki’ah, who was over the household, and Shebnah the secretary,”", ["Eli’akim", "Lachish", "Behold", "Arpad"], 18),
    word(3, "In verse 18, what word completes this phrase: “And when they called for the king, there came out to them _____ the son of Hilki’ah, who was over the household, and Shebnah the secretary,”?", "Eli’akim", 18, ["eliakim"]),
    tf(1, "The RSV does not state: “And when they called for the king, there came out to them Eli’akim the son of Hilki’ah, who was over the household, and Shebnah the secretary, and Jo’ah the son of Asaph, the recorder.”", false, 18, "The quoted wording is the RSV text of this verse."),
    blank(2, "And the _____ said to them, \"Say to Hezeki’ah, `Thus says the great king, the king of", "Rab’shakeh", 19, ["rabshakeh"]),
    mc(3, "Which word correctly completes this RSV wording: “And the _____ said to them, \"Say to Hezeki’ah, `Thus says the great king, the king of”", ["Rab’shakeh", "Sama’ria", "Field", "Hamath"], 19),
    word(1, "In verse 19, what word completes this phrase: “And the _____ said to them, \"Say to Hezeki’ah, `Thus says the great king, the king of”?", "Rab’shakeh", 19, ["rabshakeh"]),
    tf(2, "The RSV states: “And the Rab’shakeh said to them, \"Say to Hezeki’ah, `Thus says the great king, the king of Assyria: On what do you rest this confidence of yours?”", true, 19),
    blank(3, "Do you think that mere words are _____ and power for war? On whom do you now rely, that you have rebelled against", "strategy", 20, ["strategy"]),
    mc(1, "Which word correctly completes this RSV wording: “Do you think that mere words are _____ and power for war? On whom do you now rely, that you have rebelled against”", ["strategy", "make", "captain", "speak"], 20),
    word(2, "In verse 20, what word completes this phrase: “Do you think that mere words are _____ and power for war? On whom do you now rely, that you have rebelled against”?", "strategy", 20, ["strategy"]),
    tf(3, "The RSV does not state: “Do you think that mere words are strategy and power for war? On whom do you now rely, that you have rebelled against me?”", false, 20, "The quoted wording is the RSV text of this verse."),
    blank(1, "staff, which will pierce the hand of any man who leans on it. Such is _____ king of Egypt to all who rely on him.", "Pharaoh", 21, ["pharaoh"]),
    mc(2, "Which word correctly completes this RSV wording: “staff, which will pierce the hand of any man who leans on it. Such is _____ king of Egypt to all who rely on him.”", ["Pharaoh", "Hamath", "Judah", "Shalmane’ser"], 21),
    word(3, "In verse 21, what word completes this phrase: “staff, which will pierce the hand of any man who leans on it. Such is _____ king of Egypt to all who rely on him.”?", "Pharaoh", 21, ["pharaoh"]),
    tf(1, "The RSV states: “Behold, you are relying now on Egypt, that broken reed of a staff, which will pierce the hand of any man who leans on it. Such is Pharaoh king of Egypt to all who rely on him.”", true, 21),
    blank(2, "rely on the LORD our God,\" is it not he whose high places and altars _____ has removed, saying to Judah and to Jerusalem, \"You shall worship before", "Hezeki’ah", 22, ["hezekiah"]),
    mc(3, "Which word correctly completes this RSV wording: “rely on the LORD our God,\" is it not he whose high places and altars _____ has removed, saying to Judah and to Jerusalem, \"You shall worship before”", ["Hezeki’ah", "Elah", "Philistines", "Lachish"], 22),
    word(1, "In verse 22, what word completes this phrase: “rely on the LORD our God,\" is it not he whose high places and altars _____ has removed, saying to Judah and to Jerusalem, \"You shall worship before”?", "Hezeki’ah", 22, ["hezekiah"]),
    tf(2, "The RSV does not state: “But if you say to me, \"We rely on the LORD our God,\" is it not he whose high places and altars Hezeki’ah has removed, saying to Judah and to Jerusalem, \"You shall worship before this altar in Jerusalem\"?”", false, 22, "The quoted wording is the RSV text of this verse."),
    blank(3, "Come now, make a wager with my master the king of _____: I will give you two thousand horses, if you are able on your part to", "Assyria", 23, ["assyria"]),
    mc(1, "Which word correctly completes this RSV wording: “Come now, make a wager with my master the king of _____: I will give you two thousand horses, if you are able on your part to”", ["Assyria", "David", "Habor", "Hilki’ah"], 23),
    word(2, "In verse 23, what word completes this phrase: “Come now, make a wager with my master the king of _____: I will give you two thousand horses, if you are able on your part to”?", "Assyria", 23, ["assyria"]),
    tf(3, "The RSV states: “Come now, make a wager with my master the king of Assyria: I will give you two thousand horses, if you are able on your part to set riders upon them.”", true, 23),
    blank(1, "single captain among the least of my master’s servants, when you rely on _____ for chariots and for horsemen?", "Egypt", 24, ["egypt"]),
    mc(2, "Which word correctly completes this RSV wording: “single captain among the least of my master’s servants, when you rely on _____ for chariots and for horsemen?”", ["Egypt", "Eli’akim", "Pray", "Israel"], 24),
    word(3, "In verse 24, what word completes this phrase: “single captain among the least of my master’s servants, when you rely on _____ for chariots and for horsemen?”?", "Egypt", 24, ["egypt"]),
    tf(1, "The RSV does not state: “How then can you repulse a single captain among the least of my master’s servants, when you rely on Egypt for chariots and for horsemen?”", false, 24, "The quoted wording is the RSV text of this verse."),
    blank(2, "_____, is it without the LORD that I have come up against this place to destroy", "Moreover", 25, ["moreover"]),
    mc(3, "Which word correctly completes this RSV wording: “_____, is it without the LORD that I have come up against this place to destroy”", ["Moreover", "Medes", "Jo’ah", "Make"], 25),
    word(1, "In verse 25, what word completes this phrase: “_____, is it without the LORD that I have come up against this place to destroy”?", "Moreover", 25, ["moreover"]),
    tf(2, "The RSV states: “Moreover, is it without the LORD that I have come up against this place to destroy it? The LORD said to me, Go up against this land, and destroy it.’\"”", true, 25),
    blank(3, "Then Eli’akim the son of Hilki’ah, and Shebnah, and Jo’ah, said to the _____, \"Pray, speak to your servants in the Aramaic language, for we understand", "Rab’shakeh", 26, ["rabshakeh"]),
    mc(1, "Which word correctly completes this RSV wording: “Then Eli’akim the son of Hilki’ah, and Shebnah, and Jo’ah, said to the _____, \"Pray, speak to your servants in the Aramaic language, for we understand”", ["Rab’shakeh", "Rab’saris", "Moreover", "Jerusalem"], 26),
    word(2, "In verse 26, what word completes this phrase: “Then Eli’akim the son of Hilki’ah, and Shebnah, and Jo’ah, said to the _____, \"Pray, speak to your servants in the Aramaic language, for we understand”?", "Rab’shakeh", 26, ["rabshakeh"]),
    tf(3, "The RSV does not state: “ Then Eli’akim the son of Hilki’ah, and Shebnah, and Jo’ah, said to the Rab’shakeh, \"Pray, speak to your servants in the Aramaic language, for we understand it; do not speak to us in the language of Judah within the hearing of the people who are on the wall.\"”", false, 26, "The quoted wording is the RSV text of this verse."),
    blank(1, "But the _____ said to them, \"Has my master sent me to speak these words to your master", "Rab’shakeh", 27, ["rabshakeh"]),
    mc(2, "Which word correctly completes this RSV wording: “But the _____ said to them, \"Has my master sent me to speak these words to your master”", ["Rab’shakeh", "Asaph", "Hoshe’a", "Philistines"], 27),
    word(3, "In verse 27, what word completes this phrase: “But the _____ said to them, \"Has my master sent me to speak these words to your master”?", "Rab’shakeh", 27, ["rabshakeh"]),
    tf(1, "The RSV states: “But the Rab’shakeh said to them, \"Has my master sent me to speak these words to your master and to you, and not to the men sitting on the wall, who are doomed with you to eat their own dung and to drink their own urine?\"”", true, 27),
    blank(2, "Then the _____ stood and called out in a loud voice in the language of Judah: \"Hear the", "Rab’shakeh", 28, ["rabshakeh"]),
    mc(3, "Which word correctly completes this RSV wording: “Then the _____ stood and called out in a loud voice in the language of Judah: \"Hear the”", ["Rab’shakeh", "Arpad", "Ashe’rah", "Medes"], 28),
    word(1, "In verse 28, what word completes this phrase: “Then the _____ stood and called out in a loud voice in the language of Judah: \"Hear the”?", "Rab’shakeh", 28, ["rabshakeh"]),
    tf(2, "The RSV does not state: “Then the Rab’shakeh stood and called out in a loud voice in the language of Judah: \"Hear the word of the great king, the king of Assyria!”", false, 28, "The quoted wording is the RSV text of this verse."),
    blank(3, "Thus says the king: `Do not let _____ deceive you, for he will not be able to deliver you out of my hand.", "Hezeki’ah", 29, ["hezekiah"]),
    mc(1, "Which word correctly completes this RSV wording: “Thus says the king: `Do not let _____ deceive you, for he will not be able to deliver you out of my hand.”", ["Hezeki’ah", "Shebna", "Nehush’tan", "Medes"], 29),
    word(2, "In verse 29, what word completes this phrase: “Thus says the king: `Do not let _____ deceive you, for he will not be able to deliver you out of my hand.”?", "Hezeki’ah", 29, ["hezekiah"]),
    tf(3, "The RSV states: “Thus says the king: `Do not let Hezeki’ah deceive you, for he will not be able to deliver you out of my hand.”", true, 29),
    blank(1, "Do not let _____ make you to rely on the LORD by saying, The LORD will surely deliver us,", "Hezeki’ah", 30, ["hezekiah"]),
    mc(2, "Which word correctly completes this RSV wording: “Do not let _____ make you to rely on the LORD by saying, The LORD will surely deliver us,”", ["Hezeki’ah", "Zechari’ah", "Israelites", "Field"], 30),
    word(3, "In verse 30, what word completes this phrase: “Do not let _____ make you to rely on the LORD by saying, The LORD will surely deliver us,”?", "Hezeki’ah", 30, ["hezekiah"]),
    tf(1, "The RSV does not state: “Do not let Hezeki’ah make you to rely on the LORD by saying, The LORD will surely deliver us, and this city will not be given into the hand of the king of Assyria.’”", false, 30, "The quoted wording is the RSV text of this verse."),
    blank(2, "Do not listen to _____; for thus says the king of Assyria: `Make your peace with me and come", "Hezeki’ah", 31, ["hezekiah"]),
    mc(3, "Which word correctly completes this RSV wording: “Do not listen to _____; for thus says the king of Assyria: `Make your peace with me and come”", ["Hezeki’ah", "Gaza", "Tartan", "Behold"], 31),
    word(1, "In verse 31, what word completes this phrase: “Do not listen to _____; for thus says the king of Assyria: `Make your peace with me and come”?", "Hezeki’ah", 31, ["hezekiah"]),
    tf(2, "The RSV states: “Do not listen to Hezeki’ah; for thus says the king of Assyria: `Make your peace with me and come out to me; then every one of you will eat of his own vine, and every one of his own fig tree, and every one of you will drink the water of his own cistern;”", true, 31),
    blank(3, "trees and honey, that you may live, and not die. And do not listen to _____ when he misleads you by saying, The LORD will deliver us.", "Hezeki’ah", 32, ["hezekiah"]),
    mc(1, "Which word correctly completes this RSV wording: “trees and honey, that you may live, and not die. And do not listen to _____ when he misleads you by saying, The LORD will deliver us.”", ["Hezeki’ah", "Gozan", "Shebnah", "Aramaic"], 32),
    word(2, "In verse 32, what word completes this phrase: “trees and honey, that you may live, and not die. And do not listen to _____ when he misleads you by saying, The LORD will deliver us.”?", "Hezeki’ah", 32, ["hezekiah"]),
    tf(3, "The RSV does not state: “until I come and take you away to a land like your own land, a land of grain and wine, a land of bread and vineyards, a land of olive trees and honey, that you may live, and not die. And do not listen to Hezeki’ah when he misleads you by saying, The LORD will deliver us.”", false, 32, "The quoted wording is the RSV text of this verse."),
    blank(1, "of the nations ever delivered his land out of the hand of the king of _____?", "Assyria", 33, ["assyria"]),
    mc(2, "Which word correctly completes this RSV wording: “of the nations ever delivered his land out of the hand of the king of _____?”", ["Assyria", "Fuller’s", "Pharaoh", "Ivvah"], 33),
    word(3, "In verse 33, what word completes this phrase: “of the nations ever delivered his land out of the hand of the king of _____?”?", "Assyria", 33, ["assyria"]),
    tf(1, "The RSV states: “Has any of the gods of the nations ever delivered his land out of the hand of the king of Assyria?”", true, 33),
    blank(2, "Where are the gods of Hamath and Arpad? Where are the gods of _____, Hena, and Ivvah? Have they delivered Sama’ria out of my hand?", "Sepharva’im", 34, ["sepharvaim"]),
    mc(3, "Which word correctly completes this RSV wording: “Where are the gods of Hamath and Arpad? Where are the gods of _____, Hena, and Ivvah? Have they delivered Sama’ria out of my hand?”", ["Sepharva’im", "Pharaoh", "Nehush’tan", "Fuller’s"], 34),
    word(1, "In verse 34, what word completes this phrase: “Where are the gods of Hamath and Arpad? Where are the gods of _____, Hena, and Ivvah? Have they delivered Sama’ria out of my hand?”?", "Sepharva’im", 34, ["sepharvaim"]),
    tf(2, "The RSV does not state: “Where are the gods of Hamath and Arpad? Where are the gods of Sepharva’im, Hena, and Ivvah? Have they delivered Sama’ria out of my hand?”", false, 34, "The quoted wording is the RSV text of this verse."),
    blank(3, "delivered their countries out of my hand, that the LORD should deliver _____ out of my hand?’\"", "Jerusalem", 35, ["jerusalem"]),
    mc(1, "Which word correctly completes this RSV wording: “delivered their countries out of my hand, that the LORD should deliver _____ out of my hand?’\"”", ["Jerusalem", "Pray", "Elah", "Philistines"], 35),
    word(2, "In verse 35, what word completes this phrase: “delivered their countries out of my hand, that the LORD should deliver _____ out of my hand?’\"”?", "Jerusalem", 35, ["jerusalem"]),
    tf(3, "The RSV states: “Who among all the gods of the countries have delivered their countries out of my hand, that the LORD should deliver Jerusalem out of my hand?’\"”", true, 35),
    blank(1, "But the people were silent and _____ him not a word, for the king’s command was, \"Do not answer him.\"", "answered", 36, ["answered"]),
    mc(2, "Which word correctly completes this RSV wording: “But the people were silent and _____ him not a word, for the king’s command was, \"Do not answer him.\"”", ["answered", "depart", "serve", "took"], 36),
    word(3, "In verse 36, what word completes this phrase: “But the people were silent and _____ him not a word, for the king’s command was, \"Do not answer him.\"”?", "answered", 36, ["answered"]),
    tf(1, "The RSV does not state: “But the people were silent and answered him not a word, for the king’s command was, \"Do not answer him.\"”", false, 36, "The quoted wording is the RSV text of this verse."),
    blank(2, "came to Hezeki’ah with their clothes rent, and told him the words of the _____.", "Rab’shakeh", 37, ["rabshakeh"]),
    mc(3, "Which word correctly completes this RSV wording: “came to Hezeki’ah with their clothes rent, and told him the words of the _____.”", ["Rab’shakeh", "Sennach’erib", "Behold", "Israel"], 37),
    word(1, "In verse 37, what word completes this phrase: “came to Hezeki’ah with their clothes rent, and told him the words of the _____.”?", "Rab’shakeh", 37, ["rabshakeh"]),
    tf(2, "The RSV states: “Then Eli’akim the son of Hilki’ah, who was over the household, and Shebna the secretary, and Jo’ah the son of Asaph, the recorder, came to Hezeki’ah with their clothes rent, and told him the words of the Rab’shakeh.”", true, 37),
    mc(2, "Why did Hezekiah break Moses’ bronze serpent, and what was it called?", ["Israel had burned incense to it; it was called Nehushtan", "It had become damaged; it was called Cherubim", "Assyria demanded it; it was called Ephod", "It belonged to the high places; it was called Asherah"], 4),
    mc(1, "How does the text rank Hezekiah’s trust among Judah’s kings?", ["There was none like him after him or before him", "Only David trusted more", "He equaled Solomon", "He was faithful only in his early reign"], 5),
    mc(3, "What image did the Rabshakeh use for trusting Egypt?", ["A broken reed that pierces the hand of anyone leaning on it", "A cracked cistern that holds no water", "A fading flower in the field", "A broken bow in battle"], 21),
    mc(3, "Why did Judah’s officials ask for Aramaic, and how did the Rabshakeh respond?", ["They did not want the wall’s people to understand; he called out louder in Judah’s language", "They could not understand Assyrian; he summoned an interpreter", "They wanted secrecy from Hezekiah; he wrote a letter", "They wished to negotiate privately; he left Jerusalem"], 28),
  ],
};

export default bank;
