// 2 Kings 11 — quiz bank (RSV). Four verse-anchored forms per verse.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: "2 Kings",
  chapter: 11,
  tag: "quiz-v2-2kings-11",
  rows: [
    blank(2, "Now when _____ the mother of Ahazi’ah saw that her son was dead, she arose and destroyed", "Athali’ah", 1, ["athaliah"]),
    mc(3, "Which word correctly completes this RSV wording: “Now when _____ the mother of Ahazi’ah saw that her son was dead, she arose and destroyed”", ["Athali’ah", "Carites", "King", "Ba’al"], 1),
    word(1, "In verse 1, what word completes this phrase: “Now when _____ the mother of Ahazi’ah saw that her son was dead, she arose and destroyed”?", "Athali’ah", 1, ["athaliah"]),
    tf(2, "The RSV states: “Now when Athali’ah the mother of Ahazi’ah saw that her son was dead, she arose and destroyed all the royal family.”", true, 1),
    blank(3, "But _____, the daughter of King Joram, sister of Ahazi’ah, took Jo’ash the son of", "Jehosh’eba", 2, ["jehosheba"]),
    mc(1, "Which word correctly completes this RSV wording: “But _____, the daughter of King Joram, sister of Ahazi’ah, took Jo’ash the son of”", ["Jehosh’eba", "Ahazi’ah", "Jeho’ash", "Ba’al"], 2),
    word(2, "In verse 2, what word completes this phrase: “But _____, the daughter of King Joram, sister of Ahazi’ah, took Jo’ash the son of”?", "Jehosh’eba", 2, ["jehosheba"]),
    tf(3, "The RSV does not state: “But Jehosh’eba, the daughter of King Joram, sister of Ahazi’ah, took Jo’ash the son of Ahazi’ah, and stole him away from among the king’s sons who were about to be slain, and she put him and his nurse in a bedchamber. Thus she hid him from Athali’ah, so that he was not slain;”", false, 2, "The quoted wording is the RSV text of this verse."),
    blank(1, "and he remained with her six years, hid in the house of the LORD, while _____ reigned over the land.", "Athali’ah", 3, ["athaliah"]),
    mc(2, "Which word correctly completes this RSV wording: “and he remained with her six years, hid in the house of the LORD, while _____ reigned over the land.”", ["Athali’ah", "Thus", "Ahazi’ah", "Bring"], 3),
    word(3, "In verse 3, what word completes this phrase: “and he remained with her six years, hid in the house of the LORD, while _____ reigned over the land.”?", "Athali’ah", 3, ["athaliah"]),
    tf(1, "The RSV states: “and he remained with her six years, hid in the house of the LORD, while Athali’ah reigned over the land.”", true, 3),
    blank(2, "But in the seventh year _____ sent and brought the captains of the Carites and of the guards, and had", "Jehoi’ada", 4, ["jehoiada"]),
    mc(3, "Which word correctly completes this RSV wording: “But in the seventh year _____ sent and brought the captains of the Carites and of the guards, and had”", ["Jehoi’ada", "LORD’s", "Carites", "Jehosh’eba"], 4),
    word(1, "In verse 4, what word completes this phrase: “But in the seventh year _____ sent and brought the captains of the Carites and of the guards, and had”?", "Jehoi’ada", 4, ["jehoiada"]),
    tf(2, "The RSV does not state: “But in the seventh year Jehoi’ada sent and brought the captains of the Carites and of the guards, and had them come to him in the house of the LORD; and he made a covenant with them and put them under oath in the house of the LORD, and he showed them the king’s son.”", false, 4, "The quoted wording is the RSV text of this verse."),
    blank(3, "And he _____ them, \"This is the thing that you shall do: one third of you, those who", "commanded", 5, ["commanded"]),
    mc(1, "Which word correctly completes this RSV wording: “And he _____ them, \"This is the thing that you shall do: one third of you, those who”", ["commanded", "showed", "divisions", "comes"], 5),
    word(2, "In verse 5, what word completes this phrase: “And he _____ them, \"This is the thing that you shall do: one third of you, those who”?", "commanded", 5, ["commanded"]),
    tf(3, "The RSV states: “And he commanded them, \"This is the thing that you shall do: one third of you, those who come off duty on the sabbath and guard the king’s house”", true, 5),
    blank(1, "(_____ third being at the gate Sur and a third at the gate behind the guards),", "another", 6, ["another"]),
    mc(2, "Which word correctly completes this RSV wording: “(_____ third being at the gate Sur and a third at the gate behind the guards),”", ["another", "guard", "whoever", "stood"], 6),
    word(3, "In verse 6, what word completes this phrase: “(_____ third being at the gate Sur and a third at the gate behind the guards),”?", "another", 6, ["another"]),
    tf(1, "The RSV does not state: “(another third being at the gate Sur and a third at the gate behind the guards), shall guard the palace;”", false, 6, "The quoted wording is the RSV text of this verse."),
    blank(2, "and the two _____ of you, which come on duty in force on the sabbath and guard the house", "divisions", 7, ["divisions"]),
    mc(3, "Which word correctly completes this RSV wording: “and the two _____ of you, which come on duty in force on the sabbath and guard the house”", ["divisions", "king", "came", "crown"], 7),
    word(1, "In verse 7, what word completes this phrase: “and the two _____ of you, which come on duty in force on the sabbath and guard the house”?", "divisions", 7, ["divisions"]),
    tf(2, "The RSV states: “and the two divisions of you, which come on duty in force on the sabbath and guard the house of the LORD,”", true, 7),
    blank(3, "shall surround the king, each with his weapons in his hand; and whoever _____ the ranks is to be slain. Be with the king when he goes out and when he", "approaches", 8, ["approaches"]),
    mc(1, "Which word correctly completes this RSV wording: “shall surround the king, each with his weapons in his hand; and whoever _____ the ranks is to be slain. Be with the king when he goes out and when he”", ["approaches", "clapped", "rejoicing", "altars"], 8),
    word(2, "In verse 8, what word completes this phrase: “shall surround the king, each with his weapons in his hand; and whoever _____ the ranks is to be slain. Be with the king when he goes out and when he”?", "approaches", 8, ["approaches"]),
    tf(3, "The RSV does not state: “shall surround the king, each with his weapons in his hand; and whoever approaches the ranks is to be slain. Be with the king when he goes out and when he comes in.\"”", false, 8, "The quoted wording is the RSV text of this verse."),
    blank(1, "The captains did according to all that _____ the priest commanded, and each brought his men who were to go off duty", "Jehoi’ada", 9, ["jehoiada"]),
    mc(2, "Which word correctly completes this RSV wording: “The captains did according to all that _____ the priest commanded, and each brought his men who were to go off duty”", ["Jehoi’ada", "Jeho’ash", "Treason", "Jo’ash"], 9),
    word(3, "In verse 9, what word completes this phrase: “The captains did according to all that _____ the priest commanded, and each brought his men who were to go off duty”?", "Jehoi’ada", 9, ["jehoiada"]),
    tf(1, "The RSV states: “The captains did according to all that Jehoi’ada the priest commanded, and each brought his men who were to go off duty on the sabbath, with those who were to come on duty on the sabbath, and came to Jehoi’ada the priest.”", true, 9),
    blank(2, "priest delivered to the captains the spears and shields that had been King _____, which were in the house of the LORD;", "David’s", 10, ["davids"]),
    mc(3, "Which word correctly completes this RSV wording: “priest delivered to the captains the spears and shields that had been King _____, which were in the house of the LORD;”", ["David’s", "Thus", "Ahazi’ah", "LORD’s"], 10),
    word(1, "In verse 10, what word completes this phrase: “priest delivered to the captains the spears and shields that had been King _____, which were in the house of the LORD;”?", "David’s", 10, ["davids"]),
    tf(2, "The RSV does not state: “And the priest delivered to the captains the spears and shields that had been King David’s, which were in the house of the LORD;”", false, 10, "The quoted wording is the RSV text of this verse."),
    blank(3, "and the guards stood, every man with his _____ in his hand, from the south side of the house to the north side of the", "weapons", 11, ["weapons"]),
    mc(1, "Which word correctly completes this RSV wording: “and the guards stood, every man with his _____ in his hand, from the south side of the house to the north side of the”", ["weapons", "hands", "trumpeters", "sword"], 11),
    word(2, "In verse 11, what word completes this phrase: “and the guards stood, every man with his _____ in his hand, from the south side of the house to the north side of the”?", "weapons", 11, ["weapons"]),
    tf(3, "The RSV states: “and the guards stood, every man with his weapons in his hand, from the south side of the house to the north side of the house, around the altar and the house.”", true, 11),
    blank(1, "him king, and anointed him; and they clapped their hands, and said, \"_____ live the king!\"", "Long", 12, ["long"]),
    mc(2, "Which word correctly completes this RSV wording: “him king, and anointed him; and they clapped their hands, and said, \"_____ live the king!\"”", ["Long", "Treason", "Thus", "Ahazi’ah"], 12),
    word(3, "In verse 12, what word completes this phrase: “him king, and anointed him; and they clapped their hands, and said, \"_____ live the king!\"”?", "Long", 12, ["long"]),
    tf(1, "The RSV does not state: “Then he brought out the king’s son, and put the crown upon him, and gave him the testimony; and they proclaimed him king, and anointed him; and they clapped their hands, and said, \"Long live the king!\"”", false, 12, "The quoted wording is the RSV text of this verse."),
    blank(2, "When _____ heard the noise of the guard and of the people, she went into the house", "Athali’ah", 13, ["athaliah"]),
    mc(3, "Which word correctly completes this RSV wording: “When _____ heard the noise of the guard and of the people, she went into the house”", ["Athali’ah", "Bring", "Jehoi’ada", "Jehosh’eba"], 13),
    word(1, "In verse 13, what word completes this phrase: “When _____ heard the noise of the guard and of the people, she went into the house”?", "Athali’ah", 13, ["athaliah"]),
    tf(2, "The RSV states: “When Athali’ah heard the noise of the guard and of the people, she went into the house of the LORD to the people;”", true, 13),
    blank(3, "king, and all the people of the land rejoicing and blowing trumpets. And _____ rent her clothes, and cried, \"Treason! Treason!\"", "Athali’ah", 14, ["athaliah"]),
    mc(1, "Which word correctly completes this RSV wording: “king, and all the people of the land rejoicing and blowing trumpets. And _____ rent her clothes, and cried, \"Treason! Treason!\"”", ["Athali’ah", "King", "Ba’al", "David’s"], 14),
    word(2, "In verse 14, what word completes this phrase: “king, and all the people of the land rejoicing and blowing trumpets. And _____ rent her clothes, and cried, \"Treason! Treason!\"”?", "Athali’ah", 14, ["athaliah"]),
    tf(3, "The RSV does not state: “and when she looked, there was the king standing by the pillar, according to the custom, and the captains and the trumpeters beside the king, and all the people of the land rejoicing and blowing trumpets. And Athali’ah rent her clothes, and cried, \"Treason! Treason!\"”", false, 14, "The quoted wording is the RSV text of this verse."),
    blank(1, "Then _____ the priest commanded the captains who were set over the army, \"Bring her", "Jehoi’ada", 15, ["jehoiada"]),
    mc(2, "Which word correctly completes this RSV wording: “Then _____ the priest commanded the captains who were set over the army, \"Bring her”", ["Jehoi’ada", "Long", "Joram", "Jeho’ash"], 15),
    word(3, "In verse 15, what word completes this phrase: “Then _____ the priest commanded the captains who were set over the army, \"Bring her”?", "Jehoi’ada", 15, ["jehoiada"]),
    tf(1, "The RSV states: “Then Jehoi’ada the priest commanded the captains who were set over the army, \"Bring her out between the ranks; and slay with the sword any one who follows her.\" For the priest said, \"Let her not be slain in the house of the LORD.\"”", true, 15),
    blank(2, "So they laid hands on her; and she went through the horses’ _____ to the king’s house, and there she was slain.", "entrance", 16, ["entrance"]),
    mc(3, "Which word correctly completes this RSV wording: “So they laid hands on her; and she went through the horses’ _____ to the king’s house, and there she was slain.”", ["entrance", "slew", "after", "sister"], 16),
    word(1, "In verse 16, what word completes this phrase: “So they laid hands on her; and she went through the horses’ _____ to the king’s house, and there she was slain.”?", "entrance", 16, ["entrance"]),
    tf(2, "The RSV does not state: “So they laid hands on her; and she went through the horses’ entrance to the king’s house, and there she was slain.”", false, 16, "The quoted wording is the RSV text of this verse."),
    blank(3, "And _____ made a covenant between the LORD and the king and people, that they should", "Jehoi’ada", 17, ["jehoiada"]),
    mc(1, "Which word correctly completes this RSV wording: “And _____ made a covenant between the LORD and the king and people, that they should”", ["Jehoi’ada", "Carites", "Jehosh’eba", "Ba’al"], 17),
    word(2, "In verse 17, what word completes this phrase: “And _____ made a covenant between the LORD and the king and people, that they should”?", "Jehoi’ada", 17, ["jehoiada"]),
    tf(3, "The RSV states: “And Jehoi’ada made a covenant between the LORD and the king and people, that they should be the LORD’s people; and also between the king and the people.”", true, 17),
    blank(1, "it down; his altars and his images they broke in pieces, and they slew _____ the priest of Ba’al before the altars. And the priest posted watchmen", "Mattan", 18, ["mattan"]),
    mc(2, "Which word correctly completes this RSV wording: “it down; his altars and his images they broke in pieces, and they slew _____ the priest of Ba’al before the altars. And the priest posted watchmen”", ["Mattan", "Ba’al", "David’s", "Joram"], 18),
    word(3, "In verse 18, what word completes this phrase: “it down; his altars and his images they broke in pieces, and they slew _____ the priest of Ba’al before the altars. And the priest posted watchmen”?", "Mattan", 18, ["mattan"]),
    tf(1, "The RSV does not state: “Then all the people of the land went to the house of Ba’al, and tore it down; his altars and his images they broke in pieces, and they slew Mattan the priest of Ba’al before the altars. And the priest posted watchmen over the house of the LORD.”", false, 18, "The quoted wording is the RSV text of this verse."),
    blank(2, "And he took the captains, the _____, the guards, and all the people of the land; and they brought the king", "Carites", 19, ["carites"]),
    mc(3, "Which word correctly completes this RSV wording: “And he took the captains, the _____, the guards, and all the people of the land; and they brought the king”", ["Carites", "Jo’ash", "Athali’ah", "Bring"], 19),
    word(1, "In verse 19, what word completes this phrase: “And he took the captains, the _____, the guards, and all the people of the land; and they brought the king”?", "Carites", 19, ["carites"]),
    tf(2, "The RSV states: “And he took the captains, the Carites, the guards, and all the people of the land; and they brought the king down from the house of the LORD, marching through the gate of the guards to the king’s house. And he took his seat on the throne of the kings.”", true, 19),
    blank(3, "So all the people of the land rejoiced; and the city was quiet after _____ had been slain with the sword at the king’s house.", "Athali’ah", 20, ["athaliah"]),
    mc(1, "Which word correctly completes this RSV wording: “So all the people of the land rejoiced; and the city was quiet after _____ had been slain with the sword at the king’s house.”", ["Athali’ah", "LORD’s", "Carites", "King"], 20),
    word(2, "In verse 20, what word completes this phrase: “So all the people of the land rejoiced; and the city was quiet after _____ had been slain with the sword at the king’s house.”?", "Athali’ah", 20, ["athaliah"]),
    tf(3, "The RSV does not state: “So all the people of the land rejoiced; and the city was quiet after Athali’ah had been slain with the sword at the king’s house.”", false, 20, "The quoted wording is the RSV text of this verse."),
    blank(1, "_____ was seven years old when he began to reign.", "Jeho’ash", 21, ["jehoash"]),
    mc(2, "Which word correctly completes this RSV wording: “_____ was seven years old when he began to reign.”", ["Jeho’ash", "King", "Ba’al", "David’s"], 21),
    word(3, "In verse 21, what word completes this phrase: “_____ was seven years old when he began to reign.”?", "Jeho’ash", 21, ["jehoash"]),
    tf(1, "The RSV states: “Jeho’ash was seven years old when he began to reign.”", true, 21),
    blank(1, "Athali’ah the mother of Ahazi’ah saw that her son was dead, she arose and _____ all the royal family.", "destroyed", 1, ["destroyed"]),
    mc(2, "Select the missing RSV word: “king’s sons who were about to be slain, and she put him and his nurse in a _____. Thus she hid him from Athali’ah, so that he was not slain;”", ["bedchamber", "sabbath", "ranks", "around"], 2),
    word(3, "What missing word belongs in this verse 3 clause: “and he _____ with her six years, hid in the house of the LORD, while Athali’ah reigned”?", "remained", 3, ["remained"]),
    tf(1, "This wording appears in verse 4: “But in the seventh year Jehoi’ada sent and brought the captains of the Carites and of the guards, and had them come to him in the house”", true, 4),
    blank(2, "thing that you shall do: one third of you, those who come off duty on the _____ and guard the king’s house", "sabbath", 5, ["sabbath"]),
    mc(3, "Select the missing RSV word: “(another third being at the gate Sur and a third at the gate _____ the guards), shall guard the palace;”", ["behind", "looked", "cried", "tore"], 6),
    word(1, "What missing word belongs in this verse 7 clause: “and the two divisions of you, which come on duty in force on the _____ and guard the house of the LORD,”?", "sabbath", 7, ["sabbath"]),
    tf(2, "This wording appears in verse 8: “shall surround the king, each with his weapons in his hand; and whoever approaches the”", true, 8),
    blank(3, "The captains did _____ to all that Jehoi’ada the priest commanded, and each brought his men who", "according", 9, ["according"]),
    mc(1, "Select the missing RSV word: “And the priest _____ to the captains the spears and shields that had been King David’s, which”", ["delivered", "sons", "seventh", "showed"], 10),
    word(2, "What missing word belongs in this verse 11 clause: “and the _____ stood, every man with his weapons in his hand, from the south side of”?", "guards", 11, ["guards"]),
    tf(3, "This wording appears in verse 12: “son, and put the crown upon him, and gave him the testimony; and they proclaimed him king, and anointed him; and they clapped their hands, and said, \"Long”", true, 12),
    blank(1, "When Athali’ah heard the noise of the guard and of the _____, she went into the house of the LORD to the people;", "people", 13, ["people"]),
    mc(2, "Select the missing RSV word: “standing by the pillar, according to the custom, and the captains and the _____ beside the king, and all the people of the land rejoicing and blowing”", ["trumpeters", "among", "brought", "guard"], 14),
    word(3, "What missing word belongs in this verse 15 clause: “Then Jehoi’ada the priest _____ the captains who were set over the army, \"Bring her out between the ranks;”?", "commanded", 15, ["commanded"]),
    tf(1, "This wording appears in verse 16: “So they laid hands on her; and she went through the horses’ entrance to the king’s house, and there she was slain.”", true, 16),
    blank(2, "And Jehoi’ada made a _____ between the LORD and the king and people, that they should be the LORD’s", "covenant", 17, ["covenant"]),
    mc(3, "Select the missing RSV word: “slew Mattan the priest of Ba’al before the altars. And the priest posted _____ over the house of the LORD.”", ["watchmen", "began", "stole", "house"], 18),
    word(1, "What missing word belongs in this verse 19 clause: “And he took the _____, the Carites, the guards, and all the people of the land; and they brought”?", "captains", 19, ["captains"]),
    tf(2, "This wording appears in verse 20: “So all the people of the land rejoiced; and the city was quiet after Athali’ah had been slain with the sword”", true, 20),
    blank(3, "Jeho’ash was _____ years old when he began to reign.", "seven", 21, ["seven"]),
    mc(1, "Select the missing RSV word: “Now when Athali’ah the mother of _____ saw that her son was dead, she arose and destroyed all the royal family.”", ["Ahazi’ah", "Jehosh’eba", "LORD’s", "Carites"], 1),
    word(2, "What missing word belongs in this verse 2 clause: “and she put him and his nurse in a bedchamber. Thus she hid him from _____, so that he was not slain;”?", "Athali’ah", 2, ["athaliah"]),
    tf(3, "This wording appears in verse 3: “remained with her six years, hid in the house of the LORD, while Athali’ah reigned over the land.”", true, 3),
    blank(1, "guards, and had them come to him in the house of the LORD; and he made a _____ with them and put them under oath in the house of the LORD, and he showed", "covenant", 4, ["covenant"]),
    mc(2, "Select the missing RSV word: “one third of you, those who come off duty on the sabbath and guard the _____ house”", ["king’s", "blowing", "horses’", "before"], 5),
    word(3, "What missing word belongs in this verse 6 clause: “(another third being at the gate Sur and a third at the gate behind the _____), shall guard the palace;”?", "guards", 6, ["guards"]),
    tf(1, "This wording appears in verse 7: “and the two divisions of you, which come on duty in force on the sabbath and guard the house of the LORD,”", true, 7),
    blank(2, "shall surround the king, each with his _____ in his hand; and whoever approaches the ranks is to be slain. Be with", "weapons", 8, ["weapons"]),
    mc(3, "Select the missing RSV word: “The captains did according to all that Jehoi’ada the priest _____, and each brought his men who were to go off duty on the sabbath, with”", ["commanded", "years", "come", "guard"], 9),
    word(1, "What missing word belongs in this verse 10 clause: “And the priest delivered to the _____ the spears and shields that had been King David’s, which were in the house”?", "captains", 10, ["captains"]),
    tf(2, "This wording appears in verse 11: “hand, from the south side of the house to the north side of the house, around the altar and the house.”", true, 11),
    blank(3, "brought out the king’s son, and put the crown upon him, and gave him the _____; and they proclaimed him king, and anointed him; and they clapped their", "testimony", 12, ["testimony"]),
    mc(1, "Select the missing RSV word: “When Athali’ah _____ the noise of the guard and of the people, she went into the house of the”", ["heard", "proclaimed", "pillar", "between"], 13),
    word(2, "What missing word belongs in this verse 14 clause: “and when she looked, there was the king standing by the pillar, _____ to the custom, and the captains and the trumpeters beside the king, and”?", "according", 14, ["according"]),
    tf(3, "This wording appears in verse 15: “Then Jehoi’ada the priest commanded the captains who were set over the army, \"Bring her out between the ranks; and slay”", true, 15),
    mc(2, "Who rescued the infant Joash when Athaliah destroyed the royal family, and how?", ["Jehosheba stole him away with his nurse and hid him in a bedchamber", "Jehoiada carried him to Judah", "The palace guard hid him outside Jerusalem", "His mother took him to Egypt"], 2),
    mc(1, "Where and for how long was Joash hidden while Athaliah reigned?", ["In the house of the LORD for six years", "In the palace for seven years", "In Samaria for six months", "In a cave for three years"], 3),
    mc(1, "What did Athaliah cry when she saw the newly crowned king?", ["Treason! Treason!", "Long live the king!", "The sword of the LORD!", "Conspiracy! Conspiracy!"], 14),
    mc(3, "How old was Jehoash when he began to reign?", ["Seven years old", "Six years old", "Twelve years old", "Twenty years old"], 21),
  ],
};

export default bank;
