import { mc, blank, word, tf, type ChapterBank, sa } from './types'

const bank: ChapterBank = {
  book: '2 Kings', chapter: 11, tag: 'quiz-v2-2kings-11', rows: [
    mc(1, 'What did Athaliah do after seeing that Ahaziah was dead?', ['Tried to destroy the entire royal family', 'Fled to Samaria', 'Crowned Joash', 'Made a covenant with Jehoiada'], 1),
    blank(1, 'she arose and destroyed all the royal _____.', 'family', 1),
    word(3, 'Whose mother was Athaliah?', 'Ahaziah’s', 1, ['Ahaziah']),
    tf(2, 'Athaliah protected the royal heirs after her son died.', false, 1, 'After Ahaziah died, Athaliah sought to destroy the entire royal family.'),
    mc(2, 'What threat opened the chapter?', ['Athaliah tried to eliminate the royal heirs', 'Syria’s army began besieging Jerusalem', 'Baal’s priests took control of the temple', 'The palace guards abandoned their stations'], 1),
    word(2, 'Who initiated the attack on the royal house?', 'Athaliah', 1, ["Athali'ah"]),

    mc(1, 'Who rescued Joash?', ['Jehosheba, Ahaziah’s sister', 'Athaliah', 'Jehoiada alone', 'The queen mother’s sons'], 2),
    blank(3, 'and she put him and his nurse in a _____.', 'bedchamber', 2),
    word(2, 'Whose son was Joash?', 'Ahaziah’s', 2, ['Ahaziah']),
    tf(1, 'Joash’s nurse was hidden with him.', true, 2),
    mc(2, 'How did Jehosheba save the child?', ['She removed and hid him with his nurse', 'She secretly transported him into Samaria', 'She persuaded Athaliah to spare his life', 'She placed him among the armed palace guards'], 2),
    sa(1, 'How was Jehosheba related to King Joram?', 'his daughter', 2, ['daughter of Joram']),
    mc(3, 'Who preserved the royal heir, and by what immediate action?', ['Jehosheba hid Joash and his nurse in a bedchamber', 'Jehoiada crowned him publicly at once', 'Athaliah sent him to Judah', 'The guards placed him on the throne'], 2),

    mc(1, 'Where was Joash hidden?', ['In the house of the LORD', 'In the king’s palace', 'In Samaria', 'At Beth-eked'], 3),
    blank(2, 'and he remained with her _____ years', 'six', 3, ['6']),
    word(1, 'Who ruled while Joash was hidden?', 'Athaliah', 3, ["Athali'ah"]),
    tf(3, 'Joash lived openly in the palace during Athaliah’s six-year reign.', false, 3, 'He remained hidden with Jehosheba in the house of the LORD.'),
    mc(2, 'How did the hidden child survive Athaliah’s rule?', ['He stayed concealed inside the LORD’s house', 'He lived openly within the royal palace', 'He escaped across the border into Syria', 'He was raised in secret by Ahab’s sons'], 3),
    sa(2, 'How long did Athaliah rule before the seventh-year action?', 'six years', 3, ['six', '6 years']),
    mc(3, 'What protected Joash during Athaliah’s reign?', ['Concealment in the temple for six years', 'A treaty with Syria', 'A guard at Ramoth-gilead', 'Exile in Philistia'], 3),

    mc(1, 'Whom did Jehoiada bring into the temple in the seventh year?', ['Captains of the Carites and guards', 'The assembled priests serving Baal', 'The remaining descendants of Ahab', 'The senior commanders of Syria’s army'], 4),
    blank(3, 'and he made a _____ with them', 'covenant', 4),
    sa(2, 'Whom did Jehoiada show to the captains?', 'the king’s son', 4, ['Joash']),
    tf(1, 'Jehoiada placed the officers under oath in the LORD’s house.', true, 4),
    mc(2, 'What did Jehoiada establish before revealing Joash?', ['A sworn covenant with the captains', 'A public election', 'A treaty with Athaliah', 'A sacrifice to Baal'], 4),
    sa(1, 'In which year did Jehoiada act?', 'the seventh year', 4, ['seventh', '7th year']),

    mc(1, 'What fraction of the incoming Sabbath force guarded the king’s house?', ['One third', 'One half', 'Two thirds', 'All of it'], 5),
    blank(2, 'one _____ of you', 'third', 5),
    sa(1, 'When did this group come off duty?', 'on the sabbath', 5, ['Sabbath']),
    tf(3, 'Jehoiada assigned the entire Sabbath force to the royal house.', false, 5, 'One third of the force was assigned to guard the king’s house.'),
    mc(2, 'What was the first part of Jehoiada’s security plan?', ['One third would guard the king’s house', 'Every guard would enter the LORD’s house', 'No armed guard would remain with the king', 'The Carites would depart from Jerusalem'], 5),
    sa(2, 'What building did the first third guard?', 'the king’s house', 5, ['palace']),

    mc(1, 'Where were the other thirds posted?', ['At Gate Sur and the gate behind the guards', 'At the altar and north wall', 'At the horses’ entrance and palace', 'At Samaria and Jezreel'], 6),
    blank(3, 'a third at the gate behind the _____.', 'guards', 6),
    sa(2, 'What were these divisions to guard?', 'the palace', 6),
    tf(1, 'The three detachments formed a distributed palace guard.', true, 6),
    mc(2, 'Which named gate received one third?', ['Gate Sur', 'Gate of the Guards', 'Horses’ Entrance', 'Jezreel Gate'], 6),
    word(1, 'How many additional thirds are described?', 'two', 6, ['2']),

    mc(1, 'What were the two Sabbath divisions to guard?', ['The house of the LORD', 'Athaliah’s palace', 'The city gates', 'The road to Samaria'], 7),
    blank(2, 'which come on duty in _____ on the sabbath', 'force', 7),
    word(1, 'How many divisions guarded the temple?', 'two', 7, ['2']),
    tf(3, 'The incoming Sabbath divisions were assigned to escort Athaliah.', false, 7, 'The two divisions were to guard the house of the LORD around the king.'),
    mc(2, 'Why were these divisions essential?', ['They protected the temple and royal heir', 'They escorted Athaliah through Jerusalem', 'They guarded the images inside Baal’s house', 'They formed an army to march against Syria'], 7),
    sa(2, 'On what day did the guard rotation occur?', 'the sabbath', 7, ['Sabbath']),

    mc(1, 'How were the guards to protect the king?', ['Surround him with weapons ready', 'Hide him alone', 'Escort him out of Jerusalem', 'Place him behind Athaliah'], 8),
    blank(3, 'whoever approaches the ranks is to be _____.', 'slain', 8),
    sa(2, 'When were the guards to stay with the king?', 'when he went out and came in', 8, ['going out and coming in']),
    tf(1, 'Each guard was to keep his weapon in hand.', true, 8),
    mc(2, 'What penalty protected the guarded ranks?', ['Anyone approaching them was to be killed', 'The intruder would be exiled', 'The guards would sound a trumpet', 'The palace would be closed'], 8),
    sa(1, 'Whom did the armed ranks surround?', 'the king', 8, ['Joash']),

    mc(1, 'How did the captains respond to Jehoiada’s plan?', ['They carried it out fully', 'They refused the oath', 'They warned Athaliah', 'They left the temple'], 9),
    blank(2, 'each brought his _____', 'men', 9),
    sa(1, 'Who assembled both outgoing and incoming Sabbath guards?', 'the captains', 9),
    tf(3, 'The captains brought only the incoming Sabbath guard to Jehoiada.', false, 9, 'Each captain brought both those coming on duty and those going off duty.'),
    mc(2, 'What demonstrated disciplined obedience?', ['Each captain brought both Sabbath groups', 'The assembled guards crowned Queen Athaliah', 'The men discarded their weapons before entering', 'The captains postponed Jehoiada’s plan'], 9),
    sa(2, 'To whom did the forces report?', 'Jehoiada the priest', 9, ['Jehoiada']),

    mc(1, 'What weapons did Jehoiada distribute?', ['David’s spears and shields', 'Jehu’s bows', 'Syrian swords', 'Ahab’s chariots'], 10),
    blank(3, 'the spears and _____ that had been King David’s', 'shields', 10),
    sa(2, 'Where had the weapons been kept?', 'in the house of the LORD', 10, ['the temple']),
    tf(1, 'The weapons connected the new king’s defense with David.', true, 10),
    mc(2, 'Who received David’s stored weapons?', ['The captains', 'Athaliah', 'Baal’s priests', 'The people outside'], 10),
    word(1, 'Whose weapons were they?', 'David’s', 10, ['David', 'King David’s']),

    mc(1, 'Where did the armed guards stand?', ['Across the temple, surrounding king and altar', 'Only at the entrance to the royal palace', 'Outside the defensive wall of Jerusalem', 'Inside the sanctuary belonging to Baal'], 11),
    blank(2, 'every man with his _____ in his hand', 'weapons', 11),
    sa(1, 'What two sacred features did they surround?', 'the altar and the house', 11, ['altar and temple']),
    tf(3, 'The armed guards stood only outside Jerusalem’s city wall.', false, 11, 'They stood from the south side to the north side of the temple, around the altar and the king.'),
    mc(2, 'What physical arrangement secured the coronation?', ['Armed guards surrounded the king and altar', 'The young king was secretly moved to Samaria', 'Every gate in Jerusalem was locked shut', 'Athaliah’s army formed a ring around the altar'], 11),
    sa(2, 'Which directions mark the guard line?', 'south to north', 11, ['south side to north side']),

    mc(1, 'What did Jehoiada place on Joash?', ['The crown', 'A priestly robe', 'David’s shield', 'Sackcloth'], 12),
    blank(3, 'and gave him the _____.', 'testimony', 12),
    sa(2, 'What did the people shout?', 'Long live the king!', 12, ['Long live the king']),
    tf(1, 'Joash was crowned, given the testimony, and anointed.', true, 12),
    mc(2, 'How did the assembly celebrate the new king?', ['They clapped and cried, “Long live the king!”', 'They tore their garments in grief and protest', 'They fled from the temple into the city', 'They bowed before the images of Baal'], 12),
    word(1, 'Who brought out the king’s son?', 'Jehoiada', 12, ['the priest']),

    mc(1, 'What drew Athaliah to the temple?', ['The noise of the guard and people', 'A message from Jehoiada', 'The destruction of Baal’s house', 'The sound of battle'], 13),
    blank(2, 'she went into the house of the LORD to the _____.', 'people', 13),
    word(1, 'Who heard the coronation noise?', 'Athaliah', 13, ["Athali'ah"]),
    tf(3, 'Athaliah remained in the palace after hearing the coronation noise.', false, 13, 'She went into the house of the LORD to the people.'),
    mc(2, 'Which sounds alerted the queen?', ['The guard and gathered people', 'Syrian chariots', 'A single messenger', 'The demolition of the altar'], 13),
    sa(2, 'Where did Athaliah go?', 'the house of the LORD', 13, ['the temple']),

    mc(1, 'Where was the crowned king standing?', ['By the pillar according to custom', 'On Baal’s altar', 'At the horses’ entrance', 'Inside a bedchamber'], 14),
    blank(3, 'and cried, “Treason! _____!”', 'Treason', 14),
    sa(2, 'What did Athaliah do to her clothes?', 'tore them', 14, ['rent her clothes']),
    tf(1, 'Captains and trumpeters stood beside the king.', true, 14),
    mc(2, 'What scene confronted Athaliah?', ['The king amid rejoicing people and trumpeters', 'The temple standing completely empty', 'Jehoiada fleeing from the building alone', 'Baal’s priests guarding the royal throne'], 14),
    word(1, 'How many times did Athaliah cry “Treason”?', 'twice', 14, ['two', '2']),
    mc(3, 'What was Athaliah’s immediate response to the coronation?', ['She tore her clothes and cried “Treason!”', 'She bowed before Joash as the rightful king', 'She silently fled from the temple gathering', 'She ordered the musicians to stop the trumpets'], 14),

    mc(1, 'What did Jehoiada order concerning Athaliah?', ['Take her outside and kill any follower', 'Execute her immediately inside the temple', 'Crown her as a joint ruler beside Joash', 'Send her away under guard to Samaria'], 15),
    blank(2, 'Let her not be slain in the house of the _____.', 'LORD', 15, ['Lord']),
    sa(1, 'Who received Jehoiada’s command?', 'the army captains', 15, ['the captains']),
    tf(3, 'Jehoiada ordered Athaliah killed inside the house of the LORD.', false, 15, 'He explicitly said she was not to be slain in the LORD’s house.'),
    mc(2, 'What was to happen to anyone following Athaliah?', ['They were to be killed with the sword', 'They were to join the guards', 'They were to be pardoned', 'They were to leave Judah'], 15),
    sa(2, 'Through what formation was she to be taken?', 'between the ranks', 15, ['the ranks']),

    mc(1, 'Where was Athaliah killed?', ['At the king’s house beyond the horses’ entrance', 'Inside the sacred precinct of the LORD’s house', 'Immediately before the altar belonging to Baal', 'Upon the fortified outer wall of Jerusalem'], 16),
    blank(3, 'and there she was _____.', 'slain', 16),
    sa(2, 'What route did Athaliah take?', 'the horses’ entrance to the king’s house', 16, ['horses entrance']),
    tf(1, 'The guards laid hands on Athaliah.', true, 16),
    mc(2, 'How was Jehoiada’s restriction observed?', ['She was taken outside the temple before execution', 'She received a complete pardon from the new king', 'She was executed immediately beside the altar', 'She escaped through the horses’ entrance unharmed'], 16),

    mc(1, 'What covenant did Jehoiada establish?', ['The king and people would belong to the LORD', 'Judah would formally become servants of Baal', 'The new king would remain subject to Athaliah', 'The temple guards would govern Jerusalem'], 17),
    blank(2, 'that they should be the LORD’s _____.', 'people', 17),
    sa(1, 'What second relationship received a covenant?', 'the king and the people', 17, ['between king and people']),
    tf(3, 'Jehoiada’s covenant concerned only the guards and their duties.', false, 17, 'It bound the LORD, king, and people, and also established a covenant between king and people.'),
    mc(2, 'Who mediated the covenant?', ['Jehoiada', 'Athaliah', 'Joash’s nurse', 'Mattan'], 17),

    mc(1, 'What did the people do to Baal’s house?', ['Demolished it, its altars, and its images', 'Converted the building into a royal palace', 'Closed the building while leaving it undamaged', 'Transferred ownership of the house to Mattan'], 18),
    blank(3, 'they slew Mattan the priest of Ba’al before the _____.', 'altars', 18),
    sa(2, 'Who posted watchmen over the LORD’s house?', 'Jehoiada the priest', 18, ['the priest', 'Jehoiada']),
    tf(1, 'Mattan, Baal’s priest, was killed.', true, 18),
    mc(2, 'What religious reform followed the covenant?', ['Baal’s sanctuary and priest were destroyed', 'The house of the LORD was demolished', 'Baal’s priest was crowned as Judah’s king', 'The religious images were moved to Samaria'], 18),

    mc(1, 'Where did the procession take Joash?', ['From the LORD’s house to the king’s house', 'From Samaria to Jerusalem', 'From the palace to Baal’s house', 'From the city to Ramoth-gilead'], 19),
    blank(2, 'And he took his seat on the throne of the _____.', 'kings', 19),
    sa(1, 'Through which gate did they march?', 'the gate of the guards', 19, ['Gate of the Guards']),
    tf(3, 'Joash remained inside the temple instead of taking the royal throne.', false, 19, 'The procession brought him to the king’s house, where he sat on the throne of the kings.'),
    mc(2, 'Who joined the royal procession?', ['Captains, Carites, guards, and people', 'Baal’s priests together with Queen Athaliah', 'Only Jehoiada and the young king Joash', 'A contingent of soldiers sent from Syria'], 19),

    mc(1, 'How did the land respond after Athaliah’s death?', ['The people rejoiced and the city grew quiet', 'Jerusalem immediately broke into open revolt', 'The temple and palace guards fled from the city', 'Public worship of Baal increased throughout Judah'], 20),
    blank(3, 'and the city was _____.', 'quiet', 20),
    sa(2, 'Where had Athaliah been killed?', 'at the king’s house', 20, ['the palace']),
    tf(1, 'Athaliah’s removal brought public joy and civic quiet.', true, 20),
    mc(2, 'What two results marked the restored kingship?', ['Rejoicing in the land and quiet in the city', 'A severe famine followed by political revolt', 'Renewed warfare followed by a foreign siege', 'Public silence accompanied by national mourning'], 20),

    mc(1, 'How old was Jehoash when he began to reign?', ['Seven years old', 'Six years old', 'Eight years old', 'Twenty-two years old'], 21),
    blank(2, 'Jeho’ash was _____ years old', 'seven', 21, ['7']),
    word(1, 'What office did the seven-year-old assume?', 'king', 21, ['he began to reign']),
    tf(3, 'Jehoash was already an adult when he became king.', false, 21, 'Jehoash was seven years old when he began to reign.'),
    mc(2, 'Which age closes the account of Joash’s rescue and coronation?', ['Seven', 'Six', 'Twelve', 'Thirty-two'], 21),
    word(2, 'Who is the young king also called in the chapter?', 'Joash', 21, ["Jo'ash", 'Jehoash']),
  ],
}

export default bank
