// 2 Kings 24 — quiz bank (RSV). Four verse-anchored forms per verse.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: "2 Kings",
  chapter: 24,
  tag: "quiz-v2-2kings-24",
  rows: [
    blank(2, "In his days _____ king of Babylon came up, and Jehoi’akim became his servant three years;", "Nebuchadnez’zar", 1, ["nebuchadnezzar"]),
    mc(3, "Which word correctly completes this RSV wording: “In his days _____ king of Babylon came up, and Jehoi’akim became his servant three years;”", ["Nebuchadnez’zar", "Jehoi’akim", "Euphra’tes", "Chalde’ans"], 1),
    word(1, "In verse 1, what word completes this phrase: “In his days _____ king of Babylon came up, and Jehoi’akim became his servant three years;”?", "Nebuchadnez’zar", 1, ["nebuchadnezzar"]),
    tf(2, "The RSV states: “In his days Nebuchadnez’zar king of Babylon came up, and Jehoi’akim became his servant three years; then he turned and rebelled against him.”", true, 1),
    blank(3, "And the LORD sent against him bands of the _____, and bands of the Syrians, and bands of the Moabites, and bands of the", "Chalde’ans", 2, ["chaldeans"]),
    mc(1, "Which word correctly completes this RSV wording: “And the LORD sent against him bands of the _____, and bands of the Syrians, and bands of the Moabites, and bands of the”", ["Chalde’ans", "Brook", "Libnah", "Chronicles"], 2),
    word(2, "In verse 2, what word completes this phrase: “And the LORD sent against him bands of the _____, and bands of the Syrians, and bands of the Moabites, and bands of the”?", "Chalde’ans", 2, ["chaldeans"]),
    tf(3, "The RSV does not state: “And the LORD sent against him bands of the Chalde’ans, and bands of the Syrians, and bands of the Moabites, and bands of the Ammonites, and sent them against Judah to destroy it, according to the word of the LORD which he spoke by his servants the prophets.”", false, 2, "The quoted wording is the RSV text of this verse."),
    blank(1, "command of the LORD, to remove them out of his sight, for the sins of _____, according to all that he had done,", "Manas’seh", 3, ["manasseh"]),
    mc(2, "Which word correctly completes this RSV wording: “command of the LORD, to remove them out of his sight, for the sins of _____, according to all that he had done,”", ["Manas’seh", "Jehoi’achin’s", "Judah", "Elna’than"], 3),
    word(3, "In verse 3, what word completes this phrase: “command of the LORD, to remove them out of his sight, for the sins of _____, according to all that he had done,”?", "Manas’seh", 3, ["manasseh"]),
    tf(1, "The RSV states: “Surely this came upon Judah at the command of the LORD, to remove them out of his sight, for the sins of Manas’seh, according to all that he had done,”", true, 3),
    blank(2, "and also for the innocent blood that he had shed; for he filled _____ with innocent blood, and the LORD would not pardon.", "Jerusalem", 4, ["jerusalem"]),
    mc(3, "Which word correctly completes this RSV wording: “and also for the innocent blood that he had shed; for he filled _____ with innocent blood, and the LORD would not pardon.”", ["Jerusalem", "Chalde’ans", "Egypt", "Jeremiah"], 4),
    word(1, "In verse 4, what word completes this phrase: “and also for the innocent blood that he had shed; for he filled _____ with innocent blood, and the LORD would not pardon.”?", "Jerusalem", 4, ["jerusalem"]),
    tf(2, "The RSV does not state: “and also for the innocent blood that he had shed; for he filled Jerusalem with innocent blood, and the LORD would not pardon.”", false, 4, "The quoted wording is the RSV text of this verse."),
    blank(3, "Now the rest of the deeds of _____, and all that he did, are they not written in the Book of the Chronicles", "Jehoi’akim", 5, ["jehoiakim"]),
    mc(1, "Which word correctly completes this RSV wording: “Now the rest of the deeds of _____, and all that he did, are they not written in the Book of the Chronicles”", ["Jehoi’akim", "Jerusalem", "Mattani’ah", "Ammonites"], 5),
    word(2, "In verse 5, what word completes this phrase: “Now the rest of the deeds of _____, and all that he did, are they not written in the Book of the Chronicles”?", "Jehoi’akim", 5, ["jehoiakim"]),
    tf(3, "The RSV states: “Now the rest of the deeds of Jehoi’akim, and all that he did, are they not written in the Book of the Chronicles of the Kings of Judah?”", true, 5),
    blank(1, "So Jehoi’akim slept with his fathers, and _____ his son reigned in his stead.", "Jehoi’achin", 6, ["jehoiachin"]),
    mc(2, "Which word correctly completes this RSV wording: “So Jehoi’akim slept with his fathers, and _____ his son reigned in his stead.”", ["Jehoi’achin", "Jeremiah", "Jerusalem", "Israel"], 6),
    word(3, "In verse 6, what word completes this phrase: “So Jehoi’akim slept with his fathers, and _____ his son reigned in his stead.”?", "Jehoi’achin", 6, ["jehoiachin"]),
    tf(1, "The RSV does not state: “So Jehoi’akim slept with his fathers, and Jehoi’achin his son reigned in his stead.”", false, 6, "The quoted wording is the RSV text of this verse."),
    blank(2, "that belonged to the king of Egypt from the Brook of Egypt to the river _____.", "Euphra’tes", 7, ["euphrates"]),
    mc(3, "Which word correctly completes this RSV wording: “that belonged to the king of Egypt from the Brook of Egypt to the river _____.”", ["Euphra’tes", "Hamu’tal", "Surely", "Israel"], 7),
    word(1, "In verse 7, what word completes this phrase: “that belonged to the king of Egypt from the Brook of Egypt to the river _____.”?", "Euphra’tes", 7, ["euphrates"]),
    tf(2, "The RSV states: “And the king of Egypt did not come again out of his land, for the king of Babylon had taken all that belonged to the king of Egypt from the Brook of Egypt to the river Euphra’tes.”", true, 7),
    blank(3, "_____ was eighteen years old when he became king, and he reigned three months", "Jehoi’achin", 8, ["jehoiachin"]),
    mc(1, "Which word correctly completes this RSV wording: “_____ was eighteen years old when he became king, and he reigned three months”", ["Jehoi’achin", "Nehush’ta", "Babylon", "Jerusalem"], 8),
    word(2, "In verse 8, what word completes this phrase: “_____ was eighteen years old when he became king, and he reigned three months”?", "Jehoi’achin", 8, ["jehoiachin"]),
    tf(3, "The RSV does not state: “Jehoi’achin was eighteen years old when he became king, and he reigned three months in Jerusalem. His mother’s name was Nehush’ta the daughter of Elna’than of Jerusalem.”", false, 8, "The quoted wording is the RSV text of this verse."),
    blank(1, "And he did what was evil in the sight of the LORD, _____ to all that his father had done.", "according", 9, ["according"]),
    mc(2, "Which word correctly completes this RSV wording: “And he did what was evil in the sight of the LORD, _____ to all that his father had done.”", ["according", "carried", "mighty", "wives"], 9),
    word(3, "In verse 9, what word completes this phrase: “And he did what was evil in the sight of the LORD, _____ to all that his father had done.”?", "according", 9, ["according"]),
    tf(1, "The RSV states: “And he did what was evil in the sight of the LORD, according to all that his father had done.”", true, 9),
    blank(2, "At that time the servants of _____ king of Babylon came up to Jerusalem, and the city was besieged.", "Nebuchadnez’zar", 10, ["nebuchadnezzar"]),
    mc(3, "Which word correctly completes this RSV wording: “At that time the servants of _____ king of Babylon came up to Jerusalem, and the city was besieged.”", ["Nebuchadnez’zar", "Jehoi’akim", "Euphra’tes", "Chalde’ans"], 10),
    word(1, "In verse 10, what word completes this phrase: “At that time the servants of _____ king of Babylon came up to Jerusalem, and the city was besieged.”?", "Nebuchadnez’zar", 10, ["nebuchadnezzar"]),
    tf(2, "The RSV does not state: “At that time the servants of Nebuchadnez’zar king of Babylon came up to Jerusalem, and the city was besieged.”", false, 10, "The quoted wording is the RSV text of this verse."),
    blank(3, "And _____ king of Babylon came to the city, while his servants were besieging it;", "Nebuchadnez’zar", 11, ["nebuchadnezzar"]),
    mc(1, "Which word correctly completes this RSV wording: “And _____ king of Babylon came to the city, while his servants were besieging it;”", ["Nebuchadnez’zar", "Jehoi’akim", "Euphra’tes", "Chalde’ans"], 11),
    word(2, "In verse 11, what word completes this phrase: “And _____ king of Babylon came to the city, while his servants were besieging it;”?", "Nebuchadnez’zar", 11, ["nebuchadnezzar"]),
    tf(3, "The RSV states: “And Nebuchadnez’zar king of Babylon came to the city, while his servants were besieging it;”", true, 11),
    blank(1, "and _____ the king of Judah gave himself up to the king of Babylon, himself, and", "Jehoi’achin", 12, ["jehoiachin"]),
    mc(2, "Which word correctly completes this RSV wording: “and _____ the king of Judah gave himself up to the king of Babylon, himself, and”", ["Jehoi’achin", "Zedeki’ah", "Surely", "Jerusalem"], 12),
    word(3, "In verse 12, what word completes this phrase: “and _____ the king of Judah gave himself up to the king of Babylon, himself, and”?", "Jehoi’achin", 12, ["jehoiachin"]),
    tf(1, "The RSV does not state: “and Jehoi’achin the king of Judah gave himself up to the king of Babylon, himself, and his mother, and his servants, and his princes, and his palace officials. The king of Babylon took him prisoner in the eighth year of his reign,”", false, 12, "The quoted wording is the RSV text of this verse."),
    blank(2, "cut in pieces all the vessels of gold in the temple of the LORD, which _____ king of Israel had made, as the LORD had foretold.", "Solomon", 13, ["solomon"]),
    mc(3, "Which word correctly completes this RSV wording: “cut in pieces all the vessels of gold in the temple of the LORD, which _____ king of Israel had made, as the LORD had foretold.”", ["Solomon", "Euphra’tes", "Chalde’ans", "Jehoi’achin"], 13),
    word(1, "In verse 13, what word completes this phrase: “cut in pieces all the vessels of gold in the temple of the LORD, which _____ king of Israel had made, as the LORD had foretold.”?", "Solomon", 13, ["solomon"]),
    tf(2, "The RSV states: “and carried off all the treasures of the house of the LORD, and the treasures of the king’s house, and cut in pieces all the vessels of gold in the temple of the LORD, which Solomon king of Israel had made, as the LORD had foretold.”", true, 13),
    blank(3, "He carried away all _____, and all the princes, and all the mighty men of valor, ten thousand captives,", "Jerusalem", 14, ["jerusalem"]),
    mc(1, "Which word correctly completes this RSV wording: “He carried away all _____, and all the princes, and all the mighty men of valor, ten thousand captives,”", ["Jerusalem", "Mattani’ah", "Ammonites", "Nehush’ta"], 14),
    word(2, "In verse 14, what word completes this phrase: “He carried away all _____, and all the princes, and all the mighty men of valor, ten thousand captives,”?", "Jerusalem", 14, ["jerusalem"]),
    tf(3, "The RSV does not state: “He carried away all Jerusalem, and all the princes, and all the mighty men of valor, ten thousand captives, and all the craftsmen and the smiths; none remained, except the poorest people of the land.”", false, 14, "The quoted wording is the RSV text of this verse."),
    blank(1, "And he carried away _____ to Babylon; the king’s mother, the king’s wives, his officials, and the", "Jehoi’achin", 15, ["jehoiachin"]),
    mc(2, "Which word correctly completes this RSV wording: “And he carried away _____ to Babylon; the king’s mother, the king’s wives, his officials, and the”", ["Jehoi’achin", "Jehoi’achin’s", "Ammonites", "Jerusalem"], 15),
    word(3, "In verse 15, what word completes this phrase: “And he carried away _____ to Babylon; the king’s mother, the king’s wives, his officials, and the”?", "Jehoi’achin", 15, ["jehoiachin"]),
    tf(1, "The RSV states: “And he carried away Jehoi’achin to Babylon; the king’s mother, the king’s wives, his officials, and the chief men of the land, he took into captivity from Jerusalem to Babylon.”", true, 15),
    blank(2, "And the king of _____ brought captive to Babylon all the men of valor, seven thousand, and the", "Babylon", 16, ["babylon"]),
    mc(3, "Which word correctly completes this RSV wording: “And the king of _____ brought captive to Babylon all the men of valor, seven thousand, and the”", ["Babylon", "Jehoi’achin", "Jeremiah", "Book"], 16),
    word(1, "In verse 16, what word completes this phrase: “And the king of _____ brought captive to Babylon all the men of valor, seven thousand, and the”?", "Babylon", 16, ["babylon"]),
    tf(2, "The RSV does not state: “And the king of Babylon brought captive to Babylon all the men of valor, seven thousand, and the craftsmen and the smiths, one thousand, all of them strong and fit for war.”", false, 16, "The quoted wording is the RSV text of this verse."),
    blank(3, "And the king of Babylon made Mattani’ah, _____ uncle, king in his stead, and changed his name to Zedeki’ah.", "Jehoi’achin’s", 17, ["jehoiachins"]),
    mc(1, "Which word correctly completes this RSV wording: “And the king of Babylon made Mattani’ah, _____ uncle, king in his stead, and changed his name to Zedeki’ah.”", ["Jehoi’achin’s", "Chronicles", "Chalde’ans", "Zedeki’ah"], 17),
    word(2, "In verse 17, what word completes this phrase: “And the king of Babylon made Mattani’ah, _____ uncle, king in his stead, and changed his name to Zedeki’ah.”?", "Jehoi’achin’s", 17, ["jehoiachins"]),
    tf(3, "The RSV states: “And the king of Babylon made Mattani’ah, Jehoi’achin’s uncle, king in his stead, and changed his name to Zedeki’ah.”", true, 17),
    blank(1, "_____ was twenty-one years old when he became king, and he reigned eleven years", "Zedeki’ah", 18, ["zedekiah"]),
    mc(2, "Which word correctly completes this RSV wording: “_____ was twenty-one years old when he became king, and he reigned eleven years”", ["Zedeki’ah", "Jehoi’achin’s", "Surely", "Elna’than"], 18),
    word(3, "In verse 18, what word completes this phrase: “_____ was twenty-one years old when he became king, and he reigned eleven years”?", "Zedeki’ah", 18, ["zedekiah"]),
    tf(1, "The RSV does not state: “Zedeki’ah was twenty-one years old when he became king, and he reigned eleven years in Jerusalem. His mother’s name was Hamu’tal the daughter of Jeremiah of Libnah.”", false, 18, "The quoted wording is the RSV text of this verse."),
    blank(2, "he did what was evil in the sight of the LORD, according to all that _____ had done.", "Jehoi’akim", 19, ["jehoiakim"]),
    mc(3, "Which word correctly completes this RSV wording: “he did what was evil in the sight of the LORD, according to all that _____ had done.”", ["Jehoi’akim", "Syrians", "Brook", "Libnah"], 19),
    word(1, "In verse 19, what word completes this phrase: “he did what was evil in the sight of the LORD, according to all that _____ had done.”?", "Jehoi’akim", 19, ["jehoiakim"]),
    tf(2, "The RSV states: “And he did what was evil in the sight of the LORD, according to all that Jehoi’akim had done.”", true, 19),
    blank(3, "For because of the anger of the LORD it came to the point in _____ and Judah that he cast them out from his presence. And Zedeki’ah rebelled", "Jerusalem", 20, ["jerusalem"]),
    mc(1, "Which word correctly completes this RSV wording: “For because of the anger of the LORD it came to the point in _____ and Judah that he cast them out from his presence. And Zedeki’ah rebelled”", ["Jerusalem", "Chronicles", "Jehoi’achin’s", "Judah"], 20),
    word(2, "In verse 20, what word completes this phrase: “For because of the anger of the LORD it came to the point in _____ and Judah that he cast them out from his presence. And Zedeki’ah rebelled”?", "Jerusalem", 20, ["jerusalem"]),
    tf(3, "The RSV does not state: “For because of the anger of the LORD it came to the point in Jerusalem and Judah that he cast them out from his presence. And Zedeki’ah rebelled against the king of Babylon.”", false, 20, "The quoted wording is the RSV text of this verse."),
    blank(1, "In his days Nebuchadnez’zar king of Babylon came up, and _____ became his servant three years; then he turned and rebelled against him.", "Jehoi’akim", 1, ["jehoiakim"]),
    mc(2, "Select the missing RSV word: “and bands of the Syrians, and bands of the Moabites, and bands of the _____, and sent them against Judah to destroy it, according to the word of the”", ["Ammonites", "Chalde’ans", "Egypt", "Jeremiah"], 2),
    word(3, "What missing word belongs in this verse 3 clause: “the LORD, to remove them out of his sight, for the sins of Manas’seh, _____ to all that he had done,”?", "according", 3, ["according"]),
    tf(1, "This wording appears in verse 4: “and also for the innocent blood that he had shed; for he filled Jerusalem with innocent blood, and”", true, 4),
    blank(2, "Jehoi’akim, and all that he did, are they not written in the Book of the _____ of the Kings of Judah?", "Chronicles", 5, ["chronicles"]),
    mc(3, "Select the missing RSV word: “So _____ slept with his fathers, and Jehoi’achin his son reigned in his stead.”", ["Jehoi’akim", "Judah", "Elna’than", "Chalde’ans"], 6),
    word(1, "What missing word belongs in this verse 7 clause: “come again out of his land, for the king of Babylon had taken all that _____ to the king of Egypt from the Brook of Egypt to the river Euphra’tes.”?", "belonged", 7, ["belonged"]),
    tf(2, "This wording appears in verse 8: “eighteen years old when he became king, and he reigned three months in Jerusalem. His mother’s name was Nehush’ta the daughter of Elna’than of Jerusalem.”", true, 8),
    blank(3, "did what was evil in the sight of the LORD, according to all that his _____ had done.", "father", 9, ["father"]),
    mc(1, "Select the missing RSV word: “that time the servants of Nebuchadnez’zar king of Babylon came up to _____, and the city was besieged.”", ["Jerusalem", "Chronicles", "Jehoi’achin’s", "Judah"], 10),
    word(2, "What missing word belongs in this verse 11 clause: “Nebuchadnez’zar king of Babylon came to the city, while his servants were _____ it;”?", "besieging", 11, ["besieging"]),
    tf(3, "This wording appears in verse 12: “himself, and his mother, and his servants, and his princes, and his palace officials. The king of Babylon took him prisoner in the eighth year of his reign,”", true, 12),
    blank(1, "and carried off all the _____ of the house of the LORD, and the treasures of the king’s house, and cut", "treasures", 13, ["treasures"]),
    mc(2, "Select the missing RSV word: “princes, and all the mighty men of valor, ten thousand captives, and all the _____ and the smiths; none remained, except the poorest people of the land.”", ["craftsmen", "eleven", "three", "servants"], 14),
    word(3, "What missing word belongs in this verse 15 clause: “away Jehoi’achin to Babylon; the king’s mother, the king’s wives, his _____, and the chief men of the land, he took into captivity from Jerusalem”?", "officials", 15, ["officials"]),
    tf(1, "This wording appears in verse 16: “brought captive to Babylon all the men of valor, seven thousand, and the craftsmen and the smiths, one thousand, all of them strong and fit for war.”", true, 16),
    blank(2, "And the king of Babylon made _____, Jehoi’achin’s uncle, king in his stead, and changed his name to Zedeki’ah.", "Mattani’ah", 17, ["mattaniah"]),
    mc(3, "Select the missing RSV word: “Zedeki’ah was _____ years old when he became king, and he reigned eleven years in Jerusalem.”", ["twenty-one", "written", "mother’s", "eighth"], 18),
    word(1, "What missing word belongs in this verse 19 clause: “And he did what was evil in the sight of the LORD, _____ to all that Jehoi’akim had done.”?", "according", 19, ["according"]),
    tf(2, "This wording appears in verse 20: “point in Jerusalem and Judah that he cast them out from his presence. And Zedeki’ah rebelled against the king of Babylon.”", true, 20),
    blank(3, "up, and Jehoi’akim became his servant three years; then he turned and _____ against him.", "rebelled", 1, ["rebelled"]),
    mc(1, "Select the missing RSV word: “and bands of the Ammonites, and sent them against Judah to destroy it, _____ to the word of the LORD which he spoke by his servants the prophets.”", ["according", "pieces", "craftsmen", "captive"], 2),
    word(2, "What missing word belongs in this verse 3 clause: “Surely this came upon Judah at the _____ of the LORD, to remove them out of his sight, for the sins of Manas’seh,”?", "command", 3, ["command"]),
    tf(3, "This wording appears in verse 4: “and also for the innocent blood that he had shed; for he filled Jerusalem with innocent blood, and the LORD would not pardon.”", true, 4),
    blank(1, "the rest of the deeds of Jehoi’akim, and all that he did, are they not _____ in the Book of the Chronicles of the Kings of Judah?", "written", 5, ["written"]),
    mc(2, "Select the missing RSV word: “So Jehoi’akim slept with his _____, and Jehoi’achin his son reigned in his stead.”", ["fathers", "done", "reigned", "name"], 6),
    word(3, "What missing word belongs in this verse 7 clause: “the king of Egypt did not come again out of his land, for the king of _____ had taken all that belonged to the king of Egypt from the Brook of Egypt”?", "Babylon", 7, ["babylon"]),
    tf(1, "This wording appears in verse 8: “king, and he reigned three months in Jerusalem. His mother’s name was Nehush’ta the daughter of Elna’than of Jerusalem.”", true, 8),
    blank(2, "And he did what was evil in the _____ of the LORD, according to all that his father had done.", "sight", 9, ["sight"]),
    mc(3, "Select the missing RSV word: “At that time the _____ of Nebuchadnez’zar king of Babylon came up to Jerusalem, and the city”", ["servants", "craftsmen", "captive", "presence"], 10),
    word(1, "What missing word belongs in this verse 11 clause: “And Nebuchadnez’zar king of Babylon came to the city, while his _____ were besieging it;”?", "servants", 11, ["servants"]),
    tf(2, "This wording appears in verse 12: “gave himself up to the king of Babylon, himself, and his mother, and his servants, and his princes, and his palace officials. The king of Babylon took him”", true, 12),
    blank(3, "temple of the LORD, which Solomon king of Israel had made, as the LORD had _____.", "foretold", 13, ["foretold"]),
    mc(1, "Select the missing RSV word: “Jerusalem, and all the princes, and all the mighty men of valor, ten _____ captives, and all the craftsmen and the smiths; none remained, except”", ["thousand", "fathers", "mother’s", "mother"], 14),
    word(2, "What missing word belongs in this verse 15 clause: “king’s wives, his officials, and the chief men of the land, he took into _____ from Jerusalem to Babylon.”?", "captivity", 15, ["captivity"]),
    tf(3, "This wording appears in verse 16: “king of Babylon brought captive to Babylon all the men of valor, seven thousand, and the craftsmen and the smiths, one thousand, all of them strong and”", true, 16),
    blank(1, "Mattani’ah, Jehoi’achin’s uncle, king in his stead, and changed his name to _____.", "Zedeki’ah", 17, ["zedekiah"]),
    mc(2, "Select the missing RSV word: “twenty-one years old when he became king, and he reigned eleven years in _____. His mother’s name was Hamu’tal the daughter of Jeremiah of Libnah.”", ["Jerusalem", "Chalde’ans", "Egypt", "Jeremiah"], 18),
    word(3, "What missing word belongs in this verse 19 clause: “And he did what was evil in the _____ of the LORD, according to all that Jehoi’akim had done.”?", "sight", 19, ["sight"]),
    tf(1, "This wording appears in verse 20: “came to the point in Jerusalem and Judah that he cast them out from his presence. And Zedeki’ah rebelled against the king of Babylon.”", true, 20),
    mc(3, "Who was carried away when Jehoiachin surrendered, and who remained?", ["Jehoiachin, his household and officials, and ten thousand including craftsmen and smiths were taken; only the poorest remained", "Only Jehoiachin was taken; all officials remained", "Every inhabitant was taken with none left", "The army was taken, but Jehoiachin remained"], 14),
    mc(2, "Whom did Babylon’s king appoint in Jehoiachin’s place, and what name did he give him?", ["Jehoiachin’s uncle Mattaniah, renamed Zedekiah", "Jehoiachin’s son Eliakim, renamed Jehoiakim", "Gedaliah, renamed Mattaniah", "Jehoahaz, renamed Shallum"], 17),
  ],
};

export default bank;
