// 2 Kings 22 — quiz bank (RSV). Four verse-anchored forms per verse.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: "2 Kings",
  chapter: 22,
  tag: "quiz-v2-2kings-22",
  rows: [
    blank(2, "years old when he began to reign, and he reigned thirty-one years in _____. His mother’s name was Jedi’dah the daughter of Adai’ah of Bozkath.", "Jerusalem", 1, ["jerusalem"]),
    mc(3, "Which word correctly completes this RSV wording: “years old when he began to reign, and he reigned thirty-one years in _____. His mother’s name was Jedi’dah the daughter of Adai’ah of Bozkath.”", ["Jerusalem", "Azali’ah", "Harhas", "Jedi’dah"], 1),
    word(1, "In verse 1, what word completes this phrase: “years old when he began to reign, and he reigned thirty-one years in _____. His mother’s name was Jedi’dah the daughter of Adai’ah of Bozkath.”?", "Jerusalem", 1, ["jerusalem"]),
    tf(2, "The RSV states: “Josi’ah was eight years old when he began to reign, and he reigned thirty-one years in Jerusalem. His mother’s name was Jedi’dah the daughter of Adai’ah of Bozkath.”", true, 1),
    blank(3, "what was right in the eyes of the LORD, and walked in all the way of _____ his father, and he did not turn aside to the right hand or to the left.", "David", 2, ["david"]),
    mc(1, "Which word correctly completes this RSV wording: “what was right in the eyes of the LORD, and walked in all the way of _____ his father, and he did not turn aside to the right hand or to the left.”", ["David", "Judah", "Because", "Meshul’lam"], 2),
    word(2, "In verse 2, what word completes this phrase: “what was right in the eyes of the LORD, and walked in all the way of _____ his father, and he did not turn aside to the right hand or to the left.”?", "David", 2, ["david"]),
    tf(3, "The RSV does not state: “And he did what was right in the eyes of the LORD, and walked in all the way of David his father, and he did not turn aside to the right hand or to the left.”", false, 2, "The quoted wording is the RSV text of this verse."),
    blank(1, "year of King Josi’ah, the king sent Shaphan the son of Azali’ah, son of _____, the secretary, to the house of the LORD, saying,", "Meshul’lam", 3, ["meshullam"]),
    mc(2, "Which word correctly completes this RSV wording: “year of King Josi’ah, the king sent Shaphan the son of Azali’ah, son of _____, the secretary, to the house of the LORD, saying,”", ["Meshul’lam", "Behold", "Azali’ah", "Second"], 3),
    word(3, "In verse 3, what word completes this phrase: “year of King Josi’ah, the king sent Shaphan the son of Azali’ah, son of _____, the secretary, to the house of the LORD, saying,”?", "Meshul’lam", 3, ["meshullam"]),
    tf(1, "The RSV states: “In the eighteenth year of King Josi’ah, the king sent Shaphan the son of Azali’ah, son of Meshul’lam, the secretary, to the house of the LORD, saying,”", true, 3),
    blank(2, "\"Go up to _____ the high priest, that he may reckon the amount of the money which has", "Hilki’ah", 4, ["hilkiah"]),
    mc(3, "Which word correctly completes this RSV wording: “\"Go up to _____ the high priest, that he may reckon the amount of the money which has”", ["Hilki’ah", "Josi’ah", "Achbor", "Israel"], 4),
    word(1, "In verse 4, what word completes this phrase: “\"Go up to _____ the high priest, that he may reckon the amount of the money which has”?", "Hilki’ah", 4, ["hilkiah"]),
    tf(2, "The RSV does not state: “\"Go up to Hilki’ah the high priest, that he may reckon the amount of the money which has been brought into the house of the LORD, which the keepers of the threshold have collected from the people;”", false, 4, "The quoted wording is the RSV text of this verse."),
    blank(3, "and let it be given into the hand of the workmen who have the _____ of the house of the LORD; and let them give it to the workmen who are", "oversight", 5, ["oversight"]),
    mc(1, "Which word correctly completes this RSV wording: “and let it be given into the hand of the workmen who have the _____ of the house of the LORD; and let them give it to the workmen who are”", ["oversight", "workmen", "repair", "read"], 5),
    word(2, "In verse 5, what word completes this phrase: “and let it be given into the hand of the workmen who have the _____ of the house of the LORD; and let them give it to the workmen who are”?", "oversight", 5, ["oversight"]),
    tf(3, "The RSV states: “and let it be given into the hand of the workmen who have the oversight of the house of the LORD; and let them give it to the workmen who are at the house of the LORD, repairing the house,”", true, 5),
    blank(1, "that is, to the _____, and to the builders, and to the masons, as well as for buying timber", "carpenters", 6, ["carpenters"]),
    mc(2, "Which word correctly completes this RSV wording: “that is, to the _____, and to the builders, and to the masons, as well as for buying timber”", ["carpenters", "reported", "concerning", "keeper"], 6),
    word(3, "In verse 6, what word completes this phrase: “that is, to the _____, and to the builders, and to the masons, as well as for buying timber”?", "carpenters", 6, ["carpenters"]),
    tf(1, "The RSV does not state: “that is, to the carpenters, and to the builders, and to the masons, as well as for buying timber and quarried stone to repair the house.”", false, 6, "The quoted wording is the RSV text of this verse."),
    blank(2, "But no _____ shall be asked from them for the money which is delivered into their hand,", "accounting", 7, ["accounting"]),
    mc(3, "Which word correctly completes this RSV wording: “But no _____ shall be asked from them for the money which is delivered into their hand,”", ["accounting", "commanded", "obeyed", "forsaken"], 7),
    word(1, "In verse 7, what word completes this phrase: “But no _____ shall be asked from them for the money which is delivered into their hand,”?", "accounting", 7, ["accounting"]),
    tf(2, "The RSV states: “But no accounting shall be asked from them for the money which is delivered into their hand, for they deal honestly.\"”", true, 7),
    blank(3, "And _____ the high priest said to Shaphan the secretary, \"I have found the book", "Hilki’ah", 8, ["hilkiah"]),
    mc(1, "Which word correctly completes this RSV wording: “And _____ the high priest said to Shaphan the secretary, \"I have found the book”", ["Hilki’ah", "Josi’ah", "Achbor", "Israel"], 8),
    word(2, "In verse 8, what word completes this phrase: “And _____ the high priest said to Shaphan the secretary, \"I have found the book”?", "Hilki’ah", 8, ["hilkiah"]),
    tf(3, "The RSV does not state: “And Hilki’ah the high priest said to Shaphan the secretary, \"I have found the book of the law in the house of the LORD.\" And Hilki’ah gave the book to Shaphan, and he read it.”", false, 8, "The quoted wording is the RSV text of this verse."),
    blank(1, "And _____ the secretary came to the king, and reported to the king, \"Your servants", "Shaphan", 9, ["shaphan"]),
    mc(2, "Which word correctly completes this RSV wording: “And _____ the secretary came to the king, and reported to the king, \"Your servants”", ["Shaphan", "Azali’ah", "Harhas", "Jerusalem"], 9),
    word(3, "In verse 9, what word completes this phrase: “And _____ the secretary came to the king, and reported to the king, \"Your servants”?", "Shaphan", 9, ["shaphan"]),
    tf(1, "The RSV states: “And Shaphan the secretary came to the king, and reported to the king, \"Your servants have emptied out the money that was found in the house, and have delivered it into the hand of the workmen who have the oversight of the house of the LORD.\"”", true, 9),
    blank(2, "Then Shaphan the secretary told the king, \"_____ the priest has given me a book.\" And Shaphan read it before the king.", "Hilki’ah", 10, ["hilkiah"]),
    mc(3, "Which word correctly completes this RSV wording: “Then Shaphan the secretary told the king, \"_____ the priest has given me a book.\" And Shaphan read it before the king.”", ["Hilki’ah", "Judah", "Because", "Azali’ah"], 10),
    word(1, "In verse 10, what word completes this phrase: “Then Shaphan the secretary told the king, \"_____ the priest has given me a book.\" And Shaphan read it before the king.”?", "Hilki’ah", 10, ["hilkiah"]),
    tf(2, "The RSV does not state: “Then Shaphan the secretary told the king, \"Hilki’ah the priest has given me a book.\" And Shaphan read it before the king.”", false, 10, "The quoted wording is the RSV text of this verse."),
    blank(3, "And when the king heard the words of the book of the law, he rent his _____.", "clothes", 11, ["clothes"]),
    mc(1, "Which word correctly completes this RSV wording: “And when the king heard the words of the book of the law, he rent his _____.”", ["clothes", "because", "talked", "might"], 11),
    word(2, "In verse 11, what word completes this phrase: “And when the king heard the words of the book of the law, he rent his _____.”?", "clothes", 11, ["clothes"]),
    tf(3, "The RSV states: “And when the king heard the words of the book of the law, he rent his clothes.”", true, 11),
    blank(1, "And the king commanded _____ the priest, and Ahi’kam the son of Shaphan, and Achbor the son of Micai’ah,", "Hilki’ah", 12, ["hilkiah"]),
    mc(2, "Which word correctly completes this RSV wording: “And the king commanded _____ the priest, and Ahi’kam the son of Shaphan, and Achbor the son of Micai’ah,”", ["Hilki’ah", "Josi’ah", "Achbor", "Israel"], 12),
    word(3, "In verse 12, what word completes this phrase: “And the king commanded _____ the priest, and Ahi’kam the son of Shaphan, and Achbor the son of Micai’ah,”?", "Hilki’ah", 12, ["hilkiah"]),
    tf(1, "The RSV does not state: “And the king commanded Hilki’ah the priest, and Ahi’kam the son of Shaphan, and Achbor the son of Micai’ah, and Shaphan the secretary, and Asai’ah the king’s servant, saying,”", false, 12, "The quoted wording is the RSV text of this verse."),
    blank(2, "\"Go, inquire of the LORD for me, and for the people, and for all _____, concerning the words of this book that has been found; for great is the", "Judah", 13, ["judah"]),
    mc(3, "Which word correctly completes this RSV wording: “\"Go, inquire of the LORD for me, and for the people, and for all _____, concerning the words of this book that has been found; for great is the”", ["Judah", "Shaphan", "Harhas", "Jerusalem"], 13),
    word(1, "In verse 13, what word completes this phrase: “\"Go, inquire of the LORD for me, and for the people, and for all _____, concerning the words of this book that has been found; for great is the”?", "Judah", 13, ["judah"]),
    tf(2, "The RSV states: “\"Go, inquire of the LORD for me, and for the people, and for all Judah, concerning the words of this book that has been found; for great is the wrath of the LORD that is kindled against us, because our fathers have not obeyed the words of this book, to do according to all that is written concerning us.\"”", true, 13),
    blank(3, "son of Tikvah, son of Harhas, keeper of the wardrobe (now she dwelt in _____ in the Second Quarter); and they talked with her.", "Jerusalem", 14, ["jerusalem"]),
    mc(1, "Which word correctly completes this RSV wording: “son of Tikvah, son of Harhas, keeper of the wardrobe (now she dwelt in _____ in the Second Quarter); and they talked with her.”", ["Jerusalem", "Judah", "Because", "Meshul’lam"], 14),
    word(2, "In verse 14, what word completes this phrase: “son of Tikvah, son of Harhas, keeper of the wardrobe (now she dwelt in _____ in the Second Quarter); and they talked with her.”?", "Jerusalem", 14, ["jerusalem"]),
    tf(3, "The RSV does not state: “So Hilki’ah the priest, and Ahi’kam, and Achbor, and Shaphan, and Asai’ah went to Huldah the prophetess, the wife of Shallum the son of Tikvah, son of Harhas, keeper of the wardrobe (now she dwelt in Jerusalem in the Second Quarter); and they talked with her.”", false, 14, "The quoted wording is the RSV text of this verse."),
    blank(1, "And she said to them, \"Thus says the LORD, the God of _____: `Tell the man who sent you to me,", "Israel", 15, ["israel"]),
    mc(2, "Which word correctly completes this RSV wording: “And she said to them, \"Thus says the LORD, the God of _____: `Tell the man who sent you to me,”", ["Israel", "Quarter", "Bozkath", "Judah"], 15),
    word(3, "In verse 15, what word completes this phrase: “And she said to them, \"Thus says the LORD, the God of _____: `Tell the man who sent you to me,”?", "Israel", 15, ["israel"]),
    tf(1, "The RSV states: “And she said to them, \"Thus says the LORD, the God of Israel: `Tell the man who sent you to me,”", true, 15),
    blank(2, "Thus says the LORD, _____, I will bring evil upon this place and upon its inhabitants, all the words", "Behold", 16, ["behold"]),
    mc(3, "Which word correctly completes this RSV wording: “Thus says the LORD, _____, I will bring evil upon this place and upon its inhabitants, all the words”", ["Behold", "Josi’ah", "Ahi’kam", "Thus"], 16),
    word(1, "In verse 16, what word completes this phrase: “Thus says the LORD, _____, I will bring evil upon this place and upon its inhabitants, all the words”?", "Behold", 16, ["behold"]),
    tf(2, "The RSV does not state: “Thus says the LORD, Behold, I will bring evil upon this place and upon its inhabitants, all the words of the book which the king of Judah has read.”", false, 16, "The quoted wording is the RSV text of this verse."),
    blank(3, "_____ they have forsaken me and have burned incense to other gods, that they", "Because", 17, ["because"]),
    mc(1, "Which word correctly completes this RSV wording: “_____ they have forsaken me and have burned incense to other gods, that they”", ["Because", "Shaphan", "Tikvah", "Jerusalem"], 17),
    word(2, "In verse 17, what word completes this phrase: “_____ they have forsaken me and have burned incense to other gods, that they”?", "Because", 17, ["because"]),
    tf(3, "The RSV states: “Because they have forsaken me and have burned incense to other gods, that they might provoke me to anger with all the work of their hands, therefore my wrath will be kindled against this place, and it will not be quenched.”", true, 17),
    blank(1, "LORD, thus shall you say to him, Thus says the LORD, the God of Israel: _____ the words which you have heard,", "Regarding", 18, ["regarding"]),
    mc(2, "Which word correctly completes this RSV wording: “LORD, thus shall you say to him, Thus says the LORD, the God of Israel: _____ the words which you have heard,”", ["Regarding", "Asai’ah", "Behold", "Azali’ah"], 18),
    word(3, "In verse 18, what word completes this phrase: “LORD, thus shall you say to him, Thus says the LORD, the God of Israel: _____ the words which you have heard,”?", "Regarding", 18, ["regarding"]),
    tf(1, "The RSV does not state: “But as to the king of Judah, who sent you to inquire of the LORD, thus shall you say to him, Thus says the LORD, the God of Israel: Regarding the words which you have heard,”", false, 18, "The quoted wording is the RSV text of this verse."),
    blank(2, "LORD, when you heard how I spoke against this place, and against its _____, that they should become a desolation and a curse, and you have rent your", "inhabitants", 19, ["inhabitants"]),
    mc(3, "Which word correctly completes this RSV wording: “LORD, when you heard how I spoke against this place, and against its _____, that they should become a desolation and a curse, and you have rent your”", ["inhabitants", "thirty-one", "brought", "buying"], 19),
    word(1, "In verse 19, what word completes this phrase: “LORD, when you heard how I spoke against this place, and against its _____, that they should become a desolation and a curse, and you have rent your”?", "inhabitants", 19, ["inhabitants"]),
    tf(2, "The RSV states: “because your heart was penitent, and you humbled yourself before the LORD, when you heard how I spoke against this place, and against its inhabitants, that they should become a desolation and a curse, and you have rent your clothes and wept before me, I also have heard you, says the LORD.”", true, 19),
    blank(3, "_____, behold, I will gather you to your fathers, and you shall be gathered", "Therefore", 20, ["therefore"]),
    mc(1, "Which word correctly completes this RSV wording: “_____, behold, I will gather you to your fathers, and you shall be gathered”", ["Therefore", "Josi’ah", "Ahi’kam", "Thus"], 20),
    word(2, "In verse 20, what word completes this phrase: “_____, behold, I will gather you to your fathers, and you shall be gathered”?", "Therefore", 20, ["therefore"]),
    tf(3, "The RSV does not state: “Therefore, behold, I will gather you to your fathers, and you shall be gathered to your grave in peace, and your eyes shall not see all the evil which I will bring upon this place.’\" And they brought back word to the king.”", false, 20, "The quoted wording is the RSV text of this verse."),
    blank(1, "Josi’ah was eight years old when he began to reign, and he reigned _____ years in Jerusalem. His mother’s name was Jedi’dah the daughter of Adai’ah", "thirty-one", 1, ["thirty-one"]),
    mc(2, "Select the missing RSV word: “And he did what was right in the eyes of the LORD, and _____ in all the way of David his father, and he did not turn aside to the right”", ["walked", "brought", "builders", "delivered"], 2),
    word(3, "What missing word belongs in this verse 3 clause: “In the _____ year of King Josi’ah, the king sent Shaphan the son of Azali’ah, son of”?", "eighteenth", 3, ["eighteenth"]),
    tf(1, "This wording appears in verse 4: “has been brought into the house of the LORD, which the keepers of the threshold have collected from the people;”", true, 4),
    blank(2, "and let them give it to the workmen who are at the house of the LORD, _____ the house,", "repairing", 5, ["repairing"]),
    mc(3, "Select the missing RSV word: “that is, to the carpenters, and to the _____, and to the masons, as well as for buying timber and quarried stone to”", ["builders", "wife", "burned", "thus"], 6),
    word(1, "What missing word belongs in this verse 7 clause: “But no accounting shall be asked from them for the money which is _____ into their hand, for they deal honestly.\"”?", "delivered", 7, ["delivered"]),
    tf(2, "This wording appears in verse 8: “And Hilki’ah the high priest said to Shaphan the secretary, \"I have found the book of the law in the house of the LORD.\" And Hilki’ah”", true, 8),
    blank(3, "And Shaphan the _____ came to the king, and reported to the king, \"Your servants have emptied", "secretary", 9, ["secretary"]),
    mc(1, "Select the missing RSV word: “Then Shaphan the _____ told the king, \"Hilki’ah the priest has given me a book.\" And Shaphan”", ["secretary", "hand", "amount", "repairing"], 10),
    word(2, "What missing word belongs in this verse 11 clause: “And when the king _____ the words of the book of the law, he rent his clothes.”?", "heard", 11, ["heard"]),
    tf(3, "This wording appears in verse 12: “And the king commanded Hilki’ah the priest, and Ahi’kam the son of Shaphan, and Achbor the son”", true, 12),
    blank(1, "\"Go, inquire of the LORD for me, and for the people, and for all Judah, _____ the words of this book that has been found; for great is the wrath of", "concerning", 13, ["concerning"]),
    mc(2, "Select the missing RSV word: “and Ahi’kam, and Achbor, and Shaphan, and Asai’ah went to Huldah the _____, the wife of Shallum the son of Tikvah, son of Harhas, keeper of the wardrobe”", ["prophetess", "mother’s", "reckon", "repairing"], 14),
    word(3, "What missing word belongs in this verse 15 clause: “And she _____ to them, \"Thus says the LORD, the God of Israel: `Tell the man who sent”?", "said", 15, ["said"]),
    tf(1, "This wording appears in verse 16: “says the LORD, Behold, I will bring evil upon this place and upon its inhabitants, all the words of the book which the king of Judah has read.”", true, 16),
    blank(2, "that they might provoke me to anger with all the work of their hands, _____ my wrath will be kindled against this place, and it will not be quenched.", "therefore", 17, ["therefore"]),
    mc(3, "Select the missing RSV word: “But as to the king of Judah, who sent you to _____ of the LORD, thus shall you say to him, Thus says the LORD, the God of”", ["inquire", "began", "turn", "high"], 18),
    word(1, "What missing word belongs in this verse 19 clause: “against this place, and against its inhabitants, that they should become a _____ and a curse, and you have rent your clothes and wept before me, I also”?", "desolation", 19, ["desolation"]),
    tf(2, "This wording appears in verse 20: “Therefore, behold, I will gather you to your fathers, and you shall be gathered to your grave in peace, and your eyes shall not see all the evil which”", true, 20),
    blank(3, "he began to reign, and he reigned thirty-one years in Jerusalem. His _____ name was Jedi’dah the daughter of Adai’ah of Bozkath.", "mother’s", 1, ["mothers"]),
    mc(1, "Select the missing RSV word: “right in the eyes of the LORD, and walked in all the way of David his _____, and he did not turn aside to the right hand or to the left.”", ["father", "timber", "found", "words"], 2),
    word(2, "What missing word belongs in this verse 3 clause: “Josi’ah, the king sent Shaphan the son of Azali’ah, son of Meshul’lam, the _____, to the house of the LORD, saying,”?", "secretary", 3, ["secretary"]),
    tf(3, "This wording appears in verse 4: “brought into the house of the LORD, which the keepers of the threshold have collected from the people;”", true, 4),
    blank(1, "and let it be given into the hand of the _____ who have the oversight of the house of the LORD; and let them give it", "workmen", 5, ["workmen"]),
    mc(2, "Select the missing RSV word: “to the builders, and to the masons, as well as for buying timber and _____ stone to repair the house.”", ["quarried", "might", "yourself", "grave"], 6),
    word(3, "What missing word belongs in this verse 7 clause: “them for the money which is delivered into their hand, for they deal _____.\"”?", "honestly", 7, ["honestly"]),
    tf(1, "This wording appears in verse 8: “And Hilki’ah the high priest said to Shaphan the secretary, \"I have found the book of the law in the house of the LORD.\"”", true, 8),
    blank(2, "servants have emptied out the money that was found in the house, and have _____ it into the hand of the workmen who have the oversight of the house of", "delivered", 9, ["delivered"]),
    mc(3, "Select the missing RSV word: “Then _____ the secretary told the king, \"Hilki’ah the priest has given me a book.\"”", ["Shaphan", "Josi’ah", "Achbor", "Israel"], 10),
    word(1, "What missing word belongs in this verse 11 clause: “And when the king heard the _____ of the book of the law, he rent his clothes.”?", "words", 11, ["words"]),
    tf(2, "This wording appears in verse 12: “Ahi’kam the son of Shaphan, and Achbor the son of Micai’ah, and Shaphan the secretary, and Asai’ah the king’s servant, saying,”", true, 12),
    blank(3, "us, because our fathers have not obeyed the words of this book, to do _____ to all that is written concerning us.\"", "according", 13, ["according"]),
    mc(1, "Select the missing RSV word: “So _____ the priest, and Ahi’kam, and Achbor, and Shaphan, and Asai’ah went to”", ["Hilki’ah", "Josi’ah", "Achbor", "Israel"], 14),
    word(2, "What missing word belongs in this verse 15 clause: “And she said to them, \"_____ says the LORD, the God of Israel: `Tell the man who sent you to me,”?", "Thus", 15, ["thus"]),
    tf(3, "This wording appears in verse 16: “Thus says the LORD, Behold, I will bring evil upon this place and upon its inhabitants, all the words of the book”", true, 16),
    blank(1, "Because they have _____ me and have burned incense to other gods, that they might provoke me to", "forsaken", 17, ["forsaken"]),
    mc(2, "Select the missing RSV word: “of the LORD, thus shall you say to him, Thus says the LORD, the God of _____: Regarding the words which you have heard,”", ["Israel", "Josi’ah", "Ahi’kam", "Thus"], 18),
    word(3, "What missing word belongs in this verse 19 clause: “because your heart was _____, and you humbled yourself before the LORD, when you heard how I spoke”?", "penitent", 19, ["penitent"]),
    tf(1, "This wording appears in verse 20: “Therefore, behold, I will gather you to your fathers, and you shall be gathered to your grave in peace, and your eyes shall”", true, 20),
    mc(1, "How old was Josiah when he became king?", ["Eight years old", "Twelve years old", "Seven years old", "Twenty years old"], 1),
    mc(2, "What did Hilkiah find, and how did Josiah react when its words were read?", ["The book of the law; Josiah rent his clothes", "The royal chronicles; Josiah called a feast", "A hidden prophecy; Josiah left Jerusalem", "The temple plans; Josiah began repairs"], 11),
    mc(3, "Which prophetess did Josiah’s officials consult?", ["Huldah, wife of Shallum, keeper of the wardrobe, in Jerusalem’s Second Quarter", "Jezebel, daughter of Ethbaal", "The Shunammite woman", "Deborah, wife of Lappidoth"], 14),
  ],
};

export default bank;
