// 2 Kings 1 — quiz bank (RSV). Four verse-anchored forms per verse.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: "2 Kings",
  chapter: 1,
  tag: "quiz-v2-2kings-1",
  rows: [
    blank(2, "After the death of Ahab, Moab rebelled against _____.", "Israel", 1, ["israel"]),
    mc(3, "Which word correctly completes this RSV wording: “After the death of Ahab, Moab rebelled against _____.”", ["Israel", "Tishbite", "Kings", "Therefore"], 1),
    word(1, "In verse 1, what word completes this phrase: “After the death of Ahab, Moab rebelled against _____.”?", "Israel", 1, ["israel"]),
    tf(2, "The RSV states: “After the death of Ahab, Moab rebelled against Israel.”", true, 1),
    blank(3, "Sama’ria, and lay sick; so he sent messengers, telling them, \"Go, inquire of _____, the god of Ekron, whether I shall recover from this sickness.\"", "Ba’al-ze’bub", 2, ["baal-zebub"]),
    mc(1, "Which word correctly completes this RSV wording: “Sama’ria, and lay sick; so he sent messengers, telling them, \"Go, inquire of _____, the god of Ekron, whether I shall recover from this sickness.\"”", ["Ba’al-ze’bub", "Because", "Jehosh’aphat", "Ahazi’ah"], 2),
    word(2, "In verse 2, what word completes this phrase: “Sama’ria, and lay sick; so he sent messengers, telling them, \"Go, inquire of _____, the god of Ekron, whether I shall recover from this sickness.\"”?", "Ba’al-ze’bub", 2, ["baal-zebub"]),
    tf(3, "The RSV does not state: “Now Ahazi’ah fell through the lattice in his upper chamber in Sama’ria, and lay sick; so he sent messengers, telling them, \"Go, inquire of Ba’al-ze’bub, the god of Ekron, whether I shall recover from this sickness.\"”", false, 2, "The quoted wording is the RSV text of this verse."),
    blank(1, "it because there is no God in Israel that you are going to inquire of _____, the god of Ekron?’", "Ba’al-ze’bub", 3, ["baal-zebub"]),
    mc(2, "Which word correctly completes this RSV wording: “it because there is no God in Israel that you are going to inquire of _____, the god of Ekron?’”", ["Ba’al-ze’bub", "Tishbite", "Because", "Jehosh’aphat"], 3),
    word(3, "In verse 3, what word completes this phrase: “it because there is no God in Israel that you are going to inquire of _____, the god of Ekron?’”?", "Ba’al-ze’bub", 3, ["baal-zebub"]),
    tf(1, "The RSV states: “But the angel of the LORD said to Eli’jah the Tishbite, \"Arise, go up to meet the messengers of the king of Sama’ria, and say to them, `Is it because there is no God in Israel that you are going to inquire of Ba’al-ze’bub, the god of Ekron?’”", true, 3),
    blank(2, "down from the bed to which you have gone, but you shall surely die.’\" So _____ went.", "Eli’jah", 4, ["elijah"]),
    mc(3, "Which word correctly completes this RSV wording: “down from the bed to which you have gone, but you shall surely die.’\" So _____ went.”", ["Eli’jah", "Ekron", "Book", "Tishbite"], 4),
    word(1, "In verse 4, what word completes this phrase: “down from the bed to which you have gone, but you shall surely die.’\" So _____ went.”?", "Eli’jah", 4, ["elijah"]),
    tf(2, "The RSV does not state: “Now therefore thus says the LORD, `You shall not come down from the bed to which you have gone, but you shall surely die.’\" So Eli’jah went.”", false, 4, "The quoted wording is the RSV text of this verse."),
    blank(3, "The _____ returned to the king, and he said to them, \"Why have you returned?\"", "messengers", 5, ["messengers"]),
    mc(1, "Which word correctly completes this RSV wording: “The _____ returned to the king, and he said to them, \"Why have you returned?\"”", ["messengers", "order", "captains", "death"], 5),
    word(2, "In verse 5, what word completes this phrase: “The _____ returned to the king, and he said to them, \"Why have you returned?\"”?", "messengers", 5, ["messengers"]),
    tf(3, "The RSV states: “The messengers returned to the king, and he said to them, \"Why have you returned?\"”", true, 5),
    blank(1, "because there is no God in Israel that you are sending to inquire of _____, the god of Ekron? Therefore you shall not come down from the bed to which", "Ba’al-ze’bub", 6, ["baal-zebub"]),
    mc(2, "Which word correctly completes this RSV wording: “because there is no God in Israel that you are sending to inquire of _____, the god of Ekron? Therefore you shall not come down from the bed to which”", ["Ba’al-ze’bub", "Jeho’ram", "Chronicles", "Sama’ria"], 6),
    word(3, "In verse 6, what word completes this phrase: “because there is no God in Israel that you are sending to inquire of _____, the god of Ekron? Therefore you shall not come down from the bed to which”?", "Ba’al-ze’bub", 6, ["baal-zebub"]),
    tf(1, "The RSV does not state: “And they said to him, \"There came a man to meet us, and said to us, `Go back to the king who sent you, and say to him, Thus says the LORD, Is it because there is no God in Israel that you are sending to inquire of Ba’al-ze’bub, the god of Ekron? Therefore you shall not come down from the bed to which you have gone, but shall surely die.’\"”", false, 6, "The quoted wording is the RSV text of this verse."),
    blank(2, "them, \"What kind of man was he who came to meet you and told you these _____?\"", "things", 7, ["things"]),
    mc(3, "Which word correctly completes this RSV wording: “them, \"What kind of man was he who came to meet you and told you these _____?\"”", ["things", "heaven", "pray", "word"], 7),
    word(1, "In verse 7, what word completes this phrase: “them, \"What kind of man was he who came to meet you and told you these _____?\"”?", "things", 7, ["things"]),
    tf(2, "The RSV states: “He said to them, \"What kind of man was he who came to meet you and told you these things?\"”", true, 7),
    blank(3, "a girdle of leather about his loins.\" And he said, \"It is Eli’jah the _____.\"", "Tishbite", 8, ["tishbite"]),
    mc(1, "Which word correctly completes this RSV wording: “a girdle of leather about his loins.\" And he said, \"It is Eli’jah the _____.\"”", ["Tishbite", "Because", "Ahazi’ah", "Jeho’ram"], 8),
    word(2, "In verse 8, what word completes this phrase: “a girdle of leather about his loins.\" And he said, \"It is Eli’jah the _____.\"”?", "Tishbite", 8, ["tishbite"]),
    tf(3, "The RSV does not state: “They answered him, \"He wore a garment of haircloth, with a girdle of leather about his loins.\" And he said, \"It is Eli’jah the Tishbite.\"”", false, 8, "The quoted wording is the RSV text of this verse."),
    blank(1, "king sent to him a captain of fifty men with his fifty. He went up to _____, who was sitting on the top of a hill, and said to him, \"O man of God,", "Eli’jah", 9, ["elijah"]),
    mc(2, "Which word correctly completes this RSV wording: “king sent to him a captain of fifty men with his fifty. He went up to _____, who was sitting on the top of a hill, and said to him, \"O man of God,”", ["Eli’jah", "After", "Therefore", "Ahab"], 9),
    word(3, "In verse 9, what word completes this phrase: “king sent to him a captain of fifty men with his fifty. He went up to _____, who was sitting on the top of a hill, and said to him, \"O man of God,”?", "Eli’jah", 9, ["elijah"]),
    tf(1, "The RSV states: “Then the king sent to him a captain of fifty men with his fifty. He went up to Eli’jah, who was sitting on the top of a hill, and said to him, \"O man of God, the king says, `Come down.’\"”", true, 9),
    blank(2, "But _____ answered the captain of fifty, \"If I am a man of God, let fire come down", "Eli’jah", 10, ["elijah"]),
    mc(3, "Which word correctly completes this RSV wording: “But _____ answered the captain of fifty, \"If I am a man of God, let fire come down”", ["Eli’jah", "Ekron", "Book", "Tishbite"], 10),
    word(1, "In verse 10, what word completes this phrase: “But _____ answered the captain of fifty, \"If I am a man of God, let fire come down”?", "Eli’jah", 10, ["elijah"]),
    tf(2, "The RSV does not state: “But Eli’jah answered the captain of fifty, \"If I am a man of God, let fire come down from heaven and consume you and your fifty.\" Then fire came down from heaven, and consumed him and his fifty.”", false, 10, "The quoted wording is the RSV text of this verse."),
    blank(3, "_____ the king sent to him another captain of fifty men with his fifty. And", "Again", 11, ["again"]),
    mc(1, "Which word correctly completes this RSV wording: “_____ the king sent to him another captain of fifty men with his fifty. And”", ["Again", "Ahab", "Come", "Ahazi’ah"], 11),
    word(2, "In verse 11, what word completes this phrase: “_____ the king sent to him another captain of fifty men with his fifty. And”?", "Again", 11, ["again"]),
    tf(3, "The RSV states: “Again the king sent to him another captain of fifty men with his fifty. And he went up and said to him, \"O man of God, this is the king’s order, `Come down quickly!’\"”", true, 11),
    blank(1, "But _____ answered them, \"If I am a man of God, let fire come down from heaven and", "Eli’jah", 12, ["elijah"]),
    mc(2, "Which word correctly completes this RSV wording: “But _____ answered them, \"If I am a man of God, let fire come down from heaven and”", ["Eli’jah", "After", "Therefore", "Ahab"], 12),
    word(3, "In verse 12, what word completes this phrase: “But _____ answered them, \"If I am a man of God, let fire come down from heaven and”?", "Eli’jah", 12, ["elijah"]),
    tf(1, "The RSV does not state: “But Eli’jah answered them, \"If I am a man of God, let fire come down from heaven and consume you and your fifty.\" Then the fire of God came down from heaven and consumed him and his fifty.”", false, 12, "The quoted wording is the RSV text of this verse."),
    blank(2, "third captain of fifty went up, and came and fell on his knees before _____, and entreated him, \"O man of God, I pray you, let my life, and the life", "Eli’jah", 13, ["elijah"]),
    mc(3, "Which word correctly completes this RSV wording: “third captain of fifty went up, and came and fell on his knees before _____, and entreated him, \"O man of God, I pray you, let my life, and the life”", ["Eli’jah", "Ekron", "Book", "Tishbite"], 13),
    word(1, "In verse 13, what word completes this phrase: “third captain of fifty went up, and came and fell on his knees before _____, and entreated him, \"O man of God, I pray you, let my life, and the life”?", "Eli’jah", 13, ["elijah"]),
    tf(2, "The RSV states: “Again the king sent the captain of a third fifty with his fifty. And the third captain of fifty went up, and came and fell on his knees before Eli’jah, and entreated him, \"O man of God, I pray you, let my life, and the life of these fifty servants of yours, be precious in your sight.”", true, 13),
    blank(3, "Lo, fire came down from heaven, and _____ the two former captains of fifty men with their fifties; but now let my", "consumed", 14, ["consumed"]),
    mc(1, "Which word correctly completes this RSV wording: “Lo, fire came down from heaven, and _____ the two former captains of fifty men with their fifties; but now let my”", ["consumed", "sickness", "down", "answered"], 14),
    word(2, "In verse 14, what word completes this phrase: “Lo, fire came down from heaven, and _____ the two former captains of fifty men with their fifties; but now let my”?", "consumed", 14, ["consumed"]),
    tf(3, "The RSV does not state: “Lo, fire came down from heaven, and consumed the two former captains of fifty men with their fifties; but now let my life be precious in your sight.\"”", false, 14, "The quoted wording is the RSV text of this verse."),
    blank(1, "Then the angel of the LORD said to _____, \"Go down with him; do not be afraid of him.\" So he arose and went down", "Eli’jah", 15, ["elijah"]),
    mc(2, "Which word correctly completes this RSV wording: “Then the angel of the LORD said to _____, \"Go down with him; do not be afraid of him.\" So he arose and went down”", ["Eli’jah", "After", "Therefore", "Ahab"], 15),
    word(3, "In verse 15, what word completes this phrase: “Then the angel of the LORD said to _____, \"Go down with him; do not be afraid of him.\" So he arose and went down”?", "Eli’jah", 15, ["elijah"]),
    tf(1, "The RSV states: “Then the angel of the LORD said to Eli’jah, \"Go down with him; do not be afraid of him.\" So he arose and went down with him to the king,”", true, 15),
    blank(2, "\"Thus says the LORD, `Because you have sent messengers to inquire of _____, the god of Ekron, -- is it because there is no God in Israel to inquire", "Ba’al-ze’bub", 16, ["baal-zebub"]),
    mc(3, "Which word correctly completes this RSV wording: “\"Thus says the LORD, `Because you have sent messengers to inquire of _____, the god of Ekron, -- is it because there is no God in Israel to inquire”", ["Ba’al-ze’bub", "Therefore", "Jeho’ram", "Chronicles"], 16),
    word(1, "In verse 16, what word completes this phrase: “\"Thus says the LORD, `Because you have sent messengers to inquire of _____, the god of Ekron, -- is it because there is no God in Israel to inquire”?", "Ba’al-ze’bub", 16, ["baal-zebub"]),
    tf(2, "The RSV does not state: “and said to him, \"Thus says the LORD, `Because you have sent messengers to inquire of Ba’al-ze’bub, the god of Ekron, -- is it because there is no God in Israel to inquire of his word? -- therefore you shall not come down from the bed to which you have gone, but you shall surely die.’\"”", false, 16, "The quoted wording is the RSV text of this verse."),
    blank(3, "brother, became king in his stead in the second year of Jeho’ram the son of _____, king of Judah, because Ahazi’ah had no son.", "Jehosh’aphat", 17, ["jehoshaphat"]),
    mc(1, "Which word correctly completes this RSV wording: “brother, became king in his stead in the second year of Jeho’ram the son of _____, king of Judah, because Ahazi’ah had no son.”", ["Jehosh’aphat", "Ba’al-ze’bub", "Tishbite", "Because"], 17),
    word(2, "In verse 17, what word completes this phrase: “brother, became king in his stead in the second year of Jeho’ram the son of _____, king of Judah, because Ahazi’ah had no son.”?", "Jehosh’aphat", 17, ["jehoshaphat"]),
    tf(3, "The RSV states: “So he died according to the word of the LORD which Eli’jah had spoken. Jeho’ram, his brother, became king in his stead in the second year of Jeho’ram the son of Jehosh’aphat, king of Judah, because Ahazi’ah had no son.”", true, 17),
    blank(1, "acts of Ahazi’ah which he did, are they not written in the Book of the _____ of the Kings of Israel?", "Chronicles", 18, ["chronicles"]),
    mc(2, "Which word correctly completes this RSV wording: “acts of Ahazi’ah which he did, are they not written in the Book of the _____ of the Kings of Israel?”", ["Chronicles", "Judah", "Therefore", "Ba’al-ze’bub"], 18),
    word(3, "In verse 18, what word completes this phrase: “acts of Ahazi’ah which he did, are they not written in the Book of the _____ of the Kings of Israel?”?", "Chronicles", 18, ["chronicles"]),
    tf(1, "The RSV does not state: “Now the rest of the acts of Ahazi’ah which he did, are they not written in the Book of the Chronicles of the Kings of Israel?”", false, 18, "The quoted wording is the RSV text of this verse."),
    blank(1, "After the death of Ahab, Moab _____ against Israel.", "rebelled", 1, ["rebelled"]),
    mc(2, "Select the missing RSV word: “the lattice in his upper chamber in Sama’ria, and lay sick; so he sent _____, telling them, \"Go, inquire of Ba’al-ze’bub, the god of Ekron, whether”", ["messengers", "fifty", "before", "according"], 2),
    word(3, "What missing word belongs in this verse 3 clause: “angel of the LORD said to Eli’jah the Tishbite, \"Arise, go up to meet the _____ of the king of Sama’ria, and say to them, `Is it because there is no God”?", "messengers", 3, ["messengers"]),
    tf(1, "This wording appears in verse 4: “Now therefore thus says the LORD, `You shall not come down from the bed to which you”", true, 4),
    blank(2, "The messengers _____ to the king, and he said to them, \"Why have you returned?\"", "returned", 5, ["returned"]),
    mc(3, "Select the missing RSV word: “Israel that you are sending to inquire of Ba’al-ze’bub, the god of Ekron? _____ you shall not come down from the bed to which you have gone, but shall”", ["Therefore", "After", "Thus", "Ahab"], 6),
    word(1, "What missing word belongs in this verse 7 clause: “He _____ to them, \"What kind of man was he who came to meet you and told you these”?", "said", 7, ["said"]),
    tf(2, "This wording appears in verse 8: “They answered him, \"He wore a garment of haircloth, with a girdle of leather about his loins.\" And he said, \"It is Eli’jah”", true, 8),
    blank(3, "Then the king sent to him a _____ of fifty men with his fifty. He went up to Eli’jah, who was sitting on", "captain", 9, ["captain"]),
    mc(1, "Select the missing RSV word: “But Eli’jah _____ the captain of fifty, \"If I am a man of God, let fire come down from heaven”", ["answered", "knees", "fifties", "year"], 10),
    word(2, "What missing word belongs in this verse 11 clause: “Again the king sent to him _____ captain of fifty men with his fifty. And he went up and said to him, \"O”?", "another", 11, ["another"]),
    tf(3, "This wording appears in verse 12: “But Eli’jah answered them, \"If I am a man of God, let fire come down from heaven and consume”", true, 12),
    blank(1, "of fifty went up, and came and fell on his knees before Eli’jah, and _____ him, \"O man of God, I pray you, let my life, and the life of these fifty", "entreated", 13, ["entreated"]),
    mc(2, "Select the missing RSV word: “Lo, fire came down from heaven, and consumed the two former _____ of fifty men with their fifties; but now let my life be precious in your”", ["captains", "returned", "girdle", "consumed"], 14),
    word(3, "What missing word belongs in this verse 15 clause: “Then the angel of the LORD said to Eli’jah, \"Go down with him; do not be _____ of him.\" So he arose and went down with him to the king,”?", "afraid", 15, ["afraid"]),
    tf(1, "This wording appears in verse 16: “and said to him, \"Thus says the LORD, `Because you have sent messengers to inquire of Ba’al-ze’bub, the god of Ekron, -- is it because there is”", true, 16),
    blank(2, "So he died _____ to the word of the LORD which Eli’jah had spoken. Jeho’ram, his brother,", "according", 17, ["according"]),
    mc(3, "Select the missing RSV word: “Now the rest of the acts of _____ which he did, are they not written in the Book of the Chronicles of the”", ["Ahazi’ah", "After", "Therefore", "Ahab"], 18),
    word(1, "What missing word belongs in this verse 1 clause: “After the death of Ahab, Moab rebelled _____ Israel.”?", "against", 1, ["against"]),
    tf(2, "This wording appears in verse 2: “Now Ahazi’ah fell through the lattice in his upper chamber in Sama’ria, and lay sick;”", true, 2),
    blank(3, "But the angel of the LORD said to Eli’jah the _____, \"Arise, go up to meet the messengers of the king of Sama’ria, and say", "Tishbite", 3, ["tishbite"]),
    mc(1, "Select the missing RSV word: “shall not come down from the bed to which you have gone, but you shall _____ die.’\" So Eli’jah went.”", ["surely", "angel", "gone", "garment"], 4),
    word(2, "What missing word belongs in this verse 5 clause: “The messengers returned to the _____, and he said to them, \"Why have you returned?\"”?", "king", 5, ["king"]),
    tf(3, "This wording appears in verse 6: “back to the king who sent you, and say to him, Thus says the LORD, Is it because there is no God in Israel that you are sending to inquire of Ba’al-ze’bub,”", true, 6),
    blank(1, "He said to them, \"What _____ of man was he who came to meet you and told you these things?\"", "kind", 7, ["kind"]),
    mc(2, "Select the missing RSV word: “They _____ him, \"He wore a garment of haircloth, with a girdle of leather about his”", ["answered", "died", "death", "inquire"], 8),
    word(3, "What missing word belongs in this verse 9 clause: “a captain of fifty men with his fifty. He went up to Eli’jah, who was _____ on the top of a hill, and said to him, \"O man of God, the king says, `Come”?", "sitting", 9, ["sitting"]),
    tf(1, "This wording appears in verse 10: “and consume you and your fifty.\" Then fire came down from heaven, and consumed him and his fifty.”", true, 10),
    blank(2, "Again the king sent to him another _____ of fifty men with his fifty. And he went up and said to him, \"O man of", "captain", 11, ["captain"]),
    mc(3, "Select the missing RSV word: “consume you and your fifty.\" Then the fire of God came down from heaven and _____ him and his fifty.”", ["consumed", "captain", "third", "captains"], 12),
    word(1, "What missing word belongs in this verse 13 clause: “him, \"O man of God, I pray you, let my life, and the life of these fifty _____ of yours, be precious in your sight.”?", "servants", 13, ["servants"]),
    tf(2, "This wording appears in verse 14: “former captains of fifty men with their fifties; but now let my life be precious in your sight.\"”", true, 14),
    blank(3, "Then the _____ of the LORD said to Eli’jah, \"Go down with him; do not be afraid of him.\"", "angel", 15, ["angel"]),
    mc(1, "Select the missing RSV word: “-- is it because there is no God in Israel to inquire of his word? -- _____ you shall not come down from the bed to which you have gone, but you shall”", ["therefore", "meet", "returned", "girdle"], 16),
    word(2, "What missing word belongs in this verse 17 clause: “So he died according to the word of the LORD which Eli’jah had spoken. _____, his brother, became king in his stead in the second year of Jeho’ram”?", "Jeho’ram", 17, ["jehoram"]),
    tf(3, "This wording appears in verse 18: “Now the rest of the acts of Ahazi’ah which he did, are they not written in the Book of the Chronicles of the Kings of Israel?”", true, 18),
    blank(1, "_____ the death of Ahab, Moab rebelled against Israel.", "After", 1, ["after"]),
    mc(2, "Select the missing RSV word: “Now Ahazi’ah fell through the lattice in his upper chamber in _____, and lay sick; so he sent messengers, telling them, \"Go, inquire of Ba’al-ze’bub,”", ["Sama’ria", "Eli’jah", "Book", "Tishbite"], 2),
    word(3, "What missing word belongs in this verse 3 clause: “Eli’jah the Tishbite, \"Arise, go up to meet the messengers of the king of _____, and say to them, `Is it because there is no God in Israel that you are”?", "Sama’ria", 3, ["samaria"]),
    tf(1, "This wording appears in verse 4: “Now therefore thus says the LORD, `You shall not come down from the bed to which you have gone, but you shall surely”", true, 4),
    blank(2, "The messengers returned to the king, and he _____ to them, \"Why have you returned?\"", "said", 5, ["said"]),
    mc(3, "Select the missing RSV word: “Thus says the LORD, Is it because there is no God in Israel that you are _____ to inquire of Ba’al-ze’bub, the god of Ekron? Therefore you shall not”", ["sending", "lattice", "sickness", "down"], 6),
    word(1, "What missing word belongs in this verse 7 clause: “He said to them, \"What kind of man was he who _____ to meet you and told you these things?\"”?", "came", 7, ["came"]),
    tf(2, "This wording appears in verse 8: “They answered him, \"He wore a garment of haircloth, with a girdle of leather about his loins.\" And he said,”", true, 8),
    blank(3, "Then the king sent to him a captain of _____ men with his fifty. He went up to Eli’jah, who was sitting on the top", "fifty", 9, ["fifty"]),
    mc(1, "Select the missing RSV word: “But Eli’jah answered the _____ of fifty, \"If I am a man of God, let fire come down from heaven and consume”", ["captain", "pray", "word", "written"], 10),
    word(2, "What missing word belongs in this verse 11 clause: “and said to him, \"O man of God, this is the king’s order, `Come down _____!’\"”?", "quickly", 11, ["quickly"]),
    tf(3, "This wording appears in verse 12: “answered them, \"If I am a man of God, let fire come down from heaven and consume you and your fifty.\" Then the fire of God came down from heaven and consumed”", true, 12),
    mc(1, "How was Ahaziah injured, and which god did he send messengers to consult?", ["He fell through an upper-room lattice and sent to Baal-zebub of Ekron", "He was wounded in battle and sent to Chemosh", "He fell from a chariot and sent to Baal of Samaria", "He became sick and sent to Ashtoreth of Sidon"], 2),
    mc(2, "From the messengers’ description, how did Ahaziah identify Elijah?", ["He wore a garment of haircloth with a leather girdle", "He carried a staff and wore linen", "He wore a royal mantle", "He had a scar on his hand"], 8),
    mc(3, "What happened to the three captains of fifty sent to Elijah?", ["Fire consumed the first two groups; the third captain knelt and begged for his life", "All three groups were consumed by fire", "The first captain arrested Elijah and the others fled", "The first two knelt, but the third was consumed"], 14),
  ],
};

export default bank;
