// 2 Kings 17 — quiz bank (RSV). Four verse-anchored forms per verse.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: "2 Kings",
  chapter: 17,
  tag: "quiz-v2-2kings-17",
  rows: [
    blank(2, "year of Ahaz king of Judah Hoshe’a the son of Elah began to reign in _____ over Israel, and he reigned nine years.", "Sama’ria", 1, ["samaria"]),
    mc(3, "Which word correctly completes this RSV wording: “year of Ahaz king of Judah Hoshe’a the son of Elah began to reign in _____ over Israel, and he reigned nine years.”", ["Sama’ria", "Assyria", "Ba’al", "Bethel"], 1),
    word(1, "In verse 1, what word completes this phrase: “year of Ahaz king of Judah Hoshe’a the son of Elah began to reign in _____ over Israel, and he reigned nine years.”?", "Sama’ria", 1, ["samaria"]),
    tf(2, "The RSV states: “In the twelfth year of Ahaz king of Judah Hoshe’a the son of Elah began to reign in Sama’ria over Israel, and he reigned nine years.”", true, 1),
    blank(3, "he did what was evil in the sight of the LORD, yet not as the kings of _____ who were before him.", "Israel", 2, ["israel"]),
    mc(1, "Which word correctly completes this RSV wording: “he did what was evil in the sight of the LORD, yet not as the kings of _____ who were before him.”", ["Israel", "Ashe’rim", "Hamath", "Jacob"], 2),
    word(2, "In verse 2, what word completes this phrase: “he did what was evil in the sight of the LORD, yet not as the kings of _____ who were before him.”?", "Israel", 2, ["israel"]),
    tf(3, "The RSV does not state: “And he did what was evil in the sight of the LORD, yet not as the kings of Israel who were before him.”", false, 2, "The quoted wording is the RSV text of this verse."),
    blank(1, "Against him came up _____ king of Assyria; and Hoshe’a became his vassal, and paid him tribute.", "Shalmane’ser", 3, ["shalmaneser"]),
    mc(2, "Which word correctly completes this RSV wording: “Against him came up _____ king of Assyria; and Hoshe’a became his vassal, and paid him tribute.”", ["Shalmane’ser", "Sama’ria", "Samaritans", "Assyria"], 3),
    word(3, "In verse 3, what word completes this phrase: “Against him came up _____ king of Assyria; and Hoshe’a became his vassal, and paid him tribute.”?", "Shalmane’ser", 3, ["shalmaneser"]),
    tf(1, "The RSV states: “Against him came up Shalmane’ser king of Assyria; and Hoshe’a became his vassal, and paid him tribute.”", true, 3),
    blank(2, "But the king of _____ found treachery in Hoshe’a; for he had sent messengers to So, king of", "Assyria", 4, ["assyria"]),
    mc(3, "Which word correctly completes this RSV wording: “But the king of _____ found treachery in Hoshe’a; for he had sent messengers to So, king of”", ["Assyria", "Send", "Anam’melech", "Egypt"], 4),
    word(1, "In verse 4, what word completes this phrase: “But the king of _____ found treachery in Hoshe’a; for he had sent messengers to So, king of”?", "Assyria", 4, ["assyria"]),
    tf(2, "The RSV does not state: “But the king of Assyria found treachery in Hoshe’a; for he had sent messengers to So, king of Egypt, and offered no tribute to the king of Assyria, as he had done year by year; therefore the king of Assyria shut him up, and bound him in prison.”", false, 4, "The quoted wording is the RSV text of this verse."),
    blank(3, "Then the king of Assyria invaded all the land and came to _____, and for three years he besieged it.", "Sama’ria", 5, ["samaria"]),
    mc(1, "Which word correctly completes this RSV wording: “Then the king of Assyria invaded all the land and came to _____, and for three years he besieged it.”", ["Sama’ria", "Nibhaz", "Israel", "Ashe’rim"], 5),
    word(2, "In verse 5, what word completes this phrase: “Then the king of Assyria invaded all the land and came to _____, and for three years he besieged it.”?", "Sama’ria", 5, ["samaria"]),
    tf(3, "The RSV states: “Then the king of Assyria invaded all the land and came to Sama’ria, and for three years he besieged it.”", true, 5),
    blank(1, "of Hoshe’a the king of Assyria captured Sama’ria, and he carried the _____ away to Assyria, and placed them in Halah, and on the Habor, the river", "Israelites", 6, ["israelites"]),
    mc(2, "Which word correctly completes this RSV wording: “of Hoshe’a the king of Assyria captured Sama’ria, and he carried the _____ away to Assyria, and placed them in Halah, and on the Habor, the river”", ["Israelites", "Assyria", "David", "Av’vites"], 6),
    word(3, "In verse 6, what word completes this phrase: “of Hoshe’a the king of Assyria captured Sama’ria, and he carried the _____ away to Assyria, and placed them in Halah, and on the Habor, the river”?", "Israelites", 6, ["israelites"]),
    tf(1, "The RSV does not state: “In the ninth year of Hoshe’a the king of Assyria captured Sama’ria, and he carried the Israelites away to Assyria, and placed them in Halah, and on the Habor, the river of Gozan, and in the cities of the Medes.”", false, 6, "The quoted wording is the RSV text of this verse."),
    blank(2, "who had brought them up out of the land of Egypt from under the hand of _____ king of Egypt, and had feared other gods", "Pharaoh", 7, ["pharaoh"]),
    mc(3, "Which word correctly completes this RSV wording: “who had brought them up out of the land of Egypt from under the hand of _____ king of Egypt, and had feared other gods”", ["Pharaoh", "Shalmane’ser", "Ba’al", "Bethel"], 7),
    word(1, "In verse 7, what word completes this phrase: “who had brought them up out of the land of Egypt from under the hand of _____ king of Egypt, and had feared other gods”?", "Pharaoh", 7, ["pharaoh"]),
    tf(2, "The RSV states: “And this was so, because the people of Israel had sinned against the LORD their God, who had brought them up out of the land of Egypt from under the hand of Pharaoh king of Egypt, and had feared other gods”", true, 7),
    blank(3, "the customs of the nations whom the LORD drove out before the people of _____, and in the customs which the kings of Israel had introduced.", "Israel", 8, ["israel"]),
    mc(1, "Which word correctly completes this RSV wording: “the customs of the nations whom the LORD drove out before the people of _____, and in the customs which the kings of Israel had introduced.”", ["Israel", "Therefore", "Cuth", "Hoshe’a"], 8),
    word(2, "In verse 8, what word completes this phrase: “the customs of the nations whom the LORD drove out before the people of _____, and in the customs which the kings of Israel had introduced.”?", "Israel", 8, ["israel"]),
    tf(3, "The RSV does not state: “and walked in the customs of the nations whom the LORD drove out before the people of Israel, and in the customs which the kings of Israel had introduced.”", false, 8, "The quoted wording is the RSV text of this verse."),
    blank(1, "And the people of _____ did secretly against the LORD their God things that were not right. They", "Israel", 9, ["israel"]),
    mc(2, "Which word correctly completes this RSV wording: “And the people of _____ did secretly against the LORD their God things that were not right. They”", ["Israel", "Hamath", "Jacob", "Halah"], 9),
    word(3, "In verse 9, what word completes this phrase: “And the people of _____ did secretly against the LORD their God things that were not right. They”?", "Israel", 9, ["israel"]),
    tf(1, "The RSV states: “And the people of Israel did secretly against the LORD their God things that were not right. They built for themselves high places at all their towns, from watchtower to fortified city;”", true, 9),
    blank(2, "they set up for themselves pillars and _____ on every high hill and under every green tree;", "Ashe’rim", 10, ["asherim"]),
    mc(3, "Which word correctly completes this RSV wording: “they set up for themselves pillars and _____ on every high hill and under every green tree;”", ["Ashe’rim", "Send", "Anam’melech", "Assyria"], 10),
    word(1, "In verse 10, what word completes this phrase: “they set up for themselves pillars and _____ on every high hill and under every green tree;”?", "Ashe’rim", 10, ["asherim"]),
    tf(2, "The RSV does not state: “they set up for themselves pillars and Ashe’rim on every high hill and under every green tree;”", false, 10, "The quoted wording is the RSV text of this verse."),
    blank(3, "did whom the LORD carried away before them. And they did wicked things, _____ the LORD to anger,", "provoking", 11, ["provoking"]),
    mc(1, "Which word correctly completes this RSV wording: “did whom the LORD carried away before them. And they did wicked things, _____ the LORD to anger,”", ["provoking", "shall", "fathers", "went"], 11),
    word(2, "In verse 11, what word completes this phrase: “did whom the LORD carried away before them. And they did wicked things, _____ the LORD to anger,”?", "provoking", 11, ["provoking"]),
    tf(3, "The RSV states: “and there they burned incense on all the high places, as the nations did whom the LORD carried away before them. And they did wicked things, provoking the LORD to anger,”", true, 11),
    blank(1, "and they _____ idols, of which the LORD had said to them, \"You shall not do this.\"", "served", 12, ["served"]),
    mc(2, "Which word correctly completes this RSV wording: “and they _____ idols, of which the LORD had said to them, \"You shall not do this.\"”", ["served", "statutes", "made", "like"], 12),
    word(3, "In verse 12, what word completes this phrase: “and they _____ idols, of which the LORD had said to them, \"You shall not do this.\"”?", "served", 12, ["served"]),
    tf(1, "The RSV does not state: “and they served idols, of which the LORD had said to them, \"You shall not do this.\"”", false, 12, "The quoted wording is the RSV text of this verse."),
    blank(2, "Yet the LORD warned _____ and Judah by every prophet and every seer, saying, \"Turn from your evil", "Israel", 13, ["israel"]),
    mc(3, "Which word correctly completes this RSV wording: “Yet the LORD warned _____ and Judah by every prophet and every seer, saying, \"Turn from your evil”", ["Israel", "Turn", "Send", "However"], 13),
    word(1, "In verse 13, what word completes this phrase: “Yet the LORD warned _____ and Judah by every prophet and every seer, saying, \"Turn from your evil”?", "Israel", 13, ["israel"]),
    tf(2, "The RSV states: “Yet the LORD warned Israel and Judah by every prophet and every seer, saying, \"Turn from your evil ways and keep my commandments and my statutes, in accordance with all the law which I commanded your fathers, and which I sent to you by my servants the prophets.\"”", true, 13),
    blank(3, "But they would not listen, but were _____, as their fathers had been, who did not believe in the LORD their God.", "stubborn", 14, ["stubborn"]),
    mc(1, "Which word correctly completes this RSV wording: “But they would not listen, but were _____, as their fathers had been, who did not believe in the LORD their God.”", ["stubborn", "gave", "molten", "sorcery"], 14),
    word(2, "In verse 14, what word completes this phrase: “But they would not listen, but were _____, as their fathers had been, who did not believe in the LORD their God.”?", "stubborn", 14, ["stubborn"]),
    tf(3, "The RSV does not state: “But they would not listen, but were stubborn, as their fathers had been, who did not believe in the LORD their God.”", false, 14, "The quoted wording is the RSV text of this verse."),
    blank(1, "became false, and they followed the nations that were round about them, _____ whom the LORD had commanded them that they should not do like them.", "concerning", 15, ["concerning"]),
    mc(2, "Which word correctly completes this RSV wording: “became false, and they followed the nations that were round about them, _____ whom the LORD had commanded them that they should not do like them.”", ["concerning", "spoken", "killing", "sorts"], 15),
    word(3, "In verse 15, what word completes this phrase: “became false, and they followed the nations that were round about them, _____ whom the LORD had commanded them that they should not do like them.”?", "concerning", 15, ["concerning"]),
    tf(1, "The RSV states: “They despised his statutes, and his covenant that he made with their fathers, and the warnings which he gave them. They went after false idols, and became false, and they followed the nations that were round about them, concerning whom the LORD had commanded them that they should not do like them.”", true, 15),
    blank(2, "and made for themselves molten images of two calves; and they made an _____, and worshiped all the host of heaven, and served Ba’al.", "Ashe’rah", 16, ["asherah"]),
    mc(3, "Which word correctly completes this RSV wording: “and made for themselves molten images of two calves; and they made an _____, and worshiped all the host of heaven, and served Ba’al.”", ["Ashe’rah", "Send", "Anam’melech", "Assyria"], 16),
    word(1, "In verse 16, what word completes this phrase: “and made for themselves molten images of two calves; and they made an _____, and worshiped all the host of heaven, and served Ba’al.”?", "Ashe’rah", 16, ["asherah"]),
    tf(2, "The RSV does not state: “And they forsook all the commandments of the LORD their God, and made for themselves molten images of two calves; and they made an Ashe’rah, and worshiped all the host of heaven, and served Ba’al.”", false, 16, "The quoted wording is the RSV text of this verse."),
    blank(3, "And they burned their sons and their daughters as offerings, and used _____ and sorcery, and sold themselves to do evil in the sight of the LORD,", "divination", 17, ["divination"]),
    mc(1, "Which word correctly completes this RSV wording: “And they burned their sons and their daughters as offerings, and used _____ and sorcery, and sold themselves to do evil in the sight of the LORD,”", ["divination", "dwell", "according", "wrote"], 17),
    word(2, "In verse 17, what word completes this phrase: “And they burned their sons and their daughters as offerings, and used _____ and sorcery, and sold themselves to do evil in the sight of the LORD,”?", "divination", 17, ["divination"]),
    tf(3, "The RSV states: “And they burned their sons and their daughters as offerings, and used divination and sorcery, and sold themselves to do evil in the sight of the LORD, provoking him to anger.”", true, 17),
    blank(1, "_____ the LORD was very angry with Israel, and removed them out of his sight;", "Therefore", 18, ["therefore"]),
    mc(2, "Which word correctly completes this RSV wording: “_____ the LORD was very angry with Israel, and removed them out of his sight;”", ["Therefore", "Ahaz", "Halah", "Nebat"], 18),
    word(3, "In verse 18, what word completes this phrase: “_____ the LORD was very angry with Israel, and removed them out of his sight;”?", "Therefore", 18, ["therefore"]),
    tf(1, "The RSV does not state: “Therefore the LORD was very angry with Israel, and removed them out of his sight; none was left but the tribe of Judah only.”", false, 18, "The quoted wording is the RSV text of this verse."),
    blank(2, "the commandments of the LORD their God, but walked in the customs which _____ had introduced.", "Israel", 19, ["israel"]),
    mc(3, "Which word correctly completes this RSV wording: “the commandments of the LORD their God, but walked in the customs which _____ had introduced.”", ["Israel", "David", "Nergal", "Elah"], 19),
    word(1, "In verse 19, what word completes this phrase: “the commandments of the LORD their God, but walked in the customs which _____ had introduced.”?", "Israel", 19, ["israel"]),
    tf(2, "The RSV states: “ Judah also did not keep the commandments of the LORD their God, but walked in the customs which Israel had introduced.”", true, 19),
    blank(3, "And the LORD rejected all the descendants of _____, and afflicted them, and gave them into the hand of spoilers, until he", "Israel", 20, ["israel"]),
    mc(1, "Which word correctly completes this RSV wording: “And the LORD rejected all the descendants of _____, and afflicted them, and gave them into the hand of spoilers, until he”", ["Israel", "Send", "However", "Habor"], 20),
    word(2, "In verse 20, what word completes this phrase: “And the LORD rejected all the descendants of _____, and afflicted them, and gave them into the hand of spoilers, until he”?", "Israel", 20, ["israel"]),
    tf(3, "The RSV does not state: “And the LORD rejected all the descendants of Israel, and afflicted them, and gave them into the hand of spoilers, until he had cast them out of his sight.”", false, 20, "The quoted wording is the RSV text of this verse."),
    blank(1, "When he had torn Israel from the house of David they made _____ the son of Nebat king. And Jerobo’am drove Israel from following the LORD", "Jerobo’am", 21, ["jeroboam"]),
    mc(2, "Which word correctly completes this RSV wording: “When he had torn Israel from the house of David they made _____ the son of Nebat king. And Jerobo’am drove Israel from following the LORD”", ["Jerobo’am", "David", "Nergal", "Judah"], 21),
    word(3, "In verse 21, what word completes this phrase: “When he had torn Israel from the house of David they made _____ the son of Nebat king. And Jerobo’am drove Israel from following the LORD”?", "Jerobo’am", 21, ["jeroboam"]),
    tf(1, "The RSV states: “When he had torn Israel from the house of David they made Jerobo’am the son of Nebat king. And Jerobo’am drove Israel from following the LORD and made them commit great sin.”", true, 21),
    blank(2, "The people of Israel walked in all the sins which _____ did; they did not depart from them,", "Jerobo’am", 22, ["jeroboam"]),
    mc(3, "Which word correctly completes this RSV wording: “The people of Israel walked in all the sins which _____ did; they did not depart from them,”", ["Jerobo’am", "Send", "Anam’melech", "Assyria"], 22),
    word(1, "In verse 22, what word completes this phrase: “The people of Israel walked in all the sins which _____ did; they did not depart from them,”?", "Jerobo’am", 22, ["jeroboam"]),
    tf(2, "The RSV does not state: “The people of Israel walked in all the sins which Jerobo’am did; they did not depart from them,”", false, 22, "The quoted wording is the RSV text of this verse."),
    blank(3, "his servants the prophets. So Israel was exiled from their own land to _____ until this day.", "Assyria", 23, ["assyria"]),
    mc(1, "Which word correctly completes this RSV wording: “his servants the prophets. So Israel was exiled from their own land to _____ until this day.”", ["Assyria", "Nibhaz", "Sama’ria", "Ashe’rim"], 23),
    word(2, "In verse 23, what word completes this phrase: “his servants the prophets. So Israel was exiled from their own land to _____ until this day.”?", "Assyria", 23, ["assyria"]),
    tf(3, "The RSV states: “until the LORD removed Israel out of his sight, as he had spoken by all his servants the prophets. So Israel was exiled from their own land to Assyria until this day.”", true, 23),
    blank(1, "king of Assyria brought people from Babylon, Cuthah, Avva, Hamath, and _____, and placed them in the cities of Sama’ria instead of the people of Israel;", "Sephar-va’im", 24, ["sephar-vaim"]),
    mc(2, "Which word correctly completes this RSV wording: “king of Assyria brought people from Babylon, Cuthah, Avva, Hamath, and _____, and placed them in the cities of Sama’ria instead of the people of Israel;”", ["Sephar-va’im", "Ashe’rah", "However", "Jerobo’am"], 24),
    word(3, "In verse 24, what word completes this phrase: “king of Assyria brought people from Babylon, Cuthah, Avva, Hamath, and _____, and placed them in the cities of Sama’ria instead of the people of Israel;”?", "Sephar-va’im", 24, ["sephar-vaim"]),
    tf(1, "The RSV does not state: “And the king of Assyria brought people from Babylon, Cuthah, Avva, Hamath, and Sephar-va’im, and placed them in the cities of Sama’ria instead of the people of Israel; and they took possession of Sama’ria, and dwelt in its cities.”", false, 24, "The quoted wording is the RSV text of this verse."),
    blank(2, "And at the _____ of their dwelling there, they did not fear the LORD; therefore the LORD", "beginning", 25, ["beginning"]),
    mc(3, "Which word correctly completes this RSV wording: “And at the _____ of their dwelling there, they did not fear the LORD; therefore the LORD”", ["beginning", "former", "always", "began"], 25),
    word(1, "In verse 25, what word completes this phrase: “And at the _____ of their dwelling there, they did not fear the LORD; therefore the LORD”?", "beginning", 25, ["beginning"]),
    tf(2, "The RSV states: “And at the beginning of their dwelling there, they did not fear the LORD; therefore the LORD sent lions among them, which killed some of them.”", true, 25),
    blank(3, "\"The nations which you have carried away and placed in the cities of _____ do not know the law of the god of the land; therefore he has sent lions", "Sama’ria", 26, ["samaria"]),
    mc(1, "Which word correctly completes this RSV wording: “\"The nations which you have carried away and placed in the cities of _____ do not know the law of the god of the land; therefore he has sent lions”", ["Sama’ria", "Pharaoh", "Avva", "Tartak"], 26),
    word(2, "In verse 26, what word completes this phrase: “\"The nations which you have carried away and placed in the cities of _____ do not know the law of the god of the land; therefore he has sent lions”?", "Sama’ria", 26, ["samaria"]),
    tf(3, "The RSV does not state: “So the king of Assyria was told, \"The nations which you have carried away and placed in the cities of Sama’ria do not know the law of the god of the land; therefore he has sent lions among them, and behold, they are killing them, because they do not know the law of the god of the land.\"”", false, 26, "The quoted wording is the RSV text of this verse."),
    blank(1, "Then the king of _____ commanded, \"Send there one of the priests whom you carried away thence;", "Assyria", 27, ["assyria"]),
    mc(2, "Which word correctly completes this RSV wording: “Then the king of _____ commanded, \"Send there one of the priests whom you carried away thence;”", ["Assyria", "Jerobo’am", "Nergal", "Judah"], 27),
    word(3, "In verse 27, what word completes this phrase: “Then the king of _____ commanded, \"Send there one of the priests whom you carried away thence;”?", "Assyria", 27, ["assyria"]),
    tf(1, "The RSV states: “Then the king of Assyria commanded, \"Send there one of the priests whom you carried away thence; and let him go and dwell there, and teach them the law of the god of the land.\"”", true, 27),
    blank(2, "So one of the priests whom they had carried away from _____ came and dwelt in Bethel, and taught them how they should fear the LORD.", "Sama’ria", 28, ["samaria"]),
    mc(3, "Which word correctly completes this RSV wording: “So one of the priests whom they had carried away from _____ came and dwelt in Bethel, and taught them how they should fear the LORD.”", ["Sama’ria", "Send", "Anam’melech", "Egypt"], 28),
    word(1, "In verse 28, what word completes this phrase: “So one of the priests whom they had carried away from _____ came and dwelt in Bethel, and taught them how they should fear the LORD.”?", "Sama’ria", 28, ["samaria"]),
    tf(2, "The RSV does not state: “So one of the priests whom they had carried away from Sama’ria came and dwelt in Bethel, and taught them how they should fear the LORD.”", false, 28, "The quoted wording is the RSV text of this verse."),
    blank(3, "of its own, and put them in the shrines of the high places which the _____ had made, every nation in the cities in which they dwelt;", "Samaritans", 29, ["samaritans"]),
    mc(1, "Which word correctly completes this RSV wording: “of its own, and put them in the shrines of the high places which the _____ had made, every nation in the cities in which they dwelt;”", ["Samaritans", "Hamath", "Jacob", "Halah"], 29),
    word(2, "In verse 29, what word completes this phrase: “of its own, and put them in the shrines of the high places which the _____ had made, every nation in the cities in which they dwelt;”?", "Samaritans", 29, ["samaritans"]),
    tf(3, "The RSV states: “But every nation still made gods of its own, and put them in the shrines of the high places which the Samaritans had made, every nation in the cities in which they dwelt;”", true, 29),
    blank(1, "the men of Babylon made _____, the men of Cuth made Nergal, the men of Hamath made Ashi’ma,", "Suc’coth-be’noth", 30, ["succoth-benoth"]),
    mc(2, "Which word correctly completes this RSV wording: “the men of Babylon made _____, the men of Cuth made Nergal, the men of Hamath made Ashi’ma,”", ["Suc’coth-be’noth", "Shalmane’ser", "Sephar-va’im", "Sephar’vites"], 30),
    word(3, "In verse 30, what word completes this phrase: “the men of Babylon made _____, the men of Cuth made Nergal, the men of Hamath made Ashi’ma,”?", "Suc’coth-be’noth", 30, ["succoth-benoth"]),
    tf(1, "The RSV does not state: “the men of Babylon made Suc’coth-be’noth, the men of Cuth made Nergal, the men of Hamath made Ashi’ma,”", false, 30, "The quoted wording is the RSV text of this verse."),
    blank(2, "and the Av’vites made Nibhaz and Tartak; and the _____ burned their children in the fire to Adram’melech and Anam’melech, the", "Sephar’vites", 31, ["sepharvites"]),
    mc(3, "Which word correctly completes this RSV wording: “and the Av’vites made Nibhaz and Tartak; and the _____ burned their children in the fire to Adram’melech and Anam’melech, the”", ["Sephar’vites", "Adram’melech", "Ashe’rah", "However"], 31),
    word(1, "In verse 31, what word completes this phrase: “and the Av’vites made Nibhaz and Tartak; and the _____ burned their children in the fire to Adram’melech and Anam’melech, the”?", "Sephar’vites", 31, ["sepharvites"]),
    tf(2, "The RSV states: “and the Av’vites made Nibhaz and Tartak; and the Sephar’vites burned their children in the fire to Adram’melech and Anam’melech, the gods of Sephar-va’im.”", true, 31),
    blank(3, "They also feared the LORD, and appointed from among _____ all sorts of people as priests of the high places, who sacrificed for", "themselves", 32, ["themselves"]),
    mc(1, "Which word correctly completes this RSV wording: “They also feared the LORD, and appointed from among _____ all sorts of people as priests of the high places, who sacrificed for”", ["themselves", "warnings", "calves", "descendants"], 32),
    word(2, "In verse 32, what word completes this phrase: “They also feared the LORD, and appointed from among _____ all sorts of people as priests of the high places, who sacrificed for”?", "themselves", 32, ["themselves"]),
    tf(3, "The RSV does not state: “They also feared the LORD, and appointed from among themselves all sorts of people as priests of the high places, who sacrificed for them in the shrines of the high places.”", false, 32, "The quoted wording is the RSV text of this verse."),
    blank(1, "feared the LORD but also served their own gods, after the manner of the _____ from among whom they had been carried away.", "nations", 33, ["nations"]),
    mc(2, "Which word correctly completes this RSV wording: “feared the LORD but also served their own gods, after the manner of the _____ from among whom they had been carried away.”", ["nations", "river", "gods", "places"], 33),
    word(3, "In verse 33, what word completes this phrase: “feared the LORD but also served their own gods, after the manner of the _____ from among whom they had been carried away.”?", "nations", 33, ["nations"]),
    tf(1, "The RSV states: “So they feared the LORD but also served their own gods, after the manner of the nations from among whom they had been carried away.”", true, 33),
    blank(2, "commandment which the LORD commanded the children of Jacob, whom he named _____.", "Israel", 34, ["israel"]),
    mc(3, "Which word correctly completes this RSV wording: “commandment which the LORD commanded the children of Jacob, whom he named _____.”", ["Israel", "Habor", "Nebat", "Av’vites"], 34),
    word(1, "In verse 34, what word completes this phrase: “commandment which the LORD commanded the children of Jacob, whom he named _____.”?", "Israel", 34, ["israel"]),
    tf(2, "The RSV does not state: “To this day they do according to the former manner. They do not fear the LORD, and they do not follow the statutes or the ordinances or the law or the commandment which the LORD commanded the children of Jacob, whom he named Israel.”", false, 34, "The quoted wording is the RSV text of this verse."),
    blank(3, "with them, and commanded them, \"You shall not fear other gods or bow _____ to them or serve them or sacrifice to them;", "yourselves", 35, ["yourselves"]),
    mc(1, "Which word correctly completes this RSV wording: “with them, and commanded them, \"You shall not fear other gods or bow _____ to them or serve them or sacrifice to them;”", ["yourselves", "tribe", "spoken", "killing"], 35),
    word(2, "In verse 35, what word completes this phrase: “with them, and commanded them, \"You shall not fear other gods or bow _____ to them or serve them or sacrifice to them;”?", "yourselves", 35, ["yourselves"]),
    tf(3, "The RSV states: “The LORD made a covenant with them, and commanded them, \"You shall not fear other gods or bow yourselves to them or serve them or sacrifice to them;”", true, 35),
    blank(1, "but you shall fear the LORD, who brought you out of the land of _____ with great power and with an outstretched arm; you shall bow yourselves", "Egypt", 36, ["egypt"]),
    mc(2, "Which word correctly completes this RSV wording: “but you shall fear the LORD, who brought you out of the land of _____ with great power and with an outstretched arm; you shall bow yourselves”", ["Egypt", "Nergal", "Sama’ria", "Turn"], 36),
    word(3, "In verse 36, what word completes this phrase: “but you shall fear the LORD, who brought you out of the land of _____ with great power and with an outstretched arm; you shall bow yourselves”?", "Egypt", 36, ["egypt"]),
    tf(1, "The RSV does not state: “but you shall fear the LORD, who brought you out of the land of Egypt with great power and with an outstretched arm; you shall bow yourselves to him, and to him you shall sacrifice.”", false, 36, "The quoted wording is the RSV text of this verse."),
    blank(2, "And the statutes and the ordinances and the law and the _____ which he wrote for you, you shall always be careful to do. You shall not", "commandment", 37, ["commandment"]),
    mc(3, "Which word correctly completes this RSV wording: “And the statutes and the ordinances and the law and the _____ which he wrote for you, you shall always be careful to do. You shall not”", ["commandment", "saying", "despised", "heaven"], 37),
    word(1, "In verse 37, what word completes this phrase: “And the statutes and the ordinances and the law and the _____ which he wrote for you, you shall always be careful to do. You shall not”?", "commandment", 37, ["commandment"]),
    tf(2, "The RSV states: “And the statutes and the ordinances and the law and the commandment which he wrote for you, you shall always be careful to do. You shall not fear other gods,”", true, 37),
    blank(3, "and you shall not forget the _____ that I have made with you. You shall not fear other gods,", "covenant", 38, ["covenant"]),
    mc(1, "Which word correctly completes this RSV wording: “and you shall not forget the _____ that I have made with you. You shall not fear other gods,”", ["covenant", "wicked", "ways", "believe"], 38),
    word(2, "In verse 38, what word completes this phrase: “and you shall not forget the _____ that I have made with you. You shall not fear other gods,”?", "covenant", 38, ["covenant"]),
    tf(3, "The RSV does not state: “and you shall not forget the covenant that I have made with you. You shall not fear other gods,”", false, 38, "The quoted wording is the RSV text of this verse."),
    blank(1, "but you shall fear the LORD your God, and he will _____ you out of the hand of all your enemies.\"", "deliver", 39, ["deliver"]),
    mc(2, "Which word correctly completes this RSV wording: “but you shall fear the LORD your God, and he will _____ you out of the hand of all your enemies.\"”", ["deliver", "warned", "servants", "after"], 39),
    word(3, "In verse 39, what word completes this phrase: “but you shall fear the LORD your God, and he will _____ you out of the hand of all your enemies.\"”?", "deliver", 39, ["deliver"]),
    tf(1, "The RSV states: “but you shall fear the LORD your God, and he will deliver you out of the hand of all your enemies.\"”", true, 39),
    blank(2, "_____ they would not listen, but they did according to their former manner.", "However", 40, ["however"]),
    mc(3, "Which word correctly completes this RSV wording: “_____ they would not listen, but they did according to their former manner.”", ["However", "Sephar-va’im", "Adram’melech", "Assyria"], 40),
    word(1, "In verse 40, what word completes this phrase: “_____ they would not listen, but they did according to their former manner.”?", "However", 40, ["however"]),
    tf(2, "The RSV does not state: “However they would not listen, but they did according to their former manner.”", false, 40, "The quoted wording is the RSV text of this verse."),
    blank(3, "and also served their graven images; their children likewise, and their _____ children -- as their fathers did, so they do to this day.", "children’s", 41, ["childrens"]),
    mc(1, "Which word correctly completes this RSV wording: “and also served their graven images; their children likewise, and their _____ children -- as their fathers did, so they do to this day.”", ["children’s", "yourselves", "graven", "vassal"], 41),
    word(2, "In verse 41, what word completes this phrase: “and also served their graven images; their children likewise, and their _____ children -- as their fathers did, so they do to this day.”?", "children’s", 41, ["childrens"]),
    tf(3, "The RSV states: “ So these nations feared the LORD, and also served their graven images; their children likewise, and their children’s children -- as their fathers did, so they do to this day.”", true, 41),
    mc(3, "Where did Assyria place the Israelites exiled after Samaria fell?", ["In Halah, on the Habor river of Gozan, and in the cities of the Medes", "In Babylon, Cuthah, and Hamath", "In Damascus and the cities of Syria", "In Egypt and the land of Pathros"], 6),
    mc(2, "What happened because Samaria’s foreign settlers did not fear the LORD, and how did Assyria respond?", ["The LORD sent lions; Assyria returned an exiled priest to teach them the law of the god of the land", "Famine came; Assyria sent grain", "War broke out; Assyria sent soldiers", "The Jordan flooded; Assyria rebuilt the cities"], 28),
    mc(1, "How does verse 33 describe the settlers’ divided worship?", ["They feared the LORD but also served their own gods", "They abandoned every former god", "They served the LORD alone", "They feared neither the LORD nor their own gods"], 33),
  ],
};

export default bank;
