// 2 Kings 16 — quiz bank (RSV). Four verse-anchored forms per verse.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: "2 Kings",
  chapter: 16,
  tag: "quiz-v2-2kings-16",
  rows: [
    blank(2, "In the seventeenth year of Pekah the son of _____, Ahaz the son of Jotham, king of Judah, began to reign.", "Remali’ah", 1, ["remaliah"]),
    mc(3, "Which word correctly completes this RSV wording: “In the seventeenth year of Pekah the son of _____, Ahaz the son of Jotham, king of Judah, began to reign.”", ["Remali’ah", "Rezin", "Chronicles", "Syria"], 1),
    word(1, "In verse 1, what word completes this phrase: “In the seventeenth year of Pekah the son of _____, Ahaz the son of Jotham, king of Judah, began to reign.”?", "Remali’ah", 1, ["remaliah"]),
    tf(2, "The RSV states: “In the seventeenth year of Pekah the son of Remali’ah, Ahaz the son of Jotham, king of Judah, began to reign.”", true, 1),
    blank(3, "twenty years old when he began to reign, and he reigned sixteen years in _____. And he did not do what was right in the eyes of the LORD his God, as", "Jerusalem", 2, ["jerusalem"]),
    mc(1, "Which word correctly completes this RSV wording: “twenty years old when he began to reign, and he reigned sixteen years in _____. And he did not do what was right in the eyes of the LORD his God, as”", ["Jerusalem", "Damascus", "Judah", "King"], 2),
    word(2, "In verse 2, what word completes this phrase: “twenty years old when he began to reign, and he reigned sixteen years in _____. And he did not do what was right in the eyes of the LORD his God, as”?", "Jerusalem", 2, ["jerusalem"]),
    tf(3, "The RSV does not state: “Ahaz was twenty years old when he began to reign, and he reigned sixteen years in Jerusalem. And he did not do what was right in the eyes of the LORD his God, as his father David had done,”", false, 2, "The quoted wording is the RSV text of this verse."),
    blank(1, "but he walked in the way of the kings of _____. He even burned his son as an offering, according to the abominable practices", "Israel", 3, ["israel"]),
    mc(2, "Which word correctly completes this RSV wording: “but he walked in the way of the kings of _____. He even burned his son as an offering, according to the abominable practices”", ["Israel", "Pekah", "E’domites", "Remali’ah"], 3),
    word(3, "In verse 3, what word completes this phrase: “but he walked in the way of the kings of _____. He even burned his son as an offering, according to the abominable practices”?", "Israel", 3, ["israel"]),
    tf(1, "The RSV states: “but he walked in the way of the kings of Israel. He even burned his son as an offering, according to the abominable practices of the nations whom the LORD drove out before the people of Israel.”", true, 3),
    blank(2, "And he _____ and burned incense on the high places, and on the hills, and under every", "sacrificed", 4, ["sacrificed"]),
    mc(3, "Which word correctly completes this RSV wording: “And he _____ and burned incense on the high places, and on the hills, and under every”", ["sacrificed", "conquer", "treasures", "model"], 4),
    word(1, "In verse 4, what word completes this phrase: “And he _____ and burned incense on the high places, and on the hills, and under every”?", "sacrificed", 4, ["sacrificed"]),
    tf(2, "The RSV does not state: “And he sacrificed and burned incense on the high places, and on the hills, and under every green tree.”", false, 4, "The quoted wording is the RSV text of this verse."),
    blank(3, "Then Rezin king of Syria and Pekah the son of _____, king of Israel, came up to wage war on Jerusalem, and they besieged Ahaz", "Remali’ah", 5, ["remaliah"]),
    mc(1, "Which word correctly completes this RSV wording: “Then Rezin king of Syria and Pekah the son of _____, king of Israel, came up to wage war on Jerusalem, and they besieged Ahaz”", ["Remali’ah", "Damascus", "Jerusalem", "King"], 5),
    word(2, "In verse 5, what word completes this phrase: “Then Rezin king of Syria and Pekah the son of _____, king of Israel, came up to wage war on Jerusalem, and they besieged Ahaz”?", "Remali’ah", 5, ["remaliah"]),
    tf(3, "The RSV states: “Then Rezin king of Syria and Pekah the son of Remali’ah, king of Israel, came up to wage war on Jerusalem, and they besieged Ahaz but could not conquer him.”", true, 5),
    blank(1, "recovered Elath for Edom, and drove the men of Judah from Elath; and the _____ came to Elath, where they dwell to this day.", "E’domites", 6, ["edomites"]),
    mc(2, "Which word correctly completes this RSV wording: “recovered Elath for Edom, and drove the men of Judah from Elath; and the _____ came to Elath, where they dwell to this day.”", ["E’domites", "Pekah", "Elath", "Remali’ah"], 6),
    word(3, "In verse 6, what word completes this phrase: “recovered Elath for Edom, and drove the men of Judah from Elath; and the _____ came to Elath, where they dwell to this day.”?", "E’domites", 6, ["edomites"]),
    tf(1, "The RSV does not state: “At that time the king of Edom recovered Elath for Edom, and drove the men of Judah from Elath; and the E’domites came to Elath, where they dwell to this day.”", false, 6, "The quoted wording is the RSV text of this verse."),
    blank(2, "So Ahaz sent messengers to _____ king of Assyria, saying, \"I am your servant and your son. Come up, and", "Tig’lath-pile’ser", 7, ["tiglath-pileser"]),
    mc(3, "Which word correctly completes this RSV wording: “So Ahaz sent messengers to _____ king of Assyria, saying, \"I am your servant and your son. Come up, and”", ["Tig’lath-pile’ser", "Jerusalem", "Israel", "Solomon"], 7),
    word(1, "In verse 7, what word completes this phrase: “So Ahaz sent messengers to _____ king of Assyria, saying, \"I am your servant and your son. Come up, and”?", "Tig’lath-pile’ser", 7, ["tiglath-pileser"]),
    tf(2, "The RSV states: “So Ahaz sent messengers to Tig’lath-pile’ser king of Assyria, saying, \"I am your servant and your son. Come up, and rescue me from the hand of the king of Syria and from the hand of the king of Israel, who are attacking me.\"”", true, 7),
    blank(3, "the treasures of the king’s house, and sent a present to the king of _____.", "Assyria", 8, ["assyria"]),
    mc(1, "Which word correctly completes this RSV wording: “the treasures of the king’s house, and sent a present to the king of _____.”", ["Assyria", "Damascus", "Judah", "King"], 8),
    word(2, "In verse 8, what word completes this phrase: “the treasures of the king’s house, and sent a present to the king of _____.”?", "Assyria", 8, ["assyria"]),
    tf(3, "The RSV does not state: “Ahaz also took the silver and gold that was found in the house of the LORD and in the treasures of the king’s house, and sent a present to the king of Assyria.”", false, 8, "The quoted wording is the RSV text of this verse."),
    blank(1, "king of Assyria hearkened to him; the king of Assyria marched up against _____, and took it, carrying its people captive to Kir, and he killed Rezin.", "Damascus", 9, ["damascus"]),
    mc(2, "Which word correctly completes this RSV wording: “king of Assyria hearkened to him; the king of Assyria marched up against _____, and took it, carrying its people captive to Kir, and he killed Rezin.”", ["Damascus", "Pekah", "Elath", "Remali’ah"], 9),
    word(3, "In verse 9, what word completes this phrase: “king of Assyria hearkened to him; the king of Assyria marched up against _____, and took it, carrying its people captive to Kir, and he killed Rezin.”?", "Damascus", 9, ["damascus"]),
    tf(1, "The RSV states: “And the king of Assyria hearkened to him; the king of Assyria marched up against Damascus, and took it, carrying its people captive to Kir, and he killed Rezin.”", true, 9),
    blank(2, "When King Ahaz went to Damascus to meet _____ king of Assyria, he saw the altar that was at Damascus. And King Ahaz", "Tig’lath-pile’ser", 10, ["tiglath-pileser"]),
    mc(3, "Which word correctly completes this RSV wording: “When King Ahaz went to Damascus to meet _____ king of Assyria, he saw the altar that was at Damascus. And King Ahaz”", ["Tig’lath-pile’ser", "Jerusalem", "Israel", "Solomon"], 10),
    word(1, "In verse 10, what word completes this phrase: “When King Ahaz went to Damascus to meet _____ king of Assyria, he saw the altar that was at Damascus. And King Ahaz”?", "Tig’lath-pile’ser", 10, ["tiglath-pileser"]),
    tf(2, "The RSV does not state: “When King Ahaz went to Damascus to meet Tig’lath-pile’ser king of Assyria, he saw the altar that was at Damascus. And King Ahaz sent to Uri’ah the priest a model of the altar, and its pattern, exact in all its details.”", false, 10, "The quoted wording is the RSV text of this verse."),
    blank(3, "built the altar; in accordance with all that King Ahaz had sent from _____, so Uri’ah the priest made it, before King Ahaz arrived from Damascus.", "Damascus", 11, ["damascus"]),
    mc(1, "Which word correctly completes this RSV wording: “built the altar; in accordance with all that King Ahaz had sent from _____, so Uri’ah the priest made it, before King Ahaz arrived from Damascus.”", ["Damascus", "Come", "Judah", "King"], 11),
    word(2, "In verse 11, what word completes this phrase: “built the altar; in accordance with all that King Ahaz had sent from _____, so Uri’ah the priest made it, before King Ahaz arrived from Damascus.”?", "Damascus", 11, ["damascus"]),
    tf(3, "The RSV states: “And Uri’ah the priest built the altar; in accordance with all that King Ahaz had sent from Damascus, so Uri’ah the priest made it, before King Ahaz arrived from Damascus.”", true, 11),
    blank(1, "And when the king came from _____, the king viewed the altar. Then the king drew near to the altar, and", "Damascus", 12, ["damascus"]),
    mc(2, "Which word correctly completes this RSV wording: “And when the king came from _____, the king viewed the altar. Then the king drew near to the altar, and”", ["Damascus", "Pekah", "Elath", "Remali’ah"], 12),
    word(3, "In verse 12, what word completes this phrase: “And when the king came from _____, the king viewed the altar. Then the king drew near to the altar, and”?", "Damascus", 12, ["damascus"]),
    tf(1, "The RSV does not state: “And when the king came from Damascus, the king viewed the altar. Then the king drew near to the altar, and went up on it,”", false, 12, "The quoted wording is the RSV text of this verse."),
    blank(2, "offering, and poured his drink offering, and threw the blood of his peace _____ upon the altar.", "offerings", 13, ["offerings"]),
    mc(3, "Which word correctly completes this RSV wording: “offering, and poured his drink offering, and threw the blood of his peace _____ upon the altar.”", ["offerings", "north", "inquire", "palace"], 13),
    word(1, "In verse 13, what word completes this phrase: “offering, and poured his drink offering, and threw the blood of his peace _____ upon the altar.”?", "offerings", 13, ["offerings"]),
    tf(2, "The RSV states: “and burned his burnt offering and his cereal offering, and poured his drink offering, and threw the blood of his peace offerings upon the altar.”", true, 13),
    blank(3, "And the bronze altar which was before the LORD he _____ from the front of the house, from the place between his altar and the", "removed", 14, ["removed"]),
    mc(1, "Which word correctly completes this RSV wording: “And the bronze altar which was before the LORD he _____ from the front of the house, from the place between his altar and the”", ["removed", "land", "stone", "slept"], 14),
    word(2, "In verse 14, what word completes this phrase: “And the bronze altar which was before the LORD he _____ from the front of the house, from the place between his altar and the”?", "removed", 14, ["removed"]),
    tf(3, "The RSV does not state: “And the bronze altar which was before the LORD he removed from the front of the house, from the place between his altar and the house of the LORD, and put it on the north side of his altar.”", false, 14, "The quoted wording is the RSV text of this verse."),
    blank(1, "And King Ahaz commanded _____ the priest, saying, \"Upon the great altar burn the morning burnt offering,", "Uri’ah", 15, ["uriah"]),
    mc(2, "Which word correctly completes this RSV wording: “And King Ahaz commanded _____ the priest, saying, \"Upon the great altar burn the morning burnt offering,”", ["Uri’ah", "Pekah", "Elath", "Remali’ah"], 15),
    word(3, "In verse 15, what word completes this phrase: “And King Ahaz commanded _____ the priest, saying, \"Upon the great altar burn the morning burnt offering,”?", "Uri’ah", 15, ["uriah"]),
    tf(1, "The RSV states: “And King Ahaz commanded Uri’ah the priest, saying, \"Upon the great altar burn the morning burnt offering, and the evening cereal offering, and the king’s burnt offering, and his cereal offering, with the burnt offering of all the people of the land, and their cereal offering, and their drink offering; and throw upon it all the blood of the burnt offering, and all the blood of the sacrifice; but the bronze altar shall be for me to inquire by.\"”", true, 15),
    blank(2, "_____ the priest did all this, as King Ahaz commanded.", "Uri’ah", 16, ["uriah"]),
    mc(3, "Which word correctly completes this RSV wording: “_____ the priest did all this, as King Ahaz commanded.”", ["Uri’ah", "Israel", "Chronicles", "Rezin"], 16),
    word(1, "In verse 16, what word completes this phrase: “_____ the priest did all this, as King Ahaz commanded.”?", "Uri’ah", 16, ["uriah"]),
    tf(2, "The RSV does not state: “Uri’ah the priest did all this, as King Ahaz commanded.”", false, 16, "The quoted wording is the RSV text of this verse."),
    blank(3, "And _____ Ahaz cut off the frames of the stands, and removed the laver from them,", "King", 17, ["king"]),
    mc(1, "Which word correctly completes this RSV wording: “And _____ Ahaz cut off the frames of the stands, and removed the laver from them,”", ["King", "Hezeki’ah", "Edom", "Remali’ah"], 17),
    word(2, "In verse 17, what word completes this phrase: “And _____ Ahaz cut off the frames of the stands, and removed the laver from them,”?", "King", 17, ["king"]),
    tf(3, "The RSV states: “ And King Ahaz cut off the frames of the stands, and removed the laver from them, and he took down the sea from off the bronze oxen that were under it, and put it upon a pediment of stone.”", true, 17),
    blank(1, "the king he removed from the house of the LORD, because of the king of _____.", "Assyria", 18, ["assyria"]),
    mc(2, "Which word correctly completes this RSV wording: “the king he removed from the house of the LORD, because of the king of _____.”", ["Assyria", "Pekah", "Elath", "Remali’ah"], 18),
    word(3, "In verse 18, what word completes this phrase: “the king he removed from the house of the LORD, because of the king of _____.”?", "Assyria", 18, ["assyria"]),
    tf(1, "The RSV does not state: “And the covered way for the sabbath which had been built inside the palace, and the outer entrance for the king he removed from the house of the LORD, because of the king of Assyria.”", false, 18, "The quoted wording is the RSV text of this verse."),
    blank(2, "the acts of Ahaz which he did, are they not written in the Book of the _____ of the Kings of Judah?", "Chronicles", 19, ["chronicles"]),
    mc(3, "Which word correctly completes this RSV wording: “the acts of Ahaz which he did, are they not written in the Book of the _____ of the Kings of Judah?”", ["Chronicles", "David", "Pekah", "Assyria"], 19),
    word(1, "In verse 19, what word completes this phrase: “the acts of Ahaz which he did, are they not written in the Book of the _____ of the Kings of Judah?”?", "Chronicles", 19, ["chronicles"]),
    tf(2, "The RSV states: “Now the rest of the acts of Ahaz which he did, are they not written in the Book of the Chronicles of the Kings of Judah?”", true, 19),
    blank(3, "his fathers, and was buried with his fathers in the city of David; and _____ his son reigned in his stead.", "Hezeki’ah", 20, ["hezekiah"]),
    mc(1, "Which word correctly completes this RSV wording: “his fathers, and was buried with his fathers in the city of David; and _____ his son reigned in his stead.”", ["Hezeki’ah", "Come", "Judah", "Damascus"], 20),
    word(2, "In verse 20, what word completes this phrase: “his fathers, and was buried with his fathers in the city of David; and _____ his son reigned in his stead.”?", "Hezeki’ah", 20, ["hezekiah"]),
    tf(3, "The RSV does not state: “And Ahaz slept with his fathers, and was buried with his fathers in the city of David; and Hezeki’ah his son reigned in his stead.”", false, 20, "The quoted wording is the RSV text of this verse."),
    blank(1, "In the _____ year of Pekah the son of Remali’ah, Ahaz the son of Jotham, king of Judah,", "seventeenth", 1, ["seventeenth"]),
    mc(2, "Select the missing RSV word: “Ahaz was twenty years old when he began to reign, and he _____ sixteen years in Jerusalem. And he did not do what was right in the eyes”", ["reigned", "hills", "recovered", "silver"], 2),
    word(3, "What missing word belongs in this verse 3 clause: “kings of Israel. He even burned his son as an offering, according to the _____ practices of the nations whom the LORD drove out before the people of”?", "abominable", 3, ["abominable"]),
    tf(1, "This wording appears in verse 4: “And he sacrificed and burned incense on the high places, and on the hills, and under every green tree.”", true, 4),
    blank(2, "and Pekah the son of Remali’ah, king of Israel, came up to wage war on _____, and they besieged Ahaz but could not conquer him.", "Jerusalem", 5, ["jerusalem"]),
    mc(3, "Select the missing RSV word: “At that time the king of Edom _____ Elath for Edom, and drove the men of Judah from Elath; and the E’domites”", ["recovered", "peace", "burn", "down"], 6),
    word(1, "What missing word belongs in this verse 7 clause: “So Ahaz sent _____ to Tig’lath-pile’ser king of Assyria, saying, \"I am your servant and your”?", "messengers", 7, ["messengers"]),
    tf(2, "This wording appears in verse 8: “the silver and gold that was found in the house of the LORD and in the treasures of the king’s house, and sent a present to the king of Assyria.”", true, 8),
    blank(3, "And the king of Assyria _____ to him; the king of Assyria marched up against Damascus, and took it,", "hearkened", 9, ["hearkened"]),
    mc(1, "Select the missing RSV word: “When King Ahaz went to _____ to meet Tig’lath-pile’ser king of Assyria, he saw the altar that was at”", ["Damascus", "Come", "Judah", "King"], 10),
    word(2, "What missing word belongs in this verse 11 clause: “And Uri’ah the priest built the altar; in _____ with all that King Ahaz had sent from Damascus, so Uri’ah the priest made”?", "accordance", 11, ["accordance"]),
    tf(3, "This wording appears in verse 12: “And when the king came from Damascus, the king viewed the altar. Then the king drew near to the altar, and went up on it,”", true, 12),
    blank(1, "and burned his burnt _____ and his cereal offering, and poured his drink offering, and threw the", "offering", 13, ["offering"]),
    mc(2, "Select the missing RSV word: “before the LORD he removed from the front of the house, from the place _____ his altar and the house of the LORD, and put it on the north side of his”", ["between", "details", "drink", "commanded"], 14),
    word(3, "What missing word belongs in this verse 15 clause: “And King Ahaz _____ Uri’ah the priest, saying, \"Upon the great altar burn the morning burnt”?", "commanded", 15, ["commanded"]),
    tf(1, "This wording appears in verse 16: “Uri’ah the priest did all this, as King Ahaz commanded.”", true, 16),
    blank(2, "the sea from off the bronze oxen that were under it, and put it upon a _____ of stone.", "pediment", 17, ["pediment"]),
    mc(3, "Select the missing RSV word: “for the sabbath which had been built inside the palace, and the outer _____ for the king he removed from the house of the LORD, because of the king”", ["entrance", "king", "walked", "people"], 18),
    word(1, "What missing word belongs in this verse 19 clause: “Now the rest of the acts of Ahaz which he did, are they not _____ in the Book of the Chronicles of the Kings of Judah?”?", "written", 19, ["written"]),
    tf(2, "This wording appears in verse 20: “And Ahaz slept with his fathers, and was buried with his fathers in the city of David; and Hezeki’ah his”", true, 20),
    blank(3, "In the seventeenth year of Pekah the son of Remali’ah, Ahaz the son of _____, king of Judah, began to reign.", "Jotham", 1, ["jotham"]),
    mc(1, "Select the missing RSV word: “Ahaz was twenty years old when he began to reign, and he reigned _____ years in Jerusalem. And he did not do what was right in the eyes of the”", ["sixteen", "saying", "treasures", "altar"], 2),
    word(2, "What missing word belongs in this verse 3 clause: “the way of the kings of Israel. He even burned his son as an offering, _____ to the abominable practices of the nations whom the LORD drove out before”?", "according", 3, ["according"]),
    blank(1, "Remali’ah, king of Israel, came up to wage war on Jerusalem, and they _____ Ahaz but could not conquer him.", "besieged", 5, ["besieged"]),
    mc(2, "Select the missing RSV word: “At that time the king of Edom recovered _____ for Edom, and drove the men of Judah from Elath; and the E’domites came”", ["Elath", "Damascus", "Judah", "King"], 6),
    word(3, "What missing word belongs in this verse 7 clause: “of the king of Syria and from the hand of the king of Israel, who are _____ me.\"”?", "attacking", 7, ["attacking"]),
    tf(1, "This wording appears in verse 8: “house of the LORD and in the treasures of the king’s house, and sent a present to the king of Assyria.”", true, 8),
    blank(2, "to him; the king of Assyria marched up against Damascus, and took it, _____ its people captive to Kir, and he killed Rezin.", "carrying", 9, ["carrying"]),
    mc(3, "Select the missing RSV word: “When King Ahaz went to Damascus to meet Tig’lath-pile’ser king of _____, he saw the altar that was at Damascus. And King Ahaz sent to Uri’ah the”", ["Assyria", "Israel", "Chronicles", "Rezin"], 10),
    word(1, "What missing word belongs in this verse 11 clause: “had sent from Damascus, so Uri’ah the priest made it, before King Ahaz _____ from Damascus.”?", "arrived", 11, ["arrived"]),
    blank(3, "and _____ his burnt offering and his cereal offering, and poured his drink offering,", "burned", 13, ["burned"]),
    mc(1, "Select the missing RSV word: “And the _____ altar which was before the LORD he removed from the front of the house,”", ["bronze", "offerings", "evening", "pediment"], 14),
    word(2, "What missing word belongs in this verse 15 clause: “upon it all the blood of the burnt offering, and all the blood of the _____; but the bronze altar shall be for me to inquire by.\"”?", "sacrifice", 15, ["sacrifice"]),
    blank(1, "And King Ahaz cut off the frames of the stands, and _____ the laver from them, and he took down the sea from off the bronze oxen", "removed", 17, ["removed"]),
    mc(2, "Select the missing RSV word: “And the _____ way for the sabbath which had been built inside the palace, and the outer”", ["covered", "offering", "places", "time"], 18),
    word(3, "What missing word belongs in this verse 19 clause: “which he did, are they not written in the Book of the Chronicles of the _____ of Judah?”?", "Kings", 19, ["kings"]),
    tf(1, "This wording appears in verse 20: “was buried with his fathers in the city of David; and Hezeki’ah his son reigned in his stead.”", true, 20),
    mc(2, "What abominable practice did Ahaz commit with his son?", ["He burned his son as an offering", "He dedicated his son to Baal’s priesthood", "He sent his son to Damascus", "He made his son serve the Assyrian king"], 3),
    mc(3, "What did Ahaz order Uriah the priest to reproduce in Jerusalem?", ["The Damascus altar, using the model and exact pattern Ahaz sent", "The palace of Assyria", "A bronze image of the Syrian king", "The temple gates of Damascus"], 11),
    tf(2, "Ahaz told Uriah to design a new altar without using the Damascus pattern.", false, 11, "Uriah built the altar in accordance with all that Ahaz sent from Damascus."),
  ],
};

export default bank;
