import { mc, blank, word, tf, type ChapterBank, sa } from './types'

const bank: ChapterBank = {
  book: '2 Kings', chapter: 7, tag: 'quiz-v2-2kings-7', rows: [
    mc(1, 'What change did Elisha prophesy for the next day?', ['Fine meal and barley would be affordable at Samaria’s gate', 'Syria would burn Samaria', 'The famine would last seven years', 'The king would leave Israel'], 1),
    blank(1, 'a measure of fine meal shall be sold for a _____.', 'shekel', 1),
    sa(3, 'How much barley would one shekel buy?', 'two measures', 1, ['2 measures']),
    tf(2, 'Elisha placed the fulfillment at Samaria’s gate about the same time the next day.', true, 1),
    mc(2, 'What price pair did the LORD announce?', ['One measure of fine meal and two measures of barley for one shekel each', 'Two measures of meal and one of barley for ten shekels', 'One loaf and one measure of grain for five shekels', 'Seven measures of each for one talent'], 1),
    word(2, 'Whose word introduced the price prophecy?', 'the LORD’s', 1, ['the word of the LORD', 'LORD']),
    mc(3, 'What exact market reversal did Elisha predict?', ['A measure of fine meal for a shekel and two measures of barley for a shekel', 'An ass’s head for eighty shekels', 'A quarter-kab of grain for five shekels', 'Twenty loaves for one hundred men'], 1),

    mc(1, 'Who challenged Elisha’s prophecy?', ['The captain on whose hand the king leaned', 'The king of Syria', 'One of the lepers', 'The gatekeeper'], 2),
    blank(3, 'If the LORD himself should make _____ in heaven, could this thing be?', 'windows', 2),
    sa(2, 'What did Elisha say the captain would not do?', 'eat of the promised food', 2, ['eat it', 'eat of it']),
    tf(1, 'The captain would see the fulfillment with his own eyes.', true, 2),
    mc(2, 'What consequence accompanied the captain’s disbelief?', ['He would witness the abundance but not eat from it', 'He would be struck blind immediately', 'He would flee with the Syrians', 'He would become a leper'], 2),
    sa(1, 'Whose hand did the king lean on?', 'the captain’s', 2, ['the captain']),

    mc(1, 'Who sat at the entrance of Samaria’s gate?', ['Four men with leprosy', 'Four Syrian captains', 'The king’s servants', 'The sons of the prophets'], 3),
    blank(2, 'Why do we sit here till we _____?', 'die', 3),
    word(1, 'How many lepers were there?', 'four', 3, ['4']),
    tf(3, 'The four men recognized that remaining at the gate meant death.', true, 3),
    mc(2, 'What question began the lepers’ discussion?', ['Why do we sit here until we die?', 'Where is the Syrian army?', 'Has the famine ended?', 'Will the king open the gate?'], 3),
    sa(2, 'Where were the four men positioned?', 'at the entrance to the gate', 3, ['the gate entrance', 'at the gate']),

    mc(1, 'What course did the lepers decide to try?', ['Go over to the Syrian camp', 'Enter the starving city', 'Remain at the gate', 'Seek Elisha'], 4),
    blank(3, 'if they spare our lives we shall _____.', 'live', 4),
    sa(2, 'What outcome did they expect if they entered the city?', 'death from the famine', 4, ['they would die', 'die there']),
    tf(1, 'The lepers believed they faced death whether they entered the city or stayed put.', true, 4),
    mc(2, 'Why did approaching Syria seem worth the risk?', ['The Syrians might spare them, while their other choices meant death', 'They knew the camp was empty', 'Elisha had promised them protection', 'The king ordered them to scout'], 4),
    sa(1, 'What would happen at worst if the Syrians rejected them?', 'they would be killed', 4, ['die', 'the Syrians would kill them']),

    mc(1, 'When did the lepers approach Syria’s camp?', ['At twilight', 'At noon', 'At dawn', 'At midnight'], 5),
    blank(2, 'behold, there was no one _____.', 'there', 5),
    sa(1, 'What did they find at the edge of the camp?', 'no one', 5, ['nobody', 'an empty camp']),
    tf(3, 'The lepers met Syrian guards at the camp’s edge.', false, 5, 'There was no one there.'),
    mc(2, 'What first indicated that something extraordinary had happened?', ['The Syrian camp had been abandoned', 'The city gate was open', 'Rain filled the camp', 'Israel’s army was celebrating'], 5),
    sa(2, 'To whose camp did they go?', 'the Syrians’', 5, ['the Syrian camp', 'Syrians']),

    mc(1, 'What sound had the Lord made the Syrians hear?', ['Chariots, horses, and a great army', 'Thunder and rain', 'The people of Samaria', 'Trumpets from Dothan'], 6),
    blank(3, 'the king of Israel has _____ against us the kings of the Hittites', 'hired', 6),
    sa(2, 'Which two foreign powers did Syria imagine were attacking?', 'the Hittite and Egyptian kings', 6, ['kings of the Hittites and Egypt', 'Hittites and Egyptians']),
    tf(1, 'The Syrians fled because the Lord caused them to hear an approaching army.', true, 6),
    mc(2, 'How did Syria interpret the supernatural sound?', ['Israel had hired Hittite and Egyptian kings against them', 'Samaria’s starving people had escaped', 'Elisha had summoned fire', 'Their own king had ordered retreat'], 6),
    word(1, 'Who produced the sound that terrified Syria?', 'the Lord', 6, ['LORD', 'God']),

    mc(1, 'What did the Syrians leave behind?', ['Tents, horses, and asses', 'Only empty food jars', 'Their king and captains', 'All their garments but no animals'], 7),
    blank(2, 'and fled for their _____.', 'lives', 7),
    sa(1, 'When did the Syrians flee?', 'at twilight', 7, ['twilight']),
    tf(3, 'The Syrians carefully packed their camp before departing.', false, 7, 'They left the camp as it was and fled for their lives.'),
    mc(2, 'Why was the camp available for the lepers to discover?', ['The entire Syrian army had fled in panic', 'Israel had captured every soldier', 'The Syrians were hiding nearby', 'The army had marched to Egypt'], 7),
    sa(2, 'What motive drove the Syrian retreat?', 'saving their lives', 7, ['they fled for their lives', 'fear for their lives']),
    mc(3, 'Who discovered the deserted camp, and why was it empty?', ['Four lepers found it after the Lord made Syria hear a great army', 'Israelite scouts found it after a plague', 'Gatekeepers found it after Ben-hadad surrendered', 'Elisha found it after Syria marched to Dothan'], 7),

    mc(1, 'What did the lepers first do inside a tent?', ['Ate and drank', 'Called the gatekeepers', 'Burned the supplies', 'Waited for morning'], 8),
    blank(3, 'they carried off silver and gold and _____.', 'clothing', 8),
    sa(2, 'What did they do with the valuables?', 'hid them', 8, ['went and hid them']),
    tf(1, 'The lepers entered more than one tent.', true, 8),
    mc(2, 'What three kinds of valuables did they remove?', ['Silver, gold, and clothing', 'Meal, barley, and oil', 'Horses, chariots, and weapons', 'Bread, water, and wool'], 8),
    sa(1, 'What did the men do after hiding goods from the first tent?', 'returned and entered another tent', 8, ['went into another tent', 'came back to another tent']),

    mc(1, 'Why did the lepers decide to report their discovery?', ['It was a day of good news and silence could bring punishment', 'They had found no food', 'The Syrians were returning', 'The king had promised a reward'], 9),
    blank(2, 'This day is a day of good _____.', 'news', 9),
    sa(1, 'Whom did they decide to tell?', 'the king’s household', 9, ['the king', 'king’s house']),
    tf(3, 'The men concluded that keeping silent until morning was wrong.', true, 9),
    mc(2, 'What consequence did they fear if they delayed?', ['Punishment would overtake them', 'The famine would worsen', 'The Syrians would seize them', 'The gatekeepers would leave'], 9),
    sa(2, 'Until what time had they considered waiting?', 'the morning light', 9, ['morning', 'daybreak']),
    mc(3, 'What moral realization changed the lepers’ behavior?', ['They were withholding good news and risked punishment by remaining silent', 'The treasure belonged only to the king', 'The Syrians had commanded them to report', 'The food would spoil before morning'], 9),

    mc(1, 'To whom did the lepers report at the city?', ['The gatekeepers', 'Elisha', 'The captain', 'The king directly'], 10),
    blank(3, 'nothing but the horses _____, and the asses tied', 'tied', 10),
    sa(2, 'What could be heard in the Syrian camp?', 'no one', 10, ['nothing', 'no person']),
    tf(1, 'The tents remained in place in the deserted camp.', true, 10),
    mc(2, 'What evidence did the lepers give the gatekeepers?', ['No person was seen or heard, while animals remained tied and tents stood', 'The Syrians had sent a surrender message', 'Israelite soldiers occupied the camp', 'Elisha waited there with food'], 10),
    sa(1, 'Which animals did they specifically report as tied?', 'horses and asses', 10, ['horses and donkeys']),

    mc(1, 'Where did the gatekeepers send the report?', ['Into the king’s household', 'To the Syrian camp', 'To Dothan', 'To the market'], 11),
    blank(2, 'Then the gatekeepers called _____.', 'out', 11),
    sa(1, 'Who relayed the lepers’ news?', 'the gatekeepers', 11, ['gatekeepers']),
    tf(3, 'The report reached the king’s household.', true, 11),
    mc(2, 'What role did the gatekeepers play?', ['They passed the discovery into the royal household', 'They personally plundered the camp', 'They closed the city permanently', 'They arrested the four men'], 11),
    sa(2, 'Whose household received the message?', 'the king’s', 11, ['the king']),

    mc(1, 'What trap did the king fear?', ['The Syrians were hiding outside to capture those leaving the city', 'The camp contained poisoned food', 'The lepers were Syrian spies', 'Elisha had hidden the army'], 12),
    blank(3, 'They know that we are _____.', 'hungry', 12),
    sa(2, 'When did the king rise to consider the report?', 'in the night', 12, ['at night']),
    tf(1, 'The king suspected the empty camp was bait for an ambush.', true, 12),
    mc(2, 'What did the king think Syria hoped to capture?', ['The people alive and the city itself', 'Only the four lepers', 'Elisha and the gatekeepers', 'The remaining horses only'], 12),
    sa(1, 'Where did the king imagine the Syrians were hiding?', 'the open country', 12, ['outside the camp', 'open country']),

    mc(1, 'What did a servant propose sending to investigate?', ['Men with five remaining horses', 'The entire starving army', 'The four lepers', 'A message to Syria’s king'], 13),
    blank(2, 'Let some men take five of the _____ horses', 'remaining', 13),
    sa(1, 'What did the servant expect for those who remained if they did nothing?', 'the fate of Israel’s perished multitude', 13, ['they would perish', 'fare like those already dead']),
    tf(3, 'The servant argued that a scouting mission risked little because the city already faced death.', true, 13),
    mc(2, 'Why was using the remaining horses reasonable?', ['Those left in the city faced the same fate as those already lost', 'The horses could smell Syrians', 'Elisha had ordered five riders', 'The king had no men on foot'], 13),
    word(2, 'How many horses did the servant mention?', 'five', 13, ['5']),

    mc(1, 'How many mounted men did the king send?', ['Two', 'Five', 'Four', 'Fifty'], 14),
    blank(3, 'the king sent them after the army of the _____.', 'Syrians', 14),
    sa(2, 'What command did the king give the scouts?', 'Go and see', 14, ['go see', 'investigate']),
    tf(1, 'The scouts followed the route of Syria’s army.', true, 14),
    mc(2, 'What was the purpose of the mounted mission?', ['To verify what had happened to the Syrian army', 'To negotiate surrender', 'To bring Elisha to the king', 'To collect food before anyone else'], 14),
    word(1, 'Were the scouts mounted?', 'yes', 14, ['two mounted men', 'yes they were']),

    mc(1, 'How far did the scouts follow the Syrians’ trail?', ['As far as the Jordan', 'Only to the camp edge', 'To Damascus', 'To Dothan'], 15),
    blank(2, 'all the way was _____ with garments and equipment', 'littered', 15),
    sa(1, 'Why had Syria discarded garments and equipment?', 'in their haste', 15, ['because they fled hastily', 'hasty flight']),
    tf(3, 'The messengers returned and reported to the king.', true, 15),
    mc(2, 'What confirmed that Syria had truly fled?', ['Discarded garments and equipment lined the route to the Jordan', 'Syrian soldiers surrendered to the scouts', 'Ben-hadad sent a letter', 'The camp animals followed the scouts'], 15),
    sa(2, 'What two categories of items lay along the road?', 'garments and equipment', 15, ['clothing and equipment']),

    mc(1, 'What did Samaria’s people do after the report was confirmed?', ['Went out and plundered Syria’s camp', 'Stayed behind the walls', 'Pursued the Syrians to Damascus', 'Destroyed the food'], 16),
    blank(3, 'a measure of fine meal was sold for a _____.', 'shekel', 16),
    sa(2, 'How much barley sold for a shekel?', 'two measures', 16, ['2 measures']),
    tf(1, 'The market prices matched the word of the LORD.', true, 16),
    mc(2, 'How was Elisha’s prophecy fulfilled?', ['Plunder from Syria’s camp made meal and barley available at the predicted prices', 'Rain produced an instant harvest', 'Egypt sent grain to Samaria', 'The king opened a hidden storehouse'], 16),
    sa(1, 'Whose camp supplied the plunder?', 'the Syrians’', 16, ['Syrian camp', 'Syria']),

    mc(1, 'What duty did the king give the skeptical captain?', ['Charge of the gate', 'Command of the scouts', 'Guarding Elisha', 'Counting the grain'], 17),
    blank(2, 'the people _____ upon him in the gate', 'trod', 17, ['trampled']),
    sa(1, 'What happened to the captain?', 'he died', 17, ['death', 'was trampled to death']),
    tf(3, 'The captain’s death fulfilled the man of God’s warning.', true, 17),
    mc(2, 'Why was the gate assignment fatal?', ['The crowd trampled the captain while rushing through', 'The Syrians returned and killed him', 'The king executed him', 'He ate poisoned grain'], 17),
    sa(2, 'Where was the captain trampled?', 'in the gate', 17, ['at Samaria’s gate', 'the gate']),
    mc(3, 'What became of the official who doubted?', ['He saw the abundance but was trampled at the gate before eating it', 'He fled with Syria and never saw it', 'He was imprisoned by the king', 'He ate the meal and survived'], 17),

    mc(1, 'Which prophecy is repeated in verse 18?', ['Two measures of barley and one of fine meal would each sell for a shekel', 'The Syrians would return the next day', 'The famine would last seven years', 'The captain would become king'], 18),
    blank(3, 'about this time _____ in the gate of Sama’ria', 'tomorrow', 18),
    sa(2, 'Who had spoken the price prediction to the king?', 'the man of God', 18, ['Elisha']),
    tf(1, 'The repeated prophecy specified both the time and place.', true, 18),
    mc(2, 'Where would the low-priced food be sold?', ['At Samaria’s gate', 'Inside the Syrian camp', 'At the Jordan', 'In the king’s palace'], 18),
    sa(1, 'How much fine meal would one shekel buy?', 'one measure', 18, ['a measure', '1 measure']),

    mc(1, 'What skeptical image had the captain used?', ['The LORD making windows in heaven', 'The Jordan flowing backward', 'Chariots of fire descending', 'A mountain moving'], 19),
    blank(2, 'You shall see it with your own _____', 'eyes', 19),
    sa(1, 'What part of the prophecy would the captain be denied?', 'eating the food', 19, ['he would not eat of it', 'not eat it']),
    tf(3, 'The captain’s exact response and Elisha’s warning are recalled.', true, 19),
    mc(2, 'How did Elisha answer the captain’s challenge?', ['You will see it, but you will not eat it', 'You will neither see nor hear it', 'You will open heaven yourself', 'You will leave the gate before it happens'], 19),
    sa(2, 'Who had questioned whether the LORD could do this?', 'the captain', 19, ['the officer']),

    mc(1, 'How did the chapter close the captain’s story?', ['The people trampled him in the gate and he died', 'He repented and ate', 'The king pardoned him', 'He fled to Syria'], 20),
    blank(3, 'And so it _____ to him', 'happened', 20),
    sa(2, 'Who caused the captain’s death?', 'the people', 20, ['the crowd']),
    tf(1, 'The final outcome matched Elisha’s words.', true, 20),
    mc(2, 'What final detail confirms both halves of the warning?', ['He reached the gate and saw the abundance but died under the crowd', 'He remained in the palace and saw nothing', 'He ate the food before dying', 'He escaped the crowd and left Israel'], 20),
  ],
}

export default bank
