// 2 Kings 14 — quiz bank (RSV). Four verse-anchored forms per verse.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: "2 Kings",
  chapter: 14,
  tag: "quiz-v2-2kings-14",
  rows: [
    blank(2, "In the second year of Jo’ash the son of Jo’ahaz, king of Israel, _____ the son of Jo’ash, king of Judah, began to reign.", "Amazi’ah", 1, ["amaziah"]),
    mc(3, "Which word correctly completes this RSV wording: “In the second year of Jo’ash the son of Jo’ahaz, king of Israel, _____ the son of Jo’ash, king of Judah, began to reign.”", ["Amazi’ah", "Moses", "Give", "Jerobo’am"], 1),
    word(1, "In verse 1, what word completes this phrase: “In the second year of Jo’ash the son of Jo’ahaz, king of Israel, _____ the son of Jo’ash, king of Judah, began to reign.”?", "Amazi’ah", 1, ["amaziah"]),
    tf(2, "The RSV states: “In the second year of Jo’ash the son of Jo’ahaz, king of Israel, Amazi’ah the son of Jo’ash, king of Judah, began to reign.”", true, 1),
    blank(3, "and he reigned twenty-nine years in Jerusalem. His mother’s name was _____ of Jerusalem.", "Jeho-ad’din", 2, ["jeho-addin"]),
    mc(1, "Which word correctly completes this RSV wording: “and he reigned twenty-nine years in Jerusalem. His mother’s name was _____ of Jerusalem.”", ["Jeho-ad’din", "Corner", "Zechari’ah", "Lebanon"], 2),
    word(2, "In verse 2, what word completes this phrase: “and he reigned twenty-nine years in Jerusalem. His mother’s name was _____ of Jerusalem.”?", "Jeho-ad’din", 2, ["jeho-addin"]),
    tf(3, "The RSV does not state: “He was twenty-five years old when he began to reign, and he reigned twenty-nine years in Jerusalem. His mother’s name was Jeho-ad’din of Jerusalem.”", false, 2, "The quoted wording is the RSV text of this verse."),
    blank(1, "eyes of the LORD, yet not like David his father; he did in all things as _____ his father had done.", "Jo’ash", 3, ["joash"]),
    mc(2, "Which word correctly completes this RSV wording: “eyes of the LORD, yet not like David his father; he did in all things as _____ his father had done.”", ["Jo’ash", "E’phraim", "Nebat", "Jerusalem"], 3),
    word(3, "In verse 3, what word completes this phrase: “eyes of the LORD, yet not like David his father; he did in all things as _____ his father had done.”?", "Jo’ash", 3, ["joash"]),
    tf(1, "The RSV states: “And he did what was right in the eyes of the LORD, yet not like David his father; he did in all things as Jo’ash his father had done.”", true, 3),
    blank(2, "But the high places were not removed; the people still _____ and burned incense on the high places.", "sacrificed", 4, ["sacrificed"]),
    mc(3, "Which word correctly completes this RSV wording: “But the high places were not removed; the people still _____ and burned incense on the high places.”", ["sacrificed", "commanded", "cedar", "glory"], 4),
    word(1, "In verse 4, what word completes this phrase: “But the high places were not removed; the people still _____ and burned incense on the high places.”?", "sacrificed", 4, ["sacrificed"]),
    tf(2, "The RSV does not state: “But the high places were not removed; the people still sacrificed and burned incense on the high places.”", false, 4, "The quoted wording is the RSV text of this verse."),
    blank(3, "And as soon as the royal power was firmly in his hand he killed his _____ who had slain the king his father.", "servants", 5, ["servants"]),
    mc(1, "Which word correctly completes this RSV wording: “And as soon as the royal power was firmly in his hand he killed his _____ who had slain the king his father.”", ["servants", "according", "sent", "wild"], 5),
    word(2, "In verse 5, what word completes this phrase: “And as soon as the royal power was firmly in his hand he killed his _____ who had slain the king his father.”?", "servants", 5, ["servants"]),
    tf(3, "The RSV states: “And as soon as the royal power was firmly in his hand he killed his servants who had slain the king his father.”", true, 5),
    blank(1, "the murderers; according to what is written in the book of the law of _____, where the LORD commanded, \"The fathers shall not be put to death for", "Moses", 6, ["moses"]),
    mc(2, "Which word correctly completes this RSV wording: “the murderers; according to what is written in the book of the law of _____, where the LORD commanded, \"The fathers shall not be put to death for”", ["Moses", "Judah", "Come", "Kings"], 6),
    word(3, "In verse 6, what word completes this phrase: “the murderers; according to what is written in the book of the law of _____, where the LORD commanded, \"The fathers shall not be put to death for”?", "Moses", 6, ["moses"]),
    tf(1, "The RSV does not state: “But he did not put to death the children of the murderers; according to what is written in the book of the law of Moses, where the LORD commanded, \"The fathers shall not be put to death for the children, or the children be put to death for the fathers; but every man shall die for his own sin.\"”", false, 6, "The quoted wording is the RSV text of this verse."),
    blank(2, "E’domites in the Valley of Salt and took Sela by storm, and called it _____, which is its name to this day.", "Jok’the-el", 7, ["jokthe-el"]),
    mc(3, "Which word correctly completes this RSV wording: “E’domites in the Valley of Salt and took Sela by storm, and called it _____, which is its name to this day.”", ["Jok’the-el", "E’phraim", "Arabah", "Jerusalem"], 7),
    word(1, "In verse 7, what word completes this phrase: “E’domites in the Valley of Salt and took Sela by storm, and called it _____, which is its name to this day.”?", "Jok’the-el", 7, ["jokthe-el"]),
    tf(2, "The RSV states: “He killed ten thousand E’domites in the Valley of Salt and took Sela by storm, and called it Jok’the-el, which is its name to this day.”", true, 7),
    blank(3, "Then Amazi’ah sent messengers to Jeho’ash the son of _____, son of Jehu, king of Israel, saying, \"Come, let us look one another in", "Jeho’ahaz", 8, ["jehoahaz"]),
    mc(1, "Which word correctly completes this RSV wording: “Then Amazi’ah sent messengers to Jeho’ash the son of _____, son of Jehu, king of Israel, saying, \"Come, let us look one another in”", ["Jeho’ahaz", "Jehu", "Book", "Amit’tai"], 8),
    word(2, "In verse 8, what word completes this phrase: “Then Amazi’ah sent messengers to Jeho’ash the son of _____, son of Jehu, king of Israel, saying, \"Come, let us look one another in”?", "Jeho’ahaz", 8, ["jehoahaz"]),
    tf(3, "The RSV does not state: “Then Amazi’ah sent messengers to Jeho’ash the son of Jeho’ahaz, son of Jehu, king of Israel, saying, \"Come, let us look one another in the face.\"”", false, 8, "The quoted wording is the RSV text of this verse."),
    blank(1, "And _____ king of Israel sent word to Amazi’ah king of Judah, \"A thistle on Lebanon", "Jeho’ash", 9, ["jehoash"]),
    mc(2, "Which word correctly completes this RSV wording: “And _____ king of Israel sent word to Amazi’ah king of Judah, \"A thistle on Lebanon”", ["Jeho’ash", "E’phraim", "Nebat", "Amazi’ah"], 9),
    word(3, "In verse 9, what word completes this phrase: “And _____ king of Israel sent word to Amazi’ah king of Judah, \"A thistle on Lebanon”?", "Jeho’ash", 9, ["jehoash"]),
    tf(1, "The RSV states: “And Jeho’ash king of Israel sent word to Amazi’ah king of Judah, \"A thistle on Lebanon sent to a cedar on Lebanon, saying, `Give your daughter to my son for a wife’; and a wild beast of Lebanon passed by and trampled down the thistle.”", true, 9),
    blank(2, "at home; for why should you provoke trouble so that you fall, you and _____ with you?\"", "Judah", 10, ["judah"]),
    mc(3, "Which word correctly completes this RSV wording: “at home; for why should you provoke trouble so that you fall, you and _____ with you?\"”", ["Judah", "Hamath", "David", "Lebanon"], 10),
    word(1, "In verse 10, what word completes this phrase: “at home; for why should you provoke trouble so that you fall, you and _____ with you?\"”?", "Judah", 10, ["judah"]),
    tf(2, "The RSV does not state: “You have indeed smitten Edom, and your heart has lifted you up. Be content with your glory, and stay at home; for why should you provoke trouble so that you fall, you and Judah with you?\"”", false, 10, "The quoted wording is the RSV text of this verse."),
    blank(3, "up, and he and Amazi’ah king of Judah faced one another in battle at _____, which belongs to Judah.", "Beth-she’mesh", 11, ["beth-shemesh"]),
    mc(1, "Which word correctly completes this RSV wording: “up, and he and Amazi’ah king of Judah faced one another in battle at _____, which belongs to Judah.”", ["Beth-she’mesh", "Sama’ria", "E’domites", "Gath-he’pher"], 11),
    word(2, "In verse 11, what word completes this phrase: “up, and he and Amazi’ah king of Judah faced one another in battle at _____, which belongs to Judah.”?", "Beth-she’mesh", 11, ["beth-shemesh"]),
    tf(3, "The RSV states: “But Amazi’ah would not listen. So Jeho’ash king of Israel went up, and he and Amazi’ah king of Judah faced one another in battle at Beth-she’mesh, which belongs to Judah.”", true, 11),
    blank(1, "And Judah was defeated by _____, and every man fled to his home.", "Israel", 12, ["israel"]),
    mc(2, "Which word correctly completes this RSV wording: “And Judah was defeated by _____, and every man fled to his home.”", ["Israel", "David", "Lebanon", "Jerobo’am"], 12),
    word(3, "In verse 12, what word completes this phrase: “And Judah was defeated by _____, and every man fled to his home.”?", "Israel", 12, ["israel"]),
    tf(1, "The RSV does not state: “And Judah was defeated by Israel, and every man fled to his home.”", false, 12, "The quoted wording is the RSV text of this verse."),
    blank(2, "captured Amazi’ah king of Judah, the son of Jeho’ash, son of Ahazi’ah, at _____, and came to Jerusalem, and broke down the wall of Jerusalem for four", "Beth-she’mesh", 13, ["beth-shemesh"]),
    mc(3, "Which word correctly completes this RSV wording: “captured Amazi’ah king of Judah, the son of Jeho’ash, son of Ahazi’ah, at _____, and came to Jerusalem, and broke down the wall of Jerusalem for four”", ["Beth-she’mesh", "Jeho’ahaz", "Amazi’ah", "Jerobo’am"], 13),
    word(1, "In verse 13, what word completes this phrase: “captured Amazi’ah king of Judah, the son of Jeho’ash, son of Ahazi’ah, at _____, and came to Jerusalem, and broke down the wall of Jerusalem for four”?", "Beth-she’mesh", 13, ["beth-shemesh"]),
    tf(2, "The RSV states: “And Jeho’ash king of Israel captured Amazi’ah king of Judah, the son of Jeho’ash, son of Ahazi’ah, at Beth-she’mesh, and came to Jerusalem, and broke down the wall of Jerusalem for four hundred cubits, from the E’phraim Gate to the Corner Gate.”", true, 13),
    blank(3, "the treasuries of the king’s house, also hostages, and he returned to _____.", "Sama’ria", 14, ["samaria"]),
    mc(1, "Which word correctly completes this RSV wording: “the treasuries of the king’s house, also hostages, and he returned to _____.”", ["Sama’ria", "Jehu", "Chronicles", "Gath-he’pher"], 14),
    word(2, "In verse 14, what word completes this phrase: “the treasuries of the king’s house, also hostages, and he returned to _____.”?", "Sama’ria", 14, ["samaria"]),
    tf(3, "The RSV does not state: “And he seized all the gold and silver, and all the vessels that were found in the house of the LORD and in the treasuries of the king’s house, also hostages, and he returned to Sama’ria.”", false, 14, "The quoted wording is the RSV text of this verse."),
    blank(1, "with Amazi’ah king of Judah, are they not written in the Book of the _____ of the Kings of Israel?", "Chronicles", 15, ["chronicles"]),
    mc(2, "Which word correctly completes this RSV wording: “with Amazi’ah king of Judah, are they not written in the Book of the _____ of the Kings of Israel?”", ["Chronicles", "Jeho-ad’din", "E’phraim", "Jonah"], 15),
    word(3, "In verse 15, what word completes this phrase: “with Amazi’ah king of Judah, are they not written in the Book of the _____ of the Kings of Israel?”?", "Chronicles", 15, ["chronicles"]),
    tf(1, "The RSV states: “ Now the rest of the acts of Jeho’ash which he did, and his might, and how he fought with Amazi’ah king of Judah, are they not written in the Book of the Chronicles of the Kings of Israel?”", true, 15),
    blank(2, "his fathers, and was buried in Sama’ria with the kings of Israel; and _____ his son reigned in his stead.", "Jerobo’am", 16, ["jeroboam"]),
    mc(3, "Which word correctly completes this RSV wording: “his fathers, and was buried in Sama’ria with the kings of Israel; and _____ his son reigned in his stead.”", ["Jerobo’am", "Lachish", "Jo’ash", "Salt"], 16),
    word(1, "In verse 16, what word completes this phrase: “his fathers, and was buried in Sama’ria with the kings of Israel; and _____ his son reigned in his stead.”?", "Jerobo’am", 16, ["jeroboam"]),
    tf(2, "The RSV does not state: “And Jeho’ash slept with his fathers, and was buried in Sama’ria with the kings of Israel; and Jerobo’am his son reigned in his stead.”", false, 16, "The quoted wording is the RSV text of this verse."),
    blank(3, "king of Judah, lived fifteen years after the death of Jeho’ash son of _____, king of Israel.", "Jeho’ahaz", 17, ["jehoahaz"]),
    mc(1, "Which word correctly completes this RSV wording: “king of Judah, lived fifteen years after the death of Jeho’ash son of _____, king of Israel.”", ["Jeho’ahaz", "Amit’tai", "David", "Give"], 17),
    word(2, "In verse 17, what word completes this phrase: “king of Judah, lived fifteen years after the death of Jeho’ash son of _____, king of Israel.”?", "Jeho’ahaz", 17, ["jehoahaz"]),
    tf(3, "The RSV states: “Amazi’ah the son of Jo’ash, king of Judah, lived fifteen years after the death of Jeho’ash son of Jeho’ahaz, king of Israel.”", true, 17),
    blank(1, "rest of the deeds of Amazi’ah, are they not written in the Book of the _____ of the Kings of Judah?", "Chronicles", 18, ["chronicles"]),
    mc(2, "Which word correctly completes this RSV wording: “rest of the deeds of Amazi’ah, are they not written in the Book of the _____ of the Kings of Judah?”", ["Chronicles", "Arabah", "Jerusalem", "Ahazi’ah"], 18),
    word(3, "In verse 18, what word completes this phrase: “rest of the deeds of Amazi’ah, are they not written in the Book of the _____ of the Kings of Judah?”?", "Chronicles", 18, ["chronicles"]),
    tf(1, "The RSV does not state: “Now the rest of the deeds of Amazi’ah, are they not written in the Book of the Chronicles of the Kings of Judah?”", false, 18, "The quoted wording is the RSV text of this verse."),
    blank(2, "And they made a conspiracy against him in _____, and he fled to Lachish. But they sent after him to Lachish, and slew", "Jerusalem", 19, ["jerusalem"]),
    mc(3, "Which word correctly completes this RSV wording: “And they made a conspiracy against him in _____, and he fled to Lachish. But they sent after him to Lachish, and slew”", ["Jerusalem", "Salt", "Ahazi’ah", "Elath"], 19),
    word(1, "In verse 19, what word completes this phrase: “And they made a conspiracy against him in _____, and he fled to Lachish. But they sent after him to Lachish, and slew”?", "Jerusalem", 19, ["jerusalem"]),
    tf(2, "The RSV states: “And they made a conspiracy against him in Jerusalem, and he fled to Lachish. But they sent after him to Lachish, and slew him there.”", true, 19),
    blank(3, "And they brought him upon horses; and he was buried in _____ with his fathers in the city of David.", "Jerusalem", 20, ["jerusalem"]),
    mc(1, "Which word correctly completes this RSV wording: “And they brought him upon horses; and he was buried in _____ with his fathers in the city of David.”", ["Jerusalem", "Lebanon", "Kings", "Damascus"], 20),
    word(2, "In verse 20, what word completes this phrase: “And they brought him upon horses; and he was buried in _____ with his fathers in the city of David.”?", "Jerusalem", 20, ["jerusalem"]),
    tf(3, "The RSV does not state: “And they brought him upon horses; and he was buried in Jerusalem with his fathers in the city of David.”", false, 20, "The quoted wording is the RSV text of this verse."),
    blank(1, "And all the people of Judah took _____, who was sixteen years old, and made him king instead of his father Amazi’ah.", "Azari’ah", 21, ["azariah"]),
    mc(2, "Which word correctly completes this RSV wording: “And all the people of Judah took _____, who was sixteen years old, and made him king instead of his father Amazi’ah.”", ["Azari’ah", "Gate", "Arabah", "Jerusalem"], 21),
    word(3, "In verse 21, what word completes this phrase: “And all the people of Judah took _____, who was sixteen years old, and made him king instead of his father Amazi’ah.”?", "Azari’ah", 21, ["azariah"]),
    tf(1, "The RSV states: “And all the people of Judah took Azari’ah, who was sixteen years old, and made him king instead of his father Amazi’ah.”", true, 21),
    blank(2, "He built _____ and restored it to Judah, after the king slept with his fathers.", "Elath", 22, ["elath"]),
    mc(3, "Which word correctly completes this RSV wording: “He built _____ and restored it to Judah, after the king slept with his fathers.”", ["Elath", "Israel", "Jeho’ash", "Sama’ria"], 22),
    word(1, "In verse 22, what word completes this phrase: “He built _____ and restored it to Judah, after the king slept with his fathers.”?", "Elath", 22, ["elath"]),
    tf(2, "The RSV does not state: “He built Elath and restored it to Judah, after the king slept with his fathers.”", false, 22, "The quoted wording is the RSV text of this verse."),
    blank(3, "In the fifteenth year of Amazi’ah the son of Jo’ash, king of Judah, _____ the son of Jo’ash, king of Israel, began to reign in Sama’ria, and he", "Jerobo’am", 23, ["jeroboam"]),
    mc(1, "Which word correctly completes this RSV wording: “In the fifteenth year of Amazi’ah the son of Jo’ash, king of Judah, _____ the son of Jo’ash, king of Israel, began to reign in Sama’ria, and he”", ["Jerobo’am", "Gath-he’pher", "Moses", "Give"], 23),
    word(2, "In verse 23, what word completes this phrase: “In the fifteenth year of Amazi’ah the son of Jo’ash, king of Judah, _____ the son of Jo’ash, king of Israel, began to reign in Sama’ria, and he”?", "Jerobo’am", 23, ["jeroboam"]),
    tf(3, "The RSV states: “In the fifteenth year of Amazi’ah the son of Jo’ash, king of Judah, Jerobo’am the son of Jo’ash, king of Israel, began to reign in Sama’ria, and he reigned forty-one years.”", true, 23),
    blank(1, "evil in the sight of the LORD; he did not depart from all the sins of _____ the son of Nebat, which he made Israel to sin.", "Jerobo’am", 24, ["jeroboam"]),
    mc(2, "Which word correctly completes this RSV wording: “evil in the sight of the LORD; he did not depart from all the sins of _____ the son of Nebat, which he made Israel to sin.”", ["Jerobo’am", "Judah", "Jeho’ahaz", "Sama’ria"], 24),
    word(3, "In verse 24, what word completes this phrase: “evil in the sight of the LORD; he did not depart from all the sins of _____ the son of Nebat, which he made Israel to sin.”?", "Jerobo’am", 24, ["jeroboam"]),
    tf(1, "The RSV does not state: “And he did what was evil in the sight of the LORD; he did not depart from all the sins of Jerobo’am the son of Nebat, which he made Israel to sin.”", false, 24, "The quoted wording is the RSV text of this verse."),
    blank(2, "spoke by his servant Jonah the son of Amit’tai, the prophet, who was from _____.", "Gath-he’pher", 25, ["gath-hepher"]),
    mc(3, "Which word correctly completes this RSV wording: “spoke by his servant Jonah the son of Amit’tai, the prophet, who was from _____.”", ["Gath-he’pher", "Lachish", "Jeho’ash", "Amit’tai"], 25),
    word(1, "In verse 25, what word completes this phrase: “spoke by his servant Jonah the son of Amit’tai, the prophet, who was from _____.”?", "Gath-he’pher", 25, ["gath-hepher"]),
    tf(2, "The RSV states: “He restored the border of Israel from the entrance of Hamath as far as the Sea of the Arabah, according to the word of the LORD, the God of Israel, which he spoke by his servant Jonah the son of Amit’tai, the prophet, who was from Gath-he’pher.”", true, 25),
    blank(3, "For the LORD saw that the affliction of _____ was very bitter, for there was none left, bond or free, and there was", "Israel", 26, ["israel"]),
    mc(1, "Which word correctly completes this RSV wording: “For the LORD saw that the affliction of _____ was very bitter, for there was none left, bond or free, and there was”", ["Israel", "Chronicles", "Damascus", "Valley"], 26),
    word(2, "In verse 26, what word completes this phrase: “For the LORD saw that the affliction of _____ was very bitter, for there was none left, bond or free, and there was”?", "Israel", 26, ["israel"]),
    tf(3, "The RSV does not state: “For the LORD saw that the affliction of Israel was very bitter, for there was none left, bond or free, and there was none to help Israel.”", false, 26, "The quoted wording is the RSV text of this verse."),
    blank(1, "the name of Israel from under heaven, so he saved them by the hand of _____ the son of Jo’ash.", "Jerobo’am", 27, ["jeroboam"]),
    mc(2, "Which word correctly completes this RSV wording: “the name of Israel from under heaven, so he saved them by the hand of _____ the son of Jo’ash.”", ["Jerobo’am", "Corner", "Jonah", "Jeho-ad’din"], 27),
    word(3, "In verse 27, what word completes this phrase: “the name of Israel from under heaven, so he saved them by the hand of _____ the son of Jo’ash.”?", "Jerobo’am", 27, ["jeroboam"]),
    tf(1, "The RSV states: “But the LORD had not said that he would blot out the name of Israel from under heaven, so he saved them by the hand of Jerobo’am the son of Jo’ash.”", true, 27),
    blank(2, "which had belonged to Judah, are they not written in the Book of the _____ of the Kings of Israel?", "Chronicles", 28, ["chronicles"]),
    mc(3, "Which word correctly completes this RSV wording: “which had belonged to Judah, are they not written in the Book of the _____ of the Kings of Israel?”", ["Chronicles", "Damascus", "E’domites", "Kings"], 28),
    word(1, "In verse 28, what word completes this phrase: “which had belonged to Judah, are they not written in the Book of the _____ of the Kings of Israel?”?", "Chronicles", 28, ["chronicles"]),
    tf(2, "The RSV does not state: “Now the rest of the acts of Jerobo’am, and all that he did, and his might, how he fought, and how he recovered for Israel Damascus and Hamath, which had belonged to Judah, are they not written in the Book of the Chronicles of the Kings of Israel?”", false, 28, "The quoted wording is the RSV text of this verse."),
    blank(3, "And Jerobo’am slept with his fathers, the kings of Israel, and _____ his son reigned in his stead.", "Zechari’ah", 29, ["zechariah"]),
    mc(1, "Which word correctly completes this RSV wording: “And Jerobo’am slept with his fathers, the kings of Israel, and _____ his son reigned in his stead.”", ["Zechari’ah", "Jerusalem", "Ahazi’ah", "Hamath"], 29),
    word(2, "In verse 29, what word completes this phrase: “And Jerobo’am slept with his fathers, the kings of Israel, and _____ his son reigned in his stead.”?", "Zechari’ah", 29, ["zechariah"]),
    tf(3, "The RSV states: “And Jerobo’am slept with his fathers, the kings of Israel, and Zechari’ah his son reigned in his stead.”", true, 29),
    blank(1, "In the second year of Jo’ash the son of _____, king of Israel, Amazi’ah the son of Jo’ash, king of Judah, began to reign.", "Jo’ahaz", 1, ["joahaz"]),
    mc(2, "Select the missing RSV word: “He was _____ years old when he began to reign, and he reigned twenty-nine years in”", ["twenty-five", "passed", "belongs", "returned"], 2),
    word(3, "What missing word belongs in this verse 3 clause: “he did what was right in the eyes of the LORD, yet not like David his _____; he did in all things as Jo’ash his father had done.”?", "father", 3, ["father"]),
    tf(1, "This wording appears in verse 4: “But the high places were not removed; the people still sacrificed and burned incense on the high places.”", true, 4),
    mc(2, "Which two plants appeared in Jehoash’s parable answering Amaziah’s challenge?", ["A thistle and a cedar on Lebanon", "A vine and a fig tree", "An olive tree and a bramble", "A reed and an oak"], 9),
    mc(3, "Which prophet foretold the restoration of Israel’s border under Jeroboam II?", ["Jonah son of Amittai from Gath-hepher", "Amos of Tekoa", "Elisha son of Shaphat", "Jehu son of Hanani"], 25),
  ],
};

export default bank;
