import { mc, blank, word, tf, type ChapterBank, sa } from './types'
const bank: ChapterBank = { book: '2 Kings', chapter: 18, tag: 'quiz-v2-2kings-18', rows: [
  mc(1,'Who began reigning over Judah in Hoshea’s third year?',['Hezekiah son of Ahaz','Ahaz','Eliakim','Sennacherib'],1),
  blank(1,'_____ the son of Ahaz, king of Judah, began to reign.','Hezeki’ah',1,['Hezekiah']),
  word(3,'Who was Hezekiah’s father?','Ahaz',1), tf(2,'Hezekiah became king over Israel in Samaria.',false,1,'Hezekiah son of Ahaz began to reign as king of Judah.'),
  mc(2,'How old was Hezekiah when he began to reign?',['Twenty-five','Twenty-nine','Sixteen','Thirty'],2),
  blank(3,'he reigned _____ years in Jerusalem.','twenty-nine',2,['29']),
  word(2,'What was Hezekiah’s mother’s name?','Abi',2), tf(1,'Abi was the daughter of Zechariah.',true,2),
  mc(1,'Whose faithful example did Hezekiah follow?',['David’s','Ahaz’s','Hoshea’s','Solomon’s idolatry'],3),
  blank(2,'he did what was _____ in the eyes of the LORD','right',3),
  word(1,'Who is called Hezekiah’s father in the comparison?','David',3), tf(3,'Hezekiah followed the evil example of Ahaz.',false,3,'He did what was right before the LORD according to all that David had done.'),
  mc(1,'Why did Hezekiah break Moses’ bronze serpent?',['Israel had been burning incense to it','Assyria demanded it','It was broken already','It blocked the temple gate'],4),
  blank(2,'it was called _____.','Nehush’tan',4,['Nehushtan']),
  word(1,'Who had made the bronze serpent?','Moses',4), tf(2,'Hezekiah removed high places, pillars, and the Asherah.',true,4),
  mc(3,'What was Nehushtan?',['The bronze serpent used as an incense object','A priest serving at a high-place shrine','An idol brought into Judah from Assyria','A ceremonial entrance into the temple'],4),
  mc(1,'How is Hezekiah’s trust ranked among Judah’s kings?',['None before or after was like him','Only Ahaz exceeded him','He ranked below every king','The text gives no comparison'],5),
  blank(2,'He trusted in the LORD the God of _____.','Israel',5),
  sa(1,'What distinguished Hezekiah?','his trust in the LORD',5,['trust in the LORD']), tf(2,'Hezekiah’s trust was said to be ordinary among Judah’s kings.',false,5,'No king of Judah before or after him was said to be like him in trust.'),
  mc(3,'What makes the statement about Hezekiah exceptional?',['It compares him with every other king of Judah','It compares him only with his father Ahaz','It describes only his physical military strength','It identifies him as a king of northern Israel'],5),
  mc(1,'What did Hezekiah keep?',['The commandments given through Moses','The customs established by Assyrian kings','The altar regulations introduced by Ahaz','The worship practiced at Israel’s high places'],6),
  blank(2,'For he held _____ to the LORD','fast',6), word(1,'From whom did Hezekiah not depart?','LORD',6,['the LORD']),
  tf(3,'Hezekiah remained faithful to the LORD’s commands.',true,6),
  mc(1,'Why did Hezekiah prosper wherever he went?',['The LORD was with him','Egypt supplied him','Assyria protected him','Philistia paid him'],7),
  blank(2,'He rebelled against the king of _____.','Assyria',7), sa(1,'Whom did Hezekiah refuse to serve?','the king of Assyria',7,['Assyria’s king']),
  tf(3,'Hezekiah continued serving Assyria without resistance.',false,7,'He rebelled against Assyria’s king and would not serve him.'),
  mc(1,'Whom did Hezekiah defeat as far as Gaza?',['The Philistines','The Assyrians','The Moabites','The Syrians'],8),
  blank(2,'He smote the Philistines as far as _____.','Gaza',8), sa(1,'How broad was the campaign?','from watchtower to fortified city',8),
  tf(3,'Hezekiah struck Philistine territory.',true,8),
  mc(1,'Who besieged Samaria during Hezekiah’s fourth year?',['Shalmaneser king of Assyria','Sennacherib','Pharaoh','The Rabshakeh'],9),
  blank(2,'_____ king of Assyria came up against Sama’ria','Shalmane’ser',9,['Shalmaneser']), word(1,'Which city was besieged?','Samaria',9),
  tf(3,'The siege of Samaria began in Hoshea’s ninth year.',false,9,'It began in Hoshea’s seventh year and Hezekiah’s fourth year.'),
  mc(1,'How long before Samaria was taken?',['Three years','One year','Nine years','Fourteen years'],10),
  blank(2,'at the end of _____ years he took it.','three',10,['3']), sa(1,'In which year of Hoshea did Samaria fall?','the ninth year',10,['ninth']),
  tf(3,'Samaria fell in Hezekiah’s sixth year.',true,10),
  mc(1,'Where did Assyria resettle the Israelites?',['Halah, Habor, and Median cities','The neighboring lands of Egypt and Cush','Only the Syrian capital city of Damascus','The Judean capital city of Jerusalem'],11),
  blank(2,'put them in Halah, and on the _____','Habor',11), word(1,'The Habor was the river of what place?','Gozan',11),
  tf(3,'All the exiles were settled together in the city of Babylon.',false,11,'They were placed in Halah, by the Habor in Gozan, and in cities of the Medes.'),
  mc(1,'Why did Israel suffer exile?',['They disobeyed and broke the covenant','They lacked sufficient horses for warfare','The kingdom of Judah unexpectedly attacked them','They carefully obeyed everything Moses commanded'],12),
  blank(2,'they neither listened nor _____.','obeyed',12), sa(1,'Whose commands had they violated?','Moses the servant of the LORD’s',12,['Moses']),
  tf(3,'Israel’s exile is tied to covenant disobedience.',true,12),
  mc(1,'Who captured Judah’s fortified cities in Hezekiah’s fourteenth year?',['Sennacherib king of Assyria','Shalmaneser, the earlier Assyrian ruler','Hoshea, the final king of northern Israel','Pekah, the former king of northern Israel'],13),
  blank(2,'_____ king of Assyria came up','Sennach’erib',13,['Sennacherib']), sa(1,'What kind of cities did he take?','fortified cities of Judah',13),
  tf(3,'Sennacherib’s army avoided Judah’s fortified cities.',false,13,'Sennacherib came up against all the fortified cities of Judah and took them.'),
  mc(1,'Where did Hezekiah send his submission to Assyria?',['Lachish','Samaria','Egypt','Gaza'],14),
  blank(2,'three hundred talents of silver and _____ talents of gold.','thirty',14,['30']), sa(1,'What did Hezekiah admit?','I have done wrong',14),
  tf(3,'Hezekiah agreed to bear whatever Assyria imposed.',true,14),
  mc(1,'What silver did Hezekiah give Assyria?',['All the temple and royal treasury silver','Only the silver belonging personally to Hezekiah','Tribute supplied to Judah by the Egyptians','No silver, because only gold was demanded'],15),
  blank(2,'all the _____ that was found in the house of the LORD','silver',15), sa(1,'Which two treasuries were emptied?','the LORD’s house and the king’s house',15),
  tf(3,'Hezekiah protected all temple silver from the Assyrian payment.',false,15,'He gave all the silver found in both the LORD’s house and the royal treasury.'),
  mc(1,'What did Hezekiah strip from the temple?',['Gold from doors and doorposts','Bronze pillars','The ark','Curtains'],16),
  blank(2,'stripped the _____ from the doors','gold',16), sa(1,'To whom was the stripped gold given?','the king of Assyria',16,['Assyria’s king']),
  tf(3,'Hezekiah had previously overlaid the doorposts.',true,16),
  mc(1,'Which three Assyrian officials came with a great army?',['Tartan, Rabsaris, and Rabshakeh','Eliakim, Shebna, and Joah','Sennacherib, Hoshea, and Pekah','Isaiah, Hilkiah, and Asaph'],17),
  blank(2,'stood by the conduit of the _____ pool','upper',17), word(1,'From which city did the army come?','Lachish',17),
  tf(3,'The Assyrian delegation entered the temple before delivering its message.',false,17,'They stopped by the upper-pool conduit on the highway to the Fuller’s Field.'),
  mc(1,'Which Judean officials met the Assyrians?',['Eliakim, Shebna, and Joah','Isaiah, Hezekiah, and Hilkiah','Uriah, Ahaz, and Abi','Hoshea, Elah, and Asaph'],18),
  blank(2,'Shebnah the _____','secretary',18), word(1,'What office did Joah hold?','recorder',18),
  tf(3,'Eliakim was over the household.',true,18),
  mc(1,'What did the Rabshakeh question first?',['Hezekiah’s basis for confidence','The city’s food supply','Judah’s genealogy','Temple dimensions'],19),
  blank(2,'On what do you rest this _____ of yours?','confidence',19), sa(1,'Whom did he call the great king?','the king of Assyria',19,['Assyria’s king']),
  tf(3,'The Rabshakeh presented himself as an independent messenger.',false,19,'He explicitly delivered a message from the great king, the king of Assyria.'),
  mc(1,'What did the Rabshakeh dismiss as insufficient for war?',['Mere words','Chariots','Fortified walls','Gold'],20),
  blank(2,'mere words are _____ and power for war','strategy',20), word(1,'What action did he accuse Hezekiah of?','rebellion',20,['rebelling against Assyria']),
  tf(3,'The speech challenged Judah’s military confidence.',true,20),
  mc(1,'What image did the Rabshakeh use for Egypt?',['A broken reed that pierces the hand','A tall cedar able to withstand every storm','A fortified rock providing reliable protection','A fruitful vine supplying strength and abundance'],21),
  blank(2,'Egypt, that broken _____ of a staff','reed',21), word(1,'Who represented Egypt in the comparison?','Pharaoh',21),
  tf(2,'The Rabshakeh portrayed Egypt as a strong and reliable staff.',false,21,'He called Egypt a broken reed that would pierce the hand of anyone leaning on it.'),
  mc(3,'Why was Egypt a “broken reed”?',['It would fail and harm anyone depending on it','It had conquered Assyria','It supplied Judah’s strongest army','It represented the LORD'],21),
  mc(1,'How did the Rabshakeh misinterpret Hezekiah’s reform?',['He said removing high places offended the LORD','He praised Hezekiah for centralizing worship','He denied that any high places had existed','He identified the high places as Assyrian shrines'],22),
  blank(2,'You shall worship before this _____ in Jerusalem.','altar',22), word(1,'Who had removed the high places?','Hezekiah',22),
  tf(3,'The Rabshakeh portrayed reform as a reason not to trust the LORD.',true,22),
  mc(1,'How many horses did Assyria mockingly offer?',['Two thousand','Three hundred','Thirty','Ten thousand'],23),
  blank(2,'I will give you _____ thousand horses','two',23,['2']), word(1,'What could Judah supposedly not supply?','riders',23),
  tf(3,'The offer of two thousand horses praised Judah’s abundance of riders.',false,23,'The offer mocked Judah because it supposedly could not supply riders for the horses.'),
  mc(1,'On whom did Judah rely for chariots and horsemen?',['Egypt','Assyria','Philistia','Israel'],24),
  blank(2,'repulse a single _____','captain',24), sa(1,'Whose least servants were invoked?','the Assyrian king’s',24),
  tf(3,'The Rabshakeh claimed Judah could not defeat even a minor Assyrian officer.',true,24),
  mc(1,'Whose authority did the Rabshakeh falsely claim for the invasion?',['The LORD’s','Pharaoh’s','Hezekiah’s','Isaiah’s'],25),
  blank(2,'Go up against this land, and _____ it.','destroy',25), sa(1,'What did he claim the LORD told him to do?','attack and destroy the land',25),
  tf(3,'The Assyrian speaker admitted that the LORD opposed his invasion.',false,25,'He claimed that the LORD had told him to attack and destroy the land.'),
  mc(1,'Which language did Judah’s officials request?',['Aramaic','Hebrew','Egyptian','Assyrian'],26),
  blank(2,'do not speak to us in the language of _____.','Judah',26), sa(1,'Why did they request Aramaic?','so the wall’s people would not understand',26),
  tf(3,'The officials themselves understood Aramaic.',true,26),
  mc(1,'Whom did the Rabshakeh say his message also targeted?',['The men sitting on the wall','Only Hezekiah','Only Eliakim','Egyptian envoys'],27),
  blank(2,'the men sitting on the _____.','wall',27), sa(1,'What siege suffering did he graphically threaten?','eating dung and drinking urine',27),
  tf(3,'The Rabshakeh agreed to speak privately only to Judah’s officials.',false,27,'He said his message also targeted the men sitting on the wall.'),
  mc(1,'How did the Rabshakeh answer the language request?',['He shouted loudly in Judah’s language','He switched to Aramaic','He became silent','He wrote privately'],28),
  blank(2,'called out in a _____ voice','loud',28), sa(1,'Whose word did he command the people to hear?','the king of Assyria’s',28,['the word of Assyria’s king']),
  tf(2,'He deliberately addressed the people in their own language.',true,28),
  mc(3,'Why was his language choice defiant?',['He broadcast what officials wanted kept private','He was entirely unable to communicate in Aramaic','His intended audience consisted only of Assyrians','He wanted Jerusalem’s people to praise Hezekiah'],28),
  mc(1,'Whom did Assyria tell the people not to trust for deliverance?',['Hezekiah','Pharaoh','The Rabshakeh','Shebna'],29),
  blank(2,'Do not let _____ deceive you','Hezeki’ah',29,['Hezekiah']), sa(1,'From whose hand did he say Hezekiah could not deliver them?','the Assyrian king’s',29),
  tf(3,'The speech urged Jerusalem’s people to trust Hezekiah.',false,29,'The Rabshakeh told them not to let Hezekiah deceive or deliver them.'),
  mc(1,'What promise did the Rabshakeh ridicule?',['The LORD will surely deliver Jerusalem','Egypt will conquer Assyria','Samaria will return','Hezekiah will pay tribute'],30),
  blank(2,'this city will not be _____ into the hand of the king of Assyria','given',30), word(1,'Whom did Hezekiah urge the people to rely upon?','LORD',30,['the LORD']),
  tf(3,'The Rabshakeh attacked trust in divine deliverance.',true,30),
  mc(1,'What immediate prosperity did Assyria promise if people surrendered?',['Their own vines, figs, and cistern water','Temple gold','Egyptian horses','Freedom from tribute forever'],31),
  blank(2,'Make your _____ with me','peace',31), sa(1,'What water source would each person use?','his own cistern',31),
  tf(3,'The Assyrian invitation told Jerusalem’s people to remain behind the walls.',false,31,'It urged them to make peace and come out to enjoy their vines, figs, and cisterns.'),
  mc(1,'Where did Assyria ultimately promise to take them?',['A land like their own','Back to Egypt','Into Jerusalem','To Samaria only'],32),
  blank(2,'a land of olive trees and _____.','honey',32), sa(1,'What warning was repeated?','Do not listen to Hezekiah',32),
  tf(3,'The promised relocation was presented as life rather than death.',true,32),
  mc(1,'What precedent did the Rabshakeh cite?',['No national god had delivered from Assyria','Egypt had previously conquered Assyria’s army','Samaria had successfully remained independent','The kingdom of Judah had never faced invasion'],33),
  blank(2,'delivered his land out of the hand of the king of _____.','Assyria',33), sa(1,'Whose gods did he challenge?','the gods of the nations',33),
  tf(3,'The Rabshakeh said Assyria’s past victories gave Jerusalem reason for hope.',false,33,'He cited defeated nations and their gods to discourage trust in Jerusalem’s deliverance.'),
  mc(1,'Which conquered peoples’ gods were named?',['Hamath, Arpad, Sepharvaim, Hena, and Ivvah','The gods worshiped in Egypt, Cush, and Edom','Only the gods belonging to Moab and Ammon','The gods identified with the kingdoms of Judah and Israel'],34),
  blank(2,'Where are the gods of _____ and Arpad?','Hamath',34), word(1,'Which captured city was mentioned as not delivered?','Samaria',34),
  tf(3,'The Rabshakeh claimed those gods had failed.',true,34),
  mc(1,'What final comparison blasphemed the LORD?',['He treated the LORD like defeated national gods','He praised the LORD above Assyria','He asked the LORD for help','He promised temple restoration'],35),
  blank(2,'that the LORD should deliver _____ out of my hand?','Jerusalem',35), sa(1,'What did no other gods deliver?','their countries',35),
  tf(3,'The Rabshakeh distinguished the LORD as stronger than every defeated god.',false,35,'He blasphemously treated the LORD like the gods that had failed to deliver their lands.'),
  mc(1,'How did Jerusalem’s people respond?',['They remained silent','They shouted back','They surrendered','They attacked'],36),
  blank(2,'answered him not a _____.','word',36), sa(1,'Who had commanded silence?','the king',36,['Hezekiah']),
  tf(3,'The people obeyed the command not to answer.',true,36),
  mc(1,'How did the officials return to Hezekiah?',['With clothes torn','Celebrating','With Assyrian gifts','As prisoners'],37),
  blank(2,'came to Hezeki’ah with their clothes _____.','rent',37), sa(1,'Whose words did they report?','the Rabshakeh’s',37,['Rabshakeh']),
  tf(3,'Eliakim, Shebna, and Joah reported the speech.',true,37),
] }
export default bank
