// 2 Kings 4 — quiz bank (RSV). Four verse-anchored forms per verse.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: "2 Kings",
  chapter: 4,
  tag: "quiz-v2-2kings-4",
  rows: [
    blank(2, "Now the wife of one of the sons of the prophets cried to _____, \"Your servant my husband is dead; and you know that your servant feared", "Eli’sha", 1, ["elisha"]),
    mc(3, "Which word correctly completes this RSV wording: “Now the wife of one of the sons of the prophets cried to _____, \"Your servant my husband is dead; and you know that your servant feared”", ["Eli’sha", "Well", "Pour", "Send"], 1),
    word(1, "In verse 1, what word completes this phrase: “Now the wife of one of the sons of the prophets cried to _____, \"Your servant my husband is dead; and you know that your servant feared”?", "Eli’sha", 1, ["elisha"]),
    tf(2, "The RSV states: “Now the wife of one of the sons of the prophets cried to Eli’sha, \"Your servant my husband is dead; and you know that your servant feared the LORD, but the creditor has come to take my two children to be his slaves.\"”", true, 1),
    blank(3, "And _____ said to her, \"What shall I do for you? Tell me; what have you in the house?\"", "Eli’sha", 2, ["elisha"]),
    mc(1, "Which word correctly completes this RSV wording: “And _____ said to her, \"What shall I do for you? Tell me; what have you in the house?\"”", ["Eli’sha", "Gird", "Call", "Take"], 2),
    word(2, "In verse 2, what word completes this phrase: “And _____ said to her, \"What shall I do for you? Tell me; what have you in the house?\"”?", "Eli’sha", 2, ["elisha"]),
    tf(3, "The RSV does not state: “And Eli’sha said to her, \"What shall I do for you? Tell me; what have you in the house?\" And she said, \"Your maidservant has nothing in the house, except a jar of oil.\"”", false, 2, "The quoted wording is the RSV text of this verse."),
    blank(1, "Then he said, \"Go outside, borrow vessels of all your _____, empty vessels and not too few.", "neighbors", 3, ["neighbors"]),
    mc(2, "Which word correctly completes this RSV wording: “Then he said, \"Go outside, borrow vessels of all your _____, empty vessels and not too few.”", ["neighbors", "borrow", "poured", "rest"], 3),
    word(3, "In verse 3, what word completes this phrase: “Then he said, \"Go outside, borrow vessels of all your _____, empty vessels and not too few.”?", "neighbors", 3, ["neighbors"]),
    tf(1, "The RSV states: “Then he said, \"Go outside, borrow vessels of all your neighbors, empty vessels and not too few.”", true, 3),
    blank(2, "Then go in, and shut the door upon _____ and your sons, and pour into all these vessels; and when one is full,", "yourself", 4, ["yourself"]),
    mc(3, "Which word correctly completes this RSV wording: “Then go in, and shut the door upon _____ and your sons, and pour into all these vessels; and when one is full,”", ["yourself", "full", "told", "whenever"], 4),
    word(1, "In verse 4, what word completes this phrase: “Then go in, and shut the door upon _____ and your sons, and pour into all these vessels; and when one is full,”?", "yourself", 4, ["yourself"]),
    tf(2, "The RSV does not state: “Then go in, and shut the door upon yourself and your sons, and pour into all these vessels; and when one is full, set it aside.\"”", false, 4, "The quoted wording is the RSV text of this verse."),
    blank(3, "So she went from him and shut the door upon _____ and her sons; and as she poured they brought the vessels to her.", "herself", 5, ["herself"]),
    mc(1, "Which word correctly completes this RSV wording: “So she went from him and shut the door upon _____ and her sons; and as she poured they brought the vessels to her.”", ["herself", "vessel", "lived", "make"], 5),
    word(2, "In verse 5, what word completes this phrase: “So she went from him and shut the door upon _____ and her sons; and as she poured they brought the vessels to her.”?", "herself", 5, ["herself"]),
    tf(3, "The RSV states: “So she went from him and shut the door upon herself and her sons; and as she poured they brought the vessels to her.”", true, 5),
    blank(1, "When the vessels were full, she said to her son, \"_____ me another vessel.\" And he said to her, \"There is not another.\" Then the", "Bring", 6, ["bring"]),
    mc(2, "Which word correctly completes this RSV wording: “When the vessels were full, she said to her son, \"_____ me another vessel.\" And he said to her, \"There is not another.\" Then the”", ["Bring", "Geha’zi", "Take", "Carry"], 6),
    word(3, "In verse 6, what word completes this phrase: “When the vessels were full, she said to her son, \"_____ me another vessel.\" And he said to her, \"There is not another.\" Then the”?", "Bring", 6, ["bring"]),
    tf(1, "The RSV does not state: “When the vessels were full, she said to her son, \"Bring me another vessel.\" And he said to her, \"There is not another.\" Then the oil stopped flowing.”", false, 6, "The quoted wording is the RSV text of this verse."),
    blank(2, "and told the man of God, and he said, \"Go, sell the oil and pay your _____, and you and your sons can live on the rest.\"", "debts", 7, ["debts"]),
    mc(3, "Which word correctly completes this RSV wording: “and told the man of God, and he said, \"Go, sell the oil and pay your _____, and you and your sons can live on the rest.\"”", ["debts", "whenever", "table", "done"], 7),
    word(1, "In verse 7, what word completes this phrase: “and told the man of God, and he said, \"Go, sell the oil and pay your _____, and you and your sons can live on the rest.\"”?", "debts", 7, ["debts"]),
    tf(2, "The RSV states: “She came and told the man of God, and he said, \"Go, sell the oil and pay your debts, and you and your sons can live on the rest.\"”", true, 7),
    blank(3, "One day _____ went on to Shunem, where a wealthy woman lived, who urged him to eat some", "Eli’sha", 8, ["elisha"]),
    mc(1, "Which word correctly completes this RSV wording: “One day _____ went on to Shunem, where a wealthy woman lived, who urged him to eat some”", ["Eli’sha", "Take", "Well", "Pour"], 8),
    word(2, "In verse 8, what word completes this phrase: “One day _____ went on to Shunem, where a wealthy woman lived, who urged him to eat some”?", "Eli’sha", 8, ["elisha"]),
    tf(3, "The RSV does not state: “One day Eli’sha went on to Shunem, where a wealthy woman lived, who urged him to eat some food. So whenever he passed that way, he would turn in there to eat food.”", false, 8, "The quoted wording is the RSV text of this verse."),
    blank(1, "And she said to her husband, \"_____ now, I perceive that this is a holy man of God, who is continually passing", "Behold", 9, ["behold"]),
    mc(2, "Which word correctly completes this RSV wording: “And she said to her husband, \"_____ now, I perceive that this is a holy man of God, who is continually passing”", ["Behold", "Shunem", "Gird", "Call"], 9),
    word(3, "In verse 9, what word completes this phrase: “And she said to her husband, \"_____ now, I perceive that this is a holy man of God, who is continually passing”?", "Behold", 9, ["behold"]),
    tf(1, "The RSV states: “And she said to her husband, \"Behold now, I perceive that this is a holy man of God, who is continually passing our way.”", true, 9),
    blank(2, "walls, and put there for him a bed, a table, a chair, and a lamp, so that _____ he comes to us, he can go in there.\"", "whenever", 10, ["whenever"]),
    mc(3, "Which word correctly completes this RSV wording: “walls, and put there for him a bed, a table, a chair, and a lamp, so that _____ he comes to us, he can go in there.\"”", ["whenever", "before", "dwell", "following"], 10),
    word(1, "In verse 10, what word completes this phrase: “walls, and put there for him a bed, a table, a chair, and a lamp, so that _____ he comes to us, he can go in there.\"”?", "whenever", 10, ["whenever"]),
    tf(2, "The RSV does not state: “Let us make a small roof chamber with walls, and put there for him a bed, a table, a chair, and a lamp, so that whenever he comes to us, he can go in there.\"”", false, 10, "The quoted wording is the RSV text of this verse."),
    blank(3, "One day he came there, and he turned into the _____ and rested there.", "chamber", 11, ["chamber"]),
    mc(1, "Which word correctly completes this RSV wording: “One day he came there, and he turned into the _____ and rested there.”", ["chamber", "king", "embrace", "mother"], 11),
    word(2, "In verse 11, what word completes this phrase: “One day he came there, and he turned into the _____ and rested there.”?", "chamber", 11, ["chamber"]),
    tf(3, "The RSV states: “One day he came there, and he turned into the chamber and rested there.”", true, 11),
    blank(1, "And he said to Geha’zi his servant, \"Call this _____.\" When he had called her, she stood before him.", "Shu’nammite", 12, ["shunammite"]),
    mc(2, "Which word correctly completes this RSV wording: “And he said to Geha’zi his servant, \"Call this _____.\" When he had called her, she stood before him.”", ["Shu’nammite", "Carmel", "Ba’al-shal’ishah", "Behold"], 12),
    word(3, "In verse 12, what word completes this phrase: “And he said to Geha’zi his servant, \"Call this _____.\" When he had called her, she stood before him.”?", "Shu’nammite", 12, ["shunammite"]),
    tf(1, "The RSV does not state: “And he said to Geha’zi his servant, \"Call this Shu’nammite.\" When he had called her, she stood before him.”", false, 12, "The quoted wording is the RSV text of this verse."),
    blank(2, "you? Would you have a word spoken on your behalf to the king or to the _____ of the army?\" She answered, \"I dwell among my own people.\"", "commander", 13, ["commander"]),
    mc(3, "Which word correctly completes this RSV wording: “you? Would you have a word spoken on your behalf to the king or to the _____ of the army?\" She answered, \"I dwell among my own people.\"”", ["commander", "about", "noon", "sabbath"], 13),
    word(1, "In verse 13, what word completes this phrase: “you? Would you have a word spoken on your behalf to the king or to the _____ of the army?\" She answered, \"I dwell among my own people.\"”?", "commander", 13, ["commander"]),
    tf(2, "The RSV states: “And he said to him, \"Say now to her, See, you have taken all this trouble for us; what is to be done for you? Would you have a word spoken on your behalf to the king or to the commander of the army?\" She answered, \"I dwell among my own people.\"”", true, 13),
    blank(3, "And he said, \"What then is to be done for her?\" _____ answered, \"Well, she has no son, and her husband is old.\"", "Geha’zi", 14, ["gehazi"]),
    mc(1, "Which word correctly completes this RSV wording: “And he said, \"What then is to be done for her?\" _____ answered, \"Well, she has no son, and her husband is old.\"”", ["Geha’zi", "Pour", "Send", "Eli’sha"], 14),
    word(2, "In verse 14, what word completes this phrase: “And he said, \"What then is to be done for her?\" _____ answered, \"Well, she has no son, and her husband is old.\"”?", "Geha’zi", 14, ["gehazi"]),
    tf(3, "The RSV does not state: “And he said, \"What then is to be done for her?\" Geha’zi answered, \"Well, she has no son, and her husband is old.\"”", false, 14, "The quoted wording is the RSV text of this verse."),
    blank(1, "He said, \"_____ her.\" And when he had called her, she stood in the doorway.", "Call", 15, ["call"]),
    mc(2, "Which word correctly completes this RSV wording: “He said, \"_____ her.\" And when he had called her, she stood in the doorway.”", ["Call", "Mount", "Bring", "Gird"], 15),
    word(3, "In verse 15, what word completes this phrase: “He said, \"_____ her.\" And when he had called her, she stood in the doorway.”?", "Call", 15, ["call"]),
    tf(1, "The RSV states: “He said, \"Call her.\" And when he had called her, she stood in the doorway.”", true, 15),
    blank(2, "a son.\" And she said, \"No, my lord, O man of God; do not lie to your _____.\"", "maidservant", 16, ["maidservant"]),
    mc(3, "Which word correctly completes this RSV wording: “a son.\" And she said, \"No, my lord, O man of God; do not lie to your _____.\"”", ["maidservant", "brought", "chamber", "doorway"], 16),
    word(1, "In verse 16, what word completes this phrase: “a son.\" And she said, \"No, my lord, O man of God; do not lie to your _____.\"”?", "maidservant", 16, ["maidservant"]),
    tf(2, "The RSV does not state: “And he said, \"At this season, when the time comes round, you shall embrace a son.\" And she said, \"No, my lord, O man of God; do not lie to your maidservant.\"”", false, 16, "The quoted wording is the RSV text of this verse."),
    blank(3, "conceived, and she bore a son about that time the following spring, as _____ had said to her.", "Eli’sha", 17, ["elisha"]),
    mc(1, "Which word correctly completes this RSV wording: “conceived, and she bore a son about that time the following spring, as _____ had said to her.”", ["Eli’sha", "Give", "Urge", "Bring"], 17),
    word(2, "In verse 17, what word completes this phrase: “conceived, and she bore a son about that time the following spring, as _____ had said to her.”?", "Eli’sha", 17, ["elisha"]),
    tf(3, "The RSV states: “But the woman conceived, and she bore a son about that time the following spring, as Eli’sha had said to her.”", true, 17),
    blank(1, "When the child had grown, he went out one day to his father among the _____.", "reapers", 18, ["reapers"]),
    mc(2, "Which word correctly completes this RSV wording: “When the child had grown, he went out one day to his father among the _____.”", ["reapers", "caught", "staff", "sound"], 18),
    word(3, "In verse 18, what word completes this phrase: “When the child had grown, he went out one day to his father among the _____.”?", "reapers", 18, ["reapers"]),
    tf(1, "The RSV does not state: “When the child had grown, he went out one day to his father among the reapers.”", false, 18, "The quoted wording is the RSV text of this verse."),
    blank(2, "his father, \"Oh, my head, my head!\" The father said to his servant, \"_____ him to his mother.\"", "Carry", 19, ["carry"]),
    mc(3, "Which word correctly completes this RSV wording: “his father, \"Oh, my head, my head!\" The father said to his servant, \"_____ him to his mother.\"”", ["Carry", "Eli’sha", "Carmel", "Shunem"], 19),
    word(1, "In verse 19, what word completes this phrase: “his father, \"Oh, my head, my head!\" The father said to his servant, \"_____ him to his mother.\"”?", "Carry", 19, ["carry"]),
    tf(2, "The RSV states: “And he said to his father, \"Oh, my head, my head!\" The father said to his servant, \"Carry him to his mother.\"”", true, 19),
    blank(3, "And when he had lifted him, and _____ him to his mother, the child sat on her lap till noon, and then he died.", "brought", 20, ["brought"]),
    mc(1, "Which word correctly completes this RSV wording: “And when he had lifted him, and _____ him to his mother, the child sat on her lap till noon, and then he died.”", ["brought", "salutes", "returned", "became"], 20),
    word(2, "In verse 20, what word completes this phrase: “And when he had lifted him, and _____ him to his mother, the child sat on her lap till noon, and then he died.”?", "brought", 20, ["brought"]),
    tf(3, "The RSV does not state: “And when he had lifted him, and brought him to his mother, the child sat on her lap till noon, and then he died.”", false, 20, "The quoted wording is the RSV text of this verse."),
    blank(1, "And she _____ up and laid him on the bed of the man of God, and shut the door upon him,", "went", 21, ["went"]),
    mc(2, "Which word correctly completes this RSV wording: “And she _____ up and laid him on the bed of the man of God, and shut the door upon him,”", ["went", "sign", "himself", "bowing"], 21),
    word(3, "In verse 21, what word completes this phrase: “And she _____ up and laid him on the bed of the man of God, and shut the door upon him,”?", "went", 21, ["went"]),
    tf(1, "The RSV states: “And she went up and laid him on the bed of the man of God, and shut the door upon him, and went out.”", true, 21),
    blank(2, "Then she called to her husband, and said, \"_____ me one of the servants and one of the asses, that I may quickly go to", "Send", 22, ["send"]),
    mc(3, "Which word correctly completes this RSV wording: “Then she called to her husband, and said, \"_____ me one of the servants and one of the asses, that I may quickly go to”", ["Send", "Bring", "Gird", "Geha’zi"], 22),
    word(1, "In verse 22, what word completes this phrase: “Then she called to her husband, and said, \"_____ me one of the servants and one of the asses, that I may quickly go to”?", "Send", 22, ["send"]),
    tf(2, "The RSV does not state: “Then she called to her husband, and said, \"Send me one of the servants and one of the asses, that I may quickly go to the man of God, and come back again.\"”", false, 22, "The quoted wording is the RSV text of this verse."),
    blank(3, "And he said, \"Why will you go to him today? It is _____ new moon nor sabbath.\" She said, \"It will be well.\"", "neither", 23, ["neither"]),
    mc(1, "Which word correctly completes this RSV wording: “And he said, \"Why will you go to him today? It is _____ new moon nor sabbath.\" She said, \"It will be well.\"”", ["neither", "flesh", "ground", "found"], 23),
    word(2, "In verse 23, what word completes this phrase: “And he said, \"Why will you go to him today? It is _____ new moon nor sabbath.\" She said, \"It will be well.\"”?", "neither", 23, ["neither"]),
    tf(3, "The RSV states: “And he said, \"Why will you go to him today? It is neither new moon nor sabbath.\" She said, \"It will be well.\"”", true, 23),
    blank(1, "Then she saddled the ass, and she said to her servant, \"_____ the beast on; do not slacken the pace for me unless I tell you.\"", "Urge", 24, ["urge"]),
    mc(2, "Which word correctly completes this RSV wording: “Then she saddled the ass, and she said to her servant, \"_____ the beast on; do not slacken the pace for me unless I tell you.\"”", ["Urge", "Gilgal", "Carry", "Eli’sha"], 24),
    word(3, "In verse 24, what word completes this phrase: “Then she saddled the ass, and she said to her servant, \"_____ the beast on; do not slacken the pace for me unless I tell you.\"”?", "Urge", 24, ["urge"]),
    tf(1, "The RSV does not state: “Then she saddled the ass, and she said to her servant, \"Urge the beast on; do not slacken the pace for me unless I tell you.\"”", false, 24, "The quoted wording is the RSV text of this verse."),
    blank(2, "saw her coming, he said to Geha’zi his servant, \"Look, yonder is the _____;", "Shu’nammite", 25, ["shunammite"]),
    mc(3, "Which word correctly completes this RSV wording: “saw her coming, he said to Geha’zi his servant, \"Look, yonder is the _____;”", ["Shu’nammite", "Ba’al-shal’ishah", "Behold", "Therefore"], 25),
    word(1, "In verse 25, what word completes this phrase: “saw her coming, he said to Geha’zi his servant, \"Look, yonder is the _____;”?", "Shu’nammite", 25, ["shunammite"]),
    tf(2, "The RSV states: “So she set out, and came to the man of God at Mount Carmel. When the man of God saw her coming, he said to Geha’zi his servant, \"Look, yonder is the Shu’nammite;”", true, 25),
    blank(3, "you? Is it well with your husband? Is it well with the child?\" And she _____, \"It is well.\"", "answered", 26, ["answered"]),
    mc(1, "Which word correctly completes this RSV wording: “you? Is it well with your husband? Is it well with the child?\" And she _____, \"It is well.\"”", ["answered", "herbs", "meal", "ears"], 26),
    word(2, "In verse 26, what word completes this phrase: “you? Is it well with your husband? Is it well with the child?\" And she _____, \"It is well.\"”?", "answered", 26, ["answered"]),
    tf(3, "The RSV does not state: “run at once to meet her, and say to her, Is it well with you? Is it well with your husband? Is it well with the child?\" And she answered, \"It is well.\"”", false, 26, "The quoted wording is the RSV text of this verse."),
    blank(1, "came to the mountain to the man of God, she caught hold of his feet. And _____ came to thrust her away. But the man of God said, \"Let her alone, for", "Geha’zi", 27, ["gehazi"]),
    mc(2, "Which word correctly completes this RSV wording: “came to the mountain to the man of God, she caught hold of his feet. And _____ came to thrust her away. But the man of God said, \"Let her alone, for”", ["Geha’zi", "Send", "Eli’sha", "Mount"], 27),
    word(3, "In verse 27, what word completes this phrase: “came to the mountain to the man of God, she caught hold of his feet. And _____ came to thrust her away. But the man of God said, \"Let her alone, for”?", "Geha’zi", 27, ["gehazi"]),
    tf(1, "The RSV states: “And when she came to the mountain to the man of God, she caught hold of his feet. And Geha’zi came to thrust her away. But the man of God said, \"Let her alone, for she is in bitter distress; and the LORD has hidden it from me, and has not told me.\"”", true, 27),
    blank(2, "Then she said, \"Did I ask my lord for a son? Did I not say, Do not _____ me?\"", "deceive", 28, ["deceive"]),
    mc(3, "Which word correctly completes this RSV wording: “Then she said, \"Did I ask my lord for a son? Did I not say, Do not _____ me?\"”", ["deceive", "bringing", "hundred", "husband"], 28),
    word(1, "In verse 28, what word completes this phrase: “Then she said, \"Did I ask my lord for a son? Did I not say, Do not _____ me?\"”?", "deceive", 28, ["deceive"]),
    tf(2, "The RSV does not state: “Then she said, \"Did I ask my lord for a son? Did I not say, Do not deceive me?\"”", false, 28, "The quoted wording is the RSV text of this verse."),
    blank(3, "He said to _____, \"Gird up your loins, and take my staff in your hand, and go. If you meet", "Geha’zi", 29, ["gehazi"]),
    mc(1, "Which word correctly completes this RSV wording: “He said to _____, \"Gird up your loins, and take my staff in your hand, and go. If you meet”", ["Geha’zi", "Shunem", "Gird", "Call"], 29),
    word(2, "In verse 29, what word completes this phrase: “He said to _____, \"Gird up your loins, and take my staff in your hand, and go. If you meet”?", "Geha’zi", 29, ["gehazi"]),
    tf(3, "The RSV states: “He said to Geha’zi, \"Gird up your loins, and take my staff in your hand, and go. If you meet any one, do not salute him; and if any one salutes you, do not reply; and lay my staff upon the face of the child.\"”", true, 29),
    blank(1, "Then the mother of the child said, \"As the LORD lives, and as you _____ live, I will not leave you.\" So he arose and followed her.", "yourself", 30, ["yourself"]),
    mc(2, "Which word correctly completes this RSV wording: “Then the mother of the child said, \"As the LORD lives, and as you _____ live, I will not leave you.\" So he arose and followed her.”", ["yourself", "says", "feared", "except"], 30),
    word(3, "In verse 30, what word completes this phrase: “Then the mother of the child said, \"As the LORD lives, and as you _____ live, I will not leave you.\" So he arose and followed her.”?", "yourself", 30, ["yourself"]),
    tf(1, "The RSV does not state: “Then the mother of the child said, \"As the LORD lives, and as you yourself live, I will not leave you.\" So he arose and followed her.”", false, 30, "The quoted wording is the RSV text of this verse."),
    blank(2, "staff upon the face of the child, but there was no sound or sign of life. _____ he returned to meet him, and told him, \"The child has not awaked.\"", "Therefore", 31, ["therefore"]),
    mc(3, "Which word correctly completes this RSV wording: “staff upon the face of the child, but there was no sound or sign of life. _____ he returned to meet him, and told him, \"The child has not awaked.\"”", ["Therefore", "Gilgal", "Well", "Give"], 31),
    word(1, "In verse 31, what word completes this phrase: “staff upon the face of the child, but there was no sound or sign of life. _____ he returned to meet him, and told him, \"The child has not awaked.\"”?", "Therefore", 31, ["therefore"]),
    tf(2, "The RSV states: “Geha’zi went on ahead and laid the staff upon the face of the child, but there was no sound or sign of life. Therefore he returned to meet him, and told him, \"The child has not awaked.\"”", true, 31),
    blank(3, "When _____ came into the house, he saw the child lying dead on his bed.", "Eli’sha", 32, ["elisha"]),
    mc(1, "Which word correctly completes this RSV wording: “When _____ came into the house, he saw the child lying dead on his bed.”", ["Eli’sha", "Geha’zi", "Therefore", "Shu’nammite"], 32),
    word(2, "In verse 32, what word completes this phrase: “When _____ came into the house, he saw the child lying dead on his bed.”?", "Eli’sha", 32, ["elisha"]),
    tf(3, "The RSV does not state: “When Eli’sha came into the house, he saw the child lying dead on his bed.”", false, 32, "The quoted wording is the RSV text of this verse."),
    blank(1, "So he went in and shut the door upon the two of them, and _____ to the LORD.", "prayed", 33, ["prayed"]),
    mc(2, "Which word correctly completes this RSV wording: “So he went in and shut the door upon the two of them, and _____ to the LORD.”", ["prayed", "nothing", "full", "told"], 33),
    word(3, "In verse 33, what word completes this phrase: “So he went in and shut the door upon the two of them, and _____ to the LORD.”?", "prayed", 33, ["prayed"]),
    tf(1, "The RSV states: “So he went in and shut the door upon the two of them, and prayed to the LORD.”", true, 33),
    blank(2, "mouth, his eyes upon his eyes, and his hands upon his hands; and as he _____ himself upon him, the flesh of the child became warm.", "stretched", 34, ["stretched"]),
    mc(3, "Which word correctly completes this RSV wording: “mouth, his eyes upon his eyes, and his hands upon his hands; and as he _____ himself upon him, the flesh of the child became warm.”", ["stretched", "shut", "vessel", "lived"], 34),
    word(1, "In verse 34, what word completes this phrase: “mouth, his eyes upon his eyes, and his hands upon his hands; and as he _____ himself upon him, the flesh of the child became warm.”?", "stretched", 34, ["stretched"]),
    tf(2, "The RSV does not state: “Then he went up and lay upon the child, putting his mouth upon his mouth, his eyes upon his eyes, and his hands upon his hands; and as he stretched himself upon him, the flesh of the child became warm.”", false, 34, "The quoted wording is the RSV text of this verse."),
    blank(3, "got up again, and walked once to and fro in the house, and went up, and _____ himself upon him; the child sneezed seven times, and the child opened", "stretched", 35, ["stretched"]),
    mc(1, "Which word correctly completes this RSV wording: “got up again, and walked once to and fro in the house, and went up, and _____ himself upon him; the child sneezed seven times, and the child opened”", ["stretched", "herself", "live", "perceive"], 35),
    word(2, "In verse 35, what word completes this phrase: “got up again, and walked once to and fro in the house, and went up, and _____ himself upon him; the child sneezed seven times, and the child opened”?", "stretched", 35, ["stretched"]),
    tf(3, "The RSV states: “Then he got up again, and walked once to and fro in the house, and went up, and stretched himself upon him; the child sneezed seven times, and the child opened his eyes.”", true, 35),
    blank(1, "Then he summoned Geha’zi and said, \"Call this _____.\" So he called her. And when she came to him, he said, \"Take up your son.\"", "Shu’nammite", 36, ["shunammite"]),
    mc(2, "Which word correctly completes this RSV wording: “Then he summoned Geha’zi and said, \"Call this _____.\" So he called her. And when she came to him, he said, \"Take up your son.\"”", ["Shu’nammite", "Carmel", "Ba’al-shal’ishah", "Behold"], 36),
    word(3, "In verse 36, what word completes this phrase: “Then he summoned Geha’zi and said, \"Call this _____.\" So he called her. And when she came to him, he said, \"Take up your son.\"”?", "Shu’nammite", 36, ["shunammite"]),
    tf(1, "The RSV does not state: “Then he summoned Geha’zi and said, \"Call this Shu’nammite.\" So he called her. And when she came to him, he said, \"Take up your son.\"”", false, 36, "The quoted wording is the RSV text of this verse."),
    blank(2, "She came and fell at his feet, _____ to the ground; then she took up her son and went out.", "bowing", 37, ["bowing"]),
    mc(3, "Which word correctly completes this RSV wording: “She came and fell at his feet, _____ to the ground; then she took up her son and went out.”", ["bowing", "woman", "passing", "rested"], 37),
    word(1, "In verse 37, what word completes this phrase: “She came and fell at his feet, _____ to the ground; then she took up her son and went out.”?", "bowing", 37, ["bowing"]),
    tf(2, "The RSV states: “She came and fell at his feet, bowing to the ground; then she took up her son and went out.”", true, 37),
    blank(3, "And _____ came again to Gilgal when there was a famine in the land. And as the sons", "Eli’sha", 38, ["elisha"]),
    mc(1, "Which word correctly completes this RSV wording: “And _____ came again to Gilgal when there was a famine in the land. And as the sons”", ["Eli’sha", "Shu’nammite", "Gilgal", "Carry"], 38),
    word(2, "In verse 38, what word completes this phrase: “And _____ came again to Gilgal when there was a famine in the land. And as the sons”?", "Eli’sha", 38, ["elisha"]),
    tf(3, "The RSV does not state: “And Eli’sha came again to Gilgal when there was a famine in the land. And as the sons of the prophets were sitting before him, he said to his servant, \"Set on the great pot, and boil pottage for the sons of the prophets.\"”", false, 38, "The quoted wording is the RSV text of this verse."),
    blank(1, "them went out into the field to gather herbs, and found a wild vine and _____ from it his lap full of wild gourds, and came and cut them up into the", "gathered", 39, ["gathered"]),
    mc(2, "Which word correctly completes this RSV wording: “them went out into the field to gather herbs, and found a wild vine and _____ from it his lap full of wild gourds, and came and cut them up into the”", ["gathered", "roof", "before", "dwell"], 39),
    word(3, "In verse 39, what word completes this phrase: “them went out into the field to gather herbs, and found a wild vine and _____ from it his lap full of wild gourds, and came and cut them up into the”?", "gathered", 39, ["gathered"]),
    tf(1, "The RSV states: “One of them went out into the field to gather herbs, and found a wild vine and gathered from it his lap full of wild gourds, and came and cut them up into the pot of pottage, not knowing what they were.”", true, 39),
    blank(2, "they poured out for the men to eat. But while they were eating of the _____, they cried out, \"O man of God, there is death in the pot!\" And they could", "pottage", 40, ["pottage"]),
    mc(3, "Which word correctly completes this RSV wording: “they poured out for the men to eat. But while they were eating of the _____, they cried out, \"O man of God, there is death in the pot!\" And they could”", ["pottage", "turned", "king", "embrace"], 40),
    word(1, "In verse 40, what word completes this phrase: “they poured out for the men to eat. But while they were eating of the _____, they cried out, \"O man of God, there is death in the pot!\" And they could”?", "pottage", 40, ["pottage"]),
    tf(2, "The RSV does not state: “And they poured out for the men to eat. But while they were eating of the pottage, they cried out, \"O man of God, there is death in the pot!\" And they could not eat it.”", false, 40, "The quoted wording is the RSV text of this verse."),
    blank(3, "He said, \"Then bring meal.\" And he threw it into the pot, and said, \"_____ out for the men, that they may eat.\" And there was no harm in the pot.", "Pour", 41, ["pour"]),
    mc(1, "Which word correctly completes this RSV wording: “He said, \"Then bring meal.\" And he threw it into the pot, and said, \"_____ out for the men, that they may eat.\" And there was no harm in the pot.”", ["Pour", "Bring", "Look", "Geha’zi"], 41),
    word(2, "In verse 41, what word completes this phrase: “He said, \"Then bring meal.\" And he threw it into the pot, and said, \"_____ out for the men, that they may eat.\" And there was no harm in the pot.”?", "Pour", 41, ["pour"]),
    tf(3, "The RSV states: “He said, \"Then bring meal.\" And he threw it into the pot, and said, \"Pour out for the men, that they may eat.\" And there was no harm in the pot.”", true, 41),
    blank(1, "A man came from _____, bringing the man of God bread of the first fruits, twenty loaves of barley,", "Ba’al-shal’ishah", 42, ["baal-shalishah"]),
    mc(2, "Which word correctly completes this RSV wording: “A man came from _____, bringing the man of God bread of the first fruits, twenty loaves of barley,”", ["Ba’al-shal’ishah", "Shu’nammite", "Jerusalem", "Israel"], 42),
    word(3, "In verse 42, what word completes this phrase: “A man came from _____, bringing the man of God bread of the first fruits, twenty loaves of barley,”?", "Ba’al-shal’ishah", 42, ["baal-shalishah"]),
    tf(1, "The RSV does not state: “A man came from Ba’al-shal’ishah, bringing the man of God bread of the first fruits, twenty loaves of barley, and fresh ears of grain in his sack. And Eli’sha said, \"Give to the men, that they may eat.\"”", false, 42, "The quoted wording is the RSV text of this verse."),
    blank(2, "servant said, \"How am I to set this before a hundred men?\" So he repeated, \"_____ them to the men, that they may eat, for thus says the LORD, `They shall", "Give", 43, ["give"]),
    mc(3, "Which word correctly completes this RSV wording: “servant said, \"How am I to set this before a hundred men?\" So he repeated, \"_____ them to the men, that they may eat, for thus says the LORD, `They shall”", ["Give", "Take", "Carry", "Eli’sha"], 43),
    word(1, "In verse 43, what word completes this phrase: “servant said, \"How am I to set this before a hundred men?\" So he repeated, \"_____ them to the men, that they may eat, for thus says the LORD, `They shall”?", "Give", 43, ["give"]),
    tf(2, "The RSV states: “But his servant said, \"How am I to set this before a hundred men?\" So he repeated, \"Give them to the men, that they may eat, for thus says the LORD, `They shall eat and have some left.’\"”", true, 43),
    blank(3, "So he set it before them. And they ate, and had some left, _____ to the word of the LORD.", "according", 44, ["according"]),
    mc(1, "Which word correctly completes this RSV wording: “So he set it before them. And they ate, and had some left, _____ to the word of the LORD.”", ["according", "child", "servants", "beast"], 44),
    word(2, "In verse 44, what word completes this phrase: “So he set it before them. And they ate, and had some left, _____ to the word of the LORD.”?", "according", 44, ["according"]),
    tf(3, "The RSV does not state: “So he set it before them. And they ate, and had some left, according to the word of the LORD.”", false, 44, "The quoted wording is the RSV text of this verse."),
    mc(1, "What did Elisha tell the indebted widow to borrow from her neighbors?", ["Empty vessels—and not too few", "Jars filled with meal", "Silver coins", "Measures of barley"], 3),
    mc(2, "What furniture did the Shunammite woman place in Elisha’s roof chamber?", ["A bed, table, chair, and lamp", "A bed, chest, stool, and basin", "A table, couch, altar, and lamp", "A bed and table only"], 10),
    mc(3, "What did the Shunammite’s son do as he returned to life?", ["He sneezed seven times and opened his eyes", "He cried out and stood up", "He spoke Elisha’s name", "He asked for his mother"], 35),
    mc(2, "What did Elisha put into the deadly pottage to make it harmless?", ["Meal", "Salt", "Oil", "Water"], 41),
    mc(3, "What food was used to feed one hundred men with some left over?", ["Twenty barley loaves and fresh ears of grain from Baal-shalishah", "Five barley loaves and two fish", "One hundred wheat loaves", "A jar of meal and a cruse of oil"], 42),
  ],
};

export default bank;
