// 2 Kings 15 — quiz bank (RSV). Four verse-anchored forms per verse.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: "2 Kings",
  chapter: 15,
  tag: "quiz-v2-2kings-15",
  rows: [
    blank(2, "In the twenty-seventh year of _____ king of Israel Azari’ah the son of Amazi’ah, king of Judah, began to reign.", "Jerobo’am", 1, ["jeroboam"]),
    mc(3, "Which word correctly completes this RSV wording: “In the twenty-seventh year of _____ king of Israel Azari’ah the son of Amazi’ah, king of Judah, began to reign.”", ["Jerobo’am", "Jotham", "Jehu", "I’jon"], 1),
    word(1, "In verse 1, what word completes this phrase: “In the twenty-seventh year of _____ king of Israel Azari’ah the son of Amazi’ah, king of Judah, began to reign.”?", "Jerobo’am", 1, ["jeroboam"]),
    tf(2, "The RSV states: “In the twenty-seventh year of Jerobo’am king of Israel Azari’ah the son of Amazi’ah, king of Judah, began to reign.”", true, 1),
    blank(3, "sixteen years old when he began to reign, and he reigned fifty-two years in _____. His mother’s name was Jecoli’ah of Jerusalem.", "Jerusalem", 2, ["jerusalem"]),
    mc(1, "Which word correctly completes this RSV wording: “sixteen years old when he began to reign, and he reigned fifty-two years in _____. His mother’s name was Jecoli’ah of Jerusalem.”", ["Jerusalem", "Nebat", "Pekahi’ah", "Hoshe’a"], 2),
    word(2, "In verse 2, what word completes this phrase: “sixteen years old when he began to reign, and he reigned fifty-two years in _____. His mother’s name was Jecoli’ah of Jerusalem.”?", "Jerusalem", 2, ["jerusalem"]),
    tf(3, "The RSV does not state: “He was sixteen years old when he began to reign, and he reigned fifty-two years in Jerusalem. His mother’s name was Jecoli’ah of Jerusalem.”", false, 2, "The quoted wording is the RSV text of this verse."),
    blank(1, "what was right in the eyes of the LORD, according to all that his father _____ had done.", "Amazi’ah", 3, ["amaziah"]),
    mc(2, "Which word correctly completes this RSV wording: “what was right in the eyes of the LORD, according to all that his father _____ had done.”", ["Amazi’ah", "Gadi", "Hazor", "Jerobo’am"], 3),
    word(3, "In verse 3, what word completes this phrase: “what was right in the eyes of the LORD, according to all that his father _____ had done.”?", "Amazi’ah", 3, ["amaziah"]),
    tf(1, "The RSV states: “And he did what was right in the eyes of the LORD, according to all that his father Amazi’ah had done.”", true, 3),
    blank(2, "_____ the high places were not taken away; the people still sacrificed and burned", "Nevertheless", 4, ["nevertheless"]),
    mc(3, "Which word correctly completes this RSV wording: “_____ the high places were not taken away; the people still sacrificed and burned”", ["Nevertheless", "Zechari’ah", "Jan-o’ah", "Jerusalem"], 4),
    word(1, "In verse 4, what word completes this phrase: “_____ the high places were not taken away; the people still sacrificed and burned”?", "Nevertheless", 4, ["nevertheless"]),
    tf(2, "The RSV does not state: “Nevertheless the high places were not taken away; the people still sacrificed and burned incense on the high places.”", false, 4, "The quoted wording is the RSV text of this verse."),
    blank(3, "leper to the day of his death, and he dwelt in a separate house. And _____ the king’s son was over the household, governing the people of the land.", "Jotham", 5, ["jotham"]),
    mc(1, "Which word correctly completes this RSV wording: “leper to the day of his death, and he dwelt in a separate house. And _____ the king’s son was over the household, governing the people of the land.”", ["Jotham", "Hoshe’a", "Judah", "Jabesh"], 5),
    word(2, "In verse 5, what word completes this phrase: “leper to the day of his death, and he dwelt in a separate house. And _____ the king’s son was over the household, governing the people of the land.”?", "Jotham", 5, ["jotham"]),
    tf(3, "The RSV states: “And the LORD smote the king, so that he was a leper to the day of his death, and he dwelt in a separate house. And Jotham the king’s son was over the household, governing the people of the land.”", true, 5),
    blank(1, "Azari’ah, and all that he did, are they not written in the Book of the _____ of the Kings of Judah?", "Chronicles", 6, ["chronicles"]),
    mc(2, "Which word correctly completes this RSV wording: “Azari’ah, and all that he did, are they not written in the Book of the _____ of the Kings of Judah?”", ["Chronicles", "Judah", "Jabesh", "I’jon"], 6),
    word(3, "In verse 6, what word completes this phrase: “Azari’ah, and all that he did, are they not written in the Book of the _____ of the Kings of Judah?”?", "Chronicles", 6, ["chronicles"]),
    tf(1, "The RSV does not state: “Now the rest of the acts of Azari’ah, and all that he did, are they not written in the Book of the Chronicles of the Kings of Judah?”", false, 6, "The quoted wording is the RSV text of this verse."),
    blank(2, "And _____ slept with his fathers, and they buried him with his fathers in the city", "Azari’ah", 7, ["azariah"]),
    mc(3, "Which word correctly completes this RSV wording: “And _____ slept with his fathers, and they buried him with his fathers in the city”", ["Azari’ah", "Nevertheless", "Ibleam", "Gileadites"], 7),
    word(1, "In verse 7, what word completes this phrase: “And _____ slept with his fathers, and they buried him with his fathers in the city”?", "Azari’ah", 7, ["azariah"]),
    tf(2, "The RSV states: “And Azari’ah slept with his fathers, and they buried him with his fathers in the city of David, and Jotham his son reigned in his stead.”", true, 7),
    blank(3, "In the thirty-eighth year of Azari’ah king of Judah _____ the son of Jerobo’am reigned over Israel in Sama’ria six months.", "Zechari’ah", 8, ["zechariah"]),
    mc(1, "Which word correctly completes this RSV wording: “In the thirty-eighth year of Azari’ah king of Judah _____ the son of Jerobo’am reigned over Israel in Sama’ria six months.”", ["Zechari’ah", "Men’ahem", "Hazor", "Azari’ah"], 8),
    word(2, "In verse 8, what word completes this phrase: “In the thirty-eighth year of Azari’ah king of Judah _____ the son of Jerobo’am reigned over Israel in Sama’ria six months.”?", "Zechari’ah", 8, ["zechariah"]),
    tf(3, "The RSV does not state: “In the thirty-eighth year of Azari’ah king of Judah Zechari’ah the son of Jerobo’am reigned over Israel in Sama’ria six months.”", false, 8, "The quoted wording is the RSV text of this verse."),
    blank(1, "the LORD, as his fathers had done. He did not depart from the sins of _____ the son of Nebat, which he made Israel to sin.", "Jerobo’am", 9, ["jeroboam"]),
    mc(2, "Which word correctly completes this RSV wording: “the LORD, as his fathers had done. He did not depart from the sins of _____ the son of Nebat, which he made Israel to sin.”", ["Jerobo’am", "Men’ahem", "Kedesh", "Ahaz"], 9),
    word(3, "In verse 9, what word completes this phrase: “the LORD, as his fathers had done. He did not depart from the sins of _____ the son of Nebat, which he made Israel to sin.”?", "Jerobo’am", 9, ["jeroboam"]),
    tf(1, "The RSV states: “And he did what was evil in the sight of the LORD, as his fathers had done. He did not depart from the sins of Jerobo’am the son of Nebat, which he made Israel to sin.”", true, 9),
    blank(2, "_____ the son of Jabesh conspired against him, and struck him down at Ibleam,", "Shallum", 10, ["shallum"]),
    mc(3, "Which word correctly completes this RSV wording: “_____ the son of Jabesh conspired against him, and struck him down at Ibleam,”", ["Shallum", "Remali’ah", "Jeru’sha", "Jecoli’ah"], 10),
    word(1, "In verse 10, what word completes this phrase: “_____ the son of Jabesh conspired against him, and struck him down at Ibleam,”?", "Shallum", 10, ["shallum"]),
    tf(2, "The RSV does not state: “Shallum the son of Jabesh conspired against him, and struck him down at Ibleam, and killed him, and reigned in his stead.”", false, 10, "The quoted wording is the RSV text of this verse."),
    blank(3, "Now the rest of the deeds of _____, behold, they are written in the Book of the Chronicles of the Kings of", "Zechari’ah", 11, ["zechariah"]),
    mc(1, "Which word correctly completes this RSV wording: “Now the rest of the deeds of _____, behold, they are written in the Book of the Chronicles of the Kings of”", ["Zechari’ah", "Israel", "Sama’ria", "Pekah"], 11),
    word(2, "In verse 11, what word completes this phrase: “Now the rest of the deeds of _____, behold, they are written in the Book of the Chronicles of the Kings of”?", "Zechari’ah", 11, ["zechariah"]),
    tf(3, "The RSV states: “Now the rest of the deeds of Zechari’ah, behold, they are written in the Book of the Chronicles of the Kings of Israel.”", true, 11),
    blank(1, "the LORD which he gave to Jehu, \"Your sons shall sit upon the throne of _____ to the fourth generation.\" And so it came to pass.)", "Israel", 12, ["israel"]),
    mc(2, "Which word correctly completes this RSV wording: “the LORD which he gave to Jehu, \"Your sons shall sit upon the throne of _____ to the fourth generation.\" And so it came to pass.)”", ["Israel", "Jerobo’am", "Zechari’ah", "Tappuah"], 12),
    word(3, "In verse 12, what word completes this phrase: “the LORD which he gave to Jehu, \"Your sons shall sit upon the throne of _____ to the fourth generation.\" And so it came to pass.)”?", "Israel", 12, ["israel"]),
    tf(1, "The RSV does not state: “(This was the promise of the LORD which he gave to Jehu, \"Your sons shall sit upon the throne of Israel to the fourth generation.\" And so it came to pass.)”", false, 12, "The quoted wording is the RSV text of this verse."),
    blank(2, "thirty-ninth year of Uzzi’ah king of Judah, and he reigned one month in _____.", "Sama’ria", 13, ["samaria"]),
    mc(3, "Which word correctly completes this RSV wording: “thirty-ninth year of Uzzi’ah king of Judah, and he reigned one month in _____.”", ["Sama’ria", "Jerusalem", "Jabesh", "Remali’ah"], 13),
    word(1, "In verse 13, what word completes this phrase: “thirty-ninth year of Uzzi’ah king of Judah, and he reigned one month in _____.”?", "Sama’ria", 13, ["samaria"]),
    tf(2, "The RSV states: “Shallum the son of Jabesh began to reign in the thirty-ninth year of Uzzi’ah king of Judah, and he reigned one month in Sama’ria.”", true, 13),
    blank(3, "Then _____ the son of Gadi came up from Tirzah and came to Sama’ria, and he struck", "Men’ahem", 14, ["menahem"]),
    mc(1, "Which word correctly completes this RSV wording: “Then _____ the son of Gadi came up from Tirzah and came to Sama’ria, and he struck”", ["Men’ahem", "David", "Tappuah", "Galilee"], 14),
    word(2, "In verse 14, what word completes this phrase: “Then _____ the son of Gadi came up from Tirzah and came to Sama’ria, and he struck”?", "Men’ahem", 14, ["menahem"]),
    tf(3, "The RSV does not state: “Then Men’ahem the son of Gadi came up from Tirzah and came to Sama’ria, and he struck down Shallum the son of Jabesh in Sama’ria and slew him, and reigned in his stead.”", false, 14, "The quoted wording is the RSV text of this verse."),
    blank(1, "conspiracy which he made, behold, they are written in the Book of the _____ of the Kings of Israel.", "Chronicles", 15, ["chronicles"]),
    mc(2, "Which word correctly completes this RSV wording: “conspiracy which he made, behold, they are written in the Book of the _____ of the Kings of Israel.”", ["Chronicles", "Hazor", "Azari’ah", "Nebat"], 15),
    word(3, "In verse 15, what word completes this phrase: “conspiracy which he made, behold, they are written in the Book of the _____ of the Kings of Israel.”?", "Chronicles", 15, ["chronicles"]),
    tf(1, "The RSV states: “Now the rest of the deeds of Shallum, and the conspiracy which he made, behold, they are written in the Book of the Chronicles of the Kings of Israel.”", true, 15),
    blank(2, "At that time _____ sacked Tappuah and all who were in it and its territory from Tirzah on;", "Men’ahem", 16, ["menahem"]),
    mc(3, "Which word correctly completes this RSV wording: “At that time _____ sacked Tappuah and all who were in it and its territory from Tirzah on;”", ["Men’ahem", "Pekah", "Elah", "Jerusalem"], 16),
    word(1, "In verse 16, what word completes this phrase: “At that time _____ sacked Tappuah and all who were in it and its territory from Tirzah on;”?", "Men’ahem", 16, ["menahem"]),
    tf(2, "The RSV does not state: “At that time Men’ahem sacked Tappuah and all who were in it and its territory from Tirzah on; because they did not open it to him, therefore he sacked it, and he ripped up all the women in it who were with child.”", false, 16, "The quoted wording is the RSV text of this verse."),
    blank(3, "In the thirty-ninth year of _____ king of Judah Men’ahem the son of Gadi began to reign over Israel, and", "Azari’ah", 17, ["azariah"]),
    mc(1, "Which word correctly completes this RSV wording: “In the thirty-ninth year of _____ king of Judah Men’ahem the son of Gadi began to reign over Israel, and”", ["Azari’ah", "Gilead", "Israel", "Zechari’ah"], 17),
    word(2, "In verse 17, what word completes this phrase: “In the thirty-ninth year of _____ king of Judah Men’ahem the son of Gadi began to reign over Israel, and”?", "Azari’ah", 17, ["azariah"]),
    tf(3, "The RSV states: “In the thirty-ninth year of Azari’ah king of Judah Men’ahem the son of Gadi began to reign over Israel, and he reigned ten years in Sama’ria.”", true, 17),
    blank(1, "sight of the LORD; he did not depart all his days from all the sins of _____ the son of Nebat, which he made Israel to sin.", "Jerobo’am", 18, ["jeroboam"]),
    mc(2, "Which word correctly completes this RSV wording: “sight of the LORD; he did not depart all his days from all the sins of _____ the son of Nebat, which he made Israel to sin.”", ["Jerobo’am", "Rezin", "Book", "Uzzi’ah"], 18),
    word(3, "In verse 18, what word completes this phrase: “sight of the LORD; he did not depart all his days from all the sins of _____ the son of Nebat, which he made Israel to sin.”?", "Jerobo’am", 18, ["jeroboam"]),
    tf(1, "The RSV does not state: “And he did what was evil in the sight of the LORD; he did not depart all his days from all the sins of Jerobo’am the son of Nebat, which he made Israel to sin.”", false, 18, "The quoted wording is the RSV text of this verse."),
    blank(2, "Pul the king of Assyria came against the land; and _____ gave Pul a thousand talents of silver, that he might help him to confirm", "Men’ahem", 19, ["menahem"]),
    mc(3, "Which word correctly completes this RSV wording: “Pul the king of Assyria came against the land; and _____ gave Pul a thousand talents of silver, that he might help him to confirm”", ["Men’ahem", "Judah", "Nebat", "Pekah"], 19),
    word(1, "In verse 19, what word completes this phrase: “Pul the king of Assyria came against the land; and _____ gave Pul a thousand talents of silver, that he might help him to confirm”?", "Men’ahem", 19, ["menahem"]),
    tf(2, "The RSV states: “Pul the king of Assyria came against the land; and Men’ahem gave Pul a thousand talents of silver, that he might help him to confirm his hold of the royal power.”", true, 19),
    blank(3, "_____ exacted the money from Israel, that is, from all the wealthy men, fifty", "Men’ahem", 20, ["menahem"]),
    mc(1, "Which word correctly completes this RSV wording: “_____ exacted the money from Israel, that is, from all the wealthy men, fifty”", ["Men’ahem", "Kings", "Tirzah", "Gilead"], 20),
    word(2, "In verse 20, what word completes this phrase: “_____ exacted the money from Israel, that is, from all the wealthy men, fifty”?", "Men’ahem", 20, ["menahem"]),
    tf(3, "The RSV does not state: “Men’ahem exacted the money from Israel, that is, from all the wealthy men, fifty shekels of silver from every man, to give to the king of Assyria. So the king of Assyria turned back, and did not stay there in the land.”", false, 20, "The quoted wording is the RSV text of this verse."),
    blank(1, "Men’ahem, and all that he did, are they not written in the Book of the _____ of the Kings of Israel?", "Chronicles", 21, ["chronicles"]),
    mc(2, "Which word correctly completes this RSV wording: “Men’ahem, and all that he did, are they not written in the Book of the _____ of the Kings of Israel?”", ["Chronicles", "Hoshe’a", "Jecoli’ah", "Uzzi’ah"], 21),
    word(3, "In verse 21, what word completes this phrase: “Men’ahem, and all that he did, are they not written in the Book of the _____ of the Kings of Israel?”?", "Chronicles", 21, ["chronicles"]),
    tf(1, "The RSV states: “Now the rest of the deeds of Men’ahem, and all that he did, are they not written in the Book of the Chronicles of the Kings of Israel?”", true, 21),
    blank(2, "And Men’ahem slept with his fathers, and _____ his son reigned in his stead.", "Pekahi’ah", 22, ["pekahiah"]),
    mc(3, "Which word correctly completes this RSV wording: “And Men’ahem slept with his fathers, and _____ his son reigned in his stead.”", ["Pekahi’ah", "Assyria", "Hoshe’a", "Judah"], 22),
    word(1, "In verse 22, what word completes this phrase: “And Men’ahem slept with his fathers, and _____ his son reigned in his stead.”?", "Pekahi’ah", 22, ["pekahiah"]),
    tf(2, "The RSV does not state: “And Men’ahem slept with his fathers, and Pekahi’ah his son reigned in his stead.”", false, 22, "The quoted wording is the RSV text of this verse."),
    blank(3, "In the fiftieth year of Azari’ah king of Judah _____ the son of Men’ahem began to reign over Israel in Sama’ria, and he reigned", "Pekahi’ah", 23, ["pekahiah"]),
    mc(1, "Which word correctly completes this RSV wording: “In the fiftieth year of Azari’ah king of Judah _____ the son of Men’ahem began to reign over Israel in Sama’ria, and he reigned”", ["Pekahi’ah", "Hazor", "Jerobo’am", "Kings"], 23),
    word(2, "In verse 23, what word completes this phrase: “In the fiftieth year of Azari’ah king of Judah _____ the son of Men’ahem began to reign over Israel in Sama’ria, and he reigned”?", "Pekahi’ah", 23, ["pekahiah"]),
    tf(3, "The RSV states: “In the fiftieth year of Azari’ah king of Judah Pekahi’ah the son of Men’ahem began to reign over Israel in Sama’ria, and he reigned two years.”", true, 23),
    blank(1, "evil in the sight of the LORD; he did not turn away from the sins of _____ the son of Nebat, which he made Israel to sin.", "Jerobo’am", 24, ["jeroboam"]),
    mc(2, "Which word correctly completes this RSV wording: “evil in the sight of the LORD; he did not turn away from the sins of _____ the son of Nebat, which he made Israel to sin.”", ["Jerobo’am", "Zadok", "Jotham", "Jehu"], 24),
    word(3, "In verse 24, what word completes this phrase: “evil in the sight of the LORD; he did not turn away from the sins of _____ the son of Nebat, which he made Israel to sin.”?", "Jerobo’am", 24, ["jeroboam"]),
    tf(1, "The RSV does not state: “And he did what was evil in the sight of the LORD; he did not turn away from the sins of Jerobo’am the son of Nebat, which he made Israel to sin.”", false, 24, "The quoted wording is the RSV text of this verse."),
    blank(2, "of Remali’ah, his captain, conspired against him with fifty men of the _____, and slew him in Sama’ria, in the citadel of the king’s house; he slew", "Gileadites", 25, ["gileadites"]),
    mc(3, "Which word correctly completes this RSV wording: “of Remali’ah, his captain, conspired against him with fifty men of the _____, and slew him in Sama’ria, in the citadel of the king’s house; he slew”", ["Gileadites", "Pekahi’ah", "Jeru’sha", "Nevertheless"], 25),
    word(1, "In verse 25, what word completes this phrase: “of Remali’ah, his captain, conspired against him with fifty men of the _____, and slew him in Sama’ria, in the citadel of the king’s house; he slew”?", "Gileadites", 25, ["gileadites"]),
    tf(2, "The RSV states: “And Pekah the son of Remali’ah, his captain, conspired against him with fifty men of the Gileadites, and slew him in Sama’ria, in the citadel of the king’s house; he slew him, and reigned in his stead.”", true, 25),
    blank(3, "Pekahi’ah, and all that he did, behold, they are written in the Book of the _____ of the Kings of Israel.", "Chronicles", 26, ["chronicles"]),
    mc(1, "Which word correctly completes this RSV wording: “Pekahi’ah, and all that he did, behold, they are written in the Book of the _____ of the Kings of Israel.”", ["Chronicles", "Gilead", "Amazi’ah", "Shallum"], 26),
    word(2, "In verse 26, what word completes this phrase: “Pekahi’ah, and all that he did, behold, they are written in the Book of the _____ of the Kings of Israel.”?", "Chronicles", 26, ["chronicles"]),
    tf(3, "The RSV does not state: “Now the rest of the deeds of Pekahi’ah, and all that he did, behold, they are written in the Book of the Chronicles of the Kings of Israel.”", false, 26, "The quoted wording is the RSV text of this verse."),
    blank(1, "In the fifty-second year of Azari’ah king of Judah Pekah the son of _____ began to reign over Israel in Sama’ria, and reigned twenty years.", "Remali’ah", 27, ["remaliah"]),
    mc(2, "Which word correctly completes this RSV wording: “In the fifty-second year of Azari’ah king of Judah Pekah the son of _____ began to reign over Israel in Sama’ria, and reigned twenty years.”", ["Remali’ah", "Jabesh", "Gileadites", "Zadok"], 27),
    word(3, "In verse 27, what word completes this phrase: “In the fifty-second year of Azari’ah king of Judah Pekah the son of _____ began to reign over Israel in Sama’ria, and reigned twenty years.”?", "Remali’ah", 27, ["remaliah"]),
    tf(1, "The RSV states: “In the fifty-second year of Azari’ah king of Judah Pekah the son of Remali’ah began to reign over Israel in Sama’ria, and reigned twenty years.”", true, 27),
    blank(2, "was evil in the sight of the LORD; he did not depart from the sins of _____ the son of Nebat, which he made Israel to sin.", "Jerobo’am", 28, ["jeroboam"]),
    mc(3, "Which word correctly completes this RSV wording: “was evil in the sight of the LORD; he did not depart from the sins of _____ the son of Nebat, which he made Israel to sin.”", ["Jerobo’am", "Assyria", "Naph’tali", "Judah"], 28),
    word(1, "In verse 28, what word completes this phrase: “was evil in the sight of the LORD; he did not depart from the sins of _____ the son of Nebat, which he made Israel to sin.”?", "Jerobo’am", 28, ["jeroboam"]),
    tf(2, "The RSV does not state: “And he did what was evil in the sight of the LORD; he did not depart from the sins of Jerobo’am the son of Nebat, which he made Israel to sin.”", false, 28, "The quoted wording is the RSV text of this verse."),
    blank(3, "of Israel Tig’lath-pile’ser king of Assyria came and captured I’jon, _____, Jan-o’ah, Kedesh, Hazor, Gilead, and Galilee, all the land of Naph’tali;", "A’bel-beth-ma’acah", 29, ["abel-beth-maacah"]),
    mc(1, "Which word correctly completes this RSV wording: “of Israel Tig’lath-pile’ser king of Assyria came and captured I’jon, _____, Jan-o’ah, Kedesh, Hazor, Gilead, and Galilee, all the land of Naph’tali;”", ["A’bel-beth-ma’acah", "Tig’lath-pile’ser", "Jerusalem", "Israel"], 29),
    word(2, "In verse 29, what word completes this phrase: “of Israel Tig’lath-pile’ser king of Assyria came and captured I’jon, _____, Jan-o’ah, Kedesh, Hazor, Gilead, and Galilee, all the land of Naph’tali;”?", "A’bel-beth-ma’acah", 29, ["abel-beth-maacah"]),
    tf(3, "The RSV states: “In the days of Pekah king of Israel Tig’lath-pile’ser king of Assyria came and captured I’jon, A’bel-beth-ma’acah, Jan-o’ah, Kedesh, Hazor, Gilead, and Galilee, all the land of Naph’tali; and he carried the people captive to Assyria.”", true, 29),
    blank(1, "Then Hoshe’a the son of Elah made a conspiracy against Pekah the son of _____, and struck him down, and slew him, and reigned in his stead, in the twentieth", "Remali’ah", 30, ["remaliah"]),
    mc(2, "Which word correctly completes this RSV wording: “Then Hoshe’a the son of Elah made a conspiracy against Pekah the son of _____, and struck him down, and slew him, and reigned in his stead, in the twentieth”", ["Remali’ah", "Jeru’sha", "Jecoli’ah", "Jabesh"], 30),
    word(3, "In verse 30, what word completes this phrase: “Then Hoshe’a the son of Elah made a conspiracy against Pekah the son of _____, and struck him down, and slew him, and reigned in his stead, in the twentieth”?", "Remali’ah", 30, ["remaliah"]),
    tf(1, "The RSV does not state: “Then Hoshe’a the son of Elah made a conspiracy against Pekah the son of Remali’ah, and struck him down, and slew him, and reigned in his stead, in the twentieth year of Jotham the son of Uzzi’ah.”", false, 30, "The quoted wording is the RSV text of this verse."),
    blank(2, "Pekah, and all that he did, behold, they are written in the Book of the _____ of the Kings of Israel.", "Chronicles", 31, ["chronicles"]),
    mc(3, "Which word correctly completes this RSV wording: “Pekah, and all that he did, behold, they are written in the Book of the _____ of the Kings of Israel.”", ["Chronicles", "Jan-o’ah", "Jerobo’am", "Zechari’ah"], 31),
    word(1, "In verse 31, what word completes this phrase: “Pekah, and all that he did, behold, they are written in the Book of the _____ of the Kings of Israel.”?", "Chronicles", 31, ["chronicles"]),
    tf(2, "The RSV states: “Now the rest of the acts of Pekah, and all that he did, behold, they are written in the Book of the Chronicles of the Kings of Israel.”", true, 31),
    blank(3, "In the second year of Pekah the son of _____, king of Israel, Jotham the son of Uzzi’ah, king of Judah, began to reign.", "Remali’ah", 32, ["remaliah"]),
    mc(1, "Which word correctly completes this RSV wording: “In the second year of Pekah the son of _____, king of Israel, Jotham the son of Uzzi’ah, king of Judah, began to reign.”", ["Remali’ah", "Book", "Uzzi’ah", "Kedesh"], 32),
    word(2, "In verse 32, what word completes this phrase: “In the second year of Pekah the son of _____, king of Israel, Jotham the son of Uzzi’ah, king of Judah, began to reign.”?", "Remali’ah", 32, ["remaliah"]),
    tf(3, "The RSV does not state: “In the second year of Pekah the son of Remali’ah, king of Israel, Jotham the son of Uzzi’ah, king of Judah, began to reign.”", false, 32, "The quoted wording is the RSV text of this verse."),
    blank(1, "twenty-five years old when he began to reign, and he reigned sixteen years in _____. His mother’s name was Jeru’sha the daughter of Zadok.", "Jerusalem", 33, ["jerusalem"]),
    mc(2, "Which word correctly completes this RSV wording: “twenty-five years old when he began to reign, and he reigned sixteen years in _____. His mother’s name was Jeru’sha the daughter of Zadok.”", ["Jerusalem", "Jabesh", "Remali’ah", "Jeru’sha"], 33),
    word(3, "In verse 33, what word completes this phrase: “twenty-five years old when he began to reign, and he reigned sixteen years in _____. His mother’s name was Jeru’sha the daughter of Zadok.”?", "Jerusalem", 33, ["jerusalem"]),
    tf(1, "The RSV states: “He was twenty-five years old when he began to reign, and he reigned sixteen years in Jerusalem. His mother’s name was Jeru’sha the daughter of Zadok.”", true, 33),
    word(1, "In verse 34, what word completes this phrase: “what was right in the eyes of the LORD, according to all that his father _____ had done.”?", "Uzzi’ah", 34, ["uzziah"]),
    tf(2, "The RSV does not state: “And he did what was right in the eyes of the LORD, according to all that his father Uzzi’ah had done.”", false, 34, "The quoted wording is the RSV text of this verse."),
    blank(3, "_____ the high places were not removed; the people still sacrificed and burned", "Nevertheless", 35, ["nevertheless"]),
    mc(1, "Which word correctly completes this RSV wording: “_____ the high places were not removed; the people still sacrificed and burned”", ["Nevertheless", "Jerusalem", "Remali’ah", "Israel"], 35),
    word(2, "In verse 35, what word completes this phrase: “_____ the high places were not removed; the people still sacrificed and burned”?", "Nevertheless", 35, ["nevertheless"]),
    tf(3, "The RSV states: “Nevertheless the high places were not removed; the people still sacrificed and burned incense on the high places. He built the upper gate of the house of the LORD.”", true, 35),
    blank(1, "Jotham, and all that he did, are they not written in the Book of the _____ of the Kings of Judah?", "Chronicles", 36, ["chronicles"]),
    mc(2, "Which word correctly completes this RSV wording: “Jotham, and all that he did, are they not written in the Book of the _____ of the Kings of Judah?”", ["Chronicles", "Remali’ah", "Zadok", "Jotham"], 36),
    word(3, "In verse 36, what word completes this phrase: “Jotham, and all that he did, are they not written in the Book of the _____ of the Kings of Judah?”?", "Chronicles", 36, ["chronicles"]),
    tf(1, "The RSV does not state: “Now the rest of the acts of Jotham, and all that he did, are they not written in the Book of the Chronicles of the Kings of Judah?”", false, 36, "The quoted wording is the RSV text of this verse."),
    blank(2, "days the LORD began to send Rezin the king of Syria and Pekah the son of _____ against Judah.", "Remali’ah", 37, ["remaliah"]),
    mc(3, "Which word correctly completes this RSV wording: “days the LORD began to send Rezin the king of Syria and Pekah the son of _____ against Judah.”", ["Remali’ah", "Israel", "David", "Tirzah"], 37),
    word(1, "In verse 37, what word completes this phrase: “days the LORD began to send Rezin the king of Syria and Pekah the son of _____ against Judah.”?", "Remali’ah", 37, ["remaliah"]),
    tf(2, "The RSV states: “In those days the LORD began to send Rezin the king of Syria and Pekah the son of Remali’ah against Judah.”", true, 37),
    blank(3, "_____ slept with his fathers, and was buried with his fathers in the city of", "Jotham", 38, ["jotham"]),
    mc(1, "Which word correctly completes this RSV wording: “_____ slept with his fathers, and was buried with his fathers in the city of”", ["Jotham", "Shallum", "Pekah", "Elah"], 38),
    word(2, "In verse 38, what word completes this phrase: “_____ slept with his fathers, and was buried with his fathers in the city of”?", "Jotham", 38, ["jotham"]),
    tf(3, "The RSV does not state: “Jotham slept with his fathers, and was buried with his fathers in the city of David his father; and Ahaz his son reigned in his stead.”", false, 38, "The quoted wording is the RSV text of this verse."),
    mc(2, "What affliction came upon Azariah, and how did it change his life?", ["He became a leper, lived in a separate house, and Jotham governed", "He became blind and Jotham led the army", "He lost the use of his feet and lived in the palace", "He became deaf and the priests governed"], 5),
    mc(3, "What promise was fulfilled when Zechariah completed Jehu’s fourth generation on Israel’s throne?", ["Your sons shall sit upon the throne of Israel to the fourth generation", "Your house shall rule Judah forever", "Your descendants shall rebuild Samaria", "Four kings shall arise from your servants"], 12),
  ],
};

export default bank;
