// 2 Kings 6 — quiz bank (RSV). Four verse-anchored forms per verse.
import { mc, blank, word, tf, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: "2 Kings",
  chapter: 6,
  tag: "quiz-v2-2kings-6",
  rows: [
    blank(2, "Now the sons of the prophets said to _____, \"See, the place where we dwell under your charge is too small for us.", "Eli’sha", 1, ["elisha"]),
    mc(3, "Which word correctly completes this RSV wording: “Now the sons of the prophets said to _____, \"See, the place where we dwell under your charge is too small for us.”", ["Eli’sha", "Syrians", "Help", "Jerusalem"], 1),
    word(1, "In verse 1, what word completes this phrase: “Now the sons of the prophets said to _____, \"See, the place where we dwell under your charge is too small for us.”?", "Eli’sha", 1, ["elisha"]),
    tf(2, "The RSV states: “Now the sons of the prophets said to Eli’sha, \"See, the place where we dwell under your charge is too small for us.”", true, 1),
    blank(3, "Let us go to the _____ and each of us get there a log, and let us make a place for us to dwell", "Jordan", 2, ["jordan"]),
    mc(1, "Which word correctly completes this RSV wording: “Let us go to the _____ and each of us get there a log, and let us make a place for us to dwell”", ["Jordan", "Sama’ria", "Once", "Jerusalem"], 2),
    word(2, "In verse 2, what word completes this phrase: “Let us go to the _____ and each of us get there a log, and let us make a place for us to dwell”?", "Jordan", 2, ["jordan"]),
    tf(3, "The RSV does not state: “Let us go to the Jordan and each of us get there a log, and let us make a place for us to dwell there.\" And he answered, \"Go.\"”", false, 2, "The quoted wording is the RSV text of this verse."),
    blank(1, "Then one of them said, \"Be pleased to go with your _____.\" And he answered, \"I will go.\"", "servants", 3, ["servants"]),
    mc(2, "Which word correctly completes this RSV wording: “Then one of them said, \"Be pleased to go with your _____.\" And he answered, \"I will go.\"”", ["servants", "master", "took", "pass"], 3),
    word(3, "In verse 3, what word completes this phrase: “Then one of them said, \"Be pleased to go with your _____.\" And he answered, \"I will go.\"”?", "servants", 3, ["servants"]),
    tf(1, "The RSV states: “Then one of them said, \"Be pleased to go with your servants.\" And he answered, \"I will go.\"”", true, 3),
    blank(2, "So he went with them. And when they came to the _____, they cut down trees.", "Jordan", 4, ["jordan"]),
    mc(3, "Which word correctly completes this RSV wording: “So he went with them. And when they came to the _____, they cut down trees.”", ["Jordan", "Beware", "Ben-ha’dad", "Jerusalem"], 4),
    word(1, "In verse 4, what word completes this phrase: “So he went with them. And when they came to the _____, they cut down trees.”?", "Jordan", 4, ["jordan"]),
    tf(2, "The RSV does not state: “So he went with them. And when they came to the Jordan, they cut down trees.”", false, 4, "The quoted wording is the RSV text of this verse."),
    blank(3, "was felling a log, his axe head fell into the water; and he cried out, \"_____, my master! It was borrowed.\"", "Alas", 5, ["alas"]),
    mc(1, "Which word correctly completes this RSV wording: “was felling a log, his axe head fell into the water; and he cried out, \"_____, my master! It was borrowed.\"”", ["Alas", "Sama’ria", "Syria", "Shall"], 5),
    word(2, "In verse 5, what word completes this phrase: “was felling a log, his axe head fell into the water; and he cried out, \"_____, my master! It was borrowed.\"”?", "Alas", 5, ["alas"]),
    tf(3, "The RSV states: “But as one was felling a log, his axe head fell into the water; and he cried out, \"Alas, my master! It was borrowed.\"”", true, 5),
    blank(1, "Then the man of God said, \"Where did it fall?\" When he _____ him the place, he cut off a stick, and threw it in there, and made the", "showed", 6, ["showed"]),
    mc(2, "Which word correctly completes this RSV wording: “Then the man of God said, \"Where did it fall?\" When he _____ him the place, he cut off a stick, and threw it in there, and made the”", ["showed", "word", "mind", "bedchamber"], 6),
    word(3, "In verse 6, what word completes this phrase: “Then the man of God said, \"Where did it fall?\" When he _____ him the place, he cut off a stick, and threw it in there, and made the”?", "showed", 6, ["showed"]),
    tf(1, "The RSV does not state: “Then the man of God said, \"Where did it fall?\" When he showed him the place, he cut off a stick, and threw it in there, and made the iron float.”", false, 6, "The quoted wording is the RSV text of this verse."),
    blank(2, "And he said, \"_____ it up.\" So he reached out his hand and took it.", "Take", 7, ["take"]),
    mc(3, "Which word correctly completes this RSV wording: “And he said, \"_____ it up.\" So he reached out his hand and took it.”", ["Take", "Syrians", "Give", "Thus"], 7),
    word(1, "In verse 7, what word completes this phrase: “And he said, \"_____ it up.\" So he reached out his hand and took it.”?", "Take", 7, ["take"]),
    tf(2, "The RSV states: “And he said, \"Take it up.\" So he reached out his hand and took it.”", true, 7),
    blank(3, "Once when the king of Syria was warring against _____, he took counsel with his servants, saying, \"At such and such a place", "Israel", 8, ["israel"]),
    mc(1, "Which word correctly completes this RSV wording: “Once when the king of Syria was warring against _____, he took counsel with his servants, saying, \"At such and such a place”", ["Israel", "Fear", "Jordan", "Jerusalem"], 8),
    word(2, "In verse 8, what word completes this phrase: “Once when the king of Syria was warring against _____, he took counsel with his servants, saying, \"At such and such a place”?", "Israel", 8, ["israel"]),
    tf(3, "The RSV does not state: “Once when the king of Syria was warring against Israel, he took counsel with his servants, saying, \"At such and such a place shall be my camp.\"”", false, 8, "The quoted wording is the RSV text of this verse."),
    blank(1, "the king of Israel, \"Beware that you do not pass this place, for the _____ are going down there.\"", "Syrians", 9, ["syrians"]),
    mc(2, "Which word correctly completes this RSV wording: “the king of Israel, \"Beware that you do not pass this place, for the _____ are going down there.\"”", ["Syrians", "Give", "Thus", "Jerusalem"], 9),
    word(3, "In verse 9, what word completes this phrase: “the king of Israel, \"Beware that you do not pass this place, for the _____ are going down there.\"”?", "Syrians", 9, ["syrians"]),
    tf(1, "The RSV states: “But the man of God sent word to the king of Israel, \"Beware that you do not pass this place, for the Syrians are going down there.\"”", true, 9),
    blank(2, "And the king of _____ sent to the place of which the man of God told him. Thus he used to warn", "Israel", 10, ["israel"]),
    mc(3, "Which word correctly completes this RSV wording: “And the king of _____ sent to the place of which the man of God told him. Thus he used to warn”", ["Israel", "Once", "Shall", "Jerusalem"], 10),
    word(1, "In verse 10, what word completes this phrase: “And the king of _____ sent to the place of which the man of God told him. Thus he used to warn”?", "Israel", 10, ["israel"]),
    tf(2, "The RSV does not state: “And the king of Israel sent to the place of which the man of God told him. Thus he used to warn him, so that he saved himself there more than once or twice.”", false, 10, "The quoted wording is the RSV text of this verse."),
    blank(3, "and said to them, \"Will you not show me who of us is for the king of _____?\"", "Israel", 11, ["israel"]),
    mc(1, "Which word correctly completes this RSV wording: “and said to them, \"Will you not show me who of us is for the king of _____?\"”", ["Israel", "Dothan", "Eli’sha", "Jerusalem"], 11),
    word(2, "In verse 11, what word completes this phrase: “and said to them, \"Will you not show me who of us is for the king of _____?\"”?", "Israel", 11, ["israel"]),
    tf(3, "The RSV states: “And the mind of the king of Syria was greatly troubled because of this thing; and he called his servants and said to them, \"Will you not show me who of us is for the king of Israel?\"”", true, 11),
    blank(1, "And one of his servants said, \"None, my lord, O king; but _____, the prophet who is in Israel, tells the king of Israel the words that", "Eli’sha", 12, ["elisha"]),
    mc(2, "Which word correctly completes this RSV wording: “And one of his servants said, \"None, my lord, O king; but _____, the prophet who is in Israel, tells the king of Israel the words that”", ["Eli’sha", "Help", "Syrians", "Jerusalem"], 12),
    word(3, "In verse 12, what word completes this phrase: “And one of his servants said, \"None, my lord, O king; but _____, the prophet who is in Israel, tells the king of Israel the words that”?", "Eli’sha", 12, ["elisha"]),
    tf(1, "The RSV does not state: “And one of his servants said, \"None, my lord, O king; but Eli’sha, the prophet who is in Israel, tells the king of Israel the words that you speak in your bedchamber.\"”", false, 12, "The quoted wording is the RSV text of this verse."),
    blank(2, "and see where he is, that I may send and seize him.\" It was told him, \"_____, he is in Dothan.\"", "Behold", 13, ["behold"]),
    mc(3, "Which word correctly completes this RSV wording: “and see where he is, that I may send and seize him.\" It was told him, \"_____, he is in Dothan.\"”", ["Behold", "Take", "Sama’ria", "Jerusalem"], 13),
    word(1, "In verse 13, what word completes this phrase: “and see where he is, that I may send and seize him.\" It was told him, \"_____, he is in Dothan.\"”?", "Behold", 13, ["behold"]),
    tf(2, "The RSV states: “And he said, \"Go and see where he is, that I may send and seize him.\" It was told him, \"Behold, he is in Dothan.\"”", true, 13),
    blank(3, "there horses and chariots and a great army; and they came by night, and _____ the city.", "surrounded", 14, ["surrounded"]),
    mc(1, "Which word correctly completes this RSV wording: “there horses and chariots and a great army; and they came by night, and _____ the city.”", ["surrounded", "heard", "presence", "longer"], 14),
    word(2, "In verse 14, what word completes this phrase: “there horses and chariots and a great army; and they came by night, and _____ the city.”?", "surrounded", 14, ["surrounded"]),
    tf(3, "The RSV does not state: “So he sent there horses and chariots and a great army; and they came by night, and surrounded the city.”", false, 14, "The quoted wording is the RSV text of this verse."),
    blank(1, "horses and chariots was round about the city. And the servant said, \"_____, my master! What shall we do?\"", "Alas", 15, ["alas"]),
    mc(2, "Which word correctly completes this RSV wording: “horses and chariots was round about the city. And the servant said, \"_____, my master! What shall we do?\"”", ["Alas", "Eli’sha", "Dothan", "Jordan"], 15),
    word(3, "In verse 15, what word completes this phrase: “horses and chariots was round about the city. And the servant said, \"_____, my master! What shall we do?\"”?", "Alas", 15, ["alas"]),
    tf(1, "The RSV states: “When the servant of the man of God rose early in the morning and went out, behold, an army with horses and chariots was round about the city. And the servant said, \"Alas, my master! What shall we do?\"”", true, 15),
    blank(2, "He said, \"_____ not, for those who are with us are more than those who are with them.\"", "Fear", 16, ["fear"]),
    mc(3, "Which word correctly completes this RSV wording: “He said, \"_____ not, for those who are with us are more than those who are with them.\"”", ["Fear", "Beware", "Give", "Syrians"], 16),
    word(1, "In verse 16, what word completes this phrase: “He said, \"_____ not, for those who are with us are more than those who are with them.\"”?", "Fear", 16, ["fear"]),
    tf(2, "The RSV does not state: “He said, \"Fear not, for those who are with us are more than those who are with them.\"”", false, 16, "The quoted wording is the RSV text of this verse."),
    blank(3, "Then _____ prayed, and said, \"O LORD, I pray thee, open his eyes that he may see.\"", "Eli’sha", 17, ["elisha"]),
    mc(1, "Which word correctly completes this RSV wording: “Then _____ prayed, and said, \"O LORD, I pray thee, open his eyes that he may see.\"”", ["Eli’sha", "None", "Shaphat", "Jerusalem"], 17),
    word(2, "In verse 17, what word completes this phrase: “Then _____ prayed, and said, \"O LORD, I pray thee, open his eyes that he may see.\"”?", "Eli’sha", 17, ["elisha"]),
    tf(3, "The RSV states: “Then Eli’sha prayed, and said, \"O LORD, I pray thee, open his eyes that he may see.\" So the LORD opened the eyes of the young man, and he saw; and behold, the mountain was full of horses and chariots of fire round about Eli’sha.”", true, 17),
    blank(1, "And when the _____ came down against him, Eli’sha prayed to the LORD, and said, \"Strike this", "Syrians", 18, ["syrians"]),
    mc(2, "Which word correctly completes this RSV wording: “And when the _____ came down against him, Eli’sha prayed to the LORD, and said, \"Strike this”", ["Syrians", "Afterward", "Syria", "Jerusalem"], 18),
    word(3, "In verse 18, what word completes this phrase: “And when the _____ came down against him, Eli’sha prayed to the LORD, and said, \"Strike this”?", "Syrians", 18, ["syrians"]),
    tf(1, "The RSV does not state: “And when the Syrians came down against him, Eli’sha prayed to the LORD, and said, \"Strike this people, I pray thee, with blindness.\" So he struck them with blindness in accordance with the prayer of Eli’sha.”", false, 18, "The quoted wording is the RSV text of this verse."),
    blank(2, "me, and I will bring you to the man whom you seek.\" And he led them to _____.", "Sama’ria", 19, ["samaria"]),
    mc(3, "Which word correctly completes this RSV wording: “me, and I will bring you to the man whom you seek.\" And he led them to _____.”", ["Sama’ria", "Jordan", "Dothan", "Jerusalem"], 19),
    word(1, "In verse 19, what word completes this phrase: “me, and I will bring you to the man whom you seek.\" And he led them to _____.”?", "Sama’ria", 19, ["samaria"]),
    tf(2, "The RSV states: “And Eli’sha said to them, \"This is not the way, and this is not the city; follow me, and I will bring you to the man whom you seek.\" And he led them to Sama’ria.”", true, 19),
    blank(3, "As soon as they entered _____, Eli’sha said, \"O LORD, open the eyes of these men, that they may see.\"", "Sama’ria", 20, ["samaria"]),
    mc(1, "Which word correctly completes this RSV wording: “As soon as they entered _____, Eli’sha said, \"O LORD, open the eyes of these men, that they may see.\"”", ["Sama’ria", "Syrians", "Give", "Jerusalem"], 20),
    word(2, "In verse 20, what word completes this phrase: “As soon as they entered _____, Eli’sha said, \"O LORD, open the eyes of these men, that they may see.\"”?", "Sama’ria", 20, ["samaria"]),
    tf(3, "The RSV does not state: “As soon as they entered Sama’ria, Eli’sha said, \"O LORD, open the eyes of these men, that they may see.\" So the LORD opened their eyes, and they saw; and lo, they were in the midst of Sama’ria.”", false, 20, "The quoted wording is the RSV text of this verse."),
    blank(1, "When the king of Israel saw them he said to _____, \"My father, shall I slay them? Shall I slay them?\"", "Eli’sha", 21, ["elisha"]),
    mc(2, "Which word correctly completes this RSV wording: “When the king of Israel saw them he said to _____, \"My father, shall I slay them? Shall I slay them?\"”", ["Eli’sha", "Shall", "Syria", "Jerusalem"], 21),
    word(3, "In verse 21, what word completes this phrase: “When the king of Israel saw them he said to _____, \"My father, shall I slay them? Shall I slay them?\"”?", "Eli’sha", 21, ["elisha"]),
    tf(1, "The RSV states: “When the king of Israel saw them he said to Eli’sha, \"My father, shall I slay them? Shall I slay them?\"”", true, 21),
    blank(2, "He _____, \"You shall not slay them. Would you slay those whom you have taken captive", "answered", 22, ["answered"]),
    mc(3, "Which word correctly completes this RSV wording: “He _____, \"You shall not slay them. Would you slay those whom you have taken captive”", ["answered", "beneath", "arrived", "behind"], 22),
    word(1, "In verse 22, what word completes this phrase: “He _____, \"You shall not slay them. Would you slay those whom you have taken captive”?", "answered", 22, ["answered"]),
    tf(2, "The RSV does not state: “He answered, \"You shall not slay them. Would you slay those whom you have taken captive with your sword and with your bow? Set bread and water before them, that they may eat and drink and go to their master.\"”", false, 22, "The quoted wording is the RSV text of this verse."),
    blank(3, "and drunk, he sent them away, and they went to their master. And the _____ came no more on raids into the land of Israel.", "Syrians", 23, ["syrians"]),
    mc(1, "Which word correctly completes this RSV wording: “and drunk, he sent them away, and they went to their master. And the _____ came no more on raids into the land of Israel.”", ["Syrians", "Beware", "Help", "Jerusalem"], 23),
    word(2, "In verse 23, what word completes this phrase: “and drunk, he sent them away, and they went to their master. And the _____ came no more on raids into the land of Israel.”?", "Syrians", 23, ["syrians"]),
    tf(3, "The RSV states: “So he prepared for them a great feast; and when they had eaten and drunk, he sent them away, and they went to their master. And the Syrians came no more on raids into the land of Israel.”", true, 23),
    blank(1, "Afterward _____ king of Syria mustered his entire army, and went up, and besieged Sama’ria.", "Ben-ha’dad", 24, ["ben-hadad"]),
    mc(2, "Which word correctly completes this RSV wording: “Afterward _____ king of Syria mustered his entire army, and went up, and besieged Sama’ria.”", ["Ben-ha’dad", "Shaphat", "Shall", "Strike"], 24),
    word(3, "In verse 24, what word completes this phrase: “Afterward _____ king of Syria mustered his entire army, and went up, and besieged Sama’ria.”?", "Ben-ha’dad", 24, ["ben-hadad"]),
    tf(1, "The RSV does not state: “Afterward Ben-ha’dad king of Syria mustered his entire army, and went up, and besieged Sama’ria.”", false, 24, "The quoted wording is the RSV text of this verse."),
    blank(2, "And there was a great famine in _____, as they besieged it, until an ass’s head was sold for eighty shekels", "Sama’ria", 25, ["samaria"]),
    mc(3, "Which word correctly completes this RSV wording: “And there was a great famine in _____, as they besieged it, until an ass’s head was sold for eighty shekels”", ["Sama’ria", "Look", "None", "Jerusalem"], 25),
    word(1, "In verse 25, what word completes this phrase: “And there was a great famine in _____, as they besieged it, until an ass’s head was sold for eighty shekels”?", "Sama’ria", 25, ["samaria"]),
    tf(2, "The RSV states: “And there was a great famine in Sama’ria, as they besieged it, until an ass’s head was sold for eighty shekels of silver, and the fourth part of a kab of dove’s dung for five shekels of silver.”", true, 25),
    blank(3, "Now as the king of _____ was passing by upon the wall, a woman cried out to him, saying, \"Help,", "Israel", 26, ["israel"]),
    mc(1, "Which word correctly completes this RSV wording: “Now as the king of _____ was passing by upon the wall, a woman cried out to him, saying, \"Help,”", ["Israel", "Beware", "Ben-ha’dad", "Jerusalem"], 26),
    word(2, "In verse 26, what word completes this phrase: “Now as the king of _____ was passing by upon the wall, a woman cried out to him, saying, \"Help,”?", "Israel", 26, ["israel"]),
    tf(3, "The RSV does not state: “Now as the king of Israel was passing by upon the wall, a woman cried out to him, saying, \"Help, my lord, O king!\"”", false, 26, "The quoted wording is the RSV text of this verse."),
    blank(1, "said, \"If the LORD will not help you, whence shall I help you? From the _____ floor, or from the wine press?\"", "threshing", 27, ["threshing"]),
    mc(2, "Which word correctly completes this RSV wording: “said, \"If the LORD will not help you, whence shall I help you? From the _____ floor, or from the wine press?\"”", ["threshing", "small", "head", "iron"], 27),
    word(3, "In verse 27, what word completes this phrase: “said, \"If the LORD will not help you, whence shall I help you? From the _____ floor, or from the wine press?\"”?", "threshing", 27, ["threshing"]),
    tf(1, "The RSV states: “And he said, \"If the LORD will not help you, whence shall I help you? From the threshing floor, or from the wine press?\"”", true, 27),
    blank(2, "asked her, \"What is your trouble?\" She answered, \"This woman said to me, `_____ your son, that we may eat him today, and we will eat my son tomorrow.’", "Give", 28, ["give"]),
    mc(3, "Which word correctly completes this RSV wording: “asked her, \"What is your trouble?\" She answered, \"This woman said to me, `_____ your son, that we may eat him today, and we will eat my son tomorrow.’”", ["Give", "Beware", "Help", "Syrians"], 28),
    word(1, "In verse 28, what word completes this phrase: “asked her, \"What is your trouble?\" She answered, \"This woman said to me, `_____ your son, that we may eat him today, and we will eat my son tomorrow.’”?", "Give", 28, ["give"]),
    tf(2, "The RSV does not state: “And the king asked her, \"What is your trouble?\" She answered, \"This woman said to me, `Give your son, that we may eat him today, and we will eat my son tomorrow.’”", false, 28, "The quoted wording is the RSV text of this verse."),
    blank(3, "So we boiled my son, and ate him. And on the next day I said to her, `_____ your son, that we may eat him’; but she has hidden her son.\"", "Give", 29, ["give"]),
    mc(1, "Which word correctly completes this RSV wording: “So we boiled my son, and ate him. And on the next day I said to her, `_____ your son, that we may eat him’; but she has hidden her son.\"”", ["Give", "Strike", "Once", "Sama’ria"], 29),
    word(2, "In verse 29, what word completes this phrase: “So we boiled my son, and ate him. And on the next day I said to her, `_____ your son, that we may eat him’; but she has hidden her son.\"”?", "Give", 29, ["give"]),
    tf(3, "The RSV states: “So we boiled my son, and ate him. And on the next day I said to her, `Give your son, that we may eat him’; but she has hidden her son.\"”", true, 29),
    blank(1, "passing by upon the wall -- and the people looked, and behold, he had _____ beneath upon his body --", "sackcloth", 30, ["sackcloth"]),
    mc(2, "Which word correctly completes this RSV wording: “passing by upon the wall -- and the people looked, and behold, he had _____ beneath upon his body --”", ["sackcloth", "made", "such", "himself"], 30),
    word(3, "In verse 30, what word completes this phrase: “passing by upon the wall -- and the people looked, and behold, he had _____ beneath upon his body --”?", "sackcloth", 30, ["sackcloth"]),
    tf(1, "The RSV does not state: “When the king heard the words of the woman he rent his clothes -- now he was passing by upon the wall -- and the people looked, and behold, he had sackcloth beneath upon his body --”", false, 30, "The quoted wording is the RSV text of this verse."),
    blank(2, "and he said, \"May God do so to me, and more also, if the head of _____ the son of Shaphat remains on his shoulders today.\"", "Eli’sha", 31, ["elisha"]),
    mc(3, "Which word correctly completes this RSV wording: “and he said, \"May God do so to me, and more also, if the head of _____ the son of Shaphat remains on his shoulders today.\"”", ["Eli’sha", "Give", "Thus", "Jerusalem"], 31),
    word(1, "In verse 31, what word completes this phrase: “and he said, \"May God do so to me, and more also, if the head of _____ the son of Shaphat remains on his shoulders today.\"”?", "Eli’sha", 31, ["elisha"]),
    tf(2, "The RSV states: “and he said, \"May God do so to me, and more also, if the head of Eli’sha the son of Shaphat remains on his shoulders today.\"”", true, 31),
    blank(3, "_____ was sitting in his house, and the elders were sitting with him. Now the", "Eli’sha", 32, ["elisha"]),
    mc(1, "Which word correctly completes this RSV wording: “_____ was sitting in his house, and the elders were sitting with him. Now the”", ["Eli’sha", "Syria", "Shall", "Jerusalem"], 32),
    word(2, "In verse 32, what word completes this phrase: “_____ was sitting in his house, and the elders were sitting with him. Now the”?", "Eli’sha", 32, ["elisha"]),
    tf(3, "The RSV does not state: “Eli’sha was sitting in his house, and the elders were sitting with him. Now the king had dispatched a man from his presence; but before the messenger arrived Eli’sha said to the elders, \"Do you see how this murderer has sent to take off my head? Look, when the messenger comes, shut the door, and hold the door fast against him. Is not the sound of his master’s feet behind him?\"”", false, 32, "The quoted wording is the RSV text of this verse."),
    blank(1, "And while he was still _____ with them, the king came down to him and said, \"This trouble is from the", "speaking", 33, ["speaking"]),
    mc(2, "Which word correctly completes this RSV wording: “And while he was still _____ with them, the king came down to him and said, \"This trouble is from the”", ["speaking", "saved", "show", "army"], 33),
    word(3, "In verse 33, what word completes this phrase: “And while he was still _____ with them, the king came down to him and said, \"This trouble is from the”?", "speaking", 33, ["speaking"]),
    tf(1, "The RSV states: “And while he was still speaking with them, the king came down to him and said, \"This trouble is from the LORD! Why should I wait for the LORD any longer?\"”", true, 33),
    mc(1, "Why was the prophet’s son distressed when his axe head fell into the Jordan, and how did Elisha recover it?", ["The axe was borrowed; Elisha threw in a stick and made the iron float", "The axe belonged to the king; Elisha divided the river", "The axe was sacred; Elisha sent a diver", "The axe was his father’s; Elisha prayed for the river to dry"], 6),
    mc(2, "How did Syria’s servant explain Israel’s knowledge of the king’s secret plans?", ["Elisha tells Israel’s king the words spoken in the Syrian king’s bedchamber", "A Syrian captain was sending letters", "Israel had spies inside the palace", "The LORD spoke directly to Israel’s army"], 12),
    mc(3, "What did Elisha’s servant see after Elisha prayed that his eyes be opened?", ["The mountain full of horses and chariots of fire around Elisha", "The Syrian army struck blind", "An angel standing in Dothan’s gate", "A whirlwind carrying Elijah"], 17),
    mc(3, "How much did an ass’s head cost during the siege of Samaria?", ["Eighty shekels of silver", "Forty shekels of silver", "Five shekels of gold", "Two talents of silver"], 25),
  ],
};

export default bank;
