import type { QuizDifficulty, QuizType, ScriptureBookSlug } from '../../lib/types'

export type CrossReference = { book:'1 Kings'|'2 Kings'; book_slug:ScriptureBookSlug; chapter:number; verse_start:number; verse_end?:number; label:string }
export type ComprehensiveRow = { type:QuizType; difficulty:QuizDifficulty; question:string; options?:string[]; answer?:string; accepted_answers?:string[]; explanation:string; supporting_refs:CrossReference[]; review_topic:string; review_guidance:string }
const r=(book:'1 Kings'|'2 Kings',chapter:number,verse_start:number,verse_end?:number):CrossReference=>({book,book_slug:book==='1 Kings'?'1-kings':'2-kings',chapter,verse_start,verse_end,label:`${book} ${chapter}:${verse_start}${verse_end&&verse_end!==verse_start?`–${verse_end}`:''}`})
const mc=(difficulty:QuizDifficulty,question:string,correct:string,distractors:[string,string,string],explanation:string,supporting_refs:CrossReference[],review_topic:string,review_guidance:string):ComprehensiveRow=>({type:'multiple_choice',difficulty,question,options:[correct,...distractors],explanation,supporting_refs,review_topic,review_guidance})

export const rows:ComprehensiveRow[]=[
mc(1,'Which two prophets in Kings restored a woman’s son to life?','Elijah and Elisha',['Nathan and Ahijah','Micaiah and Isaiah','Jehu and Huldah'],'Elijah restored the widow of Zarephath’s son, and Elisha restored the Shunammite woman’s son.',[r('1 Kings',17,17,24),r('2 Kings',4,32,37)],'Children restored to life','Compare how Elijah and Elisha responded when each mother’s son died.'),
mc(2,'What did Elijah’s and Elisha’s miracles for widows in financial danger have in common?','God multiplied a small household supply so it met an urgent need',['Each widow found treasure buried in her field','A king supported each widow permanently from his treasury','Each widow was told to sell her home and leave Israel'],'The widow at Zarephath’s meal and oil did not fail, while Elisha’s widow filled vessels from one jar of oil and sold it to pay her debt.',[r('1 Kings',17,8,16),r('2 Kings',4,1,7)],'Provision for widows','Review what each widow possessed initially and how God provided through it.'),
mc(2,'Which statement correctly compares Elijah’s drought with the famine Elisha announced to the Shunammite woman?','Elijah said rain would cease, while Elisha warned of a famine lasting seven years',['Both were seven-year famines caused by a siege','Elisha announced the drought first and Elijah later ended it','Both warnings were given directly to Ahab in Samaria'],'Elijah announced that dew and rain would cease; Elisha later warned that the LORD had called for a seven-year famine.',[r('1 Kings',17,1),r('2 Kings',8,1,2)],'Prophetic warnings of famine','Study what each prophet announced, how the crisis was described, and who received the warning.'),
mc(2,'Which two capital cities suffered severe famine while surrounded by enemy armies?','Samaria and Jerusalem',['Bethel and Dan','Jericho and Gilgal','Jezreel and Gibeon'],'Samaria suffered famine during the Syrian siege, and Jerusalem during the Babylonian siege.',[r('2 Kings',6,24,30),r('2 Kings',25,1,4)],'Siege famines','Compare the siege of Samaria with Babylon’s final siege of Jerusalem.'),
mc(3,'How did the outcomes of the siege famines in Samaria and Jerusalem differ?','Samaria was unexpectedly delivered, but Jerusalem was breached and its people exiled',['Both cities were destroyed and their populations exiled','Jerusalem was delivered overnight, but Samaria was burned','Both sieges ended when the defending king defeated the enemy'],'The Syrians abandoned their camp outside Samaria; Babylon breached Jerusalem, destroyed it, and carried Judah away.',[r('2 Kings',7,3,16),r('2 Kings',25,1,12)],'Deliverance and exile','Trace how each siege ended and what happened to the residents afterward.'),
mc(2,'What marked the beginning and public confirmation of Elisha’s call to succeed Elijah?','Elijah placed his mantle on Elisha, and later Elisha divided the Jordan with it',['Elijah crowned Elisha at Gihon, and Elisha built an altar at Bethel','Elisha defeated the prophets of Baal, and Elijah made him king','Elisha interpreted a dream, and later received the temple scroll'],'Elijah first cast his mantle on Elisha. After Elijah was taken up, Elisha used it to divide the Jordan.',[r('1 Kings',19,19,21),r('2 Kings',2,13,15)],'Elisha succeeds Elijah','Follow the mantle from Elisha’s call through his return across the Jordan.'),
mc(2,'How did Jehu’s reform remain incomplete after he destroyed Baal worship in Israel?','He continued the worship of Jeroboam’s golden calves at Bethel and Dan',['He restored Jezebel as queen in Samaria','He immediately rebuilt Baal’s temple','He required Judah to worship Baal'],'Jehu eliminated Baal worship but did not turn from Jeroboam’s golden calves.',[r('1 Kings',12,26,33),r('2 Kings',10,18,31)],'Jehu’s incomplete reform','Review the worship system Jeroboam established and what Jehu allowed to remain.'),
mc(2,'Which later king of Judah fulfilled the prophecy against Jeroboam’s altar at Bethel?','Josiah',['Hezekiah','Jehoshaphat','Joash'],'A man of God named Josiah long before his birth; Josiah later demolished and defiled the altar.',[r('1 Kings',13,1,3),r('2 Kings',23,15,20)],'Josiah and Bethel','Compare the prediction during Jeroboam’s reign with Josiah’s actions at Bethel.'),
mc(2,'How was Elijah’s judgment against Jezebel eventually fulfilled?','She was thrown from a window at Jezreel, and dogs consumed her body',['She died in exile in Babylon and received a royal burial','She was killed on Mount Carmel with the prophets of Baal','She fled to Sidon and died during the drought'],'Elijah foretold that dogs would eat Jezebel by the wall of Jezreel; her death under Jehu fulfilled it.',[r('1 Kings',21,23),r('2 Kings',9,30,37)],'Judgment on Jezebel','Review Elijah’s sentence after Naboth’s murder and the account of Jezebel’s death.'),
mc(2,'What earlier sin explains why dogs licking Ahab’s blood was presented as divine judgment?','Ahab and Jezebel arranged Naboth’s death and seized his vineyard',['Ahab refused to build the temple in Jerusalem','Ahab stole Naaman’s gifts from Elisha','Ahab destroyed the book of the law'],'After Naboth was falsely accused and killed, Elijah pronounced judgment on Ahab’s house.',[r('1 Kings',21,7,24),r('1 Kings',22,34,38)],'Naboth and Ahab','Connect the seizure of Naboth’s vineyard with Elijah’s sentence and Ahab’s death.'),
mc(2,'What did Baasha and Zimri have in common in the way they gained power and were judged?','Each seized Israel’s throne violently, destroyed the previous royal house, and faced judgment on his own house',['Each inherited Judah’s throne peacefully','Each removed the golden calves and restored Jerusalem worship','Each was appointed king by Jezebel'],'Baasha destroyed Jeroboam’s house, and Zimri later destroyed Baasha’s house.',[r('1 Kings',15,27,30),r('1 Kings',16,9,13)],'Violent dynastic cycles','Trace how Jeroboam’s house ended and how the same pattern overtook Baasha’s house.'),
mc(1,'Which two kings of Judah were commended for doing right, yet failed to remove the high places?','Asa and Jehoshaphat',['Ahaz and Manasseh','Ahab and Jehu','Zedekiah and Jehoahaz'],'Asa and Jehoshaphat were evaluated positively, but the high places remained.',[r('1 Kings',15,9,15),r('1 Kings',22,41,44)],'Qualified reform','Compare the narrator’s evaluation of Asa and Jehoshaphat.'),
mc(2,'How did Manasseh treat the religious reforms made by his father Hezekiah?','He reversed them by rebuilding high places and restoring idolatrous worship',['He completed them by destroying the temple','He extended them into Israel after defeating Assyria','He preserved them unchanged'],'Hezekiah removed high places and idols, but Manasseh rebuilt high places and erected altars to other gods.',[r('2 Kings',18,1,6),r('2 Kings',21,1,9)],'Hezekiah and Manasseh','List what Hezekiah removed and which practices Manasseh restored.'),
mc(3,'What contrast does Kings draw between Ahaz and his son Hezekiah in responding to Assyria?','Ahaz sought Assyria’s help and gave it treasure, while Hezekiah trusted the LORD and rebelled',['Ahaz defeated Assyria, while Hezekiah became its servant','Both trusted Assyria and emptied the temple treasury','Both refused either political action or prayer'],'Ahaz appealed to Tiglath-pileser and sent treasure; Hezekiah trusted the LORD and refused submission.',[r('2 Kings',16,5,9),r('2 Kings',18,1,8)],'Ahaz and Hezekiah','Compare each king’s source of security when facing stronger nations.'),
mc(2,'What discovery led Josiah to renew the covenant and carry out a sweeping reform?','The book of the law was found in the temple',['Elijah’s mantle was found beside the Jordan','Solomon’s treasury was uncovered under the altar','The bronze serpent began speaking'],'After Hilkiah found the book of the law, Josiah humbled himself, renewed the covenant, and removed idolatry.',[r('2 Kings',22,8,20),r('2 Kings',23,1,25)],'Josiah’s reform','Follow the sequence from finding the book to renewing the covenant and reforming worship.'),
mc(2,'How did Joash’s survival as a child protect the promise connected with David’s royal line?','His rescue from Athaliah preserved a living heir from David’s family',['His rescue permanently united Israel and Judah under Jehu','He became a prophet and replaced Elisha','He returned the northern tribes from exile'],'Athaliah tried to destroy the royal family, but Joash was hidden and later crowned.',[r('1 Kings',11,32,36),r('2 Kings',11,1,12)],'David’s line','Connect God’s promise of a lamp for David with the hiding and coronation of Joash.'),
mc(3,'What warning given after Solomon built the temple explains the later exile of Israel?','Persistent rejection of the LORD and service to other gods would lead to removal from the land',['Failure to enlarge the temple would cause Egypt to conquer Israel','Refusal to appoint a second high priest would divide the kingdom','Trade with Tyre would automatically end David’s dynasty'],'God warned Solomon that idolatry would bring removal; 2 Kings explains Israel’s exile in those terms.',[r('1 Kings',9,6,9),r('2 Kings',17,7,23)],'Covenant warning and exile','Compare the temple warning with the explanation for Israel’s fall.'),
mc(3,'How did Solomon’s temple change from its dedication to the fall of Jerusalem?','It went from housing the ark to being burned and stripped by Babylon',['It was moved intact from Jerusalem to Samaria','It became Ahab’s temple of Baal and was destroyed by Jehu','It remained untouched while only the palace was destroyed'],'Solomon brought the ark into the completed temple; Babylon later burned it and removed its furnishings.',[r('1 Kings',8,1,21),r('2 Kings',25,8,17)],'The temple’s story','Compare what entered the temple at dedication with what was removed at Jerusalem’s fall.'),
mc(3,'Which event fulfilled Isaiah’s warning after Hezekiah displayed his treasures to Babylonian envoys?','Babylon carried away Jerusalem’s treasures and leading people',['Assyria returned the northern tribes to Samaria','Egypt restored Solomon’s son to the throne','Tyre rebuilt the temple with cedar and gold'],'Isaiah warned that the treasures and descendants would go to Babylon; the deportations later fulfilled it.',[r('2 Kings',20,12,19),r('2 Kings',24,10,16)],'Babylon foretold','Connect what Hezekiah showed the envoys with what Babylon later removed.'),
mc(3,'How does the ending of Kings leave a small sign of hope for David’s line after Jerusalem’s destruction?','The exiled king Jehoiachin was released and given an honored place in Babylon',['Solomon returned to rebuild the temple','Zedekiah escaped and restored Judah immediately','The northern tribes crowned Josiah’s grandson in Samaria'],'The final scene preserves and honors a descendant of David rather than ending with his death in prison.',[r('2 Kings',24,8,16),r('2 Kings',25,27,30)],'Hope after exile','Follow Jehoiachin from deportation to release and honored treatment.'),
mc(2,'How did Solomon’s many foreign marriages affect the future of his kingdom?','They turned his heart toward other gods, and the LORD announced that most of the kingdom would be torn from his son',['They persuaded every neighboring nation to worship in Jerusalem','They caused David to replace Solomon with Adonijah','They ended Israel’s trade with Egypt and Tyre'],'Solomon’s wives turned his heart to other gods, and the announced judgment took visible form when the northern tribes rejected Rehoboam.',[r('1 Kings',11,1,13),r('1 Kings',12,16,20)],'Solomon and the divided kingdom','Connect Solomon’s unfaithfulness and its announced consequence with the division under Rehoboam.'),
mc(2,'What mistake by Rehoboam helped turn the threatened division of Solomon’s kingdom into reality?','He rejected the elders’ advice and threatened to make the people’s burden heavier',['He gave the northern tribes all the temple treasure','He appointed Jeroboam high priest in Jerusalem','He refused to become king unless Egypt approved'],'Rehoboam answered the people harshly, so the northern tribes rejected David’s house and made Jeroboam king.',[r('1 Kings',11,29,39),r('1 Kings',12,1,20)],'The kingdom divides','Compare Ahijah’s prophecy with Rehoboam’s response to the people.'),
mc(2,'Why did Jeroboam establish golden calves at Bethel and Dan?','He feared that worship in Jerusalem would turn the northern tribes back to Rehoboam',['Elijah commanded him to replace the ark with calves','Solomon had already moved the temple worship to those cities','Egypt required the calves as payment for military aid'],'Jeroboam treated loyalty to Jerusalem’s temple as a political threat and created rival worship centers.',[r('1 Kings',12,26,33),r('2 Kings',17,21,23)],'Jeroboam’s lasting sin','Review Jeroboam’s political fear and how Kings later describes its effect on Israel.'),
mc(3,'Why is the phrase “the sins of Jeroboam” important throughout the history of the northern kingdom?','It identifies the rival calf worship that later kings repeatedly continued',['It refers to Jeroboam’s construction of Solomon’s temple','It describes the census that caused David’s plague','It means Jeroboam surrendered Israel to Assyria'],'The narrator repeatedly measures Israel’s kings against Jeroboam’s founding system of false worship.',[r('1 Kings',12,26,33),r('1 Kings',16,25,26),r('2 Kings',10,29,31),r('2 Kings',17,21,23)],'The sins of Jeroboam','Track the repeated evaluation of northern kings and the final explanation of Israel’s exile.'),
mc(2,'What common purpose connected Solomon’s temple dedication and Hezekiah’s prayer during the Assyrian threat?','Both appealed to the LORD as the God who hears prayer and makes his name known among the nations',['Both asked permission to move the temple to Samaria','Both promised to worship Assyria’s gods if Jerusalem survived','Both asked that Judah never experience discipline for sin'],'Solomon prayed that God would hear and that all peoples would know him; Hezekiah asked deliverance so the kingdoms would know that the LORD alone is God.',[r('1 Kings',8,22,43),r('2 Kings',19,14,19)],'Prayer and God’s name','Compare the wider purpose stated in Solomon’s prayer and Hezekiah’s plea.'),
mc(2,'How did Elijah’s contest on Mount Carmel directly answer Ahab and Jezebel’s promotion of Baal worship?','The LORD answered by fire, showing the people that he—not Baal—is God',['Baal sent rain before Elijah prayed','Jezebel publicly destroyed Baal’s altar herself','Ahab appointed Elijah chief priest of Baal'],'Ahab established Baal worship, but at Carmel the LORD’s fire exposed Baal’s powerlessness and turned the people’s confession back to the LORD.',[r('1 Kings',16,29,33),r('1 Kings',18,20,39)],'Baal and Mount Carmel','Connect Ahab’s religious policy with the question Elijah put before Israel at Carmel.'),
mc(2,'What did Micaiah’s warning and Ahab’s death demonstrate about the king’s attempt to avoid prophecy?','Disguising himself in battle could not prevent the LORD’s word from being fulfilled',['Ahab’s disguise caused Micaiah to withdraw his prophecy','The disguise allowed Ahab to defeat Syria without injury','Jehoshaphat died in Ahab’s place, canceling the warning'],'Although Ahab disguised himself, a seemingly random arrow struck him and the foretold judgment occurred.',[r('1 Kings',22,13,28),r('1 Kings',22,29,38)],'Micaiah and Ahab','Follow Ahab’s response to the warning and the details of his death in battle.'),
mc(2,'What similarity connects Elijah’s departure and the dead man revived in Elisha’s tomb?','Both accounts show that the LORD’s life-giving power was not limited by a prophet’s death or departure',['Both men were revived by touching Elijah’s mantle','Both events occurred during Solomon’s temple dedication','Both miracles persuaded Jehu to restore Baal worship'],'Elijah’s ministry continued through Elisha after he was taken up, and even contact with Elisha’s bones brought a dead man to life.',[r('2 Kings',2,9,15),r('2 Kings',13,20,21)],'Prophetic power beyond departure','Consider how each account shows that the power belongs to God rather than to a prophet’s physical presence.'),
mc(2,'How did Elisha respond differently to Naaman’s gifts than Gehazi did?','Elisha refused payment, but Gehazi secretly pursued Naaman and took gifts',['Elisha demanded silver, while Gehazi returned it','Both accepted equal payment and gave it to the poor','Both refused the gifts and never spoke to Naaman again'],'Elisha would not profit from the healing; Gehazi lied to obtain silver and garments and was judged with Naaman’s leprosy.',[r('2 Kings',5,14,19),r('2 Kings',5,20,27)],'Elisha and Gehazi','Compare their actions after Naaman was healed and the consequence for Gehazi.'),
mc(3,'How did Elisha’s treatment of the captured Syrian force differ from the king of Israel’s first impulse?','The king wanted to kill them, but Elisha had them fed and released',['The king wanted to release them, but Elisha executed them','The king offered them food, but Elisha sold them as slaves','The king ignored them, but Elisha made them priests'],'Elisha forbade killing the blinded soldiers, ordered a feast for them, and sent them home.',[r('2 Kings',6,8,23),r('2 Kings',7,3,9)],'Enemies and mercy','Review the capture, the king’s question, Elisha’s command, and the immediate result.'),
mc(2,'What did Hazael’s later attacks on Israel show about Elisha’s tears when he first met Hazael?','Elisha foresaw the suffering Hazael would inflict, and that suffering later began to occur',['Elisha mistakenly believed Hazael would protect Israel','Hazael became a peaceful prophet in Elisha’s school','Hazael attacked only Assyria and never Israel'],'Elisha wept because he knew the harm Hazael would do; Hazael later took Israelite territory and oppressed Israel.',[r('2 Kings',8,7,15),r('2 Kings',10,32,33),r('2 Kings',13,3,7)],'Hazael and Israel','Connect Elisha’s prediction with the later descriptions of Hazael’s campaigns.'),
mc(3,'How was the promise that Jehu’s descendants would rule through the fourth generation fulfilled?','Jehoahaz, Joash, Jeroboam II, and Zechariah followed Jehu before his dynasty ended',['Jehu’s four sons ruled Judah together for forty years','Four generations of Jehu’s family served as prophets under Elisha','The dynasty continued unbroken until Jerusalem fell'],'Zechariah was the fourth generation after Jehu to sit on Israel’s throne, exactly as promised.',[r('2 Kings',10,30),r('2 Kings',13,1,13),r('2 Kings',14,23,29),r('2 Kings',15,8,12)],'Jehu’s dynasty','Trace the rulers of Jehu’s house from Jehoahaz through Zechariah.'),
mc(2,'What similarity is emphasized in the reforms of Hezekiah and Josiah?','Both removed idolatrous objects and worship sites in an effort to restore loyalty to the LORD',['Both created golden calves to prevent worship in Jerusalem','Both closed the temple and copied an Assyrian altar','Both restored Baal worship after a long famine'],'Hezekiah removed high places, pillars, Asherah, and the bronze serpent; Josiah later carried out an even broader removal of idolatrous worship.',[r('2 Kings',18,1,6),r('2 Kings',23,4,20)],'Hezekiah and Josiah’s reforms','Compare the objects and worship sites removed during the two reforms.'),
mc(3,'Why did Josiah’s reform not cancel the announced destruction of Judah?','The accumulated guilt associated especially with Manasseh’s idolatry and bloodshed remained under judgment',['Josiah secretly returned to Baal worship after finding the law','Judah had already been exiled before Josiah became king','Josiah refused to read the book of the law to the people'],'Josiah turned to the LORD wholeheartedly, but the narrative says the LORD did not turn from the judgment provoked by Manasseh.',[r('2 Kings',21,10,16),r('2 Kings',23,24,27)],'Reform and judgment','Compare the praise of Josiah with the judgment that the narrator says remained.'),
mc(2,'How did the bronze temple furnishings illustrate the full arc of Solomon’s temple?','Hiram made them for the temple, and Babylon later broke them up and carried the bronze away',['Moses made them in Egypt, and Elijah hid them on Carmel','Jeroboam moved them to Bethel, and Josiah returned them','Hezekiah melted them to pay Egypt, and Manasseh replaced them'],'The carefully made bronze works of Solomon’s temple were dismantled when Jerusalem fell.',[r('1 Kings',7,13,47),r('2 Kings',25,13,17)],'Temple furnishings','Compare the construction inventory with the Babylonian removal inventory.'),
mc(3,'How did Solomon’s dedication prayer anticipate the exile described at the end of Kings?','He prayed that God would hear repentant captives who turned toward their land, city, and temple',['He promised that faithful kings would never face foreign enemies','He asked that the temple be moved with the people into Babylon','He predicted that Assyria—not Babylon—would release Jehoiachin'],'Solomon explicitly contemplated Israel being taken captive; Kings ends with Judah and its king in Babylon.',[r('1 Kings',8,46,53),r('2 Kings',25,8,21),r('2 Kings',25,27,30)],'Prayer and exile','Read Solomon’s prayer for future captives alongside the book’s closing events.'),
mc(2,'What parallel is seen in the ministries of Elijah and Elisha at the Jordan River?','Elijah divided the Jordan before his departure, and Elisha divided it when returning alone',['Both were baptized there by Naaman','Both built golden calves on its banks','Both crossed it while fleeing from Solomon'],'Elijah struck the water with his mantle and crossed with Elisha; Elisha later repeated the sign with Elijah’s mantle.',[r('2 Kings',2,6,8),r('2 Kings',2,13,15)],'The Jordan and succession','Compare the two crossings that frame Elijah’s departure.'),
mc(3,'How does Naaman’s response to healing contrast with the worship of the foreign settlers in Samaria?','Naaman confessed the LORD alone, while the settlers feared the LORD but continued serving their own gods',['Naaman worshiped Rimmon alone, while the settlers worshiped only in Jerusalem','Both immediately became priests in the Jerusalem temple','Both rejected the LORD after receiving prophetic instruction'],'Naaman declared there was no God except in Israel; the settlers practiced mixed worship.',[r('2 Kings',5,14,19),r('2 Kings',17,24,33)],'Foreigners and worship','Compare the confession following Naaman’s healing with the settlers’ divided allegiance.'),
mc(3,'What contrast does Kings make between the wisdom of Solomon’s early reign and his conduct later in life?','The king famed for God-given wisdom later acted foolishly by turning to other gods',['Solomon began as an idolater but ended by destroying every high place','His wisdom steadily increased until it prevented the kingdom’s division','Solomon rejected wisdom and asked God only for wealth'],'Solomon received extraordinary wisdom and discernment, yet his later loves drew his heart away from the LORD.',[r('1 Kings',3,5,14),r('1 Kings',10,23,25),r('1 Kings',11,1,11)],'Solomon’s rise and fall','Compare Solomon’s request and reputation with the narrator’s account of his later unfaithfulness.'),
mc(3,'What long-term contrast appears between the northern and southern royal lines after the kingdom divided?','Israel passed through repeated dynastic coups, while Judah retained David’s line despite serious threats',['Israel kept one dynasty while Judah changed families after every king','Both kingdoms were always ruled by descendants of David','Judah had no violent succession crises, while Israel had only one'],'Northern dynasties repeatedly replaced one another, whereas the rescue of Joash exemplifies preservation of David’s house in Judah.',[r('1 Kings',15,25,30),r('1 Kings',16,8,13),r('2 Kings',11,1,12),r('2 Kings',15,8,16)],'The two royal lines','Trace changes of dynasty in Israel and compare them with the preservation of David’s heir in Judah.'),
mc(2,'What did the deaths of Ahab and Jezebel have in common?','Both fulfilled judgments Elijah had spoken after Naboth’s murder',['Both died during the contest on Mount Carmel','Both were killed by Hazael in Damascus','Both repented and received honorable burial in Jerusalem'],'Ahab’s blood was licked by dogs and Jezebel was consumed by dogs at Jezreel, fulfilling Elijah’s judgment.',[r('1 Kings',21,17,24),r('1 Kings',22,34,38),r('2 Kings',9,30,37)],'Ahab and Jezebel judged','Connect each death with the specific words Elijah spoke in Naboth’s vineyard.'),
mc(2,'What connection joins Elisha’s final prophecy to Israel’s later victories over Syria?','Elisha promised Joash three victories, and Joash later defeated Syria three times',['Elisha promised seven victories, but Joash refused to fight','Elisha crowned Joash king of Syria before dying','Joash ignored Elisha and permanently lost every Israelite city'],'The number of victories matched the three times Joash struck the ground in Elisha’s presence.',[r('2 Kings',13,14,19),r('2 Kings',13,22,25)],'Elisha’s final prophecy','Follow the acted sign, its interpretation, and the reported victories.'),
mc(3,'How did Hezekiah’s display of wealth foreshadow a reversal of Solomon’s international glory?','Nations once brought treasures to Solomon, but Babylon later saw and carried Judah’s treasures away',['Hezekiah’s display caused Solomon to lose his wisdom','Babylon returned all the wealth Egypt had taken from Solomon','The envoys crowned Hezekiah king over every nation'],'Solomon’s wealth drew admiring visitors; Hezekiah displayed his wealth to Babylon, which later removed the treasures.',[r('1 Kings',10,23,25),r('2 Kings',20,12,19),r('2 Kings',24,10,13)],'Royal wealth and Babylon','Compare visitors bringing gifts to Solomon with Hezekiah showing treasure to Babylon’s envoys.'),
mc(2,'What common sign of covenant renewal appears in Solomon’s dedication and Josiah’s reform?','The king assembled the people around the temple and publicly centered them on the LORD’s covenant',['The king replaced the ark with a golden calf','The people abandoned Jerusalem for Bethel','The king invited Assyria to appoint the priests'],'Solomon gathered Israel for the ark and dedication; Josiah gathered Judah to hear the book and renew the covenant.',[r('1 Kings',8,1,21),r('2 Kings',23,1,3)],'Assembly and covenant','Compare why the people assembled and what covenant symbols or words stood at the center.'),
mc(3,'What progression links Jeroboam’s fear, Israel’s repeated royal sin, and the northern kingdom’s exile?','Political fear produced rival worship, later kings continued it, and persistent idolatry helped bring removal from the land',['Jeroboam’s fear led him to rebuild the temple, and Assyria rewarded Israel','Later kings rejected Jeroboam’s worship, but Judah forced Israel into exile','The calves protected Israel until Babylon destroyed Samaria'],'Kings traces Israel’s defining idolatry from Jeroboam’s decision through its repetition and finally into the explanation of exile.',[r('1 Kings',12,26,33),r('1 Kings',16,25,26),r('2 Kings',17,21,23)],'From false worship to exile','Trace the narrator’s repeated references to Jeroboam from the division to Israel’s fall.'),
]

export default {slug:'all-kings',tag:'all-kings-v2',status:'draft' as const,rows}
