import type { QuizDifficulty, QuizType, ScriptureBookSlug } from '../../lib/types'

export type CrossReference = { book:'1 Kings'|'2 Kings'; book_slug:ScriptureBookSlug; chapter:number; verse_start:number; verse_end?:number; label:string }
export type ComprehensiveRow = { type:QuizType; difficulty:QuizDifficulty; question:string; options?:string[]; answer?:string; accepted_answers?:string[]; explanation:string; supporting_refs:CrossReference[]; review_topic:string; review_guidance:string }
const r=(book:'1 Kings'|'2 Kings',chapter:number,verse_start:number,verse_end?:number):CrossReference=>({book,book_slug:book==='1 Kings'?'1-kings':'2-kings',chapter,verse_start,verse_end,label:`${book} ${chapter}:${verse_start}${verse_end&&verse_end!==verse_start?`–${verse_end}`:''}`})
const mc=(difficulty:QuizDifficulty,question:string,correct:string,distractors:[string,string,string],explanation:string,supporting_refs:CrossReference[],review_topic:string,review_guidance:string):ComprehensiveRow=>({type:'multiple_choice',difficulty,question,options:[correct,...distractors],explanation,supporting_refs,review_topic,review_guidance})

export const rows:ComprehensiveRow[]=[
mc(1,'Which two prophets in Kings restored a woman’s son to life?','Elijah and Elisha',['Nathan and Ahijah','Micaiah and Isaiah','Jehu and Huldah'],'Elijah restored the widow of Zarephath’s son, and Elisha restored the Shunammite woman’s son.',[r('1 Kings',17,17,24),r('2 Kings',4,32,37)],'Children restored to life','Compare how Elijah and Elisha responded when each mother’s son died.'),
mc(2,'What did Elijah’s and Elisha’s miracles for widows in financial danger have in common?','God multiplied a small household supply so it met an urgent need',['Each widow found treasure buried in her field','A king supported each widow permanently from his treasury','Each widow was told to sell her home and leave Israel'],'The widow at Zarephath’s meal and oil did not fail, while Elisha’s widow filled vessels from one jar of oil and sold it to pay her debt.',[r('1 Kings',17,8,16),r('2 Kings',4,1,7)],'Provision for widows','Review what each widow possessed initially and how God provided through it.'),
mc(2,'Which statement correctly compares Elijah’s drought with the famine Elisha announced to the Shunammite woman?','Elijah said rain would cease, while Elisha warned of a famine lasting seven years',['Both were seven-year famines caused by a siege','Elisha announced the drought first and Elijah later ended it','Both warnings were given directly to Ahab in Samaria'],'Elijah announced that dew and rain would cease; Elisha later warned that the LORD had called for a seven-year famine.',[r('1 Kings',17,1),r('2 Kings',8,1,2)],'Prophetic warnings of famine','Study what each prophet announced, how the crisis was described, and who received the warning.'),
mc(2,'Which two capital cities suffered severe famine while surrounded by enemy armies?','Samaria and Jerusalem',['Bethel and Dan','Jericho and Gilgal','Jezreel and Gibeon'],'Samaria suffered famine during the Syrian siege, and Jerusalem during the Babylonian siege.',[r('2 Kings',6,24,30),r('2 Kings',25,1,4)],'Siege famines','Compare the siege of Samaria with Babylon’s final siege of Jerusalem.'),
mc(3,'How did the outcomes of the siege famines in Samaria and Jerusalem differ?','Samaria was unexpectedly delivered, but Jerusalem was breached and its people exiled',['Both cities were destroyed and their populations exiled','Jerusalem was delivered overnight, but Samaria was burned','Both sieges ended when the defending king defeated the enemy'],'The Syrians abandoned their camp outside Samaria; Babylon breached Jerusalem, destroyed it, and carried Judah away.',[r('2 Kings',7,3,16),r('2 Kings',25,1,12)],'Deliverance and exile','Trace how each siege ended and what happened to the residents afterward.'),
mc(2,'What marked the beginning and public confirmation of Elisha’s call to succeed Elijah?','Elijah placed his mantle on Elisha, and later Elisha divided the Jordan with it',['Elijah crowned Elisha at Gihon, and Elisha built an altar at Bethel','Elisha defeated the prophets of Baal, and Elijah made him king','Elisha interpreted a dream, and later received the temple scroll'],'Elijah first cast his mantle on Elisha. After Elijah was taken up, Elisha used it to divide the Jordan.',[r('1 Kings',19,19,21),r('2 Kings',2,13,15)],'Elisha succeeds Elijah','Follow the mantle from Elisha’s call through his return across the Jordan.'),
mc(2,'How did Jehu’s reform remain incomplete after he destroyed Baal worship in Israel?','He continued the worship of Jeroboam’s golden calves at Bethel and Dan',['He restored Jezebel as queen in Samaria','He immediately rebuilt Baal’s temple','He required Judah to worship Baal'],'Jehu eliminated Baal worship but did not turn from Jeroboam’s golden calves.',[r('1 Kings',12,26,33),r('2 Kings',10,18,31)],'Jehu’s incomplete reform','Review the worship system Jeroboam established and what Jehu allowed to remain.'),
mc(2,'Which later king of Judah fulfilled the prophecy against Jeroboam’s altar at Bethel?','Josiah',['Hezekiah','Jehoshaphat','Joash'],'A man of God named Josiah long before his birth; Josiah later demolished and defiled the altar.',[r('1 Kings',13,1,3),r('2 Kings',23,15,20)],'Josiah and Bethel','Compare the prediction during Jeroboam’s reign with Josiah’s actions at Bethel.'),
mc(2,'How was Elijah’s judgment against Jezebel eventually fulfilled?','She was thrown from a window at Jezreel, and dogs consumed her body',['She died in exile in Babylon and received a royal burial','She was killed on Mount Carmel with the prophets of Baal','She fled to Sidon and died during the drought'],'Elijah foretold that dogs would eat Jezebel by the wall of Jezreel; her death under Jehu fulfilled it.',[r('1 Kings',21,23),r('2 Kings',9,30,37)],'Judgment on Jezebel','Review Elijah’s sentence after Naboth’s murder and the account of Jezebel’s death.'),
mc(2,'What earlier sin explains why dogs licking Ahab’s blood was presented as divine judgment?','Ahab and Jezebel arranged Naboth’s death and seized his vineyard',['Ahab refused to build the temple in Jerusalem','Ahab stole Naaman’s gifts from Elisha','Ahab destroyed the book of the law'],'After Naboth was falsely accused and killed, Elijah pronounced judgment on Ahab’s house.',[r('1 Kings',21,7,24),r('1 Kings',22,34,38)],'Naboth and Ahab','Connect the seizure of Naboth’s vineyard with Elijah’s sentence and Ahab’s death.'),
mc(2,'What did Baasha and Zimri have in common in the way they gained power and were judged?','Each seized Israel’s throne violently, destroyed the previous royal house, and faced judgment on his own house',['Each inherited Judah’s throne peacefully','Each removed the golden calves and restored Jerusalem worship','Each was appointed king by Jezebel'],'Baasha destroyed Jeroboam’s house, and Zimri later destroyed Baasha’s house.',[r('1 Kings',15,27,30),r('1 Kings',16,9,13)],'Violent dynastic cycles','Trace how Jeroboam’s house ended and how the same pattern overtook Baasha’s house.'),
mc(1,'Which two kings of Judah were commended for doing right, yet failed to remove the high places?','Asa and Jehoshaphat',['Ahaz and Manasseh','Ahab and Jehu','Zedekiah and Jehoahaz'],'Asa and Jehoshaphat were evaluated positively, but the high places remained.',[r('1 Kings',15,9,15),r('1 Kings',22,41,44)],'Qualified reform','Compare the narrator’s evaluation of Asa and Jehoshaphat.'),
mc(2,'How did Manasseh treat the religious reforms made by his father Hezekiah?','He reversed them by rebuilding high places and restoring idolatrous worship',['He completed them by destroying the temple','He extended them into Israel after defeating Assyria','He preserved them unchanged'],'Hezekiah removed high places and idols, but Manasseh rebuilt high places and erected altars to other gods.',[r('2 Kings',18,1,6),r('2 Kings',21,1,9)],'Hezekiah and Manasseh','List what Hezekiah removed and which practices Manasseh restored.'),
mc(3,'What contrast does Kings draw between Ahaz and his son Hezekiah in responding to Assyria?','Ahaz sought Assyria’s help and gave it treasure, while Hezekiah trusted the LORD and rebelled',['Ahaz defeated Assyria, while Hezekiah became its servant','Both trusted Assyria and emptied the temple treasury','Both refused either political action or prayer'],'Ahaz appealed to Tiglath-pileser and sent treasure; Hezekiah trusted the LORD and refused submission.',[r('2 Kings',16,5,9),r('2 Kings',18,1,8)],'Ahaz and Hezekiah','Compare each king’s source of security when facing stronger nations.'),
mc(2,'What discovery led Josiah to renew the covenant and carry out a sweeping reform?','The book of the law was found in the temple',['Elijah’s mantle was found beside the Jordan','Solomon’s treasury was uncovered under the altar','The bronze serpent began speaking'],'After Hilkiah found the book of the law, Josiah humbled himself, renewed the covenant, and removed idolatry.',[r('2 Kings',22,8,20),r('2 Kings',23,1,25)],'Josiah’s reform','Follow the sequence from finding the book to renewing the covenant and reforming worship.'),
mc(2,'How did Joash’s survival as a child protect the promise connected with David’s royal line?','His rescue from Athaliah preserved a living heir from David’s family',['His rescue permanently united Israel and Judah under Jehu','He became a prophet and replaced Elisha','He returned the northern tribes from exile'],'Athaliah tried to destroy the royal family, but Joash was hidden and later crowned.',[r('1 Kings',11,32,36),r('2 Kings',11,1,12)],'David’s line','Connect God’s promise of a lamp for David with the hiding and coronation of Joash.'),
mc(3,'What warning given after Solomon built the temple explains the later exile of Israel?','Persistent rejection of the LORD and service to other gods would lead to removal from the land',['Failure to enlarge the temple would cause Egypt to conquer Israel','Refusal to appoint a second high priest would divide the kingdom','Trade with Tyre would automatically end David’s dynasty'],'God warned Solomon that idolatry would bring removal; 2 Kings explains Israel’s exile in those terms.',[r('1 Kings',9,6,9),r('2 Kings',17,7,23)],'Covenant warning and exile','Compare the temple warning with the explanation for Israel’s fall.'),
mc(3,'How did Solomon’s temple change from its dedication to the fall of Jerusalem?','It went from housing the ark to being burned and stripped by Babylon',['It was moved intact from Jerusalem to Samaria','It became Ahab’s temple of Baal and was destroyed by Jehu','It remained untouched while only the palace was destroyed'],'Solomon brought the ark into the completed temple; Babylon later burned it and removed its furnishings.',[r('1 Kings',8,1,21),r('2 Kings',25,8,17)],'The temple’s story','Compare what entered the temple at dedication with what was removed at Jerusalem’s fall.'),
mc(3,'Which event fulfilled Isaiah’s warning after Hezekiah displayed his treasures to Babylonian envoys?','Babylon carried away Jerusalem’s treasures and leading people',['Assyria returned the northern tribes to Samaria','Egypt restored Solomon’s son to the throne','Tyre rebuilt the temple with cedar and gold'],'Isaiah warned that the treasures and descendants would go to Babylon; the deportations later fulfilled it.',[r('2 Kings',20,12,19),r('2 Kings',24,10,16)],'Babylon foretold','Connect what Hezekiah showed the envoys with what Babylon later removed.'),
mc(3,'How does the ending of Kings leave a small sign of hope for David’s line after Jerusalem’s destruction?','The exiled king Jehoiachin was released and given an honored place in Babylon',['Solomon returned to rebuild the temple','Zedekiah escaped and restored Judah immediately','The northern tribes crowned Josiah’s grandson in Samaria'],'The final scene preserves and honors a descendant of David rather than ending with his death in prison.',[r('2 Kings',24,8,16),r('2 Kings',25,27,30)],'Hope after exile','Follow Jehoiachin from deportation to release and honored treatment.'),
]

export default {slug:'all-kings',tag:'all-kings-v2',status:'draft' as const,rows}
