import type { QuizDifficulty, QuizType, ScriptureBookSlug } from '../../lib/types'

export type CrossReference = {
  book: '1 Kings' | '2 Kings'; book_slug: ScriptureBookSlug; chapter: number;
  verse_start: number; verse_end?: number; label: string;
}
export type ComprehensiveRow = {
  type: QuizType; difficulty: QuizDifficulty; question: string; options?: string[];
  answer?: string; accepted_answers?: string[]; explanation: string;
  supporting_refs: CrossReference[]; review_topic: string; review_guidance: string;
}
type Link = { topic: string; a: CrossReference; aEvent: string; b: CrossReference; bEvent: string; connection: string }

const r = (book: '1 Kings' | '2 Kings', chapter: number, verse_start: number, verse_end?: number): CrossReference => ({
  book, book_slug: book === '1 Kings' ? '1-kings' : '2-kings', chapter, verse_start, verse_end,
  label: `${book} ${chapter}:${verse_start}${verse_end && verse_end !== verse_start ? `–${verse_end}` : ''}`,
})
const links: Link[] = [
  {topic:'Solomon’s succession',a:r('1 Kings',1,38,40),aEvent:'Solomon was anointed at Gihon',b:r('1 Kings',2,12),bEvent:'Solomon sat on David’s throne and his kingdom was firmly established',connection:'Solomon’s public anointing was followed by his established reign after David’s death'},
  {topic:'Building the temple',a:r('1 Kings',5,8,18),aEvent:'Hiram supplied timber and Solomon organized the labor',b:r('1 Kings',6,1,14),bEvent:'Solomon built the house of the LORD',connection:'The preparations and materials in chapter 5 enabled the temple construction in chapter 6'},
  {topic:'The temple’s story',a:r('1 Kings',8,1,21),aEvent:'Solomon brought the ark into the completed temple',b:r('2 Kings',25,8,17),bEvent:'The Babylonians burned and dismantled the temple',connection:'The temple dedicated under Solomon was destroyed when Jerusalem fell to Babylon'},
  {topic:'Covenant warning and exile',a:r('1 Kings',9,6,9),aEvent:'God warned that persistent idolatry would bring removal from the land',b:r('2 Kings',17,18,23),bEvent:'Israel was removed from the land and carried into exile',connection:'The northern kingdom’s exile fulfilled the covenant warning given to Solomon'},
  {topic:'Solomon’s rise and fall',a:r('1 Kings',10,23,25),aEvent:'Solomon surpassed other kings in riches and wisdom',b:r('1 Kings',11,1,11),bEvent:'Solomon’s foreign wives turned his heart toward other gods',connection:'Solomon’s extraordinary glory was followed by covenant unfaithfulness and judgment'},
  {topic:'The divided kingdom',a:r('1 Kings',11,29,39),aEvent:'Ahijah announced that ten tribes would be torn from Solomon’s house',b:r('1 Kings',12,16,20),bEvent:'The northern tribes rejected Rehoboam and made Jeroboam king',connection:'Ahijah’s symbolic prophecy was fulfilled when the kingdom divided'},
  {topic:'Jeroboam’s altar and Josiah',a:r('1 Kings',13,1,3),aEvent:'A man of God named Josiah as the future destroyer of Bethel’s altar',b:r('2 Kings',23,15,18),bEvent:'Josiah defiled and demolished the altar at Bethel',connection:'Josiah fulfilled the long-range prophecy spoken against Jeroboam’s altar'},
  {topic:'Jeroboam’s dynasty',a:r('1 Kings',14,10,14),aEvent:'Ahijah foretold the cutting off of Jeroboam’s house',b:r('1 Kings',15,27,30),bEvent:'Baasha killed Nadab and all the house of Jeroboam',connection:'Baasha’s purge fulfilled the judgment pronounced by Ahijah'},
  {topic:'Cycles of northern dynasties',a:r('1 Kings',15,27,30),aEvent:'Baasha destroyed Jeroboam’s house after a prophetic judgment',b:r('1 Kings',16,9,13),bEvent:'Zimri destroyed Baasha’s house after a prophetic judgment',connection:'Baasha suffered the same kind of dynastic destruction he had inflicted on Jeroboam’s house'},
  {topic:'Ahab and Baal worship',a:r('1 Kings',16,29,33),aEvent:'Ahab married Jezebel and established Baal worship in Samaria',b:r('1 Kings',18,20,40),bEvent:'Elijah confronted Baal’s prophets on Mount Carmel',connection:'Ahab’s institutional Baal worship led to Elijah’s covenant confrontation at Carmel'},
  {topic:'Drought and restored rain',a:r('1 Kings',17,1),aEvent:'Elijah declared that no dew or rain would fall except by his word',b:r('1 Kings',18,41,45),bEvent:'After Carmel, Elijah prayed and heavy rain returned',connection:'The drought announced by Elijah ended after the LORD was vindicated at Carmel'},
  {topic:'Raising children from death',a:r('1 Kings',17,17,24),aEvent:'Elijah restored the widow of Zarephath’s son',b:r('2 Kings',4,32,37),bEvent:'Elisha restored the Shunammite woman’s son',connection:'Both Elijah and Elisha prayed over and restored a faithful woman’s dead son'},
  {topic:'Prophetic succession',a:r('1 Kings',19,19,21),aEvent:'Elijah cast his mantle upon Elisha and Elisha followed him',b:r('2 Kings',2,9,15),bEvent:'Elisha received Elijah’s mantle and was recognized as his successor',connection:'Elisha’s call under Elijah culminated in his receiving the prophetic mantle'},
  {topic:'Hazael’s commission',a:r('1 Kings',19,15,17),aEvent:'The LORD told Elijah that Hazael would become king of Syria',b:r('2 Kings',8,7,15),bEvent:'Elisha foretold Hazael’s kingship and Hazael seized the throne',connection:'Hazael’s rise carried out the commission first given to Elijah at Horeb'},
  {topic:'Jehu’s commission',a:r('1 Kings',19,16,17),aEvent:'The LORD named Jehu as a future king and instrument of judgment',b:r('2 Kings',9,1,10),bEvent:'A prophetic messenger anointed Jehu to strike Ahab’s house',connection:'Jehu’s anointing activated the judgment announced years earlier to Elijah'},
  {topic:'Ahab’s disobedience and death',a:r('1 Kings',20,34,43),aEvent:'Ahab released Ben-hadad and received a sentence of life for life',b:r('1 Kings',22,29,38),bEvent:'Ahab was killed in battle at Ramoth-gilead',connection:'Ahab’s condemned mercy toward Ben-hadad preceded his own foretold death'},
  {topic:'Naboth and Ahab’s judgment',a:r('1 Kings',21,17,24),aEvent:'Elijah pronounced judgment after Naboth was murdered',b:r('1 Kings',22,34,38),bEvent:'Dogs licked Ahab’s blood after he died',connection:'Ahab’s death fulfilled the judgment connected with Naboth’s blood'},
  {topic:'Jezebel’s judgment',a:r('1 Kings',21,23),aEvent:'Elijah said dogs would eat Jezebel by the wall of Jezreel',b:r('2 Kings',9,30,37),bEvent:'Jezebel was thrown down and dogs consumed her body',connection:'Jezebel’s death at Jezreel fulfilled Elijah’s prophecy'},
  {topic:'Elijah’s final ministry',a:r('2 Kings',1,15,17),aEvent:'Elijah delivered the LORD’s final word to Ahaziah',b:r('2 Kings',2,1,12),bEvent:'Elijah was taken up and Elisha witnessed his departure',connection:'Elijah’s judgment oracle to Ahaziah was followed by his departure and Elisha’s succession'},
  {topic:'Elijah’s mantle',a:r('1 Kings',19,19,21),aEvent:'Elijah cast his mantle upon Elisha when calling him',b:r('2 Kings',2,13,15),bEvent:'Elisha used Elijah’s mantle to divide the Jordan',connection:'The mantle used at Elisha’s call later publicly confirmed his prophetic succession'},
  {topic:'Provision through the prophets',a:r('1 Kings',17,8,16),aEvent:'The widow’s meal and oil sustained her household and Elijah',b:r('2 Kings',4,1,7),bEvent:'A widow’s small supply of oil filled many vessels',connection:'Both Elijah and Elisha brought multiplied provision to a widow in crisis'},
  {topic:'The Shunammite woman',a:r('2 Kings',4,8,37),aEvent:'The Shunammite received a son and later saw him restored to life',b:r('2 Kings',8,1,6),bEvent:'After seven years away, her house and land were restored',connection:'The woman helped by Elisha in chapter 4 received providential restoration in chapter 8'},
  {topic:'Foreigners and the God of Israel',a:r('2 Kings',5,9,19),aEvent:'Naaman was healed and confessed the God of Israel',b:r('2 Kings',17,24,29),bEvent:'Foreign settlers learned to fear the LORD while continuing other worship',connection:'Kings contrasts a foreigner’s confession after healing with the settlers’ divided worship'},
  {topic:'Aram and prophetic mercy',a:r('2 Kings',5,9,19),aEvent:'Elisha healed Naaman, commander of Syria’s army',b:r('2 Kings',6,18,23),bEvent:'Elisha spared and fed a captured Syrian force',connection:'Elisha twice answered Syrian hostility with acts that preserved life'},
  {topic:'Samaria’s famine and deliverance',a:r('2 Kings',6,24,33),aEvent:'The Syrian siege produced catastrophic famine in Samaria',b:r('2 Kings',7,3,16),bEvent:'The Syrians fled and the people plundered their camp for food',connection:'The abandoned Syrian camp supplied the deliverance from Samaria’s siege famine'},
  {topic:'The scoffing officer',a:r('2 Kings',6,24,33),aEvent:'Samaria’s siege famine reached its crisis',b:r('2 Kings',7,1,20),bEvent:'Elisha’s promise of abundance came true while the scoffing officer died',connection:'The crisis at the end of chapter 6 was reversed exactly as Elisha foretold in chapter 7'},
  {topic:'Famines announced by prophets',a:r('1 Kings',17,1),aEvent:'Elijah announced an indefinite drought governed by the LORD’s word',b:r('2 Kings',8,1,2),bEvent:'Elisha warned that the LORD had called for a seven-year famine',connection:'Both Elijah and Elisha announced prolonged food crises before their effects unfolded'},
  {topic:'Hazael and Israel',a:r('2 Kings',8,11,15),aEvent:'Elisha wept over the harm Hazael would do to Israel',b:r('2 Kings',10,32,33),bEvent:'Hazael defeated Israel and took territory east of the Jordan',connection:'Hazael’s attacks began to realize the suffering foreseen by Elisha'},
  {topic:'Jehu’s purge',a:r('2 Kings',9,6,10),aEvent:'Jehu was anointed to avenge the blood shed by Jezebel',b:r('2 Kings',10,1,17),bEvent:'Jehu destroyed Ahab’s remaining house in Samaria',connection:'Jehu’s anointing was followed by the commanded destruction of Ahab’s dynasty'},
  {topic:'Jehu’s incomplete reform',a:r('1 Kings',12,26,33),aEvent:'Jeroboam established the golden calves at Bethel and Dan',b:r('2 Kings',10,18,31),bEvent:'Jehu destroyed Baal but retained Jeroboam’s calves',connection:'Jehu’s reform stopped short of removing the northern kingdom’s founding idolatry'},
  {topic:'Preserving David’s line',a:r('1 Kings',11,32,36),aEvent:'The LORD preserved a tribe and a lamp for David in Jerusalem',b:r('2 Kings',11,1,12),bEvent:'Joash was hidden from Athaliah and crowned in the temple',connection:'The rescue of Joash preserved the Davidic line promised a continuing lamp'},
  {topic:'Repairing Solomon’s temple',a:r('1 Kings',8,1,21),aEvent:'Solomon dedicated the completed temple',b:r('2 Kings',12,4,16),bEvent:'Joash organized funds to repair that temple',connection:'The sanctuary dedicated by Solomon later required organized restoration under Joash'},
  {topic:'Elisha’s ministry from beginning to end',a:r('2 Kings',2,9,15),aEvent:'Elisha received Elijah’s mantle and began his ministry',b:r('2 Kings',13,14,25),bEvent:'Elisha’s final oracle foretold three victories that later occurred',connection:'The prophetic authority recognized at Elisha’s succession remained effective through his final oracle'},
  {topic:'Jehu’s four generations',a:r('2 Kings',10,30),aEvent:'The LORD promised Jehu’s sons the throne through the fourth generation',b:r('2 Kings',15,8,12),bEvent:'Zechariah’s death ended Jehu’s dynasty in its fourth generation',connection:'Zechariah’s reign completed the precise dynastic promise made to Jehu'},
  {topic:'The northern kingdom’s collapse',a:r('2 Kings',15,8,31),aEvent:'Repeated coups destabilized Israel’s throne',b:r('2 Kings',17,1,6),bEvent:'Assyria captured Samaria and exiled Israel',connection:'The rapid dynastic violence of chapter 15 preceded the northern kingdom’s final fall'},
  {topic:'Trusting Assyria or the LORD',a:r('2 Kings',16,5,9),aEvent:'Ahaz appealed to Assyria and surrendered temple treasure',b:r('2 Kings',18,1,8),bEvent:'Hezekiah trusted the LORD and rebelled against Assyria',connection:'Hezekiah’s trust sharply contrasts with his father Ahaz’s dependence on Assyria'},
  {topic:'Covenant warning and Israel’s exile',a:r('1 Kings',9,6,9),aEvent:'The LORD warned that idolatry would remove Israel from the land',b:r('2 Kings',17,7,23),bEvent:'Israel was exiled for covenant rebellion and persistent idolatry',connection:'The explanation of Israel’s exile matches the warning given at the beginning of the kingdom'},
  {topic:'Reform reversed',a:r('2 Kings',18,1,6),aEvent:'Hezekiah removed high places and trusted the LORD',b:r('2 Kings',21,1,9),bEvent:'Manasseh rebuilt high places and restored idolatry',connection:'Manasseh deliberately reversed the central reforms of his father Hezekiah'},
  {topic:'Assyria and Jerusalem',a:r('2 Kings',18,28,37),aEvent:'The Rabshakeh publicly mocked trust in the LORD',b:r('2 Kings',19,32,37),bEvent:'The LORD defended Jerusalem and Sennacherib returned home',connection:'Jerusalem’s deliverance overturned Assyria’s boast against the LORD'},
  {topic:'Babylon foretold',a:r('2 Kings',20,12,19),aEvent:'Hezekiah showed Babylon’s envoys all his treasures and Isaiah foretold their removal',b:r('2 Kings',24,10,16),bEvent:'Babylon carried away Jerusalem’s treasures and leading people',connection:'The Babylonian deportation fulfilled Isaiah’s warning to Hezekiah'},
  {topic:'Manasseh and Jerusalem’s fall',a:r('2 Kings',21,10,15),aEvent:'The LORD announced irreversible disaster because of Manasseh’s sins',b:r('2 Kings',24,2,4),bEvent:'Judah’s destruction was tied explicitly to Manasseh’s sins and bloodshed',connection:'The narrator connects Babylonian judgment directly to Manasseh’s covenant rebellion'},
  {topic:'The book and the reform',a:r('2 Kings',22,8,20),aEvent:'The book of the law was found and Josiah humbled himself',b:r('2 Kings',23,1,25),bEvent:'Josiah renewed the covenant and removed idolatrous worship',connection:'Discovery of the law produced Josiah’s covenant renewal and comprehensive reform'},
  {topic:'Josiah named in advance',a:r('1 Kings',13,1,3),aEvent:'Josiah was named in a prophecy against Bethel’s altar',b:r('2 Kings',23,15,20),bEvent:'Josiah destroyed that altar and burned bones upon it',connection:'The reform at Bethel fulfilled a prophecy spoken centuries earlier'},
  {topic:'Temple furnishings',a:r('1 Kings',7,13,47),aEvent:'Hiram fashioned the temple’s great bronze furnishings',b:r('2 Kings',25,13,17),bEvent:'Babylon broke up and carried away those bronze furnishings',connection:'Objects created for Solomon’s temple were dismantled when the temple fell'},
  {topic:'Prayer before exile',a:r('1 Kings',8,46,53),aEvent:'Solomon prayed for exiles who would repent toward the land and temple',b:r('2 Kings',25,8,21),bEvent:'Judah was carried away after Jerusalem and the temple were destroyed',connection:'Solomon’s dedication prayer anticipated the exile that concludes Kings'},
  {topic:'Famines in prophetic ministry',a:r('1 Kings',17,8,16),aEvent:'During Elijah’s drought, the widow’s meal and oil did not fail',b:r('2 Kings',4,38,44),bEvent:'During famine, Elisha purified food and multiplied bread',connection:'Both prophetic ministries displayed God’s provision during famine'},
  {topic:'Famines and siege',a:r('2 Kings',6,24,30),aEvent:'The Syrian siege caused horrific famine in Samaria',b:r('2 Kings',25,1,4),bEvent:'The Babylonian siege caused severe famine in Jerusalem',connection:'Both capital cities experienced devastating famine under enemy siege'},
  {topic:'Faithful kings of Judah',a:r('1 Kings',15,9,15),aEvent:'Asa removed idols but left the high places',b:r('1 Kings',22,41,46),bEvent:'Jehoshaphat did right but also left the high places',connection:'Asa and Jehoshaphat were commended while their reforms remained incomplete'},
  {topic:'Patterns of partial reform',a:r('2 Kings',12,1,3),aEvent:'Joash did right while Jehoiada taught him, but high places remained',b:r('2 Kings',14,1,4),bEvent:'Amaziah did right, though not like David, and high places remained',connection:'Joash and Amaziah received qualified approval because unauthorized worship continued'},
  {topic:'Hope after exile',a:r('2 Kings',24,8,16),aEvent:'Jehoiachin was taken captive to Babylon',b:r('2 Kings',25,27,30),bEvent:'Decades later Jehoiachin was released and given an honored place',connection:'Kings ends by moving the exiled Davidic king from prison to a place of favor'},
]

const refsText = (link: Link) => `${link.a.label} and ${link.b.label}`
const connectedRows: ComprehensiveRow[] = links.flatMap(link => {
  const refs = [link.a, link.b]
  const guidance = `Study ${refsText(link)} and trace how the earlier event leads to, parallels, or is fulfilled by the later event.`
  return [
    {type:'multiple_choice',difficulty:2,question:`How do ${link.a.label} and ${link.b.label} connect?`,options:[link.connection,'They describe one identical event from two viewpoints','The later passage cancels the earlier passage without fulfilling it','They share no narrative or theological connection'],explanation:link.connection,supporting_refs:refs,review_topic:link.topic,review_guidance:guidance},
    {type:'multiple_choice',difficulty:1,question:`In the sequence traced by ${refsText(link)}, what happened first?`,options:[link.aEvent,link.bEvent,'Both events happened simultaneously','Neither event appears in Kings'],explanation:`First, ${link.aEvent.toLowerCase()}. Later, ${link.bEvent.toLowerCase()}.`,supporting_refs:refs,review_topic:link.topic,review_guidance:guidance},
  ] as ComprehensiveRow[]
})

const famineRefs = [r('1 Kings',17,1,16),r('1 Kings',18,1,5),r('2 Kings',4,38,44),r('2 Kings',6,24,33),r('2 Kings',7,1,20),r('2 Kings',8,1,6),r('2 Kings',25,1,4)]
const famineGuidance = 'Review the drought in 1 Kings 17–18; Elisha’s famine ministry in 2 Kings 4 and 8; and the siege famines in 2 Kings 6–7 and 25.'
const synthesisRows: ComprehensiveRow[] = [
  {type:'multiple_choice',difficulty:3,question:'Which answer identifies the major famines or food crises narrated across Kings?',options:['Elijah’s drought; famine at Gilgal; Samaria’s Syrian siege; the seven-year famine; Jerusalem’s Babylonian siege','Only Elijah’s drought and Jerusalem’s siege','Solomon’s reign, Naaman’s healing, and Josiah’s reform','The building of the temple and the division of the kingdom'],explanation:'Kings narrates several distinct crises: Elijah’s drought, famine during Elisha’s ministry, siege famine in Samaria, a seven-year famine, and Jerusalem’s final siege famine.',supporting_refs:famineRefs,review_topic:'Famines across Kings',review_guidance:famineGuidance},
  {type:'multiple_choice',difficulty:2,question:'Which two famines in Kings were caused directly by enemy armies besieging capital cities?',options:['Samaria under the Syrians and Jerusalem under the Babylonians','Zarephath and Gilgal','Bethel and Dan','Jezreel and Ramoth-gilead'],explanation:'The Syrian siege produced famine in Samaria, while Babylon’s siege produced famine in Jerusalem.',supporting_refs:[r('2 Kings',6,24,33),r('2 Kings',25,1,4)],review_topic:'Siege famines',review_guidance:'Compare the siege of Samaria in 2 Kings 6–7 with the siege of Jerusalem in 2 Kings 25.'},
  {type:'multiple_choice',difficulty:2,question:'How did prophetic ministry bring provision during two different famines?',options:['Elijah’s widow received unfailing meal and oil, and Elisha’s community received safe stew and multiplied bread','Both prophets ended every famine immediately','Elijah imported Egyptian grain and Elisha opened royal storehouses','Both prophets instructed the people to surrender to Syria'],explanation:'At Zarephath the meal and oil did not fail; at Gilgal Elisha purified the stew and fed one hundred men from twenty loaves.',supporting_refs:[r('1 Kings',17,8,16),r('2 Kings',4,38,44)],review_topic:'God’s provision during famine',review_guidance:'Study the widow of Zarephath in 1 Kings 17 and Elisha’s food miracles in 2 Kings 4.'},
  {type:'multiple_choice',difficulty:3,question:'What contrast does Kings draw between the outcomes of Samaria’s and Jerusalem’s siege famines?',options:['Samaria received sudden deliverance, but Jerusalem was breached and carried into exile','Both cities were delivered overnight','Both cities were destroyed immediately','Jerusalem was delivered while Samaria was burned'],explanation:'The LORD caused the Syrians to abandon their camp outside Samaria, but Jerusalem’s Babylonian siege ended in breach, destruction, and exile.',supporting_refs:[r('2 Kings',7,3,20),r('2 Kings',25,1,12)],review_topic:'Deliverance and judgment',review_guidance:'Compare Samaria’s unexpected deliverance in 2 Kings 7 with Jerusalem’s fall in 2 Kings 25.'},
  {type:'multiple_choice',difficulty:3,question:'Which famine was explicitly announced as lasting seven years, and who was warned to leave?',options:['The famine in Elisha’s time; the Shunammite woman and her household','Elijah’s drought; Obadiah and Ahab','Samaria’s siege; Gehazi and Naaman','Jerusalem’s siege; Zedekiah and his sons'],explanation:'Elisha told the woman whose son he had restored that the LORD had called for a seven-year famine and instructed her household to sojourn elsewhere.',supporting_refs:[r('2 Kings',4,8,37),r('2 Kings',8,1,6)],review_topic:'The Shunammite and the seven-year famine',review_guidance:'Review the woman’s first story in 2 Kings 4 and its continuation in 2 Kings 8.'},
  {type:'true_false',difficulty:3,question:'Every famine mentioned in Kings ended with miraculous deliverance before a city fell.',answer:'false',explanation:'False. Samaria was delivered in 2 Kings 7, but Jerusalem’s famine ended with the city breached, destroyed, and its people exiled in 2 Kings 25.',supporting_refs:[r('2 Kings',7,3,20),r('2 Kings',25,1,12)],review_topic:'Famines: deliverance versus exile',review_guidance:'Study why the similar siege conditions in 2 Kings 7 and 25 have very different outcomes.'},
]

export const rows: ComprehensiveRow[] = [...connectedRows, ...synthesisRows]

const bank = { slug: 'all-kings', tag: 'all-kings-v1', rows }
export default bank
