import type { QuizDifficulty, ScriptureBookSlug } from '../../lib/types'
import type { ComprehensiveRow, CrossReference } from './all-kings'

const r=(chapter:number,verse_start:number,verse_end?:number):CrossReference=>({book:'Mark',book_slug:'mark' as ScriptureBookSlug,chapter,verse_start,verse_end,label:`Mark ${chapter}:${verse_start}${verse_end&&verse_end!==verse_start?`–${verse_end}`:''}`})
const mc=(difficulty:QuizDifficulty,question:string,correct:string,distractors:[string,string,string],explanation:string,refs:CrossReference[],topic:string):ComprehensiveRow=>({type:'multiple_choice',difficulty,question,options:[correct,...distractors],explanation,supporting_refs:refs,review_topic:topic,review_guidance:`Compare ${refs.map(ref=>ref.label).join(' and ')}.`})
const tf=(difficulty:QuizDifficulty,question:string,answer:boolean,refs:CrossReference[],topic:string,explanation:string):ComprehensiveRow=>({type:'true_false',difficulty,question,answer:answer?'true':'false',explanation,supporting_refs:refs,review_topic:topic,review_guidance:`Compare ${refs.map(ref=>ref.label).join(' and ')}.`})
const sa=(difficulty:QuizDifficulty,question:string,answer:string,refs:CrossReference[],topic:string,explanation:string):ComprehensiveRow=>({type:'short_answer',difficulty,question,answer,accepted_answers:[],explanation,supporting_refs:refs,review_topic:topic,review_guidance:`Review ${refs.map(ref=>ref.label).join(' and ')}.`})

export const rows:ComprehensiveRow[]=[
mc(1,'Which title for Jesus is declared at the beginning of Mark, by the heavenly voice at His baptism, and by the centurion at the cross?','Son of God',['Son of David','King of Israel','Holy One of God'],'Mark opens by naming Jesus the Son of God; the Father calls Him His beloved Son, and the centurion confesses Him at the cross.',[r(1,1,11),r(15,37,39)],'Jesus the Son of God'),
mc(2,'Who correctly identify Jesus as the Son of God before most human characters understand who He is?','Unclean spirits',['The scribes','The Pharisees','The Herodians'],'Unclean spirits call Jesus the Holy One of God and the Son of God, while Jesus restrains their speech.',[r(1,23,27),r(3,11,12),r(5,6,9)],'Recognition by unclean spirits'),
mc(2,'How does Peter’s confession at Caesarea Philippi differ from his response during Jesus’ trial?','He confesses Jesus as the Christ, but later denies knowing Him',['He first denies Jesus, but later identifies Him as Elijah','He calls Jesus the Son of David both times','He remains silent on both occasions'],'Peter names Jesus as the Christ, then later denies three times that he knows Him.',[r(8,27,30),r(14,66,72)],'Peter’s confession and denial'),
mc(3,'What connects the heavenly voices at Jesus’ baptism and transfiguration?','Both identify Jesus as the beloved Son',['Both command Jesus to leave Galilee','Both announce that John has risen','Both speak directly to the crowds in Jerusalem'],'At the baptism the voice calls Jesus the beloved Son; at the transfiguration it adds the command to hear Him.',[r(1,9,11),r(9,2,8)],'The beloved Son'),
mc(2,'Which confession at the cross echoes Mark’s opening declaration about Jesus?','The centurion’s declaration that Jesus was the Son of God',['Pilate’s question about the King of the Jews','The crowd’s demand to release Barabbas','Joseph’s request for Jesus’ body'],'Mark begins with Jesus Christ, the Son of God, and the centurion uses that title after His death.',[r(1,1),r(15,37,39)],'Mark’s opening and the cross'),

mc(1,'Which four disciples are called first and later belong to the Twelve?','Simon, Andrew, James, and John',['Philip, Bartholomew, Thomas, and Thaddaeus','Matthew, James, Judas, and Simon the Cananite','James, Joses, Judas, and Simon'],'The first fishermen called are Simon, Andrew, James, and John; all four appear in the list of the Twelve.',[r(1,16,20),r(3,13,19)],'Calling the disciples'),
mc(2,'How does the mission of the Twelve develop from their appointment to their first journey?','They are appointed to be with Jesus and preach, then are sent two by two with authority over unclean spirits',['They are appointed to govern Galilee, then sent to collect taxes','They are told never to leave Jesus, then sent alone to Jerusalem','They are appointed only to heal, then forbidden to preach'],'Jesus appoints the Twelve to be with Him, preach, heal, and cast out demons, then sends them in pairs.',[r(3,13,15),r(6,7,13)],'Mission of the Twelve'),
mc(2,'What repeated misunderstanding follows Jesus’ predictions of His suffering?','The disciples turn toward human ideas of power and greatness',['The disciples immediately understand and begin preparing His burial','The crowds ask to be baptized by John again','The Pharisees accept Jesus as the Christ'],'Peter rejects the suffering path, and later the disciples argue about greatness and seek places of glory.',[r(8,31,35),r(9,30,35),r(10,32,45)],'Discipleship and the cross'),
mc(2,'What does Jesus require of anyone who wants to follow Him?','Deny oneself, take up the cross, and follow Him',['Gain authority over the Gentiles','Seek the first place at feasts','Avoid all contact with sinners'],'Jesus defines following Him through self-denial and the cross, and presents His own service and ransom as the model.',[r(8,34,38),r(10,42,45)],'The way of discipleship'),
mc(3,'How do the disciples’ sleep in Gethsemane contrast with Jesus’ earlier teaching?','He had commanded watchfulness and prayer, but they repeatedly slept',['He had commanded sleep before trials, and they obeyed','He had forbidden prayer at night, but they prayed','He had told only the crowds to watch, not the disciples'],'Jesus teaches everyone to watch, then tells His disciples to watch and pray in Gethsemane, where they fall asleep.',[r(13,33,37),r(14,32,41)],'Watch and pray'),
mc(2,'What change occurs between the disciples’ flight at Jesus’ arrest and their work at Mark’s ending?','They flee at the arrest but later preach everywhere',['They defeat the arresting crowd and remain in Jerusalem','They never leave Galilee and do not preach','They replace Judas before Jesus is crucified'],'All forsake Jesus and flee, but after the resurrection commission they preach everywhere.',[r(14,43,52),r(16,14,20)],'Failure and restored mission'),

mc(1,'What do the two large feeding miracles have in common?','Jesus multiplies loaves, everyone eats, and baskets of fragments remain',['The disciples buy enough bread in nearby villages','Each crowd contains exactly five thousand people','Both happen inside Jerusalem'],'In both feedings Jesus receives a small supply, gives thanks or blesses it, feeds the crowd, and leaves abundant fragments.',[r(6,34,44),r(8,1,10)],'Feeding the multitudes'),
mc(2,'Which numbers correctly distinguish the two feedings?','Five loaves, five thousand, and twelve baskets; seven loaves, four thousand, and seven baskets',['Seven loaves, five thousand, and five baskets; twelve loaves, four thousand, and seven baskets','Five loaves and four thousand in both accounts','Twelve loaves and twelve thousand in the first; seven loaves and seven thousand in the second'],'Jesus Himself recalls the different numbers when challenging the disciples to understand.',[r(6,38,44),r(8,5,9),r(8,19,21)],'Remembering the loaves'),
mc(3,'What does Mark connect with the disciples’ failure to understand the loaves?','Hardness of heart',['Lack of money alone','Absence from the feeding','Opposition from John the Baptist'],'After Jesus walks on the sea Mark says they had not understood the loaves because their heart was hardened; Jesus raises the same issue later.',[r(6,45,52),r(8,14,21)],'The disciples’ understanding'),
mc(2,'How do Jesus’ two sea miracles reveal His authority?','He commands the storm to be still and later walks on the sea',['He avoids every storm by remaining on land','He asks the disciples to calm the sea both times','He parts the Jordan for the crowds'],'Jesus rebukes wind and sea in one crossing and walks across the water in another.',[r(4,35,41),r(6,45,52)],'Authority over the sea'),
mc(2,'Which two healings involve Jesus using touch and saliva away from a crowd?','The deaf man and the blind man at Bethsaida',['Jairus’s daughter and the leper','The paralytic and Bartimaeus','Simon’s mother-in-law and the Syro-Phoenician’s daughter'],'Jesus takes the deaf man and the Bethsaida blind man aside and uses personal physical actions in their healings.',[r(7,31,37),r(8,22,26)],'Healing the deaf and blind'),
mc(2,'What common response does Jesus give Jairus and the father of the afflicted boy?','He directs them toward faith in the face of fear or doubt',['He tells them their requests are unlawful','He requires payment before acting','He sends both to the priests without helping'],'Jesus tells Jairus not to fear but believe, and tells the father that all things are possible to one who believes.',[r(5,35,43),r(9,17,27)],'Faith amid fear'),
mc(2,'What is similar about the woman with the flow of blood and Bartimaeus?','Both persist in approaching Jesus and are told that faith has made them well',['Both are carried by four friends','Both ask Jesus to leave their region','Both are healed without knowing Jesus is near'],'The woman reaches through the crowd and Bartimaeus cries out despite rebukes; Jesus commends faith in both.',[r(5,25,34),r(10,46,52)],'Persistent faith'),

mc(2,'How do the cleansed leper and healed deaf man respond to commands not to publicize what happened?','They spread the news despite Jesus’ command',['They remain completely silent','They report only to Pilate','They immediately join the Twelve'],'Both accounts say proclamation increased despite Jesus’ instruction.',[r(1,40,45),r(7,32,37)],'Commands to silence'),
mc(3,'How does the former demoniac’s instruction differ from many commands to silence?','Jesus explicitly sends him home to tell what the Lord has done',['Jesus forbids him ever to speak of the healing','Jesus appoints him as one of the Twelve','Jesus sends him to confront Herod'],'Unlike several healed people told not to spread the news, the restored man is commissioned to tell his friends.',[r(1,40,45),r(5,18,20),r(7,32,37)],'Witness and silence'),
mc(2,'When is the transfiguration no longer to be kept secret?','After the Son of Man has risen from the dead',['After John is arrested','After the feeding of the four thousand','After the temple is destroyed'],'Jesus ties the end of this silence to His resurrection.',[r(9,2,10),r(16,6,15)],'Revelation after resurrection'),
mc(3,'What movement occurs from Jesus’ early secrecy commands to the ending of Mark?','The disciples move from restricted disclosure to preaching the gospel to every creature',['Jesus permanently forbids anyone from speaking about Him','Only unclean spirits receive the final commission','The message remains limited to Capernaum'],'The early narrative often restrains premature publicity; the risen Lord commands worldwide proclamation.',[r(1,34,45),r(8,27,30),r(16,14,20)],'From secrecy to proclamation'),

mc(1,'Who prepares the Lord’s way at the beginning and is later executed by Herod?','John the Baptist',['Elijah','Bartimaeus','Joseph of Arimathea'],'John appears as the promised messenger and is later beheaded because of Herod’s oath and Herodias’s hostility.',[r(1,2,8),r(6,14,29)],'John the Baptist'),
mc(2,'How is John connected with Elijah in Mark?','People speculate that Jesus is Elijah, and Jesus later teaches that Elijah has come and suffered',['John meets Elijah at the transfiguration','John claims to be Elijah and rules Galilee','Elijah baptizes John in the Jordan'],'Questions about Elijah surround Jesus’ identity, and Jesus connects the expected Elijah with one who has already been mistreated.',[r(6,14,16),r(8,27,30),r(9,9,13)],'John and Elijah'),
mc(3,'How do Herod’s and the Jerusalem leaders’ responses to John resemble each other?','Both fear other people’s regard for John while failing to follow his message',['Both become John’s disciples','Both publicly declare John to be the Christ','Both release John from custody'],'Herod fears John as just and holy; the leaders fear the people because they count John a prophet.',[r(6,17,29),r(11,27,33)],'Responses to John'),

mc(1,'What three events does Jesus repeatedly predict before entering Jerusalem?','Betrayal or rejection, death, and resurrection',['Coronation, military victory, and retirement','Marriage, exile, and return to Nazareth','A second baptism, imprisonment, and escape'],'Across three predictions Jesus teaches that He will suffer, be killed, and rise.',[r(8,31),r(9,30,32),r(10,32,34)],'Passion predictions'),
mc(2,'Which details from Jesus’ final prediction appear in the Passion narrative?','Delivery to Gentiles, mocking, scourging, spitting, death, and resurrection',['A battle at the Sea of Galilee and flight to Egypt','Release by Pilate followed by peaceful teaching','Coronation by the Twelve in the temple'],'The prediction in Mark 10 closely anticipates the treatment narrated in Mark 14–16.',[r(10,32,34),r(14,53,65),r(15,1,20),r(16,1,7)],'Prediction and fulfillment'),
mc(2,'How does the anointing at Bethany interpret Jesus’ approaching death?','Jesus says the woman has anointed His body beforehand for burial',['Jesus says it prevents His arrest','Jesus says it crowns Him as Herod’s successor','Jesus says it replaces the Passover meal'],'Jesus explicitly connects her act with His burial.',[r(14,3,9),r(15,42,47)],'Anointing and burial'),
mc(2,'What prediction about Peter is fulfilled during Jesus’ trial?','Peter denies Jesus three times before the rooster crows twice',['Peter betrays Jesus with a kiss','Peter remains awake through all three prayers','Peter testifies for Jesus before Pilate'],'Jesus’ precise warning is recalled when the rooster crows the second time.',[r(14,27,31),r(14,66,72)],'Peter’s denial'),
mc(3,'How does Jesus’ statement about giving His life connect with the Last Supper?','The ransom for many is echoed by His blood of the covenant shed for many',['The Last Supper cancels His earlier teaching about service','Both passages promise political rule to James and John','The cup is identified as John’s baptism'],'The shared phrase “for many” connects Jesus’ self-giving service with the covenant cup.',[r(10,42,45),r(14,22,25)],'The ransom and covenant'),
mc(2,'What promised meeting is announced before Jesus’ arrest and again at the empty tomb?','Jesus will go before His disciples to Galilee after He is raised',['Jesus will meet Pilate in Rome','Jesus will return to Nazareth before the cross','Jesus will meet Herod at the Jordan'],'Jesus predicts the Galilee meeting, and the young man repeats it after the resurrection.',[r(14,27,28),r(16,5,7)],'The promised Galilee meeting'),

mc(2,'How does Jesus redefine greatness after the disciples argue and seek places of honor?','The first must be servant and slave of all',['The greatest must rule like Gentile leaders','Only the two sons of Zebedee may lead','Greatness depends on wealth'],'Jesus answers rivalry with the pattern of receiving the lowly and serving rather than ruling over others.',[r(9,33,37),r(10,35,45)],'Greatness through service'),
mc(2,'What contrast does Mark draw between the rich man and the poor widow?','The rich man cannot release his possessions, while the widow gives her whole livelihood',['Both are praised for keeping their wealth','The widow asks Jesus how to inherit eternal life','The rich man gives everything immediately'],'One goes away sorrowful because he has much; the other gives all she has.',[r(10,17,31),r(12,41,44)],'Wealth and wholehearted giving'),

mc(3,'What progression concerning the temple runs from Jesus’ final week to His death?','He clears it, predicts its destruction, is falsely accused about it, and at His death its veil is torn',['He rebuilds it before entering Jerusalem','He transfers it to Galilee','He appoints the Twelve as its priests'],'Temple conflict and prophecy intensify until the veil is torn when Jesus dies.',[r(11,15,18),r(13,1,2),r(14,55,59),r(15,37,38)],'The temple in the Passion'),
mc(2,'What repeated command links Jesus’ discourse on coming troubles with Gethsemane?','Watch and pray',['Build larger barns','Return to Capernaum','Ask for a sign'],'Jesus closes the discourse with watchfulness, then gives the same command as His arrest approaches.',[r(13,32,37),r(14,32,41)],'Watchfulness'),

mc(3,'Which “hardness of heart” pattern appears among opponents, disciples, and resurrection witnesses?','Opponents resist mercy, disciples fail to understand, and the Eleven resist resurrection testimony',['Only unclean spirits are described as hard-hearted','Hardness always means physical illness','Every crowd is condemned for hardness after believing'],'Mark uses hardness in conflicts over healing, failures to understand, and refusal to believe witnesses.',[r(3,1,6),r(6,45,52),r(8,14,21),r(16,9,14)],'Hardness of heart'),
mc(2,'How do the Syro-Phoenician woman and the Gentile centurion contribute to Mark’s widening witness?','A Gentile woman receives deliverance for her daughter, and a Gentile centurion confesses Jesus as God’s Son',['Both reject Jesus after seeing miracles','Both are members of the Twelve','Both ask Jesus to leave Galilee'],'The woman’s persistent faith receives mercy, while the centurion voices the climactic human confession at the cross.',[r(7,24,30),r(15,37,39)],'Gentile faith and witness'),
mc(2,'What do the former demoniac and the final commission show about the geographic spread of witness?','Testimony moves through Decapolis and ultimately into all the world',['Witness remains confined to one synagogue','Only Jerusalem may hear the gospel','The disciples are told never to cross the sea'],'The restored man proclaims in Decapolis; the risen Jesus sends the disciples into all the world.',[r(5,18,20),r(16,15,20)],'The gospel spreads outward'),

tf(1,'True or false: Mark presents Jesus’ authority over teaching, unclean spirits, sickness, sin, and nature.',true,[r(1,21,34),r(2,5,12),r(4,35,41)],'Jesus’ authority','True. These early chapters display authority in each of those areas.'),
tf(2,'True or false: Both feeding accounts end with exactly twelve baskets of fragments.',false,[r(6,41,44),r(8,6,9)],'The two feedings','False. The five thousand leave twelve baskets; the four thousand leave seven.'),
tf(2,'True or false: Jesus praises Gentile-style domination as the model for leadership among His disciples.',false,[r(9,33,37),r(10,42,45)],'Servant leadership','False. Greatness among His followers is expressed through service.'),
tf(2,'True or false: Mark records women at Jesus’ anointing, crucifixion, burial, and empty tomb.',true,[r(14,3,9),r(15,40,47),r(16,1,8)],'Women in the Passion','True. Women are present as devoted witnesses throughout these scenes.'),
tf(3,'True or false: The command to watch appears only in Gethsemane.',false,[r(13,33,37),r(14,34,38)],'Watchfulness','False. It is central to the preceding discourse and repeated in Gethsemane.'),
tf(3,'True or false: Jesus’ three passion predictions are followed by complete understanding from the Twelve.',false,[r(8,31,38),r(9,30,37),r(10,32,45)],'Passion predictions and misunderstanding','False. Each section exposes misunderstanding about suffering, status, or discipleship.'),
tf(3,'True or false: The first and last chapters both connect belief, baptism, and gospel proclamation.',true,[r(1,4,15),r(16,15,20)],'Beginning and ending of mission','True. Mark begins with repentance, baptism, and gospel proclamation and ends with worldwide proclamation and belief joined to baptism.'),

sa(2,'Name the two occasions when a heavenly voice calls Jesus the beloved Son.','His baptism and His transfiguration',[r(1,9,11),r(9,2,8)],'The beloved Son','The Father speaks at the Jordan and on the mountain.'),
sa(2,'What two commands summarize Jesus’ response to fear and uncertainty in the storm and at Jairus’s house?','Have faith and do not be afraid',[r(4,39,41),r(5,35,43)],'Faith rather than fear','Jesus challenges fear in the boat and tells Jairus to believe.'),
sa(2,'What two places mark the movement from Jesus’ entry toward His arrest and prayer?','The temple and Gethsemane',[r(11,11,18),r(14,32,49)],'Jerusalem and Gethsemane','Jesus confronts corruption in the temple and later prays in Gethsemane before His arrest.'),
sa(3,'How do the request of James and John and the positions of the crucified robbers create an irony?','They ask for places at Jesus’ right and left in glory, while robbers occupy His right and left at the cross',[r(10,35,40),r(15,24,32)],'Right and left of Jesus','The Passion reveals a form of enthronement very different from the disciples’ ambition.'),
sa(3,'How does Mark connect prayer with ministry, spiritual struggle, and suffering?','Jesus prays in solitude and Gethsemane, teaches prayer and watchfulness, and says prayer and fasting are needed in spiritual struggle',[r(1,35,39),r(9,28,29),r(11,22,25),r(13,33,37),r(14,32,42)],'Prayer across Mark','Prayer accompanies Jesus’ mission, the disciples’ dependence, watchfulness, forgiveness, and surrender.'),
sa(3,'Trace the title “King” from Jesus’ entry into Jerusalem through His crucifixion.','The crowd welcomes David’s coming kingdom, Pilate questions Jesus as King of the Jews, soldiers mock that title, and it is written above His cross',[r(11,7,10),r(15,1,26)],'The kingship of Jesus','Mark moves from royal acclamation to ironic mockery and the crucifixion inscription.'),
sa(3,'What repeated contrast does Mark make between seeing signs and truly understanding Jesus?','Miracles and signs do not automatically produce faith or understanding; disciples and opponents can see yet remain hard-hearted or unbelieving',[r(6,45,52),r(8,11,26),r(16,9,14)],'Seeing and believing','The narrative repeatedly distinguishes physical sight or witnessed power from faithful understanding.'),
]

export default {slug:'all-mark',tag:'all-mark-v1',status:'published' as const,rows}
