// Mark 9 — quiz bank (NKJV, Orthodox Study Bible). Every row is anchored to a verse;
// fill-in-the-blank rows are verified against the stored verse text by scripts/seed-quiz-bank.ts.
import { mc, blank, word, tf, sa, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: 'Mark',
  chapter: 9,
  tag: 'quiz-v2-mark-9',
  rows: [
    // ══════════════════════════════════ v1 · Some will not taste death
    mc(1, 'Just before the Transfiguration, what did Jesus say some standing with Him would see before they tasted death?', ['The kingdom of God present with power', 'The Son of Man risen from the dead', 'Elijah coming first to restore all things', 'A cloud overshadowing them on a high mountain'], 1),
    blank(3, 'And He said to them, "Assuredly, I say to you that there are some standing here who will not taste _____ till they see the kingdom of God present with power."', 'death', 1),
    tf(3, 'Jesus told His hearers that some standing there would not taste death till they saw the kingdom of God present with power.', true, 1),

    // ══════════════════════════════════ v2–8 · The Transfiguration
    mc(1, 'Which three disciples did Jesus lead up the high mountain where He was transfigured?', ['Peter, James, and John', 'Peter, Andrew, and John', 'James, John, and Levi', 'Peter, James, and Andrew'], 2),
    word(2, 'How many days passed before Jesus took Peter, James, and John up the high mountain?', 'six', 2, ['6']),
    blank(1, 'Now after six days Jesus took Peter, James, and John, and led them up on a high _____ apart by themselves; and He was transfigured before them.', 'mountain', 2),
    tf(1, 'Jesus took Peter, Andrew, and John up the high mountain where He was transfigured.', false, 2, 'Jesus took Peter, James, and John up the mountain "apart by themselves."'),
    mc(3, 'On the mountain, how does Mark describe the clothes of the transfigured Jesus?', ['Shining, exceedingly white, like snow, such as no launderer on earth can whiten', 'Glistening like the sun, so that the disciples could not look at Him', 'White as wool, and His face shone like lightning', 'Bright like fire, so that the cloud around Him glowed'], 3),
    blank(2, 'His clothes became shining, exceedingly white, like _____, such as no launderer on earth can whiten them.', 'snow', 3),
    tf(3, 'Mark says the clothes of the transfigured Jesus were whiter than any launderer on earth could make them.', true, 3, '"Such as no launderer on earth can whiten them."'),
    mc(1, 'On the high mountain, which two men appeared talking with Jesus, and what did Peter offer to build?', ['Elijah and Moses; three tabernacles', 'Moses and Abraham; an altar', 'Elijah and John the Baptist; a synagogue', 'Moses and David; three tents of meeting'], 4),
    word(1, 'Who appeared with Moses on the mountain of Transfiguration, talking with Jesus?', 'Elijah', 4, ['elias']),
    blank(1, 'And Elijah appeared to them with _____, and they were talking with Jesus.', 'Moses', 4),
    tf(1, 'On the mountain, Elijah and Moses appeared and were talking with Jesus.', true, 4),
    mc(1, 'When Peter saw Jesus talking with Moses and Elijah, what did he offer to do?', ['Make three tabernacles, one each for Jesus, Moses, and Elijah', 'Go down and tell the other disciples what he had seen', 'Ask Elijah why the scribes say he must come first', 'Build one tabernacle for Jesus alone on the mountain'], 5),
    word(1, 'How many tabernacles did Peter propose making on the mountain?', 'three', 5, ['3']),
    blank(2, 'Then Peter answered and said to Jesus, "Rabbi, it is good for us to be here; and let us make three _____: one for You, one for Moses, and one for Elijah"', 'tabernacles', 5, ['tabernacle', 'tents', 'booths']),
    word(3, 'What title did Peter use when he addressed Jesus on the mountain of Transfiguration?', 'Rabbi', 5),
    sa(2, 'On the mountain, what did Peter say to Jesus after Moses and Elijah appeared?', '"Rabbi, it is good for us to be here; and let us make three tabernacles: one for You, one for Moses, and one for Elijah."', 5),
    tf(2, 'Peter offered to make three tabernacles: one for Jesus, one for Moses, and one for John.', false, 5, 'The third tabernacle was to be for Elijah, not John.'),
    mc(3, 'Why did Peter blurt out the offer to make three tabernacles?', ['He did not know what to say, for they were greatly afraid', 'Jesus had asked the three what they wanted Him to do for them', 'Moses and Elijah had asked for somewhere to stay on the mountain', 'He wanted the multitude below to come up and see the vision'], 6),
    tf(1, 'Mark says Peter spoke about the tabernacles because he did not know what to say, for they were greatly afraid.', true, 6),
    mc(1, 'On the mountain, what did the voice from the cloud say?', ['"This is My beloved Son. Hear Him!"', '"You are My beloved Son, in whom I am well pleased."', '"This is My Servant, whom I have chosen. Follow Him!"', '"This is Elijah, who restores all things. Hear him!"'], 7),
    word(2, 'What came and overshadowed Jesus and the disciples on the mountain before the voice spoke?', 'cloud', 7, ['a cloud', 'the cloud']),
    blank(1, 'And a cloud came and overshadowed them; and a voice came out of the cloud, saying, "This is My beloved _____. Hear Him!"', 'Son', 7),
    sa(1, 'On the mountain, where did the voice come from, and what did it tell the disciples to do?', 'The voice came out of the cloud that overshadowed them and said, "This is My beloved Son. Hear Him!"', 7),
    tf(2, 'On the mountain, the voice that said "This is My beloved Son" came out of the cloud that overshadowed them.', true, 7),
    mc(2, 'After the voice spoke from the cloud, what did the disciples see when they looked around?', ['No one anymore, but only Jesus with themselves', 'Moses and Elijah still talking with Jesus', 'The cloud lifting and the multitude waiting below', 'Jesus alone, His clothes no longer shining'], 8),
    blank(2, 'Suddenly, when they had looked around, they saw no one anymore, but only _____ with themselves.', 'Jesus', 8),
    tf(1, 'After the cloud and the voice, the disciples looked around and saw Moses and Elijah still standing with Jesus.', false, 8, 'They "saw no one anymore, but only Jesus with themselves."'),

    // ══════════════════════════════════ v9–13 · Coming down: tell no one; Elijah first
    mc(2, 'Coming down the mountain, what did Jesus command Peter, James, and John?', ['To tell no one what they had seen till the Son of Man had risen from the dead', 'To tell the other disciples what they had seen on the mountain', 'To go ahead of Him into Galilee and say nothing to the scribes', 'To pray and fast so that they could cast out the mute spirit'], 9),
    blank(2, 'Now as they came down from the mountain, He commanded them that they should tell no one the things they had seen, till the Son of Man had _____ from the dead.', 'risen', 9, ['rose', 'arisen']),
    mc(3, 'What did the three disciples do with Jesus’ command to tell no one about the Transfiguration?', ['They kept the word to themselves, questioning what the rising from the dead meant', 'They told the other nine disciples privately in the house', 'They asked Jesus openly what the rising from the dead meant', 'They forgot it when they saw the multitude at the foot of the mountain'], 10),
    sa(3, 'After Jesus told the three to tell no one what they had seen, what did they keep questioning among themselves?', 'They questioned what the rising from the dead meant.', 10),
    mc(2, 'Coming down from the mountain, what question did the disciples ask Jesus about the scribes’ teaching?', ['Why the scribes say that Elijah must come first', 'Why the scribes were disputing with the other disciples', 'Why the scribes say the Son of Man must suffer many things', 'Why the scribes would not let a man cast out demons'], 11),
    word(1, 'Coming down the mountain, the disciples asked Jesus why the scribes say who must come first?', 'Elijah', 11, ['elias']),
    blank(1, 'And they asked Him, saying, "Why do the scribes say that _____ must come first?"', 'Elijah', 11, ['elias']),
    tf(2, 'The disciples asked Jesus why the Pharisees say that Elijah must come first.', false, 11, 'They asked why "the scribes" say Elijah must come first.'),
    mc(3, 'According to Jesus, what does Elijah do when he comes first?', ['He restores all things', 'He suffers many things and is treated with contempt', 'He is betrayed into the hands of men', 'He seasons everyone with fire'], 12),
    blank(3, 'Then He answered and told them, "Indeed, Elijah is coming first and _____ all things.', 'restores', 12, ['restore', 'restoreth']),
    sa(3, 'After affirming that Elijah comes first, what did Jesus say is written concerning the Son of Man?', 'That He must suffer many things and be treated with contempt.', 12),
    mc(3, 'What did Jesus say had happened to Elijah, who "has also come"?', ['They did to him whatever they wished, as it is written of him', 'They received him and built a tabernacle for him', 'They asked him to restore all things and he refused', 'They would not hear him, so he went up the mountain'], 13),
    blank(3, 'But I say to you that Elijah has also come, and they did to him whatever they _____, as it is written of him."', 'wished', 13, ['wanted', 'willed']),
    tf(3, 'Jesus told the disciples that Elijah had not yet come.', false, 13, 'Jesus said, "Elijah has also come, and they did to him whatever they wished."'),

    // ══════════════════════════════════ v14–29 · The boy with the mute spirit
    mc(1, 'When Jesus came back to the other disciples after the Transfiguration, what did He find?', ['A great multitude around them, and scribes disputing with them', 'The disciples praying and fasting in the house', 'The disciples arguing about who would be the greatest', 'A man who did not follow them casting out demons'], 14),
    word(2, 'Who were disputing with the disciples when Jesus returned from the mountain?', 'scribes', 14, ['the scribes', 'scribe']),
    tf(2, 'When Jesus came down to the disciples, He found scribes disputing with them in front of a great multitude.', true, 14),
    mc(2, 'How did the people react when they saw Jesus arrive at the crowd below the mountain?', ['They were greatly amazed and ran to greet Him', 'They fell silent and were afraid to ask Him anything', 'They brought the boy with the mute spirit to Him at once', 'They asked Him why His disciples could not cast out the spirit'], 15),
    blank(2, 'Immediately, when they saw Him, all the people were greatly _____, and running to Him, greeted Him.', 'amazed', 15),
    blank(2, 'And He asked the scribes, "What are you _____ with them?"', 'discussing', 16, ['disputing']),
    mc(3, 'What did Jesus ask the scribes when He found them with His disciples?', ['"What are you discussing with them?"', '"Why do you say that Elijah must come first?"', '"Why could you not cast it out?"', '"What was it you disputed among yourselves on the road?"'], 16),
    mc(1, 'In the crowd below the mountain, who answered Jesus’ question and what did he say he had brought?', ['A father, who had brought his son with a mute spirit', 'A scribe, who had brought a question about Elijah', 'A mother, who had brought her daughter with an unclean spirit', 'A disciple, who had brought a little child to Jesus'], 17),
    word(1, 'What kind of spirit did the man in the crowd say his son had?', 'mute', 17, ['a mute spirit', 'dumb']),
    blank(1, 'Then one of the crowd answered and said, "Teacher, I brought You my son, who has a _____ spirit.', 'mute', 17, ['dumb']),
    mc(3, 'How did the father describe what the mute spirit did to his son whenever it seized him?', ['It threw him down; he foamed at the mouth, gnashed his teeth, and became rigid', 'It made him cry out and cut himself among the tombs', 'It made him deaf and blind so that he could not walk', 'It threw him down and left him as one dead for many days'], 18),
    blank(3, 'And wherever it seizes him, it throws him down; he foams at the mouth, gnashes his teeth, and becomes _____.', 'rigid', 18, ['stiff']),
    sa(2, 'The father of the boy with the mute spirit first went to Jesus’ disciples for help. What happened?', 'He asked the disciples to cast the spirit out, but they could not.', 18),
    tf(1, 'The father said he had asked Jesus’ disciples to cast out the spirit, but they could not.', true, 18),
    mc(1, 'How did Jesus respond when the father said the disciples could not cast out the spirit?', ['"O faithless generation, how long shall I be with you? … Bring him to Me."', '"This kind can come out by nothing but prayer and fasting."', '"If you can believe, all things are possible to him who believes."', '"Do not forbid him, for he who is not against us is on our side."'], 19),
    word(2, 'When the disciples could not cast out the mute spirit, Jesus said, "O ___ generation." Give the missing word.', 'faithless', 19, ['unbelieving']),
    sa(3, 'After calling them a faithless generation, what two questions did Jesus ask, and what did He then command?', 'He asked, "How long shall I be with you? How long shall I bear with you?" and then said, "Bring him to Me."', 19),
    mc(3, 'What happened the moment the boy with the mute spirit saw Jesus?', ['The spirit convulsed him, and he fell on the ground and wallowed, foaming at the mouth', 'The spirit cried out and came out of him, leaving him as one dead', 'He was healed at once and Jesus took him by the hand', 'He ran to Jesus with the crowd and greeted Him'], 20),
    tf(2, 'As soon as the boy saw Jesus, the spirit left him quietly and he stood up.', false, 20, 'The spirit convulsed him, and he fell on the ground and wallowed, foaming at the mouth.'),
    mc(1, 'When Jesus asked the father how long his son had suffered from the spirit, what did he answer?', ['"From childhood"', '"Twelve years"', '"Since the scribes came"', '"Three days"'], 21),
    word(1, 'The father said his son had been afflicted by the spirit since what period of life?', 'childhood', 21, ['from childhood', 'a child']),
    blank(2, 'So He asked his father, "How long has this been happening to him?" And he said, "From _____.', 'childhood', 21),
    tf(3, 'Jesus asked the boy himself how long the spirit had been troubling him.', false, 21, 'Jesus asked "his father," who answered, "From childhood."'),
    mc(2, 'Into what two things did the father say the spirit had often thrown his son to destroy him?', ['Into the fire and into the water', 'Into the sea and into the pit', 'Onto the rocks and into the fire', 'Into the tombs and into the river'], 22),
    sa(2, 'How did the father end his plea to Jesus after describing the fire and the water?', '"But if You can do anything, have compassion on us and help us."', 22),
    tf(3, 'The father told Jesus the spirit had often thrown his son into the fire and into the water to destroy him.', true, 22),
    mc(1, 'When the father said "if You can do anything," what did Jesus answer him?', ['"If you can believe, all things are possible to him who believes."', '"O faithless generation, how long shall I bear with you?"', '"This kind can come out by nothing but prayer and fasting."', '"Whoever receives one of these little children in My name receives Me."'], 23),
    blank(2, 'Jesus said to him, "If you can believe, all things are _____ to him who believes."', 'possible', 23),
    mc(1, 'What did the father of the boy with the mute spirit cry out when Jesus told him all things are possible to him who believes?', ['"Lord, I believe; help my unbelief!"', '"Lord, have compassion on us and help us!"', '"Teacher, I brought You my son; heal him!"', '"Rabbi, it is good for us to be here!"'], 24),
    blank(1, 'Immediately the father of the child cried out and said with tears, "Lord, I believe; help my _____!"', 'unbelief', 24),
    tf(3, 'The father answered Jesus calmly and without tears, "Lord, I believe."', false, 24, 'He "cried out and said with tears, ‘Lord, I believe; help my unbelief!’"'),
    sa(3, 'How does Mark describe the manner in which the father said "Lord, I believe; help my unbelief!"?', 'He cried out immediately and said it with tears.', 24),
    mc(3, 'What prompted Jesus to rebuke the unclean spirit in the boy?', ['He saw that the people came running together', 'The father cried out with tears', 'The disciples asked Him why they could not cast it out', 'The scribes began disputing with Him'], 25),
    word(2, 'Jesus addressed the spirit in the boy as a "Deaf and ___ spirit." Give the missing word.', 'dumb', 25, ['mute']),
    blank(3, 'When Jesus saw that the people came running together, He rebuked the unclean spirit, saying to it: "Deaf and dumb spirit, I command you, come out of him and enter him no _____!"', 'more', 25),
    sa(2, 'What exactly did Jesus command the deaf and dumb spirit to do?', '"I command you, come out of him and enter him no more!"', 25),
    mc(3, 'What happened to the boy when the spirit came out of him?', ['He became as one dead, so that many said, "He is dead"', 'He arose at once and began to speak plainly', 'He kept foaming at the mouth and gnashing his teeth', 'He wallowed on the ground until Jesus rebuked the spirit again'], 26),
    sa(3, 'Describe what the spirit did as it left the boy, and how the crowd reacted.', 'The spirit cried out, convulsed him greatly, and came out; the boy became as one dead, so that many said, "He is dead."', 26),
    mc(1, 'After the crowd said "He is dead," what did Jesus do for the boy?', ['Took him by the hand and lifted him up, and he arose', 'Rebuked the spirit a second time until it left him', 'Handed him back to his father and blessed him', 'Told the disciples to pray and fast over him'], 27),
    blank(1, 'But Jesus took him by the _____ and lifted him up, and he arose.', 'hand', 27),
    mc(2, 'Where and how did the disciples ask Jesus why they could not cast out the spirit?', ['Privately, when He had come into the house', 'Openly, in front of the multitude and the scribes', 'On the road, while passing through Galilee', 'On the mountain, as they came down from the Transfiguration'], 28),
    blank(2, 'And when He had come into the house, His disciples asked Him _____, "Why could we not cast it out?"', 'privately', 28, ['in private']),
    mc(1, 'Why did Jesus say the disciples could not cast out the spirit from the boy?', ['"This kind can come out by nothing but prayer and fasting."', '"Because you did not believe; all things are possible to him who believes."', '"Because you disputed among yourselves who would be the greatest."', '"Because this kind comes out only in My name."'], 29),
    word(1, 'Jesus said this kind of spirit comes out by nothing but prayer and what?', 'fasting', 29),
    blank(1, 'So He said to them, "This kind can come out by nothing but _____ and fasting."', 'prayer', 29),
    sa(2, 'What reason did Jesus give His disciples, in the house, for their failure to cast out the mute spirit?', '"This kind can come out by nothing but prayer and fasting."', 29),
    tf(2, 'Jesus told the disciples that this kind of spirit can come out only by prayer and fasting.', true, 29),

    // ══════════════════════════════════ v30–32 · Second passion prediction
    mc(2, 'After healing the boy, where did Jesus and the disciples travel, and what did He want?', ['Through Galilee, and He did not want anyone to know it', 'To Capernaum, and He wanted the twelve gathered', 'Up a high mountain, apart by themselves', 'Through Judea, and He wanted the multitudes to follow'], 30),
    word(1, 'Through which region did Jesus pass after healing the boy, not wanting anyone to know it?', 'Galilee', 30),
    blank(2, 'Then they departed from there and passed through _____, and He did not want anyone to know it.', 'Galilee', 30),
    tf(2, 'As Jesus passed through Galilee after healing the boy, He wanted everyone to know He was there.', false, 30, 'Mark says "He did not want anyone to know it."'),
    mc(2, 'Passing through Galilee, what did Jesus teach His disciples about the Son of Man?', ['He is being betrayed into the hands of men; they will kill Him, and after He is killed He will rise the third day', 'He must suffer many things and be treated with contempt while Elijah restores all things', 'He will come in the glory of His Father with the holy angels', 'He came not to be served but to serve, and to give His life a ransom for many'], 31),
    word(1, 'Jesus said the Son of Man, after being killed, would rise on which day?', 'third', 31, ['3rd', 'the third day', '3']),
    blank(2, 'For He taught His disciples and said to them, "The Son of Man is being betrayed into the hands of men, and they will kill Him. And after He is killed, He will rise the _____ day."', 'third', 31, ['3rd']),
    mc(3, 'How did the disciples respond to Jesus’ teaching in Galilee that the Son of Man would be killed and rise?', ['They did not understand the saying and were afraid to ask Him', 'They rebuked Him, as Peter had done before', 'They asked Him privately in the house what it meant', 'They disputed among themselves what the rising from the dead meant'], 32),
    tf(2, 'The disciples understood Jesus’ words about His death and asked Him many questions about it.', false, 32, 'They "did not understand this saying, and were afraid to ask Him."'),

    // ══════════════════════════════════ v33–37 · Who is the greatest; the little child
    mc(1, 'In which town did Jesus, in the house, ask the disciples what they had disputed on the road?', ['Capernaum', 'Bethsaida', 'Nazareth', 'Caesarea Philippi'], 33),
    blank(2, 'Then He came to _____. And when He was in the house He asked them, "What was it you disputed among yourselves on the road?"', 'Capernaum', 33),
    sa(3, 'In the house at Capernaum, what question did Jesus put to the disciples?', '"What was it you disputed among yourselves on the road?"', 33),
    mc(1, 'Why did the disciples keep silent when Jesus asked what they had disputed on the road to Capernaum?', ['They had disputed who would be the greatest', 'They had disputed why they could not cast out the spirit', 'They had disputed what the rising from the dead meant', 'They had disputed whether to forbid the man casting out demons'], 34),
    word(1, 'On the road to Capernaum, the disciples disputed about who would be the ___. Give the missing word.', 'greatest', 34),
    blank(1, 'But they kept silent, for on the road they had disputed among themselves who would be the _____.', 'greatest', 34),
    tf(1, 'On the road to Capernaum the disciples had argued about who would be the greatest.', true, 34),
    mc(1, 'What did Jesus tell the twelve about anyone who desires to be first?', ['He shall be last of all and servant of all', 'He shall see the kingdom of God present with power', 'He shall receive a hundredfold now in this time', 'He shall sit at His right hand in glory'], 35),
    blank(2, 'And He sat down, called the twelve, and said to them, "If anyone desires to be first, he shall be last of all and _____ of all."', 'servant', 35),
    tf(2, 'Jesus said, "If anyone desires to be first, he shall be last of all and servant of all."', true, 35),
    mc(1, 'After saying the first shall be last, whom did Jesus set in the midst of the disciples?', ['A little child, whom He took in His arms', 'A leper whom He had cleansed', 'The boy He had freed from the mute spirit', 'A poor widow from the crowd'], 36),
    word(1, 'Whom did Jesus take in His arms and set in the midst of the twelve?', 'child', 36, ['a little child', 'little child', 'a child']),
    mc(3, 'In Capernaum, what did Jesus say about whoever receives one of the little children in His name?', ['He receives Jesus, and whoever receives Jesus receives Him who sent Jesus', 'He will by no means lose his reward', 'He shall be first of all and greatest of all', 'He receives the kingdom of God present with power'], 37),
    blank(3, '"Whoever receives one of these little children in My _____ receives Me; and whoever receives Me, receives not Me but Him who sent Me."', 'name', 37),
    sa(3, 'Complete the chain Jesus drew in Capernaum: whoever receives a little child in His name receives whom, and that person in turn receives whom?', 'Whoever receives the child receives Jesus; and whoever receives Jesus receives not Him but Him who sent Him.', 37),

    // ══════════════════════════════════ v38–41 · The man casting out demons; the cup of water
    mc(1, 'What did John report to Jesus about someone who did not follow them?', ['He was casting out demons in Jesus’ name, and they forbade him', 'He was teaching the multitude in the synagogue', 'He was baptizing in the Jordan without permission', 'He was giving cups of water in Jesus’ name'], 38),
    word(1, 'Which disciple told Jesus, "we saw someone who does not follow us casting out demons in Your name"?', 'John', 38),
    blank(2, 'Now _____ answered Him, saying, "Teacher, we saw someone who does not follow us casting out demons in Your name, and we forbade him because he does not follow us."', 'John', 38),
    sa(2, 'Why did John say the disciples had forbidden the man who was casting out demons in Jesus’ name?', 'Because he did not follow them.', 38),
    tf(1, 'It was Peter who told Jesus about the man casting out demons in His name.', false, 38, 'It was John who reported it.'),
    mc(3, 'How did Jesus answer John about the man casting out demons in His name?', ['"Do not forbid him, for no one who works a miracle in My name can soon afterward speak evil of Me."', '"Forbid him, for he does not follow us and does not know Me."', '"Let him be, for this kind can come out by nothing but prayer and fasting."', '"Bring him to Me, and I will see whether he believes."'], 39),
    blank(2, 'But Jesus said, "Do not _____ him, for no one who works a miracle in My name can soon afterward speak evil of Me.', 'forbid', 39, ['hinder', 'stop']),
    tf(2, 'Jesus agreed with John that the man casting out demons in His name should be forbidden.', false, 39, 'Jesus said, "Do not forbid him."'),
    mc(2, 'What principle did Jesus give after telling John not to forbid the man casting out demons?', ['"For he who is not against us is on our side."', '"For he who does not follow us is not on our side."', '"For he who is not against us will not lose his reward."', '"For he who is on our side shall be first of all."'], 40),
    blank(1, 'For he who is not against us is on our _____.', 'side', 40),
    mc(2, 'What did Jesus promise to whoever gives a cup of water in His name because one belongs to Christ?', ['He will by no means lose his reward', 'He will be first of all and servant of all', 'He will receive Him who sent Jesus', 'He will be seasoned with salt'], 41),
    word(1, 'Jesus said whoever gives you a cup of what to drink in His name will not lose his reward?', 'water', 41),
    sa(3, 'Why, according to Jesus, would someone give the disciples a cup of water "in My name"?', 'Because they belong to Christ.', 41),
    tf(3, 'Jesus said whoever gives a cup of wine in His name will by no means lose his reward.', false, 41, 'It is "a cup of water to drink in My name."'),

    // ══════════════════════════════════ v42–48 · Millstone; hand, foot, eye; Gehenna
    mc(2, 'What did Jesus say would be better for anyone who causes one of the little ones who believe in Him to stumble?', ['A millstone hung around his neck and he thrown into the sea', 'His hand cut off so that he enters life maimed', 'To be cast into hell fire where the worm does not die', 'To be seasoned with fire like a sacrifice'], 42),
    word(1, 'What did Jesus say would be hung around the neck of one who causes a little one to stumble?', 'millstone', 42, ['a millstone']),
    tf(3, 'Jesus said it would be better for the one who causes a little one to stumble to have a millstone hung around his neck and be thrown into the fire.', false, 42, 'He said "thrown into the sea."'),
    mc(2, 'What did Jesus say to do if your hand causes you to sin?', ['Cut it off; it is better to enter into life maimed than to go to hell with two hands', 'Cut it off; it is better to enter life lame than to be cast into hell with two hands', 'Pluck it out; it is better to enter the kingdom of God with one than with two', 'Wash it; it is better to be clean than to be defiled'], 43),
    word(3, 'Jesus said it is better to enter into life ___ than, having two hands, to go to hell. Give the missing word.', 'maimed', 43, ['crippled']),
    blank(3, 'If your hand causes you to sin, cut it off. It is better for you to enter into life _____, rather than having two hands, to go to hell, into the fire that shall never be quenched', 'maimed', 43),
    blank(3, 'where ‘Their worm does not _____ And the fire is not quenched.’', 'die', 44),
    mc(3, 'After the saying about the hand, what refrain does Jesus quote about hell?', ['"Their worm does not die and the fire is not quenched"', '"Their flesh is consumed and the fire is never satisfied"', '"Their weeping does not cease and the darkness is not lifted"', '"Their worm does not rest and the smoke is not quenched"'], 44),
    tf(3, 'In the refrain following the hand saying, Jesus says "Their worm does not die and the fire is not quenched."', true, 44),
    word(3, 'Jesus said it is better to enter life ___ than, having two feet, to be cast into hell. Give the missing word.', 'lame', 45, ['crippled']),
    mc(3, 'Which body part did Jesus say to cut off so as to enter life lame rather than be cast into hell with two?', ['Your foot', 'Your hand', 'Your eye', 'Your ear'], 45),
    blank(3, 'where ‘Their worm does not die, And the _____ is not quenched.’', 'fire', 46),
    word(3, 'In the refrain after the foot saying, what creature "does not die"?', 'worm', 46, ['their worm']),
    mc(2, 'What did Jesus say to do if your eye causes you to sin?', ['Pluck it out; it is better to enter the kingdom of God with one eye than to be cast into hell fire with two', 'Cut it out; it is better to enter life maimed with one eye', 'Cover it; it is better to enter life blind than to be cast into hell', 'Wash it; it is better to see clearly than to be thrown into the sea'], 47),
    word(1, 'Jesus said if your eye causes you to sin, you should ___ it out. Give the missing word.', 'pluck', 47, ['tear', 'gouge']),
    blank(2, 'And if your eye causes you to sin, pluck it out. It is better for you to enter the kingdom of God with one eye, rather than having two eyes, to be cast into hell _____', 'fire', 47),
    tf(2, 'Jesus said it is better to enter the kingdom of God with one eye than to be cast into hell fire with two eyes.', true, 47),
    sa(3, 'Compare the three sayings about the hand, the foot, and the eye: what does Jesus say a person enters in each case?', 'With the hand cut off one enters life maimed; with the foot cut off one enters life lame; with the eye plucked out one enters the kingdom of God.', 47),
    blank(3, 'where ‘Their _____ does not die And the fire is not quenched.’', 'worm', 48),
    sa(3, 'What refrain does Jesus repeat after each of the hand, foot, and eye sayings?', '"Their worm does not die and the fire is not quenched."', 48),

    // ══════════════════════════════════ v49–50 · Seasoned with fire; salt
    mc(3, 'What did Jesus say everyone will be seasoned with, and every sacrifice seasoned with?', ['Everyone with fire, every sacrifice with salt', 'Everyone with salt, every sacrifice with fire', 'Everyone with water, every sacrifice with oil', 'Everyone with the Spirit, every sacrifice with blood'], 49),
    blank(3, '"For everyone will be seasoned with _____, and every sacrifice will be seasoned with salt.', 'fire', 49),
    tf(3, 'Jesus said everyone will be seasoned with salt, and every sacrifice with fire.', false, 49, 'It is the other way round: "everyone will be seasoned with fire, and every sacrifice will be seasoned with salt."'),
    mc(2, 'What did Jesus ask about salt that loses its flavor?', ['"How will you season it?"', '"Will it by no means lose its reward?"', '"Shall it be cast into the sea?"', '"How will it be quenched?"'], 50),
    blank(1, 'Salt is good, but if the salt loses its flavor, how will you _____ it? Have salt in yourselves, and have peace with one another."', 'season', 50),
    word(1, 'Jesus closed His teaching: "Have salt in yourselves, and have ___ with one another." Give the missing word.', 'peace', 50),
    sa(1, 'With what two commands did Jesus end His saying about salt?', '"Have salt in yourselves, and have peace with one another."', 50),
    tf(3, 'Jesus told the disciples to have salt in themselves and have peace with the scribes.', false, 50, 'He said "have peace with one another."'),
  ],
};

export default bank;
