// Mark 14 — quiz bank (NKJV, Orthodox Study Bible text as stored). Every row is anchored to a verse;
// fill-in-the-blank rows are verified against the stored verse text by scripts/seed-quiz-bank.ts.
import { mc, blank, word, tf, sa, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: 'Mark',
  chapter: 14,
  tag: 'quiz-v2-mark-14',
  rows: [
    // ══════════════════════════════════ v1–2 · The plot two days before Passover
    mc(1, 'As Mark 14 opens, how many days was it before the Passover, and what were the chief priests and scribes seeking to do?', ['Two days; to take Jesus by trickery and put Him to death', 'Three days; to seize Jesus openly in the temple as He taught', 'Six days; to hand Jesus over to a multitude with swords and clubs', 'One day; to find testimony against Jesus before the council'], 1),
    blank(2, 'After two days it was the Passover and the Feast of Unleavened Bread. And the chief priests and the scribes sought how they might take Him by _____ and put Him to death.', 'trickery', 1),
    sa(2, 'Why did the chief priests and scribes decide not to arrest Jesus during the feast?', 'They feared the people: "Not during the feast, lest there be an uproar of the people."', 2),
    tf(2, 'The chief priests and scribes planned to seize Jesus during the feast so that the whole crowd would see it.', false, 2, 'They said, "Not during the feast, lest there be an uproar of the people."'),
    word(3, 'The chief priests feared that arresting Jesus during the feast would cause what among the people?', 'uproar', 2, ['an uproar', 'riot']),

    // ══════════════════════════════════ v3–9 · The anointing at Bethany
    mc(1, 'In whose house in Bethany was Jesus sitting at the table when a woman anointed His head?', ['Simon the leper', 'Simon Peter', 'Judas Iscariot', 'The high priest'], 3),
    sa(1, 'At the house of Simon the leper in Bethany, what did the woman do with her alabaster flask?', 'She broke the flask of very costly oil of spikenard and poured it on Jesus’ head.', 3),
    blank(3, 'a woman came having an alabaster flask of very costly oil of _____. Then she broke the flask and poured it on His head.', 'spikenard', 3),
    tf(1, 'At Bethany the woman poured the oil of spikenard on Jesus’ feet.', false, 3, 'She broke the flask and poured it on His head.'),
    mc(2, 'How did some of those at Simon the leper’s table react when the woman poured out the spikenard?', ['They were indignant and asked why the fragrant oil was wasted', 'They were glad and promised to give her money', 'They were sorrowful and asked one by one, "Is it I?"', 'They marveled and said, "You also were with Jesus of Nazareth"'], 4),
    blank(2, 'But there were some who were indignant among themselves, and said, "Why was this fragrant oil _____?', 'wasted', 4),
    mc(1, 'According to those who criticized the woman at Bethany, for how much might the oil have been sold?', ['More than three hundred denarii', 'More than two hundred denarii', 'More than one hundred denarii', 'More than five hundred denarii'], 5),
    blank(1, 'For it might have been sold for more than three hundred _____ and given to the poor." And they criticized her sharply.', 'denarii', 5),
    sa(2, 'When some criticized the woman sharply at Bethany, how did Jesus first answer them?', '"Let her alone. Why do you trouble her? She has done a good work for Me."', 6),
    blank(1, 'But Jesus said, "Let her alone. Why do you trouble her? She has done a good _____ for Me.', 'work', 6),
    mc(2, 'Defending the woman at Bethany, what did Jesus say about the poor?', ['"You have the poor with you always, and whenever you wish you may do them good"', '"Sell whatever you have and give to the poor, and follow Me"', '"This poor widow has put in more than all who gave to the treasury"', '"Give the three hundred denarii to the poor, and buy bread for them"'], 7),
    blank(3, 'For you have the poor with you always, and whenever you wish you may do them good; but Me you do not have _____.', 'always', 7),
    sa(1, 'What did Jesus say the woman at Bethany had done "beforehand" by anointing Him?', 'She had come beforehand to anoint His body for burial; "She has done what she could."', 8),
    blank(2, 'She has done what she could. She has come beforehand to anoint My body for _____.', 'burial', 8),
    tf(3, 'Jesus said the woman at Bethany "has done what she could."', true, 8),
    mc(3, 'What did Jesus promise about the woman’s deed at Bethany?', ['The gospel’s hearers worldwide would be told of her deed', 'The scribes would record it for every synagogue', 'The twelve would recall it at every Passover', 'Jerusalem would proclaim her name after His resurrection'], 9),
    blank(3, 'Assuredly, I say to you, wherever this gospel is preached in the whole world, what this woman has done will also be told as a _____ to her."', 'memorial', 9),
    tf(3, 'Jesus said the woman’s deed at Bethany would be told wherever the gospel is preached in Judea.', false, 9, 'He said "wherever this gospel is preached in the whole world."'),
    word(3, 'Jesus said what the woman had done would be told as a "___ to her."', 'memorial', 9),

    // ══════════════════════════════════ v10–11 · Judas and the chief priests
    mc(1, 'After the anointing at Bethany, who went to the chief priests to betray Jesus to them?', ['Judas Iscariot, one of the twelve', 'Simon the leper of Bethany', 'One of the servant girls of the high priest', 'A certain young man in a linen cloth'], 10),
    blank(1, 'Then Judas _____, one of the twelve, went to the chief priests to betray Him to them.', 'Iscariot', 10),
    sa(2, 'How did the chief priests respond when Judas Iscariot came offering to betray Jesus?', 'They were glad and promised to give him money, and he sought how he might conveniently betray Jesus.', 11),
    blank(2, 'And when they heard it, they were glad, and promised to give him _____. So he sought how he might conveniently betray Him.', 'money', 11),
    word(3, 'After the chief priests promised him money, Judas sought how he might betray Jesus in what manner?', 'conveniently', 11),

    // ══════════════════════════════════ v12–17 · Preparing the Passover
    mc(3, 'On the first day of Unleavened Bread, when the Passover lamb was killed, what did the disciples ask Jesus?', ['"Where do You want us to go and prepare, that You may eat the Passover?"', '"Is it I who will betray You at the Passover?"', '"Where is the guest room in which we may eat the Passover?"', '"Shall we go into the city and buy bread for the Passover?"'], 12),
    tf(2, 'The disciples asked where to prepare the Passover on the first day of Unleavened Bread, when the Passover lamb was killed.', true, 12),
    mc(1, 'Jesus sent two disciples into the city to prepare the Passover. Whom did He tell them to follow?', ['A man carrying a pitcher of water', 'A man leading a colt tied at a door', 'A servant of the high priest', 'A woman carrying an alabaster flask'], 13),
    blank(1, 'Go into the city, and a man will meet you carrying a pitcher of _____; follow him.', 'water', 13),
    sa(3, 'What message were the two disciples to give the master of the house where the man with the pitcher went in?', '"The Teacher says, ‘Where is the guest room in which I may eat the Passover with My disciples?’"', 14),
    blank(2, 'The Teacher says, "Where is the _____ room in which I may eat the Passover with My disciples?"', 'guest', 14),
    word(3, 'In the message to the master of the house, by what title did Jesus refer to Himself?', 'Teacher', 14, ['the teacher']),
    mc(3, 'What did Jesus say the master of the house would show the two disciples?', ['A large upper room, furnished and prepared', 'A guest room beside the courtyard of the house', 'A room in the temple where He taught daily', 'A place on the Mount of Olives to keep the feast'], 15),
    blank(3, 'Then he will show you a large upper room, _____ and prepared; there make ready for us."', 'furnished', 15),
    sa(2, 'What did the two disciples find when they went into the city as Jesus directed?', 'They found it just as He had said to them, and they prepared the Passover.', 16),
    tf(2, 'The two disciples could not find the man with the pitcher and returned without preparing the Passover.', false, 16, 'They "found it just as He had said to them; and they prepared the Passover."'),
    mc(1, 'When did Jesus come with the twelve to the room prepared for the Passover?', ['In the evening', 'In the morning', 'At the sixth hour', 'At midnight'], 17),
    word(2, 'Jesus came to the Passover meal in the evening with how many disciples?', 'twelve', 17, ['12']),

    // ══════════════════════════════════ v18–21 · "One of you will betray Me"
    mc(1, 'As they sat and ate the Passover, what did Jesus tell the twelve?', ['"One of you who eats with Me will betray Me"', '"All of you will be made to stumble because of Me this night"', '"Before the rooster crows twice, you will deny Me three times"', '"The Son of Man is being betrayed into the hands of sinners"'], 18),
    blank(1, 'Now as they sat and ate, Jesus said, "Assuredly, I say to you, one of you who eats with Me will _____ Me."', 'betray', 18),
    sa(1, 'How did the disciples react when Jesus said one who ate with Him would betray Him?', 'They became sorrowful and said to Him one by one, "Is it I?"', 19),
    tf(2, 'The disciples all asked Jesus together in one voice, "Is it I?"', false, 19, 'They asked "one by one."'),
    mc(2, 'How did Jesus describe the betrayer to the sorrowful disciples at the table?', ['"It is one of the twelve, who dips with Me in the dish"', '"It is the one to whom I give the bread I have blessed"', '"It is the one who will kiss Me and call Me Rabbi"', '"It is one of you who sat with Me in the temple"'], 20),
    word(1, 'Jesus said the betrayer was one of the twelve who "dips with Me in the ___."', 'dish', 20),
    mc(3, 'What did Jesus say about the man by whom the Son of Man is betrayed?', ['"It would have been good for that man if he had never been born"', '"It would be better for him to be cast into the sea with a millstone"', '"He will never drink of the fruit of the vine in the kingdom of God"', '"He shall be delivered to the Gentiles to be mocked and scourged"'], 21),
    blank(3, 'The Son of Man indeed goes just as it is written of Him, but _____ to that man by whom the Son of Man is betrayed!', 'woe', 21),
    tf(3, 'Jesus said the Son of Man goes "just as it is written of Him."', true, 21),
    sa(3, 'At the Passover table, what did Jesus say of the Son of Man and of the man who betrays Him?', 'The Son of Man goes just as it is written of Him, but woe to the man who betrays Him; it would have been good for him if he had never been born.', 21),

    // ══════════════════════════════════ v22–25 · The bread and the cup
    mc(1, 'As they were eating, what did Jesus do with the bread before He gave it to the twelve?', ['He blessed and broke it', 'He dipped it in the dish', 'He gave thanks and poured oil on it', 'He set it aside until the cup was drunk'], 22),
    blank(1, 'And as they were eating, Jesus took bread, blessed and broke it, and gave it to them and said, "Take, eat; this is My _____."', 'body', 22),
    tf(1, 'At the Passover meal Jesus said of the bread, "Take, eat; this is My body."', true, 22),
    sa(2, 'What did Jesus do with the cup at the Passover meal, and what did the disciples do?', 'He took the cup, gave thanks, and gave it to them, and they all drank from it.', 23),
    blank(2, 'Then He took the cup, and when He had given thanks He gave it to them, and they all _____ from it.', 'drank', 23),
    tf(2, 'Only Peter, James, and John drank from the cup Jesus gave thanks over.', false, 23, '"they all drank from it."'),
    word(3, 'Before giving the cup to the twelve, what did Jesus give?', 'thanks', 23),
    mc(2, 'What did Jesus say the cup was?', ['"My blood of the new covenant, which is shed for many"', '"The cup that I drink, which you also will drink"', '"The cup My Father has given Me to drink"', '"The cup of the kingdom, poured out for the twelve"'], 24),
    blank(1, 'And He said to them, "This is My blood of the new _____, which is shed for many.', 'covenant', 24),
    blank(3, 'Assuredly, I say to you, I will no longer drink of the fruit of the vine until that day when I drink it new in the _____ of God."', 'kingdom', 25),
    mc(3, 'After the cup, until when did Jesus say He would no longer drink of the fruit of the vine?', ['Until the day He drinks it new in the kingdom of God', 'Until He goes before them to Galilee after He is raised', 'Until the Son of Man comes with the clouds of heaven', 'Until the Passover is fulfilled in Jerusalem'], 25),

    // ══════════════════════════════════ v26–31 · The Mount of Olives and Peter’s boast
    mc(1, 'After the Passover meal and a hymn, where did Jesus and the disciples go?', ['To the Mount of Olives', 'To Bethany, to Simon the leper', 'To the courtyard of the high priest', 'To the temple, where He taught daily'], 26),
    blank(1, 'And when they had sung a _____, they went out to the Mount of Olives.', 'hymn', 26),
    mc(2, 'On the Mount of Olives, what did Jesus say would happen to all of the disciples that night?', ['They would all be made to stumble because of Him', 'They would all deny Him three times', 'They would all be seized by the chief priests', 'They would all sleep and fail to watch one hour'], 27),
    blank(3, 'for it is written: "I will strike the Shepherd, And the _____ will be scattered."', 'sheep', 27),
    word(2, 'Jesus quoted, "I will strike the ___, And the sheep will be scattered."', 'Shepherd', 27),
    sa(3, 'What scripture did Jesus quote on the Mount of Olives to explain why the disciples would stumble?', '"I will strike the Shepherd, And the sheep will be scattered."', 27),
    tf(2, 'Jesus said the disciples would be made to stumble because of Him "this night."', true, 27),
    mc(2, 'Where did Jesus say He would go before the disciples after He had been raised?', ['To Galilee', 'To Jerusalem', 'To Bethany', 'To the Mount of Olives'], 28),
    blank(2, '"But after I have been raised, I will go before you to _____."', 'Galilee', 28),
    tf(3, 'Jesus promised that after He was raised He would go before the disciples to Jerusalem.', false, 28, 'He said, "I will go before you to Galilee."'),
    mc(1, 'Which disciple insisted, "Even if all are made to stumble, yet I will not be"?', ['Peter', 'John', 'James', 'Judas'], 29),
    sa(2, 'How did Peter respond when Jesus said all the disciples would stumble?', 'He said, "Even if all are made to stumble, yet I will not be."', 29),
    mc(1, 'What did Jesus tell Peter would happen before the rooster crowed twice?', ['Peter would deny Him three times', 'Peter would fall asleep three times', 'Peter would strike the servant of the high priest', 'Peter would flee from the garden with the others'], 30),
    blank(1, 'before the rooster crows twice, you will deny Me _____ times."', 'three', 30, ['3']),
    tf(1, 'Jesus told Peter he would deny Him three times before the rooster crowed twice.', true, 30),
    mc(3, 'How did Peter answer when Jesus foretold his denial?', ['He insisted he would die with Jesus rather than deny Him', 'He was sorrowful and asked whether it was he', 'He said nothing, then went out and wept', 'He swore that he did not know Jesus'], 31),
    blank(3, 'But he spoke more vehemently, "If I have to _____ with You, I will not deny You!" And they all said likewise.', 'die', 31),
    word(3, 'When Peter said he would die rather than deny Jesus, Mark says he spoke more how?', 'vehemently', 31),

    // ══════════════════════════════════ v32–42 · Gethsemane
    mc(1, 'What was the name of the place where Jesus told His disciples, "Sit here while I pray"?', ['Gethsemane', 'Bethany', 'Golgotha', 'Capernaum'], 32),
    word(1, 'Where did Jesus tell the disciples to sit while He prayed?', 'Gethsemane', 32),
    mc(1, 'Which three disciples did Jesus take with Him deeper into Gethsemane?', ['Peter, James, and John', 'Peter, Andrew, and John', 'James, John, and Judas', 'Peter, James, and Andrew'], 33),
    tf(2, 'In Gethsemane Jesus took Peter, James, and Andrew farther with Him.', false, 33, 'He took Peter, James, and John.'),
    sa(3, 'How is Jesus described as He went farther into Gethsemane with Peter, James, and John?', 'He began to be troubled and deeply distressed.', 33),
    mc(3, 'What did Jesus say to Peter, James, and John about His soul in Gethsemane?', ['"My soul is exceedingly sorrowful, even to death. Stay here and watch"', '"My soul is troubled; go and pray that you do not enter temptation"', '"My soul is willing, but My flesh is weak. Watch with Me one hour"', '"My soul is poured out for many; sit here while I pray"'], 34),
    blank(2, 'Then He said to them, "My soul is exceedingly sorrowful, even to _____. Stay here and watch."', 'death', 34),
    tf(3, 'Jesus told Peter, James, and John that His soul was "exceedingly sorrowful, even to death."', true, 34),
    mc(3, 'What did Jesus pray in Gethsemane when He fell on the ground?', ['That if it were possible, the hour might pass from Him', 'That the disciples might not enter into temptation', 'That the Father would send angels to strengthen Him', 'That the betrayer might repent before the hour came'], 35),
    blank(3, 'He went a little farther, and fell on the ground, and prayed that if it were possible, the _____ might pass from Him.', 'hour', 35),
    mc(1, 'How did Jesus address God in His Gethsemane prayer?', ['"Abba, Father"', '"Holy Father"', '"Lord of heaven and earth"', '"My God, My God"'], 36),
    blank(1, 'And He said, "_____, Father, all things are possible for You. Take this cup away from Me; nevertheless, not what I will, but what You will."', 'Abba', 36),
    blank(3, 'Take this cup away from Me; nevertheless, not what I will, but what You _____."', 'will', 36),
    sa(2, 'In Gethsemane, what did Jesus ask the Father to take away, and how did He submit?', 'He asked the Father to take the cup away from Him, adding, "nevertheless, not what I will, but what You will."', 36),
    tf(1, 'Jesus prayed, "Abba, Father, all things are possible for You."', true, 36),
    mc(1, 'In Gethsemane, what did Jesus find the disciples doing when He returned the first time, and what did He say to Peter?', ['Sleeping; "Simon, are you sleeping? Could you not watch one hour?"', 'Arguing; "Why do you trouble her? She has done a good work for Me"', 'Weeping; "Even if all are made to stumble, yet you will not be"', 'Fleeing; "Rise, let us be going. See, My betrayer is at hand"'], 37),
    blank(2, 'Then He came and found them sleeping, and said to Peter, "_____, are you sleeping? Could you not watch one hour?', 'Simon', 37),
    word(3, 'Jesus asked Peter, "Could you not watch one ___?"', 'hour', 37),
    tf(2, 'When Jesus returned the first time in Gethsemane, He found the disciples praying.', false, 37, 'He "found them sleeping."'),
    mc(2, 'What did Jesus tell the sleeping disciples to do in Gethsemane, and why?', ['"Watch and pray, lest you enter into temptation"', '"Rise and follow, lest you be scattered like sheep"', '"Sit here and wait, lest My betrayer find you"', '"Stay and rest, lest you be found sleeping at the hour"'], 38),
    blank(1, 'Watch and pray, lest you enter into temptation. The spirit indeed is willing, but the _____ is weak."', 'flesh', 38),
    word(1, 'Jesus said, "The ___ indeed is willing, but the flesh is weak."', 'spirit', 38),
    sa(3, 'What did Jesus do after speaking to Peter about watching one hour?', 'He went away again and prayed, speaking the same words.', 39),
    blank(2, 'Again He went away and prayed, and spoke the same _____.', 'words', 39),
    tf(3, 'The second time Jesus went to pray in Gethsemane, He spoke the same words as before.', true, 39),
    mc(2, 'When Jesus returned the second time in Gethsemane, what did He find and why?', ['The disciples asleep again, for their eyes were heavy', 'The disciples gone, for they had all forsaken Him', 'Judas arriving with the multitude, for the hour had come', 'Peter warming himself, for the night was cold'], 40),
    blank(3, 'And when He returned, He found them asleep again, for their eyes were _____; and they did not know what to answer Him.', 'heavy', 40),
    sa(3, 'When Jesus found the disciples asleep the second time, how did they respond to Him?', 'They did not know what to answer Him.', 40),
    mc(2, 'Returning the third time, what did Jesus tell the disciples had come?', ['The hour: the Son of Man is being betrayed into the hands of sinners', 'The Passover: the lamb must be killed and eaten', 'The kingdom of God: He would drink the fruit of the vine new', 'The rooster’s crowing: Peter would deny Him three times'], 41),
    blank(3, 'Then He came the third time and said to them, "Are you still sleeping and resting? It is _____! The hour has come; behold, the Son of Man is being betrayed into the hands of sinners.', 'enough', 41),
    word(3, 'How many times did Jesus come back to His disciples in Gethsemane?', 'three', 41, ['3']),
    mc(3, 'What were Jesus’ final words to the disciples in Gethsemane before Judas arrived?', ['"Rise, let us be going. See, My betrayer is at hand"', '"Stay here and watch, for My hour is at hand"', '"Go into the city, and a man will meet you"', '"All of you will be made to stumble because of Me this night"'], 42),
    blank(1, 'Rise, let us be going. See, My _____ is at hand."', 'betrayer', 42),

    // ══════════════════════════════════ v43–52 · The arrest
    mc(1, 'Who arrived in Gethsemane while Jesus was still speaking, and with whom?', ['Judas, one of the twelve, with a great multitude with swords and clubs', 'The high priest, with the chief priests, elders, and scribes', 'Peter, James, and John, with the rest of the disciples', 'A servant girl of the high priest, with the officers'], 43),
    sa(3, 'Who sent the multitude with swords and clubs that came with Judas?', 'The chief priests and the scribes and the elders.', 43),
    mc(2, 'What signal had Judas given the multitude for identifying Jesus?', ['"Whomever I kiss, He is the One; seize Him and lead Him away safely"', '"The One I call Rabbi, seize Him and bring Him to the high priest"', '"The One who dips with me in the dish, take Him"', '"The One standing in the midst, lay hold of Him and bind Him"'], 44),
    blank(2, 'Now His betrayer had given them a signal, saying, "Whomever I _____, He is the One; seize Him and lead Him away safely."', 'kiss', 44),
    mc(1, 'What did Judas say and do when he came up to Jesus in Gethsemane?', ['He said, "Rabbi, Rabbi!" and kissed Him', 'He said, "Teacher, Teacher!" and bowed before Him', 'He said, "Master!" and laid hands on Him', 'He said, "Is it I?" and drew his sword'], 45),
    word(1, 'What title did Judas call Jesus twice as he kissed Him?', 'Rabbi', 45),
    sa(1, 'What happened immediately after Judas kissed Jesus?', 'They laid their hands on Jesus and took Him.', 46),
    blank(1, 'Then they laid their _____ on Him and took Him.', 'hands', 46),
    mc(2, 'During the arrest, what did one of those who stood by do with his sword?', ['Struck the servant of the high priest and cut off his ear', 'Struck Judas and cut off his hand', 'Struck one of the officers and wounded his head', 'Struck at the young man in the linen cloth'], 47),
    blank(2, 'And one of those who stood by drew his sword and struck the servant of the high priest, and cut off his _____.', 'ear', 47),
    tf(1, 'Mark names Peter as the one who drew a sword and cut off the ear of the high priest’s servant.', false, 47, 'Mark says only that "one of those who stood by drew his sword."'),
    mc(2, 'What did Jesus ask the multitude who had come with swords and clubs?', ['"Have you come out, as against a robber, with swords and clubs to take Me?"', '"Why do you seek Me by night, when I taught daily in the temple?"', '"Whom do you seek, and why have you brought weapons?"', '"Could you not have taken Me openly in Jerusalem?"'], 48),
    blank(2, 'Then Jesus answered and said to them, "Have you come out, as against a _____, with swords and clubs to take Me?', 'robber', 48),
    mc(3, 'What did Jesus remind the arresting crowd about His teaching?', ['He was daily with them in the temple teaching, and they did not seize Him', 'He had taught in their synagogues every Sabbath without being stopped', 'He had spoken openly in Bethany and Galilee before many witnesses', 'He had taught the twelve in the upper room where no one hindered Him'], 49),
    blank(3, 'I was daily with you in the temple teaching, and you did not seize Me. But the _____ must be fulfilled."', 'Scriptures', 49),
    sa(3, 'According to Jesus at His arrest, why was He being taken at night when He had taught daily in the temple?', 'So that the Scriptures might be fulfilled: "But the Scriptures must be fulfilled."', 49),
    tf(2, 'Jesus said He had taught daily in the temple and had not been seized there.', true, 49),
    mc(1, 'What did the disciples do when Jesus was arrested?', ['They all forsook Him and fled', 'They followed Him to the high priest’s house', 'They drew their swords and fought the multitude', 'They stood by and watched at a distance'], 50),
    blank(1, 'Then they all _____ Him and fled.', 'forsook', 50),
    mc(2, 'Who followed Jesus after the arrest wearing only a linen cloth, and what happened to him?', ['A certain young man; the young men laid hold of him and he fled naked', 'Peter; the servants laid hold of him and he denied knowing Jesus', 'John; the officers seized him and he escaped to Galilee', 'A servant of the high priest; Judas laid hold of him and he fled'], 51),
    blank(2, 'Now a certain young man followed Him, having a _____ cloth thrown around his naked body.', 'linen', 51),
    sa(2, 'How did the young man in the linen cloth escape those who laid hold of him?', 'He left the linen cloth behind and fled from them naked.', 52),
    blank(2, 'and he left the linen cloth and fled from them _____.', 'naked', 52),

    // ══════════════════════════════════ v53–65 · Before the high priest
    mc(1, 'To whom was Jesus led after His arrest, and who was assembled there?', ['To the high priest, with the chief priests, elders, and scribes', 'To Pilate, with the soldiers and the whole garrison', 'To Simon the leper, with the disciples who had fled', 'To the temple, with the officers and servant girls'], 53),
    sa(2, 'Who was assembled with the high priest when Jesus was brought to him?', 'All the chief priests, the elders, and the scribes.', 53),
    mc(2, 'Where did Peter go after Jesus was led to the high priest, and what did he do there?', ['He sat with servants by the courtyard fire and warmed himself', 'He wept in the upper room over his boast to die with Jesus', 'He hid in Gethsemane until the rooster crowed', 'He stood behind the witnesses in the council chamber'], 54),
    blank(2, 'But Peter followed Him at a distance, right into the courtyard of the high priest. And he sat with the servants and warmed himself at the _____.', 'fire', 54),
    word(1, 'Peter followed Jesus to the high priest’s house at a what?', 'distance', 54),
    tf(1, 'Peter followed Jesus at a distance into the courtyard of the high priest.', true, 54),
    tf(3, 'In the high priest’s courtyard, Peter warmed himself at the fire with the elders.', false, 54, 'He "sat with the servants and warmed himself at the fire."'),
    mc(2, 'What did the chief priests and all the council seek against Jesus, and what did they find?', ['Testimony to put Him to death, but they found none', 'Witnesses who saw Him heal on the Sabbath, and they found many', 'Proof that He had destroyed the temple, and they found two witnesses', 'A charge of stirring an uproar of the people, and found it at once'], 55),
    blank(2, 'Now the chief priests and all the council sought testimony against Jesus to put Him to death, but found _____.', 'none', 55),
    sa(3, 'Why did the many false witnesses against Jesus fail to serve the council’s purpose?', 'Their testimonies did not agree.', 56),
    blank(2, 'For many bore _____ witness against Him, but their testimonies did not agree.', 'false', 56),
    blank(3, 'Then some rose up and bore _____ witness against Him, saying,', 'false', 57),
    mc(2, 'What did some false witnesses claim they had heard Jesus say?', ['He would destroy the handmade temple and build another in three days', 'Not one temple stone would remain upon another', 'He was the Christ seated at the Power’s right hand', 'He would tear down the temple while the whole world watched'], 58),
    blank(2, 'I will destroy this temple made with hands, and within _____ days I will build another made without hands.', 'three', 58, ['3']),
    word(3, 'The false witnesses said Jesus would destroy the temple "made with ___."', 'hands', 58),
    tf(3, 'The false witnesses said Jesus claimed He would build another temple within seven days.', false, 58, '"within three days I will build another made without hands."'),
    sa(3, 'What happened to the witnesses’ testimony even after the temple saying was reported?', 'Not even then did their testimony agree.', 59),
    blank(3, 'But not even then did their testimony _____.', 'agree', 59),
    mc(2, 'When the witnesses failed, what did the high priest stand up and ask Jesus?', ['"Do You answer nothing? What is it these men testify against You?"', '"Are You the King of the Jews, as these men say?"', '"By what authority do You do these things?"', '"Why do You not answer, since You taught daily in the temple?"'], 60),
    blank(3, 'And the high priest stood up in the midst and asked Jesus, saying, "Do You answer _____? What is it these men testify against You?"', 'nothing', 60),
    mc(1, 'What did the high priest ask Jesus the second time, and how did Jesus reply?', ['"Are You the Christ, the Son of the Blessed?" and Jesus said, "I am"', '"Are You the King of the Jews?" and Jesus said, "It is as you say"', '"Are You the Prophet?" and Jesus said, "You have said it"', '"Are You Elijah who was to come?" and Jesus said, "I am He"'], 61),
    blank(1, 'Again the high priest asked Him, saying to Him, "Are You the _____, the Son of the Blessed?"', 'Christ', 61),
    word(2, 'When the high priest first asked Jesus about the witnesses, Jesus kept what?', 'silent', 61, ['silence', 'quiet']),
    sa(2, 'How did Jesus respond when the high priest first asked about the witnesses, and what did the high priest ask next?', 'He kept silent and answered nothing; then the high priest asked, "Are You the Christ, the Son of the Blessed?"', 61),
    blank(1, 'Jesus said, "I am. And you will see the Son of Man sitting at the right hand of the _____, and coming with the clouds of heaven."', 'Power', 62),
    mc(3, 'After answering "I am," what did Jesus say the council would see?', ['The Son of Man at the Power’s right hand, coming with heaven’s clouds', 'The temple destroyed and rebuilt in three days without hands', 'The Shepherd struck and the sheep scattered', 'The Son of Man drinking new wine in God’s kingdom'], 62),
    word(1, 'When asked whether He was the Christ, Jesus answered "I ___."', 'am', 62),
    tf(2, 'Jesus told the high priest they would see the Son of Man coming with the clouds of heaven.', true, 62),
    mc(1, 'What did the high priest do when Jesus said, "I am"?', ['He tore his clothes and said, "What further need do we have of witnesses?"', 'He spat on Him and said, "Prophesy!"', 'He stood up in the midst and asked, "Do You answer nothing?"', 'He sent Him bound to the chief priests and the elders'], 63),
    blank(1, 'Then the high priest tore his _____ and said, "What further need do we have of witnesses?', 'clothes', 63),
    sa(3, 'What did the high priest say and do after Jesus answered "I am"?', 'He tore his clothes and said, "What further need do we have of witnesses? You have heard the blasphemy! What do you think?"', 63),
    tf(3, 'The high priest tore his clothes after hearing the false witnesses about the temple.', false, 63, 'He tore his clothes after Jesus answered "I am" to being the Christ.'),
    mc(2, 'What charge did the high priest name, and what did the council decide?', ['Blasphemy; they all condemned Him to be deserving of death', 'Sedition; they sent Him to be scourged by the officers', 'Sorcery; they demanded that He prophesy before them', 'Sabbath-breaking; they sought further witnesses against Him'], 64),
    blank(2, 'You have heard the _____! What do you think?" And they all condemned Him to be deserving of death.', 'blasphemy', 64),
    tf(1, 'The council all condemned Jesus to be deserving of death.', true, 64),
    mc(2, 'After the council condemned Jesus, how did some treat Him?', ['They spat on Him, blindfolded Him, beat Him, and said, "Prophesy!"', 'They clothed Him in purple and put a crown of thorns on Him', 'They stripped Him and cast lots for His garments', 'They led Him out to the Mount of Olives and scourged Him'], 65),
    blank(2, 'Then some began to spit on Him, and to blindfold Him, and to beat Him, and to say to Him, "_____!"', 'Prophesy', 65),
    word(3, 'After blindfolding and beating Jesus, the mockers commanded Him to do what?', 'Prophesy', 65),
    sa(3, 'How did the officers strike Jesus after the council’s condemnation?', 'The officers struck Him with the palms of their hands.', 65),

    // ══════════════════════════════════ v66–72 · Peter’s three denials
    mc(1, 'Who came to Peter as he was below in the courtyard of the high priest?', ['One of the servant girls of the high priest', 'One of the officers of the council', 'One of the elders who had condemned Jesus', 'One of the young men from Gethsemane'], 66),
    blank(1, 'Now as Peter was below in the courtyard, one of the servant _____ of the high priest came.', 'girls', 66),
    mc(1, 'What did the servant girl say when she saw Peter warming himself?', ['"You also were with Jesus of Nazareth"', '"Surely you are one of them; you are a Galilean"', '"This is the man who cut off the servant’s ear"', '"Are you not one of His twelve disciples?"'], 67),
    blank(1, 'she looked at him and said, "You also were with Jesus of _____."', 'Nazareth', 67),
    mc(2, 'How did Peter deny the servant girl’s first accusation, and what happened next?', ['He denied understanding, went to the porch, and a rooster crowed', 'He denied knowing Jesus, then went out and wept', 'He cursed and swore before the bystanders seized him', 'He said nothing and warmed himself at the fire'], 68),
    blank(2, 'But he denied it, saying, "I neither know nor _____ what you are saying." And he went out on the porch, and a rooster crowed.', 'understand', 68),
    tf(1, 'A rooster crowed after Peter’s first denial.', true, 68),
    sa(1, 'What did Peter say in his first denial to the servant girl?', '"I neither know nor understand what you are saying."', 68),
    mc(2, 'When the servant girl saw Peter again, to whom did she speak and what did she say?', ['To those who stood by: "This is one of them"', 'To Peter: "You also were with Jesus of Nazareth"', 'To the officers: "Seize him, for he is a Galilean"', 'To the high priest: "This man followed Him at a distance"'], 69),
    tf(2, 'Peter’s second accusation came from a different servant girl than the first.', false, 69, '"the servant girl saw him again."'),
    mc(2, 'What reason did the bystanders give for saying Peter was one of Jesus’ followers?', ['He was a Galilean, and his speech showed it', 'He had been seen with Jesus in the temple', 'He had drawn a sword in Gethsemane', 'He was wearing a linen cloth like the young man'], 70),
    blank(2, 'Surely you are one of them; for you are a _____, and your speech shows it."', 'Galilean', 70),
    word(1, 'The bystanders said Peter’s speech showed he was from where; they called him a what?', 'Galilean', 70, ['galilee']),
    sa(3, 'What did those standing by say to Peter a little after his second denial?', '"Surely you are one of them; for you are a Galilean, and your speech shows it."', 70),
    mc(1, 'How did Peter make his third denial?', ['He began to curse and swear, "I do not know this Man of whom you speak!"', 'He said quietly, "I neither know nor understand what you are saying"', 'He shook his head and went out on the porch', 'He wept and said, "Even if all stumble, I will not"'], 71),
    blank(1, 'Then he began to curse and swear, "I do not know this _____ of whom you speak!"', 'Man', 71),
    word(2, 'In his third denial Peter began to curse and to what?', 'swear', 71),
    mc(1, 'What happened right after Peter’s third denial?', ['A second time the rooster crowed', 'The servant girl brought the officers', 'Jesus was led out past the courtyard', 'The bystanders laid hold of Peter'], 72),
    blank(3, 'Then Peter called to mind the word that Jesus had said to him, "Before the rooster crows twice, you will deny Me three times." And when he thought about it, he _____.', 'wept', 72),
    word(1, 'What did Peter do when he remembered Jesus’ words after the rooster crowed the second time?', 'wept', 72, ['weep', 'cried']),
    tf(3, 'The rooster crowed only once during Peter’s denials.', false, 72, 'It crowed after the first denial and "a second time" after the third.'),

    // ══════════════════════════════════ Whole-chapter
    mc(2, 'Which of these happened FIRST in Mark 14?', ['The woman anointed Jesus at Bethany', 'Judas went to the chief priests', 'Jesus prayed in Gethsemane', 'The rooster crowed a second time'], 3),
    mc(3, 'Which of these people is NOT part of the Mark 14 account?', ['Pilate', 'Simon the leper', 'Judas Iscariot', 'The high priest'], 53),
    sa(3, 'In Mark 14, what two predictions did Jesus make on the Mount of Olives that came true before the chapter ended?', 'That all the disciples would stumble (they all forsook Him and fled) and that Peter would deny Him three times before the rooster crowed twice.', 50),
  ],
};

export default bank;
