// Mark 13 — quiz bank (NKJV, Orthodox Study Bible). Every row is anchored to a verse;
// fill-in-the-blank rows are verified against the stored verse text by scripts/seed-quiz-bank.ts.
import { mc, blank, word, tf, sa, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: 'Mark',
  chapter: 13,
  tag: 'quiz-v2-mark-13',
  rows: [
    // ══════════════════════════════════ v1–2 · Leaving the temple: the stones and buildings
    mc(1, 'As Jesus went out of the temple, what did one of His disciples call His attention to?', ['The manner of stones and the buildings that were there', 'The money changers at their tables in the temple', 'The fig tree with leaves but no fruit on it', 'The great crowd gathered in the temple courts'], 1),
    blank(1, 'Then as He went out of the temple, one of His disciples said to Him, "Teacher, see what manner of _____ and what buildings are here!"', 'stones', 1),
    word(1, 'Leaving the temple, a disciple addressed Jesus by what title before pointing out the stones and buildings?', 'Teacher', 1),
    tf(2, 'It was Jesus who first pointed out to His disciples the stones and buildings of the temple.', false, 1, 'One of His disciples said it to Jesus: "Teacher, see what manner of stones and what buildings are here!"'),
    sa(2, 'When a disciple marveled at the temple’s stones and buildings, how did Jesus answer him?', 'He said, "Do you see these great buildings? Not one stone shall be left upon another, that shall not be thrown down."', 2, ['Not one stone shall be left upon another, that shall not be thrown down']),
    tf(1, 'When a disciple admired the temple buildings, Jesus told him that not one stone would be left upon another.', true, 2),
    blank(2, 'And Jesus answered and said to him, "Do you see these great buildings? Not one _____ shall be left upon another, that shall not be thrown down."', 'stone', 2),
    mc(1, 'According to Jesus, what would happen to the great temple buildings the disciple admired?', ['Not one stone would be left upon another; all would be thrown down', 'They would be made a house of prayer for all the nations', 'They would stand until the Son of Man came in the clouds', 'They would be shaken like the powers in the heavens'], 2),

    // ══════════════════════════════════ v3–4 · On the Mount of Olives: the four who asked
    mc(1, 'On the Mount of Olives opposite the temple, which four disciples asked Jesus privately when these things would be?', ['Peter, James, John, and Andrew', 'Peter, Andrew, Philip, and Thomas', 'James, John, Matthew, and Thaddaeus', 'Peter, James, John, and Judas Iscariot'], 3),
    word(1, 'When Peter, James, John, and Andrew asked Jesus privately about the end, on which mount was He sitting?', 'Mount of Olives', 3, ['olives', 'mount olives', 'the mount of olives', 'olivet']),
    blank(3, 'Now as He sat on the Mount of Olives opposite the temple, Peter, James, John, and _____ asked Him privately,', 'Andrew', 3),
    tf(1, 'Peter, James, John, and Andrew questioned Jesus about the end privately while He sat on the Mount of Olives opposite the temple.', true, 3),
    mc(3, 'Where exactly was Jesus sitting when Peter, James, John, and Andrew questioned Him privately?', ['On the Mount of Olives opposite the temple', 'In the temple opposite the treasury', 'In the house of Simon the leper at Bethany', 'In a boat a little way out from the shore'], 3),
    sa(3, 'Sitting opposite the temple, what two things did Peter, James, John, and Andrew ask Jesus to tell them?', 'When these things would be, and what the sign would be when all these things would be fulfilled.', 4),
    blank(3, '"Tell us, when will these things be? And what will be the _____ when all these things will be fulfilled?"', 'sign', 4),
    tf(2, 'The four disciples asked Jesus their question about the sign openly, in front of the crowd in the temple.', false, 4, 'They asked Him privately as He sat on the Mount of Olives opposite the temple.'),

    // ══════════════════════════════════ v5–8 · Deceivers, wars, the beginnings of sorrows
    mc(1, 'What was the first warning Jesus gave when He began to answer the four disciples on the Mount of Olives?', ['"Take heed that no one deceives you"', '"Watch and pray, for you do not know when the time is"', '"Let those who are in Judea flee to the mountains"', '"Do not worry beforehand what you will speak"'], 5),
    blank(1, 'And Jesus, answering them, began to say: "Take heed that no one _____ you.', 'deceives', 5),
    sa(1, 'Jesus warned the disciples that many would come in His name. What would these people say, and what would they do?', 'They would say, "I am He," and would deceive many.', 6),
    mc(2, 'What did Jesus say the many who come in His name would claim?', ['"I am He"', '"The Christ is here"', '"The end is not yet"', '"The time is near"'], 6),
    blank(2, 'For many will come in My name, saying, \'I am He,\' and will _____ many.', 'deceive', 6),
    word(2, 'Jesus said many would come in His name saying, "I am He." What did He say they would do to many?', 'deceive', 6, ['deceive many', 'deceive them']),
    tf(2, 'Jesus said many would come in His name saying, "I am He," and would deceive many.', true, 6),
    mc(2, 'How did Jesus tell His disciples to react when they heard of wars and rumors of wars?', ['Do not be troubled, for such things must happen, but the end is not yet', 'Flee to the mountains and do not go back for anything in the house', 'Watch and pray, because the end has come and the master is at the doors', 'Take heed, for these are the signs that the Christ has come'], 7),
    blank(2, 'But when you hear of wars and rumors of wars, do not be troubled; for such things must happen, but the _____ is not yet.', 'end', 7),
    tf(1, 'Jesus told the disciples that when they heard of wars and rumors of wars, it would mean the end had come.', false, 7, 'He said, "such things must happen, but the end is not yet."'),
    sa(3, 'In Jesus’ warning on the Mount of Olives, what did He call the wars, earthquakes, famines, and troubles?', 'The beginnings of sorrows.', 8, ['beginnings of sorrows', 'the beginning of sorrows']),
    mc(3, 'Which of these did Jesus list as "the beginnings of sorrows"?', ['Nation against nation, earthquakes in various places, famines and troubles', 'The sun darkened, the moon not giving its light, the stars falling', 'Brother betraying brother and children rising up against parents', 'False christs showing signs and wonders to deceive even the elect'], 8),
    word(3, 'Jesus said nation would rise against nation, and kingdom against what?', 'kingdom', 8),

    // ══════════════════════════════════ v9–13 · Delivered up: councils, synagogues, the Holy Spirit
    mc(2, 'Jesus told His disciples they would be delivered up to councils and beaten where?', ['In the synagogues', 'In the temple courts', 'In the marketplaces', 'In the king’s hall'], 9),
    blank(3, '"But watch out for yourselves, for they will deliver you up to _____, and you will be beaten in the synagogues.', 'councils', 9),
    sa(3, 'Jesus said His disciples would be brought before rulers and kings. Why, and for what purpose?', 'For His sake, as a testimony to them.', 9, ['for My sake, for a testimony to them']),
    word(3, 'Jesus said His followers would be brought before rulers and kings for His sake, as what to them?', 'testimony', 9, ['a testimony', 'witness']),
    tf(1, 'Jesus warned that His disciples would be beaten in the synagogues.', true, 9),
    mc(1, 'What did Jesus say must first happen before the end, regarding the gospel?', ['It must first be preached to all the nations', 'It must first be written down by the disciples', 'It must first be rejected by the rulers and kings', 'It must first be preached in the synagogues of Judea'], 10),
    blank(1, 'And the gospel must first be _____ to all the nations.', 'preached', 10),
    tf(1, 'Jesus said the gospel must first be preached only in Judea before the end.', false, 10, 'He said the gospel "must first be preached to all the nations."'),
    mc(2, 'When the disciples were arrested and delivered up, what did Jesus tell them about what they should say?', ['Not to plan ahead, but to speak what was given in that hour', 'To keep silent and give no testimony before the rulers and kings', 'To repeat the words He had told them on the Mount of Olives', 'To flee to the mountains and not go back to get their clothes'], 11),
    mc(3, 'Jesus said the disciples should speak whatever was given them in the hour of arrest. What reason did He give?', ['It is not they who speak, but the Holy Spirit', 'The rulers and kings would then release them', 'It would be a testimony against the false prophets', 'The Father alone knows what they should say'], 11),
    word(1, 'When the arrested disciples spoke before their accusers, Jesus said it would not be they who spoke but whom?', 'Holy Spirit', 11, ['the holy spirit', 'spirit', 'the spirit']),
    blank(2, 'But whatever is given you in that hour, speak that; for it is not you who speak, but the _____ Spirit.', 'Holy', 11),
    tf(2, 'Jesus told the disciples to carefully prepare in advance what they would say when arrested.', false, 11, 'He said, "do not worry beforehand, or premeditate what you will speak."'),
    mc(2, 'Jesus said that in those days brother would betray brother to what?', ['Death', 'The councils', 'The synagogues', 'The rulers'], 12),
    sa(3, 'Describe how Jesus said families would turn on one another in the days of persecution.', 'Brother will betray brother to death, a father his child, and children will rise up against parents and cause them to be put to death.', 12),
    blank(3, 'Now brother will betray brother to death, and a father his _____; and children will rise up against parents and cause them to be put to death.', 'child', 12),
    tf(1, 'Jesus said children would rise up against their parents and cause them to be put to death.', true, 12),
    mc(1, 'Jesus said His disciples would be hated by all. Who did He say would be saved?', ['He who endures to the end', 'He who flees to the mountains', 'He who is found watching', 'He who speaks by the Holy Spirit'], 13),
    blank(1, 'And you will be hated by all for My name’s sake. But he who _____ to the end shall be saved.', 'endures', 13),
    word(2, 'Jesus told His disciples they would be hated by all for the sake of His what?', 'name', 13, ['my name', 'his name', 'names sake', 'name’s sake']),
    tf(2, 'Jesus said His disciples would be hated by all for His name’s sake.', true, 13),

    // ══════════════════════════════════ v14–20 · The abomination of desolation; flee to the mountains
    mc(1, 'When the "abomination of desolation" stood where it ought not, what did Jesus tell those in Judea to do?', ['Flee to the mountains', 'Go up to the housetop', 'Gather in the synagogues', 'Go out into the field'], 14),
    word(2, 'Jesus said the "abomination of desolation" had been spoken of by which prophet?', 'Daniel', 14),
    blank(2, '"So when you see the \'abomination of desolation,\' spoken of by _____ the prophet, standing where it ought not" (let the reader understand), "then let those who are in Judea flee to the mountains.', 'Daniel', 14),
    sa(3, 'What parenthetical aside does Mark insert in the middle of Jesus’ words about the abomination of desolation?', '"Let the reader understand."', 14, ['let the reader understand']),
    tf(1, 'Jesus said that when the abomination of desolation appeared, those in Judea should flee to the mountains.', true, 14),
    tf(3, 'Jesus said the "abomination of desolation" was spoken of by Isaiah the prophet.', false, 14, 'It was "spoken of by Daniel the prophet."'),
    mc(2, 'What did Jesus say the man on the housetop should do when the time came to flee?', ['Not go down into the house, nor enter to take anything out of it', 'Go down and gather his household before fleeing to the mountains', 'Go down and take his clothes and whatever he could carry', 'Stay on the housetop and watch for the master of the house'], 15),
    blank(3, 'Let him who is on the _____ not go down into the house, nor enter to take anything out of his house.', 'housetop', 15),
    tf(2, 'Jesus said the man on the housetop should go down quickly and take what he needed from his house before fleeing.', false, 15, 'He said not to go down into the house, "nor enter to take anything out of his house."'),
    mc(2, 'When the time came to flee, Jesus said the man in the field should not go back for what?', ['His clothes', 'His tools', 'His money', 'His family'], 16),
    blank(1, 'And let him who is in the _____ not go back to get his clothes.', 'field', 16),
    word(3, 'Jesus said the man working in the field should not go back to get what?', 'clothes', 16, ['his clothes', 'clothing', 'cloak', 'garment']),
    sa(3, 'In the days of fleeing, for which two groups did Jesus pronounce a "woe"?', 'Those who are pregnant and those who are nursing babies.', 17, ['pregnant women and nursing mothers']),
    blank(3, 'But woe to those who are _____ and to those who are nursing babies in those days!', 'pregnant', 17),
    mc(1, 'Jesus told the disciples to pray that their flight would not be in which season?', ['Winter', 'Summer', 'Harvest', 'Spring'], 18),
    mc(2, 'What did Jesus tell the disciples to pray concerning their flight?', ['That it may not be in winter', 'That it may not be at midnight', 'That it may not be in the morning', 'That it may be before the tribulation'], 18),
    blank(1, 'And pray that your flight may not be in _____.', 'winter', 18),
    word(1, 'Jesus told His disciples to pray their flight would not happen in what season?', 'winter', 18),
    sa(3, 'How did Jesus describe the tribulation that would come in those days?', 'Such as has not been since the beginning of the creation which God created until this time, nor ever shall be.', 19),
    mc(3, 'Jesus said the tribulation of those days would be unlike anything since when?', ['Since the beginning of the creation which God created', 'Since the days of Daniel the prophet', 'Since the temple was first built in Jerusalem', 'Since the gospel was first preached to the nations'], 19),
    blank(3, 'For in those days there will be _____, such as has not been since the beginning of the creation which God created until this time, nor ever shall be.', 'tribulation', 19),
    tf(3, 'Jesus said the tribulation of those days would be like others that had happened since the creation.', false, 19, 'It would be "such as has not been since the beginning of the creation … nor ever shall be."'),
    mc(3, 'Why did Jesus say the Lord shortened those days of tribulation?', ['For the elect’s sake, whom He chose', 'For the sake of those pregnant and nursing', 'So the gospel could be preached to all nations', 'Because the Son of Man was coming in the clouds'], 20),
    blank(3, 'And unless the Lord had shortened those days, no _____ would be saved; but for the elect’s sake, whom He chose, He shortened the days.', 'flesh', 20),
    sa(3, 'What did Jesus say would have happened if the Lord had not shortened those days?', 'No flesh would be saved.', 20, ['no flesh would have been saved', 'no one would be saved']),
    tf(2, 'Jesus said the Lord shortened the days of tribulation for the sake of the elect.', true, 20),

    // ══════════════════════════════════ v21–23 · False christs and false prophets
    mc(2, 'If anyone said, "Look, here is the Christ!" or "Look, He is there!" what did Jesus tell the disciples to do?', ['Do not believe it', 'Go and see for yourselves', 'Test them by their signs and wonders', 'Tell it to no one'], 21),
    blank(2, '"Then if anyone says to you, \'Look, here is the _____!\' or, \'Look, He is there!\' do not believe it.', 'Christ', 21),
    tf(1, 'Jesus said that if someone announced, "Look, here is the Christ!" the disciples should not believe it.', true, 21),
    mc(3, 'What did Jesus say false christs and false prophets would do?', ['Rise and show signs and wonders to deceive, if possible, even the elect', 'Deliver the disciples up to councils and beat them in synagogues', 'Come in the clouds with great power and glory', 'Betray brother to death and children their parents'], 22),
    blank(2, 'For false christs and false _____ will rise and show signs and wonders to deceive, if possible, even the elect.', 'prophets', 22),
    word(3, 'Jesus said false christs and false prophets would show signs and wonders to deceive, if possible, even whom?', 'elect', 22, ['the elect']),
    sa(3, 'After warning about false christs and false prophets, what did Jesus say He had already done for the disciples?', 'He had told them all things beforehand.', 23, ['told you all things beforehand']),
    mc(3, 'What did Jesus say immediately after warning about false christs and false prophets?', ['"But take heed; see, I have told you all things beforehand"', '"Take heed, watch and pray; for you do not know when the time is"', '"Take heed that no one deceives you"', '"And what I say to you, I say to all: Watch!"'], 23),
    blank(3, 'But take heed; see, I have told you all things _____.', 'beforehand', 23),

    // ══════════════════════════════════ v24–27 · Sun darkened; the Son of Man in the clouds
    mc(1, 'After the tribulation, what did Jesus say would happen to the sun and the moon?', ['The sun will be darkened and the moon will not give its light', 'The sun and moon will be shaken like the powers in the heavens', 'The sun and moon will fall like the stars of heaven', 'The sun and moon will pass away with heaven and earth'], 24),
    blank(1, '"But in those days, after that tribulation, the _____ will be darkened, and the moon will not give its light;', 'sun', 24),
    tf(1, 'Jesus said that after the tribulation the moon would not give its light.', true, 24),
    sa(3, 'List the four heavenly signs Jesus said would follow the tribulation, before the Son of Man is seen.', 'The sun will be darkened, the moon will not give its light, the stars of heaven will fall, and the powers in the heavens will be shaken.', 25),
    blank(2, 'the _____ of heaven will fall, and the powers in the heavens will be shaken.', 'stars', 25),
    word(3, 'Jesus said the stars of heaven would fall and what in the heavens would be shaken?', 'powers', 25, ['the powers']),
    mc(1, 'How did Jesus say they would see the Son of Man coming?', ['In the clouds with great power and glory', 'On a colt through the gates of Jerusalem', 'Walking on the sea in the fourth watch of the night', 'On a high mountain with His clothes shining white'], 26),
    blank(1, 'Then they will see the Son of Man coming in the _____ with great power and glory.', 'clouds', 26),
    word(1, 'Jesus said they would see the Son of Man coming in the clouds with great power and what?', 'glory', 26),
    mc(2, 'After the Son of Man comes in the clouds, whom did Jesus say He would send, and for what?', ['His angels, to gather His elect from the four winds', 'His disciples, to preach the gospel to all nations', 'His prophets, to show signs and wonders to the nations', 'His servants, each to his own work in the house'], 27),
    blank(3, 'And then He will send His angels, and gather together His elect from the four _____, from the farthest part of earth to the farthest part of heaven.', 'winds', 27),
    sa(3, 'From where did Jesus say the angels would gather His elect?', 'From the four winds, from the farthest part of earth to the farthest part of heaven.', 27, ['from the four winds']),
    tf(2, 'Jesus said He would send His prophets to gather together His elect from the four winds.', false, 27, 'He said, "He will send His angels, and gather together His elect from the four winds."'),

    // ══════════════════════════════════ v28–31 · The fig tree; this generation; My words
    mc(1, 'Jesus told the disciples to learn a parable from which tree?', ['The fig tree', 'The olive tree', 'The mustard plant', 'The vine'], 28),
    word(1, 'From which tree did Jesus tell the disciples to learn a parable about knowing that summer is near?', 'fig', 28, ['fig tree', 'the fig tree']),
    blank(2, '"Now learn this parable from the fig tree: When its branch has already become tender, and puts forth leaves, you know that _____ is near.', 'summer', 28),
    sa(2, 'In the parable of the fig tree, what signs show that summer is near?', 'Its branch has become tender and puts forth leaves.', 28, ['tender branch and leaves']),
    tf(1, 'In Jesus’ parable, a fig tree whose branch becomes tender and puts forth leaves shows that winter is near.', false, 28, 'It shows "that summer is near."'),
    mc(3, 'Just as tender fig branches show summer is near, what did Jesus say the disciples should know when they see these things happening?', ['That it is near—at the doors', 'That the end is not yet', 'That this generation has passed away', 'That the gospel has been preached to all nations'], 29),
    blank(3, 'So you also, when you see these things happening, know that it is near—at the _____!', 'doors', 29),
    tf(2, 'Jesus said that when the disciples saw these things happening, they should know it was near, at the doors.', true, 29),
    mc(2, 'What did Jesus say about "this generation" in relation to all these things taking place?', ['It will by no means pass away till all these things take place', 'It will be hated by all nations for His name’s sake', 'It will not know the day or the hour, nor will the angels', 'It will be gathered by the angels from the four winds'], 30),
    blank(2, 'Assuredly, I say to you, this _____ will by no means pass away till all these things take place.', 'generation', 30),
    word(3, 'Jesus solemnly said that what would by no means pass away till all these things take place?', 'generation', 30, ['this generation']),
    tf(3, 'Jesus said this generation would pass away before all these things took place.', false, 30, '"This generation will by no means pass away till all these things take place."'),
    mc(1, 'What did Jesus say would pass away, and what would by no means pass away?', ['Heaven and earth will pass away, but His words will not', 'His words will pass away, but heaven and earth will not', 'This generation will pass away, but the temple will not', 'The temple will pass away, but this generation will not'], 31),
    blank(1, 'Heaven and earth will pass away, but My _____ will by no means pass away.', 'words', 31),
    tf(1, 'Jesus said that heaven and earth would pass away, but His words would by no means pass away.', true, 31),

    // ══════════════════════════════════ v32–37 · No one knows the day or hour; watch!
    mc(1, 'According to Jesus, who alone knows the day and hour?', ['Only the Father', 'Only the Son', 'Only the angels in heaven', 'Only the elect'], 32),
    sa(3, 'Jesus said no one knows the day and hour. Whom did He specifically name as not knowing, and who does know?', 'Not even the angels in heaven, nor the Son; only the Father knows.', 32),
    blank(2, '"But of that day and hour no one knows, not even the _____ in heaven, nor the Son, but only the Father.', 'angels', 32),
    tf(1, 'Jesus said that the angels in heaven know the day and hour.', false, 32, '"No one knows, not even the angels in heaven, nor the Son, but only the Father."'),
    tf(3, 'Jesus said that even the Son does not know the day and hour.', true, 32),
    word(1, 'Jesus said that of that day and hour no one knows but only whom?', 'Father', 32, ['the father', 'god the father']),
    mc(2, 'Why did Jesus tell the disciples to take heed, watch, and pray?', ['Because they do not know when the time is', 'Because the master is coming at midnight', 'Because false christs would deceive even the elect', 'Because they would be delivered up to councils'], 33),
    blank(2, 'Take heed, watch and _____; for you do not know when the time is.', 'pray', 33),
    tf(2, 'Jesus said, "Take heed, watch and pray; for you know when the time is."', false, 33, 'He said, "for you do not know when the time is."'),
    mc(2, 'In Jesus’ illustration, what did the man going to a far country do before he left?', ['Gave authority to his servants, each his work, and commanded the doorkeeper to watch', 'Gathered his servants and told them the day and hour of his return', 'Left his house to the doorkeeper and took his servants with him', 'Planted a vineyard, set a hedge around it, and leased it to vinedressers'], 34),
    blank(2, 'It is like a man going to a far country, who left his house and gave authority to his servants, and to each his work, and commanded the _____ to watch.', 'doorkeeper', 34),
    word(2, 'In the illustration of the man going to a far country, which servant was specifically commanded to watch?', 'doorkeeper', 34, ['the doorkeeper', 'porter']),
    sa(3, 'In the illustration of the man going to a far country, what three things did he do when he left his house?', 'He gave authority to his servants, gave each his work, and commanded the doorkeeper to watch.', 34),
    tf(2, 'In Jesus’ illustration, the man going to a far country commanded his servants to sleep until he returned.', false, 34, 'He gave each servant his work and "commanded the doorkeeper to watch."'),
    mc(3, 'What four times did Jesus name when the master of the house might come?', ['Evening, midnight, rooster-crow, or morning', 'Dawn, noon, the ninth hour, or sunset', 'The first, second, third, or fourth watch', 'The Sabbath, Passover, harvest, or winter'], 35),
    blank(3, 'Watch therefore, for you do not know when the master of the house is coming—in the evening, at midnight, at the crowing of the _____, or in the morning—', 'rooster', 35),
    word(3, 'Between midnight and morning, Jesus named the crowing of which creature as a time the master might come?', 'rooster', 35, ['cock', 'the rooster', 'cockerel']),
    sa(2, 'What reason did Jesus give for why the servants must watch for the master of the house?', 'Because they do not know when the master of the house is coming.', 35),
    tf(3, 'Jesus named the crowing of the rooster as one of the times the master of the house might come.', true, 35),
    mc(2, 'What did Jesus say the servants must avoid when the master of the house comes suddenly?', ['Being found sleeping', 'Being found in the field', 'Being found on the housetop', 'Being found in the synagogue'], 36),
    blank(2, 'lest, coming suddenly, he find you _____.', 'sleeping', 36),
    word(1, 'Jesus warned that the master, coming suddenly, might find the servants doing what?', 'sleeping', 36, ['asleep']),
    mc(1, 'What was the last word of Jesus’ teaching on the Mount of Olives in Mark 13?', ['"Watch!"', '"Pray!"', '"Flee!"', '"Believe!"'], 37),
    blank(1, 'And what I say to you, I say to all: _____!"', 'Watch', 37),
    sa(3, 'Jesus had been speaking privately to four disciples. How did He close, making clear the command applied more widely?', '"And what I say to you, I say to all: Watch!"', 37, ['what I say to you I say to all watch']),
    word(1, 'Jesus closed His teaching with a single command He said applied to all. What was it?', 'Watch', 37),
    tf(2, 'Jesus said His closing command to watch was meant only for Peter, James, John, and Andrew.', false, 37, '"What I say to you, I say to all: Watch!"'),
  ],
};

export default bank;
