import { mc, blank, word, tf, type ChapterBank, sa } from './types'
const bank: ChapterBank = { book: 'Mark', chapter: 5, tag: 'quiz-v2-mark-5', rows: [
mc(1,'To whose country did Jesus and the disciples cross?',['The Gadarenes','The Judeans','The Samaritans','The Galileans'],1),blank(2,'they came to the other side of the sea, to the country of the _____.','Gadarenes',1),
sa(1,'From where did the man with an unclean spirit meet Jesus?','the tombs',2,['out of the tombs']),tf(3,'The man met Jesus before He left the boat.',false,2,'The man met Him when He had come out of the boat.'),
mc(1,'Where did the afflicted man live?',['Among the tombs','In the city','Beside the synagogue','In a fishing boat'],3),blank(2,'no one could _____ him, not even with chains','bind',3),
sa(2,'What did the man do to the chains?','pulled them apart',4,['pulled apart']),tf(1,'The man broke shackles in pieces and could not be tamed.',true,4),
mc(2,'How did the man harm himself?',['He cut himself with stones','He threw himself into the sea','He refused all food','He burned his clothing'],5),blank(1,'he was in the mountains and in the tombs, crying out and _____ himself with stones.','cutting',5),
sa(1,'What did the man do when he saw Jesus from afar?','ran and worshiped Him',6,['worshiped Him','ran to Him']),tf(3,'The man fled farther into the tombs when he saw Jesus.',false,6,'He ran to Jesus and worshiped Him.'),
mc(1,'What title did the spirit use for Jesus?',['Son of the Most High God','Son of Zebedee','Ruler of the synagogue','King of the Gadarenes'],7),blank(3,'I implore You by God that You do not _____ me.','torment',7),
sa(2,'What did Jesus command the unclean spirit to do?','come out of the man',8,['come out']),tf(1,'Jesus commanded the unclean spirit to remain in the man.',false,8,'He commanded it to come out.'),
mc(1,'What name did the spirit give?',['Legion','Beelzebub','Jairus','Boanerges'],9),blank(2,'My name is Legion; for we are _____.','many',9),
sa(2,'What did the demons beg Jesus not to do?','send them out of the country',10,['send them out of the country']),tf(3,'The demons asked to be sent far away from the country.',false,10,'They begged not to be sent out of the country.'),
mc(1,'What large herd was feeding near the mountains?',['Swine','Sheep','Cattle','Goats'],11),blank(2,'a large herd of swine was _____ there near the mountains.','feeding',11),
sa(1,'Where did the demons ask to be sent?','into the swine',12,['the swine','swine']),tf(3,'The demons asked to enter the disciples.',false,12,'They asked to enter the swine.'),
mc(3,'About how many swine rushed into the sea?',['Two thousand','Twelve hundred','Five thousand','Four hundred'],13),blank(3,'the herd ran violently down the steep place into the sea, and _____ in the sea.','drowned',13),
sa(1,'Who reported the event in the city and country?','those who fed the swine',14,['the swineherds']),tf(2,'People went out to see what had happened.',true,14),
mc(1,'How did the people find the formerly possessed man?',['Sitting, clothed, and in his right mind','Still breaking chains','Hiding among the swine','Running into the sea'],15),blank(2,'sitting and clothed and in his right _____.','mind',15),
sa(2,'What two matters did the eyewitnesses recount?','the man and the swine',16,['what happened to the man and the swine']),tf(1,'Eyewitnesses explained what happened to the possessed man.',true,16),
mc(1,'What did the people plead with Jesus to do?',['Depart from their region','Remain and teach them','Restore the swine','Enter their synagogue'],17),blank(3,'they began to plead with Him to _____ from their region.','depart',17),
sa(1,'What did the delivered man beg Jesus for?','to be with Him',18,['that he might be with Him']),tf(2,'The man asked to remain behind without Jesus.',false,18,'He begged to be with Jesus.'),
mc(2,'What mission did Jesus give the delivered man?',['Tell his friends what the Lord had done and His compassion','Follow the boat silently','Return to the tombs','Find the owners of the swine'],19),blank(1,'tell them what great things the Lord has done for you, and how He has had _____ on you.','compassion',19),
word(2,'Where did the man proclaim what Jesus had done?','Decapolis',20),tf(3,'Everyone who heard the delivered man’s report was indifferent.',false,20,'All marveled.'),
mc(1,'How did Jesus cross back to the other side?',['By boat','On foot','By chariot','On a donkey'],21),blank(2,'a great multitude gathered to Him; and He was by the _____.','sea',21),
word(1,'What was the synagogue ruler’s name?','Jairus',22),tf(3,'Jairus stood at a distance and refused to approach Jesus.',false,22,'He came and fell at Jesus’ feet.'),
mc(1,'What condition was Jairus’s daughter in?',['At the point of death','Unable to walk','Possessed by a legion','Sick with a fever'],23),blank(3,'Come and lay Your hands on her, that she may be healed, and she will _____.','live',23),
sa(2,'Who accompanied Jesus as He went with Jairus?','a great multitude',24,['the multitude']),tf(1,'The crowd thronged Jesus as He went.',true,24),
mc(1,'How long had the woman suffered a flow of blood?',['Twelve years','Forty days','Seven years','Three months'],25),blank(2,'a certain woman had a flow of blood for _____ years','twelve',25,['12']),
sa(2,'On whom had the woman spent all she had?','many physicians',26,['physicians']),tf(3,'The woman improved steadily under the physicians.',false,26,'She grew worse.'),
mc(1,'What did the woman touch in the crowd?',['Jesus’ garment','Jairus’s robe','The disciples’ boat','The synagogue door'],27),blank(2,'she came behind Him in the crowd and _____ His garment.','touched',27),
sa(1,'What did the woman believe touching Jesus’ clothes would do?','make her well',28,['she would be made well']),tf(3,'The woman believed she needed Jesus to visit her house.',false,28,'She believed touching His clothes would make her well.'),
mc(1,'What happened immediately after she touched Jesus?',['The bleeding stopped and she knew she was healed','The crowd dispersed','Jesus entered Jairus’s house','Her condition grew worse'],29),blank(3,'the fountain of her blood was dried up, and she felt in her body that she was _____','healed',29),
word(2,'What did Jesus know had gone out from Him?','power',30),tf(1,'Jesus turned and asked who had touched His clothes.',true,30),
mc(2,'Why were the disciples surprised by Jesus’ question?',['The multitude was thronging Him','No one was nearby','They had already identified the woman','Jairus had asked the same question'],31),blank(1,'You see the multitude _____ You','thronging',31),
sa(1,'Whom did Jesus look around to see?','the woman who had touched Him',32,['her who had done this thing']),tf(3,'Jesus immediately walked away without looking for her.',false,32,'He looked around to see her.'),
mc(2,'What did the woman tell Jesus?',['The whole truth','Only her name','Nothing at all','Where Jairus lived'],33),blank(3,'the woman, fearing and _____, knowing what had happened to her','trembling',33),
sa(1,'What did Jesus say had made the woman well?','her faith',34,['faith','your faith']),tf(2,'Jesus told the woman to go in peace.',true,34),
mc(1,'What news came from Jairus’s house?',['His daughter was dead','His daughter was healed','The house was empty','The mourners had left'],35),blank(2,'Your daughter is dead. Why trouble the _____ any further?','Teacher',35),
sa(1,'What did Jesus tell Jairus to do instead of fearing?','only believe',36,['believe']),tf(3,'Jesus told Jairus that hope was gone.',false,36,'He said, “Do not be afraid; only believe.”'),
mc(2,'Which three disciples were allowed to follow?',['Peter, James, and John','Andrew, Philip, and Matthew','Thomas, Thaddaeus, and Simon','James, Judas, and Bartholomew'],37),blank(1,'except Peter, James, and _____ the brother of James.','John',37),
sa(2,'What did Jesus see at the synagogue ruler’s house?','a tumult',38,['tumult']),tf(1,'People at the house were weeping and wailing loudly.',true,38),
mc(1,'How did Jesus describe the child’s condition?',['Sleeping','Hopelessly ill','Already buried','Possessed'],39),blank(3,'The child is not dead, but _____.','sleeping',39),
sa(1,'How did the mourners respond to Jesus?','they ridiculed Him',40,['ridiculed Him']),tf(2,'Jesus took the child’s parents and His companions into the room.',true,40),
mc(2,'What does “Talitha, cumi” mean?',['Little girl, I say to you, arise','Daughter, your faith has healed you','Peace, be still','Do not fear; only believe'],41),blank(3,'Little girl, I say to you, _____.','arise',41),
sa(3,'How old was the girl?','twelve years',42,['twelve','12']),tf(2,'The girl immediately arose and walked.',true,42),
mc(1,'What practical instruction did Jesus give after raising the girl?',['Give her something to eat','Take her to the priest','Tell the whole city','Bring her to the sea'],43),blank(2,'He commanded them strictly that no one should _____ it','know',43),
]};
export default bank;
