import { mc, blank, word, tf, type ChapterBank, sa } from './types'
const bank: ChapterBank = { book: 'Mark', chapter: 10, tag: 'quiz-v2-mark-10', rows: [
mc(1,'Where did Jesus teach the gathered multitudes?',['Judea beyond the Jordan','Tyre and Sidon','Bethsaida','Gennesaret'],1),
blank(2,'Is it lawful for a man to _____ his wife?','divorce',2),
word(3,'Whose command did Jesus ask the Pharisees about?','Moses',3),
tf(1,'Moses permitted a certificate of divorce.',true,4),
mc(2,'Why had Moses written the divorce precept?',['Because of their hard hearts','Because marriage was temporary','Because the disciples asked','Because children were present'],5),
blank(3,'God “made them male and _____.”','female',6),
sa(1,'Whom does a man leave to be joined to his wife?','father and mother',7),
tf(2,'Husband and wife remain two separate flesh.',false,8,'They become one flesh.'),
mc(1,'Who must not separate what God joins?',['Man','Moses','The children','The disciples'],9),
blank(2,'His disciples also asked Him again about the same _____.','matter',10),
word(3,'What does a man commit by divorcing his wife and marrying another?','adultery',11),
tf(1,'Jesus applied the adultery warning to a woman divorcing and remarrying too.',true,12),
mc(2,'Who rebuked those bringing children to Jesus?',['The disciples','The Pharisees','The scribes','The multitude'],13),
blank(3,'Let the little children come to Me, and do not _____ them','forbid',14),
sa(1,'How must God’s kingdom be received?','as a little child',15),
tf(2,'Jesus laid His hands on the children and blessed them.',true,16),
mc(1,'What did the kneeling man ask Jesus about?',['Inheriting eternal life','Receiving physical sight','Entering Jerusalem','Becoming first'],17),
blank(2,'No one is good but One, that is, _____.','God',18),
sa(3,'Name one commandment Jesus listed.','Do not commit adultery',19,['Do not murder','Do not steal','Do not bear false witness','Do not defraud','Honor your father and mother']),
tf(1,'The man said he had kept the commandments from his youth.',true,20),
mc(2,'What one thing did Jesus say the man lacked?',['Sell, give to the poor, take up the cross, and follow Him','Learn another commandment','Become a scribe','Return to his parents'],21),
blank(3,'he was sad at this word, and went away sorrowful, for he had great _____.','possessions',22),
sa(1,'Who did Jesus say finds it hard to enter God’s kingdom?','those who have riches',23,['those who trust in riches','the rich']),
tf(2,'The disciples were astonished at Jesus’ words about riches.',true,24),
mc(1,'What did Jesus say is easier than a rich man entering God’s kingdom?',['A camel going through a needle’s eye','A ship crossing the sea','A child lifting a stone','A servant becoming first'],25),
blank(2,'Who then can be _____?','saved',26),
word(3,'With whom are all things possible?','God',27),
tf(1,'Peter reminded Jesus that the disciples had left everything to follow Him.',true,28),
mc(2,'For whose sake might a follower leave family or property?',['Jesus and the gospel','The Pharisees','The Gentile rulers','Personal riches'],29),
blank(3,'who shall not receive a _____ now in this time','hundredfold',30),
sa(1,'What reversal did Jesus announce?','the first will be last and the last first',31,['first last and last first']),
tf(2,'Jesus walked behind the disciples on the road to Jerusalem.',false,32,'Jesus went before them.'),
mc(1,'To whom would the Son of Man be delivered after condemnation?',['The Gentiles','The children','The multitudes','The rich man'],33),
blank(2,'the third day He will _____ again.','rise',34),
sa(3,'Which brothers asked Jesus to grant their request?','James and John',35),
tf(1,'Jesus asked James and John what they wanted Him to do.',true,36),
mc(2,'What positions did James and John request?',['At Jesus’ right and left in glory','First and second among the scribes','Rulers over Jericho','Leaders of the Pharisees'],37),
blank(3,'Are you able to drink the _____ that I drink','cup',38),
sa(1,'What did James and John claim about the cup and baptism?','We are able',39),
tf(2,'Jesus said assigning the right and left seats was His to give freely.',false,40,'Those places were prepared for particular people.'),
mc(1,'Who became displeased with James and John?',['The other ten','The Pharisees','Bartimaeus','The children'],41),
blank(2,'their great ones exercise _____ over them.','authority',42),
sa(3,'What must a person become to be great among the disciples?','a servant',43,['your servant']),
tf(1,'Whoever desires to be first must be slave of all.',true,44),
mc(2,'Why did the Son of Man come?',['To serve and give His life as a ransom for many','To be served by Gentile rulers','To gain great possessions','To condemn Bartimaeus'],45),
blank(3,'blind Bartimaeus, the son of Timaeus, sat by the road _____.','begging',46),
word(1,'What title did Bartimaeus use for Jesus?','Son of David',47),
tf(2,'Bartimaeus became quiet when the crowd warned him.',false,48,'He cried out all the more.'),
mc(1,'What message did people bring Bartimaeus from Jesus?',['Be cheerful, rise, He is calling you','Remain seated and silent','Go to the priest','Return tomorrow'],49),
blank(2,'throwing aside his _____, he rose and came to Jesus.','garment',50),
sa(3,'What did Bartimaeus ask to receive?','his sight',51,['sight']),
tf(1,'Bartimaeus immediately received sight and followed Jesus.',true,52),

mc(3,'What did Jesus say Moses commanded at creation?',['Male and female become one flesh','Every marriage may be ended','Children should be forbidden','Riches guarantee the kingdom'],6),
sa(2,'What has God done to the married pair?','joined them together',9),
tf(3,'Jesus was pleased when the disciples stopped the children.',false,14,'He was greatly displeased.'),
mc(3,'What three actions did Jesus take toward the children?',['Took them in His arms, laid hands on them, and blessed them','Questioned, rebuked, and dismissed them','Fed, clothed, and sent them home','Baptized, taught, and appointed them'],16),
blank(1,'sell whatever you have and give to the _____','poor',21),
mc(3,'Why did the man leave sorrowfully?',['He had great possessions','He could not understand the commandments','Jesus refused to answer','The disciples rebuked him'],22),
word(2,'What did Jesus say is impossible with men but possible with God?','salvation',27,['being saved']),
tf(3,'The hundredfold promise excludes persecution.',false,30,'Jesus included persecutions.'),
mc(3,'How did the disciples react while following Jesus toward Jerusalem?',['They were amazed and afraid','They celebrated loudly','They abandoned Him','They argued with Bartimaeus'],32),
sa(2,'Name two abuses Jesus predicted from the Gentiles.','mocking and scourging',34,['mock and scourge','spitting and killing']),
mc(3,'What two images did Jesus use for His coming suffering?',['A cup and a baptism','A camel and a needle','A servant and a slave','A child and a kingdom'],38),
tf(3,'Jesus said James and John would share His cup and baptism.',true,39),
blank(1,'whoever desires to become great among you shall be your _____.','servant',43),
mc(3,'How does leadership among Jesus’ followers contrast with Gentile rule?',['Greatness means service rather than lording authority','Greatness means stronger authority','Leadership belongs only to rulers','The first should avoid serving'],44),
sa(2,'What did the Son of Man give as a ransom for many?','His life',45),
tf(3,'Bartimaeus was sitting inside Jericho’s synagogue.',false,46,'He sat by the road as Jesus left Jericho.'),
mc(3,'What did Jesus say made Bartimaeus well?',['His faith','His persistence alone','The crowd’s permission','His garment'],52),
blank(1,'Jesus, Son of David, have _____ on me!','mercy',47),
]};
export default bank;
