import { mc, blank, word, tf, type ChapterBank } from './types';
const bank: ChapterBank = { book: 'Mark', chapter: 15, tag: 'quiz-v2-mark-15', rows: [
mc(1,'To whom did the council deliver the bound Jesus?',['Pilate','Herod','The high priest','Barabbas'],1),
blank(2,'Are You the _____ of the Jews?','King',2),
word(3,'How did Jesus answer the chief priests’ many accusations?','He answered nothing',3,['nothing']),
tf(1,'Pilate pointed out the many accusations made against Jesus.',true,4),
mc(2,'What made Pilate marvel?',['Jesus still answered nothing','The crowd became quiet','Barabbas confessed','The council released Jesus'],5),
blank(3,'at the feast he was accustomed to releasing one _____','prisoner',6),
word(1,'What crime had Barabbas and his fellow rebels committed?','murder',7),
tf(2,'The multitude asked Pilate to follow his usual release custom.',true,8),
mc(1,'Whom did Pilate offer to release?',['The King of the Jews','Barabbas first','Simon of Cyrene','The centurion'],9),
blank(2,'the chief priests had handed Him over because of _____.','envy',10),
word(3,'Whom did the chief priests persuade the crowd to request?','Barabbas',11),
tf(1,'Pilate asked what to do with the one called King of the Jews.',true,12),
mc(2,'What did the crowd demand?',['Crucify Him','Release Him','Send Him to Herod','Scourge Barabbas'],13),
blank(3,'Why, what _____ has He done?','evil',14),
word(1,'Why did Pilate release Barabbas?','to gratify the crowd',15),
tf(2,'Pilate scourged Jesus before delivering Him for crucifixion.',true,15),
mc(1,'What was the soldiers’ hall called?',['Praetorium','Golgotha','Gethsemane','The council chamber'],16),
blank(2,'they clothed Him with _____','purple',17),
word(3,'How did the soldiers salute Jesus?','Hail, King of the Jews',18),
tf(1,'The soldiers struck Jesus with a reed and spat on Him.',true,19),
mc(2,'What did the soldiers put back on Jesus after mocking Him?',['His own clothes','The purple robe','Fine linen','A priestly garment'],20),
blank(3,'Simon a Cyrenian, the father of Alexander and _____','Rufus',21),
word(1,'What does Golgotha mean?','Place of a Skull',22),
tf(2,'Jesus accepted the wine mingled with myrrh.',false,23,'He did not take it.'),
mc(1,'How did the soldiers decide who received Jesus’ garments?',['By casting lots','By rank','By Pilate’s order','By tearing them evenly'],24),
blank(1,'it was the _____ hour, and they crucified Him.','third',25,['3rd']),
word(3,'What accusation was written above Jesus?','The King of the Jews',26),
tf(1,'Two robbers were crucified on Jesus’ right and left.',true,27),
mc(2,'What Scripture was fulfilled by the crucifixion with criminals?',['He was numbered with transgressors','The stone became the cornerstone','The Shepherd struck the sheep','The house became a den'],28),
blank(3,'You who destroy the temple and build it in _____ days','three',29,['3']),
word(1,'What did passersby challenge Jesus to do?','come down from the cross',30,['save Himself and come down']),
tf(2,'The chief priests mocked that Jesus saved others but could not save Himself.',true,31),
mc(1,'What did the mockers demand as proof for belief?',['That Christ descend from the cross','That Pilate release Barabbas','That Elijah appear','That darkness end'],32),
blank(2,'there was darkness over the whole land until the _____ hour.','ninth',33,['9th']),
word(3,'What does “Eloi, Eloi, lama sabachthani” mean?','My God, My God, why have You forsaken Me?',34,['My God why have You forsaken Me']),
tf(1,'Some bystanders thought Jesus was calling Elijah.',true,35),
mc(2,'What drink was offered to Jesus on a sponge?',['Sour wine','Water','Wine with myrrh','Milk'],36),
blank(3,'Jesus cried out with a loud voice, and breathed His _____.','last',37),
word(1,'How was the temple veil torn?','in two from top to bottom',38,['from top to bottom']),
tf(2,'The centurion declared Jesus to be the Son of God.',true,39),
mc(1,'Which women are named watching from afar?',['Mary Magdalene, Mary mother of James and Joses, and Salome','Martha, Mary of Bethany, and Joanna','Herodias and her daughter','Only Mary Magdalene'],40),
blank(2,'who also followed Him and _____ to Him when He was in Galilee','ministered',41),
word(3,'What was Preparation Day?','the day before the Sabbath',42),
tf(1,'Joseph of Arimathea was waiting for God’s kingdom.',true,43),
mc(2,'Why did Pilate summon the centurion?',['To confirm Jesus had been dead for some time','To arrest Joseph','To release Barabbas','To tear the veil'],44),
blank(3,'he granted the body to _____.','Joseph',45),
word(1,'What did Joseph roll against the tomb entrance?','a stone',46),
tf(2,'Mary Magdalene and Mary mother of Joses saw where Jesus was laid.',true,47),

mc(3,'Who participated in the morning consultation?',['Chief priests, elders, scribes, and the whole council','Only Pilate and Barabbas','The women from Galilee','Simon and his sons'],1),
word(2,'What did Jesus answer when Pilate asked if He was King of the Jews?','It is as you say',2),
tf(3,'Pilate believed Jesus had been handed over out of righteous concern.',false,10,'He knew envy motivated the chief priests.'),
mc(3,'What three actions did the soldiers take with the purple robe and crown?',['Clothed Him, crowned Him with thorns, and mocked His kingship','Released Him, fed Him, and honored Him','Blindfolded Pilate and crowned Barabbas','Wrapped Him in linen and buried Him'],17),
word(2,'Who carried Jesus’ cross?','Simon of Cyrene',21,['Simon a Cyrenian']),
tf(3,'The inscription above Jesus named Him King of Israel.',false,26,'It read “THE KING OF THE JEWS.”'),
mc(3,'How long did darkness cover the land?',['From the sixth hour to the ninth','From the third hour to the sixth','From morning until the third hour','From the ninth hour until evening'],33),
word(2,'What did someone hope to see after offering sour wine?','whether Elijah would take Jesus down',36,['Elijah come to take Him down']),
tf(3,'The temple veil tore from bottom to top.',false,38,'It tore from top to bottom.'),
mc(3,'What prompted the centurion’s confession?',['Seeing how Jesus cried out and died','Seeing the empty tomb','Hearing Pilate’s verdict','Watching Simon carry the cross'],39),
word(2,'What position did Joseph of Arimathea hold?','prominent council member',43),
mc(3,'How did Joseph prepare Jesus’ body and tomb?',['Wrapped Him in fine linen, laid Him in a rock-hewn tomb, and rolled a stone over it','Anointed Him with myrrh and returned Him to Pilate','Placed Him in the temple behind the veil','Buried Him in an unmarked field'],46),
]};
export default bank;
