import { mc, blank, word, tf, type ChapterBank, sa } from './types'
const bank: ChapterBank = { book: 'Mark', chapter: 6, tag: 'quiz-v2-mark-6', rows: [
mc(1,'Who followed Jesus to His own country?',['His disciples','The Pharisees','Herod’s officers','John’s disciples'],1),
blank(2,'when the Sabbath had come, He began to teach in the _____.','synagogue',2),
word(3,'What occupation did the people identify Jesus with?','carpenter',3,['the carpenter']),
tf(1,'Jesus said a prophet can lack honor in his own country, family, and house.',true,4),
mc(2,'What mighty works did Jesus do there?',['He healed a few sick people','He fed five thousand','He calmed a storm','He raised Jairus’s daughter'],5),
blank(3,'He marveled because of their _____.','unbelief',6),
sa(1,'How did Jesus send out the Twelve?','two by two',7),
tf(2,'The Twelve were told to take a bag, bread, and copper.',false,8,'They were to take none of those, only a staff.'),
mc(1,'What footwear were the Twelve told to wear?',['Sandals','Boots','No shoes','Priestly slippers'],9),
blank(2,'stay there till you _____ from that place.','depart',10),
sa(3,'What were the disciples to shake off when rejected?','the dust under their feet',11,['dust']),
tf(1,'The Twelve preached that people should repent.',true,12),
mc(2,'What did the Twelve use when ministering to many sick people?',['Oil','Water','Wine','Clay'],13),
blank(3,'John the Baptist is _____ from the dead','risen',14),
word(1,'Whom did some people think Jesus was?','Elijah',15,['the Prophet','one of the prophets']),
tf(2,'Herod thought John, whom he had beheaded, had risen.',true,16),
mc(1,'Why had Herod imprisoned John?',['Because of Herodias, his brother Philip’s wife','Because John refused to heal him','Because John supported the Pharisees','Because John entered the palace'],17),
blank(2,'It is not _____ for you to have your brother’s wife.','lawful',18),
word(3,'Who wanted to kill John but could not?','Herodias',19),
tf(1,'Herod knew John was a just and holy man and protected him.',true,20),
mc(2,'For whom did Herod give his birthday feast?',['Nobles, high officers, and Galilee’s chief men','The Twelve and the multitudes','Only Herodias and her daughter','The priests of Jerusalem'],21),
blank(3,'Ask me whatever you want, and I will _____ it to you.','give',22),
word(1,'How much of his kingdom did Herod offer?','half',23,['up to half','half his kingdom']),
tf(2,'Herodias told her daughter to request John the Baptist’s release.',false,24,'She told her to ask for John’s head.'),
mc(1,'How did the girl want John’s head delivered?',['At once on a platter','In a sealed box','After the feast in a tomb','To her mother in prison'],25),
blank(2,'the king was exceedingly _____','sorry',26),
sa(3,'Whom did Herod send to behead John?','an executioner',27,['executioner']),
tf(1,'The girl gave John’s head to her mother.',true,28),
mc(2,'What did John’s disciples do with his body?',['Laid it in a tomb','Buried it at sea','Brought it to Herod','Burned it'],29),
blank(3,'the apostles gathered to Jesus and told Him _____ things','all',30),
sa(1,'Where did Jesus invite the apostles to rest?','a deserted place',31),
tf(2,'The apostles departed to the deserted place by boat.',true,32),
mc(1,'How did the multitudes reach the destination ahead of the boat?',['They ran on foot from the cities','They sailed in larger boats','They crossed through the sea','Herod transported them'],33),
blank(2,'they were like sheep not having a _____.','shepherd',34),
sa(3,'What did the disciples say about the hour?','it was late',35,['the hour is late']),
tf(1,'The disciples wanted the multitude sent away to buy bread.',true,36),
mc(2,'How much bread did the disciples mention buying?',['Two hundred denarii worth','Thirty denarii worth','Five hundred denarii worth','Twelve denarii worth'],37),
blank(3,'Five, and two _____.','fish',38),
sa(1,'Where did Jesus have everyone sit?','on the green grass',39,['green grass']),
tf(2,'The people sat in ranks of hundreds and fifties.',true,40),
mc(1,'What did Jesus do before breaking the loaves?',['Looked to heaven and blessed','Sent the multitude away','Counted every person','Entered a synagogue'],41),
blank(2,'So they all ate and were _____.','filled',42),
word(3,'How many baskets of fragments were collected?','twelve',43,['12']),
tf(1,'About five thousand men ate the loaves.',true,44),
mc(2,'Where were the disciples sent ahead by boat?',['Bethsaida','Gennesaret','Nazareth','Jerusalem'],45),
blank(3,'He departed to the mountain to _____.','pray',46),
sa(1,'Where was the boat when evening came?','in the middle of the sea',47,['middle of the sea']),
tf(2,'Jesus approached during the fourth watch, walking on the sea.',true,48),
mc(1,'What did the disciples suppose Jesus was?',['A ghost','A fisherman','An angel','John the Baptist'],49),
blank(2,'Be of good cheer! It is I; do not be _____.','afraid',50),
sa(3,'What happened to the wind when Jesus entered the boat?','it ceased',51,['ceased','the wind ceased']),
tf(1,'The disciples had fully understood the lesson of the loaves.',false,52,'They had not understood, because their heart was hardened.'),
mc(2,'Where did Jesus and the disciples anchor after crossing?',['Gennesaret','Bethsaida','Decapolis','Capernaum'],53),
blank(3,'immediately the people _____ Him','recognized',54),
word(1,'On what were sick people carried?','beds',55),
tf(2,'As many as touched the hem of Jesus’ garment were made well.',true,56),

mc(2,'Which relatives did the people name as Jesus’ brothers?',['James, Joses, Judas, and Simon','Peter, Andrew, James, and John','Philip, Thomas, Matthew, and Thaddaeus','Herod, Philip, John, and Simon'],3),
sa(2,'What authority did Jesus give the Twelve?','power over unclean spirits',7),
mc(3,'What single journey item were the Twelve permitted to take?',['A staff','A bag','Bread','Copper'],8),
tf(3,'A rejecting city would face a judgment more tolerable than Sodom and Gomorrah.',false,11,'It would be less tolerable for that city than for Sodom and Gomorrah.'),
sa(2,'What two works did the Twelve do besides preaching?', 'cast out demons and healed the sick',13,['cast out demons and healed']),
mc(3,'What explanations did people offer for Jesus’ identity?',['John raised, Elijah, or a prophet','David, Solomon, or Moses','A scribe, priest, or tax collector','Herod, Philip, or Caesar'],15),
tf(3,'Herod imprisoned John because John approved Herod’s marriage.',false,18,'John said the marriage was unlawful.'),
word(2,'How did Herod listen to John?', 'gladly',20),
mc(3,'Why did Herod grant the girl’s request despite sorrow?',['Because of his oaths and dinner guests','Because John confessed guilt','Because the crowd demanded it','Because the executioner advised it'],26),
blank(1,'they did not even have time to _____.','eat',31),
mc(3,'Why was Jesus moved with compassion for the multitude?',['They were like sheep without a shepherd','They had brought no boats','They feared King Herod','They had rejected the apostles'],34),
tf(3,'Jesus agreed that the disciples should immediately send the crowd away.',false,37,'He told the disciples to give them something to eat.'),
sa(2,'How many loaves and fish were available?', 'five loaves and two fish',38),
mc(3,'Who distributed the broken loaves to the people?',['The disciples','Herod’s officers','The synagogue rulers','John’s disciples'],41),
blank(1,'they took up _____ baskets full of fragments and of the fish.','twelve',43,['12']),
tf(3,'Jesus remained with the disciples after sending the multitude away.',false,46,'He went to the mountain to pray.'),
mc(3,'Why were the disciples straining at the oars?', ['The wind was against them','The boat was overloaded with bread','They had lost every oar','The multitude followed them'],48),
sa(2,'What two things did Jesus tell the frightened disciples?', 'be of good cheer and do not be afraid',50),
blank(1,'their heart was _____.','hardened',52),
mc(3,'Where did people lay the sick in villages and cities?',['In the marketplaces','In the synagogues only','At the seashore','Inside Herod’s palace'],56),
]};
export default bank;
