import { mc, blank, word, tf, type ChapterBank } from './types';
const bank: ChapterBank = { book: 'Mark', chapter: 12, tag: 'quiz-v2-mark-12', rows: [
mc(1,'To whom did the owner lease his vineyard?',['Vinedressers','Pharisees','Shepherds','Fishermen'],1),
blank(2,'at vintage-time he sent a _____ to the vinedressers','servant',2),
word(3,'How did the tenants send the first servant away?','empty-handed',3),
tf(1,'The second servant was stoned and wounded in the head.',true,4),
mc(2,'What happened to another servant sent by the owner?',['The tenants killed him','They paid him fruit','They made him heir','They sent him unharmed'],5),
blank(3,'still having one son, his _____, he also sent him to them last','beloved',6),
word(1,'Why did the tenants decide to kill the son?','to take the inheritance',7,['the inheritance would be theirs']),
tf(2,'The tenants killed the son and cast him outside the vineyard.',true,8),
mc(1,'What would the vineyard owner do?',['Destroy the tenants and give the vineyard to others','Abandon the vineyard','Make the tenants heirs','Send no one else'],9),
blank(2,'The stone which the builders rejected Has become the chief _____.','cornerstone',10),
word(3,'Whose doing was the rejected stone’s exaltation?','the Lord’s',11,['the Lord']),
tf(1,'The leaders understood that the parable was directed against them.',true,12),
mc(2,'Who was sent to trap Jesus in His words?',['Pharisees and Herodians','Sadducees and disciples','Scribes and widows','Vinedressers'],13),
blank(3,'Is it lawful to pay _____ to Caesar, or not?','taxes',14),
word(1,'What coin did Jesus request?','a denarius',15,['denarius']),
tf(2,'The coin bore God’s image and inscription.',false,16,'They answered that it was Caesar’s.'),
mc(1,'What did Jesus say should be rendered to God?',['The things that are God’s','Caesar’s taxes only','Nothing material or spiritual','The denarius alone'],17),
blank(2,'some Sadducees, who say there is no _____','resurrection',18),
word(3,'What did Moses say a surviving brother should raise up?','offspring for his brother',19,['offspring']),
tf(1,'The first brother died without offspring.',true,20),
mc(2,'What happened when the second and third brothers married the woman?',['They also died without offspring','They each had a son','They divorced her','They became priests'],21),
blank(3,'So the _____ had her and left no offspring.','seven',22,['7']),
word(1,'What question did the Sadducees ask about the resurrection?','whose wife she would be',23,['whose wife will she be']),
tf(2,'Jesus said their mistake came from knowing Scripture and God’s power too well.',false,24,'They knew neither the Scriptures nor God’s power.'),
mc(1,'What are resurrected people like regarding marriage?',['Angels in heaven','The seven brothers on earth','Vinedressers','Temple scribes'],25),
blank(2,'I am the God of Abraham, the God of Isaac, and the God of _____.','Jacob',26),
word(3,'Of whom is God the God?','the living',27),
tf(1,'A scribe asked Jesus for the first commandment.',true,28),
mc(2,'What truth begins the first commandment?',['The Lord our God is one','The dead do not rise','Caesar owns everything','David is the Christ'],29),
blank(3,'love the Lord your God with all your heart, with all your _____','soul',30),
word(1,'Whom does the second commandment say to love?','your neighbor',31,['neighbor']),
tf(2,'The scribe disagreed that God is one.',false,32,'He affirmed that there is one God and no other.'),
mc(1,'What did the scribe say love surpasses?',['All burnt offerings and sacrifices','The commandments','The resurrection','Prayer and fasting'],33),
blank(2,'You are not _____ from the kingdom of God.','far',34),
word(3,'Whose son did the scribes say the Christ is?','David’s',35,['David','the Son of David']),
tf(1,'David spoke by the Holy Spirit about the Lord seated at God’s right hand.',true,36),
mc(2,'How did the common people hear Jesus?',['Gladly','With anger','In silence only','With ridicule'],37),
blank(3,'Beware of the scribes, who desire to go around in long _____.','robes',38),
word(1,'What seats did the scribes love in synagogues?','the best seats',39),
tf(2,'Jesus said pretentious long prayers would protect scribes from judgment.',false,40,'Such scribes would receive greater condemnation.'),
mc(1,'Where was Jesus sitting while observing offerings?',['Opposite the treasury','At the city gate','On the Mount of Olives','In a vineyard'],41),
blank(2,'one poor widow came and threw in two _____','mites',42),
word(3,'Who did Jesus call before speaking about the widow?','His disciples',43),
tf(1,'The widow gave all she had, her whole livelihood.',true,44),

mc(3,'What structures did the vineyard owner prepare?',['A hedge, wine vat, and tower','A synagogue, treasury, and gate','A house, boat, and road','A well, palace, and wall'],1),
word(2,'Whom did the owner send last?','his beloved son',6),
tf(3,'The tenants respected the heir as the owner expected.',false,7,'They plotted to kill him.'),
mc(3,'Why did the leaders not seize Jesus?',['They feared the multitude','They agreed with the parable','They lacked authority','They feared Caesar'],12),
word(2,'What did Jesus recognize behind the tax question?','hypocrisy',15,['their hypocrisy']),
mc(3,'What balanced instruction answered the tax trap?',['Render Caesar’s things to Caesar and God’s things to God','Pay no taxes at all','Give everything to Caesar','Use no coins'],17),
tf(3,'The Sadducees believed in resurrection.',false,18,'They said there is no resurrection.'),
mc(3,'Why were the Sadducees’ marriage assumptions mistaken?',['The risen do not marry and are like angels','Only the first brother rises','The woman does not rise','Moses forbade marriage'],25),
word(2,'Which passage did Jesus cite to show that the dead rise?','the burning bush passage',26),
blank(1,'He is not the God of the dead, but the God of the _____.','living',27),
mc(3,'What four dimensions of love for God are named?',['Heart, soul, mind, and strength','Body, wealth, land, and family','Prayer, fasting, sacrifice, and offerings','Wisdom, honor, power, and riches'],30),
word(2,'What did Jesus say after the scribe answered wisely?','You are not far from the kingdom of God',34),
tf(3,'After Jesus’ answer, many people dared to challenge Him further.',false,34,'No one dared question Him.'),
mc(3,'What contradiction did Jesus raise about David and the Christ?',['David calls Him Lord though He is David’s Son','David rejected the cornerstone','David denied resurrection','David paid Caesar’s tax'],37),
word(2,'Whose houses did the condemned scribes devour?','widows’ houses',40),
mc(3,'Why did the widow give more than the rich?',['She gave all her livelihood from poverty','Her coins had greater monetary value','She owned the treasury','The rich gave nothing'],44),
]};
export default bank;
