import { mc, blank, word, tf, type ChapterBank, sa } from './types'
const bank: ChapterBank = { book: 'Mark', chapter: 9, tag: 'quiz-v2-mark-9', rows: [
mc(1,'What would some standing with Jesus see before tasting death?',['God’s kingdom present with power','The temple rebuilt','Elijah die','The Roman kingdom fall'],1),
blank(2,'after six days Jesus took Peter, James, and _____','John',2),
sa(3,'How did Jesus’ clothes appear?','shining and exceedingly white',3,['exceedingly white','shining']),
tf(1,'Moses and Elijah appeared and spoke with Jesus.',true,4),
mc(2,'What did Peter propose building?',['Three tabernacles','A synagogue','One altar','A city'],5),
blank(3,'he did not know what to say, for they were greatly _____.','afraid',6),
sa(1,'What command came from the cloud concerning the beloved Son?','Hear Him',7),
tf(2,'After the cloud, the disciples saw Moses and Elijah still standing there.',false,8,'They saw only Jesus with themselves.'),
mc(1,'Until what event were they to keep the vision secret?',['The Son of Man’s resurrection','Their return to Galilee','Elijah’s arrival','The next Sabbath'],9),
blank(2,'questioning what the rising from the _____ meant.','dead',10),
word(3,'Who did the scribes say must come first?','Elijah',11),
tf(1,'Jesus said the Son of Man must suffer and be treated with contempt.',true,12),
mc(2,'What had people done to the Elijah who had come?',['Whatever they wished','Made him king','Built him a tabernacle','Sent him to Rome'],13),
blank(3,'He saw a great multitude around them, and scribes _____ with them.','disputing',14),
sa(1,'How did the crowd respond when they saw Jesus?','they ran to greet Him',15,['greeted Him']),
tf(2,'Jesus asked the scribes what they were discussing.',true,16),
mc(1,'What kind of spirit afflicted the man’s son?',['A mute spirit','A spirit of blindness','A spirit of fever','No spirit'],17),
blank(2,'he foams at the mouth, gnashes his teeth, and becomes _____.','rigid',18),
word(3,'What did Jesus call the generation?','faithless',19,['faithless generation']),
tf(1,'The spirit convulsed the boy when he was brought to Jesus.',true,20),
mc(2,'How long had the affliction troubled the boy?',['From childhood','Three days','Twelve years','Since that morning'],21),
blank(3,'he has thrown him both into the fire and into the water to _____ him.','destroy',22),
sa(1,'To whom are all things possible?','the one who believes',23,['him who believes']),
tf(2,'The father said, “Lord, I believe; help my unbelief!”',true,24),
mc(1,'What did Jesus command the deaf and dumb spirit?',['Come out and never enter again','Be quiet until evening','Return to the fire','Speak through the boy'],25),
blank(2,'he became as one dead, so that many said, “He is _____.”','dead',26),
sa(3,'How did Jesus help the boy arise?','He took him by the hand',27,['took him by the hand']),
tf(1,'The disciples asked publicly why they had failed.',false,28,'They asked Jesus privately in the house.'),
mc(2,'What did Jesus say was required for this kind to come out?',['Prayer and fasting','Oil and bread','A public sign','A trip to Jerusalem'],29),
blank(3,'they departed from there and passed through _____','Galilee',30),
sa(1,'On what day did Jesus say He would rise?','the third day',31,['third day','3rd day']),
tf(2,'The disciples understood the prediction and questioned Jesus boldly.',false,32,'They did not understand and were afraid to ask.'),
mc(1,'Where did Jesus ask what the disciples had disputed about?',['In a house at Capernaum','On the mountain','In Jerusalem’s temple','At Bethsaida'],33),
blank(2,'they had disputed among themselves who would be the _____.','greatest',34),
sa(3,'What must one become to be first?','last of all and servant of all',35,['servant of all','last of all']),
tf(1,'Jesus placed a little child among the disciples.',true,36),
mc(2,'Whom does a person receive by welcoming a child in Jesus’ name?',['Jesus and the One who sent Him','Only the child’s parents','Moses and Elijah','The Twelve only'],37),
blank(3,'we saw someone who does not follow us casting out _____ in Your name','demons',38),
sa(1,'What did Jesus tell John regarding the outsider?','Do not forbid him',39),
tf(2,'Jesus said whoever is not against them is on their side.',true,40),
mc(1,'What small act done in Christ’s name will not lose its reward?',['Giving a cup of water','Building three tabernacles','Giving five loaves','Lighting a lamp'],41),
blank(2,'if a _____ were hung around his neck, and he were thrown into the sea.','millstone',42),
sa(3,'What did Jesus say to do if a hand causes sin?','cut it off',43),
tf(1,'The fire described in the quotation is quenched.',false,44,'The fire is not quenched.'),
mc(2,'What did Jesus say to do if a foot causes sin?',['Cut it off','Wash it','Hide it','Anoint it'],45),
blank(3,'Their worm does not _____, And the fire is not quenched.','die',46),
sa(1,'What should be plucked out if it causes sin?','the eye',47,['eye']),
tf(2,'The repeated warning says the worm does not die and the fire is not quenched.',true,48),
mc(1,'With what will every sacrifice be seasoned?',['Salt','Oil','Water','Bread'],49),
blank(2,'Have salt in yourselves, and have _____ with one another.','peace',50),

mc(3,'Where did Jesus take Peter, James, and John?',['Up a high mountain apart','Into a crowded synagogue','Across the sea','To Herod’s palace'],2),
word(2,'Who suggested a tabernacle for Jesus, Moses, and Elijah?','Peter',5),
tf(3,'The voice from the cloud called Jesus the beloved Son and commanded them to hear Him.',true,7),
mc(3,'What two things were written concerning the Son of Man?',['He would suffer many things and be treated with contempt','He would avoid suffering and rule immediately','He would remain on the mountain','He would build three tabernacles'],12),
sa(2,'What had the disciples been unable to do for the boy?','cast out the spirit',18,['cast it out']),
mc(3,'Where had the spirit often thrown the boy?',['Into fire and water','Into tombs and mountains','Into boats and houses','Into grainfields'],22),
blank(1,'Lord, I believe; help my _____!','unbelief',24),
tf(3,'Jesus allowed the spirit to return after the boy recovered.',false,25,'He commanded it to enter him no more.'),
mc(3,'What did many conclude when the spirit left the boy?',['That he was dead','That he was asleep','That he was pretending','That he was healed by the disciples'],26),
sa(2,'What private question did the disciples ask Jesus?','Why could we not cast it out?',28,['why they could not cast it out']),
mc(3,'What sequence did Jesus predict?',['Betrayal, death, and resurrection on the third day','Coronation, exile, and return','Teaching, sailing, and fasting','Healing, imprisonment, and release'],31),
tf(3,'The disciples openly admitted arguing about greatness.',false,34,'They kept silent.'),
blank(1,'he shall be last of all and _____ of all.','servant',35),
sa(2,'Who had forbidden an outsider from casting out demons?','John and the disciples',38,['John']),
mc(3,'Why should the outsider not be forbidden?',['One doing a miracle in Jesus’ name cannot soon speak evil of Him','Only the Twelve could stop him','He had joined the Twelve','He was Elijah'],39),
tf(3,'Causing a believing little one to stumble is treated as a minor matter.',false,42,'Jesus said drowning with a millstone would be better.'),
mc(3,'What comparison does Jesus make about a sinful hand?',['Life maimed is better than two hands in unquenchable fire','Two hands are always worth any cost','A hand cannot cause sin','Only the foot should be removed'],43),
word(2,'Where is it better to enter lame than to be cast into hell?', 'life',45),
mc(3,'Where is it better to enter with one eye?', ['The kingdom of God','The synagogue','Capernaum','The high mountain'],47),
tf(3,'Jesus concluded by telling the disciples to have salt in themselves and peace with one another.',true,50),
]};
export default bank;
