import { mc, blank, word, tf, type ChapterBank, sa } from './types'
const bank: ChapterBank = { book: 'Mark', chapter: 3, tag: 'quiz-v2-mark-3', rows: [
mc(1,'What disability did the man in the synagogue have?',['A withered hand','Blindness','Leprosy','A fever'],1),blank(2,'a man was there who had a _____ hand.','withered',1),
sa(2,'Why did they watch Jesus closely on the Sabbath?','to accuse Him',2,['so they might accuse Him']),tf(3,'They watched to see whether Jesus would heal on the Sabbath.',true,2),
mc(1,'What did Jesus tell the man with the withered hand?',['Step forward','Leave the synagogue','Wash in the Jordan','Go home'],3),blank(2,'He said to the man who had the withered hand, “Step _____.”','forward',3),
sa(2,'What two alternatives did Jesus give besides doing good or evil?','to save life or to kill',4,['save life or kill']),tf(1,'Those questioned by Jesus answered Him immediately.',false,4,'They kept silent.'),
mc(1,'What grieved Jesus about those watching Him?',['The hardness of their hearts','Their physical sickness','Their absence from worship','Their lack of food'],5),blank(3,'he stretched it out, and his hand was restored as _____ as the other.','whole',5),
sa(1,'With whom did the Pharisees plot against Jesus?','the Herodians',6,['Herodians']),tf(2,'The Pharisees and Herodians plotted how they might destroy Jesus.',true,6),
mc(1,'Where did Jesus withdraw with His disciples?',['To the sea','To Jerusalem','To a synagogue','To the wilderness'],7),blank(2,'a great multitude from Galilee _____ Him','followed',7),
word(3,'Name one coastal city whose people came to Jesus.','Tyre',8,['Sidon']),tf(1,'People came from Jerusalem, Idumea, beyond the Jordan, Tyre, and Sidon.',true,8),
mc(2,'Why did Jesus have a small boat kept ready?',['So the multitude would not crush Him','To cross immediately to Jerusalem','To teach His disciples to fish','To escape the Herodians alone'],9),blank(1,'a small boat should be kept _____ for Him because of the multitude','ready',9),
sa(1,'What did afflicted people press around Jesus to do?','touch Him',10,['to touch Him']),tf(3,'People with afflictions kept their distance from Jesus.',false,10,'They pressed around Him to touch Him.'),
mc(1,'What did the unclean spirits call Jesus?',['The Son of God','The son of Zebedee','The ruler of demons','A scribe'],11),blank(2,'You are the _____ of God.','Son',11),
word(2,'How did Jesus warn the unclean spirits?','sternly',12),tf(1,'Jesus permitted the spirits to make Him widely known.',false,12,'He warned them not to make Him known.'),
mc(1,'Whom did Jesus call on the mountain?',['Those He Himself wanted','Only the scribes','The Herodians','His relatives'],13),blank(3,'He went up on the mountain and _____ to Him those He Himself wanted.','called',13),
word(1,'How many did Jesus appoint?','twelve',14,['12']),tf(2,'The Twelve were appointed to be with Jesus and be sent to preach.',true,14),
mc(2,'What authority did the Twelve receive?',['To heal sicknesses and cast out demons','To collect taxes and judge disputes','To command Roman soldiers','To appoint high priests'],15),blank(1,'to have power to heal sicknesses and to cast out _____.','demons',15),
word(1,'What name did Jesus give Simon?','Peter',16),tf(3,'Jesus renamed Simon “Boanerges.”',false,16,'Jesus gave Simon the name Peter.'),
mc(3,'What does Boanerges mean?',['Sons of Thunder','Fishers of Men','Sons of God','Men of Galilee'],17),blank(3,'He gave the name Boanerges, that is, “Sons of _____”','Thunder',17),
word(3,'Which Simon is named among the Twelve in this list?','Simon the Cananite',18,['the Cananite']),tf(1,'Thomas and Thaddaeus were among the Twelve.',true,18),
mc(1,'Which disciple later betrayed Jesus?',['Judas Iscariot','Andrew','Bartholomew','James son of Alphaeus'],19),blank(2,'Judas Iscariot, who also _____ Him.','betrayed',19),
sa(2,'What could Jesus and those with Him not even do because of the crowd?','eat bread',20,['eat']),tf(3,'The gathering multitude left them ample time to eat.',false,20,'They could not so much as eat bread.'),
mc(2,'What did Jesus’ own people say about Him?',['He is out of His mind','He has Beelzebub','He is the Son of God','He is a prophet'],21),blank(1,'they went out to lay _____ of Him','hold',21),
word(1,'From where did the accusing scribes come?','Jerusalem',22),tf(3,'The scribes claimed Jesus cast out demons by the ruler of demons.',true,22),
mc(1,'What question began Jesus’ answer to the scribes?',['How can Satan cast out Satan?','Who is My mother?','Is it lawful to heal?','Why do you fast?'],23),blank(2,'How can Satan cast out _____?','Satan',23),
sa(2,'What cannot stand if divided against itself?','a kingdom',24,['kingdom']),tf(1,'A divided kingdom can continue standing securely.',false,24,'A kingdom divided against itself cannot stand.'),
mc(1,'What second divided structure did Jesus mention?',['A house','A synagogue','A city wall','A boat'],25),blank(3,'if a house is divided against itself, that house cannot _____.','stand',25),
sa(2,'What happens to Satan if he rises against himself and is divided?','he has an end',26,['has an end','he cannot stand']),tf(1,'Jesus said a divided Satan cannot stand.',true,26),
mc(2,'What must happen before someone can plunder a strong man’s house?',['The strong man must first be bound','The door must be left open','The goods must be counted','The house must be divided'],27),blank(1,'unless he first _____ the strong man.','binds',27),
sa(1,'What did Jesus say would be forgiven the sons of men?','all sins',28,['sins and blasphemies','all sins and whatever blasphemies they utter']),tf(3,'Jesus said no sins or blasphemies could be forgiven.',false,28,'He said all sins and uttered blasphemies would be forgiven.'),
mc(2,'What sin did Jesus say never has forgiveness?',['Blasphemy against the Holy Spirit','Eating with sinners','Healing on the Sabbath','Failing to fast'],29),blank(3,'is subject to eternal _____.','condemnation',29),
sa(1,'What accusation prompted Jesus’ warning about blasphemy?','He has an unclean spirit',30),tf(2,'The warning followed their claim that Jesus had an unclean spirit.',true,30),
mc(1,'Who came and stood outside calling for Jesus?',['His mother and brothers','The Twelve alone','The scribes and Pharisees','The Herodians'],31),blank(2,'standing outside they sent to Him, _____ Him.','calling',31),
sa(1,'Who was sitting around Jesus?','a multitude',32,['the multitude']),tf(3,'Jesus’ family was outside seeking Him.',true,32),
mc(2,'What question did Jesus ask about His family?',['Who is My mother, or My brothers?','Where is My father?','Why are they outside?','Who called the multitude?'],33),blank(1,'Who is My mother, or My _____?','brothers',33),
sa(2,'At whom did Jesus look before identifying His family?','those sitting around Him',34,['those who sat about Him']),tf(1,'Jesus pointed to those around Him as His mother and brothers.',true,34),
mc(1,'Whom did Jesus identify as His brother, sister, and mother?',['Whoever does the will of God','Only His relatives','Only the Twelve','Everyone in Galilee'],35),blank(3,'whoever does the _____ of God is My brother and My sister and mother.','will',35),
]};
export default bank;
