// Mark 5 — quiz bank (NKJV, Orthodox Study Bible text as stored). Every row is anchored
// to a verse; fill-in-the-blank rows are verified against the stored verse text by
// scripts/seed-quiz-bank.ts. Questions are framed in the story (who, where, what followed),
// never as a single clause turned inside out.
import { mc, blank, word, tf, sa, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: 'Mark',
  chapter: 5,
  tag: 'quiz-v2-mark-5',
  rows: [
    // ══════════════════════════════════ v1–5 · The man among the tombs
    mc(1, 'After crossing to the other side of the sea, into whose country did Jesus come, where the man from the tombs met Him?', ['The country of the Gadarenes', 'The region of Decapolis', 'The land of Galilee', 'The town of Capernaum'], 1),
    blank(1, 'Then they came to the other side of the sea, to the country of the _____.', 'Gadarenes', 1, ['gadarene']),
    word(2, 'The people whose country lay on the other side of the sea, where Jesus met the demon-possessed man, were called what?', 'Gadarenes', 1, ['gadarene', 'the gadarenes']),
    mc(2, 'What happened immediately when Jesus came out of the boat in the country of the Gadarenes?', ['A man with an unclean spirit met Him out of the tombs', 'A ruler of the synagogue fell at His feet', 'A great multitude gathered to Him by the sea', 'Those who fed the swine fled into the city'], 2),
    tf(1, 'The man with an unclean spirit came out of the tombs to meet Jesus as soon as He stepped out of the boat.', true, 2),
    sa(2, 'Where had the man who met Jesus in the country of the Gadarenes come from, and what was wrong with him?', 'He came out of the tombs, and he had an unclean spirit.', 2),
    blank(2, 'who had his dwelling among the tombs; and no one could _____ him, not even with chains,', 'bind', 3),
    tf(2, 'The Gadarene man who lived among the tombs could be held only when he was bound with chains.', false, 3, 'No one could bind him, "not even with chains."'),
    mc(2, 'What had the demon-possessed man done to the shackles and chains people had often bound him with?', ['He pulled the chains apart and broke the shackles in pieces', 'He threw the chains and shackles into the sea', 'He cut the chains apart with stones', 'He wore them still as he sat clothed in his right mind'], 4),
    blank(3, 'And the chains had been pulled apart by him, and the shackles broken in pieces; neither could anyone _____ him.', 'tame', 4),
    word(3, 'Besides chains, what had the man among the tombs often been bound with, only to break them in pieces?', 'shackles', 4, ['shackle']),
    sa(3, 'Why could no one bind the man among the tombs, even with chains?', 'He had often been bound with shackles and chains, but he pulled the chains apart and broke the shackles in pieces, and no one could tame him.', 4),
    mc(1, 'What did the man among the tombs do to himself night and day before Jesus delivered him?', ['He cried out and cut himself with stones', 'He cast himself down the steep place', 'He tore his garment and wept loudly', 'He starved himself and refused to eat'], 5),
    blank(1, 'And always, night and day, he was in the mountains and in the tombs, crying out and cutting himself with _____.', 'stones', 5),
    tf(3, 'Night and day the demon-possessed man was in the mountains and the tombs, crying out and cutting himself with stones.', true, 5),

    // ══════════════════════════════════ v6–10 · Legion
    mc(1, 'What did the demon-possessed man do when he saw Jesus from afar?', ['He ran and worshiped Him', 'He fled into the mountains', 'He hid himself among the tombs', 'He cried out for the swineherds'], 6),
    blank(2, 'When he saw Jesus from afar, he ran and _____ Him.', 'worshiped', 6, ['worshipped']),
    mc(2, 'By what title did the demon-possessed man address Jesus when he cried out with a loud voice?', ['Jesus, Son of the Most High God', 'Jesus, Teacher of the synagogue', 'Jesus, Son of David', 'Jesus, the Holy One of God'], 7),
    blank(3, 'What have I to do with You, Jesus, Son of the Most High God? I implore You by God that You do not _____ me.', 'torment', 7),
    sa(2, 'What did the demon-possessed man beg of Jesus when he cried out, "What have I to do with You"?', 'He implored Jesus by God not to torment him.', 7),
    tf(3, 'The man with the unclean spirit implored Jesus by God that He would not send him out of the country.', false, 7, 'When he cried out he implored Jesus not to torment him; the plea about the country came after Jesus asked his name.'),
    mc(3, 'What had Jesus commanded that made the unclean spirit cry out, "I implore You by God that You do not torment me"?', ['"Come out of the man, unclean spirit!"', '"Be quiet, and come out of him!"', '"Go home to your friends"', '"Send us to the swine"'], 8),
    blank(1, 'For He said to him, "Come out of the man, _____ spirit!"', 'unclean', 8),
    mc(1, 'When Jesus asked the demon-possessed man among the tombs his name, what did he answer?', ['"My name is Legion; for we are many"', '"My name is Jairus; I rule the synagogue"', '"I am the Son of the Most High God"', '"We are the unclean spirits of the tombs"'], 9),
    word(1, 'What name did the demon-possessed man give when Jesus asked, "What is your name?"', 'Legion', 9),
    blank(1, 'And he answered, saying, "My name is _____; for we are many."', 'Legion', 9),
    sa(3, 'What reason did the spirit give for the name Legion?', 'He said, "for we are many."', 9),
    tf(2, 'The demon told Jesus his name was Legion because the spirits in the man were many.', true, 9),
    mc(3, 'What did Legion beg Jesus earnestly not to do?', ['Send them out of the country', 'Send them into the sea', 'Send them back to the tombs', 'Send them into the city'], 10),
    blank(3, 'Also he begged Him earnestly that He would not send them out of the _____.', 'country', 10),
    tf(2, 'Legion begged Jesus earnestly to send the spirits out of the country.', false, 10, 'He begged that Jesus would NOT send them out of the country.'),

    // ══════════════════════════════════ v11–13 · The swine
    blank(1, 'Now a large herd of _____ was feeding there near the mountains.', 'swine', 11),
    word(1, 'What animals were feeding near the mountains in the country of the Gadarenes?', 'swine', 11, ['pigs', 'pig', 'hogs']),
    mc(1, 'What did all the demons beg Jesus to do with them once He had commanded them out of the man?', ['Send them to the swine so they could enter them', 'Send them into the sea to be drowned', 'Send them back into the tombs and mountains', 'Send them out of the country of the Gadarenes'], 12),
    tf(1, 'All the demons begged Jesus, "Send us to the swine, that we may enter them."', true, 12),
    mc(2, 'About how many swine were in the herd the unclean spirits entered?', ['About two thousand', 'About five thousand', 'About four thousand', 'About twelve hundred'], 13),
    blank(3, 'Then the unclean spirits went out and entered the swine (there were about _____); and the herd ran violently down the steep place into the sea, and drowned in the sea.', 'two thousand', 13, ['2000', '2,000']),
    mc(2, 'What happened to the herd after the unclean spirits entered the swine?', ['It rushed down the steep place into the sea and drowned','It scattered throughout the nearby mountains and among the tombs','It fled away from the shore into both the city and countryside','It remained quietly feeding on the hillside beside the mountains'], 13),
    tf(1, 'Jesus refused the demons permission to enter the swine.', false, 13, 'At once Jesus gave them permission.'),
    sa(1, 'How did Jesus respond to the demons’ request to enter the swine, and what followed?', 'He at once gave them permission; the spirits entered the swine, and the herd of about two thousand ran violently down the steep place into the sea and drowned.', 13),

    // ══════════════════════════════════ v14–17 · The Gadarenes react
    mc(3, 'What did those who fed the swine do after the herd drowned in the sea?', ['They fled and told it in the city and in the country', 'They begged Jesus to depart from their region', 'They ran and worshiped Jesus at the shore', 'They fell at Jesus’ feet and told Him the whole truth'], 14),
    blank(2, 'So those who fed the swine fled, and they told it in the _____ and in the country.', 'city', 14),
    sa(2, 'Why did people go out from the city and the country to where Jesus was after the swine drowned?', 'Those who fed the swine had fled and told it in the city and country, so the people went out to see what had happened.', 14),
    mc(1, 'When the people came out to Jesus, how did they find the man who had had the legion?', ['Sitting and clothed and in his right mind', 'Crying out and cutting himself with stones', 'Running down the steep place after the swine', 'Bound with shackles and chains among the tombs'], 15),
    blank(2, 'Then they came to Jesus, and saw the one who had been demon-possessed and had the legion, sitting and _____ and in his right mind.', 'clothed', 15),
    word(2, 'How did the people feel when they saw the man who had had the legion sitting, clothed, and in his right mind?', 'afraid', 15, ['fear', 'fearful', 'scared']),
    sa(1, 'When the people came out from the city and country to Jesus, what did they see and how did they feel?', 'They saw the man who had had the legion sitting, clothed, and in his right mind, and they were afraid.', 15),
    mc(3, 'What two things did the eyewitnesses tell the people who came out from the city and country?', ['How it happened to the demon-possessed man, and about the swine', 'How Jesus crossed the sea, and about the boat', 'How the man broke his chains, and about the tombs', 'How Jesus was thronged, and about the woman healed'], 16),
    tf(3, 'Those who had seen it told the people how it happened to the demon-possessed man and about the swine.', true, 16),
    mc(1, 'After hearing what happened to the man and the swine, what did the people of the Gadarenes plead with Jesus to do?', ['Depart from their region', 'Stay and teach in their synagogue', 'Heal their sick who lay at the point of death', 'Restore the swine that had drowned'], 17),
    blank(1, 'Then they began to plead with Him to _____ from their region.', 'depart', 17),
    tf(1, 'The people of the Gadarenes begged Jesus to stay in their region after He healed the demon-possessed man.', false, 17, 'They pleaded with Him to depart from their region.'),

    // ══════════════════════════════════ v18–20 · Go home to your friends
    mc(2, 'As Jesus got into the boat to leave the Gadarenes, what did the man who had been demon-possessed beg for?', ['That he might be with Jesus', 'That Jesus would depart from the region', 'That Jesus would not torment him', 'That Jesus would not send the spirits out of the country'], 18),
    tf(1, 'The man Jesus delivered from the legion begged to go with Him in the boat.', true, 18),
    mc(1, 'What did Jesus tell the delivered man to do instead of coming with Him in the boat?', ['Go home and tell his friends what the Lord had done for him','Follow Jesus to the home of the ruler of the synagogue','Remain silent and tell no one what had happened to him','Go directly to the swineherds and proclaim the event to them'], 19),
    blank(2, '"Go home to your friends, and tell them what great things the Lord has done for you, and how He has had _____ on you."', 'compassion', 19),
    word(2, 'Jesus told the delivered man to tell his friends how the Lord had had what on him?', 'compassion', 19, ['mercy']),
    tf(2, 'Jesus permitted the man He delivered from the legion to get into the boat and go with Him.', false, 19, 'Jesus did not permit him, but sent him home to his friends.'),
    sa(1, 'What two things did Jesus tell the delivered man to tell his friends?', 'What great things the Lord had done for him, and how He had had compassion on him.', 19),
    mc(2, 'Where did the man delivered from the legion go and proclaim all that Jesus had done for him?', ['Decapolis', 'Galilee', 'Capernaum', 'Nazareth'], 20),
    word(1, 'In what region did the delivered man proclaim all that Jesus had done for him?', 'Decapolis', 20, ['the decapolis']),
    blank(2, 'And he departed and began to proclaim in _____ all that Jesus had done for him; and all marveled.', 'Decapolis', 20),
    tf(2, 'When the delivered man proclaimed in Decapolis what Jesus had done for him, all marveled.', true, 20),
    word(3, 'When the man proclaimed in Decapolis what Jesus had done for him, how did all who heard react — they all did what?', 'marveled', 20, ['marvelled', 'marvel']),
    sa(2, 'What did the delivered man do after Jesus sent him home, and how did people react?', 'He proclaimed in Decapolis all that Jesus had done for him, and all marveled.', 20),

    // ══════════════════════════════════ v21–24 · Jairus
    mc(3, 'When Jesus crossed back over by boat, who gathered to Him as He stood by the sea?', ['A great multitude', 'The rulers of the synagogue', 'Those who fed the swine', 'Peter, James, and John only'], 21),
    blank(3, 'Now when Jesus had crossed over again by boat to the other side, a great _____ gathered to Him; and He was by the sea.', 'multitude', 21, ['crowd']),
    mc(1, 'Who was Jairus, the man who fell at Jesus’ feet by the sea?', ['One of the rulers of the synagogue', 'One of those who fed the swine', 'One of the twelve disciples', 'One of the physicians of the region'], 22),
    word(1, 'What was the name of the ruler of the synagogue who fell at Jesus’ feet and begged for his daughter?', 'Jairus', 22),
    blank(1, 'And behold, one of the rulers of the synagogue came, _____ by name. And when he saw Him, he fell at His feet', 'Jairus', 22),
    sa(2, 'What did Jairus do as soon as he saw Jesus by the sea?', 'He fell at Jesus’ feet and begged Him earnestly to come and lay hands on his little daughter.', 22),
    mc(2, 'What did Jairus tell Jesus about his little daughter?', ['She lay at the point of death', 'She had a flow of blood for twelve years', 'She had an unclean spirit', 'She was already dead at the house'], 23),
    blank(2, 'My little daughter lies at the point of death. Come and lay Your _____ on her, that she may be healed, and she will live.', 'hands', 23),
    sa(2, 'What did Jairus beg Jesus to do for his daughter, and what did he believe would follow?', 'He begged Jesus to come and lay His hands on her so that she would be healed and live.', 23),
    tf(2, 'Jairus asked Jesus only to speak a word from afar so that his daughter would be healed.', false, 23, 'He begged Jesus to come and lay His hands on her.'),
    blank(3, 'So Jesus went with him, and a great multitude followed Him and _____ Him.', 'thronged', 24),
    tf(1, 'Jesus agreed to go with Jairus, and a great multitude followed and thronged Him.', true, 24),

    // ══════════════════════════════════ v25–29 · The woman with the flow of blood
    mc(1, 'How long had the woman in the crowd suffered a flow of blood before she touched Jesus’ garment?', ['Twelve years', 'Seven years', 'Three years', 'Forty days'], 25),
    word(1, 'For how many years had the woman who touched Jesus’ garment suffered a flow of blood?', 'twelve', 25, ['12']),
    blank(1, 'Now a certain woman had a flow of blood for _____ years,', 'twelve', 25, ['12']),
    mc(3, 'What had the woman with the flow of blood gained from spending all she had on many physicians?', ['She was no better but rather grew worse', 'She improved slowly over twelve years', 'She was healed but the affliction returned', 'She was told to go home and wait'], 26),
    blank(2, 'She had spent all that she had and was no better, but rather grew _____.', 'worse', 26),
    tf(2, 'The woman with the flow of blood had improved a little under the care of her many physicians.', false, 26, 'She "was no better, but rather grew worse."'),
    word(2, 'From whom had the woman with the flow of blood suffered many things and spent all that she had?', 'physicians', 26, ['physician', 'doctors', 'doctor']),
    sa(3, 'What had the woman’s twelve years with the physicians cost her, and with what result?', 'She had suffered many things from many physicians and spent all she had, yet she was no better but rather grew worse.', 26),
    mc(1, 'What did the woman with the flow of blood do when she heard about Jesus?', ['She came behind Him in the crowd and touched His garment', 'She fell at His feet and begged Him to lay hands on her', 'She called to Him from the ruler of the synagogue’s house', 'She sent her friends to ask Him to come to her'], 27),
    blank(1, 'When she heard about Jesus, she came behind Him in the crowd and touched His _____.', 'garment', 27, ['garments', 'clothes']),
    tf(1, 'The woman with the flow of blood came in front of Jesus and asked Him openly to heal her.', false, 27, 'She came behind Him in the crowd and touched His garment.'),
    blank(2, 'For she said, "If only I may touch His _____, I shall be made well."', 'clothes', 28, ['garment', 'garments']),
    tf(2, 'The woman believed that if only she touched Jesus’ clothes she would be made well.', true, 28),
    mc(3, 'What happened the moment the woman touched Jesus’ garment?', ['The fountain of her blood was dried up and she felt she was healed', 'Jesus turned and said, "Daughter, your faith has made you well"', 'The disciples asked who had touched Him', 'She fell down before Him trembling'], 29),
    blank(3, 'Immediately the _____ of her blood was dried up, and she felt in her body that she was healed of the affliction.', 'fountain', 29),
    word(3, 'When the fountain of her blood dried up, the woman felt in her body that she was healed of her what?', 'affliction', 29, ['afflictions']),

    // ══════════════════════════════════ v30–34 · Who touched My clothes?
    mc(2, 'What did Jesus say when He turned around in the crowd after the woman touched Him?', ['"Who touched My clothes?"', '"Why make this commotion and weep?"', '"What is your name?"', '"Do not be afraid; only believe"'], 30),
    blank(2, 'And Jesus, immediately knowing in Himself that _____ had gone out of Him, turned around in the crowd and said, "Who touched My clothes?"', 'power', 30),
    tf(3, 'Jesus knew in Himself that power had gone out of Him, so He turned around in the crowd.', true, 30),
    sa(3, 'Why did Jesus turn around in the crowd and ask, "Who touched My clothes?"', 'He knew immediately in Himself that power had gone out of Him.', 30),
    mc(2, 'How did the disciples answer when Jesus asked, "Who touched My clothes?"', ['"You see the multitude thronging You, and You say, ‘Who touched Me?’"', '"Lord, the woman suffering from the flow of blood was the one"','"Why should anyone continue to trouble the Teacher any further?"','"Teacher, no one among this entire multitude has touched You"'], 31),
    tf(3, 'The disciples pointed out to Jesus the woman who had touched Him.', false, 31, 'They protested, "You see the multitude thronging You, and You say, ‘Who touched Me?’"'),
    sa(3, 'What did the disciples say that showed they thought Jesus’ question about who touched Him was unreasonable?', 'They said, "You see the multitude thronging You, and You say, ‘Who touched Me?’"', 31),
    mc(3, 'What did Jesus do after His disciples protested that the multitude was thronging Him?', ['He looked around to see her who had done this thing', 'He went on at once to the house of Jairus', 'He commanded the multitude to be put outside', 'He got into the boat and crossed to the other side'], 32),
    tf(3, 'After the disciples spoke, Jesus dropped the matter and went on toward Jairus’ house.', false, 32, 'He looked around to see her who had done this thing.'),
    mc(2, 'How did the healed woman come before Jesus when He looked around for her?', ['Fearing and trembling, she fell before Him and told the truth','Rejoicing openly, she proclaimed throughout Decapolis what He had done','Remaining completely silent, she slipped away behind the surrounding crowd','Approaching Him boldly, she asked Him to place His hands upon her'], 33),
    blank(3, 'But the woman, fearing and trembling, knowing what had happened to her, came and fell down before Him and told Him the whole _____.', 'truth', 33),
    tf(2, 'The healed woman came to Jesus fearing and trembling and told Him the whole truth.', true, 33),
    mc(1, 'What did Jesus say to the woman who had touched His garment after twelve years of bleeding?', ['"Daughter, your faith has made you well. Go in peace, and be healed of your affliction"', '"Little girl, I say to you, arise"', '"Go home to your friends, and tell them what great things the Lord has done for you"', '"Do not be afraid; only believe"'], 34),
    blank(1, 'And He said to her, "Daughter, your _____ has made you well. Go in peace, and be healed of your affliction."', 'faith', 34),
    word(1, 'What did Jesus say had made the woman with the flow of blood well?', 'faith', 34, ['her faith']),
    word(2, 'By what name did Jesus address the woman healed of her flow of blood?', 'Daughter', 34),
    sa(2, 'What blessing did Jesus give the healed woman after telling her that her faith had made her well?', 'He said, "Go in peace, and be healed of your affliction."', 34),
    mc(3, 'Whom did Jesus address as "Daughter" in Mark 5?', ['The woman healed of the flow of blood', 'Jairus’ twelve-year-old daughter', 'The mother of the child', 'A woman among those who wept and wailed'], 34),

    // ══════════════════════════════════ v35–37 · Your daughter is dead
    mc(2, 'What news came from Jairus’ house while Jesus was still speaking with the healed woman?', ['"Your daughter is dead. Why trouble the Teacher any further?"', '"Your daughter has been healed, so return to your home quickly"','"The child is not dead at all but is merely sleeping peacefully"','"The Teacher is approaching, so prepare your household to receive Him"'], 35),
    blank(2, 'Your daughter is dead. Why trouble the _____ any further?', 'Teacher', 35),
    tf(2, 'The messengers from Jairus’ house told him his daughter was at the point of death and urged the Teacher to hurry.', false, 35, 'They said, "Your daughter is dead. Why trouble the Teacher any further?"'),
    sa(1, 'What did the messengers from the ruler of the synagogue’s house say, and when did they arrive?', 'While Jesus was still speaking, they said, "Your daughter is dead. Why trouble the Teacher any further?"', 35),
    mc(1, 'What did Jesus say to Jairus as soon as He heard that the girl was dead?', ['"Do not be afraid; only believe"', '"Your faith has made you well"', '"Why make this commotion and weep?"', '"Go in peace"'], 36),
    blank(1, 'He said to the ruler of the synagogue, "Do not be afraid; only _____."', 'believe', 36),
    tf(1, 'When Jesus heard that Jairus’ daughter was dead, He told Jairus, "Do not be afraid; only believe."', true, 36),
    mc(2, 'Whom alone did Jesus permit to follow Him to Jairus’ house?', ['Peter, James, and John the brother of James', 'Peter, Andrew, James, and John', 'All twelve of His disciples', 'Only Jairus, the ruler of the synagogue'], 37),
    blank(2, 'And He permitted no one to follow Him except Peter, James, and _____ the brother of James.', 'John', 37),
    tf(2, 'Jesus allowed all twelve disciples to follow Him into Jairus’ house.', false, 37, 'He permitted no one except Peter, James, and John the brother of James.'),
    word(3, 'John, who followed Jesus to Jairus’ house, is identified in the verse as the brother of whom?', 'James', 37),

    // ══════════════════════════════════ v38–43 · Talitha, cumi
    mc(3, 'What did Jesus find when He came to the house of the ruler of the synagogue?', ['A tumult and people weeping and wailing loudly', 'A quiet house with the child sleeping', 'A great multitude thronging the door', 'The father and mother waiting alone'], 38),
    blank(3, 'Then He came to the house of the ruler of the synagogue, and saw a _____ and those who wept and wailed loudly.', 'tumult', 38),
    mc(1, 'What did Jesus say to the mourners when He came into Jairus’ house?', ['"Why make this commotion and weep? The child is not dead, but sleeping"', '"Why trouble the Teacher any further? The child is dead"', '"Do not weep; the child has been healed of her affliction"', '"Put them all outside; the child will arise"'], 39),
    blank(1, 'Why make this commotion and weep? The child is not dead, but _____.', 'sleeping', 39, ['asleep']),
    tf(1, 'Jesus told the mourners at Jairus’ house that the child was not dead but sleeping.', true, 39),
    word(3, 'When Jesus came in to Jairus’ house, He asked the mourners why they made this what and wept?', 'commotion', 39),
    mc(2, 'How did the mourners react when Jesus said the child was sleeping, and what did He do?', ['They ridiculed Him, and He put them all outside', 'They marveled, and He blessed them', 'They were afraid, and He sent them home', 'They believed, and He let them come in'], 40),
    blank(3, 'And they _____ Him. But when He had put them all outside, He took the father and the mother of the child, and those who were with Him, and entered where the child was lying.', 'ridiculed', 40, ['mocked', 'laughed at']),
    word(2, 'What did the mourners do to Jesus when He said the child was sleeping?', 'ridiculed', 40, ['mocked', 'laughed', 'scorned']),
    sa(3, 'Whom did Jesus take with Him into the room where Jairus’ daughter was lying?', 'The father and the mother of the child, and those who were with Him.', 40, 'Those with Him were Peter, James, and John, the only ones He had permitted to follow.'),
    mc(3, 'What did Jesus say as He took Jairus’ daughter by the hand?', ['"Talitha, cumi"', '"Ephphatha"', '"Eloi, Eloi, lama sabachthani"', '"Corban"'], 41),
    blank(1, 'Then He took the child by the hand, and said to her, "Talitha, cumi," which is translated, "Little girl, I say to you, _____."', 'arise', 41),
    sa(1, 'What does "Talitha, cumi" mean, according to Mark?', 'It is translated, "Little girl, I say to you, arise."', 41),
    tf(2, 'Jesus raised Jairus’ daughter by taking her by the hand and saying, "Talitha, cumi."', true, 41),
    word(3, 'By what part of her body did Jesus take the child before saying, "Talitha, cumi"?', 'hand', 41, ['the hand', 'her hand']),
    mc(1, 'How old was Jairus’ daughter when Jesus raised her?', ['Twelve years old', 'Seven years old', 'Ten years old', 'Five years old'], 42),
    word(2, 'How many years old was the girl who arose and walked when Jesus said, "Talitha, cumi"?', 'twelve', 42, ['12']),
    blank(2, 'Immediately the girl arose and walked, for she was _____ years of age.', 'twelve', 42, ['12']),
    sa(2, 'What did the girl do immediately after Jesus spoke, and how did those present respond?', 'She arose and walked, and they were overcome with great amazement.', 42),
    blank(3, 'Immediately the girl arose and walked, for she was twelve years of age. And they were overcome with great _____.', 'amazement', 42),
    mc(3, 'After raising Jairus’ daughter, what two things did Jesus command?', ['That no one should know it, and that she be given something to eat', 'That they proclaim it in Decapolis, and that she rest', 'That they tell the Teacher, and that she be clothed', 'That the mourners return, and that she go in peace'], 43),
    blank(2, 'But He commanded them strictly that no one should know it, and said that something should be given her to _____.', 'eat', 43),
    sa(1, 'What did Jesus command strictly after Jairus’ daughter arose?', 'That no one should know it, and that something should be given her to eat.', 43),
    tf(3, 'In Mark 5, Jesus told the man delivered from the legion to keep silent but told Jairus’ household to spread the news.', false, 43, 'It was the reverse: the delivered man was sent home to tell his friends, while Jairus’ household was commanded strictly that no one should know it.'),
  ],
};

export default bank;
