import { mc, blank, word, tf, type ChapterBank } from './types';
const bank: ChapterBank = { book: 'Mark', chapter: 8, tag: 'quiz-v2-mark-8', rows: [
mc(1,'Why did Jesus call His disciples to Him?',['The great multitude had nothing to eat','The Pharisees requested a sign','A blind man needed help','They had reached Bethsaida'],1),blank(2,'the multitude being very great and having nothing to _____','eat',1),
word(1,'How long had the multitude remained with Jesus?','three days',2,['3 days']),tf(3,'Jesus felt no concern about the hungry multitude.',false,2,'He said He had compassion on them.'),
mc(2,'What did Jesus say could happen if the people left hungry?',['They could faint on the way','They would miss the boat','They would follow the Pharisees','They would demand a sign'],3),blank(1,'some of them have come from _____.','afar',3),
word(2,'Where did the disciples doubt bread could be found?','the wilderness',4,['in the wilderness']),tf(3,'The disciples immediately knew how to satisfy the crowd.',false,4,'They asked how anyone could satisfy them there.'),
mc(1,'How many loaves did the disciples have?',['Seven','Five','Twelve','One'],5),blank(2,'How many loaves do you have? And they said, “_____.”','Seven',5,['7']),
word(2,'What did Jesus do before breaking the seven loaves?','gave thanks',6),tf(1,'Jesus gave the broken loaves to His disciples to distribute.',true,6),
mc(1,'What additional food did the disciples have?',['A few small fish','Twelve baskets of fruit','One large fish','Some grain'],7),blank(3,'They also had a few small _____','fish',7),
word(1,'How many large baskets of fragments remained?','seven',8,['7']),tf(2,'Everyone ate and was filled.',true,8),
mc(1,'About how many people had eaten?',['Four thousand','Five thousand','Seven thousand','Twelve thousand'],9),blank(2,'those who had eaten were about four _____.','thousand',9),
word(2,'To what region did Jesus travel by boat?','Dalmanutha',10),tf(3,'Jesus traveled to Dalmanutha without His disciples.',false,10,'His disciples were with Him in the boat.'),
mc(2,'What did the Pharisees seek from Jesus?',['A sign from heaven','Bread in the wilderness','Healing for a blind man','Permission to follow Him'],11),blank(1,'the Pharisees came out and began to _____ with Him','dispute',11),
word(1,'How did Jesus react inwardly to the request for a sign?','He sighed deeply',12,['sighed deeply']),tf(3,'Jesus promised this generation a sign from heaven.',false,12,'He said no sign would be given.'),
mc(1,'How did Jesus leave the Pharisees?',['He took the boat to the other side','He walked to Bethsaida alone','He remained to debate them','He sent the disciples away'],13),blank(2,'getting into the boat again, departed to the other _____.','side',13),
word(2,'How many loaves were in the boat?','one',14,['one loaf','1']),tf(1,'The disciples had forgotten to take bread.',true,14),
mc(1,'Whose leaven did Jesus warn against?',['The Pharisees and Herod','The disciples and the crowd','John and Elijah','The elders and scribes only'],15),blank(3,'beware of the leaven of the Pharisees and the leaven of _____.','Herod',15),
word(1,'How did the disciples interpret Jesus’ warning?','they thought it was because they had no bread',16,['because they had no bread']),tf(2,'The disciples understood the leaven warning immediately.',false,16,'They reasoned that it concerned their lack of bread.'),
mc(2,'What condition did Jesus question in the disciples?',['Whether their hearts were still hardened','Whether they wanted a sign','Whether they feared Herod','Whether they had eaten'],17),blank(1,'Do you not yet perceive nor _____?','understand',17),
word(3,'What three failures did Jesus ask about?','seeing, hearing, and remembering',18,['see, hear, and remember']),tf(1,'Jesus reminded them that they had eyes and ears.',true,18),
mc(1,'How many baskets remained after feeding five thousand?',['Twelve','Seven','Five','One'],19),blank(2,'how many baskets full of fragments did you take up? They said to Him, “_____.”','Twelve',19,['12']),
word(1,'How many large baskets remained after feeding four thousand?','seven',20,['7']),tf(3,'The four-thousand feeding left twelve large baskets.',false,20,'It left seven.'),
mc(2,'What did Jesus still find lacking after the two reminders?',['Understanding','Bread','A boat','Witnesses'],21),blank(3,'How is it you do not _____?','understand',21),
word(1,'Where was the blind man brought to Jesus?','Bethsaida',22),tf(2,'The people begged Jesus to touch the blind man.',true,22),
mc(2,'Where did Jesus lead the blind man?',['Out of the town','Into the synagogue','To the boat','Into Jerusalem'],23),blank(1,'He had spit on his eyes and put His _____ on him','hands',23),
word(2,'What did the man initially say people looked like?','trees walking',24,['men like trees, walking']),tf(3,'The man saw everyone clearly after the first touch.',false,24,'He initially saw men like walking trees.'),
mc(1,'What happened after Jesus put His hands on the man again?',['He saw everyone clearly','He became unable to see','He returned to town','He saw only light'],25),blank(2,'he was restored and saw everyone _____.','clearly',25),
word(1,'Where did Jesus send the healed man?','to his house',26,['his house','home']),tf(3,'Jesus told him to announce the healing throughout town.',false,26,'He told him not to enter or tell anyone in town.'),
mc(1,'Near what towns did Jesus ask who people said He was?',['Caesarea Philippi','Tyre and Sidon','Bethsaida and Dalmanutha','Jerusalem'],27),blank(3,'Who do men say that I _____?','am',27),
word(2,'Name one person people thought Jesus might be.','John the Baptist',28,['Elijah','one of the prophets']),tf(1,'Some people identified Jesus with Elijah or one of the prophets.',true,28),
mc(1,'Who confessed that Jesus is the Christ?',['Peter','John','Andrew','Philip'],29),blank(2,'You are the _____.','Christ',29),
word(2,'What did Jesus warn the disciples not to do?','tell anyone about Him',30,['tell anyone']),tf(3,'Jesus instructed them to publicize Peter’s confession immediately.',false,30,'He warned them to tell no one.'),
mc(2,'What did Jesus teach would happen after He was killed?',['He would rise after three days','He would remain in the tomb','He would return to Galilee immediately','He would become an earthly king'],31),blank(3,'after three days _____ again.','rise',31),
word(1,'Who took Jesus aside and rebuked Him?','Peter',32),tf(2,'Jesus spoke the prediction openly.',true,32),
mc(1,'What did Jesus say Peter was mindful of?',['The things of men','The things of God','The needs of the crowd','The traditions of elders'],33),blank(2,'Get behind Me, _____!','Satan',33),
word(1,'What must a person take up to follow Jesus?','his cross',34,['cross']),tf(3,'Jesus said a follower should avoid self-denial.',false,34,'A follower must deny himself.'),
mc(2,'Who will save their life?',['Those who lose it for Jesus and the gospel','Those who preserve it at every cost','Those who gain the world','Those ashamed of Jesus'],35),blank(1,'whoever loses his life for My sake and the gospel’s will _____ it.','save',35),
word(2,'What can a person gain yet lose his soul?','the whole world',36),tf(1,'Gaining the whole world does not compensate for losing one’s soul.',true,36),
mc(3,'What did Jesus ask a person could give for the soul?',['Something in exchange for it','Seven loaves','A heavenly sign','A basket of fragments'],37),blank(2,'what will a man give in _____ for his soul?','exchange',37),
word(3,'With whom will the Son of Man come in His Father’s glory?','the holy angels',38,['holy angels']),tf(1,'The Son of Man will be ashamed of those ashamed of Him and His words.',true,38),
]};
export default bank;
