import { mc, blank, word, tf, type ChapterBank } from './types';
const bank: ChapterBank = { book: 'Mark', chapter: 14, tag: 'quiz-v2-mark-14', rows: [
mc(1,'How did the chief priests and scribes seek to arrest Jesus?',['By trickery','By a public vote','During His teaching','With Pilate’s warrant'],1),
blank(2,'Not during the feast, lest there be an _____ of the people.','uproar',2),
word(3,'What did the woman pour on Jesus’ head?','costly oil of spikenard',3,['oil of spikenard','spikenard']),
tf(1,'Some people considered the woman’s use of the oil wasteful.',true,4),
mc(2,'For how much could the oil have been sold?',['More than three hundred denarii','Thirty denarii','Two hundred denarii','One hundred denarii'],5),
blank(3,'She has done a good _____ for Me.','work',6),
word(1,'Who would always remain available to receive help?','the poor',7,['poor']),
tf(2,'Jesus said the woman had anointed His body beforehand for burial.',true,8),
mc(3,'Where would the woman’s deed be remembered?',['Wherever the gospel is preached worldwide','Only in Bethany','Only at Passover','Only among the Twelve'],9),
blank(1,'Judas Iscariot, one of the twelve, went to the chief priests to _____ Him','betray',10),
word(2,'What did the chief priests promise Judas?','money',11),
tf(3,'The disciples asked where to prepare the Passover on the first day of Unleavened Bread.',true,12),
mc(1,'Whom were the two disciples told to follow?',['A man carrying a water pitcher','A woman carrying oil','A servant with bread','A priest with a lamb'],13),
blank(2,'Where is the guest _____ in which I may eat the Passover with My disciples?','room',14),
word(3,'What kind of room would the master show them?','a large furnished upper room',15,['a large upper room']),
tf(1,'The disciples found everything just as Jesus had said.',true,16),
mc(2,'Who came to the prepared place in the evening?',['Jesus with the Twelve','The chief priests','Simon the leper','A great multitude'],17),
blank(3,'one of you who eats with Me will _____ Me.','betray',18),
word(1,'How did the disciples react to the betrayal announcement?','they became sorrowful',19,['sorrowful']),
tf(2,'Jesus identified the betrayer as one of the Twelve dipping with Him.',true,20),
mc(3,'What did Jesus say would have been better for the betrayer?',['Never to have been born','To leave Jerusalem','To miss the feast','To remain in Bethany'],21),
blank(1,'Take, eat; this is My _____.','body',22),
word(2,'What did Jesus do before giving them the cup?','gave thanks',23),
tf(3,'Jesus called the cup His blood of the new covenant, shed for many.',true,24),
mc(1,'When would Jesus next drink the fruit of the vine?',['In God’s kingdom','The next morning','At His trial','In Gethsemane'],25),
blank(2,'when they had sung a hymn, they went out to the Mount of _____.','Olives',26),
word(3,'What would happen to the sheep when the Shepherd was struck?','they would be scattered',27,['scattered']),
tf(1,'Jesus promised to go before the disciples to Galilee after being raised.',true,28),
mc(2,'Who insisted he would not stumble even if everyone else did?',['Peter','Judas','John','James'],29),
blank(3,'before the rooster crows twice, you will deny Me _____ times.','three',30,['3']),
word(1,'What did Peter claim he would do rather than deny Jesus?','die with Him',31,['die with Jesus']),
tf(2,'At Gethsemane Jesus told the disciples to sit while He prayed.',true,32),
mc(3,'Which three disciples did Jesus take farther?',['Peter, James, and John','Andrew, Philip, and Thomas','Judas, Matthew, and Simon','All twelve'],33),
blank(1,'My soul is exceedingly sorrowful, even to _____.','death',34),
word(2,'What did Jesus pray might pass from Him?','the hour',35),
tf(3,'Jesus submitted His own will to the Father’s will.',true,36),
mc(1,'How long had Jesus asked Simon to watch?',['One hour','Three hours','All night','Until morning'],37),
blank(2,'The spirit indeed is willing, but the _____ is weak.','flesh',38),
word(3,'What words did Jesus use in His repeated prayer?','the same words',39),
tf(1,'The disciples’ eyes were heavy when Jesus returned again.',true,40),
mc(2,'How many times did Jesus return before announcing that the hour had come?',['Three','Two','Four','Seven'],41),
blank(3,'See, My betrayer is at _____.','hand',42),
word(1,'What weapons did the arresting crowd carry?','swords and clubs',43),
tf(2,'Judas had arranged a kiss as the signal identifying Jesus.',true,44),
mc(3,'What did Judas call Jesus before kissing Him?',['Rabbi','Christ','Son of David','Master of the house'],45),
blank(1,'Then they laid their hands on Him and _____ Him.','took',46),
word(2,'Whose ear was cut off?','the high priest’s servant’s',47,['the servant of the high priest']),
tf(3,'Jesus compared the armed arrest to coming against a robber.',true,48),
mc(1,'Why did Jesus say these events happened?',['The Scriptures must be fulfilled','The disciples had planned them','The temple was closed','The feast had ended'],49),
blank(2,'Then they all forsook Him and _____.','fled',50),
word(3,'What covered the young man who followed Jesus?','a linen cloth',51),
tf(1,'The young man left his linen cloth and fled naked.',true,52),
mc(2,'To whom was Jesus led?',['The high priest','Pilate','Herod','Simon the leper'],53),
blank(3,'Peter followed Him at a _____','distance',54),
word(1,'What did the council seek against Jesus?','testimony to put Him to death',55,['testimony']),
tf(2,'The false witnesses’ testimonies agreed with one another.',false,56,'Their testimonies did not agree.'),
mc(3,'What kind of testimony did some people give?',['False witness','Eyewitness agreement','A confession from Peter','A report from Judas'],57),
blank(1,'within three days I will build another made without _____.','hands',58),
word(2,'Did the temple testimony agree?','no',59,['it did not agree']),
tf(3,'The high priest asked Jesus to answer the testimony.',true,60),
mc(1,'How did Jesus initially answer the high priest?',['He remained silent','He denied everything','He accused Peter','He requested witnesses'],61),
blank(2,'you will see the Son of Man sitting at the right hand of the _____','Power',62),
word(3,'What did the high priest tear?','his clothes',63),
tf(1,'The council condemned Jesus as deserving death.',true,64),
mc(2,'What command did Jesus’ abusers give while beating Him?',['Prophesy!','Rise!','Be opened!','Watch!'],65),
blank(3,'Peter was below in the _____.','courtyard',66),
word(1,'With whom did the servant girl say Peter had been?','Jesus of Nazareth',67),
tf(2,'A rooster crowed after Peter’s first recorded denial.',true,68),
mc(3,'Whom did the servant girl tell that Peter was one of the disciples?',['Those standing by','The high priest alone','Jesus','The Twelve'],69),
blank(1,'Surely you are one of them; for you are a _____.','Galilean',70),
word(2,'What did Peter swear about Jesus?','I do not know this Man',71,['he did not know Jesus']),
tf(3,'Peter remembered Jesus’ prediction after the rooster crowed a second time and wept.',true,72),
]};
export default bank;
