// Mark 1 — quiz bank (NKJV, Orthodox Study Bible text as stored). Every row is anchored
// to a verse; fill-in-the-blank rows are verified against the stored verse text by
// scripts/seed-quiz-bank.ts. Questions are framed in the story (who, where, what followed),
// never as a single clause turned inside out.
import { mc, blank, word, tf, sa, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: 'Mark',
  chapter: 1,
  tag: 'quiz-v2-mark-1',
  rows: [
    // ══════════════════════════════════ v1–3 · Title and the prophecy of the messenger
    mc(1, 'How does Mark open his Gospel?', ['"The beginning of the gospel of Jesus Christ, the Son of God."', '"The voice of one crying in the wilderness."', '"John came baptizing in the wilderness."', '"The time is fulfilled, and the kingdom of God is at hand."'], 1),
    blank(1, 'The beginning of the gospel of Jesus Christ, the _____ of God.', 'Son', 1),
    tf(2, 'Mark opens his Gospel by calling Jesus Christ "the Son of David."', false, 1, 'Mark’s first verse calls Him "the Son of God."'),
    mc(2, 'Before John the Baptist appears, Mark quotes the Prophets about a messenger. What is the messenger sent to do?', ['Prepare the Lord’s way before Him', 'Baptize the Lord in the Jordan River', 'Anoint the Lord as king over Israel', 'Announce the Lord’s birth in Nazareth'], 2),
    word(3, 'Mark introduces John the Baptist with a quotation about a messenger sent "before Your face." Where does Mark say this was written — the Law, the Psalms, or the Prophets?', 'Prophets', 2, ['the prophets', 'prophet']),
    sa(3, 'Before John appears, Mark quotes a promise from the Prophets. Whom does God say He will send, and for what purpose?', 'God says He will send His messenger before the Lord’s face, and the messenger will prepare the Lord’s way before Him.', 2),
    blank(1, '"The voice of one crying in the wilderness: ‘Prepare the way of the Lord; Make His paths _____.’"', 'straight', 3),
    mc(2, 'The prophecy Mark quotes speaks of "the voice of one crying in the wilderness." What does that voice tell people to do?', ['Prepare the way of the Lord and make His paths straight', 'Repent and believe in the gospel, for the time is fulfilled', 'Follow the Lord and become fishers of men', 'Show themselves to the priest as Moses commanded'], 3),
    word(2, 'In the prophecy Mark quotes about John, where is the voice crying out?', 'wilderness', 3, ['the wilderness', 'in the wilderness']),

    // ══════════════════════════════════ v4–8 · John the Baptist
    mc(1, 'When John came baptizing in the wilderness, what did he preach?', ['A baptism of repentance for the remission of sins', 'The gospel of the kingdom of God', 'A new doctrine with authority over unclean spirits', 'That the One coming after him would baptize with fire'], 4),
    blank(2, 'John came baptizing in the wilderness and preaching a baptism of repentance for the _____ of sins.', 'remission', 4),
    sa(2, 'Where did John do his baptizing, and what did he say his baptism was for?', 'John baptized in the wilderness, in the Jordan River, preaching a baptism of repentance for the remission of sins.', 4),
    mc(2, 'While John was baptizing in the Jordan, who came out to him?', ['All the land of Judea and those from Jerusalem', 'All the region around Galilee and those from Capernaum', 'The scribes and those from Nazareth', 'Simon, Andrew, James, and John'], 5),
    word(1, 'In which river did John baptize the crowds who came from Judea and Jerusalem?', 'Jordan', 5, ['the jordan', 'jordan river', 'the jordan river']),
    tf(1, 'As the people of Judea and Jerusalem were baptized by John in the Jordan, they were confessing their sins.', true, 5),
    sa(1, 'How does Mark describe John the Baptist’s clothing and food?', 'He was clothed with camel’s hair and a leather belt around his waist, and he ate locusts and wild honey.', 6),
    blank(2, 'Now John was clothed with camel’s hair and with a leather belt around his waist, and he ate _____ and wild honey.', 'locusts', 6),
    mc(2, 'Mark pauses to tell us how John the Baptist dressed. What was he wearing?', ['Camel’s hair with a leather belt around his waist', 'Goat’s hair with a rope belt around his waist', 'Linen with a woven sash around his waist', 'Sheep’s wool with a leather belt around his waist'], 6),
    word(3, 'John the Baptist wore a belt of what material around his waist?', 'leather', 6),
    tf(3, 'Mark says John the Baptist was clothed with goat’s hair and wore a leather belt.', false, 6, 'John was clothed with camel’s hair; the leather belt is right.'),
    mc(1, 'John told the crowds that One mightier than he was coming after him. What did John say he was not worthy to do for Him?', ['Stoop down and loose His sandal strap', 'Carry His cloak into the wilderness', 'Eat at His table', 'Speak His name aloud'], 7),
    sa(3, 'How did John compare himself with the One who was coming after him?', 'John said the coming One was mightier than he, and that he was not worthy to stoop down and loose His sandal strap.', 7),
    mc(1, 'John contrasted his own baptism with the baptism of the One coming after him. What was the difference?', ['John baptized with water; the coming One would baptize with the Holy Spirit', 'John baptized with water; the coming One would baptize with fire', 'John baptized in the Jordan; the coming One would baptize in the Sea of Galilee', 'John baptized Judea; the coming One would baptize Galilee'], 8),
    blank(1, 'I indeed baptized you with water, but He will baptize you with the _____.', 'Holy Spirit', 8, ['holy spirit', 'spirit']),
    word(1, 'John said the coming One would baptize with the Holy Spirit. With what did John himself baptize?', 'water', 8),
    tf(3, 'John said, "I indeed baptized you with water, but He will baptize you with fire."', false, 8, 'John said the coming One "will baptize you with the Holy Spirit."'),

    // ══════════════════════════════════ v9–11 · The baptism of Jesus
    mc(1, 'Where did Jesus come from when He was baptized by John in the Jordan?', ['Nazareth of Galilee', 'Capernaum of Galilee', 'Bethlehem of Judea', 'Jerusalem of Judea'], 9),
    sa(3, 'When Jesus was baptized, where had He come from, who baptized Him, and in what river?', 'Jesus came from Nazareth of Galilee and was baptized by John in the Jordan.', 9),
    mc(1, 'As Jesus came up from the water after His baptism, what did He see?', ['The heavens parting and the Spirit descending on Him like a dove', 'Fire coming down on the Jordan and a voice like thunder', 'The Spirit descending on John like a dove', 'Angels coming to minister to Him by the river'], 10),
    blank(1, 'And immediately, coming up from the water, He saw the heavens parting and the Spirit descending upon Him like a _____.', 'dove', 10),
    word(1, 'At Jesus’ baptism, the Spirit descended on Him like what bird?', 'dove', 10, ['a dove']),
    mc(1, 'At Jesus’ baptism a voice came from heaven. What did it say?', ['"You are My beloved Son, in whom I am well pleased."', '"This is My Son; hear Him and follow Him."', '"You are the Holy One of God; prepare My way."', '"Behold My messenger, who goes before My face."'], 11),
    blank(2, 'Then a voice came from heaven, "You are My _____ Son, in whom I am well pleased."', 'beloved', 11),
    sa(2, 'At Jesus’ baptism, where did the voice come from and what did it call Him?', 'A voice came from heaven and said, "You are My beloved Son, in whom I am well pleased."', 11),
    tf(3, 'At Jesus’ baptism it was John who declared, "You are My beloved Son, in whom I am well pleased."', false, 11, 'The words came from "a voice from heaven," not from John.'),

    // ══════════════════════════════════ v12–13 · The wilderness
    blank(1, 'Immediately the Spirit drove Him into the _____.', 'wilderness', 12),
    word(2, 'Right after His baptism, who drove Jesus into the wilderness?', 'Spirit', 12, ['the spirit', 'holy spirit', 'the holy spirit']),
    mc(1, 'How long was Jesus in the wilderness being tempted by Satan?', ['Forty days', 'Thirty days', 'Seven days', 'Three days'], 13),
    word(1, 'Who tempted Jesus during His forty days in the wilderness?', 'Satan', 13),
    blank(3, 'And He was there in the wilderness forty days, tempted by Satan, and was with the wild _____; and the angels ministered to Him.', 'beasts', 13),
    sa(3, 'Mark tells the wilderness story in a single verse. Who was with Jesus there, and who ministered to Him?', 'Jesus was tempted by Satan and was with the wild beasts, and the angels ministered to Him.', 13),
    tf(1, 'During His forty days in the wilderness, Jesus was with the wild beasts and the angels ministered to Him.', true, 13),
    tf(2, 'Jesus was in the wilderness thirty days, tempted by Satan.', false, 13, 'He was there forty days.'),

    // ══════════════════════════════════ v14–15 · Jesus begins preaching in Galilee
    mc(1, 'What had happened to John the Baptist by the time Jesus came to Galilee preaching?', ['John had been put in prison', 'John had gone up to Jerusalem', 'John had been baptized by Jesus', 'John had followed Jesus into Galilee'], 14),
    word(2, 'After John was put in prison, to which region did Jesus come, preaching the gospel of the kingdom of God?', 'Galilee', 14),
    tf(3, 'Jesus began preaching in Galilee before John was put in prison.', false, 14, 'Mark says it was "after John was put in prison" that Jesus came to Galilee preaching.'),
    mc(1, 'When Jesus began preaching in Galilee, what two things did He tell people to do?', ['Repent, and believe in the gospel', 'Fast, and pray in the synagogue', 'Confess their sins, and be baptized', 'Leave their nets, and follow Him'], 15),
    blank(2, 'and saying, "The time is fulfilled, and the kingdom of God is at hand. _____, and believe in the gospel."', 'Repent', 15),
    sa(3, 'Sum up Jesus’ first preaching in Galilee: what did He announce, and what did He call people to do?', 'He announced that the time is fulfilled and the kingdom of God is at hand, and He called people to repent and believe in the gospel.', 15),

    // ══════════════════════════════════ v16–20 · Calling the four fishermen
    mc(1, 'Where was Jesus walking when He saw Simon and Andrew casting a net into the sea?', ['By the Sea of Galilee', 'By the Jordan River', 'Through the wilderness of Judea', 'Into Capernaum on the Sabbath'], 16),
    blank(2, 'And as He walked by the Sea of Galilee, He saw Simon and _____ his brother casting a net into the sea; for they were fishermen.', 'Andrew', 16),
    tf(3, 'When Jesus first saw Simon and Andrew, they were in a boat mending their nets.', false, 16, 'Simon and Andrew were casting a net into the sea; it was James and John who were mending nets.'),
    mc(1, 'What did Jesus say to Simon and Andrew as they cast their net into the sea?', ['"Follow Me, and I will make you become fishers of men."', '"Come with Me, and I will teach you to catch men."', '"Leave your nets, and I will give you the kingdom."', '"Follow Me, and you will never fish again."'], 17),
    blank(1, 'Then Jesus said to them, "Follow Me, and I will make you become fishers of _____."', 'men', 17),
    blank(1, 'They immediately left their _____ and followed Him.', 'nets', 18),
    mc(2, 'How did Simon and Andrew respond when Jesus said, "Follow Me"?', ['They immediately left their nets and followed Him', 'They finished hauling in the net and then followed Him', 'They asked to first say goodbye to their father', 'They brought the boat to shore and went with Him'], 18),
    sa(1, 'When Jesus called Simon and Andrew, what did they leave behind and how quickly did they go?', 'They immediately left their nets and followed Him.', 18),
    mc(2, 'A little farther along the Sea of Galilee, whom did Jesus see mending their nets in a boat?', ['James the son of Zebedee and his brother John', 'Simon and his brother Andrew', 'Zebedee and his hired servants', 'Two of the scribes from Capernaum'], 19),
    blank(2, 'When He had gone a little farther from there, He saw James the son of _____, and John his brother, who also were in the boat mending their nets.', 'Zebedee', 19),
    word(2, 'Who was the father of James and John?', 'Zebedee', 19),
    sa(3, 'Contrast what Simon and Andrew were doing with what James and John were doing when Jesus came to them.', 'Simon and Andrew were casting a net into the sea; James and John were in the boat mending their nets.', 19),
    mc(3, 'When Jesus called James and John, whom did they leave behind in the boat?', ['Their father Zebedee with the hired servants', 'Their brothers Simon and Andrew with the nets', 'Their mother with the hired servants', 'Zebedee with the fish they had caught'], 20),
    tf(3, 'James and John left their father Zebedee alone in the boat when they went after Jesus.', false, 20, 'They left Zebedee "in the boat with the hired servants."'),
    sa(2, 'How did James and John respond when Jesus called them from their boat?', 'They immediately left their father Zebedee in the boat with the hired servants and went after Him.', 20),
    mc(2, 'Which four fishermen did Jesus call beside the Sea of Galilee in Mark 1?', ['Simon, Andrew, James, and John', 'Simon, Andrew, Philip, and Nathanael', 'James, John, Matthew, and Thomas', 'Andrew, Philip, James, and Levi'], 19),

    // ══════════════════════════════════ v21–28 · The synagogue at Capernaum
    mc(1, 'After calling the four fishermen, where did Jesus go, and what did He do there on the Sabbath?', ['He went into Capernaum and taught in the synagogue', 'He went into Nazareth and preached by the sea', 'He went up to Jerusalem and taught in the temple', 'He went into the wilderness and prayed'], 21),
    blank(1, 'Then they went into _____, and immediately on the Sabbath He entered the synagogue and taught.', 'Capernaum', 21),
    word(2, 'In which town did Jesus teach in the synagogue on the Sabbath and cast out an unclean spirit?', 'Capernaum', 21),
    mc(2, 'Why were the people in the Capernaum synagogue astonished at Jesus’ teaching?', ['He taught as one having authority, and not as the scribes', 'He taught from the Prophets, and not from the Law', 'He taught in parables the scribes had never heard', 'He taught in the speech of Galilee, not of Jerusalem'], 22),
    blank(2, 'And they were astonished at His teaching, for He taught them as one having _____, and not as the scribes.', 'authority', 22),
    word(3, 'In the Capernaum synagogue, Jesus taught "as one having authority, and not as the ___."', 'scribes', 22),
    sa(2, 'How did the people react to Jesus’ teaching in the Capernaum synagogue, and why?', 'They were astonished, because He taught them as one having authority and not as the scribes.', 22),
    mc(2, 'While Jesus was teaching in the Capernaum synagogue, who cried out?', ['A man with an unclean spirit', 'A leper asking to be made clean', 'Simon’s wife’s mother, sick with a fever', 'One of the scribes'], 23),
    tf(1, 'In the Capernaum synagogue there was a man with an unclean spirit, and he cried out.', true, 23),
    mc(2, 'What did the unclean spirit in the Capernaum synagogue call Jesus?', ['"the Holy One of God"', '"the Son of David"', '"the King of Israel"', '"the Prophet of Galilee"'], 24),
    mc(3, 'What question did the unclean spirit in the synagogue put to Jesus?', ['"Did You come to destroy us?"', '"Did You come to judge us?"', '"Why have You come before the time?"', '"Are You the One who is to come?"'], 24),
    blank(2, 'saying, "Let us alone! What have we to do with You, Jesus of _____? Did You come to destroy us? I know who You are—the Holy One of God!"', 'Nazareth', 24),
    word(3, 'The unclean spirit in the synagogue addressed Jesus as "Jesus of ___."', 'Nazareth', 24),
    sa(3, 'What did the unclean spirit cry out to Jesus in the Capernaum synagogue?', '"Let us alone! What have we to do with You, Jesus of Nazareth? Did You come to destroy us? I know who You are—the Holy One of God!"', 24),
    tf(3, 'The unclean spirit in the synagogue said to Jesus, "I know who You are—the Son of David!"', false, 24, 'It said, "I know who You are—the Holy One of God!"'),
    mc(3, 'In Mark 1 the voice from heaven and the unclean spirit each give Jesus a title. Which pair is right?', ['"My beloved Son" and "the Holy One of God"', '"My chosen Servant" and "the Son of David"', '"the Son of Man" and "the Holy One of Israel"', '"My beloved Son" and "the King of the Jews"'], 24),
    mc(1, 'How did Jesus answer the unclean spirit that cried out in the synagogue?', ['He rebuked it: "Be quiet, and come out of him!"', 'He asked it: "What is your name?"', 'He said: "Go, and tell no one who I am."', 'He said: "Your faith has made you clean."'], 25),
    blank(1, 'But Jesus rebuked him, saying, "Be _____, and come out of him!"', 'quiet', 25),
    mc(2, 'What happened to the man in the synagogue as the unclean spirit came out of him?', ['The spirit convulsed him and cried out with a loud voice', 'He fell to the ground as though dead, then stood up', 'He was thrown into the fire and pulled out', 'He lay still and silent until Jesus lifted him'], 26),
    blank(3, 'And when the unclean spirit had _____ him and cried out with a loud voice, he came out of him.', 'convulsed', 26),
    sa(3, 'After Jesus said, "Be quiet, and come out of him!", what did the unclean spirit do?', 'It convulsed the man, cried out with a loud voice, and came out of him.', 26),
    mc(2, 'After Jesus cast out the unclean spirit in the synagogue, what did the amazed people ask one another?', ['"What is this? What new doctrine is this?"', '"Is this not the carpenter’s son?"', '"Who then can be saved?"', '"Where did this Man get such wisdom?"'], 27),
    blank(3, 'Then they were all amazed, so that they questioned among themselves, saying, "What is this? What new _____ is this? For with authority He commands even the unclean spirits, and they obey Him."', 'doctrine', 27),
    sa(3, 'In the Capernaum synagogue, why did the crowd call Jesus’ teaching a "new doctrine"?', 'Because with authority He commanded even the unclean spirits, and they obeyed Him.', 27),
    mc(2, 'What was the result of Jesus casting out the unclean spirit in Capernaum?', ['His fame spread throughout all the region around Galilee', 'The scribes came from Jerusalem to question Him', 'The whole city followed Him back to Nazareth', 'The healed man went to tell the priests in Jerusalem'], 28),
    blank(1, 'And immediately His fame spread throughout all the region around _____.', 'Galilee', 28),

    // ══════════════════════════════════ v29–34 · Simon’s house
    mc(1, 'After Jesus healed the man with the unclean spirit in the Capernaum synagogue, whose house did He go to?', ['The house of Simon and Andrew', 'The house of James and John', 'The house of Zebedee', 'The house of the ruler of the synagogue'], 29),
    word(3, 'Leaving the Capernaum synagogue, Jesus went with James and John into the house of Simon and whom?', 'Andrew', 29),
    tf(2, 'From the Capernaum synagogue Jesus went to the house of James and John.', false, 29, 'They entered "the house of Simon and Andrew, with James and John."'),
    mc(1, 'Who lay sick in the house of Simon and Andrew when Jesus arrived?', ['Simon’s wife’s mother, with a fever', 'Simon’s daughter, with a fever', 'Andrew’s wife, with leprosy', 'Zebedee, the father of James and John'], 30),
    blank(1, 'But Simon’s wife’s mother lay sick with a _____, and they told Him about her at once.', 'fever', 30),
    tf(2, 'It was Andrew’s wife’s mother who lay sick with a fever in the house.', false, 30, 'It was Simon’s wife’s mother.'),
    mc(2, 'How did Jesus heal Simon’s wife’s mother?', ['He took her by the hand and lifted her up, and the fever left her', 'He spoke a word from the doorway, and the fever left her', 'He laid His hands on her head and prayed, and she rose', 'He commanded the fever to leave, and it obeyed Him'], 31),
    blank(3, 'So He came and took her by the hand and lifted her up, and immediately the fever left her. And she _____ them.', 'served', 31),
    word(3, 'After her fever left, what did Simon’s wife’s mother do for Jesus and those with Him?', 'served', 31, ['served them', 'serve', 'serving']),
    sa(3, 'Walk through the healing of Simon’s wife’s mother: what did Jesus do, what happened, and what did she do next?', 'Jesus took her by the hand and lifted her up; immediately the fever left her, and she served them.', 31),
    mc(3, 'When did the people of Capernaum bring their sick and demon-possessed to Jesus at Simon’s house?', ['At evening, when the sun had set', 'In the morning, before daylight', 'At noon on the Sabbath', 'At the third hour of the day'], 32),
    tf(3, 'The people brought their sick to Jesus at Simon’s house at noon.', false, 32, 'They came "at evening, when the sun had set."'),
    sa(2, 'Whom did the people bring to Jesus that evening after the sun had set?', 'They brought all who were sick and those who were demon-possessed.', 32),
    blank(1, 'And the whole _____ was gathered together at the door.', 'city', 33),
    tf(2, 'On the evening after the synagogue healing, Mark says the whole city was gathered together at the door.', true, 33),
    mc(3, 'That evening in Capernaum, why did Jesus not allow the demons to speak?', ['Because they knew Him', 'Because they were lying', 'Because it was the Sabbath', 'Because the crowd was afraid'], 34),
    blank(3, 'Then He healed many who were sick with various diseases, and cast out many demons; and He did not allow the demons to _____, because they knew Him.', 'speak', 34),
    sa(2, 'What did Jesus do for the crowd at Simon’s door that evening, and what did He forbid?', 'He healed many who were sick with various diseases and cast out many demons, and He did not allow the demons to speak because they knew Him.', 34),
    tf(3, 'Jesus let the demons speak that evening so the crowd would learn who He was.', false, 34, 'He "did not allow the demons to speak, because they knew Him."'),

    // ══════════════════════════════════ v35–39 · Prayer before daylight, then the next towns
    mc(1, 'The morning after healing the crowds in Capernaum, what did Jesus do?', ['He rose before daylight and went to a solitary place to pray', 'He returned to the synagogue and continued teaching the crowds','He walked beside the Sea of Galilee to call more disciples','He remained in the city and healed the leper who approached Him'], 35),
    blank(3, 'Now in the morning, having risen a long while before daylight, He went out and departed to a _____ place; and there He prayed.', 'solitary', 35),
    word(2, 'What did Jesus do in the solitary place He went to before daylight?', 'prayed', 35, ['pray', 'he prayed', 'praying']),
    tf(1, 'Jesus rose a long while before daylight and went out to a solitary place to pray.', true, 35),
    blank(3, 'And _____ and those who were with Him searched for Him.', 'Simon', 36),
    tf(2, 'Simon and those with him searched for Jesus when He had gone off to pray.', true, 36),
    mc(1, 'When Simon and the others found Jesus praying in the solitary place, what did they tell Him?', ['"Everyone is looking for You."', '"The whole city is at the door."', '"Why have You left us?"', '"Come, the Sabbath has begun."'], 37),
    blank(1, 'When they found Him, they said to Him, "_____ is looking for You."', 'Everyone', 37),
    sa(1, 'What did Simon and the others say when they found Jesus in the solitary place?', 'They said to Him, "Everyone is looking for You."', 37),
    mc(2, 'When told "Everyone is looking for You," how did Jesus answer?', ['"Let us go into the next towns, that I may preach there also"', '"Let us return to Capernaum, that I may heal them all"', '"Let us go up to Jerusalem, for My time has come"', '"Send them away, for I must pray alone"'], 38),
    blank(2, 'But He said to them, "Let us go into the next towns, that I may _____ there also, because for this purpose I have come forth."', 'preach', 38),
    sa(3, 'Why did Jesus say He would go on to the next towns rather than return to the crowd waiting in Capernaum?', 'He said He must preach in the next towns also, "because for this purpose I have come forth."', 38),
    tf(3, 'Jesus told Simon they should go back to Capernaum, since everyone there was looking for Him.', false, 38, 'He said, "Let us go into the next towns, that I may preach there also."'),
    mc(2, 'After leaving Capernaum, what two things was Jesus doing throughout all Galilee?', ['Preaching in their synagogues and casting out demons', 'Baptizing in the Jordan and cleansing lepers', 'Teaching by the sea and calling fishermen', 'Praying in solitary places and fasting'], 39),
    blank(1, 'And He was preaching in their _____ throughout all Galilee, and casting out demons.', 'synagogues', 39),

    // ══════════════════════════════════ v40–45 · The leper
    mc(1, 'What did the leper say to Jesus as he knelt before Him?', ['"If You are willing, You can make me clean."', '"Lord, have mercy on me, a sinner."', '"Son of David, heal me."', '"Only speak a word and I will be healed."'], 40),
    blank(1, 'Now a leper came to Him, imploring Him, kneeling down to Him and saying to Him, "If You are willing, You can make me _____."', 'clean', 40),
    word(1, 'A man with what disease came kneeling before Jesus and imploring Him to make him clean?', 'leprosy', 40, ['leper']),
    sa(2, 'How did the leper approach Jesus, and what did he ask?', 'He came imploring Jesus and kneeling down before Him, saying, "If You are willing, You can make me clean."', 40),
    mc(2, 'How did Jesus respond to the leper who said, "If You are willing, You can make me clean"?', ['Moved with compassion, He touched him and said, "I am willing; be cleansed"', 'He refused to touch him and immediately sent him away to the priest','He rebuked the man publicly and commanded him to remain silent','He directed the man to wash seven times in the Jordan River'], 41),
    blank(3, 'Then Jesus, moved with _____, stretched out His hand and touched him, and said to him, "I am willing; be cleansed."', 'compassion', 41),
    word(2, 'Jesus was moved with what when the leper knelt before Him?', 'compassion', 41),
    tf(2, 'Jesus cleansed the leper without touching him.', false, 41, 'Jesus "stretched out His hand and touched him."'),
    blank(3, 'As soon as He had spoken, immediately the _____ left him, and he was cleansed.', 'leprosy', 42),
    tf(1, 'The leprosy left the man immediately, as soon as Jesus had spoken.', true, 42),
    blank(3, 'And He strictly _____ him and sent him away at once,', 'warned', 43),
    tf(2, 'After cleansing the leper, Jesus strictly warned him and sent him away at once.', true, 43),
    mc(2, 'What did Jesus command the cleansed leper to do?', ['Tell no one, but show himself to the priest and offer what Moses commanded', 'Tell everyone throughout the city what God had done for him','Follow Jesus immediately and become one of His twelve disciples','Return to his home and wash himself seven times in the Jordan'], 44),
    blank(2, 'and said to him, "See that you say nothing to anyone; but go your way, show yourself to the _____, and offer for your cleansing those things which Moses commanded, as a testimony to them."', 'priest', 44),
    word(3, 'Jesus told the cleansed leper to offer for his cleansing the things that whom had commanded?', 'Moses', 44),
    sa(3, 'Jesus gave the cleansed leper three instructions. What were they?', 'Say nothing to anyone; go show himself to the priest; and offer for his cleansing the things Moses commanded, as a testimony to them.', 44),
    tf(2, 'Jesus told the cleansed leper to go and tell everyone what had happened to him.', false, 44, 'He said, "See that you say nothing to anyone."'),
    mc(2, 'What did the cleansed leper do after Jesus told him to say nothing to anyone?', ['He went out and proclaimed it freely, spreading the matter', 'He went quietly to the priest as he was told', 'He followed Jesus into the next towns', 'He returned to the synagogue in Capernaum'], 45),
    blank(3, 'However, he went out and began to _____ it freely, and to spread the matter, so that Jesus could no longer openly enter the city, but was outside in deserted places; and they came to Him from every direction.', 'proclaim', 45),
    sa(3, 'What was the consequence for Jesus when the cleansed leper spread the news freely?', 'Jesus could no longer openly enter the city but stayed outside in deserted places, and people came to Him from every direction.', 45),
    tf(2, 'Because the cleansed leper spread the news, Jesus could no longer openly enter the city.', true, 45),
    tf(3, 'After the leper spread the news, the crowds stopped coming to Jesus.', false, 45, 'Though He stayed in deserted places, "they came to Him from every direction."'),
    word(3, 'When Jesus could no longer openly enter the city, He stayed outside in what kind of places?', 'deserted', 45, ['deserted places', 'desert']),
  ],
};

export default bank;
