import { mc, blank, word, tf, type ChapterBank, sa } from './types'

const bank: ChapterBank = { book: 'Mark', chapter: 1, tag: 'quiz-v2-mark-1', rows: [
  mc(1, 'Whose gospel begins in Mark 1?', ['Jesus Christ, the Son of God', 'John the Baptist', 'Simon and Andrew', 'James and John'], 1),
  blank(2, 'The beginning of the gospel of Jesus Christ, the _____ of God.', 'Son', 1),
  blank(1, 'Behold, I send My messenger _____, Who will prepare Your way before You.', 'before Your face', 2, ['before your face']),
  tf(3, 'The messenger would prepare the Lord’s way.', true, 2),
  mc(1, 'Where was the crying voice heard?', ['In the wilderness', 'In the synagogue', 'Beside the sea', 'In Jerusalem'], 3),
  tf(2, 'The voice called people to make the Lord’s paths crooked.', false, 3, 'The voice said to make His paths straight.'),
  blank(1, 'John came baptizing in the wilderness and preaching a baptism of _____ for the remission of sins.', 'repentance', 4),
  sa(2, 'What did John preach for the remission of sins?', 'a baptism of repentance', 4, ['baptism of repentance']),
  mc(1, 'Where did John baptize those confessing their sins?', ['In the Jordan River', 'In the Sea of Galilee', 'In Jerusalem', 'In Capernaum'], 5),
  tf(3, 'People from Judea and Jerusalem went out to John.', true, 5),
  blank(2, 'Now John was clothed with camel’s hair and with a _____ belt around his waist', 'leather', 6),
  sa(1, 'What two foods did John eat?', 'locusts and wild honey', 6),
  mc(2, 'How did John compare himself with the One coming after him?', ['He was not worthy to loosen His sandal strap', 'He was more powerful than Him', 'He was His earthly king', 'He was called to teach Him'], 7),
  tf(1, 'John said the One coming after him was mightier than he was.', true, 7),
  blank(1, 'I indeed baptized you with water, but He will baptize you with the _____.', 'Holy Spirit', 8),
  word(3, 'With what did John baptize?', 'water', 8),
  mc(1, 'From where did Jesus come to be baptized?', ['Nazareth of Galilee', 'Jerusalem of Judea', 'Capernaum', 'The wilderness'], 9),
  tf(2, 'John baptized Jesus in the Jordan.', true, 9),
  blank(2, 'He saw the heavens parting and the Spirit descending upon Him like a _____.', 'dove', 10),
  sa(1, 'What did Jesus see parting as He came from the water?', 'the heavens', 10, ['heavens']),
  mc(1, 'What did the voice from heaven call Jesus?', ['My beloved Son', 'A mighty prophet', 'The new scribe', 'John’s disciple'], 11),
  tf(3, 'The heavenly voice said it was well pleased with Jesus.', true, 11),
  blank(1, 'Immediately the Spirit drove Him into the _____.', 'wilderness', 12),
  word(2, 'Who drove Jesus into the wilderness?', 'the Spirit', 12, ['Spirit']),
  mc(2, 'How long was Jesus tempted in the wilderness?', ['Forty days', 'Seven days', 'Three days', 'Twelve days'], 13),
  tf(1, 'Angels ministered to Jesus while He was in the wilderness.', true, 13),
  blank(2, 'Jesus came to Galilee, preaching the gospel of the _____ of God', 'kingdom', 14),
  sa(3, 'What had happened to John before Jesus came preaching in Galilee?', 'he was put in prison', 14, ['put in prison', 'imprisoned']),
  mc(1, 'What two responses did Jesus command when announcing God’s kingdom?', ['Repent and believe in the gospel', 'Fast and leave Galilee', 'Build a synagogue and teach', 'Confess to the scribes and priests'], 15),
  tf(2, 'Jesus announced that the kingdom of God was at hand.', true, 15),
  blank(1, 'He saw Simon and Andrew his brother casting a _____ into the sea', 'net', 16),
  word(2, 'What was the occupation of Simon and Andrew?', 'fishermen', 16),
  mc(1, 'What did Jesus promise to make Simon and Andrew?', ['Fishers of men', 'Rulers of Galilee', 'Teachers of scribes', 'Keepers of the synagogue'], 17),
  tf(3, 'Jesus first told Simon and Andrew to remain with their nets.', false, 17, 'He told them, “Follow Me.”'),
  blank(2, 'They immediately left their nets and _____ Him.', 'followed', 18),
  sa(1, 'What did Simon and Andrew leave behind?', 'their nets', 18, ['nets']),
  mc(2, 'What were James and John doing when Jesus saw them?', ['Mending their nets in the boat', 'Casting a net into the sea', 'Teaching in the synagogue', 'Walking toward Jerusalem'], 19),
  tf(1, 'James and John were sons of Zebedee.', true, 19),
  blank(1, 'they left their father Zebedee in the boat with the _____ servants', 'hired', 20),
  sa(3, 'Whom did James and John leave in the boat?', 'their father Zebedee', 20, ['Zebedee']),
  mc(1, 'Where did Jesus teach on the Sabbath?', ['In the synagogue at Capernaum', 'On a boat in Nazareth', 'In the temple at Jerusalem', 'In the wilderness'], 21),
  tf(2, 'Jesus entered the synagogue and taught on the Sabbath.', true, 21),
  blank(2, 'He taught them as one having _____, and not as the scribes.', 'authority', 22),
  sa(1, 'How did the listeners react to Jesus’ teaching?', 'they were astonished', 22, ['astonished']),
  mc(1, 'What afflicted the man in the synagogue?', ['An unclean spirit', 'A fever', 'Leprosy', 'Blindness'], 23),
  tf(3, 'The man with the unclean spirit remained silent.', false, 23, 'He cried out.'),
  blank(3, 'I know who You are—the _____ One of God!', 'Holy', 24),
  word(2, 'What name did the spirit use for Jesus?', 'Jesus of Nazareth', 24),
  mc(1, 'What two commands did Jesus give the unclean spirit?', ['Be quiet and come out of him', 'Rise and walk', 'Go show yourself to the priest', 'Follow Me and preach'], 25),
  tf(2, 'Jesus encouraged the unclean spirit to keep speaking.', false, 25, 'Jesus told it to be quiet and come out.'),
  blank(2, 'the unclean spirit had convulsed him and cried out with a loud voice, he came _____ of him.', 'out', 26),
  sa(1, 'What did the unclean spirit do to the man before leaving?', 'convulsed him', 26, ['convulsed']),
  mc(2, 'Why were the people amazed?', ['Jesus commanded unclean spirits with authority and they obeyed', 'The scribes expelled the spirit', 'The synagogue closed early', 'The man began teaching'], 27),
  tf(1, 'The people described Jesus’ teaching as new doctrine.', true, 27),
  blank(1, 'His _____ spread throughout all the region around Galilee.', 'fame', 28),
  word(3, 'How quickly did Jesus’ fame spread?', 'immediately', 28),
  mc(1, 'Whose house did Jesus enter after leaving the synagogue?', ['Simon and Andrew’s', 'James and John’s', 'Zebedee’s', 'The leper’s'], 29),
  tf(2, 'James and John went with Jesus to Simon and Andrew’s house.', true, 29),
  blank(2, 'Simon’s wife’s mother lay sick with a _____.', 'fever', 30),
  sa(1, 'Whose illness was reported to Jesus?', 'Simon’s wife’s mother', 30, ['Simon’s mother-in-law', 'Simons mother-in-law']),
  mc(1, 'What happened when Jesus lifted Simon’s mother-in-law by the hand?', ['The fever left her and she served them', 'She went to the synagogue', 'She remained in bed', 'She left Capernaum'], 31),
  tf(3, 'Simon’s mother-in-law began serving them after the fever left.', true, 31),
  blank(1, 'At evening, when the sun had set, they brought to Him all who were sick and those who were _____.', 'demon-possessed', 32),
  sa(2, 'When were the sick brought to Jesus?', 'at evening, when the sun had set', 32, ['at evening', 'when the sun had set']),
  mc(1, 'Where did the whole city gather?', ['At the door', 'At the seashore', 'At the synagogue', 'At the city gate'], 33),
  tf(2, 'Only a few relatives gathered at the door.', false, 33, 'The whole city gathered there.'),
  blank(2, 'He did not allow the demons to speak, because they _____ Him.', 'knew', 34),
  sa(3, 'What kinds of illnesses did Jesus heal?', 'various diseases', 34),
  mc(1, 'Where did Jesus go to pray before daylight?', ['A solitary place', 'The synagogue', 'Simon’s house', 'The seashore'], 35),
  tf(3, 'Jesus rose a long while before daylight to pray.', true, 35),
  blank(1, 'And Simon and those who were with Him _____ for Him.', 'searched', 36),
  word(2, 'Who led those searching for Jesus?', 'Simon', 36),
  mc(1, 'What did the searchers tell Jesus?', ['Everyone is looking for You', 'The synagogue is empty', 'John has been released', 'The fishermen returned home'], 37),
  tf(2, 'Simon’s group failed to find Jesus.', false, 37, 'They found Him and spoke to Him.'),
  blank(2, 'Let us go into the next towns, that I may _____ there also', 'preach', 38),
  sa(1, 'Why did Jesus say He had come forth?', 'to preach in the next towns', 38, ['to preach', 'that I may preach there also']),
  mc(2, 'What two things did Jesus do throughout Galilee?', ['Preached in synagogues and cast out demons', 'Built synagogues and appointed scribes', 'Baptized in the Jordan and stayed in Nazareth', 'Healed only in Simon’s house'], 39),
  tf(1, 'Jesus preached in synagogues throughout Galilee.', true, 39),
  blank(1, 'If You are willing, You can make me _____.', 'clean', 40),
  sa(3, 'What did the leper do as he implored Jesus?', 'knelt down', 40, ['kneeling down', 'knelt']),
  mc(1, 'What moved Jesus before He touched the leper?', ['Compassion', 'Anger', 'Fear', 'Surprise'], 41),
  tf(2, 'Jesus said, “I am willing; be cleansed.”', true, 41),
  blank(2, 'immediately the leprosy left him, and he was _____.', 'cleansed', 42),
  sa(1, 'When did the leprosy leave the man?', 'as soon as Jesus had spoken', 42, ['as soon as He had spoken', 'immediately']),
  mc(1, 'How did Jesus send the cleansed man away?', ['At once, after strictly warning him', 'Without speaking to him', 'With Simon and Andrew', 'Only after many days'], 43),
  tf(3, 'Jesus gave the man no warning before sending him away.', false, 43, 'Jesus strictly warned him.'),
  blank(3, 'show yourself to the priest, and offer for your cleansing those things which _____ commanded', 'Moses', 44),
  sa(2, 'To whom was the cleansed man told to show himself?', 'the priest', 44, ['priest']),
  mc(3, 'What happened after the cleansed man spread the news freely?', ['Jesus could no longer openly enter the city', 'Jesus returned permanently to Nazareth', 'The crowds stopped coming', 'The synagogues expelled Simon'], 45),
  tf(1, 'People came to Jesus from every direction while He stayed in deserted places.', true, 45),
] };

export default bank;
