// Mark 4 — quiz bank (NKJV, Orthodox Study Bible text as stored). Every row is anchored
// to a verse; fill-in-the-blank rows are verified against the stored verse text by
// scripts/seed-quiz-bank.ts. Questions are framed in the story (who, where, what followed),
// never as a single clause turned inside out.
import { mc, blank, word, tf, sa, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: 'Mark',
  chapter: 4,
  tag: 'quiz-v2-mark-4',
  rows: [
    // ══════════════════════════════════ v1–2 · Teaching by the sea from a boat
    mc(1, 'When Jesus began to teach by the sea again and a great multitude gathered, where did He sit to teach them?', ['In a boat on the sea', 'On a mountain above the shore', 'In the synagogue near the shore', 'In a house in Capernaum'], 1),
    blank(2, 'And a great multitude was gathered to Him, so that He got into a _____ and sat in it on the sea; and the whole multitude was on the land facing the sea.', 'boat', 1),
    tf(1, 'When Jesus taught by the sea, the whole multitude was on the land facing the sea while He sat in a boat.', true, 1),
    sa(2, 'Why did Jesus get into a boat when He began to teach by the sea again?', 'A great multitude had gathered to Him, so He got into a boat and sat in it on the sea while the whole multitude stood on the land facing the sea.', 1),
    word(1, 'When Jesus taught the great multitude from the boat, He taught them many things by what?', 'parables', 2, ['parable']),

    // ══════════════════════════════════ v3–9 · The parable of the sower
    mc(2, 'With what single word did Jesus begin the parable of the sower before the multitude?', ['"Listen!"', '"Behold!"', '"Hear!"', '"Take heed!"'], 3, 'He said, "Listen! Behold, a sower went out to sow."'),
    blank(1, '"Listen! Behold, a _____ went out to sow.', 'sower', 3),
    word(1, 'In the parable Jesus told from the boat, who went out to sow?', 'sower', 3, ['a sower', 'the sower']),
    mc(1, 'In the parable of the sower, what happened to the seed that fell by the wayside?', ['The birds of the air came and devoured it', 'The sun scorched it and it withered away', 'The thorns grew up and choked it', 'It sprang up at once because it had no depth of earth'], 4),
    blank(2, 'And it happened, as he sowed, that some seed fell by the _____; and the birds of the air came and devoured it.', 'wayside', 4),
    tf(1, 'In the parable of the sower, the seed that fell by the wayside was devoured by the birds of the air.', true, 4),
    word(2, 'In the parable of the sower, what creatures devoured the seed that fell by the wayside?', 'birds', 4, ['the birds', 'birds of the air', 'the birds of the air']),
    mc(2, 'In the parable of the sower, why did the seed on stony ground spring up immediately?', ['Because it had no depth of earth', 'Because the sun was already up', 'Because it had root in itself', 'Because the earth yields crops by itself'], 5),
    blank(1, 'Some fell on _____ ground, where it did not have much earth; and immediately it sprang up because it had no depth of earth.', 'stony', 5),
    sa(2, 'In the parable of the sower, what happened to the seed that fell on stony ground when it was first sown?', 'It sprang up immediately, because the stony ground did not have much earth and the seed had no depth of earth.', 5),
    mc(1, 'In the parable of the sower, what happened to the seed on stony ground once the sun was up?', ['It was scorched, and because it had no root it withered away', 'It was choked by the thorns and yielded no crop', 'It increased and produced some thirtyfold', 'It was carried off by the birds of the air'], 6),
    blank(2, 'But when the sun was up it was scorched, and because it had no _____ it withered away.', 'root', 6),
    tf(2, 'In the parable of the sower, the seed on stony ground withered away because the thorns choked it.', false, 6, 'It was scorched when the sun was up and withered because it had no root; the thorns choked the seed that fell among them.'),
    word(1, 'In the parable of the sower, what scorched the plant that had sprung up on stony ground?', 'sun', 6, ['the sun']),
    mc(1, 'In the parable of the sower, what became of the seed that fell among thorns?', ['The thorns grew up and choked it, and it yielded no crop', 'It was scorched by the sun and withered away', 'It sprang up immediately and produced a hundredfold', 'The birds of the air came and nested in it'], 7),
    blank(1, 'And some seed fell among _____; and the thorns grew up and choked it, and it yielded no crop.', 'thorns', 7),
    tf(1, 'In the parable of the sower, the seed that fell among thorns still yielded a small crop.', false, 7, 'The thorns grew up and choked it, "and it yielded no crop."'),
    mc(2, 'In the parable of the sower, how much did the seed on good ground produce?', ['Some thirtyfold, some sixty, and some a hundred', 'Some tenfold, some fifty, and some a hundred', 'Some twentyfold, some forty, and some eighty', 'Some sixtyfold, some eighty, and some a thousand'], 8),
    blank(2, 'But other seed fell on good ground and yielded a crop that sprang up, increased and produced: some _____, some sixty, and some a hundred."', 'thirtyfold', 8, ['thirty', '30']),
    word(2, 'In the parable of the sower, the good ground produced thirtyfold, sixty, and at most how much?', 'hundred', 8, ['a hundred', '100', 'hundredfold']),
    tf(2, 'In the parable of the sower, the largest yield from the good ground was sixtyfold.', false, 8, 'The good ground produced "some thirtyfold, some sixty, and some a hundred."'),
    sa(1, 'In the parable of the sower, which soil produced a crop, and how much did it yield?', 'The good ground; the crop sprang up, increased and produced some thirtyfold, some sixty, and some a hundred.', 8),
    blank(1, 'And He said to them, "He who has _____ to hear, let him hear!"', 'ears', 9),
    mc(2, 'How did Jesus close the parable of the sower before the crowd?', ['"He who has ears to hear, let him hear!"', '"Take heed what you hear."', '"Do you not understand this parable?"', '"Why are you so fearful?"'], 9),

    // ══════════════════════════════════ v10–13 · Alone with the twelve: why parables?
    mc(2, 'Who asked Jesus about the parable of the sower when He was alone?', ['Those around Him with the twelve', 'The great multitude on the shore', 'The scribes who came down from Jerusalem', 'His mother and His brothers'], 10),
    blank(3, 'But when He was alone, those around Him with the _____ asked Him about the parable.', 'twelve', 10, ['12']),
    tf(2, 'Those around Jesus with the twelve asked Him about the parable of the sower while the multitude was still listening.', false, 10, 'They asked Him "when He was alone."'),
    mc(2, 'When the twelve asked about the parable, what did Jesus say had been given to them?', ['To know the mystery of the kingdom of God', 'To speak the word in parables to those outside', 'To bear fruit some thirtyfold, sixty, and a hundred', 'To have more measured to them than they used'], 11),
    blank(2, 'And He said to them, "To you it has been given to know the _____ of the kingdom of God; but to those who are outside, all things come in parables,', 'mystery', 11),
    word(3, 'Jesus told the twelve that to "those who are outside," all things come in what?', 'parables', 11),
    sa(3, 'According to Jesus, how do the twelve and "those who are outside" differ in how the kingdom of God comes to them?', 'To the twelve it has been given to know the mystery of the kingdom of God, but to those who are outside all things come in parables.', 11),
    blank(3, 'so that \'Seeing they may see and not _____, And hearing they may hear and not understand; Lest they should turn, And their sins be forgiven them.\'', 'perceive', 12),
    mc(3, 'In the saying Jesus quoted about those who are outside, what two failures did He describe?', ['Seeing without perceiving, and hearing without understanding', 'Sowing without reaping, and planting without watering', 'Hearing the word gladly, and stumbling when persecution comes', 'Sleeping by night and rising by day, not knowing how the seed grows'], 12),
    word(3, 'In the quotation about those outside, what did Jesus say would be forgiven them if they should turn?', 'sins', 12, ['their sins']),
    mc(2, 'What did Jesus ask the disciples just before He explained the parable of the sower?', ['"Do you not understand this parable? How then will you understand all the parables?"', '"Why are you so fearful in this storm? How is it that you still have no faith?"','"To what shall we liken the kingdom of God, and with what parable shall we picture it?"','"Is a lamp brought to be put under a basket or beneath a bed instead of on a lampstand?"'], 13),
    sa(3, 'When the disciples did not understand the parable of the sower, what two questions did Jesus put to them?', '"Do you not understand this parable? How then will you understand all the parables?"', 13),

    // ══════════════════════════════════ v14–20 · The explanation of the sower
    word(1, 'In Jesus\' explanation of the parable of the sower, what does the sower sow?', 'word', 14, ['the word']),
    blank(1, 'The sower sows the _____.', 'word', 14),
    mc(2, 'In Jesus\' explanation of the parable of the sower, what does the seed stand for?', ['The word', 'The kingdom of God', 'The mystery', 'The harvest'], 14),
    mc(1, 'In Jesus\' explanation, who takes away the word from the ones sown by the wayside?', ['Satan, who comes immediately', 'The birds of the air that devour it', 'Tribulation that arises for the word\'s sake', 'The cares of this world entering in'], 15),
    blank(2, 'When they hear, _____ comes immediately and takes away the word that was sown in their hearts.', 'Satan', 15),
    sa(2, 'In Jesus\' explanation, what happens to the ones by the wayside when they hear the word?', 'Satan comes immediately and takes away the word that was sown in their hearts.', 15),
    tf(1, 'In Jesus\' explanation, Satan comes immediately and takes away the word sown in the hearts of the ones by the wayside.', true, 15),
    word(3, 'In Jesus\' explanation, from where does Satan take away the word sown in the ones by the wayside?', 'hearts', 15, ['their hearts', 'heart']),
    mc(2, 'In Jesus\' explanation, how do the ones sown on stony ground first respond to the word?', ['They immediately receive it with gladness', 'They hear it, but Satan takes it away at once', 'They accept it and bear fruit a hundredfold', 'They let the cares of this world choke it'], 16),
    blank(3, 'These likewise are the ones sown on stony ground who, when they hear the word, immediately receive it with _____;', 'gladness', 16),
    word(2, 'In Jesus\' explanation, the ones sown on stony ground immediately receive the word with what?', 'gladness', 16),
    mc(2, 'In Jesus\' explanation, why do the ones sown on stony ground endure only for a time?', ['They have no root in themselves', 'Satan takes the word from their hearts', 'The deceitfulness of riches chokes the word', 'They see and do not perceive'], 17),
    blank(3, 'Afterward, when tribulation or _____ arises for the word\'s sake, immediately they stumble.', 'persecution', 17),
    sa(3, 'In Jesus\' explanation, what makes the ones sown on stony ground stumble, and why?', 'When tribulation or persecution arises for the word\'s sake they immediately stumble, because they have no root in themselves and endure only for a time.', 17),
    tf(3, 'In Jesus\' explanation, the ones sown on stony ground stumble when the deceitfulness of riches enters in.', false, 17, 'They stumble when tribulation or persecution arises for the word\'s sake; the deceitfulness of riches belongs to the ones sown among thorns.'),
    blank(2, 'Now these are the ones sown among _____; they are the ones who hear the word,', 'thorns', 18),
    mc(2, 'In Jesus\' explanation, what chokes the word in the ones sown among thorns?', ['Worldly cares, deceitful riches, and desires for other things','Tribulation and persecution arising because of the word','Satan coming immediately and taking away the sown word','The scorching sun exposing that the plants have no root'], 19),
    blank(3, 'and the cares of this world, the deceitfulness of _____, and the desires for other things entering in choke the word, and it becomes unfruitful.', 'riches', 19),
    word(3, 'In Jesus\' explanation, when the word among thorns is choked, what does it become?', 'unfruitful', 19),
    sa(3, 'In Jesus\' explanation, name the three things that enter in and choke the word in the ones sown among thorns.', 'The cares of this world, the deceitfulness of riches, and the desires for other things.', 19),
    tf(2, 'In Jesus\' explanation, the cares of this world and the deceitfulness of riches choke the word so that it becomes unfruitful.', true, 19),
    mc(1, 'In Jesus\' explanation, what do the ones sown on good ground do with the word?', ['They hear it, accept it, and bear fruit', 'They hear it and receive it with gladness for a time', 'They hear it, but the cares of this world choke it', 'They hear it, and Satan immediately takes it away'], 20),
    blank(3, 'But these are the ones sown on good ground, those who hear the word, _____ it, and bear fruit: some thirtyfold, some sixty, and some a hundred."', 'accept', 20),
    sa(1, 'In Jesus\' explanation of the parable, who are the ones sown on good ground?', 'Those who hear the word, accept it, and bear fruit — some thirtyfold, some sixty, and some a hundred.', 20),
    tf(1, 'In Jesus\' explanation, the ones sown on good ground hear the word, accept it, and bear fruit.', true, 20),

    // ══════════════════════════════════ v21–25 · The lamp, hidden things, the measure
    mc(1, 'In the saying about the lamp, where did Jesus say a lamp is meant to be set?', ['On a lampstand', 'Under a basket', 'Under a bed', 'On the ground'], 21),
    word(1, 'In the saying about the lamp, Jesus asked whether a lamp is brought to be put under a basket or under what?', 'bed', 21, ['a bed']),
    sa(2, 'What two hiding places did Jesus name when He asked where a lamp is brought to be put, and where did He say it belongs?', 'Under a basket or under a bed; it is to be set on a lampstand.', 21),
    tf(2, 'Jesus asked whether a lamp is brought to be put under a basket or under a table.', false, 21, 'He said "under a basket or under a bed."'),
    blank(3, 'For there is nothing hidden which will not be _____, nor has anything been kept secret but that it should come to light.', 'revealed', 22),
    mc(2, 'After the saying about the lamp, what did Jesus say about hidden and secret things?', ['What is hidden will be revealed, and what is secret will come to light','Hidden things belong to outsiders who see without perceiving','Whatever remains hidden in the heart is immediately taken by Satan','The hidden seed sprouts and grows while the sower does not know how'], 22),
    blank(3, 'If _____ has ears to hear, let him hear."', 'anyone', 23),
    mc(3, 'After the sayings about the lamp and hidden things, what did Jesus tell the disciples to take heed of?', ['What you hear', 'What you sow', 'What you say', 'What you measure'], 24),
    blank(2, 'Then He said to them, "Take heed what you hear. With the same _____ you use, it will be measured to you; and to you who hear, more will be given.', 'measure', 24),
    sa(3, 'What did Jesus promise "to you who hear" after saying that the same measure you use will be measured to you?', 'To you who hear, more will be given.', 24),
    tf(3, 'Jesus told the disciples, "With the same measure you use, it will be measured to you."', true, 24),
    mc(3, 'In the saying about the measure, what did Jesus say happens to "whoever does not have"?', ['Even what he has will be taken away from him', 'More will be given to him', 'It will be measured to him with the same measure', 'His sins will be forgiven him'], 25),
    blank(3, 'For whoever has, to him more will be _____; but whoever does not have, even what he has will be taken away from him."', 'given', 25),
    word(3, 'In the saying about the measure, Jesus said that to "whoever has," what will be given?', 'more', 25),

    // ══════════════════════════════════ v26–29 · The parable of the growing seed
    mc(1, 'In the parable of the growing seed, what did Jesus liken the kingdom of God to?', ['A man scattering seed on the ground', 'A sower whose seed fell by the wayside', 'A lamp set on a lampstand', 'A boat crossing to the other side'], 26),
    blank(1, 'And He said, "The kingdom of God is as if a man should scatter _____ on the ground,', 'seed', 26),
    word(1, 'In the parable Jesus told after the saying about the lamp, what did the man scatter on the ground?', 'seed', 26),
    mc(3, 'In the parable of the growing seed, what did the man do while the seed sprouted and grew?', ['He slept by night and rose by day, not knowing how it grew', 'He watched by night and watered it by day', 'He put in the sickle while the seed was still sprouting', 'He set a lamp on a lampstand to see it grow'], 27),
    blank(3, 'and should sleep by night and rise by day, and the seed should sprout and grow, he himself does not know _____.', 'how', 27),
    sa(3, 'In the parable of the growing seed, what did the man understand about how the seed sprouted and grew?', 'Nothing — he slept by night and rose by day, and the seed sprouted and grew, he himself did not know how.', 27),
    mc(2, 'In the parable of the growing seed, in what order does the earth yield its crop?', ['First the blade, then the head, after that the full grain in the head', 'First the head, then the blade, after that the full grain in the head', 'First the root, then the branches, after that the full grain', 'First the seed, then the sickle, after that the harvest'], 28),
    blank(3, 'For the earth yields crops by itself: first the _____, then the head, after that the full grain in the head.', 'blade', 28),
    word(2, 'In the parable of the growing seed, what appears first when the earth yields its crop?', 'blade', 28, ['the blade']),
    mc(2, 'In the parable of the growing seed, what does the man do when the grain ripens?', ['He puts in the sickle because the harvest has come','He scatters another measure of seed over the ground','He continues sleeping by night and rising during the day','He gathers the birds of the air beneath the plant’s shade'], 29),
    blank(2, 'But when the grain ripens, immediately he puts in the _____, because the harvest has come."', 'sickle', 29),
    word(2, 'In the parable of the growing seed, what does the man put in when the grain ripens?', 'sickle', 29, ['the sickle']),
    sa(3, 'In the parable of the growing seed, why does the man immediately put in the sickle?', 'Because the grain has ripened and the harvest has come.', 29),

    // ══════════════════════════════════ v30–32 · The parable of the mustard seed
    blank(3, 'Then He said, "To what shall we liken the kingdom of God? Or with what _____ shall we picture it?', 'parable', 30),
    mc(3, 'What question did Jesus ask just before telling the parable of the mustard seed?', ['"To what shall we liken the kingdom of God?"', '"Do you not understand this parable?"', '"Is a lamp brought to be put under a basket?"', '"Who can this be, that even the wind and the sea obey Him?"'], 30),
    mc(1, 'In the parable of the mustard seed, how did Jesus describe the seed when it is sown on the ground?', ['Smaller than all the seeds on earth', 'Greater than all the seeds on earth', 'Hidden so that it cannot be revealed', 'Scattered so that the sower does not know how'], 31),
    blank(1, 'It is like a _____ seed which, when it is sown on the ground, is smaller than all the seeds on earth;', 'mustard', 31),
    word(1, 'Jesus said the kingdom of God is like what kind of seed, smaller than all the seeds on earth?', 'mustard', 31, ['mustard seed', 'a mustard seed']),
    tf(1, 'Jesus said the mustard seed, when it is sown on the ground, is smaller than all the seeds on earth.', true, 31),
    mc(3, 'In the parable of the mustard seed, what does the seed become once it is sown and grows up?', ['Greater than all herbs, with branches where birds can nest','A tree rising higher than every other tree throughout the field','A full head of grain that is immediately ready for the sickle','A crop producing thirtyfold, sixtyfold, and one hundredfold'], 32),
    blank(3, 'but when it is sown, it grows up and becomes greater than all _____, and shoots out large branches, so that the birds of the air may nest under its shade."', 'herbs', 32),
    word(2, 'In the parable of the mustard seed, who may nest under the shade of its large branches?', 'birds', 32, ['the birds', 'birds of the air', 'the birds of the air']),
    sa(2, 'In the parable of the mustard seed, what happens to the seed after it is sown?', 'It grows up and becomes greater than all herbs, and shoots out large branches so that the birds of the air may nest under its shade.', 32),
    tf(2, 'In the parable of the mustard seed, the grown plant becomes greater than all the trees.', false, 32, 'Jesus said it "becomes greater than all herbs."'),

    // ══════════════════════════════════ v33–34 · How Jesus taught
    tf(3, 'Mark says Jesus spoke the word to the people with many such parables, as they were able to hear it.', true, 33),
    sa(3, 'How does Mark say Jesus measured out His teaching to the people through parables?', 'With many such parables He spoke the word to them as they were able to hear it.', 33),
    mc(3, 'According to Mark, what did Jesus do when He was alone with His disciples after teaching in parables?', ['He explained all things to them', 'He spoke to them only in parables', 'He rebuked them for having no faith', 'He taught them from a boat on the sea'], 34),
    tf(3, 'Mark says Jesus explained all things to the multitude but spoke to His disciples only in parables.', false, 34, 'It is the reverse: without a parable He did not speak to the people, but when they were alone He explained all things to His disciples.'),
    word(3, 'Mark says that without a ___ Jesus did not speak to the people.', 'parable', 34, ['parables']),

    // ══════════════════════════════════ v35–41 · The storm on the sea
    mc(1, 'When evening came on the day of the parables, what did Jesus say to His disciples?', ['"Let us cross over to the other side."', '"Let us go to the mountain to pray."', '"Let us return to Capernaum."', '"Let us send the multitude away."'], 35),
    blank(1, 'On the same day, when evening had come, He said to them, "Let us cross over to the other _____."', 'side', 35),
    word(3, 'At what time of day did Jesus say, "Let us cross over to the other side"?', 'evening', 35),
    tf(1, 'Jesus said "Let us cross over to the other side" on the morning after He taught the parables.', false, 35, 'It was "on the same day, when evening had come."'),
    mc(3, 'When the disciples left the multitude to cross the sea, how did they take Jesus?', ['Along in the boat as He was, with other little boats also with Him', 'In a new boat they had prepared for the crossing', 'Alone in a little boat while they followed behind', 'On foot along the shore until they reached the other side'], 36),
    tf(3, 'When Jesus and the disciples crossed the sea, other little boats were also with Him.', true, 36),
    sa(3, 'When the disciples left the multitude to cross the sea, who else was on the water with Jesus\' boat?', 'Other little boats were also with Him.', 36),
    mc(1, 'What happened as Jesus and the disciples crossed the sea after the day of parables?', ['A great windstorm arose and the waves beat into the boat until it was filling', 'A great multitude followed them in other little boats', 'A great calm settled over the sea and the wind ceased', 'Jesus taught them from the boat while the crowd stood on the shore'], 37),
    blank(1, 'And a great _____ arose, and the waves beat into the boat, so that it was already filling.', 'windstorm', 37, ['wind storm', 'storm']),
    word(1, 'During the crossing, what beat into the boat so that it was already filling?', 'waves', 37, ['the waves']),
    tf(1, 'During the storm on the sea, the waves beat into the boat so that it was already filling.', true, 37),
    mc(1, 'When the storm filled the boat and the disciples woke Jesus, what did they say to Him?', ['"Teacher, do You not care that we are perishing?"', '"Teacher, command the wind and the sea to be still!"', '"Teacher, why did You bring us to the other side?"', '"Teacher, who can this be that the sea obeys Him?"'], 38),
    mc(2, 'Where was Jesus, and what was He doing, when the windstorm struck the boat?', ['In the stern, asleep on a pillow', 'In the bow, praying to the Father', 'At the oars, rowing with the disciples', 'On the shore, watching the little boats'], 38),
    blank(3, 'But He was in the _____, asleep on a pillow.', 'stern', 38),
    word(2, 'While the storm raged, Jesus was asleep in the stern on what?', 'pillow', 38, ['a pillow']),
    tf(3, 'During the storm the disciples found Jesus asleep in the bow of the boat.', false, 38, 'He was "in the stern, asleep on a pillow."'),
    sa(1, 'What were the disciples afraid of when they woke Jesus during the storm?', 'That they were perishing — they said, "Teacher, do You not care that we are perishing?"', 38),
    mc(1, 'What did Jesus say to the sea after the disciples woke Him in the storm?', ['"Peace, be still!"', '"Be quiet, and come out!"', '"Let us cross over!"', '"Be still, and hear!"'], 39),
    blank(1, 'Then He arose and rebuked the wind, and said to the sea, "Peace, be _____!" And the wind ceased and there was a great calm.', 'still', 39),
    sa(2, 'After the disciples woke Him in the storm, what did Jesus do, and what followed?', 'He arose, rebuked the wind, and said to the sea, "Peace, be still!" — then the wind ceased and there was a great calm.', 39),
    tf(1, 'Jesus rebuked the wind and said to the sea, "Peace, be still!"', true, 39),
    word(2, 'When Jesus said "Peace, be still!" the wind ceased and there was a great what?', 'calm', 39),
    mc(3, 'In the storm, Jesus rebuked the wind — but to what did He speak the words "Peace, be still!"?', ['The sea', 'The wind', 'The disciples', 'The other little boats'], 39),
    mc(1, 'After calming the storm, what did Jesus ask His disciples?', ['"Why are you so fearful? How is it that you have no faith?"', '"Do you not understand this parable?"', '"Who can this be, that even the wind and the sea obey Him?"', '"Take heed what you hear."'], 40),
    blank(1, 'But He said to them, "Why are you so fearful? How is it that you have no _____?"', 'faith', 40),
    word(1, 'After the storm, Jesus asked the disciples how it was that they had no what?', 'faith', 40),
    sa(2, 'What two questions did Jesus put to the disciples after the great calm?', '"Why are you so fearful? How is it that you have no faith?"', 40),
    mc(2, 'How did the disciples react after Jesus calmed the storm?', ['They greatly feared and asked one another who He could be','They rejoiced together and worshiped Jesus inside the boat','They fell asleep from exhaustion beside Him in the stern','They rowed across the sea toward the accompanying little boats'], 41),
    blank(3, 'And they feared exceedingly, and said to one another, "Who can this be, that even the _____ and the sea obey Him!"', 'wind', 41),
    sa(1, 'After the wind ceased, what did the disciples say to one another about Jesus?', '"Who can this be, that even the wind and the sea obey Him!"', 41),
    tf(2, 'After Jesus stilled the storm, the disciples said to one another, "Who can this be, that even the wind and the sea obey Him!"', true, 41),
    tf(3, 'Once the storm was calmed, the disciples\' fear left them entirely.', false, 41, 'They "feared exceedingly" and asked who this could be, that even the wind and the sea obey Him.'),
  ],
};

export default bank;
