// Mark 6 — quiz bank (NKJV, Orthodox Study Bible). Every row is anchored to a verse;
// fill-in-the-blank rows are verified against the stored verse text by scripts/seed-quiz-bank.ts.
// Episodes: Jesus in His own country (1–6) · the twelve sent out (7–13) · Herod hears of Jesus (14–16)
// · John imprisoned (17–20) · Herod’s birthday and John beheaded (21–29) · the apostles return (30–34)
// · the five thousand fed (35–44) · Jesus walks on the sea (45–52) · Gennesaret (53–56).
import { mc, blank, word, tf, sa, type ChapterBank } from './types';

const bank: ChapterBank = {
  book: 'Mark',
  chapter: 6,
  tag: 'quiz-v2-mark-6',
  rows: [
    // ══════════════════════════════════ v1–6 · Jesus in His own country
    mc(1, 'When Jesus went out and came to His own country, who came along with Him?', ['His disciples', 'The multitude from all the cities', 'John the Baptist’s disciples', 'Herod’s nobles and high officers'], 1),
    blank(1, 'Then He went out from there and came to His own _____, and His disciples followed Him.', 'country', 1),
    word(2, 'On what day did Jesus begin to teach in the synagogue of His own country?', 'Sabbath', 2, ['the sabbath']),
    mc(2, 'When Jesus taught in the synagogue of His own country, how did many who heard Him react at first?', ['They were astonished and asked where this Man got these things', 'They were greatly amazed in themselves beyond measure and marveled', 'They ran on foot from all the cities to come together to Him', 'They begged that they might just touch the hem of His garment'], 2),
    sa(3, 'What two questions did the astonished hearers in the synagogue ask about Jesus?', 'They asked where this Man got these things, and what wisdom was given to Him that such mighty works were performed by His hands.', 2),
    blank(3, 'And many hearing Him were astonished, saying, "Where did this Man get these things? And what _____ is this which is given to Him, that such mighty works are performed by His hands!', 'wisdom', 2),
    word(1, 'By what trade did the people of His own country identify Jesus when they asked, "Is this not the ___?"', 'carpenter', 3, ['the carpenter']),
    mc(1, 'In the synagogue, the people of Jesus’ own country named His brothers. Who were they?', ['James, Joses, Judas, and Simon', 'James, John, Judas, and Simon', 'James, Joses, Philip, and Simon', 'Joses, Judas, Simon, and Philip'], 3),
    blank(2, 'Is this not the carpenter, the Son of _____, and brother of James, Joses, Judas, and Simon? And are not His sisters here with us?', 'Mary', 3),
    tf(1, 'The people of Jesus’ own country said that His sisters were there with them.', true, 3),
    tf(2, 'The people of Jesus’ own country called Him "the carpenter, the Son of Joseph."', false, 3, 'They called Him "the carpenter, the Son of Mary."'),
    sa(1, 'After naming Jesus’ mother, brothers, and sisters in the synagogue, how did the people of His own country respond to Him?', 'They were offended at Him.', 3),
    word(3, 'Which of Jesus’ brothers is named right after James in the synagogue at His own country?', 'Joses', 3),
    mc(2, 'How did Jesus answer the people of His own country who were offended at Him?', ['"A prophet is not without honor except in his own country, among his own relatives, and in his own house"', '"Be of good cheer! It is I; do not be afraid"', '"It will be more tolerable for Sodom and Gomorrah in the day of judgment than for that city"', '"Come aside by yourselves to a deserted place and rest a while"'], 4),
    blank(1, 'But Jesus said to them, "A _____ is not without honor except in his own country, among his own relatives, and in his own house."', 'prophet', 4),
    sa(3, 'According to Jesus’ saying to the people of His own country, in what three places is a prophet without honor?', 'In his own country, among his own relatives, and in his own house.', 4),
    mc(2, 'What was the only mighty work Jesus did in His own country?', ['He laid His hands on a few sick people and healed them', 'He cast out many demons and anointed the sick with oil', 'He blessed five loaves and fed the multitude', 'He made the wind cease when He entered the boat'], 5),
    blank(2, 'Now He could do no mighty work there, except that He laid His hands on a few _____ people and healed them.', 'sick', 5),
    word(1, 'Jesus marveled at the people of His own country because of their what?', 'unbelief', 6),
    sa(2, 'After marveling at the unbelief in His own country, what did Jesus do next?', 'He went about the villages in a circuit, teaching.', 6),

    // ══════════════════════════════════ v7–13 · The twelve sent out
    mc(1, 'How did Jesus send out the twelve when He called them to Himself?', ['Two by two, with power over unclean spirits', 'One by one, each with a bag of bread', 'All together in the boat to Bethsaida', 'In groups of hundreds and fifties'], 7),
    blank(1, 'And He called the twelve to Himself, and began to send them out two by two, and gave them power over _____ spirits.', 'unclean', 7),
    word(2, 'How many disciples did Jesus call to Himself and send out two by two?', 'twelve', 7, ['12']),
    word(2, 'What was the one thing Jesus allowed the twelve to take for their journey?', 'staff', 8, ['a staff']),
    mc(3, 'Which items did Jesus forbid the twelve to take for the journey?', ['A bag, bread, and copper in their money belts', 'A staff, sandals, and a tunic', 'Oil, a boat, and a platter', 'Two tunics, a staff, and fish'], 8),
    blank(3, 'He commanded them to take nothing for the journey except a staff—no bag, no _____, no copper in their money belts—', 'bread', 8),
    tf(2, 'Jesus told the twelve to carry copper in their money belts for the journey.', false, 8, 'He commanded "no copper in their money belts."'),
    sa(3, 'What did Jesus tell the twelve about their footwear and clothing for the journey?', 'They were to wear sandals and not to put on two tunics.', 9),
    blank(1, 'but to wear _____, and not to put on two tunics.', 'sandals', 9),
    word(2, 'Jesus told the twelve not to put on two of which garment?', 'tunics', 9, ['tunic']),
    mc(2, 'What did Jesus tell the twelve to do once they entered a house in a place?', ['Stay there till they departed from that place', 'Anoint the household with oil', 'Shake off the dust under their feet', 'Buy bread in the surrounding villages'], 10),
    mc(2, 'What were the twelve to do when a place would not receive them or hear them?', ['Shake off the dust under their feet as a testimony against them', 'Lay hands on a few sick people and depart', 'Stay in the house until the people repented', 'Return to Jesus and tell Him all things'], 11),
    word(2, 'What were the twelve to shake off from under their feet when leaving a place that rejected them?', 'dust', 11, ['the dust']),
    sa(3, 'Why did Jesus say the twelve should shake off the dust under their feet when leaving a place that rejected them?', 'As a testimony against them.', 11),
    mc(3, 'Which two cities did Jesus say would fare more tolerably in the day of judgment than a city that rejected the twelve?', ['Sodom and Gomorrah', 'Bethsaida and Gennesaret', 'Tyre and Sidon', 'Capernaum and Bethsaida'], 11),
    blank(3, 'Assuredly, I say to you, it will be more tolerable for Sodom and _____ in the day of judgment than for that city!', 'Gomorrah', 11),
    tf(3, 'Jesus said it would be more tolerable for Sodom and Gomorrah in the day of judgment than for a city that rejected the twelve.', true, 11),
    word(1, 'When the twelve went out, they preached that people should do what?', 'repent', 12),
    mc(1, 'Besides casting out many demons, what did the twelve do for the sick on their mission?', ['Anointed them with oil and healed them', 'Laid them in the marketplaces to touch Jesus', 'Carried them about on beds to Jesus', 'Gave them loaves and fish to eat'], 13),
    blank(2, 'And they cast out many demons, and anointed with _____ many who were sick, and healed them.', 'oil', 13),
    sa(2, 'Summarize what the twelve did on their mission after Jesus sent them out two by two.', 'They preached that people should repent, cast out many demons, and anointed with oil many who were sick and healed them.', 13),

    // ══════════════════════════════════ v14–16 · Herod hears of Jesus
    mc(1, 'Why did King Herod come to hear of Jesus?', ['Because Jesus’ name had become well known', 'Because the twelve preached at Herod’s feast', 'Because John the Baptist told him about Jesus', 'Because Herodias reported Jesus’ mighty works'], 14),
    mc(2, 'When King Herod heard of Jesus, who did he say Jesus was?', ['John the Baptist, risen from the dead', 'Elijah, come back to Israel', 'The Prophet, or like one of the prophets', 'The carpenter, the Son of Mary'], 14),
    blank(1, 'And he said, "John the _____ is risen from the dead, and therefore these powers are at work in him."', 'Baptist', 14),
    sa(3, 'How did Herod explain the powers at work in Jesus?', 'He said John the Baptist had risen from the dead, and therefore these powers were at work in him.', 14),
    word(1, 'While Herod said Jesus was John risen, some others said Jesus was which prophet of old?', 'Elijah', 15),
    mc(3, 'Apart from Herod’s opinion, what did others say about who Jesus was?', ['"It is Elijah," or "It is the Prophet, or like one of the prophets"', '"It is the carpenter, the Son of Mary"', '"It is John, whom Herod beheaded"', '"It is a just and holy man"'], 15),
    blank(3, 'But when Herod heard, he said, "This is John, whom I _____; he has been raised from the dead!"', 'beheaded', 16),
    tf(1, 'Herod believed Jesus was Elijah raised from the dead.', false, 16, 'Herod said, "This is John, whom I beheaded; he has been raised from the dead!" It was others who said "It is Elijah."'),
    sa(3, 'When Herod heard reports about Jesus, whom did he say Jesus was, and what did he say had happened to him?', 'He said it was John, whom he had beheaded, and that John had been raised from the dead.', 16),

    // ══════════════════════════════════ v17–20 · John imprisoned
    mc(1, 'Why had Herod laid hold of John and bound him in prison?', ['For the sake of Herodias, his brother Philip’s wife, whom he had married', 'Because John baptized the multitudes in Galilee', 'Because John called Herod a just and holy man', 'Because John preached that people should repent'], 17),
    word(2, 'Herodias had been the wife of which brother of Herod?', 'Philip', 17),
    blank(2, 'For Herod himself had sent and laid hold of John, and bound him in prison for the sake of _____, his brother Philip’s wife; for he had married her.', 'Herodias', 17),
    tf(3, 'Herodias was the wife of Herod’s brother James before Herod married her.', false, 17, 'She was "his brother Philip’s wife."'),
    mc(2, 'What had John said to Herod that led to his imprisonment?', ['"It is not lawful for you to have your brother’s wife"', '"It is not lawful for you to give a feast on the Sabbath"', '"You are without honor among your own relatives"', '"It will be more tolerable for Sodom and Gomorrah than for you"'], 18),
    blank(2, 'Because John had said to Herod, "It is not _____ for you to have your brother’s wife."', 'lawful', 18),
    sa(2, 'What did John the Baptist tell Herod about his marriage to Herodias?', 'That it was not lawful for him to have his brother’s wife.', 18),
    mc(2, 'How did Herodias feel toward John after he rebuked Herod’s marriage?', ['She held it against him and wanted to kill him', 'She feared him as a just and holy man', 'She heard him gladly', 'She was exceedingly sorry for him'], 19),
    mc(3, 'Why could Herodias not kill John?', ['Herod feared John, knowing he was a just and holy man, and protected him', 'John’s disciples guarded him in prison', 'Herod had sworn an oath to spare him', 'The chief men of Galilee heard John gladly'], 20),
    blank(3, 'for Herod feared John, knowing that he was a just and _____ man, and he protected him.', 'holy', 20),
    sa(3, 'How did Herod respond whenever he heard John speak?', 'He did many things, and heard him gladly.', 20),
    tf(3, 'Herodias feared John, knowing he was a just and holy man, and protected him.', false, 20, 'It was Herod who feared John and protected him; Herodias wanted to kill him.'),
    word(3, 'Which of the two, Herod or Herodias, protected John while he was in prison?', 'Herod', 20),

    // ══════════════════════════════════ v21–29 · Herod’s birthday; John beheaded
    mc(1, 'On what occasion did Herod give a feast for his nobles, high officers, and the chief men of Galilee?', ['His birthday', 'The Sabbath', 'His marriage to Herodias', 'The day John was imprisoned'], 21),
    blank(2, 'Then an opportune day came when Herod on his _____ gave a feast for his nobles, the high officers, and the chief men of Galilee.', 'birthday', 21),
    sa(2, 'Who were the guests at Herod’s birthday feast?', 'His nobles, the high officers, and the chief men of Galilee.', 21),
    word(3, 'The chief men of which region attended Herod’s birthday feast?', 'Galilee', 21),
    tf(3, 'Mark calls the day of Herod’s birthday feast "an opportune day."', true, 21),
    mc(1, 'Who came in and danced at Herod’s birthday feast?', ['Herodias’ daughter', 'Herodias herself', 'Philip’s daughter', 'The daughter of one of the nobles'], 22),
    mc(2, 'When Herodias’ daughter danced and pleased Herod and his guests, what did the king say to her?', ['"Ask me whatever you want, and I will give it to you"', '"Come aside by yourself and rest a while"', '"You shall sit with the chief men of Galilee"', '"Bring me the head of John the Baptist"'], 22),
    mc(2, 'When Herod swore to Herodias’ daughter, how much did he promise to give her?', ['Up to half his kingdom', 'Two hundred denarii', 'Twelve baskets full of bread', 'The chief place in Galilee'], 23),
    blank(3, 'He also swore to her, "Whatever you ask me, I will give you, up to half my _____."', 'kingdom', 23),
    tf(2, 'Herod swore to give Herodias’ daughter whatever she asked, up to his whole kingdom.', false, 23, 'He swore "up to half my kingdom."'),
    word(3, 'Herod swore to give the girl whatever she asked, up to what fraction of his kingdom?', 'half', 23, ['one half', '1/2']),
    mc(1, 'When Herodias’ daughter asked her mother what she should ask of Herod, what did Herodias answer?', ['"The head of John the Baptist!"', '"Half of his kingdom!"', '"Two hundred denarii!"', '"That John be bound in prison!"'], 24),
    blank(1, 'So she went out and said to her mother, "What shall I ask?" And she said, "The _____ of John the Baptist!"', 'head', 24),
    sa(2, 'After Herod’s promise, whom did the girl go out to consult, and what did she ask her?', 'She went out to her mother and asked, "What shall I ask?"', 24),
    tf(3, 'Herodias’ daughter decided on her own to ask for the head of John the Baptist.', false, 24, 'She went out and asked her mother, and Herodias said, "The head of John the Baptist!"'),
    word(1, 'Herodias’ daughter asked Herod for the head of John the Baptist on what?', 'platter', 25, ['a platter']),
    mc(3, 'How did Herodias’ daughter come back to Herod after speaking with her mother?', ['Immediately, with haste', 'Weeping and afraid', 'Slowly, after the feast had ended', 'Together with her mother'], 25),
    tf(2, 'The girl asked Herod to give her the head of John the Baptist "at once."', true, 25),
    mc(3, 'Why did Herod not want to refuse the girl’s request for John’s head?', ['Because of the oaths and because of those who sat with him', 'Because Herodias threatened him', 'Because he had stopped fearing John', 'Because John had rebuked him before the guests'], 26),
    blank(3, 'And the king was exceedingly _____; yet, because of the oaths and because of those who sat with him, he did not want to refuse her.', 'sorry', 26),
    tf(2, 'Herod was glad to grant the request for John’s head.', false, 26, 'The king was "exceedingly sorry," yet did not want to refuse because of the oaths and those who sat with him.'),
    sa(3, 'How did Herod feel about the request for John’s head, and why did he grant it anyway?', 'He was exceedingly sorry, but because of the oaths and because of those who sat with him he did not want to refuse her.', 26),
    mc(1, 'Whom did Herod send to carry out the girl’s request for John’s head?', ['An executioner', 'One of his nobles', 'A high officer', 'Herodias herself'], 27),
    blank(3, 'Immediately the king sent an _____ and commanded his head to be brought. And he went and beheaded him in prison,', 'executioner', 27),
    word(2, 'Where was John when the executioner beheaded him?', 'prison', 27, ['in prison', 'the prison']),
    mc(2, 'After John was beheaded, what happened to his head?', ['It was brought on a platter to the girl, who gave it to her mother', 'It was laid in a tomb by John’s disciples', 'It was shown to the nobles and chief men of Galilee', 'It was sent to Philip, Herod’s brother'], 28),
    blank(2, 'brought his head on a platter, and gave it to the girl; and the girl gave it to her _____.', 'mother', 28),
    tf(3, 'The executioner gave John’s head directly to Herodias.', false, 28, 'He gave it to the girl, and the girl gave it to her mother.'),
    mc(2, 'What did John’s disciples do when they heard he had been beheaded?', ['They came and took away his corpse and laid it in a tomb', 'They fled to Jesus in a deserted place', 'They demanded his head back from Herodias', 'They anointed his body with oil in the prison'], 29),
    sa(2, 'Who buried John the Baptist, and what did they do with his body?', 'His disciples came, took away his corpse, and laid it in a tomb.', 29),

    // ══════════════════════════════════ v30–34 · The apostles return; sheep without a shepherd
    mc(2, 'What did the apostles tell Jesus when they gathered back to Him?', ['All things, both what they had done and what they had taught', 'That Herod had beheaded John the Baptist', 'That the multitude had nothing to eat', 'That a prophet has no honor in his own country'], 30),
    mc(2, 'When the apostles returned from their mission, what did Jesus tell them to do?', ['"Come aside by yourselves to a deserted place and rest a while"', '"Go into the villages and buy yourselves bread"', '"Get into the boat and go before Me to Bethsaida"', '"Make them all sit down in groups on the green grass"'], 31),
    blank(2, 'And He said to them, "Come aside by yourselves to a deserted place and _____ a while."', 'rest', 31),
    sa(3, 'Why did Jesus tell the returning apostles to come aside to a deserted place and rest?', 'Because there were many coming and going, and they did not even have time to eat.', 31),
    tf(3, 'Jesus called the apostles aside to rest because they did not even have time to eat.', true, 31),
    word(3, 'How did Jesus and the apostles travel to the deserted place to rest?', 'boat', 32, ['by boat', 'in the boat']),
    mc(3, 'How did the multitudes reach the deserted place before Jesus and the apostles?', ['They ran there on foot from all the cities', 'They followed in other boats', 'Herod’s officers led them there', 'They walked along the shore from Gennesaret'], 33),
    blank(2, 'But the multitudes saw them departing, and many knew Him and ran there on _____ from all the cities.', 'foot', 33),
    tf(3, 'The multitudes arrived at the deserted place after Jesus and His disciples had already landed.', false, 33, 'They ran on foot from all the cities and "arrived before them."'),
    mc(1, 'Why was Jesus moved with compassion when He came out and saw the great multitude?', ['Because they were like sheep not having a shepherd', 'Because they had nothing to eat', 'Because they were straining at rowing against the wind', 'Because they had carried their sick on beds'], 34),
    blank(1, 'And Jesus, when He came out, saw a great multitude and was moved with compassion for them, because they were like _____ not having a shepherd. So He began to teach them many things.', 'sheep', 34),
    sa(1, 'What did Jesus do for the multitude that was like sheep without a shepherd?', 'He began to teach them many things.', 34),

    // ══════════════════════════════════ v35–44 · The five thousand fed
    mc(3, 'What did the disciples point out to Jesus when the day was far spent?', ['That it was a deserted place and the hour was already late', 'That the boat was in the middle of the sea', 'That they had only five loaves and two fish', 'That the multitude had run there on foot'], 35),
    blank(3, 'When the day was now far spent, His disciples came to Him and said, "This is a _____ place, and already the hour is late.', 'deserted', 35),
    mc(1, 'As the hour grew late, what did the disciples want Jesus to do with the multitude?', ['Send them away to buy themselves bread in the surrounding country and villages', 'Make them sit down in ranks on the green grass', 'Send them across the sea to Bethsaida', 'Lay His hands on the sick among them'], 36),
    mc(1, 'When the disciples wanted to send the crowd away for food, what did Jesus tell them?', ['"You give them something to eat"', '"Send them away, for the hour is late"', '"Go and buy two hundred denarii worth of bread"', '"Come aside and rest a while"'], 37),
    word(3, 'How many denarii worth of bread did the disciples say it would take to feed the multitude?', 'two hundred', 37, ['200']),
    blank(3, 'And they said to Him, "Shall we go and buy two hundred _____ worth of bread and give them something to eat?"', 'denarii', 37),
    sa(3, 'When Jesus said "You give them something to eat," how did the disciples object?', 'They asked whether they should go and buy two hundred denarii worth of bread and give the people something to eat.', 37),
    mc(1, 'When Jesus sent the disciples to see how many loaves they had, what did they find?', ['Five loaves and two fish', 'Two loaves and five fish', 'Twelve loaves and two fish', 'Five loaves and no fish'], 38),
    blank(1, 'And when they found out they said, "_____, and two fish."', 'Five', 38, ['5']),
    word(1, 'How many fish did the disciples have before Jesus fed the multitude?', 'two', 38, ['2']),
    tf(1, 'Before feeding the multitude, the disciples had seven loaves and two fish.', false, 38, 'They found "Five, and two fish."'),
    sa(1, 'When the disciples protested about feeding the crowd, what did Jesus ask them and tell them to do?', 'He asked, "How many loaves do you have?" and told them, "Go and see."', 38),
    mc(2, 'Before the loaves were distributed, what did Jesus command the disciples to have the people do?', ['Sit down in groups on the green grass', 'Line up in the marketplaces', 'Get into the boats and cross to Bethsaida', 'Go into the villages for bread'], 39),
    blank(2, 'Then He commanded them to make them all sit down in groups on the green _____.', 'grass', 39),
    word(2, 'What color does Mark give the grass on which the multitude sat down to eat?', 'green', 39),
    mc(3, 'In what sized groups did the multitude sit down before the loaves were multiplied?', ['In hundreds and in fifties', 'In twelves and in fives', 'In thousands and in hundreds', 'In fifties and in twenties'], 40),
    blank(3, 'So they sat down in ranks, in hundreds and in _____.', 'fifties', 40, ['50s']),
    mc(2, 'What did Jesus do with the five loaves and two fish before giving them to the disciples?', ['He looked up to heaven, blessed and broke the loaves', 'He anointed them with oil', 'He laid His hands on them and prayed alone', 'He divided them into twelve baskets'], 41),
    blank(3, 'And when He had taken the five loaves and the two fish, He looked up to _____, blessed and broke the loaves, and gave them to His disciples to set before them; and the two fish He divided among them all.', 'heaven', 41),
    sa(3, 'Step by step, what did Jesus do with the five loaves and the two fish?', 'He took them, looked up to heaven, blessed and broke the loaves, gave them to His disciples to set before the people, and divided the two fish among them all.', 41),
    tf(2, 'Jesus gave the broken loaves to His disciples to set before the people.', true, 41),
    blank(1, 'So they all ate and were _____.', 'filled', 42),
    mc(1, 'How many baskets of fragments were taken up after the multitude ate?', ['Twelve', 'Seven', 'Five', 'Two'], 43),
    blank(1, 'And they took up _____ baskets full of fragments and of the fish.', 'twelve', 43, ['12']),
    mc(1, 'About how many men ate the loaves in the deserted place?', ['Five thousand', 'Four thousand', 'Twelve thousand', 'Two hundred'], 44),
    blank(1, 'Now those who had eaten the loaves were about five _____ men.', 'thousand', 44),
    tf(1, 'About four thousand men ate the loaves in the deserted place.', false, 44, 'Mark says "about five thousand men."'),

    // ══════════════════════════════════ v45–52 · Jesus walks on the sea
    mc(1, 'After feeding the five thousand, where did Jesus send the disciples ahead in the boat?', ['To the other side, to Bethsaida', 'To the land of Gennesaret', 'To His own country', 'To the cities of Galilee'], 45),
    blank(1, 'Immediately He made His disciples get into the boat and go before Him to the other side, to _____, while He sent the multitude away.', 'Bethsaida', 45),
    word(1, 'To which town did Jesus send the disciples ahead by boat after the feeding?', 'Bethsaida', 45),
    tf(2, 'Jesus sent the multitude away while the disciples went ahead of Him in the boat.', true, 45),
    mc(2, 'After sending the multitude away, where did Jesus go and why?', ['To the mountain to pray', 'To the boat to sleep', 'To Bethsaida to teach', 'To the villages to heal'], 46),
    blank(2, 'And when He had sent them away, He departed to the mountain to _____.', 'pray', 46),
    sa(2, 'When evening came after the feeding, where were the boat and where was Jesus?', 'The boat was in the middle of the sea, and He was alone on the land.', 47),
    tf(2, 'When evening came, Jesus was alone on the land while the boat was in the middle of the sea.', true, 47),
    mc(2, 'Why were the disciples straining at rowing that night?', ['The wind was against them', 'The boat was taking on water', 'They were racing the multitude to Bethsaida', 'They had not understood about the loaves'], 48),
    word(2, 'During which watch of the night did Jesus come to the disciples walking on the sea?', 'fourth', 48, ['4th', 'the fourth', 'the fourth watch']),
    blank(3, 'Now about the _____ watch of the night He came to them, walking on the sea, and would have passed them by.', 'fourth', 48, ['4th']),
    tf(3, 'Jesus came walking on the sea about the third watch of the night.', false, 48, 'It was "about the fourth watch of the night."'),
    mc(3, 'What does Mark say Jesus would have done as He walked on the sea toward the boat?', ['He would have passed them by', 'He would have calmed the wind first', 'He would have called to them from the shore', 'He would have waited for the morning'], 48),
    mc(1, 'What did the disciples suppose when they saw Jesus walking on the sea?', ['That it was a ghost', 'That it was Elijah', 'That it was John risen from the dead', 'That it was one of the prophets'], 49),
    blank(1, 'And when they saw Him walking on the sea, they supposed it was a _____, and cried out;', 'ghost', 49),
    sa(1, 'How did the disciples react when they saw Jesus walking on the sea?', 'They supposed it was a ghost and cried out.', 49),
    mc(1, 'What did Jesus say to the troubled disciples as He came to the boat?', ['"Be of good cheer! It is I; do not be afraid"', '"Why are you so fearful? How is it that you have no faith?"', '"Peace, be still!"', '"You give them something to eat"'], 50),
    blank(1, 'But immediately He talked with them and said to them, "Be of good _____! It is I; do not be afraid."', 'cheer', 50),
    tf(3, 'Only a few of the disciples saw Jesus on the sea and were troubled.', false, 50, '"For they all saw Him and were troubled."'),
    mc(2, 'What happened when Jesus went up into the boat with the disciples?', ['The wind ceased', 'The boat immediately reached the land', 'The disciples supposed it was a ghost', 'They understood about the loaves'], 51),
    blank(2, 'Then He went up into the boat to them, and the wind _____.', 'ceased', 51),
    sa(3, 'How did the disciples respond when Jesus entered the boat and the wind ceased?', 'They were greatly amazed in themselves beyond measure, and marveled.', 51),
    mc(3, 'Why were the disciples so amazed when the wind ceased?', ['They had not understood about the loaves, because their heart was hardened', 'They had never seen Jesus still a storm', 'They thought He was John raised from the dead', 'They had been rowing since the first watch'], 52),
    blank(3, 'For they had not understood about the _____, because their heart was hardened.', 'loaves', 52),
    tf(3, 'Mark says the disciples had not understood about the loaves because their heart was hardened.', true, 52),
    word(3, 'Mark says the disciples’ heart was what, so that they did not understand about the loaves?', 'hardened', 52),

    // ══════════════════════════════════ v53–56 · Gennesaret
    word(1, 'After crossing the sea, at what land did Jesus and the disciples anchor?', 'Gennesaret', 53),
    blank(2, 'When they had crossed over, they came to the land of _____ and anchored there.', 'Gennesaret', 53),
    tf(1, 'When they came out of the boat at Gennesaret, the people immediately recognized Jesus.', true, 54),
    mc(2, 'What did the people around Gennesaret do once they recognized Jesus?', ['Ran through the whole region and carried the sick about on beds to wherever He was', 'Ran on foot from all the cities to the deserted place', 'Brought Him five loaves and two fish', 'Asked Him to send the sick away to buy bread'], 55),
    blank(3, 'ran through that whole surrounding region, and began to carry about on _____ those who were sick to wherever they heard He was.', 'beds', 55),
    sa(2, 'How did the people of the region around Gennesaret bring the sick to Jesus?', 'They carried them about on beds to wherever they heard He was.', 55),
    mc(2, 'What did the people beg of Jesus for their sick laid in the marketplaces?', ['That they might just touch the hem of His garment', 'That He would anoint them with oil', 'That He would lay His hands on them', 'That He would speak a word and heal them'], 56),
    blank(2, 'Wherever He entered, into villages, cities, or the country, they laid the sick in the marketplaces, and begged Him that they might just touch the hem of His _____.', 'garment', 56),
    word(2, 'Where did the people lay the sick as Jesus entered villages, cities, and the country?', 'marketplaces', 56, ['marketplace', 'the marketplaces', 'market places']),
    tf(1, 'As many as touched Jesus at Gennesaret were made well.', true, 56),
    sa(3, 'Into what three kinds of places does Mark say Jesus entered, where the sick were laid in the marketplaces?', 'Villages, cities, or the country.', 56),
  ],
};

export default bank;
