import { mc, blank, word, tf, type ChapterBank, sa } from './types'
const bank: ChapterBank = { book: 'Mark', chapter: 4, tag: 'quiz-v2-mark-4', rows: [
mc(1,'From where did Jesus teach the multitude by the sea?',['From a boat','From a synagogue','From a mountain','From a house'],1),blank(2,'the whole multitude was on the land _____ the sea.','facing',1),
word(1,'What form did Jesus use to teach many things?','parables',2),tf(3,'Jesus taught the multitude only by giving commands without illustrations.',false,2,'He taught them many things by parables.'),
mc(1,'Who went out to sow?',['A sower','A fisherman','A shepherd','A merchant'],3),blank(2,'Behold, a sower went out to _____.','sow',3),
sa(2,'What devoured the seed beside the path?','the birds of the air',4,['birds','the birds']),tf(1,'Some seed fell by the wayside.',true,4),
mc(2,'Why did the seed on stony ground spring up immediately?',['It had no depth of earth','It received abundant rain','The birds planted it','The thorns protected it'],5),blank(1,'Some fell on _____ ground, where it did not have much earth','stony',5),
sa(1,'What caused the rootless plant to be scorched?','the sun',6,['sun']),tf(3,'The plant survived because it had deep roots.',false,6,'It withered because it had no root.'),
mc(1,'What happened to the seed among thorns?',['It was choked and yielded no crop','It produced a hundredfold','Birds carried it away','It became a mustard tree'],7),blank(2,'the thorns grew up and _____ it','choked',7),
sa(3,'Name the three yields from the good ground.','thirtyfold, sixty, and a hundred',8,['thirty, sixty, and a hundred']),tf(1,'The seed on good ground increased and produced a crop.',true,8),
mc(1,'Whom did Jesus call to hear?',['Whoever has ears to hear','Only the Twelve','Only the scribes','Only the crowd on shore'],9),blank(2,'He who has ears to hear, let him _____!','hear',9),
sa(2,'Who asked Jesus about the parable when He was alone?','those around Him with the twelve',10,['the Twelve and those around Him']),tf(3,'The multitude publicly explained the parable to Jesus.',false,10,'Those around Jesus and the Twelve asked Him about it.'),
mc(1,'What had been given to Jesus’ followers to know?',['The mystery of the kingdom of God','The date of the harvest','The location of hidden treasure','The number of future kings'],11),blank(3,'To you it has been given to know the _____ of the kingdom of God','mystery',11),
sa(3,'What might happen if the outsiders turned?','their sins might be forgiven',12,['their sins be forgiven']),tf(1,'The quotation speaks of seeing without perceiving and hearing without understanding.',true,12),
mc(2,'What did Jesus ask after they failed to understand the sower?', ['How then will you understand all the parables?','Why did you leave the boat?','Who touched Me?','Where is the harvest?'],13),blank(1,'Do you not _____ this parable?','understand',13),
sa(1,'What does the sower sow?','the word',14,['word']),tf(3,'Jesus said the sower sows grain only.',false,14,'The sower sows the word.'),
mc(1,'Who takes away the word sown by the wayside?',['Satan','The birds only','The disciples','The cares of the world'],15),blank(2,'Satan comes immediately and takes away the word that was sown in their _____.','hearts',15),
sa(2,'How do the stony-ground hearers initially receive the word?','with gladness',16,['gladness']),tf(1,'The stony-ground hearers receive the word immediately.',true,16),
mc(2,'What causes rootless hearers to stumble?',['Tribulation or persecution for the word’s sake','A plentiful harvest','The explanation of parables','The birds nesting'],17),blank(3,'they have no _____ in themselves, and so endure only for a time.','root',17),
sa(1,'What do those represented by thorny ground first do?','hear the word',18),tf(3,'The thorny-ground people never hear the word at all.',false,18,'They hear it, but other things choke it.'),
mc(3,'Which three pressures choke the word?',['Worldly cares, deceitful riches, and desires for other things','Fasting, prayer, and almsgiving','Wind, waves, and rain','Birds, stones, and sunlight'],19),blank(2,'the deceitfulness of riches, and the desires for other things entering in _____ the word','choke',19),
sa(2,'What do good-ground hearers do after hearing the word?','accept it and bear fruit',20,['accept it','bear fruit']),tf(1,'Good-ground hearers bear fruit in varying amounts.',true,20),
mc(1,'Where should a lamp be placed?',['On a lampstand','Under a basket','Under a bed','Inside a wineskin'],21),blank(2,'Is it not to be set on a _____?','lampstand',21),
sa(1,'What will happen to what is hidden?','it will be revealed',22,['revealed']),tf(3,'Jesus said secrets would remain permanently hidden.',false,22,'What is hidden will be revealed and come to light.'),
mc(1,'What repeated call did Jesus give?', ['If anyone has ears to hear, let him hear','Let everyone leave the shore','Only the Twelve may hear','Keep every parable secret'],23),blank(2,'If anyone has ears to hear, let him _____.','hear',23),
sa(2,'What did Jesus tell listeners to take heed about?','what they hear',24),tf(1,'The measure a person uses will be measured back to that person.',true,24),
mc(2,'What happens to the one who has?',['More will be given','Everything will be taken','He will receive no measure','He must hide it'],25),blank(3,'whoever does not have, even what he has will be taken _____ from him.','away',25),
word(1,'What does the man scatter in the kingdom comparison?','seed',26),tf(3,'Jesus compared God’s kingdom to a man scattering stones.',false,26,'He compared it to a man scattering seed.'),
mc(2,'What does the seed do while the man sleeps and rises?',['Sprouts and grows though he does not know how','Remains unchanged','Is eaten by birds every night','Immediately becomes full grain'],27),blank(1,'the seed should sprout and grow, he himself does not know _____.','how',27),
sa(2,'What is the first stage of the crop?','the blade',28,['blade']),tf(1,'The sequence is blade, head, then full grain in the head.',true,28),
mc(1,'Why does the man put in the sickle?',['The harvest has come','The seed has failed','The storm has begun','The birds have arrived'],29),blank(2,'when the grain ripens, immediately he puts in the _____.','sickle',29),
sa(1,'What was Jesus seeking a comparison for?','the kingdom of God',30),tf(3,'Jesus refused to picture the kingdom with a parable.',false,30,'He asked what parable could picture it.'),
mc(1,'How is the mustard seed described when sown?',['Smaller than all the seeds on earth','Larger than every herb','Equal to the full grain','Too large for the ground'],31),blank(3,'is _____ than all the seeds on earth','smaller',31),
sa(2,'What nested under the mustard plant’s shade?','the birds of the air',32,['birds']),tf(1,'The mustard seed grows and produces large branches.',true,32),
mc(2,'How did Jesus match His teaching to the listeners?',['He spoke as they were able to hear it','He explained nothing at all','He spoke only to the Twelve','He required them to write it'],33),blank(1,'He spoke the word to them as they were able to _____ it.','hear',33),
sa(1,'To whom did Jesus explain everything privately?','His disciples',34,['the disciples']),tf(3,'Jesus publicly explained every parable to the entire multitude.',false,34,'He explained all things to His disciples when they were alone.'),
mc(1,'What did Jesus propose when evening came?',['Crossing to the other side','Returning to Capernaum by land','Dismissal of the Twelve','Sleeping on the shore'],35),blank(2,'Let us cross over to the other _____.','side',35),
sa(2,'What accompanied Jesus’ boat?','other little boats',36),tf(1,'The disciples took Jesus in the boat as He was.',true,36),
mc(1,'What threatened the boat during the crossing?',['A great windstorm and beating waves','A crowd on shore','A damaged sail in calm weather','A school of fish'],37),blank(3,'the waves beat into the boat, so that it was already _____.','filling',37),
sa(1,'Where was Jesus sleeping?','in the stern',38,['the stern']),tf(2,'Jesus was asleep on a pillow when the disciples woke Him.',true,38),
mc(1,'What command did Jesus give the sea?',['Peace, be still!','Cross to the other side!','Rise and walk!','Come out of him!'],39),blank(2,'And the wind ceased and there was a great _____.','calm',39),
word(2,'What did Jesus say the disciples lacked?','faith',40),tf(3,'Jesus praised the disciples for being completely fearless.',false,40,'He asked why they were fearful and had no faith.'),
mc(3,'What caused the disciples to fear exceedingly?',['Even the wind and sea obeyed Jesus','The boat had reached shore','The multitude followed them','The mustard seed had grown'],41),blank(1,'Who can this be, that even the wind and the sea _____ Him!','obey',41),
]};
export default bank;
