export type ProphecyItem = {
  id: string;
  prophecy_text: string;
  prophecy_reference: string;
  fulfillment_text: string;
  fulfillment_reference: string;
  fulfillment_book_slug?: '1-kings' | '2-kings';
  fulfillment_chapter?: number;
  outcome: 'fulfilled' | 'partial' | 'historical';
};

export const PROPHET_PROPHECIES: Record<string, ProphecyItem[]> = {

  elijah: [
    {
      id: 'elijah-drought',
      prophecy_text: 'There will be neither dew nor rain in the next few years except at my word.',
      prophecy_reference: '1 Kings 17:1',
      fulfillment_text: 'After three and a half years of drought, Elijah prayed and rain returned to the land.',
      fulfillment_reference: '1 Kings 18:41–45',
      fulfillment_book_slug: '1-kings',
      fulfillment_chapter: 18,
      outcome: 'fulfilled',
    },
    {
      id: 'elijah-ahab-blood',
      prophecy_text: 'In the place where dogs licked up Naboth\'s blood, dogs will lick up your blood.',
      prophecy_reference: '1 Kings 21:19',
      fulfillment_text: 'Ahab\'s chariot was washed at the pool of Samaria, and dogs licked up his blood, as the LORD had declared.',
      fulfillment_reference: '1 Kings 22:38',
      fulfillment_book_slug: '1-kings',
      fulfillment_chapter: 22,
      outcome: 'fulfilled',
    },
    {
      id: 'elijah-jezebel',
      prophecy_text: 'Dogs will devour Jezebel by the wall of Jezreel.',
      prophecy_reference: '1 Kings 21:23',
      fulfillment_text: 'When they went to bury her, they found nothing except her skull, feet and hands. Dogs had eaten her — fulfilling Elijah\'s word.',
      fulfillment_reference: '2 Kings 9:35–37',
      fulfillment_book_slug: '2-kings',
      fulfillment_chapter: 9,
      outcome: 'fulfilled',
    },
    {
      id: 'elijah-ahab-house',
      prophecy_text: 'I will cut off from Ahab every last male in Israel — slave or free.',
      prophecy_reference: '1 Kings 21:21',
      fulfillment_text: 'Jehu killed all who remained of Ahab\'s family in Jezreel, and all his chief men, close friends and priests — leaving him no survivor.',
      fulfillment_reference: '2 Kings 10:11',
      fulfillment_book_slug: '2-kings',
      fulfillment_chapter: 10,
      outcome: 'fulfilled',
    },
    {
      id: 'elijah-ahaziah',
      prophecy_text: 'You will not leave the bed you are lying on. You will certainly die.',
      prophecy_reference: '2 Kings 1:4',
      fulfillment_text: 'Ahaziah died, according to the word of the LORD that Elijah had spoken.',
      fulfillment_reference: '2 Kings 1:17',
      fulfillment_book_slug: '2-kings',
      fulfillment_chapter: 1,
      outcome: 'fulfilled',
    },
  ],

  elisha: [
    {
      id: 'elisha-naaman',
      prophecy_text: 'Go, wash yourself seven times in the Jordan, and your flesh will be restored and you will be cleansed.',
      prophecy_reference: '2 Kings 5:10',
      fulfillment_text: 'His flesh was restored and became clean like that of a young boy.',
      fulfillment_reference: '2 Kings 5:14',
      fulfillment_book_slug: '2-kings',
      fulfillment_chapter: 5,
      outcome: 'fulfilled',
    },
    {
      id: 'elisha-gehazi',
      prophecy_text: 'Naaman\'s leprosy will cling to you and to your descendants forever.',
      prophecy_reference: '2 Kings 5:27',
      fulfillment_text: 'Gehazi went from Elisha\'s presence and his skin was leprous — white as snow. Immediate judgment.',
      fulfillment_reference: '2 Kings 5:27',
      fulfillment_book_slug: '2-kings',
      fulfillment_chapter: 5,
      outcome: 'fulfilled',
    },
    {
      id: 'elisha-famine-end',
      prophecy_text: 'About this time tomorrow, a seah of the finest flour will sell for a shekel at the gate of Samaria.',
      prophecy_reference: '2 Kings 7:1',
      fulfillment_text: 'The Arameans fled, leaving food behind. The people plundered the camp. A seah of flour sold for a shekel, just as the LORD had said.',
      fulfillment_reference: '2 Kings 7:16',
      fulfillment_book_slug: '2-kings',
      fulfillment_chapter: 7,
      outcome: 'fulfilled',
    },
    {
      id: 'elisha-officer',
      prophecy_text: 'You will see it with your own eyes, but you will not eat any of it.',
      prophecy_reference: '2 Kings 7:2',
      fulfillment_text: 'The king put the doubting officer in charge of the gate, and the people trampled him in the gateway, and he died — just as the man of God had foretold.',
      fulfillment_reference: '2 Kings 7:17–20',
      fulfillment_book_slug: '2-kings',
      fulfillment_chapter: 7,
      outcome: 'fulfilled',
    },
    {
      id: 'elisha-hazael',
      prophecy_text: 'The LORD has shown me that you will become king over Aram.',
      prophecy_reference: '2 Kings 8:13',
      fulfillment_text: 'The next day Hazael took the bed covering, dipped it in water and spread it over the king\'s face so that he died. Then Hazael succeeded him as king.',
      fulfillment_reference: '2 Kings 8:15',
      fulfillment_book_slug: '2-kings',
      fulfillment_chapter: 8,
      outcome: 'fulfilled',
    },
    {
      id: 'elisha-joash',
      prophecy_text: 'The LORD\'s arrow of victory over Aram! You will completely destroy the Arameans at Aphek.',
      prophecy_reference: '2 Kings 13:17',
      fulfillment_text: 'Because Joash struck the ground only three times instead of five or six, he won only three battles against Aram rather than destroying them completely.',
      fulfillment_reference: '2 Kings 13:18–25',
      fulfillment_book_slug: '2-kings',
      fulfillment_chapter: 13,
      outcome: 'partial',
    },
  ],

  isaiah: [
    {
      id: 'isaiah-sennacherib',
      prophecy_text: 'He will not enter this city or shoot an arrow here. By the way that he came he will return; he will not enter this city.',
      prophecy_reference: '2 Kings 19:32–33',
      fulfillment_text: 'That night the angel of the LORD struck down 185,000 in the Assyrian camp. Sennacherib broke camp and withdrew. He returned to Nineveh and was killed by his sons.',
      fulfillment_reference: '2 Kings 19:35–37',
      fulfillment_book_slug: '2-kings',
      fulfillment_chapter: 19,
      outcome: 'fulfilled',
    },
    {
      id: 'isaiah-hezekiah-healed',
      prophecy_text: 'I have heard your prayer and seen your tears; I will heal you. On the third day you will go up to the temple.',
      prophecy_reference: '2 Kings 20:5',
      fulfillment_text: 'Isaiah said to prepare a poultice of figs and apply it to the boil. They did so and Hezekiah recovered.',
      fulfillment_reference: '2 Kings 20:7',
      fulfillment_book_slug: '2-kings',
      fulfillment_chapter: 20,
      outcome: 'fulfilled',
    },
    {
      id: 'isaiah-babylon-exile',
      prophecy_text: 'Everything in your palace and all that your predecessors stored up will be carried off to Babylon. Nothing will be left.',
      prophecy_reference: '2 Kings 20:17',
      fulfillment_text: 'All the treasures of the temple of the LORD and the royal palace were carried to Babylon. Nothing was left, as the LORD had declared.',
      fulfillment_reference: '2 Kings 25:13–17',
      fulfillment_book_slug: '2-kings',
      fulfillment_chapter: 25,
      outcome: 'fulfilled',
    },
  ],

  hosea: [
    {
      id: 'hosea-exile-assyria',
      prophecy_text: 'They will return to Egypt and will eat unclean food in Assyria.',
      prophecy_reference: 'Hosea 9:3',
      fulfillment_text: 'The king of Assyria deported Israel and settled them in Halah, in Gozan on the Habor River and in the towns of the Medes.',
      fulfillment_reference: '2 Kings 17:6',
      fulfillment_book_slug: '2-kings',
      fulfillment_chapter: 17,
      outcome: 'fulfilled',
    },
    {
      id: 'hosea-samaria-falls',
      prophecy_text: 'Samaria will bear her guilt, for she has rebelled against her God. They will fall by the sword.',
      prophecy_reference: 'Hosea 13:16',
      fulfillment_text: 'Shalmaneser besieged Samaria for three years. The city fell and Israel was carried into exile — because they had not obeyed the LORD their God.',
      fulfillment_reference: '2 Kings 17:5–6',
      fulfillment_book_slug: '2-kings',
      fulfillment_chapter: 17,
      outcome: 'fulfilled',
    },
  ],

  amos: [
    {
      id: 'amos-exile-beyond-damascus',
      prophecy_text: 'Therefore I will send you into exile beyond Damascus.',
      prophecy_reference: 'Amos 5:27',
      fulfillment_text: 'The king of Assyria deported Israel, settling them in Halah, Gozan on the Habor River and the towns of the Medes — far beyond Damascus.',
      fulfillment_reference: '2 Kings 17:6',
      fulfillment_book_slug: '2-kings',
      fulfillment_chapter: 17,
      outcome: 'fulfilled',
    },
    {
      id: 'amos-jeroboam-sword',
      prophecy_text: 'I will rise against the house of Jeroboam with the sword.',
      prophecy_reference: 'Amos 7:9',
      fulfillment_text: 'Shallum conspired against Zechariah son of Jeroboam, assassinated him publicly and ended the dynasty of Jehu as God had promised.',
      fulfillment_reference: '2 Kings 15:10',
      fulfillment_book_slug: '2-kings',
      fulfillment_chapter: 15,
      outcome: 'fulfilled',
    },
  ],

  micah: [
    {
      id: 'micah-samaria-heap',
      prophecy_text: 'I will make Samaria a heap of rubble, a place for planting vineyards.',
      prophecy_reference: 'Micah 1:6',
      fulfillment_text: 'After a three-year siege, Shalmaneser captured Samaria and deported its people to Assyria. The city was repopulated with foreigners.',
      fulfillment_reference: '2 Kings 17:5–6, 24',
      fulfillment_book_slug: '2-kings',
      fulfillment_chapter: 17,
      outcome: 'fulfilled',
    },
    {
      id: 'micah-jerusalem-rubble',
      prophecy_text: 'Zion will be plowed like a field, Jerusalem will become a heap of rubble.',
      prophecy_reference: 'Micah 3:12',
      fulfillment_text: 'The Babylonian army burned the temple of the LORD, the royal palace and all the houses of Jerusalem. Every important building was burned down.',
      fulfillment_reference: '2 Kings 25:9',
      fulfillment_book_slug: '2-kings',
      fulfillment_chapter: 25,
      outcome: 'fulfilled',
    },
  ],

  jonah: [
    {
      id: 'jonah-nineveh-forty-days',
      prophecy_text: 'Forty more days and Nineveh will be overthrown.',
      prophecy_reference: 'Jonah 3:4',
      fulfillment_text: 'Nineveh repented and was spared — but only temporarily. About 150 years later the city fell to Babylon and Media (612 BC), fulfilling the spirit of Jonah\'s warning and Nahum\'s prophecy in full.',
      fulfillment_reference: 'Jonah 3:10; Nahum 1–3; 612 BC',
      outcome: 'partial',
    },
  ],

  nahum: [
    {
      id: 'nahum-nineveh-flood',
      prophecy_text: 'With an overwhelming flood he will make an end of Nineveh. He will pursue his foes into the realm of darkness.',
      prophecy_reference: 'Nahum 1:8',
      fulfillment_text: 'Nineveh fell to the combined forces of Babylon and Media in 612 BC. Ancient sources record that flooding weakened the city\'s defences before the final assault. The city was never rebuilt.',
      fulfillment_reference: 'Historical event, 612 BC',
      outcome: 'historical',
    },
    {
      id: 'nahum-no-cure',
      prophecy_text: 'Nothing can heal you; your wound is fatal. Everyone who hears the news about you claps his hands at your fall.',
      prophecy_reference: 'Nahum 3:19',
      fulfillment_text: 'Nineveh\'s destruction was celebrated across the ancient Near East. The Assyrian empire — which had devastated Israel in 722 BC — ceased to exist. The city vanished under desert sands for centuries.',
      fulfillment_reference: 'Historical record',
      outcome: 'historical',
    },
  ],

  zephaniah: [
    {
      id: 'zephaniah-nineveh-desolate',
      prophecy_text: 'He will stretch out his hand against the north and destroy Assyria, leaving Nineveh utterly desolate and dry as the desert.',
      prophecy_reference: 'Zephaniah 2:13',
      fulfillment_text: 'Nineveh fell to Babylon and Media in 612 BC and was never rebuilt. For centuries it lay buried — a ruin covered by desert sands until rediscovered by archaeologists in the 19th century.',
      fulfillment_reference: 'Historical event, 612 BC',
      outcome: 'historical',
    },
    {
      id: 'zephaniah-josiah-deferred',
      prophecy_text: 'Seek the LORD… seek righteousness, seek humility; perhaps you will be sheltered on the day of the LORD\'s anger.',
      prophecy_reference: 'Zephaniah 2:3',
      fulfillment_text: 'Josiah enacted sweeping reforms and God promised he would die in peace before the coming disaster. Judgment on Judah was deferred an entire generation because of his faithfulness.',
      fulfillment_reference: '2 Kings 22:18–20',
      fulfillment_book_slug: '2-kings',
      fulfillment_chapter: 22,
      outcome: 'partial',
    },
  ],

  jeremiah: [
    {
      id: 'jeremiah-jehoiachin',
      prophecy_text: 'Even if you were a signet ring on my right hand, I would still pull you off and hand you over to those who seek your life.',
      prophecy_reference: 'Jeremiah 22:24–25',
      fulfillment_text: 'Jehoiachin surrendered to the king of Babylon. He, his mother, his court officials and the leading men of Judah were all taken to Babylon.',
      fulfillment_reference: '2 Kings 24:12–15',
      fulfillment_book_slug: '2-kings',
      fulfillment_chapter: 24,
      outcome: 'fulfilled',
    },
    {
      id: 'jeremiah-zedekiah',
      prophecy_text: 'You will not escape from his grasp but will surely be captured. You will see the king of Babylon with your own eyes.',
      prophecy_reference: 'Jeremiah 34:3',
      fulfillment_text: 'Zedekiah was captured, brought before Nebuchadnezzar at Riblah, his sons killed before his eyes, his own eyes put out, then taken in bronze shackles to Babylon.',
      fulfillment_reference: '2 Kings 25:6–7',
      fulfillment_book_slug: '2-kings',
      fulfillment_chapter: 25,
      outcome: 'fulfilled',
    },
    {
      id: 'jeremiah-jerusalem-burned',
      prophecy_text: 'I will hand this city over to the king of Babylon, and he will burn it down.',
      prophecy_reference: 'Jeremiah 32:3',
      fulfillment_text: 'A Babylonian commander set fire to the temple of the LORD, the royal palace and all the houses of Jerusalem. Every important building was burned down.',
      fulfillment_reference: '2 Kings 25:8–10',
      fulfillment_book_slug: '2-kings',
      fulfillment_chapter: 25,
      outcome: 'fulfilled',
    },
    {
      id: 'jeremiah-seventy-years',
      prophecy_text: 'This whole country will become a desolate wasteland, and these nations will serve the king of Babylon seventy years.',
      prophecy_reference: 'Jeremiah 25:11',
      fulfillment_text: 'The exile lasted approximately 70 years — from the first deportation (605 BC) to Cyrus\'s decree permitting the exiles to return (538 BC). Fulfilled beyond the scope of 2 Kings.',
      fulfillment_reference: 'Historical / Ezra 1:1–4',
      outcome: 'historical',
    },
  ],

};
