import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

const KINGS_NORTH = [
  { question: 'Who was the first king of Northern Israel?', answer: 'Jeroboam I (930–909 BC). He led the 10 tribes in revolt against Rehoboam and established the northern kingdom, setting up golden calves at Bethel and Dan.', hint: 'He revolted against Solomon\'s son' },
  { question: 'What sin is Jeroboam I most remembered for?', answer: 'The "sin of Jeroboam" — setting up two golden calves at Bethel and Dan and declaring "Here are your gods, Israel, who brought you up out of Egypt." This became the standard of northern apostasy.', hint: 'Golden calves at two cities' },
  { question: 'Which prophet announced judgment on Jeroboam\'s house?', answer: 'Ahijah of Shiloh — he tore his cloak into 12 pieces to symbolize the divided kingdom (1 Kings 11), and later announced the destruction of Jeroboam\'s entire dynasty (1 Kings 14).', hint: 'He tore a cloak in 12 pieces' },
  { question: 'How did Elah, son of Baasha, die?', answer: 'Assassinated by Zimri, one of his military commanders, while drunk at the house of his steward Arza (1 Kings 16:9–10). Zimri then killed the entire house of Baasha.', hint: 'Drunk when he was killed; Zimri' },
  { question: 'How long did Zimri reign as king of Israel?', answer: 'Seven days (1 Kings 16:15). When the army heard he had assassinated Elah, they made Omri king instead. Zimri burned the palace down on himself rather than surrender.', hint: 'The shortest reign in Israelite history' },
  { question: 'Who was Omri and what was his most significant act?', answer: 'Omri founded the Omride dynasty and built Samaria as the new capital of the northern kingdom, purchasing the hill of Samaria from Shemer for two talents of silver (1 Kings 16:24).', hint: 'Founded the capital city of the north' },
  { question: 'Who was Ahab\'s wife and where was she from?', answer: 'Jezebel, daughter of Ethbaal king of the Sidonians. Her marriage to Ahab brought Baal worship and the murder of Yahweh\'s prophets to Israel on an institutional level.', hint: 'Phoenician princess, Baal worshiper' },
  { question: 'What was the vineyard incident, and what did it cost Ahab?', answer: 'Ahab coveted Naboth\'s vineyard; Jezebel arranged false testimony and had Naboth stoned. Elijah declared Ahab\'s blood would be licked up where Naboth\'s was, and Jezebel would be eaten by dogs (1 Kings 21).', hint: 'Naboth\'s refusal led to his death' },
  { question: 'How did Ahab die?', answer: 'Wounded by a random arrow at the battle of Ramoth-Gilead (1 Kings 22:34). He propped himself up in his chariot until evening, then died. Dogs licked his blood when his chariot was washed — fulfilling Elijah\'s prophecy.', hint: 'An arrow, not a sword, killed him' },
  { question: 'Who was Jehu and how did he come to power?', answer: 'Jehu was a military commander anointed by one of Elisha\'s prophets (2 Kings 9:1–6). He killed Joram son of Ahab, Ahaziah of Judah, and Jezebel in a rapid coup, ending the Omride dynasty.', hint: 'Anointed by Elisha\'s messenger; drove his chariot furiously' },
  { question: 'What did Jehu do to the prophets of Baal?', answer: 'He assembled all Baal worshipers under pretense of a great sacrifice, then sent in 80 guards who killed them all. He demolished the temple of Baal and made it a latrine (2 Kings 10:18–27).', hint: 'He tricked them into gathering' },
  { question: 'How many generations did God promise Jehu\'s dynasty would last?', answer: 'Four generations (2 Kings 10:30): Jehoahaz, Jehoash, Jeroboam II, and Zechariah — the longest dynasty in Israel\'s northern history. Zechariah was assassinated after 6 months, ending the line.', hint: 'Longest dynasty in the north' },
  { question: 'Which northern king had the most prosperous reign?', answer: 'Jeroboam II (793–753 BC). He restored Israel\'s borders from the entrance of Hamath to the Sea of the Arabah (2 Kings 14:25), the greatest territorial extent since Solomon.', hint: 'Son of Jehoash; contemporary of Amos' },
  { question: 'Who was the last king of Northern Israel?', answer: 'Hoshea (732–722 BC). He assassinated Pekah to take the throne, then appealed to Egypt against Assyria — prompting Shalmaneser V to besiege Samaria for three years until it fell (2 Kings 17).', hint: 'The kingdom fell during his reign' },
  { question: 'What ended the northern kingdom of Israel?', answer: 'The Assyrian conquest under Shalmaneser V and Sargon II. Samaria fell in 722 BC after a 3-year siege. The population was deported and replaced with peoples from other parts of the Assyrian empire (2 Kings 17:6).', hint: 'Fell in 722 BC; deportation policy' },
  { question: 'What was Jeroboam I\'s "innovation" in religion?', answer: 'He changed the calendar (moving the fall festival from the 7th to the 8th month), appointed non-Levite priests for the high places, and himself burned incense — all unauthorized departures from Mosaic law (1 Kings 12:31–33).', hint: 'Calendar, priests, and personal sacrifice' },
  { question: 'What is the Deuteronomistic verdict formula for northern kings?', answer: '"He did evil in the eyes of the LORD and walked in the ways of Jeroboam son of Nebat, who caused Israel to sin." Every northern king receives some version of this — not one is rated as good.', hint: 'Zero good kings in the north' },
  { question: 'Who killed Zechariah son of Jeroboam II?', answer: 'Shallum son of Jabesh assassinated him in front of the people after only six months (2 Kings 15:10), ending the Jehu dynasty as God had promised it would end after 4 generations.', hint: 'The Jehu dynasty\'s last king' },
  { question: 'Which northern king paid tribute to Tiglath-Pileser III of Assyria?', answer: 'Menahem (745–738 BC) paid 1,000 talents of silver to Tiglath-Pileser, levying it from wealthy Israelites at 50 shekels each (2 Kings 15:19–20). This is confirmed by Assyrian inscriptions.', hint: 'Paid to avoid Assyrian invasion; 1,000 talents' },
]

const KINGS_SOUTH = [
  { question: 'What caused the division of the kingdom under Rehoboam?', answer: 'Rehoboam rejected the elders\' advice to lighten Solomon\'s tax burden and instead threatened to increase it. Ten tribes revolted under Jeroboam I; Rehoboam kept only Judah and Benjamin (1 Kings 12).', hint: 'Tax policy; "my little finger is thicker than my father\'s waist"' },
  { question: 'Which king of Judah was the first to be called "good"?', answer: 'Asa (911–870 BC). He removed the male shrine prostitutes, cleared out his father\'s idols, and even deposed his grandmother Maacah for making an Asherah pole (1 Kings 15:11–13).', hint: 'Deposed his own grandmother' },
  { question: 'Who was Jehoshaphat and what alliance did he make?', answer: 'Jehoshaphat was a good king of Judah (873–849 BC) who foolishly allied with Ahab through his son Jehoram\'s marriage to Ahab\'s daughter Athaliah — bringing Omride influence into Judah (1 Kings 22; 2 Kings 8).', hint: 'Good king who allied with Ahab' },
  { question: 'Who was Athaliah and how did she come to power?', answer: 'Daughter of Ahab and Jezebel (or granddaughter via Omri). When her son Ahaziah died, she killed all the royal heirs and seized the throne — the only woman to rule Judah (2 Kings 11:1–3). She reigned 6 years.', hint: 'Only queen regnant of Judah; killed her own grandchildren' },
  { question: 'How was Athaliah overthrown?', answer: 'Jehoiada the priest had hidden Joash (the infant son of Ahaziah) in the temple for six years. In the 7th year he crowned Joash king; the crowd killed Athaliah at the palace entrance (2 Kings 11:15–16).', hint: 'Priest hid the true heir for 6 years' },
  { question: 'What did Joash do with the temple?', answer: 'Joash repaired the temple using a chest for voluntary donations (2 Kings 12:9–12) — but only after Jehoiada the priest pressured him. After Jehoiada died, Joash allowed high places to continue.', hint: 'Collection box for temple repairs' },
  { question: 'What is Hezekiah known for above all other kings of Judah?', answer: '"He trusted in the LORD God of Israel. There was none like him among all the kings of Judah after him, nor among those before him" (2 Kings 18:5). He removed high places, smashed the bronze serpent, and stood firm against Sennacherib.', hint: 'Greatest trust in God; Assyrian crisis; removed high places' },
  { question: 'What happened when Sennacherib besieged Jerusalem?', answer: 'The angel of the LORD struck down 185,000 Assyrian soldiers in one night (2 Kings 19:35). Sennacherib withdrew and returned to Nineveh, where he was assassinated by his sons (2 Kings 19:37). Jerusalem was not captured.', hint: 'Angel killed 185,000 Assyrians overnight' },
  { question: 'What was Isaiah\'s prophecy about Hezekiah\'s illness?', answer: 'Isaiah told Hezekiah he would die (2 Kings 20:1). Hezekiah prayed; Isaiah returned with a new word: God would add 15 years to his life and the sundial shadow would go back 10 steps as a sign.', hint: 'Fifteen extra years; sundial sign' },
  { question: 'What mistake did Hezekiah make near the end of his life?', answer: 'He showed Babylonian envoys all his treasure — the silver, gold, spices, oil, and armory (2 Kings 20:13). Isaiah prophesied that Babylon would one day carry everything, including Hezekiah\'s sons, into exile.', hint: 'Showed his treasury to Babylonian envoys' },
  { question: 'Who was Manasseh and why was he the worst king of Judah?', answer: 'Son of Hezekiah, reigned 55 years (697–642 BC). He rebuilt the high places, erected altars to Baal in the temple courts, made his son pass through fire, and "shed innocent blood very much" — reversing all Hezekiah\'s reforms (2 Kings 21).', hint: 'Longest reign; undid Hezekiah\'s work; child sacrifice' },
  { question: 'What did God say about Manasseh\'s sin?', answer: '"I will wipe Jerusalem as one wipes a dish, wiping it and turning it upside down" (2 Kings 21:13). The exile is explicitly attributed to Manasseh\'s sins — not merely Judah\'s.', hint: '"Wiping a dish" — the exile is his fault' },
  { question: 'Who was Josiah and what triggered his reforms?', answer: 'Josiah (640–609 BC) began reforms at age 20 (2 Chron 34) but the great catalyst was the discovery of "the Book of the Law" during temple repairs (2 Kings 22:8). When he heard it read, he tore his robes and immediately sought God.', hint: 'Found the Book of the Law during temple repairs' },
  { question: 'What did the prophetess Huldah say about Josiah?', answer: 'Because Josiah humbled himself and wept at God\'s word, he would be gathered to his fathers in peace and would not see the disaster God would bring on Judah. He died before the Babylonian exile (2 Kings 22:18–20).', hint: 'He would die before the disaster; gathered in peace' },
  { question: 'What was the Passover Josiah celebrated?', answer: '"No such Passover had been kept since the days of the judges who judged Israel, or during all the days of the kings of Israel or of the kings of Judah" (2 Kings 23:22). It was the greatest Passover in 300 years.', hint: 'Greatest Passover since the judges' },
  { question: 'How did Josiah die?', answer: 'He went out to stop Pharaoh Neco\'s army at Megiddo and was struck by archers (2 Kings 23:29). He was brought back to Jerusalem and died. Huldah\'s prophecy was fulfilled — he died before the exile, but not peacefully as expected.', hint: 'Killed at Megiddo by Egyptian archers' },
  { question: 'Who were the last four kings of Judah?', answer: 'Jehoahaz (3 months, exiled to Egypt), Jehoiakim (11 years, died in Babylon\'s first siege), Jehoiachin (3 months, exiled to Babylon), and Zedekiah (11 years, blinded and exiled after Jerusalem fell in 586 BC).', hint: 'Jehoahaz → Jehoiakim → Jehoiachin → Zedekiah' },
  { question: 'What happened to Jerusalem in 586 BC?', answer: 'Nebuchadnezzar\'s army burned the temple, the palace, and all great houses. They broke down the city walls, killed most of the men, blinded Zedekiah after making him watch his sons killed, and deported the remaining population to Babylon (2 Kings 25).', hint: 'Temple burned; Zedekiah blinded; exile to Babylon' },
  { question: 'What hopeful note ends 2 Kings?', answer: 'Evil-Merodach king of Babylon released Jehoiachin from prison, gave him a seat of honor above other kings, and provided him a regular daily allowance for the rest of his life (2 Kings 25:27–30) — a flicker of Davidic hope.', hint: 'Jehoiachin released from prison in Babylon; daily allowance' },
  { question: 'Which king is praised for removing the bronze serpent Moses made?', answer: 'Hezekiah. By his time Israelites were burning incense to it (calling it Nehushtan — "the bronze thing"). Hezekiah smashed it as idolatry, though Moses had made it by divine command (2 Kings 18:4; Numbers 21:8–9).', hint: 'Smashed the serpent Moses made; called it Nehushtan' },
]

const PLACES = [
  { question: 'What is the modern location of ancient Samaria?', answer: 'The ruins of Samaria sit on a hill near modern Sebastia (Arabic: Sebastiyya) in the West Bank, about 10 km northwest of Nablus (ancient Shechem). The Herodian city was renamed Sebaste.', hint: 'Hill near Nablus, West Bank' },
  { question: 'Where was the temple of Baal at Carmel?', answer: 'Mount Carmel is a promontory jutting into the Mediterranean in northern Israel. The traditional site of Elijah\'s contest with the Baal prophets is at el-Muhraqa ("the burning place"), near the ridge overlooking the Jezreel Valley.', hint: 'Promontory above the Jezreel Valley; the burning place' },
  { question: 'What was Jezreel and why was it significant?', answer: 'Jezreel was the secondary royal city of the northern kingdom, where Ahab had his winter palace. The Jezreel Valley (the great plain of Megiddo) dominated the main trade route between Egypt and Mesopotamia.', hint: 'Ahab\'s second palace; the great valley' },
  { question: 'What is Zarephath and where is it?', answer: 'Zarephath (modern Sarafand, Lebanon) was a Phoenician city between Sidon and Tyre, in Jezebel\'s home territory. God sent Elijah there during the drought — to a widow in the heart of Baal country.', hint: 'Phoenician city in Jezebel\'s homeland; modern Lebanon' },
  { question: 'What was Beersheba and its religious significance?', answer: 'Beersheba was the southernmost city of Judah — "from Dan to Beersheba" marked the full extent of Israel. It had ancient sacred associations with Abraham and Isaac, and was a pilgrimage site that Amos condemned.', hint: '"From Dan to Beersheba"; the southernmost point; Abraham\'s wells' },
  { question: 'Where is Horeb and why does Elijah go there?', answer: 'Horeb is another name for Sinai — the mountain of God where Moses received the law and experienced the theophany of the burning bush. Elijah flees there after Carmel, journeying 40 days to encounter God at the same mountain as Moses (1 Kings 19).', hint: 'Same as Sinai; the mountain of God; 40-day journey' },
  { question: 'What happened at Ramoth-Gilead?', answer: 'Ramoth-Gilead was a disputed city on the Transjordanian plateau. Ahab died there in battle against Aram (1 Kings 22). Later, Jehu was anointed there and launched his coup against the Omride dynasty (2 Kings 9).', hint: 'Ahab died here; Jehu anointed here' },
  { question: 'What is Dothan and why is it in the Elisha narratives?', answer: 'Dothan was a city in the Jezreel Valley region. It was at Dothan that the Aramean army surrounded Elisha, and his servant\'s eyes were opened to see the heavenly chariots (2 Kings 6:13–17).', hint: 'Elisha surrounded by Arameans; chariots of fire seen here' },
  { question: 'What was the Jordan River\'s symbolic significance in 1–2 Kings?', answer: 'The Jordan was the threshold of the Promised Land. Elijah parted it before his translation (2 Kings 2:8); Elisha parted it to begin his ministry (2:14); Naaman was healed by dipping in it 7 times (5:14). It echoes Israel\'s original crossing under Joshua.', hint: 'Three great crossings/events; echoes Joshua' },
  { question: 'What was Megiddo and why was it strategically important?', answer: 'Megiddo controlled the Jezreel pass — the main route through the Carmel ridge between the coastal plain and the northern valleys. It was one of Solomon\'s chariot cities (1 Kings 9:15) and where Josiah died fighting Pharaoh Neco (2 Kings 23:29).', hint: 'Chariot city; key pass; where Josiah died' },
  { question: 'Where was the "high place" that Solomon built and why was it significant?', answer: 'Solomon built a high place for Chemosh (Moab\'s god) and Molech on "the hill east of Jerusalem" — the Mount of Olives (1 Kings 11:7). Josiah destroyed it during his reforms 300 years later (2 Kings 23:13).', hint: 'Mount of Olives; lasted 300 years until Josiah' },
  { question: 'What was Dan and its religious role in the northern kingdom?', answer: 'Dan was the northernmost city of Israel ("from Dan to Beersheba"). Jeroboam I placed one of his two golden calves there (1 Kings 12:29), making it a rival worship site to Jerusalem for 200 years.', hint: 'Northernmost city; Jeroboam\'s golden calf site' },
  { question: 'Where was Bethel and what happened there?', answer: 'Bethel was a city on the border of Benjamin and Ephraim, 18 km north of Jerusalem. It had deep patriarchal associations (Jacob\'s ladder, Genesis 28). Jeroboam placed his other golden calf there, and a man of God from Judah prophesied its destruction — fulfilled by Josiah 300 years later.', hint: 'Jacob\'s ladder; Jeroboam\'s golden calf; prophesied destruction' },
  { question: 'What was Shechem\'s role in the divided kingdom narrative?', answer: 'Shechem was the site of the assembly where Rehoboam\'s refusal to lower taxes caused the split (1 Kings 12:1). Jeroboam was made king there. It was in the Joseph tribal territory, central to the northern kingdom\'s identity.', hint: 'Where the kingdom split; Jeroboam crowned' },
  { question: 'What was the Siloam Tunnel and who built it?', answer: 'Hezekiah\'s engineers cut a 533-meter tunnel through solid rock to channel water from the Gihon Spring into the Pool of Siloam, bringing the city\'s water supply inside the walls before Sennacherib\'s siege (2 Kings 20:20). The Siloam Inscription describes the moment the two teams met.', hint: 'Hezekiah; water security before the Assyrian siege; 533m tunnel' },
  { question: 'Where was Nineveh and what is its role in Kings?', answer: 'Nineveh was the capital of the Assyrian Empire on the Tigris River (modern Mosul, Iraq). Sennacherib retreated there after his failed siege of Jerusalem and was murdered by his sons while worshiping in the temple of Nisroch (2 Kings 19:36–37).', hint: 'Assyrian capital; Sennacherib murdered here' },
  { question: 'What was the Valley of Ben Hinnom?', answer: 'A valley south of Jerusalem (Gehenna) where some kings made their children "pass through fire" — child sacrifice to Molech (2 Kings 23:10). Josiah desecrated it. It became a symbol of judgment and later in the NT a metaphor for hell.', hint: 'Where children were sacrificed; later became Gehenna' },
  { question: 'Where was Tirzah and why does it appear in Kings?', answer: 'Tirzah was the capital of the northern kingdom before Omri built Samaria (c. 930–880 BC). It was known for its beauty (Song of Songs 6:4). Zimri burned himself to death there (1 Kings 16:18).', hint: 'First capital of the north; where Zimri burned the palace' },
  { question: 'What was Lachish and why is it archaeologically important?', answer: 'Lachish was Judah\'s second most important city after Jerusalem. Sennacherib captured it in 701 BC during his campaign; the Lachish Reliefs in the British Museum show his assault. Remains confirm the Assyrian siege and Judean destruction layers.', hint: 'Second city of Judah; Sennacherib\'s reliefs in British Museum' },
  { question: 'Where was Gilgal and what is its significance?', answer: 'Gilgal was Israel\'s first camp after crossing the Jordan under Joshua — where they were circumcised and celebrated the first Passover in Canaan. In 2 Kings 2, it\'s where Elijah and Elisha\'s journey to Elijah\'s translation begins.', hint: 'Israel\'s first Canaan camp; Elijah-Elisha journey starts here' },
  { question: 'What was Jericho\'s role in the Elisha narratives?', answer: 'After Elijah\'s translation, Elisha returned to Jericho and the "company of prophets" there saw what happened. He then healed Jericho\'s spring by throwing salt in it (2 Kings 2:19–21). The cursed city was being renewed.', hint: 'Prophets guild headquarters; Elisha healed its spring' },
  { question: 'Where was Jezreel and what prophecy was fulfilled there?', answer: 'Jezreel was the site of Naboth\'s vineyard, Ahab\'s crime, and Elijah\'s curse. Jehu shot Joram on Naboth\'s field (2 Kings 9:25–26) — fulfilling Elijah\'s word. Jezebel was thrown from a window there and eaten by dogs (9:30–37).', hint: 'Naboth\'s field; Joram killed; Jezebel eaten by dogs' },
  { question: 'What was the "house of the forest of Lebanon" in Jerusalem?', answer: 'A large building Solomon constructed, mentioned in 1 Kings 7:2, likely named for its rows of cedar columns. It served as an armory (1 Kings 10:17; Isaiah 22:8). It stood near the temple complex but served secular/military purposes.', hint: 'Solomon\'s armory; cedar columns like a forest' },
  { question: 'What was Abel-Meholah?', answer: 'Abel-Meholah was a town in the Jordan Valley, the hometown of Elisha. Elijah passed by it and threw his mantle over Elisha, who was plowing there (1 Kings 19:16, 19).', hint: 'Elisha\'s hometown; where the mantle was thrown' },
  { question: 'Where was Ekron and why does it appear in 2 Kings 1?', answer: 'Ekron was the northernmost Philistine city. King Ahaziah, after falling through his lattice, sent messengers to inquire of Baal-Zebub ("Lord of the Flies"), the god of Ekron. Elijah intercepted them with God\'s judgment (2 Kings 1:1–4).', hint: 'Philistine city; Baal-Zebub; Ahaziah\'s messengers intercepted' },
  { question: 'What was the Pool of Samaria?', answer: 'After Ahab died at Ramoth-Gilead, his blood-stained chariot was washed at the pool of Samaria — and prostitutes bathed there, fulfilling Elijah\'s prophecy that dogs would lick Ahab\'s blood (1 Kings 22:38).', hint: 'Ahab\'s blood; prophecy fulfilled at the pool' },
  { question: 'What was Ophel in Jerusalem?', answer: 'Ophel was the southern spur of the Temple Mount, just south of the temple platform. It was a fortified area in Jerusalem, mentioned in relation to building projects. Archaeological digs there have revealed significant Iron Age remains.', hint: 'Southern spur of the temple; fortified area' },
  { question: 'Where was Hamath and why is it a boundary marker?', answer: 'Hamath was a major Aramean city-state on the Orontes River in modern Syria. "From the entrance of Hamath to the Sea of Arabah" (2 Kings 14:25) marked the ideal northern and southern borders of Israel under Jeroboam II — echoing the Solomonic ideal (1 Kings 8:65).', hint: 'Northernmost ideal border marker; Jeroboam II restored it' },
  { question: 'What was Nebo in 2 Kings?', answer: 'Nebo appears in the Mesha Stele context — Mesha king of Moab conquered Nebo from Israel, taking its sacred vessels. The town was in the Transjordan, associated with Mount Nebo where Moses died (Deuteronomy 34).', hint: 'Mesha Stele; where Moses died; Transjordan' },
  { question: 'What was the location and significance of the Temple?', answer: 'Solomon built the temple on Mount Moriah (the threshing floor of Araunah, 2 Samuel 24:18-25), the northern hill of Jerusalem. The ark of the covenant was placed in the inner sanctuary (the Holy of Holies). Its construction and later destruction bookend the entire monarchical period.', hint: 'Mount Moriah; David\'s threshing floor; Ark of the Covenant' },
  { question: 'Where was Assyria\'s capital Asshur?', answer: 'Asshur (modern Qal\'at Sherqat) was the ancient religious capital of Assyria on the Tigris River. By the time of 1–2 Kings, the political capitals had shifted to Nineveh and Calah, but Asshur remained the sacred heart of Assyrian religion.', hint: 'Ancient religious capital on the Tigris; not Nineveh' },
]

const PEOPLE = [
  { question: 'Who was Elijah the Tishbite?', answer: 'Elijah was from Tishbe in Gilead (east of the Jordan). He appears without introduction in 1 Kings 17:1, announcing a drought to Ahab. He is the premier prophet of the northern kingdom, facing down Baal worship at its height.', hint: 'From Gilead; no birth narrative; sudden appearance' },
  { question: 'What is the "double portion" Elisha asks for?', answer: 'Elisha asks for "a double portion of your spirit" (2 Kings 2:9) — the firstborn\'s inheritance share. He is claiming to be Elijah\'s prophetic heir. Elijah says it will be granted if Elisha sees him taken up — and he does.', hint: 'Firstborn\'s inheritance; if he sees Elijah taken' },
  { question: 'Who was Naaman and what was his condition?', answer: 'Naaman was the commander of the Aramean army — a great man in the sight of his master, mighty in valor. He had leprosy. An Israelite slave girl told his wife to send him to Elisha (2 Kings 5).', hint: 'Aramean general with leprosy; slave girl\'s advice' },
  { question: 'Who was Gehazi and what was his downfall?', answer: 'Gehazi was Elisha\'s servant. After Naaman was healed, Gehazi ran after him and took silver and garments by deception, claiming Elisha needed them for two prophets. Elisha knew, and Naaman\'s leprosy transferred to Gehazi permanently (2 Kings 5:27).', hint: 'Elisha\'s servant; greed; inherited Naaman\'s leprosy' },
  { question: 'Who was the Shunammite woman?', answer: 'An unnamed wealthy woman who recognized Elisha as a holy man of God. She built a rooftop room for him. Elisha prophesied that she would have a son (she was childless). When that son died, Elisha raised him (2 Kings 4:8–37).', hint: 'Built Elisha a room; barren; her son was raised from death' },
  { question: 'Who was Micaiah son of Imlah?', answer: 'A prophet who told Ahab the truth about the Ramoth-Gilead battle when 400 false prophets predicted victory. Ahab hated him because he "never prophesies anything good about me." He predicted Ahab\'s death and was imprisoned (1 Kings 22).', hint: 'Told Ahab the truth; imprisoned; 400 prophets vs 1' },
  { question: 'Who was Jehoiada?', answer: 'Jehoiada was the chief priest who hid infant Joash in the temple for six years while Athaliah ruled. He orchestrated the coup, crowned Joash, and executed Athaliah. He later guided Joash\'s reforms (2 Kings 11–12).', hint: 'Priest who hid Joash; executed Athaliah' },
  { question: 'Who was Hazael and how did he come to power?', answer: 'Hazael was an official of Aram-Damascus. Elisha prophesied he would become king and bring terrible suffering to Israel. When sent by the sick king Ben-hadad to ask Elisha if he would recover, Hazael returned and smothered the king with a wet cloth (2 Kings 8:15).', hint: 'Murdered Ben-hadad with a wet cloth; anointed by Elisha\'s word' },
  { question: 'Who was Isaiah son of Amoz?', answer: 'Isaiah was the great Jerusalem prophet active during Hezekiah\'s reign. In 2 Kings 19–20, he delivers three oracles: Sennacherib will withdraw; Hezekiah will live 15 more years; and Babylon will eventually take everything. His book is the most quoted in the NT.', hint: 'Jerusalem prophet; active under Hezekiah; 3 oracles in 2 Kings' },
  { question: 'Who was Huldah the prophetess?', answer: 'Huldah was a prophetess in Jerusalem, wife of Shallum the keeper of the wardrobe. When Josiah discovered the Book of the Law, he sent a delegation to her (not to Jeremiah or Zephaniah). She confirmed the scroll\'s authority and its judgment, with mercy for Josiah (2 Kings 22:14–20).', hint: 'Consulted over Jeremiah; authenticated the Book of the Law; wife of Shallum' },
  { question: 'Who was Ben-hadad and what was his relationship to Israel?', answer: 'Ben-hadad is the name/title of multiple Aramean kings of Damascus. Ahab defeated Ben-hadad I and let him go in exchange for trade concessions (1 Kings 20). Ben-hadad II besieged Samaria (2 Kings 6–7). The relationship oscillated between war and treaty.', hint: 'Aramean kings of Damascus; Ahab let him go; besieged Samaria' },
  { question: 'Who was Tiglath-Pileser III and what was his significance for Israel?', answer: 'Tiglath-Pileser III (also called Pul in 2 Kings 15:19) was the Assyrian king who received tribute from Menahem of Israel, conquered Galilee and Transjordan under Pekah, and installed Hoshea as a vassal king. He initiated the final slide toward Israel\'s destruction.', hint: 'Also called Pul; accepted Menahem\'s tribute; conquered the north' },
  { question: 'Who was the widow of Zarephath?', answer: 'An unnamed Phoenician widow in Sidon territory who had only enough flour and oil for one last meal for herself and her son. Elijah asked for it first. She obeyed — and her flour and oil never ran out. Her son died later and Elijah raised him (1 Kings 17).', hint: 'One last meal; Sidon; her son raised by Elijah' },
  { question: 'Who was the man of God from Judah who prophesied at Bethel?', answer: 'An unnamed prophet from Judah who pronounced judgment on Jeroboam\'s altar at Bethel — naming the future king Josiah by name, 300 years before he was born (1 Kings 13:2). He died the same day after disobeying God\'s instructions by eating with an old prophet.', hint: 'Prophesied Josiah by name 300 years early; died for disobeying' },
  { question: 'Who was Sennacherib and what was his campaign against Judah?', answer: 'Sennacherib was king of Assyria (705–681 BC) who invaded Judah in 701 BC, captured 46 fortified cities, and besieged Jerusalem. The Assyrian Annals and the Taylor Prism record this campaign. He failed to take Jerusalem — 185,000 soldiers struck dead — and withdrew (2 Kings 18–19).', hint: 'Taylor Prism; 46 cities; 185,000 struck dead; withdrew' },
  { question: 'Who was Nebuchadnezzar and what did he do to Jerusalem?', answer: 'Nebuchadnezzar II was king of Babylon who besieged Jerusalem three times: 605 BC (Daniel taken), 597 BC (Jehoiachin exiled; 10,000 deported), and 586 BC (temple burned, city destroyed, Zedekiah blinded). He ended the Davidic monarchy\'s political existence.', hint: 'Three sieges: 605, 597, 586 BC; burned the temple' },
  { question: 'Who was Gedaliah?', answer: 'Gedaliah son of Ahikam was appointed governor of Judah by Nebuchadnezzar after the fall of Jerusalem (2 Kings 25:22). He urged the remaining people to submit to Babylon. He was assassinated by Ishmael son of Netaniah — a Davidic prince — leaving the remnant to flee to Egypt.', hint: 'Babylonian-appointed governor; assassinated; remnant fled to Egypt' },
  { question: 'Who was Elisha\'s mentor and predecessor?', answer: 'Elijah the Tishbite. Elisha was called when Elijah threw his mantle over him at Abel-Meholah (1 Kings 19:19). Elisha served him as his attendant (1 Kings 19:21) until Elijah\'s translation in the whirlwind (2 Kings 2).', hint: 'Called at Abel-Meholah; served him for years' },
  { question: 'Who was Mesha king of Moab?', answer: 'Mesha was a Moabite king who paid tribute to Israel but revolted after Ahab died (2 Kings 3:4–5). Jehoram, Jehoshaphat, and Edom marched against him. The Mesha Stele (Moabite Stone) — found in 1868 — is Mesha\'s own account and confirms biblical names like Omri and Israel.', hint: 'Revolted; his stele confirms Omri; sheep tribute' },
  { question: 'Who was the "company of prophets" (sons of the prophets)?', answer: 'A guild or school of prophets associated with Elijah and especially Elisha. They lived in communities at Jericho, Bethel, and Gilgal. They witnessed Elijah\'s translation (2 Kings 2:7), and Elisha performed multiple miracles among them (bad stew, floating axe head, etc.).', hint: 'Prophetic guild; lived at Jericho and Bethel; witnessed translation' },
]

const THEMES = [
  { question: 'What is the "Deuteronomistic" thesis of 1–2 Kings?', answer: 'Obedience to the Mosaic covenant brings blessing; disobedience brings covenant curse, culminating in exile. The entire narrative is structured as a long explanation of why Israel and Judah ended up in captivity — their leaders repeatedly broke the covenant God made at Sinai.', hint: 'Covenant → blessing or curse; exile is the verdict' },
  { question: 'What are the "high places" and why do they matter?', answer: 'High places (bamot) were hilltop or elevated shrines, often with altars, standing stones, and Asherah poles. God commanded worship centralized in Jerusalem. A king\'s failure to remove high places — even a "good" king — is consistently noted as a moral failure throughout Kings.', hint: 'Unauthorized hilltop worship sites; centralization issue' },
  { question: 'What is the role of the prophetic word in Kings?', answer: 'The prophetic word always comes to pass — often centuries later. "According to the word of the LORD which he spoke" is the narrator\'s refrain. This is both theological (God controls history) and literary (the narrative is structured around prophetic fulfillments).', hint: '"According to the word of the LORD" — prophecy always fulfilled' },
  { question: 'What is "the sin of Jeroboam" as a literary device in Kings?', answer: 'Every northern king is evaluated against the benchmark of Jeroboam I — he "caused Israel to sin" by the golden calves, unauthorized priests, and calendar changes. Not one northern king breaks this pattern. It functions as a typological measure of apostasy.', hint: 'Benchmark for every northern king; all fail the same way' },
  { question: 'What is the Davidic covenant\'s role in Kings?', answer: 'God promised David an eternal dynasty. Throughout Kings, God\'s patience with Judah\'s evil kings is often explicitly attributed to "for the sake of David my servant" or "for the sake of Jerusalem." The hope at the end (Jehoiachin released) keeps this promise alive.', hint: '"For the sake of David"; why Judah survives longer than Israel' },
  { question: 'What is the temple\'s symbolic function in Kings?', answer: 'The temple is where God\'s name dwells (1 Kings 8:29) — the earthly throne room of Yahweh. Its construction marks the apex of the Solomonic golden age. Its desecration (Ahaz, Manasseh) maps apostasy. Its destruction in 586 BC is the ultimate covenant catastrophe.', hint: 'God\'s name dwells there; construction = apex; destruction = catastrophe' },
  { question: 'How does exile function theologically in Kings?', answer: 'Exile is the ultimate Deuteronomic covenant curse (Leviticus 26:33; Deuteronomy 28:64). The narrator presents it not as Assyrian or Babylonian power overwhelming God, but as God using foreign empires as the instrument of covenant enforcement against his own people.', hint: 'Covenant curse (Deut 28); God using empires as instruments' },
  { question: 'What is the "remnant" theme in 1–2 Kings?', answer: 'Even in the worst apostasy, God preserves a remnant of faithful Israelites. Elijah thinks he is alone — God says 7,000 in Israel have not bowed to Baal (1 Kings 19:18). Josiah\'s faithful reform shows the remnant can revive. Jehoiachin\'s release at the end suggests hope for a remnant.', hint: '7,000 who have not bowed to Baal; Josiah; Jehoiachin' },
  { question: 'What does "walking in the ways of David" mean in Kings?', answer: 'It is the highest praise a king can receive — meaning he centralized worship in Jerusalem, removed high places, kept the Mosaic law, and remained loyal to Yahweh alone. Hezekiah and Josiah are the two kings who receive this full commendation.', hint: 'Highest praise; centralize worship; remove high places; loyal to Yahweh' },
  { question: 'How does Kings handle the question "why did this happen to Israel?"', answer: '2 Kings 17:7–23 provides the theological explanation for Israel\'s fall: they feared other gods, followed the customs of the nations, built high places, set up pillars and Asherah poles, worshiped all the host of heaven, served Baal — rejecting every warning God sent through every prophet.', hint: '2 Kings 17 is the theological autopsy of the northern kingdom' },
]

type FlashcardRow = {
  deck: string;
  question: string;
  answer: string;
  hint?: string;
};

async function main() {
  console.log('Seeding flashcards...')

  await supabase.from('flashcards').delete().neq('id', '00000000-0000-0000-0000-000000000000')

  const allCards: FlashcardRow[] = [
    ...KINGS_NORTH.map(c => ({ deck: 'kings-north', ...c })),
    ...KINGS_SOUTH.map(c => ({ deck: 'kings-south', ...c })),
    ...PLACES.map(c => ({ deck: 'places', ...c })),
    ...PEOPLE.map(c => ({ deck: 'people', ...c })),
    ...THEMES.map(c => ({ deck: 'themes', ...c })),
  ]

  const { error } = await supabase.from('flashcards').insert(allCards)
  if (error) {
    console.error('ERROR:', error.message)
    process.exit(1)
  }

  console.log(`Inserted ${allCards.length} flashcards across 5 decks.`)
  console.log('Done.')
}

main().catch(console.error)
